### ISSUE TITLE
modWebLink ignores schema for urls

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#10029]
wshawn created Redmine issue ID 10029

As discussed in this thread: [[http://forums.modx.com/thread/85820/using-wayfinder-with-absolut-addresses-for-weblinks?page=2#dis-post-473409]]

modWeblink->process() only sends a redirect and does not reference schema whatsoever.

<pre>
$this->xpdo->sendRedirect($this->_output, array('responseCode' => $this->getProperty('responseCode', 'core', 'HTTP/1.1 301 Moved Permanently')));
</pre>

There is no makeUrl structure in place as exists in the modx class.

Packages such as Wayfinder are affected by this, and situations such as an ssl link could prove problematic as the link could easily switch to a non ssl mode.

**Comment by Alroniks** [comment]
Should be closed also as parent issue was closed. See discussion in https://github.com/modxcms/revolution/issues/10248
#modxbughunt

**Comment by OptimusCrime** [comment]
@modxbot close
