### ISSUE TITLE
modx "Array to string conversion" error in @SELECT TV

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10032]
bobray created Redmine issue ID 10032

I'm seeing this error in 2.2.8 in both the front end (with NewsPublisher) and the Manager with @SELECT TVs set to Listbox (single-select) when E_NOTICE errors are on.

Input Option Values: @SELECT templatename,id FROM modx_site_templates WHERE category=0
Default: (some Template ID)

Output Options: Default

**Comment by Alroniks** [comment]
Not reproducible in the 2.x branch. So close. #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Alroniks
