### ISSUE TITLE
modElementPropertySet->getOne('Element') succeeds with invalid value

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10061]
bobray created Redmine issue ID 10061

With a modElementProperty set with these fields:

<pre>
element:           999   // invalid
element_type:   'modSnippet'
property_set:    15  // valid
</pre>

Calling getOne('Element') on the modElementPropertySet object  returns the first snippet in the table even though 999 is an invalid value.

It should return null as most (all?) of the other intersect objects do with an invalid value.

**Comment by JoshuaLuckers** [comment]
@BobRay Can you provide a sample set for this issue? I want to write a testcase for this issue and solve the issue later on.

**Comment by BobRay** [comment]
I'm guessing here (I filed this 5 year ago), but this should do it:

Create a modElementPropertySet record in the modx_element_property_sets table with the fields above (make sure the property_set is the ID of an actual property set and that there is no other record with both the same element_type, and the same property_set value).

Then, do this:
```
$intersects = $modx->getCollection('modElementPropertySet');

foreach ($intersects as $intersect) {

    if ($intersect->get('property_set') == 999) {
        echo '<br>Element ID: ' . $intersect->get('element');
        echo '<br>Type: ' . $intersect->get('element_class');
        $propSet = $intersect->getOne('PropertySet');
        if ($propSet === null) {
            echo '<b>OK';
        } else {
            echo '<br>ERROR: Retrieved element ID: ' . $propSet->get('element');
        }
    }
}

```

**Comment by BobRay** [comment]
I just tested this, and the problem seems to be solved, so I'm not sure it's worth a unit test.

I did find another curious anomaly in the process. 

```
$fields = array(
    'property_set' => 5419, // valid property set ID
    'element_class' => 'modSnippet',
);
$intersect = $modx->getObject('modElementPropertySet', $fields);
```

$intersect is NULL. It seems that the intersect object should be found with that search, but maybe I'm missing something.

**Comment by JoshuaLuckers** [comment]
Thanks for coming back to this. 

> $intersect is NULL. It seems that the intersect object should be found with that search, but maybe I'm missing something.

That's why a Unit Test would be useful!

**Comment by alroniks** [comment]
> $intersect is NULL. It seems that the intersect object should be found with that search, but maybe I'm missing something.

Tested on 2.8.1 and it returns entry. So, I am closing it. Feel free to reopen.
