### ISSUE TITLE
$site_id in config.inc.php changes with update

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#10150]
gadgetto created Redmine issue ID 10150

Just updated from 2.2.8-pl to 2.2.9-pl-sdk in our dev environment and now the $site_id value in config.inc.php has changed (it now also has a "modx" prefix to the numeric value which previously wasn't there).

Is this intended to be changed on every update or only with the current one? Or is the $site_id only changed with the special sdk release?

I'm using the $site_id for security purposes during a cron call of a script and if this value changes on every update, I can't use it as we then would have to reconfigure the cron param ever time an update is provided.

Could this be a bug?

**Comment by pbowyer** [comment]
It is designed to be regenerated every time. I don't know why this design decision was made, but I doubt it'll change.

https://github.com/modxcms/revolution/blob/2.x/setup/includes/runner/modinstallrunner.class.php#L169

Closing ticket #modxbughunt
