### ISSUE TITLE
Wrong link to the doc in manager

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#10187]
goldsky created Redmine issue ID 10187

I have no idea with other links inside the manager, but this is what I found:

After the first installation, then a Welcome message pops up.
It has 
----------------------------------------------------------------

h1.See Also

*Successful Installation, Now What do I do?*
Tag Syntax
Designer's Guide
Developer's Guide
*Troubleshooting Installation*

----------------------------------------------------------------

The bolded links are referring to a wrong place, now.

**Comment by adamwintle** [comment]
@OptimusCrime @pixelchutes I think all of this has been cleared up now, do you guys think its okay to close this issue?

**Comment by OptimusCrime** [comment]
I forgot about this. As far as I can tell the links are OK now.

Feel free to reopen or comment if there is anything I have overlooked.

@modxbot close
