### ISSUE TITLE
Support markdown in package manager readme files

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#10201]
exside created Redmine issue ID 10201

As most projects are hosted on github it would be very convenient if we could just copy and paste the content of the readme.md file to the core/components/packagename/docs/readme.txt file and have it displayed as nicely as on github. This would save time for many of us I think =).

I suck at extjs but maybe this would be helpful: http://www.sencha.com/forum/showthread.php?254825-ExtJS-and-Markdown

**Comment by alroniks** [comment]
It should be easy to implement it in 3.0 using any markdown library from packagist via composer.

**Comment by alroniks** [comment]
Closing as PR is merged to 3.x
