### ISSUE TITLE
static resource set cached causes cache probs

### ISSUE THREAD

**Issue by manu37** [modxcms/revolution#10209]
manu37 created Redmine issue ID 10209

I know it's overkill, but I just noticed this:
When you set a resource as static and cached, you get this in the error.log:
[2013-09-16 13:01:51](ERROR @ /index.php) Could not retrieve data to cache for resource 640

**Comment by pixelive** [comment]
Cannot reproduce this issue.

#modxbughunt

**Comment by rtripault** [comment]
Let's close then.

Feel free to comment/reopen if needed.
Thanks
