### ISSUE TITLE
phpThumb FunctionIsDisabled not generic enough

### ISSUE THREAD

**Issue by franzlst** [modxcms/revolution#10217]
franzlst created Redmine issue ID 10217

After moving to a new hoster with an existing MODX page, the error log was full of this message:

".../core/model/phpthumb/phpthumb.functions.php : 474) PHP warning: shell_exec() has been disabled for security reasons"

Thus I had a closer look at this file and tried to debug the error message. Then I found the bug:

The function "FunctionIsDisabled" of the "phpthumb_functions" class uses ini_get('disable_functions') and get_cfg_var('disable_functions') to detect, which functions are disabled. The result of these to function is splitted using explode(',', ...)

The problem is now, that not all servers separate the function using a comma ',', but some, at least mine, just separate using a space ' '. Therefore the function must be rewritten to cope with both cases.

Suggestion:
<pre>
$dl = @ini_get('disable_functions');
$dg = @get_cfg_var('disable_functions');

$disable_functions_local = preg_split('/,\s*/', $dl);
$disable_functions_global = preg_split('/,\s*/', $dg);
</pre>

**Comment by adamwintle** [comment]
This looks like it was originally a server issue and/or a phpThumb issue and not actually a Core MODX bug. 

@modxbot close
