### ISSUE TITLE
Alias auto-generate issue for some characters

### ISSUE THREAD

**Issue by e-kinst** [modxcms/revolution#10238]
e-kinst created Redmine issue ID 10238
1. "This field is required" alert appears when I save resource with Title containing Russian letters:
2. ? (uppercase) or 
3. ? (lowercase).

?lert disappears when I typed in alias field manually but alias saved as empty.
1. Resource is saved with empty alias BUT non-empty modx_site_content.uri database field when Title contains Russian letter ? (uppercase).

FURL parameters - at the screenshot attached.

I tried to locate the bug by myself but was not able to print anything on screen or in log. Sorry...

**Comment by Alroniks** [comment]
Checked on the latest dev, works fine with this lettes. Let's close it #modxbughunt

**Comment by rtripault** [comment]
So closing...

Feel free to comment/reopen if needed.
Thanks
