### ISSUE TITLE
Syntax errors in cache files

### ISSUE THREAD

**Issue by maclonghorn** [modxcms/revolution#10255]
maclonghorn created Redmine issue ID 10255

I just upgraded a client from Evo to Revo 2.2.9.  They are hosting on GoDaddy.  Evo worked fine, but now with Revo, I'm getting errors in the cache files, which is causing the site to fail.  It's not always the same file.  The latest one is getResources.  I've attached the cache file.  You'll see beginning on line 615 that it has basically appended getResources snippet to itself, and so errors out b/c of the additional "<?" in the middle of the file.

I've been having other issues with cache files, different syntax errors, sometimes cache not being able to be created, etc.  I've searched all over for a resolution, found some stuff on Rackspace and NFS, but can't seem to find anything that would help.  GoDaddy uses APC by default for caching, so I disabled that in php.ini file to see if that helped, but it didn't.

**Comment by pbowyer** [comment]
@maclonghorn is this still an issue/did you address it? If not, I'd like to close the ticket.

**Comment by maclonghorn** [comment]
Client moved off modx and I have not seen this issue anywhere else. So you
may close. Thanks

**Comment by pbowyer** [comment]
@theboxer Please close, thanks.
