### ISSUE TITLE
Missing thumbnails in Manager media browser

### ISSUE THREAD

**Issue by leoandrews** [modxcms/revolution#10253]
leoandrews created Redmine issue ID 10253

Various sections of the Manager which used to show thumbnails seem not to any more. The problem is most evident in the media browser. It seems that phpthumb is returning a null response but there is nothing in the error logs which shows there to be a problem.

Example URL http://channel27.net/connectors/system/phpthumb.php?src=images%2Fshows%2Fshow--winehousespecial-t.jpg&w=100&h=80&f=png&q=90&far=1&HTTP_MODAUTH=_[suppressed-for-security]_&wctx=mgr&source=1

**Comment by oneismore** [comment]
If anyone still has this problem, check out the (dirty) fix here: http://forums.modx.com/thread/50710/gallery-not-displaying-images#dis-post-296661

It involves editing the shell_exec stuff core/model/phpthumb/phpthumb.functions.php file (or for evo the same file under assets/snippets/phpthumb/). Not nice but hey it works.

**Comment by pbowyer** [comment]
@theboxer close
