### ISSUE TITLE
Some place for a customer Logo on the Manager

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#10269]
mindeffects created Redmine issue ID 10269

A "logo area next to the website name in the manager" would be helpful thing. Me and clients have sometime several managers open and get confused, which is which. Today a client unpublished half of his website because he was working in the wrong manager.

**Comment by alroniks** [comment]
In MODX 3 it is already implemented. So I am closing it.
For details see screenshots by the link https://modx3.org/updates/week-19-june-18-24-2018
