### ISSUE TITLE
Content Type adding extra dot

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#10267]
sottwell created Redmine issue ID 10267

When using a Static Resource as an attachment and a Content Type, an extra . is added to the downloaded file's path:

assets/files/testing..pdf
assets/style/css/testing..css
assets/js/testing..js

**Comment by Alroniks** [comment]
Checked, confirmed for PDS (other content types works fine) #modxbughunt
Will try to fix

**Comment by Alroniks** [comment]
Fixed

**Comment by OptimusCrime** [comment]
PR is merged. Closing this then.

@modxbot close
