### ISSUE TITLE
Browser File Tree phpThumb requests

### ISSUE THREAD

**Issue by herooutoftime** [modxcms/revolution#10270]
herooutoftime created Redmine issue ID 10270

When changing directory in file tree in MODx-Browser all preceding images will be processed by phpThumb once again. When dealing with lots of images this affects performance, especially on shared enviroments with certain limitations.

Easy to reproduce: Just click through your file tree and check your requests. Navigate to a folder with images, afterwards to either an empty folder or folder without images.

**Comment by ant-tar** [comment]
This issue isn't actual for 2.7.1 and can be closed - when changing directories via file browser for each new folder all images processed using phpThumb only once when you firstly click on folder, any further clicks on the same folder won't initialize reboot of all images via phpthumb connector.
