### ISSUE TITLE
Added makeDownload() method to modFileHandler class

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#10277]
exside created Redmine issue ID 10277

This comes handy when a file should be sent to the user as a download instead of saving it into the filesystem.

Usage:

        $this->modx->getService('file','modFileHandler');
        // create the file object and do something with it
        $fileobj = $this->modx->file->make($this->modx->getOption('assets_path') . 'filename.ext');
        if ( !$fileobj->setContent($data) ) {
            $this->modx->log(modX::LOG_LEVEL_ERROR, '[modFileHandler] file could not be written at ' . $fileobj->getPath());
        } else {
            $this->modx->log(modX::LOG_LEVEL_ERROR, '[modFileHandler] written at ' . $fileobj->getPath());
        }
        return $fileobj->makeDownload();

**Comment by rthrash** [comment]
Since the PR has been merged for 2.4 that addresses this, can it be closed?

**Comment by rthrash** [comment]
Should have pinged @Mark-H on this for the last comment.
