### ISSUE TITLE
Media source: Policy combo box on update is displaying all policies

### ISSUE THREAD

**Issue by yuka123** [modxcms/revolution#10282]
yuka123 created Redmine issue ID 10282

By default when adding an user group and selecting an access permission policy the combo box displays only Media source policies.
However after saving , and then updating the user group the policy combo box displays all the policies.

**Comment by dannevang** [comment]
I can not reproduce this error on modx 2.5.7

**Comment by rtripault** [comment]
Time flies!

Thanks @dannevang 

Closing, but feel free to comment/reopen if needed.

Thanks

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @dannevang
