### ISSUE TITLE
Access Permission on TV seems doesn't work well

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#10297]
goldsky created Redmine issue ID 10297

I have a Usergroup applied a resource access permission, in manager context.
This user group can access the resource under that permission.
But this user group can't see the TV that is also applied the same Access Permission.

**Comment by ant-tar** [comment]
@goldsky it was tested for 2.7.1 and everything is OK (TV is accessible) now, so issue can be closed.

Short summary what had been done for that:

1. New clear MODX instance
2. Usergroup (for mgr context) with separate user 
3. Resource group with appropriate usergroup access
4. Resource and TV were applied to the group

**Comment by alroniks** [comment]
Seems it works so I am closing. Please, reopen, if the issue still actual.
