### ISSUE TITLE
Correct utf-8 to utf8 when processing config file

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10307]
bobray created Redmine issue ID 10307

This is an easy mistake to make and is devilish to solve, since it usually won't show up until later. I think MODX sets things to Latin1 when this happens.

Either make the correction and/or issue an error message about an invalid character set setting.

**Comment by OptimusCrime** [comment]
I feel like this is a very trivial issue. The config file should be generated during setup, and the character set should be correct from there. If not, there is something wrong with the setup process. This issue is old and there has not been any interest since it was posted in 2013. Closing this as a wontfix.

**Comment by OptimusCrime** [comment]
@modxbot close

**Comment by BobRay** [comment]
This needs more explanation.  There are cases where the user manually enters the $database_connection_charset value in config.inc.php. If they put utf-8, they won't get utf-8 because that's not an accepted character set.  There are other charsets that a user might insert a dash into as well.

The fix is one line in each of the settup/includes/configreader classes:

`     $database_connection_charset = str_replace('-', '', $database_connection_charset);`

**Comment by OptimusCrime** [comment]
I know how to fix it. Feel free to submit a PR for it, but I think this is one very specific edge case that we simply do not benefit from implementing.

**Comment by JoshuaLuckers** [comment]
I think an invalid value in a config file should result in an error instead of making any assumptions.
