### ISSUE TITLE
Make merge the default in setProperties()

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10337]
bobray created Redmine issue ID 10337

public function setProperties($properties, $merge = false) {

I'm suggesting $merge = true as the default.

It's a rare case when you want to trash the properties you're not setting.

**Comment by BobRay** [comment]
I just took a look at the current core code, and the use of `public function setProperties()` is very inconsistent and confusing across the multiple instances in the core.  

- modResource has $merge = true as the default
 
- modElement, modRestController, modMediaSource, modParser and modPropertySet have $merge = false as the default

- modLoginController uses setProperty() to do its own merge - no choice.
 
- modManagerController gives you no choice -- merge is false. The whole properties array is replaced with what is passed in.
 
- modProcessor is the opposite. No choice, merge is always true whether you want that or not.

The ones with no choice, especially the last two, can be frustrating when you're writing unit tests.

**Comment by JoshuaLuckers** [comment]
Good points! What if we introduce new methods like `updateProperties`/`updateScriptProperties` for "merging" and `setProperties`/`setScriptProperties` for "replacing"?

**Comment by Mark-H** [comment]
You've clearly looked into this more than I have, but I do want to emphasise that `setProperties` on a database object that has a properties column (like `modResource`) does something _very_ different from setProperties on a controller or processor which is used only in a single "request" or "execution". 

Having different defaults or behaviors in such cases is to be expected and in fact desirable. 

If something merges when it shouldn't for your use (e.g. modProcessor in a unit test), simply reinstantiate the class with the new properties.

**Comment by JoshuaLuckers** [comment]
They do something very different but they still share the same name. Without looking at the implementation it's very confusing for people using these methods. My suggestion was to make the function names more descriptive to make it more descriptive of the actual thing(s) it does.

**Comment by BobRay** [comment]
Before I learned to do a global search of the entire codebase before using a MODX function, I was bitten by this a few times when I assumed that there was only one getProperties() function.

@Mark-H Fair point, but it seems crazy to me that the defaults for modResource and modElement are the reverse of each other.

It can be pretty catastrophic, too, since you might want to reset a small array of properties. If you use setProperties() where the default is replacement, you'll be wiping out all the other properties. I suspect that this mistake is made often with elements (and user extended fields, which IIRC, don't even have setProperties() available). 

Without breaking things, the only idea I have is to add separate functions like mergeProperties() and replaceProperties() to the parent classes.  I'm not crazy about the idea, but at least they'd be consistent.  Down the road, we could deprecate setProperties() (or not).

At the least, The setProperties() methods that don't have a merge option, should definitely get them, imo, with the default set to what they do now.

**Comment by Mark-H** [comment]
It's only catastrophic if you're 1) knowledgeable enough that setProperties exists on whatever thing you're using without having to look it up, and simultaneously 2) don't check the parameter types either manually or by inspection in an IDE. 

> At the least, The setProperties() methods that don't have a merge option, should definitely get them, imo, with the default set to what they do now.

That's the only suggestion I've seen in this thread that I'd happily give my stamp of approval without reservations. Adding more methods, switching defaults, etc, seems way too heavy of a hammer to me personally.

**Comment by Ibochkarev** [comment]
Fixed #15059

Thanks for taking time to report this issue and help make MODX better.
Please reopen if you still encounter this issue.

@modxbot close
