### ISSUE TITLE
install [config.dist.new.xml]

### ISSUE THREAD

**Issue by GPS777** [modxcms/revolution#10362]
GPS777 created Redmine issue ID 10362

????????? ?????? ? ???? ???????????? ????????? ? ???? ? www\setup\config.dist.new.xml ,
?? ??????????? ??? ?? ?????????,* ?? ??????????* ???? ???????????? ??

**Comment by pbowyer** [comment]
@theboxer close

**Comment by Mark-H** [comment]
Closing as missing information. If you're still having issues installing MODX, please open a new issue or thread on the forum.
