### ISSUE TITLE
The modMenu (modx_menus) table should not be unique on "text" but should have an ID field

### ISSUE THREAD

**Issue by b03tz** [modxcms/revolution#10375]
b03tz created Redmine issue ID 10375

The modMenu (modx_menus) table should not be unique on "text" but should have an ID field.
Multiple menu's with the same title should be possible. Example: Webshops Shop 1 Products Categories Orders Shop 2 Products Categories Orders More information:
 http://modxcms.com/forums/index.php/topic,55470.0.html

**Comment by alroniks** [comment]
As I see for now it can be fixed using lexicons. Titles can be shop1_products, shop1_orders, shop2_products etc. But in lexicons, it can be any value that you want. I would close it. 
@b03tz @rtripault @OptimusCrime

**Comment by OptimusCrime** [comment]
I prefere numeric IDs, but this works as well. Fine by me.

**Comment by theboxer** [comment]
As pointed out, lexicons can solve the UI part of this issue. Also unique text is better for portability and data consistency instead of auto gen id column.
