### ISSUE TITLE
Message box on save document

### ISSUE THREAD

**Issue by Mido** [modxcms/revolution#10406]
mido created Redmine issue ID 10406

I have two editors working on revo and both had the same mistake/problem/error... When editing a content and they choose "save and continue" it could happen two things: An error happen, an small error message is shown and return to the edit content page. Save is succesfull, an small confirm message is shown in the top right corner and dissapear in a few seconds. I think if everthing is OK, the message should be shown in the center of the screen.
If an error happens, it must be shown a confirmation box ( must press OK button or simmilar ) and not only a message because the editors usually thinks the document was saved correctly ( and it doesn't ) and the close the document without saving changes. Please, don't tell me my editors are stupid Tongue I've tested it and I think an small but effective change can be done to improve it.

**Comment by adamwintle** [comment]
I agree with @OptimusCrime, this is a bad idea. @modxbot close
