### ISSUE TITLE
No way to retrieve the ID of a modSymLink resource

### ISSUE THREAD

**Issue by oksushi** [modxcms/revolution#10426]
oksushi created Redmine issue ID 10426

When viewing a resource of type modSymLink, the [ &#91;*id&#93; ] returns the ID of the original resource (as you would expect). It would be useful to be able to retrieve the ID of the modSymLink itself. Forum thread: http://modxcms.com/forums/index.php/topic,54742.0.html

**Comment by adamwintle** [comment]
One thing comes to mind: You may have a page which you want to change sometimes, e.g. /promo and you want to maintain the URL structure for SEO and findability.  Then when the promo changes you'd change the redirect ID from within the SymLink to update the content, but the URL structure stays intact. 

But overall this seems convoluted and complex, and there's a lot of simpler ways to achieve the same results.
