### ISSUE TITLE
Create a custom "add MODx tag" button for the content editing fields to help insert tags.

### ISSUE THREAD

**Issue by pixelstuff** [modxcms/revolution#10458]
pixelstuff created Redmine issue ID 10458

Create a button that would pop up a form to insert a MODx TV, Snippet, or Chunk. Not sure if this would have to be in the Rich Text editor or if it could be stand alone so that it would work with Rich Text turned on or off.

**Comment by OptimusCrime** [comment]
Any other input concerning this? Is this something we'd like to incorporate in the MODX Core? I for one votes for closing this ticket as a wontfix. Good idea, but I don't feel like going in that direction.

**Comment by pixelchutes** [comment]
Seems like something an Extra could achieve. :-1:

**Comment by OptimusCrime** [comment]
Yeah, my 5 cents as well.

I'll go ahead and close this then. Feel free to comment and/or reopen.

@modxbot close
