### ISSUE TITLE
Move field to new Tab

### ISSUE THREAD

**Issue by charliez** [modxcms/revolution#10505]
charliez created Redmine issue ID 10505

Ability to move a field from one tab to another, existing or new.

**Comment by adamwintle** [comment]
This is one of those UI things which seems deeply entwined in the core MODX system, and would require an entire overhaul to achieve a satisfactory UI.

Perhaps this issue could be closed in favour of this discussion which looks at the topic in a broader way https://github.com/modxcms/revolution/issues/11774 (and suggests looking at this in MODX Next)

**Comment by jpdevries** [comment]
Unfortunately with ExtJS authoring the DOM for us this not very straightforward. Has anyone tried using JavaScript to move the filed from one tab to another after ExtJS does it's thing? I'm not sure if that would break anything or not. If that doesn't work, would it be possible to make it configurable in MODX where the fields go in the first place? Would it be worth it?

**Comment by adamwintle** [comment]
It might be possible to do it with jQuery or just plain JavaScript. But while we're stuck with ExtJS it doesn't make sense to bundle other JS libraries into the core to add workarounds and hacks; it would seem messy and would bloat the core. 

I'd say if it can't be done with ExtJS and what we have to work with now, then its not worth it and the improvement is pushed to MODX Next.

**Comment by jpdevries** [comment]
> I'd say if it can't be done with ExtJS and what we have to work with now, then its not worth it and the improvement is pushed to MODX Next.

Agreed. If we can collectively agree on an HTML-first process for the front end of MODX Next we wouldn't run into these issues that boil down to a lack of creative freedom within the Manager in the first place. In the absence of an official roadmap for MODX, I continue to hope! :pray:

**Comment by rthrash** [comment]
@rtripault if this one isn't straightforward to achieve with the current Manager, let's close this in favor of waiting for the new Manager in 3+/Next. #modxbughunt

**Comment by rthrash** [comment]
Based on discussion in the #modxbughunt Slack channel, closing this for now. In all likelihood we'll not see any action on this until the non-ExtJS, HTML first Manager is released as part of a future major version.
