### ISSUE TITLE
User settings not accurate after logout/login in front end

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10536]
bobray created Redmine issue ID 10536

If you log in as a user in the front end, then log out and log in as another user, $modx->getOption() gets the previous user's user settings. In fact, the original settings seem to persist through several logouts and logins for several users. Users continue to get the User Settings of the original user. Not sure if this is a problem in the Login snippet, with User Settings in the core, or with the cache.

**Comment by adamwintle** [comment]
I think most of this has been smoothed out now?

**Comment by OptimusCrime** [comment]
Closing because of age, and because I agree with @adamwintle that most of this (if not all) is fixed.

Feel free to reopen or comment

@modxbot close
