### ISSUE TITLE
Add capability to delete Setup directory from Manager on config check screen.

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10568]
bobray created Redmine issue ID 10568

It would be nice if the Configuration Check screen offered a button or link that let you delete the setup directory in the "Installer Still Present" warning message.

**Comment by theboxer** [comment]
There's an option to delete setup folder after the installation. I don't think we need the button in the dashboard widget rn. For the site admin it's quite easy to delete the folder from FS.
