### ISSUE TITLE
Form Customization: can't target fields for hideField/showField in non-webkit browsers

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#10571]
netprophet created Redmine issue ID 10571

Turning a string into an array with the following code flds = flds[flds] seems to work in webkit, but not in anything else (at least in my environment). flds becomes undefined in non-webkit browsers. This results in the fact that the hideField form customization rule currently only works in Webkit browsers. The following works in all browsers including webkit: flds = [flds]

**Comment by rthrash** [comment]
@netProphET I suspect this one is resolved now and can be closed for the #modxbughunt

**Comment by rtripault** [comment]
Let's close it then, but feel free to comment/reopen if needed (or send complaints to appropriate desk!)

Thanks ;)
