### ISSUE TITLE
Create system/context/user settings by copy

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#10612]
gadamiak created Redmine issue ID 10612

To create an override setting for either system, context or user requires to manually enter key and other properties. To do that it's necessary to switch back and forth between the grids. It would be much simpler and quicker to duplicate a setting in destination of choice (system, context, user) and then only adjust its properties. One destination at a time would be sufficient. I would expect it to work in two variants: Copy a setting to : 1. In settings grid select the setting to copy and use action "Copy to..."
2. Select the target destination (select, optgroup, option).
3. Copy and (optionally) display the target destination. Copy a setting from : 1. Use "Create New" button in settings grid.
2. In modal window use button "Copy from..."
3. Select the source destination (select, optgroup, option).
4. Select the setting to copy.
5. Copy and fill a form with values.
6. Edit properties and save.

**Comment by rtripault** [comment]
There has been some enhancement in the way *settings are handled, so 'ill close this one.

Please feel free to comment/reopen if appropriate.
Thanks

#modxbughunt
