### ISSUE TITLE
"Show Sorting Options" pane is not accurate

### ISSUE THREAD

**Issue by dae** [modxcms/revolution#10676]
dae created Redmine issue ID 10676

In "Show Sorting Options" pane add a tiny margin before "Sort By" and reduce the size of the arrow button (or increase the size of the text in a dropdown), because it looks disproportional. Please see the screenshot.

**Comment by rtripault** [comment]
I guess this is no more relevant since Revo 2.3, so closing.

Feel free to comment/reopen if needed.
Thanks
