### ISSUE TITLE
standardize system event names

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10701]
bobray created Redmine issue ID 10701

It's probably way too late for this, but with the onBefore events, sometimes the "before" is ahead of the object name, sometimes after it. They should be consistent so users don't have to look it up every time they use one of these events (unless I'm missing a rule here). Here are a few of them: OnBeforeDocFormSave
OnCategoryBeforeSave
OnChunkBeforeSave
OnBeforeChunkFormDelete
OnTemplateBeforeRemove
OnBeforeTempFormDelete
OnBeforeTempFormSave

**Comment by amdbuilder** [comment]
This issue is still valid in 2.3.3.  It would make things a little easier to have them standardized some.

**Comment by BobRay** [comment]
It seems like creating aliases for those that don't fit the standard would be a good interim solution.

**Comment by Mark-H** [comment]
I don't see how we can do this with a massive breaking change.

**Comment by BobRay** [comment]
I think aliases would still work, though there would be a slight performance hit.

**Comment by Mark-H** [comment]
There's no such thing as system event aliases, so feel free to elaborate or to send a pull requests with a proposed implementation. 

Sorry if I'm being harsh with closing out issues, but there's still so many that I'd like to see either a clear path we can take to closing it, or substantial benefit to keep things open.
