### ISSUE TITLE
Make the left bar in the manager follow when you scroll down a long page

### ISSUE THREAD

**Issue by leaase** [modxcms/revolution#10703]
leaase created Redmine issue ID 10703

If you have a long vertical page in the manager, and you scroll down a bit, then you lose the drag-n-drop possibilities from the left bar. So it would be great if the left bar sticks at the top of the screen when you scroll down. Like a static element in some way.

**Comment by rtripault** [comment]
Closing as won't fix any time soon (~7 years later).

Feel free to comment/reopen if needed.
Thanks
