### ISSUE TITLE
Number of assigned templates when editing a template

### ISSUE THREAD

**Issue by xpix** [modxcms/revolution#10752]
xpix created Redmine issue ID 10752

Hi, Would be nice to show the number of assigned templates for a template somewhere easy to see. A solution would be to have the tab look like "Assigned Template Variables(10)". This is an easy way to show that the template has assigned TVs. The other way would be to to navigate through all the pages(hard) or sort by Rank or Access (2 more clicks) Thanks

**Comment by rtripault** [comment]
Let's say that will do the trick.

Feel free to comment/reopen if needed.
Thanks
