### ISSUE TITLE
Install problem with database check

### ISSUE THREAD

**Issue by aceman3000** [modxcms/revolution#10760]
aceman3000 created Redmine issue ID 10760

At install you fill out the database connection fields.
When you click on "test Database settings" and the success message appears you click on the next link "Create or test selection".
If the message "Table prefix already in use" appears and you change the table prefix, and click again on the link "Create or test selection", then the old value ist still beeing used. You have to click on "test database settings" again, before you do this step. Should work directly with the second link.

**Comment by gernotebenlechner** [comment]
I can confirm that behavior on a clean 2.5.8-dev install at #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @gernotebenlechner

**Comment by alroniks** [comment]
Solved by merging #14543
