### ISSUE TITLE
Duplicate box should also include the Caption field

### ISSUE THREAD

**Issue by xpix** [modxcms/revolution#10793]
xpix created Redmine issue ID 10793

Hi, When duplicating a TV the box should also contain a caption field. If a template has 5 similar text TVs the caption box will help a lot as you do not have to click on the TV and change the caption. Maybe this can be extended to Snippets, Plugins, Templates but is not as important as for TVs.
Thx

**Comment by Alroniks** [comment]
Hooray! I did it! :)

**Comment by Alroniks** [comment]
@OptimusCrime Hi, I think we can close this issue as PR was merged.
