### ISSUE TITLE
Buttonbar position when scrolling

### ISSUE THREAD

**Issue by ronaldlokers** [modxcms/revolution#10914]
ronaldlokers created Redmine issue ID 10914

When you are editing a page and you scroll the button bar with "Save, Duplicate, Preview, Cancel..." stays in position. It would be better if it scrolls with the page until it hit's the top of the page and then start to stay at a fixed position. Because else the buttonbar will stay about 100px from the top of the page all the time, while it should have a position of about 10px from the top when you start to scroll.

**Comment by rtripault** [comment]
I guess this is no more an issue since Revolution 2.3, so closing.

Feel free to comment/reopen if needed.
Thanks
