### ISSUE TITLE
Make the two DB checks "Next" buttons rather than links

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#10977]
bobray created Redmine issue ID 10977

It may not be clear to new users what to do when they see those links. If "Next" buttons aren't feasible, at least put a message in that says "Click on this link to proceed" or something similar.

**Comment by alroniks** [comment]
If I understood correctly it is related to the installation screen. It has not been fixed yet but is going to be fixed by the new design of installation screen. Details here (buttons Test) https://modx3.org/updates/week-18-june-11-17-2018

**Comment by BobRay** [comment]
A complaint about this just appeared in a review of MODX 3. ;)

**Comment by Mark-H** [comment]
They look like buttons to me now!
