### ISSUE TITLE
Add double click or drop-down hint/indicator to editable table cells (settings)

### ISSUE THREAD

**Issue by panc** [modxcms/revolution#10987]
panc created Redmine issue ID 10987

The related forum discussion threat: http://modxcms.com/forums/index.php?topic=44160.new;topicseen#new

**Comment by rtripault** [comment]
Seems like the issue "sources" are no more available, furthermore, given that's a 5 YO issue, closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by whitebyte** [comment]
I think it's still actual. There are some grids across the manager with "right-clickable" cells, and it's absolutely not obvious that they have context menus. Futhermore, right-clicking isn't standard and expected behavior for web UIs (and there are touchscreens also), and right now this is a source of consfusdion.

**Comment by rtripault** [comment]
Yes, my bad, the coffee did not kick when closing...

**Comment by rtripault** [comment]
FWIW, some screenshots below of some manager tweaks trying to solve those issues

Contextual menu (right click) in grids

![screenshot_2017-03-10_11-41-24](https://cloud.githubusercontent.com/assets/300920/23792325/c3cb0718-0586-11e7-80ef-089d2ca0ef4b.png)

Editable grid cell being "hovered"

![screenshot_2017-03-10_11-41-49](https://cloud.githubusercontent.com/assets/300920/23792343/d66ec832-0586-11e7-9523-82e1d8c7a4fe.png)

**Comment by OptimusCrime** [comment]
What...What is going on with your manage interface there?

**Comment by rtripault** [comment]
* [ ] Pimp My Manager
* [ ] Creative Freedom
* [ ] A Momentary Lapse of Reason

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/14176 and https://github.com/modxcms/revolution/issues/14125

**Comment by Ruslan-Aleev** [comment]
I think we can close this issue, done with PR https://github.com/modxcms/revolution/pull/14748
