### ISSUE TITLE
Add final backslash to path when importing static resources

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#11003]
bobray created Redmine issue ID 11003

In "Import Resources" if the user specifies the path without a final backslash, the import is successful but there's no backslash between the final directory and the filename.

**Comment by Alroniks** [comment]
Looks like that isn't actual for now.

@OptimusCrime Candidate for closing, I guess.

**Comment by OptimusCrime** [comment]
Sweet. Nice work @Alroniks !

@modxbot close
