### ISSUE TITLE
Clarify Import Resources Panel

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#11004]
bobray created Redmine issue ID 11004

It shouldn't be necessary (or desirable) to copy static resources to the core/import folder. Maybe it would be better change the Top Menu entry to "Import Static Resources" and limit this panel to that function.

**Comment by adamwintle** [comment]
@BobRay @wshawn I'm just going through some of the very old issues, do you guys still feel this is a relevant issue to remain open? If so maybe we should look at steps to closing this after >5 years

**Comment by BobRay** [comment]
I haven't used the import resource feature since back then. It's fine with me if you close this, but I don't know if anything was ever done on it.

**Comment by adamwintle** [comment]
@modxbot close
