### ISSUE TITLE
Add ID number to manager pages (resources and elements)

### ISSUE THREAD

**Issue by frogabog** [modxcms/revolution#11096]
Could we view the ID of whatever we're viewing as a page in the manager, somewhere on the page itself?  Perhaps in the title area in parentheses? 

Example: If you've navigated elsewhere through the resource tree for any purpose, fetching an ID can prove to be a little awkward having to go back and re-open the tree to see them.  

Working reasons aside, it'd just be nice to immediately know what the ID is every time the resource is opened.  It would do wonders for ID association for developers, because after a while you'd remember the ID as well as the title/name just because you see it every time you open it.

Elements need this less, but they too may as well show the IDs.  Why not?

**Comment by OptimusCrime** [comment]
Should this be done with or without a system setting for toggling the behavior?

**Comment by gpsietzema** [comment]
Please do it with a system setting, because we personally don't want to show it to our clients.

**Comment by pepebe** [comment]
System setting would be fine with me.

**Comment by wuuti** [comment]
Note: there are already permissions "tree_show_element_ids" and "tree_show_resource_ids". It makes sense to use permissions for that instead of a setting and would be wise then to add a permission "form_show_resource_ids" or something like that.

**Comment by OptimusCrime** [comment]
Good catch. I think that makes sense as well.

**Comment by JoshuaLuckers** [comment]
This would be a nice addition. Maybe it could be added to MODX 3?
If needed I would like to help getting this feature in MODX 3.

**Comment by OptimusCrime** [comment]
Isnt there an id there today? Seem like noone has complained since we rolled out the new design (version 2.3?). In favor of closing this.

**Comment by JoshuaLuckers** [comment]
There isn't. See the screenshot posted earlier in this issue.

**Comment by OptimusCrime** [comment]
You are right, my bad. I thought perhaps the ID was added after the 2.3 redesign.
