### ISSUE TITLE
Logout user but no lock out

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#11106]
There are times in the life of a MODX admin, when he has to kick everybody out of the Manager: update time e.g. But how to prevent people from loggin in again after the just have been kicked out by "*Log out all Users*"?
Where is the "**Lock out all Users**" button to keep them from accessing the Manager before we are ready? I would love to have this feature!

**Comment by rtripault** [comment]
Huge :+1: here.

I just don't see this into the core, and would vote for having this provided as an extra/component.

**Comment by mindeffects** [comment]
What are you referring to, @rtripault? "Lock out" or "ACLs for namespaces"? ;-)

**Comment by rtripault** [comment]
Sorry, that was for the "lock out" feature (while ACLs for namespaces sounds interesting, that might be tricky to do -- at least we would need more details on what's expected -- and belongs to another issue/proposal).

As an extra, the "lock out" could be handled with a CMP (and some permissions to limit its access), where users could define which rules (user, group, role...) to define "allowed" users while manager being set as "locked".

**Comment by mindeffects** [comment]
Maybe this is a thing for an external setup/update script that kicks everybody out, locks the door, does its job and then unlocks to system again. Maybe a REST job (for the kick out), then make the manager login unavailable, which is drastic but also effective.

**Comment by inreti** [comment]
Isn't this done by the Locker extra (output of the modxccc)?

**Comment by mindeffects** [comment]
CCC rocked! Can't wait any longer for 2.4 to show some of the fruits!

**Comment by Mark-H** [comment]
[Locker](http://modx.com/extras/package/locker) will do this, so am closing the issue (unless any of you have a good reason it should stay open).
