### ISSUE TITLE
False Dirty on Key Press

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#11109]
- install MODX 2.2.11
- Edit a Resource
- Press the ⌘ key
- Navigate away from the page
- Notice the false positive leave page warning

![image](https://f.cloud.github.com/assets/592335/2077816/7010ab78-8db6-11e3-8b61-b62e5532acf8.png)

This is because the [onFieldChange method](https://github.com/modxcms/revolution/blob/develop/manager/assets/modext/widgets/resource/modx.panel.resource.js#L235) is being triggered

**Comment by alroniks** [comment]
Looks like fix already merged. So closing, feel free to reopen if needed.
