### ISSUE TITLE
Fully Remove or Re-Add File Tree Icons

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#11113]
![](http://j4p.us/image/3C073a2E212I/Screen%20Shot%202014-02-04%20at%209.11.48%20PM.png)

so the buttons in the file tab of the tree were completely removed. while attempting to remove the white line (`div.x-tab-strip-spacer`) i found myself wondering why the button row was removed in the first place

**Comment by alroniks** [comment]
I've never met some questions from people about deleted buttons for file tree. So I guess we can close it. However, buttons in resource/elements tree still discussible https://github.com/modxcms/revolution/issues/11585
