### ISSUE TITLE
Admin user not able to login after installation in Ubuntu 13.10

### ISSUE THREAD

**Issue by sharadchhetri** [modxcms/revolution#11119]
After fresh installation of modx-2.2.11-pl in Ubuntu 13.10 . Administrator privileged user is not able to login. 
I have worked on this issue and solved the problem in dirty way .
For reference, I am sharing the forum link as given below .

http://forums.modx.com/thread/88523/cannot-log-into-manager-after-fresh-install

In forum link solution and screenshot is given

**Comment by rtripault** [comment]
I guess this has been fixed with #11202, so closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by sharadchhetri** [comment]
Thankyou , I was waiting to know when the bug was fixed.

Regards
Sharad
