### ISSUE TITLE
New Feature: Exclude resource alias from child URIs

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#11153]
This can be helpful when you have a container just for site-working purposes, like grabbing it's child resources. For example:

Footer pages
- Sitemap
- Privacy statement
- Disclaimer
- Conditions

In this case you get an automated alias like "footer-pages/sitemap.html" or "footer-pages/disclaimer.html".
This is unwanted in this case, because you don't want "footer-pages/" in your url.
Of course you can use "freeze uri" function on every child, but when you a have a container with a lot of children pages and a lot of children-children pages that's a hell of a job. In that cases it's easier to turn a parent to be excluded in child paths.

I already have this working; I tried to send a PR but cannot get only those commits to be a PR. Please look at these two commits...

https://github.com/bertoost/revolution/commit/4323cfdbdb9afca3ff23d30faf0492e524b57faa
https://github.com/bertoost/revolution/commit/1a9bd36035b6bba28ff50a2692060b8567949fd3

OR to move the field below alias (and some changes to the texts)

https://github.com/bertoost/revolution/commit/07cd3a4b8045ba6868d455c6fa7965a1f5690576

**Comment by degoya** [comment]
is this features still not implemented in 2.3.3?

**Comment by vierkantemeter** [comment]
The following hack will work in both 2.2 and 2.3 to hide a resource in a URL:
https://github.com/Qwarble/revolution/commit/df1902d5b68e02d760842c19f3a6e647f38ff6ab

**Comment by osabate** [comment]
That's great. Are you gonna make a PR for it?

**Comment by vierkantemeter** [comment]
That's up to @Qwarble

**Comment by Qwarble** [comment]
I did PR, and it was closed.
https://github.com/modxcms/revolution/pull/11167

**Comment by dssaf** [comment]
2.3.3
An error occurred while trying to save the resource.

**Comment by gadgetto** [comment]
2.4 an still not available  :-(

**Comment by jonleverrier** [comment]
:-1:

**Comment by sbrin** [comment]
When this feature will be in released?

**Comment by Jako** [comment]
Since @bertoost is not working on this anymore, someone else has to check this PR on 2.5.1+

**Comment by rainbowtiger** [comment]
I just converted a client from Evolution, which has this feature, to Revolution, which doesn't. Why was this left out of Revolution?? The site needs to keep the same URLs for tracking purposes, and now I have no way of making that happen, short of hand-entering Freeze-uri for every single page that needs this.

**Comment by mrhaw** [comment]
One option if to turn off use_alias_path but that affects all folders then.

**Comment by OptimusCrime** [comment]
I agree that this issue is something we should look into. It would be nice to have in certain situations.

**Comment by digitalpenguin** [comment]
+1 for this. I could have used it many times.

**Comment by OptimusCrime** [comment]
Just wondering about what people want. 

If we have the following relationship from first parent to parent to child like so A -> B -> C, where C is the child of B and B is the child of A. Now, if A was to ignore parent alias, would it ignore just B or B and A together? Unless it was to ignore both B and A, it would be no way to specify that C should have just its own alias.

**Comment by rainbowtiger** [comment]
Same was as it works in Evolution: a checkbox "Use current alias in alias path" to apply to any container, so this would never apply to "C" in your example, only to B or A, to control which containers get included or excluded in the URL.

**Comment by OptimusCrime** [comment]
I have the following resource Foo -> Bar.

*Foo enabled, Bar enabled*

- Foo uri = foo/
- Bar uri = foo/bar

*Foo disabled, Bar enabled*

- Foo uri = foo
- Bar uri = bar

*Foo enabled, Bar disabled*

- Foo uri = foo
- Bar uri = foo/bar

*Foo disabled, Bar disabled*

- Foo uri = foo 
- Bar uri = bar

I just tested this in Evo with all the combination mentioned above. So, as far as I can tell, with the setting disabled (Do not include alias in path) all child resources will not have that alias in their uri, but the resources themselves will still have it in their alias.

**Comment by rainbowtiger** [comment]
Yes, that's how it should work, otherwise the parent resources itself couldn't be accessed; it's needs its own alias for its own URL.

**Comment by OptimusCrime** [comment]
Makes sense. Alright. If I have some spare time I'll try to take a look at this. I can't imagine this being that difficult to implement.

**Comment by OptimusCrime** [comment]
I've submitted a PR that attempts to solve this, following the discussion above and the testing I did in Evo. I would love some feedback on that PR. 

#13395

**Comment by Mark-H** [comment]
Included in 2.7 at last ;)
