### ISSUE TITLE
Feature request: Separators for Resources

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#11154]
I often have Resources which belong to a common group. Sometimes I need a way to identify them or separate them from other parts of the tree.

My approach so far has been to create a resource and give it a Page Title with a few dashes. Once you hide it from the menus and make it non searchable, it can be dropped into your tree and separate large numbers of Resources.

See Resources 100 and 177 below. 

![resource dividers](https://f.cloud.github.com/assets/1786476/2269111/c9fe98f6-9ed3-11e3-8551-c2672657ebab.png)

My approach works perfect for me but I wonder if anyone else has a similar requirement or a different approach?

Is a native divider type resource needd in the manager or are we adding bloat?

**Comment by rtripault** [comment]
As far as i understand, this is a "won't fix/won't ship into the core", so closing.

Feel free to comment/reopen if needed.
Thanks everyone
