### ISSUE TITLE
cannot login with admin password containing unsanitary characters

### ISSUE THREAD

**Issue by snowyseal** [modxcms/revolution#11161]
During fresh install of modx-2.2.12, set an admin password containing, say, ';' (semi-colon), then you cannot subsequently login to the modx manager.

handlePost() method, line 145 ./manager/controllers/default/security/login.class.php:

   $san = array("'",'"','(',')',';','>','<','../');

shows the full set of disallowed characters, which it removes from the posted password. 

Maybe installer should stop you using these special characters or perhaps escape them properly during login?

**Comment by Mark-H** [comment]
Yep, dupe.
