### ISSUE TITLE
clear cache

### ISSUE THREAD

**Issue by mrsln** [modxcms/revolution#11216]
I'm getting bizzare output after calling $modx->cacheManager->refresh(), or clicking in Site -> Clear Cache in the site manager, or changing any value in the system settings. A workaround is to clear core/cache folder. I've posted the output - https://gist.github.com/mrsln/9614623 (please tell me if there is sensetive information)

**Comment by rtripault** [comment]
I will assume that was environment related, so i'm closing this one.

Feel free to comment/reopen if needed.
Thanks
