### ISSUE TITLE
Update processor end with fatal error

### ISSUE THREAD

**Issue by woazli** [modxcms/revolution#11220]
Version: MODX Revolution 2.2.13-pl (advanced)

When updating a resource in modx with a php included file, i get the following fatal error:
Fatal error: Call to a member function getOption() on a non-object in /<...>/core/model/modx/modresource.class.php on line 853
My Code:
```
                 $fields = array(
			'id' => $iii,
			'pagetitle' => $titel,
			'alias' => $titel.$datetime,
			'menutitle' => $titel,
			'content' => $text,
			'parent' => $kategorie
		);
		 
		$response = $modx->runProcessor('resource/update', $fields);
		 
		if ($response->isError()) {
			if ($response->hasFieldErrors()) {
				$fieldErrors = $response->getAllErrors();
				$errorMessage = implode("\n", $fieldErrors);
			} else {
				$errorMessage = 'An error occurred: ' . $response->getMessage();
			}
				
			echo $errorMessage;
		 
		} else {
			
		}
```
Create/Publish/Unpublish/Delete and so on are working perfectly.

any help is appreciated :)

**Comment by rtripault** [comment]
This would indeed fall into support rather than a bug.

And since it's been a long time the issue has been opened, closing it.
