### ISSUE TITLE
Real-time resource alias

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#11225]
When we give Resources a title, the contents of the Title field (1) are mirrored in real-time at the top of a Resource (2). 

Is it difficult to have the same thing happen in the Resource Alias field (3) and just the separate words with a dash?

![real-time-alias](https://f.cloud.github.com/assets/1786476/2484639/9224f238-b10f-11e3-8149-b3f50bcca67c.png)

**Comment by rthrash** [comment]
Since the PR for this issue has been merged for 2.4, can this be closed?

**Comment by Mark-H** [comment]
Yep! My bad, should've closed it when I did the merge.
