### ISSUE TITLE
Default anonymous username hard-coded

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#11231]
For the MODX user placeholders, the default user is hard-coded as (anonymous). There really should be a way to modify that.

modx.class.php line 1207, in Revo 2.2.13

**Comment by OptimusCrime** [comment]
I am pretty sure this is implemented by now? @sottwell did your pull get merged?

**Comment by sottwell** [comment]
Yes, it's been in 2.4 for a while now.

**Comment by OptimusCrime** [comment]
Cool!

@modxbot close
