### ISSUE TITLE
Enhancement Property Sets: Allow element properties to be file/image input

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#11238]
I use the element drag and drop into content/tv functionality quite often, many times to configure chunks, that also can contain links/images where I would like the editors to be able to select the file to be linked or the image to be displayed. 

But when adding a new property to an element it is not possible to select a field type of file/image in the Type select list, which would behave like a normal file/image TV and open the media manager to select it.

![bildschirmfoto 2014-03-26 um 15 43 16](https://f.cloud.github.com/assets/445501/2525976/3f00a55e-b4f5-11e3-8da5-3aaa601a84f5.png)

**Comment by alroniks** [comment]
Seems it implemented already
