### ISSUE TITLE
Recent Resources: No date and time? FR: View personal manager log!

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#11264]
Just a little FR/improvement:
When someone wants to know WHEN he edited something, the "Recent Resources" (User > Profile > Recent Resources) does not provide that information. It only says "that" one edited a resource but nothing else/more. It tells my the ID, which I can figure out when I edit the resource (at least in the URL because the ID is nowhere else mentioned (any more)) but I have no chance to get the exact date/time if I have no access to the "manager logs" – which most users don't have.

Maybe a "View personal manager log" (only for MY stuff) would be easy to implement in exchange for the now used "Recent Resouces" listing.

And the functionality is already there, in the "manager logs" listing – just drop some of those select boxes and you are there.

**Comment by Mark-H** [comment]
Date is shown and results filtered on user in #14540.
