### ISSUE TITLE
Refactor core to support Autoloading of classes

### ISSUE THREAD

**Issue by fireproofsocks** [modxcms/revolution#11272]
This is a big one, but one that should be on the radar.  The implementation of this would likely require a _lot_ of changes:
- one class per file
- use of PHP namespaces (PSR-4 namespace to directory mapping?)
- Dedicated "loader" class to handle instantiating any new classes such as manager controllers
- Support for more flexible dependency injection (not just passing the $modx reference in the constructor)
- Probably much more...

Due to the complexities here and the high probability that this would break all backwards compatibility, this might only be appropriate for MODX 3.

**Comment by OptimusCrime** [comment]
As I expressed in my blog post http://www.optimuscrime.net/en/blog/65-thoughts-on-the-future-of-modx based on the `Keeping MODX relevant`-series by @opengeek, this is something we should do, but I fear it is way too complex with the current code base. Such a major refractor would require a LOT of work and is most likely never going to happen.

Unless @opengeek (or @TheBoxer ) have anyhing to say, I suggest closing as wontfix and we'll have to live with the current way Revo functions.

**Comment by opengeek** [comment]
I don't believe this is as unattainable or unlikely as you think @OptimusCrime. Let's leave it open...

**Comment by OptimusCrime** [comment]
Perhaps not, I'll leave it open then :)

**Comment by Codenator81** [comment]
Is any one have work in progress on this  issue? I can help.

**Comment by Mark-H** [comment]
xPDO 3 resolves a large part of this I think

**Comment by Codenator81** [comment]
@Mark-H Yes I see but classes in core/model/modx still need attention I think.

**Comment by Codenator81** [comment]
https://github.com/Codenator81/revolution/commit/97c9d6f9780daa45caec3b5197854f6b07aba138 example how to start. But any way there need move ```components``` out of core directory I think.

**Comment by Alroniks** [comment]
Leave my five cents. This work should be done, of course, but it requires a lot of efforts and time. So my proposal is to start this work from support only PHP 7. 3.0 means ability to break backward compatibility, so it possible.

**Comment by Spudley** [comment]
As noted, this does sound like quite a large task. It seems like it might be a good thing to break the task down into smaller chunks.

**Comment by opengeek** [comment]
This work is in progress for 3.x — it will not be PHP 7 only but will require at least PHP 5.5. There is no way to break this into smaller tasks as this is a change to the foundation of MODX Revolution.

**Comment by OptimusCrime** [comment]
Any reason we need to keep this issue open? There are clear goals as specified in the MAB recommendations that elaborates how this should be done.

**Comment by alroniks** [comment]
> Any reason we need to keep this issue open? 

Absolutely no. All these ideas in progress right now and clear for all. So I am closing it to keep repository sorted.
