### ISSUE TITLE
[2.2] IE compatibility

### ISSUE THREAD

**Issue by jubbbird** [modxcms/revolution#11283]
Debilitating IE issues which cause my need to use an alternative browser to that which I use primarily. Yeah, I know, IE is "awful". Well I like it, so SHUT UP! Here's some silly bugs I've observed.

IE11 + IE10 mode: Form customisation, created profile, 'Create New Set' popup appears off the top of the screen.
IE9 mode solves it.
Also affects 'Quick Create TV' - but *not* 'Quick Create Chunk'

Revo: File browser driven by media source doesn't always show content of initial target folder. 'Files', or the currently selected folder on the left-hand folder tree needs to be clicked sometimes to reveal anything.

TinyMCE: In IE11 it seems the View HTML popup doesn't actually show you any code. IE10 mode sorts it out.

TinyMCE: The styles dropdown seems to fail to apply changes.

TinyMCE: 'Edit style' button produces the popup but appears not to actually set the styles.

Revo: Custom categories appear inside every root Element node even when empty. For example, I have no chunks in one of my categories, yet the empty category folder is listed under Chunks.

IE?: After creating a directory using the modx browser, the popup doesn’t disappear, and the folder list doesn't refresh to show the new one.

IE?: Quick update a weblink, switch to files tab, drag and drop file into weblink box to get URL, 'save and close'. Edit a second weblink repeating previous steps and the drag and drop will fail to land and right-click functionality in the manager is broken till refresh.

**Comment by whitebyte** [comment]
Since 2.2 branch seems to be discontinued, is this still actual?

**Comment by OptimusCrime** [comment]
Suggest closing this because some of the issues here are resolved and other concern extras (like modxcms/tinymce-rte).

Agreed @TheBoxer ?

**Comment by TheBoxer** [comment]
:+1:

**Comment by OptimusCrime** [comment]
@modxbot close
