### ISSUE TITLE
Rich Text document option only applies to main content, not template variables

### ISSUE THREAD

**Issue by atmmarketing** [modxcms/revolution#11303]
Each Rich Text Template Variable still loads as Rich Text when you clear the **Rich Text** document option under settings. Only the primary document content loads as a plain textarea field.

**Comment by mcnickel** [comment]
Can confirm this:
MODX Revolution 2.5.7-pl (traditional)
TinyMCE 4.3.4
PHP Version 5.5.9

TVs fall back to simplyfied RTE-skin if RTE is disabled in resource.
No issue with TinyMCE-rte in same configuration.

This could be TinyMCE-issue (no related issues at https://github.com/modxcms/TinyMCE/issues)
#modxbughunt

**Comment by rtripault** [comment]
Agreed that RTE specific, so closing (that and the issue age! ;p)
Thanks @mcnickel

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @mcnickel
