### ISSUE TITLE
Add warning to manager if js is disabled

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#11309]
It sounds obvious that you need js to work with the manager, but there should be a warning if js is disabled.

It can happen (especially during development) and its causing unnecessary confusion that cold be easily prevented.

Cheers from somebody who went totally nuts because he did just that ;)

pepebe

**Comment by alroniks** [comment]
In 2018 when javascript used totally everywhere it seems completely useless. I am closing it but if you don't agree please, reopen.
