### ISSUE TITLE
Image TV opens "wrong" File browser

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#11308]
After I click on the arrow button on the right side of an image tv, the file browser opens in a modal window (on the screenshot, its the one in the back) .

The file browser is missing a selectfield for media sources. Instead there is a button on the right side of the iconba.

This button opens another file browser on top op the first one with the selectlist in the right place (this is the one in the front).

![screenshot 2014-04-23 22 40 03](https://cloud.githubusercontent.com/assets/667315/2783100/e34317ac-cb28-11e3-83fc-16e0437a2396.png)

This happens in 2.2.14 on modxcloud with a Chrome Browser on OSX Maverick.

Regards,

pepebe

**Comment by rtripault** [comment]
This seems to be fixed (at least in current develop branch -- upcoming Revo 2.4), so closing.

Feel free to comment/reopen if needed.
Thanks
