### ISSUE TITLE
Resource fails to save if HTML tags are in a parent resources title

### ISSUE THREAD

**Issue by gleighfield** [modxcms/revolution#11341]
If a resources parent has HTML elements in the title, upon page load those elements are displayed in the parent field. When trying to save you will get the error of "Uncaught SyntaxError: Invalid regular expression: missing /". The resource will save however, but it will hand on the loading bar.

If however you click to change the parent resource, and reselect the same, the HTML elements will be gone, and you can save as per the norm, with no errors. Upon reloading and visiting the same resource, the HTML elements for the title will re-appear. Meaning that for a successful save you have to reselect the parent element every time.

![fix](https://cloud.githubusercontent.com/assets/1083436/2860416/16a5c830-d1cb-11e3-8bf6-ec41e1b84c02.jpg)

**Comment by arsen2607** [comment]
Mark-H, thank's for help, this realy work

**Comment by Mark-H** [comment]
This has been since been fixed. I think in the early 2.5.x series, but not exactly sure when.
