### ISSUE TITLE
Form customization does not work for checkbox labels

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#11363]
Changing the label for a resource's checkbox like "hidemenu", "published", etc. seems to add a new hidden label and does not replace the label's text.

2.2.14-pl
2.3.0-dev

![modx-form-checkbox-label](https://cloud.githubusercontent.com/assets/1913250/2945907/49439d44-d9e6-11e3-9fda-ec788c665aee.jpg)

**Comment by rtripault** [comment]
While i did not check/confirm the issue, reading the code make me thing that is a valid issue.

https://github.com/modxcms/revolution/blob/master/manager/assets/modext/core/modx.js#L373 does not seem to handle checkboxes, which have (almost often) an empty `fieldLabel` and use a `boxLabel`.

I guess we could check if an xtype is provided and if the xtype is `xcheckbox`, then search for the nested element with `form-cb-label` class, and update the value/content.

**Comment by labr1005** [comment]
This is a duplicate of #12890
