### ISSUE TITLE
Top menu cache doesnt get cleared for all users on edit

### ISSUE THREAD

**Issue by fractalwolfe** [modxcms/revolution#11362]
For some reason the top menu cache doesn't get cleared if you for example move a component out of the components menu. It shows correctly on the user you made the edit with, but not with say a limited admin user belonging to another user group. For this user the menu item is still in its old spot. Only after manually deleting the core/cache/menu directory the top menu refreshes for all users and shows up correctly.

This issue was found on 2.2.14

**Comment by rtripault** [comment]
As far as i can tell, this seems to be fixed (at least in current develop branch -- upcoming Revo 2.4) : the whole menu cache partition is cleared when sorting menu records, so closing.

Feel free to comment/reopen if needed.
Thanks
