### ISSUE TITLE
Replace hardcoded policy template descriptions with lexicon entries

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#11360]
It seems the descriptions for the policy templates (like AdministratorTemplate) under Access Controls > Policy Templates are hardcoded during installation in _build/data/transport.core.accesspolicytemplates.php, so changing the language has no effect on them as they are always displayed in english.

**Comment by meshkov** [comment]
Confirmed in 2.6.x and 3.0.
![2018-07-05_11-05-44](https://user-images.githubusercontent.com/1703670/42310198-72dc4504-8043-11e8-97d0-353504706b27.png)
And
![2018-07-05_11-06-59](https://user-images.githubusercontent.com/1703670/42310285-b0dcf862-8043-11e8-83aa-111d5e173249.png)

**Comment by alroniks** [comment]
The issue seems easy but actually requires a lot of works to have ability use translated descriptions for this templates and policies. The issue that these entities can be added by hands without any lexicons.

**Comment by alroniks** [comment]
Finally it is done! 🎉
