### ISSUE TITLE
Feature: Use ISO 3166-1 alpha-2 country codes in core

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#11391]
Gone are the days of managing a conversion list of numeric MODX Country IDs _(e.g. 223 => United States)_, but I am curious why they weren't simply replaced with the ISO 3166-1 country codes? I'm sure there was some discussion on the matter, and I'm even willing to be convinced otherwise... IMO, storing the country as a two character ISO code would be far more useful than storing the entire country name for each User record, especially given the many circumstances where a simple short-code can be easily used programmatically vs. full text.

A few simple examples:
* Country flag icons (using 2-char ISO naming convention)
* Compatibility with 3rd party services / APIs requiring ISO codes.
* Less space allocated in database

After some quick searching, I was not able to find any discussions about why MODX may have chosen not to incorporate ISO 3166-1, but I was able to find others who might just feel the same way: /cc @Mark-H @bertoost

While you can technically store a User's country as ISO 3166-1 (alpha-2) country code out-of-the-box, the experience is still disconnected. For example, the manager at least preserves a custom country value, but "US" is not displayed as "United States". Further, if you want to manually type in the ISO code for Canada (CA), you can't.

Possibly related to #2253 and http://bugs.modx.com/issues/5387 (not seeing #5387 on GH?)

**Comment by Mark-H** [comment]
This was fixed and merged into 2.4
