### ISSUE TITLE
2.3 fonts in Description and Summary fields

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#11423]
I know this is pretty low-tech :)
Are fonts within these fields meant to be monospace?

![font-difference](https://cloud.githubusercontent.com/assets/1786476/3104854/7585c07a-e66c-11e3-86b9-7bb7efc00053.png)

**Comment by rtripault** [comment]
Not sure there is a reason behind this, so marking this as "accepting pull request" ;)

**Comment by whitebyte** [comment]
I think this is related to issue #5691, maybe should be a part of it.

**Comment by Mark-H** [comment]
This is no longer the case in 2.5.7.

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Mark-H
