### ISSUE TITLE
Make all processors class based

### ISSUE THREAD

**Issue by theboxer** [modxcms/revolution#11437]
### Context
- [x] context/setting/create (#11501)
- [x] context/setting/get
- [x] context/setting/getlist
- [x] context/setting/remove
- [x] context/setting/update
- [x] context/setting/updatefromgrid
### Element
- [x] element/plugin/event/associate
- [x] element/plugin/event/get
- [x] element/plugin/event/getassoc
- [x] element/plugin/event/remove
- [x] element/plugin/event/update
- [x] element/plugin/event/updatefromgrid
- [x] element/propertyset/asselement
- [x] element/propertyset/associate
- [x] element/propertyset/duplicate
- [x] element/propertyset/get
- [x] element/propertyset/getlist
- [x] element/propertyset/getnodes
- [x] element/propertyset/getproperties
- [x] element/propertyset/remove
- [x] element/propertyset/removeelement
- [x] element/propertyset/updatefromelement
- [x] element/template/tv/getlist
- [x] element/template/tv/updatefromgrid
- [x] element/tv/renders/getoutputs
### Resource
- [x] resource/resourcegroup/updatefromgrid (@vasia123)
### Security
- [ ] security/access/policy/createpolicydata
- [ ] security/access/policy/removepolicydata
- [ ] security/access/policy/updatepolicydata
- [x] security/access/usergroup/category/create
- [x] security/access/usergroup/category/getlist
- [x] security/access/usergroup/category/remove
- [x] security/access/usergroup/category/update
- [x] security/access/usergroup/context/create
- [x] security/access/usergroup/context/getlist
- [x] security/access/usergroup/context/remove
- [x] security/access/usergroup/context/update
- [x] security/access/usergroup/resourcegroup/create
- [x] security/access/usergroup/resourcegroup/getlist
- [x] security/access/usergroup/resourcegroup/remove
- [x] security/access/usergroup/resourcegroup/update
- [x] security/access/usergroup/source/create
- [x] security/access/usergroup/source/getlist
- [x] security/access/usergroup/source/remove
- [x] security/access/usergroup/source/update
- [x] security/access/addacl
- [x] security/access/getacl
- [x] security/access/getlist
- [x] security/access/getnodes
- [x] security/access/removeacl
- [x] security/access/updateacl
- [ ] security/documentgroup/create
- [ ] security/documentgroup/getnodes
- [ ] security/documentgroup/getpairingnodes
- [ ] security/documentgroup/remove
- [ ] security/documentgroup/removedocument
- [ ] security/documentgroup/update
- [ ] security/documentgroup/updatedocumentsin
- [x] security/forms/profile/activate
- [x] security/forms/profile/activatemultiple
- [x] security/forms/profile/deactivate
- [x] security/forms/profile/deactivatemultiple
- [ ] security/forms/rule/activate
- [ ] security/forms/rule/activatemultiple
- [ ] security/forms/rule/create
- [ ] security/forms/rule/deactivate
- [ ] security/forms/rule/deactivatemultiple
- [ ] security/forms/rule/duplicate
- [ ] security/forms/rule/getlist
- [ ] security/forms/rule/gettypelist
- [ ] security/forms/rule/remove
- [ ] security/forms/rule/removemultiple
- [ ] security/forms/rule/update
- [ ] security/forms/rule/updatefromgrid
- [x] security/forms/set/activate
- [x] security/forms/set/activatemultiple
- [x] security/forms/set/deactivate
- [x] security/forms/set/deactivatemultiple
- [x] security/forms/set/export
- [x] security/forms/set/import
- [x] security/group/setting/create
- [x] security/group/setting/getlist
- [x] security/group/setting/remove
- [x] security/group/setting/update
- [x] security/group/setting/updatefromgrid
- [ ] security/group/adduser
- [ ] security/group/get
- [ ] security/group/removeuser
- [x] security/message/create
- [x] security/message/read
- [x] security/message/remove
- [x] security/message/unread
- [x] security/resourcegroup/updateresourcesin
- [x] security/role/getauthoritylist
- [x] security/user/setting/create
- [x] security/user/setting/getlist
- [x] security/user/setting/remove
- [x] security/user/setting/update
- [x] security/user/setting/updatefromgrid
- [x] security/user/getrecentlyeditedresources
- [x] security/user/removemultiple
- [x] security/login
- [x] security/logout
### System
- [ ] system/filesys/file/remove (@exside)
- [ ] system/filesys/file/unzip (@exside)
- [ ] system/filesys/file/update (@exside)
- [ ] system/filesys/folder/create (@exside)
- [ ] system/filesys/folder/remove (@exside)
- [x] system/import/html
- [x] system/import/index
- [x] system/menu/create (@argnist)
- [x] system/menu/get (@argnist)
- [x] system/menu/getlist (@argnist)
- [x] system/menu/getmenu (@argnist)
- [x] system/menu/getnodes (@argnist)
- [x] system/menu/remove (@argnist)
- [x] system/menu/sort (@argnist)
- [x] system/menu/update (@argnist)
- [x] system/registry/register/read
- [x] system/registry/register/send
### Workspace
- [ ] workspace/providers/verify

**Comment by OptimusCrime** [comment]
What is the status on this?

**Comment by theboxer** [comment]
Few processors are still not class based...

**Comment by argnist** [comment]
Are there any of them that MODX is using?

**Comment by OptimusCrime** [comment]
No answer in two years. Closing this as I am unaware of any non-class based processors in the current code base. Prove me wrong and I'll reopen the issue.

@modxbot close
