### ISSUE TITLE
[2.3] Assign Namespaces to a Category

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#11448]
There are days in the life of a decent MODXpert, when he gets asked by a client to change some sort of "translation", "system setting" or whatever. That happens like every day. The usual response is (spoken out loud): "Sure, no thing." but honestly he/she thinks (silently): "C'mon, that's just SUCH a simple task that they should/could do themselves!". But clients cannot do this themselves because we don't dare to let them near "System Settings" or the "Lexicon(s)".

But what if Namespaces could be assigned to a Category? Wow, think of that: Clients changes those setting they are allowed to change, because they cannot break anything. They can now edit translations for those little asides headline you used in a carefully crafted chunk. Clients could change stuff just like they can change some of their user setting.

Just create a namespace e.g. "clientstuff" with an empty "core path" and an "assets path" pointing to "{assets_path}assets/clientstuff/" and a category "Client editable". Done. Now, when a client enters the "System Settings" he only sees the settings he is allowed to change. Same for the Lexicon: only the translations he should be able to do on his own are visible.

Yes, we all want that, right? Please comment and "vote" for this idea to become reality in MODX 2.3!

**Comment by Mark-H** [comment]
This was resolved in #12354
