### ISSUE TITLE
Add date joined to modUserProfile

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#11472]
I have asked for this a few times before.  It only makes sense for a a system with the power of our modUser / ACLs / Groups / etc to have access to when the account was created.

I understand this would not be retroactive, but it would really be nice in the future.

We have multiple dates for each resource, but only dates related to login and bans for users.

The blocked after could be used for subscription sites...  Etc

**Comment by Nuan8** [comment]
Has anything happened with this?

**Comment by wshawn** [comment]
As for me, I have had little time to pursue this. I got one of requests for xPDO knocked out and waiting for inclusion, but trying to get a multi million dollar site launched so I can relax a bit and get paid while knocking some of these out.
