### ISSUE TITLE
Upgrading 2.2 to 2.3 does not handle menu changes nicely

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#11473]
All items that existed before in the root (for example a custom "Actions" top menu, or in my case a "modmore" menu with all sorts of modmore-specific components) disappeared because the top menu only shows what's in the "topnav" menu group.

Dragging the item into the topnav did not work (no error, but did not stick either) and I had to recreate the top level item.

The upgrade also left behind the old menu items; perhaps the 2.3 installer should remove those automatically. 

Was upgraded from 2.2.13.

**Comment by matdave** [comment]
I noticed that when having a lot of "Custom" menu items, it really botches the upgrade process.  Basically it just decided to leave the menu in 2.2.X format, instead of converting all the actions to 2.3.X when a few extra custom "folders" and actions were put in the top nav.

**Comment by matdave** [comment]
it looks like moving custom actions into the “Components” group before running a 2.2.x to 2.3.x solves all the issues i’ve been having

**Comment by rthrash** [comment]
It sounds like that should be a part of the upgrade process—agree?

**Comment by matdave** [comment]
My theory didn't quite pan out. It still failed on me on a site without custom menus.  I have gone into "full paranoia" mode, and have a pretty length process that hasn't caused any more failures today.  Basically it involves manually editing the config file (I change databases on upgrade for lightning fast reverts), and running each step in an incognito window.

**Comment by Mark-H** [comment]
There's been a bunch of menu related fixes since I opened this issue so I'll go ahead and close it. The biggest issue I had was being unable of drag/dropping the orphaned menu items.
