### ISSUE TITLE
HTML5 cache issue in the manager

### ISSUE THREAD

**Issue by rtripault** [modxcms/revolution#11471]
It seems that when `manager_html5_cache` is activated, some issues are encountered (verified in Chrome 35).

I could summarize the issue as the cache is not cleared when some actions should have done so (ie. editing a chunk still shows the previous content after save).

Edit : #7340 might be related

**Comment by OptimusCrime** [comment]
Deprecated
HTML5 Application Cache has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Do not use it in old or new projects. Pages or Web apps using it may break at any time.

From #12869

In other words, this should no longer be an issue.

@modxbot close

**Comment by OptimusCrime** [comment]
@modxbot close
