### ISSUE TITLE
The color variables _colors-and-vars.scss is a mess

### ISSUE THREAD

**Issue by DESIGNfromWITHIN** [modxcms/revolution#11522]
I understand that during a project things get messy but for people that might want to change the theme these color variables are hard to work with.

### All colors as variables on top?

Then we need to use names like $blue-dark $blue-default $blue-light and use those as variables in the code.

    $gainsboro: rgb(240,240,240);

The name gainsboro rings no bells for me, only after checking I see it is light grey.
Also mixing hex color with rgb and rgba is confusing!

### We have a lot of grey color's that are almost the same but have different variables

I think it would be better to pick 2 or three grey variables and then adjust these if needed using darken or lighten using sass.

I like stuff like this:

    // color varibales
    $blue-default: #5ABCE5;
    $blue-light: lighten($blue-default, 20%);
    $blue-dark: darken($blue-default, 20%);

    // border colors
    $color-border: blue-default;
    $color-border-dark: blue-dark;
    $color-border-light: blue-light;

Will see if I have time to clean it up a bit.

**Comment by rtripault** [comment]
As some effort has been done that way (and we definitely need to keep going on), i'm closing this issue.

Thanks everyone
