### ISSUE TITLE
[2.3] Feature request - "add" button to every resource in tree

### ISSUE THREAD

**Issue by eighthday** [modxcms/revolution#11529]
The add button (below) is great on the context, but would be really useful if it was also present next to every resource, so you can create a new child without right clicking. 

![screen shot 2014-06-17 at 12 33 29](https://cloud.githubusercontent.com/assets/4104767/3299497/4384c63c-f613-11e3-857a-195615cd74ea.png)

Perhaps the button should only be show on mouseover?

**Comment by inreti** [comment]
+1 for that. and also: have a setting (per resource? template?) which allows to choose which templates the user is allowed to add as new child. So we do not "Add child _resource" and choose templates afterwards, but have something like "Add blog article", "Add Foto-Gallery", "Add basic page" according to the actually allowed templates _there_

**Comment by alroniks** [comment]
PR is merged, so closing this issue.
