### ISSUE TITLE
Make Content Field Available to FC

### ISSUE THREAD

**Issue by StevenMorgan** [modxcms/revolution#11525]
It would be great to be able to move the Content field via FC rules. 

There are several fields that, as I understand it, cannot be moved using FC rules. It would be great to overcome this for 2.3. 

Why should this make the 2.3 cutoff?

Several of the common criticisms levelled at MODX Manager UI relate to the layout / volume of the core Manager fields. If these can be "tidied up" or organised via FC this will go someway to addressing the concern without openning up major debates on what a revised Manage should / should not include. 

Use case:

E.g. Personally I would move Content to a tab to stop it appearing in every Tab, and potentially move some of the other core fields under Settings (ideally creating sub tabs as with TV categories). 

I'm sure there's a good reason why these fields are not currently included in FC, but I feel it worth solving for 2.3.

**Comment by rtripault** [comment]
Somehow similar to #10505 so closing as duplicate.

Feel free to comment/reopen if needed.
Thanks

#modxbughunt
