### ISSUE TITLE
2.3 Manager: Missing site information

### ISSUE THREAD

**Issue by enigmatic-user** [modxcms/revolution#11558]
Mark Hamstra (Mark-H) asked me to open a new issue for this (I erraneously posted this in [the thread where he presented the new Manager design] (https://github.com/modxcms/revolution/pull/11406#issuecomment-46794017) because I thought this was when the problem was introduced), so here it is:

As stated in the other thread, I just noticed that the site's name and the MODX version have completely vanished in the MODX 2.3 Manager. In my working copy of MODX 2.3 (downloaded a few days ago from http://modx.com/download/nightlies/) even the user's name has gone.

That's really, really bad. I'm administrating many of the sites I built for my customers, and it's important for me to be able to quickly see which site's Manager I'm looking at, whether I'm logged in as admin or as end user and whether the MODX version is the current one or if an update is required. And I don't think I'm the only one working with a bunch of MODX installations.

If the current state is the preferred one: No problem - as long as there's an option in the system settings that allows me to restore the top area that used to contain the mentioned information (with a look and feel adapted to the new design).

Mark also asked for ideas on how to integrate that into the new design. I could imagine something like this:

![modx_23_site_info_top_bar](https://cloud.githubusercontent.com/assets/434408/3354143/3a87d864-fa99-11e3-831f-c7b374fd006d.png)

Please don't tie me down to details, I didn't have much time for it... Maybe the text could be a little bit darker, the margins a little bit smaller or whatever. If someone has a better idea, please feel free to post it here.

**Comment by k9dug** [comment]
Anything happening on this issue? It's still a bit of a pain being faced with relatively anonymous manager screens, especially when two or more are open and one is accustomed to having this info at fingertips.

Can I suggest a combination of the following: 

1. A permission/system-setting as Mark-H suggests (this means it can be hidden from client users). Default to 'on'.

2. All the info in a slide-down header bar: have it something like the design by enigmatic-user at the start of this post (functional, easy to access, like it was), but only visible when you slide your cursor up to the top of the screen (which would maintain the nice neat header for StevenMorgan et al).

In fact, there could just as easily be a System Setting to switch it between permanent and slide-down.

Finally, getting it out in the next version would be great!

**Comment by OptimusCrime** [comment]
I'd like to bump this as well.

**Comment by Lefthandmedia** [comment]
me too, just start with adding the version to the footer.

**Comment by whit537** [comment]
:+1:

I just had to read the source for [`getVersionData`](http://rtfm.modx.com/revolution/2.x/developing-in-modx/other-development-resources/class-reference/modx/modx.getversiondata) and find that it was looking at `core/docs/version.inc.php` in order to determine the version number of this MODX 2.3.3 install I've inherited. I'm also working with a 2.2.15 instance, where of course the version number is easily discoverable in the web UI.

**Comment by OptimusCrime** [comment]
This is an important issue, but is exactly the same as #11576. Closing in favor of that because it is more recently updated and progressed.

@modxbot close
