### ISSUE TITLE
Save and Add Another resource removed in 2.3?

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#11567]
I can see why the save and close button was removed but the save and add another would be frequently used if it weren't so obscure to find in 2.2.x.  Adding resources over and over within a container is very clumsy being two levels deep in the resource tree menu.  

I would make the save button also have a dropdown to select "Save and Add Another"  The click and release action on the save button would be save and leave open, the click and hold focus action would open the drop down so the user can select Save and Add Another.

**Comment by alroniks** [comment]
Close it as it duplicates new one #13050 but with more straight description.
