### ISSUE TITLE
2.3 Site Footer (Site name and version)

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#11576]
As you know we've dropped the Site name and MODX version number from their usual position (top left).

While not an issue for editors that work on a single site, some of us work on more than one site at a time. I incorrectly pasted content into a completely different manager on more than 1 occasion :-/

My proposal is to create a simple footer in the manager. The footer and the rest of the manager can be seperated by a 1px grey line. Doesn't need anything more complicated than that.

![footer-version](https://cloud.githubusercontent.com/assets/1786476/3388780/5877d136-fc8c-11e3-8ebf-c47b28a416e9.png)

**Comment by rthrash** [comment]
What would everyone think about just the version number to the right of the help  menu icon? The "-pl" could even be trimmed for folks running a stock MODX distro. E.g., something along the lines of _2.3.3_ or _2.3.3-adv_ (if you were running the advanced version)?

**Comment by rthrash** [comment]
I would include the full details as first item under the help menu, too, per Christian's last screenshot earlier:

![image](https://cloud.githubusercontent.com/assets/234237/8071158/f11d7e74-0ecc-11e5-9fed-46f2d5c89952.png)

**Comment by OptimusCrime** [comment]
I like @christianseel 's much better. The whole idea is to make it easy to spot, right?

**Comment by rthrash** [comment]
That's the point of putting the basic version number (which you only care about really if someone specifically asks or you already know you're running MODX) in the navbar.

**Comment by OptimusCrime** [comment]
True. +1 add it and close this oooooooold ticket :)

**Comment by OptimusCrime** [comment]
This implemented in 2.4. Any objections on closing this ticket?

**Comment by Alroniks** [comment]
:+1:  for closing

**Comment by OptimusCrime** [comment]
@modxbot close

Feel free to reopen
