### ISSUE TITLE
[2.3] Manager TopNav Menu Icons a Little "Unorthodox"

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#11579]
Hi there,
call me picky but I don't get the logic of the new manager topnav icons: The main elements have an "arrow down" while it is obvious clear that they are "buttons". The menu items inside a dropdown WITH children don't have any icon, which is obviously not clear. – To be honest, it is only "Reports" which would need an icon like "arrow right".

Maybe the whole topnav menu could loose some weight if ALL arrow would be dropped?! We don't need them!

![image](https://user-images.githubusercontent.com/458619/51240764-b54ef300-197c-11e9-9426-b4841664e638.png)

The arrows in the RED circles could all be dropped (and also all the arrow in the right part of the top-menu bar).
Inside the GREEN circles "arrows to the right" would be nice to have.

cheers
Oliver

**Comment by Ibochkarev** [comment]
Actually for versions 2.6.x, 2.7.x and 3.x

**Comment by JoshuaLuckers** [comment]
This will be fixed by the redesign in MODX 3.
Related PR #14292
