### ISSUE TITLE
[2.3] Drop Elements Folder "Icon Line" or make it "Scrollfix"

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#11585]
The icon line at the top of the "Elements" folder is redundant because new elements can be created by the (+) icon. So the whole line could be removed (@rthrash agrees with me here), giving us more space.

The line could stay if it would be "scrollfix" – to be visible all the time even with looong element lists. Right? ;-)

cheers
Oliver

**Comment by alroniks** [comment]
I am not sure that they should be deleted. Saving the 30px of space is not solving the issue drastically but some people still may use this feature. And removing them does not give us any advantages.
I would close it. What do you think @rthrash @Mark-H @Jako

**Comment by Mark-H** [comment]
I don't have a strong opinion on this. This dates back from an older design so perhaps it needs to be revisited for 3.x, but that could be a new issue too.

**Comment by alroniks** [comment]
I've checked it in 3.x, there is no any toolbar in Elements, so it seems solved in MODX 3. 
![](https://i.imgur.com/KcdqfHa.png)

The removing it from 2.x does not make sense, so I am closing the issue.

Feel free to reopen.
