### ISSUE TITLE
Bug with JSON in modContextSetting

### ISSUE THREAD

**Issue by bezumkin** [modxcms/revolution#11611]
In current version of MODX distribution 2.2.14 we have such strings in the file /core/model/modx/modcachemanager.class.php and method generateContext(), that breaks JSON in context settings:

``` php
foreach ($matches as $match) {
    if (array_key_exists("{$match[1]}", $contextConfig)) {
        $matchValue= $contextConfig["{$match[1]}"];
    } else {
        $matchValue= '';
    }
    $v= str_replace($match[0], $matchValue, $v);
}
```

But in repository it [was already fixed](https://github.com/modxcms/revolution/commit/d68d7da09632af8770774e521c58d3d837eacb4f) a long time ago.

``` php
$matchValue= '';
foreach ($matches as $match) {
    if (isset ($this->modx->config["{$match[1]}"])) {
        $matchValue= $this->modx->config["{$match[1]}"];
    } else {
        /* this causes problems with JSON in settings, disabling for now */
        //$matchValue= '';
    }
    if (!empty($matchValue)) {
        $v= str_replace($match[0], $matchValue, $v);
    }
}
```

I think the old version of the file got somehow in a new distro.

**Comment by pixelive** [comment]
Tried JSON in both system settings as context settings and it both works. (and cached as well)

**Comment by rtripault** [comment]
So closing.

Feel free to comment/reopen if needed.
Thanks
