### ISSUE TITLE
New package update indicator not working

### ISSUE THREAD

**Issue by beau-gosse** [modxcms/revolution#11621]
I'm not sure if this issue has already been reported, but I thought I should point it out.

As you can see in the first image below, MODX 2.3 didn't detect that a package (Collections) was outdated. The 'Check for updates' button didn't find the update either. But a quick search of the same package revealed that a newer version was available.

![modx2-3-updater-issue](https://cloud.githubusercontent.com/assets/509451/3469973/8c498958-02b5-11e4-8fb4-436b63f674b9.jpg)

![modx2-3-updater-issue-2](https://cloud.githubusercontent.com/assets/509451/3469974/93a5a47a-02b5-11e4-89fd-c23f1c3d1b7f.jpg)

**Comment by whitebyte** [comment]
So, is this still an issue? Seems to work well in latest, mmm?

**Comment by rtripault** [comment]
As Mark wrote, this appears to be an infrastructure issue (package provider), so closing.

Feel free to comment/reopen if needed.
Thanks
