### ISSUE TITLE
Could not create Resource Group using cloud Manager in IE 11

### ISSUE THREAD

**Issue by vholford** [modxcms/revolution#11631]
My Modx cloud URL is http://c0758.paas1.tx.modxcloud.com/manager/
Using Security >  Resource Groups

Here is what I got;
![resource groups](https://cloud.githubusercontent.com/assets/6969904/3485125/68bb6eae-03c6-11e4-988f-1c13d4894ead.png)

Tried it again in Fire Fox;
![resource_groups___empyream_challenge_-_cluster_wars](https://cloud.githubusercontent.com/assets/6969904/3485127/a33f915e-03c6-11e4-9a13-d643830ad031.png)

This should be working in IE 11 Right?

**Comment by whitebyte** [comment]
@vholford , is it stll actual for current 2.3.2?

**Comment by TheBoxer** [comment]
Closing for long inactivity. Feel free to reopen with more details.
