### ISSUE TITLE
[2.3] Manager Theme: Uberbar color contrast too low

### ISSUE THREAD

**Issue by electrickite** [modxcms/revolution#11645]
The color contrast between the background of the uberbar search field and the background color of the menu bar is too low to meet WCAG AA requirements. WCAG AA requires a contrast ration of 4.5:1, the current color scheme provides 1.48:1.

See http://webaim.org/resources/contrastchecker/ 

I am partially color blind and it is very hard to see the dark search field on the dark menu bar background or the "Search" text hint.

Related to #11608 but I wanted to call out the accessibility issues produced by low contrast color choices.

**Comment by whitebyte** [comment]
Shouldn't this issue be moved to https://github.com/modxcms/a11y?

**Comment by OptimusCrime** [comment]
Yes it should

**Comment by OptimusCrime** [comment]
Moved to modxcms/a11y#37 , closing

@modxbot close
