### ISSUE TITLE
Panel Descriptions

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#11653]
There are descriptions on some panels which feature a grey background.  I understand their purpose but think they have no value to the user interface and add a visual noise.

Proposing dropping these. What do you think?

![panel-description](https://cloud.githubusercontent.com/assets/1786476/3508449/73cba206-068b-11e4-9507-3ade97f1fc6e.png)

**Comment by OptimusCrime** [comment]
Closing this as it celebrated 2 years not long ago. I don't think the gray is going anywhere and several of us likes how the gray color makes it stand out against the white box.

Feel free to comment or reopen this issue.

@modxbot close
