### ISSUE TITLE
Feature request: Copy complete file path from Media Browser

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#11666]
The contextual menu on the media browser should have the feature to copy the complete path to the file to your clipboard so you can paste it anywhere in the manager you need it that does not allow drag and drop.  Currently users have to guess the path to the file which may be hidden if using a pre-defined media source.  The media source base path (from site root) should also be shown somewhere so users better understand where the files are stored.

**Comment by alroniks** [comment]
PR is merged, closing as solved.
