### ISSUE TITLE
Feature request: link to snippets, chunks & TVs from resource window. 

### ISSUE THREAD

**Issue by BigBlockStudios** [modxcms/revolution#11683]
You know what would be insanely handy? If whenever a snippet, chunk or TV appeared in the body of a resource [in the manager] it was linked so that you could open and edit it in a new tab/window. 

Also search for chunks/snippets etc....

**Comment by rtripault** [comment]
I guess http://modx.com/extras/package/moddevtools is what you are looking for. So closing.

Feel free to comment/reopen if needed.
Thanks
