### ISSUE TITLE
[2.3] Misplaced slide-in/slide-out button of Resource tree when scrollbar is visible 

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#11751]
The slide-in/slide-out button of Resource tree is misplaced when scrollbar is visible + it overlaps the scrollbar. Also the padding between tree border and button changes.

![screenshot 2014-07-20 23 12 01](https://cloud.githubusercontent.com/assets/876737/3638569/33d6bcb8-1053-11e4-8013-f6b1a209fcf7.png)

**Comment by alroniks** [comment]
It seems issue solved by just merged pr.
