### ISSUE TITLE
createdby Select Field in Standard Resource Type

### ISSUE THREAD

**Issue by hephaestoskin** [modxcms/revolution#11766]
The availability of a dropdown select field to set <i>createdby</i> setting for a resource drastically simplifies and speeds the creation of blogs using tools other than Articles (ie Grid Class Key). This is the only impediment to not using Articles for blogging purposes that can't easily be gotten around.

**Comment by alroniks** [comment]
Closing it a favor to #12305 as there are the more detailed description and discussion.
But +1 for implementing that, it would be very useful.
