### ISSUE TITLE
Recolor Manager theme to match new MODX logo colors

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#11776]
Now that here is a new nice colorful MODX logo, wouldn't it be right time to overthink the washed out colors of the 2.3 theme? In special the petrol color is outdated.

Would be nice to have only 2 main colors : 

- blue accents for tabs and other small elements like form element borders
- green for main buttons

**Comment by OptimusCrime** [comment]
Due to lack of feedback I'll close this for now. Feel free to repoen if you have any feedback.

@modxbot close
