### ISSUE TITLE
No scroll bar in CMPs that return plain HTML

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#11798]
This breaks SiteCheck.

Sitecheck just returns a long log with many lines of HTML, most of which are off the bottom of the screen and can't be scrolled to. This happens in multiple browsers.

**Comment by Mark-H** [comment]
In 2.5 there's a new type of controller will do the wrapping necessary for using straight up HTML in controllers modxcookbook.com/customize-manager/cmps/cmp-made-easy.html
