### ISSUE TITLE
Setting for default_duplicate_publish_option

### ISSUE THREAD

**Issue by Pont** [modxcms/revolution#11818]
This setting has three possible options: publish, unpublish and preserve. The options are not translated. Should they be?
Since there are three fixed options, should this be a dropdown instead of a text field?

**Comment by Ruslan-Aleev** [comment]
In the russian version there is a translation of the description of the options (see the picture below), the options themselves should not be translated.
However, the implementation of the drop-down list is a more global task, now in the system settings there are only drop-down lists with "Yes / No".

**It would be nice to make a separate issue about the drop-down lists.**
So there is not a bug, but an improvement.

![setting_info](https://user-images.githubusercontent.com/12523676/51832579-85093c00-230e-11e9-81b9-84dd4a1bab8b.png)

**Comment by Ibochkarev** [comment]
These parameters are indicated in the description and they have a translation.

![изображение](https://user-images.githubusercontent.com/2138260/113410554-86928b00-93d5-11eb-8808-c78a41d0ae76.png)

![изображение](https://user-images.githubusercontent.com/2138260/113410639-b346a280-93d5-11eb-8665-a2cad749b23f.png)
