### ISSUE TITLE
Media Source ./ to image path

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#11830]
Using a simple Media Source with path and URL set to relative 'assets/images/'

When first selecting an image, the path is fine - image1.jpg and until the resource is saved, the thumbnail is also fine. But when the image is saved, it loses the thumbnail.

If you change the image, it adds ./ to the path - ./image2.jpg

phpthumb is failing to find the image:

[2014-07-27 00:39:09](ERROR @ /connectors/system/phpthumb.php) phpThumb was unable to generate a thumbnail for: /paas/c1327/www/core/cache/phpthumb/jonline.sottwell.modxcloud.com__src9ca6fcfedb26085c674b36d08d11264b_par5df3dad6621628fd102555d4b8000f6e_dat0.jpeg
[2014-07-27 00:39:09](ERROR @ /connectors/system/phpthumb.php) Error outputting thumbnail:
OutputThumbnail() failed because !is_resource($this->gdimg_output) in file "phpthumb.class.php" on line 572

**Comment by JayCarney** [comment]
I've noticed an odd behaviour, I'm having this issue on 2.4.3pl.
Selecting an image from the root of the media source does prepend `./`, but If I change to a folder within the media source, select an image, change back to the root and select the image the `./` isn't prepended. Not sure if this information helps

**Comment by Fi1osof** [comment]
+1

**Comment by Bruno17** [comment]
I think this is related to https://github.com/modxcms/revolution/issues/12625
where I had posted a possible fix. Would this fix it for you, @Fi1osof ?

**Comment by Fi1osof** [comment]
@Bruno17 it shoud not be $dir = str_replace('./','/',$dir);
Need $dir = str_replace('./','',$dir);

**Comment by Bruno17** [comment]
what happens with `$dir = str_replace('./','/',$dir);`
did you try it?

**Comment by sottwell** [comment]
I would presume it would replace the “./” with “/” which is not at all what is wanted. At least the "./" indicates "this directory", and not "root directory".

**Comment by Fi1osof** [comment]
Yes, this should not be the root directory. It will be concatenated with media-source root dir.

**Comment by sottwell** [comment]
If you click on the folder in the left tree before selecting the file, it doesn't prepend the "./" to the file path. I never was able to find where that prepending took place.

**Comment by Ibochkarev** [comment]
Thanks for your issue. This was fixed in #13778
