### ISSUE TITLE
Active Session Count on Flush All Sessions Dialog

### ISSUE THREAD

**Issue by benjaminglick** [modxcms/revolution#11842]
In the manager, if you need to flush all sessions, it would be great to see if there are any other active sessions before hitting okay.  If I could see, "There are 0 other active users." that would remove a lot of trepidation from hitting that button.  Similarly, if I saw "There are 10 other active users.", then I might choose to wait an hour or two for fewer users.

To do this, there would probably have to be some way of timestamping the last activity or page request by a user.  It might be a measure of active users in the last 10-20 minutes.  The main concern is wanting to avoid logging out a user who is about to complete a sale or some other desired action.

**Comment by bezumkin** [comment]
I think we can close it @gpsietzema

**Comment by gpsietzema** [comment]
Closing this. If you feel this was wrong, please re-open it.

@modxbot close
