### ISSUE TITLE
Revert to Previous Version of Resource for End-Users

### ISSUE THREAD

**Issue by benjaminglick** [modxcms/revolution#11841]
It would be great to have the option to revert to a previous version of a resource.  I would envision something similar to the caching system, but saving a history, rather than the current item.  This would prevent the database from becoming bloated by storing old versions of a resource.

The main concern here is the end-user.  There is the possibility that they can make a change that they have no clue how to fix, and they really need an undo button on changes they make.  

Wordpress is helpful in storing past versions, but they save them in the database, which bloats the database, and thus slows down performance for active pages.

If a backup of the current resource was saved to a file before recording changes, then it could easily be pulled back if the user needed to revert to the last version.  Again, the actual code would probably be very similar to the current caching system.  We would be storing backups of pages instead of a rendered image of the current one.

**Comment by alroniks** [comment]
I agree with Mark, that it's already can be done by VersionX. So no need to bring it into the core.
But, VersionX stores data in DB, not in files. But also I don't agree about reimplementing cache system. Cache is a cache, it can be destroyed at any time when versions should be stored always. So I am closing this one, but if you have new arguments, let's discuss.
