### ISSUE TITLE
Media Browser: "MODX Browser" button not helpful at all

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#11840]
When you open the media browser window from a file or image TV, there is that toolbar button "MODX Browser", which in 2.2.x opened another window with a more "liberal" (e.g. source combo visible) instance of the media browser...already in 2.2.x it was quite pointless, as a selected file in that second browser didn't get written into the TV the first media browser window was opened from, the selected file/path just get's lost in the nowhere, or I'm incapable of using it (anybody can effectively chose a file / image for the TV from the second media browser window?).

I'm talking about that button:
![bildschirmfoto 2014-07-28 um 13 27 44](https://cloud.githubusercontent.com/assets/445501/3719828/4da1dd7e-164a-11e4-8a50-67ef6b7ec130.png)

In 2.3.x that button doesn't even do anything else than throwing a JS error because node.elNode is undefined in the method for opening the second window (loadFileManager() in manager/assets/modext/widgets/modx.tree.directory.js L393) which is caused by the fact, that no rootId is specified for the tree, seems to be necessary since 2.3...if you specify a rootId: '/', then the root shows (and the error goes away), no matter if rootVisible is true or false (all the other trees have in fact rootVisible: false when you log them...don't know why this property is there though =D)

**to the point**: is there any value added by this button or can I just remove it completely in the upcoming media browser PR?

**Comment by rtripault** [comment]
Closing as this appears to be solved in current 2.5 branch.

Feel free to comment/reopen if needed.
Thanks
