### ISSUE TITLE
Image preview when hovering a file in files tree - should only show thumbnails

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#11852]
Hovering large sized images in files tree should not display full sized image previews. It would be better to only show thumbnails.

**Comment by RinzeVanDerBrug** [comment]
Can not reproduce this.

When hovering large sized images in the files tree in MODX 2.5.5, a thumbnail shows up: 
![thumbnail](https://cloud.githubusercontent.com/assets/25863377/23550594/1dc68078-0012-11e7-8439-aa6b8a9dffc0.jpg) 

So I guess this issue is outdated and can be closed. #modxbughunt

**Comment by gadgetto** [comment]
I can confirm this - problem gone! As creator if this issue I close it!
