### ISSUE TITLE
Updated search position (includes reintroduction of site name/version).

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#11850]
I really like how OSX handles the search (screengrab below). 
• User clicks on the search icon
• Search "drawer opens"
• Search results displayed under this.

![osx-search](https://cloud.githubusercontent.com/assets/1786476/3749688/81af7c84-17ee-11e4-973e-e847ebe91c00.png)

The benefits of this are primarily that the search field can be as long as required without affecting other menu items. In MODX 2.3, the search expands which can affect custom menus and it also has knocked the sitename and version off the manager. 

## How this might work in MODX 2.3 

We tweak the current search to mimic the OSX drawer style but displaying just the icon and no search field by default. Clicking icon reveals drawer with search field and results. 
Happily, this allows space for us to reintroduce the sitename / version too. Again, we're not restricted by the search field. Granted, its an extra click to reveal the search field but I think benefits outweigh it.

Mockup below is for illustration. I know it's not pretty!

![search-v1](https://cloud.githubusercontent.com/assets/1786476/3749723/e1c13f36-17ee-11e4-9a1f-632806d8e9d9.png)

## Alternative approach 
Alternatively, I think a neater approach would be to add a search icon in a tab beside the Resources, Elements and Files tabs. The search field sits just underneath this and we categorise all the results within the existing Templates, TVs, Chunks etc toggle bars. We'd add an extra one for Resources and remove the plus and refresh icons. But as a quick mockup. I think this is a very natural fit.

![search-v2](https://cloud.githubusercontent.com/assets/1786476/3749812/a845ddc4-17ef-11e4-9822-bf931db4c2a4.png)

**Comment by OptimusCrime** [comment]
This implemented in 2.4. Any objections on closing this ticket?
