### ISSUE TITLE
Installer can't find core path when core is moved/renamed

### ISSUE THREAD

**Issue by Pont** [modxcms/revolution#11888]
When doing an upgrade of an advanced install with the core moved/renamed the installer doesn't set the core path correctly and thus displays the findcore page. This could be avoided if the installer tried to use the config.core.php in the websites root. Something like this in `/setup/includes/config.core.php` solves the issue.

``` php
if (!include(MODX_INSTALL_PATH . 'config.core.php')) {
    define('MODX_CORE_PATH', MODX_INSTALL_PATH . 'core/');
    if (!defined('MODX_CONFIG_KEY')) define('MODX_CONFIG_KEY', 'config');
}
define ('MODX_SETUP_KEY', '@advanced@');
```

**Comment by Mark-H** [comment]
Fixed in #14304
