### ISSUE TITLE
2.3.1 Error log is empty.

### ISSUE THREAD

**Issue by darkarchon** [modxcms/revolution#11892]
Error log is empty then U tried to read through view event.
But the thing is that the log is not empty.
U can see file info by filemanager(size, dates) but the filemanager also can't view, empty.

The trick is that if error log had some of Cyrillic symbols his gone(can't view).
If U delete them, from it, then U can read it.

Env.:
MODx version 2.3.1
php 5.3.27

**Comment by bezumkin** [comment]
I believe we already fixed it [here](https://github.com/modxcms/revolution/pull/13560)

@gpsietzema

**Comment by gpsietzema** [comment]
@modxbot close
