### ISSUE TITLE
2.3.1 Quick update, can't edit a date publishedon

### ISSUE THREAD

**Issue by darkarchon** [modxcms/revolution#11891]
Can't change the date of **publishedon** in quick update window.
The date doesn't change.
On regular resource editing everything is fine.

Sometimes I've get an error

> (ERROR @ /connectors/index.php) modSystemSetting: Attempt to set NOT NULL field editedon to NULL

But, no one of resources has not been updated.

Env.:
MODx version 2.3.1
php 5.3.27

**Comment by OptimusCrime** [comment]
Confirmed. I can take a look at this.

**Comment by Flowan** [comment]
Confirmed this still does not work in 2.5.x #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point @Flowan

**Comment by bezumkin** [comment]
I can't confirm this bug, everything works as expected in MODX 2.6.1

![update](https://user-images.githubusercontent.com/1257284/36031522-4c19337e-0dab-11e8-9954-b04c169d23ef.gif)

**Comment by gpsietzema** [comment]
@modxbot close
