### ISSUE TITLE
[2.3] Intermediate upgrades not being performed

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#11906]
I've seen many reports now of people having trouble after an upgrade to version 2.3  and jumping over intermediate versions. In every case, one or more of these previous upgrade tasks did not happen. 
1. Creation of the cache_refresh_idx index in the modx_site_content table
2. Creation of the modx_extension_packages table
3. Creation of the 'name' field in the modx_context table
   
   4.? Creation of the extension_packages System Setting

I'm not sure if #4 fits the pattern, but there are definitely upgraded sites where that setting is missing.

**Comment by amdbuilder** [comment]
Do you happen to know what host(s) are being used when the upgrades are failing?  I'm wondering if the upgrade process exceeds the resource limits with some hosts.

**Comment by BobRay** [comment]
I don't, but it's an interesting question. It depends on when those events occur in the process (early or late).

**Comment by alroniks** [comment]
I hope people already upgraded their sites to the latest version (after the last news, they had to do it) and investigate issue before 2.3 does not make sense. The reason I guess was a missed proper upgrade script.
So I am closing this one as outdated.
