### ISSUE TITLE
problems in modx with php 5.4

### ISSUE THREAD

**Issue by ameshkov** [modxcms/revolution#11909]
Can`t access to manager in modx 2.3.1 with php 5.4. With php 5.3 it`s work normal.
Error:
The username or password you entered is incorrect. Please check the username, re-type the password, and try again.

I also try to install modx 2.3.1 with php 5.4 - don`t work - problem with mysql:
Connecting to database server:  
Could not connect to the existing database for upgrade. Check the connection properties and try again.

Problem in modx 2.2.15 with php 5.4:
Fatal error: Call to a member function get() on a non-object in /home/a/ameshkov/wikihow.su/public_html/core/model/modx/modmanagerresponse.class.php on line 41

**Comment by amdbuilder** [comment]
This sounds like an environment specific issue.  Could you tell us more about your hosting environment?  It's possible there are more changes required when you switch between php versions.

The error messages above have me questioning if you need to reset your database password after switching versions.

**Comment by Alroniks** [comment]
I agree with @amdbuilder about environment issue. I have the running MODX on 5.4 and 5.5 - all works fine.

**Comment by rtripault** [comment]
There's been an issue with setup & op caching in previous versions, during setup, which caused the user not to be created. This has been resolved, so closing.

Please, feel free to comment/reopen if needed.
Thanks
