### ISSUE TITLE
Hidden system settings

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#11917]
This is useful for components that want to use the benefits of $modx->getOption() but not give the users the ability to change the value in the system settings. The setting can be handled in the component for example.

**Comment by SoftAlex** [comment]
:+1:

**Comment by exside** [comment]
+1

**Comment by zaigham** [comment]
Maybe this is related? https://github.com/modxcms/revolution/pull/12354

**Comment by OptimusCrime** [comment]
@theboxer does you pull #12354 support this feature?

**Comment by theboxer** [comment]
Yes, you can create a namespace, disable an access for certain users and add system settings to it. Users without permissions will not be able to see it.

**Comment by OptimusCrime** [comment]
Is this something that is documented somewhere? Something that could be added to the RTFM?

I guess this feature means that this issue + duplicates can be closed?

**Comment by theboxer** [comment]
No there's no documentation for it...

And yes, I suppose it can be closed.

**Comment by rtripault** [comment]
So closing!
Feel free to comment/reopen if needed.
Thanks

#modxbughunt
