### ISSUE TITLE
[2.3] Console OK button should not be green when inactive

### ISSUE THREAD

**Issue by jkenters** [modxcms/revolution#11928]
I noticed this while updating packages. The inactive OK button also has a green color. A different one than the active color, but to me it still looks like it's already clickable. Personally I would prefer a real grayed out button instead of a colored one to prevent any confusion.

**Comment by Mark-H** [comment]
Still seems to be the case in 2.x.. it's faded, and not clickable, but can see how that might be confusing.

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Mark-H

**Comment by alroniks** [comment]
I don't agree that it should be grayed. Fading and disabling of buttons well-established user experience across other systems. And such behavior exists not only in the console but also in other places in MODX. So I am closing as `won't fix` but, please, do not hesitate to reopen.
