### ISSUE TITLE
[2.3] Strange focus problem on clickable elements (especially buttons) in Google Chrome

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#11954]
Using Google Chrome there seems to be a problem while releasing the focus of a button element (and other similar elements).

**Steps to reproduce this:**

1) open Menu Manage / Users (as a sample)
2) click on the **Clear filter** button (on the button text) - the button background gets blue
3) move mouse cursor away

Normally the focus of the button should release and the background color of the button element should change back to white, but most times it stays blue until you click somewhere outside the button element.

If you don't click on the center of the button element (near border) it mostly works as expected.
This also happens on other button-like elements.

No problem in: Safari, Firefox, Opera
Couldn't test in IE...

**Comment by Finetuned** [comment]
"I'm going to try and fix this today."
