### ISSUE TITLE
Upload fails in IE9. Filesize fails to detect.

### ISSUE THREAD

**Issue by bitwolfe** [modxcms/revolution#11961]
Ran into this issue with a client that only has access to IE9 on his work computer. The upload fails (as in an error is given) because the filesize cannot be determined. The actual filesizes of the files below are 33KB - 1.50MB while the max upload size in MODX and PHP is 150MB. Everything works fine in IE10+ or other browsers. Doesn't seem to be limited by filetype, nor filenames with special characters.

Running MODX 2.3.1 on PHP 5.5.

![modx_upload_fail](https://cloud.githubusercontent.com/assets/670705/4160557/eae28598-34bd-11e4-81dc-ec4bbd887fcd.png)

**Comment by herooutoftime** [comment]
Just bumped into this issue as well. Did somebody came up with a solution? @fractalwolfe @rtripault

**Comment by herooutoftime** [comment]
@rtripault @fractalwolfe I came up with another solution as Flash fallback isn't working as expected.

Furthermore I had to change some security setting regarding ActiveX. See attached screenshot.

![ie9-security-settings-overrule](https://cloud.githubusercontent.com/assets/1781080/5759065/25128c52-9ccb-11e4-9f84-9d0abd21ff85.png)


```
var api = {
    ...
    isIE: function() {
        var myNav = navigator.userAgent.toLowerCase();
        return (myNav.indexOf('msie') != -1) ? parseInt(myNav.split('msie')[1]) : false;
    }
}

// IE < 10
if(api.isIE() < 10) {
    var myFSO = new ActiveXObject("Scripting.FileSystemObject");
    var filepath = file.name
    var thefile = myFSO.getFile(filepath);
    var size = thefile.size;
    file.size = size;
}
```

It's a quick fix but it works.

**Comment by OptimusCrime** [comment]
IE9 is today only supported by Windows Vista SP2 (http://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/).

As the browser is nearing EOL, I suggest closing this as a wontfix and encourage manager users to upgrade their browsers instead.

Any objections?

**Comment by OptimusCrime** [comment]
I guess not!

@modxbot close
