### ISSUE TITLE
Large file uploads time-out in the file manager - turn on file chunking

### ISSUE THREAD

**Issue by wandering213** [modxcms/revolution#11988]
Large files that take a long time to transfer time out and lead to an internal server error. A temporary work around is to increase the max_input_time to a larger value.

If this isn't a bug, can the upload manager be updated to chunk large files that are being uploaded?

**Comment by OptimusCrime** [comment]
`max_input_time` is something that is configued on system basis, not application. MODX can not override the system defaults (as far as I know). If you want upload of such big files to work; configure Apache/nginx to support this. There is no limitation or hard coded values in MODX that limits this.

I am going to close this as we have seen no interest or further comments on the matter in years.

@modxbot close
