### ISSUE TITLE
syncsite checkbox configurable

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#11980]
It would be nice if the syncsite chechbox state were configurable instead of hard-coded...

```
'hidemenu' => $this->context->getOption('hidemenu_default', 0, $this->modx->_userConfig),
'published' => $this->context->getOption('publish_default', 0, $this->modx->_userConfig),
'searchable' => $this->context->getOption('search_default', 1, $this->modx->_userConfig),
'cacheable' => $this->context->getOption('cache_default', 1, $this->modx->_userConfig),
'syncsite' => true,
```

**Comment by whitebyte** [comment]
Since related PR is merged, i suggest this issue should be closed? Pinging @sottwell

**Comment by sottwell** [comment]
It also needs to be done in the update processor
manager/controllers/default/resource/update.class.php line 122
	
	        $this->resourceArray['syncsite'] = isset($this->resourceArray['syncsite']) && intval($this->resourceArray['syncsite']) == 1 ? true : $this->context->getOption('syncsite_default', 1, $this->modx->_userConfig);
