### ISSUE TITLE
MODx not published resources available according to schedule

### ISSUE THREAD

**Issue by Nik-ADA** [modxcms/revolution#12018]
Hi, there was a question. There are groups of users, administrators and managers. Resources are published by the administrator on a schedule published normally. Managers provide the resources the same schedule but they are not published when it comes to the time of publication.

What could be the problem that it is not added to the right managers, or a system bug.

MODX Revolution 2.2.13-pl (advanced)

**Comment by mcnickel** [comment]
@rtripault Additional information missing. Seems not to be an issue anymore. Sounds like  ACL-missconfiguration. Could probably be closed.
#modxbughunt

**Comment by rtripault** [comment]
Thanks @mcnickel let's go for a close then.
As usual, feel free to comment/reopen if needed.

Thanks

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @mcnickel
