### ISSUE TITLE
Listbox (Multi-select): In Webkit, selected items are obscurred by "x" button

### ISSUE THREAD

**Issue by JamesBurgoon** [modxcms/revolution#12061]
Modx 2.3.1:
In Safari/Webkit, the Listbox (Multi-select) selected items are obscured by a full-width "X" button. The full-width button covers the item text, rendering the item unreadable. (See attached screen-shot.)

index.css line 3277 seems to be the culprit:
min-width: 100%;

![screen shot 2014-10-14 at 12 43 18 pm](https://cloud.githubusercontent.com/assets/418072/4632936/7c051900-53c2-11e4-9c2a-9970d6d2146c.png)

**Comment by OptimusCrime** [comment]
So, fixed?

**Comment by TheBoxer** [comment]
should be
