### ISSUE TITLE
Extra padding around TV when moving to another Tab/Region

### ISSUE THREAD

**Issue by WebraumZ** [modxcms/revolution#12066]
Some extra space appears on the left of TV form when moving it to another tab using Manager Customization. This part of manager/templates/default/css/index.css causes such behaviour:

<code>.x-form-item.modx-tv {
padding: 0 0 0 15px!important;
}</code>

![image](https://cloud.githubusercontent.com/assets/1260989/4680765/a23dfe32-560d-11e4-94b5-2212a8261b0f.png)

**Comment by Flowan** [comment]
Confirm this does not work. Fixed this in https://github.com/modxcms/revolution/pull/13536 #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan 

@modxbot close
