### ISSUE TITLE
Incorrect created timestamp for downloaded packages

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12077]
If you download and install a package _(after 12pm / noon)_, the `created` timestamp in the database is not correct. The values for `updated` and `installed` are fine, however.

**Package Details:**

![package_details](https://cloud.githubusercontent.com/assets/352182/4725761/2dde8c08-595c-11e4-8b11-340a94428e77.jpg)

**Database: modx_transport_packages**

![modx_transport_packages](https://cloud.githubusercontent.com/assets/352182/4725823/a7fb16d2-595c-11e4-9771-3fe528c9c255.jpg)

**Comment by pixelchutes** [comment]
**NOTE**: This particular bug is best reproduced when installing packages sometime during the p.m. *(after noon)*

For example, if you install a package at 8**am**, the Package > View Details `Uploaded On` value will appear correct.

However, if you install a package at 8**pm**, the Package > View Details `Uploaded On` value will be **incorrect**.

**Comment by pixelchutes** [comment]
Just tested this on 2.5.5 and was unable to reproduce. 

Closing for #modxbughunt but planning to perform one final test at top of the hour (>= 13:00 test) 😉

**Comment by pixelchutes** [comment]
Confirmed still an issue. :'(

**Comment by Alroniks** [comment]
Fixed for #modxbughunt by #13509
