### ISSUE TITLE
Error with TV image

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#12084]
modx 2.3.2 and earlier
Create image TV.
Choose image:
![2014-10-23 14-32-07 editing test-page vmware citrix hyper-v - google chrome](https://cloud.githubusercontent.com/assets/1703670/4751602/1c8d28de-5aa0-11e4-9bd4-16a3e0333c37.png)
After Save and refresh page:
![2014-10-23 14-32-25 editing test-page vmware citrix hyper-v - google chrome](https://cloud.githubusercontent.com/assets/1703670/4751604/254c8f1e-5aa0-11e4-88a0-04aa42c97eeb.png)

Error log is null.

**Comment by adamwintle** [comment]
This looks like it was originally a phpThumbs issue. You can get some tips from the Forums or Slack chat at http://modx.org for tips

@modxbot close
