### ISSUE TITLE
2.3.2 breaks resources tree

### ISSUE THREAD

**Issue by tim-pearce** [modxcms/revolution#12109]
When I upgraded from 2.3.1 to 2.3.2 the resource tree only displayed the top level. The lower level entries were still in the database. Importing the backup from 2.3.1 into the database made no difference.

I also upgraded Articles from 1.7.8 to 1.7.9. I don't think the change in Articles version had anything to do with it (but I could be wrong).

The missing levels contain Articles containers, but at the third level viz:-
Australia (12) [top level and the only level showing in 2.3.2]
  2014 (13)
    2014_au_372_september (461) [Articles container]

Have restrored back to 2.3.1 and upgraded Articles to 1.7.9 and all seems ok.

**Comment by OptimusCrime** [comment]
I have no such problems.

**Comment by tim-pearce** [comment]
OptimusCrime,

Afraid I haven't been able to get back and try again. Will try again soon.

Tim

On 12/01/15 18:01, OptimusCrime wrote:
>
> I have no such problems.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/modxcms/revolution/issues/12109#issuecomment-69548570>.
>

-- 
Tim Pearce <tim@our-eden.com>
  3 Fourth Avenue, Shoalwater 6169
  Western Australia, Australia
  Phone +61-08-95281647 Mobile +61-0438916742

**Comment by tim-pearce** [comment]
Argnist,

Finally got around to trying again.

My live system is on 2.3.1. I've just updated by development system to 
2.3.2 again. Not as dramatic this time.

My resource tree in my live system looks like :-
web
   Home(1)
   Australia (12)
     2014 (13)
       2014_au_375_december (578)
       2014_au_370_july (575)
       etc.
   USA (15)
     2014 (16)
       2014_us_34_december (603)
       etc.
   Africa (552)
     2014 (553)
       2014_za_73_november (554)

The dev system looked the same, before the update, except that the 
numbers were different, of course, and the months are in a different order.
After update, the dev system looks like this :-
web
   Home(1)
   Australia (12)
     2014 (13)
       2014_au_374_november (597)
       2014_au_371_august (506)
       etc.
   USA (15)
     2014 (16)
       2014_us_31_may (368)
       etc.
   Africa (619)
and nothing more.

The 2014_ entries are Articles containers.

The missing items are in the database and I can go directly to them 
using the ID viz:- <http://clfweb/manager/?a=resource/update&id=621>
I tried changing the alias and uri of the 2014, under Africa, to see if 
that had an effect (possibility of duplicate alias) but it didn't made a 
difference).

When I do a 'clear cache', I get a message 'Resource URI 
a-word-for-the-heart-from-the-gospel-of-mark.html already exists for 
resource id = 626; skipping duplicate resource URI for resource id = 
760'. Resource 626 would be a child of resource 621.

If all else fails, I could delete the 'missing' resources and reimport 
them from the live system. I have developed a system to export and 
import an articles container so I can prepare each issue on my 
development system before transferring to the live system - it works in 
both directions.
Of course, that wouldn't explain how the problem occurred!

Tim

On 04/11/14 13:55, argnist wrote:
>
> Have you tried to delete Articles in 2.3.2 (or deactive its plugins)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/modxcms/revolution/issues/12109#issuecomment-61596856>.
>

-- 
Tim Pearce <tim@our-eden.com>
  3 Fourth Avenue, Shoalwater 6169
  Western Australia, Australia
  Phone +61-08-95281647 Mobile +61-0438916742

**Comment by tim-pearce** [comment]
It's fixed!

I went directly to resource 620, added a description and did a save!

Tim

On 04/11/14 13:55, argnist wrote:
>
> Have you tried to delete Articles in 2.3.2 (or deactive its plugins)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/modxcms/revolution/issues/12109#issuecomment-61596856>.
>

-- 
Tim Pearce <tim@our-eden.com>
  3 Fourth Avenue, Shoalwater 6169
  Western Australia, Australia
  Phone +61-08-95281647 Mobile +61-0438916742

**Comment by tim-pearce** [comment]
Spoke too soon.

When I open the lower levels by ID and do a save, the tree to that level 
is ok, but when I come back in, all trees are now shown as empty 
(despite the fact that they aren't).

Tim

On 04/11/14 13:55, argnist wrote:
>
> Have you tried to delete Articles in 2.3.2 (or deactive its plugins)?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/modxcms/revolution/issues/12109#issuecomment-61596856>.
>

-- 
Tim Pearce <tim@our-eden.com>
  3 Fourth Avenue, Shoalwater 6169
  Western Australia, Australia
  Phone +61-08-95281647 Mobile +61-0438916742

**Comment by tim-pearce** [comment]
After removing all locks, the tree has returned!
Curiously, when I did this the manager menu (across the top) disapeared. A refresh of the page brought it back.
Will now do a backup and upgrade of my live system to confirm this.

**Comment by TheBoxer** [comment]
Closing for long inactivity. Feel free to reopen with more details.
