### ISSUE TITLE
Recently Edited Resources dashboard widget: Update from grid errors

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12129]
The "Recently Edited Resources" dashboard widget apparently allows you to make edits from the grid, however the updates don't succeed, instead errors with a 500 status. I presume this is unintended behavior, and probably should be disabled.

**Comment by syts88** [comment]
This issue is fixed in 2.5.5. Can be closed. #modxbughunt

**Comment by pixelchutes** [comment]
@syts88 Interesting. I can confirm that the 500 error is no more (yay!) and the update worked, however I also noticed that if you change the `pagetitle` via this grid, that it also unexpectedly updated the `alias`, too.

I would almost think we should prevent edits from working via this grid, as it seems to exist more for informational purposes than for functional. Keep edits to the Edit / Quick Update sections maybe? Thoughts?

**Comment by pixelchutes** [comment]
@syts88 Interesting. I can confirm that the 500 error is no more (yay!) and the update worked, however I also noticed that if you change the `pagetitle` via this grid, that it also unexpectedly updated the `alias`, too.

I would almost think we should prevent edits from working via this grid, as it seems to exist more for informational purposes than for functional. Keep edits to the Edit / Quick Update sections maybe? Thoughts? #modxbughunt

**Comment by syts88** [comment]
@pixelchutes Good catch. Well personal the right click option i do think is handy. But the edit on double click is not needed. 

I will take a look at it :) #modxbughunt

**Comment by pixelchutes** [comment]
Sweet! I do think double-click option on grids is great , just not this grid 😉

**Comment by syts88** [comment]
@pixelchutes The pull request is made ;)

**Comment by pixelchutes** [comment]
Fixed by 1ead28c7af6dc6b9bb37f889bbe57e621ed76306 (#13358)
