### ISSUE TITLE
"SQL injection attempt detected" for benign context key containing the string 'union'

### ISSUE THREAD

**Issue by trevordixon** [modxcms/revolution#12121]
Create a new context with the key "unionworkers". The error log reports "(ERROR @ /connectors/index.php) SQL injection attempt detected: unionworkers", but the context is created. Attempting to delete the context causes an error, "Context not found with key: unionworkers", and the same "SQL injection attempt detected" error is logged to the error log.

https://github.com/modxcms/revolution/blob/cd690b16c303823697562c89efb1a8b2045bc429/core/xpdo/om/xpdoquery.class.php#L805-L812 decides anything with the word 'union' in it is no good.

Either benign keys with the work union in them should work fine, or they shouldn't be allowed to be a context key.

**Comment by rtripault** [comment]
Since this is related to xPDO, and you submitted a PR (thanks!), i'm closing this issue.

Thanks
