### ISSUE TITLE
Ability to set multiple constraints for Form Customization Sets

### ISSUE THREAD

**Issue by jchirschy** [modxcms/revolution#12138]
Hi,

I saw something about that in the Tracker but not on GitHub, that's why I create here an issue.
Is it possible to have a comma separated list of constraint or whatever separator when you set a constraint to a Form Customization Set .
For example, I would like to specify a set that apply for multiple resources.

Thanks in advance

**Comment by Mark-H** [comment]
Added in 6c07d38f4ca3e5728e6fe94e1bf9ebed8b3bcd40 per #11239
