### ISSUE TITLE
Error messages on login screen need better labeling and focus management (accessibility defect)

### ISSUE THREAD

**Issue by paulbohman** [modxcms/revolution#12148]
For compliance with Web Content Accessibility Guidelines (WCAG)

The feedback messages ("User not found...", "The username or password you entered is incorrect...") need to be read by screen readers when the page refreshes.

Option 1: One way to accomplish this is to force the keyboard focus onto the error message when the page reloads. The error message would need to have tabindex="-1" to effectively be able to receive the focus via JavaScript. &lt;div id="alert-message" tabindex="-1"&gt;User not found...&lt;/div&gt;. The message should precede the first relevant form field. If the username/password is incorrect, the message should appear above the username field. If the error occurs on the "Username or Email" field (after selecting "forgot password?" then the error message should appear directly above the "username or email" field, so that users hit tab once to go into that field.

Option 2: put the error message in the label of the relevant field, either by putting it in the &lt;label&gt; tag, or by using aria-label to refer to the message, e.g. refer to both the regular label and the message: 

&lt;div id=&quot;alert-message&quot;&gt;User not found...&lt;/div&gt;<br />
&lt;label for=&quot;username&quot; id=&quot;username-label&quot;&gt;Username&lt;/label&gt; <br />
&lt;input aria-label=&quot;alert-message username-label&quot; ...&gt;

Note that you would want to link the error message for the "username or email" field to that field directly, not to the "username" field. You would also want to make sure that keyboard focus goes to the "username or email" field and NOT to the top "username" field on page reload. In other words, make sure you're sending the keyboard focus to the correct field to match the error, and make sure the error message is associated with the appropriate field.
Also: Set aria-invalid="true" on the &lt;input&gt; element after the form has been submitted on all incorrect fields. Screen readers will say "invalid" to let users know they need to fix the field.

See accessibility to-do list at https://dequeuniversity.com/modx-accessibility.html#login

**Comment by rthrash** [comment]
This is being addressed at the [MODX Accessible CMS Project](https://github.com/modxcms/a11y/issues/), and with Paul's agreement has been moved there. For more details, see https://github.com/modxcms/revolution/issues/12156#issuecomment-72382480. Thank you!
