### ISSUE TITLE
keyboard focus management on login screen with "forgot your login?" (accessibility defect)

### ISSUE THREAD

**Issue by paulbohman** [modxcms/revolution#12147]
For compliance with Web Content Accessibility Guidelines (WCAG)

When users click on "forgot your login?" the keyboard focus needs to move to the "username or email" form field. Ensure that screen readers read the label appropriately (and the error message if the form is being refreshed with an error message).

See accessibility to-do list at https://dequeuniversity.com/modx-accessibility.html#login

**Comment by rthrash** [comment]
This is being addressed at the [MODX Accessible CMS Project](https://github.com/modxcms/a11y/issues/), and with Paul's agreement has been moved there. For more details, see https://github.com/modxcms/revolution/issues/12156#issuecomment-72382480. Thank you!
