### ISSUE TITLE
Color contrast of text against background in manager needs to pass WCAG (accessibility defect)

### ISSUE THREAD

**Issue by paulbohman** [modxcms/revolution#12143]
For compliance with Web Content Accessibility Guidelines (WCAG)

The color contrast ratio of the light-colored text in many places does not pass the WCAG standard of 4.5 to 1 for normal text of 3 to 1 for large text. The color contrast can be analyzed using automated tools such as FireEyes/WorldSpace http://worldspace.dequecloud.com and Wave http://wave.webaim.org

Examples from the manager login screen:

The contrast ratio between the blue link text and the grey background is too low for some users with low vision. The blue text is also too light even against the white background for accessibility contrast ratio standards. A possible value is #206e99

The contrast is too low on the grey text of the "Language" label in the bottom left and the "remember me" label. A possible value for "remember me" would be #757575. A possible value for "Language" is #575757.

The contrast is too low on the teal background color of the buttons compared to the white text on top. A possible value would be #007571.

See accessibility to-do list at https://dequeuniversity.com/modx-accessibility.html#styles

**Comment by rthrash** [comment]
This is being addressed at the [MODX Accessible CMS Project](https://github.com/modxcms/a11y/issues/), and with Paul's agreement has been moved there. For more details, see https://github.com/modxcms/revolution/issues/12156#issuecomment-72382480. Thank you!
