### ISSUE TITLE
Put aria-required="true" on login screen fields (accessibility defect)

### ISSUE THREAD

**Issue by paulbohman** [modxcms/revolution#12145]
For compliance with Web Content Accessibility Guidelines (WCAG)

Use aria-required="true" on all required <input> elements. Screen readers will say "required" when reading to users.

See accessibility to-do list at https://dequeuniversity.com/modx-accessibility.html#login

**Comment by rthrash** [comment]
This is being addressed at the [MODX Accessible CMS Project](https://github.com/modxcms/a11y/issues/), and with Paul's agreement has been moved there. For more details, see https://github.com/modxcms/revolution/issues/12156#issuecomment-72382480. Thank you!
