### ISSUE TITLE
Fix keyboard tab order of menu options in manger uberbar (accessibility defect)

### ISSUE THREAD

**Issue by paulbohman** [modxcms/revolution#12150]
For compliance with Web Content Accessibility Guidelines (WCAG)

The order of objects in the DOM differs from the visual order. The way the links are laid out visually, I would expect the order to be:

MODx/home logo
search
content/media/extras/manage
user menu
gear/system menu
help icon

The actual order starts with user and goes to the right and then goes back to the MODx home and across the left menu, which is not intuitive.

See accessibility to-do list at https://dequeuniversity.com/modx-accessibility.html#uberbar

**Comment by rthrash** [comment]
This is being addressed at the [MODX Accessible CMS Project](https://github.com/modxcms/a11y/issues/), and with Paul's agreement has been moved there. For more details, see https://github.com/modxcms/revolution/issues/12156#issuecomment-72382480. Thank you!
