### ISSUE TITLE
Easy access to pull requests in the readme

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/revolution#12157]
Not so much an issue as a suggestion.

I feel like the there is some information left out dealing with pull requests and the development of MODX. I know that there is a difference between targeting master and development, but I am not sure what. I've been watching this repo for about a year and a half and I still don't have a clue.

How about making this information (as well as the part about ACL and how to get one) directly accessable from the readme file?

**Comment by OptimusCrime** [comment]
I guess this is fixed now? I would suggest adding a link to the README, as CONTRIBUTING is not a standard file in a way (as far as I know), and people might overlook it.

**Comment by TheBoxer** [comment]
link to contributing file appears whenever you are creating new pr or new issue.

**Comment by OptimusCrime** [comment]
Well, that is embarrassing. Scratch what I just wrote.

Props for actually doing this btw. You are the best, @TheBoxer :)
