### ISSUE TITLE
Remove the "Show password on screen" and optimize handling with admin provided passwords

### ISSUE THREAD

**Issue by wuuti** [modxcms/revolution#12162]
If you edit a user password in user management, you have to choose between 2 following-up actions: send the password by email _or_ show the password on screen.
At least hey should not be radio options, because this forces you to choose one. If you do not want to either send it or show it, you have no chance.

And, **why** is the password (which has to be confirmed!) shown on the screen at all? I believe that is totally unneccessary, but instead reveals a secret in clear text, which sould be avoided if possible. 
A better way would be to have 3 actions: 
- "**Create a new password and send by E-Mail**" or 
- "**Create a new Password and show it on screen**" or 
- "**Provide a new password**" 

I can't see a reason why a password which is specified by a user and double confirmed should be sent or shown anywhere.

**Comment by alroniks** [comment]
I guess it is already fixed in MODX 3 by this PR https://github.com/modxcms/revolution/pull/13786
I am closing this one and we can continue a discussion here https://github.com/modxcms/revolution/issues/13973
