### ISSUE TITLE
IConv notice during install

### ISSUE THREAD

**Issue by feamsr00** [modxcms/revolution#12168]
Hi Folks,

I caught a php notice during the install of a new 2.3.2-PL (adv) revo site.
```
Notice: iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//TRANSLIT//IGNORE' is not allowed in [core]\model\modx\modresource.class.php on line 230
```
Let me know if you need any other info to track this down.

**Comment by OptimusCrime** [comment]
This looks like an error with the environment and not MODX itself.

Closing this due to age and lack of response.

Feel free to reopen if this is still an issue and you have more information to provide.

@modxbot close

**Comment by feamsr00** [comment]
Not to necropost, but for the record, the same environment has hosted subsequent MODX versions without issue. So, at some point, it was fixed. Thanks!
