### ISSUE TITLE
checkboxgroup/radiogroup issue in MODx.FormPanel

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12177]
If a MODx.FormPanel contains a checkboxgroup/radiogroup this panel is not rendered because of nodeToRecurse.items is an array in utilities.js (line 65) for the checkboxgroup/radiogroup item and that has not the method each.

I don't know how to fix that without breaking recursive work of that function.

**Comment by Ibochkarev** [comment]
@Jako Can you fix it now?

**Comment by Jako** [comment]
No, the issue is still there.

**Comment by sebastian-marinescu** [comment]
Hi @Jako, out of curiosity, does it work now? 🤓
