### ISSUE TITLE
User country

### ISSUE THREAD

**Issue by eladnova** [modxcms/revolution#12189]
On the Country field of a User, typing in a country not within the select list will result in error:

Code: 200 OK
{"success":false,"message":"","total":0,"data":[],"object":[]}

Same erre message results for a typo. 

It's not an error as such but a more descriptive message could be displayed.

**Comment by rtripault** [comment]
Confirmed, because of

https://github.com/modxcms/revolution/blob/master/core/model/modx/processors/system/country/getlist.class.php#L15

We should either : 

* pass a message to the `failure()`
* just return an empty array using `$this->outputArray(array()))` to prevent the error display

**Comment by OptimusCrime** [comment]
I can take a look at this :)

**Comment by Flowan** [comment]
Confirmed this works in 2.5.x #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @Flowan

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by OptimusCrime** [comment]
@rtripault Arrrgg, why did you not post a link with the latest commit? I am unable to find the correct line in the master branch right now. Do you know what happened with this?

**Comment by rtripault** [comment]
I guess the code chunk is no more. FWIW i also wasn't able to reproduce the issue

**Comment by OptimusCrime** [comment]
Awesome. Then we'll close this.

@modxbot close
