### ISSUE TITLE
Resources browser not working as expected (Chrome, ie11)

### ISSUE THREAD

**Issue by mtalvenheimo** [modxcms/revolution#12192]
Expand tree, Collapse tree, Refresh icons missing.
Sort By not working.
Works okay in Firefox.
![capture_r1_c1](https://cloud.githubusercontent.com/assets/6428699/5279525/482d75b6-7aee-11e4-91bc-b8658ae5cd84.jpg)

**Comment by syts88** [comment]
Cannot reproduce this issue. It seems this issue is fixed in MODX Revo 2.5.5. #modxbughunt

**Comment by rtripault** [comment]
So closing the issue, but feel free to comment/reopen if needed.
Thanks
