### ISSUE TITLE
Load all mgr permissions at once to MODx.perm

### ISSUE THREAD

**Issue by argnist** [modxcms/revolution#12211]
The same is done with settings which are loaded to MODx.config in core/model/modx/processors/system/config.js.php (time is about 0.06s in my tests).

I suggest to load all distinct permissions to MODX.perm in this config.js.php file. Something like:

``` php
$c = $modx->newQuery('modAccessPermission');
$c->select('name');
$c->distinct();
$perms = $modx->getIterator('modAccessPermission', $c);
$values = array();
foreach ($perms as $perm) {
    $name = $perm->get('name');
    $values[$name] = $modx->hasPermission($name);
}
$o .= 'MODx.perm = ' . $modx->toJSON($values) . ';';
```

My tests show ~0.04s for that.
### Why is it needed ?

Now permissions in JS manager code are scattered in about 40 controllers added not only to MODx.perm but in MODx object itself and on different Ext.Panel objects. Most common code is something like

``` php
MODx.perm.unlock_element_properties = "'.($this->modx->hasPermission('unlock_element_properties') ? 1 : 0).'";
```

Extra developers must write this time by time.
With this addition all simple manager permissions are concentrated in one place that yields more clean code. All additional complex permissions still will be added as above.
Also the array for MODx.perm can be cached by user id or in $_SESSION.
# area-core #enhancement

**Comment by pepebe** [comment]
+1

**Comment by alroniks** [comment]
Closing as pull request is merged. Fixed in 3.x.
