### ISSUE TITLE
Change css for title/template labels

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#12221]
If you hide the template select field via manager customization, the rules for the hidden element don't apply to the next element that moves to the top (usually resource alias), because template select is not removed from the dom, but just hidden from view. As a consequence, the vertical rhythm is broken:

![bildschirmfoto 2014-12-18 um 10 37 07](https://cloud.githubusercontent.com/assets/667315/5486113/655e2700-86a3-11e4-9393-06a33db65044.png)

The root of this problem can be found in index.css:

```
.x-form-label-top .x-form-item:first-of-type label.x-form-item-label {
padding: 0 0 4px;
}
```
It overwrites the general css for the labels enclosed in the first .x-form-item found in each column.

```
.x-form-label-top .x-form-item label.x-form-item-label {
display: inline-block;
margin: 0;
padding: 15px 0 4px;
}
```

I can't see any benefit of this rule, so I vote for removing it from https://github.com/modxcms/revolution/blob/master/manager/templates/default/css/index.css

Cheers

**Comment by OptimusCrime** [comment]
@modxbot close
