### ISSUE TITLE
Clear user groups properly in $user->joinGroup()

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12224]
joinGroup() clears this session variable on a successful join:

    unset($_SESSION["modx.user.{$this->get('id')}.userGroupNames"]);

but modUser::getUserGroups() uses the userGroups session variable. So a user is not actually joined until he or she logs out and back in.

I suggest that the line in joinGroups() (663) be changed to this:

     unset($_SESSION["modx.user.{$this->get('id')}.userGroupNames"],
           $_SESSION["modx.user.{$this->get('id')}.userGroups"]);

**Comment by pixelchutes** [comment]
Commented on the PR, but wouldn't the same need to apply for [leaveGroup()](https://github.com/modxcms/revolution/blob/9d392dadada571ccfba352781a12464f9301c0b3/core/model/modx/moduser.class.php#L733) ?

**Comment by BobRay** [comment]
For some reason, I didn't think so, but after looking again, yes it definitely should. I've created a new pull request with both changes (BobRay-patch-2).

**Comment by pixelchutes** [comment]
Thanks Bob! I did not see the PR land yet, but will be happy to test once it hits `master`.

**Comment by BobRay** [comment]
I might have made the pull request on the develop branch.

**Comment by pixelchutes** [comment]
I think the PR was made your own fork, not to `modxcms/revolution`: https://github.com/BobRay/revolution/pull/1

**Comment by BobRay** [comment]
Oops. I just issued a new PR (hopefully to the right place) with both changes. GitHub says it's a merge conflict, but reports only the two changed lines, so probably not a serious one.

**Comment by pixelchutes** [comment]
PR #12409

**Comment by BobRay** [comment]
Just added a new (clean) PR for leaveGroup.
