### ISSUE TITLE
Allow empty pagetitle in UI

### ISSUE THREAD

**Issue by inreti** [modxcms/revolution#12239]
The manager UI does not allow you to save a resource without a pagetitle. Therefore it is not possible to write a plugin which automatically sets a pagetitle when saving (like with alias or other fields). 
There are cases where you may want to hide the pagetitle via forms customiziation from the editor (not forcing the editor to give a useless title just to be able to save it, e.g. in Collections where pagetitle is not used). But if you hide the pagetitle field via fc, saving will not be possible. 

So my proposal: strip the pagetitle verification from the UI. If a resource with empty pagetitle is saved, automatically choose a pagetitle (say "resource_[[+id]]"). If the id is included it is guaranteed that all pagetitles are unique (and so are the corresponding aliases).

**Comment by TheBoxer** [comment]
Should be resolved via extra and not be part of the core.
