### ISSUE TITLE
Form Customization set: Deselecting template not working

### ISSUE THREAD

**Issue by mdehaan** [modxcms/revolution#12236]
When I create a new Form Customization set and leave the "template" field blank.
Then it works for all resource templates.
But when I select a "template" first and modify, then I can't deselect the template.

So I am able to make one set for all templates, but MODx isn't functioning the way it is supposed to, I think?

It would be nice if this worked also for the create/update option.

**Comment by rtripault** [comment]
Hi @mdehaan 

I'm not sure i'm following the issue you are reporting...

When you create a new set, the template defaults to `(empty)`, which is "no template" (stored as template ID `0` in the `fc_sets` table).

If you edit your set to use a particular template, you then should be able to select the "empty" template again (which, i suppose, should make the set behave the same way as before -- apply to all templates according to your writing).

Did i misunderstand the issue or the expected result ?
Thanks

**Comment by mdehaan** [comment]
Sorry,

Consider the issue not reported.
Today I found out the problem doesn't exist.






Met vriendelijke groet,


  


Marten de Haan




Op maandag 5 januari 2015 w2, om 15:32:44 heeft Romain Tripault het volgende geschreven:

**Comment by rtripault** [comment]
NP, errare humanum est :)
