### ISSUE TITLE
Adding new User Group Dialog has no action

### ISSUE THREAD

**Issue by konstantinj** [modxcms/revolution#12241]
Hi there,
some time ago I've updated my site to modx 2.3.1. Today I tried to create a new user group but the submit button in the dialog (manager/?a=security/permission) has no action anymore. There just nothing happening. It worked before. I will try the update to 2.3.2 I fear that this is not a known bug in 2.3.1.

**Comment by whitebyte** [comment]
Creating new user groups definitely work as expected in 2.3.2. @konstantinj , please tell  if you still have the problem after the upgrade.

**Comment by konstantinj** [comment]
Could fix this problem by removing the cache. But not via the manager menu. I had to remove everything inside the core/cache/ folder. Very strange. Unfortunately it happened again after some time, but removing the cache files helped again. If this happens again, any ideas for what I should have a look to figure this out?

**Comment by rtripault** [comment]
I'd bet you set `cache_db` setting to `true` (reproduced here with activating DB cache), right @konstantinj  ?

**Comment by TheBoxer** [comment]
Closing for long inactivity. Feel free to reopen with more details.
