### ISSUE TITLE
system setting debug = 1 destroys output of custom manager page in Quip

### ISSUE THREAD

**Issue by inreti-sb** [modxcms/revolution#12249]
A view weeks ago I installed Quip but was not able to see the custom manager page, but this line:

"Notice: Undefined index: debugUser in /home//public_html/core/components/quip/model/quip/quip.class.php on line 132"

Setting system setting "debug" from 1 to 0 solved it, but that can not be the final solution.
Maybe other warnings/errors (of packages) will destroy the output of the custom manager page, too.

MODX: 2.3.1
Quip: 2.3.3

Would be great if someone could verify this behavior and narrow down the cause.

Sebastian

**Comment by rtripault** [comment]
Definitely sounds like a Quip issue, not a Revo one.

May i suggest you to open the issue in Quip repository instead ?

A quick work around would be to comment https://github.com/modxcms/Quip/blob/develop/core/components/quip/model/quip/quip.class.php#L120, which is only supposed to be used for Quip development.

Thanks

**Comment by inreti-sb** [comment]
Thanks for the fast feedback, Romain!

Hm.. okay. Just want to get sure this is no core issue.
I already posted an issue for Quip: modxcms/Quip#13

Will link on that to this issue and close this one.
