### ISSUE TITLE
Only 10 items show up in menu editor

### ISSUE THREAD

**Issue by rainbowtiger** [modxcms/revolution#12244]
Only 10 items are showing up in the menu editor (Top Menu) underneath any particular menu heading. I've got more than 10 extras installed, but I can't sort them because they don't all show up under the Extras menu. I have to go into the back end and edit the menuindex using a MySQL editor. 

![10menuitems](https://cloud.githubusercontent.com/assets/2528374/5601378/5b139c76-92c9-11e4-9447-43c5ad1d74c9.png)

**Comment by rtripault** [comment]
I guess the solution lies in https://github.com/modxcms/revolution/blob/master/core/model/modx/processors/system/menu/getnodes.class.php#L28 (setting `limit` to `0` seems to fix the issue)

**Comment by OptimusCrime** [comment]
I guess I could take a look at this tomorrow or something and send a pull. Should be rather simple to fix.
