### ISSUE TITLE
getCollection + isLazy problem

### ISSUE THREAD

**Issue by grachov** [modxcms/revolution#12240]
When using `xPDO::getCollection` it's possible to lose some records if lazy and not lazy objects are mixing.
Imagine we have such resources as initial data:
```php
foreach (array(1, 4, 3, 2) as $i => $id) {
    $doc = $modx->newObject($id == 2 ? 'ArticlesContainer' : 'modResource');
    $doc->fromArray(array(
        'id' => $id,
        'pagetitle' => 'Doc ' . $id,
        'menuindex' => $i,
    ), '', true);
    $doc->save();
}
```
`ArticlesContainer` is always not lazy while for `modResource` this value is calculating dynamically.
Then if we will try to get all the resources ordered by `menuindex` using this code:
```php
$query = $modx->newQuery('modResource');
$query->select(array(
    'id',
    'class_key',
));
$query->sortby('menuindex');
var_dump(array_map(function ($doc) {
    return $doc->get('id');
}, $modx->getCollection('modResource', $query)));
```
we will get only 3 items instead of 4.
The problem is in [`xPDOObject::_loadCollectionInstance`](https://github.com/modxcms/revolution/blob/develop/core/xpdo/om/xpdoobject.class.php#L368) method which is using different indices depending on `isLazy` call so the new item can override already existing in collection item with the same index.

**Comment by rtripault** [comment]
Thanks @grachov for the report, but this rather belongs to https://github.com/modxcms/xpdo/issues.

Would you mind opening the issue there and close this one ?
Thanks

**Comment by grachov** [comment]
Ok, I've created an issue there with the reference to this one. But this issue is not low-important because if you have similar combination of the resources, they will disappear in the tree after moving/creation.

**Comment by rtripault** [comment]
Much thanks!

No doubt this appears not to be a "minor" issue. Unfortunately, i have no knowledge of that "lazy" stuff, nor took the time to experiment, so i won't be not helpful.

I guess @opengeek is the man with the appropriate knowledge!
