### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12253]
Not an issue, but a sort of RFC. 
MODX has it's own PHP code standard. While not being meaningless, it's more focused on MODX-specific stuff and doesn't contain almost anything about general PHP coding style. You know, brackets, indents, tabs etc. 
As a result, MODX codebase is rather patchy, and things are even worse if we look at many Extras. So I wonder, are there any plans for adopting some of the widely-used coding standards (obvious PSR-2, Pear etc)? With modern automated tools it's not a big deal to convert existing codebase to match the standard of choose, and it will give benefits of unification, higher code quality, wider adoption and easiness for newcomers, and overall robustness.

**Comment by rtripault** [comment]
PHP coding standards are defined there : http://rtfm.modx.com/revolution/2.x/developing-in-modx/code-standards#CodeStandards-PHP

But i agree, aiming at following as much as possible PSRs would be nice, especially since we expect more community contribution...

**Comment by pbowyer** [comment]
+1. Keeping the codebase to a consistent standard is more important to me than which standard is chosen.

**Comment by OptimusCrime** [comment]
Don't think this should be discussed as a issue.

**Comment by whitebyte** [comment]
Why? Github is not just a bug tracker. There are some huge projects (neovim for example) which effectively utilizes github as discussion board for development-related topics. This is the place where code-writers are "resides", not support forums.

**Comment by pbowyer** [comment]
@OptimusCrime If we had an alternative like https://wiki.php.net/rfc or https://www.python.org/dev/peps/ I'd agree - but we don't. 

Symfony uses GitHub issues for this (https://github.com/symfony/symfony/labels/RFC) and more, and it seems to work well. As do other projects.

**Comment by OptimusCrime** [comment]
WHile that is true, I belive that best discussions and most input can be found in the forums.

**Comment by Alroniks** [comment]
I've proposed use PSR earlier. In my work I use it always. MODX has own code standards, yes, but php community recommends and uses PSR, why we should find other way? It's not rational.

**Comment by goldsky** [comment]
MODX has been built years before PSR was initiated.
That said, MODX's standard was formed when "people still debated about spaces vs tabs".
What we have now is based on years of development.
The team even tries to keep this CMS runs on PHP 5.3+.

So, that's the rationale.

Most of the PSR adopters are PHP Frameworks.
Some of CMSes are actually (re-)built based on those frameworks.

In the meantime, let's don't push this topic too hard.
MODX is evolving.

So, let's open a forum to talk about this, and keep github to **count** bugs and pull requests.

**Comment by opengeek** [comment]
We are absolutely aligning the future of MODX with what the [PHP Framework Interop Group](http://www.php-fig.org/) has been working very hard to achieve. To ignore this would lead to irrelevance IMO, but @goldsky is correct—the current codebase was conceived long before any PSRs were being formally discussed in the PHP community.

As for discussing this in GitHub, I think this is absolutely the correct place for this discussion. Those developers that would most likely be interested in discussing PHP FIG standards probably feel more comfortable discussing those things here than in a forum.

Being able to make use of the vibrant ecosystem that has been constructed around the Composer/Packagist project, PSRs for autoloading, various coding standards and common interfaces, and PHP The Right Way will provide back-end developers the same level of Creative Freedom in the next generation of MODX releases that front-end developers depend on MODX for.

**Comment by opengeek** [comment]
FWIW, there is some work underway on an [xPDO 3.x branch](https://github.com/modxcms/xpdo/tree/release-3.0) which is constructed and usable as a composer library and adopts some PSR coding standards. This will be merged to master and added to Packagist in the next few weeks. We're hoping to provide at least some level of backward compatibility with existing MODX Extras which have their own database tables.
