### ISSUE TITLE
[2.3.2] Unable to save resources except with Quick Edit 

### ISSUE THREAD

**Issue by beau-gosse** [modxcms/revolution#12251]
When saving a resource in full/regular edit view, the save progress bar stays on forever. No 'Save successful' message follows as it normally does. This issue only affects resources. Other elements are behaving normally. I've worked around this by either using the quick edit option in the context menu or by manually reloading the active page after saving.

I should mention that I haven't encountered this problem with other 2.3 installs. My default timezone is correctly set to "America/Toronto". This issue is not browser-specific. I'm on a Media Temple Grid server running MySQL 5.1.72 / PHP 5.3.29.

This issue was also reported here: http://forums.modx.com/thread/95725/cannot-save-resource-changes-in-modx-revo-2-3-2#dis-post-518180

**Comment by Mark-H** [comment]
Closing as marked as closed in the linked forum topic http://forums.modx.com/thread/95725/cannot-save-resource-changes-in-modx-revo-2-3-2#dis-post-518316
