### ISSUE TITLE
Another Database Issue during setup

### ISSUE THREAD

**Issue by yaccin** [modxcms/revolution#12274]
I am currently trying to install modx and everything looks ok until i want to set up the database connection. I have the same issue as the other tickets:

Connecting to database server: Success!
- Checking MySQL server version: OK! Running: 5.5.40-36.1 
- Checking MySQL client version: OK! Running: 5.5.40

Connection character set:  utf8
Collation:  utf8_general_ci

Checking database: MODX could not create your database. Please manually create your database and then try again.

The user has full access to the specified database but is not allowed to create additional databases (that should not be needed anyways). Please let me know if you need more information, I would like to have this resolved and not vanish in the depths of the interwebs because additional information was missing.

(in another ticket there was asked if IE8 was used. The browser should have nothing to do with it but just to be sure i tested it with the most recent versions of Safari, Chrome and Firefox.)

**Comment by zaigham** [comment]
Do you have database already created?

**Comment by yaccin** [comment]
Yes, the installer is also able to connect: "Connecting to database server: Success!"

**Comment by amdbuilder** [comment]
Could you tell us more about your hosting environment?  Also just to confirm the database user has full permissions to the database you created?

**Comment by yaccin** [comment]
yes, the user has all privileges but grant. https://www.dropbox.com/s/vnf8zodmr44bw2s/Screenshot%202015-01-16%2021.37.51.png?dl=0

we are using php-fpm:

PHP 5.5.20-3~mgt (cli) (built: Jan  5 2015 15:23:24)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader v4.7.2, Copyright (c) 2002-2014, by ionCube Ltd., and
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies

and nginx:

nginx version: nginx/1.6.2

with this mysql version:

mysql  Ver 14.14 Distrib 5.5.40-36.1, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by amdbuilder** [comment]
What happens if you try to access the database via phpmyadmin or adminer with the same credentials?  If you would rather discuss this issue on skype feel free to ping me: skytoasterllc

This sounds more server related than MODX Issue at the moment.

**Comment by yaccin** [comment]
issue solved, 127.0.0.1 instead of localhost worked somehow :)

**Comment by carlitoselmago** [comment]
I solved it changing the chmod to 777 of /public_html/setup/index.php
