### ISSUE TITLE
syncsite_default is not honored. When enabled, Resource edits no longer clearing cache.

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12275]
### Summary
A recent commit 4bb7ec2fb9721f5a6eaa16671e674735d8aeff92 seems to be causing issues when testing the new `syncsite_default` setting. When enabled, the "Empty Cache" checkbox is not automatically checked, requiring manually clearing the cache after Resource edits.

### Step to reproduce
1. Checkout `master` at least to 1c1fc58157d4591e4170cdddbe794ec4b9826109
2. Install instance and ensure `syncsite_default` is enabled
3. Edit an existing, cacheable resource. Click "Save", then "View"
4. Any changes are not immediately visible.

### Observed behavior
"Empty Cache" checkbox was **not** checked (under "Settings" tab.) Manually clearing the cache was required. 

### Expected behavior
When `syncsite_default` is enabled, the "Empty Cache" checkbox should be automatically checked while editing a Resource.

### Environment
MODX 2.3.3-dev (git, latest master), Chrome 41.0.2272.3 dev (64-bit) / OS X 10.10.1

**Comment by pixelchutes** [comment]
Also, I have no FC rules configured, in case that helps?

**Comment by sottwell** [comment]
That's my fault. I didn't notice that the update processor uses "true" and "false", while the create processor is happy with the "1" and "0" from the system_setting. It needed to be converted to "true" or "false" for the update processor.

```$this->resourceArray['syncsite'] = intval($this->context->getOption('syncsite_default', 1, $this->modx->_userConfig)) == 1 ? true : false;```

**Comment by sottwell** [comment]
I'm not sure that the userConfig is relevant in this case, but it doesn't seem to be hurting anything so I thought it best to just leave it there.

**Comment by pixelchutes** [comment]
I can confirm the userConfig fallback is working as intended, providing a user-level override for this system setting, if necessary.

**Comment by sottwell** [comment]
It would be nice it it could also respect the context of the resource. Apparently the context part refers to the context in which the user is working, i.e. "mgr".

**Comment by rtripault** [comment]
@sottwell at first i thought the same about context, but in fact the resource context should already be set (see [relevant code](https://github.com/modxcms/revolution/blob/master/manager/controllers/default/resource/resource.class.php#L224-237))
