### ISSUE TITLE
Problem with FURLs and container resources

### ISSUE THREAD

**Issue by crimsonpixel** [modxcms/revolution#12285]
I'm getting a couple of strange results from sites that have recently been upgraded to 2.3.2 with the friendly URL's and resources which are set as containers.

For example I have two resources which have children and are set as containers called 'About' and 'FAQ'. The URL for each should be www.domain.com/about/ and www.domain.com/faq/ however, if you are on the www.domain.com/about/ page and try to visit the faq page the following appears as the URL www.domain.com/about/faq/ which clearly is wrong and sends visitor to the error page.

To rectify this problem I need to uncheck the resources container box and everything works fine.

Below is the system settings for FURL

![furl_set_up](https://cloud.githubusercontent.com/assets/2063237/5836492/80ff48a0-a16e-11e4-8a60-ecb286b67732.png)

**Comment by 13hakta** [comment]
Please try using <base href="[[++site_url]]"> in header section.
And also change alias of first page from "index" to whatever "start" or "main".

**Comment by 13hakta** [comment]
Filter ate: base href="[[++site_url]]"

**Comment by crimsonpixel** [comment]
Ok I've added in the base href="[[++site_url]]" and think this may have resolved the issue.

**Comment by crimsonpixel** [comment]
I will pass this on to the developer who originally built these sites so he is aware of what may be missing from other sites he is working on too. Thanks for the help :)

**Comment by rtripault** [comment]
I guess we can close this one then (would have been nice to do so on your own).

Also, please do note that kind of support would have been more suited for the forums.

Thanks

**Comment by crimsonpixel** [comment]
Apologies - yes should have closed it myself! Posted on here partly because it was suggested to me that it might be a bug.... Thankfully not!
