### ISSUE TITLE
System settings - Use of xtype = numberfield

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#12284]
I've noticed that xtype => 'numberfield' (with the exteption of 'tree_root_id') is almost never used in transport.core.system_settings.php?

https://github.com/modxcms/revolution/blob/cd690b16c303823697562c89efb1a8b2045bc429/_build/data/transport.core.system_settings.php

I might be overlooking something, but is there a good reason why we don't use this type for things like 'site_start', 'error_page', etc?

Cheers,

pepebe

**Comment by Ibochkarev** [comment]
@pepebe what are your suggestions for change?

**Comment by alroniks** [comment]
@Ibochkarev He suggested changing default content type for settings that should contain any ID (resource id or element id or another id) to number field instead of text field to avoid issues when code expects valid number but gets a string with a text.

**Comment by JoshuaLuckers** [comment]
When I have time I will fix this 😄

**Comment by Mark-H** [comment]
Fixed in #14447
