### ISSUE TITLE
Adding a context setting deletes system setting

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12280]
Modx 2.3.2
Adding a context setting which is the same as a system setting deletes it from the system settings.
I would expect all other contexts to use the default system setting value and only the context with its own value to not. I assume this isn't a feature.
The way it is, if one context has a setting added, then all contexts need that same setting added.

**Comment by pixelchutes** [comment]
This sounds similar to #11789, but I believe that was fixed for 2.3.2.

**Comment by pixelive** [comment]
Cannot reproduce this issue. #modxbughunt

**Comment by digitalpenguin** [comment]
Can't reproduce anymore either!
