### ISSUE TITLE
Media Sources - Revo 2.3.2 on modxcloud hosting

### ISSUE THREAD

**Issue by hcanning2014** [modxcms/revolution#12288]
Media sources if duplicated and values changed won't save with changed values. Also wont delete.

Recreate:
create a media source called "uploads"
right click and duplicate it: "duplicate of uploads"
try renaming it and saving...label change doesnt update
try deleting..doesnt delete

**Comment by rtripault** [comment]
Hi,

Were you able to reproduce on another host beside modxcloud ?
If not, chances are that's an environment issue, and i would suggest you to contact [modxcloud staff](https://modxcloud.com/userguide/quickstart/support-options.html).

For the record, i was not able to reproduce using 2.4.0-dev.

Thanks

**Comment by amdbuilder** [comment]
Can you confirm if this issue exists with 2.3.3 as well?

**Comment by TheBoxer** [comment]
Closing for long inactivity. Feel free to reopen with more details.
