### ISSUE TITLE
Login Screen Password-Recovery Section needs some love

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#12292]
### Summary

Just (accidentally) clicked on the "Forgot Password" link and it didn't look so pretty =)...see screenshot:

![bildschirmfoto 2015-01-23 um 19 27 21](https://cloud.githubusercontent.com/assets/445501/5880176/65946a5e-a336-11e4-9cd3-2533f7e5c869.png)
### Step to reproduce

Klick the "Forgot Password" link on the login screen.
### Observed behavior

Textfield and Button need some vertical spacing/separation
### Expected behavior

The Button should have a bit margin on top

``` css
#modx-fl-btn {
    margin-top: 10px;
}
```

should do it more or less
### Environment

MODX Revolution 2.2.x

**Comment by whitebyte** [comment]
I wonder, will 2.2 branch be continued?

**Comment by OptimusCrime** [comment]
I don't understand why.

**Comment by whitebyte** [comment]
If not, is this an issue? 2.3 login screen looks correct.

**Comment by exside** [comment]
Guess it's like windows XP, discontinued, but still everywhere =)...and yes, the 2.3 login screen looks ok...but as the fix for this issue would be so easy, I just thought it could be part of another 2.2.x patch release...

**Comment by OptimusCrime** [comment]
Upgrade to newest 2.x version and this problem is fixed.

@modxbot close
