### ISSUE TITLE
Wanted: A new global xtype to enter small JSON key/value objects

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12293]
It would be nice to have a new xtype that is displayed as a small grid and contains small JSON key/value objects. A grid type system setting or snippet property could be created that way, not nested xPDO where clauses could be clicked together by non techies …

**Comment by oori** [comment]
xtype "propertygrid" does that.     although it isn't simple, you normally have to care for two-way sync into a hidden string field (using "propertychange" and "_updated" listeners, and encoding/decoding JSON)  and more UI related hacks due to vertical space, etc..

```
/**
 * Update window
 */
OO.window.UpdateSurvey = function(config) {
    config = config || {};
    Ext.applyIf(config,{
        ooType:'survey'
        ,width: 650
        ,autoScroll: true
        
        ,fields: [{
            xtype: 'hidden'
            ,name: 'id'
        },{
        xtype:'fieldset',
        title: _('oo.update'),
        collapsible: true,
        collapsed: false,
        items :[
            {
                xtype: 'oo-combo-role'
                ,fieldLabel:_('oo.survey.role')
                ,name: 'role'
                ,anchor: '100%'
            },{
                xtype: 'oo-combo-survey'
                ,fieldLabel: _('oo.survey.id')
                ,name: 'survey'
                ,anchor: '100%'
            },{
                xtype: 'textfield'
                ,fieldLabel:_('oo.survey.title')
                ,name: 'title'
                ,anchor: '100%'
                ,id: 'surveyTitle_update'
            },{
                xtype: 'textfield'
                ,fieldLabel: _('oo.survey.lastSync')
                ,name: 'lastSync'
                ,anchor: '100%'
            },{
                xtype: 'hidden'
                ,fieldLabel:  _('oo.survey.mappedQuestions')
                ,name: 'mappedQuestions'
                ,id: 'mappedQuestions'
                ,anchor: '100%'
                ,listeners: {
                    '_updated': {fn:function(o){
                        var v = Ext.util.JSON.decode(o.getValue());
                        Ext.getCmp('mappedQuestions_grid').setSource(v);
                    },scope:this}
                }
            }]
        },{
            xtype: 'propertygrid'
            ,name: 'mappedQuestions_grid'
            ,id: 'mappedQuestions_grid'
            ,anchor: '100%'
            ,collapsed: true
            ,collapsible: true
            ,autoHeight: true
            ,autoSroll: true

            ,title:  _('oo.survey.mappedQuestions')
            ,listeners: {
                'propertychange': {fn:function(source, recordId, value, oldValue){
                    var v = Ext.util.JSON.encode(source);
                    Ext.getCmp('mappedQuestions').setValue(v);
                },scope:this}
            }
        }]
    });
    OO.window.UpdateSurvey.superclass.constructor.call(this,config);
};
Ext.extend(OO.window.UpdateSurvey,OO.window.Update);
Ext.reg('oo-window-survey-update',OO.window.UpdateSurvey);

```

This solution works well, but it's biggest limitation is that it is only usable for existing keys.  one can not add nor remove keys on the fly.

**Comment by Jako** [comment]
Seems a good start for that. It just has to get a sort of actionbuttons in each row to add a new line & remove the current line.

**Comment by JoshuaLuckers** [comment]
> Seems a good start for that. It just has to get a sort of actionbuttons in each row to add a new line & remove the current line.

@Jako Is this possible thanks to PR https://github.com/modxcms/revolution/pull/14806 ?

**Comment by Jako** [comment]
Those action columns are not created for a property grid, if I read the code right.

But I have implemented a JSON grid for a Image+ system setting: https://github.com/Jako/ImagePlus/blob/master/source/js/mgr/imageplus.grid.js.

This looks like this in the grid:
<img width="628" alt="JSON value in the grid" src="https://user-images.githubusercontent.com/148371/71547776-bbc75680-29a4-11ea-95e0-a8f1fc31868a.png">

And like this in the editing window:
<img width="585" alt="Grid in the edit window" src="https://user-images.githubusercontent.com/148371/71547785-caae0900-29a4-11ea-9116-c0109b5f5cb6.png">

This one could be reduced to a key/value pair grid.

**Comment by JoshuaLuckers** [comment]
Looks cool! Go for it :)

**Comment by Ibochkarev** [comment]
Added #14959 
@Jako :thumbsup:
@modxbot close
