### ISSUE TITLE
Syncsite setting for update bug

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12294]
The new system setting for the syncsite checkbox doesn't work for updating resources. The line 122 in manager/controllers/default/resources/update.class.php needs to be 

        $this->resourceArray['syncsite'] = intval($this->context->getOption('syncsite_default', 1, $this->modx->_userConfig)) == 1 ? true : false;

**Comment by pixelchutes** [comment]
@sottwell could this perhaps resolve #12275 ?

**Comment by sottwell** [comment]
Yes. It is an issue with a difference between the update processor and the create processor. The update processor uses "true" or "false", while the create processor uses "1" or "0". A bit of inconstancy there. So in the update processor the system_setting value had to be converted to true or false.

**Comment by pixelchutes** [comment]
Thank you for spotting this difference + the fix! Will you be submitting a PR? I'd be happy to help test / merge.

**Comment by pixelchutes** [comment]
Closing as duplicate.

**Comment by sottwell** [comment]
I just wiped out my localhost web root again, it had gotten too chaotic. So I have to clone my fork again, which is still a painful process for me. If I do it enough times, it should get easier. Anyway, it's not going to happen within the next few days.

**Comment by pixelchutes** [comment]
I'd be happy to submit the PR for you *(giving you your due credit, of course)*, for someone else to test + merge in order for this to make it into v.2.3.3-pl, if you would like.

**Comment by sottwell** [comment]
Please do. I am not at all concerned about who does what, as long as somebody does something ;)

**Comment by pixelchutes** [comment]
All set, thanks again, Susan!
