### ISSUE TITLE
Package Manager - Windows - Not Fixed as per 2.3.3 fix notes

### ISSUE THREAD

**Issue by NotebookRuled** [modxcms/revolution#12309]
I think this is the issue I've been having, on certain servers I use, after 2.3 was introduced I was no longer able to easily update or install new packages through Modx package manager (using windows). There is a less elegant solution which involves downloading the package separately from the Modx Extras web page, then uploading it and finding the package through the package manager and installing it that way..

On the fix list for 2.3.3 there is a listing for Package Manager for windows being fixed, but I've tried it and still cannot get it to work for me. Maybe this is fix for something entirely different??

**Comment by OptimusCrime** [comment]
Can you please describe what is happening? I can upgrade packages in 2.3.2 using Linux (debian) with no problems.

**Comment by TheBoxer** [comment]
Closing for long inactivity. Feel free to reopen with more details.
