### ISSUE TITLE
ERROR @ /connectors/system/errorlog.php

### ISSUE THREAD

**Issue by LEONeso** [modxcms/revolution#12303]
[2015-01-27 20:51:23] ERROR @ /connectors/system/errorlog.php Processor /core/model/modx/processors/get.php does not exist; Array
(
    [action] => get
)

**Comment by rtripault** [comment]
Hi @LEONeso,

It would be lovely if you could read https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md#submit-an-issue and update your issue accordingly.

Much thanks

**Comment by TheBoxer** [comment]
Closing for long inactivity. Feel free to reopen with more details.
