### ISSUE TITLE
Not correctly shown in columns. Radio buttons and Checkbox tvs.

### ISSUE THREAD

**Issue by designbywilliam** [modxcms/revolution#12304]
Ben i have selected the tv's radio or checkboxes to be in columns. They aren't correctly showing. See image : 

https://www.uploady.com/#!/download/AARo1pss7mt/hWImu6Us6FPMUCeo

**Comment by argnist** [comment]
I have opposite behaviour with checkboxes. The width of each column is set by pixels, not in percents, so not all columns can be visible on wide screen.

**Comment by christianseel** [comment]
Correct, this works when you set a better value to the width. You need to make sure to enter a absolute value in pixels, not percent.

#modxbughunt
@modxbot close
