### ISSUE TITLE
Add Form Customization event trigger for plugin

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#12310]
I think we need additional event trigger around Form Customization, to hack around the output.
The closest case is that [Lingua needs to detect some rules](https://github.com/goldsky/Lingua/issues/33) before the document page is rendered.

**Comment by alroniks** [comment]
It would be nice to see a more detailed explanation of the feature request. With the current description, it is unclear what to do, so I am closing it. Reopen if needed.
