### ISSUE TITLE
Wanted: Upgrade Font Awesome to v4.3.0

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12312]
### Summary
Feature request for Font Awesome upgrade!

### Observed behavior
40 new icons released in Font Awesome v4.3.0 are **not** available :cry: 

### Expected behavior
Upgrade to v4.3.0 so we can all use the new icons in the MODX Manager, such as: `bed`, `heartbeat`, `motorcycle`, `neuter`, and more!

Speaking of Feature Requests, should we consider providing a Feature Request template in the 
[contributing guidelines](https://github.com/modxcms/revolution/blob/master/CONTRIBUTING.md)?

**Comment by rtripault** [comment]
A template for FR might be a good idea indeed :)
