### ISSUE TITLE
2.3.3 changes in in widget.modx-news.php and widget.modx-security.php make admin panel loads longer 

### ISSUE THREAD

**Issue by manicko** [modxcms/revolution#12318]
After upgrade to the 2.3.3 get an error :Fatal error: Maximum execution time of 30 seconds exceeded in \manager\controllers\default\dashboard\widget.modx-security.php on line 17

the problem disappear if i comment lines 
if (function_exists('checkdnsrr') && !checkdnsrr('google.com', 'ANY')) {
     return '';
 }
as it was before

**Comment by manicko** [comment]
turning off news and feed does not help

**Comment by rtripault** [comment]
Hi @manicko , thanks for reporting the issue.

Could you please confirm your setup/installation has no access to internet ?
Thanks

**Comment by TheBoxer** [comment]
Closing for long inactivity, feel free to reopen with more details.
