### ISSUE TITLE
New FC rule to move core fields to different regions

### ISSUE THREAD

**Issue by GarretOverstreet** [modxcms/revolution#12313]
I would like to see a feature where one could move core fields to different tabs / regions similar to TVs.

For example, I'd like be able to move 'introtext' to 'modx-resource-main-right' or move 'published' to 'modx-custom-tab-name'.

It would require a bit of changes, but think it would be a great alternative to creating custom resource classes.

![fcset](https://cloud.githubusercontent.com/assets/3806848/5988208/7f61e98a-a91b-11e4-80e5-be775bec3fc9.jpg)

**Comment by Alroniks** [comment]
:+1:  It would be good.

**Comment by rainbowtiger** [comment]
I've asked for this before, too. It would greatly improve what we can do with FC.

**Comment by rtripault** [comment]
Somehow similar to #10505 so closing as duplicate.

Feel free to comment/reopen if needed.
Thanks

#modxbughunt
