### ISSUE TITLE
date output filter ordinal suffix support (st, nd, rd, th)

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12327]
### Summary
[According to RTFM](http://rtfm.modx.com/revolution/2.x/making-sites-with-modx/commonly-used-template-tags/date-formats), it does not seem possible to get the *English ordinal suffix (st, nd, rd, th)* using MODX date output filter. It seems `%s` and `%S` are already used for unix timestamp and Seconds.

### Step to reproduce
Try passing a timestamp through MODX date output filter to dynamically obtain the English ordinal suffix ```[[+date:date=`%B %e ...`]]```

### Observed behavior
Unable to output English ordinal suffix (e.g. February 4**th**)

### Expected behavior
Ability to output an ordinal suffix for the day of month in question e.g. *st, nd, rd, or th*

Is this a case of outdated RTFM, or is there not currently a way to mimic the 'S' character from PHP's internal `date` formatting via MODX `date` output modifier?

### Environment
MODX 2.3.3, PHP 5.3.29

**Comment by OptimusCrime** [comment]
According to the [code](https://github.com/modxcms/revolution/blob/master/core/model/modx/filters/modoutputfilter.class.php#L443) it uses `strftime` to output the date, not `date`. There are no equalent to `S` for ordinal suffix in ´strftime` according to the [docs](http://php.net/manual/en/function.strftime.php).

**Comment by pixelchutes** [comment]
Ahh, good catch. My oversight. Thanks!
