### ISSUE TITLE
When uninstalling packages, previous versions still appear in Package manager

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12324]
### Step to reproduce

Install any package (say AjaxManager 1.1.9 for example). 
Update it (e.g to v.1.2.0).
Uninstall it completely.
### Observed behavior

After complete uninstall of v.1.2.0, previous version (1.1.9) re-apprears in Package manager grid as downloaded, but not installed.
### Expected behavior

All versions of the package should be removed.

Revo 2.3.3-pl traditional

**Comment by exside** [comment]
Not sure if the expected behavior is really what you write =)...??

**Comment by whitebyte** [comment]
I'm not sure, bit this is counter-intuitive. It's strange to see "uninstalled" package in the list right after succesful uninstall.
