### ISSUE TITLE
Test packages by splittingred in package manager

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#12321]
Found 5 of them today in package manager. Seem to be there for a couple of years.

![bildschirmfoto 2015-02-02 um 18 29 54](https://cloud.githubusercontent.com/assets/667315/6005339/f279a9e0-ab09-11e4-9802-ed3631937b92.png)

Cheers,

pepebe

**Comment by TheBoxer** [comment]
Test packages removed :)
