### ISSUE TITLE
[2.3.3] Clear cache menu item stops working after first click

### ISSUE THREAD

**Issue by fractalwolfe** [modxcms/revolution#12320]
I just noticed that the clear cache option in the topbar stops responding to clicks after using it once. If you change page it starts working again, but only once per page load.

Can someone confirm this issue?

**Comment by whitebyte** [comment]
I can't reproduce this in latest FF and Chrome.

**Comment by TheBoxer** [comment]
Also can't reproduce.
Fell free to reopen with more details.
