### ISSUE TITLE
[Feature] Auto-suggest for context settings keys

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#12325]
### Summary
I run into this for years and thought I'd fix it in an issue to eventually address it: The key field for a context setting should be auto-suggesting existing keys from system settings when typing, this would prevent annoying copy and paste marathons when creating a new context and adding necessary settings to run it (for example as an independent site with own domain).

### Step to reproduce
Create a new context and add some basic context settings

### Observed behavior
We have to copy and paste (or remember) the setting key when adding it to a context

### Expected behavior
When starting to type in the "key" field a list of existing system setting keys is presented.

### Environment
MODX Revolution

**Comment by TheBoxer** [comment]
That's great feature.
Would you populate settings from all namespaces, or just from the one selected?

**Comment by exside** [comment]
mmh, good question, guess from the selected would reduce the ajax request payload a bit? So intuitively I'd go with that!
