### ISSUE TITLE
PHP 5.1.6 throws E_WARNING in session_set_cookie_params

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#12333]
### Summary
The session_set_cookie_params method in modx.class.php line 2434 adds all the cookie params, including httponly. But the httponly flag is only available as of PHP 5.2, while officially MODX supports 5.1+ (http://rtfm.modx.com/revolution/2.x/getting-started/server-requirements). This is causing an E_WARNING error when running MODX on 5.1.

### Step to reproduce

Run MODX on PHP 5.1 with error reporting and display errors on.  

### Observed behavior

![screen shot 2015-02-07 at 11 49 30](https://cloud.githubusercontent.com/assets/312944/6091848/6e74ff50-aebf-11e4-9fba-e96e1a1de486.png)

### Expected behavior
It shouldn't throw an error. Or, we shouldn't support 5.1 anymore.  :P 

### Environment
PHP 5.1.6. I see that 5.1.6 isn't officially supported (5.1.2 except 5.1.6) but MAMP doesn't seem to have a different version of 5.1 available.

**Comment by Mark-H** [comment]
Another one that happens on 5.2 is core/model/modx/transport/modtransportprovider.class.php line 346:
Fatal error: Call to undefined method SimpleXMLElement::count() which was added in 5.3.0 http://php.net/manual/en/simplexmlelement.count.php

So I guess develop (2.4) is for PHP 5.3 and up?

**Comment by rthrash** [comment]
Officially supporting ancient PHP versions it's not something I would vote to continue, if for no other reasons than security.

If they unofficially work in older versions, that's fine. Whatever the currently oldest maintained version of PHP is seems like a reasonable minimum version to keep up with. Security is too important today!

**Comment by OptimusCrime** [comment]
Going for 5.3 or 5.4 and up would make things a hell of a lot easier

**Comment by rthrash** [comment]
If we go with only supported versions of PHP that haven't reached EOL, that means 5.4+

http://php.net/archive/2014.php#id2014-08-14-1

**Comment by whitebyte** [comment]
So, if PHP 5.1.x is'nt supported, shouldn't this issue be closed?

**Comment by OptimusCrime** [comment]
+1

**Comment by OptimusCrime** [comment]
Close?
