### ISSUE TITLE
Custom manager theme CSS path in 2.3.3

### ISSUE THREAD

**Issue by pepitoe** [modxcms/revolution#12332]
In Modx 2.3.3 if you are using a custom manager theme the path to index.css is not inherited from the default theme correctly when a custom css file is not present.  The custom theme still attempts to load /manager/templates/custom/css/index.css instead of falling back to the default theme location.  This results in the manager loading in un-styled plain text once logged in.  In 2.2 the fallback/inheritance worked correctly.
Copying the css folder into the custom theme partially works around the issue but there are then further resources that don't load due to relative paths in the css, so at the moment it seems like you need to duplicate most of the default theme files in a custom theme.

**Comment by rtripault** [comment]
I'd say that's the intended behavior, either create your own index.css, or create `manager/templates/custom/header.tpl` with a link to the default index.css.

Just curious : how are you using custom manager theme if not to override the styling ?

**Comment by pepitoe** [comment]
In this case I'm only trying to customise the login page, and the documentation suggests that from 2.2 on you only need to make a copy of the files you are customising, so I only had login.tpl.  If this is expected behaviour on 2.3 then the documentation needs updating [here](http://rtfm.modx.com/revolution/2.x/administering-your-site/customizing-the-manager/manager-templates-and-themes)

**Comment by rtripault** [comment]
Sorry i did not get back to you... you are completely right, the default css should be used if no theme css is found
