### ISSUE TITLE
Update from grid (or inline editing) display bug in manager

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12356]
![bug-modx-theme](https://cloud.githubusercontent.com/assets/5160368/6141430/3c241fbc-b1e0-11e4-80ff-6806c5decb09.png)

When double-clicking on an editable text field in the manager, there is a display bug where you can see the old value behind the current value. See image.

**Comment by OptimusCrime** [comment]
What browser?

**Comment by digitalpenguin** [comment]
Firefox 35.0.1

**Comment by digitalpenguin** [comment]
I can confirm this is happening in Firefox on both Linux and Windows platforms.

**Comment by rtripault** [comment]
Not able to reproduce here with Iceweasel 35.0.1 (Debian Jessie) nor with Firefox Developer Edition 37.0a2 (2015-02-14) (still Debian).

Did you try disabling all your extensions, if any ?

**Comment by digitalpenguin** [comment]
Yes, all extensions disabled.

**Comment by TheBoxer** [comment]
Not able to reproduce on Windows 7 and OS X Yosemite in Safari, Chrome and Firefox

**Comment by digitalpenguin** [comment]
Thanks for looking into it. After further investigation it appears to have been caused by the Asset Manager extra. It was not uninstalling correctly so the manager was still being affected even though all extras appeared to be removed.
