### ISSUE TITLE
Smarty {$_config.manager_theme} var shouldn't be your custom theme if the file is loaded from default

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#12357]
Because when I just want to overwrite the header.tpl in my custom theme the css paths of the login are also written to my custom theme. In my header.tpl I can change that to a hard-coded "default" but I do not want to edit other templates for this.. Now my login page sucks, so I do not have any other choice I guess, but this isn't how it should work I think

**Comment by rtripault** [comment]
Closing as duplicate of #12332 (if i understand corrcetly ^^)

**Comment by bertoost** [comment]
Sorry! I searched before, but didn't find it..
