### ISSUE TITLE
Prevent empty manager theme

### ISSUE THREAD

**Issue by Lefthandmedia** [modxcms/revolution#12355]
While switching from manager theme in the system settings something went wrong and I ended up with an empty manager theme setting (manager_theme). After that the manager hardly works and the only way to fix this was to edit the database directly.
When loading the theme there should be a check and default to 'default' when empty

$theme = ($manager_theme != '')? $manager_theme : 'default';

**Comment by rtripault** [comment]
This is supposed to be the case, see https://github.com/modxcms/revolution/blob/master/core/model/modx/modmanagercontroller.class.php#L127

The only way i could see this going "wrong" is selecting a theme then delete its folder, or manually setting the value to a non existing theme

**Comment by Lefthandmedia** [comment]
Hi Romain,
no the theme folder was not deleted the theme setting was just empty.
this:  `$this->theme = $this->modx->getOption('manager_theme',null,'default');`
seems to just check if the setting exists but it does not check if its empty.
When you clear the setting in System settings  you end up with an unstyled / unmanageable manager.
You can recreate the problem by emptying the theme setting,
the code should be something like

`$this->theme = $this->modx->getOption('manager_theme',null,'default');
if($this->theme ==''){$this->theme='default'};
`

**Comment by Mark-H** [comment]
Setting a 4th param of true on the getOption would have the same effect.
Op 15 feb. 2015 01:31 schreef "Lefthandmedia" <notifications@github.com>:

**Comment by Lefthandmedia** [comment]
So the line should be
$this->theme = $this->modx->getOption('manager_theme',null,'default',true)

**Comment by OptimusCrime** [comment]
@Lefthandmedia did you ever open a pull request for this? Is it merged?

**Comment by Lefthandmedia** [comment]
I dont hink its ever been merged

**Comment by OptimusCrime** [comment]
Nice. Lets hope they merge it.

**Comment by OptimusCrime** [comment]
Fixed.

@modxbot close
