### ISSUE TITLE
Amazon S3 Buckets with Dots in Name Cannot Be connected to as Media Sources

### ISSUE THREAD

**Issue by aesop1** [modxcms/revolution#12363]
Modx doesn't connect to Amazon S3 Buckets with dots in the bucket name. Amazon requires some buckets to match domains (requiring dots) when a user wants to match the bucket to a particular domain. This issue has been reported before, but it keeps on being closed without any proof (that I can see) of resolution.

Here are two of the closed reports:
https://github.com/modxcms/revolution/pull/12034
https://github.com/modxcms/revolution/issues/12017

**Comment by aesop1** [comment]
Verified that when the following was commented out, the S3 Media Source bucket (with dots) started working:
 public function setBucket($bucket) {
         $this->bucket = $bucket;
//        if (strpos($bucket,'.') !== false) {
//            $this->driver->enable_path_style(true);
//        }

**Comment by Omeryl** [comment]
Hmm, can you show me your bucket URL? At the time I did that change it worked, but AWS might've changed something since then.

**Comment by aesop1** [comment]
//navisweb.meetnavis.com.s3-website-us-west-2.amazonaws.com

**Comment by adamwintle** [comment]
I'm also getting this issue with bucket: assets.domain.co.uk

**Comment by adamwintle** [comment]
@opengeek thanks for looking at this and marking it as priority.  For anyone interested I added some notes about this bug here: https://github.com/modxcms/revolution/issues/12017#issuecomment-170549972
