### ISSUE TITLE
How to use form array name with placeholder as key value?

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#12365]
For example:

<pre>&lt;input type="checkbox" name="list[[[*id]]]" value="true"&gt;</pre>

Notice the tripple [ and ]...
Should be written like this to make it work (without the spaces);

<pre>&lt;input type="checkbox" name="list& # 91;[[*id]]& # 93;" value="true"&gt;</pre>

Because MODX parses the the [ and ] not correctly. Above example works, but it's not very nice to use this way... Someone has figured this out?

**Comment by rtripault** [comment]
Closing as this no bug report nor feature request, but rather support, which is better suited in the [forums](http://forums.modx.com/).

Just to give some leads : did you try adding an extra space (ie. `name="list[ [[+placeholder]] ]"`) or single quotes (ie. `name="list['[[+placeholder]]']"` ?
I guess i've faced the problem and that how i solved it. One last option would be to build a snippet/output modifier to "wrap" your placeholder value, ie. ```[[snippet? &input=`[[+placeholder]]` &wrap=`list`]]``` which would return `list[parsedValue]`.
