### ISSUE TITLE
Permission for Manager Menu Actions needs Namespace checkForMenuPermissions()

### ISSUE THREAD

**Issue by jgulledge19** [modxcms/revolution#12360]
### Summary
Namespace is needed in core/model/modx/modmanagerresponse.class.php. If you add to custom CMPs to the menu or an existing Extra CMP that shares the same Action, like index. The checkForMenuPermissions() gets the first Action by the default order. This eliminates allowing to create permissions on the Menu item for those that share the same Action. 

### Step to reproduce
1. Create or install two CMP using the 2.3 method for Menus with an Action of index. I have QRBuilder: https://github.com/LippertComponents/QRBuilder and MIGX 2.8.1:http://modx.com/extras/package/migx. 
2. Now assign view_qrbuilder and view_migx to the respective Menus
3. Add the permissions to Policy: Access Control Lists -> Policy Templates -> Create or Update a policy then add the new permissions
4. Create one User Group called MIGX Users. Give permissions to access the Manager and then also view_migx 
5. Now create a second User Group called QR-Builder Users. Give permissions to access the Manager and then also view_qrbuilder.
6. Now create two users and assign one to each of the created groups.
7. Log in to a different browser one user at a time and try to access the allowed CMP, one of the users will not be able to access their CMP.

### Observed behavior
One of the users will not be able to access their CMP and will get the Access Denied page.

### Expected behavior
User should see their CMP.

### Environment
MODX 2.3.2 on MODX Cloud

**Comment by Mark-H** [comment]
Fixed in #12361 and #12255
