### ISSUE TITLE
Media Browser display different locations

### ISSUE THREAD

**Issue by Gallenkamp** [modxcms/revolution#12368]
Hi there,

when opening the media browser, you cant upload anything until you click on one of the folders to the left. Anyway, the browser shows the content of the last used folder.

Users dont understand it, because the tree is opened at the correct location. See the attached image.

Back: upload layer pointing into the wrong folder, menu expanded but not highlighted, file browser NOT presenting the CWD
Front: upload layer pointing into the correct folder, menu expanded and highlighted. FIle browser fits the CWD

![diff](https://cloud.githubusercontent.com/assets/2450164/6251618/367a59e0-b795-11e4-9a8f-2f591f065ccb.png)

This issue is as old as revo, i guess. Would be nice to have it fixed :)

**Comment by jcdm** [comment]
I've also experience this, but my installs allow the user to upload - everything just goes into the root folder when it's uploaded.

**Comment by Ruslan-Aleev** [comment]
Fixed in https://github.com/modxcms/revolution/pull/15227
Issue can be closed

**Comment by Ibochkarev** [comment]
@modxbot close
