### ISSUE TITLE
Feature Request: Change default action for containers in resource tree.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12375]
Peoples first reaction to expand a conainer in the resource tree is to click on the name instead of the arrow.
This opens the edit resource screen for that container and they get confused.

Can we make it so the default action for clicking on a container's name is to expand?
Only for resources that are tagged as containers of course.
And just add an edit option to its context menu?

Cheers!

**Comment by OptimusCrime** [comment]
I think this would be even more confusing. Having left click to two different actions in the menu would in most cases not make it easier for the users.

I suggest telling people, with emphasis, that they need to click on the arrow to expand/collaps.

**Comment by OptimusCrime** [comment]
Closing due to lack of feedback ad age. There's some improvements done to this in the overhaul of the manager in #12773 .

Feel free to reopen or comment if you feel this issue is not resolved sufficiently enough.

@modxbot close
