### ISSUE TITLE
Parameters are incorrectly passed to anchor links

### ISSUE THREAD

**Issue by tvld** [modxcms/revolution#12376]
If I have resource that as an url like #testimonial , which renders such as http://mysite.com#testimonial If I want to pass a parameter it should be passed such as  http://mysite.com?&tag=Snacks#testimonial
Currently [[~42? &tag=`Snacks`]]  generates http://mysite.com#testimonial?&tag=Snacks  which fails

**Comment by OptimusCrime** [comment]
You could just do 

```
[[~42? &tag=`snacks`]]#testimonial
````

?

**Comment by tvld** [comment]
but ~42 renders as http://mysite.com#testimonial  so that does not work
No, &tags should understand html specifications and insert at the correct position.  Real bug I think...

**Comment by OptimusCrime** [comment]
Really? Is the alias for resource 42 `#testimonial`? If that is the case I guess I could take a look at hacking this together.

**Comment by tvld** [comment]
yes, but that is by design. As we have one long home page, designed to scroll for tablets, we use multiple pages to build the home page. So we *override* the relative url Settings for the Page: URI: with a new relative one.

**Comment by OptimusCrime** [comment]
Okey, well, that makes more sense. I'll take a look at it

**Comment by OptimusCrime** [comment]
Aliases can not contain hashtags now. They are stripped upon saving the resource. Because of that, this issue is no longer relevant.

@modxbot close
