### ISSUE TITLE
Real links in Manager

### ISSUE THREAD

**Issue by jonas-veselka** [modxcms/revolution#12374]
Hi,
in Manager, there are links to Elements or Resources in the Elements/Resources tree. But these links are working only on javascript event onclick and their _href_ attribute is empty.
It causes that in some browsers on some actions (my case is middle mouse button click in Firefox) doesn't work properly. Instead of opening the element which I clicked in new tab, there is loaded the same page that was opened.
Is there any real reason why the _href_ attribute is empty, or it could be fixed?
Thanks

**Comment by OptimusCrime** [comment]
I would love to see this too. Kind of anoying having to deal with the javascript-links all the time.

**Comment by alroniks** [comment]
It seems it's already fixed. Now I can push cmd+mouse to open resource or element in the new tab. Not valid hrefs, but it was done using javascript and extjs.
So closing as solved.
