### ISSUE TITLE
minified bug

### ISSUE THREAD

**Issue by u007** [modxcms/revolution#12389]
Hi,

ive encountered this on several sites.
it seems that $hasVirtualManagerURL is overriding with $hasVirtualAssetsURL

the quick fix would be to check to ensure $hasVirtualManagerURL is false before checking for $hasVirtualAssetsURL

**Comment by OptimusCrime** [comment]
We are no longer using minified in the manager, which means that this should be fixed if you have upgraded to the last version.

Closing this. Feel free to reopen or comment if this is still an issue. I urge you to upgrade to the latest version if you have not done this already. It is not likely that this will be fixed for older versions.

@modxbot close
