### ISSUE TITLE
Feature: sanitize folder name during its creation

### ISSUE THREAD

**Issue by pawelmil** [modxcms/revolution#12385]
Is it possible to have eg. system setting for automatic change of folder name during its creatiion. sometimes users make in their mediasources folders like eg. "nowości pliki" and put there files for download...

**Comment by pepebe** [comment]
Don't know if this should be a core feature, but you can handle this with a simple plugin. I've successfully used the translit package from the repo to rename filenames sofar:

https://gist.github.com/pepebe/797b50ce6826b4dd470a

Your question made me realize that it should be enhanced to handle directories as well. Thank you!

Either fork it and add some actions OnFileManagerDirCreate and OnFileManagerRename and do a PR or wait for a couple of weeks for me to update it.

Cheers,

pepebe

**Comment by pawelmil** [comment]
Tank You very much! I'll check this.

W dniu 2015-07-20 o 09:10, pepebe pisze:
>
> Don't know if this should be a core feature, but you can handle this 
> with a simple plugin. I've successfully used the translit package from 
> the repo to rename filenames sofar:
>
> https://gist.github.com/pepebe/797b50ce6826b4dd470a
>
> Your question made me realize that it should be enhanced to handle 
> directories as well. Thank you!
>
> Either fork it and add some actions OnFileManagerDirCreate and 
> OnFileManagerRename and do a PR or wait for a couple of weeks for me 
> to update it.
>
> Cheers,
>
> pepebe
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/modxcms/revolution/issues/12385#issuecomment-122783207>.
>

-- 

Z poważaniem,
Paweł Milewski

<https://pvi.pl/>

AKTIZ Paweł Milewski
ul. Wspólna 5, 18-200 Wysokie Mazowieckie
NIP 722 131 83 13
e-mail: biuro@pvi.pl
tel. 86 270 98 81
www.pvi.pl <https://pvi.pl/>

**Comment by rtripault** [comment]
Thanks @mcnickel 

Indeed plugins/some extras could solve that, so closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @mcnickel
