### ISSUE TITLE
compress_js and compress_css does not work

### ISSUE THREAD

**Issue by u007** [modxcms/revolution#12388]
Hi,

i read in a forum that i could disable compress_js and compress_css.
on the manage screen login looks good, compression is off,
but once logged in,
everything is back to as it is. all compressed js and css.

**Comment by amdbuilder** [comment]
Did you delete the cache folder within the core directory?

**Comment by u007** [comment]
i cant recall, but i think i did

**Comment by amdbuilder** [comment]
Do you still have a problem using the manager with compress_css and compress_js disabled?  These settings are known to not work on some servers.

**Comment by u007** [comment]
ive manually fixed the assets issue on manager screen by making sure assets path is not replaced over manager path

**Comment by Mark-H** [comment]
Last comment seems to indicate the problem was resolved, and there are a number of other compress_js related issues such as #12478 #11142 and more, so I'm going to mark this one as closed. Please let me know if there is a reason this one should stay open.

**Comment by u007** [comment]
no, i hacked the minified code
