### ISSUE TITLE
improvement to news and security widget DNS check

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#12383]
### Summary

PHP's `checkdnsrr` function may exhibit buggy behavior in some environments. This may lead to PHP hanging and the web server timing out while rendering the manager's Dashboard view.

### Steps to Reproduce

This is in a Vagrant VM I'm in the process of building, so I can't share definite steps to make this reproduce-able. The VM, however is about as bare-bones as possible. See Environment below for details.

### Observed Behavior

I've encountered an odd bug in building a simple Vagrant environment for MODX. It's not a bug in MODX, and it almost seems like a bug in PHP, but it may also be a problem in my environment that leads to buggy behavior in PHP.

It boils down to this: when the `checkdnsrr()` function is called with "ANY" as the type parameter, PHP hangs. Indefinitely. This does not happen with any other valid value for the type parameter. I also cannot reproduce this in other environments, nor find evidence that this is a widespread problem.

### Expected Behavior

The manager's Dashboard view should not hang or time out as a result of the `checkdnsrr` function in the news and security widgets.

### Environment

* Vagrant VM based on an Ubuntu 12.10 base image
* Nginx 1.6.2
* PHP 5.5.12-2ubuntu4.2
* PHP fpm, cli, curl, mysql, xdebug packages
* MySQL Ver 14.14 Distrib 5.5.41, for debian-linux-gnu (x86_64) using readline 6.3

### Proposal

Although this may be an isolated problem, I'm proposing an improvement to these widgets which will not only solve the bug I'm experiencing, but could be seen as a small improvement to the DNS check in these widgets.

Currently, the widgets check for a response on "ANY" DNS type for the domain "google.com". The reason for this check is basically to make sure that the site is connected to the internet, before going ahead and attempting to read a feed.

I'm proposing to use the hostname for the actual feed being read, and to switch from the "ANY" type to just confirm an "A" record lookup for that hostname.

**Comment by Pont** [comment]
I experience this issue also on my host. It's shared hosting that uses load balanced virtual servers (they use NetApp and Nexenta). I have to remove the news widgets or edit the widget files and exchange "ANY" for "A" to be able to log in to the manager.
