### ISSUE TITLE
security/user/getlist processor unexpected behaviour

### ISSUE THREAD

**Issue by markwillis82** [modxcms/revolution#12397]
### Summary

When filtering the user grid on the "Manage Users" page within the manager if you filter by a usergroup and a keyword search you expect the keyword to filter inside the usergroup, however this does not happen
### Step to reproduce

Filter grid view by usergroup then add a keyword search for a user that is not in the group.
### Observed behavior

User appears when not in group that is filtered 
### Expected behavior

User should not appear. The search should be inclusive of all query items.
### Environment

MODX 2.2 and 2.3 are affected. When looking at the SQL that is executed it looks as though the WHERE clause is missing some brackets around the OR statements.

```
SELECT `modUser`.`id` AS `modUser_id`,
       `modUser`.`username` AS `modUser_username`,
       `modUser`.`password` AS `modUser_password`,
       `modUser`.`cachepwd` AS `modUser_cachepwd`,
       `modUser`.`class_key` AS `modUser_class_key`,
       `modUser`.`active` AS `modUser_active`,
       `modUser`.`remote_key` AS `modUser_remote_key`,
       `modUser`.`remote_data` AS `modUser_remote_data`,
       `modUser`.`hash_class` AS `modUser_hash_class`,
       `modUser`.`salt` AS `modUser_salt`,
       `modUser`.`primary_group` AS `modUser_primary_group`,
       `modUser`.`session_stale` AS `modUser_session_stale`,
       `modUser`.`sudo` AS `modUser_sudo`
FROM `modx_users` AS `modUser`
LEFT JOIN `modx_user_attributes` `Profile` ON `modUser`.`id` = `Profile`.`internalKey`
JOIN `modx_member_groups` `UserGroupMembers` ON `modUser`.`id` = `UserGroupMembers`.`member`
WHERE (`modUser`.`username` LIKE '%tui%'
       OR `Profile`.`fullname` LIKE '%tui%'
       OR `Profile`.`email` LIKE '%tui%'
       AND `UserGroupMembers`.`user_group` = '7')
```

**Comment by ilyautkin** [comment]
This commit https://github.com/modxcms/revolution/commit/886bdf8de4722301d73dc173ed2ad2c692416035 are fixed this bug, in my opinion. In 2.5.x the bug is not reproduced.

**Comment by OptimusCrime** [comment]
Looks good. Closing this as fixed then. @markwillis82 , it would be nice if you could double check this and verify too :)

@modxbot close
