### ISSUE TITLE
Errors when using CloudFlare?

### ISSUE THREAD

**Issue by albertdiones** [modxcms/revolution#12405]
Hi I got the following errors on my browser console when I'm using the manager's extension tab:

http://domain/v2/manager/min/index.php?f=/v2/manager/assets/modext/widg…ree.js,/v2/manager/assets/modext/widgets/core/tree/modx.tree.treeloader.js Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)
ext-base.js:21 Uncaught TypeError: Cannot read property 'prototype' of undefined
ext-base.js:21 Uncaught TypeError: Cannot read property 'prototype' of undefined
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'state' of null
    at CSRecorder.onQueryStateCompleted (chrome-extension://cplklnmnlbnpmjogncfgfijoopmnlemp/content_scripts/recorder.js:43:13)
ext-all.js:21 Uncaught TypeError: undefined is not a function
domain/:33 Uncaught TypeError: Cannot read property 'register' of undefined
http://domain/v2/manager/templates/default/fonts/fontawesome-webfont.woff?v=4.2.0 Failed to load resource: the server responded with a status of 522 (Origin Connection Time-out)

My MODx version is: MODX Revolution 2.3.3-pl (traditional)

This went on for hours til I realized I was on Cloudflare

I turned off Cloudflare and it worked, do you think this is MODx's error or Cloudflare's?

note: I replaced my domain with "domain"

**Comment by zaigham** [comment]
I think you will need to exclude /manager/ from Cloudflare caching. As you don't want manager to be cached.

**Comment by Mark-H** [comment]
This is an issue caused by some of CloudFlare's optimisations and not MODX specific. Have a look at https://support.cloudflare.com/hc/en-us/articles/201717894-Using-CloudFlare-and-WordPress-Five-Easy-First-Steps, replacing wp-admin with manager ;)
