### ISSUE TITLE
JavaScript Error after update to 2.3.3 in panel manager 

### ISSUE THREAD

**Issue by olegpro** [modxcms/revolution#12404]
```javascript
TypeError: Cannot read property 'prototype' of undefined
http://site.ru/manager/assets/ext3/adapter/ext/ext-base.js:21
```

On all pages.

**Comment by OptimusCrime** [comment]
Closing this due to lack of information and lack of popularity. It looks like this might have been a one-time thing that hopefully got resolved.

If this is still an issue, feel free to reopen or comment here.

@modxbot close
