### ISSUE TITLE
FR: "Create new resource here" icon next to document name in left menu

### ISSUE THREAD

**Issue by pawelmil** [modxcms/revolution#12407]
It would be nice to have "plus" icon next to document title in left menu that cereates new resource as subpage - the same as one next ro context name  in revolution 2.3. It would improve user experience.

**Comment by christianseel** [comment]
I get why you're requesting this, but also say that this would clutter the resource tree even more. So it could also be confusing…

Anybody else has an opinion on this?
#modxbughunt

**Comment by OptimusCrime** [comment]
I agree. If we did this it would be plusses everywhere in the tree. It is hard already to click where you are supposed to. Steering clear of adding more stuff to the tree is better imo.

**Comment by mintnl** [comment]
Agree with christianseel and OptimusCrime. Maybe there's an option of adding a "plus" at :hover, when the little bar turns blue?

**Comment by christianseel** [comment]
That's a good idea! I prepared a screenshot here:
<img width="326" alt="dashboard___modx_revolution" src="https://cloud.githubusercontent.com/assets/482184/23566244/61b148ce-0051-11e7-9ec6-4bffb203b163.png">

Now somebody need to build it into ExtJS :)

**Comment by OptimusCrime** [comment]
While that is a good idea on paper, we should avoid adding more things to the manager that does not work on a tablet og phone. Hovering is already much too overused in the manager is it is, and if we are going to make it tablet/phone-friendly that has to be solved in other ways.

**Comment by sottwell** [comment]
I dunno... my first reaction on seeing the screenshot was that this was to duplicate the resource. Really, is right-click, create-resource-here so much work?

**Comment by mintnl** [comment]
Agree with Sottwell about the click. But not about the plus, but thats besides the point ;-)

**Comment by christianseel** [comment]
I'm totally fine with saying we don't need this! 👍

**Comment by OptimusCrime** [comment]
Lets take a look at this in a future MODX manager overhaul. It will be difficult to incorporate this in the current tree.

@modxbot close
