### ISSUE TITLE
CodeMirror and Ace generates errors and breaks manager in MODX 2.3 - 2.3.3 

### ISSUE THREAD

**Issue by pawelmil** [modxcms/revolution#12406]
Hi, after installing Ace or Code MIrror in fresh modx install, some errors occurs and manager page breaks from time to time. 
Error log:
(ERROR @ /administracja/index.php) [OnHandleRequest]﻿
(ERROR @ /administracja/index.php) [OnManagerPageInit]﻿
This error happens from time to time. Manager page displays only top menu after this error and loads properly after pressing F5 in browser.
Can it be MOdx 2.3 issue?

**Comment by sottwell** [comment]
I've been using Ace all along with no problems. Perhaps more details of your platform?

**Comment by pawelmil** [comment]
Problem started after upgrading to MODX 2.3 and higher, I also tested it at fresh MODX 2.3.3 install. 
My environment:
MODX 2.3.3 Php 5.3.29, Apache 2.4.10, MySQL 5.6.12, Debian 7.0 64-bit, Direct Admin panel

**Comment by rthrash** [comment]
This sounds like something that's environment specific, especially since it's intermittent as indicated by "from time to time". Perhaps the PHP timeout is set too low, or there is not enough RAM allocated to the server. Closing for now, but feel free to re-open if you have more details.
