### ISSUE TITLE
Preparing for MySQL 5.7

### ISSUE THREAD

**Issue by the-dunnock** [modxcms/revolution#12401]
The upcoming release of MySQL 7.5 from Oracle will have new default SQL modes which will cause huge problems with MODX Revolution (and Evolution also). What changes is that SQL mode ONLY_FULL_GROUP_BY will be on by default so MySQL style GROUP BY's do not work.

Obviously to go around this issue is to set next into my.cnf:
sql-mode = "NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER"

This is the default without ONLY_FULL_GROUP_BY. Also this does not affect those who have sql-mode set into my.cnf already.

Later on this might also affect those who are using Percona Server or MariaDB if the new default sql mode is brought to them from Oracle's mysql build.

**Comment by Mark-H** [comment]
I'm not at all familiar with what Oracle is doing, but is there a way to fix MODX compatibility with MySQL 7.5 in our code?

**Comment by pixelchutes** [comment]
If it's anything like SQL Server, you can't `GROUP BY` anything that's not also in the `SELECT`.

**Comment by the-dunnock** [comment]
@Mark-H Yes, running command that sets session level sql-mode, that is just bubble gum fix. Then, the changes in core are really minimal (just modify tens of queries (or less if I recall right (have done it once))).

@pixelchutes I'm writing blog post about how to deal with upcoming changes in the MySQL. Trying to get it out this week and is aimed for extra developers in mind.

**Comment by goldsky** [comment]
https://github.com/modxcms/revolution/issues/12826#issue-121693438 patch works
I'm not reverting the SQL mode for this.

**Comment by Jako** [comment]
Are all MySQL 5.7 issues solved and could this be closed?

**Comment by Ibochkarev** [comment]
I vote to close this issue.

**Comment by alroniks** [comment]
I use MySQL 5.7 for testing 2.x and 3.x I have not met any issues since that time. So yes, it can be closed.
Feel free to reopen or even better create a new issue with the specific case.
