### ISSUE TITLE
Schema int type mismatched due to attributes="unsigned" not being placed on Foreign Keys

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#12419]
At first I thought this was an isolated occurrence, but have found it all over the place modx.mysql.schema.xml.

Examples:
### modUserProfile

``` xml
<field key="internalKey" dbtype="int" precision="10" phptype="integer" null="false" index="unique" />
```

Which is a FK for modUser id which has attributes="unsigned".
### modResource

``` xml
<field key="parent" dbtype="int" precision="10" phptype="integer" null="false" default="0" index="index" />
```

Which is a FK for modResource id which has attributes="unsigned".

This can be found all over the schema, wherever a Foreign Key is matched to a xPdoSimpleObject Primary Key.

Essentially, any record over 2147483647 in the child relationships will be mismatched and probably cause errors. 

xPdoSimpleObject can have a maximum of 4294967295 due to it being unsigned. This leaves quite a lot of room for records to no longer be synced due to a simple error.

The entire schema requires review and correction with an emphasis on any relation to the 'id' primary key - even within the same class.

**Comment by wshawn** [comment]
Still exists in 2.4.0

**Comment by alroniks** [comment]
Potentially can break backward compatibility, so tagged into 3.x version.

**Comment by JoshuaLuckers** [comment]
The PR to resolve this this issue has been merged into 3.x
