### ISSUE TITLE
Manager hangs when saving a sub page where the parent has html code in the title

### ISSUE THREAD

**Issue by intersel** [modxcms/revolution#12423]
I've got a page where the title page has html code and is:
International :<br><span style="text-transform: none;">The One Stop Shop Solution</span>

When I save the page, everything is fine and work perfectly.

I've got a children page with content...
Anytime I save it, modx Manager hangs with the "please wait... saving..." window... The page is saved but I need to reload the page with F5 to continue the job...

I've got the following error:
VM33482:1 Uncaught SyntaxError: Unexpected token ILLEGAL 
When I clicked on the given link 'VM33482, I've got the following content:
({"success":true,"message":"","total":0,"data":[],"object":{"id":138,"type":"document","contentType":"text\/html","alias":"financial-reporting","published":true,"pub_date":0,"unpub_date":0,"parent":94,"isfolder":false,"richtext":true,"template":16,"menuindex":1,"searchable":true,"cacheable":true,"createdby":1,"createdon":"2015-04-19 13:38:10","editedby":1,"editedon":"2015-04-19 14:29:12","deleted":false,"deletedon":0,"deletedby":0,"publishedon":"2015-04-19 14:12:00","publishedby":1,"donthit":false,"privateweb":false,"privatemgr":false,"content_dispo":0,"hidemenu":false,"class_key":"modDocument","context_key":"en","content_type":1,"uri":"our-expertises\/international-the-one-stop-shop-solution\/financial-reporting.html","uri_override":0,"hide_children_in_tree":0,"show_in_tree":1,"create-resource-token":"55339f90727905.53264760","reloaded":"0","parent-original":"94","parent-cmb":"International :<br><span style="\&quot;text-transform:" none;\"="">The One Stop Shop Solution&lt;\/span&gt; (94)","syncsite":1,"fltr_resource":"138","fltr_user":"","fltr_from":"","fltr_context_key":"","class":"","fltr_until":"","ext-comp-1058":"20","index":"1","follow":"1","tiny_toggle":"1","action":"resource\/update","resource_groups":"[]","preview_url":"\/en\/our-expertises\/international-the-one-stop-shop-solution\/financial-reporting.html"}}</span>)

When I remove the html tag from the parent title... no problem...

**Comment by wshawn** [comment]
I do not see this as a bug. 

There are much better ways of doing this, such as using a lexicon /placeholder/ snippet call / etc.

I have hundreds of dynamic pages which have a placeholder in the pagetitle / menutitle / longtitle subsequently populated when the page is created via a snippet call. Users are unaware and the sanity of the database structure remains intact.

You should also be aware, when I Googled your url, the closest match,which I believe is your site, does not allow users to click on the responding link to get to your site. Firefall/Waterfox insists on saving the page or making the user select the option to open it in a browser.

Once I cut the domain out and got to the site it looks nice.

**Comment by intersel** [comment]
You're right about doing such things other way but my concern was that the manager hanged with no apparent reason due to a problem on a parent page... and that can be a little frightening for a final user ;-)
Did not try if the problem still there on the 2.4.x versions

Thanks for your alert about my website... was it www.intersel.fr? as I'm not sure to see the problem you mentionned?

**Comment by Mark-H** [comment]
This was fixed with #13018, which will be included in 2.5.1.
