### ISSUE TITLE
Document is not saving when "/etc/" is in field of content

### ISSUE THREAD

**Issue by Tertiumnon** [modxcms/revolution#12429]
Document is not saving when
/etc/
is in field of content.

Console shows:
SyntaxError: expected expression, got '<' ext-all.js:2:0

modx traditional 2.3.3
checkbox Use HTML-editor is disabled

**Comment by zaigham** [comment]
Sounds like a mod_security issue?

**Comment by TheBoxer** [comment]
I can't reproduce this issue, feel free to reopen and provide more details.
