### ISSUE TITLE
Duplicating a context - missing entries in modx_media_sources_elements

### ISSUE THREAD

**Issue by MacConin** [modxcms/revolution#12428]
when duplicating a context from the tree (right-click-> duplicate context, the database table
modx_media_sources_elements is not properly updated.
TVs are not assigned to the duplicated context and have to be opened and saved again.
Other workaround is to change the table manually and insert the missing entries.

**Comment by Flowan** [comment]
Confirmed this in 2.5.x #13318 

Will have a look at this

**Comment by sonicpunk** [comment]
#modxbughunt #1point for @Flowan

**Comment by alroniks** [comment]
Solved by merged PR
