### ISSUE TITLE
Manager Tabs Always Going Back to Resources

### ISSUE THREAD

**Issue by alexcua** [modxcms/revolution#12439]
When I click on a Template, TV, Chunk or Snippet in the Elements tab, it returns to the Resources tab as soon as the element is loaded. It will expand the default context and close all others.
Clicking on anything in the Files tab does the same thing.

Behavior is normal if I click on anything inside the resource tab.

2.3.3 in ModxCloud.

**Comment by alexcua** [comment]
Still experiencing this issue. Is this just on modxcloud or just mine?

**Comment by OptimusCrime** [comment]
Do you have multiple windows open in your browser? The default tab is fetched from session data (I think).

**Comment by alexcua** [comment]
No. But it seems the issue was resolved in 2.3.5
