### ISSUE TITLE
User receives Permission Denied error message On Save Resource

### ISSUE THREAD

**Issue by jgulledge19** [modxcms/revolution#12447]
### Summary
User receives Permission Denied error message On Save Resource but page still saves correctly. User has limited permissions but permissions to save.
```
Code: 200 
OK {"success":false,"message":"Permission denied!","total":0,"data":[],"object":[]}
```
![on-resource-save-error](https://cloud.githubusercontent.com/assets/671767/7713136/c4a452a8-fe43-11e4-8350-75b3918fdaa5.jpg)

### Step to reproduce
 - Load these permissions into MODX: https://github.com/jgulledge19/MODX-ACL-Exports/tree/master/access-policies for a User group Context Access. ![usergroup-context-access](https://cloud.githubusercontent.com/assets/671767/7713607/e4f1aac6-fe46-11e4-85b0-db4acc07c091.png)
 - Create and assign some pages to it. Then in the same user group assign that Resource Group with the standard MODX Resource Access Policy for the mgr context. ![usergroup-resource-group-access](https://cloud.githubusercontent.com/assets/671767/7713769/cb45a356-fe47-11e4-96f8-1a43b5c52958.png)
 - Create a user assigned only to the created user group and log in with account
 - Edit a page that was assigned to the created Resource Group and then click Save.

I added the permission view_users as suggested in #12103 and it stopped the popup. But I do not what to give that permission to the user groups.

### Observed behavior
The error message in the photo above but the resource did save.

### Expected behavior
Save as normal. 

### Environment
MODX 2.3.3pl, nginx on MODX Cloud

Related to #12103 

Thanks for reviewing!

**Comment by TheBoxer** [comment]
Hello, this issue is related to VersionX which uses core processor to fetch users (which requires view_users permissions). Please report this issue to https://github.com/Mark-H/VersionX2

**Comment by jgulledge19** [comment]
I reported: https://github.com/Mark-H/VersionX2/issues/80 

Thanks!
