### ISSUE TITLE
feature request - allow admin to drag n drop resources

### ISSUE THREAD

**Issue by hcanning2014** [modxcms/revolution#12441]
...but deny other users (editors) if needs be in the manager navigation tree.

**Comment by rtripault** [comment]
Hi,

I'd say this is already doable. Just set system setting `enable_dragdrop` to `no` to disable drag & drop globally, then either : 

* create the same user group setting (with a value of `yes`) if you want to enable the feature for a user group, or 
* create a user setting for each hand picked users you want to be able to use drag & drop

Hope that makes sense/fills your need.

**Comment by hcanning2014** [comment]
How would I go about creating the same user group setting? I'd that a checkbox in Access Policies or someplace? Thanks

**Comment by hcanning2014** [comment]
*Is that

**Comment by rtripault** [comment]
In Revolution, drag & drop is not considered as a right (so not handled by ACL/policies), but as a setting.

To create a user group setting (Revo 2.3+) :

1. head over to Access Control List (found in the "cog" menu)
2. update the desired user group (ie. "Administrators")
3. in the "settings" tab, hit the "create new" button and fill in the setting details

Same would apply for a particular user ("Manage" > "Users")

Note : your user(s) might need to log in again to "refresh" their settings.

Hope that will help.

**Comment by hcanning2014** [comment]
Where can I find out what to populate the settings with? Like what even goes into the boxes? Totally lost in here. Any direction appreciate or link to how-to appreciated. Following http://www.webhostinghub.com/help/learn/modx/managing-modx/creating-system-settings right now. Thanks
![how-to](https://cloud.githubusercontent.com/assets/6403224/7652587/0dfa10ca-fadc-11e4-987a-5d32a443f8e2.PNG)

**Comment by hcanning2014** [comment]
Perfect .. what a great feature. Thanks!

**Comment by rtripault** [comment]
Hm sorry, i may have assumed too many things.

Head over the system settings ( "cogs" menu > "system settings") and search for setting `enable_dragdrop`.

Edit/update the setting and set its value to "no" to disable drag & drop feature for everyone/globally.

Then, in your user group settings, create the same `enable_dragdrop` setting and copy all fields values from the original system setting, besides the "value" field, which you would want to set to `1`.

Hopefully this time will be the good one!

**Comment by hcanning2014** [comment]
Great thanks

**Comment by rthrash** [comment]
Hi Howard, did Romain's solution address your need?

**Comment by OptimusCrime** [comment]
With the lack of response I'd say yes

**Comment by hcanning2014** [comment]
Yes it worked thanks.

**Comment by OptimusCrime** [comment]
Please close then :)
