### ISSUE TITLE
svg preview in file manager

### ISSUE THREAD

**Issue by Pfeifakopf** [modxcms/revolution#12459]
Please add the svg support in the file manager.

**Comment by natedin** [comment]
+1 would like to see this added

**Comment by frischnetz** [comment]
+1 (imageTV preview for SVG is also broken)

**Comment by pixelive** [comment]
I'm going to try and fix this today.

**Comment by RinzeVanDerBrug** [comment]
Tested this in MODX 2.5.5.

It IS possible to add a .SVG file, but you are not able to view a thumbnail. #modxbughunt

**Comment by udovichenko** [comment]
+1 Looking forward to this!

**Comment by mazyone** [comment]
+1 would like to see this added

**Comment by OptimusCrime** [comment]
This is an interesting issue as thumbnails are generated though phpThumb, which (as far as I know) does not handle .SVG files. SVG files are just vector data. Perhaps it could be possible to have a special connector handler for just this file type. It would be interesting to look closer at this.

**Comment by frischnetz** [comment]
A first approach could be to just skip thumbnail generation for SVG-files and show the files directly.

**Comment by OptimusCrime** [comment]
I am not too familiar with the SVG filetype, but how does that define image size? Can you (with HTML) display a SVG and scale it accordingly? Like defining a maximum height and/or width and everything happens by itself, or does it require more "magic" than that?

**Comment by frischnetz** [comment]
It's complicated :-) There are options inside the SVG to set a size and viewbox and aspect-ratios. And you can use SVGs as imgs, as objects and inline-code and iframe and background-image. But usually it works for most files to use it just in an img-tag with a fixed size. Everything is better than no image at all.

https://css-tricks.com/scale-svg/

**Comment by alroniks** [comment]
It seems that all related PRs merged and feature already released. So closing it.
