### ISSUE TITLE
When have more than 20 template variables got 20 browsers refreshes

### ISSUE THREAD

**Issue by Codenator81** [modxcms/revolution#12450]
When I add on 2.3.2 many template variables got browser refreshes. It is language design problem?
extjs problem? Can we rebuild template variable to make it more powerful?

**Comment by OptimusCrime** [comment]
Unless there is more information here I suggest closing. I have no idea what the issue is here.

**Comment by rthrash** [comment]
Can you provide more details on how to reproduce this @Codenator81? Thanks!

**Comment by Codenator81** [comment]
There issue not about 20 TV but about browser refreshes as many time as TV is in document. If u look in browser tab when navigate to document and open TV tab there something like refreshes. Just my client complain about this and I reproduse

**Comment by OptimusCrime** [comment]
I am pretty sure those are ajax calls?

**Comment by Codenator81** [comment]
yes

**Comment by OptimusCrime** [comment]
Well...I think that is intended behavior. I can't understand what is wrong with those ajax calls?

**Comment by TheBoxer** [comment]
I don't really understand the problem here... 

Data for TVs are not fetch via AJAX, but from Resource controller.

**Comment by OptimusCrime** [comment]
Me neither
