### ISSUE TITLE
An error occurred when trying to save the policy

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12453]
MODX 2.3.3

Tried to create a policy called "Developers". It gave me the error "An error occurred when trying to save the policy."

I changed the name to "Develop" and tried saving again. It worked.
Immediately tried changing back to "Developers". Same error.

Came back to it a bit later and tried changing again to "Developers". It worked this time.

Has anyone else experienced something like this? Odd.

**Comment by OptimusCrime** [comment]
Not able to reproduce.

**Comment by OptimusCrime** [comment]
Closing due to age and lack of feedback. Like I said almost a year ago, I am not able to reproduce this at my end.

Feel free to comment or repoen this if this is still an issue.

@modxbot close

**Comment by digitalpenguin** [comment]
Yeah best closed. I haven't seen this happen in any version after 2.4
Cheers

**Comment by OptimusCrime** [comment]
Thank you for feedback @digitalpenguin :)

If you experience this again, please contact us and we'll investigate further.
