### ISSUE TITLE
Container resources are available by urls both with and without container suffix

### ISSUE THREAD

**Issue by sitex-pro** [modxcms/revolution#12465]
### Summary

If we turn furls on and create a container, it will be available by both urls: site.com/container and site.com/container/ - regardless of the value of [friendly_urls_strict] setting. 
### Step to reproduce
1. Install modx 2.3.3-pl
2. rename ht.access to .htaccess
3. set [friendly_urls_strict] on
4. create container
### Observed behavior

One can access container's page both slash and without a slash at the end of url
### Expected behavior

301 redirect to the url with trailing slash should occur when accessing container's page without trailing slash
### Environment

modx 2.3.3-pl
### How to fix

file /core/model/modx/modrequest.class.php, comment out the unwanted line 332:
$identifier = "{$identifier}{$containerSuffix}";
followed by line:
$found = $this->modx->findResource("{$identifier}{$containerSuffix}");

**Comment by shamarin** [comment]
On modx revo 2.5.2 it's not fixed.

**Comment by shamarin** [comment]
Also main paige of site is available via index.php. It would be nice to make 301 redirect site.com/

**Comment by Mark-H** [comment]
Fixed in 2.7 per #13142
