### ISSUE TITLE
No log entries for non-existent snippet calls?

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12467]
### Summary

When we call a non-existent snippet, it silently fails (e.g. produces no output at all). I think it should add some kind of warning into the MODX logs, because it's a source of non-obvious errors.
### Environment

MODX 2.3.x

**Comment by TheBoxer** [comment]
You can create a plugin which will let you know about non-existing snippet call. I don't think that this should be part of the core...

**Comment by whitebyte** [comment]
Of course i do, but undefined snippet call is an exceptional condition and shouldn't be just silently ignored by default. This is really frustrating in certain cases. We recieve warnings and errors in PHP when trying to call some non-existent stuff, so why MODX parser shouldn't do the same? This is expected behavior.

**Comment by sottwell** [comment]
+1 (for what it's worth, I think this would be a good idea)

**Comment by inreti** [comment]
+1. MODX core should support development as good as possible. Logging these could help a lot.

**Comment by Alroniks** [comment]
+1 for logging.

**Comment by garryn** [comment]
This would be good if the error message also logged what element it was called from (and/or resource). Perhaps have it on log level INFO too.

**Comment by rtripault** [comment]
:-1:  here.

This is something useful for development "only", and already possible with the existing events system (as explained by @theboxer). Should be up to the developer(s) to set their tools/environment.

On an another hand, :+1: for having more properties available as suggested by @garryn (for what it worth, `OnElementNotFound` is triggered from [modParser::getElement](https://github.com/modxcms/revolution/blob/develop/core/model/modx/modparser.class.php#L564)

**Comment by mindeffects** [comment]
:+1: Actually it's a :+10: from my site (no icon for that), because I already spent hours searching for typos in snippet/chunk calls! So, yes, error log, please!

BTW: The whole error-log is for "developers only". So, either we kick it completely out or do it in a proper way! ;-)

**Comment by OptimusCrime** [comment]
I just submitted a pull request with this functionality. Feel free to take a look at it: #12984.

**Comment by Mark-H** [comment]
Will be included in 2.6. There's a setting to turn it off.
