### ISSUE TITLE
Wrong value of [^p^] tag - almost always "0,0000 s"

### ISSUE THREAD

**Issue by sitex-pro** [modxcms/revolution#12474]
### Summary
Tag [^p^] produces wrong value.

### Step to reproduce
Add this code to the bottom of a page template:
MySQL: [^qt^] ([^q^] queries) PHP: [^p^] Total: [^t^]

### Observed behavior
MODx prints "0,0000 s" instead of [^p^] tag.

### Expected behavior
MODx should print some value other than 0,0000 s

### Environment
MODX 2.3.3-pl, phpinfo: http://psychoid.ru/phpinfo.php

### How to fix
In file /core/model/modx/modresponse.class.php replace lines 107 - 113 with these:
            $totalTime= (microtime(true) - $this->modx->startTime);
            $queryTime= $this->modx->queryTime;
            $queryTime= sprintf("%2.4f s", $queryTime);
            $queries= isset ($this->modx->executedQueries) ? $this->modx->executedQueries : 0;
            $totalTime= sprintf("%2.4f s", $totalTime);
            $phpTime= $totalTime - $queryTime;
            $phpTime= sprintf("%2.4f s", $phpTime);

**Comment by zaigham** [comment]
You should do a pull request. :smiley:

**Comment by pixelchutes** [comment]
I can't seem to reproduce this. Tested, confirmed working in MODX 2.3.5-pl.

### Three separate tests:

> PHP: [^p^] outputs: PHP: 0.2117 s
> PHP: [^p^] outputs: PHP: 0.2331 s
> PHP: [^p^] outputs: PHP: 0.2033 s

Can you attempt to upgrade and verify again?

**Comment by sitex-pro** [comment]
zaigham, created a pull request, thanks.
pixelchutes, this was because of locale that uses comma as decimal point.

In modx 2.3.5-pl behavior is the same.

lines:
> $queryTime= sprintf("%2.4f s", $queryTime);
> $totalTime= sprintf("%2.4f s", $totalTime);
> $phpTime= $totalTime - $queryTime;

result in smth like:
"0,4321 s" - "0,1234 s"

You can make a test:
```php
<?php

setlocale(LC_ALL,'en_US.utf8');
$arg1 = sprintf("%2.4f s", 0.4321);
$arg2 = sprintf("%2.4f s", 0.1234);

echo $arg1 - $arg2;

echo "<br />";

setlocale(LC_ALL,'ru_RU.utf8');

$arg1 = sprintf("%2.4f s", 0.4321);
$arg2 = sprintf("%2.4f s", 0.1234);

echo $arg1 - $arg2;

?>
```
Results are:
> 0.3087
> 0

**Comment by pixelchutes** [comment]
Ah, great catch! Thanks for the PR.

**Comment by Mark-H** [comment]
@sitex-pro it looks like you may have made this pull request on your own fork. Could you create it on modxcms/revolution? ;)

**Comment by sitex-pro** [comment]
@Mark-H oh, thanks for letting me know :) I'll try to do it right now
