### ISSUE TITLE
Output filter returns $input on empty or null

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#12476]
This is an old one that has not been solved so far.

http://forums.modx.com/thread/72494/custom-outputfilter---return-empty-string

If I build an output filter that returns "nothing", the output filter returns the original input.

My test snippet

```
<?php
/* 
   test output filter 
   [[*id:test]]
*/
return "";
```

attached to a placeholder

```
[[*id:test]]
```

will automatically return the id of the current resource instead of "nothing".

I don't see the benefit of this behavior.

Is there anyting that I'm missing?

Regards,

pepebe

**Comment by pepebe** [comment]
I've done some research. Seems the lines 659+ in https://github.com/modxcms/revolution/blob/092e698b81f65c11eab263d3a74c44ebd2521a2d/core/model/modx/filters/modoutputfilter.class.php explain this behaviour:

````
$tmp = $this->modx->runSnippet($m_cmd, $params);
if ($tmp!='') $output = $tmp;
break;
````

As a consequence the original value is always returned by $output if the return value is empty.

I guess most of us have found some kind of dirty workaround for this problem. To make this solution backward compatible, I suggest the following solution:

````
$tmp = $this->modx->runSnippet($m_cmd, $params);
if (!empty($tmp)) { // return anything but Null or empty.
    $output = $tmp;
}
elseif(is_null($tmp)) { // return Null by your snippet if you don't want to return anything.
    $output = '';
}
else { // !empty() OR !iy_null() - return an empty string to get the original value
    $output = $output;
}
break;
````

**Comment by pepebe** [comment]
I just thought that a system setting could solve the whole problem:

 ++empty_output_filter_returnvalue 
Allowed values: 
* placeholder - default behaviour, so we don't break anything)
* empty - just return nothing at all

```
$tmp = $this->modx->runSnippet($m_cmd, $params);
if (!empty($tmp)) {
   $output = $tmp;
}
else{
   $rv = $this->getOption('empty_output_filter_returnvalue ', NULL,'placeholder',true);
   if($rv != 'placeholder') {
      $output = '';
   };
}
break;
```

**Comment by OptimusCrime** [comment]
I'm afraid this is actually a cantfix. At least with the current way we do things. This would lead to a HUGE breaking change. Reason is:

Snippet 1:
```
return null;
```

Snippet 2:
```
return '';
```

All these twosnippets evaluate to the following:
```
string(0) ""
```

This means that if you want to display a empty string, you also do the same for `null`. This will break a implementation that a lot of people currently rely on. I see no way to get around that without breaking a lot of sites.

Optionally, to get the functionality you want, you could to something like:
```
[[*id:test:eq=``:then=``]]
```

This outputs nothing. Not perfect, I know, but I can't say changing the behavior for `null` handling is that much better at this point.

**Comment by JoshuaLuckers** [comment]
@OptimusCrime Since this might be a breaking change, maybe it's a good idea to implement a change in this behavior in MODX 3?

**Comment by OptimusCrime** [comment]
Depends. Should this be implemented? Does not seem like something a lot users have had problems with.

**Comment by alroniks** [comment]
Based on the discussion I am closing it as wontfix.
