### ISSUE TITLE
What triggers the "Configuration warning: Config file still writable!"?

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#12485]
Hi guys,
this is one of the most unimportant things, but I just wonder about the logic of the configuration warning "Config file still writable!". I ran some tests:
```
444 r--r--r-- OK
644 rw-r--r-- OK
466 r--rw-rw- OK
666 rw-rw-rw- Warning

644 rw-r--r-- OK
464 r--rw-r-- OK
446 r--r--rw- OK

664 rw-rw-r-- OK
646 rw-r--rw- Warning
```
644 and 466 are OK? Both?
But who should NOT be allowed to write? The owner, which is the webserver itself? The group? Or the others?
Just curious.

**Comment by OptimusCrime** [comment]
I am guessing the user you are executing php with?

**Comment by OptimusCrime** [comment]
Closing due to lack of feedback. I know there were problems with this widget in the beginning, which has been closed since.

Feel free to comment or reopen if you still experience these problems, @mindeffects 

@modxbot close
