### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by ColinRyan** [modxcms/revolution#12499]
When I attempt to login to Modx I get sent back to the login screen. No errors of any kind. I've checked the database and modx_session shows a new session. As well, modx_user_attributes increments my login count, suggesting to me that I have been authenticated. I've changed the password via phpMyAdmin and I've tried different different browsers. I've truncated modx_session and I've cleared browser history. This isn't a fresh install and I have been able to login before. 

The behavior of the issue is similar to what has been described here:http://tracker.modx.com/issues/6465

The version I'm using is MODX Revolution 2.2.14-pl.

Any ideas as to what might cause this?

Thanks!

**Comment by Mark-H** [comment]
Try clearing your browser cookies. I've also seen that happen when the site's base url or cookie path setting was set incorrectly, causing it to be unable of setting the cookie on your browser.

**Comment by Mark-H** [comment]
That said, this is a discussion that should probably take place on the forums instead of here in the bug tracker, unless an actual core bug is discovered.
