### ISSUE TITLE
Bug: Resource Tree not refreshed when new context created

### ISSUE THREAD

**Issue by wuuti** [modxcms/revolution#12495]
### Reproduce

When you create a new context, it is displayed immediately in the contexts grid, but not in the resource tree. The resource tree is not refreshed, you have to reload the page to see the new context there.

**Comment by RinzeVanDerBrug** [comment]
I'm going to review this today.

**Comment by RinzeVanDerBrug** [comment]
Able to reproduce.

Tested this on macOS Sierra (10.12.3) in Chrome v56.0.2924.87.

Confirmed, still an issue in MODX 2.5.5. #modxbughunt

**Comment by sottwell** [comment]
Related? Have the Contexts page open in the Manager, delete a context using the context menu in the Tree, the context is deleted from the Tree but not from the Contexts page, and of course trying to delete it again from the page throws an error, without refreshing the list.

**Comment by Oetzie** [comment]
I'm going to try and fix this today.
