### ISSUE TITLE
Security > Manage User Overview

### ISSUE THREAD

**Issue by crimsonpixel** [modxcms/revolution#12505]
This is a feature request - would it be possible to have additional columns selectable in the overview. For example the lastlogin, logincount and possibly telephone number as well.

**Comment by syts88** [comment]
I'm going to try and take a look this today. #modxbughunt

**Comment by OptimusCrime** [comment]
No feedback or comment in more than two years. Going to close this off. Feel free to comment or reopen. If you want this particular functionality I guess you could create a Extra that does this. The Manager User Overview is mostly used to handle users, permissions and groups. I don't see how mixing this with a compact information grid is possible with todays implementation. Still, should be very much doable with a simple custom component.

@modxbot close
