### ISSUE TITLE
modRest is loosing http header

### ISSUE THREAD

**Issue by vguna** [modxcms/revolution#12500]
I'm using modx 2.3.4 with its modRest client. It seems that it looses headers when I'm sending json requests. I found the problem within the order of the prepare function:

``` php
    protected function prepare() {
        $this->prepareHandle();
        $this->prepareAuthentication();
        $this->prepareUrl();
        $this->preparePayload();
        $this->prepareHeaders();
        $this->prepareRequestOptions();
    }
```

prepareHeaders() replaces any existing headers set by preparePayload (I'm using json POST).
Caling prepareHeaders() before preparePayload() seems to do the trick.

**Comment by Mark-H** [comment]
Could you share some example code of what you're doing? What header is it overwriting?

**Comment by vguna** [comment]
Sure, but it doesn't matter what header is set :). Just do a POST to somewhere using an array as JSON content. You'll see that e.g. the content-type header (application/json), set by the preparePayload() method, gets cleared by prepareHeaders(). It simply creates/sets a new array instead of adding its headers. That leads to a (default?) form-related content-type which is send to the server. Which isn't correct.

```php
$userData = array(); // my user data array that is converted to json

$config = array (
		'baseUrl' => 'myurl',
		'format' => 'json', // json or xml, the format to request
		'suppressSuffix' => true, // if false, will append .json or .xml to the URI requested
		'curlOptions' => array (
				CURLOPT_TIMEOUT => 60 
		), // cURL request timeout in seconds
		'userAgent' => 'MODX RestClient/1.0.0' 
);

$modRestClient = new modRest($modx, $config);

$result = $modRestClient->post('user', $userData);
```

**Comment by JoshuaLuckers** [comment]
To reproduce this issue:

The code below will automatically add the header "Content-Type: application/json; charset=utf-8" set by preparePayload().
```php
<?php
$modx->getService('rest','rest.modRest');

$config = [
    'baseUrl' => 'http://example.com/api/',
    'format' => 'json',
    'suppressSuffix' => false,
];

$client = new modRest($modx, $config);

$result = $client->post('/resources',[]);
$response = $result->process();
```

But when adding headers via the config array the headers previously being set by preparePayload() will be overwritten:
```php
<?php
$modx->getService('rest','rest.modRest');

$config = [
    'baseUrl' => 'http://example.com/api/',
    'headers' => [
	    'Authorization' => 'Api-Key secretkey',
    ],
    'format' => 'json',
    'suppressSuffix' => false,
];

$client = new modRest($modx, $config);

$result = $client->post('/resources',[]);
$response = $result->process();
```

**Comment by JoshuaLuckers** [comment]
This issue may be closed.

**Comment by Mark-H** [comment]
Thanks Joshua
