### ISSUE TITLE
Chmod'ing a directory from file tree should check for valid value

### ISSUE THREAD

**Issue by garryn** [modxcms/revolution#12508]
Chmod'ing a directory currently allows any text to be passed as the chmod value - MODX should be checking for a valid value.

Passing a non-valid value (e.g. "lockmeout") as the chmod value can lock the permissions down on the folder making it impossible to access until you chmod it back correctly via SSH/Cpanel etc.

**Comment by Mark-H** [comment]
hmm I wonder if this should be checked in the browser/directory/chmod processor, or in the modMediaSource->chmodContainer method? Or both?

**Comment by garryn** [comment]
I think the check should be in modFileMediaSource::chmodDirectory() and let the error bubble up through the processor (if I'm reading the code right, I haven't looked too long at this). Thoughts?

**Comment by garryn** [comment]
Actually, having looked, checking it in modFileResource::chmod() makes more sense.

**Comment by Mark-H** [comment]
Fixed in 2.3.6

**Comment by OptimusCrime** [comment]
I can take a look at this

@OptimusCrime

**Comment by OptimusCrime** [comment]
New PR opened. #modxbughunt

**Comment by OptimusCrime** [comment]
This is fixed now :)

@modxbot close
