### ISSUE TITLE
error in long filenames of TV propertyes

### ISSUE THREAD

**Issue by Setest** [modxcms/revolution#12501]
For example we create custom TV type with long filenames, and we have structure:
- input/veryverylllongfilenameeeeee.tpl
- inputproperties/veryverylllongfilenameeeeee.tpl

If we wont open Properties of TV in manager with current TV, what we will get? NOTHING! Because in query to server http://www.domain.ru/connectors/index.php
we have next attrs:
- action:element/tv/renders/getInputProperties
- context:mgr
- tv:1
- type:**veryverylllongfilena**

Only 20 symbols in type... probably this appear after my experiments with filename but i think evil lies in:

``` html
<input type="text" size="24" autocomplete="off" id="modx-tv-type" class="x-form-text x-form-field modx-combo x-trigger-noedit x-form-focus" style="width: 1168px;" readonly="">
```

And it look more than strange, because we see maximum in 24 symbols in input field.

MODX Revolution 2.3.3-pl (traditional). Browser: Opera 30.0.1835.88

**Comment by Mark-H** [comment]
The "type" field in the database is set with a precision (length) of 20:

```` xml
<field key="type" dbtype="varchar" precision="20" phptype="string" null="false" default="" />
````

You'll likely need to use shorter input names. ;)

Longer term it would also be possible to increase the length of the type field to accommodate longer names.

**Comment by pixelive** [comment]
I think this one can be closed, this is indeed the database field who limits it.

#modxbughunt

**Comment by rtripault** [comment]
Closing.
Feel free to comment/reopen if needed.

Thanks
