### ISSUE TITLE
Add SVG, TTF and MD to uploadable file types

### ISSUE THREAD

**Issue by inreti** [modxcms/revolution#12519]
Currently the following filetypes are allowed for uploading:

`txt,html,htm,xml,js,css,zip,gz,rar,z,tgz,tar,htaccess,mp3,mp4,aac,wav,au,wmv,avi,mpg,mpeg,pdf,doc,docx,xls,xlsx,ppt,pptx,jpg,jpeg,png,gif,psd,ico,bmp,odt,ods,odp,odb,odg,odf`

`svg,svgz`, `eot,ttf,woff` and `md` are missing here. They should be added by default as they are standard file types in web projects. I am also missing `tiff` here.

**Comment by markwillis82** [comment]
This has now been merged
