### ISSUE TITLE
Default Per Page number of packages listed not related to the Default Per Page System Setting

### ISSUE THREAD

**Issue by boostventilator** [modxcms/revolution#12518]
The System Settings has a preference called Default Per Page (default_per_page), described as “The default number of results to show in grids throughout the manager”, but this number is not being used as the default number of packages listed per page in the manager.

**Extras > Installer > Package Management > Packages > Per Page = 10**

Instead it is just set as 10 in here:

**Path:** manager/assets/modext/workspace/package.grid.js
**Line 86:** `,pageSize: 10`

**Comment by netProphET** [comment]
Confirmed behavior. Going to try to fix this #modxbughunt

**Comment by netProphET** [comment]
This was likely overridden for performance reasons. On discussion with opengeek and rtripault in #modxbughunt, I'm going to propose a fix that uses the `default_per_page` setting but limits it from being too high. Will hard-code that limit to 25 for now, but perhaps making that upper limit a system setting could be discussed as a separate feature request.

**Comment by netProphET** [comment]
Pull request created #modxbughunt 
https://github.com/modxcms/revolution/pull/13348
