### ISSUE TITLE
A simple search across chunks / snippets

### ISSUE THREAD

**Issue by dennis-f** [modxcms/revolution#12521]
As we work in bigger teams we often need to find content thats IN chunks/snippets/templates etc. Right now it's easier for us to sumply search in the database tables via phpmyadmin. So why is there nothing like a search across elements!?

**Comment by OptimusCrime** [comment]
I think fulltext search is one of the pending pull requests here somewhere.

**Comment by dennis-f** [comment]
sry didn't find it

**Comment by OptimusCrime** [comment]
I am wondering if #12515 might add this feature, but I am not sure.

**Comment by pepebe** [comment]
The initial PR will add this and much more.

![28120694-b7b5-11e4-8788-30a793f37d40](https://cloud.githubusercontent.com/assets/667315/8825297/5df0bd04-307e-11e5-8b84-e55e03ff3810.png)

Future PRs will add some eye candy and more search options.

Before this happens it must pass the ever watchful eyes of our beloved integrators...

**Comment by dennis-f** [comment]
alrighty then ...
