### ISSUE TITLE
Should MODx.on('ready') Event Firing on Resource Save?

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#12530]
Noticed some recent bugs in Extras due to this behavior. According to @Mark-H it has been happening for awhile but I'm curious if this is a bug or not. Couldn't find docs to clarify.

It seems like the 'ready' event should just fire the one time.
I looked for a duplicate issue but couldn't find one.

**Comment by OptimusCrime** [comment]
Two years with no answer. Going to close this due to lack of feedback and details. If this is still an issue today, feel free to comment or reopen the issue.

@modxbot close
