### ISSUE TITLE
"sendRedirect" with "//" protocol don't work properly + eventually bugfix (to check)

### ISSUE THREAD

**Issue by Jacqbus** [modxcms/revolution#12547]
### Summary
"sendRedirect" doesn't work properly for protocol "//" (for choosing http or https).

### Step to reproduce
Fresh install of MODX Revolution 2.3.2-pl (traditional) and:
+ Friendly URL enabled
+ one resource with alias "some-thing"
+ simple plugin with "OnWebPagePrerender" event attached and with follow code (of course change sitename.com to real domain!):
```
// Force redirect to this resource
$modx->sendRedirect('//sitename.com/some-thing');
```

### Observed behavior
It redirect me to: "http://sitename.com//sitename.com/some-thing"
HTTP Headers: 
```
HTTP/1.1 302 Moved
[...]
Location: http://sitename.com//sitename.com/some-thing
```

### Expected behavior
Should redirect to "//sitename.com/some-thing" (http or https depends on protocol before redirect)
HTTP Headers: 
```
HTTP/1.1 302 Moved
[...]
Location: //sitename.com/some-thing
```

### Environment
Only tested MODX Revolution 2.3.2-pl (traditional) on IdeaWebServer/v0.80, but i don't think it's important, because...

### ...there is bugfix (to check)
I spent over a dozen minutes to figure it out, and i found this:
https://github.com/modxcms/revolution/blob/master/core/model/modx/modresponse.class.php#L265
if i change
```
exit();
```
into:
``` 
return;
```
It is working properly!
I get that HTTP response:
```
HTTP/1.1 302 Found
[...]
Location: //sitename.com/some-thing
```
It's small difference there, because on response is "**302 Found**", but i think this is proper response rather than "**302 Moved**"

Is this fix is proper way? (not exitting in the middle of script, just returning?)

**Comment by Mark-H** [comment]
While from a code design perspective the `return;` sounds potentially better than `exit()`, I think that would be a breaking change we can't make until 3.0 due to semver. The current behaviour is that $modx->sendRedirect() stops the process, which means there might be code that does not expect anything after the sendRedirect call to be executed. Change that behaviour and it might lead to unexpected results.. 

It would be interesting to find out why it works with the return rather than the exit though - maybe there's something happening after the sendRedirect that fixes the behaviour? 

Slightly relevant is the discussions here as to whether relative protocol URIs are valid in Location headers: http://stackoverflow.com/questions/19235829/does-the-location-header-accept-the-protocol-notation (TL;DR: not really, but most clients will understand it anyway)

**Comment by Jacqbus** [comment]
OK after some investigation i figure that, if i return any content (eg. echo ('test'); ) right before exit, i'll get 
```
HTTP/1.1 302 Found
[...]
Location: //sitename.com/some-thing
```
 and if there's no any content (empty output, just headers) i'll get
```
HTTP/1.1 302 Moved
[...]
Location: http://sitename.com//sitename.com/some-thing
```

That's exmplain working of  "return" rather than "exit" thing (i didn't check what content it try to return, but it's doesn't matter)

I think that adding "http://sitename.com" part to location header might be caused by server (or PHP parser if it's not detect any content), but i'm not sure.

### About the legitimacy of sending "//" in header: 

It's not valid indeed, and if I/we want to be as close to standards as possible i decided to use "server_protocol" option from system settings as base to all my sendRedirect function calls.

I'm also wondering if doubleslash is using for relative URLs? Because if it's not, i can do a litle patch to automatically apply "server_protocol" option, when $url begins with "//" on https://github.com/modxcms/revolution/blob/master/core/model/modx/modresponse.class.php#L264

What do you thing about that solution?

**Comment by OptimusCrime** [comment]
Reading the link to StackOverflow reveals that this was never supposted to "work", so I suggest just closing this as invalid.

Any objections?

**Comment by Jacqbus** [comment]
@OptimusCrime I'd agree with you, but even Google Company uses that doubleslash "thing":
example straight from source of https://google.com:
```
href="//www.google.pl/intl/pl/policies/privacy/?fg=1"
```
So i'm not sure this is just someone's fad.

Btw. which part do You mean if you write *this was never supposted to "work"*? About duobleslash in "Location" header or doubleslash at all?

I agree it's not an issue anymore, but i just want to discuss about it (maybe there's some better place for that).

**Comment by OptimusCrime** [comment]
@Jacqbus It is two different things. Linking in HTML can use the protocol relative URL. However, as the StackOverflow link says, it is not allowed when redirecting. Redirecting requires a full URL.

If the latter also accepted a relative URL we had to implement this, but it does not.

I am going to go ahead and close this for now. Feel free to comment and/or reopen if you feel like it.

@modxbot close

**Comment by Jacqbus** [comment]
Ok i understand it - thanks.

But my last proposition was to detect, if someone try use doubleslash in the following way:
```
$modx->sendRedirect("//sitename.com/whatever-page");
```
and if he does, automatically change "//" into "{server_protocol}://sitename.com/whatever-page" ("server_protocol" is from system settings of course). Plus update "sendRedirect" rtfm page.

After that, "Location" header always will be full URL :)

If you like that idea, i can pull request for that change, and if it's not just answear me about that and you can finally close that topic :)

**Comment by OptimusCrime** [comment]
Sure, I think that can be cool. Not up to me either way.

@theboxer any input? :)
