### ISSUE TITLE
Feature Request: Breadcrumbs in the Manager

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#12548]
Could we please get Breadcrumb or related navigation in the manager,

For example:

Working on a site with a dozen User Groups and associated roles is a pain as there is no way directly back to the list of Groups.

Even put it to the left of the Save Close Help! menu...

**Comment by pixelchutes** [comment]
Great idea!

While it does not cover Users *(or other areas that could benefit from this idea)*, there is an extra **modDevTools** that adds a breadcrumbs feature when editing Resources. It's very helpful!

**Comment by christianseel** [comment]
I'd say this is not a feature for the current manager layout and should be handled by an extra like modDevTools does. But I'll write it down for the complete new MODX Manager in the MODX Advisory Board working group.

@wshawn agree to close this issue?
#modxbughunt

**Comment by OptimusCrime** [comment]
No answer in two years. Going to close this. Feel free to comment or reopen.

@modxbot close
