### ISSUE TITLE
Linebreak at start of core/lexicon/ar/setting.inc.php causing "Cannot modify header information" errors

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#12544]
Accidentally switched to `ar` manager language, noticed it was adding a bunch of errors to the error log due to a line break at the beginning of the lexicon file. Only on develop branch. https://github.com/modxcms/revolution/blob/develop/core/lexicon/ar/setting.inc.php

@theboxer since translations are managed via crowdin, do you think something's wrong with how the translation file is generated?

**Comment by theboxer** [comment]
I see the line break also in en lexicons https://github.com/modxcms/revolution/blob/develop/core/lexicon/en/setting.inc.php

**Comment by theboxer** [comment]
And I just tried to switch to ar and I didn't se any errors or anything not working...

**Comment by Mark-H** [comment]
Well, that'd explain it. Looks like that happened in #11799 which I merged. Whoops. :astonished:

**Comment by Mark-H** [comment]
I'm not sure what request in the manager actually triggered the error, definitely not on all requests. Mind if I fix the english lexicon directly or do you want a PR? I'm assuming crowdin will fix the other files after a sync.

**Comment by theboxer** [comment]
Fix it directly, I'll sync crowdin and than all translations

**Comment by Mark-H** [comment]
@theboxer /en/setting.inc.php on develop has been updated

**Comment by theboxer** [comment]
Ok, uploaded to crowdin, will sync it into repo in a few mins.

**Comment by theboxer** [comment]
@Mark-H Updated, please check if it's ok

**Comment by Mark-H** [comment]
@theboxer Nope, still has the line break: https://github.com/modxcms/revolution/blob/develop/core/lexicon/ar/setting.inc.php

I think you may need to sync the develop branch with crowdin separately rather than just on master and merging that into develop.. if you look at crowdin the 2.4 branch is also separate.

**Comment by Mark-H** [comment]
Yep, all good!
