### ISSUE TITLE
Site name in MODX Manager header (2.4.0-rc1) not accounting for quotes

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12549]
### Summary
A long `site_name` containing quotes `"` is not loaded into `Ext.Tooltip` correctly in MODX Manager `2.4.0-rc1` when hovering over the site name.

### Step to reproduce
1. Install MODX 2.4.0-rc1
2. Configure a long `site_name` *(to result in Ext.Tooltip hover overflow being activated)* containing one or more quotation marks `"` followed by some other text.
3. Clear cache and refresh MODX manager
4. Hover mouse over site name in the manager header

### Observed behavior
Tooltip is loaded with partial site name, nothing after first quote `"` is visible. The HTML is not escaping the quotes, resulting in invalid HTML syntax.

![demo_site_name](https://cloud.githubusercontent.com/assets/352182/9235058/ab1c5120-40f9-11e5-91df-4bf798b07ac3.jpg)

### Expected behavior
Rendered HTML should be valid, account for possible quotation marks.

### Environment
MODX 2.4.0-rc1 (git) / Chrome 46

**Comment by OptimusCrime** [comment]
I thought this would be pretty easy to solve, but I can't figure out where on earth this is fetched from. Simply searching from `site_name` in this repo does not have any results that looks like the source.

**Comment by pixelchutes** [comment]
manager/templates/default/header.tpl

**Comment by OptimusCrime** [comment]
Silly, wrong branch.

Fixing this should be pretty easy. I think. On this line [manager/templates/default/header.tpl#L67](https://github.com/modxcms/revolution/blob/develop/manager/templates/default/header.tpl#L67):

    <div id="site_name" class="info-item site_name" title="{$_config.site_name}">{$_config.site_name}</div>

Replace with:

    <div id="site_name" class="info-item site_name" title="{$_config.site_name|escape}">{$_config.site_name}</div>

**Comment by pixelchutes** [comment]
PR and I'll merge!

**Comment by OptimusCrime** [comment]
You got it, mister ;)
