### ISSUE TITLE
Elements not generated on Tabbed Windows

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#12552]
When you add a tabbed MODX.Window, the elements don't get generated until after the tab has loaded.  This can lead to lost data when submitting a form, because the missing elements aren't submitted.  It also causes LoadDropZone to fail due to no dom being available on uncreated elements. 

The solution I have so far is to add an on 'activate' function that cycles through the tabs. 
<pre>
this.on('activate',function() {
        Ext.getCmp('second-tab').show();
        Ext.getCmp('first-tab').show();
});
</pre>

It doesn't seem like an idea solution however, and there needs to be a way for all the register flds to become actual elements on render.

**Comment by bezumkin** [comment]
it seems that behavior you have described [is default for Ext JS](http://docs.sencha.com/extjs/3.4.0/#!/api/Ext.TabPanel-cfg-deferredRender).

Try to specify for your tab panel:
```
deferredRender: false,
```

By the way, it is set to true in (MODx.Tabs](https://github.com/modxcms/revolution/blob/b5dce74a173fca4d8a56ab45478306edb6b5cea1/manager/assets/modext/widgets/core/modx.tabs.js#L7) widget.

**Comment by matdave** [comment]
Guess i missed that one, thanks bezumkin
