### ISSUE TITLE
Form Customization Title

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12557]
### Summary
Wrong title during editing a Form Customization Set.

### Step to reproduce
Edit a Form Customization Set.

### Observed behavior
Title is 'Create New Set'.

### Expected behavior
Title should be 'Edit Set'.

### Environment
MODX 2.3.5

**Comment by OptimusCrime** [comment]
Now it simply says `Form Customization`. 

@modxbot close

**Comment by OptimusCrime** [comment]
@modxbot open

**Comment by OptimusCrime** [comment]
Too fast on the trigger there. I located the correct placement. Sorry about that.

**Comment by OptimusCrime** [comment]
@modxbot close :)

**Comment by OptimusCrime** [comment]
@modxbot close :)
