### ISSUE TITLE
[MODX 2.4.0-rc1] ACLs for "Namespace access" and "Media Source Access" seem to be mixed

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#12559]
### Summary
ACLs for "Namespace access" and "Media Source Access" seem to be mixed/twisted.
(And it should be "Namespace Access" – with a capital "A" – like in the other tabs.)

### Step to reproduce
In a fresh MODX 2.4.0-rc1 system, I went to `MAIN MENU: Settings > ACLs` and did an `Update User Group` for the `Administrators` group, jumped to the `Permission` tab and chose `Namespace access`.
Then I clicked on `Filter by Namespace ...` and could select a "namespace" named `Filesystem` when this list should just show `core`. 

![image](https://cloud.githubusercontent.com/assets/458619/9308071/37015044-4502-11e5-94ab-348460b627cd.png)

Also, `Filter by Policy ...` list two Media Source Policies (`Media Source Admin` and `Media Source User`). Is that correct?

![image](https://cloud.githubusercontent.com/assets/458619/9308114/801c3b18-4502-11e5-9d22-ac7fdfb61c47.png)

On the other hand, I cannot select a Media Source in the according tab – also filtering policies does not work.

![image](https://cloud.githubusercontent.com/assets/458619/9308280/82796740-4503-11e5-924b-807ce6672410.png)

### Environment
A fresh MODX 2.4.0-rc1 system.

Thanks for all your hard work to make 2.4 possible!!!

cheers
Oliver

**Comment by pixelchutes** [comment]
Fixed by #12560
