### ISSUE TITLE
500 error on clear cache

### ISSUE THREAD

**Issue by Bumme** [modxcms/revolution#12561]
### Summary

500 error on clear cache
### Step to reproduce

Create multiple contexts
Create an usergroup and user that are not allowed with that context
Login to the manager
Click "clear cache"
### Observed behavior

The console window will popup.
The following text will be shown: 
Console running...
Principal {userid} does not have permission to load object of class modContext with primary key: {context_key}

The connector will return an 500 error : PHP Fatal error:  Call to a member function getOption() on a non-object in /core/model/modx/modresource.class.php on line 880, referer: /manager/?a=resource/update&id=21341254

After the return of the 500 error Extjs doesn't know the request is finished so you can't click on the "ok" button of the console window and the cache isn't cleared.
### Expected behavior

Clear cache 
### Environment

Apache
MODX 2.3.2-pl
PHP 5.3.29
MySQL 5.5.31

**Comment by christianseel** [comment]
That works as expected in MODX 2.5.5! 👍 

Closing this because it's already fixed.
#modxbughunt

@modxbot close
