### ISSUE TITLE
Bug: non-sudo users cannot change group settings

### ISSUE THREAD

**Issue by wuuti** [modxcms/revolution#12566]
In 2.3.5 a non-sudo, but admin user (full admin policy) cannot change any group settings value. A "permission denied" is thrown when the user tries to change the value of a group setting. 
On the other hand he _can_ create new settings and _can_ delete existing settings...

When giving the user sudo access, everthing works fine. 

User/Context/System settings are not affected. 

Haven't tested it so far on the new 2.3.6 and 2.4.0-rc1 versions...

**Comment by pixelchutes** [comment]
Hmm... what is an example of one of the group settings you are trying to change?

**Comment by inreti** [comment]
Does not matter. You can create one, say "test_setting". After it is created you are not allowed to change the value any more. Same goes for overwriting common settings, like "manager_language".

**Comment by Mark-H** [comment]
See #13544 for a fix.
