### ISSUE TITLE
Tag order from GitHub incorrect

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12569]
This is more a curiosity than a bug.

Getting the tag versions from GitHub with a cUrL call to https://api.github.com/repos/modxcms/revolution/tags has always returned the latest version as the first member of the array.

Currently, 2.4.0-rc and 2.4.0-pl are reversed -- 2.4.0-rc is first in the array. (Try pasting the URL above in a browser to see it.)

I need to get the latest version. It's not a big deal -- I can sort them in less than a millisecond with a custom insertion sort and version_compare(), but if anyone else is counting on them being in order, they may not notice the reversal and could run into trouble (I think the MODX install script, for example, will not have the latest stable version at the top of the list), and I'm curious about how this happened.

**Comment by inreti** [comment]
Oh. Good to know. Then I have to change the Updater extra as well... not choosing the first available tag. Damn.

**Comment by OptimusCrime** [comment]
The releases from Github are not sortable, they appear in the order they were created, which means 2.4.0 was tagged before 2.3.6. There is unfortunately nothing to do with this.

**Comment by BobRay** [comment]
I'm pretty sure it's fixable by deleting and re-creating the pl tag, though doing some trials on a test repo would probably be a good idea. 

I'm guessing wildly here:

git checkout V2.4.0-pl

git tag -d v2.4.0-pl
git push origin :refs/tags/v2.4.0-pl

git tag v2.4.o-pl
git push origin :refs/tags/v2.4.0-pl

git checkout HEAD



Recreate tag, and push again

**Comment by OptimusCrime** [comment]
Yes it should be possible. However, you should not rely on the order of the tags as they are when fetched from GitHub. It will never be reliable.

**Comment by inreti** [comment]
Close this issue?

**Comment by OptimusCrime** [comment]
@modxbot close
