### ISSUE TITLE
Revo 2.4 Manager Alert - Code: -1 transaction aborted undefined

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12577]
Just started playing with 2.4
I've been noticing an alert popping up randomly showing 
`Code: -1 transaction aborted
undefined`
when moving between manager pages.
Because it occurs when moving between pages it just shows briefly and then disappears.

I haven't worked out the criteria for replicating it yet but has anyone else encountered this?

**Comment by sirazitdinov** [comment]
Faced with this error to 2.5.0

**Comment by digitalpenguin** [comment]
I think this seems to happen if you have a slow connection press back or forward before everything has finished loading. Same for you?

**Comment by sirazitdinov** [comment]
The error no longer occurs. Perhaps there were problems with connection.

**Comment by syts88** [comment]
Cannot reproduce this in Modx revo 2.5.5. #modxbughunt

**Comment by digitalpenguin** [comment]
Yup I haven't seen this in a while too
