### ISSUE TITLE
Help links missing target_blank

### ISSUE THREAD

**Issue by terrybarth** [modxcms/revolution#12570]
The links to additional information for the settings (under + sign) open in the same window as the manager. They should open to a new window.

**Comment by Alroniks** [comment]
We can check links in description field and try add `target="_blank"` to each or just add handlers to this links, but in system settings from MODX will be more easy check existing links and fix lexicons manually and for settings from extras let's left this task to authors of extras.

**Comment by Alroniks** [comment]
So, I've added missed target=blank in system settings, for extras please send issues to author of extra.

**Comment by terrybarth** [comment]
Great. Thank you.

**Comment by Alroniks** [comment]
PR was merged for the next release, so this issue can be closed I guess. @theboxer
