### ISSUE TITLE
Dragging files into Ext Windows. Cannot read property 'getStyle' of null

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#12576]
Okay this takes a bit of setup to accomplish, but really ruins a whole plan i had for a CMP. 

_Requirements:_
* a file from the file tree
* two Ext windows

Open the first Ext window, and drag a file from the file tree into a text field.  It should render the file path. Close the first window. 

Open the second Ext Window without refreshing the page, and attempt the same thing. It should result in a "Cannot read property 'getStyle' of null" error.

**Comment by bezumkin** [comment]
My fix for this - https://github.com/modxcms/revolution/pull/12572

**Comment by bezumkin** [comment]
A similar problem with dnd to template content https://github.com/modxcms/revolution/pull/12572

**Comment by matdave** [comment]
![image](https://cloud.githubusercontent.com/assets/2213127/9448897/d7171b88-4a64-11e5-967c-06b08e394376.png)
I'm not getting errors from the *modx.treedrop.js* script, and updating to your version didn't fix it.

**Comment by bezumkin** [comment]
My PR is for similar trouble, not for the same. Maybe it somehow related - don`t know.

**Comment by matdave** [comment]
<pre>


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
Ext.dd.DragDropMgr.getZIndex = function(element) {
    var body = document.body,
        z,
        zIndex = -1;
    var overTargetEl = element;
 
    element = Ext.getDom(element);
    while (element !== body) {
 
        // this fixes the problem
        if(!element) {
            this._remove(overTargetEl); // remove the drop target from the manager
            break;
        }
        // fix end
 
        if (!isNaN(z = Number(Ext.fly(element).getStyle('zIndex')))) {
            zIndex = z;
        }
        element = element.parentNode;
    }
    return zIndex;
};
</pre>

Add this to my component fixed this issue.  Found the solution here https://www.sencha.com/forum/showthread.php?264400-Ext-JS-3.4.4.1-Drag-amp-Drop-broken
