### ISSUE TITLE
Wrong URL path when redirected after creating a new dashboard's widget

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#12587]
### Summary

After creating a dashboard's widget, the page was loaded with wrong "action" argument, led an error in center page.
### Step to reproduce

https://rtfm.modx.com/revolution/2.x/administering-your-site/dashboards/creating-a-dashboard-widget
### Observed behavior

After created a widget, the page was redirected to 
`http://localhost/modx/a11y/www/manager/index.php?a=system/dashboard/widget/update&id=6`
But the center page went unloaded with this error:
`Could not find action file at: D:/localhost/modx/a11y/www/manager/controllers/default/system/dashboard/widget/update.php`
### Expected behavior

This address is valid:
`http://localhost/modx/a11y/www/manager/index.php?a=system/dashboards/widget/update&id=6`
Notice **dashboards** with **"s"**

But it reveals a new question, since the processors are in `processors/system/dashboard/widget`
Notice **dashboard** without **"s"**

Which one is preferable?
### Environment

MODX 2.4.0-pl-sdk

**Comment by sottwell** [comment]
It should be "dashboard", since the actual path is in fact processors/system/dashboard/...

**Comment by sottwell** [comment]
Version 2.4.0-pl there's no problem with creating widgets.

**Comment by janice171** [comment]
I still get an error in 2.4.0-pl: 
<em>Could not find action file at: /home/myWebsitepublic_html/new/manager/controllers/default/system/dashboard/widget/update.php</em>
The widget does actually get written OK though, i just get the error above on this page: 
<em>myWebsite.co.uk/new/manager/?a=system/dashboard/widget/update&id=8</em>

**Comment by sottwell** [comment]
I always create at least three dashboard widgets for every site I install, and don't get that error. However, it is probably not a good thing that in the core it's "dashboard" while in the manager it's "dashboards". Have you updated to 2.4.1 yet? Still get the same problem?

**Comment by janice171** [comment]
Sottwell -  I haven't upgraded yet but will report back when i do.

**Comment by syts88** [comment]
This issue is indeed fixed. Tested in Modx 2.5.5. #modxbughunt
