### ISSUE TITLE
Form Customization - Only top 20 templates listed

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12588]
MODX 2.4.0

When creating a new set in form customization, the template combo-box in the create window will only list the top 20 templates.

The only steps needed to replicate this is create more than 20 templates then try to create a new set and attempt to select the 21st template.

**Comment by OptimusCrime** [comment]
Fixed :)

The fc template dropdown now has pagination if there is more than 20 templates in the list. Tested with 2.4.0-git

@modxbot close
