### ISSUE TITLE
Revo 2.4 Property set with the lowest id drops after saving any chunk or snippet

### ISSUE THREAD

**Issue by manicko** [modxcms/revolution#12580]
I found that after saving any element (chunk, plugin or snippet) one of my property sets became empty. It is not deleted but only drops all parameters. I was trying to find out any dependencies and the only thing is that it is the Property set with minimal id. 
If i create the new Property set with same parameters it will not drop and if i delete the  Property set with the lowest id the next Property will drop.

**Comment by bezumkin** [comment]
Quick fix by Fi1osof - https://gist.github.com/Fi1osof/ff3ea018841b1bb1f99b

**Comment by Fi1osof** [comment]
@bezumkin Without discussion will not understand what need to edit. https://modx.pro/development/6312-how-not-to-extend-modx-processors/

**Comment by bezumkin** [comment]
@Fi1osof As i understood we can just [replace this processor](https://github.com/modxcms/revolution/blob/e5727d94938269205e3fac84b8cb15c7eaf21b62/core/model/modx/processors/element/propertyset/updatefromelement.class.php) with your quickfix and it will work?

For proper PR need to add various lexicons and comments on english.

**Comment by Fi1osof** [comment]
@bezumkin yes.

**Comment by manicko** [comment]
thanks for  bug fix it works like a charm!

**Comment by Fi1osof** [comment]
@manicko you are welcome! :)

**Comment by mrhaw** [comment]
Nice! :+1:

**Comment by mrhaw** [comment]
Google translated to english https://gist.github.com/mrhaw/97a664ad46e614899f1d

**Comment by Fi1osof** [comment]
@mrhaw  Thanks!

Sended PR https://github.com/modxcms/revolution/pull/12614
