### ISSUE TITLE
Plugin event expected result behavior change

### ISSUE THREAD

**Issue by josht** [modxcms/revolution#12595]
### Summary
The class based login processor introduced new behavior when checking results from the plugin events 'OnBeforeWebLogin' & 'OnBeforeManagerLogin'

### Step to reproduce
In a plugin attached to either of these events, make the call: `$modx->event->output(true);`

### Observed behavior
This will now act as if login validation failed and return '1' as the reason for login failure.

### Expected behavior
Should allow login process to proceed with no error messages.

### Environment
MODX version 2.4

**Comment by pixelchutes** [comment]
May be related to this: #11594

**Comment by josht** [comment]
I think a few of the plugin events use the event output field differently. The issue I'm reporting here breaks from what the docs currently say is the expected behavior. [rtfm.modx.com - OnBeforeManagerLogin](http://rtfm.modx.com/revolution/2.x/developing-in-modx/basic-development/plugins/system-events/onbeforemanagerlogin)

The discussion you linked to is a step deeper into plugins than where this current issue takes place.

**Comment by pixelchutes** [comment]
I think you're right, I must have personally only used it for handling errors...

Regardless, it definitely sounds like a bug to me if issuing `$modx->event->output(true)` is triggering an error as described.

**Comment by pixelchutes** [comment]
Fixed by #12623
