### ISSUE TITLE
Save Error Alert Visability

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#12592]
When editing template variables on a new resource and there is a duplicate alias auto-generation error, the save button appears to be non-functioning because there is no visual cue that there is a duplicate alias error on the main tab.  There needs to be some sort of error feedback visible adjacent to the save button.

**Comment by inreti** [comment]
Quite the same as #12378, #9248. Related to #10406.

+1 for extra visual feedback of save errors/requirements.

**Comment by pyrographics** [comment]
I searched but didn't see these, no need for a duplicate issue so I'll close this.
