### ISSUE TITLE
[2.4] Date TV ignores min-max-time settings

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#12591]
### Problem

The "hide time" feature for the TV-type "date" – introduced with #12348 – is nice but has some flaws: instead of storing a fixed time, the current time is being saved. Even if the values min- & max-time are set, they get ignored which results in a more or less "random" time being saved. Setting it to a fixed 00:00:00 would have been much better. Why?

A non-fixed time makes comparisons on the database layer overcomplicate: Find the same date? Difficult. One must strip the time time before the comparison, because a random time was stored and is influencing the result:
`2015-12-31 12:34:56 > 2015-12-31 01:23:45`
`2015-12-31 00:00:00 = 2015-12-31 00:00:00`

Another thing: You need a "time-only" field? Bad luck. Not possible.
### Solution Proposal

The following solutions does not need any new fields, only some logic behind analysing the values and setting the date-time-picker accordingly. And it can create three variants of the date TV.
##### Date only

If min and max time are equal, no time-picker is displayed, the time is set to the (identical) min-max-value and gets saved.
##### Time only

If min and max date are equal, no date-picker is displayed, the date is set to the (identical) min-max-value and gets saved
##### Date and Time

Everything is like it's used to be in the old days. But the time and date min-max-values are taken into account before the date-time-picker is shown and the value are corrected according to the boundries.
### Result

Everybody smiles and is happy. :-)

**Comment by inreti** [comment]
I prefer having separate DateTime, Date and Time TVs with clean semantics. The above would  always be stored in the DB as timestamp where you cannot see which semantics is inside. If we had different TV types here, the TV type only decides over the semantics of the timestamp. If it is only one TV type we also need to interpret the TVs options to clearly understand what the timestamp means...

**Comment by JoshuaLuckers** [comment]
Hiding the time option with the current `date` template variable what do developers and/or users expect regarding the time when selecting a date?
- the time is set to the current time
- the time is set to `00:00:00`
- don't store the time at all

**Comment by mindeffects** [comment]
In no scenario, inside the knows universe, I can imagine storing the `current time` is of any use considering that I want to hide the time.
I would expect the time to be a constant value, like 00:00:00 to make comparisons easier, like `date 1 > date2`. I would also be fine with no time being stored at all (assuming it is not stored as a timestamp, of course).

**Comment by JoshuaLuckers** [comment]
I want to propose a solution that doesn't break backwards compatibility for this template variable. It might be possible that there are developers who use the time value even if it's hidden.

Improving the options to set a default value for the date and time is a better approach.

**Comment by mindeffects** [comment]
The only „never breaking anything“ solution would be cloning the TV `date` into `dateOnly` and `timeOnly`. 
Then you would need to willingly change your tv to behave in the new way.

**Comment by Jako** [comment]
The „never breaking anything“ solution has to handle existing and new values different on input side. And I suggest to save it with `00:00:00`.

**Comment by Ibochkarev** [comment]
Fixed #15000 
@mindeffects Thanks
@modxbot close
