### ISSUE TITLE
Media Sources getting wrong name

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12596]
In a site with 13 Media Sources, upon upgrade to 2.4 Media Source 1 (Filesystem) is displayed with the name of Media Source 11. It shows correctly in select drop-downs, such as when selecting a Media Source for a TV, but once selected it displays with the name of 11 (Directors).
![screen shot 2015-08-25 at 9 35 31 pm](https://cloud.githubusercontent.com/assets/1073780/9475748/53d33d66-4b71-11e5-81cb-fc1c0f086ab2.png)
![screen shot 2015-08-25 at 9 39 01 pm](https://cloud.githubusercontent.com/assets/1073780/9475863/22167aa8-4b72-11e5-9f1d-7d9da5733e01.png)
![screen shot 2015-08-25 at 9 39 15 pm](https://cloud.githubusercontent.com/assets/1073780/9475885/36c7c38a-4b72-11e5-9f2c-4d5999d4213d.png)

**Comment by krismas** [comment]
Reproduced, on a fresh 2.4 install, with new Media Sources. The problem seem to appear for any Media Source if his ID in [10, 20[ and his name (sort ASC) is before "Filesystem"... A sort key/value problem !?

**Comment by krismas** [comment]
At the initial display the name is valid, then after some ms this "valid label" is replaced by the "wrong label". So an ExtJS problem !?

**Comment by OptimusCrime** [comment]
Guessing it is fetched from some processor and applied somehow, not sure how

**Comment by krismas** [comment]
"source/getlist" is called as many times as the number of Media Sources! No cache! Is this normal?

**Comment by inreti** [comment]
@krismas: that would indeed be a performance problem.

**Comment by sottwell** [comment]
this is still an issue with 2.5.1 - media sources #1, #2 etc are given the name of #10, #20, etc. They appear in the alphabetical listing in the order one would expect if they had the correct names.
![screen shot 2016-08-13 at 20 22 52](https://cloud.githubusercontent.com/assets/1073780/17644603/c681b2e6-6193-11e6-8e10-3d27b8df63c7.png)

**Comment by sottwell** [comment]
For example, that second Cache should be Carousel, and the second Directors should be Filesystem.

**Comment by IamNeo1** [comment]
Hi,
i have an installation with 7 contexts and 3 media source for each context. I have this problem too and my customers are not very assumed about that. 
I am using  modx 2.5.1.
![media_sources](https://cloud.githubusercontent.com/assets/8747516/19859099/670e2fc2-9f84-11e6-982b-3e5c3298bbc2.png)

Please fix that!

I think there is an other effect too: when i assign a media source to a TV there is a weired behavior too. I set a background image for each context an when you want set it in the context with the name problem and open the folder with the images the wrong/old images where shown. Could it be that the cache could not deleted for the media sources with problems?

**Comment by Mark-H** [comment]
Fixed by #13189 which will be included in 2.5.x!
