### ISSUE TITLE
mod_security rule being tripped by modx manager save AND package download actions

### ISSUE THREAD

**Issue by BigBlockStudios** [modxcms/revolution#12594]
Have not got a lot of info on this at the moment, but it appears that on a save action in the manager AND when trying to update a package with the installer a mod_security rule is getting tripped. causing the manager to appear to hang on the "saving" dialaog. 

this only happens with some resources - so I am assuming that it has something to do with template variable values. 
The package manage is mor concerning though.

the rule is:
# Rule 340162: Generic PHP code injection protection in URI w/ anti-evasion

SecRule REQUEST_URI "(?:\/(?:(?:wp-admin\/(page|post|widgets|link|network/site-settings.php|options|themes/basic/themify/img.php\?src=|admin.php?cf/cf.php)|admin\/(?:edittemplate|webpage_upd$
# SecRule ARGS "!@pmFromFile trusted-domains.conf" chain

SecRule ARGS|!ARGS:/_online_/|!ARGS:reason|!ARGS:installFull|!ARGS:b2w|!ARGS:/email/|!ARGS:term|!ARGS:/source_array/|!ARGS:/button/|!ARGS:rdfrom|!ARGS:/bestand/|!ARGS:/^request/|!ARGS:m_wb|!ARGS$
         "phase:2,deny,status:403,capture,id:340162,t:none,t:urlDecodeUni,t:replaceNulls,t:compressWhiteSpace,t:lowercase,chain,rev:294,severity:2,msg:'Protected by Atomicorp.com Basic Non-Realt$
SecRule TX:1 "!@beginsWith %{request_headers.host}" "t:none,t:lowercase"
# SecRule MATCHED_VARS "!@rx ://%{SERVER_NAME}/" "t:none,t:urlDecodeUni,t:lowercase"

The mod_security rule appears to have been updated on the 21st [when the problem first manifested] 

If I try to update the smarttag package - I get a apache log error:

[Tue Aug 25 11:34:40 2015] [error] [client 70.48.171.143] ModSecurity:  [file "/etc/httpd/conf/modsecurity.d/rules/tortix/modsec/50_plesk_basic_asl_rules.conf"] [line "207"] [id "340162"] [rev "294"] [msg "Protected by Atomicorp.com Basic Non-Realtime WAF Rules: URL detected as argument, possible RFI attempt detected"] [data "%TX:1,TX:1"] [severity "CRITICAL"] Access denied with code 403 (phase 2). Match of "beginsWith %{request_headers.host}" against "TX:1" required. [hostname "www.domain.ca"] [uri "/connectors/index.php"] [unique_id "VdyZINhGZdwAABP3A3oAAAAF"]

and in the chrome inspector index.php -> post -> 403 -> xhr -> ext-base.js:21 

also getting the same error when trying to download and install a new package. 

this was both on modx 2.3 and updated to latest 2.4

**Comment by vierkantemeter** [comment]
We've got the exact same problem with 2.3 and 2.4.

**Comment by alroniks** [comment]
Due to inactivity, I am closing the issue. I am not sure that mod_security module widely used, but if any issue will happen, please reopen it.

Also, in documentation exists an article about troubleshooting while using mod_security tool. https://docs.modx.com/current/en/getting-started/installation/troubleshooting/modsecurity
