### ISSUE TITLE
Add notes about GZIP to Docs or Installation Instructions?

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#12606]
Over at https://github.com/modxcms/revolution/pull/12538 we've been discussing the compression settings and how they effect performance and optimization. 

While concatenating and minifying the files is good (if done on the front end never if done on the back end) the truth is that enabling GZIP compression alone will have a more significant benefit. In other words, you're better of serving unminified flat files that are GZIPed than you are minified ones that aren't.

So anyways, I don't think MODX can automatically enable GZIP on people's servers but I was wondering if maybe it is worth a note in the docs...

![](http://j4p.us/image/2K2B3Z1v2A1P/Screen%20Shot%202015-08-27%20at%204.03.21%20AM.png)

https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer?hl=en

**Comment by zaigham** [comment]
This is looking very very interesting! :+1:

**Comment by jpdevries** [comment]
moving the issue to the docs repo here https://github.com/modxcms/docs/issues/94
