### ISSUE TITLE
Plugin: saving with system events in group "system" -> Error 403

### ISSUE THREAD

**Issue by achterbahn** [modxcms/revolution#12600]
Updatet MODX from 2.3.5 -> 2.4.0

Installed Babel and with it created a plugin. I can save the plugin, but when I choose ```onHandleRequest``` and save error 403 flashes and nothing is saved. Actually all system events within the group "System" behave like this.

can anyone reproduce this behaviour?

**Comment by sottwell** [comment]
Almost sounds like a server mod_security issue.

**Comment by sottwell** [comment]
Indeed, works fine on the MODX Cloud and localhost.

**Comment by achterbahn** [comment]
hm, on the other hand: all system events not in the group system can be stored without any problems...
I'll check what you suggested and close the issue then.
