### ISSUE TITLE
Update the Delete Resource alert box

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#12608]
Too many people "accidentally" delete resources.  We have actually started removing the ability for users to purge resources.  I think it would help to have a better warning box when someone is going to delete a resources. 

![image](https://cloud.githubusercontent.com/assets/2213127/9523572/4aa71638-4ca0-11e5-878f-a87018388855.png)

**Comment by OptimusCrime** [comment]
I thought the whole point of the trashcan was to avoid this middle step.

**Comment by inreti** [comment]
There are a lot of problems for customers/users with deleting resources (we prevent purging for our end-users as well). Most important for me:

* the warning box does not contain the name of the resource (which may lead to accidently delete the wrong resource). Solution: print out the pagetitle in alert box.
* purging is done for the whole site, cross-context. You don't actually see, which resources are purged then. Some may be deep in the tree, some inside a Collections container. You will most of the time purge a resource some other user might like to restore later. That's a small problem in single user blog sites, but in professional sites with lots of users you have a serious problem then.  
Solution: have a manager page where all deleted resources are listed with certain filter/select options before purging.

**Comment by matdave** [comment]
Or a "trashcan" tree drop view

**Comment by alroniks** [comment]
I guess it was solved by adding new trash manager. So, closing it.
