### ISSUE TITLE
Manager Crashes HARD if min library can't find a file

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#12609]
- Install MODX
 - Enable `compress_js` and `compress_css`
 - Install an Extra like Ace
 - delete `assets/components/ace/*` so that the server won't find the file(s)
 - notice the manager is so broken you have to manually update the settings in the database tables to get it to work again. All because it couldn't find assets that were in no way imperative to the core functionality of the manager.

**Comment by Mark-H** [comment]
Closed per #12611
