### ISSUE TITLE
2.4 - editing user group SQL error

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12607]
Opening a user group for update causes this error:

```[2015-08-27 14:58:34] (ERROR @ /connectors/index.php) Error HY000 executing statement: 
Array
(
    [0] => HY000
    [1] => 1267
    [2] => Illegal mix of collations (utf8_general_ci,IMPLICIT) and (utf8_unicode_ci,IMPLICIT) for operation '='
)```

Revo 2.4.0 on the MODX Cloud

**Comment by pixelchutes** [comment]
I cannot reproduce this.

**Comment by sottwell** [comment]
Might be the specific MODX Cloud server. This one is on paas1.ams

**Comment by Omeryl** [comment]
I tried reproducing it on my p1a cloud, can't do it @sottwell.

**Comment by sottwell** [comment]
Hm. Seems to just be this one site.

**Comment by sottwell** [comment]
Checked the whole database, it's all utf8_unicode_ci and of course there's nothing to tell exactly where this error is coming from.

**Comment by sottwell** [comment]
Checked the whole database, it's all utf8_unicode_ci and of course there's nothing to tell exactly where this error is coming from.
