### ISSUE TITLE
Manager save remove custom cache partitions

### ISSUE THREAD

**Issue by juillerat** [modxcms/revolution#12615]
When a resource is saved inside the MODx manager, all custom cache partitions are also removed (using xPDOFileCache).
Create a new partition:

<pre>
    $cm = $modx->getCacheManager();
    $cacheOptions = array(
        xPDO::OPT_CACHE_KEY => 'test',
        xPDO::OPT_CACHE_HANDLER => $modx->getOption('cache_handler')
    );
    $cm->set(0, 'this is a test', 0, $cacheOptions);
</pre>

Then save a resource inside the manager. Your "test" partition will be removed

**Comment by sdrenth** [comment]
I'm going to try and fix this today.

**Comment by sdrenth** [comment]
I cannot reproduce this issue, it looks like this issue is already fixed and can be closed.

#modxbughunt
