### ISSUE TITLE
Manager Breaks when loading off domain assets with API and compress_js

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#12610]
- Install MODX
 - Enable `compress_js` and `compress_css`
 - Create a simple plugin that uses something like loads an off-domain asset
 - notice the minifier will try and fopen that file and break the whole manager :+1: 

#### Example
`$modx->controller->addJavascript('https://cdnjs.cloudflare.com/ajax/libs/ace/1.1.9/ace.js');`
or
`$modx->regClientStartupScript('https://cdnjs.cloudflare.com/ajax/libs/ace/1.1.9/ace.js')`

![](https://slack-files.com/files-tmb/T025K7SUQ-F09KLHXV4-0bbdcedb2c/pasted_image_at_2015_08_25_02_53_pm_1024.png)

**Comment by Mark-H** [comment]
Closing as #12611 made js compression safer, and should only be disabled for development.
