### ISSUE TITLE
Change in handling of OnBeforeManagerLogin and OnBeforeWebLogin  in 2.4.0 breaks Captcha

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12624]
In 2.3.6 and earlier, you returned true from these events to pass the user and allow login. In 2.4.0, you have to pass false  or '' to pass the user.  People with the Captcha plugin enabled can't log in (even if captcha_enabled is off). This change will also break any other plugins that reject users in those two events.

The modProcessor class processEventResponse() method hasn't changed. It assumes that everything that isn't empty is an error. But the old login.php processor never called it. The old login.php assumed that everything that wasn't === true was an error.

The new login.class.php processor calls processEventResponse(), which causes the problem.

I don't see an easy solution. I think the best option might be to override the processEventResponse() method in the login class with something like this:

    public function processEventResponse($response) {
        $preventLogin = false;
        /* If the event fired, loop through the event array and fail if there's an error */
        if (is_array($response)) {
            foreach ($response as $key => $value) {   /* php4 compatible */
                if ($value !== true) {
                    $preventLogin = true;
                    if (is_string($value) {
                        $this->modx->log(modX::LOG_LEVEL_ERROR, '[Login]' . $value);
                    }
                    break;
                }
            }
            unset($key, $value);
        }
        return $preventLogin;
    }

**Comment by pixelchutes** [comment]
Related #12595

**Comment by pixelchutes** [comment]
Fixed by #12623
