### ISSUE TITLE
Error: [configcheck] check core lockdown curl err: 28

### ISSUE THREAD

**Issue by jolichter** [modxcms/revolution#12626]
I have updated a instance with one context from MODX 2.3.6 to 2.4.0, my core is outside the web root and I have no errors.

My second instance with 3 contexts, MODX 2.4.0 on the same server and core outside I get the error:  (ERROR @ /manager/index.php) [configcheck] check core lockdown curl err: 28

Maybe is it a bug with multi-context sites?

At the moment I use PHP 5.5.28 and my dashboard has no configuration warnings. Curl is enabled on the server and the extra installer is working.

Please also note: http://forums.modx.com/thread/98153/what-is-configcheck-check-core-lockdown-curl-err-28#dis-post-530869

**Comment by Mark-H** [comment]
Curl error 28 stands for a time out, apparently the request to check if
your core is public or not is timing out causing the error to be logged.
Op 2 sep. 2015 7:36 PM schreef "jolichter" <notifications@github.com>:

**Comment by jolichter** [comment]
Hi, it seems like a problem with my cache.
I have been getting this error after any 'clear cache' in the MODX Manager.
After that, I have no more errors. I guess that isn't a real error, however it is odd.

**Comment by pixelchutes** [comment]
Perhaps your page is taking [longer than 1s](https://github.com/modxcms/revolution/blob/eeba3277e884e2055f6e173bada6302dc1a5da91/core/model/modx/processors/system/config_check.inc.php#L82-L84) (1000ms) to load?

**Comment by inreti** [comment]
Such a small functionality, and so many interesting unforeseen problems... :-)
Ok, if I get that right, this special timeout error is good for the check, isn't it? Having a timeout is essentially saying: not 200 OK, and therefore exactly what we want. So we should catch that error and do not log then. I will try to fix that.

**Comment by Mark-H** [comment]
This was fixed in 2.4.3
