### ISSUE TITLE
Revolution, Formit, Output Modifiers

### ISSUE THREAD

**Issue by kelly8116** [modxcms/revolution#12639]
If you attempt to use FormIt and output modifiers, Formit will not process the @ symbol causing the entire chunk to fail. 

Example:
If you use:
[[*template:eq=`2`:then=`[[$chunkname]]`]]

And put a Formit call in [[$chunkname]], when you put the @ symbol in the "emailTo" field, it will cause the entire chunk to fail to render.

**Comment by zaigham** [comment]
Related: https://github.com/modxcms/revolution/issues/11269

**Comment by OptimusCrime** [comment]
Duplicate? Close?

**Comment by inreti** [comment]
Thats indeed duplicate. Same error, and better documented in #11269. Vote for close in favor of that issue.

**Comment by OptimusCrime** [comment]
@modxbot close

Feel free to reopen if you feel otherwise. I agree with @inreti
