### ISSUE TITLE
php.net link doesn't work in Package Management

### ISSUE THREAD

**Issue by AndreyPanyush** [modxcms/revolution#12634]
Link in the warning message (cURL must be installed and configured as an extension for PHP for you to use Package Management. You can find more information about cURL on the PHP cURL website.) to php.net/curl doesn't work in some languages (ex. Russian). 
![default](https://cloud.githubusercontent.com/assets/14142401/9701246/159a213e-5429-11e5-81c8-4b79e03a22d8.png)

**Comment by Mark-H** [comment]
Should've been fixed in crowdin.
