### ISSUE TITLE
Make sure setup checks the minimum supported PHP version

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#12637]
### Summary
It is possible to install MODX 2.4 on PHP 5.2, even though the minimum version was bumped to 5.3.3 in that release. This can cause a fully functional manager, except for the package manager which requires 5.3. 

### Step to reproduce, Observed behavior
Install on PHP 5.2. Browse to package manager, and it wont show the installed packages, throwing the following fatal error: 

````
<b>Fatal error</b>:  Call to undefined method SimpleXMLElement::count() in <b>/core/model/modx/transport/modtransportprovider.class.php</b> on line <b>348</b>
````

### Expected behavior
The setup throws an error when trying to install on PHP < 5.3.

### Environment
PHP < 5.3

**Comment by Jako** [comment]
+1
