### ISSUE TITLE
[Feature] [Meta] Add slackin badge

### ISSUE THREAD

**Issue by adamwintle** [modxcms/revolution#12636]
### Summary
To add a little SVG badge to the [README.md](https://github.com/modxcms/revolution/blob/2.x/README.md) which shows the current connected users in the Slack chat room (https://modxcommunity.slack.com/) in realtime.

Example from the widely popular [Bootstrap framework](https://github.com/twbs/bootstrap):

![](https://bootstrap-slack.herokuapp.com/badge.svg)

The badge could also link to the community chat signup/login page ([https://modxcommunity.slack.com/](https://modxcommunity.slack.com/)) to encourage new users to join in with our discussions and participate. 

Slackin also allows us to have a nice `<iframe>` badge, similar to Twitter and Facebook social widgets, which could be used on the MODX blog and other community pages. Example:

![](https://camo.githubusercontent.com/b324afb72425883a18c38f7ab9293755773fea56/68747470733a2f2f636c6475702e636f6d2f496169506e44454141362e676966)

### Step to reproduce
To use Slackin (https://github.com/rauchg/slackin) to generate the badge we need a server to run the tiny app, perhaps MODX can donate a small amount of server capacity, maybe discovermodx.com could be used or maybe @Mark-H has a server which this little app could be running from.

**Comment by OptimusCrime** [comment]
+1

**Comment by zaigham** [comment]
+1

**Comment by Omeryl** [comment]
MODX LLC is going to set this up, and we'll eat the costs for the server to run it.

Will submit a PR shortly.
