### ISSUE TITLE
Empty trash and clear cache for individual context and not all contexts at once.

### ISSUE THREAD

**Issue by mdehaan** [modxcms/revolution#12649]
I have multiple client websites on different contexts within one MODX installation.
This really is great for maintaining, bugfixes and implementing new features.

Each client has a user account with witch they can manage their own individual context/site.
These clients need to be able to empty the trash for their site/context individually.
Also when clients save a resource, the cache of all contexts will automatically be cleared.
It would be nice that clearing the cache could be handled for each context individually...

It would be great to have these functionalities implemented in a next version of MODX!

**Comment by christianseel** [comment]
There is an other issue with the same topic and today has been created a PR to support this with a system setting! So we can close this. :)

#modxbughunt
@modxbot close
