### ISSUE TITLE
Different tree styles for unpublished + hidemenu

### ISSUE THREAD

**Issue by inreti** [modxcms/revolution#12644]
### Summary
Not possible to differentiate hidemenu at the resource tree.

![screenshot from 2015-09-10 16 22 48](https://cloud.githubusercontent.com/assets/2852461/9790787/38dd0bb8-57d8-11e5-91e1-d94146e4f06e.png)

### Step to reproduce
Create a resource with unpublished+hidemenu and another one with unpublished+!hidemenu.
 
### Observed behavior
Both resources are displayed in the same way at the resource tree. Style italic, same color. 

### Expected behavior
Hidemenu: opaque color, unpublished: italic. The unpublished+!hidemenu style should be colored normal (resource 3 in the screenshot), and italic. 

### Environment
2.4.0-pl, 2.4.0-dev. FF and Chrome. 

Maybe this behaviour is intended, but imho the state styles _should_ be different. 

I would also like something better, though this is not a quick fix and I currently do not know exactly how to achieve. Either the unpublished or the hidemenu state should be visualized by anything else than the text style/color - perhaps an overlay icon for hidemenu?

**Comment by rthrash** [comment]
I would think the Unpublished but shown in menu would match the color of the Published resource: color to indicate menu toggle, italics to indicate publish status.

**Comment by inreti** [comment]
@rthrash yep, thats what I wanted to say with "colored normal". So to be exact, (3) has to be italic and with the color of (4).

**Comment by rthrash** [comment]
I concur and that's what I was trying to say, too. :+1:

**Comment by inreti** [comment]
Great :-)
