### ISSUE TITLE
Default media source in contexts not working with the resource browser

### ISSUE THREAD

**Issue by mdehaan** [modxcms/revolution#12648]
For TinyMCE, TinyMCE Rich Text Editor 1.1.0-pl, FCK editor and all other WYSIWYG the resource browser doesn't show the default media source that is set in a context.

This is the fix.
Can this please get implemented in the core?

http://forums.modx.com/thread/87320/default-media-source-in-contexts-not-working-with-the-resource-browser

**Comment by alroniks** [comment]
It works as expected in 3.x
