### ISSUE TITLE
Error on system/event page.

### ISSUE THREAD

**Issue by mishantrop** [modxcms/revolution#12640]
`$this->modx->toJSON($this->logArray)` returning empty string.
File /core/cache/logs/error.log exists.
![logarray](https://cloud.githubusercontent.com/assets/5341208/9755007/eeb1f4a6-56d6-11e5-9860-1b996d96626b.png)

**Comment by mishantrop** [comment]
I cleared the file, the error disappeared.
But when error.log contain this text, bug appears:
> [2015-08-31 11:29:36] (ERROR @ /index.php) Array
> (
>     [name] => МИША
> )

**Comment by bezumkin** [comment]
JSON [works only with UTF-8](https://en.wikipedia.org/wiki/JSON#Data_portability_issues).

**Comment by mishantrop** [comment]
@bezumkin I write in error.log data, received from YandexKassa. 
Now charset of recreated file is UTF-8, but error appears.
![1](https://cloud.githubusercontent.com/assets/5341208/9757781/5071408e-56eb-11e5-9080-728be4d2d722.png)

**Comment by OptimusCrime** [comment]
Duplicate of #13079 

Closing in favor of issue with more information.

@modxbot close
