### ISSUE TITLE
modMail error - can't embed images

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12645]
### Summary
It's impossible to embed images using modMail service.

### Step to reproduce
Try to use `$modx->mail->embedImage();`

### Observed behavior
Image is not embedded due to the error in MODX phpMailer wrapper

### Expected behavior
Image should be embedded

### Environment
MODX 2.3.x, 2.4.0

The error is in `/core/model/modx/mail/modphpmailer.class.php`, line 251:
```
$this->mailer->AddEmbeddedImage("/".$image,$cid,$name,$encoding,$type);
```
As you see, leading slash is always added, making every path absolute. As a quick fix one should remove leading slash:
```
$this->mailer->AddEmbeddedImage($image,$cid,$name,$encoding,$type);
```
to mirror actual phpMailer AddEmbeddedImage function.

OT: what is the rationale behind modMail at all? I don't see any advantages of this wrapper. It's poorly documented and difficult to update (e.g. we can't just drop in a new version of phpMailer. Actual vesion is 5.2.12 while MODX still uses 5.2.8)

**Comment by Mark-H** [comment]
> OT: what is the rationale behind modMail at all? I don't see any advantages of this wrapper. It's poorly documented and difficult to update (e.g. we can't just drop in a new version of phpMailer. Actual vesion is 5.2.12 while MODX still uses 5.2.8)

The ability to use other mailers rather than just phpmailer :) There's only one other modMail instance I can think of which is for Swift, but there might be others.

**Comment by Alroniks** [comment]
I agree with @Mark-H 
It's good practice to use wrapper (adaprter design pattern or the same) for doing operations, but have ability transparently change implementation.
Nonetheless, bug with image path should be fixed.
