### ISSUE TITLE
Extras rating in the manager

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12659]
I think the rating system in manager extra installer is a bit flawed. Extras in top-10 list always have a lot of attention, especially from newcomers, and recieves a lot of installations. This is a self-supporting process and a source of troubles. For example, Breadcrumbs and phpThumbOf extras that are abandoned and heavily outdated are still shown in the "most popular" list. TinyMCE, №1 in this list is updated 3 years ago, and more modern and (imo) more useful CKEditor isn't shown at all.

**Comment by beau-gosse** [comment]
+1

**Comment by Jako** [comment]
+1

**Comment by fourroses666** [comment]
+1

**Comment by mishantrop** [comment]
+1

**Comment by achterbahn** [comment]
+1
