### ISSUE TITLE
Spaces in URI encoded as +

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12656]
### Summary

Spaces in URI query strings are encoded as + in generated URIs.
### Step to reproduce

Using MODX link tag with spaces in its properties such as [[~42? &file=path/to/some file name.pdf]]
### Observed behavior

This will generate a URI with the spaces replaced with a + sign, which can break scripts consuming the generated URI.
### Expected behavior

The generated URI should have spaces replaced with the correct RFC 3986 compliant %20 encoding
### Environment

All versions, any environment.

The modLinkTag class, in core/model/modx/modparser.class.php, in its process() function, uses the PHP function urlencode() on line 1326 which does replace spaces with + signs. The PHP function rawurlencode uses RFT 3986 entities for replacement. So changing the use of urlencode() to rawurlencode() would solve this issue.

**Comment by syts88** [comment]
I'm going to try and fix this today.

**Comment by sottwell** [comment]
I'm pretty sure this was already fixed https://github.com/modxcms/revolution/pull/12675#issuecomment-216269895

**Comment by sottwell** [comment]
core/model/modx/modparser.class.php on line 1338
```                        if ($qs= implode('&', $qs)) {
                            $qs= rawurlencode($qs);
                            $qs= str_replace(array('%26','%3D'),array('&amp;','='),$qs);
                        }
```

**Comment by syts88** [comment]
You are right :)! So perhaps this issue should be closed official. We need to get the open issue counter down :) #modxbughunt

**Comment by sonicpunk** [comment]
Awesome work and communication!!!!  Thanks!!!
