### ISSUE TITLE
Download class problems in 2.4

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12658]
The updates for dependency injection have broken SiteCheck, and possibly other extras.

First of all, this is what the process() function returns for me  when it's *successful*:

    Array
    (
        [success] => 
        [message] => Could not download and create transport package with signature: peoples-1.0.1-pl
        [total] => 0
        [errors] => Array
            (
            )
        [object] => Array
            (
            )
    )
I'm not sure what it returns on failure, but if [errors] is empty, there's no way to tell if the call was successful..

Second, consider this code I was using because process() doesn't return any helpful error messages -- just a generic failure message:

        if (!$processor->provider->getClient()) {
            return $this->modx->lexicon('sitecheck_provider_err_no_client');
        }

        $processor->getTransportPackage();
        $metaLoaded = $processor->getPackageMetadata();
        if ($metaLoaded !== true) {
            return 'Failed to load package metadata';
        }
        $processor->getPackageMetadata();
        $processor->setPackageVersionData();
        $url = $processor->getFileDownloadUrl();
        if (!is_string($url)) {
            return 'Failed to get package URL';
        }
        if (!$processor->downloadPackage($url)) {
            return $this->modx->lexicon('sitecheck_package_download_err')
                . ' ' . $url;
        }

getClient() is now protected and none of the other methods exist any more, so they all result in PHP fatal errors. I can live without the missing functions (assuming that just calling process() in the same way will work in older versions of MODX), but the processor should really return the proper value for [success[ and [message]. I can't figure out why it doesn't.

**Comment by BobRay** [comment]
[Update] I've confirmed that the return array is exactly the same when trying to download a non-existent package, so there's no way to know if the call was successful. I would think that makes this a serious bug for MODX itself.

**Comment by Mark-H** [comment]
getClient being protected is being addressed in #12633

In your code samples, what is $processor an instance of?

**Comment by BobRay** [comment]
modPackageDownloadProcessor

**Comment by BobRay** [comment]
I see what's happening. It's not the bug I thought it was. The problem is that I was using the downloadPackage() method, which is gone. My use case is fixing a package that exists in the DB, but has no transport file, so I want to download the transport file, but don't want to save it in the DB.  

The process() method calls provider->transfer(), which both downloads the package and tries to save it in the DB. Saving it fails (because it's already there), so success is false even though the transport file is downloaded.

It looks like I'll have to write my own downloadPackage() method (ouch) if I can get  information necessary to do it. Go ahead and close this if the downloadPackage() method is not coming back.

**Comment by silentworks** [comment]
@theboxer close
