### ISSUE TITLE
Display Template Variables Header when below content?

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#12651]
When you set TVs to display below the content, the are displayed there but there is no title to help relay to users that those are template variables.

![](http://j4p.us/image/2K2Q2U110D0z/Screen%20Shot%202015-09-14%20at%208.52.39%20AM.png)

Yet there always is for content
![](http://j4p.us/image/0q2z161G0J0B/Screen%20Shot%202015-09-14%20at%208.54.40%20AM.png)

Seems inconsistent and might be helpful to new users if there were a Template Variable title to identify them in all cases

**Comment by Mark-H** [comment]
I get the consistency argument, but I have to say I personally do like how it's just there. Editors don't have to know it's called a template variable in that case. 

Does the content need a title? :P [/devilsadvocate]

**Comment by jpdevries** [comment]
it does look nice like that but according to a11y you need a title. I also think it makes it easier to say to newbs (scroll passed the content area and you'll find template variables) and have it clarified what you referring to (because what if a plugin inserts something _in between_ the content and tv area and now your instructions don't make any sense)

**Comment by sottwell** [comment]
It's easy enough to rename the tab in FC by giving the modx-panel-resource-tv a title.

**Comment by jpdevries** [comment]
I'm wondering if it should ship that way though...

**Comment by OptimusCrime** [comment]
This has not generated any interest or activity in a few years and was mostly met with opposing opinions. Closing. Feel free to reopen or comment.

@modxbot close
