### ISSUE TITLE
Revert commit 8896c78a040e190e0548db7d9670aa771ef9a2ab

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12668]
### Summary
https://github.com/modxcms/revolution/commit/8896c78a040e190e0548db7d9670aa771ef9a2ab prevents displaying Image+ thumbnails on some servers. See this thread http://forums.modx.com/thread/73897/tv-input-type-imageplus?page=8#dis-post-532085

### Step to reproduce
It is a server specific issue and I don't have that issue. The thumbnail image is calculated wrong. It is described on http://forums.modx.com/thread/73897/tv-input-type-imageplus?page=6#dis-post-531868 and after.

### Observed behavior
The thumbnail image is calculated wrong.

### Expected behavior
The thumbnail image should be calculated right. 

### Environment
MODX 2.4 and Image+ 2.3.x

**Comment by theboxer** [comment]
Reverted
