### ISSUE TITLE
MODx file browser - cannot select folder if folder contains at least one file

### ISSUE THREAD

**Issue by hexcollective** [modxcms/revolution#12679]
In at least the last 2 versions of MODx REVO -  it's not been possible to select folders in the file manager when the folder has at least one file, the selection always defaults to the 1st file.
This means that the only way to ensure you can upload to the required folder is to upload files using the CTRL/click context menu. 
I assume this isn't a feature though rather a minor bug.
<img width="583" alt="folder-selection" src="https://cloud.githubusercontent.com/assets/692359/10135094/09be927a-65e3-11e5-8a0a-540f834470bd.png">

**Comment by Alroniks** [comment]
Checked on latest 2.5.5, all works fine. @Mark-H Candidate for closing.

**Comment by sottwell** [comment]
Also appears to be fine in 2.5.4
![screen shot 2017-02-09 at 21 22 08](https://cloud.githubusercontent.com/assets/1073780/22799261/dd205a2c-ef0d-11e6-8a3f-a359b67eeb18.png)
