### ISSUE TITLE
Slash should be stripped from an alias

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12671]
### Summary
If we create a resource with a pagetitle containing slash sign ("/"), it's auto-generated alias will also contain it.
E.g. "MIG/MAG torch" pagetitle genrates "mig/mag-torch" alias. This breaks friendly URL for this resource and makes it unreacheable.

### Step to reproduce
Crete a new resouce with a pagetitle containing slash sign.

### Observed behavior
Resource is unreacheable by URL. E.g. http://mysite.com/mig/mag-torch.html returns 404, because this URL does not match an actual hierarchy of resources - there is no "mig/" container.

### Expected behavior
Slash should be "escaped" or replaced with dash.

### Environment
2.x

**Comment by sottwell** [comment]
See the System Setting "friendly_alias_restrict_chars_pattern" for a regular expression you can modify as you wish.

**Comment by whitebyte** [comment]
Yes, but this check should be enabled by default.

**Comment by sottwell** [comment]
Hmm... is that setting applied to the automatic generation of the alias?

**Comment by whitebyte** [comment]
Yes it does, and also affects realime alias. Slightly modified regex
``` 
/[\/\0\x0B\t\n\r\f\a&=+%#<>"~:`@\?\[\]\{\}\|\^'\\]/
``` 
seems to resolve this. I suppose this regex should be used by default. This isn't the first time I ran into this issue, and it may be "hidden" for a long period. I found it by occasion when checking a site for broken URLs.

**Comment by sottwell** [comment]
Yes, that works. At any rate it strips it from the alias. Would be nice if it replaced the specified illegal characters with a hyphen.

**Comment by opengeek** [comment]
You can have it replaced by hyphen if you add it to the word delimiters instead of restricted chars. However, the URL should be perfectly valid if it includes a `/` — i.e. that URL should be reachable.

**Comment by sottwell** [comment]
How can it be a valid URL? MODX is going to think that "this/that.html" is a resource with the alias "that" with a parent with an alias of "this".

**Comment by whitebyte** [comment]
@sottwell that's exactly what i'm talking about.

**Comment by Mark-H** [comment]
MODX doesn't search through the tree, it searches by URI. `this/that.html` is a perfectly valid URI. 

I've just tested this on a local 2.3.5 install, works fine here.

**Comment by sottwell** [comment]
And so it does. I retract and repent.
