### ISSUE TITLE
Static file, media source and browser window

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12681]
### Summary
If you edit i.e. a snippet with a static file (i.e. snippet file) that uses a different media source than the default media source, the MODX-Browser window opens with the default media source and not with the selected media source.

### Step to reproduce
Create a snippet, set it to static, select a media source for the static file, open the MODX-Browser by click on the static file browse icon.

### Observed behavior
The MODX-Browser is opened with the default media source.

### Expected behavior
The MODX-Browser should open with the selected media source.

### Environment
MODX 2.4.0

**Comment by rtripault** [comment]
This appears to be solved in 2.5 branch, so closing.

Feel free to reopen if needed ;)
