### ISSUE TITLE
Custom context settings not recognised inside @CHUNK binding

### ISSUE THREAD

**Issue by hugopeek** [modxcms/revolution#12682]
When you have a TV with an @CHUNK binding to generate the Input Options, it seems that you cannot use custom context settings in that chunk.

Example chunk code:

```
--- Select a CTA ---==0||
[[getResources?
    &parents=`[[++overview_cta_id]]`
    &tpl=`@INLINE [[+pagetitle]]==[[+id]]`
    &outputSeparator=`||`
    &showHidden=`1`
    &showUnpublished=`1`
    &limit=`99`
    &sortBy=`menuindex`
    &sortDir=`ASC`
]]
```

The overview_cta_id setting only works when you add it to System Settings too, and then it will grab the value from there. Everywhere else outside the TV, the correct value of the context setting is being shown.

Replacing the @CHUNK binding with an @EVAL binding and a snippet call has the same effect:

```
@EVAL $cta = $modx->getOption(overview_cta_id); return '--- Select a CTA ---==0||' . $modx->runSnippet('getTVInputOptions',array ('parents' => $cta));
```

MODX 2.4.1
Also confirmed in MODX 2.3.5

**Comment by sottwell** [comment]
Did you try specifying the context in the getResources properties?

**Comment by hugopeek** [comment]
Yes I did. I also tried `$modx->context->getOption`, to no avail.

An easier way to replicate the issue is to just return the option as input value immediately:

```
@EVAL $test = $modx->getOption(some_custom_context_key); return $test;
```

**Comment by Mark-H** [comment]
Have a look at $modx->context->key; that will be mgr and not the web/secondary context you might expect.
