### ISSUE TITLE
MODX 2.4.1 - Duplicate URL's - no warning in the MODX manager

### ISSUE THREAD

**Issue by smashstack-kris** [modxcms/revolution#12687]
### Summary

I have 2 sites I recently upgrade to the 2.4.x branch and when saving MODX resources in the manager, no warning is being given when there are duplicate URL aliases.
### Step to reproduce

Create 2 resources with the same URL alias.  Save 1 and then create a new resource with the same URL alias...no warning occurs.
### Observed behavior

I was expecting a warning and did not get one.  As a result clients have Resources on the site and when a user clicks to go to this Resource, instead they are redirected to the homepage of the site.
### Expected behavior

There should be a warning (in the past the field would have a red border applied to the alias field) and you could not save the Resource.  There is no longer a warning.

In the MODX documentation for [duplicate alias](https://rtfm.modx.com/revolution/2.x/administering-your-site/settings/system-settings/allow_duplicate_alias), there is a value to set to check for duplicate alias.  I'm not seeing this option in the 2.4.x branch.  Instead I see `setting_global_duplicate_uri_check` [which I set to "yes"](http://files.smashstack.com/1foNX/3DJlWD4W) assuming this would do the same as the above setting.  Even when set to "yes" no warning is given when creating a duplicate alias.
### Environment

MODX 2.4.1 running on the MODX cloud.

**Comment by boformer** [comment]
I can confirm this.

**Comment by jcdm** [comment]
I can confirm this is still the case in 2.4.2-pl

**Comment by jcdm** [comment]
Further to this, in recent discussion it was pointed out that this was about being able to duplicate branches and ensure that their leaves held their aliases. The fix will need to check the primary page being duplicated for a duplicate URL and rewrite it before allowing any descendants to stay as they are.

**Comment by syts88** [comment]
As of MODX 2.5.5 Revo, you will get a error. And you cant use a duplicate alias. So this issue is fixed. #modxbughunt

**Comment by alroniks** [comment]
The original issue fixed in 2.7.0-dev, however, some other bugs exists in this area and described already. I am closing this one.

About the last comment, it works fine I guess. When `automatic_alias` allowed and after duplicating the resource, the new alias will be generated after saving the new duplicated resource. And in most cases, titles will be different, but when aliases will be the same user will get the error message.
