### ISSUE TITLE
Add sanity check in Widget Controller

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12684]
Above line 61 of the manager\controllers\default\system\dashboards\update.class.php file, there's no sanity check on the $placement->getOne('Widget') call. If the placement exists and the widget doesn't (how this can happen is another issue), line 61 throws a PHP fatal error. 

```
        $placement->getOne('Widget');
        if ($placement->Widget->get('lexicon') != 'core:dashboards') {
            $this->modx->lexicon->load($placement->Widget->get('lexicon'));
        }
```

I'm not sure what should happen if the widget doesn't exist -- maybe this:

```
  if (! $placement->getOne('Widget')) {
       $placement->remove();
       continue;
   }
```

**Comment by Ibochkarev** [comment]
@Alroniks @Jako fix was merged #13604 .

Please close.
