### ISSUE TITLE
Unable to access dashboard 504 error.

### ISSUE THREAD

**Issue by MarkOdey** [modxcms/revolution#12689]
After I connect it the process never finishes. I eventually get a 504.

```
    $modx->request->handleRequest();
```

  this line makes it break. If I comment it out I get a blank page. 

I have been able to connect onto the manager by bypassing the dashboard therefore it seems the dashboard is the problem.

I have found out that the news feed in the dashboard was provoking a 504. 

If someone could help me track down this one it would be awesome.

Thanks 

Mark

**Comment by MarkOdey** [comment]
I believe this is related. Analytics seems to be the problem maybe?

[2015-10-02 01:06:34] (ERROR @ /home/schizoghost/webapps/fonderiedarling_dev/core/components/analytics/model/analytics/analytics.class.php : 37) PHP warning: curl_setopt(): You must pass either an object or an array with the CURLOPT_HTTPHEADER, CURLOPT_QUOTE, CURLOPT_HTTP200ALIASES and CURLOPT_POSTQUOTE arguments

**Comment by amdbuilder** [comment]
Can you tell us more about your hosting environment?  Also what happens if you disable the news and security feeds in the system settings?

**Comment by MarkOdey** [comment]
Hey, Well the problem goes away of course.  The website is running on php 5.5, Apache/2.2.3, CentOS release 5.11 (Final)

**Comment by Mark-H** [comment]
Sounds like an issue retrieving feeds, which was probably temporary.
