### ISSUE TITLE
Add version parameters to manager css and js

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#12690]
Just a quick idea. 

I've spend ages telling clients why the manager sometimes looks funny after updates and how to solve this problem.

How about we add the version number to script and link tags?

```
<script src="/manager/assets/modext/core/modx.js?v=2.4.1pl" type="text/javascript"></script>
```

This would force a browser to load the most recent fileversion after every update/upgrade.

Regards,

pepebe

**Comment by zaigham** [comment]
This is great idea actually, we always do this with public facing websites to bust caches, so why not for manager.

:+1:

**Comment by amdbuilder** [comment]
There is one potential problem with that approach.  If the resource is included on the login page, the version number would be publically revealed.  What about a random string of say four characters, generated during the setup/upgrade process?

**Comment by pepebe** [comment]
@amdbuilder Good point. I like the idea of a random string. 

Taking about security. I never thought about this, but all those manager specific js and css files could also be used for finger printing.

Can anyone give a good reason why not to slim down the necessary code to a generic login.css and a generic login.js?

**Comment by inreti** [comment]
Random string +1. Or random number. A 2-byte hex should be enough to mark a new css version. Could be simply stored as a system setting, whenever setup is run. As it is just a "version-like" parameter to certain urls, it shouldn't interfere with anything. 

What about using "_settings_version_token_" for the key name?

**Comment by pepebe** [comment]
@inreti Sounds good to me.

Anyone volunteering for a PR? I don't see me looking into this before the end of October.

**Comment by inreti** [comment]
I still have some other PRs to work on, but I can try it in the next 2 weeks.

**Comment by pepebe** [comment]
If you beat me on this, I'll buy you a beer!

**Comment by inreti** [comment]
Almost done. Just a few tests missing... :-)

**Comment by pepebe** [comment]
Beer always gets it done :-).

**Comment by pepebe** [comment]
Either pm me your address or wait for modxexpo and get it there.

**Comment by inreti** [comment]
@pepebe: well, we missed the beer exchange at the modxpo :-(.

**Comment by OptimusCrime** [comment]
This has been solved.

@modxbot close
