### ISSUE TITLE
Expanding instead of editing

### ISSUE THREAD

**Issue by mishantrop** [modxcms/revolution#12698]
Hello. 
Could you create the system option e.g. "expand_parent = 1/0"? It would be nice, because icon for expanding is so small (one reason).
Expanding instead of editing when clicking on resource (isfolder=1) in resources tree.

**Comment by whitebyte** [comment]
How will we edit container nodes in this case? Especially when we haven't "right click" option (tablets etc).

**Comment by sottwell** [comment]
tablets etc "right-click" if you hold on an ordinary click, at least Adroid does. Anyway, what about double-click for edit?

**Comment by sottwell** [comment]
That should be fairly easy to remember, as all of the grids edit with double-click.

**Comment by mishantrop** [comment]
whitebyte, continuous tap is replacement of right click. At least that's in my case (Android 5).

**Comment by vasyahuyasa** [comment]
I like behaviour with small arrow as it is now.

**Comment by Mark-H** [comment]
Since #12773, clicking outside the text but inside the list item will expand instead of edit the resource.
