### ISSUE TITLE
Duplicate does not preserve menu order

### ISSUE THREAD

**Issue by intersel** [modxcms/revolution#12696]
When duplicating entire folders and their children, the menu order of the items is not preserved.

To Reproduce :
- Create a MODx resource
- Create multiple resources under that resource
- Create multiple grandchildren so you end up with a folder of folders, each with some children.
- Right-click the parent resource and choose to "Duplicate"

The result is generally a mixed order, menu index is randomly set :-(

It's really a big issue when copying (sub)tree for other contexts or creating things from a tree template...

**Comment by intersel** [comment]
Update:
When looking at the file core/model/modx/modresource.class.php, found that there is a settings 'preserve_menuindex' that when set to 1 will preserve the menu index order...?

Add it in my settings and sounds to do the job....
Is that the correct way to fix this problem?

**Comment by pixelchutes** [comment]
Good to know! Wasn't aware of `preserve_menuindex` either... Not sure why this setting is missing / must be manually added?

**Comment by pixelchutes** [comment]
I guess an additional question would be: Can `preserve_menuindex` be added without clobbering an existing value for anyone who may have stumbled upon this setting and manually added it?

**Comment by opengeek** [comment]
It can be added easily — new settings added in the build are only created if they do not already exist.
