### ISSUE TITLE
Missing Lexicon Error: MediaSource Access Policy

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#12701]
![image](https://cloud.githubusercontent.com/assets/2213127/10320083/349ef49e-6c37-11e5-88a2-205b42c4cee0.png)

Just noticed when a Policy isn't selected there is an empty error on the Media Source access policy creation window.

**Comment by syts88** [comment]
I'm going to try and fix this today.

**Comment by syts88** [comment]
Entered a pull request with the fix. #modxbughunt

**Comment by Mark-H** [comment]
Fixed in 2.5.6
