### ISSUE TITLE
Silent Fail on Login where User doesn't have mgr Context access.

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/revolution#12706]
Uers who are in User Groups that do not have access permissions for the manager (`mgr`) context who attempt to login to the MODX Manager will see the login page reload and silently fail. It appears that upon submit, the manager page reloads, a 301 redirects to the manager with no trailing slash eg: `manager` and then 302 to `manager/`. 

This should not fail silently, should it?

**Comment by bezumkin** [comment]
I will try to fix it

**Comment by OptimusCrime** [comment]
Is this fixed then?

**Comment by gpsietzema** [comment]
Jup 👍 🎉

**Comment by bezumkin** [comment]
I think Optimus asked about to close this issue. Lets try this magic!

@modxbot close
