### ISSUE TITLE
MODx.config is empty

### ISSUE THREAD

**Issue by MarkOdey** [modxcms/revolution#12707]
Hello guys, its me again with crazy bugs.

This one is kind of hard to debug actually. I migrated my site onto a local environement and for some reason once I reach the manager, the MODX.config is empty. I have been able to figure this out as it seems that these config are being injected to javascript in core/model/modx/processors/system/config.js.php at line 93 and this causes a syntax error in javascript.

After that I managed to output the Modx.config alone to figure out that it is actually empty

This setup is running locally with wamp. I using a vhost to point my environement to a certain url 

ie pictographix.localhost

The front end works fine however. Even after clearing my cache, I am able to regenerate the page with modx.

Could someone help me debug this one.

Thanks

**Comment by inreti** [comment]
This may happen if the config returned by the processor is not valid json. Is there anything in your error.log? (Both MODX error log and MAMP apache error log?

**Comment by pixelchutes** [comment]
Is it `MODx.config`? (lowercase 'x')

**Comment by MarkOdey** [comment]
Hey guys, Sorry for this I feel my apache vhosts where not properly set.  Thanks for the attention it's greatly appreciated.
