### ISSUE TITLE
User's Photo not display in manager

### ISSUE THREAD

**Issue by ViieeS** [modxcms/revolution#12718]
After 2.4 update user's photo not display in manager. Incorect path, because this method is return string(1) "/":
```php
 $this->xpdo->getOption('connectors_url', MODX_CONNECTORS_URL)
```
### /core/model/modx/moduser.class.php line: 884

![_ _moon river_ - google chrome 2015-10-14 08 23 55](https://cloud.githubusercontent.com/assets/8194543/10474179/eafb4330-724c-11e5-8a7c-55cb4fa694b0.png)
![ekscom - e__projects_ekscom - c__users_viiees_appdata_local_temp_scp17907_www_moonriverwedding ru_core_model_modx_moduser class php - phpstorm 9 0 2 2015-10-14 08 24 24](https://cloud.githubusercontent.com/assets/8194543/10474191/fd602df6-724c-11e5-9224-cde38bbe9b4c.png)

**Comment by Setest** [comment]
Hey peoples, somebody fix it with: 
```php
return $this->xpdo->getOption('connectors_url', null, MODX_CONNECTORS_URL)...
```

**Comment by ViieeS** [comment]
@Setest thank you, it's work))

**Comment by christianseel** [comment]
PR is merged. Issue should be closed.
