### ISSUE TITLE
Issue: Multiple snippet tags bug

### ISSUE THREAD

**Issue by HitkoDev** [modxcms/revolution#12715]
### Summary
Incorrect result when there are several identical snippet tags on the same page

### Step to reproduce
Make a snippet with the following code, then insert multiple (uncached) snippet tags on the same page.
```php
$pl = $modx->getPlaceholder('dsfsdfds');
if(!$pl) {
    $pl = 1;
} else {
    $pl++;
}
$modx->setPlaceholder('dsfsdfds', $pl);
return $pl . ' * ';
```

### Observed behavior
Output: __5 * 5 * 5 * 5 * 5 *__  (the final value of the placehoder gets outputed on each call)

### Expected behavior
Output: __1 * 2 * 3 * 4 * 5 * ...__ (the output increments with each call)

### Environment
Tested on MODX 2.4.2, probably occurs on previous versions as well. The most likely candidate for this bug is something like ```$content = str_replace($tag, $output, $content);``` in the parser.

**Comment by pixelchutes** [comment]
See #11338

**Comment by Bruno17** [comment]
you will need to call the snippet with different params each time.
you could try ```[[!yoursnippet? &placeholder=`[[dsfsdfds]]`]]```
does it work, then?

**Comment by HitkoDev** [comment]
@Bruno17 that doesn't solve the problem. As long as the snippet tags are identical, the output from the last call will override output from the previous calls. Adding spaces to the snippet tag will make a difference though (same spaces -> same output), even though the params are equal.

**Comment by HitkoDev** [comment]
https://github.com/modxcms/revolution/pull/12716
