### ISSUE TITLE
FontAwesome font file not found

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12713]
/working/templates/default/fonts/fontawesome-webfont.woff2/?v=4.4.0 is causing a MODX page-not-found error in working/templates/default/css/index.css

This is new to Revo 2.4.2

I don't know if this is in some way related to the fact that the 'manager' directory has been renamed to 'working'.

```
@font-face { 
font-family:FontAwesome;
src:url(../fonts/fontawesome-webfont.eot?v=4.4.0);
src:url(../fonts/fontawesome-webfont.eot?#iefix&v=4.4.0) format("embedded-opentype"),
url(../fonts/fontawesome-webfont.woff2?v=4.4.0) format("woff2"),
url(../fonts/fontawesome-webfont.woff?v=4.4.0) format("woff"),
url(../fonts/fontawesome-webfont.ttf?v=4.4.0) format("truetype"),
url(../fonts/fontawesome-webfont.svg?v=4.4.0#fontawesomeregular) format("svg");
font-weight:400;
font-style:normal 
}
```

**Comment by jpdevries** [comment]
Unable to reproduce on 2.4.x branch Safari latest. It shouldn't matter if manager was renamed to working, the font files are loaded relative to the CSS file.

What browser? I'm not sure what browsers woff2 is for.

**Comment by pixelchutes** [comment]
Is the site in a subdirectory, by chance?

**Comment by sottwell** [comment]
Firefox 41.0.1 OS X.

That's what shows up in the LogPageNotFound error log. Every time the Manager page is loaded. 

```
/working/templates/default/fonts/fontawesome-webfont.woff2/?v=4.4.0 	12/10/15 17:46:05:884 	84.228.213.249 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:41.0) Gecko/20100101 Firefox/41.0 	IGLD-84-228-213-249.inter.net.il 	http://benzodev.work/working/templates/default/css/index.css
/working/templates/default/fonts/fontawesome-webfont.woff2/?v=4.4.0 	12/10/15 17:46:14:431 	84.228.213.249 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:41.0) Gecko/20100101 Firefox/41.0 	IGLD-84-228-213-249.inter.net.il 	http://benzodev.work/working/templates/default/css/index.css
```

**Comment by sottwell** [comment]
All of the expected icons in the Tree and elsewhere, as far as I can tell anyway, are displayed as expected.

**Comment by sottwell** [comment]
No, not in a subdirectory.

**Comment by sottwell** [comment]
Odd... did a localhost installation in exactly the same way, and it's not doing it, nor do any Cloud installations seem to be doing it. So I'd have to say this is something weird with that particular installation.
