### ISSUE TITLE
processor resource/update have bug

### ISSUE THREAD

**Issue by vovanfenix** [modxcms/revolution#12723]
If i don't send parameter content_type, which designated as optional in processor
resource/update, method getAliasPath return url without (.html). Then this URL go in method
isDuplicateAlias() for checking takes, and takes won't be found. But normal url with html in the end will save in database. 
![Image of Yaktocat](http://dl1.joxi.net/drive/0007/3957/503669/151015/0bb7a23e08.jpg)
![Image of Yaktocat](http://dl1.joxi.net/drive/0007/3957/503669/151015/d0d75af9a1.jpg)
Sorry for my bad English.

**Comment by core01** [comment]
@vovanfenix эта проблема еще актуальна?

**Comment by alroniks** [comment]
I am closing it as issues do not have many details and too old. If issues still valid, please, reopen.
