### ISSUE TITLE
Please create way to turn tooltips OFF, and/or set the delay time

### ISSUE THREAD

**Issue by rainbowtiger** [modxcms/revolution#12732]
I can't believe this hasn't been officially requested here before. Has it? We need a way to turn tootips off. They can be very annoying for experienced users. Addtionally, being able to set the timing would be good.

**Comment by sottwell** [comment]
About a hundred +++++ for this one. They drive me crazy.

**Comment by Jako** [comment]
Disabling this is quite simple, edit change line 324 in manager/assets/modext/util/utilities.js from
`if (this.description) {` to `if (false) {`. This part could be made configurable by a MODX system setting.

Setting/changing showDelay does not work in my tests after line 92 in manager/assets/modext/core/modx.js for some reason.

**Comment by sottwell** [comment]
The only thing I have against completely disabling them is that a few of them on the toolbars are actually convenient. It's the ones on the resource editing forms that are such a nuisance.

**Comment by jpdevries** [comment]
What if we just got real crazy and printed the descriptions out on the page? Notice what I've done to the description field here:

![](http://j4p.us/image/2Z0N2u2e2A3a/Screen%20Shot%202015-10-25%20at%201.41.17%20PM.png)

For accessible and responsive design (there is no hover on touch devices) simply printing the description under the title of the field is a total win. The way ExtJS implements tooltips is pathetic from an accessibility perspective. I'd give it an F-. Screen readers won't speak them. People without hover won't see them. People without JavaScript well, you get the picture.

**Comment by eighthday** [comment]
you can do it with a plugin on OnManagerPageInit:

    $modx->regClientStartupHTMLBlock('
       <script type="text/javascript">
        Ext.onReady(function() {
            Ext.QuickTips.disable();
        });
      </script>
    ');

but yes, a system setting to disable would be great.

**Comment by jpdevries** [comment]
I'm curious if people want to disable them because the hover effect is annoying or because the information is considered not useful. If it is the former I think we should simply print the description below each title which could also be considered an a11y improvement.

### See Also
https://github.com/modxcms/revolution/issues/12757
https://github.com/modxcms/revolution/pull/12664#issuecomment-142355890
https://github.com/modxcms/revolution/issues/2176

**Comment by rainbowtiger** [comment]
Because it's annoying. I wouldn't want the description below the title because that make the Document area taller, pushing the content area even farther down the page, and I already have to expand my browser height to the very bottom of my 21" screen to edit content and see the entire content box without having to scroll down. The only way around that (and this would be a different good thing to have) would be to use a cookie and have MODX remember the setting for collapsing and expanding the top tabbed area, so that a user can collapse the top tabs in order to see the content area by itself, and then move from resource to resource to edit content, maintaining the collapsed tabs without have to click the up arrow for every single resource.

**Comment by SnowCreative** [comment]
Seems like this has gone nowhere. Anyone interested in taking it on?

**Comment by Ruslan-Aleev** [comment]
Logically related - https://github.com/modxcms/revolution/issues/3357

**Comment by Mark-H** [comment]
Fixed in #14535
