### ISSUE TITLE
[Feature Request] "Next Resource" / "Previous Resource" buttons in Manager

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12739]
The point of this is to avoid needing to go back to the resource list just to select the next resource in the list.
It would double the speed of data entry especially when working with collections.

It's not so bad when using regular resources, as you can select the next resource from the tree on the left, but when working with collections after an edit you need to go back before you can go forward.

The next resource should be determined by however they are currently sorted under the current parent and could default to sort by menuindex I guess.

I know this could have been a collections issue but would love to have this on regular documents too.

**Comment by inreti** [comment]
Maybe then it is a good idea to have these buttons provided by Collections? It already has the "back to collection" extra button, and more collection navigation buttons would be useful esp. there. 
You should open that issue there: https://github.com/modxcms/Collections/issues

**Comment by digitalpenguin** [comment]
Fair point, but the reason for putting it here was it would also be handy to have on regular documents as when doing a lot of data entry people often hide the resource tree to prevent it refreshing all the time.

**Comment by OptimusCrime** [comment]
This is something that can be solved by developing an extra. If this is an issue related to Collections, the best solution would be to solve it there.

@modxbot close
