### ISSUE TITLE
Deactivated plugins not greyed out anymore in tree

### ISSUE THREAD

**Issue by hugopeek** [modxcms/revolution#12733]
![image](https://cloud.githubusercontent.com/assets/5436121/10657824/c2bd88dc-78a1-11e5-9468-312894a1123f.png)

It was still working in 2.3:

![image](https://cloud.githubusercontent.com/assets/5436121/10657802/80e7c472-78a1-11e5-8487-6e45d403e1eb.png)

**Comment by sottwell** [comment]
Opened, fixed and merged #12710

**Comment by hugopeek** [comment]
Ah sorry, I didn't find that one.. Nice work!
