### ISSUE TITLE
Legacy files not removed during setup

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12737]
In MODX 2.3 and 2.4, most processors have been converted to be class based. (see #11437).

If a site began on an earlier version of MODX *(e.g. v2.2)*, it seems the original processors still remain on the FS.

Should there be some kind of process during setup put in place for the MODX instances not installed from Git to perform this cleanup?

**This is just a sample of some of the old processors that still exist:**

![legacy_processors](https://cloud.githubusercontent.com/assets/352182/10717088/8b192c78-7b13-11e5-9fdf-98c4822d2d82.jpg)

**Comment by inreti** [comment]
IMHO that should be done by setup for _all_ legacy files. In fact I had an instance where a hacker added a file inside the connectors folder. And as upgrading only consists of copying over/merging new files to the old ones, any legacy (and illegal) file stays in the installation until eternity...
At least, at the end of setup, there should be an information window if legacy files are detected. 
Or even better IMHO - it should be included in the config check...

**Comment by pixelchutes** [comment]
@inreti Great point!

I've submitted the above PR to target MODX 2.5.0, which hopefully identifies *any* legacy file, not just processors.
