### ISSUE TITLE
date.timezone setting should be requested on install

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12735]
The current behaviour is a bit annoying, if the date.timezone setting is missing in PHP:

```
FATAL ERROR: MODX Setup cannot continue.

To use PHP 5.3.0+, you must set the date.timezone setting in your php.ini. Please do set it to a proper timezone before proceeding. A list can be found here.
```

Two options are thinkable: use a default date.timezone setting or prepare an input for the user to generate it and try a @ini_set for this before showing the error message.

**Comment by digitalpenguin** [comment]
+1
