### ISSUE TITLE
Download option broken for files on S3

### ISSUE THREAD

**Issue by studiorepublic** [modxcms/revolution#12730]
### Summary

Right clicking on a file hosted on S3 in the files panel and choosing download causes an error.
### Step to reproduce

See above
### Observed behavior

This fatal error:
Fatal error: Call to a member function make() on null in /XXXXX/core/model/modx/processors/browser/file/download.class.php on line 36
### Expected behavior

The file should download
### Environment

MODX 2.4.2 on OSX and Apache

**Comment by flolopdel** [comment]
Hi!
I had the same issue. I fix it trying to replay the modFileHandler download function in the download procesor.php. This is the easy way to fix it. The right solution will be create other modFileHandler for the S3 media sorce.

My solution is change in the /XXXXX/core/model/modx/processors/browser/file/download.class.php file the **download function**

> FROM

```
public function download() {
    $fileobj = $this->source->fileHandler->make($this->source->getBasePath() . $this->getProperty('file'));

    $fileobj->download();
}
```

> TO

```
public function download() {

    if(get_class($this->source) == "modS3MediaSource_mysql") {
        $fileobj = $this->source->getObjectContents($this->source->getBasePath() . $this->getProperty('file'));

        $options = array_merge(array(
            'mimetype' => 'application/octet-stream',
            'filename' => $fileobj['basename'],
        ), $fileobj);

        $output = $options['content'];

        header('Content-type: ' . $options['mimetype']);
        header('Content-Disposition: attachment; filename=' . $options['filename']);
        header('Content-Length: ' . $options['size']);

        echo $output;
        die();
    }else{
        $fileobj = $this->source->fileHandler->make($this->source->getBasePath() . $this->getProperty('file'));

        $fileobj->download();
    }
}
```

**Comment by Jako** [comment]
Nice idea! Could it be made more general (not only for 'modS3MediaSource_mysql') or more special by putting the download code into the modS3MediaSource object.

**Comment by alroniks** [comment]
Works in 3.x with S3 bucket attached
