### ISSUE TITLE
Creating a name with a quote in the Lexicon breaks the manager...

### ISSUE THREAD

**Issue by intersel** [modxcms/revolution#12748]
When creating a new entry in the lexicon with a quote like in "Plan d'Accès" ("access map" in french) as a name, then save the entry, everything goes fine... but refreshing the manager and you lost it... no more left bar, just the top menus that don't work, well... the manager is broken....

Ext-Js generates an error due to the quote in the javascript...

The solution is not easy:
- remove the quote in the mysql database in modx_lexicon_entries table
- clear the cache on the server...

If we could just protect the entry names with quote would be great... because when it happens, it is quite scary!

**Comment by Mark-H** [comment]
This appears fixed. If you can still reproduce it, please reopen the issue.
