### ISSUE TITLE
Resource icon in the tree ignores "isfolder" flag

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12742]
### Summary
It seems that resource icon in the tree ignores `isfolder` flag. Even if it's checked, resource shown as a regular one. Only actual presence/absence of children is taken into account. I think "folder" resource should be shown as "folder" icon even if it contains zero children. "isfolder" flag affects fURL suffix, so it's state should be clearly visible in the tree.

### Environment
2.4.2

**Comment by pixelchutes** [comment]
Fixed in `v2.5.1`
