### ISSUE TITLE
session_cookie_lifetime has no effekt on manager login (remember me)

### ISSUE THREAD

**Issue by weitblick** [modxcms/revolution#12754]
In MODX 2.4.2 "remember me" in manager login has no effect any more. The browser forgets the login after closing it.

It is reproducible in MODX cloud plain installation of MODX 2.4.2:
manager login -> "remember me" -> close browser after login -> open the manager page again -> :-(
(for comparison: in MODX 2.2.16-pl it works as expected)

**Comment by timbx** [comment]
Yes, I found the same problem.
Looking to Login processor code https://github.com/modxcms/revolution/blob/2.x/core/model/modx/processors/security/login.class.php#L32. There's a compare the value of "rememberme" checkbox and "on" value. The problem that value of "rememberme" is "1", NOT "on".

**Comment by Mark-H** [comment]
Fixed per merge #12802
