### ISSUE TITLE
Feature request: system setting to hide modx version

### ISSUE THREAD

**Issue by eighthday** [modxcms/revolution#12753]

**Comment by OptimusCrime** [comment]
Hide it from where?

**Comment by digitalpenguin** [comment]
Just guessing - but I assume in the top-left corner of the manager.

**Comment by jpdevries** [comment]
Also see https://github.com/modxcms/revolution/pull/12496#issuecomment-157266965

**Comment by OptimusCrime** [comment]
Still wondering why this is wanted? What do you gain by hiding this? In 9 of out 10 cases it is better to actually display the version than hiding it.

I mean, using system settings we can add options to show, hide and manipulate more or less every piece of the manager, but I am starting to wonder WHY we want to do just that.

**Comment by eighthday** [comment]
The reason is to provide a clean. non technical UI for clients.

**Comment by OptimusCrime** [comment]
Sure, makes sense. I can see if I get the time to prepare a pull request for this. Should be rather simple.

**Comment by rtripault** [comment]
> The reason is to provide a clean, non technical UI for clients.

I'd say that's rather the purpose of a manager theme, don't you think ?

**Comment by eighthday** [comment]
Bit overkill for a manager theme ? also manager themes have the habit of breaking with upgrades / moving clouds etc..

**Comment by jpdevries** [comment]
I don't think you need a separate manager theme, you can just add a stylesheet that

```css
#modx-site-info .full_appname { display:none }
```

**Comment by eighthday** [comment]
yes I have done this using a plugin - would be nice as a system setting 👍

**Comment by rtripault** [comment]
> Bit overkill for a manager theme ? 

Could be, was just sharing some thought... 
Anyway, it's just a matter of changing a system setting & adding a file.
I find it easier/faster than creating a plugin.

**Comment by Mark-H** [comment]
Many different ways to solve this exist today, so closing.
