### ISSUE TITLE
Context menu order doesn't preserved after page refresh

### ISSUE THREAD

**Issue by whitebyte** [modxcms/revolution#12759]
If we have multiple contexts on a site and sort them in desired order by drag'n'drop, and then reload a page, contexts become sorted alphabetically and don't remember their menu order.

2.4.2

**Comment by whitebyte** [comment]
Well, I just realized that sort order can be preserved with `context_tree_sort` system settings is turned on. So technically this issue may be closed. But now I'm trying to figure out, what is the purpose of this setting? Are there any use cases when we dont't want contexts to be sortable? If so, contexts should not be sortable at all when `context_tree_sort` setting is disabled and shouldn't silently restire initial order after page reload.

**Comment by OptimusCrime** [comment]
I agree that this setting should be on by default. It might be because of backwards changes or something? Still voting to change the default behavior here.

**Comment by sebastian-marinescu** [comment]
This should definitely be activated by default. 
Or if the setting is deactivated by default, it shouldn't allow dragging around the contexts.
Also the description of this setting **needs** to be corrected, as it states it sorts _alphanumerically_.

**Comment by christianseel** [comment]
Closing because the PR has been merged. The setting is on by default in the next minor release.
Also I created #13537 to fix the setting descriptions.
#modxbughunt 

@modbot close

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @christianseel
