### ISSUE TITLE
Ditch bower?

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#12765]
Apparently it is down to 1ish maintainers and development has ceased https://twitter.com/chris_hugs/status/665514225259823104

People are talking about switching to npm.

Maybe the community will pitch in and save bower but it isn't sounding likely.

**Comment by Omeryl** [comment]
Bower doesn't seem dead, per se, they're looking for more active contributors and funding to continue, it seems:

https://github.com/bower/bower/pull/1748#issuecomment-154819159

**Comment by jpdevries** [comment]
I personally like bower, but some say it doesn't have much of a roadmap.
https://github.com/rackt/redux/issues/944#issuecomment-154858804

Bower seems to serve revolution's purposes just fine imo. Just made the issue for the discussion and to keep an eye on where bower goes, if anywhere.

**Comment by jpdevries** [comment]
Paul Irish shed some light on the situation. Sounds like things were over exaggerated https://twitter.com/robertschultz/status/665211786656813058

**Comment by Omeryl** [comment]
Over exaggeration in opensource? Sheesh, that never happens ;).
