### ISSUE TITLE
sanitize filenames on upload and folders on creation

### ISSUE THREAD

**Issue by luluabraham** [modxcms/revolution#12767]
At the moment users are able to create files and folders with space and other non alphanumeric characters. It would be great if files/folders were automatically sanitized upon creation or upload.

**Comment by Pathologic** [comment]
You can use http://modx.com/extras/package/filesluggy
Creation of more suitable solutions need https://github.com/modxcms/revolution/issues/12752 and https://github.com/modxcms/revolution/issues/12751 to be solved.

**Comment by exside** [comment]
also the filetranslit package is helpful in that regard http://modx.com/extras/package/filetranslit

**Comment by christianseel** [comment]
There are extras available to get the desired functionality, so I'm closing this.
@modxbot close
