### ISSUE TITLE
Double Quote in page title causes a blank manager page after save.

### ISSUE THREAD

**Issue by neoneddy** [modxcms/revolution#12769]
Example title was of a person - Catherine "Katie" Holmquist

**Comment by Pathologic** [comment]
Simply add double quote to friendly_alias_restrict_chars_pattern system setting.

**Comment by OptimusCrime** [comment]
Does not happen in 2.4.0-git.

Closing as fixed. Feel free to reopen if this is still an issue.

@modxbot close
