### ISSUE TITLE
PHP 5.6 and its annoing self-signed SSL issues - PHPMailer (SMTP) related

### ISSUE THREAD

**Issue by rutkas** [modxcms/revolution#12763]
Latest PHP blocks SMTP SSL connections to the servers with self signed certificates or the certificates with domain names not matching. So if we have an own mail server with self signed cert it is hard to make SMTP through ssl or tls working. It would be perfect to add an option to turn off the PHP strict check (unfortunately PHP does not give an option in .ini to do that). This code (that should be set before launching PHPMailer) makes PHP to ignore nasty certificate checks and would allow self signed certs:

$mail->SMTPOptions = array(
    'ssl' => array(
        'verify_peer' => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    )
);

I think that bool option like "mail_smtp_ignore_verify_ssl" = true - could run this code and allow using own mail servers with self signed SSL certificates. but for respecting PHP security ideas default should be false (do not change these vars)

**Comment by inreti** [comment]
Hmm... wouldn't it be better to provide a proper certificate instead? This is pretty easy to do if you have your own mailserver, and it is possible to get free certificates e.g. at StartSSL or with the new LetsEncrypt service. This way you can also get rid of any problems with Outlook, where you can't "accept" invalid/self-signed certificates...

Besides: It is a good idea to have that checks configurable. But I would split it up and not have verify_peer, verify_peer_name and allow_self_signed in one setting. A binary combined value should do the trick here. verify_peer = 1, verify_peer_name = 2, allow_self_signed = 4 and so on... That way other options can be added without adding more and more system settings for the same problem domain. Of course the possible values have to be in the system setting description then to make it self-explaining.

**Comment by rutkas** [comment]
Of course providing properly signed certificate can help. I have added the certificate symlink with the hash name to the cert vault in /etc/ssl/certs and php on this server now accepts my certificate.. Even not needed to sign it on free CA services.

But anyway it should be a *simple* option to pass the certificate checks. Binary values requires more time to understand this feature to the user. Maybe each option separately will be correct, like:
smtp_ssl_verify_peer
smtp_ssl_verify_peer_name
smtp_ssl_allow_self_signed
each option could be true, false and not set. if not set - the default php behaviour is left

**Comment by Mark-H** [comment]
I'm not a fan of workarounds like that.
