### ISSUE TITLE
Image crashing MediaManager?

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#12768]
### Summary

Just finished "debugging" a very strange issue where the MediaManager crashed completely because of an image file (which doesn't look suspicious at all).
### Step to reproduce

It's just one single file (see attachment) that is able to result in this problem, it was uploaded by one of our editors. As soon as it finishes uploading (that it does), the media manager becomes inaccessible in the folder where that file was uploaded, it returns a 503 Service Unavailable Error, also further uploads seem not to be possible anymore to that directory. The 503 errors are returned by either the directory.php connector or the fileapi.php connector, but I believe the problem is originating from phpthumb trying to make a thumbnail from that image. This I believe for the reason that the no-thumbnail directory-listing in the Files-Tab is still working while the media manager dies...

![screen shot 2015-11-19 at 11 19 55](https://cloud.githubusercontent.com/assets/445501/11270778/0eace536-8ec2-11e5-8404-5a854eb182e7.png)

**This is not really a bug report as it's an edge case MODX probably cannot do anything about, but it would be interesting to know wtf is wrong with this file, I wasn't able to see anything strange about it...so maybe somebody else can have a closer look at that file and maybe sees something strange?**
### Environment

MODX 2.2.x, Litespeed (Apache), PHP 5.5

This is the file I'm talking about (beware, could crash your media manager =D, just delete it either via FTP or via Files-Tab, then everything works again)
![snowpenair 615x390](https://cloud.githubusercontent.com/assets/445501/11270680/35c8e436-8ec1-11e5-85e4-c5512fe05d95.jpg)

I'm not really familiar with file forensics, so I don't really know how to interpret something like 
http://www.imageforensic.org/show/5fd3995c7db552509385417ba5248d35/ee1e8a43-9112-4534-9456-74ca10964051

**Comment by jpdevries** [comment]
is it still broken if you refresh the page and browse the media manager to the folder where that image is located? If not, it must be something specific to the upload process? Is the image large? Could it be over or close to your max upload file size? Have you been able to upload images similar in either file size or dimensions successfully?

**Comment by exside** [comment]
Yes absolutely, the folder is not accessible via MediaManager anymore, the error shown in the screenshot above will immediately appear, the thumbnails will not load and the file cannot be deleted via media manager (which was the problem for the editors as they don't have access to the Files-Tab in the Tree) and consequently the image (although uploaded into that folder) is not selectable via TVs...so basically any directory that image is uploaded to is completely inaccessible via MediaManager, it is accessible via the Files Tab and the image can be deleted there as well, which resolves the problem.

Regarding filesize: not at all, thought the same, and tried with a huge 10MB image, no issue at all, upload maxsize is at 300MB (as we also upload videos) and yes, all other images with similar or bigger dimensions work without problems...

something with that specific image is wrong so phpthumb cannot process it, so I'm trying to find out what exactly is wrong with that image. The point of that would (hopefully) be to find a way to detect such images and avoid breaking directories in such a way as it just happened, e.g. make the media manager more robust against (seemingly) corrupted files.

Sidenote: I actually use pThumb to do the thumbnailing in the MediaManager...ugly core hack...but phpthumb is way too slow for a lot of images...server likes to slow down drastically or even crash when phpthumb "thumbnails" a folder with 500+ images...the problem mis the "dynamic" fetching of the thumbnail via php connector/processor instead of just linking static cached thumbnail files...

**Comment by inreti** [comment]
I cannot reproduce that (MODX 2.3.5 and 2.4.2) - maybe github sanitizes the image you posted here? Can you store the image somewhere else and provide a download link, so that we are absolutely sure to get the original data file?
Another point: please turn on debugging for modx and set pthumb to debug - maybe the log lines give more information about what is going wrong at which step. I suspect either the fact that the image is uncompressed or something special inside the metadata of the file - which sometimes causes trouble e.g. with special chars inside...

**Comment by Mark-H** [comment]
Closing due to lack of feedback on @wuuti's follow up questions.
