### ISSUE TITLE
Landing Pages for Top-Level Menu Items?

### ISSUE THREAD

**Issue by jpdevries** [modxcms/revolution#12777]
Over in https://github.com/modxcms/revolution/pull/12776 we are working on making the 2.5 manager interface for mobile friendly. It is coming along nicely, but the roll over top navigation doesn't translate very well to touch.

![](http://j4p.us/image/1K3Y1C3o3U1z/Screen%20Shot%202015-11-22%20at%204.39.03%20PM.png)

So, I'm thinking it would be great if each top-level menu item was a link to an associated landing page. Thoughts?

This would allow me to click the Media Sources top level icon, be taken to a landing page, which some Media Source related stuff and some nice big buttons to access the links in the roll-over nav.

**Comment by Devlanda** [comment]
I think with the current web techniques a loose landing page for Top Level menu items would be not be an added value.

**Comment by OptimusCrime** [comment]
Not in favor of implementing this. The menu is fine as it is, we should perhaps look into other ways of transforming the manager to make it more mobile friendly. For example collapsing it using the typical burger-approach as you can find in for example [Bootstrap](http://getbootstrap.com/css/).

**Comment by rtripault** [comment]
Agreed here too, so let's close!

Feel free to comment/reopen if needed.
Thanks
