### ISSUE TITLE
Allow [[++url_scheme]] in site_url config

### ISSUE THREAD

**Issue by minagerges** [modxcms/revolution#12789]
This allows a context to keep it's URL scheme whether http or https when creating full url links

```
[[~123? &scheme=`full`]]
```

currently http(s) is expected and anything else causing the view button of a resource to have the tag appended to the opened url

```
https://site.ext/manager/[[++url_scheme]]/manager/resourse123.html
```

**Comment by Mark-H** [comment]
Try {url_scheme} instead, I think that should work.
