### ISSUE TITLE
Changed Symlink Template Variables Reverting to Linked Values

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#12780]
Modified Symlink Template Variables keep reverting to linked resource TV values in web context. When editing the page in the manager they are correct.  When cache is refreshed after editing they are correct again in the web context but at some point revert back to the linked version's values.  I don't know how to reproduce because they are always correct immediately after editing but revert back after some time of non-editing.

**Comment by Mark-H** [comment]
Isn't the idea the of symlinks that they are kept in sync? Sounds like at some point (perhaps a save of the target resource) the data is updated.

**Comment by Mark-H** [comment]
Closing due to lack of feedback. If still an issue feel free to reopen.
