### ISSUE TITLE
Uberbar fails to open on wide viewport

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12792]
### Summary
Since the merge of #12776, I've noticed that Uberbar does not open for larger viewports (e.g. `1400px`, likely less)

### Step to reproduce
Install current MODX 2.5.0-dev, attempt to open Uberbar (above mobile/tablet viewport widths)

### Observed behavior
Clicking magnifying glass does nothing.

### Expected behavior
Clicking magnifying glass should open Uberbar.

### Environment
MODX 2.5.0-dev, latest Chrome / Safari (OS X)

### Related
#12776

**Comment by pixelchutes** [comment]
Threshold appears to be ~ `640px`

Anything below, and the uberbar does open *(however, the arrow / visual connector is not aligned correctly)*:

<img width="373" alt="uberbar" src="https://cloud.githubusercontent.com/assets/352182/11505334/23a8e310-9807-11e5-9ad2-8725fff38a75.png">

**Comment by jpdevries** [comment]
hmmmm that is odd. I'll have a look. All the Sass in https://github.com/modxcms/revolution/pull/12776 should be wrapped in a mobile media query so it shouldn't affect desktop styles but I'll take a look
