### ISSUE TITLE
checkbox's label style is overlapping

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#12796]
### Summary

![checkbox-styling-bug](https://cloud.githubusercontent.com/assets/308524/11522109/43b997e6-98e6-11e5-939d-fe1a1499081e.png)
### Step to reproduce

Create checkbox with boxLabel
### Observed behavior

The label goes on top of checkbox
### Expected behavior

It should be on the right of checkbox
### Environment

MODX 2.4.0-pl

**Comment by Mark-H** [comment]
This doesn't appear to happen with e.g. the published or hide from menu checkbox when editing a resource, so I suspect it may be (at least in part) originated in your own extjs. Perhaps the `layout` is not set to form? Or is this in specific browser?

**Comment by goldsky** [comment]
For my case, it's for top toolbar.
It worked fine for 2.3.x

**Comment by OptimusCrime** [comment]
Closing as this most likely is an error in the user implementation, not the core.

If this is indeed a problem we need some code to reproduce the exact problem.

@modxbot close

#modxbughunt
