### ISSUE TITLE
[utf8, i18n] While performing workspace/packages/rest/getList manager json request, result is malformed

### ISSUE THREAD

**Issue by altmind** [modxcms/revolution#12806]
Thank you guys for your great work on modx, it is really pleasant cms to work with.

I run modx on xampp, on windows machine with default russian culture(important).
Here is the phpinfo output(if you need it) https://altio.us/files/phpinfo-f981bea1.html

Wherever i go to "Package Management" and select some node, i see empty data table. It seems that i receive malformed ajax response. 

```
Request URL:http://modx.local/connectors/index.php
action:workspace/packages/rest/getList
provider:1
tag:4d66d2e6b2b0830ebe000006
HTTP_MODAUTH:modx5662b753aeac48.84193901_15662b801bcbc75.20300196
```

Response

``` json
{"success":true,"total":"25","results":}
```

I tracked down problem to \modProcessor::outputArray - \xPDO::toJSON. line `json_encode($array)` fails with error `JSON_ERROR_UTF8`. It seems that json_encode chokes while trying to encode releasedon field(which stores localized date):
![What we try to serialize](http://i.imgur.com/U4Q6gjp.png)

The field is generated like this
![image](https://cloud.githubusercontent.com/assets/107891/11611094/f6ef8116-9bcc-11e5-94a3-337e5ef7d531.png)

It seems that the result in `releasedon` is in local system encoding(which is cp1251 in my case), not in utf8. We may need to encode localized dates to utf8 before outputting them
![image](https://cloud.githubusercontent.com/assets/107891/11611107/7606ad94-9bcd-11e5-813b-3f466ec57e9f.png)

Unfortunately, i dont know how to get default system encoding, phpinfo dont seem to mention anything like "cp1251". It also seems that php.ini 'default_charset' is not set.

**Comment by altmind** [comment]
I understand that this is corner case(system should be non-unicode, default_charset is not set to utf8 either), however this breaks part of modx. One of solutions may be to add check for default_encoding to be set during install time, or manually set it in index.php/.htaccess

**Comment by Jako** [comment]
Closing this in favour of #13079 because the other issue is more general. A solution without a patch is mentioned in https://github.com/modxcms/revolution/issues/13079#issuecomment-268984710. I hope it catches all charset issues.
