### ISSUE TITLE
MODX news feed and SSL

### ISSUE THREAD

**Issue by exside** [modxcms/revolution#12805]
Just switched my sites to Let's Encrypt SSL and noticed, that the MODX News Feed dashboard widget throws a mixed content warning because of the smiley added to a news entry (2.4.2)...

```
Mixed Content: The page at 'https://www.somesite.tld/manager/' was loaded over HTTPS, but requested an insecure image 'http://modx.com/assets/components/discuss/themes/modx/images/smileys/laugh.gif'. This content should also be served over HTTPS.
```

This could easily be avoided by just using a protocol relative url for that smiley, e.g.

```
//modx.com/assets/components/discuss/themes/modx/images/smileys/laugh.gif
```

While this doesn't actually make the manager less secure, it is desirable to show the SSL lock icon (or similar) to clients and myself. The only solution is to either disable the feed altogether or write some kind of proxy script that strips out the image tags in news entries, which seems overkill, so I'd kindly ask that somebody with access to that news feed content changes that URL to be protocol relative (and that should be checked each time a new entry is published =D)

**Comment by Mark-H** [comment]
One slight problem there is that MODX.com doesn't work over https...
Op 5 dec. 2015 11:09 p.m. schreef "Lukas Zahnd" <notifications@github.com>:

**Comment by exside** [comment]
oh man...you're right...ok, remove that smiley! =)

@modx, what about using Let's Encrypt, its free!

**Comment by jaygilmore** [comment]
It's not a matter of the cert. We have a cert for modx.com. It's not in place due to technical limitations. I'll revisit with the team and see what can be done.

**Comment by Alroniks** [comment]
https://letsencrypt.org/ can be good solution

**Comment by exside** [comment]
@jaygilmore: Or you could just remove that problematic smiley from the newsfeed? =)

**Comment by exside** [comment]
anybody? That cannot be so hard, no?

Just remove that:

![screen shot 2016-01-10 at 23 15 34](https://cloud.githubusercontent.com/assets/445501/12224422/386bdf7e-b7f0-11e5-8f9a-6c02eb6c2797.png)

**Comment by pixelchutes** [comment]
Closing. Just checked the feed and the source protocol for the infamous smiley appears to have been updated to `https`:
 
> https://modx.com/assets/components/discuss/themes/modx/images/smileys/laugh.gif :smile:

I've got the green lock :lock: in Chrome for the Manager, and dev tools Network > `mixed-content:display` filter is empty!
