### ISSUE TITLE
Editors unable to logout

### ISSUE THREAD

**Issue by Lefthandmedia** [modxcms/revolution#12819]
For my editors i made a copy of the acces policy 'Content Editors' and added a few policies.
And even though 'logout - To be able to logout as a user.' IS checked the user has no possibility in the manager to actually log out.
In 2.4.2-pl

**Comment by sebastian-marinescu** [comment]
> the user has no possibility in the manager to actually log out

You mean he actually doesn't *see* the Dropdown with the Logout-Link? 
Is **menu_user** maybe needed for that?

**Comment by sottwell** [comment]
Yes, that one has given me pause from time to time when I forget it.

**Comment by OptimusCrime** [comment]
`menu_user` is required to display the user navigation menu. Also `logout` is required for the actual logout action. Adding these will solve the problem. Confirmed in 2.5.1.

Closing this as not an issue. Feel free to reopen or comment if you feel otherwise.

@modxbot close
