### ISSUE TITLE
Missing remove old packages button

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12818]
### Summary

To clean up the space of an installation, a 'Remove Old Packages' button is missing.
### Step to reproduce

In Package Mananagement the details of a package could be shown with a list of all previous installed package versions. The entries in that grid could be removed one by one. There is a button missing for 'Remove Old Packages' that removes all old package versions.
### Expected behavior

The Button should remove all old package entries in the database and all old package files on the installation for that package.

**Comment by Mark-H** [comment]
Ready for 2.7
