### ISSUE TITLE
Missing context settings after editing name or description

### ISSUE THREAD

**Issue by tillilab** [modxcms/revolution#12823]
If a user changes one of the context settings, modifying name or description, new entries are added inside the modx_lexicon_entries table; 
so the function inside **/core/model/modx/mysql/modcontextsetting.class.php** outputs multiple results due to the join conditions of the query.
This produces inconsistent **pagination** of context settings and some of them are just **not** displayed.

May be possible solution could be:
1) add inside the modcontextsetting.class.php the query option: 
$c->groupby("modContextSetting.{$xpdo->escape('key')}");
Not a real solution...since it returns the first result and usually it's not the most updated lexicon entry

2) avoid duplication of lexicon entries, updating existing ones

**Comment by Mark-H** [comment]
Option 2 sounds best.

**Comment by Flowan** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by EasterPeanut** [comment]
#modxbughunt Tested this PR and works, no new entries in the modx_lexicon_entries table are added.

**Comment by Mark-H** [comment]
Fixed in 2.5.6
