### ISSUE TITLE
Resource overview close button not working

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12822]
### Summary

When viewing a Resource Overview page, clicking the <kbd>close</kbd> button does nothing.
### Step to reproduce
1. Right-click a Resource in the tree
2. Select Overview
3. Click the <kbd>close</kbd> button
### Observed behavior

Nothing happens.
### Expected behavior

The page should close and either go back, or to the dashboard.
### Environment

MODX 2.4.x / OS X 10.11.1 / Chrome 48

**Comment by jpdevries** [comment]
I think this begs the question do we even need a close button to begin with?

**Comment by pixelchutes** [comment]
In general, or on the Overview page?

**Comment by jpdevries** [comment]
In general IMO. It seems fairly pointless even on the overview screen. Do we really need a Close button in the action bar of the resource edit screen?

I'd also make a case for removing the Help! button from the action bar (I tried to sneak removing it into 2.3 but it didn't fly)

**Comment by pixelchutes** [comment]
Perhaps related to my previous [comment/question](https://github.com/modxcms/revolution/issues/12660#issuecomment-142322186) regarding `action=resource/locks/release`. Seems to be some confusion around it.

Regardless, to your point, irrelevant to Resource Overview...
