### ISSUE TITLE
uberbar search result resource icons ambiguous

### ISSUE THREAD

**Issue by smaddock** [modxcms/revolution#12828]
### Summary

This appears to be a repeat of #11875. The uberbar resource search results should use the same icons as the resource tree.
### Step to reproduce

Search for resources in the uberbar.
### Observed behavior

All resources use identical "file" icons
### Expected behavior
- The icon shown for Resources should match what is used in the resource tree.
- If the result is a Weblink / Symlink / Static Resource, it should uses the specific icon for that resource type.
- If the result is a CRC or has a template icons, those should be displayed instead.
### Environment

MODX 2.4.2

**Comment by smaddock** [comment]
PR #12749 offers a workaround using a custom processor, but the above should still be in core.

**Comment by neoneddy** [comment]
I just came here to say, weblinks should have a different icon.  Or they should match the tree styles.  Which may have been said here or in another.  That is all.

**Comment by alroniks** [comment]
Note for me and other contributors: it seems one AC missed - about template icons attached to resources.

**Comment by alroniks** [comment]
Checked in 2.7.0-dev, it respects template icons too.
