### ISSUE TITLE
Can't Create Database on New Install

### ISSUE THREAD

**Issue by MarkG33** [modxcms/revolution#12829]
MODX could not create your database. Please manually create your database and then try again.

This is an issue which has been discussed before in the Modx forums here 

http://forums.modx.com/thread/91476/modx-could-not-create-your-database-please-manually-create-your-database-and-then-try-again#dis-post-525324

I've just done another fresh install and the problem still exists nearly 18 months later.

This time I just tried re entering the same info several times and eventually it installed.

So there's obviously some issue here.

Sometimes it works sometimes it doesn't.

Anyway see the original post for more details.

I'm just reporting the bug here so that it's on record.

**Comment by sottwell** [comment]
Did you look in your server's error logs to see if they had anything relevant to the issue?

**Comment by MarkG33** [comment]
Nothing in the server logs.

And only this in the modx error logs

(ERROR @ /home/armadal2/public_html/core/model/modx/processors/system/config_check.inc.php : 94) PHP warning: curl_setopt(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set

**Comment by OptimusCrime** [comment]
This is due to incorrect server settings and is not a MODX error.

**Comment by inreti** [comment]
The problem with the database creation at setup is weird. I had it before sometimes. I heard of a workaround, which indeed worked: place your cursor in one of the input fields, and press RETURN. Sounds weird, but then it works - if your settings are correct. Therefore I think it must be a js bug at the setup page. But as it is not reproducible reliably, it's hard to fix...

**Comment by pixelchutes** [comment]
I +1 that this intermittent error exists. I've yet to identify how to reliably reproduce, but can confirm does happen on occasion as described.

**Comment by adamwintle** [comment]
It looks like this is a specific server setup issue and not actually a core MODX problem.  You can post on the MODX Forums or Slack chat rooms (http://modx.org) for extra setup help

@modxbot close
