### ISSUE TITLE
Improve ht.access handling during/after install

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12837]
### Summary

Some ideas for better handling of ht.access files during/after install
### Observed behavior

During/after the installation some ht.access files have to be renamed manually to .htaccess 
### Expected behavior

That could be automated somehow: Check if the host is running on apache, check if no .htaccess file exists (at several places), check if a checkbox 'Rename/Prepare .htaccess files' is set during install -> then rename the files. That way an automatic Friendly URL system setting activation could be provided.

Maybe the same system could be prepared for other host systems like nginx etc.

**Comment by sottwell** [comment]
I'm sorry, usually I'm all for automation, but I have a sinking feeling that this would cause far more problems than the existing way it's handled ever has. There are just too many variations on server configurations for a CMS (or any other) application to meddle with the server.

**Comment by lokamaya** [comment]
Agree with Susan Ottwell. I choose nginx over apache when available, that make .htaccess automation not usable.

**Comment by inreti** [comment]
@lokamaya That's no reason not to do it. If you are using nginx you will probably not be affected by the .htaccess, do you? 

And why don't you want an option to make this automatically during setup? I really don't like this "I don't need this, so no one has to have it" behaviour. If it is optional, you personally will not be affected. But we are developing a system for a lot of people, many of them not experienced with exactly those "server" things, some may just forget to do it the right way. 

_If we ever want MODx to come out of it's niche existence, we have to provide ways to make it more easy to install, more easy to secure and overall less error prone even for experienced users._

I plea for a constructive argumentation: what are the edge cases here? @jako 's proposal was to check for a very focused case: apache running, no .htaccess already existing, (additional check for mod_rewrite is not necessary if htaccess is build with a check condition). What possible problems do we expect then? How can we prevent them? Overall, we can have it all optionally- if you don't tick the checkbox, nothing will be done and everything is like it always was. If we don't detect an environment case we are absolutely sure we can handle automatically we don't even need to show the option to the user. 

Besides, I remember we had the same somehow choked discussion about the .htaccess protecting the core folder in #12565, #12490.

**Comment by lokamaya** [comment]
Seem this stuff has been discussed many times @inreti. :+1:

**Comment by OptimusCrime** [comment]
Can any core members shed some light on this? Is this functionality we want inside the core or is this considered something the devs should do as a part of their "right of creative freedom"?

**Comment by OptimusCrime** [comment]
One year later and no feedback.

@modxbot close
