### ISSUE TITLE
Update MODX's LinkedIn link description in the help section of the manager

### ISSUE THREAD

**Issue by beau-gosse** [modxcms/revolution#12831]
## Summary
The link description for MODX's LinkedIn account currently reads: `LinkedIn: google.com/+modx`. That's wrong. 

## Step to reproduce
See the "_You can also follow MODX on these channels_" section under `manager/?a=help`

![modx-manager-help](https://cloud.githubusercontent.com/assets/509451/11855170/9a6aa8a6-a416-11e5-9310-d70aacb4d977.png)

## Expected behaviour
It should read: `linkedin.com/groups/MODX-697477` or whatever else is more relevant.

## Environment
MODX 2.4.x

**Comment by Mark-H** [comment]
@beau-gosse Would it be possible for you to send a pull request for that fix by chance? :) It's stored in manager/templates/default/help.tpl in the 2.x branch

**Comment by beau-gosse** [comment]
@Mark-H Sure thing! I'll do it as soon as I get a chance.

**Comment by beau-gosse** [comment]
@Mark-H Done!
