### ISSUE TITLE
System Setting Paging issue

### ISSUE THREAD

**Issue by phillipdade** [modxcms/revolution#12832]
MODXCloud Hosted, revolution version 2.4.2-pl

When viewing system settings and clicking the next button, pagination doesn't work. I get redirected to page 101 of 5, instead of page 2 of 5.

![screen shot 2015-12-22 at 11 56 40](https://cloud.githubusercontent.com/assets/8309145/11954775/19addf08-a8a3-11e5-8da1-68b8347f243a.png)

**Comment by pixelchutes** [comment]
I cannot reproduce this (at least not on `2.4.3-dev`). What specific browser + version / operating system?

**Comment by Mark-H** [comment]
Can't reproduce either on 2.4.3-dev on Mac in Chrome, Firefox or Safari.

**Comment by Mark-H** [comment]
I am actually reproducing now, but only if the `default_per_page` system setting is set to a number larger than 30... wut?

**Comment by Mark-H** [comment]
Found it, PR is incoming.
