### ISSUE TITLE
Can't delete resource from resouce group from manager

### ISSUE THREAD

**Issue by Kookabura** [modxcms/revolution#12842]
When there are multiple equal resources in different group you can't choose the wanted one by click. That happens because of equal id for resources.
The bug might be fixed by replacing line 59 at core/model/modx/processors/security/resourcegroup/getnodes.class.php
`'id' => 'n_'.$resource->get('id').'_'.$resourceGroup->get('id'),
`

**Comment by Mark-H** [comment]
Thanks for the report, a fix is pending merge in #13283.

**Comment by sdrenth** [comment]
@Mark-H This issue can be closed according to
https://github.com/modxcms/revolution/pull/13283

**Comment by Mark-H** [comment]
We tend to keep issues open until a fix has been merged, and we don't merge our own pull requests ;)

**Comment by rtripault** [comment]
Closing as it's merged for 2.5.6
