### ISSUE TITLE
Modx SQL ODBC Error 42S22

### ISSUE THREAD

**Issue by ASM87** [modxcms/revolution#12845]
### Summary

SQL Error in manager error log. No resources load in tree. Front end fails to load.
### Step to reproduce

A fresh install on the environment listed below will produce this error every time.
### Observed behavior

No resources load in the resource tree

(ERROR @ / connectors/index. php) Error 42S22 executing statement: 
Array
(
    [0] => 42S22
    [1] => 207
    [2] => [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'true'.
)
### Environment

Windows Server 2008 / IIS 7 
SQL Server 2008 R2
PHP Version 5.6.10
SQL drivers: php_sqlsrv_56_nts.dll & php_pdo_sqlsrv_56_nts.dll
MODX Revolution 2.4.2-pl

**Comment by Mark-H** [comment]
I don't have a similar enough environment to test that on currently, but I can definitely agree that "true" is not a valid column name! Don't suppose you have had any luck figuring out what query specifically is causing the error?

**Comment by opengeek** [comment]
ODBC Driver 11? This should be using the SQL Server PDO driver, no?

**Comment by kelly8116** [comment]
Any new information? I've verified that the PDO driver is installed and I'm still getting the same error message.

**Comment by kelly8116** [comment]
I have some more information about this.

Changing this line in the core/model/modx/processors/resource/getnodes.class.php file resolves the site tree issue:

[b]Original:[/b] [code]$c->leftJoin('modResource', 'Child', array('modResource.id = Child.parent AND Child.show_in_tree = true'));[/code]
[b]New:[/b] [code]$c->leftJoin('modResource', 'Child', array('modResource.id = Child.parent AND Child.show_in_tree = 1'));[/code]

This is running on SQL Server. Is this a bug or an environment issue? Can anybody help shed some light on this?

[b]Environment:[/b]
Windows Server 2012 R2 Standard
IIS 6.0
SQL Server 2008
PHP 5.6.15

[b]Drivers:[/b]
extension=php_mysql.dll
extension=php_mysqli.dll
extension=php_mbstring.dll
extension=php_gd2.dll
extension=php_gettext.dll
extension=php_curl.dll
extension=php_exif.dll
extension=php_xmlrpc.dll
extension=php_openssl.dll
extension=php_soap.dll
extension=php_pdo_mysql.dll
extension=php_pdo_sqlite.dll
extension=php_imap.dll
extension=php_tidy.dll
extension=php_sqlsrv_56_nts.dll
extension=php_pdo_sqlsrv_56_nts.dll
extension=php_imagick.dll

**Comment by OptimusCrime** [comment]
Looks like the different drivers handles these kinds of things differently. It should be relatively easy to simply change this query. As far as I know substituting 1 with true is not valid SQL anyways.

**Comment by pixelchutes** [comment]
Great find! Curious if something similar is impacting your front end then, or does this fix resolve that as well?

**Comment by opengeek** [comment]
I thought this was fixed already? @Mark-H or @pixelchutes ?

**Comment by pixelchutes** [comment]
Yes, this is fixed. There is another SQL Server issue nested within a dupe here: https://github.com/modxcms/revolution/issues/13172#issuecomment-259686786
