### ISSUE TITLE
Feature Request: Quick Update “Code” Field

### ISSUE THREAD

**Issue by EkoOne** [modxcms/revolution#12843]
Include the option to use **Ace** or **CodeMirror** (assuming the user has already installed either) in the QU “Code” field.

**Comment by sottwell** [comment]
I believe there's an extra for that.

**Comment by sottwell** [comment]
TinyMCEWrapper can be set to work on QuickUpdate/QuickCreate forms, and I know I've seen a plugin for doing the same with elements.

**Comment by EkoOne** [comment]
Yes, TinyWrapper works with QU, but is best with rich-text fields, not things like Chunk and Snippets which it wraps in `<p>`. If I disable Tiny’s `<p>` setting then it messes with rich-text editing. I also use the TinyWrapper CodeMirror plugin which technically works but the above caveats still apply. Besides, some extras like StaticElement Accelerator don't currently support an editor. Maybe this just isn't a good idea. Thanks anyway. If there's another plugin does something similar I've never seen it.

**Comment by adamwintle** [comment]
+1 for this!

**Comment by donShakespeare** [comment]
TinymceWrapper is only for resources at the moment.
It will incredibly be easy to do something for CodeMirror. And since CodeMirror does not need to be installed at all, since every bit of it exists on a CDN, this will be quick work.

**Comment by donShakespeare** [comment]
As of TinymceWrapper 2.2.2+ this feature can now be turned on.

**Comment by OptimusCrime** [comment]
Closing this as "fixed by extra"?
