### ISSUE TITLE
Quick-edit settings lose focus, changes, with slightest scroll movement

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#12848]
When quick-editing settings as well as fields in other packages and the scroll action is bumped the field loses focus as well as all changes made to the field.  This may only be an issue because my mouse (Apple) has a touch sensitive surface that is easily bumped.

**Comment by Mark-H** [comment]
I'm not sure if I understand the problem? You have a sensitive mouse..?

**Comment by sottwell** [comment]
I've had the same "problem" forever. Scroll the least little bit after double-clicking to open the setting field for editing and the field closes. Using a MacBook Pro's touchpad, two fingers scrolling, so if I accidentally even touch the touchpad with two fingers it'll close the field. It's more of an annoyance than anything else.

**Comment by Mark-H** [comment]
Ah, that's what this is about. I honestly could not figure out what the problem was from the description. Yes, I've seen that annoyance too. 

I'm going to close this issue as I very much doubt there'll be a fix for this with ExtJS, but if anyone does find one, pull requests are much welcome.

**Comment by pixelchutes** [comment]
Ran into this for the first time today myself working on property sets. Don't recall it always being so sensitive, but I guess it really has.
