### ISSUE TITLE
[Meta] [Area: MODX.com] HTTPS for modx.com 

### ISSUE THREAD

**Issue by adamwintle** [modxcms/revolution#12858]
(This issue could be labeled as [Area: MODX.com](https://github.com/modxcms/revolution/labels/area-modx.com) by one of the MODX Integrators.)

### Summary
The modx.com marketing site should load over HTTPS. There's no reason why this should be an issue; if its funds related then a community fundraiser could be initiated. Usually SSL certs are around USD $90.

My main concern with this is the modx.com marketing website should show off all the benefits that MODX has to offer. MODX is SEO friendly out-of-the-box, has total creative freedom the front-end. Why not show that it has security features out-of-the-box too?

### Step to reproduce
Visit https://www.modx.com

**Comment by adamwintle** [comment]
Related to: https://github.com/modxcms/revolution/issues/12805

**Comment by pixelchutes** [comment]
Also related #11200 (feed fixed at the time, yet still breaks on smiley image)

**Comment by OptimusCrime** [comment]
Letsencrypt! Free SSL certs that are super easy to install. Unlimited sub domains etc. GOGO

**Comment by jaygilmore** [comment]
We're working on this again. The certs have been owned for some time. The marketing site is not yet uncoupled from all the .modx.com integrations and services. This is unfortunately not as simple as a normal website. It is a priority. Thanks for requesting it.

**Comment by jaygilmore** [comment]
modx.com is now available via https. We're working on several other things before we force https connections.

**Comment by adamwintle** [comment]
Awesome! Is it also possible to get [https://www.modx.com/](https://www.modx.com/) (the domain with the www.) as HTTPS too?

**Comment by pixelchutes** [comment]
Congrats! Thank you :smile:

**Comment by jaygilmore** [comment]
This is a work in progress. The likelihood is that www will redirect to . rather than resolve on both. We just need to update the nginx config. I am not sure when that will happen. www. hasn't worked for some time.

**Comment by Mark-H** [comment]
:tada:

**Comment by OptimusCrime** [comment]
Nice work guys!

**Comment by pixelchutes** [comment]
Looks like with `www` now also working on HTTPS, can this issue be closed?

**Comment by jaygilmore** [comment]
Hopefully all is working, so use. Close this puppy.
