### ISSUE TITLE
Starter Theme available on Setup

### ISSUE THREAD

**Issue by adamwintle** [modxcms/revolution#12859]
### Summary

While the community were developing the [New Base Template](https://github.com/modxcms/revolution/pull/12855#issuecomment-172258819) @Mark-H has brought up the idea of a Starter Theme:

> There is still a need for a full starter/sample site, which is well-built using a variety of extras, TVs, settings and what not. This is not that, nor does it aspire to be, and the delivery mechanism of that should indeed be kept separate from the MODX core repo. Probably as a transport package installed when the user ticks a checkbox in the set up. I'd be happy to dedicate some time to such an effort as well, but to me that's a completely different project and not affected by this PR.

The concept is nicely summarised by Mark in the above quote.  I like the idea that this is totally optional on first setup, and the files of the Starter Theme are not bundled with the MODX core but grabbed from the MODX Extras repository on install. 

I'd say the theme would need to:
- Emphasis the "creative freedom" aspects of MODX first and foremost
- Built with modern technologies (HMTL5, CSS3, mobile first, responsive, etc)
- Install a few of the best MODX Extras, but not too many
- Not show MODX to be only a blog (like WordPress default theme does); but perhaps show some simple examples of the power of MODX

A possible good candidate for a Starter Theme could be the [Flat So theme](https://github.com/modxcms/flatso) by @dubrod and @theboxer. This ticks many boxes already, with some tweaks to make the theme more general (e.g. removing @dubrod's photo) it could be a good Starter Theme, which can be improved and updated over time. 

This theme also uses [MTX the current official MODX Theme Framework system](https://github.com/modxcms/mxt), although this this Theme Framework system isn't perfect its still pretty good and its the best MODX has right now.  As the Theme Framework evolves so can the starter theme. 

If the Flat So theme isn't suitable, then I know @DESIGNfromWITHIN and @sottwell have both independently worked on Starter Themes of their own; perhaps one of these could be adapted into an official MODX Starter Theme.

This concept could lead to an entire package instillation step during the main Setup; where users can pre-install Extras and a Theme. But for now, to keep it simple, this would be a single checkbox on Setup to install one theme which the community has developed for this purpose.

**Comment by Mark-H** [comment]
Just to be fair this wasn't necessarily my idea, many other people in the community have in the past mentioned or even worked on such a starter site.

**Comment by OptimusCrime** [comment]
I guess some people could benefit from this, and that is great, but in most cases I guess things are so custom this will be skipped.

**Comment by OptimusCrime** [comment]
MODX now has a starter template that does some of the things mentioned in the original issue.

@modxbot close

#modxbughunt
