### ISSUE TITLE
modMenu installation fails because of schema relation

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#12867]
### Summary

CMP installation fails because `modMenu` has schema relation with `modAction` which inserts ID into database, not `index` as expected.
### Step to reproduce

[Add the Menu and Action](https://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/developing-an-extra-in-modx-revolution/developing-an-extra-in-modx-revolution,-part-iii#DevelopinganExtrainMODXRevolution%2CPartIII-TheBuildScript#DevelopinganExtrainMODXRevolution,PartIII-AddingtheMenuandAction)

for MODX 2.4.2 database, it should have been like this:

```
$action = $modx->newObject('modAction');
$action->fromArray(array(
    'id' => 1,
    'namespace' => 'doodles',
    'controller' => 'index',
    'haslayout' => true,
    'lang_topics' => 'doodles:default',
    'assets' => '',
        ), '', true, true);

$menu = $modx->newObject('modMenu');
$menu->fromArray(array(
    'text' => 'doodles',
    'parent' => 'components',
    'action' => 'index', ///////////// <== This is a string, not integer
    'description' => 'doodles_desc',
    'icon' => 'images/icons/plugin.gif',
    'menuindex' => 0,
    'params' => '',
    'handler' => '',
    'namespace' => 'doodles', ///////////// <== Adding this
        ), '', true, true);
$menu->addOne($action);

return $menu;
```
### Observed behavior

Problem occurs because [schema has relation](https://github.com/modxcms/revolution/blob/2.x/core/model/schema/modx.mysql.schema.xml#L731) between `action` field in **modMenu** and `id` field in **modAction**.

After installation, modMenu has ID of `modAction` inside its `action` field, while its namespace is no longer `core` which brings FATAL ERROR because of fallback behavior.
`
Fatal error: Class 'IndexManagerController' not found in D:\path\to\core\model\modx\modmanagerresponse.class.php on line 185
`
It's make sense because `$menu->addOne($action);` automatically generates relationship.
### Expected behavior

Well, as we speak about [building component for >2.3.x](https://rtfm.modx.com/revolution/2.x/case-studies-and-tutorials/developing-an-extra-in-modx-revolution/developing-an-extra-in-modx-revolution,-part-ii#DevelopinganExtrainMODXRevolution,PartII-ActionsandMenus), there must be a way to remove that schema relationship while preserving fallback behavior.
### Environment

MODX 2.4.2-traditional

**Comment by Mark-H** [comment]
It looks like you're combining the 2.3 and 2.2 styles. The expected behaviour would be to either provide a modAction object (2.2 style, action is an integer), or to provide an action string (2.3 style, no modAction object, just the string and namespace).

**Comment by goldsky** [comment]
Doc says so?
So, I sould just ignore modAction?

**Comment by fogshot** [comment]
@Mark-H could you expand on this? I think I'm facing a similar issue after following the doodles tutorial on the MODX docs. How exactly should I change the code below to make it work? Sadly, I can't find anything in the docs on how to do this correctly, 2.3-style.

My _build/data/transport.menu.php:
`<?php
$action= $modx->newObject('modAction');
$action->fromArray(array(
    'id' => 1,
    'namespace' => 'events',
    'parent' => 0,
    'controller' => 'index',
    'haslayout' => true,
    'lang_topics' => 'events:default',
    'assets' => '',
),'',true,true);

$menu= $modx->newObject('modMenu');
$menu->fromArray(array(
    'text' => 'events',
    'parent' => 'components',
    'description' => 'events.desc',
    'icon' => 'images/icons/plugin.gif',
    'menuindex' => 0,
    'params' => '',
    'handler' => '',
),'',true,true);
$menu->addOne($action);
unset($menus);

return $menu;
`

**Comment by Mark-H** [comment]
That code looks fine, that's the 2.2 way of doing it.

In 2.3+ there is an other way to do it, which is to NOT create the modAction object (the first block of code), instead setting `'action' => 'index'` and `'namespace' => 'mynamespace'` directly on the modMenu (second object) and removing the line `$menu->addOne($action)`.

The basics of how you set up 2.3-style menus can be found in https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/custom-manager-pages-in-2.3, though that's about doing it via the UI and not through the build script.

**Comment by Mark-H** [comment]
If there's any docs that need updating, let me know. For now this seems to be a case of getting two different ways of doing it mixed up.
