### ISSUE TITLE
Protected Weblink 404's when hidden from menu

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12871]
### Summary
A Weblink protected by a Resource Group (tied to a specific User Group) cannot be viewed when hidden from menu. A `404 error`is thrown.

### Step to reproduce
~~*NOTE: I am documenting my findings here so far, I will update as necessary as soon as I've identified the minimum requirements to reproduce.*~~

* `use_weblink_target` = **yes** in System Settings.
* Setup a Resource Group and parallel User Group
* Setup a non-admin User, and add to the new User Group (w/ Member Role)
* Create a new Weblink (e.g. id: 123) to a static file, like a .pdf in /assets/
  * Make sure it is Published (but hide from menus), and add it to the new Resource Group
* Create another Resource (e.g. id: 124), and place a link tag to the Weblink *(override global `use_weblink_target` here to enforce the protection on the URL to the static file)*: 
```html
<a href="[[~123? &use_weblink_target=`0`]]">Protected Weblink</a>
```
* On a fresh session, login as new non-admin User to `web` context
* Browse to new Resource (124) and click the generated link

### Observed behavior
A `404 error` is thrown.

**However**, if you update the protected Weblink to NOT be hidden from menus, it works as expected!

### Expected behavior
Weblink should direct user to the static file under *both* conditions.

### Environment
MODX 2.4.1, NGiNX 1.8.1, MySQL 5.6, Chrome 49.

**Comment by pixelchutes** [comment]
@opengeek were you able to reproduce this? I'm assuming so based on the recent labels, but hoping to confirm.

**Comment by opengeek** [comment]
it's still on my list of things to work on unfortunately — will see if I can get to it tonight or early in the morning

**Comment by opengeek** [comment]
@pixelchutes — I have gone through these steps and not been able to reproduce this behavior so far.

**Comment by pixelchutes** [comment]
@opengeek 

Aha! Sometimes forget to increase the verbosity of the MODX error log when looking into issues like this. Here's what I found when attempting to access for MODX User ID 123:

> Principal 123 does not have permission to load object of class `modWebLink` with primary key: 456

Is `modWebLink` not covered by the **Resource** Access Policy?

**Comment by opengeek** [comment]
It's definitely covered. Not sure why this user doesn't have permission unless there is a problem with the assigned policy?

**Comment by pixelchutes** [comment]
@opengeek  -- Here's what I'm seeing, nothing is jumping out at me:

```sql
SELECT 
    Acl.target,
    Acl.principal,
    Acl.authority,
    Acl.policy,
    Policy.data
FROM
    `modx_revo_entrepreneur`.`modx_access_resource_groups` Acl
        LEFT JOIN
    `modx_revo_entrepreneur`.`modx_access_policies` Policy ON Policy.id = Acl.policy
        JOIN
    `modx_revo_entrepreneur`.`modx_document_groups` ResourceGroup ON Acl.principal_class = 'modUserGroup'
        AND (Acl.context_key = 'web'
        OR Acl.context_key IS NULL
        OR Acl.context_key = '')
        AND ResourceGroup.document = 456
        AND ResourceGroup.document_group = Acl.target
GROUP BY Acl.target , Acl.principal , Acl.authority , Acl.policy;
```

Shows two records:

```json
{"load":true}
```
and
```json
{"add_children":true,"create":true,"copy":true,"delete":true,"list":true,"load":true,"move":true,"publish":true,"remove":true,"save":true,"steal_lock":true,"undelete":true,"unpublish":true,"view":true}
```

**Comment by sottwell** [comment]
Are you sure that policy is being applied to the mgr context and not the web context?

**Comment by pixelchutes** [comment]
`web` is the target context, user has not access to `mgr`

**Comment by opengeek** [comment]
This is making no difference in my test here — I didn't add the anonymous Load only policy however, so I get a 404 with an anonymous user, but not with the user that is a member of the Resource Group. Let me try adding back the anonymous Load Only policy for the Resource Group.

**Comment by pixelchutes** [comment]
Does your front-end User need to log out and back in (e.g. refresh session after changes like that?)

**Comment by opengeek** [comment]
Absolutely. Or you need to flush permissions at least.

**Comment by opengeek** [comment]
If the change affects a Resource, as it does in this case, the cache will also need to be refreshed.

**Comment by pixelchutes** [comment]
Also, not sure if it matters, but Weblink in question is set to (empty) Template, and PDF content type. Uncacheable.
