### ISSUE TITLE
MODX manager RSS feed breaks https browser security

### ISSUE THREAD

**Issue by JimKillock** [modxcms/revolution#12880]
The front page ot MODX manager contains “MODX News Feed" which in turn contains 

http://forums.modx.com/thread/98074/revolution-2-4-package-dependencies-more#dis-post-530329

which contains http://modx.com/assets/components/discuss/themes/modx/images/smileys/laugh.gif

Which because we use https-only causes media security warnings on our site.

**Comment by pixelchutes** [comment]
Closing as duplicate #12858 #12805

**Comment by pixelchutes** [comment]
It appears the offending post has been updated now that HTTPS support has been rolled out. You may need to clear cache to ensure the up-to-date news feed is being rendered, but everything checks out OK on my end.
