### ISSUE TITLE
Make package installation "fill or kill"

### ISSUE THREAD

**Issue by wuuti** [modxcms/revolution#12881]
### Summary

The package installation produces sometimes wrongly installed packages/versions - if something goes wrong during install, it may be shown on the console (unobserved because a lot of messages are always there) or not. But anyway it runs through, you can click the "OK" button (even if nothing was ok) and the packages overview page suggests you a successful installed new package/version. If you once click OK then, all log messages are irreversible gone. 
### Step to reproduce

E.g. restrict write access for PHP script to the connectors folder (as seen in some installations). If a package install tries to install its own connector to that location, you will end up with a broken package install, because these files won't be written to the location the package itself expects. 
This is just a general example, there are a lot of things that can go wrong during package installations and they highly depend on the system setup and security options you implemented. 
Also possible: namespace overuse, where a package uses a namespace used by another package or (more likely) uses a namespace which leads to a core/components/ path (#12879) already used by a custom, manually set up component. 
### Observed behavior

Installed packages may not be installed correctly, but failures may not show up directly, maybe only after a certain time of use or if you use a special package feature.
### Expected behavior

If possible, the package installer should _not_ install a package if a problem is detected. E.g. we could implement a dry-run before, where file operations are checked, and if there is any problem with any file in the package, installation should be rejected. Also _any_ (not dependant to the system log level) log message during a package installation should be _copied_ into a separate logfile (like "install_getresources-1.5.0-pl.log) to allow an error search afterwards.

**Comment by Mark-H** [comment]
> If possible, the package installer should not install a package if a problem is detected. 

That's an option you can specify in your package per vehicle. In the modmore premium extras, we have that set to prevent installation if the license doesn't check out. 

```` php
$attributes= array(
    xPDOTransport::ABORT_INSTALL_ON_VEHICLE_FAIL => true,
````

**Comment by inreti** [comment]
Ah cool. Did not know that. But which cases lead to a vehicle fail? And what if the package maintainer does not set this attribute? And why don't we assume these attribute as always set?

**Comment by Mark-H** [comment]
It depends on the type of vehicle.. typically there's a return true or false somewhere ;) 

And not all fails are bad. Just think of errors adding fields to a database table because they already exist, you don't want that to prevent the package from installing as that's not really an error.

**Comment by inreti** [comment]
No I don't. But that's the point with the errors in the console during installation: you can't distinguish (and a normal user more than ever) between _good_ and _bad_ error messages.

**Comment by alroniks** [comment]
In addition to ABORT_INSTALL_ON_VEHICLE_FAIL it also possible to use package validators for checking is package installable. There is can be a lot of things that package can require (php version, modx version, installed extensions, installed extras etc.) about that MODX will not know.
So implementing it in MODX looks too complicated. I am closing it, but feel free to reopen.

**Comment by Jako** [comment]
If I am right, the console window will be recreated with version 2.7 everytime. So the issue will be invalid then.
