### ISSUE TITLE
RFC: Adding optional "X-Powered-By: MODX Revolution" header to MODX sites?

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#12882]
Following this conversation on twitter (https://twitter.com/brandonkelly/status/691953553494028288):

<img width="338" alt="screen shot 2016-01-26 at 19 25 34" src="https://cloud.githubusercontent.com/assets/312944/12590312/9a7128f4-c462-11e5-89ec-ae3358937759.png">

I'm wondering if perhaps there would be consensus to add an X-Powered-By header to MODX installs. The primary benefit would be a better way to get MODX represented properly in website analysers like W3Techs and BuiltWith.com. The primary disadvantage would be that a site can be identified as built with MODX; if a critical vulnerability is found that could lead to highly targeted attacks*, even if it doesn't include the specific release. 

What I'd like to propose is adding the X-Powered-By header with value "MODX Revolution" or slightly more specifically "MODX Revolution 2.x". I'm not sure if it should be opt-in or opt-out; with opt-out we might get faster adoption of the header and better adoption from w3techs/builtwith, but it might be perceived as pushing it onto people. Opt-in with a checkbox during setup might be better. 

Historically, MODX has always been very clear about not messing with what the site builder puts in. As this is only a header and not anything added to the output, I don't think that has to be a problem. 

Implementation of such a header is pretty simple (here's how it can be done as a plugin: https://gist.github.com/Mark-H/bda283b073b6145cfde1). 

* Fun side note: when I added the X-Powered-By header to some of my own sites, that actually overwrote an existing X-Powered-By header that showed the specific PHP version used. In a way, this makes it more secure, but that is obviously debate-able :P

**Comment by Mark-H** [comment]
Craft has the X-Powered-By header enabled by default, so opt-out (https://craftcms.com/docs/config-settings#sendPoweredByHeader)

**Comment by isaacniebeling** [comment]
I would definitely want that to be opt-in. I don't like advertising what I'm using as much as possible, and MODX is the most easily-camouflaged system I've used to date.

**Comment by Omeryl** [comment]
I find one of the biggest things MODX CMS does right is no branding. Once you change manager location and the first resource, you're unlikely to ever be found out. That's a huge security plus, not a negative.

**Comment by bezumkin** [comment]
+1 for X-Powered-By, enabled by default. But with system option for disable.

Lack of header do not makes your site more secure. MODX can be easy revealed with one HTTP request to /manager/ with default setup. 

If you are wondering about security, it is better to change names of directories and close manager with HTTP Base Auth.

**Comment by Mark-H** [comment]
I keep going back and forth on if it should be opt in myself.. Opt in to not expose anything by default, but opt out so that it doesn't require effort to set up.

Maybe a checkbox in the setup that is ticked by default? Camouflages in an instant, still enabled for people that don't care.

**Comment by isaacniebeling** [comment]
@bezumkin Of course you have to do other things to make it more secure, but why add to that burden? What benefit does the header offer?

@Mark-H What would happen with existing sites? I'd be more ok with it being opt-out as long as it's automatically off (opt-in) for previous installs. I shouldn't have to remember to go make that change when I update a site that's been around (and potentially secured) for a while already.

**Comment by bezumkin** [comment]
@isaacniebeling I think that we must tell everyone about MODX.

Security through obscurity is not the solution.

**Comment by OptimusCrime** [comment]
People are still using WP, which is the most identifiable piece of software out there. One glance at the source code and you will most likely spot multiple obvious hints.

I see no problem adding this header as opt-in, or even opt-out, but I know some people hate that.

Adding this header could make it possible to scrap the webpages and identify MODX usage (just like craftcms is doing).

**Comment by Mark-H** [comment]
> What would happen with existing sites? I'd be more ok with it being opt-out as long as it's automatically off (opt-in) for previous installs. I shouldn't have to remember to go make that change when I update a site that's been around (and potentially secured) for a while already

On upgrade you'd see the checkbox to enable the header, which would be ticked if the associated setting is enabled as well. First upgrade would follow opt in or out as decided. Next upgrades follow the setting.

**Comment by isaacniebeling** [comment]
I'd say first upgrade should be opt-in -- it's changing a default behavior. After that it should follow the setting. I'd be ok with an opt-out on new installations if the first upgrade is opt-in.

**Comment by jaygilmore** [comment]
For new installs, I would personally be okay with new behavior with an obvious system setting to disable. 
For upgrades, I think and opt out or opt-in would be fine so long as it was part of the prompts either on the last page or via cli prompt.

**Comment by inreti** [comment]
I was always a fighter for not allowing fingerprinting for MODx as much as we can. But in fact, to detect that (any) MODx version is running, is quite easy for everyone who knows the system a bit - no matter if you hide the manager and core (hint: assets folder). Getting the version is quite harder, yet to avoid that more important for security. 
So I would say, @Mark-H's suggestion with the opt-in/opt-out on setup/upgrade would be a nice way. If the header (without version information) improves MODx awareness without making it less secure or an attack target, I am fine with that.

**Comment by christianseel** [comment]
This must be an opt-in! I use MODX because I can completely hide MODX from the visitor or hacker… I'd say it's a no-go if we start sending a (hidden) http header.

It might be an opt-out for the next major release with MODX 3.0, where you expect major changes to system…

**Comment by Mark-H** [comment]
Given that people are mostly positive about the idea, as long as there is control over it, I've drafted a pull request: https://github.com/modxcms/revolution/pull/12885.

On new installs, it will have a checkbox ticked by default that will enable the associated setting. On upgrades, there is no checkbox, and it will simply keep the value as is (which means disabled if it wasn't changed by the user).

**Comment by Mark-H** [comment]
This was merged and released with 2.5, so closing. Thanks for the discussion folks :)

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx-header-response/4772/3
