### ISSUE TITLE
hidemenu custom label in Manager Form Customization does not work

### ISSUE THREAD

**Issue by madze** [modxcms/revolution#12890]
### Summary
Custom Labels for the 'hidemenu' item in Manager Form Customization do not change the label.

### Step to reproduce
Add a custom label for the 'hidemenu' item and then view that input in the manager while logged into the corresponding user group.

### Observed behavior
The label still reads: "Hide From Menus" instead of the custom label.

### Expected behavior
Should be replaced with the custom label.

### Environment
REVO  2.4.0-pl

**Comment by Mark-H** [comment]
Fixed per #13025 in 2.5.1.
