### ISSUE TITLE
Changing the key of a context is not possible in the MODX Manager

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#12891]
### Summary

The context key can't be changed in the general information of a context.
### Step to reproduce

Edit the context. The key is readonly.
### Observed behavior

The key is not editable.
### Expected behavior

The key should be editable (and changeable, if it is not 'mgr' or 'web'). Resources and context settings using that key have to be modified by a processor after.
### Environment

MODX 2.5-dev

**Comment by christianseel** [comment]
The context_key would also need to be updated in ACLs, mediasources and potentially more (besides resources and context settings).

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @christianseel

**Comment by OptimusCrime** [comment]
A huge downside here is that the primary key for the context is the context key itself, not an interger value. This makes renaming the context a pain in the ass, as it affects MANY tables, attributes, cache and scripts.

**Comment by Jako** [comment]
Regarding the work that has to be done to solve this issue, I'll better close it.
