### ISSUE TITLE
MODX2.5RC1: Unknown method get_template_vars

### ISSUE THREAD

**Issue by pixelfanatiker** [modxcms/revolution#12895]
**Description**
After updating MODX from 2.4.2 to 2.5 RC1, login to the manager is not possible. I get an 500 error.

**Expected behaviour**
- Manager login page is visible and login is possible

**Steps to reproduce**
- Quickstartbuttons have to installed
- Update to MODX 2.5 RC1
- Access the manager login page

**Server log**
`PHP Fatal error:  Uncaught  --> Smarty: Call of unknown method 'get_template_vars'. <-- \n  thrown in /var/www/vhosts/xxx/web/core/model/smarty/sysplugins/smarty_internal_templatebase.php on line 554`

**Short analysis**
Some dashboard widgets (SimpleCart, QuickstartButtons) accessing the method addLangTopic.
This method seems to be removed.

There should be an logic to prevent  the exeption so that accessing to the manager login page is always possible.

**Comment by Mark-H** [comment]
This pull request should sort that out: https://github.com/modxcms/revolution/pull/12897
