### ISSUE TITLE
MODX 2.4.3 changes expected filter behavior

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#12901]
The example below worked for all previous versions of MODX Revo for the last few years by inserting the 3.3.5 version as the default.

```html
<link rel="stylesheet" href="[[+TWITTERBOOTSTRAPURL]][[+bootstrapVersion:default=`3.3.5`]]/css/bootstrap.min.css">
```

With 2.4.3 this functionality no longer works when a template calls a chunk (HEADER) which in turn calls other chucks (SEO)(BOOTSTRAP)(FONTAWESOME) with the default predetermined in the chunks.

I have already added a note on my Packages telling people to direct call versions from the parent chunk.

Was this change intended?

**Comment by pixelchutes** [comment]
@wshawn curious if it could be related to 7158bd929fec20f9ba2f6fe744896ddfe08d714e

While not recommended, what happens if you set `parser_recurse_uncacheable = 0` and clear your cache?

**Comment by pixelchutes** [comment]
Please continue any discussion on #12906, which includes a pending fix.
