### ISSUE TITLE
Function/feature terminology mismatch on Plugins

### ISSUE THREAD

**Issue by nitrojane** [modxcms/revolution#12900]
Plugins - using the shortcut menu (right-click) the user has the option of Activating or Deactivating the plugin whereas on the Create/edit plugin page the user has the option to check Plugin Disabled or not. Need to standardize terminology if they're the same function.

**Comment by whitebyte** [comment]
Duplicate of  #9523

**Comment by nitrojane** [comment]
I wasn't reading for comprehension obviously - didn't see the other issues that are related. Should I close this?
