### ISSUE TITLE
No table for users within DB

### ISSUE THREAD

**Issue by anahitghazaryan** [modxcms/revolution#12909]
I just realised that no users existing for accessing the Admin Panel,

Checked DB and did not found even the table for users

What was going on?

**Comment by Mark-H** [comment]
That sounds like a broken site alright. Were you just installing MODX, doing an upgrade or did an existing site just magically break? At any rate, inspecting the error log of both MODX (core/cache/logs) and your server/php would be a good next step.

**Comment by OptimusCrime** [comment]
Closing due to lack of feedback. This issue is next to impossible to debug/reproduce as it is right now.

Feel free to comment/reopen if you have further information.

@modxbot close
