### ISSUE TITLE
Unfortunate error in warning about core-dir

### ISSUE THREAD

**Issue by Flygenring** [modxcms/revolution#12904]
On a completely fresh install of `MODX Revolution 2.5.0-rc1` I got the `Core folder is accessible by web` as expected, but clicking the link to the changelog I actually got a `404`.
This might mislead people who don't know MODX or programming to think the message is an error and their site is safe!

I found out it's because the link took me to `/docs/changelog.txt` and not `/core/docs/changelog.txt` as it should.
The reason behind it is that the core path is never used when building the URL in [config_check.inc.php, line 251](https://github.com/modxcms/revolution/blob/v2.5.0-rc1/core/model/modx/processors/system/config_check.inc.php#L251)

I know that it's noted in the comment just above, but I figured it might be worth noting so it could be fixed before the 2.5 stable release.

**Comment by pixelchutes** [comment]
Interesting... I just tested on a local install, and the changelog link worked as expected: `/core/docs/changelog.txt` **HTTP/1.1 200 OK**

**Comment by pixelchutes** [comment]
Looks like `2.5.0-rc1` was built 2/4, but the fix for this issue wasn't merged until 2/11.

**Comment by OptimusCrime** [comment]
Indeed, this was fixed later

**Comment by Flygenring** [comment]
Sounds great, I just wanted to make sure it didn't go unnoticed :)
