### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by anahitdev** [modxcms/revolution#12908]
I am using MODX and my website is broken, no styles and code didin't work. 

In configcore.php i have the following

<?php
define('MODX_CORE_PATH', '/home/holidayls/public_html/core/');
define('MODX_CONFIG_KEY', 'config');
?>

Am i doing anything wrong?

**Comment by Mark-H** [comment]
I'm going to close this issue. That config.core.php file looks fine and this does not contain nearly enough information to warrant a bug report. Perhaps the forums are a better place for you to figure out what happened @anahitdev.
