### ISSUE TITLE
New startup theme charset meta tag

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12915]
### Summary
The new default template's charset meta tag has a hard-coded value.
### Step to reproduce
Edit the new default template and look at the charset meta tag.

### Observed behavior
The value is hard-coded to be utf-8. (whether or not this tag should be explicitly self-closed is a matter of personal preference in HTML 5).
```
<meta charset="utf-8" />
```

### Expected behavior
It should be using a system setting. While it probably won't cause a problem, MODX uses the system setting 'modx_charset' when setting the HTML headers for the page. If the headers don't match the meta tag in the HTML head, at the least the W3C validator will complain.
```
<meta charset="[[++modx_charset]]" />
```

### Environment
MODX Revo 2.5.0

**Comment by sottwell** [comment]
Hah! Beat me to it, I had just upgraded my OS and was working on getting my dev environment re-established so I could clone and do a pull request. No hurry about that now!

**Comment by zaigham** [comment]
:smiley:
