### ISSUE TITLE
mail_smtp_user & emailsender settings editing is broken

### ISSUE THREAD

**Issue by kasthack** [modxcms/revolution#12919]
### Summary
mail_smtp_user and emailsender are not checked to be valid email addresses and leading/trailing spaces are not trimmed.

### Step to reproduce
1. Go to system settings page.
2. Set emailsender and/or mail_smtp_user to ' \<valid_email_login\>'.
3. Logout and try to recover password with email.

### Observed behavior
1. Value is saved and used as-is without validation and trimming.
2. Error message about bad smtp login/pass.

### Expected behavior
1. emailsender/mail_smtp_user should be trimmed and/or checked to be valid email addresses.

### Environment
Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.5.9-1ubuntu4.14
MODX: 2.43-pl

**Comment by pixelchutes** [comment]
Somewhat related to #12000

**Comment by kasthack** [comment]
Duplicate: #12000

**Comment by Mark-H** [comment]
`mail_smtp_user` is not always an email address, it can also be a username for services like Mandrill.

**Comment by jaygilmore** [comment]
As @Mark-H pointed out, `mail_smtp_user` is any smtp username and not just an email address. Mandrill does use email addresses, however, SendGrid does not. See: 
![configure_modx_to_use_an_email_service_provider_ _modx_cloud_support](https://cloud.githubusercontent.com/assets/378199/13447705/ee327ef0-dff3-11e5-9cb1-3141adcd0fc5.png)

**Comment by OptimusCrime** [comment]
Based on feedback here, there is no "correct" way to validate this system setting as both regular strings and emails should be allowed.

Sorry @kasthack, but I am afraid you must validate/make sure your settings are correct using an other approach. Feel free to reopen or comment if you disagree with this closing.

@modxbot close
