### ISSUE TITLE
Duplicate button is missing when editing Weblinks

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#12910]
### Summary
When editing a Weblink Resource  (`modWeblink`), the <kbd>Duplicate</kbd> button is missing.

### Step to reproduce
1. Login to MODX Manager _(Administrator role is fine)_
2. Edit an existing Weblink Resource.
3. Look at the top row of buttons.

### Observed behavior
<kbd>Duplicate</kbd> button is missing.

### Expected behavior
<kbd>Duplicate</kbd> button should be present given proper permissions.

To compare, edit a normal Resource (`modResource`) and you'll see <kbd>Duplicate</kbd> next to <kbd>Save</kbd> button.

### Environment
MODX 2.4.3

**Comment by Mark-H** [comment]
Fixed per #13029
