### ISSUE TITLE
MODx.loadHelpPane modal-window has extra scrollbar in Chrome/Opera

### ISSUE THREAD

**Issue by sebastian-marinescu** [modxcms/revolution#12914]
### Summary

When loading the MODx.loadHelpPane, the window has a vertical scrollbar, which isn't needed. Seems to only happen in Chrome and Opera, so on the gWebkits. 
### Step to reproduce

Click on the Help! button inside a resource.
### Observed behavior

Scrollbar. Some window-body container has 5px too much in the height or something.
### Expected behavior

Clean modal. No Scrollbar. Only for the inner iFrame if needed.
### Environment

MODx 2.4.2pl

**Comment by OptimusCrime** [comment]
Confirmed

**Comment by sebastian-marinescu** [comment]
Thanks @OptimusCrime for confirming. I just stumbled upon it yesterday again. 
I think I'll prepare a PR, when I find the appropriate styles.

**Comment by OptimusCrime** [comment]
No problem, just stumbled upon it yesterday myself. Weird how there is ALWAYS a scrollbar that moves the iframe just a couple of pixels. Not sure just what is off.

**Comment by Oetzie** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by Mark-H** [comment]
Fixed for 2.5.6

**Comment by OptimusCrime** [comment]
@Mark-H Really? Via my PR? Because it is still open as far as I can see?

**Comment by OptimusCrime** [comment]
Edit: Derp. I see the other PR now. It was not referenced.
