### ISSUE TITLE
Change Lexicon entry 'Deleted' for Resources to 'Move to Trash'

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12928]
When you click on the Delete button or select it on the Resource Tree context menu, you're not really deleting the resource in any conventional sense of the word.

'Mark for Removal' or  (probably better) 'Move to Trash' would be much clearer. 

This would involve changing these two lexicon entries:

core:default -- delete
core:resource -- resource_delete

I've tried the change and it doesn't seem to cause any rendering problems.

A change would also probably be required in some languages other than English, depending on how 'delete' is currently translated.

**Comment by mrcycling** [comment]
:+1:

**Comment by Jako** [comment]
+1 for `In Trash` (or `trashed`) and `Move to Trash`

**Comment by inreti** [comment]
+1 for "Move to trash" - if we also implement a trash. Currently we don't have a trash as users are familiar with from their computers over years. You cannot go into the trash, see what's in there or pick out one resource to finally delete it. And "move" is the wrong word then, if we keep the current behaviour of shown the resources in the tree at the same place, but with red, strikestrough style. 

+1 for "Mark for removal": as long as we don't have a trash CMP, this is exactly what it is. Nothing less and nothing more. Even better: "Mark for deletion". Delete is the correct word imho. And the fact that "removal" is used elsewhere (in places normal users shouldn't know of like snippets!) only shows that the wording at those places might have to be changed as well :-)

**Comment by Mark-H** [comment]
Pull requests to change the lexicon entries are welcome, it really seems like way overkill to keep an issue for typos/preferences like this. For non-english changes, use http://translate.modx.com/.

**Comment by BobRay** [comment]
I think this has been fixed, at least for English. "Mark for Deletion" is used (unless I made that change myself in Lexicon Management).
