### ISSUE TITLE
Package Manager no longer allows you to browse subcategories in 2.4.3

### ISSUE THREAD

**Issue by rthrash** [modxcms/revolution#12920]
### Summary
In earlier versions of MODX, you could click on "Extras" for example and it would show a list of sub-categories. In 2.4.3 (possibly earlier), the categories are no longer clickable. They only show the top-level options. (Hat tip to Evgeny Zhulin reporting the isssue in MODX Cloud.)

### Step to reproduce
1. Extras > Installer > Download Packages 
2. Click "Extras" in the left column.

<img width="537" alt="package_management___motorsports_marketing_resources" src="https://cloud.githubusercontent.com/assets/234237/13269323/c53f7450-da4c-11e5-8f24-d269577c760c.png">

### Observed behavior
No list of categories to browse. When clicking each master category, I do not get a post to packages-rest.php as in earlier versions:

<img width="1240" alt="package_management___motorsports_marketing_resources" src="https://cloud.githubusercontent.com/assets/234237/13269477/7496cc14-da4d-11e5-9dd8-bcddb3ca55be.png">

### Expected behavior
List of categories, e.g., like in 2.2.x and presumably 2.3.x (did not test in 2.3.x or earlier than 2.4.3).

<img width="576" alt="package_management___ryan_thrash__blog_" src="https://cloud.githubusercontent.com/assets/234237/13269358/fc7c77ec-da4c-11e5-8547-b4ab9f4fe01c.png">

<img width="1233" alt="package_management___ryan_thrash__blog_" src="https://cloud.githubusercontent.com/assets/234237/13269488/84bf5ac0-da4d-11e5-98a4-70cd127131ac.png">

### Environment
Tested in MODX Cloud (nginx/PHP5.6).

**Comment by sebastian-marinescu** [comment]
I can confirm this is also not working in 2.4.2. 
But it works in 2.2.0-pl2 and even 2.0.8-pl.

**Comment by inreti** [comment]
Despite - is anyone using that? It took so long until someone realized it is not working any more... Maybe a good idea to rebuild that part together with the extras section on the webpage instead trying to fix that? Just a quick guess...

**Comment by OptimusCrime** [comment]
Never knew this was possible.

**Comment by sebastian-marinescu** [comment]
When I started developing in/for MODX I didn't know all the Extras names and I didn't know what to search for, so I used that sub-categories to explore the packages. So imho I would keep it, as long as it doesn't hurt (or _does_ it hurt someone?) - new users could only benefit from it...

Even the introductory text on the Packages-Browser [states that you should choose one of these categories to begin browsing](https://github.com/modxcms/revolution/blob/d63cc1735422a9c5c51b18a9f21d26bd1f6c390b/core/lexicon/en/workspace.inc.php#L176) (and remember, when we all first started, we surely did read these kind of helper-messages, and I'm 100% certain newcomers will too).

Also right now clicking on the three categories **doesn't do anything**, it just leaves you wondering what happened. And where everything went. _You are lost_ (as a beginner). To see anything again you need to either type in a search, or go _back_ to the Packages-Workspace and click again on the button to see the start-page (Top 10 Packages / Latest Packages) of the Packages-Browser. In fact there is a (hacky) way to come back to the the start-page of the repository without leaving the page or reloading: search for anything (or nothing) and then you can click on the breadcrumb-icon "Package-Browser".

![image](https://cloud.githubusercontent.com/assets/3798871/13322026/be790c3a-dbd2-11e5-8b2e-de7da588cac7.png)

So I would not only vote for bringing it back, but actually also vote to either

- add a new automatic top-level entry for every package-provider, e.g. "Overview", "Start" or "Top 10"
- or make the "Package-Browser"-Breadcrumb (are all breadcrumbs - doesn't hurt) always clickable, even if no sub-category is selected

This way the navigation-concept in the Package-Browser would be more consistent.

**Comment by rthrash** [comment]
Great suggestions @sebastian-marinescu :+1:

**Comment by sebastian-marinescu** [comment]
Thanks @rthrash 

And I also came to the conclusion that 
- add a new automatic top-level entry for every package-provider, e.g. "Overview", "Start" or "Top 10"

would be the better and more consistent option.
What do you think @theboxer ?
