### ISSUE TITLE
Uncaught Error: Call to undefined function xml_parser_create()

### ISSUE THREAD

**Issue by neilyamit** [modxcms/revolution#12927]
I'm a frontend guy and knows little about backend stuff. Here are the things I found after some quick digging. These are non-critical websites, hence a more 'experimental' setup.

### Summary
Manager showing blank white screen when logging in.  Notice this problem on two websites I manage running on different servers.

Log returns the following error:

```
2016/02/28 21:53:07 [error] 2503#0: *5987 FastCGI sent in stderr: "PHP message: Failed to load PHP's XML Extension. http://www.php.net/manual/en/ref.xml.php
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /var/www/example.com/html/core/model/modx/xmlrss/magpierss.class.php:514
Stack trace:
#0 /var/www/example.com/html/core/model/modx/xmlrss/magpierss.class.php(454): MagpieRSS->php4_create_parser('<?xml version="...', 'UTF-8', true)
#1 /var/www/example.com/html/core/model/modx/xmlrss/magpierss.class.php(103): MagpieRSS->create_parser('<?xml version="...', 'UTF-8', NULL, true)
#2 /var/www/example.com/html/core/model/modx/xmlrss/rssfetch.class.php(292): MagpieRSS->__construct('<?xml version="...', 'UTF-8', NULL, true)
#3 /var/www/example.com/html/core/model/modx/xmlrss/rssfetch.class.php(175): _response_to_rss(Object(Snoopy))
#4 /var/www/example.com/html/core/model/modx/xmlrss/modrssparser.class.php(40): fetch_rss('http://forums.m...')
#5 /var/www/example.com/html/manager/controllers/default/dashboard/widget.modx-security.php(28): modRSSParser->parse('http://forums.m...')" while reading response header from upstream, client: 110.55.115.45, server: www.example.com, request: "GET /manager/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "www.example.com", referrer: "http://www.example.com/manager/"

```

### Step to reproduce
Simply logging into the manager gives a blank screen. 

### Observed behavior
When not logged in, the /manager/ loads with the login form. Once the you input the correct login credentials, you're greeted with a blank screen.

### Environment
Modx 2.5.0
PHP 7.0.3-10+deb.sury.org~trusty+1 (cli) ( NTS )
Nginx/1.8.1
Ubuntu 14.04
mysql  Ver 14.14 Distrib 5.5.47

**Comment by OptimusCrime** [comment]
According to the [server requirements](https://rtfm.modx.com/revolution/2.x/getting-started/server-requirements), MODX Revo requires the SimpleXML extension. You either have to install or activate this on your server.

**Comment by neilyamit** [comment]
@OptimusCrime You're right. Found out that updating to 7.0.3 somehow removed SimpleXML from the php modules. I had to run:
`sudo apt-get install php7.0-xml`
/manage/r is back. Thanks.
