### ISSUE TITLE
Input Type TAG (tag.class.php) error when trying to save the resource.

### ISSUE THREAD

**Issue by designbywilliam** [modxcms/revolution#12933]
### Summary

When using the TAG input type as a template variable. I do get the different options listed in the resource under template variables. But it never saves the value.

*_I get this error: *_
`[2016-03-08 18:27:43] (ERROR @ /var/www/domain.com/public/core/model/modx/processors/element/tv/renders/mgr/input/tag.class.php : 31) PHP warning: htmlspecialchars() expects parameter 1 to be string, array given`

The line in tag.class.php
`'value' => htmlspecialchars($itemValue,ENT_COMPAT,'UTF-8'),`
### Step to reproduce

Create a template variable. Select TAG as input type. Create input option values:
`White==#fff||Black==#000` assign it to a template and go to a resource using the TV, Try select a value and then save the resource. Reload the page.
### Observed behavior

Value is not stored in database.
### Expected behavior

Selected values should be stored to database.
### Environment

MODX 2.4.3, MYSQL, APACHE

**Comment by sdrenth** [comment]
I'm going to try and fix this today.

**Comment by sdrenth** [comment]
I cannot reproduce this issue, I think this issue has already been resolved.

I tested this issue with a clean install of MODX Revolution 2.5.5-pl.

**Comment by OptimusCrime** [comment]
I can verify that this is no longer an issue. 

@modxbot close
