### ISSUE TITLE
System setting 'cache_disabled' appears to be not working correctly.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#12938]
### Summary

Working with static elements, I enabled the system setting 'cache_disabled'. Changes do not appear until I clear the cache. So, it appears caching is still happening even though this system setting is supposed to turn everything off.
### Step to reproduce
- Enable the cache_disabled system setting. 
- Edit a static template in your IDE of choice.
- Refresh the page in your browser. Note how your edit is not there.
- Refresh the MODX cache.
- Refresh the page in your browser. See that your edit has now appeared.
### Observed behavior

Editing a static element produces no result on the front end unless the MODX cache is refreshed.
### Expected behavior

The cache should not need to be refreshed as caching should be disabled.
### Environment

MODX 2.5.0-rc1

**Comment by jcdm** [comment]
+1 in MODX 2.5.1-rc1

**Comment by wuuti** [comment]
Reviewing this issue #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @wuuti

**Comment by wuuti** [comment]
Digging into it: even if cache_disabled is active, MODX generates the cache files. IMHO that is wrong in the first place, and not necessary: if we disable the cache we can spare the generation of any cache file...

**Comment by wuuti** [comment]
I cannot find _any_ use of __cache_disabled__ in core/model or core/xpdo. I found a changelog entry from version 2.0.0-beta-1 saying that this feature is no longer used but will again be usable in the future??? Can it be that this never was worked in again and we have taken over legacy configs over years?

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @wuuti

**Comment by OptimusCrime** [comment]
Paging @opengeek

**Comment by AntonFix** [comment]
Same problem. I use Webstorm and Deployment via ftp.

**Comment by alroniks** [comment]
PR is merged, closing the issue.
