### ISSUE TITLE
Official Docker image

### ISSUE THREAD

**Issue by vh** [modxcms/revolution#12947]
There are official images for [Wordpress](https://hub.docker.com/_/wordpress/) and [Joomla](https://hub.docker.com/_/joomla/), but lacks MODX.

I've created https://github.com/vh/docker-modx, but some [issues](https://github.com/vh/docker-modx/issues) need to be resolved.
Especially:
- https://github.com/vh/docker-modx/issues/4
- https://github.com/vh/docker-modx/issues/5

What do you think about this?

**Comment by jaygilmore** [comment]
Hi @vh I am not sure that this belongs in the bug tracker unless there are specific issues with MODX preventing packaging. You may wish to discuss a Docker Image of MODX with members of the community at the MODX Community Slack at modx.org or at the MODX Forums at https://forums.modx.com

**Comment by rthrash** [comment]
Awesome initiative @vh. Glad to see 2.5 resolved one of the issues inked above.

**Comment by vh** [comment]
@rthrash thanks! At this moment image is ready to be used (with MariaDb). Just need to push it to Docker Hub. Also can we resolve this issue https://github.com/vh/docker-modx/issues/2 (move this repo to MODX github organization) before talk with Docker team?

**Comment by vh** [comment]
Will close this issue. All discussions and issues regarding docker already should be here - https://github.com/modxcms/docker-modx
