### ISSUE TITLE
On empty cache event report on manager actions

### ISSUE THREAD

**Issue by neoneddy** [modxcms/revolution#12949]
### Summary

When done so via the menu having a log of when the cache is manually cleared would be nice.  Or at all in some cases to know if certain cache plugins are working correctly.
### Step to reproduce

Clear the cache via manager menu
### Observed behavior

No event registered in manager actions log
### Expected behavior

Since it's an action taken in the manager,  it shoudl be registered in the log
### Environment

MODX Revo, NGINX

**Comment by Oetzie** [comment]
I'm going to try and fix this today.

**Comment by alroniks** [comment]
Related PR marked as closed, but really it is already implemented in this commit https://github.com/modxcms/revolution/commit/a28a2a0f8ade192cf3d11de04f82980e08e10150
So closing as solved.
