### ISSUE TITLE
Locales de_DE, de_AT and de_CH cause problems with Package Manager

### ISSUE THREAD

**Issue by enigmatic-user** [modxcms/revolution#12946]
I encountered a very strange issue regarding the Package Manager. On two sites (both on the same server, one of them served as a dev site for the other one), when I clicked on "Download Extras" in the Package Manager, the main part of the page with the lists of the most popular and the newest packages wasn't displayed, I just saw the message "Loading...".

When clicking on "Extras" in the tree and then on some of the categories, the list was empty and greyed out, again "Loading..." was displayed. Strangely enough, some categories seemed to work normally, but only some pages: Email (first page), Feeds (first page), Hotfixes & Security Updates, Multimedia (first three pages), Richtext Editors, Style (first page), and Uncategorized (first three pages). I could even download and install packages from those categories.

All other MODX sites, on the same server or elsewhere, including a dev site on my local XAMPP server, worked just fine.

It literally cost me several hours to investigate this. Finally I found out that the problem was caused by the locale setting in the system settings, which was de_DE. I could set this to whatever I wanted (fr_FR, nl_NL, de, de_De, de_dE, dE_DE, De_DE, de-DE, de_DE.UTF8, hjgfjhdgfjdf, jkflukg_DE, ...) except de_DE, de_AT, and de_CH (German-speaking countries Germany, Austria, and Switzerland). I could reproduce this on a MODX Cloud site, but not on my local XAMPP server, where de_DE didn't cause any issues.

I'm not sure why this happens and don't have the time to investigate this further at the moment. Hopefully someone has an idea what impact these locales have on the Package Manager. Since the Package Manager worked on both sites several months ago (and most probably after I had set the locale), I guess this behavior has been introduced with an update.

I'm using MODX Revolution 2.4.3 on a Linux server (Apache 2.4.10, PHP 5.6.16 running as CGI); I could reproduce it on a MODX Cloud sever with MODX 2.4.0, but not on a local XAMPP server (Apache 2.4.10, PHP 5.6.3 running as Apache module) on a Windows 7 x64 system.

The issue occurred on every current Windows browser I used.

**Comment by OptimusCrime** [comment]
Was there any errors in the log?

**Comment by enigmatic-user** [comment]
No, nothing showed up there. The PHP error log didn't help, either.

**Comment by enigmatic-user** [comment]
BTW: This should be quite easy to reproduce, since it behaved in the same way on a MODX Cloud that was almost "naked", I did nothing more than a few tests there.

**Comment by Jako** [comment]
Please use a UTF8 capable locale to bypass this. There could be other issues with JSON connector responses using no UTF8 capable locales.

But it should be fixed with #13182
