### ISSUE TITLE
Tree not disabled in 2.5.0-rc2

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#12950]
### Summary

The Tree is not disabled before refreshing, so you can delete an item and then click on it before the tree refreshes, getting error messages.
### Step to reproduce

Delete an item, then click on it before the Tree refreshes.
### Observed behavior

Various error messages are displayed depending on what action you clicked on, saying the object doesn't exist.
### Expected behavior

The tree used to be disabled, so clicking on things didn't do anything until after the refresh.
### Environment

Revo 2.5.0-rc2

**Comment by OptimusCrime** [comment]
Has this behavior changed? Was the tree disabled before?

**Comment by wuuti** [comment]
That's kind of hard to reproduce - even with throttled network connection in chrome. #modxbughunt

**Comment by OptimusCrime** [comment]
@sottwell Do you have anything to add here?

**Comment by OptimusCrime** [comment]
Not able to reproduce this either. The second I click the refresh tree button it becomes disabled and I can not click anything. In fact, the entire tree is collapsed and removed.

Closing this due to lack of feedback/more details. Feel free to reopen or comment. 

@modxbot close
