### ISSUE TITLE
site_start and default_template system settings on install

### ISSUE THREAD

**Issue by sepiariver** [modxcms/revolution#12958]
### Summary
In rare cases, `site_start` and `default_template` system settings get the wrong values on install.

### Step to reproduce
Setup a galera clustered environment. Install MODX on the various nodes. Notice how the different servers will get different IDs for the Base Template and default Resource, but the System Settings will not reflect this. This makes bad things happen.

### Observed behavior
Without a valid `site_start` you get a server error on the front-end. Without a valid `default_template` new Resources are kinda borked.

### Expected behavior
`site_start` should have the actual ID of the default installed Resource. `default_template` should have the actual ID of the default installed Base Template.

### Environment
MODX 2.4.x in specialized cluster environment.

**Comment by Mark-H** [comment]
How is MODX installed on those nodes? I haven't seen something like this before, ever, so it does sound specific to something you're doing...

**Comment by Omeryl** [comment]
It's not, I can explain it further:

In Galera, the nodes are each "holding" an id. Server A holds 1, B holds 2, C holds 3.

Let's say B is the one to install, so it's first incremental value is 2, then it's next is 5 (+3), then 8, then 11. This is to avoid having two nodes insert at the same ID, causing a race condition. The way the installer works is weird in a way that it assumes the rows will always get the initial value of 1 which isn't always the case.

**Comment by Mark-H** [comment]
Gotcha. I thought the reported issue was that the setting value was set to a random ID, but the problem is that it isn't set correctly. Misread, sorry.
