### ISSUE TITLE
Allow snippet-type widgets to use property sets

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#12962]
### Summary

Feature Request:

Since widget snippets have no tag and no way to attach a property set, upgrading the widget package reverts all the snippet's default properties to their default values. This is really bad for packages like UpgradeMODX, which have a lot of control properties, including security settings and access tokens.

Using System Settings for the properties doesn't make sense because the properties are only used by the widget and could conflict with settings for other packages..

**Comment by Jako** [comment]
Using system settings should be the appropriate way. You could use namespaced system setting having a namespace prefix for this, i.e. 'upgrademodx.versionsToShow'.

**Comment by OptimusCrime** [comment]
:+1: for using system settings for this.

Why would you not place them there? Settings for widgets seems very logical and correct to me. Namespaces like @Jako suggest is also the "correct" way to store settings to make sure there is no conflicts.

**Comment by BobRay** [comment]
1. It's a snippet. Snippets already use property sets, there's just no convenient way to specify one for a snippet-type widget. In fact, you can already create and edit a property set for the widget snippet, you just can't use it. It should be possible to put a Property Set selection on the Create/Edit Widget panel for snippet-type widgets. 

2. Snippet-type widgets should be able to use property sets for the same reason that plugins can.

3. Properties in a property set are easier to create, easier to find, and easier to set than System Settings.

4. System Settings are primarily for things that need to be available site-wide. These properties are just for the widget. 

5. If we encourage widgets to use System Settings, we'll end up with a lot more System Settings, all of which will be loaded all the time and many of which won't be needed except very occasionally.

6. MODX motto: "creative freedom."  Adding this feature won't prevent anyone from using System Settings if that's what they think is appropriate for their widget.

**Comment by sottwell** [comment]
There is no way to get at a property set in a snippet's code? Actually you posted this on the forums five years ago
```
<?php
$set = $modx->getObject('modPropertySet',array('name'=>'MyPropertySet'));
$props = $set->getProperties();
 
return print_r($props, true);
```

**Comment by Jako** [comment]
@BobRay they are loaded once from the db, are cached and loaded then from the cache. I still don't see a reason not to use system/user settings for this. 

Widget settings would be good, but not snippet property sets for snippets used in widgets.

**Comment by OptimusCrime** [comment]
One and a half year later and it seem like this is not a problem for anyone else. I am going to close this as a wontfix. As mentioned previously in this issue, system settings is a fine place to store such data.

Feel free to comment or reopen it.

@modxbot close
