### ISSUE TITLE
Restyaboard integration

### ISSUE THREAD

**Issue by reidharry** [modxcms/revolution#12963]
I'm looking to integrate MODX Revolution with [Restyaboard](https://github.com/RestyaPlatform/board)

Can I get the integration document, if any?

**Comment by Mark-H** [comment]
What do you mean with an integration document?

**Comment by OptimusCrime** [comment]
Hello @reidharry. I am not familiar with Restyaboard.

However, the [MODX forums](http://forums.modx.com/) is better suited for asking help like this.

**Comment by OptimusCrime** [comment]
@modxbot close

**Comment by OptimusCrime** [comment]
@modxbot close
