### ISSUE TITLE
modDbRegister->clear doesn't work

### ISSUE THREAD

**Issue by artimarkov** [modxcms/revolution#12965]
### Summary

Register "clear" method doesn't work because of two reasons

package: modx
subpackage: registry
file: /core/model/modx/registry/moddbregister.class.php
class: modDbRegister
method: clear  (line 72)

```
/**
 * Clear the register messages.
 *
 * {@inheritdoc}
 */

  public function clear($topic) {
        $result = $this->modx->removeCollection('modDbRegisterMessage', array('topic' => $topic));
        return (bool)$result;
    }
```

**First reason:** $this->modx->removeCollection throws error.
collection name should be replaced:

```
$result = $this->modx->removeCollection('registry.db.modDbRegisterMessage', array('topic' => $topic));
```

**Second reason:** $topic argument can't be passed to remove collection directly. We have to get topic ID first.

Below is candidate to replace whole method:

```
/**
     * Clear the register messages.
     *
     *  @param string $topic A topic container in which to broadcast the message.
     */
    public function clear($topic) {
        $result = false;

        if (empty($topic) || $topic[0] != '/') $topic = $this->_currentTopic . $topic;
        $topicIdx = array_search($topic, $this->subscriptions);
        $queueId = $this->_queue->get('id');
        if ($queueId && $topicIdx !== false) {
            if ($topicObj = $this->modx->getObject('registry.db.modDbRegisterTopic', array('queue' => $queueId, 'name' => $topic))) {
                $topicId = $topicObj->get('id');
                $result = $this->modx->removeCollection('registry.db.modDbRegisterMessage', array('topic' => $topicId));
            }
        }

        return (bool)$result;
    }
```
### Environment

MODX Revolution 2.5.4

**Comment by artimarkov** [comment]
any actions here?

**Comment by sdrenth** [comment]
Since I'm not familiar with modDbRegister I do not understand why the second reason your giving is an issue? If you just pass the topic id to the clear method it will clear the messages for the given topic ID as long as modDbRegisterMessage has been changed to registry.db.modDbRegisterMessage.

Why can't you just pass a topic ID? Is this method called from somewhere where it will always pass the topic name instead of the ID?

Below clears all messages with topic id 4:
```
$modx->registry->food->clear(4);
```

**Comment by artimarkov** [comment]
@sdrenth yes, we don't use ID. We always calling methods with topic name.
Example:
```
$modx->registry->cartRegistry->send(
                        '/user_cart/',
                        array($session_id => $cart_data),    //storing data with msg num =0
                        array('ttl' => 259200) //OPTIONS: store for 3 days
                    );
```
