### ISSUE TITLE
Checkbox output delimiter being ignored

### ISSUE THREAD

**Issue by paramaniac** [modxcms/revolution#12980]
### Summary

I am seeing this issue in my Revo 2.4.4-pl (trad) install: http://tracker.modx.com/issues/4232
The TV options are being output with pipe symbols and not the specified ","
I can see the comma delimiter setting is saved in the DB.

**Comment by pixelchutes** [comment]
Same issue linked above, but here on GH #4232

**Comment by Lefthandmedia** [comment]
#modxbughunt SInce #4232 has been fixed this issue can be closed too i assume

**Comment by rtripault** [comment]
Alright, let's close.
Feel free to comment/reopen if needed.
Thanks
