### ISSUE TITLE
MODx 2.5.0 administrator is not working right after updating from 2.4.4

### ISSUE THREAD

**Issue by fernandovn** [modxcms/revolution#12998]
### Summary
After updating MODx from version 2.4.4 to 2.5.0 the administrator stopped to work correctly.

### Step to reproduce
While any ID can be modified and saved under the Resources tab, None of the ID's from Elements and Files Tabs can be saved.
![error_shown](https://cloud.githubusercontent.com/assets/446464/15003215/3b746b86-116f-11e6-98b3-b234319ce827.JPG)
![installation_resume](https://cloud.githubusercontent.com/assets/446464/15003216/3b74d12a-116f-11e6-8b95-a81350cd1e94.JPG)
![installation_resume_2](https://cloud.githubusercontent.com/assets/446464/15003214/3b745c5e-116f-11e6-883a-e4e3ccca47e5.JPG)

### Observed behavior
When the user is editing and finally saving any change done to the ID, a blank page appear only displaying buttons at the right corner,

### Expected behavior
The changes applied to the ID must be saved after editing,

### Environment
- MODX version 2-5-0
- Apache
- PHP 5.5.33
- libmysql - 5.1.73
- the error appear in all the tested browsers: Chrome, Firefox and Edge

**Comment by Jako** [comment]
Is the compress_js system setting enabled? Switch it off then.

**Comment by jpdevries** [comment]
As of 2.5.0 compress_css and compress_js shouldn't break anything.

**Comment by OptimusCrime** [comment]
Open up the developer console and look for errors/404s.

**Comment by fernandovn** [comment]
@Jako, I 've already tried switching off the compress_js and compress_css in the settings but the result is the same.

@jpdevries, perhaps something else is affecting the administrator but I haven't been able to find a solution.

@OptimusCrime, no errors related to this beahvior are displayed in the developer console.

I am still stuck with this behavior. I will still be editing directly into the DB until this is fixed in a next release of MODx.

**Comment by Mark-H** [comment]
Doesn't look like a javascript error, as in that case the action buttons seen in the first screenshot don't appear. Makes me wonder if there may be some extra interfering with the elements specifically? Which extras do you have installed, and which plugins are enabled in the elements/plugins tree?

**Comment by fernandovn** [comment]
@Mark-H , I attached an image with the 9 extras I installed in my MODx's website.

**Comment by Mark-H** [comment]
Can you try disabling codemirror? that's the only one on that list that I can think of that would only run on element pages.

**Comment by fernandovn** [comment]
@Mark-H I uninstalled the codeMirror component but I got the same results... It's still not working.

**Comment by pixelchutes** [comment]
For the record, is this with Administrator/Super User user, `sudo = 1`, etc?

**Comment by fernandovn** [comment]
This happens with any user (including administrator or super user)

**Comment by Mark-H** [comment]
@fernandovn If you can send a manager login to hello@markhamstra.com I'll take a quick look to see what's up with that. I haven't seen it elsewhere yet though, so seems to be something specific to that site.

**Comment by OptimusCrime** [comment]
Closing due to lack of feedbck. We need to see the developer console and any javascript errors, as the information given here is not relevant in this case.

Feel free to reopen if you have more information or if you are still experiencing this issue.

@modxbot close
