### ISSUE TITLE
Build error: Source file cache.manifest.php is missing

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#13003]
### Summary
During transport core / build process of a MODX Git installation, the following error is thrown:

> ERROR @ core/xpdo/transport/xpdovehicle.class.php (Line 362)
> Source file **manager/cache.manifest.php** is missing.

### Steps to reproduce

1. Checkout current HEAD of `2.5.x`
2. Perform MODX [Git installation prerequisites](https://rtfm.modx.com/revolution/2.x/getting-started/installation/git-installation)
3. Run `php _build/transport.core.php`
4. See the error after the "Packaged in web context" step.

### Observed behavior
Error is logged due to missing file.

> [2016-05-05 08:17:15] (ERROR @ core/xpdo/transport/xpdovehicle.class.php : 362) Source file manager/cache.manifest.php is missing

### Expected behavior
No errors thrown. Perhaps some missed references since #12985 is now merged?

### Environment
MODX 2.5.x-dev (git)

**Comment by pixelchutes** [comment]
I think the fix is to simply remove [this reference](https://github.com/modxcms/revolution/blob/5324f9245a59c07abfa6f39c1d05673483cd89e5/_build/transport.core.php#L518-L522) from the build script.

**Comment by OptimusCrime** [comment]
Damnit, I must have overlooked this when I removed the HTML5 references. I'll try to submit a new pull request as soon as I can. @pixelchutes solution should do it.

**Comment by Jako** [comment]
Maybe a test for the build process should be added in `_build/test`
