### ISSUE TITLE
Wrong phptype or wrong create value

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13007]
### Summary
The date_sent field in modUserMessage has a datetime phptype but the create processor uses time() during create the record in that field. See https://github.com/modxcms/revolution/blob/2.5.x/core/model/modx/processors/security/message/create.class.php#L153

### Step to reproduce
Maybe it does not create any visible issue, but the value is wrong. It should be some value created by strftime.

**Comment by Mark-H** [comment]
Pretty sure that's valid: https://github.com/modxcms/revolution/blob/2.x/core/xpdo/om/xpdoobject.class.php#L817-L822 (`is_int($v)` would be true on line 820)

**Comment by Jako** [comment]
Is datetime php type equal to unixtime php type? If not, the type is wrong in my opinion.

**Comment by Mark-H** [comment]
There is no "unixtime" php type.

xPDOObject->set transforms values for a `datetime` to a unix time internally (even if you pass it a date/time string), and then in xPDOObject->get it transforms it into a date/time string with strtotime. 

Looks intentional to me.

**Comment by OptimusCrime** [comment]
Unixtime is simply an internal integer.

**Comment by Jako** [comment]
Maybe my initial note was somewhat unclear. The schema definition is the following: https://github.com/modxcms/revolution/blob/2.x/core/model/schema/modx.mysql.schema.xml#L1369

The field is created in the table with this definition:
```
`date_sent` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
```

According to @Mark-H notes, the value is transformed to integer before it is saved. This is somehow wrong, since the dbtype is datetime.

**Comment by Mark-H** [comment]
The `phptype` is only checked when you're setting a value. If the passed value is not an integer, it would turn it into an integer at https://github.com/modxcms/revolution/blob/2.x/core/xpdo/om/xpdoobject.class.php#L823 and back into a properly formatted date string when retrieved in https://github.com/modxcms/revolution/blob/2.x/core/xpdo/om/xpdoobject.class.php#L1020 

Unless there are any bugs indicating a problem with the value being converted from one format to the other and back, I'm proposing to close.

**Comment by OptimusCrime** [comment]
Me too.

Feel free to reopen if you have further information or opinions concerning this issue.

@modxbot close
