### ISSUE TITLE
MODX tree tabs hidden when context collapsed (modx-leftbar-tabpanel)

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#13008]
### Summary
After a vanilla `2.5.x` install, I noticed that the tabs (Resources, Elements, Files) of the MODX tree are inadvertently hidden/toggled whenever the default `web` context is (un)collapsed.

### Step to reproduce
1. Install MODX 2.5.x (may also occur on 2.5.0)
2. Collapse the Web context item in the MODX tree
3. Look for the tabpanel tabs at the top in both states

### Observed behavior
When collapsed, the tabs are hidden.

![tab](https://cloud.githubusercontent.com/assets/352182/15081591/d33571e6-1380-11e6-8604-0d2bea229296.gif)

Changing `compress_js` and `compress_css` settings + clearing cache did not seem make a difference here.

### Expected behavior
Tabs should not hide, and be visible in both states.

### Environment
MODX `2.5.x`, Chrome `52.0.2723.2 dev (64-bit)`

### NOTE:
I believe this is most likely a Chrome (dev) issue and not specific to MODX (does not occur in Safari stable, for example.) I am filing this here for tracking purposes, and will close if it self-resolves.

**Comment by sottwell** [comment]
I haven't seen it in Firefox.

**Comment by pixelchutes** [comment]
Thanks @sottwell. Appreciate it.

Better yet, I'll close this now, and only re-open if it appears in Chrome 52 _stable_.
