### ISSUE TITLE
Error 200 Permission Denied

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#13009]
This error is popping up in 2.5 on MODXCloud with Content Editor permissions. 

Code: 200 OK
{"success":false,"message":"Permission denied!","total":0,"data":[],"object":[]}

I found a thread and report on troubleshooting this but looking through Chrome console logs isn't something a general user should have to do.  Since the error doesn't appear to impact operation shouldn't we have a system setting to hide it from end users or just log it in the log and let developers deal with it if necessary?

**Comment by pixelchutes** [comment]
See #12568 ?

**Comment by pixelchutes** [comment]
@pyrographics closing as dupe, please move any discussion to the thread above.
