### ISSUE TITLE
Error Log not loading in 2.5

### ISSUE THREAD

**Issue by davidpede** [modxcms/revolution#13006]
### Summary
MODX Error Log panel does not load in 2.5 due to 403 errors

### Step to reproduce
Upgraded from 2.4.4, click error log, view console to see files returning 403 error.

### Observed behavior
Error Log panel does not load. Worked as expected before upgrade to 2.5. Consoles shows: 
"NetworkError: 403 Forbidden - manager/assets/modext/sections/system/error.log.js"
"NetworkError: 403 Forbidden - manager/assets/modext/widgets/system/modx.panel.error.log.js"
"NetworkError: 403 Forbidden - manager/assets/modext/sections/system/error.log.js"

### Expected behavior
Should display the MODX Error Log

### Environment
MODX 2.5, Apache 2.4.18, PHP 5.4.45, Mysql 10.0.25, All Browsers.

**Comment by sottwell** [comment]
Do you have something in your .htaccess for the /manager/ directory denying all?

**Comment by davidpede** [comment]
No, just a HTTPS rewrite. Worked fine before upgrade and haven't changed anything.

**Comment by Mark-H** [comment]
If those files exist in those locations, they might have wrong file permissions causing the 403s. When uploading files that can sometimes happen. Also check the folders leading up to it for their permissions.

**Comment by davidpede** [comment]
files exist and permissions are correct

**Comment by OptimusCrime** [comment]
There must be something else going on here. The files are in place and exists. There is nothing that should trigger a 403 for these files in the MODX source code as far as I can tell.

There must be some sort of rewrite or something that triggers this.

**Comment by davidpede** [comment]
looks like its this in the htaccess causing it:
`# htaccess, htpasswd, logs and config.core.php protection
<FilesMatch "(\.log|config\.core\.php|\.[hH][tT][aApP].*)">
  Order allow,deny
  Deny from all
  Satisfy All
</FilesMatch>`

Removed it and the log loads correctly. Confused as it worked fine in 2.4.4.

**Comment by Mark-H** [comment]
Sounds like that'll need some tweaking then, the `\.log` section must be matching on `anything.log.anything` which is too broad for the manager files being loaded.
