### ISSUE TITLE
Error in package manager on Apache 2.4, PHP 7, Windows 10

### ISSUE THREAD

**Issue by DFSko** [modxcms/revolution#13011]
fresh install modx 2.5.0-pl

stuck on loading
![image](https://cloud.githubusercontent.com/assets/811811/15170543/1bf75a06-1760-11e6-9033-b6196c725ed0.png)
JS error in console
![image](https://cloud.githubusercontent.com/assets/811811/15170561/2dc42796-1760-11e6-81f0-6bc500694fa6.png)
![image](https://cloud.githubusercontent.com/assets/811811/15170569/3bfaed40-1760-11e6-86b5-ac007846b4ca.png)

**Comment by OptimusCrime** [comment]
Pretty sure this is the same issue as #13002.

**Comment by Jako** [comment]
Found a solution on #13002. Maybe this is a fix for your installation too.

**Comment by OptimusCrime** [comment]
Closing as a duplicate.

@modxbot close
