### ISSUE TITLE
Issue: Parent Combo Select Breaks Save Process

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#13017]
### Summary
If a parent resource has elements in it's page title, e.g. `<span> <strong> <sup>`, it breaks the resource save process with a Virtual Memory error.  The resource saves, but the saving screen never vanishes.

### Step to reproduce
Create a page with the title, `<span>Overproduced <sup>®</sup></span> Pagetitle`
Add a subpage and save the subpage.
The first save might work, but onces it's refreshed and you're in update mode try to save again.

### Observed behavior
The saving screen continues to spin without being able to complete.  I can confirm this on a 2.2.X site as well. 

### Expected behavior
It would be preferred if the parent title was stripped of elements before being displayed

### Environment
All versions affected.

**Comment by Mark-H** [comment]
Fixed in #13018
