### ISSUE TITLE
Strange behavior of separator

### ISSUE THREAD

**Issue by mishantrop** [modxcms/revolution#13010]
Impossible to move separator normally.
### Step to reproduce
1. Go to http://localhost/manager/?a=security/permission
2. Move separator.
   ![Lal](http://i.imgur.com/gNMYOfA.png)
### Expected behavior

Like in previous releases of MODX, e.g. 2.4.6.
### Environment

Windows and GNU/Linux, MODX 2.5, Opera 37 and Chromium 49.

**Comment by Mark-H** [comment]
It looks like it works as expected when a user group is selected (so that the users grid is shown on the right), so might be a layout issue relevant to that.

**Comment by ajilderda** [comment]
When the 'anonymous'-group is selected (default) the right panel gets 'x-hide-display' as a class. When you disable the 'display: none' on this element the panel resizing works as it should.

**Comment by OptimusCrime** [comment]
This is a duplicate of #13511 as far as I can tell. It was also fixed by #13555.

@modxbot close
