### ISSUE TITLE
extended user settings with quotes in the name

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13012]
### Summary
At the moment you could create a extended setting i.e. with quotes in the name. Those settings can't be edited/deleted after.

### Step to reproduce
Create an extended user setting with a quote in the name and try to edit/delete it.

### Expected behavior
The chars should be restricted for the name field (or htmlspecialchars should be used there).

### Environment
MODX 2.5

### Somehow Related
#12841

**Comment by OptimusCrime** [comment]
This should not be too hard to fix

**Comment by OptimusCrime** [comment]
Wait, has this already been fixed?

**Comment by Jako** [comment]
Not in the name field, If I am right.

**Comment by OptimusCrime** [comment]
I can not recreate this with the extended fields themselves, but the containers crash if they contain quotes. Is that what you meant?

**Comment by OptimusCrime** [comment]
Never mind, now I see

**Comment by Mark-H** [comment]
Fixed per #13019
