### ISSUE TITLE
Migx Modx not displaying in manager 

### ISSUE THREAD

**Issue by waweru1** [modxcms/revolution#13023]
Hi people, how come I can't display Migx or a template variable properly. 

I thought there would be fields and options to add content. 

Kindly advice.

See the screenshot attached.

![screen shot 2016-05-21 at 16 12 05](https://cloud.githubusercontent.com/assets/19505058/15448588/05db14f8-1f6f-11e6-9886-3fd5073ed8ef.png)

### Summary
Quick summary what's this issue about.

### Step to reproduce
How to reproduce the issue, including custom code if needed.

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by OptimusCrime** [comment]
Most likely a problem with MIGX and not MODX, I'd guess.

**Comment by Mark-H** [comment]
Fields and options to add content are shown when you edit a resource with that specific template.

**Comment by sebastian-marinescu** [comment]
They are shown in the Template-Variable Tab, if you don't change their positions via customizations.

**Comment by digitalpenguin** [comment]
You're in the wrong spot - when you create a Template Variable, you assign it to a specific template.
You can then edit the values of that TV on any resource editing page (provided the resource is assigned to the same template)

**Comment by Mark-H** [comment]
@waweru1 I'm marking this issue as closed as it does not appear to be a MODX bug, but simply a misunderstanding. The best place to get help if you're stuck with MODX might be the MODX Community Slack channel (you can get an invite via modx.org), or the MODX forums.
