### ISSUE TITLE
FR: Sorting of error log

### ISSUE THREAD

**Issue by vierkantemeter** [modxcms/revolution#13030]
It would be nice if you can have control over the sorting of the errors in the error log. Now all new errors are added to the end of the file, so you need to scroll down the long list of errors if you want to see the latest one (happens sometimes).

It's a first world problem, and I guess it's not that easy implemented because of the nature of the error log file, but it's just an idea that came up.

**Comment by zaigham** [comment]
@vierkantemeter Please see this http://modx.com/extras/package/controlerrorlog

**Comment by vierkantemeter** [comment]
Thanks, I'm already using this addon. It's great!

**Comment by Jako** [comment]
Since there is an extra available solving this issue, I close this.

The behaviour of the log file can't be changed, only the display could be different. The extra mentioned above does this quite good.
