### ISSUE TITLE
Media Source policy in modMediaSource

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#13033]
### Summary

I'm trying to retrieve files for FileDownload-R using media source, but it seems the mediasource's permissions are not matching with Media Source policy.
In getContainerList(), it requires "[directory_list](https://github.com/modxcms/revolution/blob/2.x/core/model/modx/sources/modfilemediasource.class.php#L145)" and "[file_list](https://github.com/modxcms/revolution/blob/2.x/core/model/modx/sources/modfilemediasource.class.php#L171)", but Media Source policy doesn't provide them.
I added those permissions into **MediaSourceTemplate** through ACL page in manager, but it still doesn't work.
After investigated a bit, it seems modMediaSource gets its permissions from other than Media Source policy.
### Step to reproduce

Install FileDownload-R, use media source. Eg:

```
[[!FileDownload?
&getDir=`downloads`
&mediaSourceId=`1`
]]
```

Let's say "downloads" is a folder in "public_html"
### Observed behavior

[$scanDir = $this->mediaSource->getContainerList($rootPath);](https://github.com/goldsky/FileDownload-R/blob/master/core/components/filedownloadr/model/filedownloadr/filedownloadr.class.php#L1103) returns empty.

I have to override the permissions like this:

```
$this->mediaSource->permissions['directory_list'] = true;
$this->mediaSource->permissions['file_list']      = true;
$scanDir = $this->mediaSource->getContainerList($rootPath);
```

which is not recommended inside the core code.
### Expected behavior

Shouldn't the media source gets the permissions from Media Source policy?
### Environment

MODX 2.4.0-pl
Server version: Apache/2.4.20 (Ubuntu)
Server built:   2016-05-05T15:42:04
PHP Version 5.6.21-9+donate.sury.org~xenial+1
MySQL 5.7.12-0ubuntu1

**Comment by Mark-H** [comment]
`directory_list` and `file_list` are part of the administrator template. Media source policies control access to the media sources themselves. 

There's probably a hint of legacy showing here from before media sources were introduced...

**Comment by wuuti** [comment]
@Mark-H So this is not a bug and can be closed. #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @wuuti

**Comment by OptimusCrime** [comment]
@modxbot close
