### ISSUE TITLE
[Enhancement] cleanAlias on base of context settings

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13046]
### Summary

The modX cleanAlias method should get the friendly_alias_translit setting on base of the context of the resource.
### Observed behavior

At the moment the translit table could only be set globally for the whole site (according to some tests and after inspecting the code).
### Expected behavior

It should be set on context base.

**Comment by Flowan** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by OptimusCrime** [comment]
PR merged. Closing.

@modxbot close
