### ISSUE TITLE
Potential for cache poisoning

### ISSUE THREAD

**Issue by paulkoan** [modxcms/revolution#13040]
### Summary
If base_href is set to [[+site_url]] and the website is the default site of a web server, then a third party can poison the cache by crafting an HTTP GET request with a Host: header of their choosing, causing the bash_href to be populated with the URL placed in the host: record in the MODX cache.  This would then cause subsequent visitor to load resources from the third party controlled server.

### Step to reproduce
1) Set base_href to be [[+site_url]]
2) Make site the default of a webserver (for example when accessed by IP address - say 99.99.99.99)
3) On another machine edit your hosts file, and put the hostname you want to be inserted into base_href as the resolution to the webserver IP address (99.99.99.99 mymalicioussite.com)
4) Clear the MODX cache
5) Access the site using the hostname defined (mymalicioussite.com)

### Observed behavior
base_href takes on the third party hostname (http://mymalicioussite.com/), and is saved to the cache.  Subsequent visits to the site by anyone would cause things like css, images, javascript to be loaded from the external site - such as http://mymalicioussite.com/js/scripts.js

### Expected behavior
How it should behave after following steps above.
This is the expected behaviour by design, perhaps it shouldn't be?

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

Confirmed on MODX 2.4, probably any site where http_host is defined as  `$http_host= array_key_exists('HTTP_HOST', $_SERVER) ? $_SERVER['HTTP_HOST'] : 'domain.com';`

**Comment by Mark-H** [comment]
That's why you always need to use that particular setting uncached: [[!++site_url]]

If there's documentation not clearly stating that, those docs should be fixed.

**Comment by paulkoan** [comment]
Yes, Jason (opengeek) just pointed that out in Slack.  I think this may be understood by many, but it didn't occur to me until my cache was poisoned - I certainly missed it.

Given the nature of its use, perhaps it should be an uncached setting by default?

**Comment by Omeryl** [comment]
Furthermore, you really shouldn't allow a MODX site to be the default host, in my opinion. Lock down your web server configuration.

**Comment by Omeryl** [comment]
It's not .. really possible to do what you want. This is kind of down to the site creator to make it uncached if they deem it fit (or to just, you know, fix their web configs). Let's not force a solution down people's throats.

**Comment by paulkoan** [comment]
Shall we close this?

**Comment by OptimusCrime** [comment]
While this is indeed in theory possible, I have a hard time understanding how configured servers possibly could be attacked by this. Unless you to listen for ALL incoming traffic and pass it to the MODX installation, this would never happen.

What does other people think? Could it be smart to fix this potential hack?

**Comment by paulkoan** [comment]
A web server configured without named virtual servers would do exactly this - however, it is not good practice to have a server configured this way even with a single site.  Even if this was fixed in MODx the same problem could potentially arise using any caching approach for servers configured this way.  I think this is a close because it is not a MODx problem unless there is already a server problem - so the server problem should be fixed.  There is more detail in the slack discussion.
