### ISSUE TITLE
Installer Button

### ISSUE THREAD

**Issue by EkoOne** [modxcms/revolution#13048]
Installer "Continue" button text not centered. See screenshot.

Revo 2.5.0

![installer](https://cloud.githubusercontent.com/assets/1754223/15873539/caa76c02-2cc4-11e6-97c6-2e071f5c4fd5.png)

**Comment by meshkov** [comment]
Confirm
![2016-06-08_14-06-09](https://cloud.githubusercontent.com/assets/1703670/15892418/3428877a-2d82-11e6-8330-25b50d3d8942.png)

**Comment by Pathologic** [comment]
I've fixed that by changing  https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/workspace/package.panels.js#L152 to:
```
            Ext.getCmp('package-install-btn').autoWidth = true;
            Ext.getCmp('package-install-btn').setText(_('continue')).syncSize();
```

**Comment by Jako** [comment]
@Pathologic Thanks for your solution. I have created a slightly modified PR with that.

**Comment by Pathologic** [comment]
Thanks for quick response, @Jako
