### ISSUE TITLE
OnDocFormRender set template bug

### ISSUE THREAD

**Issue by Tauntik** [modxcms/revolution#13049]
In plugin with OnDocFormRender event, i can't set document template.

$resource->set('template', 3);
or
$modx->controller->setProperty('template', 3);
make no effect

MODx version: 2.5.

On version 2.2 
$modx->controller->setProperty('template', 3);
this wariant worked fine.

**Comment by Realetive** [comment]
It's ok for me. See working example here: https://gist.github.com/Realetive/b92384dc615cd481e5f436d586a2d82f

**Comment by Flowan** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by Alroniks** [comment]
Could be this issue to be related to your fix? https://github.com/modxcms/revolution/issues/10140 @Flowan

**Comment by OptimusCrime** [comment]
This worked before the patch?

**Comment by Mark-H** [comment]
Merged #13330 which fixes this.
