### ISSUE TITLE
Static Resources and Manager/Form Customization and the "Content" field

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#13042]
### Summary

It doesn't seem to be possible to hide the "content" field of a static resource. 
It's also not possible to change the label/title of this field.

Use case: I don't want my users to mess around with the value stored inside "content" because I'm setting the destination of a static resource with a file TV using a dedicated media source (assets/id/{id}/files/).
### Step to reproduce

Create a form customization rule for a template that is used with static resources. Try to hide or rename the content field.
### Observed behavior

The content field remains unaffected by form customization.
### Expected behavior

You should be able to hide this field or to rename it.
### Environment

Latest (2.5) MODX Revo on Skytoaster.

Cheers,

pepebe

**Comment by mindeffects** [comment]
+2
Good point! There should be a "consistent" user interface/experience, where similar things are handled similar.

**Comment by pepebe** [comment]
Still an issue in 2.5.4. settings in Manager Customisation are ignored. The field can't be renamed or hidden. 

The main cause seems to be the fact that "static resource" and "content" are totally different UI elements with different ids, etc.

Lets do some brainstorming how to tackle this without breaking something...

The first thing that comes to my mind is a new line in MC (**modx-resource-content-static**) just below **modx-resource-content**.

I guess adding this to the MX form would already do the trick (no proof for this, I have to look this up).

**Comment by Ibochkarev** [comment]
Fixed #15637
