### ISSUE TITLE
 No 'system_settings' 

### ISSUE THREAD

**Issue by mregan** [modxcms/revolution#13054]
### Summary
On doing a new install the 'system_settings' table is not being created

### Step to reproduce
This appears to be specific to mySQL 5.7 with 'NO_ZERO_DATE' set in the sql_mode

### Observed behavior
Setup runs with no errors until it tries to Login where I got a 503 error. The cache log file indicated that there was no 'system_settings' table - which I confirmed in phpMyAdmin.

### Expected behavior
Setup to run and complete normally

### Environment
MODX version - 2.4.3, 2.5.0.pl and 2.5.0.rc2 - this doesn't appear to be version specific

Webserver:
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-04-15T18:00:57

Database Server:
Server type: MySQL
Server version: 5.7.12-0ubuntu1 - (Ubuntu)

**Comment by Mark-H** [comment]
Could you try this with the latest 2.5.x branch from github? I believe there have been several issues fixed related to MySQL strict mode and some 5.7 related changes. Those fixes would have targeted 2.5.1 which is not yet available as stable release.

**Comment by mregan** [comment]
Mark -
That fixed it.

I haven't used GIT Hub before - do I mark the tread as fixed or do you 
do that?

Michael Regan
TIMR Web Services
http://www.timrwebservices.com
250.218.5285

Follow Us on G+
https://plus.google.com/115502661566705774119/posts

**Comment by pixelfanatiker** [comment]
Sehr geehrte Damen und Herren,

von 17. bis 25. Juni bin ich im Urlaub. Ihre Nachricht wird ab dem 27. Juni beantwortet.

Mit freundlichen Grüßen
Florian Gutwald
Agile Software Developer

**Comment by Mark-H** [comment]
We both can do that :)
