### ISSUE TITLE
FC's new name don't work for hidemenu

### ISSUE THREAD

**Issue by Realetive** [modxcms/revolution#13053]
### Summary
If setup new label name for hidemenu field, this isn't use. If this setup for published it's ok.

### Step to reproduce
Create new Form Customization rule and try to setup new label name for hidemenu. 

### Observed behavior
Nothing to changes.

### Expected behavior
Checkbox label need to equal new label name from CMP

### Environment
MODX v2.5.0-pl

**Comment by Jako** [comment]
I think you mean FC (Form Customization) instead of CMP (Custom Manager Page).

**Comment by Realetive** [comment]
@Jako sorry, yes, you are right.

**Comment by Mark-H** [comment]
Dupe of #12890 and fixed in #13025 for 2.5.1

**Comment by Realetive** [comment]
Many thanks @Mark-H . Good news.
