### ISSUE TITLE
MODX missing lexicon values

### ISSUE THREAD

**Issue by sakshi083** [modxcms/revolution#13058]
I am new to MODX. I have installed MODX Revolution 2.2.0-pl2 (traditional) on a windows shared server.
PHP version 5.6.
After installation lexicon values are missing. No entries found under system->lexicon management.
This results in improper website back-end and front-end. I also googled the issue but I found nothing helpful.Need help.

**Comment by Mark-H** [comment]
MODX 2.2.0-pl2? That's pretty old, any reason you didn't install the latest stable version?

**Comment by sakshi083** [comment]
I am moving a site from another server. And, the existing site is in MODX 2.2.0-pl2. Don't want to mess up with newer version.

**Comment by Jako** [comment]
I suppose it is a PHP version issue. What version do you have on the old host, what version on your local host?

**Comment by sakshi083** [comment]
On old host version is PHP 5.3 and on new host (Provided by network solutions) its 5.6.
Everything was working good on old server. On local server froent end works but back end has a very different UI. No lexicon values being fetched. Can you tell me where we code to include lexicon files?

**Comment by Jako** [comment]
Could you downgrade your windows shared server to PHP 5.3 to test, if it works with that version?

If not: Maybe something is misconfigured in MODX. If the backend is showing issues, deactivate compress_js/compress_css with in modx_system_settings table and clear the cache folder after this.

**Comment by sakshi083** [comment]
No, I cannot downgrade PHP Version becuse it is windows server.
And, I already deactivated compress_js/compress_css with in modx_system_settings table.
Also, cleared cache folder. but nothing works.

**Comment by Jako** [comment]
Is it a live site? Otherwise you should try an update to 2.5 (maybe with a few version stops between 2.2 -> 2.3 -> 2.4 -> 2.5).

**Comment by sakshi083** [comment]
Yes it is a live site.

**Comment by Jako** [comment]
Creating a local copy and test this copy with PHP 5.3 (should be possible with XAMPP - see http://stackoverflow.com/questions/25397219/how-to-downgrade-php-from-5-5-to-5-3) could be an option. Then you know, If this is caused by PHP issues.

**Comment by sakshi083** [comment]
I have created a local copy with PHP 5.2.9 and everything is working fine there.

**Comment by sakshi083** [comment]
I cannot downgrade PHP version from 5.6 to 5.3 on new hosting as it is a shared server. Please help.

**Comment by Mark-H** [comment]
My guess is that if you can't downgrade PHP, you'll need to upgrade MODX. While I can't guarantee it solves this issue, it will resolve tons of bugs that have been fixed since 2.2, including several security related ones.

**Comment by Jako** [comment]
You could upgrade the local copy to 2.5 and upload this to a different host (i.e. a subdomain) on the shared server …

**Comment by sakshi083** [comment]
I upgraded local copy to 2.5 also upgraded PHP version on local to 5.6.21. Everything works fine on local.
So, I upgraded MODX to version 2.5 on Server. Now when I run setup I get this error:
Fatal error: Uncaught --> Smarty: Unable to load template file 'header.tpl' <-- thrown in www\core\model\smarty\sysplugins\smarty_internal_template.php on line 219

Unable to run setup.Please help.

**Comment by OptimusCrime** [comment]
Does this happen when you try to run the setup? Missing files might suggest something has gone wrong while uploading/moving the files. I can not reproduce this at this end. Also, it might be smart to open individual issues dealing with different things.

**Comment by wuuti** [comment]
@sakshi083 Did you manage to upgrade your old site? 

I think this issue can be closed.

**Comment by pixelchutes** [comment]
Agreed. Please move this conversation to Slack or the forums if you are seeking further support.
