### ISSUE TITLE
Modx Manager Logout Url?

### ISSUE THREAD

**Issue by TheNullByte** [modxcms/revolution#13069]
### Summary
Is there any way to provide a redirect after logging out of the manager in modx. Essentially we are trying to provide a single logout solution via SAML, but we can't do so currently because we can't redirect the logout page to our idp logout page. 

Essentially what I'm looking for is something like this https://github.com/TheNullByte/revolution/commit/94c34c2e126c3537c3c7889a475a7ee387b188cd

### Step to reproduce
Just logging out if needed.

### Environment
MODX version 2.5.0, apache 2.4, Chrome

**Comment by OptimusCrime** [comment]
Not 100% sure what you mean, but you could call the `runProcessor` on the logout process and redirect the user after that?

Something like this: http://forums.modx.com/thread/?thread=95621

**Comment by TheNullByte** [comment]
But how would we hook into that? Essentially I would like to be able to have someone go into the manager, click the logout in the top right, and have it redirect to our SAML logout page. Every plugin event I've tried doesn't seem to work because of the ajax response, and the runProcessor I think would only be useful outside of the manager context, no? I could be wrong though.

**Comment by Mark-H** [comment]
It's possible to create custom menu items... maybe just add your own with the right link and hide (with permissions) or remove the standard one?

**Comment by TheNullByte** [comment]
Oh duh, I completely forgot about that! That'll work!

**Comment by pixelchutes** [comment]
Seems related to #11848

**Comment by TheNullByte** [comment]
Ah that's exactly what my issue is related to!
