### ISSUE TITLE
PHP Warnings like in #13041

### ISSUE THREAD

**Issue by LitvK** [modxcms/revolution#13073]
### Summary

Having following errors too:
AH01071: Got error 'PHP message: PHP Warning:  session_start(): Session callback expects true/false return value in /srv/www/core/model/modx/modx.class.php on line 2270\n'
### Step to reproduce

It begins after setting variables in php.ini:
session.gc_probability = 1
session.gc_divisor = 100

In this case warning will arise every 100 pages. Perhaps if you set session.gc_divisor to 1, this warning will fall every time. It makes real troubles on AJAX scripts which returns JSON data. This warning brokes JSON data and make pages unavailable.
### Observed behavior

If you have activated garbage collector for sessions and enabled E_WARNING errorlevel in PHP, it will throw warnings about ModX callback function. The same problem was in roundcube some time ago:
https://github.com/roundcube/roundcubemail/issues/4948.
### Expected behavior

No warnings at all.
### Environment

PHP 7.0.4-7ubuntu2.1 (cli) ( NTS )
Apache/2.4.18 (Ubuntu)
MODX Revolution 2.5.0-pl

**Comment by meshkov** [comment]
I have this warnings too.
`[Fri Mar 10 10:09:57.114320 2017] [:error] [pid 39551] [client 217.69.134.14:41997] PHP Warning:  session_start(): Session callback expects true/false return value in /server/public_html/core/model/modx/modx.class.php on line 2284`
Environment:
MODX Revolution 2.5.5-pl (traditional)
PHP Version 7.0.15
Apache/2.4.7
php.ini:
session.gc_divisor = 100
session.gc_probability = 1

**Comment by meshkov** [comment]
This is hosting settings and I can not change them - session.gc_divisor and session.gc_probability.
In Google there are a lot of sites with this problem.
example:
![image](https://cloud.githubusercontent.com/assets/1703670/23821562/7dc75da4-0647-11e7-98cd-f8207792ed86.png)
My search query in google:
`PHP Warning: session_start(): Session callback expects true/false return value in core/model/modx/modx.class.php on line 22`

**Comment by Mark-H** [comment]
Fixed in 2.6
