### ISSUE TITLE
Opening .htaccess over filetree redirects manager to error page

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#13083]
As said in the title.

I'll go more into details tonight or tomorrow.

Cheers,

pepebe

### Summary
Quick summary what's this issue about.

### Step to reproduce
How to reproduce the issue, including custom code if needed.

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by OptimusCrime** [comment]
Closing as this is not a valid issue. Feel free to reopen if you fill in the missing information.

@modxbot close
