### ISSUE TITLE
Error with thumbs in manager

### ISSUE THREAD

**Issue by Gliba** [modxcms/revolution#13082]
### Summary

Error with thumbs in manager wen usin s3 bucket as media source
### Step to reproduce

Folowe standard docs for setup s3 media source, and using resizer option in pThumb
### Observed behavior

I get error shown on scr
![image](https://cloud.githubusercontent.com/assets/1550782/17066453/699ae168-5047-11e6-9f88-277ec0a1f84c.png)
### Environment

Using (serverpilot setup) php 5.6, ubuntu 14, modx 2.5.1 width pThumb

**Comment by Jako** [comment]
Could you try this PR to solve this: #13125

**Comment by OptimusCrime** [comment]
No feedback or comment in a year. 

@modxbot close
