### ISSUE TITLE
Output filters else/then et al error with PHP 7 handling of eval with empty conditions

### ISSUE THREAD

**Issue by prioritypie** [modxcms/revolution#13086]
Using `:else` and `:then` output filters (and possibly `show`, `hide`) generates parse errors if the conditional test is empty. PHP 7 now throws a `ParseError` if the eval-ed code is invalid - [PHP manual](http://php.net/manual/en/function.eval.php). Previously `eval` would return `FALSE` on errors, so the filter continued to process.

### Steps to reproduce
Trivial example that will throw the error:
```[[*PossiblyEmptyTV:notempty=`This is not empty`:else=`It is empty`]]```

### Workaround
In the output filter, check for empty conditional before running eval, e.g. in `core/model/modx/filters/modxoutputfilter.php`, ~175
```
    case 'else':
        $conditional = join(' ', $condition);
        if($conditional==='') $conditional = "''"; // Give eval something to work with so it does not throw error
        try {
            $m_con = @eval("return (" . $conditional . ");");  // In PHP7, the code "return ();" will throw a ParseError
            $m_con = intval($m_con);
            if (!$m_con) {
                $output= $m_val;
             }
         }
         catch (Exception $e) {}
    break;
``` 

### Environment
MODX 2.5.1 Mysql 5.6 PHP 7.0.8 Apache 2.4

**Comment by Jako** [comment]
Your modifier chain is invalid: notempty is not a conditional modifier, so else is not valid there.

But you are somehow right: `then` and `else` should only run if the $condition array is not empty.
