### ISSUE TITLE
User profile events  - OnUserChangePassword?

### ISSUE THREAD

**Issue by Jacqbus** [modxcms/revolution#13080]
I can't find any events that can be fired if there's changes are made in user's profile/password form (i mean /manager/?a=security/profile) in manager. My idea (in this certain case) was to force users to use certain pattern of password, if they want to change it on that page. But i think there's much more possibilities to use that events.

So my suggestion is to attach "OnUserChangePassword" event to this page, or create new one eg. OnProfileChangePassword. Similary other events (form render, form save etc.).

But im not sure which approach will be better - use existing one, or create new ones?

**Comment by ilyautkin** [comment]
If user change password from (/manager/?a=security/profile), fired event OnUserChangePassword.

There are no info about old user pass, if admin change user password at (/manager/?a=security/user/update). You need to use OnUserFormSave event. For example
```
if ($user->get('newpassword') == 'true') {
    $modx->log(1, 'OnUserFormSave. Password was changed, Pass: ' . $user->specifiedpassword);
} else {
    $modx->log(1, 'OnUserFormSave. Password was not changed');
}
```

There is no need in the event OnProfileChangePassword, on my opinion.

**Comment by Jacqbus** [comment]
So i need to review my code again, because when i posted that issue, "OnUserChangePassword" was not trigerred when i changed password from there. Now (on fresh install o modx 2.5.5) it works just fine.

But still don't have idea how to force users to use certain password pattern (eg. min 10 characters with letters and at least 2 special characters and 2 digits. I don't want to (and of course i shouldn't) override core files, because of future modx updates. Any ideas?

**Comment by bezumkin** [comment]
@Jacqbus You need to use `OnBeforeUserFormSave` event and check `$data['newpassword']` variable. If it is not good enough - return error and user will not be saved:
```
$modx->event->output('Bad password!');
```


I think it should be closed @Mark-H
