### ISSUE TITLE
Problems with resources after update from v2.5.0 to v2.5.1

### ISSUE THREAD

**Issue by Oliver-Meyer** [modxcms/revolution#13085]
### Summary
After update from v2.5.0 to v2.5.1 I can't add or edit resources.

### Step to reproduce
Update from v2.5.0 to v2.5.1 and then try to add or edit resources.

### Observed behavior
Unable to add or edit resources.

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to a member function get() on array in /var/www/vhosts/example.com/example.com/manager/controllers/default/resource/resource.class.php:152\nStack trace:\n#0 /var/www/vhosts/example.com/example.com/core/model/modx/modmanagercontroller.class.php(158): ResourceManagerController->firePreRenderEvents()\n#1 /var/www/vhosts/example.com/example.com/core/model/modx/modmanagerresponse.class.php(74): modManagerController->render()\n#2 /var/www/vhosts/example.com/example.com/core/model/modx/modmanagerrequest.class.php(180): modManagerResponse->outputContent(Array)\n#3 /var/www/vhosts/example.com/example.com/core/model/modx/modmanagerrequest.class.php(128): modManagerRequest->prepareResponse()\n#4 /var/www/vhosts/example.com/example.com/manager/index.php(62): modManagerRequest->handleRequest()\n#5 {main}\n thrown in /var/www/vhosts/example.com/example.com/manager/controllers/default/resource/resource.class.php on line 152\n'`

### Expected behavior
To be able to add and edit resources.

### Environment
- MODX v2.5.1pl (traditional package)
- Apache v2.4.6
- Nginx v1.11.1 (reverse proxy)
- PHP v7.0.9 (fpm)

**Comment by rthrash** [comment]
By chance, do you have TinyMCE installed?

**Comment by Oliver-Meyer** [comment]
Yes, it was TinyMCE - thanks :) Deinstalled - all working again.

**Comment by rthrash** [comment]
There should be a newer TinyMCE available, and TinyMCE Wrapper that doesn't have this problem. An update should be released for the original Tiny, too, and tracking down the source of the breaking change on this as well.

**Comment by Mark-H** [comment]
The fix for TinyMCE can be found here: https://github.com/modxcms/TinyMCE/pull/20

**Comment by Mark-H** [comment]
MODX 2.6.0 also has a patch that prevents this error from another angle, so as long as you keep your extras and core up to date you'll be fine.
