### ISSUE TITLE
Advanced setup page had mysql password pre-filled.

### ISSUE THREAD

**Issue by Dutchy-** [modxcms/revolution#13090]
### Summary

On an existing installation, the mysql password is displayed on the 'advanced installation' setup page, even though it says you need to know this password. This is a security risk; users may falsely believe that leaving the setup available temporarily is secure.
### Step to reproduce
- Install modx revolution
- Leave the setup on the server
- Go to setup and click advanced installation.
### Observed behavior

It had the database password pre-filled.
### Expected behavior

It should not display the database password.
### Environment

2.5.0-pl.

Extra note, I do not have a test setup and am not directly affected by this, but I encountered this on a test environment for a customer.

**Comment by OptimusCrime** [comment]
I guess it is just a matter of turning autocomplete off on the input fields here. I suggest the content is fetched from previous submissions.

**Comment by Dutchy-** [comment]
This was not a browser autofill. This is the CMS pre-filling. I was not an administrator of this server and should not have these credentials.

**Comment by OptimusCrime** [comment]
You are right, but it looks like this only happens when you are doing an upgrade with the setup already ran? There is no way for the modx installer to "guess" the password if it is the initial run.

Also, there are several warnings informing the user that a public installer is not safe. It even says so on the manager dashboard if present.

**Comment by Dutchy-** [comment]
Straight from my development proxy:

```
GET /setup/index.php?action=database HTTP/1.1
Host: acc.real.host.hidden.com
```

```
HTTP/1.1 200 OK
Date: Fri, 12 Aug 2016 09:46:22 GMT
Server: Apache
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
X-FRAME-OPTIONS: SAMEORIGIN
Connection: close
Content-Type: text/html; charset=utf-8
Content-Length: 6679

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

(contents shortened)

   <div class="labelHolder">
        <label for="database-user">Database inlognaam:</label>
        <input id="database-user" name="database_user" value="the-prefilled-username-was-here" />
        &nbsp;<span class="field_error" id="database-user-error"></span>
    </div>
    <div class="labelHolder">
        <label for="database-password">Database wachtwoord:</label>
        <input id="database-password" type="password" name="database_password"  value="the-prefilled-password-was-here" />
        &nbsp;<span class="field_error" id="database-password-error"></span>
    </div>
```

And yes, this is after the install, when you access the setup/upgrade again. Note that that page says "you need the username and password". That was obviously not true because it was pre-filled.

**Comment by Dutchy-** [comment]
Some more info:

```
<tr>
    <th>
        <img src="assets/images/im_inst_upgrade.gif" width="32" height="32" alt="" />
        <label>
            <input type="radio" name="installmode" id="installmode3" value="3" />
            Geavanceerde upgrade opties<br /><small>(wijzig database configuratie)</small>
        </label>
    </th>
    <td>Voor geavanceerde database beheerders of verplaatsen naar servers met een ander database verbinding karakterset. <strong>Je dient jouw volledige database naam, gebruiker, wachtwoord en verbinding/collatie details te weten.</strong></td>
</tr>
```

So installmode 3 and the text there is the message saying you need to know the username and password. Again, I was not the administrator and I shouldn't be able to find out the password even if the setup was left on the server.

I'm just making this very explicit here because "autocomplete off" (if we're talking about the browser/html option) is not a solution and reactions like that worry me.

**Comment by sottwell** [comment]
I get this if I have the password to the new installation's Manager saved. The browser sees the "password" field and loads it with the manager's login password. If I have used the same password for the MODX manager and the database, it will have the effect you're mentioning. Since I never do that, it's always a different password, but you get the point. If you have any password saved for that domain, it'll use it to populate any password field from anywhere on the domain.

**Comment by Dutchy-** [comment]
I have proof that it was sent by the server, but this contains customer data; I can't send this to you. Anonymous data is already posted above. I don't know what else I can say, but I'm really done with "it was probably your browser".

**Comment by OptimusCrime** [comment]
I do agree that this comes from the server, but only in the cases I mentioned. If you already have the config up and running MODX detects that you are doing an upgrade and enters the details for you. As far as I know this has always been the case.

However, I also think that what @sottwell describes is the case too, there is no `autocomplete="off"` on the fields, meaning the browser could do the same thing too.

**Comment by Mark-H** [comment]
Why are we even discussing this? The report is clear and this definitely needs to be addressed.

**Comment by Dutchy-** [comment]
I would appreciate not conflating the issues, and I recommend that you do not waste your time on autocomplete=off: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields

>  - if a site sets autocomplete="off" for a form, and the form includes username and password input fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits this page.
> - if a site sets autocomplete="off" for username and password input fields, then the browser will still offer to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits this page.

And thanks @Mark-H

**Comment by wuuti** [comment]
That's one of the reasons why we have to implement a _password check at the start of the setup_ (first step!). Only users in the admin group (with sudo or having a new permission "run_setup" or something) would then be able to continue the setup, should be somewhat easy to implement. 

I don't think it's ok to lean back and say, hey, we warned you not to leave the setup there several times. Even if I always delete the setup after upgrade, there is still the remaining time between the copying of the folder and the final setup stage. The upgrade might be interrupted for some time, or something fails on the server leaving the folder there. And in the meantime the described problem may occur. Or someone else enters a remote database and performs a fresh installation (possible?) of my site. Or does nothing but only notes down the shown password to do some subtle nasty stuff afterwards. 
To get back to this discussion: why should we ever send back a cleartext password for the db from the server just for the prefilling convenience? **MODX shouldn't do that**. Never. No matter under what circumstances this happens.

**Comment by jaygilmore** [comment]
Folks, I don't know if anyone has looked into the script, but isn't the upgrade installer reading the `core/config/config.inc.php` to find the credentials? I don't think we're talking about autocomplete here. I think we're talking about a UX decision made to simplify an upgrade.

**Comment by pixelchutes** [comment]
Whatever direction we take, remember the installer needs to support new installs as well. In that scenario, there would be no SUDO user or Administrator defined yet.

**Comment by jaygilmore** [comment]
@pixelchutes I agree. This should only affect upgrades where the DB credentials would be exposed to alter.

**Comment by wuuti** [comment]
Should be easy to programmatically differentiate between a new install or an upgrade. But that should be discussed elsewhere - I think even if the setup is authenticated we should never send a password back from the server.

**Comment by jaygilmore** [comment]
@wuuti , the point of the advanced install is to allow the changing of the DB settings and directory paths from the UI rather than via the filesystem. Keeping in mind that I am 99.99% certain the setup is fetching the credentials and paths from the `/core/config/config.inc.php`. So, what you're suggesting is removing this part of the UI altogether?

**Comment by wuuti** [comment]
Maybe I am puzzled a bit here. Are we talking about an upgrade or a change from traditional to advanced (with DB changes included)?
If one wants to change the db settings via UI in an existing installation, there is no need to deliver the password back to the user (and then back to the server). Either the user has just transferred the db to another location keeping the old password. Or a new db password has to be set during the adv-setup - in this case we don't need the old one any more. So, maybe, if at adv. setup the pw field is left blank by the user that means "do not change password" (i think thats a common way). If something is entered, this is the new pw. The input fields there could be manually activated by a "I want to change the password" trigger...

**Comment by jaygilmore** [comment]
I'll leave it to others to decide on execution. I just think we're being over cautious here. What shouldn't happen is that an anonymous user should ever see the password via a web ui. After that I have little concern how it's handled.

**Comment by Mark-H** [comment]
Pull request in #13282 - I also hid got rid of the database username and database name. Left in database server and collations as those are not as critical to protect (and the host is `localhost` 99% of the time), so I opted to keep the usability of not having to look those things up.

**Comment by Jako** [comment]
@Dutchy- Thanks for opening the issue
@Mark-H Thanks for fixing this
