### ISSUE TITLE
five curly brackets will become substituded to one squared bracket

### ISSUE THREAD

**Issue by mopox** [modxcms/revolution#13091]
### Summary
{{{{{ }}}}} becomes substituded to [ ] in templates.

### Step to reproduce
include {{{{{ }}}}} into a template or <?php return "{{{{{ }}}}}"' into a snippet

### Observed behavior
the output always will be [ ]

### Expected behavior
though, it should be untouched and the expected output should be {{{{{ }}}}}. that is important if one is working with JSON that are more than 5 levels deep.

### Environment
Tested with MODX Revolution 2.5.0 and 2.5.1, Apache/2.4.7 (Ubuntu), MySQL 5.5.50, Firefox 47.0

**Comment by pixelchutes** [comment]
Very interesting. I've tried both Template and custom snippet, neither of which are converting my output:

![test](https://cloud.githubusercontent.com/assets/352182/17719228/3e3fc3d8-63d6-11e6-936e-3b86411dfe7d.jpg)

**Comment by pixelchutes** [comment]
@mopox how is the data being loaded? _e.g. via traditional **GET**, or perhaps, **POST**?_

**Comment by mopox** [comment]
well, i was able to reproduce ur findings. with a cleanly installed modx without modules and so one. i do not see the problem. so i ve to trace down the module which is making the trouble.

**Comment by mopox** [comment]
by the way, for loading the JSON data i am using **XMLHttpRequest**. but i don't really think it matters. coz when i load it traditionally it is the same issue...

**Comment by Mark-H** [comment]
If you're using pdoTools (the pdoParser) I think the {{ }} syntax might have a meaning there?

**Comment by Jako** [comment]
It could be the Fenom parser. Please deactivate the Fenom parser for the page template in modx system setting: `pdotools_fenom_parser` -> `no`

**Comment by mopox** [comment]
Yes, i am using pdoTools but pdotools_fenom_parser  is already deactivated ... so i ll go into pdoTools more. thx

**Comment by pixelchutes** [comment]
Think we are good to close this issue?

**Comment by mopox** [comment]
It seems not to be a issue of the core. so i think you can close it. i also have a workaround for my usage. i opened a thread here https://forums.modx.com/thread/100731/trouble-with-json-output for further discussions.

**Comment by bezumkin** [comment]
@mopox I believe you need to update Tickets components. It is the [very old issue](https://github.com/bezumkin/Tickets/blob/94462227fcea2d43ef2f1e7db088c9c2012cce0b/core/components/tickets/elements/plugins/plugin.tickets.php#L38).

**Comment by mopox** [comment]
haha, thank you. that solved the issue for me. i removed tickets. i just was fiddling around with that. it is runing as expected now. thx
