### ISSUE TITLE
No files match the specified filter

### ISSUE THREAD

**Issue by soydemadrid** [modxcms/revolution#13131]
### Summary
Hi I hope you don't mind me also opening a bug here, although this seems an issue with the Gallery module, I'm not sure if it is the gallery or something in modx that needs a fix?

I recently upgraded to Ubuntu 16.10, but the problem is it uses php7 and mysql 5.7, everything seems to work well except when I try to view my Gallery albums there are no longer any images within them.

Just the error "No files match the specified filter."

I'm running modx 2.5.1 if anyone can please help? This is what is in my error log, it looks like an issue with xpdoobject.class.php:

> (ERROR @ /home/public_html/core/xpdo/om/xpdoobject.class.php : 240) Error 42000 executing statement: 
> Array
> (
>     [0] => 42000
>     [1] => 1055
>     [2] => Expression #13 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'siteusername.AlbumItems.rank' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
> )

**Comment by Mark-H** [comment]
This does sound like something specific to Gallery.

**Comment by OptimusCrime** [comment]
Indeed. This is not core related.

**Comment by Jako** [comment]
Please post the issue here https://github.com/modxcms/Gallery
