### ISSUE TITLE
modRestService and empty XML tags

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13132]
### Summary

Bug or feature: Empty XML tags are converted into empty arrays in _xml2array method.
### Step to reproduce

POST/PUT an empty tag to the modRestService
### Observed behavior

The value is converted into an empty array.
### Expected behavior

I would suggest, that it should be converted into null or into an empty string. But that's a design decision.

**Comment by pixelchutes** [comment]
Do we have any knowledge of internal logic currently relying on this behavior?

**Comment by Jako** [comment]
I haven't. With the current code it is not possible to update a record value by put with an empty value using the default put method. The value would contain `Array`. 

Those values have to be handled by a beforePut method

```
    public function beforePut()
    {
        foreach ($this->object->_fields as $fieldname => $field) {
            if (is_array($field) && empty($field)) {
                $this->object->set($fieldname, '');
            }
        }
        return true;
    }
```

**Comment by pixelchutes** [comment]
Do you have an example model (field/data type) this can be tested with? Looking to reproduce / verify, though I've only ever used JSON w/ modRestService.

**Comment by pixelchutes** [comment]
I was able to verify this report using a `modRestController` and an XML payload.

Updating via `PUT` using XML with empty string definitely is converting to `Array`. This does **not** happen when using JSON payloads, which appear to be functioning as expected.

My vote is that this is a bug 🐛
