### ISSUE TITLE
New Category option duplicating view of elements

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#13136]
### Summary
Elements are duplicated in the tree view when creating a new category via context menu.

### Step to reproduce
Right-click on a template in the tree. Select 'New Category' and type in the category name. When you click save you will see the categories in the tree are duplicated below the template you opened the context menu on. The duplicated elements are effectively treating the selected element as the top of the hierarchy.

### Observed behavior
As you can see in the screenshot, the templates are duplicated. The template I right-clicked on in the picture is "VideosDetailTemplate". Thankfully, the duplicated elements are not saved, they disappear after refreshing. 
![screenshot from 2016-09-28 15-56-43](https://cloud.githubusercontent.com/assets/5160368/18905370/62fbd8e8-8595-11e6-8b36-72eea5333f43.png)

### Expected behavior
The elements shouldn't be duplicated in the tree view.
### Environment
MODX 2.5.1

**Comment by rtripault** [comment]
@digitalpenguin thanks for the report.
In case you could test the proposed fix, it would be cool to now if it solves the issue for you too!
Many thanks

**Comment by digitalpenguin** [comment]
Hmmm it still seems to be happening for me. After making the edit to modx.tree.element.js I manually deleted all the cache but is still occurring. 
Can anyone else give it a try?

**Comment by rtripault** [comment]
Do you have `compress_js` activated ? If so it could be a "minified" version is used instead of the modified file.
Also, clearing your browser cache could help

**Comment by digitalpenguin** [comment]
It was the browser cache. Sorry! :P 
Yes I can confirm it's now fixed!

**Comment by OptimusCrime** [comment]
Close?

**Comment by rtripault** [comment]
Should automatically be closed when related PR will be merged

**Comment by OptimusCrime** [comment]
Ah. Sorry. Did not see the pull. We'll wait for that, then.
