### ISSUE TITLE
Broken search results in Extras Manager

### ISSUE THREAD

**Issue by Fosterscape** [modxcms/revolution#13143]
### Summary

Broken search results in Extras Manager when searching for the term "**ajax**".
Other search terms are working.
### Step to reproduce

Login to manager, go to menu item "Extras -> Installer".
Click "Download Extras" button.
Type "ajax" into search field and hit "enter" on keyboard.
### Observed behavior

Results page shows "**Page 1 of 68**", click the "Next Page" arrow button. You are taken to "**Page 2 of 2**". Clicking "Previous Page" arrow button **doesn't** take you anywhere, you are left on Page 2.
### Expected behavior

The results page should only show "Page 1 of 2" on first results page and then once going to Page 2 clicking "Previous Page" should take you back to Page 1.
### Environment

This was tested on two different installs of 2.5.0 (one on local server and one with separate web hosting company) and on one install of 2.5.1 on modxcloud.com

I think the issue may relate to the listing for the "AjaxForm Extra", maybe something in the extra's description causing it.

**Comment by Jako** [comment]
It is maybe fixed, could you check this?

**Comment by Fosterscape** [comment]
Yes, this is now fixed and working properly.
