### ISSUE TITLE
Missing file connectors/security/login.php prevent from renewing session

### ISSUE THREAD

**Issue by vladmirx** [modxcms/revolution#13144]
### Summary
Missing folder /connectors/security/ and file connectors/security/login.php
Both needed to renew session if it is expired during your work in manager.
At this commit file was removed https://github.com/modxcms/revolution/commit/ec21e6f5e0b64aaaaf8e4f390c7f16b1efc82035

### Step to reproduce
Log in to manager, open any resource, delete session cookie and try to save resource.

### Observed behavior
If you submit modal login window, manager will do nothing. Because there is no such file there.

### Expected behavior
With this file, white notify message should popup with text: Session extended!
And you can continue to work.

### Environment
PHP 7.0
MODX Revolution 2.5.1-pl Advanced edition

**Comment by Mark-H** [comment]
That file is not supposed to be needed. Instead the index.php connector should be posted to with the action security/login. That loads up the right logic. It does look like there's an issue, but I don't think your summary has the root cause right.

**Comment by bezumkin** [comment]
@Mark-H But auth window [tries to send action into](https://github.com/modxcms/revolution/blob/07656896542a6b4195f65886fb43eaae366c34d1/manager/assets/modext/widgets/windows.js#L833) `MODx.config.connectors_url + 'security/login.php'`

**Comment by Jako** [comment]
Hey, you have found another bug 👍  Try this change:

```
url: MODx.config.connectors_url,
action: 'security/login'
```

**Comment by pixelchutes** [comment]
Fixed in 5c9e11ac61826c52e022f9e67869a24424265055

**Comment by pixelchutes** [comment]
See previous PR for additional detail, but [connectors/security/login.php](https://github.com/modxcms/revolution/blob/d4ecf6106c2c86e68d44be0c79e0568122492676/connectors/security/login.php) **still exists** as of `2.5.2-dev`, and I cannot seem to reproduce this issue. _(e.g. I can renew session via this file without issue)_

Can you clarify what you mean by "missing folder" for **connectors/security/***? Does that not exist in the 2.5.1-advanced transport file, or are you suggesting it's not properly installed during setup? Have you tried re-running setup / transferring files from the 2.5.1 installer?

Lastly, what is your `compress_js` configured as? Does toggling `compress_js` setting have any effect for you?

**NOTE:** A quick way to test this is to login to the MODX Manager, then delete the PHP session cookie (via Dev tools), then kick of an XHR event, such as expanding a node in the Resource tree (to attempt the MODX registry call) -- this will bring up the login prompt to test extending your session.

**Comment by pixelchutes** [comment]
I can confirm **connectors/security/login.php** will `404` for download distribution installs.

For [Git Installation](https://docs.modx.com/revolution/2.x/getting-started/installation/git-installation) workflow, however, the file exists without issue.
