### ISSUE TITLE
Output modifier "default" does not works.

### ISSUE THREAD

**Issue by mishantrop** [modxcms/revolution#13152]
### Step to reproduce
1. Create chunk "Hello".
2. ```<span>website: [[+anchor:default=`[[+href]]`]]</span>```.
3. ```[[$Hello? &anchor=`` &href=`https://modx.com`]]``` returns nothing.

### Environment
MODX 2.5.1-pl
Apache 2.4 x64
PHP 7.0.8 x64

**Comment by Jako** [comment]
Sorry but your example works fine in 2.5.0, 2.5.1 and 2.5.2 prerelease.

**Comment by mishantrop** [comment]
Sorry, it works on fresh installation. Apparently, MODX upgrade (2.4 to 2.5) was incorrect.
Fixed.
