### ISSUE TITLE
Missing Documents in Resource Tree

### ISSUE THREAD

**Issue by jac31885** [modxcms/revolution#13155]
### Summary

Some Documents are missing in the Resource Tree even though they are in the database and no issue with them.
### Step to reproduce

I simply re-ordered a document and the one above went missing. 
### Observed behavior

No errors occured, just some documents not showing
### Expected behavior

Re-order and show all documents still. 
### Environment

MODX Revolution 2.5.1-pl (traditional), PHP Version 5.5.38, mySQL 5.6.28, Chrome

**Comment by OptimusCrime** [comment]
Impossible to reproduce. Could be caused by some ajax call that failed. As far as I can know, there are no issues with documents that are found in the database, and are somehow not displayed.

**Comment by Jako** [comment]
Could you make a screencast for this. Maybe it will be more clear after viewing it.

**Comment by pixelchutes** [comment]
This sounds like you may have (inadvertently) created orphaned resource(s)? As Jako stated, it's not entirely clear, so a video or some other information would be necessary to properly diagnose.

One recommendation could be to run: **Manage > Clear Cache > Refresh URIs** While it doesn't sound entirely related, I do know that it can resolve issues with Resources not showing in the tree depending on the state of your cache and how your hierarchy changes were performed (e.g. If you did it direct in db, this step can be used to synchronize things). Watch the console log output for any possible issues...

My gut says you may end up having to manually identify and fix parent/relationships in the database.

**Comment by Jako** [comment]
It could be also an UTF-8 sign in the pagetitle (other fields are thinkable too) and a not UTF-8 capable database setting. Then a whole (sub-)tree would be missing.

**Comment by digitalpenguin** [comment]
I remember this same thing sometimes happening back in 2.2.x but haven't seen it since 2.3.
The only way to fix it was setting the parent manually in the db.

**Comment by Mark-H** [comment]
Closing due to lack of feedback and no steps to reproduce.
