### ISSUE TITLE
Empty directory shows arrow in file tree

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#13166]
### Summary
An empty directory also has an arrow indicating the folder contains files, even though the directory is actually empty.

### Step to reproduce
- Create an empty directory
- Refresh the tree

### Observed behavior
An arrow is shown indicating the directory contains files.

Before clicking to expand directory:
![screen shot 2016-10-31 at 14 38 03](https://cloud.githubusercontent.com/assets/7802465/19855920/5724f256-9f77-11e6-8b07-64e9087bff76.png)

After clicking to expand directory:
![screen shot 2016-10-31 at 14 38 49](https://cloud.githubusercontent.com/assets/7802465/19855936/77ec25cc-9f77-11e6-9667-50a8e93ac7c8.png)

### Expected behavior
The arrow should not be shown, because the directory does not contain any files.

### Environment
- MODX: MODX 2.5.1-PL traditional

**Comment by Mark-H** [comment]
I think the technical reason for this is that the tree does not yet know that the directory is empty. Without recursively going through directories just to list one level, I don't think this can be easily fixed, unless someone else has any good ideas?

**Comment by Oetzie** [comment]
I'm going to try and fix this today.

**Comment by OptimusCrime** [comment]
I agree with @Mark-H . I did look at this and that was the problem I encountered too. Unless @Oetzie has a good plan to fix this I'd recommend closing this off as wontfix.

**Comment by OptimusCrime** [comment]
Closing as wontfix. In order to fix this issue we need an additional check for every directory to determine if it is empty or not. The I/O overhead for this operation is not worth the minimal gain of removing a few unnecessary arrows.

@modxbot close
