### ISSUE TITLE
Can't install/update two packages with install options 

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13169]
### Summary
Can't install/update two packages with 'Setup Options'. The second package is never marked as installed and the first (previous) package is installed again.

### Step to reproduce
Update two packages with 'Setup Options' without reloading the workspaces manager page.

### Observed behavior
The install console repeats the install messages of the first (previous) package. The second package is not marked as installed/updated even when the installer console finishes without an error.

### Expected behavior
The second package should be installed/updated and marked as installed.

### Environment
MODX 2.5.1

**Comment by Mark-H** [comment]
I've seen this behaviour from time to time, but never made the link with the installation options. I think whenever it happens, it seems to show information for the 2nd extra, however the console shows it's installing the first extra.

**Comment by Jako** [comment]
It happens also during installing two packages with install options.

**Comment by sottwell** [comment]
A package without install options installs fine after one with options.

At any point after installing a package with options, the previous one with options will be re-installed, even if you’ve installed other packages in between.

**Comment by Alroniks** [comment]
Merged https://github.com/modxcms/revolution/pull/13557
