### ISSUE TITLE
Refactor setUserGroups/addUsers methods

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13160]
### Summary

The setUserGroups/addUsers methods in [`core/model/modx/processors/security/user/update.class.php`](https://github.com/modxcms/revolution/blob/5405d07138292ba53392c4661d6336dc2332effa/core/model/modx/processors/security/user/update.class.php#L163-L185) and [`core/model/modx/processors/security/group/update.class.php`](https://github.com/modxcms/revolution/blob/5405d07138292ba53392c4661d6336dc2332effa/core/model/modx/processors/security/group/update.class.php#L69-L86) should be refactored: They should not remove the user from all existing groups and add it afterwards to all belonging groups. This is ineffective and does not allow to have the OnUserAddToGroup event triggered for adding the user only to new groups.
### Expected behavior

The methods should load the existing groups, look if each existing group is in the new groups and remove it otherwise. The remaining extisting group has to be cross checked with the new group (array_diff) to detect the new groups the user has to be added to. Then the user has to be added only to the new groups.
### Environment

MODX 2.5.1 and below

**Comment by pixelchutes** [comment]
NOTE: There is also a separate processor that gets triggered when adding a User to a User Group via the ACL page.

**Comment by alroniks** [comment]
It seems PR was merged and issue solved. So closing it.
