### ISSUE TITLE
Snippet params include backticks in values when followed by more than one space

### ISSUE THREAD

**Issue by k9dug** [modxcms/revolution#13168]
I have a simple custom snippet with max two params. If there is more than one space following the param the output param value includes the backticks in the string. This occurs whether there is only one param or if there is a following param, eg:

```
[[!Calculator? &packages=`packageOne, packageTwo, packageThree`  ]]
```

or
```
[[!Calculator? &packages=`packageOne, packageTwo, packageThree`  &mode=`full`  ]]
```

outputs:
```
`packageOne, packageTwo, packageThree`
```

When there is one space, the backticks are not included, eg:

```
[[!Calculator? &packages=`packageOne, packageTwo, packageThree` ]]
```
or
```
[[!Calculator? &packages=`packageOne, packageTwo, packageThree` &mode=`full` ]]
```

outputs:
```
packageOne, packageTwo, packageThree
```

I have checked that the backticks and spaces are all correct and the latter not hidden characters etc.

I would expect the backticks to never be included.

MODX revo 2.5.1
PHP 5.3.3
mysql 5.1.73

**Comment by Jako** [comment]
I have updated your text and surrounded the snippet calls by three backticks.

Does this happen when you insert the snippet call in a RTE or also in a nomal textarea?

**Comment by k9dug** [comment]
Thanks Jako, I tried to comment my backticks to make them show..

OK, good point, and the answer is that it only seems to happen in the RTE (TinyMCE), not in the normal text area.

BTW I have seen this issue before, back around v2.3.5.

**Comment by Jako** [comment]
You maybe have some invisible spans in that rte code.

**Comment by k9dug** [comment]
All checked and pretty sure it's clean.

**Comment by Jako** [comment]
Any other inivisble chars like non breaking spaces?

**Comment by Mark-H** [comment]
Sounds like a RTE induced bug - please reopen if it does turn out to be something in the MODX core.
