### ISSUE TITLE
File Manager does not check extension of renamed file

### ISSUE THREAD

**Issue by Pathologic** [modxcms/revolution#13178]
### Summary
File Manager does not check extension of renamed file, so it's possible to upload php file as image and then rename.

### Step to reproduce
1. Create file image.jpg:
```
<?php
phpinfo();
```
2. Upload via File Manager
3. Rename to image.php

### Observed behavior
image.jpg turns to image.php

### Expected behavior
File renaming should be aborted if new file does not have extension allowed by Media Source or system settings. 

### Environment
MODX 2.5.1

**Comment by Pathologic** [comment]
Temporary fixed with plugin:
```
$e = $modx->event;
if ($e->name == 'OnFileManagerFileRename') {
    $properties = $source->getProperties();
    $allowed = empty($properties['allowedFileTypes']['value']) ? $modx->getOption('upload_files') : $properties['allowedFileTypes']['value'];
    if (!empty($allowed)) {
        $ext = strtolower(pathinfo($path, PATHINFO_EXTENSION));
        $allowed = explode(',',$allowed);
        if (!in_array($ext,$allowed)) unlink($path);
    }
}
```

**Comment by Jako** [comment]
Good catch! 👍

**Comment by Pathologic** [comment]
Not my catch, that was mentioned in modx.pro community.
