### ISSUE TITLE
Unable to view previous versions of packages: sortby works incorrect with the IF operator

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#13179]
### Summary
xPDOQuery::sortby stops to work with conditions like this 

> $c->sortby('IF(modTransportPackage.release = "" OR modTransportPackage.release = "ga" OR modTransportPackage.release = "pl","z",IF(modTransportPackage.release = "dev","a",modTransportPackage.release)) DESC','');

It's because of [this](https://github.com/modxcms/revolution/blob/37973d2a2cdc29ca6f4894f2f9e787e33650844c/core/xpdo/om/xpdoquery.class.php#L402-L405).

### Step to reproduce
Open any Extra which has the old versions and go to the tab "Uploaded Versions". There will be nothing.

### Environment
MODX version 2.5.2-pl.

**Comment by Mark-H** [comment]
Fixed per #13190 in 2.5.3
