### ISSUE TITLE
pclzip.lib.php problem when installing MODX 2.5.2 on PHP 7.0.x based system

### ISSUE THREAD

**Issue by FBachofner** [modxcms/revolution#13188]
### Summary
The final step when running  /site/setup/  shows a warning at the very top of the browser window (above the MODX "chrome"):

`Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor in /home/my_obscured_path/MODX/2.5.2/core/xpdo/compression/pclzip.lib.php on line 190`

### Step to reproduce
Happens at last setup step after upgrading any site from MODX 2.5.1 to 2.5.2 on a PHP 7.0.8 system

Presumably this will happen on new MODX 2.5.2 installs on PHP 7.x as well.

### Observed behavior
MODX manager (or site) is then able to start and seems otherwise unaffected.

### Expected behavior
This error should not happen.  PHP 7.0 is now mainlined.  The pclzip.lib.php needs to be updated.

### Environment
MODX: 2.5.2 (advanced)
PHP: 7.0.8
nginx: 1.11.6
mysql: MariaDB 10.1.19
browser: Firefox 50.0

**Comment by yuka123** [comment]
On line 190 function PclZip($p_zipname) need changing to function function __construct($p_zipname)

and then below that function we need to add the backwards compatibility for old PHP users something like:

function PclZip($p_zipname)
    {
        self::__construct();
    }

Can you apply those changes and test if this fixes?

**Comment by Jako** [comment]
> The pclzip.lib.php needs to be updated.

It seems uptodate, but the version is very old: http://www.phpconcept.net/pclzip/release-notes
So we have to patch this on our own.

**Comment by Jako** [comment]
Did you change something in the initial MODX system settings to activate pclzip? Because @opengeek asked this here: https://github.com/modxcms/xpdo/pull/79#issuecomment-193349441

**Comment by OptimusCrime** [comment]
What is pclzip used for? I thought it was a user implementation of ZIP functionality? MODX already requires the zlib extension according to the [server requirements](https://docs.modx.com/revolution/2.x/getting-started/server-requirements).

Could it be possible to remove this outdated lib (if this is indeed the case).

**Comment by opengeek** [comment]
This is based on the presence of the zip extension, not zlib. On systems that do not have the zip extension enabled, PclZip takes care of allowing package management operations to be performed, as well as other zip/unzip operations. This should be externalized in the `3.x` branch if an appropriate composer library can be identified, but I will update this for now in `2.x`.

**Comment by FBachofner** [comment]
@Jako:

> @FBachofner Did you change something in the initial MODX system settings to activate pclzip?

Not that I am aware of.  Where would you expect I would have changed something like this?  Some text file or within the MODX Manager?

Pretty much all of my MODX installations are fairly "vanilla" except that I use the "advanced" download and _always_ separate the core folder out of the public document root.  I also habitually change directory names for "connectors" etc.

Also, I use MariaDB instead of MySQL and NGINX instead of Apache.  [This platform seems just slightly  "rare" compared with other MODX users.]

**Comment by opengeek** [comment]
@FBachofner there is a system setting called `archive_with` that if set to Yes (true) will enable the use of PclZip instead of ZipArchive from the PHP Zip extension. Some servers do not have the PHP Zip extension enabled and this setting allows users to still extract extras packages using PclZip instead.
