### ISSUE TITLE
Category when сreating new template/tv/chunk/plugin/snippet 

### ISSUE THREAD

**Issue by legiero** [modxcms/revolution#13187]
### Summary
When you create an element category becomes category with lowest id

### Step to reproduce
New installation of MODX 2.5.2 (no packages)
Create 1 category
Create 1 element ( template/tv/chunk/plugin/snippet )

### Observed behavior
When you create an element category becomes category with lowest id

### Expected behavior
When you create an element category must be "None", 0.

### Environment
MODX version: 2.5.2, Testing on modxcloud.com (2.5.1 normal behavior

UPD. 02/12/2016
When i use this buttons the category is "None" and link is "a=element/template/create"
![image](https://cloud.githubusercontent.com/assets/1620809/20840331/f0341ac8-b8c0-11e6-9ae7-abf6a101ece2.png)

When i use right click on element category the category is the category with lowest id and link is "a=element/template/create&category=0"
![image](https://cloud.githubusercontent.com/assets/1620809/20840475/6d446644-b8c1-11e6-91c3-64ec495a0c43.png)

If i use "a=element/template/create&category=**id**" where **id** is negative or non-existent, then the category of the element becomes empty as the expected behavior.

**Comment by himurovich** [comment]
+1 The same issue detected on 2.5.2 modxcloud too

**Comment by ychelovek** [comment]
+1

**Comment by OptimusCrime** [comment]
The behavior changed between versions? That is really weird. I'll check it out.

**Comment by natedin** [comment]
+1

**Comment by Marduh** [comment]
+1

**Comment by Mark-H** [comment]
Fixed per #13207
