### ISSUE TITLE
Installation on sqlsrv/mssql shows the connecting to mysql was successful

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#13195]
### Summary
Installing MODX on a server with mssql/sqlsrv. Database connection step. It shows a success message that mentions mysql, not sqlsrv/mssql. 

### Step to reproduce
See above

### Observed behavior
See above

### Expected behavior
Say sqlsrv, not mysql

### Environment
IIS server with MS SQL database

**Comment by Ibochkarev** [comment]
@Mark-H In connection with the agreed Dropping support for SQL Server in 3.0, I suggest closing this issue =)

**Comment by Mark-H** [comment]
Agreed!
