### ISSUE TITLE
Modx 2.5.2 Cache issue?

### ISSUE THREAD

**Issue by vJazziee** [modxcms/revolution#13200]
### Summary
Every so often, the backend displays a white screen or the resources/elements don't appear. The only fix is to clear the cache folder in the FTP and hope you get more than 5 minutes before the next crash.

### Step to reproduce
It randomly happens with this version of Modx.

### Observed behavior
White screen/resource tree not loading.

### Environment
MODX version: 2.5.2-pl.
Apache: 2.0
Mysql: 5.7.14
PHP: 5.6

**Comment by OptimusCrime** [comment]
Anyting in the error log(s)? Either MODX's or PHP's?

**Comment by vJazziee** [comment]
I'll post the logs when it happens again.

**Comment by vJazziee** [comment]
There isn't a MODX error log appearing in the backend > reports or in the cache folder. There doesn't seem to be any logs being generated anywhere when the system blanks out, I will disable the modx cache to see if that fixes the issue for now.

**Comment by skazhikadyadya** [comment]
@vJazziee, you disable MODX cache? After it your problem solved?

**Comment by vJazziee** [comment]
@skazhikadyadya No it didn't, I'm still having the issue.

**Comment by skazhikadyadya** [comment]
@vJazziee maybe I can help you. Update your TinyMCE for latest version (4.3.4 imho).

**Comment by Mark-H** [comment]
Are you on a cloud server, perhaps?

Some environments have issues with file locking, aka flock. There are some possibilities to work around that, including setting `use_flock` => false in the $config_options in your configuration file?

**Comment by Mark-H** [comment]
Suspecting environment issue, that `use_flock` should help with. Closing for now.
