### ISSUE TITLE
Duplicate Resource Alias Alert Doesn't Display unless Document Tab Visible

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#13202]
There is a user experience issue in MODX 2.5.2 where, when saving a new resource, if you are in template variables tab when you click save and there is an error on the document tab (duplicate alias) it will not display the notification to the end-user.  I think there should be an additional alert directly under the save button.

**Comment by markwillis82** [comment]
This happens on all of the required fields. We should switch the active tab to where the error is.

Forced URI is another example.

**Comment by OptimusCrime** [comment]
Tried to implement a solution for this problem. I've experienced it multiple times myself without knowing what the heck is going on. I am pretty sure there are other issues similar to this that may be hidden from the users, but I could not remember any while I was coding. Feel free to check my solution out.

**Comment by OptimusCrime** [comment]
There is a PR for this posted now. It also solves similar problems if you have any errors in the TV section.
