### ISSUE TITLE
Wrong behaviour of output filter if resource have no such a field 

### ISSUE THREAD

**Issue by manicko** [modxcms/revolution#13203]
### Summary
The output filters for the non-existent resource fields does not work as expected

### Step to reproduce
Put the code  [[*newField:default=`DEFAULT`]] in a Modx resource content or template or chunk. (Be sure that resource do not have the field with this name).

### Observed behavior
Returns nothing.

### Expected behavior
The expected output is DEFAULT

### Environment
MODX 2.5.1

This makes impossible the usage of the same chunk for Modx resources and migx tables.
E.g. if I have the field MyField in Migx table and I'm using  the same chunk for both Migx and  Modx resources with the code below [[*MyField:default=`DEFAULT`]]
I expect that for Modx resources I get otput as DEFAULT  and for Migx I expect to see the value of the field MyField.  Though for Modx resources the output is empty.

**Comment by pixelchutes** [comment]
At first I thought this may be related to #11969, but after re-reading this I'm not thinking it is.

I can't say I've ever tried using MODX TV tags (for non-existent TVs) combined with output modifiers... That said _(and MIGX aside)_, I was not able to reproduce this in core.

### Example:

```
[[*abc:default=`xyz`]]
```
> Non-existent TV: `abc`

### Expected output (per the above comments)

Returns nothing.

### Actual behavior

Outputs:
> xyz

**Comment by OptimusCrime** [comment]
I tested this as well and I got the same output as @pixelchutes 

@manicko perhaps this is an issue tied to MIGX? I do not use this extra, so I am not sure how it works, or just what it does. Or perhaps you have changed the default MODX parser to pdoTools or something? Either way I am pretty sure this is not a MODX core bug.

**Comment by manicko** [comment]
No, you can reproduce this on the fresh installation
Please check: 
[https://c0849.paas1.fra.modxcloud.com/manager/?a=element/template/update&id=1](url)

Log: Admin
Pass: 123654789

**Comment by manicko** [comment]
![1](https://cloud.githubusercontent.com/assets/1097057/20845441/2842ad02-b8d6-11e6-961c-c936a018dbf1.png)

![2](https://cloud.githubusercontent.com/assets/1097057/20845442/28441782-b8d6-11e6-89b2-a31180dde2d2.png)

**Comment by OptimusCrime** [comment]
I can confirm that this is happening when building from source.

**Comment by OptimusCrime** [comment]
@manicko Thank you for reporting this. Sorry about the confusing reports earlier. This is indeed an error as far as I can tell. I've opened a PR that attempts to solve this issue.

**Comment by pixelchutes** [comment]
Wow, so I still can't figure out why I was not able to reproduce? I tested on 2.5.2, what's the catch?

**Comment by Mark-H** [comment]
@manicko Please don't post manager logins publicly 😱 I've edited your comment to take out that information; if anyone still needs it, please contact each other via a slightly more secure channel (email or slack or something)

**Comment by OptimusCrime** [comment]
@pixelchutes Really? Well, browsing the code it makes sense that this fails. Not sure why it did not earlier. I had a clean git installation without any extras or anything and I got the same results.

@Mark-H I think it was just a dummy site running on an isolated modx cloud. Not sure how much you can do with login in a scenario like that.

**Comment by Mark-H** [comment]
Upload files to spread malware is one thing that comes to mind. Security
101: manager access is for trusted people only. Even if there's nothing in
the site, it's still inviting random people scouring the web to do bad
things.

Op 3 dec. 2016 3:00 a.m. schreef "OptimusCrime" <notifications@github.com>:

**Comment by OptimusCrime** [comment]
Sure, but I thought these things lived in a container that you could just kill with the push of a button, like a droplet at Digital Ocean or Docker. But yeah, I see your point.

**Comment by manicko** [comment]
@Mark-H Thank you for the comment, same as OptimusCrime I was thinking that there are no any risk in this. Thank you for changing the post.

**Comment by Mark-H** [comment]
Fixed for 2.6.
