### ISSUE TITLE
Cannot delete elements when reviewing (removable only from tree)

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#13211]
### Summary
In Revo there is currently no way to Delete an element from the edit/update page, a pretty important feature missing from early MODX Evo days. This pattern is already established for Resources in Revo, for example.

### Step to reproduce
1. Browse to the update page for any element (TV, Chunk, Snippet, etc)
2. After reviewing or deciding it is safe for removal, you cannot easily remove it from the system. (Missing <kbd>Delete</kbd>)

### Observed behavior
To delete an element, today you are forced to:

1. (optional) Reveal the tree
2. Jump to Elements tab
3. (optional) Expand the [TV|Chunks|Snippets|Plugins] Tab
4. (optional) Know (and find) the Element's Category container
5. (optional) Expand the container
6. Browse through results to (hopefully) find the correct element
    - _(Especially important if lots of results or similar naming convention in effect)_
7. Right-click
8. Select **"Delete [TV|Chunk|Snippet|Plugin]"**

### Expected behavior
There should be a way to delete an Element from the edit page. A <kbd>Delete</kbd> button, just like for Resources.

Not only is this far more convenient, it's a safer way to purge content from the system since you can actively be reviewing the very Element you're considering for deletion.

### Environment
MODX 2.5.2-dev

**Comment by achterbahn** [comment]
Deleting a resource this way just marks the resource as deleted in the tree view. The resource itself stays open on the right side.
As for elements there is no functionality to mark them as deleted. Discussed here #764. 
When adding a delete button, what should happen after deleting the element? Loading the dashboard? 
As of writing this: wouldn't it be convenient to show a grid when clicking on elements category headers instead of collapsing/expanding it? There is the little arrow to perform this action.

**Comment by pixelchutes** [comment]
Flagging an Element for deletion (e.g. Trash) would indeed be a cool feature, and welcomed addition.

This issue is more about not restricting Element deletion to the tree, requiring knowing a potential Category, and having the right collapsed state + right-click / context menu knowledge.

There should simply be a <kbd>Delete</kbd> button on the page you edit Elements from, similar to Resources. Should Element "trashing" feature be introduced in the future, saidn button could easily be adapted to support, but for now, it should mimic the current supported behavior (immediate deletion), just as it works from the Elements tree.

**Comment by pixelchutes** [comment]
Classes by cc5ed4b
