### ISSUE TITLE
Fatal error crashes manager for nonexistent Chunks

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#13210]
### Summary
When attempting to edit a Chunk using an ID that doesn't exist, MODX Manager crashes with a 500 fatal error instead of handling it better, like it does with Template Variables or Resources.

### Step to reproduce
1. Browse to Chunk edit page for ID that doesn't exist, e.g. https://domain.com/manager/index.php?a=element/chunk/update&id=9999999999

### Observed behavior
500 Fatal error when browsing to nonexistent Chunk ID.

> NOTICE: PHP message: PHP Fatal error:  Call to a member function get() on null in manager/controllers/default/element/chunk/update.class.php on line 134

### Expected behavior
Still usable manager with a more appropriate error message (like that of TVs and Resources):

![better_error_handling](https://cloud.githubusercontent.com/assets/352182/20904626/a7e456c2-bafd-11e6-9e82-4001e0a6a8e1.jpg)

_^ Like this, but for Chunks._

### Environment
MODX 2.5.2 / PHP 5.6

**Comment by Mark-H** [comment]
Fixed per #13226
