### ISSUE TITLE
Duplicating a context with a a lot of resources may trigger php memory error

### ISSUE THREAD

**Issue by kinaz** [modxcms/revolution#13217]
### Summary
Duplication of a very "fat" context (a lot of resources) may not complete triggering a php memory error.

### Step to reproduce
Command line:
php modcli.php context/duplicate key=en newkey=fr

### Observed behavior
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 81 bytes) in CUSTOM_PATH/core/xpdo/xpdo.class.php on line 1385

### Expected behavior
The duplication of the context should complete succesfully.

### Environment
MODX Revolution 2.1.16-pl, PHP 5.3.10

**Comment by OptimusCrime** [comment]
Pretty sure this is the problem: https://github.com/modxcms/revolution/blob/2.x/core/model/modx/processors/context/duplicate.class.php#L107-L126

Because they are all fetched at the same time, a new instance of the object is created for each of them. This becomes a memory issue if you have too many objects to keep alive at the same time.

**Comment by FerX** [comment]
change line 108:
 `$resources = $this->modx->getIterator('modResource',array(`

**Comment by kinaz** [comment]
I did, issue is still present.

It's probably related to the number of TVs.

**Comment by FerX** [comment]
@kinaz, please test my pull request #13285.

**Comment by Mark-H** [comment]
@kinaz Have you had a chance to see if the pull request in #13285 resolves the issue you were having? I'm inclined to merge it anyway, even if it doesn't, but would be good to get some verification from you that it also solved the problem :)

**Comment by kinaz** [comment]
@Mark-H @FerX I'll try and give it a go tomorrow!

**Comment by kinaz** [comment]
Duplication completed with no issue

**Comment by OptimusCrime** [comment]
Sounds like a fix then. Thank you for confirming, @kinaz :)

**Comment by Mark-H** [comment]
Should be fixed in 2.6 then. There might be further improvements possible per https://github.com/modxcms/revolution/pull/13285#issuecomment-278787220 but this one should save a lot of memory already.
