### ISSUE TITLE
getObject() without criteria crashes collection methods work.

### ISSUE THREAD

**Issue by spectrum48k** [modxcms/revolution#13218]
### Summary
getObject() without criteria causes nesting level error for collection methods.

### Step to reproduce
1) clear cache for 'someClass' db objects
2) $modx->getObject('someClass') and $modx->getCollection('someClass') after that.

### Observed behavior
execution of php script stops with "nesting_level_error"..
![trace_screen](https://cloud.githubusercontent.com/assets/17526628/21256298/28ffacdc-c37a-11e6-9970-f85489171c99.png)

debugging results:
in case of no cache files created for db objects of 'someClassKey':
->getObject('someClassKey'); and ->getCollection('someClassKey') (or ->getMany('someAliasOfClassKey')) after that
shoots to cache file with same md5 prefix, but collection methods need different nesting of arrays inside cache files. This causes wrong recursion and nesting level error when collection loads from cache. So, ->getObject() without unique criteria is bad practice for current xPDO caching principle of version that I  use (MODX Revolution 2.3.3-pl (traditional)).

### Expected behavior
expected single instance of  'someClass' object and collection array of  'someClass' objects in results.

### Environment
MODX version MODX Revolution 2.3.3-pl (traditional)

**Comment by OptimusCrime** [comment]
Pretty sure this should be reported in the xPDO repository instead?

**Comment by spectrum48k** [comment]
moved to xPDO repository issues
