### ISSUE TITLE
File Unzip feature broken

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#13223]
### Summary
the Files unzip feature fails due to an invalid path, the site base path is shown as "undefined"

### Step to reproduce
Upload a zip file, then from the context menu choose Unzip File.

### Observed behavior
Error message
![screen shot 2016-12-21 at 16 39 21](https://cloud.githubusercontent.com/assets/1073780/21393265/62b174ee-c79c-11e6-8c06-c7b99c37c3db.png)

### Expected behavior
Unzip the file in the same location

### Environment
MODX Cloud, Revolution 2.5.2

**Comment by igorsuhinin** [comment]
Hi @sottwell,

Thanks for your report.
Could you please check again if all is okay? I've accidentally uploaded the wrong file on modx.com.
Hopefully it should work now.

**Comment by Bruno17** [comment]
I can confirm that issue

**Comment by sottwell** [comment]
I believe this is related to #3170 and #3180

**Comment by Bruno17** [comment]
it is.
https://github.com/modxcms/revolution/blob/b9ce93658cbfd8846f89714e0658eeb0129f559c/manager/assets/modext/widgets/system/modx.tree.directory.js#L604

**Comment by OptimusCrime** [comment]
Fixed in #13238

**Comment by OptimusCrime** [comment]
@modxbot close
