### ISSUE TITLE
new resource in root level of resource tree gets moved to a folder, all resources on the root level disappear (show_in_tree = 0)

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/revolution#13230]
### Summary
When new resource in root level of resource tree gets moved to a folder, all resources on the root level disappear (show_in_tree = 0)

### Step to reproduce
Create a new resource via the main create resource button above the resource tree.  Move it per drag n drop into a resource folder.  Find the resource and edit it.  

### Observed behavior
The resource tree refreshes and all resource in the root level disappear.

### Environment
MODX version 2.5.2,  Google Chrome was tested , Strato Power Plus L shared hosting

**Comment by sonicpunk** [comment]
Manager report shows following:

![screen shot 2017-01-03 at 16 07 41](https://cloud.githubusercontent.com/assets/447453/21612015/a42c63ce-d1cf-11e6-948a-44b60f7718a2.png)

No errors are logged in MODX after it happens

**Comment by sottwell** [comment]
Cannot reproduce.

**Comment by sonicpunk** [comment]
I will make a screencast of it shortly

**Comment by sonicpunk** [comment]
Here is a link to the screencast.  

https://protonet.seda.digital/public_links/15axHP6fxmy6ECsTqU-WOQ

I can reproduce this every time following these steps.

**Comment by OptimusCrime** [comment]
What does the php error log say about the internal error?

**Comment by sonicpunk** [comment]
the php error log shows nothing for that instance.  Just errors regarding a wordpress installation residing on the same webspace.

**Comment by OptimusCrime** [comment]
Any fatal/internal errors should write to the log unless this is not turned on. We do not have enough information to investigate this bug/problem further as it currently is.

As @sottwell said, she could not reproduce this, and neither can I. This leads me to belive that there is something specific to your setup, to your environment that crashes this. We are unable to know just what that is unless we have the PHP error log.

**Comment by Mark-H** [comment]
I've not been able of reproducing this either. Maybe related to a plugin of sorts.
