### ISSUE TITLE
Filemanager doesn't mark selected file

### ISSUE THREAD

**Issue by himurovich** [modxcms/revolution#13234]
### Summary
Filemanager doesn't mark selected file, "Filesystem" folder remains closed.

### Step to reproduce
In the backend sidebar click on "Files" then open "Filesystem" and select any file. 

![template variable_ new tv _ modx revolution - mozilla firefox 2017-01-04 12 32 14](https://cloud.githubusercontent.com/assets/2815640/21657302/a7f39334-d2d2-11e6-95be-26d07e465d4e.png)

### Observed behavior
"Filesystem" still closed, file wasn't marked as selected. 

![edit file_ ht access _ modx revolution - mozilla firefox 2017-01-04 12 33 29](https://cloud.githubusercontent.com/assets/2815640/21657299/a7f1ca22-d2d2-11e6-9bac-4dae312c284e.png)

### Expected behavior

It would be nice if filemanager shows what file is currently opened, moreover "Filesystem" would also be active (open)

Here are some helpful screenshots where you can find element's classes which could solve the issue.

![firebug - edit file_ ht access _ modx revolution 2017-01-04 12 35 08](https://cloud.githubusercontent.com/assets/2815640/21657300/a7f23246-d2d2-11e6-97b1-97213140dc80.png)

![firebug - edit file_ ht access _ modx revolution 2017-01-04 12 46 12](https://cloud.githubusercontent.com/assets/2815640/21657303/a7f59a08-d2d2-11e6-931d-380992bd6cf1.png)

It is important to say that the same (current object selection within tree) works correctly for "Resources" and "Elements" tabs entities.
Also I've noticed that 2.5.1 version was able to mark as "opened" Filesystem folder icon, unfortunately file was also non-selected there. 

![edit file_ styles css - google chrome 2017-01-04 22 45 29](https://cloud.githubusercontent.com/assets/2815640/21657301/a7f331e6-d2d2-11e6-9e99-b482c3a9abd5.png)

### Environment
MODX Revolution 2.5.4-pl on MODXCloud

**Comment by guyinpv** [comment]
I observed this behavior but only when no subfolders were expanded. (on 2.5.6-pl)

TEST: 
With NO subfolders expanded, click some file in the root folder like htaccess or index.php. 
Now simply expand ANY folder in the sidebar, just expand it, don't even select a file under it. Now click on a root-level file again. This time the sidebar remains open.

It seems to be collapsed when a file is opened, only when no subfolders are expanded. Strange.

**Comment by Ibochkarev** [comment]
Fixed #15228 

@modxbot close
