### ISSUE TITLE
Suggestions to guide new users to generally changed default settings

### ISSUE THREAD

**Issue by benguthrie** [modxcms/revolution#13237]
### Summary
When someone creates a new install of MODX, there is some default content that is configured that should really be changed, and it's not intuitive where for users new to MODX.

Examples of how this could be accomplished:
- The page title is by default "MODX Revolution" for any site. My suggestion would be to change that setting to "Page Title - Change in System Settings --> site_name"
- It could also be nice to have a section added to the start menu with links internal to the site manager that could be used to direct people to the sections populated by default they could & should update to make the site theirs:
  - Default Page title
  - Default 'from' address
  - Add your "favicon.ico" to the "Files" root

![image](https://cloud.githubusercontent.com/assets/231012/21695241/92bba39a-d34e-11e6-83bd-1928a3fe5804.png)

### Step to reproduce
Anyone unfamiliar with MODX would need these on starting.

### Observed behavior
It takes realizing that all your pages' titles are "MODX Revolution" to realize that you'd want to change this setting.

### Expected behavior
Goal: make onboarding and setup as straightforward as possible.

### Environment
Relevant as of MODX 2.5.2

**Comment by Mark-H** [comment]
Additions/changes to the default content are welcome, but I don't really understand what you're suggesting to change exactly - is that the right screenshot?

The default content is here https://github.com/modxcms/revolution/blob/2.x/setup/templates/base_resource.tpl and the default template is here https://github.com/modxcms/revolution/blob/2.x/setup/templates/base_template.tpl

**Comment by benguthrie** [comment]
Ok, so specifically, my suggestion would be to:
- change the starting *site_name* value to *Page Title - Change in System Settings --> site_name*
- Add to the "Getting Started" section things like: 
  - change your default site name '<a href="manager/?a=system/settings">System Settings</a> and search for *site_name*
  - repeat for favicon.ico, etc.

**Comment by Mark-H** [comment]
I'd be happy with that addition to the default content, but that's an awfully long site name. Not sure if that's really improving things.

**Comment by benguthrie** [comment]
Just had some side conversations with @jaygilmore . It sounds like the startup experience of using MODX Cloud skips some of the installation options that you'd normally get doing a fresh install.

So this issue is largely created by that process skipping some steps.

I'll close this.

Thanks for your attention.
