### ISSUE TITLE
Modx setup redirect to http, and make it impossible to install modx with ssl

### ISSUE THREAD

**Issue by carlo-13** [modxcms/revolution#13241]
### Summary
Modx setup redirect to http, and makes it impossible to install modx with ssl

### Step to reproduce
Make a fresh install of Modx.
Upload the htaccess file below.
And try to run the setup in ssl

### Observed behavior
The first page is https, but when I go to "/setup", it keeps redirecting to http.

### Expected behavior
The website should remain https during the process

### Environment
MODX 2.5.4
PHP 7.0.14
Database 5.5.50-MariaDB
Server app CGI/FastCGI
System Linux

### Htaccess file

[htaccess.pdf](https://github.com/modxcms/revolution/files/689434/htaccess.pdf)

**Comment by shamarin** [comment]
And what's the problem?! It's not modx bug. You just didn't done redirect via .htaccess file. Uncomment this code in you .htaccess file:
'''
RewriteCond %{SERVER_PORT} !^443
RewriteRule (.*) https://example-domain-please-change.com/$1 [R=301,L]
'''

**Comment by Jako** [comment]
It is a bug and the rewrite is a workaround.

**Comment by OptimusCrime** [comment]
Odd. I am pretty sure I have ran successful setups on my development server, which uses strict HTTPS. Let me give it a try

**Comment by manicko** [comment]
this refers to an issue #13259 

There should be massive checks in the htaccess 

e.g.
RewriteCond %{SERVER_PORT} !^443
RewriteCond %{HTTPS} !=on
RewriteCond %{HTTP:X-Forwarded-Proto} !https [NC]
RewriteCond %{HTTP:Front-End-Https} !on
RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

and the massive checks in the config core
