### ISSUE TITLE
bug in option: level

### ISSUE THREAD

**Issue by rkm432** [modxcms/revolution#13247]
It's NOT Work:
```
[[!Wayfinder? &startId=`0`&level=`1` !]]
```

It's WORK:
```
[[!Wayfinder? &level=`1`&startId=`0` !]]
```

In first case level not work, output all levels. In second case level limit work good. I think it's bug.

MODX Revolution 2.5.4-pl
wayfinder-2.3.3-pl

**Comment by sottwell** [comment]
This is not a core MODX issue.

The tags for an uncached snippet call would be [[!...]] Sometimes it helps to structure snippet calls like this:

[[!Wayfinder?
  &startId=`0`
  &level=`1`
]]

**Comment by Jako** [comment]
Susan is right, it is not a MODX core issue (and not a Wayfinder issue too). Please use the right snippet call syntax and please use spaces (or new lines) between the snippet properties.
