### ISSUE TITLE
Resource Class function get() on array PHP fatal error

### ISSUE THREAD

**Issue by kisfelix** [modxcms/revolution#13257]
### Summary
PHP Fatal error:  Call to a member function get() on array in /[server document root]/manager/controllers/default/resource/resource.class.php on line 152

### Step to reproduce
Just create a new resource / edit an existing one.

### Observed behavior
Redirect right back to the site's homepage.

### Expected behavior
Create/edit a resource form in manager.

### Environment
MODX 2.5.4

**Comment by Mark-H** [comment]
Got tinymce installed? Update it to the latest version.

**Comment by kisfelix** [comment]
Damn it, that works.
