### ISSUE TITLE
Titletag of Manager Login

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#13252]
### Summary
Every MODX Manager Login page has the same title. This is a problem if you have a list of bookmarks to all of your MODX managers...

![screenshot 2017-01-13 09 32 24](https://cloud.githubusercontent.com/assets/667315/21923284/7c61f5ce-d973-11e6-8522-2e6442619a2b.png)

### Step to reproduce
Add a bookmark to your bookmark list on any browser

### Observed behavior
All managers have the same title: 

**MODX CMF Manager Login**

The title changes once you have been logged in:

**Dashboard | example.de**

### Expected behavior
Include [[++site_name]] in the manager title. Make the new title as short as possible, so it will always be meaningful even if some of the title is not displayed.

**Login | [[++site_name]]**

### Environment
Any environment.

**Comment by sottwell** [comment]
It's very easy to customize the login page. Simply clone a new login template in a custom theme folder, such as  manager/templates/mytheme/security/login.tpl. I find it easiest to simply clone the entire manager/templates/default/ folder.

Then set the System Setting `manager_theme` to your custom theme, in this case `mytheme`. Edit the login.tpl file as desired.

An example of the possibilities https://sottwell.com/manager/

**Comment by pepebe** [comment]
Hi Mrs Ottwell,

thanks for your reply. It's embarrassing to admit that this never crossed my mind.

I'm using customised manager logins a lot and I recommend everyone to do so. It makes our clients feel much more at home. :)

That being said, I really believe, that adding the [[++site_name]] to the login page title should be the default behaviour.

I can imagine circumstances where one might want to have an anonymous login page. For edge cases like that, there could be a system setting to override this behaviour.

**Comment by Mark-H** [comment]
PR sent #13254

**Comment by OptimusCrime** [comment]
While the idea is good I think "Bookmarks have identical names" is a bad reason. In most browsers you can customize the bookmark name to anything you'd like.

However, arguing the the login page should contain the name of the site is a more fair concern to raise.

**Comment by pepebe** [comment]
@Mark-H Thanks for your PR!

@OptimusCrime - Your right. Complaining about bookmarks was far too specific. I guess I was just too annoyed about my handcrafted list of 40+ bookmarks with useless titles. ;)

P.S. I'm so happy that this was solved! Free virtual drinks for everyone!
