### ISSUE TITLE
[Feature Request] Resource Tree Contextual Menu Customization

### ISSUE THREAD

**Issue by EkoOne** [modxcms/revolution#13255]
Having a mechanism for customizing the contextual menu of the Resource Tree would be useful, something similar to how Manager Customization works.

For example, being able to hide the Settings tab in the Quick Update modal.

Let's say I use Manager Customization to hide the entire Settings tab (or just a single field within Settings) in the main Manager window for a specific user-group. It's relatively quick and easy to configure. Great.

But it's all moot because the user can simply launch Quick Update and have complete access to everything I just hid which pretty much qualifies as an "exercise in futility".

As BobRay suggested on the forum there might be a way to hide it with a plugin and CSS, but that seems rather ugly considering that so much can already be done with Manager Customization.

Soooo, any chance for a native mechanism? Or am I just outta luck?

**Comment by Mark-H** [comment]
First you mention the context menu, and then the resource window. Which one is it going to be? ;)

**Comment by EkoOne** [comment]
I was able to achieve the desired effect using permissions which in the end seems a much quicker and simpler solution than the Manager Customization route I was trying to explain above.

Let's close this one. Sorry for any unintended confusion.
