### ISSUE TITLE
SSL on apache + nignix not working

### ISSUE THREAD

**Issue by manicko** [modxcms/revolution#13259]
### Summary
Hi, just faced the problem that my hosting uses the chain of two servers, thus the SSL is installed on the front end server only and it does not return the $_SERVER['HTTPS'] variable and the $_SERVER['SERVER_PORT'] is set to  80.
Thus all checks in the core config file are missing and site returns the http protocol for the base_url/site_url.

Instead hosting is returning _SERVER['HTTP_FRONT_END_HTTPS'] === 'on'. Serfing the web I found that other hostings are using $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' which could be used as a reference too.

### Step to reproduce
The easies way is to set $_SERVER['HTTPS'] to nothing and the $_SERVER['SERVER_PORT']  to  80.
The hard way is to use shared hosting with chain of servers apache + nignix,

### Observed behavior
Thus all checks in the core config file are missing and site returns the http protocol for the base_url/site_url.

### Expected behavior
Should return the correct https

### Environment
MODX version 2.5.4, apache+nginx 

I suggest to add more robust function to config checking the ssl:
 ```
if(!function_exists('is_https')){
 function is_https($https_port=443)
  {
    if (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) === 'on')
    {
      return TRUE;
    }
    elseif (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
    {
        return TRUE;
    }
    elseif (isset($_SERVER['HTTP_FRONT_END_HTTPS']) && $_SERVER['HTTP_FRONT_END_HTTPS'] === 'on')
    {
      return TRUE;
    }
    elseif (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] === $https_port)
    {
      return TRUE;
    }
    return FALSE;
  }
}
```

And chage the  $isSecureRequest as follows:
```
if(defined('PHP_SAPI') && (PHP_SAPI == "cli" || PHP_SAPI == "embed")) {
    $isSecureRequest = false;
} else {
    $isSecureRequest = is_https($https_port);
}
```

**Comment by manicko** [comment]
And the htaccess

```
    RewriteEngine On
    RewriteCond %{SERVER_PORT} !^443 [OR]
    RewriteCond %{HTTPS} !=on [OR]
    RewriteCond %{HTTP:X-Forwarded-Proto} !https [NC] [OR]
    RewriteCond %{HTTP:Front-End-Https} !on 
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

**Comment by OptimusCrime** [comment]
The two request fields you are relying on here are non-standard: https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields

I am not sure if this is a good idea. I also find it very weird that your host does not state that https is turned on like almost every single piece of software would expect.

**Comment by Mark-H** [comment]
I don't think it's that uncommon @OptimusCrime - reverse proxies or CDNs/platforms like cloudflare have their own connection with the server which isn't always over HTTPS. To the origin server the request looks like HTTP, unless you check for additional headers that indicate the upstream request was HTTPS - HTTP_X_FORWARDED_PROTO is pretty common in my experience.

@manicko Have you tried setting the link_tag_scheme system setting to https to force MODX to generate HTTPS urls? That, plus your https tweak, should be sufficient to get things to work without core patches.

**Comment by manicko** [comment]
Hi Mark, actually, setting link_tag_scheme to https was the first thing I've tried. It didn't help, and that is why I've finished modifing core config. 

The reason is simple the url is generated in the cor config basing on the $isSecureRequest variable "'ve tweaked in the above code.
here is the original code
```
$https_port=443;
if(defined('PHP_SAPI') && (PHP_SAPI == "cli" || PHP_SAPI == "embed")) {
    $isSecureRequest = false;
} else {
    $isSecureRequest = ((isset ($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) == 'on') || $_SERVER['SERVER_PORT'] == $https_port);
}
if (!defined('MODX_URL_SCHEME')) {
    $url_scheme=  $isSecureRequest ? 'https://' : 'http://';
    define('MODX_URL_SCHEME', $url_scheme);
}
```

Thus if $_SERVER['HTTPS']) = null and $_SERVER['SERVER_PORT']  is 80 the check fail.

**Comment by OptimusCrime** [comment]
There is a system setting where you can chose between http and https. Does that have any effect?

**Comment by manicko** [comment]
>There is a system setting where you can chose between http and https. Does that have any effect?

server_protocol? I put it server_protocol=https

I do not know what it does but it had not had any effect in my case

**Comment by meshkov** [comment]
My method of solving this problem:
In the file core/config/config.inc.php change the site url from http to https and in the system settings setting change the server_protocol to https  and clear the cache.
In core/config/config.inc.php line:
if (!defined('MODX_URL_SCHEME')) {
    $url_scheme=  $isSecureRequest ? 'https://' : 'http://';
    define('MODX_URL_SCHEME', $url_scheme);
}
change to:
if (!defined('MODX_URL_SCHEME')) {
    $url_scheme=  $isSecureRequest ? 'http://' : 'https://';
    define('MODX_URL_SCHEME', $url_scheme);
}

**Comment by zaigham** [comment]
@meshkov You can just add `url_scheme` to system settings and valid values for it are: `https://`, `http://`, `//`

**Comment by manicko** [comment]
This will not help

**Comment by christianseel** [comment]
@manicko what you need to do is to set your `site_url` to something like `https://mysite.com/` in your system OR context settings. This will force MODX to generate all URLs with HTTPS! We're using this on all our projects.

Furthermore, I agree `HTTP_X_FORWARDED_PROTO` is quite common and could be added.

#modxbughunt

**Comment by manicko** [comment]
could you please make the PR changing the core/config/config.inc.php as follws:

1) Add function is_https
`
if(!function_exists('is_https')){
function is_https($https_port=443)
 {
   if (isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) === 'on')
   {
     return TRUE;
   }
   elseif (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
   {
       return TRUE;
   }
   elseif (isset($_SERVER['HTTP_FRONT_END_HTTPS']) && $_SERVER['HTTP_FRONT_END_HTTPS'] === 'on')
   {
     return TRUE;
   }
   elseif (isset($_SERVER['SERVER_PORT']) && $_SERVER['SERVER_PORT'] === $https_port)
   {
     return TRUE;
   }
   return FALSE;
 }
}
`
2)chage the $isSecureRequest:
 `
if(defined('PHP_SAPI') && (PHP_SAPI == "cli" || PHP_SAPI == "embed")) {
    $isSecureRequest = false;
} else {
    $isSecureRequest = is_https($https_port);
}

`

**Comment by vguna** [comment]
Today I ran into the same issue. My config is Apache with https in front. Then ProxyPass to a docker container where a apache+modx is running in. Although the request comes in with https, the returned html page contains a base url with http. HTTP_X_FORWARD_PROTO sounds like it's the way to go.

Tomorrow I will take a look at `site_url`. But that would mean, that the site will always run in https and that the client won't be able to decide.

**Comment by vguna** [comment]
Ok I got it running now. I'm setting the url to `//mysite.com` - so in theory it should handle http/https as well transparently. But I'm still voting for the header, since currently I have to configure/setup that config "manually" after setup :(.

**Comment by OptimusCrime** [comment]
Sent a PR. I rewrote some of the code.

**Comment by alroniks** [comment]
Fixed in 3.x https://github.com/modxcms/revolution/pull/15487
