### ISSUE TITLE
editor_css_path System Setting is ignored on MODX 2.5.2

### ISSUE THREAD

**Issue by pmacswebteam** [modxcms/revolution#13251]
### Summary
After upgrading from 2.5.1 to 2.5.2, it was discovered that the editor_css_path System Setting is being ignored.

### Step to reproduce
Create custom editor stylesheet
Add stylesheet path to editor_css_path System Setting
View rich text editor (Using CKEditor)

### Observed behavior
ALL custom styles are being ignored

### Expected behavior
Custom styles should render

### Environment
MODX 2.5.2

**Comment by OptimusCrime** [comment]
Do you have installed an extra for this? I am pretty sure editor_css_path is not a MODX core system setting.

**Comment by OptimusCrime** [comment]
I double checked, it is a part of the default installation as far as I can tell. However, it is up to the extras to honor this setting. I'll take a look at what's happening.

**Comment by pmacswebteam** [comment]
The RTE package we're using is CKEditor. The editor_css_path system setting seemed to be working fine in MODX 2.5.1 with this package. Thanks for looking into this!

**Comment by Mark-H** [comment]
This should be fixed when you upgrade to 2.5.4, the `_path` in that setting was getting filtered by a slightly over ambitious security fix in 2.5.2.
