### ISSUE TITLE
Quick Create Weblink Modal Not Working

### ISSUE THREAD

**Issue by neoneddy** [modxcms/revolution#13266]
### Summary
Quick Creating a weblink doesn't seem to be working currently.

### Step to reproduce
Right + Click parent resource, quick create new weblink

### Observed behavior

Looks like this

![image](https://cloud.githubusercontent.com/assets/819083/22350179/65bba800-e3d8-11e6-83fb-723467a31f75.png)

### Expected behavior
It should work normally, no screenshot currently, but you guys know.

### Environment
MODX 2.5.4, NGINX, Multicontext, Content Blocks .  Testing in Chrome

**Comment by mrhaw** [comment]
It works on my localhost xampp, but generates this error in Chrome:

`Uncaught TypeError: Cannot read property 'style' of undefined
    at Ext.Element.setStyle (ext-all.js:21)
    at MODx.window.QuickCreateResource.resizeWindow (modx.jsgrps-min.js:4)
    at h.Event.fire (ext-all.js:21)
    at doResizeEvent (ext-all.js:21)
    at b (ext-all.js:21)`

**Comment by Jako** [comment]
Have you done something else before quick create? Since it works fine here.

**Comment by Mark-H** [comment]
I witnessed this in Chrome as well earlier today, but didn't keep track of the exact steps and am not able of reproducing when I try it now.

**Comment by syts88** [comment]
Cannot reproduce on MODX 2.5.5. So can be closed? #modxbughunt

**Comment by rtripault** [comment]
So let's close...

Feel free to comment/reopen if needed.
Thanks
