### ISSUE TITLE
Installer crashes

### ISSUE THREAD

**Issue by iamdave210** [modxcms/revolution#13263]
### Summary
The install crashes with the following error:
`mod_fcgid: stderr: PHP Fatal error:  Can't inherit abstract function modDashboardWidgetInterface::render() (previously declared abstract in modDashboardFileWidget) in /var/www/clients/client2/web5/web/core/model/modx/moddashboardwidget.class.php on line 117`

All checks on the summary page are passed and all sql modes are off but clicking 'install' results in a 500 and only 27 tables are created in the database.

### Environment
MODX 2.5.4, apache 2.4.7, mysql 5.5.53, php 5.5.9

**Comment by sottwell** [comment]
This was a bug reported and supposedly fixed some time ago https://bugs.php.net/bug.php?id=43200

**Comment by sottwell** [comment]
What database charset are you trying to use? MODX won't install with utfmb4.

**Comment by iamdave210** [comment]
I just left it as the default latin1 and latin1_swedish_ci. Once I tried changing it to utf8 and utf8_unicode_ci and that resulted in a different error:
`[Wed Jan 25 15:42:08.806198 2017] [fcgid:warn] [pid 10683] (104)Connection reset by peer: [client 149.149.130.135:59388] mod_fcgid: error reading data from FastCGI server, referer: https://centerhillmarina.com/setup/index.php?action=summary
[Wed Jan 25 15:42:08.806300 2017] [core:error] [pid 10683] [client 149.149.130.135:59388] End of script output before headers: index.php, referer: https://centerhillmarina.com/setup/index.php?action=summary`

**Comment by Mark-H** [comment]
That error is not making sense at all.. from what I can tell, all classes extending modDashboardWidgetInterface have a render method and none are abstract other than the interface class. Do you have any custom widgets of sorts?

I also don't think the php bug posted by Susan is related. Despite its name, modDashboardWidgetInterface is an abstract class, not an interface.

**Comment by iamdave210** [comment]
This is a vanilla install. I just downloaded the latest stable release from modx.com, extracted and ran setup.

**Comment by Mark-H** [comment]
This is the code it complains about

``` php

/**
 * A file-based widget that returns only the content of its include.
 * 
 * @package modx
 * @subpackage dashboard
 */
class modDashboardFileWidget extends modDashboardWidgetInterface {
    public function render() {
        return $this->content;
    }
}
````

I don't see a problem.

**Comment by goldsky** [comment]
@iamdave210 try to raise the PHP's memory limit up

**Comment by iamdave210** [comment]
It looks like the underlying issue may have been the database using utf8mb4 charset. Changing it to utf8 seems to have fixed it.
