### ISSUE TITLE
Improve reporting of bad links so they are easier to find

### ISSUE THREAD

**Issue by opengeek** [modxcms/revolution#13265]
### Summary
Currently, invalid link tags or calls to makeUrl with non-existent resources log a generic error that makes it impossible to find the source. This should be improved so finding broken links is easier.

### Step to reproduce
Create a link tag, e.g. `[[~0]]`, or call the `$modx->makeUrl(0)` function with a resource id that does not exist.

### Observed behavior
No information is logged for link tags and makeUrl calls only provide a generic error message that is not useful for finding the broken link.

### Expected behavior
Log information about the location of the broken link.

### Environment
ALL environments.

**Comment by matdave** [comment]
One thing that helps (at least me anyway) is injecting URI into the xpdo.class.php _log statements starting around line 2069

```
        switch ($target) {
            case 'HTML' :
                echo '<h5>[' . strftime('%Y-%m-%d %H:%M:%S') . '] (' . $this->_getLogLevel($level) . $def . $file . $line . ') <br/>URI('. $_SERVER['REQUEST_URI'] .')</h5><pre>' . $msg . '</pre>' . "\n";
                break;
            default :
                echo '[' . strftime('%Y-%m-%d %H:%M:%S') . '] (' . $this->_getLogLevel($level) . $def . $file . $line . ') URI('. $_SERVER['REQUEST_URI'] .') ' . $msg . "\n";
        }
```

However, the issue first needs to be addressed for logging errors when no link can be created during parsing `[[~0]]`.

**Comment by pixelchutes** [comment]
Thank you for logging this one, Jason, and @matdave for the recommendation to help troubleshoot it. Would ❤️ seeing something implemented in core to improve this.

One scenario to result in ```[[~0]]``` is if you have a template that uses:

```html
<a href="[[~[[*parent]]]]">Parent Link</a>
```

...but you end up rendering it on a Resource already at the root of the site.

**Comment by Mark-H** [comment]
#13268 was merged

**Comment by labr1005** [comment]
@pixelchutes was right. This floods my error log.

For example this in a template
```
[[*parent:is=`15`:then=`
    <a href="[[~[[*parent]]]]">Back</a>
`]]
```
throws this error for every resource on the root level as the parent is 0 and the inner part gets parsed anyway.

Same with
```
[[+whatever:notempty=`
    <a href="[[~[[+whatever]]]]">Whatever</a>
`]]
```
and so on...

**Comment by Bruno17** [comment]
@labr1005 
try it this way:
```
[[[[*parent:is=`2`:or:is=`3`:or:is=`4`:then=`$makeLink? &id=`[[*parent]]` `]]]]
```
the chunk makeLink:

```
<a href="[[~[[+id]]]]">Back</a>
```

**Comment by OptimusCrime** [comment]
Is this possible:

```
[[[[*parent:is=`2`:or:is=`3`:or:is=`4`:then=`~[[+id]]`]]]]
```

?

**Comment by Bruno17** [comment]
this is possible, but it would miss the ```<a href="....``` part
that's why I suggested to use a chunk

**Comment by labr1005** [comment]
IMO the log level should be lowered to INFO just like done here for contexts.

Issue #13278
PR #13305
