### ISSUE TITLE
Honor value of "server_protocol"

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/revolution#13269]
### Current state

Right now, as of MODX 2.x, the setting `server_protocol` does not do anything (?). The setting has the values `http` and `https`. Anyone would expect the choice here to be honored by MODX, but it does not. The actual protocol is fetched automatically by evaluating the request which is done by inspecting various server settings and values.

### Potential

Sometimes you want to set the value absolute, and sometimes the value is not evaluated correctly by MODX because of various shared host solutions (se relevant issues). Sometimes you also know that you are either always serving everything over http, or you know that everything is served over https.

### Idea

- Add a new value (default) that is automatic. Perhaps just call it `automatic` (?).
- The automatic value evaluates as best as it can if the request is http or https. This value is needed for sites that is served over both http and https.
- http value should NEVER allow to serve over https.
- https value should NEVER allow to serve over http.

### Relevant issues

#13259 and perhaps more

**Comment by sottwell** [comment]
What does Wayfinder et. al. use to determine how to generate full URLs? If it just uses the current automatic settings, you'd end up with all kinds of mixed up URLs because of caching.

**Comment by OptimusCrime** [comment]
The automatic setting it how MODX does things today, as you can not force either http or https automatically. MODX determine if the request is a secure one by doing this: https://github.com/modxcms/revolution/blob/fbf126690f6ce903faeaeb9f1d958211fc2203c9/core/docs/config.inc.tpl#L49-L57

**Comment by gadgetto** [comment]
+1 for honoring **server_protocol** setting to override automatic fetching of protocol

**Comment by christianseel** [comment]
Isn't that what `site_url` is doing right now? If you set that as a system or context setting to something like `https://mysite.com/`, MODX will generate all URLs with https. That's what we're doing at our projects…

From my perspective there is no reason to change the `server_protocol` behavior.

#modxbughunt

**Comment by OptimusCrime** [comment]
After I opened this issue i learned that `server_protocol` does nothing. I should in fact be removed.

What I actually wanted was `link_scheme` which defines if links should be created with or without SSL.

**Comment by OptimusCrime** [comment]
I have learned that we need to specify the protocol much earlier than when we have the system settings available. This means that this approach is essentially worthless. A better configuration file which is better at identifying SSL and reverse proxies would be better. I have a PR for this ready in #13594. While it does not solve the problem completely, it should make some edge cases work out of the box.

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/why-my-source-files-get-http-instead-of-https/4208/3
