### ISSUE TITLE
Make duplicating Context Resources optional when duplicating Context

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/revolution#13277]
### Summary
It should be optional to duplicate the Resources under a Context when duplicating the Context either from the tree or as suggested in #13276. Add checkbox to the dialog to confirm choice to duplicate Resources.

### Step to reproduce
Trigger duplicating a Context from the Resource Tree. Dialog pops up with options. It should be another unchecked checkbox on the dialog box to confirm that they wish to duplicate the Resources as well.

### Observed behavior
Currently, it is not possible to optionally duplicate Resources when duplicating a Context. The Resources will be Duplicated.

### Expected behavior
![duplicate_child_resources](https://cloud.githubusercontent.com/assets/378199/22664363/bf14de38-ec86-11e6-91d6-fec453e9ad1a.png)
Allow the user to choose to duplicate or not duplicate the children Resources of a Context. Add the checkbox input with the text: "Duplicate child Resources". It may also make sense to disable the `Preserve duplicated resources alias` and `Preserve duplicated resources menu index` checkboxes until the `Duplicate child Resources` has been checked. 

### Environment
Current MODX Revolution Managers +

**Comment by joeke** [comment]
I'll look into this. #modxbughunt

**Comment by Mark-H** [comment]
Included in 2.6
