### ISSUE TITLE
Take FilesMatch standard into htaccess

### ISSUE THREAD

**Issue by funkyduke** [modxcms/revolution#13273]
Sometimes there are problems with fonts and icons when switching between http(s)://website.com and http(s)://www.website.com (so with or without www). (Mostly Firefox and Chrome)

Yes, you can set a rewrite-rule, but if you use routing this is not always possible or the best solution.

Maybe the code below can be standard in the htaccess-file? It works for me.

```
<IfModule mod_headers.c>
   <FilesMatch "\.(ttf|ttc|otf|eot|woff|font.css|css)$">
   Header set Access-Control-Allow-Origin "*"
   </FilesMatch>
</IfModule>
```

**Comment by OptimusCrime** [comment]
I've never had this problem with my installations, usually redirecting from www to the site without www. As this is a problem for just some users I'd much rather not have it in the htaccess file by default.

**Comment by funkyduke** [comment]
@OptimusCrime indeed, I see in the new 2.5.5. that the redirect is rewriten, so good case.

Case closed.
