### ISSUE TITLE
Feature request: ad possibility to "lock" single packages in package management to prevent accidentally updating

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13272]
### Summary
Sometimes you need to modify core code of installed add-on. Reason: add-on isn't maintained for a long time and needs fixes/changes, customized add-ons, ...
Therefore it would be nice to have a kind of "locking" feature for single packages **to prevent accidentally updating**.

Those "locked" packages could also be excluded from update checks.

### Step to reproduce
-

### Observed behavior
-

### Expected behavior
Add checkbox to package row to enable prevention of package updates.

### Environment
-

**Comment by sottwell** [comment]
That's the wrong way to do it. If you need to modify an add-on's core code, clone it with a different name, and modify the clone. Never modify core code or supplied elements of an add-on. Always use your own customized versions.

**Comment by OptimusCrime** [comment]
I agree with @sottwell . The need to avoid upgrading (by accident) is only relevant when you have done something that in my opinion is wrong. The correct approach is either to fork the package and apply your changes, OR you install it as a local package. Local packages are not upgradeable.

I'm -1 this idea.

**Comment by zaigham** [comment]
You can achieve this by removing the provider from package.

**Comment by Jako** [comment]
Removing the provider could be done by clicking on the 'View Details' button of a package. On the following page, you could set the provider to none.

Forking the package and installing an own version is sometimes a bit overkill, if you just need a small patch before it is available in the package provider version.

Closing this as solved.
