### ISSUE TITLE
[Feature] Provide an 'opt-out' option in the installer to not include the default template code and resource content.

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#13275]
A few versions back a new template design was added (instead of the blank page) to new installs of MODX. 
I completely understand the reason for doing so, and it's great for a newbie to MODX to be able to see something immediately after a successful install. However, for anyone else it means removing it as the first step for each install.

What does everyone think about having a checkbox during the install process that would allow this default content/template to not be included?
It could be opt-out so it's ticked by default.

**Comment by Mark-H** [comment]
It's a single (1) template with a single (1) resource with content. Both of which existed before, they were just a lot simpler. Assuming you at some point have to edit both of those, and MODX can't function without them, I disagree it's an extra step to take. If anything, a checkbox during the setup is an extra step.

**Comment by digitalpenguin** [comment]
Sure, I understand. 
I suppose what I'm getting at is that a barebones template was provided before with the only thing being some standard head tags and only the content tag in the body. This was great! It allowed me to jump straight in.
Recently, the first thing I do each time is open the resource, delete the content, save the resource, open the template, select and delete everything between the style tags, select and delete everything between the body tags except for the content tag, save the template.

For me at least, unticking a box during the install process would be preferable to this. 

I'm sure everyone has their own process for removing the content and I know it would be faster to simply delete the template and create another but I like having the head tags to start with.

If I'm the only one who feels this way it's not a problem. It's just a tiny issue anyway ;)

**Comment by christianseel** [comment]
I agree to Mark and say it's the same work if you replace the 1 resource with your own content (plus template) VS. adding your content to the 1st resource (and template). There is no benefit as you would still get a (empty) resource and template when disabling that requested checkbox.

Voting for close!
#modxbughunt

**Comment by digitalpenguin** [comment]
Alrighty, looks like I'm out-voted. :)
Closing!
