### ISSUE TITLE
xpdo 2.5.3-pl not working $query->groupby()

### ISSUE THREAD

**Issue by andchir** [modxcms/revolution#13287]
### Summary
xpdo 2.5.3-pl not working $query->groupby().

### Step to reproduce
Make query with $query->groupby() no results.

### Environment
modx 2.5.1pl, xpdo 2.5.3-pl

**Comment by Mark-H** [comment]
MODX 2.5.1? Update immediately, you're vulnerable to some serious issues.

Also if this is the bug I think it is (hard to tell if you don't provide at the very least the query you're building) that would also be resolved in 2.5.4+.

**Comment by andchir** [comment]
Thank you for your response. I updated to MODX 2.5.5. But the problem is not solved.

**Comment by OptimusCrime** [comment]
@andchir Can you provide the actual code that does not work?

**Comment by andchir** [comment]
Example:

~~~
$query = $modx->newQuery('modResource');
$query->select(array('id','parent','pagetitle'));
$query->sortby('pagetitle','asc');
$query->groupby('parent');

$collection = $modx->getCollection('modResource', $query);

var_dump( count( $collection ) );
~~~

If I remove ``$query->groupby('parent');`` - output: int(36)

**Comment by andchir** [comment]
Maybe thi is my local MySQL settings. I have message:

> SELECT list is not in GROUP BY clause and contains nonaggregated column 'modx.modResource.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by Jako** [comment]
You have some STRICT checks enabled in the MySQL/MariaDB configuration.

```
$query->select($modx->getSelectColumns('modResource','modResource','',array('id','parent','pagetitle')));
```

Does this help?

**Comment by andchir** [comment]
I disabled the setting "only_full_group_by" and it solved the problem.
http://stackoverflow.com/questions/23921117/disable-only-full-group-by
You can close this task. Thank you all.

**Comment by OptimusCrime** [comment]
@andchir Reason @Jako asked this is to fix the issue for future incidents. Think we better leave this open until we have fixed this with `only_full_group_by` turned on.

**Comment by Jako** [comment]
@opengeek Maybe that groupby method could trigger a select query by default. This could avoid a lot of MySQL/MariaDB strict issues.

**Comment by OptimusCrime** [comment]
This is not a MODX core related issue. I've opened up a feature request to implement this (referencing this issue too) at modxcms/xpdo#111

@modxbot close
