### ISSUE TITLE
it is not possible Injects css or js via plugin at the login page

### ISSUE THREAD

**Issue by FerX** [modxcms/revolution#13280]
### Summary
it is not possible Injects css or js via plugin at the login page

### Step to reproduce
view file login.tpl 
missing the code:
```{$maincssjs}
{foreach from=$cssjs item=scr}
{$scr}
{/foreach}
```

### Environment
MODX 2.5.4

**Comment by alroniks** [comment]
Closing, as proposed pull request was declined. It means that this task becomes "won't fix".
