### ISSUE TITLE
Duplicating resource folder with hidden children does not ask to duplicate children

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/revolution#13298]
### Summary
Another issue - when you have children that are hidden from the resource tree, like when using the Collections extra for example. Clicking duplicate on the parent resource will not duplicate the children if they are not shown in the resource tree. Also the checkbox option for duplicating children does not show up in the modal.

It seems that duplicating children only works with resources that are actually shown in the resource tree.

Attribute hasChildren=false, even though it technically does have children, just that they are not shown in the tree.

### Step to reproduce
Make a parent resource with children.  Change the children show_in_tree value to 0 in the database. These children resources are no longer shown in the resource tree.

### Observed behavior
Right click on the parent resource.  The checkbox for duplicating the children does not show.

### Expected behavior
Technically the children do exist, therefore I would expect the ability to duplicate them as well.

### Environment
MODX version 2.5.5

**Comment by wuuti** [comment]
Can confirm that. In the ResourceGetNodesProcessor the children count (L376) is only populated with resources not hidden tree (L170). But this value is then used in modx.tree.resource.js (L124) to configure the duplicate modal (window.js), where it is then used to show up the opton "Duplicate children" or not. 
IMHO the option should be visible _always_ if there are any children, regardless of whether they are visible or not. As the processor returned attribute "hasChildren" might be used elsewhere, it would be a good idea to add something like "hasAnyChildren" here, which is then evaluated by the duplicate modal. 
I can also think of a more verbose modal where a checkbox labelled with "Duplicate children (15 total, 3 hidden in tree)", which would warn you then if you dare to duplicate a collection with thousands of children.

**Comment by sdrenth** [comment]
I'm going to try and fix this today.

**Comment by sonicpunk** [comment]
#modbughunt Thanks @sdrenth !  I just added the hashtag so that we can filter it out.  Get those bugs!!!

**Comment by sdrenth** [comment]
I've added a pullrequest which fixes this issue and also adds a child counter next to the duplicate children option:

https://github.com/modxcms/revolution/pull/13322

**Comment by sonicpunk** [comment]
I was thinking that we shouldn't overwrite the current behaviour but maybe instead create a new value that saves the count of all children regardless of the show_in_tree value.  Then we could have a new system setting that would allow the admin to choose which behaviour they would like to have.

**Comment by Mark-H** [comment]
Fixed in 2.5.6

@sonicpunk I can't imagine anyone looking for the behaviour where they can't choose to duplicate resources or not, but feel free to open a new issue if you disagree ;)

**Comment by sonicpunk** [comment]
The point being that if you needed a container with hidden children, whereby you really didn't want the admin to know about the children, then the option to duplicate children would not be needed.

**Comment by goldsky** [comment]
The update creates a bug for GridClassKey
https://github.com/modxcms/revolution/commit/0b50ba3dd60c83b7d1bbde9ca2fda24be09178c2#diff-50fadcbafc5ab9b8bc728f0b088fed88
Care to reopen?
