### ISSUE TITLE
Probably a security issue if you write  

### ISSUE THREAD

**Issue by halvid** [modxcms/revolution#13290]
### Summary
If you write  in the description field of a template element something like `<base href="...." />`, then MODX manager does not redirect correctly because it uses descriptions base url as a base url.

### Step to reproduce
Create or update a template and type in the comment field `<base href="[[!++site_url]]" /`>
Save it

### Observed behavior
Create or edit a document and try to change the template. 
Then once the page reloads you will forced to a wrong url that will include [[!++site_url]]

### Expected behavior
It should reload the page you are loading

### Environment
Latest modx version (also occurred in some versions before )

**Comment by Mark-H** [comment]
@halvid If you have information about a security issue, please email it to security@modx.com.

**Comment by sottwell** [comment]
Doesn't happen to me, neither on localhost nor on a MODX Cloud installation.

**Comment by Mark-H** [comment]
With the updated issue description I can reproduce.

**Comment by Mark-H** [comment]
Fix in #13291.

**Comment by sottwell** [comment]
That's a weird one.

**Comment by halvid** [comment]
My guess is that it has something to do with Ext JS. When we debug the issue we found that when the page reloads the json feed includes the base url tag

**Comment by pixelchutes** [comment]
Fixed in 9310f41
