### ISSUE TITLE
Files Tree images broken when media source above doc root

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#13292]
### Summary
When using media sources that sit above the doc root:
- the preview images, when hovering over the filename in the Files Tree, are broken.
- the preview images in the MODX browser incl. zoom are rendered.

![bildschirmfoto-2017-02-14-um-18 36](https://cloud.githubusercontent.com/assets/1913250/22941359/76df87ca-f2e5-11e6-8b3e-ff4222b0ef4e.jpg)

### Step to reproduce
System setting phpthumb_allow_src_above_docroot Yes.

Create a media source above the doc root with
- an absolute basePath and basePathRelative No.
- an absolute baseUrl and baseUrlRelative No.

### Observed behavior
The preview images, when hovering over the filename in the Files Tree, are broken.

### Expected behavior
The preview images, when hovering over the filename in the Files Tree, should be rendered.

### Environment
MODX 2.5.5
Apache 2.2.29
PHP 7.0.8

**Comment by joeke** [comment]
I'll look into this #modxbughunt

**Comment by Flowan** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by labr1005** [comment]
But there's already a pull request for this.

**Comment by Flowan** [comment]
@labr1005 Oh wow, missed that completely. Thanks, will continue to the next issue :D
