### ISSUE TITLE
Error in parsing nested

### ISSUE THREAD

**Issue by FerX** [modxcms/revolution#13308]
### Summary
I found that when there are complex tags, modx does not correctly parse.

### Step to reproduce
I ran the test with "extra If", but the same bug I encountered with my snippet.

#### Without bugs
```
[[If? &subject=`[[*pagetitle]]`	&operand=`[[*pagetitle]]` &then=`then1 
    [[If? &subject=`[[*pagetitle]]`	&operand=`[[*pagetitle]]` &then=`then2 
	`]]
`]]
```
#### With bugs
```
[[If? &subject=`[[*pagetitle]]`	&operand=`[[*pagetitle]]` &then=`then1 
    [[If? &subject=`[[*pagetitle]]`	&operand=`[[*pagetitle]]` &then=`then2 
        [[If?	&subject=`[[*pagetitle]]` 	&operand=`[[*pagetitle]]` 	&then=`then3`]] 	
	`]]
`]]
```

### Environment
MODX revolution 2.5.5-pl.

**Comment by mrhaw** [comment]
Try this
`[[!If?...
    [[If?...
        [[If?...
	`]]
`]]`
or
`[[If?...
    [[!If?...
        [[!If?...
	`]]
`]]`

**Comment by FerX** [comment]
thanks for the advice.
I tried in different combinations and the solution is put `!` in the first call.

### no BUG 5 level !!!
```
[[!If? &subject=`[[*pagetitle]]`	&operand=`[[*pagetitle]]` &then=`then1 
    [[If? &subject=`[[*pagetitle]]`	&operand=`[[*pagetitle]]` &then=`then2 
        [[If?	&subject=`[[*pagetitle]]` 	&operand=`[[*pagetitle]]` 	&then=`then3
            [[If?	&subject=`[[*pagetitle]]` 	&operand=`[[*pagetitle]]` 	&then=`then4
                [[If?	&subject=`[[*pagetitle]]` 	&operand=`[[*pagetitle]]` 	&then=`then5`]] 	
        `]] 	
        `]] 	
	`]]
`]]

```

**Comment by Jako** [comment]
If you ever use such nested placeholder/snippet call tags, you should prefer to write a snippet instead.
