### ISSUE TITLE
Help pages shows old documentation-link

### ISSUE THREAD

**Issue by gpsietzema** [modxcms/revolution#13309]
**PLEASE NOTE - THIS ISSUE IS FOR CREATING A CONTRIBUTORS VIDEO - PLEASE DO NOT REMOVE/CLOSE/TOUCH IT**

### Summary
?a=help shows rtfm.modx.com link, should be docs.modx.com

### Step to reproduce
Go to the help page and click 'Documentation'.

### Observed behavior
It goes to http://rtfm.modx.com/, which redirects you to https://docs.modx.com/

### Expected behavior
Go straight to https://docs.modx.com/

### Environment
MODX 2.5.5

**Comment by gpsietzema** [comment]
Test comment with #modxbughunt

**Comment by Mark-H** [comment]
Will you post a test fix too? #modxbughunt :trollface:

**Comment by mrhaw** [comment]
This will need to be updated in all lexicons: 
https://github.com/modxcms/revolution/search?utf8=%E2%9C%93&q=rtfm&type=Code

- core/lexicon/en/about.inc.php 

» https://github.com/mrhaw/revolution/commit/91f6981855c386f246dbd19ef82ec111877952cf

**Comment by OptimusCrime** [comment]
@mrhaw As far as I can tell you did not open a PR to this?

**Comment by mrhaw** [comment]
Here it is https://github.com/mrhaw/revolution/pull/1

**Comment by OptimusCrime** [comment]
@mrhaw Ah. You opened a PR in your own repository. You have to open one in this one (modxcms) :)

**Comment by OptimusCrime** [comment]
@modxbot close

I think?
