### ISSUE TITLE
Default TV Values in Form Customization Sets: Database entries not deleted

### ISSUE THREAD

**Issue by umnic** [modxcms/revolution#13312]
### Summary
Default TV Value Entries in Form Customization Sets should be deleted after the fields are cleared via the manager/fc set. This is not the case at the moment (Test in Revo 2.5.2), so each TV will continue to have an empty string as its default value, instead of no default value.

### Step to reproduce
Create a FC Set for creating or updating a resource. Set a default value for any TV. Save the FC Set. Clear the default value, save again.

### Observed behavior
You will still have a database entry in modx_actiondom with the name of the tv (e.g. tv123) and an empty value field. If you created a FC Set for updating a resource, everytime you open the resource, the tv values will jump to the empty default value.

### Expected behavior
If the default value field for a tv is cleared/empty in the FC Set, the corresponding database entry should be deleted (or at least inactive).

### Environment
MODX Revo 2.5.2, later versions not tested at the moment

**Comment by sdrenth** [comment]
I'm going to try and fix this today.

**Comment by sdrenth** [comment]
I can't reproduce this issue, if I clear the default value for a TV for the FC set the record in modx_actiondom table is removed as you would expect. 

Tested with MODX Revolution 2.5.5-pl.

**Comment by alroniks** [comment]
Seems not reproducible.
