### ISSUE TITLE
#modxbughunt Cannot view resources from the tree of a newly duplicated context

### ISSUE THREAD

**Issue by EasterPeanut** [modxcms/revolution#13339]
### Summary
It's not possible to 'view' a resource when you just duplicated a context. Only after clearing the cache.

### Step to reproduce
When you duplicate a context having resources, and you try to 'view' a resource in this new context via the right click context menu, you cannot see the 'view' option.

### Observed behavior
It seems like the cache has to be cleaned first.

### Expected behavior
Usability-wise it would be better to see the 'view' option right after the duplication.

### Environment
2.5.5, nginx 1.4.6, 5.5.53-MariaDB, Chrome Version 56.0.2924.87 (64-bit)

**Comment by digitalpenguin** [comment]
Confirmed. I can reproduce.

**Comment by gernotebenlechner** [comment]
I **can NOT reproduce** this issue on a fresh 2.5.8-dev install #modxbughunt (MAMP, Apache, MySQL) either with (YES) or without (NO) system setting "cache_disabled".

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @gernotebenlechner 

@modxbot close

**Comment by digitalpenguin** [comment]
I can still reproduce this on 2.5.7 - has something changed for 2.5.8-dev?

**Comment by OptimusCrime** [comment]
I can try this out as well
