### ISSUE TITLE
#modxbughunt Items in file trees can only be drag dropped once

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#13351]
### Summary
Directories or files in file trees can only be drag dropped once.

### Steps to reproduce 
Files Tree
- Dir A
  - File
- Dir B
- Dir C

Drag File from Dir A to Dir B.
Drag File from Dir B to Dir C.

### Observed behavior
The complete tree reloads and File is still in Dir B.

### Expected behavior
File should be in Dir C.

### Environment
MODX 2.5.5
Apache 2.2.29
PHP 7.0.8

**Comment by digitalpenguin** [comment]
I can reproduce this issue.

**Comment by labr1005** [comment]
I almost had a fix, but not quite. If some ExtJs expert is interested maybe I can give you a starting point.

**Comment by OptimusCrime** [comment]
@labr1005 Please link your attempt :)

**Comment by labr1005** [comment]
It works, but it looks ugly and doesn't feel right to call refreshNode as this reloads the parent node.

But it sorts the child nodes alphabetically. :)

**Comment by labr1005** [comment]
I'm not sure if ExtJs Tree Sorter is an option, but that's too high for me for now.
http://docs.sencha.com/extjs/3.4.0/#!/api/Ext.tree.TreeSorter

IMO the desired behavior should be

- drop the directory/file
- expand the target directory, if it's closed
- place the directory/file in it's alphabetically correct place inside the target directory
- do the fancy drop animation on the dropped directory/file

**Comment by Finetuned** [comment]
"I'm going to try and fix this today."
