### ISSUE TITLE
settings grid per-page logic is flawed

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#13355]
### Summary
Settings grids are showing 30 results per page unless system setting `default_per_page` is > 30.

### Step to reproduce
Set system setting `default_per_page` to 10, or 20.

### Observed behavior
System setting grids show 30 results per page.

### Expected behavior
Settings grids should show the number of results per page as configured with `default_per_page` setting.

### Environment
All.

**Comment by netProphET** [comment]
Existing "bug" effectively places a minimum of 30 results on the settings grids. Perhaps this is desired? Will changing this be too much of a shock to people?

**Comment by jonleverrier** [comment]
i guess technically it should honour the ```default_per_page``` setting. From a usability perspective I can't imagine the scenario where I would want to lower the limit < 30

**Comment by netProphET** [comment]
Perhaps a better solution would be to have a setting for minimum value on this grid, and it could default to 30. Based on feedback, this doesn't sound too critical, so I'll close.
