### ISSUE TITLE
Critical error when invoking not existant widget

### ISSUE THREAD

**Issue by MarkOdey** [modxcms/revolution#13367]
### Summary

Unable to reach the manager when migrating the database of a production environement to a local developement environement.  It seems I uninstalled some package in my developpement environement that my production database is still tracking thus trying to invoke it. I believe that those dashboard widget should be silently failing inorder to avoid cataclysmic issues.

Fatal error: Call to a member function setNamespace() on null in /var/www/core/model/modx/moddashboardwidget.class.php on line 104

### Step to reproduce

Just uninstall some widget on one side of the platform and override your database again. 

### Observed behavior

Gives you a blank page if debug mode turned off. Give you this error if debug mode turned on.

Fatal error: Call to a member function setNamespace() on null in /var/www/core/model/modx/moddashboardwidget.class.php on line 104

### Expected behavior

The error should be handled so no critical php error fires. And possibly log an error in the logs to notify the developper that some package reference is missing.

### Environment
MODX 2.5.2, apache/nginx and Apache/2.4.16 (Ubuntu), mysql  Ver 14.14 Distrib 5.5.46

**Comment by MarkOdey** [comment]
I don't know if that is intended behaviour or not. I am sure one of you guys know what would be the ideal solution. However this did the trick.

    ```
  if($widget == null) {
            return;
        }
    
```

Not optimal but could be a potential fix.

**Comment by OptimusCrime** [comment]
The fatal error should not happen, but I am not sure how you are doing your migration? Exporting/importing a database is not all you have to do. You also need to move the corresponding files.

**Comment by MarkOdey** [comment]
Very true. Might not be very relevant to provide a fix. It would help though figuring what precisly is crashing when the dashboard is loading. I don't know.

**Comment by Jako** [comment]
Which dashboard widget causes the issue and could you maybe post the code of that widget? 

There should be created somewhere a new modDashboardWidget or inherited object, that is not checked after creating.

**Comment by sottwell** [comment]
Could be a snippet-type widget that got its snippet deleted, but the widget is still attached to the dashboard.

**Comment by MarkOdey** [comment]
Hey guys, a little update on my situation. First off, the main problem was related to file permission on some files that couldn't run. No error were apparent at that level. I believe it was my google analytics widget causing it to crash like so. However it was hard to tell which one was the guilty one since I couldn't get the source of the error. Ideally I should have gotten a 500 somewhere to help figure out the issue. Am I right?

Another problem was related to the $modx->toJson() this one occurred many times to me but I keep forgetting about it. Maybe I should open a new issue or maybe it is a non issue or it is only a issue on how I did setup my db. Basically, my database was using latin1 instead of utf-8 on some of my tables. Since some of the characters are problematic with json_encode. Everywhere $modx->toJson() was being used it was outputting a empty string. Because no error were reported the editor would output a whole bunch of js errors without reporting php errors. I believe this would have greatly helped me to figure out what was the issue if I would have gotten a json_encode error. 

Anyways, I don't know if anything should be undertaken for that issue.  But I believe we could take small measure to ease our error probing in the platform. 

Thanks for the support.

Mark

**Comment by OptimusCrime** [comment]
I can apply a fix where we attempt to check that a valid widget was returned before running it, and logging potential errors. What is harder is if the problem is manifested in the Google analytics extra. If that is the case, the extra must be fixed too. Furthermore, the issue with `toJson` is hard to debug. There's no way to validate that a encoding was successful. The error here is you using latin1. MODX should somehow validate this during setup or upgrade, as we can use this to avoid a lot of errors that are harder to track down.

**Comment by MarkOdey** [comment]
Right but correct me if I am wrong. If google analytics is existent but has an error. The $widget object won't be null anymore. $widget in that context is just a string containing the front facing. Am I right?  

Anyways I will let you decide on what should be done at that point I think you guys know alot more than I do about php and modx revo. I would be glad to help more if you need me.

Mark

**Comment by OptimusCrime** [comment]
I am not 100% sure how this widget system works, and I am not sure just what you did to make it crash, to recreating it is somewhat difficult here. I can create a PR with a fix that checks for null before calling the widget method? According to your first comment here it solved the problem? Logical null checks should be done where a potential null pointer may be present.

**Comment by OptimusCrime** [comment]
I've submitted an attempted fix. Does it look alright to you?

**Comment by MarkOdey** [comment]
All right, I consider this resolved. Thanks OptimusCrime for your commitement. Hopefully, if someone faces issues on undefined widget it won't fall into a white page but will report that the widget is non-existant.

**Comment by Mark-H** [comment]
An easy way I found to reproduce the dashboard is to create a file widget with an invalid file bath (just "foobar" is enough)

Anyway, fixed in 2.6.
