### ISSUE TITLE
If context_tree_sort is set to false, disable drag and drop of contexts [#modxbughunt]

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/revolution#13363]
### Summary
The context "blocks" are drag and droppable. This can be used to reorder them as they have a rank system similar to resources. However, if the system setting `context_tree_sort` is false the state will not be stored. This is confusing. It would be better that in scenarios where `context_tree_sort` is set to false, dragging and dropping is disabled.

### Step to reproduce
Set `context_tree_sort` to false (system default). Reorder contexts by dragging them. Refresh site.

### Observed behavior
Reordering is not saved.

### Expected behavior
Reordering is not possible.

### Environment
modxcms/revolution@842f03fbdb7b7bfef1b91cc15db9639f53026096

**Comment by jcdm** [comment]
+1 - just discovered this via a client who'd been trying to drag and drop sort but finding it didn't 'stick'. Was in 2.5.5.

**Comment by Mark-H** [comment]
Fixed in 2.6
