### ISSUE TITLE
Edit context in grid adds context key multiple

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13371]
### Summary
Edit context directly in the grid adds the context key in brackets multiple.

### Step to reproduce
Edit a context directly in the context grid by i.e. changing the description and reload the grid afterwards. 

### Observed behavior
The name column contains the context key in brackets twice (or even more - each edit adds one context key in brackets).

### Expected behavior
It should contain the context key once.

### Environment
MODX 2.5.5

**Comment by OptimusCrime** [comment]
Sent a PR for this.

**Comment by achterbahn** [comment]
I've never came to an end with my try to fix this issue. So discard my commits and go for @OptimusCrime 's solution.

**Comment by OptimusCrime** [comment]
No problem @achterbahn. It it turns out that my approach is too fragile and open for bugs, we might end up using your solution.
