### ISSUE TITLE
MySQL 8.x and utf8mb4 will soon affect new MODX installations

### ISSUE THREAD

**Issue by FBachofner** [modxcms/revolution#13373]
### Summary
Reviewing sessions for the upcoming Percona/mySQL conference I just learned that MySQL 8.x will set the default character set to utf8mb4.

> Our plan however, is to change the default character set to utf8mb4. This means that going forward, we expect users to less frequently be needing to change the character set at all.

from: http://mysqlserverteam.com/sushi-beer-an-introduction-of-utf8-support-in-mysql-8-0/
see also:
- https://blog.gabriela.io/2017/01/10/what-mysql-8-0-1-means-to-you-as-a-developer/
- http://mysqlserverteam.com/the-mysql-8-0-0-milestone-release-is-available/

### Details relevant to MODX
This mySQL enhancement is very good news for mySQL/MariaDB in general, but a specific challenge for MODX.  As we know, MODX does not "play nice" when databases use utf8mb4.
see in particular the following issues:
- [12445](https://github.com/modxcms/revolution/issues/12445) (priority-2-high) this seems the cardinal description of the problem
- [13121](https://github.com/modxcms/revolution/issues/13121) (priority-1-urgent) causes installer failure
- [13263](https://github.com/modxcms/revolution/issues/13263) (no priority, same basic issue as 13121)

### A question of renewed urgency
Another significant change in mySQL 8.x is a change in intention in how tablespaces will be handled.  Two issues here **_will very likely speed adoption of 8.x with hosting providers_**:
- simplification/reduction of files in the tablespace (i.e. elimination of .frm and index files, etc.)
- file per database (including, possibly separating InnoDB data into file-per-database . . . that seems to be one long term intent)

These enhancements will likely make mySQL even more attractive to hosting providers because:
- less resource usage in some regards [at least fewer inodes used in Linux / fewer files per folder in Windows (for the "identical" DB), among other increased efficiencies]
- DBs can be more cleanly separated between users (conceptually useful in multi-tenant, i.e. shared-hosting companies)
- DBs will potentially become more easily "portable" [I personally hope for binary copies of (Inno)DBs as one can do with SQLite and Firebird]      However, the new [global data dictionary](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-0.html#mysqld-8-0-0-data-dictionary) seems to contradict this potential, at least initially.

### Environments affected
at minimum, all MODX <= 2.5.5

### Desired outcome
MODX >=2.5.6(?) completely supports utf8mb4

**Comment by FBachofner** [comment]
By the way, the Percona conference will be held almost exactly 18 months after the release of mySQL 5.7 and the mySQL team endeavors to release a major new GA every 18-24 months.

Further, (at conference time) it will have been been 7 months since MySQL Server 8.0.0-dmr

I wonder if they may possibly use the conference to release 8.0?  [ A bit unlikely, but certainly possible.]

**Comment by digitalpenguin** [comment]
Besides limiting varchar columns to 191, what else is required to get this fixed?
