### ISSUE TITLE
xPDOFileCache->get might return invalid data when use_flock is false

### ISSUE THREAD

**Issue by uplex-lf** [modxcms/revolution#13383]
### Summary
I think I spotted a problem in xPDOFileCache while looking into a cache corruption issue on NFS for a customer:

xPDOFileCache->get always uses flock even when use_flock is false. Meanwhile xPDOCacheManager->writeFile which is used by xPDOFileCache->set honours use_flock and will use file based locking if use_flock is false.

### Step to reproduce
n/a

### Observed behavior
If use_flock is false cache files are read and their contents returned by get even when they are currently being (re)written.

### Expected behavior
If use_flock is false xPDOFileCache->get should return null when the existence of a lockfile signals that a (re)write is in progress.

### Environment
MODX 2.5.5

**Comment by lawrenz1337** [comment]
I think it is better to report this issue to xPDO repository

**Comment by OptimusCrime** [comment]
I'm not too familiar with flock and how it works, but could this be a duplicate of #12740?

Also, it should be posted in modxcms/xpdo repository.

**Comment by uplex-lf** [comment]
Okay, thanks for looking into it. This is more or less a duplicate of #12740. What is not mentioned in #12740 is that this can actually lead to data corruption. I will move this issue over to modxcms/xpdo.
