### ISSUE TITLE
Rename Category popup without rank value

### ISSUE THREAD

**Issue by himurovich** [modxcms/revolution#13391]
### Summary
I can't see rank value for category with previously updated rank value, empty field is always there

![chunk_ head - google chrome 2017-03-21 20 28 53](https://cloud.githubusercontent.com/assets/2815640/24162105/7c011946-0e77-11e7-8e3e-3befee1685d6.png)

### Step to reproduce
Create some category / open already existing one, set "rank" field value, press "Save". Open category popup again, you won't see saved rank value here, field will be empty (at the same time DB stores it and category tabs sorting within "Template variables" is correct due to that stored values)

### Observed behavior
Rank field is empty always even for non empty category rank values.

### Expected behavior
It's OK have empty rank field for default (when you create category firstly or didn't update rank before; default DB value is empty for ranks) but for other cases there should be current non-zero rank value.

### Environment
2.5.5-pl on MODX Cloud

**Comment by Flowan** [comment]
@himurovich Tested this and works ok. Mark as fixed? #modxbughunt

**Comment by gpsietzema** [comment]
@modxbot close
