### ISSUE TITLE
Editing a user, it's not possible to enter date of birth 1970-01-01 when in UTC timezone

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13406]
### Summary
When your server runs in an UTC timezone it's not possible to save a date of birth 1970-01-01.

### Step to reproduce
Set the system setting `date_timezone` to an UTC timezone (or simply leave field empty). Now try to edit a user and set it's date of birth to 1970-01-01. In database the dob field will be 0 (unix time stamp). ExtJS decides this is an empty value and the dob field is cleared.

### Expected behavior
It should be possible to set a users date of birth to 1970-01-01 although in UTC timezone. 

### Environment
MODX version 2.5.5

### Possible fix

Always save the dob with UTC timezone and add 1 second to differ between empty birth date and birth date of 1970-01-01

sample code to show what I mean:
```php
$oldTimeZone = date_default_timezone_get();
date_default_timezone_set('UTC');
$dobTimeStamp = strtotime($dobYear.'-'.$dobMonth.'-'.$dobDay.'T00:00:01'); 
date_default_timezone_set($oldTimeZone);
```

**Comment by rtripault** [comment]
Thanks for your report. 
Just wanted to highlight that might be related to #11873 ;)

**Comment by gadgetto** [comment]
Hey, already forgot about this old one! :)

**Comment by Finetuned** [comment]
"I'm going to try and fix this today."

**Comment by rtripault** [comment]
@Finetuned i'll closing this one in favor of the other one, would you mind commenting there/referencing the other issue please ?

Thanks
