### ISSUE TITLE
Error message attributed to wrong context

### ISSUE THREAD

**Issue by fountainheadllc** [modxcms/revolution#13403]
### Summary
Attempted to duplicate a context into a new context that already existed and error message popped up that context already exists, but was assigned to the old key not the new key.

### Step to reproduce
Attempt to copy context to an existing alternative context, error message will reproduce in pop-up.

### Observed behavior
Error message in red displays for Old Key not New Key

### Expected behavior
Error message in red should display for New Key

### Environment
MODX 2.5.5, MODXCloud nginx and php 5.6.x
![screen shot 2017-03-29 at 9 22 21 am](https://cloud.githubusercontent.com/assets/26174817/24457137/4d45faa8-1463-11e7-88b1-a2dac54984d3.jpg)

**Comment by Alroniks** [comment]
Fixed during the #modxbughunt

**Comment by Alroniks** [comment]
Merged, so closing.
