### ISSUE TITLE
Forbidden characters in MODX user passwords

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13402]
### Summary

Setting a password for a user in MODX manager is not possible if the password contains some special characters (explained below). IMHO, there should be no limitation of allowed characters in a password.

### Step to reproduce

Edit a user and try to set it's password to `abcdefg:)`

I found this in /core/model/modx/processors/security/user/_validation.php:

```
} elseif (!preg_match('/^[^\'\\x3c\\x3e\\(\\);\\x22]+$/', $specifiedPassword)) {
    $this->processor->addFieldError('specifiedpassword', $this->modx->lexicon('user_err_password_invalid'));
```

### Observed behavior

If you try to enter a password which contains the following characters: ()'\  the password field shows a field error "Invalid password"

### Expected behavior

No password should be invalid.
No special chars should be forbidden in passwords.

### Environment
MODX version 2.5.5-pl

**Comment by sottwell** [comment]
It probably has something to do with the hashing algorithm having a problem with those characters.

**Comment by gadgetto** [comment]
Could this be a legacy problem? The password hashing is different since MODX 2.1.x...

**Comment by jaygilmore** [comment]
According to @opengeek from a recent conversation we had internally, this is due to the following code which enables modExt to function properly: 

```php
$chars = array("'",'"','(',')',';','>','<','!','../');
$this->scriptProperties[$k] = str_replace($chars,'',$v);
```

This apparently has to do with _encodeLiterals/_decodeLiterals in modConnectorResponse (https://github.com/modxcms/revolution/blob/43c4615a065fc095b15056d27b89a19deba1d056/core/model/modx/modconnectorresponse.class.php)

**Comment by gadgetto** [comment]
Ok, this means, this problem (character restriction) only exists in MODX manager?
Changing/setting passwords via front-end (e.g. Login add-on) won't need this restriction?

**Comment by jaygilmore** [comment]
If any Extra is using the built in processors/classes, it will still be restricted on this core code. The Manager login is currently built on and loads Ext. I suppose if you write something to bypass this for a user record and write directly via xPDO/MySQL.

**Comment by OptimusCrime** [comment]
Does this mean that a ExtJS input field can not handle these types of characters as their input? I get that some of these characters might create problems for ExtJS if they are used in the ExtJS object markup, but I can not imagine something "crashing" if you try to log in with a parenthesis in the password. Couldn't the password area avoid getting stripped this way? Restricting what characters people can use in their passwords is really bad practice.

**Comment by jaygilmore** [comment]
I think everyone can agree this is a bad limitation. IDK anything about specifically where the limitations are. All I know is they exist and they would need refactoring to solve this issue. It is worthy of fixing but not an easy task, from what I can guess.

**Comment by alroniks** [comment]
While we use ExtJS, we have to use such limitations as I see. I am closing the issue, because in case the new manager, not ExtJS, such a thing won't be existing.
