### ISSUE TITLE
Add link to view changelog before updating a package

### ISSUE THREAD

**Issue by hugopeek** [modxcms/revolution#13410]
### Summary
This is a feature request for adding a "View changelog" button / link in the Update Package modal (the one below).

![screenshot from 2017-04-05 14-39-22](https://cloud.githubusercontent.com/assets/5436121/24693387/edfbdfba-1a0f-11e7-95fb-dfefb817c977.png)

### Observed behavior
Right now, you will only see the release notes _after_ you click the install button. If there's anything scary in there and you want to abort the installation, you'll end up with the package being displayed as "not installed" in the grid:

![screenshot from 2017-04-05 14-47-37](https://cloud.githubusercontent.com/assets/5436121/24693385/ea959cd0-1a0f-11e7-96c6-6971bdf88cee.png)

Now, the package wasn't installed yet and you can go back to the currently installed version by selecting "Remove" in the grid.. But I don't know how many people are aware of that, as it's not really the behavior you'd expect when clicking a remove button.

### Desired behavior
It would be better if you can preview the changelog before deciding to install the package. Maybe you edited some core files of a package and only want to update if your fix is implemented in that release, or maybe the release comes with breaking changes that you'll need to sort out first on your local install.. Lots of reasons why you'd want to read the changelog first!

### Side note
The modal also says: Please select the version to update this package to, but it seems to always update to the latest release. If we're being really meticulous here, it should either show all updates between current and latest version, or simply say it will update to the latest version (with version number of course, and the new view changelog link).

**Comment by Jako** [comment]
The side note is not complete: It would show all not deprecated versions of a package with a higher version than the current in a list with radio boxes.

Since the changelog in the package is not sent back to the MODX installation when it requests the list of possible updates, not only the MODX code but also the provider code has to be changed. It has to extract the changelog information out of the transport package and send it together with the version info or it has to handle the changelog information in some extra package info table field.

**Comment by Mark-H** [comment]
The package provider response does include the changelog from what I can tell. [Example request/response](http://rest.modx.com/extras/package/update?signature=clientconfig-1.3.1-pl)

**Comment by Jako** [comment]
Ok: the MODX extra provider on rest.modx.com sends back the info that is saved in the changelog field. But that has not to be equal to the changelog info in the package itself.

**Comment by Mark-H** [comment]
True, it's up to the developer to make sure that has useful info. With the modmore provider that's automatically synced to the changelog file so we don't have to enter it twice. :D 

I'm assuming the form on the MODX site filters the accepted HTML?

**Comment by Jako** [comment]
It should be better extracted out of the package without any manual input ...

**Comment by Mark-H** [comment]
Will be in 2.6
