### ISSUE TITLE
manager search top left cant click on results in 2.5.6

### ISSUE THREAD

**Issue by phantomphondler** [modxcms/revolution#13416]
### Summary
the search on the top left in the manager. Can not click on result.

getting js error 

detailed error: TypeError: e.stopPropagation is not a function
modx.js...-min.js (line 4, col 5159)

### Step to reproduce
search on anything on the top left and try click on it. 

### Observed behavior
nothing happens when clikc gettinng js error

detailed error: TypeError: e.stopPropagation is not a function
modx.js...-min.js (line 4, col 5159)

### Expected behavior
should display the page that you clicked on

### Environment
apache, php 5.6, using SSL

**Comment by OptimusCrime** [comment]
Already reported in #13404 and fixed in #13405. A new version 2.5.7 will have the fix. 

Thank you for reporting, we know this is an annoying issue. Hopefully a hotfix will be released soon that adresses this issue.

@modxbot close

**Comment by OptimusCrime** [comment]
EDIT: By the way, using the arrow keys still work, so you can use that as a work around for now.
