### ISSUE TITLE
chmod'ing a directory no longer works

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#13429]
### Summary
Since 2.5.6 it's not possible to chmod a directory. This seems to be caused by #13352, which runs a preg_match on the result of `$this->parseMode` which runs `octdec` which transforms the value from something like `0755` to a decimal `493`, which doesn't pass that check. 

### Step to reproduce
Right click a directory in the files tree, attempt to change the chmod (folder permissions), see it fail with a generic error.

### Observed behavior
Error is thrown 

### Expected behavior
chmod should be executed

### Environment
Confirmed by 3 different people on different environments (including local installs and MODX cloud), does not appear to be server related.

**Comment by Jako** [comment]
This could be solved by moving the line 212 after 216 in https://github.com/OptimusCrime/revolution/blob/f89be6e74d53aa86ce187f3bcd87db01b5ce304e/core/model/modx/modfilehandler.class.php#L212 but then the error message is wrong, when the folder can't be chmod, because of PHP/Filesystem restrictions.

**Comment by Jako** [comment]
The regex validation has to be done outside of the modFileSystemResource->chmod method, i.e. in the modFileMediaSource->chmodContainer method.

**Comment by Jako** [comment]
Until that #13352 should be reverted.

**Comment by OptimusCrime** [comment]
@Jako Haha, why did you reference my fork?

**Comment by OptimusCrime** [comment]
Oh, because of my PR. I see. I did not alter the underlying implementation, I only fixed the validation of the regex.

**Comment by Jako** [comment]
But your validation uses the value of `$more`, that was changed in `$this->parseMode`. It can't be validated with the regex at that moment anymore.
