### ISSUE TITLE
Directory traversal vulnerability in MODX  2.5.7 search page, please confirm!

### ISSUE THREAD

**Issue by fantasy7082** [modxcms/revolution#13432]
### Summary
Hello, i found a directory traversal vulnerability in search page. the reproduction is below:

### Step to reproduce
I have already sent it to your mail, my email is fantasy7082@hotmail.com

### Observed behavior
It will causes the system directory information to leak

### Expected behavior
It will not causes the system directory information to leak

### Environment
MODX version, 2.5.7

**Comment by Mark-H** [comment]
Please responsibly disclose security issues via security@modx.com, not in a public issue..

**Comment by fantasy7082** [comment]
oh, sorry.I have already sent it to your mail, my email is fantasy7082@hotmail.com

**Comment by fgeek** [comment]
Have you scheduled 2.5.8 release already?

**Comment by JoshuaLuckers** [comment]
@Mark-H is this already looked into?

**Comment by fgeek** [comment]
It's very confusing to leave issues like this open for over a year. Nothing about this issue in ChangeLog.

**Comment by Mark-H** [comment]
Looked up the related responsible disclosure, yes this was addressed. The issue is confusing but basically files no longer served a purpose exposed a vulnerability, so those files were removed entirely in #13433.
