### ISSUE TITLE
Permission error for System Events

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#13435]
### Summary
The permission error popup for System Events is really ugly.

### Step to reproduce
Log in as a Manager user, not sudo, that does not have the Events permission, this is the default setting in Administrator policy. Go to System Settings, and the System Events tab. You will not see any events in the grid. Try to create a New Event.

### Observed behavior
An error popup is displayed with code.
![screen shot 2017-04-23 at 7 15 24](https://cloud.githubusercontent.com/assets/1073780/25310745/8e0cd08e-27f5-11e7-8e6b-a2aff2d5d9d6.png)

### Expected behavior
A comprehensible error message.

### Environment
Revo 2.5.7

**Comment by navtsi** [comment]
Same issue but on other place. It appears because I made some restrictions to elements. An Editor usergroup can edit a resource but cannot select templates with category »Admins only«. In previous versions it works.

If I delete the restrictions the message disappears.

**Comment by Flowan** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by Ibochkarev** [comment]
Improved in https://github.com/modxcms/revolution/pull/15402
