### ISSUE TITLE
Image TV not editable upon creation with space in filename

### ISSUE THREAD

**Issue by Izacktly** [modxcms/revolution#13449]
### Summary
When creating an image TV using XPDO, the image could not be updated in the manager as the option to select the image was not visible.  The issue being, the name of the image contained a space (At the end of the filename).

### Step to reproduce
1) Create a Resource and add a image name to an existing TV using the following code.  Please note that the image filename MUST have a space to the end.
2) I pre-uploaded all the images for the image TV, before running the script below.

`$resource = $modx->newObject('modResource');
        $resource->set('pagetitle', 'testresource');
        $resource->setContent('My resource content');
        $resource->set('parent', 2);
        $resource->set('show_in_tree',0);
        $resource->set('published',1);
        $resource->set('template',22);
        $resource->save();

        /*
         * Only if resource created successfully, then update TV.
         */
        if($resource->save() === true){

            $tvObject = $modx->getObject('modTemplateVar', 77);
            if(is_object($tvObject)){
                 * Update Image File.
                 */
                $tvObject->setValue($resource->get('id'), 'myimage.jpg ');
                $tvObject->save();
            }else{
                //echo "Product Image could not be saved";
            }

        }

    }`

### Observed behavior
1) The resource was created fine
2) The image TV value was created properly in the database.
3) The image showed up in the manager.
4) Not able to update the image value in the manager as the option to select a new image was not visible.

### Expected behavior
Should be able to view and update the image in the manager.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.
1) Modx Cloud
2) MODX Version: 2.5.5
3) php 5.6
4) chrome 58.0.3.029.26
5) nginx (not sure of version)

**Comment by Flowan** [comment]
Hi @Izacktly I was not able to reproduce this. Could it be this was an one time browser cache issue?

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan 

@modxbot close
