### ISSUE TITLE
Stringent CSPv3 policy not possible (breaks manager functionalities)

### ISSUE THREAD

**Issue by XStreamke** [modxcms/revolution#13440]
### Summary
Issue about using CSP policies together with ExtJS, which is used by the ModX Manager

### Step to reproduce
Just use a stringent CSP policy eg.
Content-Security-Policy "default-src 'self' www.google-analytics.com www.googletagmanager.com;; script-src 'self' www.google-analytics.com www.googletagmanager.com; child-src 'none'; media-src 'none'; font-src 'none'; object-src 'none'; style-src 'self';"

### Observed behavior
When I use a stringent CSP(v3) policy (example: no unsafe-eval, unsafe-inline) the manager stops showing the resources (which uses ExtJS and thus eval functions)

### Expected behavior
Working manager or a work-around

### Environment
MODX v2.5.6/v2.5.7

**Comment by sottwell** [comment]
You should be interested in this, then http://modx.com.mt/ 
It's definitely not going to happen in the Revo 2 and probably not in the Revo 3 branches.

**Comment by OptimusCrime** [comment]
Yeah, as the MODX manager panel is based on ExtJS and uses eval, I see no easy way around this. Revo 4.x (or something like that) may include a manager interface created from scratch, perhaps that will solve the problem. Before that, I doubt this will work.

**Comment by Mark-H** [comment]
It would be interesting to see what parts of ExtJS are to blame, and if there's any simple way to avoid those parts in core code.

**Comment by XStreamke** [comment]
Mark, 
I didn't dig into the coding yet. I Have other things to do first. But if there isn't a solution soon, it might be that I'll post a work-around perhaps. At the moment I'm too busy. What's broken is the lists of all the resources. But even with the working solution (using unsafe eval & inline) it doesn't do it well in IE11 either (but they don't support it well neither). I just started using modx so I'm still learning. There are other JS frameworks that also have some issues/other way of working with CSP like eg. AngularJS. I didn't look into those things neither. For the moment I lowered the restrictions. Nevertheless ExtJS probably could have rewritten the evals (but that's another question for ExtJS). It's more than just the unsafe eval/inline. You need to set the child-src (new frame-src) to self, in order to save your modifications (save pop-up) and you need to set object-src also to self.

**Comment by XStreamke** [comment]
All. with the last update of IE (have to check some stuff at home and with other browsers) it's possible to remove the lines: unsafe-eval and unsafe-inline. Meaning the security headers can be improved giving you a rate A+ again. So it might be that this issue can be closed. Keep you posted in the coming days.

**Comment by XStreamke** [comment]
As expected. Latest IE version is neglecting CSP completely, while Chrome, FF and Tor Browser are following the CSP. I'll close this issue because this will not be fixed soon.
