### ISSUE TITLE
2.5.6 ignores hide_children_in_tree value

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#13442]
### Summary
Since 2.5.6, new update has changed the resource tree behavior.

### Step to reproduce
Just install Grid Class Key, and add resource into it.

### Observed behavior
The child resources are shown in the tree.

### Expected behavior
It should be hidden, because the Tree Node should respect `show_in_tree` and `hide_children_in_tree` values.

### Environment
Since MODX 2.5.6.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/13322

**Comment by rtripault** [comment]
Just to add that `show_in_tree` is currently respected (at least on the 2.x branch)

**Comment by goldsky** [comment]
Rephrased the title
This ignores `hide_children_in_tree` value (top => down behavior)

**Comment by goldsky** [comment]
I've modified GridClassKey instead.
https://github.com/goldsky/GridClassKey/issues/140

**Comment by rtripault** [comment]
Thanks @goldsky , glad you found a workaround!

The problem remaining in the core, i'm reopening this one!
