### ISSUE TITLE
Enhance duplicate dialog

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#13448]
### Summary
If you duplicate a resource by rightclicking on it in the tree, the duplicate dialog doesn't give any feedback which resource you are going to duplicate.

![bildschirmfoto vom 2017-05-04 09-58-56](https://cloud.githubusercontent.com/assets/667315/25694752/5d9caca8-30b0-11e7-83f2-8444c27f79ae.png)

### Step to reproduce
resource -> rightclick -> context menu -> duplicate

### Observed behavior
The right clicked resources looses focus, the dialog doesn't give any clue about the resource title or id of the resource you are about to duplicate. If you are clumsy you'll duplicate a whole part of the tree including all children and so on (I just did that...)

### Expected behavior
Give some feedback about what you are about to do.

Show the pagetitle and the id on top of the dialog

![bildschirmfoto vom 2017-05-04 10-07-59](https://cloud.githubusercontent.com/assets/667315/25694996/9756b44c-30b1-11e7-85a0-d4fc652dd2a5.png)

As the available space in the head might be a concern, moving the pagetitle/id inside the box might be3 a good compromise.

### Environment
MODX all versions.

**Comment by mindeffects** [comment]
+1

**Comment by wuuti** [comment]
Even more important: the same applies to the delete alert. You don't have a clue if you are really deleting the right resource there...

**Comment by pepebe** [comment]
@wuuti Yes, the deleted alert is also lacking in user friendliness. That being said, the whole deletion practice in MODX is terrible broken:

https://github.com/modxcms/revolution/issues/764

I really have to split this thread into different issues...

**Comment by Alroniks** [comment]
Fixed by #13475.

@modxbot close

**Comment by Alroniks** [comment]
#modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Alroniks
