### ISSUE TITLE
Base_url automatically changing to rb_base_url in settings search and when trying to add settings to contexts

### ISSUE THREAD

**Issue by Elawphant** [modxcms/revolution#13458]
### Summary
In settings, when searching for base_url, or when trying to add a setting in a context, the context key automatically changes to rb_base_url. As Mark Hamstra suggested in modxcommunity slack 
> that might be because base_url is not created as a setting by default, and rb_base_url is the closest match

### Step to reproduce
Search base_url in settings, or in a context add context setting, write base_url in key tab
### Observed behavior
it will autofill/change to rb_base_url

### Expected behavior
base_url

### Environment
MODX version 2.5.7-pl

**Comment by zaigham** [comment]
There is a UX gap here, the drop down is select box listing existing options, but if you press enter, it will default to whatever close match you have highlighted. Instead, for now, you need to click on the **_Save_** button and it will save the `base_url` instead of `rb_base_url`.

**Comment by Mark-H** [comment]
I'm not sure what the best way to fix this is. Perhaps removing the rb_base_url setting as I don't think that's used anymore. Alternative might be to hardcode base_url as a valid setting key..

**Comment by OptimusCrime** [comment]
Note: `rb_base_url` is used. For example in `modFileHandler::getBaseUrl`.

I guess this rpboelm could be fixed by providing an empty `base_url` system setting?

**Comment by Ibochkarev** [comment]
Fixed #14886
@modxbot close
