### ISSUE TITLE
View link not working after saving a new unpublished resource.

### ISSUE THREAD

**Issue by neoneddy** [modxcms/revolution#13456]
### Summary
If I create or duplicate an unpublished resource initially the View button will link to an about:blank url

### Step to reproduce
Duplicate or create new a resource as unpublished.  Click view button with out a refresh.  a refresh seems to fix it.

### Expected behavior
When clicking save without refreshing the view button should show the unpublished url when authenticated.

### Environment
MODX 2.5.7, NGINx, PHP Version 5.6.30

**Comment by wuuti** [comment]
Normally saving a new resource triggers a page refresh in the manager. Isn't that happening in your case?

**Comment by neoneddy** [comment]
It might be, but the end  result is we have to manually refresh before that link works.

**Comment by Flowan** [comment]
@neoneddy I was not able to reproduce the issue like you described. Could it be that the duplicated resource had no alias/uri? When i manually remove those two options from the database table, i get a blank page.

**Comment by rtripault** [comment]
I wasn't also able to reproduce on the 2.x branch

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by OptimusCrime** [comment]
Seem like this problem was caused by corrupt data in the database.

@modxbot close

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @goldsky

**Comment by goldsky** [comment]
@sonicpunk I don't deserve this.
Thx anyway.
