### ISSUE TITLE
failed_login_attempts setting doesn't work as you'd expect

### ISSUE THREAD

**Issue by Bryan-Lund** [modxcms/revolution#13459]
### Summary
The failed_login_attempts setting in the CMS doesn't work quite as you'd expect - the number you give is not the amount of login attempts actually taken into account.

### Step to reproduce
Go into the settings in the MODx manager and update the failed_login_attempts setting (defaults to 5).

### Observed behavior
When attempting to log in once more than the amount set for the failed_login_attempts setting, you can still try to login. After checking this with different settings (3 and 2 times instead of the default of 5), I noticed that for setting it to 3, it would set your account to be blocked after the 6th attempt, setting it to 4 blocks your account after the 4th attempt (basically doubled depending on the setting you give). 

### Expected behavior
It should mark your account as blocked after the nth amount of trying to login (where n is the failed_login_attempts setting), instead of nth x 2.

### Environment
MODX version - 2.5.7
apache version 2.4.7
mysql version 15.1
browser - Chrome 58.0.3029.110 (not checked other browsers)

**Comment by spectrum48k** [comment]
fixed in #13516 PR

**Comment by rtripault** [comment]
PR merged, so closing.

Thanks
