### ISSUE TITLE
Content manager Filesystem rules error

### ISSUE THREAD

**Issue by Kuzzmich** [modxcms/revolution#13453]
### Summary
Problem with list of approve folders for content manager. I use some rules for content manager, that hide Filesystem folder from him. When I logedin as content manager I see "1" in the list of approve folders in MODX Resource Browser, but I cn choose right folder there. How to use right default folder? (approved)

### Step to reproduce
I've tried change roles for folders. Use newer version of MODX (2.5.7) and TinyMCE rich text editor (1.1.1)

### Observed behavior
The same problem.
![default](https://cloud.githubusercontent.com/assets/17698621/26192891/021ded58-3bbc-11e7-8932-f8786b0f9d6e.PNG)
![2](https://cloud.githubusercontent.com/assets/17698621/26192894/022477ea-3bbc-11e7-8630-0219ce8baa4a.PNG)
![3](https://cloud.githubusercontent.com/assets/17698621/26192893/02247ee8-3bbc-11e7-88ad-da5def22aba2.PNG)
![4](https://cloud.githubusercontent.com/assets/17698621/26192892/022428d0-3bbc-11e7-9cec-265d4c4d465d.PNG)

**Comment by OptimusCrime** [comment]
Are you sure the default media browser for this template variable is not Filesystem? If that is the case then you will have to change the default one.

**Comment by Kuzzmich** [comment]
I found the answer. I need to set default_media_source for any users, who isn't an Administrator.
