### ISSUE TITLE
Help Page Newsletter Subscribe Fix

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/revolution#13463]
### Summary
The MODX Newsletter subscription form on the Help Page (/manager/?a=help) was using an outdated post form link and was failing.

### Step to reproduce
Visit /manager/?a=help and try to subscribe to the MODX Insider

### Observed behavior
Arrives at appilcation 404 page at Mailchimp

### Expected behavior
The newsletter subscription should work with the correct subscription form processor link in place. 

### Environment
NA

**Comment by Mark-H** [comment]
Fixed per #13464
