### ISSUE TITLE
Context setting listing fetches too few settings

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/revolution#13461]
### Summary
The context setting listing does not list the amount of settings it should. The list is truncated too soon.

### Step to reproduce and observed behavior
We have (the default value?) setting named `default_per_page` as 20. However, in the Context Settings tab, the `Per Page` value is 30. What is even weirder is that the listed settings is only 12 although there are more settings in the list. If we increase the `Per Page` value to 50 it lists 20 settings, and 300 lists all the 27 settings.

In addition, the pagination states that there are no more pages (Page 1 of 1).

### Expected behavior
Correctly list the number of settings it is said to list.

### Environment
MODX 2.5.7

**Comment by neoneddy** [comment]
I've seen this too.   Use CrossContext Settings as a work around for now.

**Comment by Jako** [comment]
Maybe this is caused by the namespaces of the context settings (if you want to investigate that further).

**Comment by Flowan** [comment]
I'm going to try and fix this today.

**Comment by Flowan** [comment]
Confirmed bug in 2.5.x I will update my current PR. #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan
