### ISSUE TITLE
getResources tvFilter on decimal values

### ISSUE THREAD

**Issue by pwsllc** [modxcms/revolution#13469]
### Summary
When filtering resources from getResources with tvFilter and a decimal value, the CAST is not working correctly.  

### Step to reproduce
Create a tv with a decimal value.  eg. price.  Assign a value, eg. 11.99.  Query for the resource with getResources:

[[!getResources?
    &parents=`...` 
    &tpl=`...`
    &includeTVs=`1` 
    &processTVs=`1` 
    &includeContent=`1`
    &tvFilters=`price<=11.00`
]]

### Observed behavior
The resource created with 11.99 price is found.

### Expected behavior
The resource created with 11.99 price is filtered.

### Environment
MODX 2.5.7-pl , getResources 1.6.1-pl, mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for debian-linux-gnu

### Solution
Change the CAST statement in getResources:

===================================================================
--- getResources.php	(revision )
+++ getResources.php	(revision )
@@ -279,8 +279,8 @@
                         $tvValueField = "CAST({$tvValueField} AS SIGNED INTEGER)";
                         $tvDefaultField = "CAST({$tvDefaultField} AS SIGNED INTEGER)";
                     } else {
-                        $tvValueField = "CAST({$tvValueField} AS DECIMAL)";
-                        $tvDefaultField = "CAST({$tvDefaultField} AS DECIMAL)";
+                        $tvValueField = "CAST({$tvValueField} AS DECIMAL(11,2))";
+                        $tvDefaultField = "CAST({$tvDefaultField} AS DECIMAL(11,2))";
                     }
                 } else {
                     $tvValue = $modx->quote($f[1]);
@@ -377,7 +377,7 @@
                 $criteria->select("CAST(IFNULL(tvSort.value, tvDefault.default_text) AS SIGNED INTEGER) AS sortTV");
                 break;
             case 'decimal':
-                $criteria->select("CAST(IFNULL(tvSort.value, tvDefault.default_text) AS DECIMAL) AS sortTV");
+                $criteria->select("CAST(IFNULL(tvSort.value, tvDefault.default_text) AS DECIMAL(11,2)) AS sortTV");
                 break;
             case 'datetime':
                 $criteria->select("CAST(IFNULL(tvSort.value, tvDefault.default_text) AS DATETIME) AS sortTV");
@@ -393,7 +393,7 @@
                 $criteria->select("CAST(ISNULL(tvSort.value, tvDefault.default_text) AS BIGINT) AS sortTV");
                 break;
             case 'decimal':
-                $criteria->select("CAST(ISNULL(tvSort.value, tvDefault.default_text) AS DECIMAL) AS sortTV");
+                $criteria->select("CAST(ISNULL(tvSort.value, tvDefault.default_text) AS DECIMAL(11,2)) AS sortTV");
                 break;
             case 'datetime':
                 $criteria->select("CAST(ISNULL(tvSort.value, tvDefault.default_text) AS DATETIME) AS sortTV");

**Comment by Jako** [comment]
Could you open this issue on https://github.com/opengeek/getResources, please?
