### ISSUE TITLE
newObject context_key by default

### ISSUE THREAD

**Issue by Skippidar** [modxcms/revolution#13465]
```
        $resource = $modx->newObject('modResource', array(
            'template' => 73,
            'published' => 1,
            'hidemenu' => 0,
            'hidemenu' => 1,
            'menuindex' => $index,
            'createdon' => time(),
            'publishedon' => time(),
            'createdby' => $modx->getUser()->get('id'),
            'publishedby' => $modx->getUser()->get('id'),
            'pagetitle' => $values['pagetitle'],
            'longtitle' => $values['longtitle'],
            'alias' => $values['alias'],
            'parent' => 2665
        ));
```
This code creates resource with context_key 'web' even if it's parent is in other context. I think it would be better to check parent's context and use it by default if 'context_key' is not provided. Otherwise, resources created with wrong context_key are not shown in resource tree.

MODX 2.5.7

**Comment by OptimusCrime** [comment]
Pretty sure this is by design.

**Comment by Mark-H** [comment]
You basically have two options when creating a resource.

1) Do it manually, with $modx->newObject and the likes. If you do this, it's your responsibility to provide the proper values, such as the context_key in this case, but also things like aliases (you're not checking if it already exists in your sample code for example).

2) Use the processor via $modx->runProcessor('resource/create', $opts, $data), which will run all the checks and transformations to properly create a resource.
