### ISSUE TITLE
authentication check methods not work if user logged in to several contexts

### ISSUE THREAD

**Issue by spectrum48k** [modxcms/revolution#13471]
### Summary
authentication check methods not work if user logged in to several contexts

### Step to reproduce
User is logged in to contexts 'web' and 'mgr' at the same time

### Observed behavior
$modx->user->isAuthenticated('mgr') returns false
(core/model/modx/moduser.class.php:469 here used strict comparison of two arrays. I'm not sure but maybe it has to be used with additional $strict == true parameter)

### Expected behavior
$modx->user->isAuthenticated('mgr') returns true

### Environment
MODX version 2.5.5

**Comment by pixelchutes** [comment]
I cannot reproduce this behavior. This appears to be working as expected. I've logged into Manager (mgr), and also to frontend (web):

```php
$output = 'mgr = '.$modx->user->isAuthenticated('mgr');
$output .= ' web = '.$modx->user->isAuthenticated('web');

return "output: $output";
```

**Result:**
> output: mgr = 1 web = 1

Are you running your MODX manager from the same (sub)domain? Have you verified the same `session_id()` (session cookie)?

**Comment by spectrum48k** [comment]
can not verify if my user have session in 'web' context as another user from manager panel:
![h_1498051493_6210960_ad60d3b877](https://user-images.githubusercontent.com/17526628/27386580-f96f2d86-569e-11e7-94ee-6db2dbf36e89.png)

I did mistake in issue conditions. can not check if this user logged in another context as another user and
after debugging I realized that this methods check session as user of the same id
but not even session in another context as another user whith this cookie/cookie domain
(sorry for my poor english skills)
