### ISSUE TITLE
[ ENHANCEMENT ] Manager Welcome Message

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13474]
### Summary
When you install MODX for the first time, and login to the manager, a welcome screen is displayed. 

This message can be customised and is very useful for displaying initial setup information to manager users such as finishing setup details in ClientConfig, setting up Tags in Tagger, how to use design patterns and style guides, basic MODX tips and tricks, and ways on how to report bugs to me.

For example:

![screen shot 2017-06-22 at 12 05 33](https://user-images.githubusercontent.com/2373940/27428704-281ba822-5743-11e7-8fd5-3dc1c4365a1b.png)

### Step to reproduce
Install a fresh version of MODX and login to the manager where you'll see this welcome message:

![screen shot 2017-06-22 at 12 03 15](https://user-images.githubusercontent.com/2373940/27428617-ea169460-5742-11e7-9221-6903050795d3.png)

### Observed behavior
When any user logs in to the manager for the first time, this sets the system setting "welcome_screen" from "Yes" to "No".

![screen shot 2017-06-22 at 12 06 56](https://user-images.githubusercontent.com/2373940/27429135-7301578c-5744-11e7-9318-f738839e17dc.png)

### Expected behavior
Similar behaviour to the above, but on a per manager user basis. So every user that logs in for the first time will see the welcome message, rather than just the first manager user who logs in.

For example, at the moment User A logs in, triggers the welcome message, but because of this behaviour, User B, User C, User D can no longer view the welcome message, therefore missing useful information.

### Environment
Any version of MODX, specifically, 2.5.7

**Comment by sottwell** [comment]
I like it. Didn't know that Welcome popup was configurable. Always looking for ways to inform and interact with client users.

**Comment by OptimusCrime** [comment]
Could this potentially be a system setting to toggle the "display welcome message to all new users"? We dont use this feature and for our users I think this would just confuse them as we have individual training for our clients. Other than that, if people train their clients like this I am all for this feature.

**Comment by jonleverrier** [comment]
@OptimusCrime The system setting route sounds great.

I wouldn't say I use the welcome message specifically for training, but it is certainly useful for summarising points from a training session that a client is likely to forget. As the welcome message can be customised, it could be used in many different ways to interact with manager users.

I appreciate this varies from client to client but, manager users come and go, not everybody gets trained up.

If you would like to see my welcome message, so you can see where i'm coming from, I'd be happy to send it to you

**Comment by OptimusCrime** [comment]
Of course, I see the benefit of this feature, no doubt. I just want to have the option to steer clear of this, and hopefully have it disabled by default, so it is an opt-in feature.

**Comment by guyinpv** [comment]
Sounds like something where the setting would be on the user accounts themselves. A flag or checkbox of sorts.
On default install, the flag for all new users could be on. And then a system setting could change the default for new users to be off if desired.

**Comment by jonleverrier** [comment]
nice idea @guyinpv - would certainly give more granular control.

**Comment by OptimusCrime** [comment]
It would have to be toggled somewhere if the current behavior (first visit = display welcome screen), because this is simply stored as a boolean value in the settings table. This approach is not expandable to individual users directly.

**Comment by rtripault** [comment]
From reading the involved code source, the feature should already be *almost* possible. 

What you need to do is create a user setting for each user, with `welcome_screen` key and a `true` value (boolean setting) (this can be automated with a plugin when a user is created using `OnUserFormSave` i guess).

The difficult part is that the global (system) setting `welcome_screen` is set to `false` anytime the message is displayed. You would need to create a plugin to change that setting value back to `true` anytime someone visits the "welcome page".

**Comment by OptimusCrime** [comment]
Yeah, the global system setting was what I ment to address.

**Comment by jonleverrier** [comment]
@rtripault this makes sense. 

Out of curiosity, I created a user setting with `welcome_screen` key set to `true` and deleted the global setting from my test installation, hoping that the user setting would be inherited.

It is inherited, after a user views the welcome message `welcome_screen` is set to `false`. Problem is, the welcome message keeps on displaying regardless, because I deleted the global setting :)

**Comment by rtripault** [comment]
Since i was interested in the feature (had that in mind since quite some times but never took the time to give it a try), here a sample plugin that should get you started : https://gist.github.com/rtripault/f948caecd98d01ea59ab9cfe4e729725

**Comment by jonleverrier** [comment]
Good job @rtripault ! Your plugin works perfectly.

As this enhancement can be achieved through a plugin without touching the core - shall I close this issue?

**Comment by rtripault** [comment]
As almost everything in Revo : you can do almost anything without touching the core. So i'd say it's up to you, if you want this shipped within the core.

On a personal preference, i'd like to remove features from the core rather than adding more ;)

**Comment by jonleverrier** [comment]
I agree with you. I'm going to close this issue - feel free to re-open if you feel like the default `welcome_screen` code needs some refactoring.
