### ISSUE TITLE
Items in file tree subfolder are loaded twice, when resource is saved before file tree fully loaded

### ISSUE THREAD

**Issue by itWilllBeOk** [modxcms/revolution#13476]
When I open a resource and save it before the file tree is fully loaded, the resources in the subfolder of the file tree, where the opened resource is located, are loaded and shown twice in the file tree.

### Step to reproduce
- open resource to edit
- before the contents of resource's parent are loaded in file tree, save resource (click on save and shortcut)

Can't pin down the exact moment you have to save, but has to be before (see above).

### Environment
MODX version 2.5.7
Windows 10
Chrome 58.0.3029.110 
Opera 45.0.2552.888

**Comment by alroniks** [comment]
Seems it works fine on 3.x and even on the latest 2.x. Please, feel free to reopen if it is still actual.
