### ISSUE TITLE
xPDOCacheManager's lockFile fails when $_SERVER['SERVER_ADDR'] is an IPv6 address

### ISSUE THREAD

**Issue by ttyiav** [modxcms/revolution#13477]
xPDOCacheManager's lockFile method (called when use_flock is FALSE) generates bad filename when $_SERVER['SERVER_ADDR'] is an IPv6 address. 
https://github.com/modxcms/revolution/blob/7826c3e0ec8425cc92e3650a213e24b38da325ca/core/xpdo/cache/xpdocachemanager.class.php#L279

IPv6 addresses contain ':' symbols which are not allowed on Windows filesystems. 
$tmpLockFile variable could be sanitized in any possible way, for example like here
https://github.com/modxcms/revolution/blob/7826c3e0ec8425cc92e3650a213e24b38da325ca/core/xpdo/cache/xpdocachemanager.class.php#L315 
or with _str_replace()_.

### Environment
Any MODX version containing the xPDOCacheManager::lockFile, 
IPv6 enabled server installation, 
IPv6 client.

**Comment by alroniks** [comment]
As it moved to xPDO, I am closing this one. This closed issue still will be available by the link.
