### ISSUE TITLE
Wrong year in copyright section in README.md

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/revolution#13473]
The current [README.md](https://github.com/modxcms/revolution/blob/ddfbc9e910f38a737e4e80d2fa16ca3d9261ac16/README.md#copyright) has copyright set to 2016. We are currently in 2017.

**Comment by OptimusCrime** [comment]
@Mark-H :O Did you just push that to master :OOOOO

**Comment by Mark-H** [comment]
I wouldn't dare!
