### ISSUE TITLE
Context order not saved

### ISSUE THREAD

**Issue by iamdave210** [modxcms/revolution#13489]
### Summary
When dragging and dropping contexts to change their order in the resource tree the order is not saved and returns to the default order on page refresh.

### Step to reproduce
Create multiple contexts. Try to change their order.

### Observed behavior
Order reverts to previous after page refresh.

### Expected behavior
New order should be saved.

### Environment
MODX 2.5.4, Apache 2.2.15, MySQL 5.5.56, all browsers

**Comment by OptimusCrime** [comment]
Fixed by #13376.

@modxbot close
