### ISSUE TITLE
parser can be null in modScript class

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#13482]
### Summary
Under certain conditions, this code in the modScript.class.php file (line 81), the parser is null and causes a fatal PHP error at the second line below: 

```
 $maxIterations= intval($this->xpdo->getOption('parser_max_iterations',null,10));
 $this->xpdo->parser->processElementTags(
```

### Step to reproduce
This sometimes occurs for me when  a snippet is called with runSnippet()  from a form processing snippet (in MyComponent) and the snippet called with runSnippet() then runs code from an included file, and there are no tags in the output. 

The included code is a build.transport.php file to build an extra. The error only occurs for some extras, but I can't see any reason why. The original snippet runs fine from the command line always, for all extras, probably because it instantiates MODX.

### Solutions

There are two simple solutions:

1) 
```
 $maxIterations= intval($this->xpdo->getOption('parser_max_iterations',null,10));
 $this->xpdo->getParser();
 $this->xpdo->parser->processElementTags(
```

2)
```
 $maxIterations= intval($this->xpdo->getOption('parser_max_iterations',null,10));
 if (!isset($this-xpdo->parser)) {
     $this->xpdo->getParser();
 }
 $this->xpdo->parser->processElementTags(
```

I've tested both, but I'm not sure which one is better.

**Comment by OptimusCrime** [comment]
For simplicity, related code in [modscript.class.php#L80-L90](https://github.com/modxcms/revolution/blob/ba369815b85f32702c009b505c7de35827d19105/core/model/modx/modscript.class.php#L80-L90).

What about:

```
if ($this-xpdo->parser === null) {
     $this->xpdo->getParser();
 }
```

Using isset to check if a instance variable is set is unorthodox (to me).

**Comment by BobRay** [comment]
The problem is that === null will throw an E_NOTICE  error if the variable is ever undefined and the speed difference with isset() is about a millionth of a second.

Using ! isset() is perfect because it returns false if the variable is null or unset, which is exactly what we want. And it's way faster than empty().

Strangely, I edited the post above to take out the first solution after I benchmarked the if(!isset()) test at .00000016 seconds. I saved it but apparently the edit didn't take.

**Comment by snoopdouglas** [comment]
Just encountered this problem as well, and (coincidentally) found the same solution (@BobRay's first one).

Something to note: I firstly tried putting `$this->xpdo->getParser();` at the top of `process()` just below the call to the super. `$this->xpdo->parser` appears to be set to `null` at some point in the following `if (!$this->_processed) { ...` block.

**Comment by OptimusCrime** [comment]
@BobRay The variable can never be undefined? That would lead to a fatal error in the next couple of lines ` $this->xpdo->parser->processElementTags`. As, as far as I see it, the only reason this check is required is to make sure the variable is not `null`, which is expressed much better by a strict comparison, over the use of `isset`. Additionally, as you would like to avoid negating expressions, `is_null` or `=== null` is less confusing than `!isset`.

Finally, the speed is irrelevant here. This is a simple comparison OP no matter which solution you chose, which will use at minimum one clock cycle. Anything that has to do with reading disks (cache) or querying the database is several orders og magnitude slower.

I just ment that if you are going to check if a variable is null, which is what we want here, then `=== null` or `is_null` is much more readable than `isset`, wheras `isset` makes more sense in code such as `isset($_GET['key'])`.

Just my 5 cents.

**Comment by BobRay** [comment]
> The variable can never be undefined? **That would lead to a fatal error in the next couple of lines** 

That would appear to be an  argument for my position.  ;)

I don't feel that strongly about it, but since speed is not an issue, it seems wise to make sure the fatal error you refer to can never occur since the parser variable is neither set, nor received as an argument.  === null wouldn't do that. 

How about !isset() and  a comment?

`/* Make sure we have the parser */`

**Comment by OptimusCrime** [comment]
Submitted PR.

**Comment by BobRay** [comment]
Looks good.

**Comment by OptimusCrime** [comment]
@modxbot open

Lets keep it open until the PR is actually merged.

**Comment by BobRay** [comment]
OK.

**Comment by opengeek** [comment]
This is impossible as far as I can tell. `modElement::process()`, which is called via `parent::process()` in `modScript::process()`, already explicitly calls `getParser()`.

**Comment by BobRay** [comment]
That's what I thought until the error actually occurred every time I ran certain code. 

Snoopdouglas above also encountered the error.

**Comment by opengeek** [comment]
Something has to be unsetting the parser service in that case, or you have multiple instances of modx/xpdo somehow involved. I don't see any other way for it to happen.

**Comment by BobRay** [comment]
Me too, but I couldn't find any evidence of that happening.
