### ISSUE TITLE
False pending changes warning

### ISSUE THREAD

**Issue by davidpede** [modxcms/revolution#13483]
### False pending changes warning when closing a resource
When a resources template is set to 'empty' the user receives a false 'You have changes pending; are you sure you want to cancel?' warning.

### Step to reproduce
1. Set a resources template to 'empty'
2. Save resource
3. Click close

### Observed behavior
User receives a false 'You have changes pending; are you sure you want to cancel?' warning.

### Expected behavior
No warning as resource is saved

### Environment
MODX 2.5.7, all browsers

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @davidpede 

#1point to @jbbuist
