### ISSUE TITLE
Static Resource PDFs do not load on iPhone

### ISSUE THREAD

**Issue by pmacswebteam** [modxcms/revolution#13487]
### Summary
Static Resource PDFs do not load on iPhone. When trying to load the PDF, we get the error "Safari cannot open the page because the network connection was lost", however, the PDF loads fine on desktops.

### Step to reproduce

1. Create a Static Resource
    * Uses Template: (empty)
    * Resource Alias: test
    * Resource Type: Static Resource
    * Content Type: PDF
    * Content Disposition: Inline
1. Save Resource
1. Load website on Safari on iPhone
1. Click the Resource in the navigation
1. Error "Safari cannot open the page because the network connection was lost"

### Observed behavior
We get the error "Safari cannot open the page because the network connection was lost"

### Expected behavior
The PDF should load

### Environment
MODX version 2.5.7
Safari on iOS 10.3.2

**Comment by OptimusCrime** [comment]
What happens if you dont use Content Disposition: Inline?

**Comment by pmacswebteam** [comment]
Hi, when changing Content Disposition to attachment, the same thing happens in mobile. We get the  "Safari cannot open the page because the network connection was lost" error message.

**Comment by pmacswebteam** [comment]
In Chrome on the same iPhone we get the message "There is no Internet connection".

**Comment by OptimusCrime** [comment]
Really weird. Does it work on desktop? I dont have access to a MODX installation right now, but I'd like to double check this and investigate when I have the time. Nice find.

**Comment by iamdave210** [comment]
I don't have this issue in MODX 2.5.4 with iOS 10.3.2. Wonder if maybe it's a server issue.

**Comment by pixelchutes** [comment]
The last time I personally encountered something weird like this I found that the `Content-length` header was being set, but with an invalid file size. Each browser handled this scenario a bit differently. This was custom though, not part of MODX core. Anyway, could be completely unrelated!

@pmacswebteam What do the HTTP headers for the static resource in question look like?

**Comment by devlanda** [comment]
I cannot confirm this issue by following the steps above (MODX 2.5.7-pl). #modxbughunt

Possibly a configuration error in .htaccess?

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @devlanda

**Comment by pmacswebteam** [comment]
Thanks all for your help, @OptimusCrime yes, it works on desktop. It also loads on an Android phone in the Chrome browser, but not in the default Android web browser. We do suspect that this could be a server related issue since they seem to load fine on our production server in mobile, but not on our development server in mobile. We will update this thread if/when we get this issue resolved in case this happens to anyone else for their reference.

Thanks!

**Comment by OptimusCrime** [comment]
No problem. I'll double check this myself when I get the time. I'll look at the behavior.

**Comment by Mark-H** [comment]
I'm going to close this issue for now as it appears to have been a server issue. If the problem continues and it is suggested that it is due to a bug in MODX, feel free to reopen @pmacswebteam.
