### ISSUE TITLE
Show message for no errors in setup

### ISSUE THREAD

**Issue by jcdm** [modxcms/revolution#13484]
### Summary
At the end of the setup process, there's expanders (labelled 'Toggle Success Messages' and 'Toggle Warnings' to show success and error messages. If there are no error messages, a message should be shown that specifically says '[No errors]' otherwise it's a bit ambiguous if there are no errors or if there's just data missing from that area.

### Step to reproduce
Run a successful set up and click the 'Toggle Warnings' messages to expand the errors.

### Observed behaviour
If there's no warnings, it's ambiguous if the link has even worked.

### Expected behaviour
Roll down the error messages and you get a message such as '[No errors to report]'. New lexicon entry perhaps?

### Environment
All MODX versions until now as far as I'm aware.

**Comment by mindeffects** [comment]
You mean this message?

<img width="676" alt="setup_success" src="https://user-images.githubusercontent.com/458619/27966498-bb284988-633f-11e7-80a9-b3623d12bf29.png">

The sentence "Core installation was successful. Click next to complete the installation process." could need a little spacing before.
The "next" could be written like "**Next**". 
Also, if everything went right, those three links below don't need to be shown.

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @mindeffects

**Comment by OptimusCrime** [comment]
I found it really weird that we display success or warnings this way. The entire thing should be redesigned and changed to be less confusing and obscure.

**Comment by jcdm** [comment]
On review my original message wasn't clear enough. It was late here when I wrote it and I should have reviewed it the next day. I've now updated it now for clarity.

@mindeffects my point was never that there was not a success message. It's exactly what you said following your screen shot.

It's weird to have a link that says 'Toggle Warnings' but then when you click that, nothing happens if there were no warnings.

I disagree that the links (or at least some kind of message) shouldn't be shown, but only because that will make it trickier to support people with install issues. If parts of the interface go missing it makes it harder to ask questions about what they saw to help diagnose.

e.g.
"My install didn't work"

"At the end of the install, are there any links at the end to errors or did you just see a success message?" - hard for someone not familiar with the process to know.
vs
"At the end of the install when you click the "Toggle Warnings" message, what do you see?" - very easy to answer concisely whether you've seen it before or not.

Of course, a redesign of this area with these concepts in mind would work too.

**Comment by devlanda** [comment]
The count of lines of Success Messages or Warnings could be shown between parentheses.

**Comment by ilyautkin** [comment]
Related issue: https://github.com/modxcms/revolution/issues/4573

> @Alroniks commented:
> I would prefer to see the full report of installation including warnings and success messages but it should be implemented in the new installation screen, not as a bug.

**Comment by Ibochkarev** [comment]
Improved in 3.x
