### ISSUE TITLE
Session expired after migrate

### ISSUE THREAD

**Issue by MrRoco** [modxcms/revolution#13488]
### Summary
After migrating sites to new environment we keep on getting complains about people being logged out all the time. When they try to log back in they get stuck in a loop.Clearing the browser cache helps for a few days but the problem keeps on coming back.

### Step to reproduce
Migrate sites to new environments

### Observed behavior
After the migration everything works fine, after a few days users get a session expired popup, when trying to log back in, they get stuck in a loop and keep on getting the popup.

### Expected behavior
Being able to login and use the manager till logging out.

### Environment
MODX 2.3+, Modxcloud & nginx, php 5.6 & php 7.1, all

**Comment by Mark-H** [comment]
Tried clearing the cookies? Are the session settings correct (path/httponly/secure)? Paths correct?

**Comment by OptimusCrime** [comment]
I kept getting this error because my site was behind basic auth. Do you use it too?

**Comment by gpsietzema** [comment]
Some additional data/comments-thread from a support thread:

> I haven't tested it with a brand new cloud. After reinstalling the other clouds I did like 200 logins and it didn't happen again though.

What is happening, is that HTTP_MODAUTH is empty when doing an Ajax-request to connectors/index.php

Some things I think could be a reason or related or should be checked: 
- Corrupt MODX core files (reinstall should could fix that) 
- Bad cookies (dunno how they can break or be wrong) 
- Too crowded on the server which somehow might mess up stuff 
- ACL's, but then again, they are able to login, it is just the connectors not working

I had a strange, dunno if related, thing happen: museumstadappingedam.nl (which is session-expired victim), showed a 504 page everywhere and the error.log showed max-execution-time-30secs errors everywhere. It just kept loading all over the place (frontend + manager). I replaced it with 2 day old backup and it didn't fix it. Reinstalling didn't fix it. But when I set it to PHP7.1 it worked again...

> I don't think cookies are the problem here. As for the HTTP_MODAUTH thing, I'm confused. Is that empty when the session expires or always empty? You said it didn't happen again, but that HTTP_MODAUTH is empty, so is that just an unrelated observation?

> In the cases where we got the session_expired modal, we noticed that the HTTP_MODAUTH was empty when doing ajax-requests to the connectors/index.php

> That sounds suspiciously like this might be being caused by a specific MODX extra that has a connector which is not working properly with regard to the HTTP_MODAUTH. Is there a component with a connector common to these sites that has not been updated in a while?

> No, all plugins / extras are up-to-date. Also most plugins don't fire on every manager page, so I'm pretty sure those wouldn't cause an issue. The only one that runs on event 'OnManagerPageBeforeRender' is FormIt, which then runs this code: https://github.com/Sterc/FormIt/blob/develop/core/components/formit/elements/plugins/formit.plugin.php 
Could this be the issue? That for instance some of the $modx methods are not available yet, or that perhaps the OnManagerPageBeforeRender event runs too soon or something?

> I don't think that has anything to do with connectors losing HTTP_MODAUTH, which seems to be the problem here.

![revo-13488-2](https://user-images.githubusercontent.com/381017/27947018-82007806-62f4-11e7-8c1f-e68598b2dca1.jpg)
![revo-13488-1](https://user-images.githubusercontent.com/381017/27947019-822c2dac-62f4-11e7-8442-b2675df89503.jpg)

**Comment by Flowan** [comment]
Confirmed on 2.5.x #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by gpsietzema** [comment]
# Fix this and win an amazing bounty!
- 150 mini KitKats
- 150 mini Bounties
**- A one-night hotel accommodation for the MODX Meetup in Amsterdam on September 21st**

**Comment by Jako** [comment]
Maybe this could help further: If I logout from the MODX backend on an installation that is secured with http_auth, I am logged out of the http_auth too. Since this happens not everytime, I can't tell a way to reproduce this. But I have seen this behaviour quite often. 

Maybe it is a session cookie problem.

**Comment by guyinpv** [comment]
After migration of the site, run the MODX setup and do an upgrade (even if same version).
Clear core/cache, of course.
Clear all sessions/logout all users, bla bla.

What was different in the environment change? PHP/Apache/MySQL/other versions change? The MODX setup should tell you if the environment meets requirements, maybe a PHP or Apache module needs enabled?

Are there any HTTP/HTTPS issues with your links? If a user authenticates over HTTP domain but then some link somewhere switches them to HTTPS, they won't be logged in. Make sure the domain they log in and authenticate with, remains the same throughout their session and doesn't change.

Check error logs. I assume the MODX error log probably doesn't have anything useful, but do look up the PHP and Apache logs.

Check the new environment/host for any "special" performance or other features they have turned on with your account. It could be security related, perhaps mod security settings or automatic free SSL or caching or "tuning" or whatever. If they have any kind of proxy happening with traffic, look for it.

Are you able to create a test install on the same server/environment with a fresh installation and test it that way? If it works, then MODX can run and it's something with the previous configuration. If not, it's something with the host. Analyze the headers and look for anything related to session, cookies, timeouts, etc.

**Comment by sonicpunk** [comment]
#modxbughunt #1point @guyinpv

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @Jako

**Comment by goldsky** [comment]
Check you `session_cookie_domain` in your System Settings.
Try this: `.yourwebsite.com`
Yeah, dot at the front.

**Comment by OptimusCrime** [comment]
@goldsky Shooould really work with the default domain too(?)

**Comment by goldsky** [comment]
yep. proven.
