### ISSUE TITLE
Privacy issue: News feeds in the manager are active by default and phone home to google

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#13498]
### Summary
See next section:

### Why is it needed?
After installing a fresh MODX and logging into the manager, google gets connected via feedburner. So before a website is even started being build it is already "in the index". This causes some privacy issues because maybe the URL of the website should not be made public or for other reason. Having the feeds turned on by default is done without asking the user and getting his OK. 

### Related issue(s)/PR(s)
none

### Step to reproduce
Install MODX locally and have a network monitor (like little snitch on macOS) running. It will report outgoing connections like "www4.l.google.com" and also to "develop.modx.com" or "api.modx.com"

### Observed behavior
When having the feeds are turned of no connection are being made. Yeah! ;-)

### Expected behavior
Don't connect any "other" servers without asking firat.

### Environment
any (except when behind a strong firewall ;-) )

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @mindeffects

**Comment by Omeryl** [comment]
Just putting my thoughts down.

1. The URL of the website isn't "exposed," the IP of the server definitely is. But with proper vhosting they won't just see the site. 
2. We could definitely have an opt-in, that idea is cool.
3. Any other servers? Including *.modx.com? How might we do that?

**Comment by OptimusCrime** [comment]
Agree with @Omeryl

**Comment by OptimusCrime** [comment]
Anyone else or can this be closed?

**Comment by mindeffects** [comment]
OK, can be closed. Thanks!

**Comment by OptimusCrime** [comment]
@modxbot close
