### ISSUE TITLE
Media browser creating directory not always refreshing the tree correctly

### ISSUE THREAD

**Issue by pixelive** [modxcms/revolution#13495]
### Summary
Media browser creating directory not always refreshing the tree correctly.

### Step to reproduce
Create a new directory and leave the parent directory empty.

### Observed behavior
Not refreshing the tree at all.

### Expected behavior
Should refresh the tree.

### Environment
-

**Comment by rtripault** [comment]
Confirmed on 2.x branch

**Comment by Flowan** [comment]
I'm going to try and fix this today. #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @rtripault

**Comment by Alroniks** [comment]
Merged, so closing.
