### ISSUE TITLE
Quick create resource does not show new resource in tree if it's the first child

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#13492]
### Summary
Quick creating a resource does not show the newly created resource in the tree if it's the first child of its parent.

### Step to reproduce
Quick create a resource in a resource that has no children.

### Observed behavior
The parent does not expand, so the newly created resource is not shown in the tree.

### Expected behavior
The parent should expand and the newly created resource should be shown in the tree.

### Environment
MODX 2.5.8-dev

**Comment by rtripault** [comment]
Confirmed on 2.x branch

**Comment by rtripault** [comment]
Working on it

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @rtripault
