### ISSUE TITLE
Media browser active state problem in tree

### ISSUE THREAD

**Issue by pixelive** [modxcms/revolution#13494]
### Summary
Media browser active state problem in tree.

### Step to reproduce
Create a directory with no subfolders, click the directory once, then click another directory and after that switch back. You cannot select folder anymore.

### Observed behavior
You cannot select a childless directory if it is clicked once.

### Expected behavior
Selecting a childless directory should be possible.

### Environment
-

**Comment by rtripault** [comment]
Confirmed on 2.x branch, with Chrome (if relevant)

**Comment by Flowan** [comment]
Fixed the issue, see pr https://github.com/modxcms/revolution/pull/13496 #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @rtripault

**Comment by sdrenth** [comment]
Also confirmed on 2.5.x branch

**Comment by Alroniks** [comment]
Merged, so closing.
