### ISSUE TITLE
Package Manager modal popup doesn't display right title during download

### ISSUE THREAD

**Issue by devlanda** [modxcms/revolution#13503]
### Summary
The Package Manager modal popup doesn't display right title.

### Step to reproduce
Without page reloading I installed multiple Extra's, like FormIt, TinyMCE Rich Text Editor and pdoTools. Thereafter, I downloaded package 'Collections'. In the console window title (modal popup) it displays still the title of installing FormIt.

### Observed behavior
Wrong title is displayed in console window title (modal).

<img width="1499" alt="package manager modal popup" src="https://user-images.githubusercontent.com/15090785/27953921-f152c038-630d-11e7-82b5-1a20220df6b2.png">

### Expected behavior
It should display the title 'Please wait...'.

### Environment
MODX 2.5.8-dev
Apache 2.4.25
PHP 7.1.6
MySQL 5.7.18
Browser Chrome

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @devlanda

This was only related to sterc-extras right?

**Comment by devlanda** [comment]
I guess that is a different error. I will try that too.

**Comment by rtripault** [comment]
I'm able to reproduce on 2.x with FormIt. I believe this is related to installation/setup options (trying to validate that idea)

**Comment by rtripault** [comment]
Here is the issue https://github.com/Sterc/FormIt/blob/develop/_build/setup.options.php#L50

Somehow not related to the core (albeit a fix could probably be provided)

**Comment by gpsietzema** [comment]
Thanks @rtripault 

#modxbughunt #1point to @rtripault
