### ISSUE TITLE
Access control page view is broken #modxbughunt

### ISSUE THREAD

**Issue by lawrenz1337** [modxcms/revolution#13511]
### Summary
When I pull the side slider it collapses the wrong way. Also the button is under the slider

### Step to reproduce
![](http://joxi.net/VrwnpZncKOKDVA.jpg)
Open Access control page and pull the side slider.

### Observed behavior
It collapsed to the right

### Expected behavior
It should move the slider accordingly to my mouse movements

### Environment
MODx 2.5.5

**Comment by Finetuned** [comment]
"I'm going to try and fix this today."

**Comment by sonicpunk** [comment]
#modxbughunt #1point

**Comment by pixelchutes** [comment]
Fixed by #13555
