### ISSUE TITLE
Quick resource update breaks publish date and unpublish date depending on manager_date_format and manager_time_format

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#13526]
### Summary
Quick updating a resource that has a publish date or unpublish date set breaks this data - depending on the system settings manager_date_format and manager_time_format.

### Step to reproduce
Make sure manager_time_format is **not** set to "Y-m-d" and / or manager_time_format is **not** set to "H:i:s" (default after install should be "Y-m-d" and "g:i a").

Set a publish (and / or unpublish) date for a resource. Quick update the resource.

### Observed behavior
The publish and unpublish dates should be the same as before.

### Expected behavior
The publish and unpublish dates are empty or "1970-01-01 12:00 am".

### Environment
MODX 2.5.8-dev

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/1913250/27967458-6ce8ad36-6343-11e7-8023-c748a74c44a8.gif)

**Comment by labr1005** [comment]
With manager_time_format set to "Y-m-d" and manager_time_format to "H:i:s" quick updating works fine.

**Comment by Flowan** [comment]
Confirmed this is not working in 2.5.x I will have a look at this. #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @Flowan

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @labr1005

**Comment by labr1005** [comment]
This might be related and also fix https://github.com/modxcms/revolution/issues/11891
