### ISSUE TITLE
[BUG/FIX] Copying 'ht.access' to '.htaccess' = 500 Internal Server Error

### ISSUE THREAD

**Issue by stevenventimiglia** [modxcms/revolution#13549]
**Problem:**

".htaccess" - once copied from "ht.access" - would cause MODX to throw me a 500 Internal Server Error.

**Solution:**  

On last line of the file...
php_value date.timezone 'America/New_York''

I removed the extra single quotation mark...
php_value date.timezone 'America/New_York'

**Version:**

MODX Revolution 2.5.7-pl

**Source:**

https://modx.com/download

**Comment by Mark-H** [comment]
That line does not seem to be in the default ht.access? https://github.com/modxcms/revolution/blob/2.x/ht.access

**Comment by Omeryl** [comment]
Double confirmed, this isn't in the ht.access or the distributions. Looks like you or a colleague added it.

**Comment by stevenventimiglia** [comment]
Odd.  Could have been some automated mumbo jumbo involving writing an .htaccess file to the dev server.  We uncompressed, installed, went to copy file, and "boom!".

I'm guessing this issue can be closed, and I'll smack our server admin with a JIRA issue of his own.

Thanks.

**Comment by OptimusCrime** [comment]
@modxbot close
