### ISSUE TITLE
Svg support for image TV preview

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#13556]
### Summary
The image TV preview does not support svg.

### Step to reproduce
Add "svg" to the system setting "upload_images"  and your media source's "imageExtensions" setting.
Upload and choose a svg in your image TV. 

### Observed behavior
The image TV preview does not show (a preview of) the svg.

<img width="1279" alt="bildschirmfoto 2017-07-18 um 19 09 41" src="https://user-images.githubusercontent.com/1913250/28330118-b1fd675c-6bec-11e7-855b-ca83d777213b.png">

### Expected behavior
The image TV preview should show (a preview of) the svg.

### Environment
MODX 2.5.8-dev
Apache/2.2.29 (Unix)
PHP 7.0.8

**Comment by labr1005** [comment]
https://github.com/modxcms/revolution/pull/13547

**Comment by OptimusCrime** [comment]
Not sure if I understand? Did you create this because no issue was posted about SVG preview in the manager? Or did the PR not work?

**Comment by labr1005** [comment]
The referenced PR only fixes SVG support in the MODX Browser and the Files Tree - not for image TVs. If the PR gets accepted and merged, this could/should/will be a new issue.

**Comment by labr1005** [comment]
The referenced PR only fixes SVG support in the MODX Browser and the Files Tree - not for image TVs. If the PR gets accepted and merged, this could/should/will be a new issue.

**Comment by OptimusCrime** [comment]
Ah, okey. That is fine. This should be there then, as this is separate. Good work :)

**Comment by JoshuaLuckers** [comment]
The Image TV uses phpthumb for the preview thumbnails as can be seen here:
https://github.com/modxcms/revolution/blob/21c52bc479282964201a27123277decd62c7174c/manager/templates/default/element/tv/renders/input/image.tpl#L3
and
https://github.com/modxcms/revolution/blob/21c52bc479282964201a27123277decd62c7174c/manager/templates/default/element/tv/renders/input/image.tpl#L51

The SVG preview in, for example, the tree is handled differently:
https://github.com/modxcms/revolution/blob/21c52bc479282964201a27123277decd62c7174c/core/model/modx/sources/modfilemediasource.class.php#L236-L251

**Comment by Ibochkarev** [comment]
Fixed #15865

**Comment by eire69k** [comment]
Hi @JoshuaLuckers,
this fix was for Modx Revolution 2.5.8-dev. Is it possible to find a corresponding fix for Modx 3.0 - 3.0.2?
Because I have the same problem with Modx 3. - BTW. the files which are listed above do not exist in Modx 3.
(btw 2: the SVG files are shown in my collection view but not on my TV.)
