### ISSUE TITLE
Can't change value in system settings

### ISSUE THREAD

**Issue by KenjiroArt** [modxcms/revolution#13562]
### Summary
On an iPad Air2 iOs10, When logged into the manager, I'm unable to change settings under system settings. Happens in chrome and safari.

### Step to reproduce

1. Log into manager on an iPad Air2;
2. Go to system settings;
3. Try to change any setting.

### Observed behavior
You should be unable to change settings here.

### Expected behavior
I should be able to change values.

### Environment
MODX Revo 2.5.7. On iOs10.3.2

**Comment by OptimusCrime** [comment]
Pretty sure this is a known problem. The manager does not play nicely with touch devices like that. I could not get much to work in my iPhone when I tried.

**Comment by JoshuaLuckers** [comment]
In 3.x System Settings can be edited on devices that don't support double click using the new "action columns" introduced in PR #14806
