### ISSUE TITLE
[BUG] Security > Resource Groups Menu entry missing

### ISSUE THREAD

**Issue by 749** [modxcms/revolution#13567]
### Summary
The Menu entry to get to the Resource Groups Page is missing.
Accessing the page directly with ?a=security/resourcegroup works...

### Step to reproduce
Fresh Install of Modx
Login as Sudo User
Goto Security Menu

### Observed behavior
Resource Groups is not there

### Expected behavior
Menu Entry should be present

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.
ModX Revo 2.5.7
Language: de-DE
Browser: Edge, Firefox and Chrome
Nginx: 1.10.3
mariaDB: 5.5.57-0+deb7u1-log

**Comment by Mark-H** [comment]
Resource Groups is under Content, not Security - the security menu doesn't exist anymore since 2.3 or 2.4?

**Comment by 749** [comment]
Oh! sorry i figured it would be in the cog menu then.
Thanks for letting me know
