### ISSUE TITLE
modphpmailer SMTP class not loaded resulting in error

### ISSUE THREAD

**Issue by bvandorp** [modxcms/revolution#13570]
### Summary
While using SMTP (via Mailgun) for our mails send out of MODX we normally have no issues whatsoever. But we've encountered something strange while installing the website on a IIS webserver (hosted by Vevida).

When sending email (formit email hook) we encountered:
`Fatal error: Uncaught Error: Call to undefined method SMTP::getServerExt()`

So it seems the smtp class was not loaded and after some investigation I altered [revolution/core/model/modx/mail/modphpmailer.class.php](https://github.com/modxcms/revolution/blob/2.x/core/model/modx/mail/modphpmailer.class.php)
I've added
`require_once $modx->getOption('core_path') . 'model/modx/mail/phpmailer/class.smtp.php';`
after (at line 26):
`require_once $modx->getOption('core_path') . 'model/modx/mail/phpmailer/class.phpmailer.php';`
and now all seems fine.
But the strange thing is that I did not encounter this behavior on our own development environment.

### Environment
MODX version 2.5.7
PHP Version 7.0.21
MySQL 10.1.25-MariaDB
Windows NT NET3-NL-IIS-261 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64

If any extra data is needed, just let me know.

**Comment by JoshuaLuckers** [comment]
Is this issue still present in a more recent release? And if yes, would you like to open a PR with your fix?

**Comment by bvandorp** [comment]
Hi Joshua, 

I don't have a environment right now compared to what I was installing the website on then so I can't say if this is still an issue but, I haven't ever encountered it again and it seems like I am the only one that ever encountered this. So I think it's safe to assume this won't need any further action.
