### ISSUE TITLE
A more extended core modx development manual

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#13579]
## Summary
I think some key documentation is missing for developers who are working on the MODX core. Therefore I think it would be handy to perhaps create a MODX Core development manual, add a short description in the repo README or to extend the becoming a contributor documentation (https://docs.modx.com/community/contribute/becoming-a-contributor) depending on the amount of documentation that will be added.

### Subjects
I think at least the following subjects should be documented somewhere to make it easier for developers to work on the core of MODX. 

- How to add new lexicons and how lexicons are managed within the core of MODX and how it is translated with Crowdin. Complete description of the translations workflow.
- How to edit core JS/CSS and to rebuild minified files using grunt build in /_build/templates/default/

Where do you guys think this documentation should be added and can you think of any other subjects that might need to be documented for MODX core developers?

**Comment by Mark-H** [comment]
The MODX.org site that [we're drafting content for](https://docs.google.com/document/d/1eG9j51Nzyip_l6AL8H1S8zbzaP1TTz8tij4J0qcbS9U/edit?usp=sharing) has a contribution section, but for in-depth instructions and examples I think the documentation is still the best place.

**Comment by sdrenth** [comment]
I think adding a section **Core development** at the docs here would be logic and quite easy to find:
https://docs.modx.com/revolution/2.x/

**Comment by alroniks** [comment]
@Ibochkarev Have a look, please. If you can create a skeleton of such a document, I will contribute and fill in the details.

**Comment by Ibochkarev** [comment]
@sdrenth https://docs.modx.com/current/en/contribute/code

![изображение](https://user-images.githubusercontent.com/2138260/112245693-92ff4100-8c7b-11eb-85db-2289c4b3b286.png)

This section has been seriously revised and rewritten @Mark-H , so I vote to close this request.

**Comment by alroniks** [comment]
Yep, it covers the main topic and it can be improved, but the issue solved.
