### ISSUE TITLE
After Clearing cache - 500 error

### ISSUE THREAD

**Issue by dancalder** [modxcms/revolution#13595]
Each time we clear the cache we get a 500 error until we refresh a page 3 times.
Stack trace:
#0 /home/a1build/public_html/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(216): Sabberworm\CSS\Parser->parseCharacter(false)
#1 /home/a1build/public_html/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(400): Sabberworm\CSS\Parser->parseStringValue()
#2 /home/a1build/public_html/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(357): Sabberworm\CSS\Parser->parsePrimitiveValue()
#3 /home/a1build/public_html/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(322): Sabberworm\CSS\Parser->parseValue(Array)
#4 /home/a1build/public_html/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php(289): Sabber in /home/a1build/public_html/core/components/minifyx/munee/vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php on line 253

**Comment by OptimusCrime** [comment]
This seem to be related to the component named minifyx, not the MODX core. Report the issue in their own GitHub repository.

@modxbot close

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/error-500-on-cache-clear/2587/5
