### ISSUE TITLE
The modX::addEventListener method is not fixed

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#13608]
### Summary
My fixes from the [PR](https://github.com/modxcms/revolution/pull/13124) are not applied to the 2.5.x branch. So the addEventListener and removeEventListener methods don't work correctly.

### Step to reproduce
Try to call the $modx->addEventListener('OnHandleRequest', $pluginId).

**Comment by OptimusCrime** [comment]
You sat the PR taget to 2.x. However, as this is a bugfix, it should have been 2.5.x.

**Comment by sergant210** [comment]
Ok. How fix it?

P.S. I don't understand what for brach 2.x  is needed?

**Comment by rthrash** [comment]
Thank you very much for your PR @sergant210. :)

2.x is for the next minor release which contains new features and functionality, which will be released as 2.6. 

2.5.x is where bug fixes should be targeted.

**Comment by pixelchutes** [comment]
Considering the public API method signature was changed in your PR, `2.x` was probably the correct target branch for this fix. I don't believe this will be cherry-picked into `2.5.x` at this point. I will be closing this issue, but please continue the discussion here as needed.
