### ISSUE TITLE
[ BUG ] Custom folder location of "manager menu item" lost after upgrade

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13615]
### Summary
If the top menu in the manager is customised and default manager items are moved into different folders, when upgrading, these changes are lost, and default manager items "default" to their natural state.

### Step to reproduce

1. Install a vanilla version of MODX 2.5.8
2. Go to system menu and click on menus
3. Expand the Extras folder, drag the menu item "Installer" into the Manage folder (as an example)
4. Navigate back to the dash board, and check that the Installer is now in the Manage folder
5. Logout and upgrade to MODX 2.6 (in this example, I upgraded through MODX Cloud)

### Observed behavior
After upgrading, the Installer menu item has moved back into the Extras menu folder

### Expected behavior
To respect the custom location I set in the Menus system setting

**Comment by eighthday** [comment]
I have the same problem when upgrading from any version of Modx.

**Comment by jonleverrier** [comment]
Closing because I believe this is something possibly related to MODX Cloud install updates. I can't reproduce updating installations manually.
