### ISSUE TITLE
switching language in process of setup

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#13611]
### Summary
Setup switching language during installation or updating modx

### Step to reproduce
Install or update modx with Russian language. During the installation, the Russian language is switched to English language.
on page /setup/index.php?action=install - Ru
on page /setup/index.php?action=complete - Eng

### Observed behavior
![jamwsmk3mm](https://user-images.githubusercontent.com/1703670/30584986-174132e2-9d34-11e7-98d3-e4c6507fdce7.gif)

### Expected behavior
Does not switch language during installation or updating modx.

### Environment
MODX 2.5.7 and above.

**Comment by sdrenth** [comment]
@meshkov I'm going to try and fix this today #modxbughunt

**Comment by OptimusCrime** [comment]
@modxbot close
