### ISSUE TITLE
ACL - Remove Access Policy defaults to sudo user

### ISSUE THREAD

**Issue by natedin** [modxcms/revolution#13616]
If a user assigned to a user group which then has an access policy deleted, it defaults to a sudo user.

### Step to reproduce
Access Control Lists > Create New User Group > Add User to group > Update User Group > Under Permissions tab, Context sub-tab add Context access policy to User Group 

Cog (system menu) > Access Control Lists > Access Policies > Delete the policy you added to the above User Groups context access, the users in the Group will now have sudo access

### Environment
MODX 2.5.8

**Comment by wuuti** [comment]
@natedin I can't reproduce that. Despite the fact, that your steps to reproduce might be more detailed, the conclusion does not make sense to me. Sudo is a flag for a user and has nothing to do with user groups and permissions. If the user had sudo access after your steps, their user profiles needed to have changed. Maybe you are mixing with Super-User _role_ here?

**Comment by natedin** [comment]
I've just tried again and failed to reproduce it too, must of been a one off / session problem
