### ISSUE TITLE
2.5.8 - title of buttongroup-xtype unvisible, because of line-height:0

### ISSUE THREAD

**Issue by Bruno17** [modxcms/revolution#13612]
### Summary
the line-height of 
```
.x-toolbar td, .x-toolbar span, .x-toolbar input, .x-toolbar div, .x-toolbar select, .x-toolbar label
```
has changed from 1 to 0, which results in unvisible titles in buttongroups.

### Step to reproduce
See filter- or actions- buttongroups for example at above MIGX-grids.

### Observed behavior
titles of buttongroups are unvisible

### Expected behavior
buttongroup - titles should be visible.

### Environment
MODX 2.5.8

**Comment by OptimusCrime** [comment]
Can you post a image illustrating this? I have never used MIGX and I am not sure how those button groups looks. Does this result in problems in the MODX core or only extras?

**Comment by Bruno17** [comment]
![image](https://user-images.githubusercontent.com/148223/30596032-453f47c8-9d53-11e7-9990-79ebba9159ce.png)
![image](https://user-images.githubusercontent.com/148223/30596101-7bfac1ca-9d53-11e7-819f-c4b0be85dd59.png)

**Comment by Bruno17** [comment]
Not sure, if they are used anywhere else. This is just xtype:buttongroup and I think the title should be visible by default, if used anywhere.

**Comment by Alroniks** [comment]
It seems that it was merged, so I am closing it. Feel free to reopen.
