### ISSUE TITLE
[FEATURE] Trash resources

### ISSUE THREAD

**Issue by pixelive** [modxcms/revolution#13617]
### Summary
Being able to permanently delete a resource without clicking the trash icon. Maybe we can add another option in the context menu called `Permanently delete`?. Or just show the option once a resource is already on `deleted = 1`. 

It would also be useful if the trash icon shows which resources will be deleted if clicked.

**Comment by wuuti** [comment]
@pixelive There is PR request (still needs some TLC) open covering deleted resources: https://github.com/modxcms/revolution/pull/13515 

Besides that, the idea to show the permanently remove on deleted resources' context menu sounds good for me.

**Comment by pixelive** [comment]
@wuuti awesome!

**Comment by wuuti** [comment]
Renewed https://github.com/modxcms/revolution/pull/13764

**Comment by alroniks** [comment]
The feature already implemented so I am closing the issue.
