### ISSUE TITLE
Saving a page containing an image does not work in firefox

### ISSUE THREAD

**Issue by janwidmer** [modxcms/revolution#13624]
### Summary
When saving a page after adding an image, the loading bar stays forever because a JS Exception happens. The Problem only occurs in Firefox (vs 56) on Windows (10)

### Step to reproduce

1. Open a page in the manager
2. Add an image within the content or as a template variable
3. click on the save button

### Observed behavior
The loading bar stays forever, the changes do not get saved. The following js error is thrown in the console:
![modx-tiny-mce-error](https://user-images.githubusercontent.com/3381820/31122809-9da1caae-a83d-11e7-8fed-9d7af9819052.png)

### Expected behavior
The saving works

### Environment
MODX version 2.5.8, Apache/2.4, mysql version 10.1-MariaDB, Firefox vs. 56, Windows 10

**Comment by Mark-H** [comment]
This appears to be a tinymce issue. Had a modmore client last week with the
same issue, and there's a few forum posts about it, but other than advising
to switch to a different RTE I haven't found a fix for it yet.

Op 3 okt. 2017 1:25 p.m. schreef "Jan Widmer" <notifications@github.com>:

**Comment by OptimusCrime** [comment]
Indeed. This does not look like a MODX core error. Is this the TinyMCE or tinymce-rte extra?

**Comment by matdave** [comment]
> Indeed. This does not look like a MODX core error. Is this the TinyMCE or tinymce-rte extra?
It looks like old TinyMCE, @janwidmer I would recommend upgrading to the new TinyMCE RTE.  It works much better in modern browsers.

**Comment by janwidmer** [comment]
ok I will see if I can do an update

**Comment by alroniks** [comment]
Closing because it's unrelated to MODX directly. Feel free to reopen.
