### ISSUE TITLE
Save, Save and Close of chunks not working version  2.5.8

### ISSUE THREAD

**Issue by mikegomy** [modxcms/revolution#13621]
### Summary
Editing and saving of chunks not working in version 2.5.8 but works as expected in version 2.5.6.
The problem is intermittent.

### Step to reproduce
Edit a chunk by clicking on the name, or right click and select either  Edit Chunk or Quick Update Chunk.
Make some changes.
Click on Save or on Save And Close. 

### Observed behavior
The expected "Save successful" message does not appear. 
With "Save And Close" the edit session does not close.
After closing the session manually and reopening it, the original text is back without the changes made.
(Similarly, when creating a new chunk.  Clicking on Save does not cause the new name to appear in the list of chunks.  After closing, the newly created chunk still does not exist.)

### Expected behavior
The "Save successful" message should appear. 
"Save And Close" should close the session.
Changes should be saved.

### Environment
MODX version: MODX Revolution 2.5.8-pl (traditional)
 apache/nginx and version:   2.4.27 
 mysql version:  10.0.31-MariaDB-cll-lve 
browser: Chrome

**Comment by OptimusCrime** [comment]
Anything in your error logs (MODX or PHP)?. I am unable to reproduce this here.

**Comment by mikegomy** [comment]
Hello,

The support guys of the hosting company  did the following and the problem
has gone away for a few days now.  >>>>  "I have disabled mod_security on
your domain now. I added SecFilterEngine Off to the .htaccess"

Does that shed any light on the subject?

Best regards,
Mike Montgomery
Give more than you can afford. Take less than you need. Leave every
situation better than you found it.

**Comment by mikegomy** [comment]
Hello again,

I had reported it to the hosting server guys because an additional symptom
was that I was getting "Your connection to this server has been blocked in
this server's firewall."  This happened soon after the chunk failed to be
saved.  They removed my IP address from the block list a few times, but the
error kept coming back.

Both the problem of failing to save and the blocking have stopped since
they made the changes mentioned.

Best regards,
Mike Montgomery
Give more than you can afford. Take less than you need. Leave every
situation better than you found it.

**Comment by OptimusCrime** [comment]
A very strict mod_security configuration causes problems with MODX. This is a known problem, and is stated in the [installation documentation](https://docs.modx.com/revolution/2.x/getting-started/installation/basic-installation/installation-on-a-server-running-modsecurity). Additionally, if the connection is blocked by the server's firewall, that is an other issue altogether. Both of these are _not_ related to the MODX core, but are problematic server configurations.

**Comment by mikegomy** [comment]
Hello,

Thanks for the info.  The installation was entirely automated via CPANEL
and Softaculous.  Softaculous goes through quite a lengthy list of checks
but did not report on this non-compliance.

Best regards,
Mike Montgomery
Give more than you can afford. Take less than you need. Leave every
situation better than you found it.

**Comment by Mark-H** [comment]
The behaviour you describe with chunks not saving or closing seem to be a result of the request being blocked by mod security. The save doesn't receive a success message, so it doesn't show the success/close the window. There's likely something in your chunk that triggers a specific set of mod security rules.

Getting blocked on the firewall is also a common result of mod security rules; once you trigger a rule X times within X minutes, your IP gets blocked. 

One way to prevent mod security issues is to have the server folks whitelist the manager and connectors directory. That way you still have the protection on the frontend, but don't have troubles running the manager. 

I'm closing this issue as it doesn't appear to be a bug in MODX. There are many forum threads about mod security if you'd like more background or other ideas on dealing with it.
