### ISSUE TITLE
[2.5.8] Endless refresh loop when error.log gets too big

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#13631]
### Summary
If the MODX `error.log` gets too large to view, the current fallback option is to display a download button to pull down the large log file vs. showing the entire contents client-side.

However, I believe since #13560, this now results in an "endless loop," constantly refreshing the Error Log page if the log file gets too big.

### Step to reproduce
1. For example, fill your `error.log` to 10MB in size (or whatever the threshold is).
2. Browse to Error Log page in MODX manager
3. Watch as the page gets caught in a never-ending refresh loop.

### Observed behavior
Page refreshes, over and over.

### Expected behavior
No refresh should happen.

### Related
#13560 /cc @bezumkin @Alroniks 

### Environment
MODX 2.5.8-pl, Chrome v63 / macOS

**Comment by Jako** [comment]
Fixed by #13632
