### ISSUE TITLE
Fatal error: Class 'Smarty_Internal_Compile_foreach' not found Modx Install

### ISSUE THREAD

**Issue by amcikkerim** [modxcms/revolution#13638]
### Summary
This is the error code:
Fatal error: Class 'Smarty_Internal_Compile_foreach' not found in /kunden/175516_65428/webseiten/dev/modx-2.5.8-pl/core/model/smarty/sysplugins/smarty_internal_templatecompilerbase.php on line 750

I get this each time I type in the Admin fields (Admin username, email, password) in the pre-install process. After that I get this error line and nothing happens.
Everything before worked. Connection to the db worked....

Didn't find anything in the net about this error line. I am trying to install modx 2.5.8 in a sub directory on my site to do a new design.

I hope that someone has a clue about this annoying error in the install process.

**Comment by OptimusCrime** [comment]
Sounds like a corrupt installation. Are you sure you got all the files where they should be? Try to reupload the files and rerun the setup.

**Comment by OptimusCrime** [comment]
Closing this as error with setup, rather than a MODX issue. Feel free to comment or reopen.

@modxbot close
