### ISSUE TITLE
Remove maxWidth from west/east splitbar

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#13637]
### Summary
According to the extjs docs, the max-Width for the splitbar is 2000px. Setting a max-width is optional. 

https://github.com/modxcms/revolution/blob/31e663b05930373e4ffd5eb60ba1ce4c8f7f4980/manager/assets/modext/core/modx.layout.js#L144

sets this value to 800.

### Step to reproduce
Move the splitbar to the right.

### Observed behavior
You can't move the splitbar beyond the 800px limit.

### Expected behavior
I can see no apparent need to do so. Removing this property would give the user the ability to decide whats appropriate. 

If there are use cases where this would destroy something, then there should at least be a system setting that controls that behaviour.

### Reasons why this is important for me.
The western region can be used for more things than displaying resource, elements and files. 

Examples are alternative views for the file browser, a preview function , etc.

Removing unnecessary restrictions will make it easier to work with this region. 

### Environment
Latest MODx version and all versions before.

**Comment by Mark-H** [comment]
I've seen your slack messages for what you're trying to do, and I'm not against making that better :D

**Comment by Finetuned** [comment]
modxbughunt#3

**Comment by Mark-H** [comment]
Fixed in #13756
