### ISSUE TITLE
site_status = 0 has no effect for anonymous users when session_enabled = 0

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#13630]
### Summary
site_status = 0 doesn't show the site_unavailable_page for anonymous users when session_enabled = 0.

### Step to reproduce
Set the system setting site_status = 0.
Add the web context setting session_enabled = 0.

### Observed behavior
Anonymous users can browse the website.

### Expected behavior
Anonymous users should see the site_unavailable_page.

### Environment
MODX 2.5.7

**Comment by sottwell** [comment]
In 2.5.8 it's called anonymous_sessions, otherwise, what he said.

**Comment by labr1005** [comment]
@opengeek wrote on Slack:

> yeah,
>
> I see the bug immediately looking at the code
>
> if there is no session it assumes permission
>
> https://github.com/modxcms/revolution/blob/5d7bc87ce01654bef3c9da28e891d08b384d7465/core/model/modx/modx.class.php#L2155
>
> hasPermission will always return true if sessions are disabled
>
> if it is in SESSION_STATE_INITIALIZED
>
> which seems more like the actual bug here
>
> if session_enabled is false, that should be SESSION_STATE_UNAVAILABLE

**Comment by opengeek** [comment]
FWIW, this effects the behavior of `site_status` using either `session_enabled = 0` or `anonymous_sessions = 0`.

**Comment by Jako** [comment]
Fixed by #13635
