### ISSUE TITLE
Feature Request: Expand Categories of Elements When They Are Nested for System Events

### ISSUE THREAD

**Issue by playcock** [modxcms/revolution#13642]
### Summary
Expand Categories of Elements When They Are Nested for System Events

### Step to reproduce
When using Ext.getCmp, the only options for categories that I am able to retrieve for each of the Elements are:

- modx-template-category
- modx-chunk-category
- modx-snippet-category
- modx-plugin-category
- modx-tv-category

### Expected behavior
I would like to see these categories expanded to include their parent categories when they are nested and be able to retrieve them with Ext.getCmp and/or by other means. I basically would like to retrieve the category hierarchy of the immediate category instead of just be limited to retrieving the immediate category, please.

### Environment
MODX 2.5+

**Comment by Mark-H** [comment]
It's probably cause I'm late here, but I honestly don't know what you're asking for... Ext.getCmp will load anything by its ID, so are you saying some element you're looking to interact with doesn't have an ID while it should?

**Comment by playcock** [comment]
For example purposes, let's say I created several chunks and have created a category for them called "Custom". Later on, I create even more chunks and assign them to "Custom" category. Many of the chunks in the "Custom" category could be grouped together in different sub-categories inside the "Custom" category. So now, I have a category structure like this:

Custom>Forms
Custom>Functions
Custom>Forms>Commercial
Custom>Forms>Public

So when I run `Ext.getCmp(config.categoryInput);` I am only getting the closest category that the chunk belongs to and not getting any of the Categories about the subcategory. For instance, I only get "Public" back, but I don't get all the categories back, like that Public is a subcategory of Forms, which is a subcategory of Custom.

Being able to get the whole of the categories and subcategories would be nice to have when saving the modx elements as static files into a server directory structure that match how the elements are nested into the categories and subcategories in the CMS.

**Comment by OptimusCrime** [comment]
But this depends a lot more on the ExtJS code for a TreeElement than MODX code? Could you not iterate the parents? Are there other examples of MODX code delivering APIs for anything similar to this?

**Comment by playcock** [comment]
What brought this request up, was that I was looking into using the [StaticSaver](https://docs.modx.com/extras/revo/staticsaver) MODX extra. 

In the js/staticsaver.js, the extra is setting a categoryInput variable off of running `Ext.getCmp(config.categoryInput)`. This brought me to go down the rabbit hole, as well as researching, how I could set up the server directory structure to match what the category structure is in MODX for the elements. I could not find out how to set a full path for the static files being created with what I could find available to use.For example, I wanted the server directory path to be Custom/Forms/Public if that is how I have it nested in the CMS. I am under the impression that there needs to be something in MODfor creating a new setting, like modx-chunk-category-fullpath, or an option/param that i can pass to the existing setting to get the full path that I would like.

**Comment by alroniks** [comment]
I am not sure that MODX (core) responsible for this. It is possible to get the full path for category using a processor but it should be done from StaticSaver plugin side, not from MODX.

**Comment by alroniks** [comment]
I tend to close as not fully clear. Reopen if needed.
