### ISSUE TITLE
Feature Request: Add column with user_id to modx_session - table

### ISSUE THREAD

**Issue by Bruno17** [modxcms/revolution#13645]
### Summary
Add a new column to modx_session - table with user_id. This way, it would be possible to delete specific sessions of specific users.

### Step to reproduce
How to reproduce the issue, including custom code if needed.

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by OptimusCrime** [comment]
I thought the same session id was used when one user changed `user_id`? Like when a user logs in or logs out? How would this handle that?

**Comment by Bruno17** [comment]
you get a new session id, each time you login again. So, when you logout and login with another user or even with the same user at the same machine/browser, you get a new session id, also when you login on different machines/browsers at the same time, you get multiple session ids.
I think, this would mean, each session id in the session-table belongs to exactly one user.

**Comment by OptimusCrime** [comment]
This means this is doable without too much hacking and changing in the core?

**Comment by Bruno17** [comment]
@OptimusCrime you are right. 
If you login with different users on the same browser, the same session-item is reused. Means, this idea wouldn't work, as i was hoping.
