### ISSUE TITLE
Map file issue since MODX 2.6-dev

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13656]
### Summary
Testing the 2.6-dev version I get the following lines in map files generated by Git-Package-Management:

```
  'tableMeta' => 
  array (
    'engine' => 'MyISAM',
  ),
```

I am not sure, if that is wanted. It maybe restricts the generation of the tables to MyISAM during installing an extra built by GPM. I don't think that the issue is restricted to GPM, since it uses the default $generator->parseSchema 

### Environment
2.6-dev

### Related issue
https://github.com/theboxer/Git-Package-Management/issues/106

**Comment by OptimusCrime** [comment]
For people unfamiliar with GPM, how is this related to the changes introduced in 2.6? What is this field used for?

**Comment by Jako** [comment]
It is maybe caused by the changes having InnoDB as default engine.

https://github.com/modxcms/revolution/commit/11cca9dfba431117ba0d876a514e1e5f03643c99

**Comment by OptimusCrime** [comment]
I think that is very, very likely as well, but I still don't understand the scope of the issue. Is this not something GPM should handle in its own specific way? What does it have to do with the MODX core?

**Comment by Jako** [comment]
Every build script for an installable extra will include those map files.

**Comment by Mark-H** [comment]
The changeset you linked to @Jako wouldn't explain why you're seeing MyISAM - if anything, that commit would change it to InnoDB. Are you sure you don't simply have the defaultEngine set on your schema?

**Comment by Jako** [comment]
Thanks, that was it. The default engine in the schemas is/was MyISAM.

But before 2.6 this was not saved into the map files.
