### ISSUE TITLE
problem using float in xpdo with andCondition function

### ISSUE THREAD

**Issue by intersel** [modxcms/revolution#13657]
### Summary
Using floats in a 'andCondition' call would transform them as integer

### Step to reproduce
create an XPDO query calling andCondtion as this following exemple
```
$query->andCondition(
	 array(
		  'location_latitude:>=' => 48.858201356788,
		  'AND:location_latitude:<=' => 48.861798643212,
	 )			
);
```

### Observed behavior
result is like this one :
` SELECT `id` FROM `match_request` AS `MatchRequest` WHERE (  `MatchRequest`.`location_latitude` >= 48 AND `MatchRequest`.`location_latitude` <= 48)`

### Expected behavior
`SELECT `id` FROM `match_request` AS `MatchRequest` WHERE (  `MatchRequest`.`location_latitude` >= 48.858201356788 AND `MatchRequest`.`location_latitude` <= 48.861798643212)`

### Suggestion for solving the problem

Perhaps I missed something but...

The problem was detected in the parseBindings function using the 'quote' function... called line 2704 in core/xpdo/xpdo.class.php 
```
if ($type > 0) {
                    $v= $this->quote($v, $type);
```
Whatever type (int, float, ...) , you call 'quote'...

The problem sounds to be solved by changing line 2560 in core/xpdo/xpdo.class.php in function quote
```
           case PDO::PARAM_INT:
                $quoted = trim($quoted);
                //$quoted = (integer) trim($quoted, "'");//removed
                $quoted = trim($quoted, "'");//added
                break;
```
Actually, it seems like float are seen like "param_int" (versus param_str) all along the processing... 
so it should not be cast here as values in float could arrive here...

**Comment by OptimusCrime** [comment]
This is most likely the correct repository for you: https://github.com/modxcms/xpdo

**Comment by intersel** [comment]
ok thanks
move it so to https://github.com/modxcms/xpdo/issues/125

**Comment by OptimusCrime** [comment]
Closing this off then. Thank you :)

@modxbot close

**Comment by intersel** [comment]
well actually, from my point of view, the issue is still there in modx revo...
moreover, the version of xpdo in modx is slightly different from the one in the xpdo git repo...
I don't know neither what are your procedure to update it if there an issue fixed in the xpdo...

so I would say it will be fixed once it is fixed in Modx Repo or that it was not an issue or whatever ...
so I don't consider that the issue is to be closed here...

**Comment by Mark-H** [comment]
xPDO should be considered a separate dependency, even tho it's currently copied into the repository. The version shipped with MODX will get updated as updates to xPDO are made available. 

For 3.x, xPDO has been taken out of the repo, and will be included through composer instead.

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/php-issue-rounding-variables/2820/8
