### ISSUE TITLE
Duplicating chunk in 2.5.8 causes original and duplicated versions to share same value

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#13658]
### Summary
When duplicating a chunk, if you change the contents of the chunk the original also shares the changes. Again if you go and change the content of the original, the duplicate then shares the changes. 

Can anyone replicate and confirm this? Seems like rather a big issue if not just on my install.

### Step to reproduce
Duplicate a chunk with a different name. Try changing the duplicated chunk content and save. Open the original chunk and you'll see the change mirrored here.

### Observed behavior
Both original and duplicated chunks get updated when saving one or the other. So they share the same content.

### Expected behavior
Of course they should have different content if changed. Content should not be mirrored.

### Environment
MODX 2.5.8

**Comment by bezumkin** [comment]
Maybe you just duplicated a static chunk therefore all your changes are shared via its file?

**Comment by digitalpenguin** [comment]
@bezumkin Ah you are indeed correct. Sorry all, more sleep is needed.
