### ISSUE TITLE
Bug: Editing context sort order

### ISSUE THREAD

**Issue by alienbuild** [modxcms/revolution#13651]
**### Summary**
Issue is present when there are multiple contexts and an administrator attempts to change the sort order of the context. 

**### Step to reproduce**
Create multiple contexts and then proceed to click and drag one context above another. When you refresh or click onto another manager page the context sort order is reverted back.

**### Observed behavior**
Reversal of updated sort order.

**### Expected behavior**
Expected the context sort order to be saved.

**### Environment**
MODX 2.5.8

**Comment by OptimusCrime** [comment]
Duplicate of #13363 and fixed by PR #13376 that is merged for 2.6. This will soon be fixed :)

@modxbot close
