### ISSUE TITLE
Possibly wrong URL generation for Manager's user avatar image.

### ISSUE THREAD

**Issue by Unchqua** [modxcms/revolution#13650]
### Summary
User avatar picture doesn't show up in Manager.
See the whole description here: https://forums.modx.com/thread/102898/possible-minor-bug-in-manager .

### Step to reproduce
I've just freshly installed 2.5.7 version and later upgraded it to 2.5.8.
Upload an image for Manager's admin account as its avatar.

### Observed behavior
The image doesn't show up due to wrong URL generated for it.

### Expected behavior
Avatar picture for Manager's user account.

### Environment
Windows 8, nginx 1.12.1 web server, latest Firefox and latest MODX 2.5.8-pl upgraded from 2.5.7-pl.

As I installed MODX I set up Admin account and uploaded a user photo for it. It didn't show up. In admin settings, its path is relative: "assets/user-avatar.png". My absolute path to MODX installation is J:\modx-2.5.8-pl\modx\ (two "modx" directories due to nginx url rewrite tricks).
The script which produces thumbnail images for this is connectors/system/phpthumb.php , all the processing starts here and goes deep into MODX classes.

Relevant classes are:
core/model/modx/processors/system/phpthumb.class.php
core/model/modx/sources/modmediasource.class.php
core/model/modx/sources/modfilemediasource.class.php
core/model/modx/moduser.class.php

Problem is that the URL which points to the picture uploaded is being made badly: somehow path "J:\modx-2.5.8-pl\modx\assets/user-avatar.png" becomes "J:\modx-2.5.8-pl\modx\J:\modx-2.5.8-pl\modx\assets/user-avatar.png", note two J:\... prefixes.
Also I've found settings for Media Sources - Filesystem, which has 2 relevant parameters: "basePath" (string) and "basePathRelative" (boolean). Playing with these settings I see different behaviour of phpthumb.php but basically there are two results: image's source either becomes "assets/user-avatar.png" (and it's not working because this path is relative and the script can't tell relative to what) or "J:\modx-2.5.8-pl\modx\J:\modx-2.5.8-pl\modx\assets/user-avatar.png" (double J:\ which is obviously wrong).

Finally I nailed it: in core/model/modx/moduser.class.php there are lines:

public function getProfilePhoto($width = 128, $height = 128) {
...
$path = $source->getBasePath($this->Profile->photo) . $this->Profile->photo;
...
}

If I change it to:

$path = $this->Profile->photo;

I get user picture right.

What I see is that this $path should stay relative here and only after that, going through modmediasource.class.php and its function prepareSrcForThumb($src), it becomes an absolute path which finally resolves to real path to local image.

**Comment by jonleverrier** [comment]
I can't seem to replicate the issues based on the steps you've provided.

I have an installation of MODX running on a Windows server and don't seem to get the same double base path as described.

Out of interest - do you have ImageMagick installed? As I believe phpthumbof requires it to work.

**Comment by Unchqua** [comment]
Sorry for being THAT late.
I tested several cases and found different behaviour between MODX versions.
First, I remind my setup: I use Nginx and not Apache; don't know if it's relevant or not.
Versions tested are 2.5.8 and 2.6.0, both "traditional" package and setup afresh, including separate database schemas. Also, for 2.5.8 I tried both root directory and root/subdir with nginx URL rewrite, with the same results.

*Images don't show up in either my setups by default.*
In MODX Browser though, it shows well.
I should note that after any change I clear browser cache and Ctrl-reload the entire page.

I then tried to play with abovementioned Media Sources - Filesystem settings "basePath" and "basePathRelative" and received different results.

In 2.5.8:
No matter what I have in these settings, image doesn't show up. I tried leaving "basePath" empty and enter absolute directory (J:/modx-2.5.8-pl/" in my case, without assets/... which is added in runtime) there. I tried "basePathRelative" set to Yes and No. No combination works.

In 2.6.0:
More interesting. By default, image doesn't show up. I entered "J:/modx-2.6.0-pl/" into basePath (having basePathRelative=Yes) and after page reload I see it! But description for basePathRelative setting says the opposite - "If the Base Path setting above is not relative to the MODX install path, set this to No."
This path "J:/modx-2.6.0-pl/" is NOT relative so I set basePathRelative to No. Image disappears. I set this to Yes, and avatar appears again. But this should work the opposite way, right?

OK, looking further. I changed basePath value to garbage like "3gbvw4gv3gq3v34tf34" and left basePathRelative=Yes. Image is on its place! I changed basePath value to a space " ". Image is there. But as soon as I make basePath empty, image disappears.

So, in essence: in my installations...
2.5.8 doesn't show avatar images, and
2.6.0 shows the image when basePath is non-empty (exact value doesn't matter) and basePathRelative=Yes.

Also, for these tests I added some error_log() PHP function calls to see what happens under the hood. In core/model/modx/moduser.class.php in function getProfilePhoto() even if variable $path has right value like "J:\modx-2.6.0-pl-test/assets/avatar.jpg" the real avatar image isn't shown in web colsole.

Should I provide any detailed info on what I do here? Am I alone seeing this glitch?

**Comment by OptimusCrime** [comment]
Seems related to the Windows platform? I have never experienced these problems.

**Comment by Unchqua** [comment]
@OptimusCrime Dunno... I guess my situation is rare for some reason.

**Comment by OptimusCrime** [comment]
I don't have access to a single Windows environment, so I am afraid I don't have the chance of testing this.

**Comment by Unchqua** [comment]
Both installations of mine are affected, Win7 and Win8.
I'll see if I can trace it down to its root cause.

**Comment by Unchqua** [comment]
So I'm lost. I have a fix for my case and it seems it's only Windows machines which experience it.
The logic around basePath / basePathRelative seem inconsistent for me. $src variable value passed to modx\core\model\modx\sources\modmediasource.class.php#prepareSrcForThumb() seems to have excess paths depending on basePathRelative value and thus it's the place where $src value gets doubled.
Reviewing the code, found several places where only *nix file paths style taken into consideration and this doesn't work for Windows environment.
Sadly I don't have any Linux server at hand to test.

**Comment by Ruslan-Aleev** [comment]
This is true for the Apache+Nginx server, tried to upload a picture for the user, but I get error path, see the image below.

The avatar is displayed in different ways:
1) the image is displayed without the path of the file source:
`<img src="Avatar.jpg">`

2) the image is displayed with the path of the file source (assets/ folder), but the path is generated relative to the server folder:
`<img src="/connectors/system/phpthumb.php?zc=1&h=128&w=128&amp;src=/home/a/aleeviz8/m3/public_html/assets/Avatar.jpg">`

![avatar_info](https://user-images.githubusercontent.com/12523676/53228824-d43b5600-369b-11e9-903b-2c902bcade65.png)

Perhaps related to - https://github.com/modxcms/revolution/pull/14420
