### ISSUE TITLE
bug on several of our sites after upgrade 

### ISSUE THREAD

**Issue by antfrolov** [modxcms/revolution#13664]
1. https://yadi.sk/i/1Iwn8OGJ3PLxov 
2. without quotes in the name - ок https://yadi.sk/i/iedSYa1j3PLy3d 
3. with quotation marks in the name - bug https://yadi.sk/i/PhXQKRob3PLyHF

on several of our sites

**Comment by OptimusCrime** [comment]
I can not get the images to show here. Could you upload them directly to GitHub instead of using external sources?

**Comment by antfrolov** [comment]
![2017-11-02_18-55-22](https://user-images.githubusercontent.com/33340307/32364222-790fbdb6-c095-11e7-8d16-5f334e50481b.png)
![2017-11-02_18-57-07](https://user-images.githubusercontent.com/33340307/32364225-7bdffe3e-c095-11e7-867f-c2dfffd65136.png)
![2017-11-02_18-57-54](https://user-images.githubusercontent.com/33340307/32364227-7e095eda-c095-11e7-90fd-86d964cf7e1b.png)

**Comment by Mark-H** [comment]
An empty Manager page like that suggests a JavaScript error. Could you
check for that in the browser developer tools?

Op 3 nov. 2017 8:50 a.m. schreef "antfrolov" <notifications@github.com>:

**Comment by antfrolov** [comment]
Uncaught SyntaxError: Unexpected identifier
?a=resource/update&id=1241:387 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:387
    at ext-all.js:21
    at b (ext-all.js:21)
?a=resource/update&id=1241:427 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:427
    at ext-all.js:21
    at b (ext-all.js:21)
?a=resource/update&id=1241:467 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:467
    at ext-all.js:21
    at b (ext-all.js:21)
?a=resource/update&id=1241:528 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:528
    at ext-all.js:21
    at b (ext-all.js:21)
?a=resource/update&id=1241:587 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:587
    at ext-all.js:21
    at b (ext-all.js:21)
?a=resource/update&id=1241:727 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:727
    at ext-all.js:21
    at b (ext-all.js:21)
?a=resource/update&id=1241:827 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:827
    at ext-all.js:21
    at b (ext-all.js:21)
?a=resource/update&id=1241:2252 Uncaught TypeError: Cannot read property 'getForm' of undefined
    at ?a=resource/update&id=1241:2252
    at ext-all.js:21
    at b (ext-all.js:21)

**Comment by Jako** [comment]
Please check the commit of @labr1005 - it should fix your issue.

**Comment by antfrolov** [comment]
Please reformulate your phrase. I can not translate into Russian. )))

**Comment by antfrolov** [comment]
fix. thanks

**Comment by OptimusCrime** [comment]
@Jako The PR is merged, can this issue be closed?

**Comment by Jako** [comment]
@OptimusCrime The PR is open, as far as I can see.

**Comment by OptimusCrime** [comment]
Oh, sorry. I looked at the PR you referenced in the comment above. I see now that it was closed in favor of another PR. My bad.

**Comment by pashajanx** [comment]
Hey.
When the parent has a `&quot;` in the header. Child resources can not be saved.

<img src="https://file.modx.pro/files/f/0/b/f0b66bde4825d36bfb84a1e0aa137896.jpg" />
