### ISSUE TITLE
Some page titles in Form Customisation are not 'title' format

### ISSUE THREAD

**Issue by jcdm** [modxcms/revolution#13668]
### Summary
Several pages in the Form Customisation area have incorrect page title formatting

### Step to reproduce
Visit /manager/?a=security/forms on an install of 2.6
Also affects /manager/?a=security/forms/set/update?id=#

### Observed behavior
The titles read correctly ('Form Customization' and 'Edit Set', but are formatted as paragraph text instead of &lt;h2&gt;s and also have excess padding

### Expected behavior
Should be formatted as &lt;h2&gt;s with the relevant classes to remove the padding.

### Environment
Issue seems to have been introduced in 2.6 - 2.5.8 not affected.

**Comment by jonleverrier** [comment]
I can see this too on 2.6.

**Comment by achterbahn** [comment]
Collecting all pages with this behaviour: 

- manager/?a=security/forms/
- manager/?a=security/forms/set/update
- manager/?a=resource/site_schedule

Anywhere else?
