### ISSUE TITLE
Media browser wrong image size

### ISSUE THREAD

**Issue by Pfeifakopf** [modxcms/revolution#13670]
### Summary
The media browser shows the wrong image size. Because of that, image+ think all images are to small.

### Step to reproduce
Just uploaded the images via media browser upload. 

### Observed behavior
You can see the small image-sizes. My image was shown with an width of 800px instead of the real 2600px. I downloaded the image from the server. This image has still the right size.

### Environment
modx 2.6.0
PHP 7.0.25 fastcgi
Ubuntu 14.04 
![image](https://user-images.githubusercontent.com/3351449/32391714-5ff7f24c-c0d3-11e7-8781-e4fb097ab0a3.png)

**Comment by labr1005** [comment]
Confirmed.
Introduced in #13629.
I'm working on a fix.

**Comment by labr1005** [comment]
@Pfeifakopf Please check the PR #13672 - it should fix the issue.

**Comment by labr1005** [comment]
@Pfeifakopf Did you have some time to check the recommended PR and did it fix your problems?

**Comment by Pfeifakopf** [comment]
@labr1005 Changes are done, works all fine now.

**Comment by Jako** [comment]
Merged into 2.6.x
