### ISSUE TITLE
pThumb images in other context

### ISSUE THREAD

**Issue by funkyduke** [modxcms/revolution#13679]
I have a website in 2 languages. There are some pics on it where I use pThumb on through a TV. In the standard context (web) everything works fine, in the second context the image is not show.

It should be /fr/assets/image-cache/userfiles/image.jpg
but it shows just image.jpg, without the path

Empty the cache or deleting the pThumb image-folder doesn't work.

UPDATE:
I deleted the pThumb-code and still the image-path is not shown. So it's not a pThumb-problem I think. Everything on my TV is ok (media-source). My global media-source is also ok.

![screenshot_1](https://user-images.githubusercontent.com/1769979/32471494-e0a32b14-c35d-11e7-9d3a-e72584c2cc2f.jpg)

It always worked before upgrading to Modx 2.6 (previous version 2.5.8)

### Environment
Modx 2.6, PHP 7.1.8

UPDATE 2:
I found a simple solution, but don't know how it comes this happens. When I change the TV from image to something else, save it and then change it back to image everything is working. Very strange, but that solved it for me.

**Comment by FerX** [comment]
Read this:
Quick Create TV does not preappend custom "baseUrl" value #13481

**Comment by zaigham** [comment]
@funkyduke did u create 2nd context after creating the tv? if so open the tv and resave it. There is a known issue where tv doesnt have access to media source in newly created contexts.

**Comment by funkyduke** [comment]
@zaigham Indeed I did. Resave does help. Hope this will be solved in an upcoming upgrade. Thx.

**Comment by OptimusCrime** [comment]
@zaigham Is this known issue in the bug tracker? Is it the issue @FerX referenced #13481?

**Comment by zaigham** [comment]
Reference bug: #9058
@OptimusCrime

**Comment by OptimusCrime** [comment]
Can we close this as a duplicate then?

**Comment by OptimusCrime** [comment]
@modxbot close
