### ISSUE TITLE
updatedon and updatedby fields aren't updated after a resource undeletion

### ISSUE THREAD

**Issue by sartatpdev999** [modxcms/revolution#13673]
### Summary
updatedon and updatedby fields in site_content table aren't updated after a resource undeletion.

### Step to reproduce
1. Delete a resource
2. Undelete the resource
3. Watch updatedon and updatedby fields of the resource in the database

### Observed behavior
updatedon and updatedby fields in site_content table aren't updated after a resource undeletion.

### Expected behavior
Update of updatedon and updatedby fields in site_content table after a resource undeletion.

### Environment
MODX Revolution 2.6.0-pl

**Comment by bezumkin** [comment]
But deletion and undeletion is not really an **update** of resource. You just change the `deleted` flag in table.

So I believe, everything works as expected.

**Comment by sartatpdev999** [comment]
The resource field `deleted` is the same field as `published` or `hidemenu`. After their change `editedby` and `editedon` are updated. So i think that after deletion or undeletion of a resource `editedby` and `editedon` should also be updated
