### ISSUE TITLE
Unable to flush permissions after upgrading to 2.6.0 from 2.5.7

### ISSUE THREAD

**Issue by digitalpenguin** [modxcms/revolution#13687]
### Summary
Unable to flush permissions after upgrading to MODX 2.6 from 2.5.7

### Step to reproduce
Upgrade to 2.6 then try to flush your permissions in the manager.

### Observed behavior
Browser gets an empty response from the processor and error in console is:
 `SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data`

### Expected behavior
Permissions should flush.

### Environment
MODX 2.6.0, PHP 7.1

**Comment by digitalpenguin** [comment]
https://github.com/modxcms/revolution/blob/2.x/core/model/modx/processors/security/access/flush.class.php#L14

Line 14 in the link above is returning false.

**Comment by digitalpenguin** [comment]
https://github.com/modxcms/revolution/blob/2.x/core/model/modx/modcachemanager.class.php#L772

Line 772 in modCacheManager is what's failing.

The contents of the `$serialized` variable in the line above is:
```a:3:{i:0;s:2:"en";i:1;s:3:"mgr";i:2;s:3:"web";}```

**Comment by OptimusCrime** [comment]
If it is failing, do you have anything in your error log?

**Comment by digitalpenguin** [comment]
Also can confirm it's happening on more than one install.
Both fresh 2.6 install and upgraded from 2.5.7/2.5.8.
Also different environments: local as well as remote server.

**Comment by OptimusCrime** [comment]
MySQL version?

**Comment by digitalpenguin** [comment]
One environment is MySQL 5.6.37
another is MySQL 5.7.17

**Comment by Bruno17** [comment]
maybe it was introduced with this commit?
https://github.com/modxcms/revolution/commit/ecc1b0d00bd01ff6d94aa4a830e771a8425185eb#diff-7815df8a113600b79e256c26e16369cf

return `false` instaed of `$this->modx->error->success('');`
