### ISSUE TITLE
Cant create resource with double quotes

### ISSUE THREAD

**Issue by wax100** [modxcms/revolution#13686]
### Summary
Cant create resource with double quotes

### Step to reproduce
Pagetitle like test "test"

### Observed behavior
After page reload - white page

### Expected behavior
Normal page reload

### Environment
MODX version 2.6.0., 
I think it depends on OS. On Mac it works well, the problem was on Windows 8

**Comment by achterbahn** [comment]
Can confirm this issue. Even on Mac.

**Comment by labr1005** [comment]
Fixed in #13669 for MODX 2.6.1
