### ISSUE TITLE
Quotation marks in pagetitle = blank Resource screen

### ISSUE THREAD

**Issue by mtalvenheimo** [modxcms/revolution#13695]
### Summary
If resource field *Title contains quotation marks, resource doesn't open. Other special characters not tested?

### Step to reproduce
Add quotation mark somewhere in Pagetitle -> save -> reload page

### Observed behavior
After reload or open, blank space where Resource settings should be?

### Environment
MODX version: 2.6.0
mysql version: 5.5.57-MariaDB-1ubuntu0.14.04.1
browser: Chrome (at least)

**Comment by Bruno17** [comment]
see #13669

**Comment by mtalvenheimo** [comment]
Ok. Thank You!

**Comment by sottwell** [comment]
I tested the patch with all special characters on the keyboard, and all was well.
