### ISSUE TITLE
Lexicon placeholder issues

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#13698]
### Summary
There are around 70 entries on Crowdin, that have `[[+ placeholdername]]` (a space occurs after the `+` sign) in the string, this seems to be the cause of an automatic translation. Maybe each translator could look for those issues in his managed language.

### Environment
MODX Revolution 2.6

**Comment by opengeek** [comment]
Why is there a space after the `+` sign in these entries?

**Comment by Jako** [comment]
I don't know that for sure. I think that the change happened on Crowdin, when a (semi) automatic translation is suggested.

**Comment by Jako** [comment]
Example: https://github.com/modxcms/revolution/blob/72104bd2eed37a0c412987bc5e0a8738f1d4b2c9/core/lexicon/de/tv.inc.php#L39

**Comment by opengeek** [comment]
This has been resolved.

**Comment by opengeek** [comment]
See commit b41662ee1
