### ISSUE TITLE
Add system setting - SYSTEM TEMPLATE

### ISSUE THREAD

**Issue by wax100** [modxcms/revolution#13692]
### Summary
Add system setting - SYSTEM TEMPLATE, that allows to hide some templates in listbox from managers

**Comment by Bruno17** [comment]
Can't you do this same thing with element-categories and permissions to element-categories?
Just create a category 'System Template', put your template in it and give only the admin - group load,list,view - permission to this category

**Comment by wax100** [comment]
AS I know, if I do as U write - I will have no access to TМы
But I try it on new version of Modx

**Comment by OptimusCrime** [comment]
How would this system setting work? How would one (global) system setting decide which templates should be visible? And how should permissions be handled for this?

**Comment by Mark-H** [comment]
The ACLs system already lets you do this in a way that some user groups can and other can't access the category (as Bruno suggested), so unless there is a very strong reason that is not sufficient, I'm going to mark this as closed.
