### ISSUE TITLE
Changing resource type to RSS breaks RTE

### ISSUE THREAD

**Issue by bschwenk** [modxcms/revolution#13718]
### Summary
Changing the resource type to RSS in the "Settings" tab blocks editing in the RTE.

### Step to reproduce
1. Create a new resource (leave type set to HTML)
2. Add any content in RTE and save
3. Edit resource again then go to Settings -> Resource Type, select "RSS"
4. Save resource, manually refresh browser

### Observed behavior
RTE now shows no syntax highlighting, and it's not possible to edit any text in the RTE until you change the resource type again then manually refresh.

Browser console shows JS error:

```GET https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.4/mode-undefined.js net::ERR_ABORTED```

Network tab also shows error 400 on this resource.
![image](https://user-images.githubusercontent.com/8420188/33911277-d9b57c08-df5f-11e7-9e5e-b2fa0df302ef.png)

### Environment
MODX Revolution 2.5.7-pl (traditional)
nginx
(hosted MODX cloud)

**Comment by donShakespeare** [comment]
Which RTE (Rich Text Editor) do you have installed and running?
Which Code Editor do you have installed and running?

**Comment by OptimusCrime** [comment]
This looks related to a MODX extra, not the MODX core?

**Comment by bschwenk** [comment]
It's TinyMCE. I thought TinyMCE was included with a vanilla install. Screenshot attached for reference. If that's not the case, please close the issue and my apologies for the inconvenience.

![image](https://user-images.githubusercontent.com/8420188/33943790-127f0972-dfe8-11e7-84c2-2ea5d71ece3e.png)

**Comment by OptimusCrime** [comment]
TinyMCE is a third party extra. It is not a part of the manager core.  Additionally, the attached picture does not look like TinyMCE to me, it looks like CodeMirror or something?

I'm closing this issue, but feel free to respond and we will try to find the correct place to file this issue.

@modxbot close

**Comment by Jako** [comment]
It should be an ACE issue and you could open an issue [there](https://github.com/danyaPostfactum/modx-ace).

ACE only works on the content field, when no RTE is active.

And for some reason ACE tries to detect the content type, switches to mode-undefined, tries to load the according script and fails because it is not found.
