### ISSUE TITLE
Template Variable Type "Resource List" crashes resource editor

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13712]
### Summary
Using the Template variable type "Resource List" crashes the resource editor. The result is a 500 error.

### Step to reproduce
Setup a resource template which uses a template variable with type "Resource List".
Try to create/edit a resource.

### Observed behavior
The resource editor crashes with a 500 error.

### Expected behavior
Should not crash.

### Environment
MODX version: MODX Revolution 2.6.0-pl
Apache version: Apache/2.4.10 (Debian)
MySQL version: 5.5.53-0+deb8u1
PHP version: 5.6.29-0+deb8u1
Browser: Safari, Chrome, Firefox, IE not tested

**Comment by sottwell** [comment]
Can't reproduce on localhost 2.6 or 3.0 installation. PHP version 7.1.8, basic MAMP installation.

**Comment by sottwell** [comment]
Also cannot reproduce on MODX Cloud 2.6 installations, PHP 7.1

**Comment by OptimusCrime** [comment]
@gadgetto A 500 error results in a error log. We need this to be able to debug the problem. Like @sottwell has stated; it seems to work here.

**Comment by gadgetto** [comment]
I retried it many times but no error log entry!

It seems this could be a problem with the huge list of resources on this page -> about 9000.
If I try to open a resource which is bound to a TV type "Resource List", the page loads about 10-15 seconds and then the error 500 occurs.

As soon as I unbind this TV from the corresponding template, the resources opens immediately and without a problem.

**Comment by sottwell** [comment]
Ah. 9,000 resources. That's no surprise in this case, it may well be a script timeout issue.

A 500 error probably won't show up in the MODX error log (core/cache/logs), but it will show up in your server's error log, either its PHP error log or the web server's access logs.

**Comment by gadgetto** [comment]
Seems to be also a memory problem. We raised the PHP memory limit to 512 (I know it's an absurd value) and now - after a long site loading time the resource editor loads without an error.

**Comment by OptimusCrime** [comment]
@gadgetto Did you check your PHP log? I did not mean the MODX one. This should result in a our of memory error, otherwise this will result in guesswork.

**Comment by gadgetto** [comment]
I currently don't have access to the server. Will post this later...

**Comment by Jako** [comment]
As @sottwell says: it is a timeout issue during generating the resource list. Could you limit the resources by an @SELECT in the TV? Otherwise you have to switch to something, that creates the resource list on AJAX base with a pagination and live search, like the SuperBoxSelect extra.

**Comment by gadgetto** [comment]
IMHO: If the current implementation of this TV type doesn't scale with large resource lists, it should be treatened as a bug.

@Jako Thanks, I'll have a look at the SuperBoxSelect add-on!

**Comment by Jako** [comment]
This issue can't be solved. The `Resource List` TV type could maybe restricted with a limit, but it is not meant to show many resources.
