### ISSUE TITLE
System Setting "log_level" doesn't work as expected

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13713]
### Summary
System Setting "log_level" doesn't seem to work as expected. No matter if I set it to 0 (FATAL), 1 (ERROR), 2 (WARN), 3 (INFO) or 4 (DEBUG) - it always logs the other levels too.

### Step to reproduce
Set the log_level system setting to 0 and watch how log entries with ERROR, WARN, INFO are written to the system log.

### Observed behavior
If I set the log_level to 0 the system shouldn't write 1 (ERROR), 2 (WARN), 3 (INFO) messages to the log. If set to ERROR it should only write ERRORs and FATALs. and so on...

### Environment
MODX version: MODX Revolution 2.6.0-pl
Apache version: Apache/2.4.10 (Debian)
MySQL version: 5.5.53-0+deb8u1
PHP version: 5.6.29-0+deb8u1
Browser: Safari, Chrome, Firefox, IE not tested

**Comment by bezumkin** [comment]
I will check it

**Comment by gadgetto** [comment]
It seems it could be an add-on which sets log level to "info". I'll try again on a fresh install an post back result. (will need a few days until I have time.)

**Comment by muzzwood** [comment]
I can't replicate the issue on 2.6.1

**Comment by bezumkin** [comment]
@gadgetto Any news?

**Comment by gadgetto** [comment]
No problems in a fresh install so far.
