### ISSUE TITLE
modx revo 2.6.1  Parse error: syntax error, unexpected '<', expecting end of file in...\core\cache\includes\elements\modplugin\4.include.cache.php on line 25

### ISSUE THREAD

**Issue by ALexeyP0708** [modxcms/revolution#13729]
modx revo 2.6.1  Parse error: syntax error, unexpected '<', expecting end of file in...\core\cache\includes\elements\modplugin\4.include.cache.php on line 25

generates script in file .\core\cache\includes\elements\modplugin\4.include.cache.php
```

<?php
/** @var modX $modx */
switch ($modx->event->name) {

    case 'OnMODXInit':
        $fqn = $modx->getOption('pdoTools.class', null, 'pdotools.pdotools', true);
        $path = $modx->getOption('pdotools_class_path', null, MODX_CORE_PATH . 'components/pdotools/model/', true);
        $modx->loadClass($fqn, $path, false, true);

        $fqn = $modx->getOption('pdoFetch.class', null, 'pdotools.pdofetch', true);
        $path = $modx->getOption('pdofetch_class_path', null, MODX_CORE_PATH . 'components/pdotools/model/', true);
        $modx->loadClass($fqn, $path, false, true);
        break;

    case 'OnSiteRefresh':
        /** @var pdoTools $pdoTools */
        if ($pdoTools = $modx->getService('pdoTools')) {
            if ($pdoTools->clearFileCache()) {
                $modx->log(modX::LOG_LEVEL_INFO, $modx->lexicon('refresh_default') . ': pdoTools');
            }
        }
        break;
}
return;
<?php
/** @var modX $modx */
switch ($modx->event->name) {

    case 'OnMODXInit':
        $fqn = $modx->getOption('pdoTools.class', null, 'pdotools.pdotools', true);
        $path = $modx->getOption('pdotools_class_path', null, MODX_CORE_PATH . 'components/pdotools/model/', true);
        $modx->loadClass($fqn, $path, false, true);

        $fqn = $modx->getOption('pdoFetch.class', null, 'pdotools.pdofetch', true);
        $path = $modx->getOption('pdofetch_class_path', null, MODX_CORE_PATH . 'components/pdotools/model/', true);
        $modx->loadClass($fqn, $path, false, true);
        break;

    case 'OnSiteRefresh':
        /** @var pdoTools $pdoTools */
        if ($pdoTools = $modx->getService('pdoTools')) {
            if ($pdoTools->clearFileCache()) {
                $modx->log(modX::LOG_LEVEL_INFO, $modx->lexicon('refresh_default') . ': pdoTools');
            }
        }
        break;
}
return;


```

**Comment by sottwell** [comment]
That's a bad plugin, not a MODX issue. The plugin code was duplicated, including the initial `<?php` line, which is causing your problem.

**Comment by sottwell** [comment]
I've done that when editing code in an editor, then copy/pasting it back into the plugin field, but not first erasing the original code in the field.

**Comment by ALexeyP0708** [comment]
@sottwell 
The file is generated dynamically. Its change will not lead to the correct result.
The error is repeated several times, even if you edit the file.
I have no idea who is to blame for this. Core MODx or modPlugin or Cache

**Comment by Mark-H** [comment]
What's the contents of plugin #4 according to the manager/database? 

I've heard of some issues in the past where some cache files get duplicated contents', possibly because php couldn't properly get a lock on the cache files while 2 separate processes write to it.

**Comment by ALexeyP0708** [comment]
The error was repeated 3 times. Occurs spontaneously. I suspect that this happens while saving the snippet. The version is fresh. Installed a couple of days ago on localhost. Server on Apache2.4 + php7.1 in Windows 10.

**Comment by sottwell** [comment]
Is the code duplicated in the snippet content (database), or only in the cache file?

**Comment by ALexeyP0708** [comment]
The code is duplicated in a file. I am correcting it and everything is fine. But after a while, when saving, the error occurs again. In MODX settings, all possible caches are disabled.

**Comment by OptimusCrime** [comment]
@ALexeyP0708 Please provide the entire content of your plugin with ID 4.

**Comment by ALexeyP0708** [comment]
@OptimusCrime 
ID 4- pdoTools
```
<?php
/** @var modX $modx */
switch ($modx->event->name) {

    case 'OnMODXInit':
        $fqn = $modx->getOption('pdoTools.class', null, 'pdotools.pdotools', true);
        $path = $modx->getOption('pdotools_class_path', null, MODX_CORE_PATH . 'components/pdotools/model/', true);
        $modx->loadClass($fqn, $path, false, true);

        $fqn = $modx->getOption('pdoFetch.class', null, 'pdotools.pdofetch', true);
        $path = $modx->getOption('pdofetch_class_path', null, MODX_CORE_PATH . 'components/pdotools/model/', true);
        $modx->loadClass($fqn, $path, false, true);
        break;

    case 'OnSiteRefresh':
        /** @var pdoTools $pdoTools */
        if ($pdoTools = $modx->getService('pdoTools')) {
            if ($pdoTools->clearFileCache()) {
                $modx->log(modX::LOG_LEVEL_INFO, $modx->lexicon('refresh_default') . ': pdoTools');
            }
        }
        break;
}
```

**Comment by OptimusCrime** [comment]
There is a system setting called `use_flock`. What is the current value, and could you try to change it to see if that fixes the problem?

**Comment by batulin** [comment]
Tell me please how to solve the problem.

**Comment by Bruno17** [comment]
@batulin did you try, what @OptimusCrime had suggested?

**Comment by batulin** [comment]
Bruno17 I did not find the system setting - use_flock

**Comment by Bruno17** [comment]
you can try just to add this system setting

**Comment by batulin** [comment]
thank you Bruno17 What should be the value? but where can I learn more about this?

**Comment by Bruno17** [comment]
https://forums.modx.com/thread/78611/core-cache-file-locks-and-will-not-update#dis-post-434053

try a yes/no - system setting and set it to no

**Comment by Bruno17** [comment]
also here
https://docs.modx.com/revolution/2.x/faqs-and-troubleshooting

**Comment by batulin** [comment]
thank you.

**Comment by batulin** [comment]
Hello Bruno17!
I registered a parameter in the config.inc.php parameter file 'use_flock' => 'false', but after a while I started to get errors again.
Parse error: syntax error, unexpected '<', expecting end of file in D:\IT\webserver\domains\tests\core\cache\includes\elements\modplugin\8.include.cache.php on line 34 Please tell me how to be in this situation. Thank you

**Comment by alexeyp0708** [comment]
@batulin   
try for modx revo 261 for dev.
1. Clean the cache manually. Delete all folders in the www \ core \ cache \ directory.
2. If the error reappears, replace the file www \ core \ xpdo \ cache \ xpdocachemanager.class.php from MODX REVO 257
3. Try to work in one web window, so as not to block the cache by other windows when editing plug-ins or snippets. Also, there are problems when opening files or catalogs in IDE, Notepad, file manager, web browser. This error can be phantom due to the problem described below.

FOR XPDO developers
see the file www\core\xpdo\cache\xpdocachemanager.class.php
Class : xPDOCacheManager
Methods : writeFile
Code:

```
// find code 
 $fmode = (strlen($mode) > 1 && in_array($mode[1], array('b', 't'))) ? "a{$mode[1]}" : 'a';
$file= @fopen($filename, $fmode);
//   access type mode  for fopen equally "a"
.....
//find code
if ($locked) {
                    fseek($file, 0);
                    ftruncate($file, 0);
                    $written= fwrite($file, $content);
                    if ($this->getOption('use_flock', $options, true)) {
                        flock($file, LOCK_UN);
                    } else {
                        $this->unlockFile($filename, $options);
                    }
                }
```
function - fseek 
Read manual http://php.net/manual/en/function.fseek.php
Note:
If you have opened the file in append (a or a+) mode, any data you write to the file will always be appended, regardless of the file position, and the result of calling fseek() will be undefined.
Note:
Not all streams support seeking. For those that do not support seeking, forward seeking from the current position is accomplished by reading and discarding data; other forms of seeking will fail.

**Comment by alexeyp0708** [comment]
About use_flock please see  issue https://github.com/modxcms/xpdo/issues/113

**Comment by alexeyp0708** [comment]
@batulin there is an option to replace the xPDOFileCache engine with another one. Read Google.

**Comment by batulin** [comment]
ALexeyP0708 thank you!

**Comment by wshawn** [comment]
Uninstall PDOTools and remove it.
Clear the cache via cache directory contents removal stated above
Reinstall PDOTools via Package Manager

**Comment by batulin** [comment]
wshawn thank yoy

**Comment by VoiD2008** [comment]
this happens when cache manager trying to update cache on same script twice in one time
without flock option same content will be written two times in one cache file.
Thats because xpdo cachemanager reads fopen mode "wb" as "ab"
```
        $fmode = (strlen($mode) > 1 && in_array($mode[1], array('b', 't'))) ? "a{$mode[1]}" : 'a';
        $file= @fopen($filename, $fmode);
```

**Comment by batulin** [comment]
thank you VoiD2008
