### ISSUE TITLE
Anonymous user and disabled anonymous sessions

### ISSUE THREAD

**Issue by wkwkgit** [modxcms/revolution#13736]
modx 2.6.0 (2.6.1 too), on disabled anonymous session - policy for anonymous users is not working.

**Comment by OptimusCrime** [comment]
Please follow the template (that you edited out?). What do you mean by "is not working"? This could mean a million things. We also need some steps to reproduce this.

Please fill out _all_ the necessary information.

**Comment by Mark-H** [comment]
Closing due to lack of information. @wkwkgit please feel free to either edit your original post with more details following [this template](https://github.com/modxcms/revolution/blob/2.x/.github/ISSUE_TEMPLATE.md), or open a new issue.
