### ISSUE TITLE
Import HTML does not respect richtext_default setting

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#13737]
### Summary
Import HTML sets the richtext field of all imported docs, even if the parent folder has it off and the richtext_default System Setting is set to No. 

### Step to reproduce
Turn off richtext_default System Setting.
Clear Cache.
Import a document using Content -> Import HTML

### Observed behavior
Richtext checkbox is checked

### Expected behavior
Rich text checkbox not checkec.

### Environment
MODX 2.6.1, localhost, XAMPP.

I'm not sure if the fix should involve the parent's folder's richtext setting or just the richtext_default System Setting.

**Comment by OptimusCrime** [comment]
For what it is worth, I am in favor of removing the 'Import HTML' feature in a major release of MODX. It has nothing to do in the core and the implementation lacks a lot of features and guards.

**Comment by sottwell** [comment]
While I have made use of it once or twice, it would be better as a separate add-on, installed when needed and removed afterwards.

**Comment by BobRay** [comment]
I agree that it makes more sense as an extra.

**Comment by mrhaw** [comment]
I wish Control Error log would be part of the core
https://modx.com/extras/package/controlerrorlog
I can't work with Revo without it

Batcher should also be integrated.

I can see
Upgrade MODX, 
Backup MODX 
being extras because of the issues with server environments. 

I can see Import HTML being an extra but thinks that strips MODX from a great feauture that will fade away and only be used by specialists who can modify the code for individual projects.

**Comment by alroniks** [comment]
@mrhaw I am against pull everything into the system. The explanation is simple: all that things increase code base, maintenance of which also has cost, by time mostly. MODX was called and modular and extendable, which means, it contains modules, which extend the core. All things, like import, export, backup, and others should be implemented in different extras/components. But, to provide a good experience to the user they can be included into the CMS package.

**Comment by Mark-H** [comment]
With #15841 this feature will be removed from 3.0, so when that's merged this can be closed.
