### ISSUE TITLE
Resource Description field does not fit new Google Description 320 character limit

### ISSUE THREAD

**Issue by ATypicalGiraffe** [modxcms/revolution#13738]
### Summary
Google has changed the maximum characters displayed to 320 characters in search result listings. MODX currently has a 255 character limit in the Description field.

### Step to reproduce
View page description returned in Google search results.

### Observed behavior
MODX Resource Description field will not accept updated Google character limit.

### Expected behavior
The default Description field should be expected to accomodate full SEO Description character limit.

### Environment
All versions - this is caused by external standards being changed.

**Comment by digitalpenguin** [comment]
Actually as of 2.6 the max length is 191 characters due to UTF8mb4 support.
As varchar can't be longer than 191 characters, I assume if this is changed it would need to be TEXT type.

**Comment by sottwell** [comment]
No, not all varchar fields, only those used as an index. In all cases here as far as I know, those are "name" fields, not "value" or "content" fields.

**Comment by sottwell** [comment]
All of the elements that came from Evo had short name fields, like chunks and templates, have always been something like 50 chars. It's the new tables with Revo that had everything set to 255 chars by default. I suppose it seemed like a good idea at the time...

**Comment by OptimusCrime** [comment]
>Values in VARCHAR columns are variable-length strings. The length can be specified as a value from 0 to 255 before MySQL 5.0.3, and 0 to 65,535 in 5.0.3 and later versions. The effective maximum length of a VARCHAR in MySQL 5.0.3 and later is subject to the maximum row size (65,535 bytes, which is shared among all columns) and the character set used.

UTF8mb4 uses 4 bytes so that means the highest length is rounded down to 65,535 / 4 = 16,383. This upper limit means that you easily can specify an upper limit of 320 * 4 = 1,280 without any problems.

**However**, the minimum requirement for MODX MySQL is version 4.1.20. 

This means that unless we change the field to be TEXT type, there is no way of limiting this without bumping the MySQL minimum requirement to 5.x.

**Comment by Mark-H** [comment]
As description is not an index by itself (it is part of an index group `content_ft_idx`, but that's fulltext, so not affected by the utf8mb4/innodb limits), I see no problems with slightly bumping the description field to give people that bit of extra room. 

Alternatively, the `introtext` field is `text` so has no practical limit.

**Comment by gpsietzema** [comment]
I'd love to see the description-field changed to text as well then.

**Comment by dimitrihilverda** [comment]
+1 for me

**Comment by alroniks** [comment]
PR is merged, so closing.
