### ISSUE TITLE
MIGX doesn't load Media Source.

### ISSUE THREAD

**Issue by BorisGH** [modxcms/revolution#13735]
### Summary
When I click on Add Item, MIGX TV loads the main page instead of the media source folder.  
Simple TV with image type loads the media source correctly.
MODx Media Browser loads the media source correctly.
How can I load the media source clicking on MIGX TV Add Item?

### Step to reproduce
Create a MIGX TV.

### Observed behavior
MIGX doesn't load Media Source when using it on my hosting. But on my home computer MIGX works correctly.

### Expected behavior
Add Item button should load Media Source.

### Environment
MODX Revolution 2.6.1-pl, migx 2.11.0-pl.

**Comment by sottwell** [comment]
MIGX is not MODX, it is a third-party extra. You need to talk to the MIGX author about this.
