### ISSUE TITLE
No fall back to context key if context name isn't specified.

### ISSUE THREAD

**Issue by bennyb** [modxcms/revolution#13739]
### Summary
A number of sites where i've upgraded from older version don't contain a context name, so nothing is displayed in the context drop down.  Pre 2.6.1 both the context name and key were displayed so if no name was added the key would still display but in 2.6.1 only the name is displayed.

### Step to reproduce
No value is set for the context name.
Manager >> Access Control Lists >> Update a user group>> Permissions >> Context Access >> Context drop down.
This is the same for any combobox that lists the context.

### Observed behavior
Combobox doesn't display a name.

### Expected behavior
Should fall back to displaying the key
### Environment
MODX version 2.6.1

**Comment by Oetzie** [comment]
I'm going to try and fix this today #modxbughunt

**Comment by alroniks** [comment]
PR is merged, so closing this one.
