### ISSUE TITLE
undefined index - notices on many TV - smarty-templates, because of undefined placeholders

### ISSUE THREAD

**Issue by Bruno17** [modxcms/revolution#13748]
### Summary
undefined index - notices on many TV - smarty-templates, when called for example by MIGX
There is no way, to get all possible placeholders for all TV-types programmatically

### Step to reproduce
create a MIGX - TV with some fields.
set the system-setting debug to 1
As soon, as you try to create or add MIGX - items, the form with the TVs gets corrupted, because of undefined index - notices

### Observed behavior
As soon, as you try to create or add MIGX - items, the form with the TVs gets corrupted, because of undefined index - notices

### Expected behavior
no undefined index - notices should be thrown

### Environment
MODX 2.6.1, but also older versions

### Possible Fix
add `|default` to all smarty - placeholders in the TV-templates like 
`{minLength|default}` `{maxLength|default}` `{regex|default}` and so on

**Comment by Bruno17** [comment]
#modxbughunt trying I will try to fix this today

**Comment by Mark-H** [comment]
Many have been resolved in 2.7 per #13769

**Comment by mailspayes** [comment]
Could you re-open this PR please, this fix a lot of bugs when we use MIGX? Thanks

**Comment by Jako** [comment]
This is an issue and not a PR. The PR is already merged into 2.7, which will hopefully be released soon.
