### ISSUE TITLE
Italian Translations

### ISSUE THREAD

**Issue by digitalplayer-steemit** [modxcms/revolution#13749]
Hello

My name is Michael Asumcinei and I would like to contribute with Italian translations.

I can do that only using Github as I am an adopter of Utopian.io project to reward open source software.

Just let me know if you are interested and I will be there for it

Best Regards
Michael Asumcinei
steemit.com/@digitalplayer

**Comment by Mark-H** [comment]
@digitalplayer-steemit We use Crowdin for translation management. Your help is of course more than welcome via translate.modx.com.

**Comment by digitalplayer-steemit** [comment]
I cannot provide Crowdin contributions but only Github.

**Comment by Mark-H** [comment]
Sorry @digitalplayer-steemit - we don't take PRs for translations. CrowdIn gives translators a nice interface, and allows us to do a  single translation sync in the release process, making it easier for all involved.
