### ISSUE TITLE
Changing Alias before View Issue

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#13740]
### Summary

If you edit any resource, change an alias, save, then click the view button the link loads the old alias instead of the new one.  You can do it over and over, MODX always loads the alias from before the change is made and saved.

### Step to reproduce

1. Go to a saved resource
2. Edit the alias field, save, then view resource
3. When viewing the resource, the page loads fine
4. Go back to the resource, edit the alias field, save and view the resource again
5. This results in a page not found until you refresh the page (or double save) in the manager

### Observed behavior

Incorrect (old) URL opened.

### Expected behavior

Updated URL opened.

### Environment

MODX 2.6.1 and before

**Comment by OptimusCrime** [comment]
@pyrographics Could you please use the provided template. There is a reason we have it.

**Comment by digitalpenguin** [comment]
Issue confirmed 2.6.1

**Comment by jonleverrier** [comment]
Steps to reproduce;

1. Go to a saved resource
2. Edit the alias field, save, then view resource
3. When viewing the resource, the page loads fine
4. Go back to the resource, edit the alias field, save and view the resource again
5. This results in a page not found

**Comment by pyrographics** [comment]
Apologies for not filling in the whole template.  I will only submit issues when I have time to do so from now on...if I remember.   Tested in 2.6.1 multiple installations on modxcloud and lamp, the alias change on save appears to not be passing the new alias to the view button so when the view button is clicked it takes the user to the old alias.

**Comment by Mark-H** [comment]
It only takes 30 seconds longer to use the template @pyrographics, that time investment is easily outweighed by the time it saves many volunteers that triage and try to fix issues in understanding the issue. Asking to follow a template is not asking you to sacrifice your first-born.

Thank you @jonleverrier for providing the steps to reproduce.

**Comment by Oetzie** [comment]
I'm going to try and fix this today #modxbughunt

**Comment by jdaehne** [comment]
I am on it too...

**Comment by Oetzie** [comment]
Oke, then i will take a look at another bug :-)

**Comment by Mark-H** [comment]
Fixed in 2.6.2 per #13768 :)
