### ISSUE TITLE
Very Interesting Parser/Chunk/Properties/Placeholder/Filter Bug

### ISSUE THREAD

**Issue by sepiariver** [modxcms/revolution#13744]
### Summary
Counter-intuitive and surprising parsing of Chunks and Properties when Output Filters are used on an unset placeholder. Happy to work on this and submit a PR but could use some help from someone who knows the parser class, and maybe the chunk class (filter class?) really, really well. I've played around with these files a decent amount but the surprising nature of this bug has me puzzled where to look.

### Step to reproduce
Template, Resource, and Chunk code is at this gist:
https://gist.github.com/sepiariver/77651d2611cacfc461d980470ed9ff38

### Observed behavior
**Scenario 1**
The output of the Resource content (without the Template wrapper), from that setup is:
```
<div class="outer">

    <div id="test nested">
    <div class="inner">
    0
    <div class="bar">my string.</div>
    <div class="empty"></div>
    </div>  
    </div> 

</div>
```
See: view-source:https://c0340.paas3.tx.modxcloud.com/index.php?id=1

NOTE: the wrapper for `[[+foo]]` is missing but the value is there. That's an implementation bug, using `:notempty` instead of :is:then:else. 

**Scenario 2**
If you change the `$testInner` Chunk to:
```
    <div class="inner">
        [[+foo:notempty=`<div class="foo">[[+foo]]</div>`]]
        [[+bar:is=``:then=``:else=`<div class="bar">[[+bar]]</div>`]]
        [[+emptyProp:empty=`<div class="empty">[[+emptyProp]]</div>`]]
        [[+unsetProp:notempty=`<div class="unset">[[+unsetProp]]</div>`]]
    </div>
```
NOTE the unsetProp is not commented out anymore.
The output of the Resource content (without the Template wrapper) now is:
```
<div class="outer">
 
</div>
```
See: See: view-source:https://c0339.paas3.tx.modxcloud.com/index.php?id=1
Everything's gone!!

The key factors seem to be:
1. There's an unset placeholder in the inner Chunk. Set but empty placeholders don't cause the issue.
2. The unset placeholder has an output filter applied.
3. THIS IS THE WEIRDEST. Only if the options passed to the output filter contain a `=` character, not only is the output of the inner Chunk blown away, but the property string on the outer Chunk also becomes empty. The quirky behaviour is scoped to that property on the outer Chunk. The rest of the Chunk/Resource rendering proceeds normally. No errors appear in the MODX log and no error file is generated in the document root.

### Expected behavior
Scenario 1
If the `:notempty` filter condition is not met, should it render the value of the placeholder? Or nothing? The expected behaviour is nothing, but in the case of `(int) 0` it will show a string "0". In all other cases of `empty()` being empty, it will render nothing.

Scenario 2
The _entire property string_ for the property "testProp" on the Chunk "testOuter" called in the Resource, disappears! I don't think anyone intended for this to happen...did they? So the expected behaviour is that the rest of the property string remains intact while the conditional is evaluated and the output rendered for that placeholder based on the results.

### Environment
Fresh install on MODX Cloud, no Extras. Reproducible on 2.6.1 and 2.5.8. Also reproduced locally.

**Comment by Bruno17** [comment]
I think, this has todo with the parsing - order.
I never would try to send properties with tags like that to the parser.
I'm rather would do it this way:

resource:
```
[[$testOuter?
    &testProp=`testProp1`
]]
```

chunk testProp1:
```
    <div id="test nested">
[[$testInner?
    &foo=`0`
    &bar=`my string.`          
    &emptyProp=``
]]
    </div>
```

chunk testOuter:
```
<div class="outer">
[[$[[+testProp]]]]
</div>
```

I put the property-code into a chunk and send only the chunkname.
This way the parsing

I will have a look to the empty - issue, later

**Comment by sepiariver** [comment]
Thanks @Bruno17

Yes it’s not a usual case of Chunk usage. Ive never ran into this bug before.

It’s the specific weirdness—you must have a `=` character in the output filter of the nested Chunk’s content and furthermore affects content outside that Chunk, but scopes to the value of a property in the outer Chunk?

Not asking anyone to fix this, I’m curious enough that I will dig into it myself! Just looking for a bit of help/direction :D

**Comment by sepiariver** [comment]
Plausible workarounds include:

1. Setting default values for properties in the inner Chunk's property set
2. What Bruno suggested above if the use case works with it
3. Don't use `=` character inside filter options if placeholder might not be set

#1 seems to be the most reliable, and is good practice anyways because unset placeholders seem to trigger unnecessary passes by the parser.

**Comment by sepiariver** [comment]
@Bruno17  regarding the `empty` filter, it's just how php `empty()` works. `0` evaluates to false as well as the string "0". Updated [this post](https://www.sepiariver.ca/blog/modx-web/wrap-(notempty)-modx-fields/) with a workaround.

**Comment by OptimusCrime** [comment]
Could you see what happens if you revert my patch here: https://github.com/modxcms/revolution/pull/13205/files ?

**Comment by Mark-H** [comment]
There are a number of issues floating around regarding nested calls confusing the parser, in particular #13034. 

I'm going to close as duplicate, but feel free to reopen if it's indeed a separate issue.

**Comment by sepiariver** [comment]
@OptimusCrime FYI reverting that block in the modparser.class.php file doesn't seem to change the quirky behaviour.

@Mark-H I think maybe you linked the wrong Issue ID because #13034 doesn't seem related?

**Comment by Mark-H** [comment]
Whoops, meant #13043, sorry!
