### ISSUE TITLE
regClientScript and regClientHTMLBlock do nothing

### ISSUE THREAD

**Issue by c0mat0se** [modxcms/revolution#13741]
### Summary
When using `regClientScript` or `regClientHTMLBlock` within a plugin, they do not render. I was able to get `regClientCSS`, `regClientStartupScript` and `regClientStartupHTMLBlock` to work with the system events: OnManagerPageBeforeRender, OnManagerPageAfterRender and OnCacheUpdate.

### Step to reproduce
Create a Plugin with the system events listed above, and add the following code to your plugin. 
`$outputJS = $modx->regClientScript('../js/jquery-3.2.1.min.js');
return $outputJS;`
Rename your core/cache folder and clear your system cache. Then load any MODX resource.

### Observed behavior
Nothing is rendered at the end before the body text.

### Expected behavior
It should render a script with "../js/jquery-3.2.1.min.js" in it.

### Environment
MODX Revo 2.6.1

**Comment by bezumkin** [comment]
For manager you need to use `$controller` variable:
```
$modx->controller->addHtml('<script>Ext.onReady(function() {' . $script . '});</script>');
```

At the moment of firing OnCacheUpdate, I believe, all scripts and styles should be already registered - so it is just too late.

**Comment by c0mat0se** [comment]
Hmm. I might need some more context on this. 

I am trying to render my locally saved jQuery file at the end of the body tag, as rendering it in the head does not allow me to target any of the input fields in MODX. Maybe this is not the best way to do it.

Now when I plugin your script above, I get the following in the head:
`<script>Ext.onReady(function() {../js/jquery-3.2.1.min.js});</script>`

Passing my own jQuery into the head after this still does not accomplish what I am trying to do.

Thanks for your help!

**Comment by jonleverrier** [comment]
@c0mat0se Not sure this is a bug...

Perhaps you're looking for `OnDocFormPrerender` and `$modx->regClientStartupHTMLBlock`

```
switch ($modx->event->name) {
    // load on system event OnDocFormPrerender
    case 'OnDocFormPrerender':
        
        $modx->regClientStartupHTMLBlock('
            <script src="../js/jquery-3.2.1.min.js"></script>
        ');

break;
}
```

**Comment by bezumkin** [comment]
Do you need jQuery inside MODX **Manager** (inside admin part of site)? If so - that is simple
```php
if ($modx->event->name == 'OnManagerPageBeforeRender') {
    $controller->addHtml('<script src="/assets/js/jquery-3.2.1.min.js"></script>');
}
```

**Comment by OptimusCrime** [comment]
This code:

```
<script>Ext.onReady(function() {../js/jquery-3.2.1.min.js});</script>
```

Is not valid JavaScript. That will never work, regardless of plugins and hooks.

**Comment by c0mat0se** [comment]
Hi Bezumkin,

Thank you for that! jQuery is now in the head. 

Unfortunately, it looks as though I cannot target anything in the manager with jQuery because it is rendered before anything on the page. I think that's why I would have to render it at the end near the closing `</body>` tag. 

Is there any way with the php you provided above to have it be rendered at the end of the page?

Sorry for all of the questions... I should have used the forums for this probably...

**Comment by bezumkin** [comment]
> Unfortunately, it looks as though I cannot target anything in the manager with jQuery because it is rendered before anything on the page.

Maybe you need to wrap your jQuery code into this?
```
$(window).on("load", function() {
  // Things that need to happen after full load
});
```

**Comment by c0mat0se** [comment]
Interestingly enough, that seems to work!

I had it previously wrapped in:
` 
$( document ).ready(function() {
        // Things that need to happen after full load
});
 `

and that did not seem to work.

Thank you for your help Bezumkin. Greatly appreciated!

**Comment by bezumkin** [comment]
https://jquery.com/upgrade-guide/3.0/#breaking-change-on-quot-ready-quot-fn-removed
