### ISSUE TITLE
Custom Manager Pages don't Scroll

### ISSUE THREAD

**Issue by jarofgreen** [modxcms/revolution#13759]
Initially discussed at https://forums.modx.com/thread/103479/creating-custom-page-can-039-t-scroll-it but after further investigation I'm pretty sure this is a bug in ModX or the docs so passing on.

Basically, it looks like the ModX JS never sets an explicit height on the div's surrounding custom manager pages, and thus scroll doesn't work.

**Comment by bezumkin** [comment]
This is just an basic example in MODX docs, so you should look into sources of existing extras with CMP to learn how to create them today. You can register your own CSS for your extra with any styles.

I believe it should be closed

**Comment by Mark-H** [comment]
This indeed is something that should be better explained in the docs, but is not necessarily a bug due to the way extjs works.

**Comment by jarofgreen** [comment]
Please try and see things from my point of view.

I have followed the official documentation on https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/custom-manager-pages-in-2.3 and my new custom manager page can't scroll, which is pretty basic functionality. There is no way I can turn my page over to users if they can't scroll it.  

You seem to be saying this is expected behaviour in ModX, and I have to do more work to make scroll work. But it's not documented anywhere. 

This makes it hard for me, or any other outside developer coming to ModX, to know what to do.


To be more exact with my questions:

@bezumkin 

> This is just an basic example in MODX docs, so you should look into sources of existing extras with CMP to learn how to create them today.

Is there any more docs that would help with this? Specifically, with making scroll work?

Can https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/custom-manager-pages-in-2.3 be edited to link to them?

> You can register your own CSS for your extra with any styles.

Yes, I know, I have done that before. $this->addCss() in your controller right? But how does that help in this case? What CSS should I add to get Scroll to work?

@Mark-H  

> This indeed is something that should be better explained in the docs,

Can you help me ask the right questions so people update the documentation to help with this? I would argue that documentation that does not cover basic functionality is incomplete.

>  but is not necessarily a bug due to the way extjs works.

I don't really see how this is relevant. I'm not trying to use extjs, I'm trying to use ModX. To that end I have followed the official ModX guide. If there is problems with how extjs works, I would expect that to be covered in the ModX Code or Guide. 




Thanks,
James

**Comment by Mark-H** [comment]
Hey @jarofgreen - sorry, didn't mean to dismiss your troubles. Was trying to say that this is better discussed elsewhere, as it's not a bug in the sense that the core has to be fixed. 

The MODX manager is built with ExtJS, which brings some design decisions with it. One of them being that the content is not by default a scrollable thing. It expects an interface built with ExtJS, which becomes a scrollable region.

The "Developing an Extra" tutorial is rather in-depth: https://docs.modx.com/revolution/2.x/case-studies-and-tutorials/developing-an-extra-in-modx-revolution - in particular part 2 which details setting up the extjs bits and pieces to make it all work.

There is also a non-extjs way to build components, where you can indeed just build HTML and use your own CSS/JS to do what you want, but while looking for the instructions I can't seem to find them, so I've created an issue in our docs tracker about that https://github.com/modxcms/docs/issues/232

**Comment by Mark-H** [comment]
Here you can find a JavaScript way to enable proper scrolling, part of the (as I just found out, undocumented) parsed controller class: https://github.com/modxcms/revolution/blob/2.x/core/model/modx/modmanagercontroller.class.php#L1013-L1025

**Comment by jarofgreen** [comment]
Hello. Thank you for your replies.

We have managed to solve this by adding some JavaScript to set the height manually onload and on window resize. It's not perfect but seeing as we already have a load of pages that just output HTML and they scrolled fine in older versions we don't have the time to migrate to ExtJs fully now. If we have more problems with this we will look into modParsedManagerController more.

Can I suggest an addition to https://docs.modx.com/revolution/2.x/developing-in-modx/advanced-development/custom-manager-pages/custom-manager-pages-in-2.3 - at the end add something like:

"Unfortunately, there is a major problem with the page we have just created. It won't scroll. If you replace the content in your template with some long paragraphs of text copied and pasted from somewhere you can see this.

This is because of how ModX uses the ExtJS framework to structure our admin interface.

If you want to read more on how to make a custom admin page unlocking the full power of ExtJS, please see the "Developing an Extra" tutorial.

If you want to just make your page scroll without using ExtJS, please see the new documentation from https://github.com/modxcms/docs/issues/232" 

Thanks again,
James
