### ISSUE TITLE
System setting to change the error log path and error log name

### ISSUE THREAD

**Issue by IamNeo1** [modxcms/revolution#13752]
I am looking for an system setting to change the default error log path and the name.
I am logging to a different path with an error_handling snippet and i want to see the log at the modx error log page. Currently it is empty, because it expects the defaut path an name ".../cache/logs/error.log"

It is similar to this request #12352

**Comment by OptimusCrime** [comment]
Please use the issue template.

**Comment by christianseel** [comment]
I'm working on this right now…
