### ISSUE TITLE
emoji

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#13777]
### Summary
MODX don`t support emoji.

### Step to reproduce
From tablet or mobile phone:
1. Edit the resource using a tablet or mobile phone.
2. Paste emoji in resource.
3. Save.
4. Refresh page.

From Google Chrome:
1. Edit the resource.
2. Copy/paste this 😢 in resource.
3. Save.
4. Refresh page.

### Observed behavior
MODX removes all data in the resource (in pagetitle, content, description, etc) that are behind the emoji.

### Expected behavior
MODX will not delete data from resource.

### Environment
MODX 2.6.1 with visual editor (TINYMCE RTE) and without

**Comment by OptimusCrime** [comment]
Do you use utf8mb4 as database type? This is required for emojies to work, as they require this.

Read here: https://stackoverflow.com/questions/39463134/how-to-store-emoji-character-in-my-sql-database

**Comment by meshkov** [comment]
I use utf8. I will try to convert db.

**Comment by meshkov** [comment]
I converted db to utf8mb4 with sorting utf8mb4_unicode_ci, and everything is working fine.

**Comment by OptimusCrime** [comment]
@meshkov So emojis are now working? 😀 

If it is, please close this issue.

**Comment by meshkov** [comment]
Yes, now working.
