### ISSUE TITLE
Issue: Typo on label for Template Variable> Input Options

### ISSUE THREAD

**Issue by chrisdempsey** [modxcms/revolution#13776]
### Summary
Just a typo.

### Step to reproduce
Edit or create a Template Variable.  The label for Input Option Values has a typo.

### Observed behavior
At the end of the line the Input Options Label reads:  _White==#000000||Black==#ffffff_

### Expected behavior
Should read _White==#ffffff||Black==#000000_

### Environment
MODX Revolution 2.6.1-pl

**Comment by Mark-H** [comment]
Nice find.

Care to send a pull request? :) Looks like it's defined here: https://github.com/modxcms/revolution/blob/2.x/core/lexicon/en/default.inc.php#L493

Normally translations are managed through [crowdin](http://translate.modx.com/) but English is the exception as it's the source language; that one is managed through pull requests.

**Comment by chrisdempsey** [comment]
Pull request created (on second attempt, I need to learn to start using Github properly).

**Comment by Mark-H** [comment]
Fixed in 2.7!
