### ISSUE TITLE
AMP

### ISSUE THREAD

**Issue by funkyduke** [modxcms/revolution#13787]
Just a quick question. I suppose AMP is no problem to integrate with websites made with Modx? AMP is new to me. Any thoughts on AMP?

https://www.ampproject.org

**Comment by Mark-H** [comment]
The issue tracker is not for questions, please use the forum or slack ;) 

A quick google gave me the following links:

- https://modx.com/extras/package/ampify
- https://www.sepiariver.ca/blog/modx-web/amp-ify-your-modx-site/
- https://github.com/modxcms/ampify
- https://www.sterc.nl/blogs/verandert-amp-het-landschap-van-mobiel-internet
