### ISSUE TITLE
default favicon.ico can overwrite custom one with git/composer installs

### ISSUE THREAD

**Issue by rthrash** [modxcms/revolution#13788]
### Summary
The git installation includes an ancient favicon.ico in web root that could overwrite an existing 
custom one.

### Step to reproduce
Install via git or composer into a directory with a custom favicon present.

### Observed behavior
![image](https://user-images.githubusercontent.com/234237/36512403-e01cd21e-172f-11e8-8ce5-b24aa28e054c.png)

### Expected behavior
![image](https://user-images.githubusercontent.com/234237/36512415-ee76ba5a-172f-11e8-92a0-01544319274b.png) … or whatever custom favicon.ico file that actually existed previously.

The default content can have a basic favicon and assets/ and the Manager could get a more robust set in the manager path as well. Suggested graphics found in the [favicons.zip](https://github.com/modxcms/revolution/files/1746140/favicons.zip) archive.

### Environment
~~A. MODX installs from Downloads on MODX.com
B. MODX installs from third-party installers like Bitnami~~
C. Hipster-compliant installs via git/composer
~~D. All of the above
E. None of the above~~

**Comment by Mark-H** [comment]
What exactly did you do, and what exactly did you expect it to do?

AFAIK, neither a git clone nor the new composer create-project (which I assume you mean by "hipster compliant installation..?) will let you install into a non-empty directory. And if it did, how do you propose it should handle conflicts that arise wether a favicon or core files?

At any rate, this is for setting up new projects, not for importing into existing projects, so I'm tempted to close. However as this is about a very new feature, I'm happy leaving it open for a little longer to allow us to work through potential issues or lacking docs.

**Comment by rthrash** [comment]
Jason and I discussed this earlier and he requested an issue be opened. There was sarcasm in the environment. ;)

**Comment by Mark-H** [comment]
That doesn't even _attempt_ to answer my questions...

Keep in mind that issues should make sense and be actionable to people without access to whatever private conversations you may have. As it stands, this doesn't seem actionable to me and is either missing critical steps to reproduce, or is simply invalid...

The only fixable thing I see is the favicon being behind a few iterations but that does not seen to be the focus of the title nor summary of the issue... If that was the primary concern, I'd suggest editing the issue to clarify that.

**Comment by opengeek** [comment]
The problem is that having a favicon.ico in the root of the project will overwrite custom favicons people put in their project roots. It is also not used anywhere that I can see. Having it there is both irrelevant and problematic. It's not even included in the zip distributions. Removing it seems like the best solution, IMO.

**Comment by opengeek** [comment]
To be clear, if I install via git and want to update from git, I cannot put a custom favicon.ico in my project root because this one already exists.

**Comment by Mark-H** [comment]
It shouldn't be overwriting anything as you can't install into a non empty directory to my knowledge, but happy to see it gone if it outlived its purpose. New logo looks better anyway ;)

Edit: looks like I just missed your second comment about updating. That makes sense and would've been useful in the issue description.

**Comment by opengeek** [comment]
Read my previous comment, please.

**Comment by Mark-H** [comment]
Read my edit :p I'm slowly typing on a small screen, sorry.

**Comment by opengeek** [comment]
LOL. GitHub apparently does not present edits unless I reload. Sorry.
