### ISSUE TITLE
Message system sends group messages to wrong or nonexistent users

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#13795]
### Summary
If you select the 'usergroup' option in the Manager's message System, the messages are sent to the wrong recipients. 

### Step to reproduce
Send a test message to a user group.

### Observed behavior
Some (or all) messages don't arrive. Some messages get sent to non-group members or members that don't exist.

### Issue

The problem is that the security/message/create processor uses the ID of the record in the modx_member_groups table as the user ID instead of the 'member' field.

### The fix (tested)

It's a simple change to one line of code (line 135 in my version) in the processor:

File: core/model/modx/processors/security/message/create.class.php 

    `public function getRecipients($users, $primaryKey = 'id') {
            /** @var xPDOSimpleObject $user */
            $recipients = array();
            foreach ($users as $user) {
               if ($user->get($primaryKey) == $this->modx->user->get('id')) {
                      continue;
                }
               -  $recipients[] = $user->get('id');
               + $recipients[] = $user->get($primaryKey);
            }
            return $recipients;
     }
`

The bug is sometimes masked by the fact that the ID of the member_group_,member record may be the same as the user ID.

Let me know if you want a PR.

**Comment by OptimusCrime** [comment]
We always want PRs, otherwise someone else will need to redo the change you just did :)

However, I might add that we are currently debating if we should remove the messages as a part of the core in the upcoming 3.x release and instead make it a separate extra. Reason being that it is a complex system and not very much used. Might be worth considering here. Ping @Alroniks

**Comment by alroniks** [comment]
Fixed in this PR https://github.com/modxcms/revolution/pull/13390 and works as expected. Closing.
