### ISSUE TITLE
Disable 'sudo' field for non-sudo users

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#13806]
### Summary
Prevent non-sudo users from elevating themselves or other to 'sudo'.

### Step to reproduce
Edit any user, by any user, the 'sudo' checkbox is available.

### Observed behavior
A user can elevate himself or another user to 'sudo'.

### Expected behavior
A non-sudo user should not even see the sudo checkbox, and most certainly should not be able to elevate himself or another user to 'sudo'.

### Environment
Any

![screen shot 2018-03-06 at 20 47 08](https://user-images.githubusercontent.com/1073780/37051709-e16e2ab4-217f-11e8-9db6-dd71f63fe93a.png)

**Comment by Bruno17** [comment]
but, by default, no one is a Sudo User, right?
So, no one would be able to set any Sudo User.

I think, it has to be a permission, if you can set Sudo Users

**Comment by ghost** [comment]
The installed default user is Sudo.

**Comment by Bruno17** [comment]
you are right, sorry
But I still think, there should be a permission 'set_sudo' or something like that

**Comment by ghost** [comment]
This is intended as step one of tightening user management. Only sudo can do suso, step 2 only Administrator can do Administrator, step three otherwise user managers can only deal with users in the same groups as the current user. Or something along those lines. But one step at a time.

**Comment by akimsullec** [comment]
It can be managed by plugin.

**Comment by labr1005** [comment]
@akimsullec How?

**Comment by akimsullec** [comment]
```
$en = $modx->event->name;
switch ($en) {
    case 'OnUserBeforeAddToGroup':
    case 'OnUserBeforeRemoveFromGroup':
    case 'OnUserBeforeSave':
        $user_current = (int)$modx->user->get('id');
        $user_managed = $user->toArray();
        if ($user_current !== 1 && (int)$user_managed['id'] === 1){
            $modx->false();
        }
        if($user_current !== 1 && (int)$user_managed['id'] !== 1) {
            if ($en === 'OnUserBeforeAddToGroup'){
                $user_group = $usergroup->toArray();
                if ( (int)$user_group['id'] === 1 || (int)$user_group['id'] === 4 ) {
                    $modx->false();
                }
            }
            if ($en === 'OnUserBeforeSave'){
                if ((int)$user_managed['sudo'] === 1){
                    $modx->false();
                }
            }
        }
        break;
    case 'OnUserDuplicate':    
    case 'OnUserBeforeRemove':
        $user_current = $modx->user->get('id');
        if ($user_current !== 1){
            $modx->false();
        }
        break;
    default:
  	break;
}
```
This is for one of my projects. There are only one godlike admin :)
Also there can be rewrited for checking the id of group.

**Comment by alroniks** [comment]
The pull request also has an explicit discussion. I would say that is solved. If not, please, reopen.
