### ISSUE TITLE
Make manager search function search by ID

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#13803]
### Summary
Feature request to make Search box in the Manager search by ID.  Error messages for snippets and plugins give the ID of the element, but not its name, so it would be really nice to be able to find the offending object on a large site by searching by ID.

I'd suggest just adding 'id' to the fields being searched.  Will do a PR.

### Observed behavior
If you use an ID in the search, no results are returned.

### Expected behavior
Return objects with matching IDs

### Environment
MODX 2..6.1

**Comment by alroniks** [comment]
Seems it's already implemented and PR is merged. Should be closed.
