### ISSUE TITLE
Problem with system settings

### ISSUE THREAD

**Issue by salamanderer** [modxcms/revolution#13816]
### Summary
If user set "cache_system_settings" = 0 (No), system setting didn't apply automatically. Even if he change it back to "cache_system_settings" = 1 (Yes)!
So user definitely must perform two actions: 1)set "cache_system_settings" = 1 (Yes), after that - 2)clear the folder "/core/cache/" manually.

### Step to reproduce
Set "cache_system_settings" = 0, change "site_name" for the visible effect, refresh the page. 
Then set "cache_system_settings" = 1, change "site_name" for the visible effect, refresh the page. 

### Observed behavior
The site name changed in visible system settings.
The site name didn't apply in both cases.

### Expected behavior
The site name changed in visible system settings.
The site name applied in both cases.

### Environment
Any i think, (my version of Modx is MODX Revolution 2.6.1-pl)

**Comment by JoshuaLuckers** [comment]
I'm closing this because `cache_system_settings` has been removed as a setting in system settings for new installations.
