### ISSUE TITLE
Seychelles not showing up in country list

### ISSUE THREAD

**Issue by SB401** [modxcms/revolution#13822]
### Summary
Seychelles not showing up in the dropdown list of countries on the user management page.

I posted this issue in modx community forum and Bob Ray found that the problem is that the lexicon/country/en.inc.php contains 2 countries with the sc placeholder

$_country_lang["sc"] = 'Seychelles'; // Seychelles
$_country_lang["sc"] = 'Sint Maarten (Dutch part)'; // Sint Maarten (Dutch part)

Changes the second line to:
 $_country_lang["sx"] = 'Sint Maarten (Dutch part)'; // Sint Maarten (Dutch part)

fixes the problem

### Step to reproduce
Go to manage>user. 
Double click on a username to open the user info page. 
Click the Country dropbox in the general information tab 

### Observed behavior
Seychelles is not included in the list

### Expected behavior
Seychelles should be included.

### Environment
MODX Revolution 2.6.1-pl .

**Comment by alroniks** [comment]
PR is merged, so closing.

**Comment by JoshuaLuckers** [comment]
~~Commit 322046af701ee4a7baac5f14b1f4169b07a8d1ec reintroduces this issue.~~
