### ISSUE TITLE
Creating a ressource with " (quotes) in the title make the ressource not editable

### ISSUE THREAD

**Issue by squarou** [modxcms/revolution#13825]
### Summary
When I create a ressource with quotes in the title, I can't edit the ressource after CMP reload.
It works if right click in the tree and quick edit.

### Step to reproduce
Create (or rename) a ressource with quote : For example : Lorem "ipsum"
Save
Reload or reopen the ressource

### Observed behavior
The CMP is empty 
![image](https://user-images.githubusercontent.com/6338874/37700036-5b4188ca-2cea-11e8-90f9-2b50e3a2b40e.png)

### Expected behavior
There should be the edition fields
### Environment
MODX 2.6.1, php 7.1

**Comment by Mark-H** [comment]
Hm, an issue exactly like this was fixed in a recent update. Have you made sure the browser cache was cleared since updating?

**Comment by squarou** [comment]
Hi Mark, the same issue is related by different users with differents browsers.
I cleared the cache yes.

**Comment by Mark-H** [comment]
Okay, you'll have to do some more digging then as it's not a known issue in 2.6.1 and the issue doesn't give enough details to fix it atm. Resources with quotes work fine in 2.6.1 in my testing.

Start by looking at the browser developer tools for javascript errors. Could be a core issue, but could also be an issue caused by an extra.

**Comment by Jako** [comment]
Are there any JS errors in the browser console?

**Comment by ghost** [comment]
Revo 2.6.1, PHP 7.1.1, MODx Cloud new installation. Works as expected.

**Comment by squarou** [comment]
Ok. After looking at XHR console, no error message, no alert...
By comparing the loading XHR request on another resource, I identified that other connectors were loaded from modules : adminTools, Tagger and versionX.
By renaming the resource without quotes and reloading the resource, those connectors load well.

==> So my conclusion is that issue is not related to MODx processor, by related to one of this extensions.

Thank you all for your help, I'm closing the ticket.
