### ISSUE TITLE
Could not load class: xPDOTransport from transport.xpdotransport

### ISSUE THREAD

**Issue by gpsietzema** [modxcms/revolution#13841]
### Summary
When installing any extra in the 3.x branch, you get this error.

### Step to reproduce
Go to Extras > Installer -> install an extra

### Observed behavior
Extra installs fine, but you get this error mentioned in red: Could not load class: xPDOTransport from transport.xpdotransport

### Expected behavior
No error message.

### Environment
MODX on 3.x branch, nginx, php 7.1

**Comment by BobRay** [comment]
I'm seeing this as well.

**Comment by bezumkin** [comment]
@gpsietzema We can merge #13888 to current 3.x code - it will fix this error.

**Comment by alroniks** [comment]
It seems PR was merged, so it's a reason to close this ticket.
