### ISSUE TITLE
Remove type="text/javascript"

### ISSUE THREAD

**Issue by ezersky** [modxcms/revolution#13846]
### Summary
The validator.w3.org shows an error when connecting scripts using $modx->regClientScript or $modx->regClientStartupScript . 

After removing type="text/javascript" from strings:

- core/model/modx/modmanagercontroller.class.php
- core/model/modx/modmanagercontrollerdeprecated.class.php
- core/model/modx/modx.class.php

we have successful page validation by the validator.w3.org

**Comment by JoshuaLuckers** [comment]
Relevant discussion: https://github.com/modxcms/revolution/pull/13850

**Comment by Ibochkarev** [comment]
HTML5 no longer requires an explicit type statement. Can we delete this?

```html
<!-- HTML4 -->
<script type="text/javascript" src="javascript.js"></script>

<!-- HTML5 -->
<script src="javascript.js"></script>
```

**Comment by alroniks** [comment]
Closed because it merged with https://github.com/modxcms/revolution/pull/15533
