### ISSUE TITLE
Feature request: Sort by access field when editing template (TV's tab)

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#13842]
### Summary
When editing a template you can not sort the enabled Template Variables results by access on/off. Would be nice if you could sort the Templates Variables based on if they are active or not. This makes it easier te see a list of all TV's that are enabled for the current template, this is especially handy when have lots of TV's and want to check which TV's are enabled for the current template.

**Comment by ghost** [comment]
Try the extra ModDevTools. It adds a lot of small features to the Manager.

![screen shot 2018-03-29 at 15 28 34](https://user-images.githubusercontent.com/1073780/38088836-eeb7f888-3365-11e8-9a98-5e2090e611b1.png)

**Comment by sdrenth** [comment]
@sottwell In my opinion these improvements should live in the core and should not be added through an extra.

**Comment by Jako** [comment]
Sorting the template variables by access is possible without an extra here in a 2.6.1 installation.

This should be the possible after this commit since 2.6.0 https://github.com/modxcms/revolution/commit/3a9f912a45b8d119551b9a9d7928805b474b2d0c

**Comment by sdrenth** [comment]
@Jako Should have checked with the latest version first, checked with a new install and this has already been fixed indeed! So i'm closing this issue.
