### ISSUE TITLE
MODX3 / MariaDB Validation Error

### ISSUE THREAD

**Issue by sofasurfer** [modxcms/revolution#13867]
### Summary
I tried to install MODX3 with MariaDB and getting an error when validating the DB connection. The same setups also runs MODX2 Pages.

### Step to reproduce
Install MODX3 via composer, enter DB information and click on test Database

### Observed behavior
I got this ERROR in the AJAX Call
`
Fatal error: Uncaught Error: Class 'xPDO' not found in /var/www/modx3/setup/includes/drivers/modinstalldriver_mysql.class.php:155 Stack trace: #0 /var/www/modx3/setup/processors/database/connection.php(71): modInstallDriver_mysql->verifyServerVersion() #1 /var/www/modx3/setup/includes/request/modinstallconnectorrequest.class.php(81): include('/var/www/modx3/...') #2 /var/www/modx3/setup/processors/connector.php(31): modInstallConnectorRequest->handle() #3 {main} thrown in /var/www/modx3/setup/includes/drivers/modinstalldriver_mysql.class.php on line 155
`
### Environment
MODX3, nginx/1.10.2, 5.5.56-MariaDB, PHP Version 7.1.11,

**Comment by labr1005** [comment]
Not sure if this is related, but I had the same problem with MySQL 5.5(.42). But it worked with MySQL 5.6(.38).

**Comment by JoshuaLuckers** [comment]
Is this issue still relevant?

**Comment by alroniks** [comment]
It was fixed by this pr https://github.com/modxcms/revolution/pull/14274

**Comment by sofasurfer** [comment]
Thank you for the Update!
