### ISSUE TITLE
MIGX grid TV reload images when unfolds folded elements tab on left

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#13860]
### Summary
MIGX grid TV reload images when unfolds folded elements tab on left inside Elements tree.

### Step to reproduce
Here is short video how it happens: https://monosnap.com/file/Wdm7qIrQ4z20uQXihYzicAyMabU0sU#

1. Create MIGX TV via MIGX-Config, one column should has image
2. Open it: Template Variables -> appropriate tab for this new TV -> this new TV  
3. Play with any elements tab - try to close it, then reopen

### Observed behavior
Images on the right are constantly jump and refresh, which is annoying, especially when there are a lot of them

### Expected behavior
It seems to me that opening the resource tree tab should not affect the updating of MIGX (and any other TV data on the right), images should be rest in peace.

### Environment
MODX Revolution 2.6.0-pl (traditional), ExtJS Version: 3.4.1, migx-2.12.0-pl

**Comment by OptimusCrime** [comment]
@himurovich How is this not a bug in migx?

**Comment by ant-tar** [comment]
@OptimusCrime thanks for clarification, I made a mistake in a hurry and will move it to https://github.com/Bruno17/MIGX

**Comment by OptimusCrime** [comment]
@himurovich No problem. I was just wondering if you checked if the problem was caused by either MODX or MIGX, as I suspected that it would be caused by the latter. However, there is also a possibility that the problem is caused by MODX. If the problem is not in MIGX itself, feel free to reopen this issue.
