### ISSUE TITLE
Demo content copyright date incorrect

### ISSUE THREAD

**Issue by mkschell** [modxcms/revolution#13872]
### Summary
The demo content created with a new installation contains the copyright year 2016. This should be updated to the correct year, or better, made dynamic to always show the current year.

### Step to reproduce
Install MODX Revolution.

### Observed behavior
See incorrect copyright year on the default resource on the front end.

### Expected behavior
One would expect to see the current year in the copyright notice.

### Environment
All new MODX Revolution installations where the demo content is applied to the default single resource that is created.

**Comment by JoshuaLuckers** [comment]
In my opinion the copyright year in the demo content and other files should be changed when a new major version is released.

MODX3 is right around the corner, updating the copyright year before releasing 3.0 might be a good idea.
