### ISSUE TITLE
Undo removal of system setting "manager_language"

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#13883]
### Summary
#13786 (amongst other things) removed the possibility to manually set the manager (and login screen) language globally, for usergroups or specific users.

IMO the part that changed the manager_language handling should be reverted respectively it should be possible to define which mode to use - auto detect or manual.

Some more opinions on this from Slack:

> I like it better to specify. The Norwegian language is terrible, and we usually just force them to use english.

> also if you're doing SSO into the manager you may not see a login screen, if anyone does that sort of thing

> yeah, it definitely needs to be manageable, not just automated or set from login, people aren't going to want to switch it manually on every login if the auto selection is not what they wanted

> Yes please have it configurable on top of auto-detect.

### Observed behavior
It's not possible to manually set the manager (and login screen) language globally, for usergroups or specific users.

### Expected behavior
It should be possible to manually set the manager (and login screen) language globally, for usergroups or specific users.

### Environment
MODX 3

**Comment by Mark-H** [comment]
> I like it better to specify. The Norwegian language is terrible, and we usually just force them to use english.

One translation being terrible is not a very good reason to take away a very useful autodetection feature. If anything, that is an argument for people to spend time on their translation to ensure it is usable and helps their local geographic manage their sites in their native language. 

> also if you're doing SSO into the manager you may not see a login screen, if anyone does that sort of thing

SSO integrations can set the language in the session they create. This could be hardcoded, fed in from a third party system that knows what language people want to use or have the same autodetect as the standard login. 

> yeah, it definitely needs to be manageable, not just automated or set from login, people aren't going to want to switch it manually on every login if the auto selection is not what they wanted

I believe the chosen language is stored in a cookie, not just the session, so it doesn't revert to an auto selection every single time; only when the user has not yet chosen one in which case it will look at browser language. But that's worth testing to be sure.

> Yes please have it configurable on top of auto-detect.

How would configuration and auto detect work together? If the configuration overrides the auto detect, that means auto detect is useless. If auto detect overrides configuration, that means configuration is useless. From a core perspective, I don't see how you can have both. 


In my opinion, 90% of the arguments against the changes to how the language is handled in the manager boils down to change aversion. People are used to having a setting, and feel like they're losing control, while in reality that control is only handed down from the admin to the users themselves who can now easily change their language themselves. And by automatically detecting the browser language, people don't even have to think about it in most cases: it just works!

The 10% with an actual problem should be addressed. But that should be done by investigating those specific problems and coming up with a solution that addresses them specifically. 

Reverting #13786 (or even just reverting the part that changed the manager_language handling) is not an option in my opinion.

**Comment by labr1005** [comment]
When a company decides that it's business language is Xyz and they want their CMS to be in this language for all employees, you're taking away that possibility.

All I'm doing is to communicate a need of most of our clients.

**Comment by ghost** [comment]
What will be the default language if the user's browser language isn't available? How will individual selection of preferred language work if the user has cookies deleted on closing the browser, or on leaving the site? Will the user have to change his preferred language on every login?

**Comment by Mark-H** [comment]
And then six months later they hire an external consultant who doesn't speak that business language and they need to get back to you to figure out how to set the language for just that user? Languages are personal, not business... I've had to debug so many issues on MODX sites with a hardcoded language, that I can almost navigate the user settings without understanding the language by now.

**Comment by labr1005** [comment]
I'll leave this conversation now. I agree on most of your points and I didn't say that the feature as it is is bad or wrong. I'll either go with a custom login page or with a plugin to set the language. I suggest to leave this issue open for a couple more days and see how the conversation develops. Feel free to close it any time.

**Comment by Jako** [comment]
A user setting should at least overwrite the detected language. I don't like to work per default in an german manager, because most of the docs are in english. And I would prefer a system wide setting. 

If the current code will not be changed: Please add a dashboard widget or menu entry with a dropdownselect, that could quickly change the manager language and save that in a user setting.

**Comment by Mark-H** [comment]
Sorry if I was too harsh/dismissive, had a bit of a bad day yesterday.

**Comment by labr1005** [comment]
Closing this because of no progress and #13945 was closed.
