### ISSUE TITLE
Mysqlv8 compatibility issue

### ISSUE THREAD

**Issue by faradaytrs** [modxcms/revolution#13881]
### Summary
Quick summary what's this issue about.
Even clean install has blank dashboard
### Step to reproduce
How to reproduce the issue, including custom code if needed.
install mysqlv8 + clean modx
### Observed behavior
How it behaved after following steps above.
Everything works except for dashboard
### Expected behavior
How it should behave after following steps above.
Dashboard should work
### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.
I use Caddy 0.10.14, mysqlv8

**Comment by opengeek** [comment]
You'll need to provide some idea of what errors occurred during installation. Check error logs and provide additional information, please.

**Comment by JoshuaLuckers** [comment]
Without the relevant information we are unable to solve this issue. Feel free to open a new issue providing the requested information.
