### ISSUE TITLE
Error TV filter

### ISSUE THREAD

**Issue by wm-simon** [modxcms/revolution#13880]
When i use the following snippet there is an error in MODX. gallery_id is 8728355.

Snippet:
```
[[[[+gallery_id:isempty='
Redirectoid?
&id='67'
&context='photo'
']]]]
```

Error:
[2018-04-26 13:56:09] (ERROR @ /core/model/modx/modparser.class.php : 540) Could not find snippet with name 8728355.

But code works fine, just getting an error.

**Comment by FerX** [comment]
try:
```
[[+gallery_id:is=``:then=`empty`:else=`not empty`]]
```

**Comment by wm-simon** [comment]
This will always redirect, no matter if the id is emtpy or not.

**Comment by FerX** [comment]
I'm sorry but I can not understand what to do

**Comment by OptimusCrime** [comment]
Did you change the markup? Because you should use forward ticks `, not apostrophe in the MODX syntax.

This is wrong:

```
[[[[+gallery_id:isempty='
    Redirectoid?
        &id='67'
        &context='photo'
']]]]
```

This is correct:

```
[[[[+gallery_id:isempty=`
    Redirectoid?
        &id=`67`
        &context=`photo`
`]]]]
```

Could you please try this?

**Comment by wm-simon** [comment]
I use the correct markup, just had here some problems with the parsing of the code.
Here is the real code, should be the same as yours @OptimusCrime : https://jsfiddle.net/8q80L308/#&togetherjs=HUUMCIQmjj

**Comment by OptimusCrime** [comment]
I am pretty sure this is a problem because of the parsing order. If `Redirectoid` is invoked as the snippet is parsed, then this will because problems.

I suggest simply rewriting it like this:

```
[[my-snippet?
    &input=`[[+gallery_id]]`
    &redirectId=`67`
    &redirectContext=`photo`
]]
```

**my-snippet**

```
if (!empty($input)) {
    return null;
}

return $modx->runSnippet('Redirectoid', [
    'id' => $redirectId,
    'context' => $redirectContext,
]);
```

Simple as that.

This is not really a bug, as the parsing is correct they way MODX interprets it.

**Comment by Jako** [comment]
@Pfeifakopf Your code above depends on when the `[[+gallery_id]]` placeholder is filled. This could sometimes happen later than the placeholder code is parsed first. `[[+placeholder]]` tags often survive the parsing better than `[[+placeholder:xxx]]` tags (with modificators). If you use cached/uncached snippets this could get even worse.

So please check if the placeholder is set in an uncached snippet, then the placeholder has to be called uncached. If the placeholder is created outside of a snippet call and if it is used inside of a snippet template chunk, try to submit that placeholder into the snippet by a snippet call property. I.e. ```&gallery_id=`[[+gallery_id]]` ``` (Not every snippet could work with that, i.e. pdoResources does).

**Comment by JoshuaLuckers** [comment]
It seems to me that this is not a bug in MODX. Feel free to open a new issue if you feel otherwise. 👍
