### ISSUE TITLE
[3.x] Flash swf file success check in installation summary shows as warning

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#13890]
### Summary
That the flash file isn't there is a good thing, shouldn't be styled as warning.

![schermafbeelding 2018-05-03 om 12 09 20](https://user-images.githubusercontent.com/312944/39571239-29b1d7bc-4ecb-11e8-9d0b-2774dfe21b56.jpg)

I think this was introduced in #13814

### Step to reproduce
Install 3.x branch from git which has that file removed already

### Observed behavior
Styled as warning.

### Expected behavior
Styled as success

### Environment
Revision 2f762359b163674cd6e845a52d6de72111547cb3

**Comment by alroniks** [comment]
Issue fixed in 3.x.
