### ISSUE TITLE
Resource creation and parameters to preset setting values

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#13891]
### Summary

URL parameters can change important settings of a new resource.

### Observed behavior

Create new resource: 
* manager/?a=resource/create 

OK

Create new resource with parent=2:
* manager/?a=resource/create&parent=2 

OK, the parent of the new resource is preset to 2

Create a new resource with template=3 
* manager/?a=resource/create&template=3 

OK, the template of the new resource os preset to 3

Create a new resource with template=3 AND parent=2
?a=resource/create&parent=2&template=3

BOOM, template is ignored, but parent is preset to 2.

Theory, only the first parameter is processed.

Let's switch the position of the parameters:
?a=resource/create&template=3&parent=2

I'd expect template to work this time, but again only parent is processed.

I have no idea how to explain that...

### Step to reproduce

Use the urls string above to check it out.

### Expected behavior

Right now it seems that only one parameter can be preset. URL parameters should effect the default settings of new resources. It should also be possible to preset multiple resource properties.

On top of this I believe that every resource setting should be effected by url settings during creation.

Incomplete list of fields that can not be preset: class_key,  content_type, etc.

### Why is this important?

Dashboard can be very useful to provide customized links to create resources with a range of presets.

I suppose that manager customization or plugins could be used to have a similar effect, but it is much more complicated and less intuitive.

If we can already preset template OR parent, why can't we preset both or even more settings?

### Environment
Current MODX (2.6.3 as well as older versions).

**Comment by pepebe** [comment]
Update:

It seems that this could be related to the publish state of the parent resource (yes, this doesn't make any sense). If I publish the parent and then create a new child by using this link:

?a=resource/create&template=3&parent=2

Everything works as expected.

**Comment by Mark-H** [comment]
Setting both the template and parent works fine here - are you sure you're not triggering any form customisation defaults with the parent (or template)? Or that you have another plugin that's setting the template based on parent?

**Comment by alroniks** [comment]
Works fine for me as well. So, closing.
