### ISSUE TITLE
MODX 3.0 - 3x-redesign branch - Package Manager not installing packages

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/revolution#13896]
### Summary
When testing 3.0, I tried to install some packages. Packages were downloaded, but the installation process was broken.

### Step to reproduce
Install an extra using the Package Manager

### Observed behavior
500 Internal Server Error shown in the console.

### Expected behavior
Extra should be installed

### Environment
MODX version: 3.0 , Mamp :)

<img width="1425" alt="screen shot 2018-05-08 at 21 32 54" src="https://user-images.githubusercontent.com/447453/39825937-6363719a-53b3-11e8-9dd8-8ab49496b6f5.png">

**Comment by Ibochkarev** [comment]
This bug has been fixed earlier. Packages are installed correctly.
Tested on the latest version installed from the composer.

I vote for closing this request.
