### ISSUE TITLE
3.x Regex validation for text TVs not working correctly

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#13899]
### Summary
Some simple regular expressions seem to work, but others don't.

### Step to reproduce
Create a text-type TV
In the Regular Expression input, put any of these expressions to validate a 3-digit number (with or without enclosing delimiters):

```
^\d\d\d$
\d\d\d
^\d{3}$
\d{3}
```
Edit the TV in a resource.

### Observed behavior
Anything you type appears to be valid.

Strangely, the following regular expression works as expected:

`hello|goodbye`

The input must contain hello or goodbye.

I couldn't find the code that actually validates the input.

### Expected behavior
Invalid message unless input is a 3-digit number

### Environment
MODX 3.0.0 Windows 10. PHP 7.1

**Comment by OptimusCrime** [comment]
What browser did you use? Can you also try this expression: `^[0-9]{3}$`?

**Comment by BobRay** [comment]
Results are the same in both Chrome and Firefox.  Your expression works, so apparently the regex engine we're using is not PCRE compliant. I see that \d is not supported by POSIX (or GNU grep), though it's a pretty standard usage in my experience. Validating a phone number gets pretty verbose without it and it's certainly recognized by any recent version of JavaScript. 

Is this an ExtJS issue?

If we're stuck, I guess this would be an option: [convert PCRE to Regexp](https://www.npmjs.com/package/pcre-to-regexp)

**Comment by OptimusCrime** [comment]
I am not sure why it does not work. `\d` should work fine in javascript as far as I am aware. As long as Extjs uses the in-browser regex engine (and not a drop-in replacement) it should work out of the box. We will have to dig a bit deeper on this one.

**Comment by JoshuaLuckers** [comment]
I found the problem. When using `\d` all values are invalid. Except when using an actual d.
This means the `\` is being ignored/removed.

When I use `\\d` it works like expected.

**Comment by JoshuaLuckers** [comment]
The [MDN documentation on RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp) states the following: 
> When using the constructor function, the normal string escape rules (preceding special characters with \ when included in a string) are necessary. For example, the following are equivalent:
```javascript
var re = /\w+/;
var re = new RegExp('\\w+');
```

**Comment by BobRay** [comment]
I had a similar problem  with a regex search function in a processor I was writing that It used the MySQL regex engine. 

This odd-looking function solved it:

```
function(fixRegex) {
    return addcslashes(preg_quote($searchTerm), "\0'\"\n\r\x1A"); 
        // charlist = All characters that escape by real_escape_string except backslash;
}
```

**Comment by OptimusCrime** [comment]
I think we can just use the regular `addslashes` in this case.

**Comment by BobRay** [comment]
Possibly, though not if the backslashes have been removed before it runs. 

addcslashes escapes all the regex characters that need escaping.

**Comment by JoshuaLuckers** [comment]
Escaping the input was not needed to solve this issue.

**Comment by BobRay** [comment]
Joshua, in your earlier comment, you said that the backslashes were ignored or removed. If they are removed, addcslashes would be required to put them back. 

The issue is clearly complicated. I have an Ajax call that sends regular expressions to a MODX processor.  Any backslashes are automatically doubled in the request to the processor, but somehow still require that function to work.

**Comment by JoshuaLuckers** [comment]
> Joshua, in your earlier comment, you said that the backslashes were ignored or removed. If they are removed, addcslashes would be required to put them back.

Today I researched the problem a bit more and figured out that the backslashes are "ignored" instead of removed. For more info and technical details see the pull request I made: #13916 

> The issue is clearly complicated. I have an Ajax call that sends regular expressions to a MODX processor. Any backslashes are automatically doubled in the request to the processor, but somehow still require that function to work.

This issue is about the regex validation for text TV's. I think that the problem with the processor and AJAX calls you outline is separate from this and should be discussed in another issue.

**Comment by BobRay** [comment]
Agreed. The AJAX issue might have been relevant if the backslashes were being removed, but as you found, they're not. Good sleuthing. 👍

**Comment by alroniks** [comment]
PR with fixes merged, so closing this one. If any issues will be found, please, reopen the ticket.
