### ISSUE TITLE
MODX 3.0 - 3x-redesign branch - Trash can not deleting 

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/revolution#13895]
### Summary
When I deleted a resource using the Resource Tree context menu, the resource tree gets refreshed and the resource is marked as deleted, but the trash can symbol is still inactive. 

### Step to reproduce
see above.

### Observed behavior
The user cannot purge the deleted resources. The trash can becomes active only after a page refresh 

### Expected behavior
When you click on the trash can, it should delete the resources marked as "deleted".

### Environment
MODX version: 3.0 , Mamp :)

**Comment by jonleverrier** [comment]
Can't reproduce this in
MODX3 Alpha v 3.0.0-dev
Chrome Version 67.0.3396.99

![modx3_trashcan](https://user-images.githubusercontent.com/2373940/42331246-3efdd964-8075-11e8-8ac1-aefa221e45e0.gif)

**Comment by OptimusCrime** [comment]
@sonicpunk What browser and version did you use?

**Comment by jonleverrier** [comment]
Can't reproduce in Firefox 61.0 or Safari 11.1 either

**Comment by JoshuaLuckers** [comment]
I'm unable to reproduce this issue. Feel free to reopen the issue if this is still not working for you.
