### ISSUE TITLE
Creating a new Media Source starts with an error message

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#13918]
### Summary
When creating a new Media Source the dialog instantly gives an error on the "Source Type" field.

### Step to reproduce
Create a new Media Source

### Observed behavior
It starts with an error because there is no default "Source Type" selected.

### Expected behavior
It should not give an error immediately. Give the error when the Media Source is being saved or add an option to set a default source type. Preferable defaulting to "sources.modFileMediaSource".

### Environment
MODX 2.6.*, 3

**Comment by alroniks** [comment]
To avoid conflicts during merging fix should be applied to 3.x version where media sources already refactored.

**Comment by meshkov** [comment]
Confirmed in MODX 3
![2018-07-23_12-56-59](https://user-images.githubusercontent.com/1703670/43070285-219442bc-8e78-11e8-9c3c-3ccb6f0bda46.png)

**Comment by JoshuaLuckers** [comment]
To fix this issue it's best to introduce a new setting for the media source source type: `default_media_source_type` with a default value of `sources.modFileMediaSource`.
This way users can change the default source type.

**Comment by meshkov** [comment]
Can we rename "sources.modFileMediaSource"? Now it confused
![image](https://user-images.githubusercontent.com/1703670/67837241-a7c7bb80-faff-11e9-919a-01281f95864e.png)

**Comment by JoshuaLuckers** [comment]
@meshkov thanks for taking time sharing your suggestion, can you open a new issue for your suggestion because this issue is closed and it might go unnoticed.

**Comment by meshkov** [comment]
@JoshuaLuckers  done. https://github.com/modxcms/revolution/issues/14818
