### ISSUE TITLE
Increase the default value for "password_generated_length"

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#13919]
### Summary
The default value for the setting "password_generated_length" is 8. In the code responsible for generating the password the default value is set to 10.

### Step to reproduce
Install MODX.

### Observed behavior
Value for "password_generated_length" is set to 8

### Expected behavior
It should be consistent with the value in the code. Or the value in the code has to be adjusted to 8.

### Environment
MODX 2.6.*, MODX 3.0.*

**Comment by alroniks** [comment]
My bet is to increase value in system settings. It will make MODX a bit more secure.
