### ISSUE TITLE
Add packages required for developing to composer.json

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#13910]
### Summary
When you install MODX through composer packages for development are not installed. To help new contributors set up a development environment it would be helpful if the development packages were included in composer.json.

### Step to reproduce
Download the MODX source via Git, composer etc.

### Observed behavior
composer.json has a list of required packages but it's missing the packages required for development (like the correct phpunit version).

### Expected behavior
composer.json should include require-dev packages.

**Comment by OptimusCrime** [comment]
Which other packages does this concern other than PHPUnit?

**Comment by JoshuaLuckers** [comment]
At the moment PHPUnit seems to be the only one (it has to be a specific version to get it work with the current MODX unit test code).

**Comment by pbowyer** [comment]
@modxbot close
