### ISSUE TITLE
Error with ModSecurity rules enabled on hosting

### ISSUE THREAD

**Issue by liberty2010** [modxcms/revolution#13917]
### Summary
After entering a certain set of characters in the text, editing becomes impossible

### Step to reproduce
If you insert certain lines into a text field or a text editor (created as migx), the following editing of the block is impossible: https://prnt.sc/jmibwk.
This happens only when ModSecurity is enabled on the hosting

**Lines:**
0,001/128,18 = 0.000007801529 AUD 0.000007801529 х 50000 = 0.390 AUD
or
0.390 х 2,0600 = 0,8034

### Observed behavior
https://prnt.sc/jmibwk
But the text on the site is displayed.
An error occurs in the control panel in the console:
/assets/components/migx/connector.php:1 -> Failed to load resource: the server responded with a status of 424 (Failed Dependency) ->
-> {"success":false,"message":"\u0414\u043e\u0441\u0442\u0443\u043f \u0437\u0430\u043f\u0440\u0435\u0449\u0451\u043d.","total":0,"data":[],"object":{"code":401}}

### Expected behavior
Field must be editable

### Environment
MODX Revolution 2.6.2-pl, apache, MySQL 5.7., PHP 5.6, ModSecurity.
http://1264322.libe.web.hosting-test.net/phpinfo.php

**Comment by ghost** [comment]
MODX has a great deal of AJAX (Javascript remote calls) going on, especially when MIGX is involved. If something triggers a server's ModSecurity blocks, there is nothing to be done. This is not a MODX issue, but a server configuration issue.

**Comment by liberty2010** [comment]
Ok. Thanks
