### ISSUE TITLE
Make modNative hasher the default password hash_class in MODX 3

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#13927]
### Summary
#13926 introduces a new modNative hasher that uses native PHP functions to hash and verify passwords. The MODX core should be updated to use modNative by default on new users.

- [x] For supported database drivers, set the `modUser.hash_class` default to `hashing.modNative` 
- [x] In a database migration script, update the table schema for existing sites. 

With these 2 steps, any newly created user will be given a natively hashed password.  

I've not included this in #13926 because the status of the model in MODX 3 is currently a bit in limbo and the core's model build script 1) errors out and 2) upgrades the entire model to xPDO 3 (unsuccessfully) when fixed and executed. 

### Updating existing user accounts

See #13928.

**Comment by JoshuaLuckers** [comment]
@Mark-H are there still any blockers open that prevent us from implementing/moving forward with this?

**Comment by Mark-H** [comment]
Jason immediately made it the default for new users in https://github.com/modxcms/revolution/commit/a5df4b1e5ed6f35edb287a0b6c06288f4e906ce2 (as part of my PR https://github.com/modxcms/revolution/pull/13926) so this issue is complete and closed.
