### ISSUE TITLE
set-cookie secure flag is incorrect

### ISSUE THREAD

**Issue by shamarin** [modxcms/revolution#13921]
If to setup secure cookie to "yes" in "session and cookies" settings Set-Cookie HTTP header will be 
"Set-Cookie: PHPSESSID=...; secure; HttpOnly". But "secure" flag must be "Secure" (from capital letter) and that's why https://observatory.mozilla.org/ showing that secure flag for cookies is not setup if to check site.
Correct this error.

**Comment by shamarin** [comment]
Found that the bug is with CookieList addon for MODX https://modx.com/extras/package/cookielist. If this plugin is installed he add to Set-Cookie "cookieList[cl_check]=1". With this in header Mozilla site showing that cookie is without secure flag. And if to set "Set-Cookie: Secure, HttpOnly" it will be ok. In Mozilla documentation Set-Cookie secure flag is "Secure" with capital letter.

**Comment by OptimusCrime** [comment]
Could you please follow the provided template? I am not sure where to go look for this cookie. Is it during setup or the entire system?

**Comment by OptimusCrime** [comment]
If the problem is caused by a third party extra, then you should report this problem in their repository, not here.

This is their repository by the way: https://github.com/Mark-H/CookieList

Can you verify that this problem is not related directly to the MODX core?

**Comment by shamarin** [comment]
Also it's MODX bug because in all documentation secure cookie flag must be "Secure". Maybe I'm wrong. But if to unistall this addon Mozilla site showing that cookie is with secure flag.

**Comment by OptimusCrime** [comment]
@shamarin Could you please explain where you see this problem? I am still not sure what is going on. As far as I know, we do not construct any cookies on our own, we just use the PHP method `setcookie`.

**Comment by shamarin** [comment]
Go to system settings, core, cookies and session, set cookie to secure. I think that it's not a bug of MODX core now, because if to unisntall this addon everything is ok.

**Comment by Mark-H** [comment]
Thanks for taking the time to report an issue :) 

I've logged Mark-H/CookieList/issues/7 as it turns out CookieList is hardcoded to keep HttpOnly and Secure off. That should not have any effect on core cookies, just the ones CL uses. Perhaps that's flagging Mozilla's test, not because it affects the core cookies, but because it causes there to be cookies without those flags. 

Like @OptimusCrime says though, I don't think MODX nor CookieList have any control over the casing in the attributes.

**Comment by Mark-H** [comment]
Looks like RFC 6265 states the Secure and HttpOnly flags are case insensitive: https://tools.ietf.org/html/rfc6265#section-5.2.5

**Comment by shamarin** [comment]
Ok, thank you.

**Comment by OptimusCrime** [comment]
@modxbot close
