### ISSUE TITLE
MODX_CACHE_DISABLED doesn't work in the config file

### ISSUE THREAD

**Issue by degoya** [modxcms/revolution#13937]
### Summary
The Config Setting MODX_CACHE_DISABLED for disabling the Cache in the config file is not working

### Step to reproduce
set the the cache to false in the config file

### Observed behavior
cache is still generated

### Expected behavior
cache should be disabled

### Environment
Modx 2.6.4, NGINX

#### in the Changelog of the MODX 2.0 Beta i found the following comment
modX->getCacheManager() no longer supports MODX_CACHE_DISABLED or config['cache_disabled']; the cacheManager is required, though you will still be able to effectively turn off all caching in the future via this setting (this will be worked back in)

but is seems this didn't got worked back in yet. But why is the setting still available in the default config?

how can i disable the caching with the config file?

**Comment by Mark-H** [comment]
At least 2 issues about this already exist:  https://github.com/modxcms/revolution/issues/12938 https://github.com/modxcms/revolution/issues/10121

That feature is not implemented and I highly doubt it ever will, as disabling caching is not a good thing to do.

Closing as duplicate.
