### ISSUE TITLE
MODX 3: can't change manager language

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13945]
### Summary
MODX 3 was installed in a german language environment so the installer automatically chosed "de" as manager language. But I'd like to change the manager language from "de" to "en". Changed all language related system settings to "en" -> cleared cache -> reloaded site but still German.

### Expected behavior
Changing the system setting to "en" should change the manager interface language. 

### Environment
MacOS 10.13.5 German
MODX version: MODX 3 alpha
browser: Safari (german)

**Comment by gadgetto** [comment]
Just realized that there is no longer a `manager_language` setting. What is the intended method for changing the language in manager?

**Comment by gpsietzema** [comment]
Just change it at the login and it will remember it.

**Comment by gadgetto** [comment]
Ok, this works. But I don't think this is very intuitive. Why removing the system setting?

**Comment by OptimusCrime** [comment]
This was decided a while back. Also, we can not have both the system setting and allowing the user to chose the language during login.

**Comment by gadgetto** [comment]
OK, issue can be closed.

**Comment by OptimusCrime** [comment]
@modxbot close
