### ISSUE TITLE
MODX3: Errors in log all displaying on one line. (Firefox)

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#13946]
### Summary
All errors are displaying on a single line in the error log.

### Step to reproduce
View the error log page when errors have been logged.

### Observed behavior
There are no new lines / line breaks

### Expected behavior
Each error should be on it's own line.

### Environment
MODX 3.0 alpha. PHP 7.1, Firefox 60

**Comment by gadgetto** [comment]
Hmm, can't reproduce this. In my environment it's fine. But I got the MODX 3 version from @bezumkin which seem a bit ahead of the official one.

**Comment by muzzwood** [comment]
Hmmm ok. This is the zip download with dependencies included.

**Comment by gadgetto** [comment]
I'm testing this version: https://cloud.2head.ru/s/iRbxnxcNwXHTzc6 which is the full build with all dependencies included.

**Comment by muzzwood** [comment]
Actually I just tried with Chrome and it works fine. It seems to be a Firefox specific issue.

**Comment by muzzwood** [comment]
This is Firefox 60 running on Ubuntu 18.04
If you're on a different platform, could you try with Firefox and see if it's platform specific?

**Comment by muzzwood** [comment]
Removing `white-space:nowrap` fixes the issue. 
However it also changes the behaviour in Chrome so that each line wrapped rather than overflow.

**Comment by shamarin** [comment]
Confirm, in Firefox log error is displaying in one line.

**Comment by jonleverrier** [comment]
Confirmed too, that in FF the error log is displaying on one line.

**Comment by muzzwood** [comment]
Thanks for confirming, will attempt a PR.

**Comment by muzzwood** [comment]
Closing due to PR  #13966.

**Comment by muzzwood** [comment]
Re-opening issue until PR is merged.

**Comment by Jako** [comment]
I don't think that this is a pure CSS issue. That nowrap attribute makes sense because locating a new log line is easier then.

Please locate why Firefox does not wrap after one log line.

**Comment by alroniks** [comment]
PR is merged, so closing.
