### ISSUE TITLE
MODX 3: dashboard widget "Updates" is empty (when manager language is "de")

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13944]
### Summary

See screenshot:

<img width="553" alt="bildschirmfoto 2018-07-03 um 07 39 36" src="https://user-images.githubusercontent.com/876737/42200612-73b480d2-7e94-11e8-8893-95f4ae0c600d.png">

I tried to change language to "en" - clear cache but nothing changed.

### Environment
MacOS 10.13.5 German Language
MODX version: MODX 3 alpha
PHP version: 7.1.12
Browser: Safari, Chrome

**Comment by gadgetto** [comment]
When manager runs in "en" the widget texts are displayed. So only missing language strings...

**Comment by OptimusCrime** [comment]
Pretty sure the languages are not syncronized yet, so a lot of strings are missing. I think you should test in english first.

**Comment by Ibochkarev** [comment]
This should get resolved the next time the lexicons are synchronized with crowdin.

**Comment by Ruslan-Aleev** [comment]
In my opinion the bug is not relevant anymore

**Comment by Ibochkarev** [comment]
Thanks for taking time to report this issue and help make MODX better.
Please reopen if you still encounter this issue.
@modxbot close
