### ISSUE TITLE
MODX 3: Manager Customization not working properly for the Document tab

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#13941]
### Summary
In manager customization, if I opt to put a TV in "modx-resource-main-left", the TV no longer appears above the Content field, it shows up below it!! That's not where I want it. If I assign the TV to "modx-resource-content", it shows up in the same place, under the Content field. So, now there is no difference between "modx-resource-content" and "modx-resource-main-left".

### Step to reproduce
Assign a TV to modx-resource-main-left.

### Observed behavior
In the past, this puts TVs under whatever is in the left panel, but above the Content field.

### Expected behavior
TVs assigned to modx-resource-main-left should be ABOVE the Content field. Or, at least, some way should be provided to determine where the Content field is going to sit in the Document tab now that it is no longer in its own panel underneath everything.

### Environment
MODX 3.0 alpha

**Comment by jonleverrier** [comment]
Confirmed.

MODX3 Alpha v 3.0.0-dev
Chrome Version 67.0.3396.99

**Comment by Ibochkarev** [comment]
![изображение](https://user-images.githubusercontent.com/2138260/111813164-0c590580-8903-11eb-9adc-ee18781b98d8.png)

Fixed https://github.com/modxcms/revolution/pull/15552

**Comment by SnowCreative** [comment]
What exactly is the fix? Your screen shot shows the TestTV field below Content, rather than above it.

**Comment by Ibochkarev** [comment]
I am getting better. I did not fully understand the problem.

In 2.8.1

![изображение](https://user-images.githubusercontent.com/2138260/111815725-35c76080-8906-11eb-93ac-71b648e810c2.png)

In 3.x

`modx-resource-content` is inside `modx-resource-main-left`. Therefore, it is displayed below, you need to take out `modx-resource-content` from `modx-resource-main-left`

![изображение](https://user-images.githubusercontent.com/2138260/111816049-9060bc80-8906-11eb-97c7-a66decf64eb5.png)

**Comment by SnowCreative** [comment]
Right. Or, like we're doing now for modx-resource-main-right, create subsections: modx-resource-main-left-top,  modx-resource-main-left-bottom. These wouldn't be separate panels like on the right, but really just sections of the single panel. This would let us put TVs above or below the content.

So, the three divs right above modx-resource-content would get wrapped together in a div with ID "modx-resource-main-left-top", which would then be available in the manager customization. Like this:

![neworder](https://user-images.githubusercontent.com/2528374/111826338-f45f9280-88be-11eb-9ba8-8c13796a653e.jpg)


But really, "modx-resource-content" is not a separate panel any more, so structurally it makes more sense changing the name to modx-resource-main-left-bottom.

**Comment by theboxer** [comment]
To position fields below or above content you can use `modx-content-above` and `modx-content-below`.

![image](https://user-images.githubusercontent.com/845220/137147709-bb889b0d-c0b8-4349-a2c5-14e53053fd18.png)
![image](https://user-images.githubusercontent.com/845220/137147762-531687f7-8f3c-4992-b7ea-4b4d9d290205.png)
