### ISSUE TITLE
MODX 3: new checkbox toggle switches - graphical glitch on small screen sizes

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13947]
### Summary
The new checkbox toggle switches have a graphical glitch on smaller screen sizes. It seems the glitch only happens when the checkbox label consists of not only one single word and a word break happens. Please see screenshot:

<img width="243" alt="bildschirmfoto 2018-07-03 um 09 11 13" src="https://user-images.githubusercontent.com/876737/42204279-84b5460c-7ea1-11e8-825b-f63c100285c6.png">

### Step to reproduce
Create a new resource (or open an existing one). Resize browser window until the toggle switch falls apart.

### Environment
MODX version: MODX 3 alpha
Browser: Safari, Chrome

**Comment by jonleverrier** [comment]
I can reproduce this too in Chrome.

It's related to these styles having `top: 50%;` applied.
```
#modx-resource-tabs .x-fieldset legend [type="checkbox"]:checked + .x-form-cb-label:after
#modx-resource-tabs .x-fieldset legend [type="checkbox"] + .x-form-cb-label:after
```
either add the below to the above styles only
```
left: 0.1em;
top: 0.8em;
```
or 

```
#modx-resource-tabs .x-form-check-wrap [type="checkbox"] + .x-form-cb-label:after, #modx-resource-tabs .x-form-check-wrap [type="checkbox"] + .x-fieldset-header-text:after, #modx-resource-tabs .x-fieldset-checkbox-toggle legend [type="checkbox"] + .x-form-cb-label:after, #modx-resource-tabs .x-fieldset-checkbox-toggle legend [type="checkbox"] + .x-fieldset-header-text:after, #modx-resource-tabs .x-fieldset legend [type="checkbox"] + .x-form-cb-label:after, #modx-resource-tabs .x-fieldset legend [type="checkbox"] + .x-fieldset-header-text:after {
    left: .1em;
    top: 0.8em;
    margin-top: -.65em;
    height: 1.3em;
    width: 1.3em;
    border-radius: 50%;
    background-color: #fff;
    z-index: 11;
}
```
which works, but not sure what the impact is with the other class names. needs more testing.

**Comment by alroniks** [comment]
Closing as PR is merged. Thank you for reporting.
