### ISSUE TITLE
MODX 3: Login - No hover style on login button

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13950]
### Summary
I appreciate this is a small detail...

When you hover over the Login button, no hover style is triggered.

### Step to reproduce
Hover over the Login button.

### Observed behavior
No hover style is triggered.

### Expected behavior
For consistency, a hover style should be triggered like the other green buttons used within the manager (as an example, like the save button on a resource page).

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

Button hover
![screen shot 2018-07-03 at 11 10 59](https://user-images.githubusercontent.com/2373940/42210643-cc64c47c-7eb1-11e8-8518-0c94af426b9c.png)

Button
![screen shot 2018-07-03 at 11 10 56](https://user-images.githubusercontent.com/2373940/42210644-cc82915a-7eb1-11e8-9621-0341fedc83f1.png)

Login button on hover
![screen shot 2018-07-03 at 11 10 31](https://user-images.githubusercontent.com/2373940/42210646-cca18a2e-7eb1-11e8-83ee-483abf313757.png)

**Comment by meshkov** [comment]
Why are you closing?

**Comment by alroniks** [comment]
Closing as PR is merged.
