### ISSUE TITLE
MODX 3: small graphical glitches in resource editor

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13959]
### Summary
- all whitespaces should be same size
- and there is a light shadow behind the active tab

<img width="760" alt="bildschirmfoto 2018-07-03 um 11 01 21" src="https://user-images.githubusercontent.com/876737/42218285-59f37f48-7ec8-11e8-9357-a734e19cb071.png">

**Comment by Ibochkarev** [comment]
@gadgetto After making changes to the styles of the administrative panel. This bug is not relevant.

**View at the moment:**
![2019-01-24_16-38-40](https://user-images.githubusercontent.com/2138260/51672796-9395e180-1ff6-11e9-96a5-c443c7e706f6.png)

I vote for closing issue

**Comment by alroniks** [comment]
It seems Mark fixed it in a more radical way :) Feel free to reopen.
