### ISSUE TITLE
MODX 3: Manager Sidebar - Width is increased after browser resize

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13954]
### Summary
If you resize your browser window to a small size and then increase it, the sidebar width becomes very large and overlaps content below.

### Step to reproduce
1. Load the manager
2. Shrink your browser in width to see the "mobile" view
3. Resize your browser back again

### Observed behavior
The sidebar becomes large.
The content below the sidebar is no longer full width.

![screen shot 2018-07-03 at 11 57 38](https://user-images.githubusercontent.com/2373940/42213474-22ae2f1a-7eb9-11e8-826e-dc42aa7f0a39.png)

### Expected behavior
The sidebar to retain it's original width after resize.

### Environment
MODX3 Alpha v 3.0.0-dev
From 3.x branch and https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99
Firefox 61.0
Safari 11.1

**Comment by jonleverrier** [comment]
Is this a problem inherited from MODX 2.x does anybody know?

**Comment by Mark-H** [comment]
Fixed in #14271 - though we have seemed to regress and the manager no longer works properly on mobile.
