### ISSUE TITLE
MODX 3: graphics/design suggestions for buttons (consistency!)

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13958]
### Summary
In the name of **consistency** - how about this color changes for buttons:

- green button color for primary buttons matches green checkbox toggle color
- the heavy darkblue hover color on other buttons should be changed to something light
- also changed the icon size of fa icons to icon-large which looks much better in my opinion

![2018-07-03 10_17_50](https://user-images.githubusercontent.com/876737/42218179-02b9108a-7ec8-11e8-9c1a-540e93f6750f.gif)

**Comment by alroniks** [comment]
Issue solved via https://github.com/modxcms/revolution/pull/14306. Thank you!
