### ISSUE TITLE
MODX 3: Resource/Elements/File Tree - contrast of row stripes

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13957]
### Summary
The row stripes in the resource/element/file tree have such little contrast between the light and dark colours, that they can't be seen on budget or old monitors with less colours. 

I mention this, because in general, i'm finding the new Resource/Elements/File Tree very grey, and lacks contrast that helps with viewing the general hierarchy of content.

![screen shot 2018-07-03 at 13 11 13](https://user-images.githubusercontent.com/2373940/42216689-fa574772-7ec2-11e8-8716-05f9b765f2cd.png)

### Step to reproduce
View resource/element/file tree on a cheap monitor or view on a regular monitor

### Observed behavior
Resource/element/file tree have such little contrast between the light and dark colours

### Expected behavior
If it can't really be seen, why display it? It just creates extra eye fuzz.

Removing the stripes or increasing the contrast of the stripes, might add more overall contrast to the resource/element/file tree in general - as i'm finding it hard to distinguish between:
1. The hierarchy of Templates, Template Variables, Chunks, Snippets, Plugins, Categories compared to MODX 2.x.x
2. Open folders/categories in Templates, Template Variables, Chunks, Snippets, Plugins, Categories compared to MODX 2.x.x
3. Viewing active / selected elements compared to MODX 2.x.x
4. The bin icon being active vs non active 
5. Hidden / non hidden resources

![screen shot 2018-07-03 at 13 22 48](https://user-images.githubusercontent.com/2373940/42217124-46b1385c-7ec4-11e8-80a3-86b188ac6630.png)

Related: 
https://github.com/modxcms/revolution/issues/13969
https://github.com/modxcms/revolution/issues/13960

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by meshkov** [comment]
Why are you closing?

**Comment by jonleverrier** [comment]
i've just built MODX from the 3.x branch in github, which has a slightly different resource, elements and file tree. spacing in this area looks much tighter with more clarity and focus. i'm going to close this ticket for the time being.
