### ISSUE TITLE
MODX 3: Login - Animation between login and forgot password forms

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13952]
### Summary
I appreciate this is a small detail...

I wonder if the animation between the login and forgot password forms should be changed. On initial first click it seemed a little busy and sluggish as it animated between form content.

### Step to reproduce

1. Go to the Login
2. Click "Forgot your password?" link
3. Observe the animation
4. Click the "Back to login" link"
5. Observe the animation

### Observed behavior
Between the animation, both forms are loaded fully on the page which might give the _perception_ of it loading slowly.

![screen shot 2018-07-03 at 11 30 24](https://user-images.githubusercontent.com/2373940/42211724-85b1a060-7eb4-11e8-9c0d-b1b54acdd246.png)

### Expected behavior
Perhaps a different animation should be used - something that gives the _perception_ that the content is loading faster than it currently is.

### Environment
MODX3 Alpha v 3.0.0-dev
Chrome Version 67.0.3396.99

**Comment by Mark-H** [comment]
Any proposed solutions for this?

**Comment by jonleverrier** [comment]
@Mark-H - I would say horizontal animation vs vertical might feel quicker. i'm closing this because it's not going to stop launch.
