### ISSUE TITLE
MODX 3: Resource/Elements/File Tree - no active state / colour 

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13956]
### Summary
When you click on a resource or element, there is no active colour to indicate what page you have clicked on. I think this would be useful to add some contrast, now that many shades of grey have been introduced.

### Step to reproduce
1. Create a chunk called "inc_example_1"
2. Create another chunk called "inc_example_2"
3. Now click on the chunk called "inc_example_1"

### Observed behavior
There is no visual indicator to show you what you've clicked on, or what you are currently viewing. This is particularly important for sites with many elements or resources.

### Expected behavior
To display an active state.

Here I have clicked on the chunk called "callLogin"

![screen shot 2018-07-03 at 13 05 01](https://user-images.githubusercontent.com/2373940/42216331-ce01bd8e-7ec1-11e8-9911-955acaf866e9.png)

Here I have clicked on the chunk called "callLogin" in MODX 2.6.4

![screen shot 2018-07-03 at 13 05 22](https://user-images.githubusercontent.com/2373940/42216357-e5c6ff4c-7ec1-11e8-9f21-9317695e82ae.png)

**Related**
https://github.com/modxcms/revolution/issues/13960

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by alroniks** [comment]
Close as PR is merged.
