### ISSUE TITLE
MODX 3: Empty size-selection dield for new Dashboard Widgets

### ISSUE THREAD

**Issue by jdaehne** [modxcms/revolution#13955]
### Summary
By adding a new Dashboard-Widgets, i can select empty options for sizes.
This only happens in a german MODX site. If i change "manager_language" to anglish. Everything is ok.

![bildschirmfoto 2018-07-03 um 12 21 13](https://user-images.githubusercontent.com/10563227/42214358-a4d3e046-7ebb-11e8-8990-1338f34c3a05.png)

### Step to reproduce
1. go to dashboard
2. click button "add +" in the right top corder
3. select options in field "size"

### Expected behavior
This empty options should be removed or "named".

### Environment
MODX3 Alpha v 3.0.0-dev

**Comment by alroniks** [comment]
It looks like that German strings have not been translated (or didn't placed into the build) yet. I would close it but let's wait when translation will be finished.

**Comment by Ibochkarev** [comment]
@modxbot close
Fixed
