### ISSUE TITLE
MODX 3: Manager Sidebar - Sidebar position whilst loading

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13953]
### Summary
I appreciate this is a small detail...

As the manager is loading, the avatar, settings and help icon change position from being placed just below the "Manage" icon, to being positioned at the bottom of the browser window. This causes a slight jump in content and causes distraction, especially for those with a slow internet connection.

### Step to reproduce
1. Login to the manager and keep an eye on the placement of your avatar, settings and help icon.
2. Browse around other pages and notice the jump/change in position as the page loads.

![screen shot 2018-07-03 at 11 41 37](https://user-images.githubusercontent.com/2373940/42212742-4ad8a274-7eb7-11e8-9cfa-41f4374d7d39.png)

![screen shot 2018-07-03 at 11 50 55](https://user-images.githubusercontent.com/2373940/42212779-66628c80-7eb7-11e8-8cd0-b42e7ef95345.png)

### Observed behavior
The jump seems to be caused whilst the browser loads the javascript, which then applies a height to the sidebar.

### Expected behavior
Perhaps some CSS should be applied such as 'vh', 'vmin', 'min-height' or even a 'height: 100%;' to the sidebar, whilst the javascript loads, to make it feel less jumpy and give the impression the manager is loading faster than it actually is.

### Environment
MODX3 Alpha v 3.0.0-dev
Chrome Version 67.0.3396.99

**Comment by OptimusCrime** [comment]
Why are you closing all these issues?

**Comment by alroniks** [comment]
Close as PR is merged.
