### ISSUE TITLE
MODX 3: Media Browser - multiple selection of files shows text highlighting 

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13963]
### Summary
I appreciate this is a small detail...

If you select multiple files in the Media Browser - after you've selected more than 1-2 files, the browsers text highlighting starts to show. 

### Step to reproduce
1. Upload 10 image files
2. Hold down shift and start to multiple select images

### Observed behavior
After selecting the 2-3 image, the browser highlighting starts to show.

![screen shot 2018-07-03 at 14 54 38](https://user-images.githubusercontent.com/2373940/42221124-53d29fdc-7ed1-11e8-8844-7a3c0bb9245f.png)

![modx3_mediabrowser_multiselect_1](https://user-images.githubusercontent.com/2373940/42221554-b1dc5d56-7ed2-11e8-8b23-ed7d6f57f293.gif)

### Expected behavior
Browser highlighting of the thumbnails can be disabled by adding this CSS to `.modx-browser-thumb-wrap`
```
user-select: none;
```
https://caniuse.com/#feat=user-select-none

Fixed with user-select:

![modx3_mediabrowser_multiselect_2](https://user-images.githubusercontent.com/2373940/42221652-17ceed72-7ed3-11e8-80e6-a1328a958948.gif)

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by alroniks** [comment]
Closing as PR is merged. Thank you for reporting.
