### ISSUE TITLE
MODX 3: Media Browser - Rename Files

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#13967]
### Summary
Rename files in Media browser does not work correctly

### Step to reproduce
Try to rename several files
1. Go to Media browser
2. Rename first file
3. Try to rename another file

![ifchbiz5j7](https://user-images.githubusercontent.com/1703670/42276528-c478189a-7f9c-11e8-995a-12916d06289a.gif)

### Observed behavior
Renamed file exist only after refreshing page

### Environment
MODX 3.0
Chrome Version 67.0.3396.99

**Comment by jonleverrier** [comment]
Confirmed. 

Just to clarify, the first file you rename works fine. But when you rename another file, you get the following error

![screen shot 2018-07-04 at 17 01 33](https://user-images.githubusercontent.com/2373940/42284188-07e47d26-7fac-11e8-992b-ca19e65738f2.png)

MODX3 Alpha v 3.0.0-dev
Chrome Version 67.0.3396.99

**Comment by Ibochkarev** [comment]
I confirm this bug.
MODX 3.0.0-pl installed through composer.

**Comment by Ibochkarev** [comment]
Fixed in #14772 
@modxbot close
