### ISSUE TITLE
MODX 3: Media Browser - uploads can't be seen until refresh

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13962]
### Summary
When you upload a file in the Media Browser either by using the upload icon or dragging files onto the manager, you can't see that they have been successfully uploaded into you refresh your view.

### Step to reproduce
1. Upload a file using the upload icon or by dragging files on to the browser

### Observed behavior
After uploading a file the page isn't updated automatically. You have to click on the folder you just uploaded to, or refresh the page to use the file.

![modx3_mediabrowser_uploadnorefresh](https://user-images.githubusercontent.com/2373940/42220016-15c64476-7ece-11e8-922f-be63bb2c4939.gif)

### Expected behavior
After upload you can see the file.

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by meshkov** [comment]
Confirm.
Also problem with drag&drop files.
![ifchbiz5j7](https://user-images.githubusercontent.com/1703670/42278146-7bb9222e-7fa2-11e8-848d-b01b9213c158.gif)

**Comment by Ibochkarev** [comment]
I confirm this bug. Not updated in both cases.

3.0.0-pl

**Comment by alroniks** [comment]
Solved.
