### ISSUE TITLE
MODX 3: Media Browser - no active state / colour for current folder

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13960]
### Summary
Whilst the new media browser file tree no longer displays files in the tree anymore, just folders, it would be good to add an active state / colour to show what folder you have clicked on, otherwise, from a visual perspective, it's impossible to know what folder you're viewing (unless you check the breadcrumb at the bottom).

**An example  - what folder have I clicked on?**

![screen shot 2018-07-03 at 14 00 14](https://user-images.githubusercontent.com/2373940/42218598-75f7912e-7ec9-11e8-8acc-da78acf5af02.png)

### Step to reproduce
1. Click on the media icon in the sidebar
2. Click media browser 
3. Click on the assets folder

### Observed behavior
There is no visual cue to show you that you've clicked on assets and you're now viewing the contents of the assets folder

### Expected behavior
A visual cue to show me what folder i've clicked on / currently viewing. Similar to https://github.com/modxcms/revolution/issues/13956

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by alroniks** [comment]
Close as PR is merged.
