### ISSUE TITLE
MODX 3: Login - no css style for .is-success on forgotten password

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13976]
### Summary
A non styled success message displays if you enter a user that exists in the system.

![modx_login_sucess](https://user-images.githubusercontent.com/2373940/42332161-a076ca64-8077-11e8-917c-2bbe7d01a92f.gif)

### Step to reproduce
1. Go to the forgotten password tool on the login
2. Type a user that exists in the system, 
3. After pressing "Send Activation Email" a non styled success message displays.

### Observed behavior
A non styled success message displays.

### Expected behavior
For a styled success message to display. Although if they are colour coded - their is a minor security issue; somebody might be able to tell that a user does exist (green success message) or does not exist (red success message) in the system. Maybe develop a neutral message colour (although they could still check the generated html for `.is-success` vs `.is-error`.

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by OptimusCrime** [comment]
Please reopen this

**Comment by alroniks** [comment]
Closing as PR is merged.
