### ISSUE TITLE
MODX 3: Resource - form customisation panel titles icon bug

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13971]
### Summary

A small detail but...

Using form customisation, if you rename publishing, template and menu panels to something that breaks onto 2 lines or you just make your browser small, the collapsable icon becomes slightly hidden and vertically aligned - this might be an issue for multilingual sites.

![modx3_resource_formcustomisation_1](https://user-images.githubusercontent.com/2373940/42285917-474ccb9e-7fb1-11e8-84c7-eff729250c16.gif)

### Step to reproduce
1. Setup some basic form customisation
2. In Regions, change the title of `modx-resource-main-right-top`, `modx-resource-main-right-middle`, `modx-resource-main-right-bottom` to something long

### Observed behavior
If the content breaks onto 2 lines - the icon becomes hidden. If your browser window is even smaller for the content to break onto 3 lines - the icon becomes vertically centred.

### Expected behavior
For the icon to be in view and aligned to the top, regardless of content

### Fix

Add `flex: 1;` to `#modx-resource-tabs .x-panel-header .x-panel-header-text`

Remove `align-items: center;` from  `#modx-resource-tabs .x-panel-header`

![modx3_resource_formcustomisation_2](https://user-images.githubusercontent.com/2373940/42286977-e981c1c8-7fb4-11e8-97d9-7c2af86c7d69.gif)

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by jonleverrier** [comment]
Can't replicate this using the 3.x branch on github. Going to close this for the time being.

**Comment by alroniks** [comment]
Closing as PR is merged. Thank you for reporting.
