### ISSUE TITLE
MODX 3 - No files displayed if a symlink exists in the directory

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#13970]
### Step to reproduce
Create a symlink in a directory that you have a media source set up for. Try to browse that directory (not the symlink, but the directory it is contained in). A popup error is shown saying links aren't supported, but none of the other files/directories are shown.

### Observed behavior
Error popup, but no files/directories.

### Expected behavior
If it cannot support the symlink, it should still show other files and directories.

### Environment
MODX 3 @ 0ba86ec05d9d99327d55d45083312b98ac80229a
PHP 7.1.12

**Comment by Jako** [comment]
Does flysystem supports symlinks?

**Comment by Mark-H** [comment]
What I suspect is that it doesn't and throws an exception, which the media source catches, and stops it from loading anything else. I'd be happy for it to not allow drilling into a symlink, but at least other items in the same directory should still be accessible.

**Comment by hugopeek** [comment]
I just ran into this issue with 3.0 RC2. I found a workaround for still being able to use symlinks, albeit somewhat limited..

> Does flysystem supports symlinks?

From one of their developers: https://github.com/thephpleague/flysystem/issues/599#issuecomment-185221354

It is only supported if the root is a symlink. But as I suspected, each media source seems to use its own flysystem instance. So if you create a new media source with a symlink as root, the contents will be visible.

> What I suspect is that it doesn't and throws an exception, which the media source catches, and stops it from loading anything else. I'd be happy for it to not allow drilling into a symlink, but at least other items in the same directory should still be accessible.

The parent media source indeed still throws an error (Unsupported symbolic link encountered at location), preventing you from browsing regular files in the folder containing the symlink.

**Comment by Mark-H** [comment]
I believe Flysystem offers a config property for this behavior to ignore symlinks instead of causing an exception whenever it encounters one. Didn't realise this was an issue still!

**Comment by sepiariver** [comment]
Plus one just encountered this on 3.0.1. If I can track this down I'll submit a PR

**Comment by sepiariver** [comment]
Figuring out the unit test will take a hot minute but the fix seems trivial. You were right, @Mark-H  :)
