### ISSUE TITLE
MODX 3: Resource/Elements/File Tree - bin icon hidden for French users

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13972]
### Summary
When using the manager in a different language other than English, such as French, the bin icon is not in view. The only way to select it is to increase the width of the resource tree.

![screen shot 2018-07-04 at 20 13 46](https://user-images.githubusercontent.com/2373940/42290705-3dbe4678-7fc7-11e8-8261-bba3db29f1a6.png)

### Step to reproduce
1. Go to the login screen
2. Select the language "French" before logging in
3. Login

### Observed behavior
The bin icon can't be seen unless you increase the width of the resource tree. This might be confusing for users that don't know the resource tree width can be adjusted.

### Expected behavior
To see the bin icon or to see a visual cue that something is hidden / off screen.

### Environment
MODX3 Alpha v 3.0.0-dev
Chrome Version 67.0.3396.99

**Comment by Ibochkarev** [comment]
MODX3 Alpha v 3.0.0-dev
Chrome Version 67.0.3396.99

It's OK

![Image ](https://i.imgur.com/7HR69zs.png)

**Comment by jonleverrier** [comment]
@Ibochkarev Quite possibly - you're testing a different version to me. Your nav bar (resources, elements, files) are styled different to mine?

**Comment by Mark-H** [comment]
@Ibochkarev looks to be using the 3.x branch, while I suspect you're using the alpha build from modx3.org @jonleverrier? The alpha build has #13934 included which is not yet in 3.x.

**Comment by jonleverrier** [comment]
that's correct @Mark-H. if i'm testing something old and this issue has been fixed in the latest build, please close this ticket. potentially, there might be other issues i've reported that have been fixed with the latest build too. I've gone through all my tickets and made sure it's clear what build I have used to test.

**Comment by jonleverrier** [comment]
i've just tested this with the 3.x branch on github and can't reproduce. i'm going to presume that the "regular" build on https://modx3.org/project-statement was out of date, so going to close for the time being. feel free to reopen.
