### ISSUE TITLE
MODX 3 - System Settings & Events

### ISSUE THREAD

**Issue by lirompage** [modxcms/revolution#13974]
### Summary
When used modx3 in Russian language, when trying to enter the system settings, it gives an error 500

### Step to reproduce
When you enter the panel select Russian language, try to enter the system settings

### Observed behavior
This page isn’t working
alphanavgroup.com is currently unable to handle this request.
HTTP ERROR 500

### Environment
MODX Revolution 3.0.0-dev (git), Apache 2.0 Handler, 10.1.26-MariaDB-1~jessie, Chrome,Safari, etc.

**Comment by ghost** [comment]
If you look at your server's PHP error log you should be able to see a specific PHP error that causes the 500 server error.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue.

This issue is already being fixed (but not yet in the current MODX 3 release).
See PR https://github.com/modxcms/revolution/pull/13936

@modxbot close

**Comment by Mark-H** [comment]
Just to clarify, it should be fixed in the 3.x branch, just not in the build published on modx3.org.
