### ISSUE TITLE
MODX 3: what was the reason to remove the "modAB" div container from header.tpl?

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#13975]
https://github.com/modxcms/revolution/blob/0ba86ec05d9d99327d55d45083312b98ac80229a/manager/templates/default/header.tpl#L71

This breaks add-ons which have their own customized action buttons rendered to this container.

**I used to use this piece of code:**
(and some other Add-ons like Articles -- yes I know it's dead but it works perfectly in some of our older projects)

```
Ext.extend(GoodNews.HomePanel,MODx.Panel,{
    init: function(){
        this.actionToolbar = new Ext.Toolbar({
            renderTo: 'modAB'
            ,id: 'modx-action-buttons'
            ,defaults: { scope: this }
            ,items: this.getElements()
        });                                
        this.actionToolbar.doLayout();
    }
    ...
```

**It seems that I now have to use this:**
(It seems to work as before, so I don't know why this "modAB" div container was here in previous MODX versions)

```
Ext.extend(GoodNews.HomePanel,MODx.Panel,{
    init: function(){
        this.actionToolbar = new Ext.Toolbar({
            renderTo: 'modx-action-buttons-container'
            ,id: 'modx-action-buttons'
            ,defaults: { scope: this }
            ,items: this.getElements()
        });                                
        this.actionToolbar.doLayout();
    }
    ...
```

I don't know why this container was removed. But I'm not very good in (Ext)JS. Would be good to know the reason to fix the problems in my add-ons.

**Comment by OptimusCrime** [comment]
I guess it was removed as a part of the cleanup/restructure of the templates. It looks very out of place and I think we better use this chance for breaking changes and remove it now. If the fix it simply to change the `renderTo` parameter, the components that used this old relic should do this now.

**Comment by gadgetto** [comment]
Yes, I'm completely with you! I only questioned this because I don't know if it is the right way to use `modx-action-buttons-container` for rendering action buttons - and I don't want to have any negative side effects.

**Comment by gadgetto** [comment]
And the fact that this line of code is only commented out and not removed completely makes me a bit nervous... :-)

**Comment by JoshuaLuckers** [comment]
These old commits might be related. https://github.com/modxcms/revolution/commit/7e7264e8ff80bdde706cf5c5c95c893145e82df7

Rendering them to `modx-action-buttons-container` seems to be the best way if it gives the results you want.

**Comment by gadgetto** [comment]
Thanks for the info! As it works, the issue can be closed.
