### ISSUE TITLE
MODX 3: Sidebar - line height on menu items too big if text falls onto 2 lines

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#13983]
### Summary
If you have a custom menu or have re-named a menu item that falls onto 2 lines - the line height is too large. Might be problematic for content users who use the manager in different languages.

![screen shot 2018-07-09 at 12 39 36](https://user-images.githubusercontent.com/2373940/42446168-9ab22244-8375-11e8-8d12-14ca6daa1d94.png)

### Step to reproduce
1. Go to system settings and click on menus
2. Right click on System and update
3. Change lexicon key to "System Menu" and save

### Observed behavior
Line height of the menu item is too big.

### Expected behavior
Line height of the new item to be smaller

### Fix

Fix not fully tested but perhaps something like this would work;

On `#modx-navbar a` change `line-height` to 12px so the full style reads:
```
cursor: pointer;
    color: #FFF;
    display: block;
    line-height: 11px;
    font-size: 10px;
    text-decoration: none;
```

On `#modx-navbar #modx-topnav > li:not(#modx-home-dashboard):not(#modx-manager-search-icon):not(#modx-leftbar-trigger) > a:after` remove the absolute positioning, and add `width: 100%;`.

Things display better, but now the icons are the wrong way round, so perhaps use `#modx-navbar #modx-topnav > li:not(#modx-home-dashboard):not(#modx-manager-search-icon):not(#modx-leftbar-trigger) > a:before` rather than after?

### Environment
MODX3 Alpha v 3.0.0-dev
From https://github.com/Sterc/modx3builds/raw/master/latest/modx3-alpha-regular.zip
Chrome Version 67.0.3396.99

**Comment by JoshuaLuckers** [comment]
Would you like to contribute by creating a pull request for this?

**Comment by jonleverrier** [comment]
@JoshuaLuckers Done :) thanks so much for your help!!!

**Comment by alroniks** [comment]
Close as PR is merged.
