### ISSUE TITLE
Package update fails if Update button was pressed twice

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#13982]
### Summary
Package update fails if  Update button was pressed twice

### Step to reproduce
It's a bit curious and I believe not everyone can be so tricky :) but I had wide tree section so popup had a bit another positioning..I've tried to repeat that with standard width for left part and this is unlikely, but possible. So I wanted to close the popup but missed the goal and pressed the Update button again. After that as you can see from below some strange popup cycling happened, you can't update any package correctly until you reload the page.

### Observed behavior
Here is animated GIF how it was, hope it's clear:

![button_popup_issue](https://user-images.githubusercontent.com/2815640/42443068-262d0eca-8375-11e8-8430-7ffeba3161b6.gif)

### Expected behavior
The update package process should continue correctly.

### Environment
MODX 2.6.4-pl on MODXCloud

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. The issue is clear and I'm able to reproduce it.
