### ISSUE TITLE
CollapseAll doesn't work in grids when RowExpander plugin used

### ISSUE THREAD

**Issue by alroniks** [modxcms/revolution#13989]
### Summary
When the grid uses custom row expander attempts to expand or collapse all rows triggers an error that collapseAll is not a function (i.e. method not found).

### Step to reproduce
Set up the grid
```
this.exp = new Ext.ux.grid.RowExpander({
    tpl: new Ext.Template(nlInfos)
    ,enableCaching: false
});
```
and call after anywhere method `collapseAll()` from grid. For example, in any listener:
```
listeners: {
    'check': function(cbx,checked){
        this.collapseAll();
        this.toggleAutoRefresh(cbx,checked);
    }
    ,scope:this
}
```

### Observed behavior
Now it raises an error `Uncaught TypeError: this.exp.collapseAll is not a function`

### Expected behavior
It should work as before, collapsing/expanding all rows.

### Environment
2.6.4, I guess 3.x also affected, but I don't check yet.

The reason why it happens here - https://github.com/modxcms/revolution/commit/26583acc454bf85f0f28d53005fa8012984b7a98
Plugin RowExpander was updated and in updated code expandAll, collapseAll method removed.

Detailed description on the forum - https://forums.modx.com/thread/104033/extjs-problem-with-grid-rowexpander-plugin-collapseall-doesn-039-t-work#dis-post-559499

**Comment by gadgetto** [comment]
There is another problem related to this:

In methods `expandAll` and `collapseAll` (multiple occurrence in different grid types)

https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/core/modx.grid.js#L500

```
    ,expandAll: function() {
        if (!this.exp) return false;

        this.exp.expandAll();
        this.tools['plus'].hide();
        this.tools['minus'].show();
        return true;
    }

    ,collapseAll: function() {
        if (!this.exp) return false;

        this.exp.collapseAll();
        this.tools['minus'].hide();
        this.tools['plus'].show();
        return true;
    }

```

the rowExpander is "hardcoded" to name "exp"

this won't let you execute the method:

```
    this.nlexpander = new Ext.ux.grid.RowExpander({
```

this works:

```
    this.exp = new Ext.ux.grid.RowExpander({
```

**Comment by garryn** [comment]
I'm not finding this issue with the extras I have that use row expanders, although the call to RowExpander is slightly different:

```
    this.exp = new Ext.grid.RowExpander({
        tpl : new Ext.Template(
            '<p><strong>' + _('stackpath.conditions') + '</strong>:</p><p><ul>{conditions}</ul></p>'
        )
    });
```

Maybe try calling it using `Ext.grid.RowExpander` vs `Ext.ux.grid.RowExpander`?

**Comment by alroniks** [comment]
@garryn They are the same. https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/core/modx.grid.js#L1037

Did you try to expand all items? It appears I've seen some issues similar to this before.

**Comment by garryn** [comment]
Yeah, I've had all rows expanded, refreshed and they all maintained their expanded status (and allow me to collapse all of them afterwards) ... only possible difference is that I'm using grouping on that example I posted.

**Comment by gadgetto** [comment]
@garryn which problem are your referencing? "collapsAll/expandAll"? Could it be you are posting in the wrong issue? "collapseAll/expandAll" can't work in your environment as the methods are definitely missing in plugin.

**Comment by gadgetto** [comment]
A workaround for this issue is to add this two methods to your grid and call them instead the original:

```
    // Workaround for https://github.com/modxcms/revolution/issues/13989
    // (methods missing in rowExpander plugin in modx.grid.js)
    ,_expandAll: function() {
        var a = this.getView().getRows();
        for (var i=0;i<a.length;i++) {
            this.exp.expandRow(a[i]);
        }
    }
    ,_collapseAll: function() {
        var a = this.getView().getRows();
        for (var i=0;i<a.length;i++) {
            this.exp.collapseRow(a[i]);
        }
    }
```
