### ISSUE TITLE
MODX 3: Potential composer.json version collision

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#14005]
### Summary
I initially installed MODX3 via Composer but found it won't update to the alpha due to the version not being changed in the recent build (or that it is not included in the `composer.json` file on a project create). I grabbed the download and was about to copy the files over the existing MODX3 3.dev and it dawned on me that developers may indeed have installed other packages onto their MODX3 site, thereby changing the composer.json (and lock) to include those files. Future updates to MODX3 may potentially collide and overwrite the site composer.json populated with those packages. Currently, I have quite a few nonMODX3 packages installed via Composer, which I have little difficulty believing will be the norm for developers in the future.

These are not extras, so the https://github.com/composer/installers/blob/master/src/Composer/Installers/ModxInstaller.php does not apply.

What did you guys envision for the use of Composer to add third-party nonMODX3 Extras for MODX3?

**Comment by OptimusCrime** [comment]
The root composer file is ment to build the project. It is not ment for installing extras in your project. That will never work. Additionally, I do not think the actual composer file will be shipped with the zip file for production.

**Comment by JoshuaLuckers** [comment]
@OptimusCrime you can define a custom type for a package with composer. A custom installer can be written to make it possible to install the package as an extra.
https://getcomposer.org/doc/articles/custom-installers.md

**Comment by wshawn** [comment]
If memory serves, even the custom type Composer package, still requires the primary composer to be edited to link to it, does it not? I've always strongly adhered to and supported the concept of leaving the core alone.

**Comment by wshawn** [comment]
If I have time, I might play with installing composer and assigning {core}/components/vendor to it. We should really have a streamlined method for importing NON extras / outside classes to projects via composer and make them available to extras we are building.

**Comment by OptimusCrime** [comment]
As far as I know there is no way to have both the composer.json + .lock file checked in to Git, and also allow it to be edited. This would also cause problems if you changed the versions locked in by upgrading.

Additionally, if you use any composer dependencies, would it not make sense to place them within your component directory, to avoid adding more files at difference places in the MODX project? I have done this many times before, placing them in core/component/[my-component]/vendor. I think this makes a whole lot more sense, and does not involve using the composer file tied to the MODX project at all.

Agan, I do not think these files will be included in the packaged MODX zips at all. It would be a security issue if attackers easily could get their hands on which versions of dependencies you have installed, and .json and .lock files are just text documents that would be (by default) served by the web server.

I do not see the issue presented here. Are we talking about the same thing?

**Comment by wshawn** [comment]
My thought was to have a generic place for a local user Composer repository. I believe placing it in the /component/[my-component]/vendor may be problematic as a single import may be used in multiple extras. I was thinking maybe a core/component/composer.lock etc feeding into a site-wide /core/component/vendor. That will separate the MODX project files and facilitate all the benefits of Composer. Though your argument may be that each Extra needs to handle its own upgrades/dependencies.

My original question was to discover if the devs had envisioned how we would be able to implement Composer. The introduction of namespaces and PSR 0,4,7 into MODX opens up a world of new opportunity.

**Comment by wshawn** [comment]
Well, I guess I answered my own question and went with the suggestions made by @OptimusCrime, and created a vendor directory in each of my components. My decision was based on the ability to have my own applications update the vendor packages. Trying to manage a global composer.json file would be problematic at best, at least until composer has the means to read all the *.json files in a given location... Most of my applications are massive and beyond the scope of an "Extra", but I tend to share libraries.  In any case, I will close this and hope it is informative for those that follow with the same question.
