### ISSUE TITLE
MODX 3 : Quick Update on Weblink/Symlink doesn't expand the popup editing window

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#14014]
### Summary
Quick Update on Weblinks and Symlinks doesn't expand the popup editing window.

### Step to reproduce
Make a Weblink or Symlink, then right-click and select "Quick Update".

### Observed behavior
The popup window is collapsed:
![screen shot 2018-07-25 at 11 12 20 am](https://user-images.githubusercontent.com/2528374/43209962-eee3ce70-8ffb-11e8-99c0-c3803aa8a285.png)
For all other resource types, the popup window is expanded to show all the editing fields.

### Expected behavior
Popup window should be the same as with other resource types.

### Environment
MODX 3.0.0-dev

**Comment by jonleverrier** [comment]
I can re-produce this issue.

**Comment by Ibochkarev** [comment]
I don't see this problem.

MODX Revolution 3.0.0-alpha3 (git), PHP Version 7.4.12

https://user-images.githubusercontent.com/2138260/110241246-f7cb5380-7f79-11eb-9ada-74e1af0fa31c.mp4

**Comment by ghost** [comment]
I don't have the problem here either, alpha 3, March 1 nightly. 

FF 86, OS X 11.2.2, MODX Cloud with PHP 7.3

**Comment by SnowCreative** [comment]
Yes, seems to be fixed now. Closing this issue.
