### ISSUE TITLE
Slack badge not working in the README.md

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14015]
### Summary
The Slack badge is not working in the README.md.
The link for the badge does not work. When opening the source of the badge in the browser (https://modx.org/badge.svg) it turns into a redirect to join the Slack community.

### Step to reproduce
Navigate to the root of the repo on GitHub.

### Observed behavior
The Slack badge image does not load.

### Expected behavior
A visible Slack badge image.

### Environment
GitHub

**Comment by alroniks** [comment]
It seems that before have been used tool based on node.js, now it just redirects to slack.
I would remove it at all or replaces by badge without numbers, just a picture with a link.
