### ISSUE TITLE
License type of the repo not detected

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14023]
### Summary
[As noted](https://github.com/modxcms/revolution/pull/13993#issuecomment-409462920) by @OptimusCrime in PR #13993 the repo is not showing the license being used.

More info about licensing a repo can be found [here](https://help.github.com/articles/licensing-a-repository/).

### Step to reproduce
Check the tabs of this repo.

### Observed behavior
No tab with the license being used.

### Expected behavior
A tab showing the license being used.

### Environment
GitHub

**Comment by OptimusCrime** [comment]
I am pretty sure it happens because GitHUb detects that the text is not identical to the template.

**Comment by JoshuaLuckers** [comment]
[GitHub scheduled it to be redetected](url
https://twitter.com/GitHubHelp/status/1030590886395224064). Sadly it did not seem to work and I've contacted GitHub Support about it.

**Comment by OptimusCrime** [comment]
Any news about this?

**Comment by JoshuaLuckers** [comment]
[Someone will get back to me soon.](https://twitter.com/GitHubHelp/status/1033469568474406912)

**Comment by JoshuaLuckers** [comment]
Support mailed me back:
> If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. Our team wrote more abut this here:
> https://help.github.com/articles/licensing-a-repository/#detecting-a-license
> 
> My guess is that our systems are also detecting that COPYRIGHT file in the root:
> https://github.com/modxcms/revolution/blob/2.x/COPYRIGHT
>
> Could you move that file into its own folder and see if that helps detect the LICENSE in the top right corner?

Ping @opengeek

**Comment by OptimusCrime** [comment]
Do we need both a copyright and a license?

**Comment by Jako** [comment]
@JoshuaLuckers Is it possible to check that on your fork?

**Comment by alroniks** [comment]
I've experimented on my own repo (see last commits https://github.com/Alroniks/modx-foo-bar-extra/commits/master) and removing copyright file solves the issue. 
I've tried to repeat the full cycle with files in MODX repo: created copyright file at first, after created license file with some strings of text, after selected GPL v2 license from suggested by GitHub during editing the file, and nothing happened. But when I removed copyright file - license mark appeared.

**Comment by JoshuaLuckers** [comment]
Thanks for testing @Alroniks! If we remove the copyright file the copyright headers have to be modified again..

**Comment by OptimusCrime** [comment]
Would they? Why? The license say the same as the copyright doesn't it?

**Comment by opengeek** [comment]
WTAF!?

**Comment by JoshuaLuckers** [comment]
@OptimusCrime in the file headers there are references to the LICENSE and COPYRIGHT file.

@opengeek Can we remove or move the COPYRIGHT file?

**Comment by JoshuaLuckers** [comment]
There is a view license tab now. I’m fine with the solution we have now.
