### ISSUE TITLE
Resource hangs when saving

### ISSUE THREAD

**Issue by smashstack-kris** [modxcms/revolution#14025]
### Summary
On MODX Revo 2.6.5 we're finding that when saving a Resource in the MODX manager, it simply hangs: the save progress bar goes into a loop and never confirms the Resource is saved.  We're finding irregularities in reproducing this issue.  It happens on PC (Win 10) and Mac OS (High Sierra) on Chrome browser, Firefox and MS Edge.  Sometimes when we hop over to PC Firefox browsers, the problem does not happen (sometimes).  

### Step to reproduce
Setup a fresh MODX install, save a MODX Resource using the Chrome browser.

### Observed behavior
The saving load bar just hangs.

### Expected behavior
The saving load bar should only appear for a few seconds max and then disappear alerting the Manager that the Resource has been saved.

### Environment
Localhost (WAMP) on MODX 2.6.5.  We're also experiencing this using MODX 2.6.5 on https://bitnami.com/stack/modx hosting.  This video demonstrates what we're seeing along with the error being returned in the browser:

* http://files.smashstack.com/k7Sf2r
* https://www.dropbox.com/s/e9ha2lskgxr9c21/2018-08-03_09-40-52.png?dl=0

**Comment by Mark-H** [comment]
Could you take a look at the response for the ajax request, the one to `connectors/index.php` that goes out when you hit save?

**Comment by JoshuaLuckers** [comment]
Does this also happen when you disable JS compression in system settings (you have to clear the cache afterwards)?

**Comment by smashstack-kris** [comment]
@JoshuaLuckers @Mark-H thanks for the questions.  Turns out the client had a plugin installed on the server to help with caching to speed up the load time and it was causing the problem.  I'll close out this issue.

**Comment by JoshuaLuckers** [comment]
It would be helpful to share what plugin was being used. It might help others in the future.
