### ISSUE TITLE
MODX 3 site and user credentials available via MODX Object / xPDOObject in clear text

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#14026]
### Step to reproduce
var_dump or print_r an XPdoObject or the MOD object.

### Observed behavior
 ``[+connection_mutable] => 1 [+connections0dsn] => mysql:host=localhost;dbname=XXXXXXXXXX;charset=utf8 [+connections0username] => XXXXXXXXXX [+connections0password] => XXXXXXXXXX 
  Array ( [id] => 1 [username] => XXXXXXXXXX [password] => XXXXXXXXXX [cachepwd] => [class_key] => modUser [active] => 1 [remote_key] => [remote_data] => [hash_class] => hashing.modPBKDF2 [salt] => XXXXXXXXXX
``
### Expected behavior
I thought these were removed *many* versions ago. 

### Environment
MODX 3

**Comment by Mark-H** [comment]
That password looks like modUser.password, which should be hashed. The connection DSN comes from the configuration file.


What was changed a while ago as far as I can remember is that sensitive config options/settings were not being made available to any manager user through the MODx.config object.

**Comment by wshawn** [comment]
OK.  Yeah, and in an advanced setup situation. I have been coding 14 hours today and just noticed it.  I just wanted to make sure. I half-remember those being removed.  I was sure both were clear text, but closed the notepad++ tab they were in once I posted it.  Closing.
