### ISSUE TITLE
Force composer to require PHP extensions that needed for proper work of MODX

### ISSUE THREAD

**Issue by alroniks** [modxcms/revolution#14048]
### Summary
I guess subject explain the issue enough. Five cents additionally. We already have documented requirements to environments for running MODX but also It would be cool to have these requirements in the comoser.json file.

### Observed behavior
Now, you can try to download MODX and setup it but if some extensions not installed it can cause issues during the using the system later. For example, problems with image thumbs when `php-gd` wasn't installed before.

### Expected behavior
As we have an awesome tool - Composer, it should notify the user that the environment is not ready for proper work of the software that he or she tries to use.

### Environment
all

**Comment by Jako** [comment]
That leads to the following question: Will the installable package of MODX3 work without using composer? I hope so, since a lot of shared host installations can't run composer.

**Comment by alroniks** [comment]
It will work, of course, but if somebody will use composer-way of installation, it will show the found problems.

**Comment by OptimusCrime** [comment]
@Jako all hosts can run composer, but it is a lot more difficult for some (those without cli for example).

However, I was under the impression that MODX itself would ship without the composer.json file? Who would this work for then? People that clone the repository?

**Comment by alroniks** [comment]
Any automation tools that can setup MODX via composer, people who like composer-way of installation, and I hope all other people, who have more modern environments. Of course, it won't be must-have tool for all users, but... Who knows.

**Comment by JoshuaLuckers** [comment]
People who are going to use `composer create-project modx/revolution`

**Comment by Jako** [comment]
Could those composer php extension requirements somehow be used to automatically generate an installation check for an 'composer-less' installation?

**Comment by alroniks** [comment]
@Jako Potentially yes, there is simple JSON file and can be parsed by any part of a code.
