### ISSUE TITLE
Media Browser in 2.6.5 Thumbnail Containers wrong size for thumbnail imgs

### ISSUE THREAD

**Issue by LucyI** [modxcms/revolution#14051]
### Summary
Thumbnail images have been created at max-height of 100px, but container is now set to height of 80px, so some thumbs hang below container div and overlap filename display area.

### Step to reproduce
View Media Browser in 2.6.5 and observe images with square or portrait aspect ratios.

### Expected behavior
Image thumbs will be contained by wrapping div.

### Environment
MODX 2.6.5

### Details and Fix
Looks like thumbs are (were) generated at max 100px width and max 100px height, but thumbs container is only allowing for max 80px height. Changing the style on this container div:
```.modx-browser-thumb```
to:
```height: 100px; line-height: 100px;```
fixes this. (Works in the inspector anyway.)

![image](https://user-images.githubusercontent.com/810839/44280094-b808b900-a221-11e8-9cee-3dac7d98da18.png)

**Comment by jonleverrier** [comment]
Thanks for your fix @LucyI. I've just submitted a PR so hopefully it will be fixed soon.
