### ISSUE TITLE
Insert Template Variables-tab before the resource Settings-tab

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14067]
The location of the TV-tab before Settings-tab is more appropriate in terms of UX / UI:

1) By default, the TV tab is located after the settings, but most of the time the user works in the Document-tab and the TV-tab - it is not clear why they are separated by the rarely used Settings-tab. Especially since Document-tab and the TV-tab relate to content.

2) The new MODX-user or content-manager will be intuitively easier to find where all content of the resource located. And even if you do not remember the name of the tab, it's easier to remember that the content in the first 2 tabs.

![new_tabs](https://user-images.githubusercontent.com/12523676/44796426-06bd3800-abbe-11e8-968e-cdcdb6533894.png)

Most likely I unnecessarily pay attention to tabs location, but still ;)

p.s. It is clear that you can move the TV after the content in Settings or remake the location using the Manager Customization

**Comment by Mark-H** [comment]
Moved tabs in #14250
