### ISSUE TITLE
Illogical checkbox "Hide From Menus" in Resource

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14070]
_Checkbox "Published" works on this principle:_
Selected **(active)** - Resource published **(active)**.

_But the Checkbox "Hide From Menus" works in reverse way:_
Selected **(active)** - The resource is hidden from the menu **(NOT active)**.

And this is confusing, especially when they are located nearby. It is more appropriate in terms of UX / UI to put a **checkbox - "Show in the menu"**, it seems to me.

Especially it will attracts attention in the design of MODX3, because there the orange color of the checkbox shows the "non-standard" behavior of the resource, although the display of the resource in the menu is the "standard" behavior of the resource.

p.s. By the way, in the concept design for MODX3 is the checkbox "Show in the menu":

![resource-edit-settings](https://user-images.githubusercontent.com/12523676/44919084-a5c46a00-ad4d-11e8-8c2c-4fd7695b47d6.png)

**Comment by alroniks** [comment]
It already has been discussed before. 
It seems it's here https://github.com/modxcms/revolution/issues/9523

I guess we need close it is as a duplicate but with comments in the original ticket.
