### ISSUE TITLE
Double-click of image in Media Browser goes to blank page

### ISSUE THREAD

**Issue by guyinpv** [modxcms/revolution#14075]
### Summary
Double-click  image in Media Browser opens blank page.

### Step to reproduce
Open Media Browser and go to a folder with JPGs in it. Double-click on a JPG image (could be other images formats too). Multiple people confirmed this behavior already on Slack.

### Observed behavior
Blank page comes up. And further, hitting the back button does not take you back to Media Browser, but back to whatever page you had open before Media Browser. So this really just knocks you out of browsing media entirely.

### Expected behavior
I'm assuming the best behavior here would be a popup preview window. There already exists a popup preview for images, the double-click action should open that as well.

### Environment
Using 2.6.5-pl on  Apache server. Tested on a very clean install.

**Comment by JoshuaLuckers** [comment]
I can confirm this issue.

**Comment by Jako** [comment]
> I'm assuming the best behavior here would be a popup preview window. There already exists a popup preview for images, the double-click action should open that as well.

What kind of popup do you mean? There is a sidebar with a preview.

**Comment by jonleverrier** [comment]
For reference, this is the sidebar @Jako is talking about;

![screen shot 2018-09-07 at 13 52 19](https://user-images.githubusercontent.com/2373940/45217737-778edf00-b2a5-11e8-94cb-179e1fe7afe4.png)

**Comment by guyinpv** [comment]
@jonleverrier In the screenshot you posted, you can click on the image in the upper-right of the sidebar and it will show a popup image preview at full size of the image.

I'm thinking a double-click would just open the same popup.

Further, that popup shows the full image but has scroll bars, maybe a slightly improved image preview popup is in order, like a full size lightbox for example.

Double-click needs some kind of behavior. I mean, it is actually doing something now, it goes to this blank page. Maybe in the past this had a different behavior? Why the blank page?

Regardless, using the same popup as the sidebar is an easy-button fix perhaps.

**Comment by Jako** [comment]
I'm a bit confused. First you are talking about double clicking on an image in the media browser and now you are talking about a popup issue when clicking on an image in the media browser sidebar.

I could confirm the double clicking issue in in the browser and tried to fix that. 

I don't think that a double click should open a popup. If you use that browser i.e. in a template variable, double clicking a file will fill the TV value and close the window. If a similar browser does a totally different thing on a double click (instead of nothing), this feels like bad UX for me.

Please open another issue for the sidebar image popup.

**Comment by guyinpv** [comment]
The sidebar works fine. I'm saying the behavior of clicking on the image in the sidebar (it opens a popup), could be the same behavior for the double-click and that would be fine.

On Sep 9, 2018, at 11:17 PM, Thomas Jakobi <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm a bit confused. First you are talking about about double clicking on an image in the media browser and now you are talking about double clicking on an image in the media browser sidebar.

I could confirm the double clicking issue in in the browser and tried to fix that (somehow wrong). Please open another issue for the sidebar image.

**Comment by Jako** [comment]
The PR is merged, so I close this as resolved. Please open another issue, if there is something left.
