### ISSUE TITLE
Manager is hanging when saving

### ISSUE THREAD

**Issue by smashstack-kris** [modxcms/revolution#14073]
### Summary
We've been building sites on MODX 2.6.5 and upgrading clients as well to 2.6.5 and one of the common issues we're hearing from our clients is that when saving a MODX Resource, the manager simply hangs.  It just keeps looping in the ‘Saving…’ progress bar window.  It's happening to our dev team as well.

### Step to reproduce
Login to MODX manager, create a new Resource and save it.  Seems more common with Chrome, but have observed this on FF as well.

### Observed behavior
It just keeps looping in the ‘Saving…’ progress bar window.

### Expected behavior
The MODX Resource should save and the progress bar should disappear.

### Environment
MODX version: 2.6.5
apache/nginx and version: this is happening on our clients hosted on the MODXcloud and bitnami as well. 
mysql version: whatever is installed on the MODXcloud
browser: seems common on Chrome.

**Comment by Mark-H** [comment]
This is a symptom for some sort of unexpected response to the save Ajax request. There could be any number of reasons for that, so you'll have to do some more digging before this can be treated as a bug.

Start by keeping the browser dev tools open and looking at the response for the connector request. That may give you an answer as to why it fails, or at the very least hopefully a clue to follow further.

**Comment by smashstack-kris** [comment]
@Mark-H ok got it.  I know we opened this as a ticket before, but we isolated the issue to a plugin on the server.  Let me see if we can replicate this issue and then we'll follow the steps you outlined and report back.

Thanks!

**Comment by Mark-H** [comment]
Feel free to reopen if your research points to a core issue. If you need help figuring out the cause, please post on the MODX forums.
