### ISSUE TITLE
__DIR__ bug in revo 2.6.5.pl

### ISSUE THREAD

**Issue by SB401** [modxcms/revolution#14072]
### Summary
The following error message pops up when trying to setup modx

 ```
Warning: include() [function.include]: Failed opening '__DIR__/bootstrap.php' for inclusion (include_path='.:/usr/lib64/php:/usr/share/pear') in /home2/user/public_html/core_xxx/model/smarty/Smarty.class.php on line 72

Fatal error: Class 'Smarty_Template_Compiled' not found in /home2/user/public_html/core_xxx/model/smarty/sysplugins/smarty_internal_template.php on line  554
```

### Step to reproduce
- Download package from modx website
- Upload to server
- Extract to directory
- Create blank database with user and password
- Start setup by entering path to the setup directory (eg example.com/setup)

### Observed behavior
error message come up

### Expected behavior
setup page

### Environment
MODX 2.6.5, php version 5.4.24

### Fix

I managed to fix the issue by replacing ` __DIR__` with `dirname(__FILE__)`

**Comment by Jako** [comment]
Could you check, why the `__DIR__` constant does not work in your PHP 5.4? It should work since PHP 5.3 according to: http://php.net/manual/en/language.constants.predefined.php

**Comment by Mark-H** [comment]
Related forum thread https://forums.modx.com/thread/104358/class-039-smarty-template-compiled-039-not-found-during-setup#dis-post-561357

I have no idea why `__DIR__` would not work on PHP 5.4...

**Comment by SB401** [comment]
Hi Jako, I did a few more test and it turns out that my host is running version 5.2.17 despite quoting that they are running version 5.4.24 in control panel

**Comment by SB401** [comment]
Mark, I started that thread you're referring too.

**Comment by SB401** [comment]
I have now addressed the issue in my control panel and `_DIR_` works

**Comment by Jako** [comment]
Have closed this as invalid, since the server requirements are PHP 5.3.3 and above.
