### ISSUE TITLE
Не показывает значки сайта

### ISSUE THREAD

**Issue by Versionger** [modxcms/revolution#14071]
Уже давно перестали показываться надписи на кнопках сайта, вроде "сохранить" и так далее. Как исправить?
![default](https://user-images.githubusercontent.com/42956971/45012630-a8121700-b020-11e8-8237-70c6b85593d9.PNG)

**Comment by ant-tar** [comment]
Как давно, что-нибудь этому предшествовало? какая версия MODX(судя по всему не актуальная, обновиться до 2.6.5 не пробовали)? Укажите пожалуйста больше деталей. P.S. Да, конечно же по английски :)

**Comment by JoshuaLuckers** [comment]
Please use the issue template when filling bug reports. It might also be really helpful to have an English translation.

**Comment by Jako** [comment]
Пожалуйста, используйте английский язык
