### ISSUE TITLE
An error occurred while trying to save the resource.

### ISSUE THREAD

**Issue by mirkofisic** [modxcms/revolution#14081]
I got message: An error occurred while trying to save the resource. It happens if the content contains none english characters(čćšđž). I checked my database Collation is utf8_general_ci also CMS settings are UTF-8 but problem still exist.

**Comment by OptimusCrime** [comment]
Please use the provided issue template. We need a lot more information than this. E.g. what is your current MODX version?

**Comment by mirkofisic** [comment]
My version is MODX-Revolution 2.6.5-pl also I can not find logs to check details for this error message.

**Comment by jonleverrier** [comment]
I can't replicate this issue unfortunately;

I put these `čćšđž` characters in a freshly created resource in the title, longtitle, description, summary, menu title, link attributes and content field, then pressed save but received no saving errors.

Tested on MODX 2.6.5-pl

**Comment by Jako** [comment]
@mirkofisic Please check the collation of your tables and columns too.

**Comment by mirkofisic** [comment]
this was my big mistake, all tables and database are utf8_general_ci but columns are latin1_swedish_ci and I don't know how this happened. I am sorry for this mistake. Problem solved thank you.
Br

**Comment by Jako** [comment]
Maybe this issue will be repaired with #14069
