### ISSUE TITLE
height of the manager header bar increases after minimising/maximising browser window

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#14082]
### Summary
The height of the manager header bar increases after minimising/maximising browser window

### Step to reproduce
![modx_issue_navbar](https://user-images.githubusercontent.com/2373940/45352713-6f8eb200-b5b9-11e8-8e2d-879966d7d6cb.gif)

### Observed behavior
Header height doesn't snap back to default height.

### Expected behavior
Header height should snap back to default height.

### Environment
MODX 2.5.6

**Comment by Mark-H** [comment]
Is this a problem for anyone but developers checking the responsiveness of the manager?

**Comment by JoshuaLuckers** [comment]
Yes, people around me who use the manager do resize the window once in a while.

**Comment by jonleverrier** [comment]
@Mark-H i'm with you on this one! but I had a client call me this morning about it, so took a look (as it was an easy fix)
