### ISSUE TITLE
Incorrect password behavior and message issue

### ISSUE THREAD

**Issue by minagerges** [modxcms/revolution#14084]
### Summary
When failed login is attempted N number of times, the account gets blocked as it was blocked by an admin, and displayed message is "login_blocked_admin" instead of "login_blocked_too_many_attempts"

### Step to reproduce
1- Enter credential several times, and check received message is incorrect.
2- Notice which message received for block
3- Check DB table [modx_user_attributes] fields: [blocked] which should be set upon admin blocking a user and [failedlogincount] is 0 (just misleading)

### Observed behavior
How it behaved after following steps above.
- The logic used in "checkIsBlocked" function in "/var/www/dispatch_Portal/core/model/modx/processors/security/login.class.php" is unusual
- User attribute "failedlogincount" is set to 0
- Only indication to user and admin that the user was blocked due to several invalid credentials login attempts is a guess based on the value in "blockeduntil" and "blocked", which should mean that an admin blocked the user for a period of time.
- A successful login does not reset "failedlogincount" 

### Expected behavior
How it should behave after following steps above.
- Correct message to be displayed to user
- "failedlogincount" value should remain as an indicator of the block cause
- Block should be based on "failedlogincount" and "blockeduntil", while "blocked" should be reserved for admin blocking only
- the lexicon message "login_blocked_admin" should not indicate (manager) as same lexicon is returned for other contexts.
- After the specified block period passes, the counter should be reset allowing additional N number of failed logins, prior to blocking again for same period of time.
- A successful login should reset "failedlogincount"

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

Revolution 2.6.5-pl
Apache 2.4
MariaDB

**Proposed fix below**, provided while keeping in mind minimal changes, to avoid introducing any new issues in such critical class.
**N.B:** Code has been tested for all mentioned criteria.
1- Correct status represented in DB (failedlogincount + blockeduntil) only
2- Reset "failedlogincount" upon providing correct password
3- Block period end resets "failedlogincount"
4- Correct messages are returned based on block status and cause

_../core/lexicon/en/login.inc.php_
`$_lang['login_blocked_admin'] = 'You have been blocked by an administrator.';`

_../core/model/modx/processors/security/login.class.php_ 

```
     /**
     * Check if user is not active or blocked
     * @return bool|null|string
     */
    public function checkIsBlocked() {
        if (!$this->user->get('active')) {
            return $this->modx->lexicon('login_user_inactive');
        }

        /** @var modUserProfile $profile */
        $profile = $this->user->Profile;

        /* Update block state */
        if ($profile->get('blockeduntil') < time()) {
            if ($profile->get('blockeduntil') > 0) {
                $profile->set('failedlogincount', 0);
            }
            $profile->set('blockeduntil', 0);
            $profile->save();
        }
        if ($this->user->passwordMatches($this->givenPassword)) {
            $profile->set('failedlogincount', 0);
            $profile->save();
        }
        if ($profile->get('failedlogincount') >= $this->modx->getOption('failed_login_attempts') &&
            $profile->get('blockeduntil') < time()) {
                $profile->set('blockeduntil', time() + (60 * $this->modx->getOption('blocked_minutes')));
                $profile->save();
        }
        
        /* Validate block state */
        if ($profile->get('failedlogincount') >= $this->modx->getOption('failed_login_attempts') &&
            $profile->get('blockeduntil') > time()) {
            return $this->modx->lexicon('login_blocked_too_many_attempts');
        }
        if ($profile->get('blocked')) {
            return $this->modx->lexicon('login_blocked_admin');
        }
        if ($profile->get('blockeduntil') > time()) {
            return $this->modx->lexicon('login_blocked_error');
        }
        if ($profile->get('blockedafter') > 0 && $profile->get('blockedafter') < time()) {
            return $this->modx->lexicon('login_blocked_error');
        }

        return false;    
    }
```

**Comment by OptimusCrime** [comment]
Great find. Could you by chance provide a pull request with the suggested fixes?

**Comment by minagerges** [comment]
Pull request 
https://github.com/modxcms/revolution/pull/14085

**Comment by alroniks** [comment]
Closing as PR accepted and merged.
