### ISSUE TITLE
Error: Thumbnail could not be created for pdf

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14088]
### Summary
Viewing the contents of a directory in the file tree that contains a PDF file results in an error in the log stating that a thumbnail could not be created for the PDF file.

### Step to reproduce
Upload a pdf file and then view the containing directory's contents.

### Observed behavior
The following error is logged for each PDF file that is viewed:
[2018-09-15 11:47:58] (ERROR @ /home/user/core/model/modx/sources/modfilemediasource.class.php : 276) Thumbnail could not be created for file: /path/here/

### Expected behavior
Either the error should not be logged, or a thumbnail should be successfully generated. The latter is preferable.

### Environment
MODX version 2.6.5

**Comment by OptimusCrime** [comment]
What php modules do you have installed? I think thumbnails for PDFs needs some other modules to work that regular image formats does not need.

**Comment by muzzwood** [comment]
I have imagemagick installed which should be able to create thumbnails for PDFs. 
Is anyone seeing thumbnails of pdf files in the file tree?

**Comment by jonleverrier** [comment]
@digitalpenguin I also have `php-imagick` installed on my server. When viewing a directory of PDF's I see a `No Preview Available` thumbnail.

**Comment by jonleverrier** [comment]
Just to add - I get no errors in the error log.

**Comment by alroniks** [comment]
@jonleverrier Need to add `pdf` extension to `imageExtensions` setting of the media source. 

I've got the error, but I don't think that it is a bug but system limitation. PDF is not an image, even if phpthumb can handle it. The main issue with PDF that we can not get dimensions (width and height) of the pdf file without special libraries to work with PDF. And error appears in the log by this reason.

**Comment by muzzwood** [comment]
In this case, perhaps we can downgrade the error to a warning.

**Comment by muzzwood** [comment]
It appears the error is only logged when attempting to generate a preview within the file tree. (on mouseover)
@jonleverrier I assume you were testing in the media browser rather than the file tree?

**Comment by alroniks** [comment]
Seems it was refactored in 3.x and I can not find such an error message. Generating thumbs for PDF possible task, but it goes out boundaries of MODX responsibility. Closing.
