### ISSUE TITLE
MODX3: Content of Symlink/Weblink/Static Resource not saved

### ISSUE THREAD

**Issue by morelmm** [modxcms/revolution#14087]
### Summary
Saving resource with Class key set to Symlink/Weblink/Static Resource shows "Save successful", but content is not saved to database. Quick update works good.

### Step to reproduce
Install fresh Modx 3, create symlink/weblink/static resource, open it, change content and click save

### Environment
3.0.0, tried Apache and nginx, PHP 7 and 5.6, firefox and chrome

**Comment by jonleverrier** [comment]
Just to add - It looks like a new Symlink/Weblink/Static Resource will save the `content` if you specify a value. 

After save, if you try and edit this value it will not save.

**Comment by morelmm** [comment]
exactly like @jonleverrier said, new resource is saved, but updating doesn't work. Any ideas what might be the cause?

**Comment by morelmm** [comment]
Hm, i've just noticed that there are two 'content' entries in POST data 
![image](https://user-images.githubusercontent.com/1436118/53402551-3a80eb00-39b2-11e9-918c-11ffe8305e60.png)

**Comment by morelmm** [comment]
So it's caused by field ordering, HiddenContent being put after real content, in Modx 2.7 it was before, now it is after

**Comment by JoshuaLuckers** [comment]
Thanks for the extra info @morelmm. I found the issue and submitted a PR to get this fixed.
