### ISSUE TITLE
Not allowed and Insecure private parameters of phpThumb in admin panel

### ISSUE THREAD

**Issue by colorwebdesigner** [modxcms/revolution#14093]
### Summary

I change default log_level setting in 2 (WARN) and see the following warnings in the log every time when the image preview is generated in the admin panel.

```bash
[2018-09-20 21:58:48] (WARN @ /XXXXXXXX/core/model/phpthumb/modphpthumb.class.php : 89) Detected attempt of using private parameter `wctx` (for internal usage) of phpThumb that not allowed and insecure
```
```bash
[2018-09-20 21:58:48] (WARN @ /XXXXXXXX/core/model/phpthumb/modphpthumb.class.php : 89) Detected attempt of using private parameter `source` (for internal usage) of phpThumb that not allowed and insecure
```
```bash
UPDATE
[2018-09-27 01:31:55] (WARN @ /XXXXXXXX/core/model/phpthumb/modphpthumb.class.php : 89) Detected attempt of using private parameter `imageplus` (for internal usage) of phpThumb that not allowed and insecure
```

### Observed behavior
I installed the package pThumb from the MODx repository and change default phpthumbof settings in system settings:
- `Images Base Directory` to `img` (from www site directory)
- `pThumb Cache Location` to `img/cache`
- `Use pThumb Cache` to `yes`
- `Use Resizer` to `yes`

I'm not shure that the problem is in pThumb, because i changed log level settings after installation of pThumb. May be it was before.

I was able to find the parameters from the log warnings only in the html code in the admin panel 

```
/connectors/system/phpthumb.php?src=www/img/.....&wctx=mgr&amp;source=1....
```

So, warnings appear every time when admin panel called for image preview:
- when i open file manger
- when I point the mouse at the image file in the left column tree and the preview appears

UPDATE 27-09-2018
- when i use TV type "imageplus" and try to open file manager with this TV

### Environment

Linux 4.9.0-6-amd64 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 
MODX Revolution 2.6.5-pl (advanced)
mysql 10.1.26-MariaDB-0+deb9u1
PHP Version 7.1.20-1
Apache 20120211

**Comment by alroniks** [comment]
It appeared after fixing one of the latest security issues. It does not have an impact on functionality but produces such warnings. It can be improved, of course, but seems as known.

**Comment by colorwebdesigner** [comment]
Can you tell me please is it a safe idea if i add this parameters `wctx`, `source`, `imageplus` to $allowed array in modphpthumb.class.php at line 79?

**Comment by Jako** [comment]
Should be safe.

**Comment by alroniks** [comment]
@colorwebdesigner It's safe but it should be solved by unsetting this values from the array after usage. An allowed list should be left as is and this list comes from original phpThumb class. So I don't like an idea to mess it up.

**Comment by Jako** [comment]
Then the core phpthumb connector has to handle removing those modx specific parameters. Are they used anywhere in modPhpThumb?

The `imageplus` parameter is not used anywhere in the Image+ code and not by the core phpthumb connector and will be removed in the next Image+ version.

**Comment by colorwebdesigner** [comment]
Thanks for reply, I temporarily added them, so as not to catch tons of warnings in the logs.

@Jako I spent about 4 hours trying to find where they come from ) and found them only in the admin panel html code

**Comment by Jako** [comment]
Sorry for closing this accidentally. 

Please try this patch and check, if the issue is solved. Image+ has to be patched separate with https://github.com/Jako/ImagePlus/commit/f675438651e89ff9aa5397cb9a4de3f87c954e5b

**Comment by MrRoco** [comment]
Tested it with your PR #14096 and can't reproduce it anymore so looks i would say Solved it.
You would need to patch the imageplus though.
