### ISSUE TITLE
Manager is hanging when saving (update)

### ISSUE THREAD

**Issue by smashstack-kris** [modxcms/revolution#14106]
I originally posted the issue here (it was closed so I created this new ticket):

* https://github.com/modxcms/revolution/issues/14073

@Mark-H had [asked me to document the specific error](https://github.com/modxcms/revolution/issues/14073#issuecomment-418918569) so I've done so below.

We installed a fresh copy of MODX 2.6.5 and used the dev tools to identify the issue.  You can see the specific error here in this screencast:

* http://files.smashstack.com/BW3l3r

The log points out ext-all.js being the culprit.  We're seeing this across all our MODX 2.6.5 sites.  Since we did the update, we've gotten numerous emails from many different users about this issue.  Whether it's on the MODXcloud hosting, localhost setup or on bitnami, we're encountering the same error.

I re-posted the original notes below.  Is this something we can help you with to debug?

### Summary
We've been building sites on MODX 2.6.5 and upgrading clients as well to 2.6.5 and one of the common issues we're hearing from our clients is that when saving a MODX Resource, the manager simply hangs.  It just keeps looping in the ‘Saving…’ progress bar window.  It's happening to our dev team as well.

### Step to reproduce
Login to MODX manager, create a new Resource and save it.  Seems more common with Chrome, but have observed this on FF as well.

### Observed behavior
It just keeps looping in the ‘Saving…’ progress bar window.

### Expected behavior
The MODX Resource should save and the progress bar should disappear.

### Environment
MODX version: 2.6.5
apache/nginx and version: this is happening on our clients hosted on the MODXcloud and bitnami as well. 
mysql version: whatever is installed on the MODXcloud
browser: seems common on Chrome.

**Comment by Mark-H** [comment]
As suggested in the other issue, look at the network tab for the save request. The response of that request is what hopefully explains that. 

The js error indicates the response is malformed/unexpected.

**Comment by smashstack-kris** [comment]
@Mark-H ok, we'll do that shortly and post a response back.

**Comment by smashstack-chester** [comment]
@Mark-H 

There's really nothing to it,it shows 200 response
http://files.smashstack.com/Em5eqc

But the ext-all.js still throws this error which made the dialog stick on the screen.
http://files.smashstack.com/1XrXAZ

It successfully saved the page but the problem is the saving dialog doesnt disappear.
http://files.smashstack.com/kdhSxU

**Comment by smashstack-kris** [comment]
@Mark-H as @smashstack-chester is pointing out above, most of the time (not all the time), the Resource saves when the dialog box hangs.

**Comment by OptimusCrime** [comment]
Could this be the infamous locale error? Can you check your local setting in MODX, then which locales are available on the server?

**Comment by Jako** [comment]
To dig a little bit deeper: could you switch off `compress_js` in the MODX system settings.

After that, put a breakpoint at the start of handleResponse method (line 300) of `manager/assets/modext/util/utilities.js` and look whats in response.responseText and what could cause the Ext.decode issue there.

**Comment by Jako** [comment]
The decoded response looks well in the Chrome DevTools -> Network -> Preview, but for some reason Ext can't decode the same response.

**Comment by smashstack-chester** [comment]
@Jako 

This is what I got.
http://files.smashstack.com/X5Xudt
When I followed your instruction above.

**Comment by smashstack-chester** [comment]
@OptimusCrime 

They're both empty.
http://files.smashstack.com/uX1kVH
http://files.smashstack.com/dyOooZ

Is that the setting that you pointed out above?

**Comment by Jako** [comment]
In the response I see some stray `<div id="droplr-chrome-extension-is-installed" style="display: none;"></div>` after the JSON. This could cause the issue.

**Comment by Jako** [comment]
Please look if this (or another) additional string occurs on the `Response` tab of the connector request too. It seems not to be shown in the `Preview` tab, but Chrome could filter that.

**Comment by smashstack-kris** [comment]
@Jako 

> In the response I see some stray `<div id="droplr-chrome-extension-is-installed" style="display: none;"></div>` after the JSON. This could cause the issue.

We'll take a look at that.  Most of our clients that are reporting this issue are not using droplr (including a few developers on our team), but we'll remove this plugin from our browsers and test again.

**Comment by jonleverrier** [comment]
@smashstack-kris when you removed the droplr plugin, how did your testing go?

**Comment by smashstack-chester** [comment]
@Jako 

Thank you so much, that's the cause of this bug. It's the droplr extension on my browser. I uninstalled it and I can save modx resources smoothly now. 

@jonleverrier 
That fixed the bug.

**Comment by JoshuaLuckers** [comment]
Maybe this issue can be reported to Dorplr so they can fix their extension.

**Comment by smashstack-kris** [comment]
@jonleverrier funny you ask.  I recently switched to a new computer without droplr but haven't had the issue since removing the plugin.  My only concern is for our clients that do not use droplr that are having this problem.  I've advised them to remove all plugins from their browser or use a browser without plugins and test to see what happens.  I just sent out an email to them all this morning with our findings.  I'd like to keep this ticket open to see what they say as to whether using a browser without any plugins fixes the issue.

**Comment by JoshuaLuckers** [comment]
The more info we have to reproduce this issue the better.

**Comment by smashstack-kris** [comment]
@JoshuaLuckers agreed.  I just sent an email to all my clients that have reported the issue and we'll try and debug this with them.  It's an odd issue we've never seen prior to 2.6.5.  Once we upgraded our clients to the newest version, this issue started becoming a big problem.

**Comment by Jako** [comment]
Your clients should have similar response issues. The JSON itself could be invalid or some additional code could be appended. Inspect the code the `Response` tab.

**Comment by spyavery** [comment]
This is mostly an internet issue as i have noticed. Check your dns settings in router and also in browser. Also check locale from modx and server. I usually use google dns to fix this issue in router.
