### ISSUE TITLE
Make cache destination a config setting

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#14115]
### Summary
Right now temporary cache files are located inside the core/ folder

The modx cache manager is handling all caching stuff. It should be able to grab the cache directory locaction from config.inc.php.

## Possible Issues
* the cache folder can become quite big. You don't want them to be part of backups or ftp downloads
* you want to move it outside the web root to offer another level of security
* you have to delete it after moving your installation to a new folder. Excluding the cache folder is a lot easier if it is not located inside core/.
* content inside the core/cache folder doesn't belong to the core, so why put them there?

All these issues could be solved by this.

## Other benefits
* an official tmp folder would also be a good location for thumbnails and other stuff the might change over time:

Example: 
* tmp/cache/
* tmp/phpthumb/

## Possible Problems
Third party plugins might have the path hard wired.

**Comment by Jako** [comment]
We need at least two cache folders. One outside and one inside of the webroot. Thumbs or whatever generated files have to be accessible directly from web. Logs and other files don’t. I don’t think that redirect/rewrite rules could cover everything.

**Comment by Mark-H** [comment]
This is already possible by adding `'cache_path' => '/abs/path/to/cache/'` in `$config_options` in your config file though I've never seen the need to move it myself.
