### ISSUE TITLE
Protect important directories (assets/connectors/core/manager)

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#14114]
### Summary
Protect important directories from renaming or deletion from WITHIN the manager:

Important directories:
* assets/
* connectors/
* core/
* manager/

### Observed behavior
Right click on any of these folders, rename or delete them and you are in trouble.
Could also reduce impact of malicious actions by people with low morals or a short temper.

### Expected behavior
MODX should not allow these actions.

**Comment by Ibochkarev** [comment]
I agree with the colleague about the protection of the following folders:
- assets/
- connectors/
- core/

But the **manager** folder should be protected only from deletion. Many rename this folder to protect against hacking.

**Comment by Ruslan-Aleev** [comment]
@Ibochkarev The rest of the folders are also renamed often, so the comment to all folders is appropriate :)

**Comment by pepebe** [comment]
They might be renamed, but who does that from within the manager?

I guess it would be possible to look up the correct paths for these folders from within config.inc.php and then protect them from being deleted.
