### ISSUE TITLE
Show a link to edit an item in its name in the MODX tables

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14125]
In MODX many settings are edited via the context menu, but this is not obvious, especially if you are not familiar with MODX.
For example in "Context" settings: clicked on the row - nothing happened, clicked 2 times on row - nothing happens either.

- [x] I think it is _worth duplicating the link from the context menu on the item name_, clicked on the link and the settings opened.

**How I see it:**
![link_2](https://user-images.githubusercontent.com/12523676/47645390-50101080-db8a-11e8-8570-5031e1a4376c.png)

I think links should be added to all such tables, this is more understandable for the user than the context menu.
p.s. By the way, in the "Manage -> Users" section the links are already made, but only it is not visible until you hover on it.

**Also a good variant with icons suggested by @Jako:**

- [x] We should also add a icon-button column to all grids in the manager. The 'real' links of some manager pages should be inserted there too (to make those buttons be clickable with a command-click/controll-click while opening the link in a new tab).

Done with https://github.com/modxcms/revolution/pull/14806

![icons_2](https://user-images.githubusercontent.com/148371/47647571-a9bb0f80-db77-11e8-968c-47eb2219bd2f.png)

**Comment by Jako** [comment]
We should better add a button column like in [SwitchTemplate](https://github.com/Jako/SwitchTemplate/blob/master/source/js/mgr/widgets/switchtemplate.grid.js#L204-L238) to all grids in the manager. The 'real' links of some manager pages should be inserted there too (to make those buttons be clickable with a command-click/controll-click while opening the link in a new tab).

Screenshot:
<img width="1056" alt="bildschirmfoto 2018-10-29 um 12 30 15" src="https://user-images.githubusercontent.com/148371/47647571-a9bb0f80-db77-11e8-968c-47eb2219bd2f.png">

**Comment by Ruslan-Aleev** [comment]
@Jako Yes, the icons are also useful, but the links on the names of the lines are more noticeable and understandable. Ideal variant - make and links on names and icons.

**Comment by Jako** [comment]
Some grids could be edited inline and the links can't be used there, so we would have different UX for inline grids, which is a bad habit.

**Comment by Ruslan-Aleev** [comment]
@Jako In the "System settings", for example, inline editing, a window pops up by clicking on the link.
The goal is not to change the functional, but to copy the link from the context menu to the name, the functional already exists.
Or are you talking about something else, you can specify an example of inline editing?

**Comment by Jako** [comment]
If you i.e. double click the name of a context in your example above, the value could be edited inline without a popup. Thats not possible anymore, if the name is surrounded with a link, like you want to do.

**Comment by Jako** [comment]
Example:
<img width="1052" alt="bildschirmfoto 2018-10-29 um 13 17 05" src="https://user-images.githubusercontent.com/148371/47649253-f6551980-db7c-11e8-92aa-900d23f97412.png">

**Comment by Jako** [comment]
You could also directly edit the value of the system setting with a double click.

**Comment by Ruslan-Aleev** [comment]
@Jako Yes, you are right, the context name cannot be changed in this way, but on a page (when clicked), the name can be changed (for other table elemets in a pop-up window).
Here the question is what is more important and changes more often: the name of the context or the context setting (i think the settings)?

And in the system settings it’s true that by double-clicking the value changes, but for a new MODX user, this is not at all obvious, and it’s not obvious how to go, for example, to the context settings (double-clicking here will not work).

We need to think about it, but it seems to me that the benefits of links are more than the ability to quickly change the name.
Button column is also good variant, but, in my opinion, the icon will be less noticeable, especially in large lists and moving the mouse to the button at the end of the line is also uncomfortable.
Correctly move the button to the beginning of the line.

In any case, we need a more discussion :)

**Comment by Jako** [comment]
Both options (inline editing and no right click) could be possible with a button column.

**Comment by Ruslan-Aleev** [comment]
@Jako Yes, the variant is good, but the icon is difficult to see at the end of the list, it should be made brighter, then the variant will be exhaustive.

In any case, it will be clearer than it is now.

**Comment by Jako** [comment]
@gpsietzema Could you add this to the UX change requests for MODX3?

**Comment by Ruslan-Aleev** [comment]
@Jako By the way, the name through a double click can be changed, even if there is a link (we discussed above), you can test PR https://github.com/modxcms/revolution/pull/14581

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/13780

**Comment by Mark-H** [comment]
Resolved with a new actions column / gear icon automatically added to grids in #14806

**Comment by Ruslan-Aleev** [comment]
@Mark-H  I wanted to start adding links to the name in grids in the future, as for example, now in the 
`/manager/?a=security/user` section.
I think it’s worth reopening this issue.
The new gear menu is cool, but with a link there will be less unnecessary clicks, more useful for UX.

**Comment by JoshuaLuckers** [comment]
It would be great if you add a task list with work that still needs to be done before we can consider this issue solved.

**Comment by Ruslan-Aleev** [comment]
I think we can close this issue. Done with PR https://github.com/modxcms/revolution/pull/14864 and https://github.com/modxcms/revolution/pull/14806
