### ISSUE TITLE
thislogin and lastlogin are the same value, but different with :ago modifier

### ISSUE THREAD

**Issue by squarou** [modxcms/revolution#14130]
### Summary
In users attributes, thislogin and lastlogin are the same values. I can't use a real lastlogin

### Step to reproduce
Put this in a page after the user's loggedin (not an administratorn but a normal user).
```
[[!Profile? &prefix=`user.`]]
[[!+user.lastlogin:date=`%d-%m-%Y %H-%M`]]
[[!+user.thislogin:date=`%d-%m-%Y %H-%M`]]
```

### Observed behavior
The 2 dates are the same. 
Strange behavior, using ago modifier ```[[!+user.lastlogin:date=`%d-%m-%Y`:ago]]``` outputs a valuer near the one stored in DB before the user loggeind

### Expected behavior
I guess that ```[[+lastlogin]]``` should display the last time the user loggedin

### Environment
MODX 2.6.5

**Comment by Jako** [comment]
First: Profile is not part of the MODX core. It belongs to the Login package, which has its own repository at https://github.com/modxcms/Login

To help you a bit: Do ```[[!+user.lastlogin]]``` and ```[[!+user.thislogin]]``` have the same value? If not and if boths values are somehow readable, then you have to use:

```
[[!Profile? &prefix=`user.`]]
[[!+user.lastlogin:strtotime:date=`%d-%m-%Y %H-%M`]]
[[!+user.thislogin:strtotime:date=`%d-%m-%Y %H-%M`]]
```

**Comment by squarou** [comment]
Thanks but [[!+user.lastlogin]] and [[!+user.thislogin]] have the same value. In DB, both fields are updated after login. I'll go post this to the Login repo.
