### ISSUE TITLE
Trash: right click "Purge Resource"

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#14138]
### Summary
When you click on the trash can, and right click over a resource to "purge resource", you get the following error message "Resource not specified."

### Step to reproduce
1. Create some test resources
2. Delete those test resources
3. Click on the trash can icon
4. Right click on a particular resource and select "Purge resource"
5. Click "yes" button to confirm

### Observed behavior
Error is reported "Resource not specified."

![bug1](https://user-images.githubusercontent.com/2373940/48489044-6670ca00-e822-11e8-8b05-1d8979c38c2b.gif)

### Expected behavior
No error

### Environment
MODX 2.7.0-dev built from github

**Comment by alroniks** [comment]
Closing as related PR is merged.
