### ISSUE TITLE
[2.7.0] Error log entries added to single line

### ISSUE THREAD

**Issue by dannevang** [modxcms/revolution#14144]
### Summary
All messages in the manager error log are added in a single line, without line breaks.

<img width="1625" alt="screenshot 2018-11-20 at 21 52 56" src="https://user-images.githubusercontent.com/1267643/48802236-ead5b800-ed0e-11e8-8bbc-ab5965c9cddc.png">

### Step to reproduce
Install the pre-release traditional version of 2.7.0 and open the manager. Use the manager so a couple of deprecation warnings are added to the error log.

### Observed behavior
All messages are on a single line.

### Expected behavior
Each message should be on it's own line.

### Environment
MODX 2.7.0 traditional, nginx. 
Local testing environment using valet+ on a Mac.

**Comment by Jako** [comment]
Could be a duplicate of #13946

**Comment by Jako** [comment]
#13966 should be cherry picked into 2.x

**Comment by dannevang** [comment]
After reading #13946 I tested in more browsers.

This behaviour occurs on Safari 12 and Firefox 63 on my machine. Not in Chrome.

**Comment by Jako** [comment]
Is it fixed with that 3.x PR?

**Comment by opengeek** [comment]
This should be addressed now. The changes from #13966 were cherry-picked into 2.x for inclusion in 2.7.
