### ISSUE TITLE
Small bugs

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14142]
1.0 If go to the resource view in "Overview" - there are no styles for the title.

![overview_error](https://user-images.githubusercontent.com/12523676/48629330-c1492380-e9d2-11e8-88cd-69024ba16f54.png)

1.1 In the "Recently Edited Resources" widget the link "Preview Resource" is not working if enabled "Strict Request Method" in "System Settings -> Gateway". Also in the widget there is a link "View", although in the resource tree the same link is called "Overwiew" (see above), and the link "View" in the tree also available and has a different function.

![overview_error_2](https://user-images.githubusercontent.com/12523676/48905760-d531d100-ee7b-11e8-8fe2-af9b1dc71a11.png)

2.0 The tab with the error field for elements (chunks, TV, etc.) does not open.
For example, in TV without adding Name, go to another tab and save. For resources the tab with the error field opens (see picture below), illogical behavior.

2.1. Sometimes the style of the message in the resource for the field with an error are not correct.

![invalid_field_error](https://user-images.githubusercontent.com/12523676/48629747-e5593480-e9d3-11e8-9f8e-93d0d39034eb.png)

3.0 Offset Search Button. Seen when hovering.
Need set "margin: 0" at #modx-manager-search .x-form-field-wrap .x-form-trigger {}

![search_style](https://user-images.githubusercontent.com/12523676/48807461-03f25f00-ed37-11e8-97d7-c47ad216f974.png)

MODX 2.6.5

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report these issues and make MODX better.

It's better to submit a new issue instead of having one issue with a list of issues/bugs/improvements (point 1.0, 1.1 etc can be in one issue). For now it's fine to keep the issue as is.

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Always happy to help!
I agree that they could be divided into different issues, but when I created first one, the bugs were small and not related. And only then I accidentally found a another related bug.

**Comment by Mark-H** [comment]
1.0, 2.1, 3.0 are fixed in 2.7.1 thanks to #14233 and #14230.

**Comment by alroniks** [comment]
It seems that all issues are fixed. So I am closing this bug.
