### ISSUE TITLE
Rank on context not working

### ISSUE THREAD

**Issue by funkyduke** [modxcms/revolution#14147]
The context is ordered like it is in the database, not by the key rank.

### Environment
MODX 2.6.5

**Comment by Mark-H** [comment]
Did you enable `context_tree_sort` and set `context_tree_sortby` to `rank`?

**Comment by funkyduke** [comment]
Thx! Didn't know about this.

**Comment by Mark-H** [comment]
For reference, #13356 (74c78a1b7c4256089c554107e615ab2384817841) made this the default in 2.6. Older sites may need to have it changed manually.
