### ISSUE TITLE
Проблема с MODX белый экран

### ISSUE THREAD

**Issue by NickWelikiy** [modxcms/revolution#14146]
Не могу ничего изменить в MODX, просто белый экран

**Comment by Advanc8d** [comment]
> Не могу ничего изменить в MODX, просто белый экран

Очень подробное описание проблемы =)) Пишите версию modx, настройки хостинга, версию php/mysql.

**Comment by ghost** [comment]
This is where bugs and requests for features are recorded; there are other venues for requests for help.

"I can not change anything in MODX, just a white screen" and "Very detailed description of the problem =)) Write the modx version, hosting settings, php / mysql version." would be more appropriately handled in the Russian section of the forums, https://forums.modx.com/board/230/russian

**Comment by JoshuaLuckers** [comment]
I'm closing this issue because it's a request for support. If it's an actual bug feel free to create a new issue and provide the required information using the issue template that's provided.

Thanks for using MODX.

@modxbot close
