### ISSUE TITLE
Incorrect behavior of the "Uses Template" list in the resource.

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14143]
The "Uses Template" list in resource will open only when **clicking on the button** with arrows, although, for example, in the "Settings"-tab, lists ("Resource Type", "Content Type", etc.) are opened by **clicking on any place** in the list row.

![list_error](https://user-images.githubusercontent.com/12523676/48767819-015d1e80-ecd1-11e8-9c9a-9e4bda58bbb8.png)

MODX 2.6.5

**Comment by alroniks** [comment]
It is an editable field, so after click field becomes in focus for entering values as a usual text field. Other similar fields allow only select existing variants.
So I would say that it is not a bug.

**Comment by Ruslan-Aleev** [comment]
@Alroniks In the list of templates there are only existing variants, or not? And catch the button is less conveniently.
This behavior appeared not so long ago, right?

**Comment by alroniks** [comment]
@Ruslan-Aleev Nope, last changes from 2016, and they unrelated. So it exists for a long time.

**Comment by Ruslan-Aleev** [comment]
@Alroniks :) Very strange, noticed it quite recently and constantly clicked on the entire list instead of the button, apparently, did not pay attention.

**Comment by JoshuaLuckers** [comment]
The template list being an editable field does yield some odd behaviour. If I type in a name of a non-existing template and save the resource it automatically defaults to the base template.

**Comment by Ruslan-Aleev** [comment]
By the way, in the form of quickly creating / editing a resource, the template selection list works by clicking the full width of the list.

**Comment by Ruslan-Aleev** [comment]
@Jako @opengeek @rthrash Any thoughts on this? This is not a bug, but I do not know if this functionality is needed here?

**Comment by rthrash** [comment]
It makes sense to treat it as a traditional select list. I consider it a poor UX.
