### ISSUE TITLE
Name for system setting "automatic_template_assignment" too long

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14168]
### Summary
The lexicon value `setting_automatic_template_assignment ` for the name of the system setting `automatic_template_assignment` is too long.

### Step to reproduce
Go to system settings via the manager and find the entry for `automatic_template_assignment`.

### Observed behavior
It's almost impossible to read the full line.

### Expected behavior
Split the value up so one part can be used in the description instead.

### Environment
MODX 2.7.0-pl

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers There is no key for description setting "setting_automatic_template_assignment_desc" in lexicon setting.inc.php, but there are 2 key for settings "setting_automatic_template_assignment" and because of this description replaces the name of the setting.

**Comment by JoshuaLuckers** [comment]
Thanks for finding the cause of this issue!
