### ISSUE TITLE
MODX 2.7:  Error "Flat file processor support is deprecated"

### ISSUE THREAD

**Issue by weitblick** [modxcms/revolution#14166]
### Summary
Error "Flat file processor support is deprecated" in Error Log

### Step to reproduce
Plain MODX 2.7.0. installation without any changes: Every call of the manager submits an error to error log:
[2018-11-29 19:29:57] (ERROR in modProcessor::run @ /webseiten/modxtest/core/model/modx/modprocessor.class.php : 177) Flat file processor support is deprecated since version 2.7.0. 

### Environment
MODX 2.7, Apache, PHP Version 7.0

**Comment by ghost** [comment]
It can be turned off by `log_deprecated` system setting.

**Comment by ghost** [comment]
Also see https://github.com/modxcms/revolution/pull/14160

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this bug and make MODX better.

As mentioned by @sottwell those messages can be turned off. A fix for this particular message is already submitted with PR #14160 therefore I’m closing this issue.

@modxbot close
