### ISSUE TITLE
Resource media browser context menu [bug]

### ISSUE THREAD

**Issue by kolbykruger** [modxcms/revolution#14170]
### Summary
When right clicking to get a context menu in the modx media browser in list view, the context menu's position is located in the same place every time. The location is not relative to the cursor.

### Step to reproduce
Open the MODX media browser, select list view, click a folder to show some files/images, and right click on any of them to get the popup context menu.

### Observed behavior
The context menu appears, but it is not positioned correctly.

### Expected behavior
The context menu should be relative to the cursor's position when right-clicking.

### Environment
MODX 2.6.5 and 2.7.0 (tested on both).

### Screenshot for more context
![untitled](https://user-images.githubusercontent.com/10890005/49295920-f3538e80-f484-11e8-9ec0-9ef9a33e151d.png)

**Comment by JoshuaLuckers** [comment]
I can confirm this issue. It seems that the position of the contextmenu is related to the width of the element where the right click is triggered on.

**Comment by tolanych** [comment]
This bug isset also in 3.x, but this solution incompatible with it.
In 3.x bug redeclared and located at file /assets/modext/widgets/media/modx.browser.js

https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/media/modx.browser.js#L452

**Comment by alroniks** [comment]
Closing it as PR is merged.
