### ISSUE TITLE
Incorrect display TV with "Tag" input type

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14177]
### Summary
In the resource, the TV field with the "Tag" input type is displayed incorrectly if not set Input Option Values. For other TVs, if Input Option Values is not set, there is no input field, for Tag, the field appears, but incorrect.

![tag_error](https://user-images.githubusercontent.com/12523676/49387962-77836b80-f73c-11e8-83e6-577cdc157443.png)

### Environment
MODX 2.7

**Comment by jonleverrier** [comment]
I can reproduce the issue too.
