### ISSUE TITLE
Nested categories display their id instead of their name

### ISSUE THREAD

**Issue by kolbykruger** [modxcms/revolution#14183]
### Summary
When editing a chunk, placing the chunk in a nested category (a category inside another category), where it would normally display the name of the category, it displays the category id.

### Step to reproduce
Create a category within another category, then create a chunk and assign it to the nested category

### Environment
2.7.0

### Screenshot
![untitled-2](https://user-images.githubusercontent.com/10890005/49565957-15229a80-f8f7-11e8-8a8f-0ca104791b37.png)

**Comment by JoshuaLuckers** [comment]
I can confirm this issue.

**Comment by JoshuaLuckers** [comment]
Fixed by PR #14205
