### ISSUE TITLE
"undefined" text in Trash manager button tooltip

### ISSUE THREAD

**Issue by GulomovCreative** [modxcms/revolution#14189]
### Summary
We will see "undefined" on hover in Trash manager button tooltip

### Step to reproduce
Delete resource right in document tree and hover Trash manager button

![ux](https://user-images.githubusercontent.com/20814058/49691003-1f010380-fb6c-11e8-9476-8576bf5b7f09.gif)

### Environment
MODX 2.7.0-pl

**Comment by JoshuaLuckers** [comment]
I close this issue because a fix for this bug has been merged and will be included in MODX 2.7.1.
