### ISSUE TITLE
Composer install is not working

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#14187]
### Summary
When using the `composer create-project modx/revolution` command the installation of MODX fails during the install action because `/core/packages/core.transport.zip ` does not exist. I noticed that the packages directory contains a gitignore file which ignores everything, so it also ignores the core transport.

### Step to reproduce
Install MODX using composer create-project modx/revolution and try to complete the setup.

**Comment by ghost** [comment]
Don't you still have to build it before you can install it even using Composer?

**Comment by sdrenth** [comment]
@sottwell You're absolutely right, my bad. Thank you!

**Comment by Mark-H** [comment]
Actually no, that is supposed to be done for you automatically https://github.com/modxcms/revolution/blob/2.x/composer.json#L46

**Comment by alroniks** [comment]
For me, it works. Composer built the package and it is available in core/packages folder.

**Comment by sdrenth** [comment]
The issue seems to be the post-create-project-cmd for me somehow:

I get the following output if these commands are being run:
```
You made a reference to a non-existent script @php -r "file_exists('_build/build.properties.php') || copy('_build/build.properties.sample.php', '_build/build.properties.php');"
You made a reference to a non-existent script @php -r "file_exists('_build/build.config.php') || copy('_build/build.config.sample.php', '_build/build.config.php');"
You made a reference to a non-existent script @php _build/transport.core.php
```

So it seems the copy command is not working for me for some reason? But the files build.config.sample.php and build.properties.sample.php do exist.

**Comment by ghost** [comment]
File permissions, perhaps?

**Comment by sdrenth** [comment]
Actually running `composer global self-update` fixed this issue for me. Thank you for helping me out!
