### ISSUE TITLE
Don't work middle mouse button click on Trash manager button

### ISSUE THREAD

**Issue by GulomovCreative** [modxcms/revolution#14190]
### Summary
Don't work **middle mouse** and **Ctrl + Left mouse** buttons click on Trash manager button

### Expected behavior
Open the Trash manager in new tab

### Environment
MODX 2.7.0-pl

**Comment by Jako** [comment]
That will be a larger rewrite and has to go into 3.x. It is a button now and not a link, so it does not have a target, if I remember right.

**Comment by JoshuaLuckers** [comment]
You are right @Jako, it's a button with a handler that redirects on click:
https://github.com/modxcms/revolution/blob/a4b469b4c123a1c0d9b76ec99ba94bef207aab82/core/model/modx/processors/resource/gettoolbar.class.php#L70

**Comment by Ruslan-Aleev** [comment]
Related issue - https://github.com/modxcms/revolution/issues/14242

**Comment by Ibochkarev** [comment]
@Jako can you do it?

**Comment by Mark-H** [comment]
Replacing that function with `MODx.loadPage('resource/trash')` should do the trick as that has support for middle mouse/ctrl+click built in.
