### ISSUE TITLE
Consider adding a SECURITY.md file to encourage responsible disclosure

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#14204]
### Summary
Add a SECURITY.md file to the MODX project to save searching around for the correct contact details.

### Why is it needed?
Encourage responsible disclosure

### Suggested solution(s)
A good example:
https://github.com/snyk/snyk/blob/master/SECURITY.md

### Related issue(s)/PR(s)
None

**Comment by Ibochkarev** [comment]
@JoshuaLuckers Can you make it happen?

**Comment by Ibochkarev** [comment]
Made in #14445 
@modxbot close
