### ISSUE TITLE
Unused static files disappear from server after updating new static file

### ISSUE THREAD

**Issue by valokammi** [modxcms/revolution#14206]
When I upload new static chunk file and point to it in MODX unused chunk file disappears from server.

### Step to reproduce
Create  new static file and upload to server. Point chunk to new static file, old unused file disappears from server.

### Expected behavior
Old file should stay in server.

### Environment
2.7.0-PHP Version 7.0.33, linux

**Comment by jonleverrier** [comment]
I can reproduce the issue.

Just to re-clarify the steps to reproduce: 
1) Upload 2 files. Lets say `chunk_test1.tpl` and `chunk_test2.tpl`
2) Create a static chunk and point it towards `chunk_test1.tpl` then save.
3) Now point the static chunk from `chunk_test1.tpl` to `chunk_test2.tpl` then save.

`chunk_test1.tpl` is missing from the file system

**Comment by Jako** [comment]
Does this happen with or without enabling `static_elements_automate_chunks`?

**Comment by valokammi** [comment]
Setting is "no".

**Comment by valokammi** [comment]
Same happens when changing static template too.

**Comment by JoshuaLuckers** [comment]
PR #14135 introduced this behaviour:
> When removing/deleting a static element, it will remove the static file (if not used by another -element) and will also remove the parent directory automatically for you if the directory is empty.

**Comment by Jako** [comment]
That behaviour should only be executed, when the automatic static workflow is enabled. So this has to be fixed. @sdrenth Could you look for this?

**Comment by sdrenth** [comment]
@Jako @tassu I've added a PR that fixes this issue

**Comment by JoshuaLuckers** [comment]
Fixed by PR #14208 and PR #14228
