### ISSUE TITLE
Ensure Automatic Aliases are Unique and Characters are Compatible with ID elements

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#14200]
### Summary
Automatic generated aliases contain characters which are not friendly when used in css ID elements and cause jQuery (such as a bootstrap 4 accordion) not to function correctly.  I noticed if there is a parenthesis in the title it is passed to the alias and caused the content for an accordion not to display.

### Why is it needed?
It has always been a good practice to only use alphanumeric in file and page names, why should aliases be any different?

### Suggested solution(s)
I would like to see the automatic alias to be generated with a combination of alpha-numeric characters only from the page title with underscores and dashes in place of spaces and the ID number of the resource appended to the characters to ensure auto-generated aliases will always be unique.

**Comment by jonleverrier** [comment]
Hi @pyrographics! 

Sorry if I sound condescending, but have you had a look at the FURL URL system settings? Because they've got you covered for about 99% of your requests...

> generated aliases contain characters which are not friendly when used in css ID elements and cause jQuery (such as a bootstrap 4 accordion) not to function correctly
- friendly_alias_translit (has your back here!)
- friendly_alias_restrict_chars_pattern

> I would like to see the automatic alias to be generated with a combination of alpha-numeric characters only from the page title

- friendly_alias_restrict_chars
- friendly_alias_restrict_chars_pattern
- friendly_alias_trim_chars

> with underscores and dashes in place of spaces
- friendly_alias_word_delimiter
- friendly_alias_word_delimiters

**Comment by OptimusCrime** [comment]
I agree with @jonleverrier .

Additionally, the FURL is supposed to be used as a HTTP URI, not HTML ID. The aliases generated today are perfectly valid URIs. If you do not want to mess around with the system settings like Jon suggested above, I suggest you make your own snippet that takes in the alias and strips out everything that you want ignored.

No reason to make these changes to the MODX core in my opinion.

Suggest closing this.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to request this feature. 


If we consider the rules for the ID attribute in the HTML standard:
> ID tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":")

Versus the allowed characters in URI’s:
> ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=

Then it should be clear why we can’t restrict the alias to be compatible with ID attributes.
