### ISSUE TITLE
[enhancement] Add explanatory text with MODX tags to the description of the "System Settings" and "Lexicon" sections

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14229]
### Summary

All the important elements of MODX ("pagetitle", "tv", "chunks") have a hint about how to use them and display them in the site, but not the fields in "System Settings".
At acquaintance with MODX it is not obvious that the fields in the system settings can not only be changed, but also used with tag [[++key]].
I propose to add an explanatory text to the description of the "System Settings" section, for example, would be:

![system_settings_1](https://user-images.githubusercontent.com/12523676/50547730-e8914280-0c58-11e9-8b73-7045c8c77bf0.png)

Similar explanatory text must be added to the **"Context Settings"** section and to the **"Lexicon Management"** section.

Perhaps in the future in the "System Settings" there will be a tip with a hint - https://github.com/modxcms/revolution/issues/14176 But in the description information about the use will be useful.

**Comment by alroniks** [comment]
Closing as PR is merged. Thank you for your impact!
