### ISSUE TITLE
[enhancement] MODX setup: changing fields and their order

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14238]
### Summary
1) When installing MODX, in the db setting, in the current version the "Database name" and "Database login name" fields are separated by the "Database password" field, but very often these fields have the same value and they are filled in via copy / paste, they must be nearby.
**The correct order, in my opinion, should be:**
...
"Database name"
"Database login name"
"Database password"
...

p.s. In the /core/config/config.inc.php file, need also place variables next to each other ($dbase, $database_user).

2) When setting up an administrator, the "Admin username" and "Admin password" fields are separated by the "Admin email" field, but the "Username - Password" combination should always be nearby, this is already standard :)
**The correct order, in my opinion, should be:**
...
"Admin email"
"Admin username"
"Admin password"
"Confirm password"
...

3) Add the **"Site Settings" item** to the MODX installation and add the **"Site Status"** field (enabled or not), uncheck the box and you can not worry about indexing the unfinished site.
Also add the **"Site name"** field, a useful setting, is found in other CMS, and it is logical to set the Site name when installing the site.
I am not sure, but it also makes sense to add the "Site email" field, which is now in the "System settings" - the key "emailsender" and is equal to "Admin email", but in fact these should be different fields.

Perhaps it makes sense to add more important fields, or not to add them at all, but the order of the fields (points 1 and 2) needs to be changed precisely.
**Anyway, we need a discussion.**

_Upcoming MODX3 installer design:_
![3-connect](https://user-images.githubusercontent.com/12523676/50730618-eeac8500-116a-11e9-8d7c-7366be17ce55.png)

**Comment by Mark-H** [comment]
Where'd you get that screenshot from?

**Comment by Ruslan-Aleev** [comment]
@Mark-H :) I found it here - https://modx3.org/updates/week-18-june-11-17-2018

**Comment by Mark-H** [comment]
Thanks. Someone should implement that design... maybe I can find some time in the next few weeks. :)

**Comment by Ruslan-Aleev** [comment]
It would be great, but, besides design in MODX3, if the item "Site settings" will be added, then need to select useful settings, in addition to "Site status", "Site name". Need a discussion.

**Comment by Ibochkarev** [comment]
> Thanks. Someone should implement that design... maybe I can find some time in the next few weeks. :)
 
@Mark-H If you provide mockups, I can join

**Comment by Ibochkarev** [comment]
@Ruslan-Aleev is it still topical?  we kind of made edits on this topic

**Comment by Ruslan-Aleev** [comment]
I create a separate issue
