### ISSUE TITLE
Panel Disapeared in chrome, firefox and explorer

### ISSUE THREAD

**Issue by agatamaciej** [modxcms/revolution#14239]
### Summary
Left panel with resourses have disapeared, I am using MODX Revolution 2.5.2-pl everyday, I am using Chrome version 71.0.3578.98  (64-bit), at first I thought that just some cache problem and I used ingonito mode, but today, modx doesn't work on any explorer I have check firefox and explorer. Now it doesn't work even in the incognito mode. I don't know what to do, and I need to make update on the website.

### Environment
MODX Revolution 2.5.2-pl, Chrome version 71.0.3578.98

**Comment by Mark-H** [comment]
First of all, you need to upgrade your site. 2.5.2 has known security vulnerabilities.

There can be different reasons for the manager to break, but the issue tracker is not where we can help you with that. The issues tracker is for bugs that can be fixed. As this issue does not contain enough information for core contributors to fix a problem in the core, I'm going to close this issue.

Please use the forum or slack to get help with debugging your problem. If you have posted on the forum, please feel free to share the link here to get some more people to look at it.

**Comment by agatamaciej** [comment]
What forum do You mean? Is there a place where I can ask for help?



[cid:PremAIR_ffce7b74-9541-491a-afa1-10f6f2d61c59.jpg]<http://www.ventilation-alnor.co.uk/index/news/industrial-news/new-premair-from-alnor.html>
Best regards / Pozdrawiam

Agata Maciejak
Specjalista ds. marketingu

Mobile: +48 667 544 524
Tel:      +48 22 737 40 75

[cid:2_96aa07b2-82a8-4b39-a224-9e0566b9aadd.png]<https://www.facebook.com/Alnor.Systemy.Wentylacji/> [cid:Instagram_be1b055f-80d0-41e3-a034-93ea04b66604.png] <https://www.instagram.com/alnor_systemy_wentylacji/>  [cid:5_82a36495-9e9c-464c-9e40-8ceb3ea4d962.png] <https://www.linkedin.com/company/220331/>  [cid:6_8333991a-37f9-4c55-a13a-7b611aa499d5.png] <https://www.youtube.com/channel/UCOZ5Gw3nN9e8V2K-PCikGrw>

[cid:Logo-Alnor-250_f9996bc8-b67f-4e65-943b-5d3c15fd4fbd.png]<http://www.alnor.com.pl/> ALNOR Systemy Wentylacji Sp. z o.o.
Polska, 05-552 Wola Mrokowska, Aleja Krakowska 10

Alnor Systemy Wentylacji Sp. z o.o., 00-719 Warszawa, ul. Zwierzyniecka 8b REGON: 010685817 NIP: 521-10-68-747, Kapitał zakładowy 334 500 PLN
Sąd rejonowy dla m. st. Warszawy, XIII Wydział Gospodarczy KRS nr 0000038889
Administratorem danych osobowych, których nam dostarczasz, jest Alnor Systemy Wentylacji sp. z o.o.
z rejestrowaną siedzibą w Warszawie i adresem ul. Zwierzyniecka 8B, 00-719 Warszawa.
Zbieramy Twoje dane osobowe, w celach kontaktowym w związku z realizacja zamówień oraz w celach marketingowych.
Więcej informacji na temat polityki prywatności znajdą Państwo pod tym linkiem<http://www.alnor.com.pl/index/firma/oswiadczenie-o-ochronie-prywatnosci.html>.

**Comment by Mark-H** [comment]
Yes, the [MODX forums](https://forums.modx.com) :)
