### ISSUE TITLE
Vertical Tabs explode if TV names longer than 169px

### ISSUE THREAD

**Issue by IamNeo1** [modxcms/revolution#14240]
The template variable container is defined with a fixed width of 169px. If the names of the template variables are longer, the whole layout of the vertical tabs explodes.

![modx_long_tv_names_1](https://user-images.githubusercontent.com/8747516/50828344-67fdd080-1341-11e9-9691-90bd153f56f7.PNG)

It is simple to reproduce and simple to fix.

After each update of the manager CSS I have to search and adjust the two places where the width is fixed to 169px. It is already commented as "dirty hack". Why not just set it to "auto". Then the content area adapts.

index.css 6068 rule: `.vertical-tabs-panel .vertical-tabs-header`

![modx_long_tv_names_2](https://user-images.githubusercontent.com/8747516/50828541-f5d9bb80-1341-11e9-9a70-fe317403e4fb.PNG)

index.css 6112 rule: `.vertical-tabs-panel .vertical-tabs-header .x-tab-strip-wrap ul.x-tab-strip > li.x-tab-strip-active`
![modx_long_tv_names_3](https://user-images.githubusercontent.com/8747516/50828641-3c2f1a80-1342-11e9-82e7-3ab64255ffb5.PNG)

See here with "auto" at both rules
![modx_long_tv_names_4](https://user-images.githubusercontent.com/8747516/50828810-bd86ad00-1342-11e9-9ab6-93ae34ec0c5a.PNG)

Please fix that.

**Comment by Ruslan-Aleev** [comment]
@IamNeo1 <del>I can't reproduce this bug, how do you test it?</del>
