### ISSUE TITLE
Deprecate 'upload_flash' setting.

### ISSUE THREAD

**Issue by guyinpv** [modxcms/revolution#14245]
### Summary
It's about time to deprecate the system setting `upload_flash`. Or combine it with the media setting. Does anybody still use swf and fla files?

![deprecate setting](https://user-images.githubusercontent.com/708955/50852007-9d9fbb00-133b-11e9-85e0-3a58eb834d22.png)

**Comment by OptimusCrime** [comment]
Kill it with fire!

**Comment by alroniks** [comment]
PR is merged, closing.
