### ISSUE TITLE
MODX 3.0 Translation is not loaded - file_folder_visibility

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14246]
### Summary
Go to Media - Media Management - go to the desired folder with the image. We right-click on the image and see the lack of translation for file_folder_visibility

![14246](https://raw.githubusercontent.com/Ibochkarev/other-repo/0d1c21a34a8ce5e56ee29eebbe88825d718b6687/14246.jpg)

@JoshuaLuckers   There is no entry for the Russian language in the namespace (core), subject (file) - file_folder_visibility

![14246-1](https://raw.githubusercontent.com/Ibochkarev/other-repo/feac384acb4f3a665d2804c01d14c2ffa01038a5/14246-1.jpg)

### Environment
MODX 3.0.0-pl, apache, mysql 5.6, browser Google chrome 71.0.3578.98

**Comment by Mark-H** [comment]
This should get resolved the next time the lexicons are synchronized with crowdin.

**Comment by Ibochkarev** [comment]
@Mark-H Good. Thanks
