### ISSUE TITLE
Bug with continue in switch xPDOVehicle.php

### ISSUE THREAD

**Issue by Ser1ous** [modxcms/revolution#14253]
### Summary
After install modx 3.0-dev warnings in 
https://monosnap.com/file/E6cjSij2SqMrkwAC4uTofc3S6dWTZP
`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/dev.ser1ous.com/core/vendor/xpdo/xpdo/src/xPDO/Transport/xPDOVehicle.php on line 134

Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/dev.ser1ous.com/core/vendor/xpdo/xpdo/src/xPDO/Transport/xPDOVehicle.php on line 211`

### Step to reproduce
Instal last step

### Environment
php-fpm 7.3 
MySQL 8.0

**Comment by Ser1ous** [comment]
More one:
`Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/dev.ser1ous.com/core/model/modx/modcachemanager.class.php on line 608`

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue and help make MODX better.

> `Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/dev.ser1ous.com/core/vendor/xpdo/xpdo/src/xPDO/Transport/xPDOVehicle.php on line 134
> 
> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/dev.ser1ous.com/core/vendor/xpdo/xpdo/src/xPDO/Transport/xPDOVehicle.php on line 211`

This is an xPDO "issue". It is better to [report it as xPDO issue](https://github.com/modxcms/xpdo/issues) 

> More one:
> `Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/dev.ser1ous.com/core/model/modx/modcachemanager.class.php on line 608`

This issue is fixed in the 2.x branch. Once we merge 2.x into 3.x it will be fixed there as well.
