### ISSUE TITLE
[bug] For default.inc.php in the translation line $ _lang ['remove_this_confirm'] does not work the parameter "[[+type]]"

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14256]
### Summary
The string $_lang['remove_this_confirm'] in English looks like this:

Are you sure you want to remove the [[+type]]: "[[+name]]"?

However, the "[[+type]]" parameter does not work, tested in different languages, see the picture below.

![lang_bug_1](https://user-images.githubusercontent.com/12523676/51030994-9b946100-15b4-11e9-81de-d871a1e81b14.png)

### Environment
MODX 2.7.0

**Comment by alroniks** [comment]
I see that it works fine. Chunk is a placeholder, it shouldn't be translated in this case. Also, lexicons do not support nested lexicon tags, only simple placeholders. So it should be fixed, but my comment as a clarification.

**Comment by Ruslan-Aleev** [comment]
Placeholders are translated, in other places they are displayed correctly, but not in this pop-up message.

![lang_bug_2](https://user-images.githubusercontent.com/12523676/51047158-4589e280-15e1-11e9-8df5-123565ecdc28.png)

**Comment by JoshuaLuckers** [comment]
This issue has been solved with PR #14272
