### ISSUE TITLE
Media Browser doesn't show files for directories with an ampersand (&) character 

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14264]
### Summary
While testing PR #14263 I noticed that the media browser doesn't show files for directories containing an ampersand (&) character. 

### Step to reproduce
1.  Create a directory with an ampersand, eg. Something & Something (not via the media browser).
2. Put some files in it 
3. Navigate to the directory using the MODX media browser.

### Observed behavior
The media browser does not list the files in the directory if the directory name contains an `&` character. Deleting it is also not possible and will throw an error: `The specified directory is not a directory.`

### Expected behavior
The media browser should display files in directories whose name contain characters the filesystem allows. 

### Environment
MODX 2.7.x-dev

**Comment by Ruslan-Aleev** [comment]
Perhaps related to https://github.com/modxcms/revolution/issues/12932

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/13412

**Comment by smg6511** [comment]
This is still a problem in 2.8.6 (but is not on 3.x) ... checking it out ....
