### ISSUE TITLE
[enhancement] Make TV input fields active by clicking on the input field

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14268]
### Summary
If the width of the TV fields is 100% as suggested here - https://github.com/modxcms/revolution/issues/11856, then the buttons, for example, the TV with image selection will be located on the right and it will be difficult to get on it, especially with the current size of the monitors.

![tv_2](https://user-images.githubusercontent.com/12523676/51076573-9f5add00-16b3-11e9-836c-2f5a778ca8c2.png)

We can make TV active immediately by clicking on the field, and not just on the button.

_But even if the width is not increased by 100% - in my opinion, it will be more convenient, there will be no need for an extra click on the button._

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/11856

**Comment by JoshuaLuckers** [comment]
I'm not in favour of implementing this because it will prevent manually changing and/or copy/paste the value.

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Yes, you are right, I forgot about it...

Another variant is to move the active TV button to the left in the input field, see the picture below.
But this should be done specifically for TV, because for a resource, active buttons look better stylistically to the right (choosing a template, for example).

![tv_3](https://user-images.githubusercontent.com/12523676/51078214-60388600-16cb-11e9-8bb2-6b7e84707dac.png)

**Comment by Ruslan-Aleev** [comment]
In general, I created this issue  as a supplement / discussion on the issue https://github.com/modxcms/revolution/issues/11856, since the issue https://github.com/modxcms/revolution/issues/11856 has the label "state / accepting-pull-request", but not everything is clear.
