### ISSUE TITLE
Strange behavior at the event OnUserSave (seems like the user saved twice)

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [modxcms/revolution#14279]
### Summary
Strange behavior at the OnUserSave event. It seems that the user is saved twice. I discovered this when I posted a script for sending a letter to an event if someone had registered on the site. I emulate the preservation of a (already existing) user through the admin area, I received two letters each. How to reproduce this will describe below.

### Step to reproduce

1. create a plugin with the code below
```php
<?php
if ($modx->event->name != 'OnUserSave') return;

$modx->log(modX::LOG_LEVEL_ERROR, $mode);
```

2. Go to the page of any user through the admin panel and click save

### Observed behavior
We get two errors...
```php
[2019-01-15 22:16:15] (ERROR @ /home/user/www/core/cache/includes/elements/modplugin/3.include.cache.php : 4) upd
[2019-01-15 22:16:15] (ERROR @ /home/user/www/core/cache/includes/elements/modplugin/3.include.cache.php : 4) upd
```

### Expected behavior
Must receive one error, because we save user only 1 time.

### Environment
MODX 2.7.0 Tested on a clean site.
PHP 7.2

**Comment by GulomovCreative** [comment]
I'll match and raise @iWatchYouFromAfar issue.

### Steps

1. Create a user without a group and save
2. Create plugin with the code bellow:

```
<?php

if ($modx->event->name != 'OnUserSave') return;
$modx->log(1, print_r($user->getUserGroupNames(), 1));
```
3. Now add the user to some group and save

We will get this:

```
[2019-01-15 22:50:49] (ERROR @ path\core\cache\includes\elements\modplugin\17.include.cache.php : 4) Array
(
)

[2019-01-15 22:50:49] (ERROR @ path\core\cache\includes\elements\modplugin\17.include.cache.php : 4) Array
(
    [0] => Administrator
)
```

**Comment by Jako** [comment]
The user object is saved twice in the create/update processor. Once in the saveObject method and once in the setUserGroups method to save the primary group. I am not sure how this could be avoided.

**Comment by iWatchYouFromAfar** [comment]
> The user object is saved twice in the create/update processor. Once in the saveObject method and once in the setUserGroups method to save the primary group. I am not sure how this could be avoided.

From the point of view of work from front-end, everything works correctly. Because there is written its own algorithm for registering (or not?) and saving a user profile - Office component.

I do not claim, but it seems to me that double saving the user is wrong. But once in so much time, I first paid attention to this, which means it is not fatal.

P.S.
Just tested on the Login component. From the front-end also saved user only once.
