### ISSUE TITLE
Form customization: Constraint value isn't displayed in grid if constraint value is 0

### ISSUE THREAD

**Issue by GulomovCreative** [modxcms/revolution#14285]
### Step to reproduce
1. Create new set in FC
2. Fill **"Constraint Field"**: `isfolder` (for example)
3. Fill **"Constraint"**: `0`

Screenshots are below

![screenshot-tutorial-2019 01 16-18-59-50](https://user-images.githubusercontent.com/20814058/51248064-89099580-19c1-11e9-81c7-403e1bfd0f5d.png)
![screenshot-tutorial-2019 01 16-19-00-39](https://user-images.githubusercontent.com/20814058/51248065-89a22c00-19c1-11e9-85ea-17fd1c60bad0.png)

### Environment
MODX Rebolution 2.7.0-pl (Advanced)

**Comment by alroniks** [comment]
Issue solved by merged PR.
