### ISSUE TITLE
User update page context menu position bug

### ISSUE THREAD

**Issue by GulomovCreative** [modxcms/revolution#14286]
### Summary
When right clicking to get a context menu in the update user page in **Access Permissions** tab, the context menu's position is located always in the center. The location is not relative to the cursor.

![screenshot-tutorial-2019 01 16-19-30-54](https://user-images.githubusercontent.com/20814058/51249442-dbe54c00-19c5-11e9-9f1e-945b04c4cb6d.png)

A similar bug was in Media Browser #14170 

### Step to reproduce
Open the user update page, move to **"Access Permissions"** tab and right click on some group/setting

### Observed behavior
The context menu is not positioned correctly.

### Expected behavior
The context menu should be relative to the cursor's position when right-clicking.

### Environment
MODX 2.7.0-pl

**Comment by Ruslan-Aleev** [comment]
**Solution:** replace in `/manager/assets/modext/widgets/security/modx.panel.access.policy.template.js` `m.show(e.target);` on `m.showAt(e.xy);`
Similar to https://github.com/modxcms/revolution/pull/14199/files
