### ISSUE TITLE
In 2.7.0 installing extras gives deprecation error for different exta

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#14302]
### Summary
When I install an Extra that has a routing-based menu item, I see an error message in red referencing another extra which doesn't.

For example, when installing the new version of Orphans, which contains no action object and has one routing-based menu item, I see this:

> modAction support is deprecated since version 2.3.0. Support for modAction has been replaced with routing based on a namespace and action name. Please update the extra with the namespace **sitecheck** to the routing based system.

Many people won't read to the end of this and will assume that Orphans has a deprecated menu system. I don't think this is caused by a left-over action because the action is removed in the Orphans validator, unless the system is responding to an older version of Orphans that is still in core/packages, but in that case the namespace in the message would be 'orphans.' 

A similar error message gets written to the error log when you drop down the Extras menu, so I don't think it's necessary for this to appear when extras are installed.

### Step to reproduce

Install an extra with a modAction. Install another extra with a routing-based menu. 

### Observed behavior
You seen the error message in the console during package installation

### Expected behavior
No error message

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.
MODX 2.7.0
Localhost/XAMPP
PHP 7.0

**Comment by sebastian-marinescu** [comment]
Very annoying, as my initial automated setup (with Gitify package-installation) now "fails" (still usable, but red and not green with a big ok anymore).
