### ISSUE TITLE
Better log for: "Encountered empty IN condition with key id"

### ISSUE THREAD

**Issue by sebastian-marinescu** [modxcms/revolution#14316]
### Summary
Sometimes I get this error in the logs: 

> (ERROR @ /somepath/www/core/xpdo/om/xpdoquery.class.php : 764) 
> Encountered empty IN condition with key id

Looking at this line: 
https://github.com/modxcms/revolution/blob/2.x/core/xpdo/om/xpdoquery.class.php#L764
it doesn't even seem to be something grave - but I'd still like to find the origin of it. 

That's why I would like more information on this log. 

### Why is it needed?
Better debugging and fixing of possible errors. 

### Suggested solution(s)
I could imagine something like this could be sufficient: 
```
$this->xpdo->log(xPDO::LOG_LEVEL_ERROR, "Encountered empty {$operator} condition with key {$key}: " . print_r($val, true));
```

So either show $val `print_r($val, true)` or $conditions `print_r($conditions, true)`.

If someone can confirm this approach, or give me a recommendation, I'd be happy to prepare a PR.

**Comment by Mark-H** [comment]
Isn't $val or $conditions just going to contain an empty condition? Not sure if that's going to help figure out what's causing it just yet. 

Also, this is an xpdo issue: https://github.com/modxcms/xpdo

**Comment by sebastian-marinescu** [comment]
Yes, you're right - in both cases :) 

Logging `$conditions` didn't help much: 
```
Encountered empty IN condition with key id: Array
(
    [id:IN] => Array
        (
        )
)
``` 

I added this issue to the xpdo-repo: 
https://github.com/modxcms/xpdo/issues/155
