### ISSUE TITLE
$modx->runProcessor('security/user/create') only works once. 

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14314]
### Summary
Attempting to create multiple users with ```$modx->runProcessor('security/user/create', $fields);```
only works the first time. Subsequent attempts return an empty array when calling: ```$response->getObject();```

### Step to reproduce
I originally tried it within a standard `for` loop. Like this:
```
for($i=0;$i<$numOfTutors;$i++) {
    $faker = Faker\Factory::create('en_HK');
    $fields = [];
    $fields['active'] = true;
    $fields['passwordgenmethod'] = 'g';
    $fields['passwordnotifymethod'] = 's';
    $fields['email'] = $faker->email;
    $fields['username'] = $faker->userName;
    $fields['class_key'] = 'CustomClass';
    $response = $modx->runProcessor('security/user/create', $fields);
    $newTutor = $response->getObject();
    var_dump($newTutor);
}
```
A loop is not necessary however, it is the same result even if just attempting to create 2 new users one after the other.

### Observed behavior
The first iteration works, the rest do not. The provided field values are unique in each iteration so that's not the problem. There are no errors or warnings in the log.

### Expected behavior
It should create new users.

### Environment
MODX 2.7.0

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue and help us make MODX better. 

This issue is a duplicate of issue #11951, therefore I'm closing this issue.

**Comment by muzzwood** [comment]
Sorry, I missed that one. Thanks!

**Comment by JoshuaLuckers** [comment]
No worries, thanks for reporting it 🥇
