### ISSUE TITLE
Improve the file preview  in the media manager

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14321]
### Summary
Improve the file preview in the media manager by improving the quality of the "No Preview Available" image and make it translatable and/or use actual images matching the file type.

### Why is it needed?
For non-images the media browser shows a "No Preview Available" image. As mentioned by @Ruslan-Aleev in issue #14307 this image is of poor quality. 
>  It is also worth changing the picture "No Preview Available" to an icon, since The picture is of poor quality and does not look very good, see the picture below.
The image is also in English and may confuse non-english users (although I'm sure most non-english speakers are still able to figure out it's meaning).

Because all non-image files show the "No Preview Available" image it's hard for users to distinguish files. The Media Browser is not used only to browse images but also other kind of files.

### Suggested solution(s)

One thing that needs to be done is to improve the quality of the image itself by creating a higher resolution image. 

To make it translatable we can:
1. Make a "No Preview Available" image for each language MODX supports.
2. Make the text available as lexicon and use an image processor to add the text dynamically. 

To better distinguish the different file types I propose to add preview images corresponding the file type. Like a PHP icon for php files, PDF icon for PDF files etc etc.

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Why did you refuse the option with the icon? In my opinion, this is the simplest and most universal solution.

![file_icon](https://user-images.githubusercontent.com/12523676/51675547-6a248800-1fed-11e9-85dc-653cf27d07e8.png)

If the Media Browser will open different files in the preview window, then yes, it would be helpful to see the icon with the file type (php, jpg, txt, etc.), but if the view is not available, then the icon with the type is not needed.

**Comment by JoshuaLuckers** [comment]
My mistake, the icon you suggest is also a possible solution I would like to suggest (did you make the icon?)

**Comment by Ruslan-Aleev** [comment]
The icon is already in Font Awesome, just need replace the image tag with an icon tag, for example:
`<i class="far fa-eye-slash"></i>` - the best choice in my opinion
or
`<i class = "far fa-window-close"></i>`

Or another suitable icon - https://fontawesome.com/icons?d=gallery&m=free
