### ISSUE TITLE
Information is not displayed in the Recently Edited Resources panel.

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14334]
### Summary
Information is not displayed in the Recently Edited Resources panel.

### Observed behavior
Here is the next bug:
- the resource id is not displayed correctly (if it is a resource)
- resource title is not displayed
- the date of resource editing is not displayed

![2019-02-06_10-33-23](https://user-images.githubusercontent.com/2138260/52320784-69332380-29fb-11e9-9be2-a334a7465f01.png)

### Expected behavior
Must correctly display a list with resources.

### Environment
The latest version of MODX 3.0.0pl recruited using composer.

**Comment by alroniks** [comment]
Related to https://github.com/modxcms/revolution/issues/14333

**Comment by Mark-H** [comment]
This was fixed in the processors refactor.
