### ISSUE TITLE
Trash manager grid resource title not correctly escaped

### ISSUE THREAD

**Issue by travisbotello** [modxcms/revolution#14338]
### Summary
Using script tag inside content field of a deleted resource causing resource's title in trash manager grid being messed up.

### Step to reproduce
- Create a resource with `pagetitle` *test* and content like this:
```
<script>
var test = "test";
</script>
```
- Delete this resource
- Switch to trash manager

### Observed behavior
In grid you will see the resource's title being rendered `">Test` and tooltip content preview `var test =`

### Expected behavior
Resource's title in the grid shouldn't be messed up by content.

### Environment
MODX 2.7.0 advanced

**Comment by JoshuaLuckers** [comment]
This problem is solved by merging PR #14401
