### ISSUE TITLE
Incorrectly working list of editable resources by the user.

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14333]
### Summary
Incorrectly working list of editable resources by the user.

### Step to reproduce
It is necessary to click on the User main menu, then Edit user, go to the Recent Resources tab.

### Observed behavior
A list is displayed, but there is no name and ID is not displayed correctly. The screenshot shows the ID of the resources in the list.

![2019-02-06_04-48-06](https://user-images.githubusercontent.com/2138260/52309505-8a2f5080-29ca-11e9-9c7f-e90ebcad787f.png)

Right click on the item from the list, select Edit and get the error.
![2019-02-06_04-49-27](https://user-images.githubusercontent.com/2138260/52309542-a7fcb580-29ca-11e9-90e4-93721eed0510.png)

Right click on an item from the list, select View and get error 500.
![2019-02-06_04-58-56](https://user-images.githubusercontent.com/2138260/52309963-ee9edf80-29cb-11e9-9efa-1a180bcce7d2.png)

### Expected behavior
Must correctly display a list with resources.

### Environment
The latest version of MODX 3.0.0pl recruited using composer.

**Comment by alroniks** [comment]
Please, hold it before 2.x will be merged into 3.x because the similar problem already was solved in 2.7.1 - https://github.com/modxcms/revolution/pull/14234. So it may raise conflicts.

**Comment by alroniks** [comment]
Related to https://github.com/modxcms/revolution/issues/14334

**Comment by Mark-H** [comment]
This was fixed in the processors refactor.
