### ISSUE TITLE
[bug] Confirmation window changes width

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14340]
### Summary
In the Deleted Resources Manager, **possibly in other sections**, the confirmation window changes its width.

### Step to reproduce
1) In the Deleted Resources Manager, mark the resources and click "Purge All"
2) On the confirmation window, click "No"
3) Press "Purge All" again - the window has reduced its width.

![trash](https://user-images.githubusercontent.com/12523676/52404292-1aac8480-2ae2-11e9-8f17-40af3a3fd420.gif)

### Environment
MODX 2.7.0

**Comment by Ibochkarev** [comment]
I can reproduce this bug. MODX 2.7.0

**Comment by ant-tar** [comment]
Noticed that too for 2.7.1

**Comment by Ibochkarev** [comment]
The problem also exists in 3.x

**Comment by Ibochkarev** [comment]
Fixed #15984
