### ISSUE TITLE
Stored XSS: Media Source

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14341]
### Summary
Stored XSS: Media Source

### Step to reproduce
Go to the Media menu, then media sources. Create or edit an existing media source and insert `<img src=# onerror=alert(1); />`

![screencast 2019-02-07 16-13-07](https://user-images.githubusercontent.com/2138260/52404785-0b363700-2af4-11e9-844a-fe6cf8507591.gif)

### Observed behavior
The application processes the html tags or scripts and it is getting stored in the database.

### Expected behavior
It should not accept any scripts or html tags.

### Environment
MODX Revolution 2.7.0-pl

**Comment by Mark-H** [comment]
I think this is a duplicate of #14094 that was fixed in #14336 just 22 hours ago? Can you still reproduce in the latest 2.x?

**Comment by Ibochkarev** [comment]
@Mark-H  
**Still found**:
In Content types - /manager/?a=system/contenttype
In Profile - /manager/?a=security/forms
In the panels - /manager/?a=system/dashboards
In access policy - /manager/?a=security/permission
In the parameter sets - /manager/?a=element/propertyset
In lexicons - /manager/?a=workspaces/lexicon
In namespaces - /manager/?a=workspaces/namespace

I will try to test the latest version of github and try to fix it myself on the weekend!

**Comment by Mark-H** [comment]
I've created PR #14344 that applies XSS protection for all grid columns by default. There are still places where object names are inserted into a header dynamically, without running them through htmlEncode, so those will still need manual fixing.

**Comment by Ibochkarev** [comment]
@Mark-H It is excellent!

**Comment by Ibochkarev** [comment]
Fix to #14344
