### ISSUE TITLE
Stored XSS: Context

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14342]
### Summary
Stored XSS: Context

### Step to reproduce
Go to the Settings menu, then Contexts. Create or edit an existing context and insert `<img src=# onerror=alert(1); />`
![russian inn - revista rusa en espana russian inn - 2019-02-07 16-29-12](https://user-images.githubusercontent.com/2138260/52405533-b2679e00-2af5-11e9-9d96-c088c3bbce17.jpg)
![web111 russian inn - revista rusa en espana russian inn - 2019-02-07 16-28-47 1](https://user-images.githubusercontent.com/2138260/52405534-b2679e00-2af5-11e9-80b1-5f1edfdbc545.jpg)

### Observed behavior
The application processes the html tags or scripts and it is getting stored in the database.

### Expected behavior
It should not accept any scripts or html tags.

### Environment
MODX Revolution 2.7.0-pl

**Comment by OptimusCrime** [comment]
Does it also print the alert, or is that stripped out?

**Comment by Ibochkarev** [comment]
@OptimusCrime An example of execution can be seen here: #14341  Runs the same.

**Comment by JoshuaLuckers** [comment]
~Fixed in 3.x by merging PR #14344~

**Comment by JoshuaLuckers** [comment]
Sorry, PR #14344 didn't solve this particular case.
