### ISSUE TITLE
Webp format and MODX is not friend yet.

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [modxcms/revolution#14355]
### Summary
As you probably know, the format of webp images is becoming more and more relevant. If you do not know, then here's an article on Wikipedia - https://en.wikipedia.org/wiki/WebP.

In MODX there are several problems that I discovered while trying to work with this format. What I want to tell below.

### Step to reproduce & Observed behavior
**Problem 1.**
Go to the settings and look for the key ** upload_images **. The description of the setting tells us that here we can specify the format of images that can be loaded into the _assets/images/_ folder. Specify the format webp and when you try to download the image in this folder, we get an error.

![1](https://user-images.githubusercontent.com/16403917/52524776-fe5f4200-2cb1-11e9-91e5-8c0748ee5254.gif)

**Improvement 1.**
After our unsuccessful attempt to upload an image, look for the setting with the ** upload_files ** key and specify the wepb format there. After that, we successfully upload the image. Perhaps it is necessary to register this format by default in future versions?

**Problem 2.**
As you can see, the preview image in the webp format is not available for us to see. This is sad, because MODX modern CMS!

![2](https://user-images.githubusercontent.com/16403917/52524785-0e772180-2cb2-11e9-9250-557828feb55e.gif)

### Observed behavior
**Problem 1.**
if I understood correctly, after specifying the format of the webp, we should easily upload the image to this directory?

**Problem 2.**
FTW We must see the preview!

### Environment
PHP 7.2
MODX 2.7.0

**Comment by JoshuaLuckers** [comment]
WebP is not supported by one of the major browsers. And if I’m not mistaken phpthumb doesn’t support WebP either.

**Comment by Ibochkarev** [comment]
> WebP is not supported by one of the major browsers. And if I’m not mistaken phpthumb doesn’t support WebP either.

At the moment, phpthumb does not support the format of the webp as this issue says 
https://github.com/JamesHeinrich/phpThumb/issues/107.

I added a PR that changes the setting and registers this format in the list of allowed downloads.

**Comment by muzzwood** [comment]
It looks like there's a PR adding this to phpthumb as of 4 hours ago.
https://github.com/JamesHeinrich/phpThumb/commit/884abbdb1b045c16b58b9b3f0969d93e043a7b26

**Comment by JoshuaLuckers** [comment]
MODX and `webp` are now friends! Thanks a lot to all involved.
