### ISSUE TITLE
Form Customization: Menu Title / Form Title

### ISSUE THREAD

**Issue by achterbahn** [modxcms/revolution#14352]
### Summary
Actually the menu entry for FC is "Manager Customization". But the title of the form is "Form Customization". 

### Step to reproduce
Click manager menu "Manager Customization" and watch the title in the form opened.
![image](https://user-images.githubusercontent.com/1411919/52520360-3f7f3400-2c69-11e9-8e15-1ab635dbe4ec.png)

### Observed behavior
--

### Expected behavior
Identical naming 

### Environment
MODX => 2.7.0

**Comment by opengeek** [comment]
Fixed via #14780
