### ISSUE TITLE
[bug] MODX3: Scroll overlaps controls in the tree

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14375]
### Summary
In the tree, if a scroll appears, it will overlaps the controls and the trash bin in the tree, see gif below.

![scroll_bug](https://user-images.githubusercontent.com/12523676/52734786-7b0a5d00-2fdf-11e9-8271-64478c892927.gif)

### Environment
MODX3

**Comment by Mark-H** [comment]
Fixed in alpha2.
