### ISSUE TITLE
2.7.0-pl upgrade script is running on installing 2.7.1

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#14382]
### Summary
The 2.7.0-pl upgrade script is running on installing 2.7.1.

### Step to reproduce
Install MODX 2.7.1 on a modx 2.7.0 installation. The alias_visible column is added again and throws an error, since it already exists.

### Observed behavior
The alias_visible column is added again and throws an error, since it already exists.

### Expected behavior
The alias_visible column is not added again.

### Environment
2.7.1

**Comment by Ibochkarev** [comment]
I can reproduce this error.
