### ISSUE TITLE
XSS: Dangerous table name

### ISSUE THREAD

**Issue by AgelxNash** [modxcms/revolution#14389]
### Summary
No escaping HTML tags

### Step to reproduce
Create table with name
```
"><img src="#" onerror=alert(1);>
```
Open **System Info** -> **Database tables**

### Observed behavior
![image](https://user-images.githubusercontent.com/1748872/52866364-4e318380-3160-11e9-9f4d-cd908ae00a9a.png)

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this potential security issue. If someone is able to access the database with create privileges this attack vector then this is of least concern, therefore I'm closing this issue.

A personal request from me to you: please consider reporting security issues responsible by using the "[Report a Security Issue](https://develop.modx.com/contribute/security/report/)" form.
