### ISSUE TITLE
Error loading files to Media Source root

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14380]
### Summary
When you try to download the file to the root of the media source, an error appears: `Please specify a valid directory.`

### Step to reproduce
Go to the Files tab, right-click on the Media Source Filesystems, select the Load files item in the context menu.

### Observed behavior
```
Error
- ekko-lightbox.min.js: Please specify a valid directory.
- ekko-lightbox.css: Please specify a valid directory.
- 2019-02-12 01.41.53.jpg: Please specify a valid directory.
- 2019-02-12 01.42.17.jpg: Please specify a valid directory.
```

### Expected behavior
Errors when loading to the root of the Media source should be absent

### Environment
The latest version of MODX 3.0.0pl recruited using composer.

**Comment by Ruslan-Aleev** [comment]
Pretty serious bug for UX

**Comment by alroniks** [comment]
Solved.
