### ISSUE TITLE
Unpacking zip file allows uploading arbitrary files

### ISSUE THREAD

**Issue by AgelxNash** [modxcms/revolution#14385]
### Summary
Bypass **upload_files** settings

### Step to reproduce
- Upload zip file containing files not allowed by upload_files setting
- Unpack

**Comment by ghost** [comment]
I must admit this is one of the reasons I wanted the "unpack" feature in the first place. But I suppose it's not really a good idea to be able to do that.

Was anything ever done about the "rename" feature? I also used to simply upload files with a .txt sufix, then rename the file with .php suffix or whatever it was I wanted to upload.

Of course, opening an FTP/SFTP client and uploading necessary files from that is much preferable, but sometimes I just feel lazy.

**Comment by Mark-H** [comment]
> Was anything ever done about the "rename" feature? I also used to simply upload files with a .txt sufix, then rename the file with .php suffix or whatever it was I wanted to upload.

Yes, that was fixed in #13240.

**Comment by opengeek** [comment]
Can this not be avoided by preventing the upload of a zip file via the upload_files setting?

**Comment by Ruslan-Aleev** [comment]
@opengeek In the context menu there is a whole item on unpacking the zip-archive, i.e. in addition to the preventing .zip, we need to think about unpack functionality (remove it or something else).
