### ISSUE TITLE
Wrong icon for descending sort order

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#14395]
### Summary
Wrong icon for descending sort order

### Step to reproduce
Open resource page, Resource Groups tab and try descending sorting
### Observed behavior
The icon was broken probably
![editing_ home _ modx revolution - google chrome 2019-02-16 15 50 06](https://user-images.githubusercontent.com/2815640/52900129-63abb980-3203-11e9-9b8b-71ba4c5c51f6.png)

### Expected behavior
Proper "triangle" icon should be therre

### Environment
2.7.0

P.S. this is easy issue, will upload correct icon via PR shortly.

**Comment by GulomovCreative** [comment]
This is the legacy of the old Ext Js

**Comment by ant-tar** [comment]
I got sick (( 
Could you please guys replace it at /manager/templates/default/images/modx-theme/grid/sort_desc.gif ? 
Here is actual icon attached: 
![sort_desc](https://user-images.githubusercontent.com/2815640/53089632-29e9f400-351e-11e9-9b44-84d9a9d1eeab.gif)
Many thanks.
