### ISSUE TITLE
Stored XSS: Lexicon

### ISSUE THREAD

**Issue by AgelxNash** [modxcms/revolution#14391]
### Summary
All lexicons no escaping HTML tags

### Step to reproduce
```
"><img src="#" onerror=alert(1);>
```

### Observed behavior
Simple example
![image](https://user-images.githubusercontent.com/1748872/52872776-2990d800-316f-11e9-970c-f3ae322417b6.png)

**Comment by Mark-H** [comment]
The grid XSS should be resolved in 3.x, beyond that I don't think we need to escape lexicons. Many of them contain markup for highlights/links so this would break that.

Editing lexicons is also an administrator level functionality, so it's not something just about anyone could pull off.

**Comment by AgelxNash** [comment]
Like other XSS reports

**Comment by sergant210** [comment]
@Mark-H  as for me, I think that lexicons should not contain html markup.

**Comment by alroniks** [comment]
Agree with @sergant210, but also with @Mark-H. In 3.x it is fixed globally, so I am closing it as wontfix.
