### ISSUE TITLE
Title input field is deactivated when copying child resources

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14409]
### Summary
Title input field is deactivated when copying child resources

### Step to reproduce
When duplicating a resource, if it has child resources when switching the checkbox (Copy child resources), the field for entering the title for the duplicate is deactivated.

### Observed behavior
![](https://file.modx.pro/files/5/3/b/53b5b76b638899662dc38f202a05a032.jpeg)

### Expected behavior
The checkbox (copy child resources) in the checked state should not deactivate the field named

### Environment
MODX version 2.7.1

**Comment by JoshuaLuckers** [comment]
Isn't that the default behaviour for form inputs?

**Comment by GulomovCreative** [comment]
@JoshuaLuckers Checkbox should choose whether child resources are copied and nothing else, but now if you uncheck the box and put it back, the title field becomes unavailable

**Comment by JoshuaLuckers** [comment]
Thanks for clarifying @GulomovCreative. I was clicking the radio buttons instead of the checkbox.
