### ISSUE TITLE
Media manager sometimes uploads files to the wrong folder

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#14400]
### Summary
The media manager doesn't always upload files to the expected folder.

### Step to reproduce
1. Set up a TV (file or image) and link it to a specic media source. In that media source, create folders (like "images/newsletter/" for example). 
2. In a resource that uses that TV, link the TV to a file INSIDE a subfolder. Save the resource. 
3. Edit a different resource, then go back to the original resource.
4. Edit the TV. In the middle pane, the media browser will show the files inside the folder corresponding to the TV setting you saved.
5. Click the upload button in the upper left of the media browser and upload a file. 

### Observed behavior
Following the steps above, the file will be uploaded into the ROOT folder of the media source, NOT the folder whose contents are displayed in the main panel.

### Expected behavior
As it is now, a folder on the left has to be clicked on first, before clicking the upload button, to make files go into that folder. When the media browser first opens, if the contents of a subfolder are displayed in the main panel, that folder should ALSO be selected in the left list of folders/files. Otherwise, even though a folder is not selected on the left, users think that uploading a file will go into the folder that is being viewed in the main panel. 

### Environment
All versions of MODX.

**Comment by SnowCreative** [comment]
Put another way, when opening the media browser from a TV field that has a file entered, make the media browser tree have the folder containing that file selected.

**Comment by JoshuaLuckers** [comment]
Thanks for adding additional information!

**Comment by SnowCreative** [comment]
Any update on this? I continually have to educate new clients about this bug in the media manager so they can upload files where they want them to go.

**Comment by SnowCreative** [comment]
Any update?

**Comment by JoshuaLuckers** [comment]
Sorry, I don’t have any update on this. My time is also a bit limited due to my baby girl being born! 

Maybe @Ruslan-Aleev is able to help fix this?

**Comment by Ruslan-Aleev** [comment]
Sorry, but I have no time and no opportunity.

Maybe @Jako is able to help fix this? :)

**Comment by SnowCreative** [comment]
> Sorry, I don’t have any update on this. My time is also a bit limited due to my baby girl being born!
>

Hey, that's exciting! Congrats!

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/5320

**Comment by Ruslan-Aleev** [comment]
> Any update?

@rainbowtiger You can replace this line https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/system/modx.tree.directory.js#L725
with:
`var path = this.config.openTo || this.config.rootId || '/';`
Then the path will be saved.

I haven't figured out how to add select class to the directory on the left yet.

**Comment by SnowCreative** [comment]
Thanks — that fixes uploading to the wrong place. Highlighting the folder on the left would also be great, but at least this will fix the main problem for clients.

**Comment by Ibochkarev** [comment]
Fixed #15227

@modxbot close
