### ISSUE TITLE
[bug] Input Option Values for TV: bugs with a field and description

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14424]
### Summary
Recently, an unnecessary Input Option Values for TV was hidden (https://github.com/modxcms/revolution/pull/14040), however there are a couple of bugs:
1) The input field still displayed for TV with types **"Auto-tag", "Hidden", "RichText" and "URL"**, but it is not needed in these TVs.

2) The input field description-label is **always shown**, even if the field itself is hidden, which is strange, see the picture below.

![tv_input_options_bug](https://user-images.githubusercontent.com/12523676/53235714-f0df8a00-36ab-11e9-8397-035b91c54d6e.png)

### Expected behavior
The field should be displayed and **be required** only for fields for which Option Values are needed, for example, the checkbox TV.
And the Option Values field should be checked at the stage of saving, as suggested by @JoshuaLuckers - https://github.com/modxcms/revolution/pull/14275#issuecomment-454428234 (which is a more logical option than I suggested in PR)

For the rest of the TV, this field and its description should be removed.

### Environment
MODX 2.7.1

**Comment by Jako** [comment]
The description is outside of the `element` there. But it has a `for` attribute with the value of the element id. Maybe you could get the description with:

```
Ext.select('label[for="' + element.id + '"]');
```

and hide that, if it is found.
