### ISSUE TITLE
A save animation appears above the logo when editing a resource

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14428]
### Summary
If you update the panel **when editing a resource** and drag any resource in the tree, the save animation will appear above the logo once, see the picture below.
After refreshing the page, the bug will be repeated.

![menu_animate_bug](https://user-images.githubusercontent.com/12523676/53422486-041a8e80-39f9-11e9-98ef-ac490c7a6d11.gif)

### Environment
MODX3, Windows 7, Google Chrome

**Comment by Ruslan-Aleev** [comment]
As it turned out, this bug is also relevant for version 2.7.

**Comment by Ibochkarev** [comment]
Fixed #14790 
@modxbot close
