### ISSUE TITLE
friendly_alias_realtime setting not working

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#14438]
### Summary
The friendly_alias_realtime is "on" whether or not the System Setting is set to "No".

### Step to reproduce
Make sure the friendly_alias_realtime System Setting is set to "No". Create a new resource, and type in the title.

### Observed behavior
The Alias field will echo the title as it is being typed.

### Expected behavior
If the System Setting is set to "No", the Alias field should not be filled out until after the resource is saved.

### Environment
MODX Revolution 2.7.1

**Comment by Mark-H** [comment]
Fixed per #14441 in 2.7.2
