### ISSUE TITLE
[bug] In the description of the system settings html tags are not processed

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14437]
### Summary
In version 2.7.1, there was a lot of PR on protection from XSS with html-escaping tag output.
Now in the system settings, in the description, the tags are not processed, see the picture below.

![setting_error](https://user-images.githubusercontent.com/12523676/53592149-1d653b80-3baf-11e9-8fb0-f0fc84c1922d.png)

### Environment
MODX 2.7.1

**Comment by Mark-H** [comment]
Unless we reintroduce XSS issues, this can't easily be fixed.

**Comment by Jako** [comment]
A striptags could fix the current output.

**Comment by Ruslan-Aleev** [comment]
@Mark-H it seems the issue has been fixed through https://github.com/modxcms/revolution/pull/14453

**Comment by Ibochkarev** [comment]
Fixed in #14453
@modxbot close

**Comment by Mark-H** [comment]
Glad I was proven wrong on this issue ;)
