### ISSUE TITLE
Spaces before or after search word distort the result

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#14448]
### Summary
If you accidentally (or not) enter an extra space into search field before or after the criteria, you won't find expected results.

### Step to reproduce
Please check next video, I've tried space before and after the word

![trim_spaces](https://user-images.githubusercontent.com/2815640/53687760-7d8fe500-3d49-11e9-9263-a30f93cb7354.gif)

### Observed behavior
If space is there you won't find expected elements. It's terrible especially when you need to copy/paste cell values (which have been saved carefully with spaces) from xls (or any other) file into search and find appropriate elements 

### Expected behavior
As for me we need trim() here

### Environment
MODX 2.7.1

**Comment by JoshuaLuckers** [comment]
The PR to resolve this this issue has been merged.
