### ISSUE TITLE
Mark required fields automatically

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#14452]
### Summary
Append/prepend an asterix automatically to a field that has `allowBlank: false` set.
This could be done by adding a css class with js or by js itself.

### Why is it needed?
Automatisation. Better handling of RTL languages.

### Suggested solution(s)
Add some javascript that add a css class and maybe some html to a field that has `allowBlank: false` set. I am not sure, wether a css rule will be enough from an accessibility perspective.

### Related issue(s)/PR(s)
None known.

**Comment by alroniks** [comment]
PR is merged, that means the issue solved. Closing.
