### ISSUE TITLE
modx-tree-usergroup is not defined. Javascript error

### ISSUE THREAD

**Issue by GulomovCreative** [modxcms/revolution#14450]
### Summary
There is an error in the browser console. The **modx-tree-usergroup** is not defined

### Step to reproduce
1. Open Access Control Lists page
2. Go to any tab except the first
3. Refresh the page
4. See to browser console

![screenshot-revolution-2019 03 03-06-13-02](https://user-images.githubusercontent.com/20814058/53688960-d87f0780-3d5c-11e9-8ebe-5bc246682425.png)

### Observed behavior
Error displayed in console.

### Expected behavior
There should not be an error in the console.

### Environment
MODX 3.x

**Comment by Mark-H** [comment]
Fixed by #14451
