### ISSUE TITLE
MODX 3: Lexicon (login.inc.php) "Good night" should be "Good evening" in English. 

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14470]
### Summary
"Good night" isn't used in contemporary English as a greeting. It's typically used as a farewell.

### Step to reproduce
Go to the manager login page.

### Observed behavior
n/a

### Expected behavior
The English lexicon value for `$_lang['login_greeting_night']` should be changed to `<strong>Good evening</strong>, welcome back!`

I would have done a PR for this but I'm not sure if changes are made directly or through the Crowdin system. (?)

**Comment by Ibochkarev** [comment]
You can send a PR to correct, then the guys will synchronize with Crowdin for translation into other languages

**Comment by muzzwood** [comment]
Thanks, will do!

**Comment by Jako** [comment]
I would prefer 'Hello Nightowl' ;-)

Serious: In german the meaning of `good night` is similar than in english. So we should better think what could be set as welcome string in the night or completely remove that entry.

**Comment by ghost** [comment]
I think a generic greeting would be the better idea. If someone wants a time- or season-specific greeting that is easy enough to create.

**Comment by muzzwood** [comment]
Haha night owl works for me! 
My line of thinking was that perhaps some languages need differentiation between evening and night whereas English doesn't. So, in that case it'd be best to keep the entry and just double up the values on the English (and German?) side.
