### ISSUE TITLE
Media sources have no icon in media browser

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14487]
### Summary
In the Media browser, there is no icon in the sources tree on the left, but in the Files tab the icon is correctly displayed, see the picture below.

![no_icon](https://user-images.githubusercontent.com/12523676/54392473-33035680-46c1-11e9-9457-b5ff18c00af0.png)

### Environment
MODX 2.7.1

**Comment by JoshuaLuckers** [comment]
The PR to resolve this this issue has been merged.
