### ISSUE TITLE
New design for installer

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14504]
### Summary
It is rewritten the pages of the installer in accordance with the designed design.

### Why is it needed?
![1-welcome](https://user-images.githubusercontent.com/2138260/54737119-9d902700-4bd8-11e9-9faf-7115aebaa2eb.png)
![2-settings](https://user-images.githubusercontent.com/2138260/54737120-9d902700-4bd8-11e9-924e-e171738d1486.png)
![3-connect](https://user-images.githubusercontent.com/2138260/54737121-9e28bd80-4bd8-11e9-90ba-6ca508073fca.png)
![4-test](https://user-images.githubusercontent.com/2138260/54737123-9e28bd80-4bd8-11e9-9559-75cc199032f1.png)
![5-installed](https://user-images.githubusercontent.com/2138260/54737126-9e28bd80-4bd8-11e9-817d-f14830b997e6.png)

### Suggested solution(s)
- [x] Add rules to gruntfile.js for compiling styles for the installer
- [x] Connect normalize to reset styles
- [x] Delete unused images
- [x] Delete unnecessary style files after assembly via Grunt
- [x] Rewrite layout using flexbox

### Related issue(s)/PR(s)
N/A

This process I'll do the other day. Please assigned me for this request.

Also, please comment on what else needs to be improved. This will be the first step in this improvement.

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/14238, https://github.com/modxcms/revolution/issues/13876

**Comment by Ibochkarev** [comment]
can be closed. made in #14507
