### ISSUE TITLE
Move "Deleted" checkbox from the resource settings

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14501]
### Summary
In the resource editing tab on the right there are the publishing group, it seems to me that it is right there to place the "Deleted" checkbox.

Firstly, the checkbox is logically associated with the publication, secondly, it will be immediately see that the resource has been deleted or it will be easier to delete it (other settings do not change often, unlike deletion).

![delete](https://user-images.githubusercontent.com/12523676/54695950-5c4e3780-4b44-11e9-8236-8de6ff4ee682.png)

**Comment by Mark-H** [comment]
Fixed in #14545
