### ISSUE TITLE
Unpublish for the "site_start" resource

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14509]
### Summary
The resource that is specified in the system settings as "site_start" cannot be unpublished from the context menu in tree - an error will appear, see the picture below.

![site_start](https://user-images.githubusercontent.com/12523676/55071533-57d4d200-50a2-11e9-9167-beb2b49960c4.png)

But at the same time, the editing of this resource can be unpublished trough chekbox, and the site will open with 404, see the picture below.

![site_start_error](https://user-images.githubusercontent.com/12523676/55071534-586d6880-50a2-11e9-81dc-8a216758ef79.png)

By the way, a similar inconsistency for **deletion "site_start" resource** (the context menu in the tree / resource editing form)

### Environment
MODX 2.7.1
https://github.com/modxcms/revolution/issues/9774 - Discussed earlier, but now it works in opposite way, as it seems to me.

**Comment by JoshuaLuckers** [comment]
While it's not recommended I do think it should be possible to mark any resource as unpublished if you really want to.

**Comment by Ruslan-Aleev** [comment]
This is logical, yes. Then in the context menu should activate this possibility.

**Comment by devlanda** [comment]
The behaviour should be consistent.

**Comment by JoshuaLuckers** [comment]
I agree.

**Comment by ghost** [comment]
More than once I've accidentally clicked the "unpublish" menu option, but I have never accidentally unchecked the "published" checkbox.

**Comment by Ruslan-Aleev** [comment]
By the way, a similar inconsistency for **deletion "site_start" resource** (the context menu in the tree / resource editing form)

**Comment by Ibochkarev** [comment]
Fixed #15579
