### ISSUE TITLE
Incorrect version display PHPMailer and Smarty

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14515]
### Summary
Incorrect version display PHPMailer and Smarty

### Step to reproduce
Go to menu Management -> Reports -> System Information

### Observed behavior
![Информация о системе | MODX Revolution 2019-03-30 08-00-03](https://user-images.githubusercontent.com/2138260/55269922-fccdf580-52c2-11e9-95bd-0e75e0db1393.png)

### Expected behavior
https://github.com/modxcms/revolution/blob/2.x/core/model/smarty/Smarty.class.php#L30
https://github.com/modxcms/revolution/blob/2.x/core/model/modx/mail/phpmailer/class.phpmailer.php#L34

### Environment
MODX version 2.7.1.

**Comment by JoshuaLuckers** [comment]
The PR to resolve this this issue has been merged.
