### ISSUE TITLE
Incorrect behavior of the menu tree in the "Menu" section

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14521]
### Summary
1) If I move the item to the main section "Top Menu", the item will simply disappear from the menu in the manager panel. You can make a mistake and do not understand why the item disappeared, but the item is present in the menu section (the nesting of the items is not clear until all the menus are minimized).

![menu-bug](https://user-images.githubusercontent.com/12523676/55397391-2ef78580-5557-11e9-9973-695e7a7eea27.gif)

This section "Top Menu" should be renamed to "Main Menu" and **prohibit dragging items into it or create an menu item with an empty parent**, as it seems to me.

There is another related bug. **If you delete the main categories (Top Navigation and User Navigation), then the new created items can no longer be displayed in the manager panel**.

2) There is also missing icon in the tree, by analogy with another tree, for example, the resource tree.

![top-menu-1](https://user-images.githubusercontent.com/12523676/55397884-5438c380-5558-11e9-941b-b7d35a1e814b.png)

---

It may be worth hiding the root category (Top menu) and leaving only the menu categories (Top navigation and User navigation) so that the menu item cannot be added by dragging to the root category. But then it is worth removing the empty parent (root category) when creating an item.

![top-menu-2](https://user-images.githubusercontent.com/12523676/55497417-626b0a80-5652-11e9-9106-5e1ad8bcf21f.png)

### Environment
MODX 2.7.1.

**Comment by JoshuaLuckers** [comment]
Related issue: #14220

**Comment by Ruslan-Aleev** [comment]
Also, if you move menu items from "Main Navigation" to "User Navigation", then the icon item is not displayed.

![menu_bug_3](https://user-images.githubusercontent.com/12523676/86520679-cd0b8700-be4f-11ea-8bc9-3c67f94f36e8.png)

**Comment by JoshuaLuckers** [comment]
The description of the menu item shouldn't be displayed when it's a direct child of the main navigation.
<img width="448" alt="Screen Shot 2020-07-07 at 09 43 02" src="https://user-images.githubusercontent.com/1268085/86739568-44027480-c036-11ea-8968-9d3f7bb7afab.png">

**Comment by Ruslan-Aleev** [comment]
> The description of the menu item shouldn't be displayed when it's a direct child of the main navigation.
> <img alt="Screen Shot 2020-07-07 at 09 43 02" width="448" src="https://user-images.githubusercontent.com/1268085/86739568-44027480-c036-11ea-8968-9d3f7bb7afab.png">

I fixed this (both your comment and mine) at https://github.com/modxcms/revolution/pull/15152
More precisely, descriptions can be set, they work, but in the correct way (corrected styles). But for all the main items the descriptions are no longer set.

**Comment by alroniks** [comment]
A lot of pull requests merged, so seem to be fixed.
