### ISSUE TITLE
Parent of resource doesn't changing

### ISSUE THREAD

**Issue by geforester** [modxcms/revolution#14531]
### Summary
Parent of resource on settings tab doesn't change if old parent and new parent have same alias but different contexts

### Step to reproduce
see https://youtu.be/YC-rH3ipxaU
old parent and new parent must be have same alias and different contexts

### Observed behavior
resource have old parent 

### Expected behavior
resource have new parent 

### Environment
MODX 2.7.1, safari of latest macos.

**Comment by Electrica** [comment]
This bag don't have in 3. version.
Video: https://youtu.be/RhSYQLgPdpE

**Comment by Ibochkarev** [comment]
This problem is not reproducible

https://user-images.githubusercontent.com/2138260/112868203-9a8c7300-90dd-11eb-8515-0a8443bf3b19.mov
