### ISSUE TITLE
Bug when deleting the parent item in the "Menu" section

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14530]
### Summary
If you delete the parent item in the menu, the **child item is no longer displayed in the tree**, but it is not deleted.
It will not be possible to create an item with the same name and it is in the list of parents.

![menu-delete](https://user-images.githubusercontent.com/12523676/55484803-3774bc80-563a-11e9-9af4-9efce3a0b280.png)

![menu-delete-2](https://user-images.githubusercontent.com/12523676/55484804-3774bc80-563a-11e9-9296-7135e6f3aa36.png)

When creating a new item, the last edited item is automatically assigned as a parent, even if it has been deleted and when saving item an error pops up that the parent is not found.

![menu-delete-3](https://user-images.githubusercontent.com/12523676/55484949-7e62b200-563a-11e9-8587-c2ba4d15db00.png)

### Environment
MODX 2.7.1
https://github.com/modxcms/revolution/issues/14220
https://github.com/modxcms/revolution/issues/14521

**Comment by alroniks** [comment]
So, I've started work on it and faced with a problem. What to do with nested menus?
Somebody accidentally can remove top menu (even after confirming popup) and in case removing all menus will go away directly from a database, it can be painful to restore them from the database.
The second option - move a menu to the level of deleted.

Please, vote using emoji for this comment. 👍 for the removing, 👎 against removing that also means moving to the upper level.

**Comment by Jako** [comment]
With a warning 'removing' the children should be ok.

**Comment by Jako** [comment]
If a parent is removed, the children should be removed (with a warning). Otherwise it will be a lot of work to delete a whole tree. Moving items up is not a normal behavior for me.

**Comment by jcdm** [comment]
The 'next level' would be to have a marked-as-deleted for menu items from which they can be undeleted, but that would increase the scope a fair bit so I couldn't say if it would have much value in terms of value for users for the investment.

**Comment by JoshuaLuckers** [comment]
Maybe we could ask the users to move the items “up” or to another element?

**Comment by Mark-H** [comment]
Fixed in #14532
