### ISSUE TITLE
MODX 3 Installation error 'missing dependencies'

### ISSUE THREAD

**Issue by gentlemesh** [modxcms/revolution#14537]
### Summary
Can not install MODX 3 on local test host from ready build, getting Error 503 and a "Site temporarily unavailable; missing dependencies." message. According to the installation procedure, there should be '/core/vendor/autoload.php' file, but this file is absent.

### Step to reproduce
Download nightly MODX 3 build (https://nightly.modx.by/download/modx-3.0.0-dev-20190407.zip), unpack the archive into site folder, open in browser 'http://modx3test.local/setup/'

### Observed behavior
Server gives Error 503 with the following message "Site temporarily unavailable; missing dependencies."

### Expected behavior
Installation should continue as usual, file '/core/vendor/autoload.php' should be in it's place.

### Environment
MODX version: modx-3.0.0-dev-20190407,
apache/nginx: Apache 2.4, nginx 1.14,
mysql: 5.7,
OS: Windows 8,
Web-server bundle: OpenServer(https://ospanel.io/),
browser: doesn't matter.

**Comment by Mark-H** [comment]
As of 3.x, you need to run `composer install` when building from source. I thought @Alroniks also fixed that in the nightly builds, but perhaps not?

**Comment by alroniks** [comment]
Cron script used composer without proper full path so this step was skipped without any warnings in logs. Now it fixed. Closing the issue.
