### ISSUE TITLE
Convert Security processors

### ISSUE THREAD

**Issue by opengeek** [modxcms/revolution#14547]
Convert processor classes in `core/model/modx/processors/security/` to `src/Processors/Security/`

Submit PR to the draft PR #14534 via https://github.com/opengeek/revolution/tree/psr4

Document Group - seems it is not in classes and replaced by Resource Group processors, but file left in the code base and should be removed.

- [x] Access (https://github.com/opengeek/revolution/pull/13)
- [x] Forms (https://github.com/opengeek/revolution/pull/17)
- [x] Group (https://github.com/opengeek/revolution/pull/12)
- [x] Message (https://github.com/opengeek/revolution/pull/8)
- [x] Profile (https://github.com/opengeek/revolution/pull/9)
- [x] Resource Group (https://github.com/opengeek/revolution/pull/11)
- [x] Role (https://github.com/opengeek/revolution/pull/7)
- [x] User (https://github.com/opengeek/revolution/pull/15)
- [x] Flush, Login, Logout (https://github.com/opengeek/revolution/pull/10)

**Comment by alroniks** [comment]
It seems solved.
