### ISSUE TITLE
Welcome message: wrong background image + bad text links

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#14541]
### Summary
Welcome popup message: wrong background image + incorrect URL links

### Step to reproduce
Install fresh 2.7.1 MODX and check welcome screen content

### Observed behavior

![2019-04-06 12 43 01](https://user-images.githubusercontent.com/2815640/55723079-b0945b00-5a10-11e9-9a36-458710a1f06c.png)

1. Background image doesn't load from https://modx.com/assets/i/headline_bg_2col.jpg

![2019-04-07 16 26 26](https://user-images.githubusercontent.com/2815640/55723078-b0945b00-5a10-11e9-9119-371f5e5b3d60.png)

2. "Page not found" for donation https://modx.com/community/wall-of-fame/support-modx/
3. MODX Forums URL can be changed from https://modx.com/forums/ to https://community.modx.com/  

### Expected behavior
Background image should be loaded
Proper links for Donation(if any) and Community

P.S. Is it possible to have i18n for this text? 

### Environment
2.7.1

**Comment by ant-tar** [comment]
I can send PR here, just clarify proper URLs for me please.

**Comment by Mark-H** [comment]
That page is embedded from the MODX site, so that has to be corrected by someone at the LLC: @opengeek @matdave @rthrash?

**Comment by ghost** [comment]
Which is precisely why I have never been in favor of depending on any third-party for any landing page activity. It gives a very poor appearance to have such a failure be the first thing a new user will see.

**Comment by alroniks** [comment]
Yes, the image should be placed to the repository. Links can be changed during time, it's not a huge problem and easy to fix.

**Comment by opengeek** [comment]
It should not be in the repository, as that requires a release to fix it if changes are needed. We are working to resolve the issues that were oversights from the recent relaunch of modx.com. Thanks for the report.

**Comment by opengeek** [comment]
Moving forward, i.e. for 3.x+, I think we should come up with a simple app to present the welcome information from modx.org with an i18n-capable presentation that could be maintained by contributors, similar to the documentation efforts.

**Comment by jaygilmore** [comment]
These pages have been fixed and while I was at it, I also inlined the little CSS they use and cut the volume of CSS by 96% (since it was using old CSS from the website from 2010.) Should be much snappier and has correct links.

**Comment by OptimusCrime** [comment]
Close this issue then?

**Comment by Ibochkarev** [comment]
Fixed earlier. 
For example: the welcome message for 2.8.x http://misc.modx.com/revolution/welcome.28.html
