### ISSUE TITLE
Incorrect use of the getOption method in the modResource class

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#14583]
### Description
```
// modResource::filterPathSegment()
$xpdo->getOption('use_multibyte', false)
```
The second parameter must be an array. Аnd the default value should be passed in the third parameter

[Source code](https://github.com/modxcms/revolution/blob/3.x/core/model/modx/modresource.class.php#L206)

P.S. By the way, it is not necessary to pass $xpdo by reference.

**Comment by Ibochkarev** [comment]
Fixed #15638
