### ISSUE TITLE
Error loading static template

### ISSUE THREAD

**Issue by alienbuild** [modxcms/revolution#14588]
### Summary
When trying to load a static template in the manager upon save it returns the error:
`An error occurred while saving the template.`

### Step to reproduce
Create a new template, click 'is static' and proceed to load a template and save.

### Observed behavior
Returns an error on saving.

### Expected behavior
Expected to load static template.

### Environment
MODX3, PHP 7.1

**Comment by Ibochkarev** [comment]
The problem does not reproduce in the next environment:

MODX Revolution 3.0.0-devBuilt on Nov 25, 2019
PHP Version 7.2.19
Apache/2.4.35 (Win64) OpenSSL/1.1.1b
mysqlnd 5.0.12-dev

Fixed Earlier
@modxbot close
