### ISSUE TITLE
MODX3: Icon for "container" is not displayed

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14597]
### Summary
The resource does not change the icon in the tree, even if the resource is a "container".

**MODX 2.7.1:**

![icon_1](https://user-images.githubusercontent.com/12523676/58821447-23ebcf00-8646-11e9-8425-d5142c5877eb.png)

**MODX 3:**

![icon_2](https://user-images.githubusercontent.com/12523676/58821448-23ebcf00-8646-11e9-8f24-bb2a11e215f5.png)

Possibly related to https://github.com/modxcms/revolution/pull/14383

### Environment
MODX 3

**Comment by Mark-H** [comment]
Fixed in #14786
