### ISSUE TITLE
Browse Locally For Vapor Packages Not Functioning in 2.7.1

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#14600]
### Summary
Use vapor to create a snapshot of a website, upload into core/packages and package will not display in the list.  This has always functioned in the past.  I resorted to using theme packager component to migrate sites but this doesn't work as well.

### Step to reproduce
1. Install fresh modx.  
2. Use vapor to create a package 
3. Manually upload the package into core/packages
4. Use the Search Locally for Packages button to make it appear

### Observed behavior
Package does not appear

### Expected behavior
Package should appear

### Environment
MODX version 2.7.1, PHP 7.1, Apache 2.4

**Comment by ghost** [comment]
I think it's something to do with the name being too long. You can change the default name either in the vapor.php file or with a custom config.php file, that should help.

**Comment by pyrographics** [comment]
Thank you, I'll try that.  It is something new in 2.7.X because I've never had an issue with it previously.

**Comment by pyrographics** [comment]
I did fix it by changing vapor.php lines 118 and 119 to:

if (!defined('PKG_NAME')) define('PKG_NAME', 'VaporImport');
if (!defined('PKG_VERSION')) define('PKG_VERSION', '1.0');

For those who use this, changing only the name alone didn't solve the issue, I had to change the package version too.  I did not attempt to change the version without the name to see if it was one and not the other.

**Comment by Ibochkarev** [comment]
The problem is not related to the MODX, but is related to the addition. 
The solution is found in the comment above. 
Сan be closed!
