### ISSUE TITLE
Error Update from 2.6.5 to 2.7: Could not set the locale. Please check if the locale fr exists on your system

### ISSUE THREAD

**Issue by cjac-itafran** [modxcms/revolution#14601]
## Bug report

After Updating to 2.7 we had a "Could not set the locale. Please check if the locale fr exists on your system" error.

But on the sytem we have the right locale wich is "fr_FR.UTF-8".

### Environment
MODX version 2.7

**Comment by cjac-itafran** [comment]
We found a Solution:

The error says "Error:/var/www/html/core/model/modx/modx.class.php at line 2506" wich is due to locale found by getOption not existing on the system

So in order to acces the manager you can:
Comment the code in /var/www/html/core/model/modx/modx.class.php (the whole if instruction)

we can now access the manager. 
So we started searching for were the getOption fonction found the wrong locale set as "fr"

An it happen to search it in system settings 
on the locale key wich was set to "fr" instead of "fr_FR.UTF-8".

In order to solve the problem you can either set it to the right locale "fr_FR.UTF-8" here 
or
Remove the value wich will  set it to the default of your system

After doing that you can uncomment the code it now work as usual

**Comment by Mark-H** [comment]
Are you suggesting that the manager does not work when the locale is not found? If I'm reading the code right, that should just trigger a message in your MODX error log, and not do anything else.

**Comment by cjac-itafran** [comment]
You are right the log_target was set to HTML thats probaly why the manager did not work
> 
> 
> Are you suggesting that the manager does not work when the locale is not found? If I'm reading the code right, that should just trigger a message in your MODX error log, and not do anything else.
