### ISSUE TITLE
MediaBrowser allowedFileTypes is empty

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#14604]
### Summary
When having a mediasource and setting the allowedFileTypes to `jpg,jpeg,png,gif,psd,ico,bmp,svg,doc,docx,pdf,vcf`. I still see files which should be hidden. While debugging I found out that the allowedFileTypes property in the processor is empty:

```
action: browser/directory/getfiles
prependPath: 
prependUrl: 
source: 3
allowedFileTypes: 
wctx: web
dir: 
```

So I did a console.log inside **modx.browser.js** on line 39: 
```
console.log(config);

Which outputs:
{xtype: "modx-browser-view", onSelect: {…}, source: "3", allowedFileTypes: "", wctx: "web", …}
allowedFileTypes: ""
baseParams: {action: "browser/directory/getfiles", prependPath: null, prependUrl: null, source: "3", allowedFileTypes: "", …}
closeAction: "hide"
........
```

### Step to reproduce
1. Set the allowedFileTypes property of a mediasource to: `jpg,jpeg,png,gif,psd,ico,bmp,svg,doc,docx,pdf,vcf`
2. Add for example a .gitignore file into one of the directories of the source
3. Now you see that the .gitignore file is still visible

### Observed behavior
I still see the .gitignore files and other files which are not included in the allowedFileTypes property of the mediasource. And I also noticed that the property is an empty string in the config in ExtJS, while that should contain the same value as configured in the media source.

### Expected behavior
I expected the .gitignore files to not be visible anymore and also the allowedFileTypes ExtJS property to have the same value as configured in the media source.

### Environment
MODX 3

**Comment by sdrenth** [comment]
Also see this screenshot which calls the getlist processor:

![Screenshot 2019-08-06 at 14 11 53](https://user-images.githubusercontent.com/7802465/62538910-38219780-b854-11e9-96a3-4456fe0905c9.png)

**Comment by JoshuaLuckers** [comment]
After reproducing this issue I noticed that the file tree handles this correctly but the Media Browser doesn't.

**Comment by JoshuaLuckers** [comment]
The PR to resolve this this issue has been merged, therefore I'm closing this issue.
