### ISSUE TITLE
The problem displaying preview in media Manager

### ISSUE THREAD

**Issue by alexsoin** [modxcms/revolution#14621]
### Summary
The problem displaying preview in media Manager.

### Step to reproduce
Go to media Manager and upload image.

### Observed behavior
![The problem displaying preview in media Manager](https://user-images.githubusercontent.com/3787132/60241106-935e8280-98c3-11e9-830e-3ce64e9786ef.png)

### Expected behavior
Show preview image

### Environment
MODX 3 with the latest commit
PHP 7.2
MySQL 5.7.23

**Comment by alroniks** [comment]
The refactoring issue, the problem with a path to phpthumb processor.

**Comment by opengeek** [comment]
This was fixed in 49512d93ff1bf846123d73030ba42f85112b286d.
