### ISSUE TITLE
Empty resource tree in manager

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#14627]
### Summary
The resource tree is not showing up in the manager. I believe this is due to the big MODX 3 refactor PR that has been merged.

### Step to reproduce
- Clean install of MODX 3
- Open resource tree

### Observed behavior
I only see the trash can icon, resource tree is not showing.
![Screenshot 2019-06-28 at 15 04 03](https://user-images.githubusercontent.com/7802465/60344151-27a91200-99b6-11e9-8433-76e499717a61.png)

### Expected behavior
I expect to see the resource tree.

### Environment
MODX 3

**Comment by JoshuaLuckers** [comment]
Are there any error in the error log and/or console of your webbrowser?

**Comment by sdrenth** [comment]
@JoshuaLuckers There is nothing to find in the console or XHR requests in my browser, the server log also doesn't contain any error messages. The MODX error log contains these messages:
```
(ERROR @ /core/vendor/simplepie/simplepie/library/SimplePie.php : 1474) User warning: /Users/sander/Development/projects/vhosts/modx/webroot/core/cache/rss/ is not writable. Make sure you've set the correct relative or absolute path, and that the location is server-writable.
(ERROR in xPDO\xPDO::call @ /core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 759) MODX\Revolution\modX::loadClass is deprecated since version 3.0. Replace references to class modSystemSetting with MODX\Revolution\modSystemSetting to take advantage of PSR-4 autoloading.
(ERROR in xPDO\Om\xPDOObject::load @ /core/vendor/xpdo/xpdo/src/xPDO/Om/xPDOObject.php : 399) MODX\Revolution\modX::loadClass is deprecated since version 3.0. Replace references to class modSystemSetting with MODX\Revolution\modSystemSetting to take advantage of PSR-4 autoloading.

```

**Comment by guelu63** [comment]
It happens to me exactly the same

**Comment by JoshuaLuckers** [comment]
How did you install MODX3, via Git?

**Comment by Ibochkarev** [comment]
I have a fresh installation with the latest https://github.com/modxcms/revolution/commit/d374dbd071648c4ad2b359cd6c8172ae8bfeeb7f. The error is not reproduced

**Comment by OptimusCrime** [comment]
@modxbot close
