### ISSUE TITLE
Plus sign for quick create is shown in managing resource groups

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#14630]
### Summary
Since #13774 the plus sign for quick create is visible in managing resource groups.

### Step to reproduce
Visit manager/?a=security/resourcegroup and hover a resource entry on the right.

### Observed behavior
A plus sign will occur on the right with no functionality.

### Expected behavior
No plus sign should be shown.

### Environment
#13774

**Comment by smg6511** [comment]
I'm about to submit a PR to solve the immediate problem (for 2.x). From what I see, the problem does not exist for 3.x (referring to the most current alpha 3). The reason I'm commenting before the PR is I'd like to suggest some other tweaks to improve the UI a bit; these same tweaks would be proposed for 3.x as well. See the following mockup:

<img width="706" alt="Resource Groups Panel Design Tweak" src="https://user-images.githubusercontent.com/689075/136712938-e3f52ca8-a0bb-4dc6-8aa7-68ebd592e6ed.png">

**Comment by smg6511** [comment]
@opengeek @Jako @alroniks - Just FYI, I don't think you need this issue in the 3.x milestone as the problem does not exist in 3.x.

**Comment by Jako** [comment]
I have moved this to 2.x, because this is not valid for 3.x.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/15833
