### ISSUE TITLE
Test connection and test collation buttons error on setup

### ISSUE THREAD

**Issue by guelu63** [modxcms/revolution#14632]
The $ _lang ['btn_test'] entry in setup/lang/en/default.inc.php is missing in other langs, causing a no-text buttons during setup.

**Comment by alroniks** [comment]
Thank you for your impact.

It is awaited behaviour as translations usually come from [Crowdin](https://crowdin.com/project/modx-revolution) service before release.

So I am closing it as it's not a real bug.
