### ISSUE TITLE
Exporting "Load, List and View" Access Policie doesn't work

### ISSUE THREAD

**Issue by theuros** [modxcms/revolution#14637]
### Summary
Exporting "Load, List and View" Access Policie doesn't work. 

### Step to reproduce
Just right click on template and export it

### Observed behavior
Exporting return an error: ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

### Expected behavior
Exporting an XML file of the policie

### Environment
Modx 2.7.1 on Modx cloud and some other server.

**Comment by alroniks** [comment]
Works fine in 2.x and 3.x
