### ISSUE TITLE
modWebLink Bug

### ISSUE THREAD

**Issue by wax100** [modxcms/revolution#14636]
### Summary
When creating a modWebLink  and fill content field, after saving and reloading page U get empt content field.
But if U create resource with fast creating - modWebLink  redirect works.

### Step to reproduce
Create resource with modWebLink  class. Fill content field. Save resource. Reload page

### Expected behavior
Should save content and redirect to URL \ resource that is in content field

### Environment
MODX3 version

**Comment by wax100** [comment]
[https://www.youtube.com/watch?v=6uKeBie81sQ](url) Video for better understanding

**Comment by alroniks** [comment]
I can not reproduce it. One case only when it possible, if to start creating usual resource and after change type to the weblink, then yes, the content field will be changed by another, but it is expected. In case, when I selected create weblink from context menu, fill the content field and save it, it works as expected.

I am closing it, but feel free to reopen it.
