### ISSUE TITLE
Improve mediabrowser handling for existing files

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#14641]
### Summary
The mediabrowser handling can be improved when an image is uploaded which already exists. 

### Why is it needed?
This will improve user experience when uploading files which already exists.

### Suggested solution(s)
The best solution would be to ask the user what action to take when a file with the same name exists:

- Cancel the upload
- Overwrite the old file
- Keep both and generate a unique name for this file

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/14566
https://github.com/modxcms/revolution/issues/8371

**Comment by Ibochkarev** [comment]
@sdrenth Thanks

Added #15232 
@modxbot close
