### ISSUE TITLE
MODX 3: database table type

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#14649]
### Summary
If installing MODX 2.7.1 database table type is InnoDB, but if installing MODX 3 database table type is MyISAM.

### Step to reproduce
Install MODX 3 with composer

### Expected behavior
database table type is InnoDB

### Environment
MODX 3  installation with composer
php7.3
MySQL server version 5.7.21-20
MySQL client version 5.0.12-20150407

**Comment by muzzwood** [comment]
Can confirm this.

**Comment by Ibochkarev** [comment]
@meshkov I installed a clean install using the command: `composer create-project modx/revolution www 3.x-dev`

As a result, I have everything in the database

![изображение](https://user-images.githubusercontent.com/2138260/111132642-cd921b00-85a3-11eb-97bc-8c86edc2853c.png)

**Comment by Ibochkarev** [comment]
Thank you for contacting us. This problem was fixed earlier.
