### ISSUE TITLE
Move the translit component settings from core

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14640]
### Summary
In the current version, the "translit" component is often used for translating url, but the component is activated in the "System settings", which is not logical.

It seems to me that the settings should be transferred to the settings of the "translit" component.

In the future, this will allow extending the functionality of the component, for example, adding file transliteration, but without requiring changes in the core.

As I see, **in MODX 3 it would be great to have the functionality of adding basic components during installation**, for example, the same "translit" or "Deleted Resource Manager" and others.
And these basic components in the future can also be updated, deleted, etc.

**Comment by Mark-H** [comment]
The idea of the translit settings is that core knows how / what to initialize, while an extra can provide the actual implementation. Seems fine to me?

**Comment by Ruslan-Aleev** [comment]
@Mark-H sorry, but I did not understand your comment :) Can you explain more specifically?

**Comment by Ruslan-Aleev** [comment]
I, as a user, are confused by the fact that "translit" is part of the core, which was taken out in a separate component, while the settings remained inside the core. Or I do not understand this correctly?

**Comment by Mark-H** [comment]
The idea is that the core needs to knows **what translit class to load** (hence translit settings are in the core, and not the extra), but the core **does not need to know how that transliteration works**; any extra can provide that implementation. 

The `translit` extra is probably the primary/only extra that does that now, but it would be really easy to do a `russiantranslit` or `bettertranslit` or `translitX` that handles transliteration in a different, potentially better, way, without needing to update the core. 

(Kind of like interfaces in php, if you're familiar with that concept.)
