### ISSUE TITLE
Send site administrator about the update of MODX and components

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14648]
### Summary
The recent massive hack of MODX made it clear that the site administrator should quickly and widely notified about the new version of CMS.

I think it would be useful to send an email to the administrator about MODX and components updates, especially this practice is standard for other CMS.

It is worth adding a system setting for this, with options such as:
- Send notification of a new version of MODX and components
- Send notification of a new version of MODX
- Send notification of new versions of components
- Do not send update notifications

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/14007
https://github.com/modxcms/revolution/issues/6092

**Comment by ghost** [comment]
Aren't there mailing lists that can be subscribed to? I know I'm subscribed to a security list, and get emails whenever there's a security-related issue.

**Comment by Ruslan-Aleev** [comment]
In my opinion, just knowing about security issues is not enough. It is more important to know which site has these issues, especially if you have a lot of sites. And with an email letter, it will be more difficult to forget about any website :)
Also be aware of the update CMS will be useful for a simple user or site manager (not the admin).

**Comment by ghost** [comment]
You mean something like https://sitedash.app/

**Comment by alroniks** [comment]
We are speaking about notification which comes from outside, then we already have different monitoring tools for it, like SiteDash. I am closing it as won't fix, just because it is not direct MODX responsibility.
