### ISSUE TITLE
MODX 3: Setup Installation summary error field color

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#14654]
### Summary
if there are errors, then the color of error fields is gray instead of red
![2019-08-01_11-03-09](https://user-images.githubusercontent.com/1703670/62280594-ed1f1300-b454-11e9-92e6-e6663639aa7c.png)

### Step to reproduce
during installation, change permissions on some folder
`chmod 000 connectors`

### Expected behavior
should be red like this:
![2019-08-01_12-01-40](https://user-images.githubusercontent.com/1703670/62280693-1a6bc100-b455-11e9-8a21-f47fb85b4158.png)

### Environment
MODX 3 installation with composer

**Comment by Ibochkarev** [comment]
I will fix it this week.

**Comment by Mark-H** [comment]
I don't think you've worked on this yet, right @Ibochkarev?

**Comment by Mark-H** [comment]
PR sent: #14708

**Comment by Ibochkarev** [comment]
Fixed #14708 @modxbot close

**Comment by meshkov** [comment]
I try with MODX 3 with last comment installation with composer and it not fix:
![image](https://user-images.githubusercontent.com/1703670/66909581-ad100b00-f015-11e9-837a-ff90fbad1ef1.png)

**Comment by Jako** [comment]
Sorry, thats a different issue.

**Comment by Ruslan-Aleev** [comment]
@meshkov I fixed it in PR - https://github.com/modxcms/revolution/pull/14785, try to test.
Perhaps then this PR will be introduced with minor changes.
