### ISSUE TITLE
Manager Form Customization and values comma separeted in constraint field.

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [modxcms/revolution#14651]
### Summary
In modx there is such a nice thing like manager form customization. Today I decided to create a rule and specify several identifiers in the value of constraint, separated by commas. I created a rule for updating the resource, and set to that rule remove the `modx-resource-content` field and my TV. The rule worked for both resources, but only for the `modx-resource-content` field, for TV the rule worked only for the first identifier.

### Step to reproduce
1. Create a rule.
2. Set for constraint value like ID's = 8,9,10,11 and etc.
3. Remove `modx-resource-content` field and some custom TV for example

### Observed behavior
TV disappears only at the first resource in the list, at the same time, `modx-resource-content` field in both resources.

### Expected behavior
Both `modx-resource-content` & TV must dissapear, like `modx-resource-content` that did.

### Environment
MODX 2.7.1

I hope quite clearly stated the problem

**Comment by OlegShchavelev** [comment]
Great idea. I propose to implement the ability to set for constraint value with the ability to specify the operator "not equal"

For instance.

modResource.parent != 21

It will be useful when you need to hide TV in one template in all resources except documents with parent ID 21. Please consider this a supplement, not an alternative.

**Comment by OlegShchavelev** [comment]
I propose to discuss a similar case if we create two rules.

![изображение](https://user-images.githubusercontent.com/20732384/95257947-b9483600-082d-11eb-85a6-f34e46290de5.png)


**First rule.**

Create a rule.

Action: Create & Update Resource
Template: set Catalog

![изображение](https://user-images.githubusercontent.com/20732384/95258014-d1b85080-082d-11eb-9c42-5ce615bcc7ef.png)

Go to the Template Variables tab

![изображение](https://user-images.githubusercontent.com/20732384/95258091-eeed1f00-082d-11eb-9fb8-325009dbfa67.png)

tv_catalog_series_boolean turn off сheckbox visible

**Create the second rule**

Action: Create & Update Resource
Template: set Catalog

Set for constraint value like parent's ID 21

![изображение](https://user-images.githubusercontent.com/20732384/95258723-d92c2980-082e-11eb-9dc2-f1830a20f2bd.png)


tv_catalog_series_boolean turn on сheckbox visible

![изображение](https://user-images.githubusercontent.com/20732384/95258588-b13cc600-082e-11eb-8161-10f0ce6ffa82.png)


Expected Result. TV is displayed in documents parent ID 21. But the field is not displayed in resources.
