### ISSUE TITLE
Different panel templates in the manager panel

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14663]
### Summary
MODX has different panel design templates for some sections of the manager panel: some with a top tab, some without (see screen below). And because of the different templates, the styles are not correct displayed.

We need to add a tab to all panels so that the styles display correctly and make it easier to edit style in the future.

![template_panel](https://user-images.githubusercontent.com/12523676/62826171-e10b2200-bbc7-11e9-8029-6f83b136e1e5.png)

---

This is not difficult, for example, **for the "Namespaces" section (/manager/assets/modext/workspace/namespace/modx.namespace.panel.js) need change**:

```
...

,items: [{
    html: _('namespaces')
    ,id: 'modx-namespaces-header'
    ,xtype: 'modx-header'
},{
    layout: 'form'
    ,items: [{
        html: '<p>'+_('namespaces_desc')+'</p>'
        ,xtype: 'modx-description'
    },{
        xtype: 'modx-grid-namespace'
		,cls:'main-wrapper'
        ,preventRender: true
    }]
}]

...
```

to:

```
...

,items: [{
    html: _('namespaces')
    ,id: 'modx-namespaces-header'
    ,xtype: 'modx-header'
},MODx.getPageStructure([{
    title: _('namespaces')
    ,layout: 'form'
    ,items: [{
        html: '<p>'+_('namespaces_desc')+'</p>'
        ,xtype: 'modx-description'
    },{
        xtype: 'modx-grid-namespace'
        ,cls:'main-wrapper'
        ,preventRender: true
    }]
}])]

...
```

### Environment
MODX 2.7>

**Comment by Mark-H** [comment]
Fixed in #14695
