### ISSUE TITLE
The rss folder during installation is not created

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14669]
### Summary
The `rss` folder during installation is not created along the path `core/cache/rss/`

### Step to reproduce
Go to Error Log

### Observed behavior

`[2019-08-13 07:48:20] (ERROR @ /home/s19424/www/core/vendor/simplepie/simplepie/library/SimplePie.php : 1474) User warning: /home/s19424/www/core/cache/rss/ is not writable. Make sure you've set the correct relative or absolute path, and that the location is server-writable.
`

### Expected behavior
The folder must be created during installation

### Environment
MODX 3 with the latest commit

**Comment by Mark-H** [comment]
Fixed in #14682
