### ISSUE TITLE
Remove references to old core actions

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14667]
### Summary
In MODX 3.x `modConfigJsProcessor`/ `ConfigJs` doesn't load actions for backwards compatibility. 

This line of code is removed in `ConfigJs` (the processor responsible to  output $modx->config to JSON).

```
// Load actions for backwards compatibility (DEPRECATED)
$actions = $this->modx->request->getAllActionIDs();
$o .= 'MODx.action = ' . $this->modx->toJSON($actions) . ';';
```

### Step to reproduce
1. Checkout the 3.x branch with all recent changes.
2. Drag and drop a resource in the tree
3. Open the developer console

### Observed behavior
An error appears: `TypeError: undefined is not an object (evaluating 'MODx.action['resource/update']')`

### Expected behavior
No error. 

### Environment
MODX 3

**Comment by Mark-H** [comment]
Considering actions have been deprecated since 2.2 I'm okay with that... though that will cause breakage in extras.

**Comment by JoshuaLuckers** [comment]
> Considering actions have been deprecated since 2.2 I'm okay with that... though that will cause breakage in extras.

I'm not sure who removed it from the code. We can always reconsider the removal and put it back if to many (unmaintained) extra's break that are being used "heavily".

**Comment by JoshuaLuckers** [comment]
Or create a “compatibility mode” extra!

**Comment by JoshuaLuckers** [comment]
It has been "agreed" on to add back support for the deprecated actions and remove support in a future versions.
