### ISSUE TITLE
Static template file not updated (/sync) when changed though a clear cache is done

### ISSUE THREAD

**Issue by intersel** [modxcms/revolution#14674]
### Summary
When a template is static, if the static file of the template is changed with an external editor, then we do a clear cache, there is no sync of the template, changes are not taken into account...

### Step to reproduce
1. create a template with a static file
2. create a resource using the template
3. change and save the static template file with an editor outside modx
4. clear cache in the manager (or remove the core/cache content)
5. view the resource

### Observed behavior
Nothing has changed or was updated... the resource parsed with the old template.

### Expected behavior
The view is updated according to the changes made in the template static file

To have the template updated, it is needed to go to the manager and edit the template... that reloads the static file and seems to sync at that moment. 
then save template or clear cache...
Perhaps is there a simpler way to have the template updated in modx from its static file?

### Environment
MODX 2.7.1, apache 2.4.25 (Debian 9.8),  10.1.38-MariaDB-0+deb9u1, firefox/chrome

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. Unfortunately I'm unable to reproduce this bug. 

What is the Media Source for the template?

**Comment by intersel** [comment]
args... so it sounds to be a environment problem... but what... I've got no pb with static chunks or snippets...

To answer your question:

media source is set to "Filesystem"
static file name is like core/components/website/templates/page/page-section/category/myfile.template.html

I've just done a new test with another template with static file and it's working fine with it :-s
I have to go deeper in my analyse... as I've got one wrong and the other ok :(

The difference is that the one that does not work is parsed through the API... I mean I get the content of the template through the API 

`
$template = $modx->getObject('modTemplate',$tempId);
$output = $template->get('content');
`

**Comment by JoshuaLuckers** [comment]
> The difference is that the one that does not work is parsed through the API... I mean I get the content of the template through the API
> 
> `$template = $modx->getObject('modTemplate',$tempId); $output = $template->get('content');`

This will fetch the template from the database (not from the file). I believe `$template->getContent()` will get the unparsed content from the static file.

**Comment by intersel** [comment]
great! and that's make perfect sense...
Thanks for your expertise... that's working now :)
