### ISSUE TITLE
MODX3: When saving a document, the form for creating a new document opens

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14670]
### Summary
When creating and saving a document instead of continuing editing the current document, a form for creating a new document opens.

### Expected behavior
Continue editing the current document.

![doc_new](https://user-images.githubusercontent.com/12523676/62932858-01a6c800-bdd2-11e9-8dd2-628023374bee.gif)

### Environment
MODX3

**Comment by ghost** [comment]
Are there settings for this behavior? A long time ago there were options and settings to select the behavior or to set a default.

**Comment by Ruslan-Aleev** [comment]
I did not find such a setting

**Comment by JoshuaLuckers** [comment]
Did you test this on the 3.x branch or with the changes from PR #14662?

**Comment by Ruslan-Aleev** [comment]
I looked in the version of MODX3 with @bezumkin  edits (in my opinion, the essence is the same)

**Comment by Ibochkarev** [comment]
Confirmed, #14662 does not fix this bug

**Comment by JoshuaLuckers** [comment]
Maybe it’s related to https://github.com/modxcms/revolution/issues/14667 

I will check it tomorrow

**Comment by JoshuaLuckers** [comment]
It's not related, ~I'm not sure yet what's causing this issue~.

**Comment by Ibochkarev** [comment]
Fixed in #14676 
@modxbot close
