### ISSUE TITLE
Need a lexicon refactor in Crowdin

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14673]
### Summary
I often notice that translations come to the final version of MODX, it is not clear by what logic.

1) In my opinion, if the translation is approved, for example, in the version of the file for MODX 2.5, but for 2.7 it is not approved, then version 2.7 will receive the translation from version 2.5 (but I'm not sure about that).

2) It seems that translations are inherited from the old version to the new one and, if necessary, they can be redefined in the new version, **but this is not so**.

For example, if we open the file “setting.inc.php” and search by the key “settings_desc”, we see that for version 2.5 the translation will be taken from version 2.3, if the translation is not specified and the line will be grayed out (and the pop-up message will say that translation is not required).

![crowdin_1](https://user-images.githubusercontent.com/12523676/62949460-43963500-bdf7-11e9-9bcc-69e9021d12ed.gif)

However, for version 2.7, the translation for the same line is not taken from the previous branch, but for some reason is separate. And if you delete the line, then there will be an empty line.
And for version 3, the translation is taken from 2.7.

Those. it turns out that for some reason 2 separate and independent translation lines appeared.

![crowdin_2](https://user-images.githubusercontent.com/12523676/62949467-498c1600-bdf7-11e9-8e07-545e05279803.png)

Together with paragraph 1, the translation is difficult to edit, and it is not clear what will go to MODX in the end.

**It seems to me that we need to leave one final translation, without branches, which is easier to edit.**

### Environment
Crowdin

**Comment by JoshuaLuckers** [comment]
cc @theboxer

**Comment by JoshuaLuckers** [comment]
Improvements have been made:

> We do need to make sure not to put things in the sources that are not strings to be translated
> The sources are `core/lexicon/en/`, `setup/lang/en/` and `core/lexicon/country/en.inc.php`
