### ISSUE TITLE
MODX 3 Field selection error

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#14675]
### Summary
![2019-08-15_11-21-56](https://user-images.githubusercontent.com/1703670/63082615-591e7280-bf4f-11e9-8da7-13faa927ddbb.png)

### Step to reproduce
1. Go to Package Management
2. Select a Provider
3. Try to Save without select Provider

### Expected behavior
I think it should be like in bootstrap 4:
![image](https://user-images.githubusercontent.com/1703670/63082578-3e4bfe00-bf4f-11e9-9955-81c5609a1c10.png)

### Environment
MODX 3  with last comment installation with composer

**Comment by Mark-H** [comment]
Just to make sure I understand, what you're suggesting is that it should show a message along with the invalid error state border?
