### ISSUE TITLE
No translated lexicon for some languages

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14672]
### Summary
Apparently, after a recent lexicon update with Crowdin, some lines for some languages disappeared (became in English), see screenshots.

Sections:
"Refresh URLs"
Items in "Reports"

Perhaps in other elements of the manager panel.

**AR:**
![ar](https://user-images.githubusercontent.com/12523676/62938335-ed69c780-bddf-11e9-8ee3-60bfd4ea2f0f.png)

**RU:**
![ru](https://user-images.githubusercontent.com/12523676/62938336-ed69c780-bddf-11e9-9643-7340bbdcb50e.png)

**Most likely in other languages (in Belorussian for sure)**

### Environment
MODX 2.x

**Comment by JoshuaLuckers** [comment]
They have to be changed in Crowdin.

**Comment by Ruslan-Aleev** [comment]
For some reason, in Crowdin, this file was completely cleared.

![topmenu_inc_error](https://user-images.githubusercontent.com/12523676/62945259-776d5c80-bdef-11e9-9ff6-2154db858011.png)

**Comment by Ruslan-Aleev** [comment]
@opengeek There is some information and thoughts why the file **topmenu.inc.php** was cleared and how to restore it?

**Comment by opengeek** [comment]
Not a clue. Nothing has been done to it other than the usual process which includes sources being uploaded from the English files (any changes there would clear related translations) and a build done in CrowdIn and pulled down.

**Comment by Ruslan-Aleev** [comment]
@opengeek Can you restore the file?

**Comment by opengeek** [comment]
Not until we know why it has been cleared in CrowdIn or the same thing will just happen again.

**Comment by Ruslan-Aleev** [comment]
Some thoughts about Crowdin https://github.com/modxcms/revolution/issues/14673

**Comment by opengeek** [comment]
Thanks to @theboxer , we have determined why these files were losing translations. It appears translators have been escaping single-quotes in the translations on CrowdIn which makes the file invalid. So when it is synced with CrowdIn, it resets the entire file. I am manually searching and replacing any instances of `\\` in the lexicons now and will re-upload those specific files to try and correct the issue.

**Comment by Mark-H** [comment]
I believe the CrowdIn implementation was fixed and this should be better now.
