### ISSUE TITLE
MODX 3 Visual errors with styles

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14686]
### Summary
- [ ] 1) In the TV, the "Set to default" button is located strangely.
![tv](https://user-images.githubusercontent.com/12523676/63338282-928e1e00-c353-11e9-9a9b-c8928172414b.png)

- [ ] 2) Text is not aligned in height
![valign](https://user-images.githubusercontent.com/12523676/73382208-8c2ba700-42e0-11ea-8673-263e2b8fe108.png)

- [ ] 3) The font in the package installer does not look very nice.
![fonts](https://user-images.githubusercontent.com/12523676/63339494-0e896580-c356-11e9-8dc8-cadb3ed78783.png)

- [ ] 4) In my opinion, red is not the best choice for uninstalled packages.
![package-color](https://user-images.githubusercontent.com/12523676/73382315-b3827400-42e0-11ea-9239-a485df6055b7.png)

- [ ] 5) No padding on top, it looks weird
![padding-top](https://user-images.githubusercontent.com/12523676/73392295-f1889380-42f2-11ea-9002-eea01c7ccaf9.png)

- [ ] 6) some inaccuracies in the tree
![tree_1](https://user-images.githubusercontent.com/12523676/73612110-08d0c500-4602-11ea-8d3c-1bf67ee790f0.png)

![tree_2](https://user-images.githubusercontent.com/12523676/73612111-08d0c500-4602-11ea-8b65-6c1fd8adca5a.png)

### Environment
MODX 3

**Comment by meshkov** [comment]
I think it can be added here:
Go to Files and open Filesystem 

![image](https://user-images.githubusercontent.com/1703670/64236536-41f5f380-cf03-11e9-8377-aa12c58c04c4.png)

**Comment by Ruslan-Aleev** [comment]
https://github.com/modxcms/revolution/issues/14597

**Comment by Ruslan-Aleev** [comment]
https://github.com/modxcms/revolution/issues/14375

**Comment by Ruslan-Aleev** [comment]
![tree_buttons](https://user-images.githubusercontent.com/12523676/66674194-5f8d4a00-ec73-11e9-952a-0fb8e441e911.png)

**Comment by Ruslan-Aleev** [comment]
Text is not centered on the buttons in height:

![bh](https://user-images.githubusercontent.com/12523676/69011930-5fc2e880-0989-11ea-9523-2187ff69a3aa.png)

**Comment by Ruslan-Aleev** [comment]
In my opinion, red is not the best choice for uninstalled packages.

![package-un](https://user-images.githubusercontent.com/12523676/69011979-e24ba800-0989-11ea-8266-81a6848f4259.png)

In the manger panel, the red color is responsible for displaying errors, but here there are no errors.

**Comment by Ruslan-Aleev** [comment]
https://github.com/modxcms/revolution/issues/14828

**Comment by JoshuaLuckers** [comment]
> In my opinion, red is not the best choice for uninstalled packages.
> 
> ![package-un](https://user-images.githubusercontent.com/12523676/69011979-e24ba800-0989-11ea-8266-81a6848f4259.png)
> 
> In the manger panel, the red color is responsible for displaying errors, but here there are no errors.

I agree, red is not the best choice. It would be good to align it with how we display the status of a resource. For packages/extras that are not installed: 
- Row/text lighter then installed packages
- Package name in italic

**Comment by Ruslan-Aleev** [comment]
>  It would be good to align it with how we display the status of a resource.

Yes, it would be useful. Although there was discussion about the status of resources, but the discussion has not yet reached a concrete conclusion - https://github.com/modxcms/revolution/issues/13969.

**Comment by Ruslan-Aleev** [comment]
https://github.com/modxcms/revolution/issues/14006#issuecomment-533638017
