### ISSUE TITLE
Is cacheManager->generateResource work correct? It does not cache TVs...

### ISSUE THREAD

**Issue by iWatchYouFromAfar** [modxcms/revolution#14718]
### Summary
I'm trying to create a resource cache through a script, for this I use:
`cacheManager->generateResource`

### Step to reproduce
Just execute this simple code:
```php
$q = $modx->newQuery('modResource');
$q->sortby('id');
$q->where(array(
    'published' => true,
    'deleted' => false,
    'cacheable' => true,
    'searchable' => true,
    'class_key' => 'modDocument',
));
$q->limit(100);
$resources = $modx->getCollection('modResource', $q);
$modx->getCacheManager();
foreach ($resources as $page) {
    $page->process();
    $page->_contextKey = $page->get('context_key');
    $modx->cacheManager->generateResource($page);
}
```

### Observed behavior
You get a resources cache without TVs.

### Expected behavior
I expect to get a full cached resource with TVs.

### Environment
MODX 2.7.1
PHP 7.2

**Comment by Mark-H** [comment]
I don't think that method was meant to be used outside of the regular resource rendering flow. It relies on the in-memory element and source cache, as well as registered scripts, so is *not* a completely self-contained way of generating the resource cache. 

While that means the bug report is technically correct, calling it like you're doing now results in an incomplete cache, I don't think it's something we necessarily have to fix.
