### ISSUE TITLE
MODX3: The country name in the user section is not always displayed

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14732]
### Summary
Sometimes the name of the country is not loaded, for what reason this happens - it is not clear. The consoles are silent.

On the gif, I just refresh the page:

![country](https://user-images.githubusercontent.com/12523676/64611519-aec92c00-d3e2-11e9-95f9-d11688f14bee.gif)

The bug is found in both https://github.com/modxcms/revolution/pull/14731 and https://github.com/modxcms/revolution/pull/14420

And in my opinion, this bug **has always been.**

This is how it looks in .js - https://github.com/modxcms/revolution/pull/14731/files#diff-28553f69fb263eee4808c9f7d481ef28R255

### Environment
MODX 3
Windows 7
Google Chrome 76.0.3809.132, (64)

**Comment by Jako** [comment]
Is this the normal MODX combo? If yes, there has to be an empty or late response of the connector. Please look for XHR requests with an `system/country/getlist` action.

The processor is called, when the combo is displayed and when the combo is opened. When the combo is displayed, it is called with an 'iso' request property, that should filter the result to the selected country. The processor does not cover this case and creates a response with all countries everytime. So the patch has to go in manager/assets/modext/widgets/core/modx.combo.js

**Comment by Jako** [comment]
Do you see the flickering value just before the blank value occurs? It shows `At`, but the keys i.e. in core/lexicon/country/en.inc.php are lowercase. Is that user created in MODX? How did you get the `At` value in that field?

**Comment by Ruslan-Aleev** [comment]
This is pure MODX3 and the administrator that is created during installation, I did not make any additional changes. **For the appearance of this bug, I just refresh the page several times and that's it**.

**Comment by Ruslan-Aleev** [comment]
By the way, I described this behavior in february - https://github.com/modxcms/revolution/pull/14420#issuecomment-466306163
What a strange bug :)

**Comment by Jako** [comment]
Could you look for the database values in the user country? Are they uppercase or titlecase? If not, are they transformed during the Ajax Request?

**Comment by Ruslan-Aleev** [comment]
The value with uppercase is written to the database (lexicon files have an ISO code in lowercase)

![country_db](https://user-images.githubusercontent.com/12523676/64657763-064cb380-d446-11e9-872c-703e120af229.png)

As I understand it, this line is responsible for this https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/Processors/System/Country/GetList.php#L39

**Comment by Jako** [comment]
Ok, thats fine. But in the other example there was a `At` instead of `AT`, if I remember right.

But I think this is not the issue. It should be caused by the listener that sets the values for the form. At the moment it runs at 'setup' but that could be too early. Maybe that could be switched to   'afterlayout' or whatever there is available.

**Comment by Ruslan-Aleev** [comment]
In my opinion, the value in the field is always displayed with capital letters, I don’t remember, for example, `At` instead of `AT`. And in the examples, it seems, this does not happen.

**Comment by JoshuaLuckers** [comment]
I'm unable to reproduce this issue. 
Can you provide these additional details:

- Browser version
- Did you test other browsers?
- Is it a clean install of MODX?
- It happens sometimes, what steps did you do before it happens?

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers Here are the details:
- OS - Windows 7
- Browsers - Google Chrome 76.0.3809.132, (64), Firefox 68.0.1 (64)
- Yes, clean install through the console
- This sometimes happens when the page reloads (in Firefox, by the way, more often than in Google Chrome)
Nothing is displayed in consoles.

**Comment by travisbotello** [comment]
I can reproduce this issue 1:1 with MODX 2.7.3 in Chrome 85.0.4183.102 (64-Bit) on MacOS 10.15.6. Seems to also apply to 2.X branch.

Can't reproduce this in Firefox or Safari. This only applies in Chrome.

**Comment by Ibochkarev** [comment]
Fixed #15413
