### ISSUE TITLE
Change behavior of "duplicate resource".

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#14737]
### Summary
We need to be able to duplicate single resources no matter where they are in the tree. Currently, the only way to do that is right-clicking on a resource in the tree and selecting Duplicate there, which shows an option to copy children or not.

### Why is it needed?
When users want to duplicate a single resource, there is no way for them to do that using the Duplicate button if that resource has children. The Duplicate button should show the same options as using the context menu in the tree.

### Suggested solution(s)
Rather than just display the alert "Are you sure you want to duplicate this resource? Any item(s) it contains will also be duplicated.", give the option to either duplicate the children or just duplicate the single resource.

**Comment by GulomovCreative** [comment]
https://github.com/modxcms/revolution/pull/14411

Maybe I didn’t understand something?

**Comment by SnowCreative** [comment]
Sorry, should have said this has to do with the Duplicate button, not with using a context menu by right-clicking an item in the tree. I have clients who aren't that savvy and just use the Duplicate button, which doesn't display the option to not copy children. Looks like you found a related post that addresses adding this to the Duplicate button, as well as add a redirect option (good idea!).

I've updated my original description, but this could be just merged into #14411.

**Comment by GulomovCreative** [comment]
@rainbowtiger Description from my PR:

> Adds normal resource duplication dialog like duplicating via context menu in resource tree

In that PR I changed behavior of the Duplicate button too

**Comment by GulomovCreative** [comment]
![GIF](https://user-images.githubusercontent.com/20814058/65216198-52e55e00-dada-11e9-83b4-04a0dbdf5ff0.gif)

> Maybe I didn’t understand something?
