### ISSUE TITLE
MODX3: On a small screen, when open MODX browser, element tree does not disappear correctly

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14736]
### Summary
On large screens, when you open the MODX browser, the tree of elements **hides to the left**.
But on a small screen, when you open the MODX browser, the element tree **should be hiding up**. Because this does not happen, an empty area remains.

![browser](https://user-images.githubusercontent.com/12523676/64719565-8ff99100-d4d9-11e9-9b4d-a0b4db5f94b9.gif)

### Expected behavior
Element tree should be hiding up on small screen

### Environment
MODX 3
https://github.com/modxcms/revolution/pull/14735

**Comment by Ibochkarev** [comment]
Fixed #14783 
@modxbot close
