### ISSUE TITLE
3.0 Installation Issues

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#14742]
### Summary
Installation of 3.0 nightly build fails

### Step to reproduce
download nightly build, try to install

### Observed behavior
If in a subdirectory, paths are not found, there is no styling and installation cannot continue beyond the first unstyled page, all links appear to go to the site root /setup/

If in the root, installation proceeds past the first page, to an empty second page, and fails with a fatal error when trying to create the database.

``` Warning: array_merge(): Expected parameter 2 to be an array, null given in /Applications/MAMP/htdocs/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php on line 302 ```

``` Fatal error: Uncaught Error: Class '\xPDO\Om\\xPDODriver' not found in /Applications/MAMP/htdocs/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php:1890 Stack trace: #0 /Applications/MAMP/htdocs/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php(303): xPDO\xPDO->getDriver() #1 /Applications/MAMP/htdocs/setup/includes/modinstall.class.php(468): xPDO\xPDO->__construct(NULL, NULL, NULL, Array, Array) #2 /Applications/MAMP/htdocs/setup/includes/modinstall.class.php(171): modInstall->_connect(NULL, NULL, NULL, NULL, Array) #3 /Applications/MAMP/htdocs/setup/includes/test/modinstalltest.class.php(315): modInstall->getConnection() #4 /Applications/MAMP/htdocs/setup/includes/test/modinstalltest.class.php(51): modInstallTest->_checkDatabase() #5 /Applications/MAMP/htdocs/setup/includes/modinstall.class.php(247): modInstallTest->run(NULL) #6 /Applications/MAMP/htdocs/setup/controllers/summary.php(27): modInstall->test(NULL) #7 /Applications/MAMP/htdocs/setup/includes/request/modinstallrequest.class.php(80): include('/Applications/M...') #8 /Applications in /Applications/MAMP/htdocs/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php on line 1890 ```

### Expected behavior
It should install from within a subdirectory.

The 2.7.2 nightly build installs as expected.

### Environment
modx-3.0.0-dev-20190918
MAMP 5.5
Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.3.8 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.10 Perl/v5.24.0 
MySQL Server version: 5.7.26 - MySQL Community Server (GPL)
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
FF 69.0 OS/X

**Comment by ghost** [comment]
The header.tpl for 3.0 has ```<base href="/setup/">```  Any particular reason for that?

**Comment by ghost** [comment]
![Screen Shot 2019-09-24 at 13 24 26](https://user-images.githubusercontent.com/1073780/65504404-87d52480-decf-11e9-9e7d-dfe42f23c4e2.png)
After the initial Welcome page and language selection, it appears that the same page is reloaded, only empty. Clicking the Next button here proceeds to the Options page.

**Comment by ghost** [comment]
On the Options page, the three setup options are not exactly vision-impaired friendly. Simply changing the outline from grey to blue didn't catch my attention until I had examined it several times.
![Screen Shot 2019-09-24 at 13 30 11](https://user-images.githubusercontent.com/1073780/65504428-9c192180-decf-11e9-8204-79c38490a7a9.png)

**Comment by JoshuaLuckers** [comment]
I'm unable to reproduce the fatal error during setup using the nightly build.

**Comment by Ibochkarev** [comment]
Fixed #14999 
@modxbot close
