### ISSUE TITLE
Scroll screen to required TV

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14743]
### Summary
If the TVs are located under the content and they are required, then saving the resource does not seem to work, because it is not visible that you need to fill in the TV field.

![tv-r](https://user-images.githubusercontent.com/12523676/65239895-078a7a00-daf1-11e9-9dd4-15293eafcfb9.gif)

p.s. Misunderstanding often happens with customers because of this.

### Suggested solution(s)
Move the screen to the required fields.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/14235
https://github.com/modxcms/revolution/issues/11112

**Comment by Mark-H** [comment]
Fixed in 2.8
