### ISSUE TITLE
Resource setting isfolder is not set to true if you drag another resource into it

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14747]
### Summary
**Resource setting isfolder is not set to true if you drag another resource into it. But if you create a child resource, then the isfolder will become true (what's the difference?)**

There are a lot of different closed issues about this behavior, but there are no changes and the behavior is strange, as it seems to me.

![isfolder](https://user-images.githubusercontent.com/12523676/65364803-1ffbb100-dc25-11e9-84c8-6a5bf929c5c9.gif)

Probably related https://github.com/modxcms/revolution/issues/13722

### Environment
MODX 2.7.1

**Comment by JoshuaLuckers** [comment]
The PR to resolve this this issue has been merged.
