### ISSUE TITLE
Pager for context-settings is broken

### ISSUE THREAD

**Issue by unnamed1337** [modxcms/revolution#14746]
### Summary
When I open the context-settings of any context, the page-size does not match the amount of displayed items. For example the default is set to 20 and i only get 11 displayed items (of 12 items total). Changing the value doesn't make it better.

![Example](https://user-images.githubusercontent.com/33615872/65317386-08c4b100-db9c-11e9-8c90-5dd1398eceab.PNG)

### Step to reproduce
1. Edit any Context with context-settings
2. open context-settings tab
3. play around with the "Per Page"-value ;)

### Observed behavior
page-size | displayed items
:---: | :---:
4 | 2
5 | 3
6 | 3
7 | 4
8 | 5
9 | 5
10 | 6
12 | 7
15 | 8
18 | 10
19 | 11
20 | 11
21 | 12
### Expected behavior
page-size | displayed items
:---: | :---:
4 | 4
5 | 5
6 | 6
7 | 7
8 | 8
9 | 9
10 | 10
12 | 12
15 | 15
18 | 18
19 | 19
20 | 20
21 | 21

### Environment
MODX version: MODX Revolution 2.7.1-pl
apache/nginx and version: Apache 2.4.29
mysql version: mysql  Ver 14.14 Distrib 5.7.27, for Linux (x86_64) using  EditLine wrapper
browser: **Chrome** Version 77.0.3865.90 (Official Build) (32-bit), **Firefox** 69.0 (32-Bit)

**Comment by Mark-H** [comment]
Try making a list of context settings in the database and comparing that against the ones that are missing. Hopefully that will help identify a pattern - perhaps settings you don't have namespace access for are hidden?

**Comment by unnamed1337** [comment]
I get all settings, if I set the page-size high enough, which works for me as a workaround. In my case anything >= 21.
All settings are inside the core namespace and I also have full access.

Also this happens every context (currently 15) and I can't come up with any SQL query, that would give me something else than the 12 settings ;)
