### ISSUE TITLE
MODX 3 - Custom resource class packages not working.

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14759]
### Summary
(Apologies if this is already a known issue, I couldn't find it.)
Installing an extra that extends modResource appears to not currently be working.
The package installation log gives repeated errors such as:
```
Could not find legacy class CollectionSetting after converting to MODX\Revolution\CollectionSetting
```
and
```
Could not find legacy class LocationProfile after converting to MODX\Revolution\LocationProfile
```
However, the relevant db tables are still created and the installation log claims it was installed correctly. So the script does complete.

### Step to reproduce
Install an extra that uses a Custom Resource Class then attempt to change a resource type to the new custom type.
I tried this with:
- Collections
- LocationResources

### Observed behavior
Installs with errors and the custom resource type is not displayed in the "Resource Type" dropdown box on a resource create/edit form.
No errors are logged when opening the dropdown.

### Expected behavior
It should install without errors and the custom resource type should be listed along with the defaults.

### Environment
MODX 3.0-dev (latest Composer install), PHP 7.3

**Comment by theboxer** [comment]
I believe this is resolved by #14920.
