### ISSUE TITLE
MODX3: Incorrectly displayed date in the file editing form

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14750]
### Summary
The date is incorrectly displayed in the file editing form for MODX 3, although there is no such problem in MODX 2.7.

![m3](https://user-images.githubusercontent.com/12523676/65376786-2174ba00-dcb5-11e9-8163-b1205d0d31c1.png)

![m2](https://user-images.githubusercontent.com/12523676/65376785-2174ba00-dcb5-11e9-80bc-7cc73e42a8fb.png)

**It is necessary to display the date and time in accordance with the date format in the system settings.**

### Environment
MODX 3

**Comment by meshkov** [comment]
I'm still able to reproduce this issue.
Environment:
MODX 3, php7.3, ubuntu
