### ISSUE TITLE
MODX 3 - Menu items in manager missing "permissions" index

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14755]
### Summary
While viewing any page in the manager the following is logged once for each menu item that exists:
```
[2019-09-24 17:51:37] (WARN @ /home/vagrant/code/modx3/public_html/manager/controllers/default/header.php : 314) PHP notice: Undefined index: permissions
```
So although this is only being logged as a warning, I assume this means the permissions are not being set for menu items.
https://github.com/modxcms/revolution/blob/3.x/manager/controllers/default/header.php#L314

### Step to reproduce
Set logging to 2 or above then load a page in the manager.

### Environment
MODX 3.0-dev ,PHP 7.3

**Comment by theboxer** [comment]
This is caused by the language toggle under user menu...
