### ISSUE TITLE
MODX3: Expand breadcrumbs

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14769]
### Summary
In the current version, breadcrumbs, in fact, work only for child resources.

It would be useful if breadcrumbs would work for related sections.

**For example:**
Media Sources `(/manager/?a=source)` -> Media Source: Filesystem `(/manager/?a=Source/Update&id=1)`

This is relevant for Contexts, Users, Form Customization, Dashboards, Widgets and for others.

### Related issue(s)/PR(s)
None

**Comment by Ibochkarev** [comment]
@modxbot close 
Fixed #14890
