### ISSUE TITLE
Open in New Tab Context Menu Item

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#14766]
### Summary
Add "open in new tab" as an item in the context menu.

### Why is it needed?
I often need to open more than one resource or element at once while working. Currently, I accomplish this by right-clicking the MODX logo, opening in new tab, and then navigating back to the resource or element I want to open.

### Suggested solution(s)
It would save a couple steps if I could right-click on a resource or element and select "open in new tab" from the resulting context menu.

**Comment by Mark-H** [comment]
Tried using cmd/ctrl + click?

**Comment by Ruslan-Aleev** [comment]
In general, the **mouse wheel and ctrl + click** are responsible for the new tab - it all works now :)
It seems to me that the new item will be superfluous.

**Comment by Ruslan-Aleev** [comment]
Although, if we look from the other side, the context menu implies an action different from the usual one.
Those the usual action is editing an element by clicking on it.
And the action in the context menu - perhaps it should be editing in a new tab?
There is logic too :)

**Comment by ghost** [comment]
I did not know that ctrl+click opened in a new tab. I've always right-clicked. This is going to improve my whole browsing experience! lol

**Comment by Ruslan-Aleev** [comment]
> This is going to improve my whole browsing experience! lol

:) Using the mouse wheel is even easier!

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to submit this feature request. 

The requested feature is already provided by webbrowsers therefore I’m closing this issue.
