### ISSUE TITLE
Manager navbar bug when the screen width is between 681px and 980px

### ISSUE THREAD

**Issue by iLinkoDes** [modxcms/revolution#14770]
This error break the navbar, putting it in a strange position inside the manager dashboard.

![Screen Shot 2019-09-27 at 12 51 57 PM](https://user-images.githubusercontent.com/45241620/65790601-9e74b900-e125-11e9-8c3c-123f9aa326ef.png)

To reproduce this error, just rezise the window to 961px - 980px and the navbar will be broken by itself.

### Environment
MODx 2.7.1-pl, Apache 2.2.34, MySQL 5.7.23 - MySQL Community Server (GPL), PHP 7.2.10

**Comment by Ruslan-Aleev** [comment]
This, as I understand it, is due to the fact that the text does not fit in width.
What language do you use?

**Comment by Ibochkarev** [comment]
> What language do you use?

This is Spanish.
