### ISSUE TITLE
TV default value is rendered for templates without TV template access

### ISSUE THREAD

**Issue by labr1005** [modxcms/revolution#14773]
### Summary
The TV default value is rendered for templates without TV template access.

### Steps to reproduce
These steps simulate that you already have existing resources with different templates and you add a new TV with a default value that you only want to work for selected templates.

1. Create 2 templates "templateA" and "templateB" and add `[[*tvWithDefaultValue]]` to both templates. (It doesn't matter if you call the TV un/cached...)
2. Create 2 resources, 1 with "templateA" and 1 with "templateB".
3. Create a TV "tvWithDefaultValue" (eg. Input Type "Check Box", Input Option Values "Yes==1", Default Value "1") and set Template Access for "templateA".
4. View the resource with "templateB". (Don't edit/save it in the manager, go straight to the frontend output.)

### Observed behavior
The default value "1" is rendered.

### Expected behavior
The default value should not be rendered since the used template does not have TV template access.

### Environment
MODX 2.7.1 advanced, PHP 7.2.20, MySQL 5.7.26, Apache and NGINX

**Comment by Ruslan-Aleev** [comment]
I can not reproduce this bug.
However, my default value for TV is not displayed at all, even for TV, which is set for the template.
MODX 2.7.1

**Comment by Ruslan-Aleev** [comment]
And there is also an illogical behavior: if TV has a value, but then the TV was unselect from the template (but retained the value from the resource), then the value of this TV will still be displayed in the template. Although, it seems to me, it should not be displayed.

**Comment by labr1005** [comment]
You are right. My steps to reproduce were in the wrong order. This problem occurs when you already have resources with different templates in place and then add a new TV with a default value that you only want to work for selected templates. I adjusted the description.

**Comment by labr1005** [comment]
Concerning the illogical behavior: If you uncheck the checkbox and save the resource, the TV then has a value "" (it's empty, but still a value) and the default value will not be used.

**Comment by labr1005** [comment]
https://github.com/modxcms/revolution/issues/1852

Hm. I don't agree but I guess I'll close this issue then... I'll wait some more days for any comments on this.

**Comment by JoshuaLuckers** [comment]
This behavior works like intended. The actual UI and description around this behavior in the manager is wrong causing confusing and raises wrong expectations. 

The value of the input field whose label is "Default Value" is used to set the `default_text` field for the `modTemplateVar` object. 

When getting the value of a template variable for a resource it return the raw value of the template variable in context of the specified resource.
When no value is found the `default_text` for the template variable is returned.

**Comment by labr1005** [comment]
Yup, that's really confusing.

Closing this issue because it works like designed.
