### ISSUE TITLE
New right triangle in MODX menus with submenus not in a good place

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#14777]
### Summary
Position for the new triangle that appears in dropdown menus that have submenus is not in an ideal place.

### Step to reproduce
Turn off Show Descriptions in Top Menu.

### Observed behavior
Without descriptions, the triangle is now at the very bottom edge of the dropdown menu items rather than being centered vertically.

![Screen Shot 2019-10-01 at 12 56 13 PM](https://user-images.githubusercontent.com/2528374/65983152-e740b080-e44a-11e9-979c-f8a6310b8c6c.png)

### Expected behavior
People should be able to turn off the descriptions in dropdown menus and have the submenu indicator still be in a reasonable place. Currently, it's set in the CSS to appear 24 pixels from the top. 12px from the top makes it center-aligned with the menu title.

An alternative to changing this one CSS entry would be to add a class to the main menu UL (e.g., "no-descriptions") when the "topmenu_show_descriptions" system setting is set to "no", so that the current CSS entry would apply when descriptions are shown and an alternate CSS setting could be applied when there are no descriptions.

### Environment
MODX version 2.7.2.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. Merging PR (#14778) fixed this issue and therefore I'm closing this issue.
