### ISSUE TITLE
[3.x] Breaking extras with CMPs

### ISSUE THREAD

**Issue by theboxer** [modxcms/revolution#14796]
I've tested few extras (all had custom manager pages) and none of them worked out of the box.

Changes required for making them work were easy - all needed to fix processors that were extending `abstract mod*Processor` and add the namespace to the extended processor; adjust the namespace for `modExtraManagerController`. After those changed everything (usually) started to work as expected.

This might be solve with aliasing abstract classes:
- modExtraManagerController
- mod*Processor

Other class worth of aliasing might be `modResource` as its `filterPathSegment` method is commonly used.

**Comment by Mark-H** [comment]
Yeah, those should be added: https://github.com/modxcms/revolution/blob/3.x/core/include/deprecated.php
