### ISSUE TITLE
MODX3: Set Visibility on File

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#14810]
### Summary
Don`t work Set Visibility on File

### Step to reproduce
1. Go to Media Browser
2. Try to Set Visibility on File

### Environment
MODX 3 with last comment installation with composer

**Comment by JoshuaLuckers** [comment]
Some notes after a quick investigation:

The `handler` for the "Set Visibility" context menu is set to `this.setVisibility`:
https://github.com/modxcms/revolution/blob/d374dbd071648c4ad2b359cd6c8172ae8bfeeb7f/core/src/Revolution/Sources/modMediaSource.php#L2025-L2030
https://github.com/modxcms/revolution/blob/d374dbd071648c4ad2b359cd6c8172ae8bfeeb7f/core/src/Revolution/Sources/modMediaSource.php#L2103-L2108

In the file browser component `MODx.browser.View` the method `setVisibility` is missing.
https://github.com/modxcms/revolution/blob/b3c2ddc519ee332adfcda051143f88b9b567b7fc/manager/assets/modext/widgets/media/modx.browser.js#L99-L468

The method is available elsewhere, inside `MODx.tree.Tree`:
https://github.com/modxcms/revolution/blob/b3c2ddc519ee332adfcda051143f88b9b567b7fc/manager/assets/modext/widgets/system/modx.tree.directory.js#L606-L625

**Comment by Ibochkarev** [comment]
Fixed #14835 
@modxbot close
