### ISSUE TITLE
MODX 3: Path in Quick Update File

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#14811]
### Summary
![image](https://user-images.githubusercontent.com/1703670/67747191-49380a00-fa39-11e9-912d-b08653e02c3b.png)

### Step to reproduce
1. Go to Media Browser
2. Quick Update File in path. Such as connectors/system/phpthumb.php

### Environment
MODX 3 with last comment installation with composer

**Comment by Ruslan-Aleev** [comment]
Yes, confirm the bug, although if you open the file from the file tree, then there is no such bug:

![f_path](https://user-images.githubusercontent.com/12523676/68412694-1d89f200-01a6-11ea-9be6-178b9e13acee.png)

**Comment by Ibochkarev** [comment]
Fixed #14834 

@modxbot close
