### ISSUE TITLE
Source type of Create New Media Source 

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#14818]
### Summary
When creating a new Media Source the source type is "sources.modFileMediaSource". Now it confused
![image](https://user-images.githubusercontent.com/1703670/68430904-1244bf80-01c2-11ea-8af1-9764c59d9ef8.png)

### Step to reproduce
Create a new Media Source 

### Environment
MODX 3

**Comment by Ruslan-Aleev** [comment]
By the way, a similar bug for the "Resource Type" when creating a new resource (for 2.x this is not observed):

![d_type](https://user-images.githubusercontent.com/12523676/68433094-2f33bf80-01cf-11ea-9b46-3f3fcc2bbc4b.png)

**Comment by Ibochkarev** [comment]
Fixed #14836 
@modxbot close
