### ISSUE TITLE
[modx3] Including composer.lock in the repository

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#14814]
I just ran into an issue with a git installation of 3.x that was solved by running `composer update` - even though I'd already done `composer install` earlier, which installs the _locked_ versions.

This may have been previously touched on, and I seem to recall @opengeek not being too fond of including `composer.lock` into the repository, but I'm a little fuzzy on the details and want to invite people that use git installations to weigh in.

## Proposal: lock down dependencies by committing composer.lock

The benefit of locking down the composer.lock file is consistency. Without the composer.lock file, git installations are not guaranteed to run any particular version of any particular dependency. 

In my case today, `xpdo/xpdo` was out of date. But it can also go the other way, where a (potentially incompatible) newer version of a dependency is installed. 

### Pros

- Guaranteed version usage. Users should be encouraged to use `composer install` (or `composer install --no-dev`) after a `git pull`. 
- More control over supported versions. 

### Cons

- More work for integrators as new versions of dependencies will not be automatically available to people using a git installation; the "official" composer.lock file needs to be updated first. Users can of course do a manual `composer update` and resolve conflicts later in case of security issues or whatever. This can also be automated with a dependency bot that automatically sends pull requests whenever new versions come out. I'm using [dependabot](https://dependabot.com/) on some projects for that. 

## ...

Anything missing?

**Comment by alroniks** [comment]
We use the composer.lock always in our extensions and deployments to guaranty that proper versions are used. So I vote for adding it.

**Comment by opengeek** [comment]
https://github.com/modxcms/revolution/pull/14815

**Comment by alroniks** [comment]
Seems the issue with 7.0 gone away and we could return to the question about including composer.lock into the repo.

**Comment by opengeek** [comment]
I'm still against this. Different versions of PHP will load different dependencies. It's going to cause problems.

**Comment by opengeek** [comment]
Not to mention if a security issue in a dependency comes out and could simply be updated via composer, any git-based installations will have to update the lock file, which will then be modified and could potentially cause problems updating MODX from git. Or it will require us to immediately release a new version because a dependency needs updating.

**Comment by alroniks** [comment]
Then I suggest close it. I know and understand the reasons why not, we many times faced it in our project (my work), but one difference, that we manage almost all installations, so for us it's not a big problem. Feel free to reopen.
