### ISSUE TITLE
MODX3: User avatar does not display correctly due to fixed sizes

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14828]
### Summary
The user avatar is not displayed correctly due to fixed sizes in the widget:

![avatar](https://user-images.githubusercontent.com/12523676/69012048-8fbebb80-098a-11ea-8039-9b7ae6ae7889.png)

https://github.com/modxcms/revolution/blob/3.x/manager/templates/default/dashboard/onlineusers.tpl#L20

### Environment
MODX 3

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report and solve this issue.
