### ISSUE TITLE
MODX3: Error 503: Service temporarily unavailable after the installation

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14844]
### Summary
Immediately after the NEW installation is completed, after redirecting to the login page, an error appears:
**Error 503: Service temporarily unavailable**

![503](https://user-images.githubusercontent.com/12523676/69637993-400b7e80-1073-11ea-8052-32d09ecb0881.png)

This is solved by reloading the page, but the behavior is strange.
I tried to install 3 times, and through the console, and the night build.

### Environment
MODX 3, php7.1

Server information:
Ubuntu
Apache: 2.4.10
MySQL: 5.7.21-20-beget
Nginx: 1.13.4
Perl: 5.26.1
PHP: 5.2 5.3 5.6 7.0 7.1 7.2 7.3
Python: 2.7

**Comment by Ibochkarev** [comment]
The problem does not reproduce in the next environment:

- MODX Revolution 3.0.0-devBuilt on Nov 25, 2019
- PHP Version 7.2.19
- Apache/2.4.35 (Win64) OpenSSL/1.1.1b
- mysqlnd 5.0.12-dev

**Comment by JoshuaLuckers** [comment]
After you run setup, and before going to the manager login, does the config file exist (`core/config/config.inc.php`)?

**Comment by Ruslan-Aleev** [comment]
I will test later, and take a closer look.

**Comment by Ruslan-Aleev** [comment]
I did not manage to catch the moment, but sometimes the `config.inc.php` file is not created completely, as it seems to me. This does not always happen, but sometimes it happens, at 50% for me.

It’s not clear, but here is what it looks like during installation (after page reload the problem disappears):

![503](https://user-images.githubusercontent.com/12523676/69742129-ae287200-1155-11ea-84b9-7a5f2058440e.gif)

**Comment by JoshuaLuckers** [comment]
@Ruslan-Aleev are you still able to reproduce this error? And if yes, does it also happen when you wait a bit before clicking next after installing?

**Comment by Ruslan-Aleev** [comment]
> are you still able to reproduce this error?

I have not noticed this bug lately.

>  does it also happen when you wait a bit before clicking next after installing?

In my opinion, the wait time does not depend much, but I'm not sure.

This is not a bug, but maybe we should add some kind of check for `config.inc.php` if the error will happen again?

**Comment by Ruslan-Aleev** [comment]
I think it’s worth closing this issue now. In the future, if the error will happen again, we need to come up with something :)
