### ISSUE TITLE
3.x The context menu with a gear is shown in a grid in which it should not be

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14862]
### Summary
Unfortunately, the new and cool menu is shown on almost all grids, even in which there are no actions, for example (`/manager/?a=source`):

![gear-menu](https://user-images.githubusercontent.com/12523676/69918680-9bcc7200-148e-11ea-8b2f-75e72a6d493c.png)

This is very confusing. Need additional check.
We partially discussed this in PR - https://github.com/modxcms/revolution/pull/14806#issuecomment-545055982, created a separate issue, so that the bug is not lost.

### Environment
MODX 3

**Comment by Mark-H** [comment]
Yeah, there will be cases of this. It's easy to fix. Would be great to get a list (in a single issue) of the grids that are affected so they can be quickly fixed ahead of the alpha.

**Comment by Ruslan-Aleev** [comment]
Is it possible to do this somehow more universally?
For example, in grids where there is a context menu there is a call to getMenu (this function, in my opinion, has this name everywhere) - https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/source/modx.panel.sources.js#L142.
And in grids where there is no context menu, getMenu is also not called - https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/source/modx.panel.sources.js#L298. Two different grids (with and without actions) in one file.
p.s. Perhaps my example is not correct.

Unfortunately, there are a lot of files with grids, and again they are not clearly named (somewhere the grids are called by a separate file, and somewhere there are several grids in the form of tabs in one file) and how to understand which file is connected and where - is not obvious.

**Comment by JoshuaLuckers** [comment]
List of grid components that don't have a getMenu function:
- [x] MODx.grid.Search - manager/assets/modext/widgets/modx.panel.search.js
- [x] MODx.grid.PluginEvent - manager/assets/modext/widgets/element/modx.grid.plugin.event.js
- [x] MODx.grid.TVSecurity - manager/assets/modext/widgets/element/modx.grid.tv.security.js
- [x] MODx.grid.TemplateVarTemplate - manager/assets/modext/widgets/element/modx.grid.tv.template.js
- [x] MODx.grid.ActiveResources - manager/assets/modext/widgets/resource/modx.grid.resource.active.js
- [x] MODx.grid.ResourceSecurity - manager/assets/modext/widgets/resource/modx.grid.resource.security.js
- [x] MODx.grid.ResourceSchedule - manager/assets/modext/widgets/resource/modx.panel.resource.schedule.js
- [x] MODx.grid.RoleUser - manager/assets/modext/widgets/security/modx.grid.role.user.js
- [x] MODx.grid.UserGroupCategory - manager/assets/modext/widgets/security/modx.grid.user.group.category.js
- [x] MODx.grid.UserGroupNamespace - manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js
- [x] MODx.grid.UserGroupResourceGroup - manager/assets/modext/widgets/security/modx.grid.user.group.resource.js
- [x] MODx.grid.UserGroupSource - manager/assets/modext/widgets/security/modx.grid.user.group.source.js
- [x] MODx.grid.WhoIsOnline - manager/assets/modext/widgets/security/modx.grid.user.online.js
- [x] MODx.grid.RecentlyEditedResourcesByUser - manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js
- [x] MODx.grid.SourceTypes - manager/assets/modext/widgets/source/modx.panel.sources.js
- [x] MODx.grid.ManagerLog - manager/assets/modext/widgets/system/modx.grid.manager.log.js
- [x] MODx.grid.DatabaseTables - manager/assets/modext/widgets/system/mysql/modx.grid.databasetables.js
- [x] MODx.grid.DatabaseTables - manager/assets/modext/widgets/system/sqlsrv/modx.grid.databasetables.js
- [x] MODx.grid.PackageBrowserGrid - manager/assets/modext/workspace/package.browser.panels.js
- [x] MODx.grid.Package - manager/assets/modext/workspace/package.grid.js
- [x] MODx.grid.Provider - manager/assets/modext/workspace/provider.grid.js
- [x] MODx.grid.Language - manager/assets/modext/workspace/lexicon/language.grid.js
- [x] MODx.grid.LexiconTopic - manager/assets/modext/workspace/lexicon/lexicon.topic.grid.js
- [x] MODx.grid.PackageVersions - manager/assets/modext/workspace/package/package.versions.grid.js

**Comment by Ruslan-Aleev** [comment]
Unfortunately, it turned out to be more difficult. For example, in the search (`/manager/?a=search`), the context menu works, but getMenu is not called - https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/modx.panel.search.js

**Here the context menu works**:
- MODx.grid.Search - manager/assets/modext/widgets/modx.panel.search.js (Search page `/manager/?a=search`)
- MODx.grid.PluginEvent - manager/assets/modext/widgets/element/modx.grid.plugin.event.js ("System Events" tab in Plugin edit page)
- MODx.grid.RoleUser - manager/assets/modext/widgets/security/modx.grid.role.user.js (If this is a user editing page `/manager/?a=security/user/update&id=1`, the "Access Permission" tab)
- MODx.grid.RecentlyEditedResourcesByUser - manager/assets/modext/widgets/security/modx.grid.user.recent.resource.js (Account editing page `/manager/?a=security/profile`, "Recent Resources" tab, but if this a page `/manager/?a=system/info`, the "Recent documents" tab, then menu dont work :) )

User Group editing page `/manager/?a=security/usergroup/update&id=1`, the "Permissions" tab)
- MODx.grid.UserGroupCategory - manager/assets/modext/widgets/security/modx.grid.user.group.category.js ("Element Category Access")
- MODx.grid.UserGroupNamespace - manager/assets/modext/widgets/security/modx.grid.user.group.namespace.js ("Namespace Access")
- MODx.grid.UserGroupResourceGroup - manager/assets/modext/widgets/security/modx.grid.user.group.resource.js ("Resource Group Access")
- MODx.grid.UserGroupSource - manager/assets/modext/widgets/security/modx.grid.user.group.source.js ("Media Source Access")

---

As a result, it is not clear whether there is a broken context menu, because in the examples above there is no call to getMenu, but the context menu works :)

**Comment by theboxer** [comment]
`getMenu` function is on every grid that extends `MODx.grid.Grid`. It defaults to a `menu` value returned from the processor for each row.
