### ISSUE TITLE
Make MODX 2.6.x the minimum required version for direct upgrades to MODX 3.x

### ISSUE THREAD

**Issue by JoshuaLuckers** [modxcms/revolution#14878]
### Summary
Make MODX 2.6.x the minimum required version for direct upgrades to MODX 3.x

### Why is it needed?
If we set a minimum required version that's needed to upgrade to MODX 3.x we can clean up various legacy upgrade scripts. 

### Related issue(s)/PR(s)
Discussion in PR #14877:  https://github.com/modxcms/revolution/pull/14877#pullrequestreview-328556511

**Comment by Ibochkarev** [comment]
I agree

**Comment by Mark-H** [comment]
This minimum is already implemented. 

https://github.com/modxcms/revolution/commit/9a527c6b4ac51c9a49c765dc04d93202ce0ca43e#diff-948b50215f9ff1174344c1b416fd0ac5
