### ISSUE TITLE
3.x Unused grids scripts

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14875]
### Summary
In the process of working on https://github.com/modxcms/revolution/pull/14864, I discovered that there are script files that I think are not used. Need a refactor unused grid scripts.

For example:
- `modx.grid.resource.security.js` (https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/resource/modx.grid.resource.security.js), but another file is used `modx.grid.resource.security.local.js` (https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/resource/modx.grid.resource.security.local.js)
- `modx.grid.role.user.js` (https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/security/modx.grid.role.user.js), in my opinion the file is not used
- `language.grid.js` (https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/workspace/lexicon/language.grid.js), in my opinion the file is not used
- `lexicon.topic.grid.js` (https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/workspace/lexicon/lexicon.topic.grid.js), in my opinion the file is not used

Most likely there are more unused files.
Everyone would like cleanliness in the distribution, otherwise the final archive is heavier and heavier with each version :)

### Environment
MODX 2.7>

**Comment by JoshuaLuckers** [comment]
I'll prepare a PR in the upcoming days. :)

**Comment by Mark-H** [comment]
Resolved in alpha2.
