### ISSUE TITLE
3.x Customization form profile cannot be saved

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14887]
### Summary
In the profile editing panel of the customization form, saving does not work, an error pops up.

GIF:
![fc_edit](https://user-images.githubusercontent.com/12523676/70632862-07f66500-1c49-11ea-8ae6-945119e7bd0f.gif)

### Environment
MODX 3

**Comment by Ibochkarev** [comment]
Fixed #14888 
@modxbot close
