### ISSUE TITLE
MODX 3 alpha1 - New install requires manual creation of some directories or it fails

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14892]
### Summary
Setup fails unless the user manually created the `cache`, `config` and `export` directories within core.

### Step to reproduce
Do a fresh install on a Linux box.

### Observed behavior
On a new install attempt, setup won't even start without manually creating the `cache` directory within core. It then fails when running tests until both the `config` and `export` directories are manually created.

### Expected behavior
Setup should automatically create these directories or include them in the download.

### Environment
MODX 3.0.0-alpha, Ubuntu 18.04, PHP 7.3

**Comment by JoshuaLuckers** [comment]
Are there any errors logged? Does the same happen if you try to install 2.7.2?

**Comment by muzzwood** [comment]
I don't remember having come across this exact problem with 2.7

As for 3.. it's not a permissions issue. I set everything to 777 to make sure. First error is this one:
![Screenshot_2019-12-13 Screenshot](https://user-images.githubusercontent.com/5160368/70796653-c64af300-1ddd-11ea-9fe2-67b8cc5638e8.png)
Creating the cache folder fixes it.

Next issues are at the test screen:
![Screenshot_2019-12-13 MODX Revolution 3 0 0-alpha1 » Install](https://user-images.githubusercontent.com/5160368/70796720-eed2ed00-1ddd-11ea-9cc0-1b8f2018fe45.png)
Creating the export and config directories manually fixes it.

There is a notice there about Linux machines:
```
For new Linux/Unix installs, please create a blank file named config.inc.php in your MODX core config/ directory with permissions set to be writable by PHP.
```
This is not entirely accurate, you don't need to create the blank file, just creating the directory fixes it.

**Comment by Mark-H** [comment]
That doesn't look like something new in the alpha - it's just recognizing that it can't create them due to the file/folder permissions so it tells you to do it.

**Comment by muzzwood** [comment]
Apologies - this one was the result of vagrant permissions not behaving as expected.
This is a non-issue. Closing!

**Comment by JoshuaLuckers** [comment]
@digitalpenguin thanks for reporting back! If others encounter this issue, what do they need to change to make the permissions behave as expected with Vagrant?
