### ISSUE TITLE
MODX 3 alpha1 - Deleting resource with new switch (checkbox) shows duplicate in tree

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14893]
### Summary
Deleting a resource using the deleted switch (checkbox) displays a duplicate of the deleted resource in the resource tree.

![Screenshot_2019-12-13 Editing Home MODX Revolution](https://user-images.githubusercontent.com/5160368/70773362-393e7480-1db2-11ea-8bcb-b9ab4c996789.png)

### Step to reproduce
Edit a resource, click deleted, then click save. You'll see two of the same deleted resource in the resource tree.

### Observed behavior
The issue occurs when the user clicks deleted and then save. The duplicate disappears when the page is reloaded.

### Expected behavior
Only one instance of the resource should show.

### Environment
MODX version 3.0.0-alpha1

**Edit**: 
Undeleting the resource in the same manner causes the same issue.

**Comment by Mark-H** [comment]
Fixed in alpha2.
