### ISSUE TITLE
MODX 3 alpha1 - The list of downloaded packages is not updated

### ISSUE THREAD

**Issue by alexsoin** [modxcms/revolution#14903]
### Summary
After downloading the package, the downloaded package is not shown.
If you press the "reset filter" button, the package appears.
All actions were performed after clean installation.

![1](https://user-images.githubusercontent.com/3787132/70908445-9a6d7e80-2024-11ea-9a44-3bccc954dcfe.png)

![2](https://user-images.githubusercontent.com/3787132/70908453-9f323280-2024-11ea-9488-f9b3f49f048e.png)

![3](https://user-images.githubusercontent.com/3787132/70908430-917cad00-2024-11ea-8354-742a82348c09.png)

### Step to reproduce
1. Go to package manager.
2. Download the package.
3. Go to package list.

### Observed behavior
Empty list of packages.

### Expected behavior
List of packages with the downloaded package

### Environment
MODX version 3.0.0-alpha1

**Comment by Ibochkarev** [comment]
@alexsoin thanks. This bug was fixed earlier.
