### ISSUE TITLE
MODX 3 alpha1 - link update on the page help in administration panel

### ISSUE THREAD

**Issue by alexsoin** [modxcms/revolution#14908]
### Summary

The administration panel on the pages `/manager/?a=help` contains outdated links, such as a link to the forum at `http://forums.modx.com/`, after which we are invited to go to `https://community.modx.com/`

link to google+ - this service was closed.

**Comment by Ibochkarev** [comment]
Fixed in #14909 
@modxbot close

**Comment by Ibochkarev** [comment]
@alexsoin Thanks
