### ISSUE TITLE
MODX 3 alpha1 - dependency list

### ISSUE THREAD

**Issue by alexsoin** [modxcms/revolution#14904]
### Summary
After installing the list of dependencies, you cannot install a package that requires them.

![photo_2019-12-16_15-14-29](https://user-images.githubusercontent.com/3787132/70908688-35665880-2025-11ea-8c8d-4645905fdcbd.jpg)

![photo_2019-12-16_15-14-30](https://user-images.githubusercontent.com/3787132/70908689-35665880-2025-11ea-8822-d4630f6bf051.jpg)

### Environment
MODX version 3.0.0-alpha1

**Comment by Mark-H** [comment]
Fixed in #14994 - thanks for the report!
