### ISSUE TITLE
Вug front-end Install screen one

### ISSUE THREAD

**Issue by OlegShchavelev** [modxcms/revolution#14900]
## Bug report

Russian language

Screen

![Install screen](https://i.imgur.com/ZtIaAMO.png)

### Environment
MODX Revolution 3.0.0-alpha1 , Browser Firefox 71.0 (64-bit)

**Comment by Ruslan-Aleev** [comment]
Fixed at https://github.com/modxcms/revolution/pull/14785 but not yet approved.

**Comment by OlegShchavelev** [comment]
![image](https://user-images.githubusercontent.com/20732384/73572208-46f2ab00-4481-11ea-8b69-a4064c3e6a24.png)

**Comment by Ibochkarev** [comment]
@DetaliDigital thanks. This bug was fixed earlier.
