### ISSUE TITLE
MODX 3 alpha1 - Static plugins/snippet are not allowed

### ISSUE THREAD

**Issue by theboxer** [modxcms/revolution#14922]
### Summary
You can't create a static snippet or plugin, because `php` extension is not allowed.

### Step to reproduce
Try and create a static snippet/element and link a `php` file.

### Observed behavior
Error will appear.

### Expected behavior
Error shouldn't appear :P

### Environment
MODX Revolution 3.0.0-alpha1

**Comment by JoshuaLuckers** [comment]
This is a duplicate of https://github.com/modxcms/revolution/issues/13898
