### ISSUE TITLE
MODX 3 alpha1 - bug save add user 

### ISSUE THREAD

**Issue by OlegShchavelev** [modxcms/revolution#14930]
## Bug report

When adding a new user. I click the save button after the full establishment of all user data, the progress of the download bar does not close.

When you refresh the page, all data is saved, and the new user is in the list.

![no_bar_add_user](https://user-images.githubusercontent.com/20732384/71305198-1418ba00-23e1-11ea-83d9-c715dfc8baaf.gif)

List

![изображение](https://user-images.githubusercontent.com/20732384/71305207-314d8880-23e1-11ea-8599-2d9721c79570.png)

### Environment
MODX 3 alpha1.

**Comment by JoshuaLuckers** [comment]
I'm unable to reproduce this error. Are there any errors in the console of your browser?

**Comment by OlegShchavelev** [comment]
![изображение](https://user-images.githubusercontent.com/20732384/71347963-91c4fd00-257c-11ea-909b-ecd5db1644d4.png)

**Comment by OlegShchavelev** [comment]
console errors
![изображение](https://user-images.githubusercontent.com/20732384/71348164-fc763880-257c-11ea-9a05-efac3b4dad43.png)

**Comment by JoshuaLuckers** [comment]
Is this a clean install or upgrade? Does it help if you clean the cache of your browser and/or try it in another browser?

**Comment by Ibochkarev** [comment]
@DetaliDigital please test again

**Comment by Ibochkarev** [comment]
With the latest current state - the problem does not recur. Tested in 2 browsers

![image](https://user-images.githubusercontent.com/2138260/84429783-8c529080-ac4a-11ea-87b5-3d1f9b95c8d5.png)

![2020-06-12-01-16-08](https://user-images.githubusercontent.com/2138260/84429741-7f35a180-ac4a-11ea-98e8-c2a2af358590.gif)

Thanks for taking time to report this issue and help make MODX better.
Please reopen if you still encounter this issue.

@modxbot close
