### ISSUE TITLE
[3.x] Add support for legacy components 

### ISSUE THREAD

**Issue by CrazyBoy49z** [modxcms/revolution#14944]
### Summary
I plan to add support for legacy components to the MODX kernel as class_alias deprecated https://github.com/modxcms/revolution/blob/3.x/core/include/deprecated.php

Do you offer this PR, is it not worth the time to spend it?

**Comment by JoshuaLuckers** [comment]
Do you have a list of the legacy components that (might) not work in 3.x?

**Comment by CrazyBoy49z** [comment]
https://docs.google.com/spreadsheets/d/1HyKwqz1qdCW6C46eH8PcWZLZNllI2HB8yAwkhkVPbX8/edit#gid=0

**Comment by Jako** [comment]
What do you mean with 'Partly support'? What is the difference to 'Support'?

**Comment by Mark-H** [comment]
I think we want to avoid adding every single change - but adding classes that people have been told to extend over the years (like resource processors, required for custom resources) or certain services (modMail, modParser, etc) would probably be quite useful.

**Comment by OlegShchavelev** [comment]
@Jako 

![изображение](https://user-images.githubusercontent.com/20732384/71731371-97acbf00-2e55-11ea-9c27-11f236fa0ab5.png)

**Comment by CrazyBoy49z** [comment]
> I think we want to avoid adding every single change - but adding classes that people have been told to extend over the years (like resource processors, required for custom resources) or certain services (modMail, modParser, etc) would probably be quite useful.

This is what I want, just using these classes will be easy to create simple sites at the beginning in MODX that will speed up testing ...

**Comment by JoshuaLuckers** [comment]
Can you share a list of the classes you would like to add?

**Comment by CrazyBoy49z** [comment]
@JoshuaLuckers 

modMail,
modDashboardWidgetInterFace,
modTemplateVarInputRender,
modSystemEvent,
modManagerController

**Comment by CrazyBoy49z** [comment]
You will then be able to build sites and actively test the kernel

**Comment by JoshuaLuckers** [comment]
I propose to add `modPHPMailer` as well.

**Comment by Ibochkarev** [comment]
Added #14964 

Thanks for taking time to report this issue and help make MODX better.
Please reopen if you still encounter this issue.

@modxbot close
