### ISSUE TITLE
[3.x] Add dump function in MODX3

### ISSUE THREAD

**Issue by CrazyBoy49z** [modxcms/revolution#14941]
### Summary
The dump() Function
The VarDumper component creates a global dump() function that you can use instead of e.g. var_dump. By using it, you'll gain:

Per object and resource types specialized view to e.g. filter out Doctrine internals while dumping a single proxy entity, or get more insight on opened files with stream_get_meta_data;
Configurable output formats: HTML or colored command line output;
Ability to dump internal references, either soft ones (objects or resources) or hard ones (=& on arrays or objects properties). Repeated occurrences of the same object/array/resource won't appear again and again anymore. Moreover, you'll be able to inspect the reference structure of your data;
Ability to operate in the context of an output buffering handler.

https://symfony.com/doc/current/components/var_dumper.html

### Why is it needed?
There is a lack of a convenient output when developing snippets and add-ons

**Comment by Mark-H** [comment]
Implementing `__debugInfo` where needed would be very useful. 

I've added this into an xPDOObject which allows regular var_dump on it without it dumping everything in memory:

``` php
    public function __debugInfo()
    {
        return [
            'new' => $this->isNew(),
            'dirty' => $this->_dirty,
            'fields' => $this->toArray(),
            'fieldMeta' => $this->_fieldMeta,
        ];
    }
```

Been thinking we should add that to the base `xPDOObject`.

**Comment by JoshuaLuckers** [comment]
Would be a good idea to move this issue to the xPDO repo instead then?

**Comment by CrazyBoy49z** [comment]
> Would be a good idea to move this issue to the xPDO repo instead then?

A good idea. But I think it should be in the kernel when enable the "debug" parameter

It is in the component [modHelpers](https://modstore.pro/packages/utilities/modhelpers)

**Comment by JoshuaLuckers** [comment]
> Implementing `__debugInfo` where needed would be very useful.
> Been thinking we should add that to the base `xPDOObject`.

Would be a good addition! Do you have time to prepare a PR for this? 😄

**Comment by Mark-H** [comment]
I wont have time for that before alpha2.

**Comment by Mark-H** [comment]
Maybe I do have time before alpha2.

**Comment by Mark-H** [comment]
xPDO PR: https://github.com/modxcms/xpdo/pull/174

**Comment by Ibochkarev** [comment]
Added in https://github.com/modxcms/xpdo/pull/174
@modxbot close
