### ISSUE TITLE
[3.x] dublicate /manager/?a=security/forms

### ISSUE THREAD

**Issue by CrazyBoy49z** [modxcms/revolution#14953]
### Summary

![image](https://user-images.githubusercontent.com/3448603/72476528-1c082600-37f6-11ea-9e39-92bf3c38f13c.png)

 Upgrade MODX 2.7.2 to MODX 3.0.0-alpha1

**Comment by Ibochkarev** [comment]
Related https://github.com/modxcms/revolution/pull/14780

@theboxer please help

**Comment by Ibochkarev** [comment]
Fixed #15112 
@modxbot close
