### ISSUE TITLE
Creating a folder with resource ID in media source settings

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14955]
## Feature request
It would be useful to have a setting that allows you to create folders with the resource ID in the media source.

It often happens that the source for the TV is one, but resources are many, with an additional ID folder it would be easier to manage resource files.

Many file management components have this default setting. I think it would be useful to have it in the core.

![res_id](https://user-images.githubusercontent.com/12523676/72522756-dbe98780-3877-11ea-8424-c44ed2cbdbf0.png)

**Comment by ghost** [comment]
See the MIGX snippet migxResourceMediaPath. 

```[[migxResourceMediaPath? &pathTpl=`assets/images/quilts/{id}/` &createFolder=`1`]]```

https://github.com/Bruno17/MIGX/blob/master/core/components/migx/elements/snippets/migxresourcemediapath.snippet.php

**Comment by Ruslan-Aleev** [comment]
Yes, I worked with `migxResourceMediaPath`, but there is an inconvenient limitation in it - the file browser does not allow you to see files outside the ID folder.

**Comment by Bruno17** [comment]
you could of course modify that snippet to point to the folder above but create the resource-folder anyway.

But yes, having something build in the core like that could be handy.
Not only for resources, but also for items of custom tables. 
It would be nice, if there was a way to send custom query parameters within the file-management, like resource-ids or ids of customtable items and we could use this query parameters to create file-folders.

**Comment by JoshuaLuckers** [comment]
To me it would make more sense if this feature was provided by an extra/plugin instead of providing it in the core.
There are various `OnFileManager*` [System Events](https://docs.modx.com/current/en/extending-modx/plugins/system-events) that can be leveraged.

**Comment by theboxer** [comment]
I agree with Joshua, this might be a good fit for a custom media source.

**Comment by Ruslan-Aleev** [comment]
I fundamentally disagree with you. And the fact that creating the resource folder is found in packages just indicates that the functionality is useful and many lack it.

**Comment by theboxer** [comment]
That's the reason for packages, if there's a feature that the core doesn't have and is wanted from people they create a package.

Same as you can find a package for gallery - it's a wanted feature for many, but is not part of the core.

**Comment by Ruslan-Aleev** [comment]
I understand you, but this is not an argument. Gallery is a more global entity. We can also, for example, remove all TVs, but create a separate package that adds TV...
Once again, I understand you, I just disagree with you :)

**Comment by theboxer** [comment]
The example with TVs is actually pretty good one. We have the most common in core and ability to add others via a package :)

Same thing applies to media sources, we have the most common in core, if you need a special one, you can add it via a package.

Not every feature can make it to the core.

**Comment by Ruslan-Aleev** [comment]
>  We have the most common in core...

I do not agree :) MIGX is used in projects more often than, for example, TV with a URL type. But MIGX is not in the core.

In general, there is no concrete justification for why some functions are implemented in the core, and some are not.
If it were my will, I would embed it in the core, and, for example, "Import / Export html" from the core would delete :) But we have what we have.

**Comment by JoshuaLuckers** [comment]
I don't think the Media Source is the right place for this option. It's doesn't have a relation with "Resources". 

If we add such an option it would make more sense to make it available as Template Variable option instead.
