### ISSUE TITLE
Double load for TV media sources list

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#14966]
### Summary
User should click twice on source selectore while changing media source for TV

### Step to reproduce
1. Create second media source (additionally to default one).
2. Open any TV and try to change appropriate media source via Media Sources tab 

### Observed behavior
Please check this:

![media_source_double_load](https://user-images.githubusercontent.com/2815640/72981617-435e8480-3dee-11ea-95c8-f560f12eb5cc.gif)

### Expected behavior
Better UX  - list should be loaded only once after click OR preloaded initially somehow. Single click should allow to open the list and select another source anyway. 

By the way, there are no problems in "System settings" with the choice of the sources.

### Environment
MODX 2.7.2

**Comment by Ruslan-Aleev** [comment]
Duplicate https://github.com/modxcms/revolution/issues/14760
Although it’s written more competently here, I’ll close my.

**Comment by Ruslan-Aleev** [comment]
If we delete this line https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/element/modx.panel.tv.js#L669, then there is no double loading, but the source name is not displayed (only its id):

![tv-sources](https://user-images.githubusercontent.com/12523676/81921558-7ae27e00-95e3-11ea-9f83-a17f9a973ba4.gif)

In principle, in the system settings and other elements in manager grids only id is displayed.
For the UI, hiding the name is a minus, but the lack of double loading is a huge plus :)

Can we leave id output @JoshuaLuckers @Jako what do you think?

**Comment by Ruslan-Aleev** [comment]
If we delete this line https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/element/modx.panel.tv.js#L669, then there is no double loading, but the source name is not displayed (only its id):

![tv-sources](https://user-images.githubusercontent.com/12523676/81921558-7ae27e00-95e3-11ea-9f83-a17f9a973ba4.gif)

In the system settings and other elements in manager grids only id is displayed.
For the UI, hiding the name is a minus, but the lack of double loading is a huge plus :)

Can we leave id output @theboxer , what do you think?

p.s. Most likely, many will not notice the changes, but the double loading bug is extremely annoying.

**Comment by Jako** [comment]
@Ruslan-Aleev It is better to detect the bug than disabling an option.

**Comment by Ruslan-Aleev** [comment]
@Jako Thank you for helping with the bug!
It’s clear that it’s better to fix the bug, no one argues. I just suggested a quick solution. Moreover, a similar behavior is already found in the "System settings".
In my opinion, a crooked solution is better than an ideal one, but somewhere in the distant future...
p.s. I would fix the bug correctly if I knew how :)

**Comment by Jako** [comment]
> Moreover, a similar behavior is already found in the "System settings".

Could you give an example?

**Comment by Ruslan-Aleev** [comment]
I meant that the name of the media source is not displayed:

![source_setting](https://user-images.githubusercontent.com/12523676/85201915-9b50d700-b30b-11ea-8b96-602171d4156c.gif)

**Comment by Ibochkarev** [comment]
Fixed #15122 

@himurovich Thanks for taking time to report this issue and help make MODX better.
Please reopen if you still encounter this issue.

@modxbot close

**Comment by Jako** [comment]
@Ruslan-Aleev Could you open a feature request for your issue?
