### ISSUE TITLE
when creating a new resource (without saving) and changing the template modX shows an error when the user can't access the default_context

### ISSUE THREAD

**Issue by emiehilbelink-adwise** [modxcms/revolution#14965]
### Summary

When creating a new resource (without saving) and changing the template modX shows an error when the user can't access the default_context.

If the default_context is web, and the user only has access to context de (for german resources), the follow error shows up:

"Context_err_nf"

We try to overwrite the default_context in the setting of the user, and the user roll. But this did not fixed this problem. 

After we gave the user also permission to access the default_context, the error does not show up.

### Step to reproduce

Create a user that only has access to the context that is not de default_context. Create a new resource and change the template (without saving it).

Because after you safe the resource, the user is able to change the template.

### Observed behavior

The error "Context_err_nf" shows up.

### Expected behavior

There should not be an error, and the user should be able to edit the resource.

### Environment

ModX version: 2.7.2 and 2.6.5, browser Chrome

**Comment by Ibochkarev** [comment]
@emiehilbelink-adwise Please fill in the error information in the message body, and not in the subject. And add an error log or any other useful information.

thanks

**Comment by emiehilbelink-adwise** [comment]
@Ibochkarev I just updated this bug. Also reported this bug in Modx Slack Development 23-01-2020 at 10:45.

**Comment by JoshuaLuckers** [comment]
Thanks again for taking time to submit this issue and for helping me solve it. The PR resolving this this issue has been merged and will is part of MODX 2.7.3.
