### ISSUE TITLE
Display dates in manager in one format

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14961]
### Summary
In the system settings, there are date and time settings:
- `manager_date_format`
- `manager_time_format`

However, these settings are sometimes not used. For example, in the “Edit File form” and in the “Error log”, the date is displayed in a different format (most likely in other sections too). Although the settings are `d/m/Y` and `H:i`:

It is worth bringing the output of dates and times to the format specified in the settings.

**The sections do not take into account time settings, but should:**
- "Who's Online" widget;
- "Created On" field in "User" edit form;
- "Recent documents" tab in "System Info" section.

### Environment
MODX 2.7 >

**Comment by Jako** [comment]
The error log date format can't be changed (on the fly), the other ones should be formatted with one format.
