### ISSUE TITLE
Setup Welcome Screen Blank on Next

### ISSUE THREAD

**Issue by jaygilmore** [modxcms/revolution#14974]
### Summary
When installing 3.0-alpha2, after selecting a language and clicking the _Next>_ button to proceed, the screen remains on the Welcome page, however, it is now blank.  
![installer-welcome-blank](https://user-images.githubusercontent.com/378199/73306224-26f98800-41f2-11ea-99bb-a3938de25dd7.png)

### Step to reproduce
Start to install Revo, select a language from the language screen and click _Next>_. 

### Observed behaviour
The **Welcome** page appears to be reloaded as blank after clicking _Next>_ the first time. I retested this and didn't see any errors in the console. 

### Expected behavior
After selecting the language and clicking _Next>_, the user should be presented with the option to change the context key, or click _Next>_ again to take the user to the **Options** screen. 
<img width="937" alt="installer-welcome-b" src="https://user-images.githubusercontent.com/378199/73306172-0e896d80-41f2-11ea-9fd7-0782c628cf5a.png">

### Environment
3.0-alpha2
PHP 7.2.1
MySQL 5.6.38

**Comment by qodo** [comment]
+1 I am seeing this too on both Windows Firefox and Chrome.
There are no error messages in neither the server logs or browser console - it's just blank.

This doesn't prevent the user from continuing to the next step though!

**Comment by Ibochkarev** [comment]
Resolved #14999 
@modxbot close
