### ISSUE TITLE
MODX 3 alpha2 - bug style input Static file: templates, chunks ...

### ISSUE THREAD

**Issue by OlegShchavelev** [modxcms/revolution#14986]
Bug styles input

**Chunk**

![image](https://user-images.githubusercontent.com/20732384/73581546-9f827200-449a-11ea-9801-acd823147542.png)

Templates

![image](https://user-images.githubusercontent.com/20732384/73581584-b628c900-449a-11ea-8c62-d636035f618c.png)

Snippet

![image](https://user-images.githubusercontent.com/20732384/73581606-c80a6c00-449a-11ea-894f-64d334b03813.png)

Plugin

![image](https://user-images.githubusercontent.com/20732384/73581631-e2444a00-449a-11ea-8ae1-5c0913f242e7.png)

Error saving static file

![image](https://user-images.githubusercontent.com/20732384/73581719-3ea76980-449b-11ea-96ed-4d66a3de4855.png)

**Comment by Ruslan-Aleev** [comment]
Also, the list of sources is displayed not in full width:

![file_static](https://user-images.githubusercontent.com/12523676/73584522-779f0880-44b2-11ea-8242-7e9905730be9.png)

Google Chrome 79.0.3945.130
Monitor 1920 x 1080
