### ISSUE TITLE
Change style of breadcrumbs to a new one in "Packages" section

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#14985]
### Summary
Because the manager panel now has useful breadcrumbs (thanks to the @theboxer ) https://github.com/modxcms/revolution/pull/14983 https://github.com/modxcms/revolution/pull/14890, it makes sense to change the style of breadcrumbs in the "Packages" section to a new one.

**Breadcrumbs in the "Packages" section:**

![bc_1](https://user-images.githubusercontent.com/12523676/73545243-63c4b980-4454-11ea-889b-f3d6389f91ac.png)

**New breadcrumbs:**

![bc_2](https://user-images.githubusercontent.com/12523676/73545244-63c4b980-4454-11ea-9b55-04bcc0923eb2.png)

### Why is it needed?
For standardization in design.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/14983
https://github.com/modxcms/revolution/pull/14890
https://github.com/modxcms/revolution/issues/14769

**Comment by theboxer** [comment]
I don't think the comparison above (package management and FC) is apples to apples.

On the FC -> Profile -> Set, breadcrumbs reflects the whole page, but in the Package Manager, it reflects the Panel/Grid under the Packages tab. As the breadcrumbs changes in the Package Manager, only the part under the Packages tab actually changes, not the whole page.

I'd vote for keeping that as is.

**Comment by Ruslan-Aleev** [comment]
I agree with you, we can leave it as it is.
The only thing I would change the icon to the icon of packages, because there seems to be a link to the Homepage in breadcrumbs:

![bc_icon](https://user-images.githubusercontent.com/12523676/84282126-0cd99a00-ab42-11ea-8ec5-b67d77708cfe.png)

**Comment by theboxer** [comment]
That's set somewhere in styles and is not really relevant to this issue any more. Feel free to open new one about changing the icon. It'll have to target only breadcrumbs in the package manager and not the whole breadcrumbs component though.
