### ISSUE TITLE
Use single quotation marks in queries to support ANSI_QUOTES SQL mode in MySQL

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#14991]
### Summary
I was unable to see the list of previous versions for specific packages in the manager. The processor was failing and after some debugging found it was due to double quotes being used in the sortby statement.
https://github.com/modxcms/revolution/blob/2.x/core/model/modx/transport/mysql/modtransportpackage.class.php#L65

This is incompatible with ANSI_QUOTES mode for string literals in MySQL 8.
https://dev.mysql.com/doc/refman/8.0/en/string-literals.html

I tested the query with single quotes and that fixed it.

If no one does it first, I can attempt a PR in the next few days.

### Step to reproduce
Have a MySQL database with ANSI_QUOTES mode. Try to view previous packages in the package manager.

### Observed behavior
No data loaded in grid.

### Expected behavior
Data should load.

### Environment
MODX 2.7.2, nginx and PHP7.4, mysql 8 with ANSI_QUOTES enabled.

**Comment by Ibochkarev** [comment]
Fixed #15011 

Thanks for taking time to report this issue and help make MODX better.
Please reopen if you still encounter this issue.

@modxbot close
