### ISSUE TITLE
Add transliteration of files when uploading to a media source

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15007]
### Summary
It would be useful to add transliteration of files when uploading to a media source.

Yes, there are packages that do a great job of this. However, such functionality in the core would not be amiss.

**Again there is transliteration in url, but there is no transliteration of files - it is not logical and look unfinished.**

### Why is it needed?
English-speaking MODX users do not even know how many problems a file can give on server, for example, with a russian name.

Perhaps this was discussed earlier, I did not find.

**Comment by Mark-H** [comment]
Per #15019, this would ideally be implemented by tapping into existing transliteration settings (and not a hardcoded table). Perhaps worth reconsidering the default translit setting values in 3.x to make sure some default transliteration is applied even if people don't know what transliteration is.

**Comment by ilyautkin** [comment]
I'm going to work on this

**Comment by Ibochkarev** [comment]
Improved in #15457
