### ISSUE TITLE
Add ability to hide media source in file tree

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15006]
### Summary
With a large list of media sources, the file tree is incredibly slow, for example, a commerce site + TV with iown media sources.
MODX tries to load the entire list of sources and files and slows down. It would be useful to load files at the source only if the user expanded it in a tree.

### Why is it needed?
Manager slowly loading, bad for UX

### Suggested solution(s)
It would be useful to have a source setting that allows you to collapse/hide the source in the file tree.
Or it would be useful to have a system setting in which you could choose: "Collapse media sources in the tree."

**Comment by JoshuaLuckers** [comment]
In 3.x the files are only loaded when the media source is collapsed, the manager seems to remember the last state and in my case they are hidden by default. Do I overlook something?

**Comment by Ruslan-Aleev** [comment]
Interestingly, I did not know this.
Let the issue be open, in the future, after the tests, I will close it if there are no problems with manager loading.

**Comment by theboxer** [comment]
I'll close this as it was quite a long time for some tests :) Feel free to reopen if it's still an issue.

**Comment by Ruslan-Aleev** [comment]
> I'll close this as it was quite a long time for some tests :) Feel free to reopen if it's still an issue.

Because MODX3 has not yet been released, there are no active projects on 3 and tests, too :)
