### ISSUE TITLE
Removed INI directive safe_mode

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#15029]
### Summary
Ran a PHP Compatibility report using [https://github.com/PHPCompatibility/PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) which gave me the following error message. I checked and it still lives in the 3.x branch:
https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/Transport/modTransportPackage.php#L440

There are multiple warnings/warnings when checking with MODX 2.7.1, might be worth checking with 3.x as well.

### Step to reproduce
Run PHPCompatibility on MODX and check the output of the report. There will be multiple notifications about removed ini directives. 

I've checked with MODX 2.7.1 which also gave me some deprecation messages which might be fixed in later MODX versions, but just as an FYI.

FILE: /core/model/modx/transport/modtransportpackage.class.php

------------------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------------------------
 401 | WARNING | INI directive 'safe_mode' is deprecated since PHP 5.3 and removed since PHP 5.4
------------------------------------------------------------------------------------------------------------

### Environment
MODX 2.x & 3.x

**Comment by Ibochkarev** [comment]
Fixed #15058 
Thanks for taking time to report this issue and help make MODX better.
Please reopen if you still encounter this issue.
@modxbot close
