### ISSUE TITLE
Assign TV to chunks

### ISSUE THREAD

**Issue by eremozin** [modxcms/revolution#15026]
### Summary
Assign TV to chunk 

### Why is it needed?
Like this you can make TV's for specific chunk and when you use that chunk in a Template. This TV's wil automatically show in your resources.

**Comment by ghost** [comment]
They are Template variables for a reason. Their values are tied to resources that use the template, and even then they don't show up unless you include their tags somewhere. If you want a chunk to show a TV, just put the TV tag in the chunk. You can also use properties in a chunk, and in the chunk use its [[+property-name]] tag to output the property value.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to submit a feature request. 

Might it be that [Properties and Property Sets](https://docs.modx.com/current/en/building-sites/properties-and-property-sets) is what you are looking for?
