### ISSUE TITLE
Prevent TV default value from being evaluated in manager

### ISSUE THREAD

**Issue by dmoagx** [modxcms/revolution#15024]
MODX Version: 2.7.2-pl

* Create a new "text" TV, assign it to a template and use it in the template
* Create a new resource and set the value of the TV to `@RESOURCE 42` (or another existing ID)
* Save and view the document
* Result:
  * In the `modx_site_tmplvar_contentvalues` table `@RESOURCE 42` will be saved
  * When viewing the resource, the content of resource 42 will be shown

Now, let's say I'm lazy and I want `@RESOURCE 42` to be the default value for the TV on every new resource I create:
* Set the default value of the TV to `@RESOURCE 42`
* Create a new resource and save it
* Save and view the document
* Result:
  * When editing the resource in the manager, the TV value will not show `@RESOURCE 42`, but the actual contents of that resource
  * In the `modx_site_tmplvar_contentvalues` table the contents of resource 42 at the time of creation of the new resource will be saved
  * When viewing the resource the expanded TV will contain whatever the content of resource 42 was at the time of creation of the resource, but not what it is right now

This is something that worked in Evo but I don't see a way to achieve the same result in Revo. From looking at `processBindings` it doesn't seem that there is any way to escape the default value, either.

**Comment by JoshuaLuckers** [comment]
> Now, let's say I'm lazy and I want `@RESOURCE 42` to be the default value for the TV on every new resource I create
> [...]
>  When editing the resource in the manager, the TV value will not show `@RESOURCE 42`, but the actual contents of that resource


[According to the documentation](https://docs.modx.com/current/en/building-sites/elements/template-variables/bindings), it works as intended:

> Please note that @ bindings will work only when used inside "Input Option Values" or "Default Value" fields.
> 
> When placing @ bindings inside the "Input Option Values" field, they are used to format input options only when editing document within the Manager, for example to create a drop-down list of Cities or Countries.
> 
> When placing @ bindings inside the "Default Value" field the returned value is used to render to the final web page. This makes it simple to build complex forms for data input on the web very quickly.

I'm not sure if bindings should be parsed when they are used as value in Template Variables..
