### ISSUE TITLE
modMediaSource.parseProperties: shadowed argument

### ISSUE THREAD

**Issue by dmoagx** [modxcms/revolution#15028]
In `modMediaSource.parseProperties` an argument `$properties` is expected.
However that argument is immediately overwritten by the first statement in the function and never used:
```php
    public function parseProperties(array $properties) {
        $properties = $this->getProperties();
```
The only call to `parseProperties` is in `getProperties` as 
```php
$properties = $this->parseProperties($properties);
```
which looks to me like the author intended his passed in properties to be parsed. Thus I believe this to be a bug.

Version: 2.7.2-pl

**Comment by JoshuaLuckers** [comment]
Good catch! The properties are no longer overwritten immediately in 3.x: https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/Sources/modMediaSource.php#L1319-L1332

Are you affected by this bug? The properties are parsed when retrieved using `modMediaSource::getPropertyList()`.

**Comment by dmoagx** [comment]
No, I'm not personally affected by this. Just found it while stepping through the code.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. I close this issue because it has been fixed in 3.x.
