### ISSUE TITLE
2.7.3 upgrade deprecated message

### ISSUE THREAD

**Issue by rutkas** [modxcms/revolution#15030]
After copying new files to modx htdocs dir and running /setup to perform update (for the first time):

`Deprecated: Array and string offset access syntax with curly braces is deprecated in /var/www/htdocs/setup/includes/parser/modinstallsmarty.class.php on line 75`

updating from 2.7.2 to 2.7.3, PHP Version 7.4.3

**Comment by rutkas** [comment]
One more deprecated during upgrade was noticed:

> Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /var/www/htdocs/core/model/modx/modx.class.php on line 678

**Comment by muzzwood** [comment]
I can confirm this is happening on fresh installs as well. 
PHP 7.4.4

It showed on the summary screen after installation was successful.

**Comment by jurismai** [comment]
Deprecated: Array and string offset access syntax with curly braces is deprecated in setup/includes/parser/modinstallsmarty.class.php on line 75

PHP 7.4.x  

PHP 7.3.x is still working.

change the curly braces to normal () did it

**Comment by Ibochkarev** [comment]
> Deprecated: Array and string offset access syntax with curly braces is deprecated in setup/includes/parser/modinstallsmarty.class.php on line 75
> 
> PHP 7.4.x
> 
> PHP 7.3.x is still working.
> 
> change the curly braces to normal () did it

Fixed:
https://github.com/modxcms/revolution/pull/15082/files#diff-136a6baaf63dfcefab2c3fbca282db72R75

**Comment by Ibochkarev** [comment]
Fixed #15032 
@modxbot close
