### ISSUE TITLE
pcre8 doesn't match emails

### ISSUE THREAD

**Issue by it-scripter** [modxcms/revolution#15040]
### Summary
In one (only one) of my installations of MODX I have a  problem to send emails.
In core/model/modx/mail/phpmailer/class.phpmailer.php each email address (independently the purpose) will check against certain rules. In this installation, the validation routine detects PCRE8 (cause version 10.30 is installed). 
But there is no match of the regular expression against any email.  Therefore no email is sendable.  

I guess there is an error in PCRE 10.30 - and this is PCRE2
If I test it with https://regex101.com/, it works fine. 
Is the problem known or has it occurred before? 

My solution at the moment is to avoid using pcre8 for the validation of email addresses with PCRE 10.30. 
So I changed the line 1087 with
`
if (version_compare(PCRE_VERSION, '8.0.3') >= 0 AND version_compare(PCRE_VERSION, '10.30 2017-08-14') !== 0) {
`
### Step to reproduce
Nothing special, but the following environment.
 
### Environment
MODX version: 2.7.2 (code in 2.7.3 is identically I could see so far)
PHP 7.3.2
PCRE Library Version: 10.30 2017-08-14
PCRE Unicode Version: 10.0.0
PCRE JIT Support: not compiled in

**Comment by Mark-H** [comment]
This sounds like an issue in phpmailer and is probably better to report there. When there's a new version of phpmailer available, we can incorporate that into MODX.

**Comment by it-scripter** [comment]
Right, Mark!
Thanks for your hint to phpmailer. Didn't noticed, that this is the original phpmailer class.
And yes, the bug was reported before: https://github.com/PHPMailer/PHPMailer/issues/1641
The phpmailer bug is closed now.  

The actual phpmailer is in version 5.5 - MODX 2.7.3 uses 5.2.7, right?
Now the standard validator is "PHP" and pcre8 isn't used - normally, I guess. 

That would also be a short fix for us.

**Comment by JoshuaLuckers** [comment]
MODX 2.7.3 includes PHPMailer 5.2.27.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this bug and help make MODX better, because it is a bug in an external library I'm closing this issue.
