### ISSUE TITLE
Clear system/phpthumb connector 't 'property

### ISSUE THREAD

**Issue by smahelos** [modxcms/revolution#15054]
### Summary
Clear system/phpthumb connector property 't'

### Step to reproduce
just open filemanager and in log you will see error

### Observed behavior
in manager error log: modphpthumb.class.php : 97) Detected attempt of using private parameter `t`

### Expected behavior
nothing in manager log

### Environment
MODX 2.7.3, apache 2.4.39, mysql 5.7.26, google chrome latest

**Comment by Jako** [comment]
It could be better to detect, why the 't' property is set and if it is in use.

**Comment by smahelos** [comment]
Hallo, thank you very much for your response Jako!

I don't know exactly when(in which version of modx) and why it was added to 
**core/model/modx/sources/modfilemediasource.class.php** 
Neer line 277 and 1134 there is passed new parameter in $query_data array to fc "http_build_query"

't' => $file->getMTime(),

But I think it is similar issue as
https://github.com/modxcms/revolution/issues/14093
and than you send FIX for it 
https://github.com/modxcms/revolution/pull/14096.

I can workaround it by myself in my project, but i want to send PR to be it in stable version of MODx

**Comment by smahelos** [comment]
Thank you again Jako! 
That's exactly what I wanted to do, but came back here now and it's already done by yourself...

Good job, sm
