### ISSUE TITLE
/connectors/system/phpthumb.php 500-error after upgrade 2.7.3-pl

### ISSUE THREAD

**Issue by codexx20** [modxcms/revolution#15067]
### Summary
After upgrading to 2.7.3-pl the /connectors/system/phpthumb.php return 500 errors on all images in the manager. 

### Step to reproduce
Upgrade from 2.6.5-pl to 2.7.3-pl and see the media browser for example. 

### Observed behavior
No thumbs shown, 500 error in developer screens and no further logging to the error log or server level logs. 

### Expected behavior
Showing nice thumbs :-)

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. Does clearing the MODX cache solve this issue?

**Comment by codexx20** [comment]
Hi Joshua,

No unfortunately it doesn’t.

**Comment by JoshuaLuckers** [comment]
Does it help if you reinstall MODX?

**Comment by codexx20** [comment]
Hi Joshua,

Reinstalling is impossible because then I'm losing all data. My site has over 500 resources, it's impossible to overwrite that data.

**Comment by JoshuaLuckers** [comment]
Can you provide some details about your environment, like PHP versions, GD version etc?

**Comment by codexx20** [comment]
PHP: 5.3.29  <= Maybe this is my issue? 
GD: bundled 2.1.0 compatible

I've noticed another issue, some $_POST actions don't function anymore.

**Comment by JoshuaLuckers** [comment]
PHP 5.3 isn't supported, please make sure to use a more recent version of PHP (5.6 is the minimum required version).

**Comment by codexx20** [comment]
This solved the issues. Thanks Joshua.

**Comment by Ruslan-Aleev** [comment]
This is not the first time that there have been errors related to the PHP version.
It may make sense to display a message in the manager panel, here:

![php_error](https://user-images.githubusercontent.com/12523676/81673226-f7deed80-9453-11ea-9301-df84857a0fd0.png)

**Comment by JoshuaLuckers** [comment]
@codexx20 Thanks for letting us know! 

@Ruslan-Aleev You are right, this will be solved once I finish PR 14999
