### ISSUE TITLE
Delete account section, it is not particularly useful

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15084]
### Summary
In the current version of MODX there are sections of the account and user. However, they are almost no different. I think it would be right to leave only the user section and hide the areas / tabs **if the user is not a sudo**.
A link from the account to change to the user (icon in main manu, and other).

User section
![user_1](https://user-images.githubusercontent.com/12523676/83301744-d37c6280-a202-11ea-9168-cc1bf304f1d9.png)

Account section
![user_2](https://user-images.githubusercontent.com/12523676/83301865-06265b00-a203-11ea-88a7-14b1b65a6e6e.png)
_All fields are in the user section. And the Recent Resources tab is also not needed - there is a widget on the home page._

### Why is it needed?
First, there will be less duplicate code. Secondly, the user will not get confused in unnecessary entities.

### Suggested solution(s)
I think it would be right to leave only the user section and hide the areas / tabs **if the user is not a sudo**.

### Related issue(s)/PR(s)
None

**Comment by Mark-H** [comment]
The account section allows any user to change their password and personal information - the users section is for managing any other user. That seems like two very different use cases we both need?

**Comment by Ruslan-Aleev** [comment]
Yes, these are different sections. But in fact, all the data that is set in the account section (including password) can be changed in the user section and vice versa.
I would leave the ability to manage users only for sudo, and non sudo can only edit their personal data.

![user_2](https://user-images.githubusercontent.com/12523676/83851216-b2dc6d00-a71a-11ea-91f1-c5ef4f9c6da7.png)

Perhaps I do not see the whole picture, and my proposal is not very correct. I will be glad to discuss :)

**Comment by theboxer** [comment]
I don't agree with this change at all.

Restricting user management just for `sudo` users seems also like a huge step back, if you consider how granular MODX permissions are.

As Mark mentioned, there are **valid** different use-cases for both of these sections.
