### ISSUE TITLE
Wrong headline on edit content type modal dialog.

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#15089]
### Summary

Wrong headline on edit content type modal dialog.

### Step to reproduce
* Open https://your-domain.com/manager/?a=system/contenttype
* Right click on any content type. 
* Click "edit"

### Observed behavior
A Modal pops up with a modal header "New Content Type" (see screenshot below).

![image](https://user-images.githubusercontent.com/667315/83974181-ac511f80-a8eb-11ea-8d28-4a5222ae28d1.png)

This is misleading as you are editing an already existing modal type.

### Expected behavior

The header should be "Edit Content Type"

### Environment
Current MODX Version (2.7.3). Could not check older versions so far.

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/13554
