### ISSUE TITLE
When changing a template for a new document - &id=undefined appears in the url

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15090]
### Summary
When changing a template for a new document - &id=undefined appears in the url:

![new_doc](https://user-images.githubusercontent.com/12523676/84005782-52e20280-a976-11ea-8a40-a52edce2c0dd.gif)

This is because there is no verification of the operation — creation or editing: https://github.com/modxcms/revolution/blob/0c1289f79d35417ae3ef4f2393427a42db368dd6/manager/assets/modext/widgets/resource/modx.panel.resource.js#L339

The bug is not critical, but it looks strange.

### Environment
MODX 2.x>

**Comment by pepebe** [comment]
This happend, when you change the template BEFORE you have set a title. Its an annoying bug, but easily prevented. That being said, it happens to me a lot :(

**Comment by sergant210** [comment]
> This happend, when you change the template BEFORE you have set a title. 

@pepebe This happens because the response object hasn't the id property. 
![74eb821e21](https://user-images.githubusercontent.com/4679725/84225292-74aec700-aae7-11ea-8d37-00b584b5a8b9.jpg)
and this fact is not verified.

**Comment by sergant210** [comment]
In addition
![2020-06-10_07-20-11](https://user-images.githubusercontent.com/4679725/84226699-30bdc100-aaeb-11ea-83d7-6594340ca391.png)
![2020-06-10_07-18-32](https://user-images.githubusercontent.com/4679725/84226700-31eeee00-aaeb-11ea-8286-671bb1061c08.png)
The same actions, but the parameters are different. Maybe it's normal. I don't know.
