### ISSUE TITLE
Make the tab active if there are errors in the form

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15116]
### Summary
@Alroniks made extremely useful functionality that catches the tab with errors and makes it active - https://github.com/modxcms/revolution/pull/14235

**But, as it turned out, tab does not always become active.**

_For example, if the name TV contains invalid characters:_

![tab_error_1](https://user-images.githubusercontent.com/12523676/84759977-1c3c6580-afd0-11ea-9606-bf279acc76f9.gif)

_Although if the name TV is empty, the tab is activated, everything is fine:_

![tab_error_2](https://user-images.githubusercontent.com/12523676/84759985-1d6d9280-afd0-11ea-9290-d24b5b9f6285.gif)

### Expected behavior
Make the tab active if there are ANY errors in the form

### Environment
MODX 2.x >

**Comment by Ruslan-Aleev** [comment]
Most likely related with https://github.com/modxcms/revolution/issues/15088

**Comment by smg6511** [comment]
I have a solution for this and will be submitting a PR in the next few days. The reason this happens (in the other element form panels as well) is the failure method that ultimately fires the failureSubmit event is missing. The reason it works when the name field is blank is that the native extjs allowBlank validation is triggering the failure whereas invalid field value errors are reported in the submission failure response.

**Comment by Ruslan-Aleev** [comment]
> I have a solution for this and will be submitting a PR in the next few days.

It would be great! If you have a desire, look at this issue - https://github.com/modxcms/revolution/issues/15088 they are related.

**Comment by smg6511** [comment]
Almost finished on this issue and #15088 that you mentioned. Trying to cover as many scenarios as I can think of ... the last of which (for now) is handing the behavior when tvs are moved into custom panels via manager customization rules. I should have the PR very soon...

**Comment by JoshuaLuckers** [comment]
> I should have the PR very soon...

You can always create a PR and mark it as draft! We really appreciate the effort!

**Comment by Mark-H** [comment]
Fixed in 2.8
