### ISSUE TITLE
User-entered data in a TV with a Listbox (Multi-Select) type is not displayed in the resource form

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15136]
### Summary
There is another problem with setting "**Force Selection to List:**" (forceSelection). It allows you to enter values not from the list. And for a multiple lis the values entered by the user are not displayed in the TV, in the resource form.

Listbox (Multi-Select):

![listbox_m_forse](https://user-images.githubusercontent.com/12523676/85009571-50965a00-b167-11ea-908a-6ed262004f51.gif)

Although there is no such problem for Listbox (Single-Select):

![listbox_s_forse](https://user-images.githubusercontent.com/12523676/85009578-512ef080-b167-11ea-931d-bcfede1e0127.gif)

p.s. Personally, I am against the "forceSelection" setting as a whole, it creates potential bugs. Why let the user enter values other than specified in the "Input Option Values"? You can simply use TV text if you need data not from the "Input Option Values".

### Expected behavior
Display user input

### Environment
MODX 2.7>
Related with https://github.com/modxcms/revolution/pull/14957

**Comment by JoshuaLuckers** [comment]
To clarify: the TV doesn't show the manually entered value that's saved in the database for that particular resource, which it should just like the single select.
