### ISSUE TITLE
The "Set to default" link does not work for some TVs

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15143]
### Summary
It is not clear how to set the default value for TV with the type image and file, multiple list, etc. in the form of a resource.
Somewhere "Set to default" link works, but somewhere not:

![tv_def](https://user-images.githubusercontent.com/12523676/85953611-5f0c1f00-b97a-11ea-811b-7a953d156ede.gif)

### Environment
MODX 2>

**Comment by JoshuaLuckers** [comment]
Code for reference: https://github.com/modxcms/revolution/blob/5a6051536b47d5ccc499f81afd0ae3ec8c5e8265/manager/templates/default/resource/sections/tvs.tpl#L45-L71

**Comment by alroniks** [comment]
I am closing this one as we have a detailed and more common issue that covers more cases. Move discussion here please https://github.com/modxcms/revolution/issues/14945 if you want.
