### ISSUE TITLE
Export in "Access Control Lists" section causes 500 error

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15194]
### Summary
Export Policy and Policy Template in "Access Control Lists" section causes 500 error:

![export_acl](https://user-images.githubusercontent.com/12523676/90047309-62652b00-dcda-11ea-8022-7cd6255b7312.gif)

Perhaps export in other sections will cause the same error, I don't remember where else there is export of files.

### Related issue(s)/PR(s)
N/A

### Environment
MODX 3 alpha-3

**Comment by JoshuaLuckers** [comment]
> Fatal error: Uncaught Error: Call to a member function make() on null in ~/Projects/modx/modx-3x/core/src/Revolution/Processors/Model/ExportProcessor.php on line 99

**Comment by Ibochkarev** [comment]
Fixed #15201 
@modxbot close
