### ISSUE TITLE
Emoji symbols can cause errors on the site

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15207]
### Summary
Now emoji are already used more often than words, and their presence on the site: in forms, comments, content, this can cause errors. Several users have already reported this bug.

The problem is in the base encoding.
By default, MODX uses `utf8mb4`. Perhaps for MODX 3 it is worth changing the encoding to `utf8mb4_unicode_ci`

### Environment
MODX >

**Comment by Mark-H** [comment]
Where does MODX define the default collation/charset? I can only think of the setup, but as far as I know that dynamically selects the server default and is not hardcoded to anything in particular?

**Comment by Ruslan-Aleev** [comment]
Yes, probably, you are right. Most likely I was mistaken, I will clarify this question, and close the issue if necessary.
