### ISSUE TITLE
Problem activating media source popup for TVs

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15204]
### Summary
Setting the media source for TVs always requires two tries to activate the media source selection list. 

### Step to reproduce
Edit a TV and try to change the media source. Double-click on the media source name to activate the popup.

### Observed behavior
The text turns into a selection element. Click on the media source name, or click the double arrows at the right edge of the selection element, to activate the popup list. A brief "loading" message appears, then the selection element goes away, leaving the media source as just text again. Double-click the media source again, and the selection element appears again. This time, clicking the selection element brings up the popup list with media sources.

### Expected behavior
The selection list should work the first time it's activated.

### Environment
All versions of MODX.

**Comment by Ruslan-Aleev** [comment]
Already fixed in:
https://github.com/modxcms/revolution/pull/15122
https://github.com/modxcms/revolution/pull/15123

**Comment by Ibochkarev** [comment]
@modxbot close
