### ISSUE TITLE
Tried to create chunk ...

### ISSUE THREAD

**Issue by blue-eyed-devil** [modxcms/revolution#15219]
ParseError: syntax error, unexpected 'access' (T_STRING), expecting ')'

 

Errors:

 xPDO\Cache\xPDOFileCache->get(string "lexicon/en/core/resource", Array ( [cache_key] => lexicon_topics [cache_handler] => xPDO\Cache\xPDOFileCache [cache_format] => 0 ) )
 xPDO\Cache\xPDOCacheManager->get(string "lexicon/en/core/resource", Array ( [cache_key] => lexicon_topics [cache_handler] => xPDO\Cache\xPDOFileCache [cache_format] => 0 ) )
 MODX\Revolution\modLexicon->loadCache(string "core", string "resource")
 MODX\Revolution\modLexicon->load(string "resource")
 MODX\Revolution\Processors\Processor->run()
 MODX\Revolution\modX->runProcessor(string "MODX\Revolution\Processors\Security\User\GetRecentlyEditedResources", Array ( [limit] => 10 [user] => 1 ) )
 modDashboardWidgetRecentlyEditedResources->render()
 MODX\Revolution\modDashboardWidgetInterface->process()
 MODX\Revolution\modDashboardWidget->getContent(object)
 MODX\Revolution\modDashboard->render(object, object)
 WelcomeManagerController->process(Array ( ) )
 MODX\Revolution\modManagerController->render()
 MODX\Revolution\modManagerResponse->outputContent(Array ( ) )
 MODX\Revolution\modManagerRequest->prepareResponse()
 MODX\Revolution\modManagerRequest->handleRequest()

**Comment by blue-eyed-devil** [comment]
An in console is following:

GET http://***.net/connectors/lang.js.php?ctx=mgr&topic=topmenu,file,resource,&action= net::ERR_ABORTED 500 (Internal Server Error)
DevTools failed to load SourceMap: Could not load content for http://***.net/manager/assets/lib/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
(index):18 GET http://***.net/connectors/modx.config.js.php?action=&wctx=mgr net::ERR_ABORTED 500 (Internal Server Error)
modx.jsgrps-min.js:1 Uncaught ReferenceError: _ is not defined
    at modx.jsgrps-min.js:1
(anonymous) @ modx.jsgrps-min.js:1
layout.js:1 Uncaught TypeError: Cannot set property 'Default' of undefined
    at layout.js:1
(anonymous) @ layout.js:1
modx.jsgrps-min.js:1 Uncaught ReferenceError: _ is not defined
    at modx.jsgrps-min.js:1
    at ext-all.js:21
    at b (ext-all.js:21)
(anonymous) @ modx.jsgrps-min.js:1
(anonymous) @ ext-all.js:21
b @ ext-all.js:21
setInterval (async)
e.delay @ ext-all.js:21
(anonymous) @ ext-all.js:21
fire @ ext-all.js:21
b @ ext-all.js:21
ext-all.js:21 Uncaught TypeError: b[(d.xtype || e)] is not a constructor
    at Object.create (ext-all.js:21)
    at MODx.load (modx.js?v=31340c78:86)
    at (index):22
    at ext-all.js:21
    at b (ext-all.js:21)

**Comment by blue-eyed-devil** [comment]
There must be some issue with files inside cache/lexicon_topics/ because when it starts throwing 500 errors and I delete whole folder cache/lexicon_topics it works back again

**Comment by Jako** [comment]
When this issue occurs again, please download the files in cache/lexicon_topics and validate them.

**Comment by blue-eyed-devil** [comment]
so the problem is in lexicon/en/core/default.cache.php
on line 535 is an array node either with uncommented quotes or unfinished node:
`534 -  'refresh_failure' => 'Refresh failed! (NOTE: this cache partition may just be empty)',`

`535 -  'refresh_lexicon_topics' => 'Clearing the lexicon topics cac=> 'Last Page',`

`536 -  'ext_mindate' => 'This date is before the minimum date.',`

**Comment by Jako** [comment]
That looks like a hickup in the caching process. I don't see any reasons for this in the 'refresh_lexicon_topics' or 'ext_last' lexicon entry.

**Comment by alroniks** [comment]
I am closing it due to inactivity. Please, reopen if needed.
