### ISSUE TITLE
Links to "Help" do not work in some sections

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15216]
### Summary
Links to "Help" do not work in some sections and display information for the 2.x branch.

![help_links](https://user-images.githubusercontent.com/12523676/91577437-5a9bbc80-e951-11ea-81cc-7d88ecd50b54.gif)

### Environment
MODX 3.0.0-alpha3

**Comment by Mark-H** [comment]
This may require tweaking the base help url in MODX and perhaps also setting up some redirects on the docs-side.

**Comment by Ibochkarev** [comment]
Related https://github.com/modxcms/revolution/pull/15411

**Comment by Ibochkarev** [comment]
@Mark-H We've updated the system setting and updated the rules for redirects. It is necessary to merge in the documentation site with the 3rd version and you can close this problem.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/15572
