### ISSUE TITLE
Synchronize View Resouce and Edit Resource

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#1522]
bobray created Redmine issue ID 1522

I don't think any information should be available in View that isn't available in Edit. It will be annoying to have to switch to View while editing a resource, for example, to see the cached output. I can see View having a subset of the info available while editing but to have stuff in View that's not in Edit just seems wrong, IMO.

**Comment by adamwintle** [comment]
This is a pretty ancient bug. Is it referring to the Resource View button which loads a front-end preview? 

@BobRay are you suggesting that somewhere in the same edit screen is a live preview of the finished rendered page?

**Comment by sottwell** [comment]
The original had to do with Evo. Evo used to have a view of the cached page. I don't know if it still does or not.

**Comment by adamwintle** [comment]
@sottwell ah okay, that makes sense.  I don't have the privileges to close issues, but maybe this one can be just closed by someone else?

**Comment by OptimusCrime** [comment]
@modxbot close
