### ISSUE TITLE
Add explanatory text in the window for creating a directory in the file tree

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15225]
### Summary
When creating a directory inside a media source - `/` is always specified in the creation window instead of the root folder of the media source.
Those it is not clear where the directory is created, inside the root folder of the media source, or inside the root folder of the site.

![source-path](https://user-images.githubusercontent.com/12523676/92309122-759eaa00-efab-11ea-8547-3e22189c3d85.gif)

We need to add clarifying text below the field.

For example:
![source-path-2](https://user-images.githubusercontent.com/12523676/92309123-77686d80-efab-11ea-9400-7e561d46a8d4.png)

### Environment
MODX 2>

### Why is it needed?
UX improvement

**Comment by alroniks** [comment]
Merged
