### ISSUE TITLE
The form for creating a lexicon entry does not work correctly

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15223]
### Summary
You can create an lexicon entry without set either "Namespace", "Topic", or "Language", because the dropdowns are editable.
The entry will be created visually, but then it cannot be found in the search.

**We need to make these lists required.**
By the way, this form has no required fields at all, which is strange.

![lexicon-bug](https://user-images.githubusercontent.com/12523676/91947140-2553ed80-ed08-11ea-884f-7c0337d7a4d0.gif)

Perhaps there are such bugs in other creation windows too, we need to check.

### Environment
MODX 2.x >

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/logic-behind-structure-of-processors/4583/1

**Comment by Ibochkarev** [comment]
Fixed in #15892
