### ISSUE TITLE
XXE Vulnerability

### ISSUE THREAD

**Issue by dahua966** [modxcms/revolution#15237]
snipped

**Comment by Mark-H** [comment]
The email is security@modx.com. I'm not sure about that form (will get that checked), but publicly posting vulnerability details rather than asking somewhere on how to privately disclose if the first avenue doesn't work is... a little disappointing.

**Comment by Mark-H** [comment]
The security report form seems to work as expected, test email sent and arrived.

**Comment by Ruslan-Aleev** [comment]
It seems to me that @dahua966  is talking about the page that is listed in the template for "Report a security vulnerability" on github. There is a page listed - https://modx.com/community/contribute/report-a-security-issue and it doesn't work.

**Comment by Mark-H** [comment]
@jaygilmore / @rthrash can you get the old URL https://modx.com/community/contribute/report-a-security-issue to redirect to the new form at https://modx.com/about/security-reports?

@Ruslan-Aleev Where are you seeing that URL on? I'm only seeing a reference to security@modx.com in the CONTRIBUTING.md.

**Comment by Ruslan-Aleev** [comment]
@Mark-H In the file https://github.com/modxcms/revolution/security/policy, you can go to it when creating a security issue.

![security](https://user-images.githubusercontent.com/12523676/93356921-70154f80-f848-11ea-991e-03376be1424a.png)

**Comment by Mark-H** [comment]
Ah, there it is. Fixed, thanks.

**Comment by Mark-H** [comment]
Fixed in #15238 - @dahua966 if you want to take a look at that and confirm it resolves it that would be appreciated.
