### ISSUE TITLE
If a resource is deleted, then its parent is not shown in the breadcrumbs of the manager

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15243]
### Summary
If a resource is deleted, then **its parent is not shown** in the breadcrumbs of the manager.
Quite an interesting bug :)

### Observed behavior
![bc_bug](https://user-images.githubusercontent.com/12523676/93495175-8093fb80-f916-11ea-9a5d-fa2bd0171316.gif)

### Environment
MODX 3-alpha3

**Comment by Jako** [comment]
Maybe the whole breadcrumb path is not shown.

**Comment by Ruslan-Aleev** [comment]
Not sure, maybe.

**Comment by theboxer** [comment]
Confirmed, the whole path doesn't show up.
