### ISSUE TITLE
MODX3: Some visual bugs

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15247]
### Summary
1) In a very strange way, the form is displayed if the screen width is less than 1025px, for example, 1024px (an empty space appears on the right):

![width_1024](https://user-images.githubusercontent.com/12523676/93573765-37888980-f9a0-11ea-86e2-369b41270615.png)

2) The collapse content icon overlaps the buttons.

![icon_arrow](https://user-images.githubusercontent.com/12523676/93575416-4708d200-f9a2-11ea-9088-c16ff49189bc.gif)

### Environment
MODX 3-alpha3

**Comment by Ruslan-Aleev** [comment]
@JoshuaLuckers

> Then there is still the problem of the elements below not having enough space. I looked into this a while ago but didn’t find a good solution without moving the elements to above/below the main section.

@Jako 

> Displaying the whole element below, in a new tab or appended to 'settings' could be an option (only for small screens).

@Ruslan-Aleev 

> It is necessary to reduce both the menu on the left in width and the tree on the left, because even at significantly width (1280px), the interface looks skinny. And for small screens, yes - we need to move it down or add a new tab.

**Comment by alroniks** [comment]
Seems it solved by merged PRs, but @Ruslan-Aleev please check. If something left, please, create a new issue.
