### ISSUE TITLE
Display or errors during setup breaks the installation experience

### ISSUE THREAD

**Issue by barryhughes** [modxcms/revolution#15253]
### Summary
Problems such as using curly braces for array access ([seen here](https://github.com/modxcms/revolution/blob/v2.7.3-pl/setup/includes/parser/modinstallsmarty.class.php#L75)&mdash;though this specific problem has [already fixed been fixed](https://github.com/modxcms/revolution/commit/0bb5701c01fab7fffa6bf31fdca9f8e80fa22993), just not released) can break the installation/initial setup experience, because the display of errors is turned on [(see here)](https://github.com/modxcms/revolution/blob/v2.7.3-pl/setup/includes/request/modinstallrequest.class.php#L24).

This is at best annoying, because errors appear at the top of the installation screens (reduces confidence) and at worst breaks the setup experience entirely, because when a form submission is made it leads to one of these page stoppers: _"Cannot modify header information - headers already sent."_

...Just to emphasize, I realize the curly brace error is fixed and just hasn't shipped yet as a public release: the problem (in my eyes) is the decision to display errors during installation (or, more specifically, to use the PHP itself for this purpose instead of something more graceful such as a custom error handler&mdash;which would allow control over where and when errors are displayed).

### Step to reproduce
* Be sure to use a modern version of PHP (I used 7.4.x).
* Download 2.7.3 (latest stable/public version at time of writing).
* Run through the setup procedure.

### Observed behavior
* Error messages display at the top of various setup/installation screens.
* Form submissions (example: language selection) break, because the errors are output before redirect can take place.

### Expected behavior
* I should be able to complete initial setup without modifying code (I adjusted `modinstallrequest.class.php` to work around this problem).

### Related issue(s)/PR(s)
* No PR, yet ;-) ... interested in your thoughts as to whether `ini_set('display_errors', 1)` in modinstallrequest.class.php is desirable or not (I see this same thing is also true in [3.0.0-alpha2](https://github.com/modxcms/revolution/blob/v3.0.0-alpha2/setup/includes/request/modinstallrequest.class.php)).

### Environment
* MODX 2.7.3-pl
* PHP 7.4.10

**Comment by Mark-H** [comment]
This was added in v2.5.2 in PR #13107. That seems to have gone in without much discussion at the time. 

I can see the value in making sure users see an error if something Seriously Bad (tm) happens and their host does not display or log errors somewhere easily accessible, however I also understand we don't want to break the install for something like the curly braces warning (#15082).

Perhaps the suitable middle way here is to keep `display_errors`, but limit `error_reporting` to a higher level that ignores warnings like this one?

**Comment by barryhughes** [comment]
Yep that sounds reasonable (and, would also be easier and faster to change than something more involved, like a custom error handler).

...I guess "what's best" might depend a little on what sort of technical level we generally expect new users of MODX to be at :thinking:

**Comment by alroniks** [comment]
I disagree with the approach when we lowering the error level just to ignore some issues. It is very important to recognize a potential issue during setup. It may be worse when the site is already run on production. So I prefer to leave the current implementation and solve the issues themselves, like curly braces which were deprecated in the last PHP versions (already fixes).

I tend to close it, but feel free to reopen it.
