### ISSUE TITLE
Wrong image dimensions in the media browser

### ISSUE THREAD

**Issue by Oetzie** [modxcms/revolution#15255]
### Summary
The media browser shows the wrong image dimensions.

### Step to reproduce
Upload an image bigger then 800 pixels in the media browser the media browser, the image dimensions on the right panel displays the wrong image size. 

I have an image with the 1920x700 size, the media browser displays 800x292 pixels.

### Environment
MODX 3

Media browser size:
![Schermafbeelding 2020-09-21 om 10 28 49](https://user-images.githubusercontent.com/5370832/93747726-651b4000-fbf7-11ea-82c3-267c7fcebd12.png)

Real size:
<img width="274" alt="Schermafbeelding 2020-09-21 om 10 29 49" src="https://user-images.githubusercontent.com/5370832/93747767-76644c80-fbf7-11ea-940e-a43317cc7fae.png">

**Comment by Ruslan-Aleev** [comment]
Yes, there is a bug.
Thank you for participating!

**Comment by wax100** [comment]
I even fix this bug somewhere , but as  usuall did not add it to github

**Comment by Ibochkarev** [comment]
> I even fix this bug somewhere , but as usuall did not add it to github

Please find a fix and kill this error =)
