### ISSUE TITLE
JavaScript error while creating a new folder in the root of a media source

### ISSUE THREAD

**Issue by Oetzie** [modxcms/revolution#15263]
### Summary
When you you create a new folder in the root of the media source you will get a JavaScript error.

TypeError: Cannot read property 'constructor' of undefined
 /manager/assets/modext/widgets/system/modx.tree.directory.js:593

### Step to reproduce
Open de the media browser and create a folder (do not select any parent folder), you will get a JavaScript error.

### Fix
Change the line 593 of modx.tree.directory.js:
`if (this.cm.activeNode.constructor.name === 'constructor' || parent === '' || parent === '/') {`
To:
`if ((this.cm.activeNode && this.cm.activeNode.constructor.name === 'constructor') || parent === '' || parent === '/') {`

### Environment
MODX 3 and at least MODX 2.7.3

**Comment by Ibochkarev** [comment]
I confirmed bug in 2.7.3
![image](https://user-images.githubusercontent.com/2138260/93872026-629d1100-fcf1-11ea-95d1-64ee09f78659.png)

**Comment by Ibochkarev** [comment]
The proposed solution works.

**Comment by Mark-H** [comment]
Fixed in 2.8
