### ISSUE TITLE
Incorrect display of files or directories in the file tree, if the name contains +

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15271]
### Summary
Incorrect display of files or directories in the file tree if the directory or file name contains `+`:
- Files are no longer displayed in the file tree if they are inside a directory with a “+” in the name (although the file is in the directory).
- And the preview for the picture also ceases to be displayed if there is a “+” in the name of the picture.

However, there are no such problems in the MODX file browser.
There is no bug in MODX3 either.

More information here -https://community.modx.com/t/creating-a-directory-which-ends-with-a-doesnt-load-in-modx-dashboard/3135

Possible explanation:
> Maybe it has to do with the fact, that a plus sign in the query string of a url represents a space.
If the manager makes a call to .../connectors/index.php?action=browser/directory/getList&id=gl+/&type=dir, the id-parameter is possibly interpreted as gl plus a space.

### Environment
MODX 2.7.3

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/creating-a-directory-which-ends-with-a-doesnt-load-in-modx-dashboard/3135/5

**Comment by Ruslan-Aleev** [comment]
@rthrash Yes, I indicated this in the description of the issue :)

**Comment by Mark-H** [comment]
Pssst, @rthrash is a bot. Don't tell anyone tho.

**Comment by pixelstuff** [comment]
Possibly related. If you create a folder named [[++holidaytheme]] in the file system the MODx folder tree (left column) will create an infinitely nested loop of those folders.

![image](https://user-images.githubusercontent.com/428855/97478165-f41e2500-1926-11eb-9b73-c505512e39f6.png)

https://community.modx.com/t/file-folder-looping-or-something-bug/3253

**Comment by alroniks** [comment]
It fixed by merged PR
