### ISSUE TITLE
Setting the resource [[*alias_visible]] is disabled if you change the template when creating a resource before saving the resource

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15283]
### Summary
The resource setting `[[*alias_visible]]` is disabled **if you change the template when creating a resource BEFORE saving the resource**.

### Step to reproduce
1) Create a resource, but **not save the resource**.
2) Change the resource template and save the resource.
3) Open the "Settings" tab and look at `[[*alias_visible]]`.

### Observed behavior
![res_alias](https://user-images.githubusercontent.com/12523676/95343234-f7db0080-08c0-11eb-97af-2757ec5956dc.gif)

### Expected behavior
Setting `[[*alias_visible]]` shouldn't change.

### Environment
MODX 2.x, 3.x

**Comment by sergant210** [comment]
The same for "empty cache" checkbox.

**Comment by Ibochkarev** [comment]
Fixed #15289 

@modxbot close
