### ISSUE TITLE
core/xpdo/COPYING file has no file extension

### ISSUE THREAD

**Issue by patrickatwsrn** [modxcms/revolution#15291]
## Bug report
Just noticed that there is a file without a file extension in core/xpdo

![grafik](https://user-images.githubusercontent.com/68318893/95456779-2663e480-0970-11eb-936f-7d4832a83539.png)

This seems to be the xpdo licence text and it has not been update in 10 years.

### Expected behavior
I don't know what kind of problems might arise from this, but I believe it can't hurt to make it a .txt file.

**Comment by Mark-H** [comment]
That's also in the [xPDO repository (2.x)](https://github.com/modxcms/xpdo/tree/2.x/xpdo) so technically better reported there. However I honestly don't see any harm in this file (to be fair - no value either) and it has already been removed in 3.x so I'd consider this already solved.
