### ISSUE TITLE
Incorrect display of paths for files (path mismatch)

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15302]
### Summary
After merging PR https://github.com/modxcms/revolution/pull/15262 for an open file, the active class was no longer added to the file tree.

![file_class](https://user-images.githubusercontent.com/12523676/96333464-bc83c300-1072-11eb-82ae-877fa7437e74.png)

This happens because the validation condition (`node.id == activeFile`) is not working (see https://github.com/modxcms/revolution/pull/15228).
In `node.id` we have, for example, `images/product/file.txt`, and in `activeFile` (taken from url) we get `images%2Fproducts%2Ffile.txt`

### Step to reproduce
Open any file attached to the folder in the element tree - the active class will not appear. Although, if you open the file at the root, then there is no problem, because there is no `/` in the path and id.

Of course, we can just decode the `node.id` in the condition, but we need to be sure that there are no more problems of this kind. For example, the same kind of problem is relevant for 3.x - https://github.com/modxcms/revolution/issues/15244

**We need to bring it to a single format.**

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/15244
https://github.com/modxcms/revolution/pull/15228
https://github.com/modxcms/revolution/pull/15227

### Environment
MODX 2.8.0

**Comment by alroniks** [comment]
I am not sure that we have to fix it. In 3.x it works as expected.

**Comment by Ruslan-Aleev** [comment]
Yes, there is no such problem for 3.x. Both URL and ID display the decoded path, for example: `images%2Fproducts%2Ffile.txt`.
Although some time ago there was.

**Comment by wfoojjaec** [comment]
This might be related https://github.com/modxcms/revolution/pull/15505
Both sides (back and front) need to have id encoded and decoded, or left unchanged.

After applying https://github.com/modxcms/revolution/pull/15709 this issue is resolved, **but only for** files inside website root directory. It remains broken for other files in tree, in nested directories.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/15835
