### ISSUE TITLE
Systeminformation is no longer accessible

### ISSUE THREAD

**Issue by sscWhitevision** [modxcms/revolution#15303]
### Summary
After Update from 2.7.x to 2.8.0 - Systeminformation is no longer accessible

Fatal error: Uncaught Error: Class 'PHPMailer\PHPMailer\PHPMailer' not found in /Applications/MAMP/htdocs/dev/public/modx/controllers/default/system/info.class.php:47 Stack trace: #0 /Applications/MAMP/htdocs/dev/private/model/modx/modmanagercontroller.class.php(155): SystemInfoManagerController->process(Array) #1 /Applications/MAMP/htdocs/dev/private/model/modx/modmanagerresponse.class.php(79): modManagerController->render() #2 /Applications/MAMP/htdocs/dev/private/model/modx/modmanagerrequest.class.php(187): modManagerResponse->outputContent(Array) #3 /Applications/MAMP/htdocs/dev/private/model/modx/modmanagerrequest.class.php(135): modManagerRequest->prepareResponse() #4 /Applications/MAMP/htdocs/dev/public/modx/index.php(59): modManagerRequest->handleRequest() #5 {main} thrown in /Applications/MAMP/htdocs/dev/public/modx/controllers/default/system/info.class.php on line 47

### Step to reproduce
Update Modx and click on Systeminformation in the Mainmenu.

### Observed behavior
-

### Expected behavior
-

### Related issue(s)/PR(s)
-

### Environment
MODX 2.8.0

**Comment by Ibochkarev** [comment]
This is fixed in PR #15277 

@modxbot close
