### ISSUE TITLE
Unable to save snippet with a description that is "too long"

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#15319]
### Summary
Saving a snippet with a description that is "too long" will fail without explaining why.

### Step to reproduce
Create or update a snippet in the manager with a description that is more than a couple of lines.

### Observed behavior
The snippet does not save and a pop-up appears saying "An error occurred while saving the snippet."
The MODX error log shows the following:
```
/core/xpdo/om/xpdoobject.class.php : 1452) Error 22001 executing statement:
INSERT INTO `modx_site_snippets` (`source`, `property_preprocess`, `name`, `description`, `editor_type`, `category`, `cache_type`, `snippet`, `locked`, `moduleguid`, `static`, `static_file`) VALUES (0, 0, 'snippetName', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 0, 2, 0, 'return \'\';', 0, '', 0, '')
Array
(
    [0] => 22001
    [1] => 1406
    [2] => Data too long for column 'description' at row 1
)
```
and the same error for an UPDATE request.

### Expected behavior
Possible fixes:
- The snippet should save and just truncate the description.
- There should be a more informative error message and form validation highlighting showing where the issue is.
- If the description field isn't indexed, it could be made longer that 191 chars and still be compatible with UTF8mb4 InnoDB.

### Environment
MODX version 2.8.1

**Comment by sergant210** [comment]
Temporary solution - make a plugin for the OnBeforeDocFormSave event and validate the form data.

**Comment by alroniks** [comment]
Fixed
