### ISSUE TITLE
Wrong 404 link for support page

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#15316]
### Summary
Wrong 404 link for support page

### Step to reproduce
Use MODX 2.8.1 and open domain.tld/manager/?a=help
See screenshot:
![2020-11-03 11 56 19](https://user-images.githubusercontent.com/2815640/97965895-1b17a380-1dcc-11eb-9f82-1f509f87367e.png)

### Observed behavior
Page link gives 404 error.

### Expected behavior
Should be proper page URL, maybe https://modx.com/get-help/ ?

### Related issue(s)/PR(s)
Don't know

### Environment
MODX 2.8.1

**Comment by Ruslan-Aleev** [comment]
The page is working, apparently it was restored, I think the issue can be closed.

**Comment by Jako** [comment]
https://modx.com/resources/free-support-options is available again.

**Comment by JoshuaLuckers** [comment]
The link on the help page, `https://modx.com/community/free-support-options` redirects to a new page `https://modx.com/resources/free-support-options`.
We should update the help page with the new link.

**Comment by ant-tar** [comment]
Great, thanks!
