### ISSUE TITLE
v2.8.1 generates invalid xml

### ISSUE THREAD

**Issue by tartakxg** [modxcms/revolution#15314]
## Bug report

Non valid XML files in /core/model/schema, because these files have invalid character `<`

Please fix these files:
https://github.com/modxcms/revolution/search?q=%5Ba-zA-Z0-9%5Cx2d-%5Cx2f%5Cx7f-%5Cxff-_%5Cs%5D
Please replace `(?<!\s)` with `(?!\s)`

**Comment by opengeek** [comment]
This is part of a REGEXP inside of a string contained within an attribute. The XML is parsed by SimpleXML just fine. I'm not sure why you are saying this is invalid, but it works for our purposes and is only used at development time anyway.

**Comment by Mark-H** [comment]
Can you provide some more information on how this issue might be reproduced @tartakxg? Are you trying to run the schema build script, or using these files in a different way?

**Comment by tartakxg** [comment]
Please try to check /core/model/schemamodx.mysql.schema.xml with https://codebeautify.org/xmlvalidator
_error : Unescaped '<' not allowed in attributes values_


In my case I got error using uicmpgenerator
PHP Version 7.4.7
_FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /core/components/uicmpgenerator/model/uicmpgenerator/mysql/dbhelper.class.php:73_

In file dbhelper.class.php:
```
$schemaFile = $schemaFile ? $schemaFile : MODX_CORE_PATH .'model/schema/modx.mysql.schema.xml';
$this->schema = new SimpleXMLElement($schemaFile, 0, true);
```

**Comment by Mark-H** [comment]
Thanks for the additional detail.

Can confirm running the core `core/model/schema/build.modx.php` also fails on this (PHP 7.3.9):

```
Warning: SimpleXMLElement::__construct(): core/model/schema/modx.mysql.schema.xml:396: parser error : Unescaped '<' not allowed in attributes values in core/xpdo/om/xpdogenerator.class.php on line 203
....
Fatal error: Uncaught Exception: String could not be parsed as XML in core/xpdo/om/xpdogenerator.class.php:203
Stack trace:
#0 core/xpdo/om/xpdogenerator.class.php(203): SimpleXMLElement->__construct('/Users/mhamstra...', 0, true)
#1 core/model/schema/build.modx.php(69): xPDOGenerator->parseSchema(...)
#2 {main}
  thrown in core/xpdo/om/xpdogenerator.class.php on line 203
```

**Comment by opengeek** [comment]
I have confirmed that this rule was recently modified, adding the invalid character to the regex. When it was incorporated, the contributor obviously did not re-generate the maps using the script, as it will not execute now either.

**Comment by Ibochkarev** [comment]
@opengeek  is it still relevant or is it fixed here https://github.com/modxcms/revolution/pull/15349?

**Comment by opengeek** [comment]
Fixed
