### ISSUE TITLE
Save the selected state of the content (by the collapse button)

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15322]
### Summary
In MODX, the content has a Collapse button, but the content state is not saved at all.
It seems to me more logical to save this state for all resources, otherwise, _when the page is refreshed, everything returns as it was_:

![content_space](https://user-images.githubusercontent.com/12523676/98364043-19a2e100-2041-11eb-8e76-5c8245925082.gif)

**It would also be useful to have this button for other elements (chunks, templates), since almost a third of the screen is occupied by a place that is not often edited.**

### Related issue(s)/PR(s)
N/A

**Comment by SnowCreative** [comment]
Related issue: #12786.

**Comment by alroniks** [comment]
I am closing it as a duplication of https://github.com/modxcms/revolution/issues/12786
Thank you for the screens, and sorry about removing the issue, but the original one has more details in the discussion, which will help with implemetation.
