### ISSUE TITLE
File browser not opening folders with special chars

### ISSUE THREAD

**Issue by ezrarieben** [modxcms/revolution#15328]
### Summary
When trying to open a folder within MODX's file browser that contains one of the following special chars:
* ä
* ö
* ü

The folder does not expand and there is no hover effect on mouseover.

### Step to reproduce
1. Create a folder named "Porträt"  using the MODX file manager .
2. Place a test file in the folder using FTP or another type of directory access (not using MODX).
3. Refresh the file manager in MODX and try to expand the folder "Porträt".

### Observed behavior
Any folder with a special char (out of the list above) in it's name does not expand and has no hover effect on mouseover.

### Expected behavior
The folder should expand, the files within the folder should be visible and the hover effect should be visible.

### Related issue(s)/PR(s)
N/A

### Environment
* MODX: 2.8.1
* Apache: 2.4
* MySQL: 5.7
* Browser: Edge (Version 86.0.622.51) / Chrome (Version 86.0.4240.193)

**Comment by Askalab** [comment]
I have exactly the same issue with French chars : "éèàêâùô"...

So : any "non-english" char !

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/15271 & https://github.com/modxcms/revolution/issues/14264 & https://github.com/modxcms/revolution/issues/12932 & https://github.com/modxcms/revolution/issues/13412
Posibly related with https://github.com/modxcms/revolution/issues/14320 & https://github.com/modxcms/revolution/issues/13855 & https://github.com/modxcms/revolution/issues/15682 & https://github.com/modxcms/revolution/issues/14508

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/filemanager-cant-load-folders-with-umlauts-in-2-8/3698/1

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/15505

**Comment by frischnetz** [comment]
I don't think, this is resolved in 2.8.3, yet. I still have the same issues with umlauts in file/folder names. 

In https://community.modx.com/t/filemanager-cant-load-folders-with-umlauts-in-2-8/3698/1 it was suggested to remove line 65 from `core/model/modx/processors/browser/directory/getlist.class.php`:

`$item['id'] = htmlentities($item['id'], ENT_QUOTES, 'UTF-8');`

When I try this for testing purposes, this issue is indeed resolved. But I doubt that this is the best solution.

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/directory-content-not-displayed-in-manager-filesystem-tab/4426/2

**Comment by frischnetz** [comment]
Dear @rthrash, This discussion you mention links back to this issue. 

And as I have described, the issue has not been fixed as far as I see. On a number of websites with version 2.8.3 where umlaut-filenames never made problems before, they now dissappear from the manager. I would appreciate it if you check if for yourself.

**Comment by Mark-H** [comment]
Ryan's a bot that automatically posts when an issue is mentioned on the forum. ;)

**Comment by webinmd** [comment]
set system setting
locale = en_US.UTF-8

**Comment by smg6511** [comment]
Folks, I'm taking a look at this on 2.8.5 and it seems to no longer be an issue. (Note that in my environment, the locale system settings is not set.) I'm going to close this, but if anyone can reproduce this in the current 2.x version (2.8.6 as of now) feel free to re-open.
