### ISSUE TITLE
+modx.user.id:userinfo=`role` returns empty string

### ISSUE THREAD

**Issue by patrickatwsrn** [modxcms/revolution#15338]
### Summary

According to the docs (https://docs.modx.com/current/en/building-sites/tag-syntax/output-filters#)

This code snippet should output the current role of a user:
[[!+modx.user.id:userinfo=`role`]]

### Observed behavior
Nothing is returned for "role". Other properties like "username", etc work like expected.

### Expected behavior
While I'm logged in, I should use something like "super user"

### Environment
MODX 2.7.3

**Comment by patrickatwsrn** [comment]
Update: 

userinfo seems to be restricted to fields included in *_user_attributes. "role" is not part of this table. I suspect that this is the problem and the "bug" is the documentation.

**Comment by Jako** [comment]
Maybe the bug in the documentation is caused by the Evo -> Revo changes.

**Comment by theboxer** [comment]
https://github.com/modxorg/Docs/pull/254
