### ISSUE TITLE
New character limit of 191 doesn't match Manager enforcement on descriptions, also breaks some Extra installs

### ISSUE THREAD

**Issue by jaredfhealy** [modxcms/revolution#15339]
### Summary
I first noticed this issue when going to install QuickApi 1.0.0-beta2. I received an error during the installation.

### Step to reproduce
1. Install the referenced version from the store, or another known Extra with a Description field over 191.
2. See the error displayed

**Note:** I just published a new version that has reduced Description field lengths and some other changes. Depending on timing you may need to download the previous version and install manually.

### Steps to reproduce - related manager issue
1. Go to create a snippet, or any element with a description field
2. Populate any description that is greater than 191 characters but less than the previously allowed 255.
3. Save the record
4. See a modal error: 

![image](https://user-images.githubusercontent.com/9794500/100109084-ba0e4900-2e28-11eb-9f54-4393a78eb5d4.png)

5. Put over 255 characters into the description
6. Manager displays error message based on old character limit of 255

![image](https://user-images.githubusercontent.com/9794500/100109545-2ee18300-2e29-11eb-8427-9aebcee30620.png)

It appears that when the field length change was made, the enforced lengths in the ExtJS components were not updated so hints are displayed with pervious values.

### Observed behavior
When installing any Extra that has over 191 character description on any element, an error is displayed that it is unable to insert.

```
Error 22001 executing statement: INSERT INTO `modx_site_snippets` (`source`, `property_preprocess`, `name`, `description`, `editor_type`, `category`, `cache_type`, `snippet`, `locked`, `properties`, `moduleguid`, `static`, `static_file`) VALUES (1, 0, 'ApiAuthorized', 'Authorize any API calls: $quickapi (QuickApi class instance), $authToken (X-API-Key if present), $hostname, $method (HTTP), $body (Array), $path (Array), $params (Array query parms)\\nThis Snippet is called for every API call.', 0, 2, 0, '/**\n * Default authorization snippet\n * \n * You can override this authorization script in two ways.\n * 1. Create an api specific authorization snippet using the naming convention:\n * ApiAuthorized (/api/hello_world = ApiHelloWorldAuthorized)\n * 2. Create a generic override for all API calls. Duplicate the current\n * ApiAuthorized script and name it MyApiAuthorized\n * \n * These are attempted in sequence. If an api specific authorization snipppet is\n * present, that will be executed. Next it checks for MyApiAuthorized, and finally\n * runs the ApiAuthorized only if no other authorization snippet was found.\n * \n */\n\n// If the auth is false, a 403 response is returned\n$auth = false;\n\n// Check for a token matching the system property\nif ($authToken === $modx->getOption(\'quickapi.x_api_key\', [\'quickapi\'], \"\")) {\n // Set auth to allow\n $auth = true;\n}\nelse {\n // Check if the user is authenticated as an admin\n if ($modx->user->isMember(\'Administrator\') && $modx->user->get(\'sudo\') === true) {\n $auth = true;\n }\n else if ($modx->user->isAuthenticated(\'web\')) {\n // Validate web user api calls\n $auth = true;\n }\n}\n\nreturn $auth;', 0, 'a:0:{}', '', 0, 'core/components/quickapi/elements/snippets/ApiAuthorized.php') Array ( [0] => 22001 [1] => 1406 [2] => Data too long for column 'description' at row 1 )
PHP notice: Array to string conversion
snippet_err_createArray
Error saving vehicle object of class modSnippet; criteria: Array ( [name] => ApiAuthorized )
Could not install related objects with locally owned keys for vehicle object of class modCategory; criteria: Array ( [category] => QuickApi )
Successfully installed package quickapi-1.0.0-beta2
```
The important part of the error is: `Array ( [0] => 22001 [1] => 1406 [2] => Data too long for column 'description' at row 1 )`

### Expected behavior
The installation process could truncate the description field to maintain backward compatibility. Expected behavior is that Extras install with no issues.

### Related issue(s)/PR(s)
https://community.modx.com/t/why-do-some-fields-have-a-varchar-precision-of-191-for-moduserprofile-in-the-modx-schema/940

### Environment
Modx 2.8.1-pl, Ubuntu, PHP 7.4.7, Apache, MySQL Ver 14.14 Distrib 5.7.23, for Linux (x86_64)

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/why-do-some-fields-have-a-varchar-precision-of-191-for-moduserprofile-in-the-modx-schema/940/7

**Comment by muzzwood** [comment]
Related to: https://github.com/modxcms/revolution/issues/15319

**Comment by alroniks** [comment]
Duplicates https://github.com/modxcms/revolution/issues/15319
