### ISSUE TITLE
How do I update my TinyMCE?

### ISSUE THREAD

**Issue by pavelyakymenko** [modxcms/revolution#15340]
Hello, there was a question a week ago. Looking for options on the Internet, I never found an answer. I have the standard TinyMCE ~ 2.0.0v (tinymce-4.3.4-pl), there was an idea to upgrade to the latest version 5.6.1 and put a template from Bootstrap.
According to the Tiny [instruction](https://www.tiny.cloud/docs/general-configuration-guide/upgrading/#upgradingtinymceself-hostedmanuly). I need to replace and properly connect. Since I am far from it, I have to just download the files, and I can't connect. Somewhere far away, I understand that you need to go to the plugin itself TinyMCE on modx and either reassign the path of loading the tini itself, or prescribe a new path.

**Comment by Ibochkarev** [comment]
@xKalwiNx Please write this request in the appropriate repository. https://github.com/modxcms/TinyMCE or https://github.com/modxcms/tinymce-rte

Thanks!

**Comment by Mark-H** [comment]
For starters using the `TinyMCE RTE` package gets you a newer version than the old `TinyMCE` package which has not been actively maintained for a very long time.
