### ISSUE TITLE
 Issue with IF in SELECT on xpdo query.

### ISSUE THREAD

**Issue by touol** [modxcms/revolution#15347]
### Summary
Quick summary what's this issue about.
On some queries I use the following construction:
`'select'=>[
                        'MaterialDet'=>'IF(SUM(MaterialDet.status_id)/COUNT(MaterialDet.status_id)<2,1,2) as material_status1',
                    ],`

MODX does shielding 1:
`SELECT IF(SUM(MaterialDet.status_id)/ COUNT(MaterialDet.status_id)<2, `1`, 2) AS material_status1`

Miraculously I found the code in which this disgrace occurs :-). In the file /core/xpdo/om/mysql/xpdoquery.class.php on line 57 the escaping check:
`$escape = !preg_match('/\bAS\b/i', $column) && !preg_match('/\./', $column) && !preg_match('/\(/', $column);`

I found a way out and added a check for numbers and a string:
`$escape = !preg_match('/\bAS\b/i', $column) && !preg_match('/\./', $column) && !preg_match('/\(/', $column) && !preg_match('/^\d+[\.,]?\d*$/', trim($column)) && !preg_match('/^\'[^ \']*\'$/', trim($column));`

Please correct this problem!

### Step to reproduce
How to reproduce the issue, including custom code if needed.

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by opengeek** [comment]
```'select'=>[ 'MaterialDet'=>'IF(SUM(MaterialDet.status_id)/COUNT(MaterialDet.status_id)<2,1,2) as material_status1', ],```
This is incorrect usage. The alias is the array key. It should be…
```'select'=>[ 'material_status1'=>'IF(SUM(MaterialDet.status_id)/COUNT(MaterialDet.status_id)<2,1,2)', ],```
If that still does not provide the correct value, reply back.

**Comment by touol** [comment]
I'm sorry. I am using pdoTools. Now I found out that this error is from pdoTools
