### ISSUE TITLE
ACL operations not working in MODX 3?

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#15341]
### Summary
Has anyone tested the basic process of hiding objects in the front and back end in MODX 3?

I've used the basic process of hiding resources in mgr and web contexts from my book. It works in MODX2, but in MODX3 the "hidden" resources are visible and editable by people who shouldn't have access to them. 

### Step to reproduce

1. Put some, but not all resources in a resource group called hidden.

2. Connect that resource group to the Administrator user group with a Resource Group Access ACL, context: mgr.

3. Flush permissions and logout all users.

4. Log in to the Manager as a user who is not a member of the Administrator group, but who belongs to a group that has only a Context Access ACL entry for both the mgr and web contexts (so they have mgr access and can see the web section of the tree).

### Observed behavior

The resources in the Hidden resource group are visible and can be edited. I got a similar result in the front end.

### Expected behavior
The resources in the Hidden resource group should not be visible.

I've tried this twice with a clean install of MODX 3 and the same result,  but I may be doing something wrong, so could someone check out this behavior. It may extend to protecting elements, categories, and media sources, though in a quick check I was able to successfully protect a TV by adding it to a resource group.

### Environment
MODX3 Alpha-3
Php 7.1

**Comment by Ruslan-Aleev** [comment]
Also, you cannot remove a Resource Group from the User Group, an error pops up:

![acl_resources_group_del](https://user-images.githubusercontent.com/12523676/100909185-74631780-34dd-11eb-8925-aea7e048d41d.png)

**Comment by Ibochkarev** [comment]
Fixed #15394 
@BobRay thanks!
