### ISSUE TITLE
Package manager broken icons

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#15353]
### Summary
old bug with icons in Package manager:
![image](https://user-images.githubusercontent.com/1703670/102249471-754f6c80-3f13-11eb-8a4d-0dd4147dbece.png)

![image](https://user-images.githubusercontent.com/1703670/102249703-b2b3fa00-3f13-11eb-9eaf-ec58619a2c39.png)

![image](https://user-images.githubusercontent.com/1703670/102249900-ee4ec400-3f13-11eb-977f-f16112d5b1cb.png)

### Step to reproduce
Go to Package manager and click on Extras, Front End Templates and Manager Templates

### Environment
MODX 2.8

**Comment by Ibochkarev** [comment]
@jaygilmore

**Comment by jaygilmore** [comment]
This is now fixed. I've replaced the legacy images. However, I'd suggest a new PR to remove the images altogether or to replace them with SVGs. I do not think images add any benefit to those specific views at this time.

**Comment by jaygilmore** [comment]
By the way, Thanks @meshkov for the report and thanks to @Ibochkarev for letting me know about it.

**Comment by JoshuaLuckers** [comment]
@jaygilmore I believe the image is part of the data returned by the package provider.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue @meshkov, this issue is now resolved and therefore I'm closing this issue.
