### ISSUE TITLE
Autosave doesn't work with event OnDocFormSave

### ISSUE THREAD

**Issue by EMDM45** [modxcms/revolution#15359]
[From docs](https://docs.modx.org/current/en/extending-modx/plugins/system-events/ondocformsave):

> Saving Happens Automatically No need to run the $resource->save() method as that happens automatically.

I have modx 2.8.1 and autosave doesn't work.
But if run method `$resource->save()`, resource will be saved.

**Comment by Bruno17** [comment]
I think, that note is related to the example above and related to `$resource->setTVValue`
If you modify the resource-object itself, you will need to save it by yourself

**Comment by JoshuaLuckers** [comment]
The `OnDocFormSave` event is triggered after the resource is saved. 

@Bruno17 is right, the note about saving happening automatically is related to `$resource->setTVValue()`.

**Comment by Ruslan-Aleev** [comment]
@EMDM45 If there really is a bug, then it is better to describe it in the Documentation repository - https://github.com/modxorg/Docs/issues.
