### ISSUE TITLE
In extended user fields, the <i> tag is added in the attribute tree

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15356]
### Summary
When editing a user, any attribute can be added on the "Extended Fields" tab, however, an `<i>` tag is added around the attribute value in the attribute tree:

![user_fields](https://user-images.githubusercontent.com/12523676/102588681-e747d180-411e-11eb-8eec-ebd85e0f9ea4.gif)

### Related issue(s)/PR(s)
N/A

### Environment
MODX 2.x, 3.x

**Comment by Ibochkarev** [comment]
Fixed  #15389
