### ISSUE TITLE
A label is cut off after applying form customization rule

### ISSUE THREAD

**Issue by alroniks** [modxcms/revolution#15357]
### Summary
If you try to rename the label of any default field of the resource and use a comma in the text, it will fail. See images.
![Screen Shot 2020-12-23 at 13 09 14](https://user-images.githubusercontent.com/303498/102985492-4db66080-4520-11eb-8778-32ef0909cf87.png)
![Screen Shot 2020-12-23 at 13 10 23](https://user-images.githubusercontent.com/303498/102985495-4ee78d80-4520-11eb-900e-9d74f7359501.png)

### Step to reproduce
Create any form of customization set and rule. In the rule, write a new name for any default field, like pagetitle, for example.
Use a comma in the name. After to go to the resource and check what label is shown.

### Observed behavior
Labels are cut off after the rule is applied.

### Expected behavior
Labels should be the same as it was set.

### Related issue(s)/PR(s)
N/A

### Environment
MODX 2.8.1

**Comment by SnowCreative** [comment]
Thanks! I've been meaning to report that for a while, but never got around to it. Very annoying.

**Comment by alroniks** [comment]
I don't know why [here](https://github.com/modxcms/revolution/commit/a366c93cff32aa7bbd75b00df973487dcd40892a#diff-f7829d55613e5bdec6699a9901b3f11ac3ae0dd616cea490c27d36392be3a96eR38-R40) splitting by a comma is used.

I can not imagine the places where it can be needed. Maybe you @Mark-H know, or you @opengeek remember something about it. The easiest way to fix just to remove splitting for labels.

**Comment by wfoojjaec** [comment]
This was the reason https://github.com/modxcms/revolution/commit/a366c93cff32aa7bbd75b00df973487dcd40892a

**Comment by smg6511** [comment]
I'm starting to play with this and am failing to see how the splitting is relevant or useful in the current version of 2.8.x. Every single rule is saved in its own db record; the rules are not being serialized in any way. Maybe this is a remnant from when ManagerManager was used to customize forms? Am I missing something?

**Comment by Ibochkarev** [comment]
Fixed #15889
