### ISSUE TITLE
Old logo in website template

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15364]
@opengeek You forgot about the logo in the "Base Template" for MODX-extras:

![logo_old](https://user-images.githubusercontent.com/12523676/95689515-fb9cb900-0c19-11eb-9ff0-c6ccce826eff.png)

_Originally posted by @Ruslan-Aleev in https://github.com/modxcms/revolution/issues/15294#issuecomment-706764341_

Environment
MODX 2.x

**Comment by Ibochkarev** [comment]
Improved in #15405
