### ISSUE TITLE
sanitizeRequest doesn't remove MODX tags completely

### ISSUE THREAD

**Issue by Bruno17** [modxcms/revolution#15366]
### Summary
It seems santizeRequest doesn't remove all MODX tags completely

### Step to reproduce
Try to save a form from fronend with something like that:

```
[[test? 
  &ids = `[[!getids 
    &field=`id` 
    &resource=`[[+resource]]`
    ]]
  &parents=`2`
`]]
```

### Observed behavior
this keeps that:

```
`
    
  &parents=`2`
`
```

### Expected behavior
It should remove everything within the MODX tag completely

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX 2.8.1

changing in modx.class.php

```
    public $sanitizePatterns = array(
        'scripts'       => '@<script[^>]*?>.*?</script>@si',
        'entities'      => '@&#(\d+);@',
        'tags1'          => '@\[\[(.*?)\]\]@si',
        'tags2'          => '@(\[\[|\]\])@si',
    );
```

to

```
    public $sanitizePatterns = array(
        'scripts'       => '@<script[^>]*?>.*?</script>@si',
        'entities'      => '@&#(\d+);@',
        'tags1'          => '@\[\[(?:(?!(\[\[|\]\])).)*\]\]@si',
        'tags2'          => '@(\[\[|\]\])@si',
    );
```
seems to solve that

**Comment by Jako** [comment]
Hmm, why did you not create a PR with that changes?

**Comment by Bruno17** [comment]
I will, if it is not only me, who has that issue

**Comment by Jako** [comment]
Before:
https://regex101.com/r/zbKPPe/1

After:
https://regex101.com/r/blPEwz/1

So the change seems to be valid.
