### ISSUE TITLE
Permission system definitely broken in MODX 3

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#15375]
### Summary
Protected resources in MODX 3 Manager are still visible

### Step to reproduce

I created a Codeception acceptance test to verify this. In MODX 2 all assertions pass. In MODX 3, it runs fine, but the two assertions that "dontSee()" the hidden resource fail, because it's not hidden.

How to reproduce the issue, including custom code if needed.

Here's the acceptance test code. The users, resources, user groups, resource groups, and role are all created before the test runs. The ACL entry that should protect the Private resource is created in the test code.  When the test logs in the PublicUser, who should not be able to see the PrivateResource (because it's in the PrivateResources resource group which is connected to the PrivateUsers user group, which the PublicUser is not a memeber of), the PrivateResource is visible in the Resources Tree. 

JoeTester, an admin super user is also not a member of the PrivateUsers user group, but he can also see the PrivateResource in the tree.

```
 public function ResourceProtectionTest(AcceptanceTester $I)
    {
        assertTrue(true);
        $testPage = new ResourceTestPage($I);
        $wait = 2;

        /* Login admin user JoeTester */
        $loginPage = new LoginPage($I);
        $loginPage->login('JoeTester', 'TesterPassword');
        $I->see('Content');
        $I->see('Manage');
        $I->wait($wait);

        /* *** Create ACL entry *** */

        /* Go to ACL panel */
        $I->wait($wait + 1);
        $I->moveMouseOver($testPage::$systemMenu);
        $I->click($testPage::$systemMenu);
        $I->wait(1);
        $I->moveMouseOver($testPage::$acl_option);

        $I->click($testPage::$acl_option);
        $I->wait($wait);

        /* Update PrivateUser user group */
        $I->clickWithRightButton($testPage::$privateUsersGroup);
        $I->wait($wait+2);

        $I->click($testPage::$updateUserGroupOption);
        $I->wait($wait);

        /* Select Permissions top tab */
        $I->click($testPage::$permissionsTab);
        $I->wait($wait);

        /* Select Resource Group Access left tab */
        $I->click($testPage::$resourceGroupAccessTab);

        $I->wait($wait);

        /* Create actual ACL entry */
        $I->click($testPage::$addResourceGroupButton);

        $I->wait($wait);

        /* Set Resource Group */
        $I->click($testPage::$resourceGroupInput);
        $I->wait($wait);

        $I->click($testPage::$privateResourcesOption);

        /* Set Context */
        $I->click($testPage::$contextInput);
        $I->wait($wait);

        $I->click($testPage::$mgrOption);

        /* Set Role */
        $I->click($testPage::$authorityInput);

        $I->wait($wait+2);

        $I->click($testPage::$testUserOption);

        /* Set Policy */
        $I->click($testPage::$policyInput);
        $I->wait($wait);

        $I->click($testPage::$resourceOption);

        $I->wait($wait);

        /* Save ACL entry */
        $I->click($testPage::$addResourcePanelSaveButton);
        $I->wait($wait);
        $I->reloadPage();

        /* Make sure JoeTester can see PublicResource
           and can't see PrivateResource */
        $I->wait($wait+1);
        $I->see("PublicResource");
        $I->dontSee("PrivateResource");  /* Fails in MODX 3 */

        /* Logout JoeTester */
        $I->wait($wait);
        $loginPage->logout();
        $I->wait($wait);
        $I->see('Password');

        /* Login PrivateUser */
        $I->wait($wait);
        $loginPage->login('PrivateUser', 'somepassword');
        $I->see('Content');
        $I->see('Manage');
        $I->wait($wait);

        /* Make sure Private resource is visible */
        $I->wait($wait);
        $I->see("PublicResource");
        $I->see("PrivateResource");

        /* Logout PrivateUser */
        $I->wait($wait);
        $loginPage->logout();
        $I->wait($wait);
        $I->see('Password');

        /* Login PublicUser */
        $I->wait($wait);
        $loginPage->login('PublicUser', 'somepassword');
        $I->see('Content');
        $I->see('Manage');
        $I->wait($wait);

        /* Make sure Private resource is not visible */
        $I->see("PublicResource");
        $I->dontSee("PrivateResource");  /* Fails in MODX 3 */

        /* Logout PublicUser */
        $I->wait($wait);
        $loginPage->logout();
        $I->wait($wait);
        $I->see('Password');
    }
}
```

### Observed behavior
How it behaved after following steps above.

### Expected behavior
How it should behave after following steps above.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by BobRay** [comment]
I have not tested ACL protection in MODX 3 for Element Categories or TVs. It may be broken for them also.

**Comment by JoshuaLuckers** [comment]
Would it be possible to submit a PR with failing Unit Tests for this?

**Comment by BobRay** [comment]
I'm sure it's possible to create a unit test for this, but I don't think I know enough about the permissions architecture to write it. One issue is that we don't know if the bug is in the creation of the ACL protection or in the application of it.

I could possibly upload the acceptance test, but it requires Codeception, PhpUnit, WebDriver, the Selenium standalone server, a browser driver (e.g. chromedriver), an installed browser, and a bunch of support and configuration files. I question whether anyone would actually use it.

If I can find the time, I'll run Git bisect on the repo using my acceptance test to see if I can identify the commit where things went bad.

**Comment by BobRay** [comment]
This commit is as far back as I could test, due to method signature conflicts and the lack of BC for instantiating MODX:

Jan 08, 2020
ecd7f8d24300f32553c4579315fb0fc2b011c462  

The problem is older than that commit.

**Comment by BobRay** [comment]
I just wanted to add that a this is not merely a display issue. The user who shouldn't be able to see the resource in the tree can also edit it and successfully save changed versions of it.

**Comment by BobRay** [comment]
I created a test to see if this problem extends to Element Category Access ACL entries. I tested all types of elements and there are no problems with them in MODX3.

**Comment by BobRay** [comment]
My test confirms the fix.

**Comment by Ibochkarev** [comment]
@BobRay Thanks!
