### ISSUE TITLE
MODX3: Menu item sorting does not work

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15386]
### Summary
In https://github.com/modxcms/revolution/pull/15230 I added a parameter `ddAppendOnly: true` to the script, this prevented the menu items from being dragged behind the main menu areas (Main Navigation and User Navigation).

It was necessary because when dragging, the menu item could disappear from the main menu, which is not correct.

![menu_dd_1](https://user-images.githubusercontent.com/12523676/92591988-89962480-f2a7-11ea-9eb1-1808600acc0d.gif)

**But this parameter, apparently, also participates in the sorting of menu items.**

### Step to reproduce
Try changing the sorting in the menu settings.

### Expected behavior
In general, a solution is needed that would prohibit dragging the menu item outside of the main areas (Main Navigation and User Navigation), but would also enable drag-and-drop sorting.

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/15230

### Environment
MODX 3

**Comment by JoshuaLuckers** [comment]
In this case it would be better to revert the changes because not being able to sort the menu items is worse then the bug it tried to fix. 
I'm also to blame here, I should have tested it better (I only tested if the bug was fixed, not if it was breaking anything else).

Maybe we can add an event listener for the `beforenodedrop` event and check if we are dropping it outside the main menu?

**Comment by Ruslan-Aleev** [comment]
> and check if we are dropping it outside the main menu?

Moving inside the Main Menu (root node) won't work either (the menu will disappear), that's why I hid the root node.

> Maybe we can add an event listener for the beforenodedrop event

Yes it would be nice :)

Does extjs have an option for trees that disallows dragging? It could be enabled only for Main Navigation and User Navigation, and disabled for Main Menu (root node).

**Comment by Ibochkarev** [comment]
Fixed #15388
