### ISSUE TITLE
Select Element Options when dragging snippet to editing panel

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#15384]
### Summary
When dragging a pdoField snippet into a resource's field, the Select Element Options "field" field is restricted to a numeric value, and the field is a text value, i.e. "pagetitle".

### Step to reproduce
Drag the pdoField snippet into one of a resource's fields.

### Observed behavior
The Select Element Options form pops up offering fields to fill out for a number of properties used by the snippet. The "id" field is a numeric field, as is correct, since it takes the ID of the resource to get the field from. But the "field" field is also a numeric field, which is not correct, since it takes the name of the field to get.

### Expected behavior
The "field" field should be a text field.

### Related issue(s)/PR(s)
None that I am aware of.

### Environment
MODX 2.8.1, MODX Cloud

**Comment by ghost** [comment]
This raises the question, how does MODX determine what snippet properties to provide fields for in the Select Element Options form popup? I tried the same thing with the getResourceField snippet, and it just offers caching and property set options, no properties. 

This hardly seems fair, since the getResourceField has a comment section at the beginning of its code that exposes all of the properties that it uses, while pdoField does not have any comments at the beginning of its code at all.

**Comment by Jako** [comment]
The popup is created with the property set of the dragged snippet. The property set is normally created during the installation of a snippet (if the snippet author created the set).

pdoField is not part of the core and it has to be changed in the pdoTools repository: https://github.com/bezumkin/pdoTools/blob/master/_build/properties/properties.pdofield.php
