### ISSUE TITLE
Weblink default protocol

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#15392]
### Summary
When creating a weblink the default protocol is http.

### Why is it needed?
It's annoying to have to keep changing the default http to https when creating weblinks. If I even remember to do so.

### Suggested solution(s)
Change the default to https. Actually, it would be even better if it were a system setting.

### Related issue(s)/PR(s)
None that I know of.

![new-weblink](https://user-images.githubusercontent.com/1073780/107846785-26c52e00-6def-11eb-87dd-b05461a0bb52.jpg)

**Comment by ghost** [comment]
Line 37 of https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/resource/modx.panel.resource.weblink.js

`            ,value: (config.record.content || config.record.ta) || 'http://'`

**Comment by Ruslan-Aleev** [comment]
Maybe it makes sense to specify a link without a protocol: `//`?
Because an unknowing user may not know such things, and may indicate a link to a site that does not have a certificate, and then the browser will return an error, but the site without a certificate will always open.

**Comment by JoshuaLuckers** [comment]
We need to provide example values in the description and leave the default value empty.
1. It's easier to type the correct value yourself.
2. No additional steps are needed when you want to paste a weblink.
3. A weblink can also be an ID of a resource
4. etc.

**Comment by Ibochkarev** [comment]
Fixed #15422
