### ISSUE TITLE
Wrong Default Template

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#15397]
### Summary
The wrong default template is used. It appears that the ID of the template is offset somewhere.

### Step to reproduce
Set template #4 to be the default. 

<img width="398" alt="Screen Shot 2021-02-19 at 12 39 07" src="https://user-images.githubusercontent.com/1073780/108493879-8cae2b80-72af-11eb-86ee-b42d724dab70.png">
<img width="573" alt="Screen Shot 2021-02-19 at 12 39 21" src="https://user-images.githubusercontent.com/1073780/108493903-933ca300-72af-11eb-9334-3fcbde4d2b87.png">

### Observed behavior
Template #3 is the default.

<img width="433" alt="Screen Shot 2021-02-19 at 12 41 42" src="https://user-images.githubusercontent.com/1073780/108494181-e9a9e180-72af-11eb-8d58-03c667484def.png">
<img width="282" alt="Screen Shot 2021-02-19 at 12 42 37" src="https://user-images.githubusercontent.com/1073780/108494260-fb8b8480-72af-11eb-8510-b658f00177d5.png">

### Expected behavior
Template #4 should be the default.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX 2.8.1

**Comment by Ruslan-Aleev** [comment]
MODX has recently added a setting - `automatic_template_assignment` and the default is set `parent`. Those the parent template will be added to the nested resource (can be configured differently).
But for an unnested resource, the default template from the `default_template` setting will be set.

Or is your behavior different? It works for me as I described above.

**Comment by ghost** [comment]
That was it.
