### ISSUE TITLE
Console warnings of bad SameSite value in cookies

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#15407]
### Summary
Getting this warning in Firefox console that the PHPSESSID cookie will be rejected

### Step to reproduce
Load a Manager page and view the browser console.

### Observed behavior
Produced the warning
```Cookie “PHPSESSID” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite index.php```

### Expected behavior
Don't throw warnings, and certainly don't get rejected.

### Related issue(s)/PR(s)
None that I know of

### Environment
MODX 2.8.1, Firefox 85.0.2, OSX 11.2.1, MODX Cloud

**Comment by Ibochkarev** [comment]
Related https://github.com/modxcms/revolution/issues/15301

**Comment by ghost** [comment]
Sorry, I didn't see that one when I searched.
