### ISSUE TITLE
[PHP8, 2.x] Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in PHPMailer

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#15416]
### Summary

```
Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /core/model/modx/mail/phpmailer/PHPMailerAutoload.php on line <i>45</i>
```

### Step to reproduce

Use the MODX mailer class to send an email.

[Any mail code will do](https://docs.modx.com/current/en/extending-modx/services/modmail), but I'm a big fan of using Bob's QuickEmail extra for email testing. 

### Observed behavior

Throws a fatal error, does not send email.

### Expected behavior

Should not throw a fatal error, but send my delicious email across the interwebs to its intended receiver.

### Related issue(s)/PR(s)

#14594 - that warns about it being deprecated, but we're now in the situation of it breaking completely in PHP8.

### Environment

PHP 8

**Comment by Ibochkarev** [comment]
PHPMailer 5.2 (which is compatible with PHP 5.0 — 7.0) is no longer supported, even for security updates.

**Comment by Mark-H** [comment]
Looks like we'll indeed need to upgrade to the 6.x branch to get rid of this https://github.com/PHPMailer/PHPMailer/blob/master/UPGRADING.md

At least these days their minimum bump to 5.5 is no problem - IIRC we're minimum 5.6 now. 

_Hopefully_ those breaking changes are manageable. While I ❤️ composer, for 2.x it probably makes sense to do a manual integration and `require`ing the specific files just like it does now.
