### ISSUE TITLE
Warning: session_cache_limiter(): Cannot change cache limiter when session is active

### ISSUE THREAD

**Issue by VincentLanglet** [modxcms/revolution#15414]
### Summary

I'm using a tool to report any exception/warning on my project. And I get the following warning:
```
Warning: session_cache_limiter(): Cannot change cache limiter when session is active
```
in `connectors/system/phpthumb.php`.

I don't really know the best way to fix this. Should the check be:
```
if(session_status() !== PHP_SESSION_ACTIVE) {
  session_cache_limiter('public');
}
```
?

**Comment by alroniks** [comment]
One example from Yii https://github.com/yiisoft/yii2/pull/15638/files

**Comment by alroniks** [comment]
And it inroduced by these changes https://github.com/modxcms/revolution/pull/13805/files
