### ISSUE TITLE
Incorrect version is displayed in the welcome window

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15412]
### Summary
Incorrect version is displayed in the welcome window

### Step to reproduce
Install a clean version of MODX 3.x

### Observed behavior
![photo_2021-02-24_03-06-21](https://user-images.githubusercontent.com/2138260/108963850-e3977480-76a4-11eb-87fa-8eae29026773.jpg)

### Expected behavior
Should display the correct version of MODX Revolution 3.x

https://github.com/modxcms/revolution/blob/3.x/_build/data/transport.core.system_settings.php#L1835

### Related issue(s)/PR(s)
NA

### Environment
MODX version: Latest version with Github

**Comment by Ibochkarev** [comment]
@jaygilmore I think this is for you =)

**Comment by muzzwood** [comment]
Yeah it looks like the latest one is: https://misc.modx.com/revolution/welcome.28.html

We need a https://misc.modx.com/revolution/welcome.30.html

**Comment by Ibochkarev** [comment]
@opengeek Can you create a 3.0 file and fix the documentation links?  I will correct the value in the system settings.

**Comment by jaygilmore** [comment]
I've resolved this. You can preview the page at https://misc.modx.com/revolution/welcome.30.html

**Comment by Ibochkarev** [comment]
Fixed #15613
