### ISSUE TITLE
[PHP8, 2.x] modLexicon->parse() throws fatal error if $params contains nested array

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#15415]
### Summary

If the lexicon $params contains an error, PHP 8 throws:

```
Exception: str_replace(): Argument #2 ($replace) must be of type string when argument #1 ($search) is a string
```

### Step to reproduce

For now I haven't found a core place where this goes wrong (stumbled across it testing Commerce), but it's reproducible with the following in a snippet:

```
$modx->lexicon->load('core:default');
return $modx->lexicon('resource', ['key' => 'value', 'properties' => ['more' => 'values']]);
``` 

The key has to be valid and loaded for it to kick into the str_replace; it does not need to have [[+placeholders]] in the string.

I've gotten used to this method passing in an entire object into a lexicon (e.g. `$modx->lexicon('key', $object->toArray())`) to allow the lexicon key to access whatever is in there to provide a contextualised piece of text, however in PHP 8 that breaks if the object has any embedded arrays.  

### Observed behavior

```
Exception: str_replace(): Argument #2 ($replace) must be of type string when argument #1 ($search) is a string
```

### Expected behavior

It should return the lexicon key with any accessed values replaced. Ideally it should work the same as elements in parsing nested arrays (e.g. `[[+properties.foo.bar]]`), but as a stopgap it should make sure the value is scalar and skip arrays.

### Related issue(s)/PR(s)

N/a.

### Environment
MODX 2.8.2-dev (2.x branch as of Feb 22)

**Comment by wax100** [comment]
I create snippet and place on page. But there is no errors in **error.log**
```
<?php
$modx->lexicon->load('core:default');
return $modx->lexicon('resource', ['key' => 'value', 'properties' => ['more' => 'values']]);
```

**Comment by Jako** [comment]
The issue should be logged in the PHP error log and not in the MODX error log.
