### ISSUE TITLE
[3.x] Resource tree content is slightly too tall for its container

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#15425]
### Summary
If you have more than one resource there is a bit of overflow on the `y` axis causing a scroll bar to appear.
It's not there if only one resource.

![Screenshot_2021-03-02 Editing test MODX Revolution](https://user-images.githubusercontent.com/5160368/109621384-dcc1a380-7b75-11eb-9c79-a75a87d571e0.png)

### Step to reproduce
Add a second resource and look at the tree.

### Expected behavior
The scrollbar shouldn't appear unless it's required.

### Environment
MODX 3.x latest, Firefox 86, Pop!_OS, Gnome

**Comment by Ruslan-Aleev** [comment]
Yes, the problem is observed on the Firefox browser.

**Comment by muzzwood** [comment]
It appears to be the `.modx-tree-node-btn-create` that is causing the overflow.
It has a couple of undefined classes there too strangely...

![Screenshot from 2021-03-03 11-52-23](https://user-images.githubusercontent.com/5160368/109750446-6ecdb880-7c17-11eb-9c6e-07a9218fe659.png)

**Comment by theboxer** [comment]
@Ibochkarev can you stop assigning issues to me? Feel free to work on a PR instead.

**Comment by Ibochkarev** [comment]
@theboxer Ok, I will not use this function anymore. Sorry if I have caused you any inconvenience.

**Comment by muzzwood** [comment]
This issue is fixed by adding `overflow: hidden;` to:
```
.x-tree-node-el .modx-tree-node-btn-create
```
https://github.com/modxcms/revolution/blob/3.x/_build/templates/default/sass/_tree.scss#L304

**Comment by Ibochkarev** [comment]
Fixed #15962
