### ISSUE TITLE
[3.x] When creating a new resource from the "plus" button above the tree, Resource Type field shows "modDocument"

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#15423]
### Summary
On a resource under the settings tab, the default value is shown as `modDocument`. This only occurs when using the plus button above the resource tree as far as I can tell. If you use a context menu by right-clicking on the tree, it correctly shows "Document".

![Screenshot from 2021-03-02 13-19-30](https://user-images.githubusercontent.com/5160368/109601863-9f9be800-7b5a-11eb-90e3-b177146b9eea.png)

### Step to reproduce
Click the plus button above the resource tree to create a new resource then click the settings tab.

### Observed behavior
The dropdown shows `Document`, it's just the placeholder that shows `modDocument`

### Expected behavior
It should show `Document` in every situation.

### Environment
MODX 3 latest git

**Comment by theboxer** [comment]
Already resolved.
