### ISSUE TITLE
Developer access policy not resolved to policy template during installation

### ISSUE THREAD

**Issue by travisbotello** [modxcms/revolution#15431]
### Summary
The _Developer_ access policy is not resolved to its corresponding policy template during setup causing _Developer_ access policy missing in manager.

### Step to reproduce
- install MODX
- go to manager -> access policies
- search for Developer access policy -> missing in the list
- create a new access policy and name it Developer and save it -> saving error
- check database table _modx_access_policies_ -> there already is a policy called Developer but its template column is set to 0 and therefore it is not displayed in the manager

### Observed behavior
- _Developer_ access policy is not available in manager

### Expected behavior
- _Developer_ access policy should either be available in manager or not being installed via setup

### Related issue(s)/PR(s)
Following issues seem to be related:
- https://github.com/modxcms/revolution/issues/12453
- https://github.com/modxcms/revolution/issues/8961

### Environment
MODX 2.8.1 advanced

The policy is installed here https://github.com/modxcms/revolution/blob/v2.8.1-pl/_build/data/transport.core.accesspolicies.php#L109

...but _Developer_ is missing in the corresponding resolver mapping here https://github.com/modxcms/revolution/blob/2.x/_build/resolvers/resolve.policies.php#L8

I am not sure if this was intended to be removed completely or someone forgot to add it to the mapping. How to proceed here?

**Comment by alroniks** [comment]
Solved
