### ISSUE TITLE
Impossible to replace file duplicate without reopening upload popup window 

### ISSUE THREAD

**Issue by ant-tar** [modxcms/revolution#15437]
### Summary

I wanted to upload a file to backend, upload manager informed me that such file exists. I expected that it would simply overwrite it, but no. Okay, I deleted previous file on the left in the tree, and try to upload new one again, error message repeats again. 

### Step to reproduce

Step 1. 
![2021-02-27 10 27 27](https://user-images.githubusercontent.com/2815640/109919854-6e422a00-7cca-11eb-9760-d64529375d15.png)
Step 2.
![2021-02-27 10 28 21](https://user-images.githubusercontent.com/2815640/109919871-7732fb80-7cca-11eb-8899-43fcc787e3cf.png)
Step 3.
![2021-02-27 10 28 47](https://user-images.githubusercontent.com/2815640/109919901-81ed9080-7cca-11eb-911c-766fab177c7e.png)
Step 4.
![2021-02-27 10 29 26](https://user-images.githubusercontent.com/2815640/109919919-8e71e900-7cca-11eb-9680-159632adbeb5.png)

### Observed behavior

Message appears over and over again until you open popup window again after file deletion. 

### Expected behavior
Error message is not repeated second time after deleting file from tree on the left, without reloading pop-up window 

![2021-02-27 10 30 03](https://user-images.githubusercontent.com/2815640/109919960-9b8ed800-7cca-11eb-8251-cc8000828941.png)

### Related issue(s)/PR(s)
I don't know about such 

### Environment
MODX Revolution 2.8.1-pl,  MODXCloud

**Comment by sergant210** [comment]
@Ibochkarev It's not a bug. This is a specific behavior of the upload dialog. Only the first click performs the upload operation. So the following clicks do not perform any operation. To re-upload a file you need to clear the file list and choose it again. Or reopen the dialog, which is essentially the same thing.

@himurovich To overwrite an existing file set the "upload_check_exists" system setting to **No**.

**Comment by ant-tar** [comment]
Thanks @sergant210 ,I've got the idea!
