### ISSUE TITLE
There is no Deactivate plugin item in the context menu

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15446]
### Summary
There is no Deactivate plugin item in the context menu

### Step to reproduce
Go to the Elements tab, the Plugins section and right-click on any plugin

### Observed behavior
![2021-03-05 13-41-12 Dashboard   MODX Revolution - Google Chrome](https://user-images.githubusercontent.com/2138260/110083726-3fef4800-7db9-11eb-805c-73691cf3bd97.png)

### Expected behavior
In modx 2.8.1:
![2021-03-05 13-44-53 Dashboard   Venus - Google Chrome](https://user-images.githubusercontent.com/2138260/110083773-51d0eb00-7db9-11eb-8f6c-34da1ebd3605.png)

### Related issue(s)/PR(s)
NA

### Environment
MODX 3 (git), PHP Version 7.4.12

**Comment by muzzwood** [comment]
Ah you just beat me to this one! Well done

I can confirm this issue.

Edit: While the deactivate plugin option is missing from the context menu, you can still deactivate the plugin using the checkbox on the edit plugin screen.

**Comment by Mark-H** [comment]
Is the activate option there (in the context menu) if a plugin is deactivated or is that also missing?

**Comment by muzzwood** [comment]
activate plugin is also missing @Mark-H

**Comment by Ibochkarev** [comment]
> Is the activate option there if a plugin is deactivated or is that also missing?

When editing a plugin is open, you can disable the plugin, but in quick edit the menu item is skipped

**Comment by Mark-H** [comment]
Added a €10 bounty to this. Small issue, but nice to have fixed. ;)

**Comment by muzzwood** [comment]
I'm going to work on this

**Comment by muzzwood** [comment]
Should be fixed now

**Comment by JoshuaLuckers** [comment]
Fixed in PR #15449
