### ISSUE TITLE
The link "Preview" in "Recent Resources" in the account does not work

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15448]
### Summary
The link "Preview" in "Recent Resources" in the account does not work, although there is no problem in the resource tree.

### Step to reproduce
![res_preview](https://user-images.githubusercontent.com/12523676/110088282-b8e4a480-7da5-11eb-904e-1076e9a8cb4a.gif)

### Environment
MODX 3-alpha-3

**Comment by Ibochkarev** [comment]
I confirm this
https://user-images.githubusercontent.com/2138260/110089160-f3f3d180-7dbf-11eb-9a9d-35e54aa4c8f2.mp4

**Comment by sdrenth** [comment]
I will fix this
