### ISSUE TITLE
Recursive display of the folder with MODX tags in the name

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15508]
### Summary
 If you create a folder with any MODX tag in the name the MODx folder tree will create an infinitely nested loop of those folders.
![97478165-f41e2500-1926-11eb-9b73-c505512e39f6](https://user-images.githubusercontent.com/4679725/110207435-806fc400-7e94-11eb-8818-bda2dcedbc46.png)

The reason - MODX sanitized GET parameters and cut MODX tags. It passes only POST parameters with MODX tags if the system setting "allow_tags_in_post" is on.

### Step to reproduce
1. Create a folder with name [[++holidaytheme]].
2. Try to open it in the MODX file manager.

### Environment
MODX 2.x.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/15505
