### ISSUE TITLE
Plugin not greyed out in tree after deactivating

### ISSUE THREAD

**Issue by hugopeek** [modxcms/revolution#15503]
### Summary
Plugins can be succesfully activated and deactivated from the tree, but there's no visual distinction between the two:

![image](https://user-images.githubusercontent.com/5436121/110199740-d5133f00-7e94-11eb-9b4b-130487b00f1e.png)

### Step to reproduce
Try to deactivate a plugin in latest 3.x build.

### Observed behavior
Plugin not greyed out.

### Related issue(s)/PR(s)

Ghost from the past? #12710

### Environment
MODX 3.x, Firefox Dev

**Comment by muzzwood** [comment]
Hmmm this one is ok for me:

![Screenshot from 2021-03-06 16-07-04](https://user-images.githubusercontent.com/5160368/110199957-2112b380-7e96-11eb-9961-63e1ea30a71e.png)

**Comment by Ibochkarev** [comment]
I confirm. If the plugin is located in the (Categories) folder, then the styles of the inactive plugin are not applied

**Comment by muzzwood** [comment]
Ah, it's got to be in a category.
Yup, can also confirm. 

Edit: It does however work as expected if not in a category.

**Comment by Ibochkarev** [comment]
@hugopeek Please do not use [3.x] in the title

**Comment by Ibochkarev** [comment]
Fixed #15519
