### ISSUE TITLE
User not found. when trying to create a message

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15500]
### Summary

User not found. when trying to create a message

### Step to reproduce
Go to the User menu, then select Messages. Create new message

### Observed behavior

![image](https://user-images.githubusercontent.com/2138260/110199352-3847a600-7e82-11eb-8f27-d6597acde0ac.png)

![image](https://user-images.githubusercontent.com/2138260/110199333-282fc680-7e82-11eb-904d-f8cbe3146c6a.png)

### Expected behavior
The message must be sent

### Related issue(s)/PR(s)
NA

### Environment
MODX Revolution 3.0.0-alpha3 (git), PHP Version 7.4.12

**Comment by sergant210** [comment]
I'll take it.

**Comment by sergant210** [comment]
The same for role.

**Comment by alroniks** [comment]
Fixed
