### ISSUE TITLE
Error flush_sessions_not_supported

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15510]
### Summary
After upgrading from version 2.8.1 to nightly build modx-3.0.0-alpha3-20210301 and after clicking on the button in the Manage -> Logout All Users menu, an error appears `flush_sessions_not_supported`. There is no such bug in a clean assembly of MODX3.

### Step to reproduce
Install a clean build of version 2.8.1 before the nightly build modx-3.0.0-alpha3-20210301, clicking on the button in the Manage -> Logout All Users menu, an error appear `flush_sessions_not_supporteds`. Check for errors in the error log. Before upgrading, set the system setting log_level to 4

### Observed behavior

https://user-images.githubusercontent.com/2138260/110235847-98127f80-7f5c-11eb-93e0-453938c88038.mp4

``` shell
[2021-03-07 12:40:53] (DEBUG @ /home/s25444/www/core/src/Revolution/modLexicon.php : 525) Language string not found: "flush_sessions_not_supported"
```

### Expected behavior
After the click, there should be no error and the actions to complete all sessions should be performed

### Related issue(s)/PR(s)
NA

### Environment
modx-3.0.0-alpha3-20210301, PHP Version 7.3.24-3

**Comment by Mark-H** [comment]
What's your `session_handler_class` system setting set to? Flushing sessions is only supported for the standard MODX session handler (database sessions), so perhaps (1) you're using PHP file sessions or (2) the session is set to `'modSessionHandler'` and should get rewritten in an upgrade to the full namespaced class name.

**Comment by Ibochkarev** [comment]
> What's your `session_handler_class` system setting set to? Flushing sessions is only supported for the standard MODX session handler (database sessions), so perhaps (1) you're using PHP file sessions or (2) the session is set to `'modSessionHandler'` and should get rewritten in an upgrade to the full namespaced class name.

Set `MODX\Revolution\modSessionHandler`

**Comment by Mark-H** [comment]
Can confirm the issue here as well. 

This check in the Security\Flush processor must not be right, perhaps that's expecting double-escaped slashes in the setting? 


        if ($this->modx->getOption('session_handler_class',null,modSessionHandler::class) === modSessionHandler::class) {

**Comment by Ibochkarev** [comment]
This error is not reproducible on the last git build.
