### ISSUE TITLE
Invalid includes in 3.0 migrations

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#15514]
### Summary

Migrations in setup/includes/upgrades/mysql/3.0.0-pl.php and setup/includes/upgrades/sqlsrv/3.0.0-pl.php are trying to include the following files that don't exist: 

``` php
include dirname(__DIR__) . '/common/3.0.0-cleanup-richtext-editor-system-settings.php';
include dirname(__DIR__) . '/common/3.0.0-remove-tv-eval-system-setting.php';
include dirname(__DIR__) . '/common/3.0.0-remove-upload-flash-system-setting.php';
include dirname(__DIR__) . '/common/3.0.0-cleanup-authentication-security-system-settings.php';
include dirname(__DIR__) . '/common/3.0.0-cleanup-lexicon-language-system-settings.php';
```

These individual migrations have been combined into `3.0.0-cleanup-system-settings.php` in #14856 by yours truly, but apparently I forgot to remove these references. 

### Step to reproduce

Doesn't seem to cause any visible errors, maybe when you have `display_errors` on and notice/warnings in `error_reporting`.  

### Observed behavior

N/a

### Expected behavior

N/a

### Related issue(s)/PR(s)

#14856

### Environment

Any

**Comment by alroniks** [comment]
It seems to be fixed with one of the merged pull requests.
https://github.com/modxcms/revolution/blob/3.x/setup/includes/upgrades/mysql/3.0.0-pl.php
