### ISSUE TITLE
Incorrect display of the file creation path

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15513]
### Summary

Incorrect display of the file creation path 

### Step to reproduce

Go to the Files tab, right-click on the assets folder and select Quick Create File from the menu.

https://user-images.githubusercontent.com/2138260/110241473-2bf34400-7f7b-11eb-83aa-a8bd4de1ae75.mp4

### Observed behavior
![image](https://user-images.githubusercontent.com/2138260/110241531-8ee4db00-7f7b-11eb-9fe7-3a2a86383bc9.png)

### Expected behavior
Should be `assets/` instead of `assets%2F`

### Related issue(s)/PR(s)
NA

### Environment
MODX Revolution 3.0.0-alpha3 (git), PHP Version 7.4.12

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/15244

**Comment by Ibochkarev** [comment]
Fixed #15517
