### ISSUE TITLE
Installation error. Make fields required?

### ISSUE THREAD

**Issue by wax100** [modxcms/revolution#15518]
### Summary
On step **setup/?action=database** If U do not fill email \ password\ username and click ENTER - page will be reloaded and all Database credentials disappear. But U can go to next page

### Step to reproduce
https://www.youtube.com/watch?v=kE-l4irUep0

### Expected behavior
Do not allow to send form (also by keyboard ENTER) if any field is empty.
Save in Session JS (or somewhere else) setting for DB if we relaod this page

### Environment
MODX 3

**Comment by Ibochkarev** [comment]
Fixed #15518
