### ISSUE TITLE
MODX3 purge cache popup changes size

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15542]
### Summary
The purge cache popup changes widths after the first use. 

### Step to reproduce
Go into the Trash manager to purge files. Remove one file, then remove a second (or else remove but cancel and then try again).

### Observed behavior
The purge cache popup is the correct size when you first click on "Erase all" or select "Purge selected resources" from the Bulk Actions popup. If you close the box or click "No", then click "Erase all" or select "Purge selected resources", the popup window shrinks to a very narrow width, and remains that width for the rest of the time you're in the Trash section.

First time popup loads:
![Screen Shot 2021-03-12 at 2 48 44 PM](https://user-images.githubusercontent.com/2528374/110993188-f668a500-8344-11eb-9331-b3f7246eda6b.png)

Second and all subsquent times:
![Screen Shot 2021-03-12 at 3 03 23 PM](https://user-images.githubusercontent.com/2528374/110993205-fd8fb300-8344-11eb-8fd4-0b0cb5e30508.png)

### Expected behavior
Cache popup should stay the same width.

### Environment
MODX 2.8.1, and also MODX 3 Alpha 3 20210309

**Comment by Ibochkarev** [comment]
Related https://github.com/modxcms/revolution/issues/14340

**Comment by Ibochkarev** [comment]
Double issue #14340
