### ISSUE TITLE
MODX3 button colors seem wrong

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15541]
### Summary
Buttons in popup windows are gray now instead of blue

### Step to reproduce
For example, delete a resource, go into the trash, click Purge All. 

### Observed behavior
The popup window has yes and no buttons, with the background color of yes being gray and no white

### Expected behavior
Primary button should be blue, not gray. Gray makes it look like the button is deactivated.

MODX 3 popup:

![Screen Shot 2021-03-12 at 2 48 44 PM](https://user-images.githubusercontent.com/2528374/110991722-fff10d80-8342-11eb-842d-a4163c46a17d.png)

Same popup in MODX 2.8:
![Screen Shot 2021-03-12 at 2 56 05 PM](https://user-images.githubusercontent.com/2528374/110991816-18f9be80-8343-11eb-9539-ef291edb054f.png)

### Environment
MODX 3 alpha 3 20210309

### Solution
The "index.css" file has this:

 .x-btn-over.x-btn, .actions button.x-btn-over,
  .x-btn-over.inline-button,
  .x-btn-over.x-superboxselect-item,
  .x-btn-over.x-form-trigger,
  .x-btn-over.x-date-mp-ok,
  .x-btn-over.x-date-mp-cancel, .x-btn:hover, .actions button:hover,
  .inline-button:hover,
  .x-superboxselect-item:hover,
  .x-form-trigger:hover,
  .x-date-mp-ok:hover,
  .x-date-mp-cancel:hover, .x-btn-focus.x-btn, .actions button.x-btn-focus,
  .x-btn-focus.inline-button,
  .x-btn-focus.x-superboxselect-item,
  .x-btn-focus.x-form-trigger,
  .x-btn-focus.x-date-mp-ok,
  .x-btn-focus.x-date-mp-cancel, .x-btn:focus, .actions button:focus,
  .inline-button:focus,
  .x-superboxselect-item:focus,
  .x-form-trigger:focus,
  .x-date-mp-ok:focus,
  .x-date-mp-cancel:focus {
    background-color: #E4E4E4;
    box-shadow: #DCDCDC;
    color: #515151;
    /*button {
      color: inherit;
    }*/ }

The background color should be changed from #E4E4E4 to #3697cd (or whatever the theme color is for primary buttons), like it is in MODX 2.8.

**Comment by Ruslan-Aleev** [comment]
Yes, it makes sense to make the buttons more visible.

**Comment by smg6511** [comment]
I believe this can be closed, as my PR that was recently merged addresses the issue. Note that I did not add back in the background behind the buttons that appears in 2.x, as it's IMO unnecessary.

**Comment by Ibochkarev** [comment]
Improved in #15826
