### ISSUE TITLE
Setting modx_browser_default_viewmode not working

### ISSUE THREAD

**Issue by Spheerys** [modxcms/revolution#15563]
I'm using Media Source with MODX 2.8.1
The default view when uploading a file inside this media source is grid.
There is a setting called modx_browser_default_viewmode where we can change the default view to list
But it is not effective (always grid view) and it's look like a bug.

Didn't it ?

**Comment by Ruslan-Aleev** [comment]
I can not reproduce the bug, I see it as a list (both in the file manager and in TV with files):

![list](https://user-images.githubusercontent.com/12523676/111658889-d2620380-881d-11eb-9fc9-25cc88598bb8.png)

The settings are set:

![sys_list](https://user-images.githubusercontent.com/12523676/111659065-f58cb300-881d-11eb-8cc2-2e9ccefc797b.png)

**Comment by Spheerys** [comment]
Hummm I realized the problem occurs under the Redactor's filemanager...
Sorry for the issue, I will search on Modmore support
