### ISSUE TITLE
Namespace info not being retrieved

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15569]
### Summary
The modNamespace object is not returning namespace info

### Step to reproduce
Put this in some code:
$obj = $modx->getObject('modNamespace', array('name', '[namespacename]'));
$componentCorePath = $obj->getCorePath();
$componentAssetsPath = $obj->getAssetsPath();

Enter whatever namespace you want.

### Observed behavior
The paths for the "core" namespace are returned, no matter which namespace you specify.

### Expected behavior
Correct paths should be returned

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX 2.8.1

**Comment by Mark-H** [comment]
Looks like a coding error:

```
 $obj = $modx->getObject('modNamespace', array('name', '[namespacename]'));
```

should be:


```
 $obj = $modx->getObject('modNamespace', array('name' => 'namespacename'));
```

Note using the key => value syntax in the array there.

**Comment by SnowCreative** [comment]
Yeah, already figured that out. I had just copied and pasted that from one of Bob Ray’s pages without looking closely. Got to notifiy him!
