### ISSUE TITLE
New password cannot be copied

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15573]
### Summary
New password cannot be copied after automatic generation of MODX

### Step to reproduce
Go to Management - Users. Select a user, check the New password checkbox, select automatic password generation and save.

### Observed behavior

https://user-images.githubusercontent.com/2138260/111960771-5cf67b80-8b1a-11eb-92bd-1dbaf5bb4248.mp4

### Expected behavior
After generation, the notification should not close immediately

### Related issue(s)/PR(s)
NA

### Environment
MODX Revolution 3.0.0-alpha3 (git), PHP Version 7.4.12

**Comment by ghost** [comment]
Actually it can be copied, but it has to be done very, very carefully. There cannot be any mouseup events. You have to move the mouse down to the notification, highlight the password without letting the mouse up, then copy using ctl-c or cmd-c. The notification will remain in place until there is a mouseup event, it doesn't disappear automatically.

That said, it is definitely a UI problem that needs to be fixed.

**Comment by Ibochkarev** [comment]
Fixed #15629
