### ISSUE TITLE
Unnecessary tabs for the anonymous user group

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15584]
### Summary
We have a user group for anonymous users. It is virtual. There are 4 tabs in the group editing interface. 

![User Group anonymous  tabs](https://user-images.githubusercontent.com/4679725/112261984-ed010600-8c7d-11eb-801e-3c0d06d39bc3.jpg)

The last two require a real group, not a virtual one. Therefore, trying to add a user or a setting to the anonymous group will cause an error.

![User Group anonymous](https://user-images.githubusercontent.com/4679725/112262133-2d608400-8c7e-11eb-8eaf-791a5a2c085d.jpg)

### Expected behavior
For the anonymous group these tabs should not be displayed.

### Environment
MODX 2.x, MODX 3.x.

**Comment by Ruslan-Aleev** [comment]
How did you get into the anonymous group edit form? Through direct link? If so, then this is not really a bug :)

**Comment by sergant210** [comment]
> How did you get into the anonymous group edit form? Through direct link?

Magic )

![Access Control Lists  MODX Revolution — Mozilla Firefox](https://user-images.githubusercontent.com/4679725/112278632-19278180-8c94-11eb-8159-f8a01c3cc075.jpg)

**Comment by Ruslan-Aleev** [comment]
In my opinion, it is more logical to turn off the menu for anonymous group. Because anonymous group shouldn't be edited or not?

**Comment by sergant210** [comment]
This group should be able to configure access permissions for contexts and resource groups.

**Comment by Ibochkarev** [comment]
Fixed #15802
