### ISSUE TITLE
Help button appears when "help" permission is set to off

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15587]
### Summary
Help button in various places appears when "help" permission is set to off. 

### Step to reproduce
Edit the ACL for your user level and turn off "help" for the assigned policy. This should remove all access to the Help page.

### Observed behavior
The Help menu is removed, as expected, but Help buttons still appear. For example, when editing a resource:

![Screen Shot 2021-03-24 at 10 18 43 AM](https://user-images.githubusercontent.com/2528374/112326217-b7aee500-8c8a-11eb-8398-cdf116cfc943.png)

### Expected behavior
If access to Help is turned off, then all buttons that link to Help should not appear.

### Environment
MODX 2.8.1 and 3.0

**Comment by sergant210** [comment]
In general, it is very strange to prohibit users from receiving help. Very very strange.

**Comment by SnowCreative** [comment]
> In general, it is very strange to prohibit users from receiving help. Very very strange.

Well, I don't agree. *I* am the help for my clients. They wouldn't be able to make any sense out of the MODX help pages, which aren't geared towards editors. And, one less button up there makes the screen less cluttered.

**Comment by Mark-H** [comment]
IIRC, the help permission is for the dedicated help page, not the contextual help buttons. Can see the confusion but I'd say that's working as expected

**Comment by ghost** [comment]
I remember years ago being able to customize those help buttons to load my own help text, but I see now that it's hard-coded in the ExtJS to the base_help_url System Setting. I suppose that you could set that to your own Help resource, and take it from there.

**Comment by alroniks** [comment]
As said Mark, it allows to define own page for showing under this button, so I am closing it as wontfix. Feel free to reopen if needed.

**Comment by SnowCreative** [comment]
Yes, it allows for a custom help page, but there is no way to disable the button altogether. That's what I'm asking for (which it seems would need a new system setting). Guess I'll have to resort to installing custom CSS to hide the button.

**Comment by SnowCreative** [comment]
And now, in MODX 3, turning the "help" option off in the policy templates doesn't even remove the help icon from the main menu.
