### ISSUE TITLE
Category rank updates only after a reload of the page

### ISSUE THREAD

**Issue by JoePetts** [modxcms/revolution#15580]
### Summary
If you rewrite the rank of the category, it will be updated only after reloading the page.

### Step to reproduce
Right click on the category, rename, rewrite rank value, save.

### Observed behavior
If you right-click on the category again and go back to rename, the old value is still there, although the new content was transferred to the database.

### Expected behavior
Here the new values should be updated automatically.

### Environment
MODx Revolution 2.8.1-pl
PHP 7.3
MariaDB

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/sort-categories-in-resource/3847/5

**Comment by ghost** [comment]
This is because the Tree is loaded via AJAX, and is not refreshed upon every change in a resource or element. That's what the `Refresh` icons are for next to each element section.

<img width="296" alt="Screen Shot 2021-03-23 at 17 18 54" src="https://user-images.githubusercontent.com/1073780/112170804-07929b00-8bfc-11eb-879f-c68c448d51ba.png">

**Comment by JoePetts** [comment]
> This issue has been mentioned on MODX Community. There might be relevant details there:
> 
> https://community.modx.com/t/sort-categories-in-resource/3847/5
This is my contribution in the community which I also wanted to mention here.

@Sottwell
Thanks for the clarification, had hardly used the update so far. Now I know in which cases this is useful.

**Comment by sergant210** [comment]
I think it's a bug. The changes should be displayed immediately. The category name changes immediately, but the rank still has the old value if you reopen the Rename dialog.

**Comment by Ibochkarev** [comment]
Fixed #15956
