### ISSUE TITLE
MODX3 Can't log in unless I'm a sudo user

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15586]
### Summary
Can't log in unless I'm a sudo user.

### Step to reproduce
Install MODX 3 alpha 3 nightly March 23. Assign your user Administrator permissions, super user. Uncheck "sudo" and save.

### Observed behavior
You'll get logged out, and can't log in again. I've tried assigning other user groups and roles, and they all fail unless sudo is checked off.

### Expected behavior
Should log in! I hadn't tested this with previous versions of alpha 3, so I don't know if this is new.

### Environment
MODX 3 alpha 3  20210323

**Comment by sergant210** [comment]
1. I created a test user without the sudo permission.
2. Added him to the Administrator group with the "Super user" role.
3. Logged in to the manager successfully.

Did I do everything right?

**Comment by SnowCreative** [comment]
> 1. I created a test user without the sudo permission.
> 2. Added him to the Administrator group with the "Super user" role.
> 3. Logged in to the manager successfully.
> 
> Did I do everything right?

Did you use the latest nightly from March 23?

**Comment by sergant210** [comment]
I just tested on the latest dev 3.x branch. It works as expected.

**Comment by Ibochkarev** [comment]
Checked on a build installed today using a composer (3.x-dev 0acc0d92fcea3fc97ab5692a8d3b55648fd6ef2c)

https://user-images.githubusercontent.com/2138260/112715700-1767f300-8f0c-11eb-861c-18cf3916c2d8.mov

**Comment by sergant210** [comment]
Did you install from the 3.x branch or as usual?

**Comment by Ibochkarev** [comment]
> Did you install from the 3.x branch or as usual?

`composer create-project modx/revolution www 3.x-dev`

**Comment by sergant210** [comment]
Confirmed.

**Comment by sergant210** [comment]
It seems to me that no one has tested permissions in MODX3. They don't work at all.

**Comment by Ibochkarev** [comment]
> It seems to me that no one has tested permissions in MODX3. They don't work at all.

This is an alarming signal.

**Comment by ghost** [comment]
Updated from github 31 March
Created user in Administrator group, not sudo user.

<img width="250" alt="Screen Shot 2021-03-31 at 8 14 37" src="https://user-images.githubusercontent.com/1073780/113093857-5ee6cb80-91f9-11eb-8684-1ca53c065670.png">

**Comment by ghost** [comment]
Aside from the obvious access denied, there is the question of the "welcome back" when this is a new user's first attempt to log in.

**Comment by sergant210** [comment]
@sottwell I found out the reason - the permissions do not work. For sudo users the permissions are not checked.

**Comment by ghost** [comment]
Yes, I just thought the screenshot and the conditions of my test would help clarify the situation.

**Comment by ghost** [comment]
I thought someone had been using MODX 3 for some time in a production environment? Did they never use the permission system, or has their customized version solved the issue for their purpose?

**Comment by sergant210** [comment]
I mean that permissions don't work for all contexts and access targets.

**Comment by sergant210** [comment]
> I thought someone had been using MODX 3 for some time in a production environment?

I think that there are no such crazy people.

**Comment by ghost** [comment]
They were in a discussion on Slack some time ago, unfortunately that means no history and I don't remember the agency's name... there was mention made of their agency returning their modifications to the community.

**Comment by Mark-H** [comment]
Sterc has been using their fork in production, but technically that's closer to 2.x than 3.x. Or 2.x with a 3.x skin. ;)

I also have a dummy site on 3.x live on alpha1 I believe but that serves nothing of any importance. 

There was a "fixing permissions" PR before the SnowUp, will see if I can find that when I'm in the office, could be related.

**Comment by Ibochkarev** [comment]
> There was a "fixing permissions" PR before the SnowUp, will see if I can find that when I'm in the office, could be related.

https://github.com/modxcms/revolution/pull/15482 - I think you mean this one. There were no others as far as my memory serves

**Comment by Mark-H** [comment]
Nope, little older than that. It was [this issue](https://github.com/modxcms/revolution/issues/15375) that should've been resolved with #15394

**Comment by SnowCreative** [comment]
Still not working in latest nightly (March 31).

**Comment by sergant210** [comment]
Not so fast. The workflow is next
1. Bug needs to be fixed (done).
2. It needs to be tested (in progress).
3. To create a PR and push it to the repository.
4. To wait a few months for the merging.

So be patient ;))

**Comment by opengeek** [comment]
> * Bug needs to be fixed (done).
> * It needs to be tested (in progress).

This is not true. This issue has not identified a specific bug that has been fixed, yet. Nor is anyone working on it that I know of. Please correct me if I'm wrong.

> * To wait a few months for the merging.

Can we PLEASE stop with the sarcasm? It is counter-productive at the very least.

**Comment by sergant210** [comment]
> This is not true. This issue has not identified a specific bug that has been fixed, yet. 

This is not true. I've identified the problem, fixed it and  I'll test it as soon as I can. 

> Nor is anyone working on it that I know of. Please correct me if I'm wrong.

You are wrong. Look at the assignees above.

> Can we PLEASE stop with the sarcasm? It is counter-productive at the very least.

A sense of humor very often saves us from depression. I think we could all use a little smile ;)

**Comment by opengeek** [comment]
> > This is not true. This issue has not identified a specific bug that has been fixed, yet.
> 
> This is not true. I've identified the problem, fixed it and I'll test it as soon as I can.
> 
> > Nor is anyone working on it that I know of. Please correct me if I'm wrong.
> 
> You are whrong. See the assignees above.

Thank you for clarifying. I did not read any comments saying the problem had been identified or that you were working on a solution. Assigning yourself the issue does not tell me anything specific.

> > Can we PLEASE stop with the sarcasm? It is counter-productive at the very least.
> 
> A sense of humor very often saves us from depression. I think we could all use a little smile.

I agree. Humor is very important. But this particular comment and other similar comments coming from people that are supposed to be working together to increase the pace of integration on this project are debatably funny and can easily be misinterpreted by those that have been responsible for integration. It has been made clear over and over how everyone feels about the pace of integration. There is no need to amplify that. We can make different jokes and work together to solve the contribution issues.

**Comment by Ibochkarev** [comment]
Fixed #15632
