### ISSUE TITLE
Create and Quick Create Dropdowns 

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#15590]
### Summary
The Create and Quick Create dropdowns don't drop down

### Step to reproduce
In the Tree, in the Resources tab, right-click to bring down the Resources menu. 

### Observed behavior
The Create and Quick Create dropdowns don't drop down.

<img width="318" alt="Screen Shot 2021-03-25 at 7 48 47" src="https://user-images.githubusercontent.com/1073780/112425947-ae338480-8d3f-11eb-818c-328fcad4b091.png">

### Expected behavior
The Create and Quick Create submenus should drop down, as they do on earlier installations

<img width="421" alt="Screen Shot 2021-03-25 at 7 56 23" src="https://user-images.githubusercontent.com/1073780/112425987-c5727200-8d3f-11eb-9b7f-b68e2d807958.png">

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX 3.0.0 Alpha 3, updated from git 25 March

**Comment by Ruslan-Aleev** [comment]
@digitalpenguin When you have time, please fix this bug.
After your PR - https://github.com/modxcms/revolution/pull/15424 this condition is no longer triggered:

https://github.com/modxcms/revolution/blob/5169becd127ae0f5fe3eb5794da63797372af779/manager/assets/modext/widgets/resource/modx.tree.resource.js#L665

**Comment by muzzwood** [comment]
Sure, I'll look into that tomorrow morning.

**Comment by muzzwood** [comment]
Fixed in #15593
