### ISSUE TITLE
Resource and Element Duplicate Checkbox Default State Consistency

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#15592]
### Summary
The "Redirect to duplicate" checkbox default states are not consistent

### Step to reproduce
Duplicate a Resource or Element from the Tree
<img width="300" alt="Screen Shot 2021-03-25 at 8 18 27" src="https://user-images.githubusercontent.com/1073780/112427987-2ea7b480-8d43-11eb-82bf-c95c77f164d0.png">

Duplicate a Resource or an Element from its menu
<img width="300" alt="Screen Shot 2021-03-25 at 8 19 12" src="https://user-images.githubusercontent.com/1073780/112428054-3b2c0d00-8d43-11eb-82dd-abebe644350b.png">

### Observed behavior
When duplicating from the Tree, the checkbox is clear by default.
When duplicating from the Resource's or the Element's menu, the checkbox is checked by default.

### Expected behavior
The two should be consistent, both either checked or clear by default.

### Environment
MODX 3.0.0 Alpha 3, from git 25 March.

**Comment by Ruslan-Aleev** [comment]
I think the current state is correct.
When copying a resource through a tree, a redirect to the copy is not needed, because you can edit a completely different resource, or, for example, a chunk.
And when copying a resource from the resource editing form, it is more often necessary to edit the new copy, as it seems to me. If we turn off the checkbox in resource editing form, you will have to turn it back on when copying - bad for the UX.

**Comment by ghost** [comment]
That makes sense, although even if it were checked by default and you were redirected to the new duplicate, you can still use the Tree to go where you want just the same.

However, it's a very minor matter of personal perception, since no real functionality is impacted.

**Comment by alroniks** [comment]
> That makes sense, although even if it were checked by default and you were redirected to the new duplicate, you can still use the Tree to go where you want just the same.

What if you have unsaved changes in the current documents, but a copy is really needed? You may lose them. The current implementation seems to be more convenient. It is not about consistency, it about useful UX based on the context of usage.

I am closing it as wontfix, but you always free to restart the discussion by reopening issues.
