### ISSUE TITLE
User name in the manager

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15595]
### Summary
In the manager it is not clear what user is logged in. 

![username](https://user-images.githubusercontent.com/4679725/112712944-985ec480-8ee3-11eb-9617-d47cf8399f5d.jpg)

### Suggested solution(s)
May be to add a header to the context menu.
![username](https://user-images.githubusercontent.com/4679725/112713104-65690080-8ee4-11eb-9be0-a49dc4641946.jpg)

**Comment by Ruslan-Aleev** [comment]
@opengeek @rthrash And why are labels hidden in the bottom menu? Can we display them in the same way as in the menu above? Now it's just hidden through css. And it will be like this:

![footer_menu](https://user-images.githubusercontent.com/12523676/113025517-b43ac280-9190-11eb-9f5f-9f3c3842835f.png)

**Comment by opengeek** [comment]
@Ruslan-Aleev — @rthrash and I have nothing to do with that as far as I know. I'm not sure why you are @ mentioning us?

**Comment by sergant210** [comment]
I would suggest to rename the Admin menu item to System.

**Comment by Ruslan-Aleev** [comment]
@opengeek Who to ask then? Knowing your conservative attitude towards PRs, it is probably logical to assume that such a display of the menu was done, at least with your approval.

**Comment by Mark-H** [comment]
Jason has never been involved with the UI side of things, we all have our areas of expertise 😅

I suppose this was built this way for simplicity, based on initial designs that came out of the sterc project. That was probably not extensively discussed one way or another, but just one person's concept that was further adapted over time.

Important to note there's not much room (horizontally), 
so people using an email address as username for example would never fit in the sidebar itself. 

For system/help it would fit better if people think that's better. Right now in 2.x there's no label for that either though.

**Comment by jaygilmore** [comment]
I don't think any value is added in finding out who made the specific design choice or who accepted it in the first place. I think our energies would be better spent in working to offer considered solutions to what is likely a valid UX concern. 

The "how" it gets implemented definitely merits discussion. As @Mark-H notes, it could get messy there with longer usernames or lexicon entries for different languages (German words can get pretty long). Without looking at the code recently, there may also be some other considerations around accessibility. 

Something that pops into my mind is that there is a fairly common admin UI, UX pattern of having image/icon-only toolbars in a minimal state but can be expanded for full-text versions. It would be good to consider this pattern in the wild when it comes to considering how we implement this. Also, it makes sense to see if there are other icon-only elements in MODX and how we're presenting those. There may be some way to find similarities, but things like a help icon might not ever need text displayed.  

Finally, this feature request, is pointing to the fact that the username is not displayed with the icon representing the User. Could the logged-in user's name to appear elsewhere in the Manager while logged in?

**Comment by alroniks** [comment]
> May be to add a header to the context menu.

I suggest replacing the Profile title in the first element with a username.

**Comment by Ruslan-Aleev** [comment]
Fixed in https://github.com/modxcms/revolution/pull/15973
