### ISSUE TITLE
sanitizePatterns should be extended to avoid xss

### ISSUE THREAD

**Issue by it-scripter** [modxcms/revolution#15604]
### Summary
XSS issues for the usage of sanitizePatterns

### Step to reproduce
In my case with a search form based upon simpleSearch - but this is based on modx::sanitizePatterns, so it will be pop up on different places.
use these parameters  for your simpleSearch-Page-URL: 
A: ?search=Test"><svG%20onLoad=prompt(9)>
or
B: ?search=Test"><img%20src=...here an URL for an image - without quotes %20/>
or
C: ?search=Test"><script%20src=...here an URL for an js file - without quotes %20/>

### Observed behaviour
You can see
A: a prompt (just to show that there was code executed
B: an image is shown as "not found string"
C: a javascript code is loaded and executed as "not found string"

### Expected behaviour
This must suppress - nothing of this should happen

### Related issue(s)/PR(s)
unknown

### Environment
MODX version 2.8.1
simpleSearch: 2.1.2

Again: simpleSearch based upon the core sanitized function and therefore is a core issue

My first trial is to change modx.class.php #224 added "images", "svg" and "scripts" ( this is script with ending tag: /> )
```php
    public $sanitizePatterns = array(
        'scripts'       => '@<script[^>]*?>.*?</script>@si',
        'entities'      => '@&#(\d+);@',
        'tags1'         => '@\[\[(.*?)\]\]@si',
        'tags2'         => '@(\[\[|\]\])@si',
        'images'        => '@<img@si',
        'svg'           => '@<svg@si',
        'scripts2'      => '@<script[^>]*?>.*?/?>?@si',
    );
```
But I have no clue if this has side effects.

**Comment by Mark-H** [comment]
I don't think that's meant for XSS protection, and if simplesearch is using it that way, simplesearch is doing it wrong. To my knowledge that's only supposed to filter out MODX tags in non-mgr contexts.

**Comment by it-scripter** [comment]
Okay, Mark. "Sanitize" sounds like a way to avoid xss. And with <script>...</script> it works. 
Is there another method to sanitize incoming post or get parameters?  

If so, can I make a change request for simpleSearch.
It is now developed by sterc and not splittingred, right?

I always thought that POST and GET parameters are cleaned automatically by modx, or am I confusing it with another system again?

**Comment by Ibochkarev** [comment]
> It is now developed by sterc and not splittingred, right?

https://github.com/modxcms/SimpleSearch

**Comment by it-scripter** [comment]
What's about:
https://docs.modx.com/current/en/extras/simplesearch/index
there is a link to this repo: https://github.com/Sterc/SimpleSearch

that's confusing, @Ibochkarev 
and as I can see, the sterc repo isn't a fork.

**Comment by sergant210** [comment]
This is the responsibility of the site developer, not MODX. 

As for SimpleSearch, it should filter user data.

**Comment by Ibochkarev** [comment]
> What's about:
> https://docs.modx.com/current/en/extras/simplesearch/index
> there is a link to this repo: https://github.com/Sterc/SimpleSearch
> 
> that's confusing, @Ibochkarev
> and as I can see, the sterc repo isn't a fork.

I was wrong. Sterс will have a fresh fork.

**Comment by Mark-H** [comment]
> Okay, Mark. "Sanitize" sounds like a way to avoid xss. And with <script>...</script> it works.

Sanitize can mean very different things in different contexts and will need different handling depending on where and how it's used. 

> Is there another method to sanitize incoming post or get parameters?

For simplesearch/xss filtering, you'd typically use htmlentities as part of the render process. I've definitely added the htmlent output filter to the simplesearch form on a few sites before so if that hasn't since been made the default, it should be. ;)

**Comment by it-scripter** [comment]
> > Okay, Mark. "Sanitize" sounds like a way to avoid xss. And with <script>...</script> it works.
> 
> Sanitize can mean very different things in different contexts and will need different handling depending on where and how it's used.

Indeed

> > Is there another method to sanitize incoming post or get parameters?
> 
> For simplesearch/xss filtering, you'd typically use htmlentities as part of the render process. I've definitely added the htmlent output filter to the simplesearch form on a few sites before so if that hasn't since been made the default, it should be. ;)

You are right: I remember using it before (a long time ago). Of course, it would be better to handle it with the incoming data, because XSS is just one risk, and SQL injection remains a high risk

**Comment by it-scripter** [comment]
After some further research I've found an access to a request variable directly from url - for using inside the form - with no sanitizing via modx or simpleSearch. 
Therefore this is obviously my fault this bug report can be close. 
Thanks for your support.
