### ISSUE TITLE
Incorrect class key for new user

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15619]
### Summary
Incorrect default value of the class key in the "New user" from.

![user](https://user-images.githubusercontent.com/4679725/113248517-ccf8c480-92c5-11eb-9360-dace204c7076.jpg)

### Step to reproduce
Try to create a new user.

### Observed behavior
The class key has `modUser` value.

### Expected behavior
The default value should be `MODX\Revolution\modUser`.

### Environment
MODX3 alpha3.

**Comment by alroniks** [comment]
Seems to be fixed
