### ISSUE TITLE
Inactive permission for the toggle language item

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15616]
### Summary
For not sudo users the "Toogle language" menu item is not displayed. The reason is that the corresponding permission is not checked in the access policies.

### Step to reproduce
1. Add a new user (not sudo) with the Administrator access permission with the Super User role.
2. Log in in the manager.
3. Optn the user menu.

### Observed behavior
![lang1](https://user-images.githubusercontent.com/4679725/113097369-745ef400-91ff-11eb-8722-f303c61e1ef2.jpg)

### Expected behavior
![lang2](https://user-images.githubusercontent.com/4679725/113097391-7a54d500-91ff-11eb-86d6-44ca243a3068.jpg)

### Environment
MODX3 alpha3.

**Comment by sergant210** [comment]
@alroniks The error is [here](https://github.com/modxcms/revolution/blob/0a3052e5afe038389820a6df64ea2c7870bee48b/_build/data/transport.core.menus.php#L397).

**Comment by Ibochkarev** [comment]
Fixed #15621
