### ISSUE TITLE
Incorrect display of messages in installer

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15617]
### Summary
Incorrect display of messages in the installer:
1) Some css styles are missing.

![installer](https://user-images.githubusercontent.com/12523676/113179181-08f54080-9258-11eb-9e5f-4019ea940cf5.png)

2) There are empty lists without messages (`<li class=""></li>`).

```
<ul class="checklist success">
    <li class="testPassed"><p>Checking PHP version: <span class="ok">OK! Running: 7.3.20</span></p></li>
    <li class=""></li>
    <li class="testPassed"><p>Checking PHP for zlib dependency:  <span class="ok">OK!</span></p></li>
    ...
    <li class=""><p>Creating connection to the database: </p></li>
    <li class="testWarn"><p class="notok">Database connection failed!</p><div class="notes"><p>Setup will attempt to create the database.</p></div></li>
    <li class=""></li>
    <li class="testPassed"><p>Checking for suhosin issues:<span class="ok">OK!</span></p></li>
    ...
</ul>
```

The templates for displaying messages are clearly not working correctly.

### Step to reproduce
Cause a database connection error, for example.

### Environment
MODX 3

**Comment by Ibochkarev** [comment]
Fixed #15642
