### ISSUE TITLE
Untranslated descriptions of ACL policy templates

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15625]
### Summary
ACL Policy Template Descriptions display untranslated lexicon key.

![acl](https://user-images.githubusercontent.com/4679725/113377417-e9a40380-937c-11eb-9cf4-95d85412d335.jpg)

### Step to reproduce
Open any ACL Policy Template.

### Environment
MODX3 alpha3.

**Comment by Ibochkarev** [comment]
Related https://github.com/modxcms/revolution/pull/14009
