### ISSUE TITLE
Missing "file_folder_rename" lexicon key 

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15639]
### Summary
Missing "file_folder_rename" lexicon key for non english language.

### Step to reproduce
Open the file tree tab and right click on any folder.

### Observed behavior
![folder_rename](https://user-images.githubusercontent.com/4679725/113815686-4720c180-977c-11eb-89cc-8d595bb93062.jpg)

### Environment
MODX 3.0.0-aplha3.

**Comment by Ibochkarev** [comment]
@sergant210 https://github.com/modxcms/revolution/pull/15420/files#diff-504b9db47edaa07ce0652980a302dacb243685a90efbf80d858fe51f71272154R74 - It was added in this PR

**Comment by sergant210** [comment]
@Ibochkarev Only for English lexicon. So for other languages we got only the untranslated lexicon key.

**Comment by Ibochkarev** [comment]
@opengeek I checked in Crowdin - this key is not available for translation. This is a sync error.

**Comment by Ibochkarev** [comment]
This fixed in https://github.com/modxcms/revolution/pull/15615
