### ISSUE TITLE
Missing "updates_type" lexicon key

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15649]
### Summary
Missing "updates_type" lexicon key in the[ dashboard lexicons ](https://github.com/modxcms/revolution/blob/8b80072f03c4efc539edea1d906e82ff60266480/core/lexicon/en/dashboard.inc.php#L27)for other languages.

### Step to reproduce
Open the dashboard.
![dashboard](https://user-images.githubusercontent.com/4679725/113976879-5ec67b80-984a-11eb-8a0a-73f8e297bc2e.jpg)

### Expected behavior
![type_english](https://user-images.githubusercontent.com/4679725/113976985-8cabc000-984a-11eb-937c-8705a959cd59.jpg)

### Environment
MODX 3.0.0-alpha3.

**Comment by Ibochkarev** [comment]
![изображение](https://user-images.githubusercontent.com/2138260/113979786-8841d000-9867-11eb-82fc-88865d54fd81.png)

Translated 10 days ago. But PR from Crowdin not.

**Comment by JoshuaLuckers** [comment]
@sergant210 @Ibochkarev is the lexicon still missing?

**Comment by Ibochkarev** [comment]
![изображение](https://user-images.githubusercontent.com/2138260/131216530-ac61d887-285a-41d2-bb9e-66940ca51ab1.png)

latest build
