### ISSUE TITLE
Dropdown menu is broken when creating internal message

### ISSUE THREAD

**Issue by alroniks** [modxcms/revolution#15662]
### Summary
When you try to create an internal message and try to select a user group or role as a recipient, the dropdown with these entities is broken (see screenshot).

![Messages _ MODX Revolution](https://user-images.githubusercontent.com/303498/114288317-54d59000-9a77-11eb-83b8-9e97f5230889.png)

### Step to reproduce
Try to send messages to the user group or role.

### Observed behavior
Dropdown works, but the width set too small and the UI looks broken.

### Expected behavior
The field should be available for usage without UI glitches.

### Related issue(s)/PR(s)
N/A

### Environment
MODX 3 git, nginx, mysql 5.7, chrome.

**Comment by sergant210** [comment]
I can't reproduce it.

**Comment by theboxer** [comment]
Can't reproduce it either. Feel free to reopen with more details if you still experience the issue.
