### ISSUE TITLE
Bug in sending internal message

### ISSUE THREAD

**Issue by realrork** [modxcms/revolution#15661]
### Summary
When I send a message to an internal user and select the 'Send email' option, the delivered message shows 'emailsubject' instead of the subject entered in the 'Subject' field. Subject of the message is correctly displayed inside MODX Manager. I checked it in English and Polish version.

### Step to reproduce
Sending a message to an internal user with the 'Send email' option checked.

### Observed behavior
The received message contains 'emailsubject' instead of a valid message subject.

### Expected behavior
The received message should contain an email subject that matches the one entered in the 'Subject' field when the message was created.

### Related issue(s)/PR(s)
I didn't find one.
Actually this one #15661 

### Environment
MODX version - 3.0.0-ALPHA3, apache version 2.4.6, mysql versionVer 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1 , browser Opera and Vivaldi, etc.
![obraz_2021-04-09_153235](https://user-images.githubusercontent.com/55298437/114187905-cf53c200-9948-11eb-9ae3-abbb8d2f0209.png)

**Comment by alroniks** [comment]
I can not reproduce it on the latest git version of MODX 3. I am closing the issue. But could you please check, that the latest code works for you?
