### ISSUE TITLE
Missing Lexicon [Bug] 

### ISSUE THREAD

**Issue by Jasper-TM** [modxcms/revolution#15684]
### Summary
Lexicon is not available or missing. Couldn't find or locate the string in the Lexicons. 
Searched in manager and crowdin.

### Observed behavior
![Missing lexicon2](https://user-images.githubusercontent.com/82947152/115593108-61a67f00-a2d4-11eb-9146-3fc53283d1d5.jpg)

### Expected behavior
Should be translatable to other languages

### Environment
MODX 2.8.2-dev, MODX 2.x

**Comment by Ruslan-Aleev** [comment]
This is the media source name, can be configured in `/manager/?a=source` section.

![ms](https://user-images.githubusercontent.com/12523676/115851922-2ae57b80-a430-11eb-8b07-65634a36bf39.png)

**Comment by alroniks** [comment]
It is the name of the resource (in this case media source) which means that it can not and shouldn't be translated. Closing as wontfix.
