### ISSUE TITLE
Russian characters are not displayed in the media source

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15682]
### Summary
Russian characters are not displayed in the media source, neither in folder names, nor in files.

![browser_ru](https://user-images.githubusercontent.com/12523676/115532674-b0d1bd00-a29e-11eb-9eac-7d2f9fb28ab4.gif)

And they are cut when uploading files to the server (the file in the GIF was called `фон_123.png`).

![browser_ru_2](https://user-images.githubusercontent.com/12523676/115532680-b202ea00-a29e-11eb-82ad-325039b56989.gif)

Moreover, if you create a folder with a russian name inside a folder, for example, inside `assets`, then another empty `assets` folder will appear inside `assets`, and so on for any folder.

![browser_ru_3](https://user-images.githubusercontent.com/12523676/115533649-9a783100-a29f-11eb-91d9-cb162296fe5a.gif)

Perhaps the problem is relevant for other languages as well.

p.s. And it doesn't depend on the `upload_translit` setting, as it might seem at first.

### Step to reproduce
Try to create a folder, for example, named `привет`.

### Environment
MODX 3-alpha3

**Comment by webinmd** [comment]
To display russian characters, you must set in the system settings
locale = ru_RU.UTF-8

Or change php function basename 
https://github.com/modxcms/revolution/blob/48af06a07a436ca2f7775a49fc681fa36269e4d5/core/src/Revolution/Sources/modMediaSource.php#L1942

**Comment by rthrash** [comment]
This seems to be fixed per https://github.com/modxcms/revolution/issues/15328#issuecomment-1742291356 … can you confirm @Ruslan-Aleev

**Comment by Ruslan-Aleev** [comment]
@rthrash Yes, visually everything works. Thank!
