### ISSUE TITLE
XPDO sortby: Default Sort Direction Breaks Some Queries

### ISSUE THREAD

**Issue by smg6511** [modxcms/revolution#15687]
### Summary
When supplying a SQL function/clause [ e.g., _->sortby('RAND()')_ ] instead of the typical _->sortby('column', 'direction')_, some queries are broken. Currently the RAND function is forgiving of the 'ASC' added to the resulting ORDER BY clause although it is not technically correct to do so. I imagine the same goes for the FIELD function. However, the use of a CASE/WHEN clause will break because the direction is specified within each case of that clause.

### Step to reproduce
This issue was found when attempting to sort on a date TV — used to indicate an expiration date for an announcement banner — where the value could be left empty (null) to allow the condition to be open-ended. The sort clause below is used to first order the field by those that are null first (where the createdon date would serve as the sorting value) and the filled values second (where the TV value is used to sort).
`
$c->sortby('
    CASE WHEN `dateEnd` IS NULL THEN 0 ELSE 1 END,
    CASE WHEN `dateEnd` IS NULL THEN `createdon` ELSE `dateEnd` END DESC
');
`

### Observed behavior
The sortby clause is appended with 'ASC' — the default direction value — resulting in two direction specs, causing the entire query to fail. Also when attempting to move the direction (DESC) specification out of the CASE clause and to the second parameter of sortby, the query is broken. (This would be an undesirable strategy, even if it worked, as it would still not allow multiple CASE conditions having different sort directions.) Finally, attempting to supply an empty string for the direction parameter also failed.

### Expected behavior
The easiest way to overcome the issue and maintain compatibility is to allow for an empty (explicitly set) direction value, for example:
`->sortby('[Custom Clause]', '');`

### Related issue(s)/PR(s)
A PR with my proposed solution will be issued momentarily.

### Environment
Observed in MODX 2.7.3 (the issue would be present in 2.8 and 3.x as well [the xpdo code has not changed])
Linux, Mysql (5.5.68-MariaDB), Apache 2, PHP 7.4.16

**Comment by opengeek** [comment]
This should be on the xPDO repository, not Revolution.

**Comment by smg6511** [comment]
OK, didn't realize that. Will re-post to that repo.

**Comment by alroniks** [comment]
@smg6511 Please, link issues after posting it on the xPDO repo and close this one. Thank you in advance.

**Comment by smg6511** [comment]
Reposted to XPDO repo, [Issue #202](https://github.com/modxcms/xpdo/issues/202)
