### ISSUE TITLE
Can no longer drag files to other folders in the Files tree in 2.8.2

### ISSUE THREAD

**Issue by shonnarenae** [modxcms/revolution#15694]
### Summary
Can no longer drag files to other folders in the Files tree. 

### Step to reproduce
Upload a file. Attempt to drag it into another folder.

### Observed behavior
The tree collapses and refreshes and the file does not appear in the desired folder, it remains where it was.

### Expected behavior
The file should be moved to the folder it was dragged to.

### Environment
Observed on sites upgraded from 2.8.1 to 2.8.2 as well as a new clean 2.8.2 install. PHP 7.3. This was all done on nginx / MODX Cloud, not sure if issue is specific to that environment.

**Comment by opengeek** [comment]
I can confirm this behavior in 2.8.2 on PHP 8, as well.

**Comment by wfoojjaec** [comment]
Related to https://github.com/modxcms/revolution/pull/15505
Id's in filesystem tree look like "assets%2F" instead of "assets/". This prevents any actions on them.
