### ISSUE TITLE
Media browser thumbnails missing in MODX 2.8.2/PHP8

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [modxcms/revolution#15691]
### Summary
Media browser thumbnails missing in MODX 2.8.2/PHP8.

### Step to reproduce
Update to MODX 2.8.2 and switch to PHP8.

### Observed behavior
Thumbnails are visible in PHP 7.4

### Expected behavior
Thumbnails should be visible visible

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX 2.8.2  / PHP 8.03
```FastCGI sent in stderr: "PHP message: PHP Fatal error: Array and string offset access syntax with curly braces is no longer supported in .../core/model/phpthumb/modphpthumb.class.php on line 269```

The offending line: 
``` } elseif ($this->iswindows && isset($filename{1}) && ($filename{1} == ':')) {```

**Comment by wfoojjaec** [comment]
Messed with branches.
The updated PR with all changes is here.
https://github.com/modxcms/revolution/pull/15699
