### ISSUE TITLE
table_prefix no longer working in @SELECT

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [modxcms/revolution#15695]
### Summary
I used to be able to use [[++table_prefix]] in a @SELECT chunk used in a TV

### Step to reproduce
tv: wine_select_id; type: listbox; input options: @CHUNK wine_select_id
chunk: wine_select_id; code:
@SELECT '---' as pagetitle, '' as id UNION ALL SELECT pagetitle, id FROM [[++table_prefix]]site_content 
WHERE parent IN(301) AND class_key='modDocument' AND deleted=FALSE AND hidemenu=FALSE
ORDER BY pagetitle ASC

### Observed behavior
Only shows blank line and previously selected ID
No errors

### Expected behavior
I expected a list of IDs

If I change  [[++table_prefix]]site_content  to  modx_site_content the listbox works as expected, but this makes the code much less portable

### Environment
MODX 2.8.2 / PHP 7.4.16

**Comment by sergant210** [comment]
In 2.8.2 some sensitive settings [were removed](https://github.com/modxcms/revolution/pull/15677) from system placeholders for security reasons. Use the way from the [documentation](https://docs.modx.com/current/ru/building-sites/elements/template-variables/bindings/select-binding).

**Comment by jmacdonald-spectacle** [comment]
Excellent. Thank you!

**Comment by opengeek** [comment]
I would argue this is disruptive and that many people were using this placeholder in this way. I think this should be fixed.

**Comment by jmacdonald-spectacle** [comment]
At the least, the change log could have been more specific. If I had known it would be a problem, I wouldn't have updated until I addressed it.

**Comment by Mark-H** [comment]
Setting placeholders being removed from TVs was not an intentional change, hence not in the changelog. ;)

**Comment by sergant210** [comment]
@Mark-H I believe that this placeholder should be hidden. There is [another way](https://docs.modx.com/current/ru/building-sites/elements/template-variables/bindings/select-binding) to use the table prefix in TVs.

**Comment by opengeek** [comment]
> @Mark-H I believe that this placeholder should be hidden. There is [another way](https://docs.modx.com/current/ru/building-sites/elements/template-variables/bindings/select-binding) to use the table prefix in TVs.

I don't understand why this additional PREFIX placeholder was created. 🤦🏻

**Comment by jmacdonald-spectacle** [comment]
And when? And why such a generic name?

**Comment by sergant210** [comment]
![table_prefix](https://user-images.githubusercontent.com/4679725/117188579-e1107400-ade5-11eb-9786-87666cc3591a.jpg)

**Comment by opengeek** [comment]
Aaaaaand that's what I get for opening my mouth. 🤐 😂

**Comment by opengeek** [comment]
But, regardless of blame, I still do not understand the need for these extra placeholders when the regular placeholders could be used. And how are these any less of a security risk than the regular placeholders for those options?

**Comment by Mark-H** [comment]
As it's only in select bindings from the looks of it that would greatly limit the exposure if those variables. Perhaps we can add the table_prefix there too as a way to keep BC without making it available globally in frontend variables too?

**Comment by opengeek** [comment]
> As it's only in select bindings from the looks of it that would greatly limit the exposure if those variables. Perhaps we can add the table_prefix there too as a way to keep BC without making it available globally in frontend variables too?

Would it? Don't more lower-level editors have access to Template Variables than Templates, Chunks, etc.? Perhaps I'm not thinking of the same exposure?

**Comment by Mark-H** [comment]
I was thinking of content editors placing it in resources more so than elements.

**Comment by opengeek** [comment]
> I was thinking of content editors placing it in resources more so than elements.

Exactly… if an editor can access a Resource, can't they edit the TVs on it?

**Comment by Mark-H** [comment]
Oh like that. I thought only the people editign the actual TV could affect the `@SELECT` and tweak that to read the actual value, but may be wrong.

**Comment by SnowCreative** [comment]
> In 2.8.2 some sensitive settings [were removed](https://github.com/modxcms/revolution/pull/15677) from system placeholders for security reasons. Use the way from the [documentation](https://docs.modx.com/current/ru/building-sites/elements/template-variables/bindings/select-binding).

Hmm. On that documentation page, shouldn't:

JOIN site_tmplvar_contentvalues as tv_val ON page.id=tv_val.id

instead be:

JOIN site_tmplvar_contentvalues as tv_val ON page.id=tv_val.contentid

?

**Comment by jmacdonald-spectacle** [comment]
I'm not following the logic for where and why this change was made, but I just tested adding [[++table_prefix]] in the content field as a content-only user. 2.8.1 shows the setting, when the resource is viewed while 2.8.2 does not. This seems to be at least part of the reason for the change, so I guess that's good.

On the other hand, regarding the 'replacement' placeholder: [[+PREFIX]] seems a little non-specific and generic enough that a developer might use it for something else.

**Comment by Mark-H** [comment]
Correct, the reason for it is also described here: #15677

`[[+PREFIX]]` is set specifically only for the TV processing so shouldn't be available in other cases.
