### ISSUE TITLE
Update to 2.8.2 issue with migx & media sources - not creating directories using migxObjectMediaPath

### ISSUE THREAD

**Issue by BigBlockStudios** [modxcms/revolution#15707]
I have a migx config that creates directories in 2 specific media sources for a project manager tool within the modx manager.
The directories are no longer automatically created after the update to 2.8.2

The tools process is:

- create and save a new project
- the code will then create the directories for that project in the media sources (not working)
- the media sources basepath and baseurl are defined as:

[[!migxObjectMediaPath? &pathTpl=assets/projects/{id}/documents/ &createFolder=1]]

So here is the funny part ... all I have to do is view the Media->Media Sources page, I don't even have to open the specific media source ... and the directories will be created - the user can return to the project and start adding files.

Seems to be cache related so I am including the core/cache/media_sources/web/source.cache.php files (which looks very odd)
[source.cache.txt](https://github.com/modxcms/revolution/files/6435683/source.cache.txt)

**Comment by Bruno17** [comment]
could you try downgrading to 2.8.1 or try the same setup on a 2.8.1 installation, to confirm, that it is related to the MODX upgrade

**Comment by BigBlockStudios** [comment]
It's been in daily use for several years now, I don't see how it is not related.  I will spin up a backup on a test site though to confirm. 

Seems to be cache related?  how/when does modx refresh the media source cache? (I'm thinking of manually clear the media source cache before the project is saved?)

**Comment by Bruno17** [comment]
And I currently don't see, how it can be related. I want to be sure, that the same setup is working on 2.8.1 but not working on 2.8.2 before taking the time to dive into it. And I can't say, if it has anything todo with caching before diving.

**Comment by BigBlockStudios** [comment]
Fair enough! :)     I'll spin up the backup sometime later today & let you know.

**Comment by BigBlockStudios** [comment]
OK - did some testing on the old version of modx:

- the error is not related to the update modx 2.8.1 -> 2.8.2
- the error manifests when migx is updated from 2.12 -> 2.13 

still the same behaviour though, I get a directory does not exist error unles I just open the media source page - then the dynamic directories get created.

**Comment by BigBlockStudios** [comment]
Solved.    The issue is in the migxObjectMediaPath snippet

$createpath can never be set TRUE unless the $objectid is empty

this fixes,  looking at the original app I had to do this years back also.

$createpath = false;
$createpath = $createfolder; <- works.

**Comment by opengeek** [comment]
Identified as an issue in an extra and not the core.
