### ISSUE TITLE
Static element with [[++core_path]] no longer finds path in 2.8.2

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#15708]
### Summary

Static snippet with media source set to (empty) and path like this:

```
[[++core_path]]components/something/elements/snippets/something_else.snippet.php
```

no longer appears to resolve, leaving the snippet empty and functionality broken. 

### Step to reproduce

Add a static snippet with a path like above, save, refresh and note it stays empty.

Change it to the full path, save, refresh, and note it does render.

### Observed behavior

Stays empty, snippet no longer works.

### Expected behavior

This gets tricky but #15677 seems to have had more side effects than intended (like #15695 as well) and we either need to relax the settings that get filtered, or perhaps find a way to not have it affect specific use caes.   

### Related issue(s)/PR(s)

#15677

### Environment

MODX 2.8.2

**Comment by sergant210** [comment]
I stated my thoughts on the forum in the security section.

**Comment by Mark-H** [comment]
We're no longer dealing with this as a potential security issue so I'm not sure we have to discuss the next step to deal with the unintended side effect in private?

**Comment by opengeek** [comment]
For now, would it be sufficient to add the setting to disable this filtering as an actual system setting and bring significant attention to it in the release announcement for 2.8.3?
