### ISSUE TITLE
MODX 2.8.2 PHP8 issue with phpthumb.class.php after applying #15699

### ISSUE THREAD

**Issue by deJaya** [modxcms/revolution#15703]
### Summary
After applying #15699 - a further step was required to fix the issue of thumbnails not showing in the Media Browser.

### Step to reproduce
Apply #15699 - thumbnails still missing.

### Observed behavior
Thumbnails still missing. Following PHP error:

[03-May-2021 21:42:35 UTC] PHP Fatal error:  Uncaught TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /home/xyz/public_html/core/model/phpthumb/phpthumb.class.php:1922
Stack trace:
#0 /home/xyz/public_html/core/model/phpthumb/phpthumb.class.php(1922): round()
#1 /home/xyz/public_html/core/model/phpthumb/phpthumb.class.php(3455): phpthumb->ImageMagickThumbnailToGD()
#2 /home/xyz/public_html/core/model/phpthumb/phpthumb.class.php(371): phpthumb->ExtractEXIFgetImageSize()
#3 /home/xyz/public_html/core/model/phpthumb/modphpthumb.class.php(164): phpthumb->GenerateThumbnail()
#4 /home/xyz/public_html/core/model/modx/processors/system/phpthumb.class.php(69): modPhpThumb->generate()
#5 /home/xyz/public_html/core/model/modx/modprocessor.class.php(185): modSystemPhpThumbProcessor->process()
#6 /home/xyz/public_html/core/model/modx/modx.class.php(1770): modProcessor->run()
#7 /home/xyz/public_html/core/model/modx/modconnectorresponse.class.php(144): modX->runProcessor()
#8 /home/xyz/public_html/core/model/modx/modconnectorrequest.class.php(86): modConnectorResponse->outputContent()
#9 /home/xyz/public_html/core/model/modx/modconnectorrequest.class.php(73): modConnectorRequest->prepareResponse()
#10 /home/xyz/public_html/connectors/system/phpthumb.php(19): modConnectorRequest->handleRequest()
#11 {main} thrown in /home/xyz/public_html/core/model/phpthumb/phpthumb.class.php on line 1922

Lines 1921 and 1922:
```
$nw = ((round($nw) != 0) ? round($nw) : '');
$nh = ((round($nh) != 0) ? round($nh) : '');
```
If changed to the following, the error is gone and the thumbnails show - but not sure how appropriate it is as a fix:
```
$nw = ((round((int)($nw)) != 0) ? round((int)($nw)) : '');
$nh = ((round((int)($nh)) != 0) ? round((int)($nh)) : '');
```

### Expected behavior
Thumbnails should show.

### Environment
MODX 2.8.2 - PHP8.0

**Comment by wfoojjaec** [comment]
Another potential fix is here:
https://github.com/JamesHeinrich/phpThumb/issues/169
