### ISSUE TITLE
MODX News Feed and Security Feed Not Loading in PHP 8

### ISSUE THREAD

**Issue by opengeek** [modxcms/revolution#15712]
### Summary
When loading the manager dashboard, the MODX Security Feed and MODX News Feed are not loading in PHP 8.

### Step to reproduce
Load the manager dashboard in a PHP 8 environment.

### Observed behavior
Neither feed is loading.

### Expected behavior
The feeds should be loading.

### Related issue(s)/PR(s)
n/a

### Environment
MODX 2.8.3-dev-20210511, nginx 1.19.10, mariadb 10.5.9, Google Chrome 90.0.4430.93, on macOS 11.3.1

**Comment by wfoojjaec** [comment]
[MagpieRSS](https://sourceforge.net/projects/magpierss/files/) was last updated on 2005-11-05. Probably, this is a good time to switch.
