### ISSUE TITLE
MIGX 2.13.0-rc3 renderer:this.renderChunk error

### ISSUE THREAD

**Issue by geesmo** [modxcms/revolution#15713]
### Summary
After updating to MIGX 2.13.0-rc3 all MIGX TVs that had in the Grid Columns "renderer":"this.renderChunk" crached.
They show all the MIGX TV value as JSON on the grid column and when editing they do not show the values and save does not work.

### Step to reproduce
create a MIGX TV with a listbox-multiple TV type field and put some resources on the inputOptionValues: 

[
{"caption":"Console codes", "fields":[
{"field":"console","caption":"Console","inputTVtype":"listbox-multiple","inputOptionValues":"@EVAL return $modx->runSnippet('listMyResources_adv',array('parent' => 15));"}
]}
]

listMyResources_adv snippet returns "pagetile:id" options for every capable resource.

on the grid Columns use renderChunk:

[
{"header": "Console", "width": "160", "sortable": "true", "dataIndex": "console" , "renderer": "this.renderChunk"}
]

### Observed behavior
MIGX TV value shown as JSON on the grid column and when editing  the selected values are not shown and save does not work.

### Expected behavior
The grid column must show the resources pagetitles and editing and save must work.

### Workaround
remove the renderer from the grid Columns and everything is working.
the only problem is that on the table now you see the "pagetitle:id" as values and not only the "pagetitle". Its a little bit annoying when you develop a backend for your customer that needs a clear view. 

### Environment
MODX version 2.8.2, nginx 1.18.0.2-2.centos.7+p18.0.35.0+t210402.1610 , mysql 10.2.37-1.el7.centos

**Comment by opengeek** [comment]
I believe this needs to be directed to the MIGX project, not the MODX Revolution core.

**Comment by geesmo** [comment]
Issue moved to https://github.com/Bruno17/MIGX/issues/371
