### ISSUE TITLE
Error with decimal field in query with IN

### ISSUE THREAD

**Issue by touol** [modxcms/revolution#15724]
### Summary
When you make an IN query with a 'decimal' field, the fractional values are converted to integers. 

`
$modx->addPackage("gtsbalance",MODX_CORE_PATH."components/gtsbalance/model/");
$q = $modx->newQuery("gtsBTranslation");
$q->where([
    'sum:IN'=>['3848597.60'],
    ]);
$q->prepare();
echo $q->toSQL();
if($Translation = $modx->getObject("gtsBTranslation",$q)){
    echo "<pre>".print_r($Translation->toArray(),1)."</pre>";
}`
`WHERE `gtsBTranslation`.`sum` IN (3848597)`
Please add a 'decimal' field to this line.
https://github.com/modxcms/revolution/blob/218b7c34c6b7c9bdb8d3935debf35b34d2764335/core/xpdo/om/xpdoquery.class.php#L83

**Comment by opengeek** [comment]
There is no decimal PHP type in xPDO. You need to declare the field as a float PHP type in the model. Also, this is an issue for the xPDO library, not the Revolution CMS application.
