### ISSUE TITLE
Media Browser blank

### ISSUE THREAD

**Issue by Jorgenh** [modxcms/revolution#15723]
Modx 2.8.2 / tinyMCE 4.3.4 / tinyMCE RTE 2.0.1
Media browser shows up empty when inserting image in content. 
<img width="1269" alt="afbeelding" src="https://user-images.githubusercontent.com/2128284/119131399-b9521a80-ba39-11eb-818a-c536d1dac744.png">

**Comment by Ibochkarev** [comment]
@Jorgenh This fixed in https://github.com/modxcms/revolution/pull/15692

Please update MODX to 2.8.3 https://modx.s3.amazonaws.com/releases/nightlies/2.8.x/modx-2.8.3-dev-20210519.zip or change code https://github.com/modxcms/revolution/pull/15692/files
