### ISSUE TITLE
syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ']'

### ISSUE THREAD

**Issue by GaneshKandu** [modxcms/revolution#15727]
### Summary

Hi,

i am getting this issue in v2.8.3-pl when i visit Manage -> reports->system info

Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ']' in manager/controllers/default/system/info.class.php on line 48 

### Step to reproduce
Install v2.8.3-pl and visit ```Manage -> reports->system info```

### Observed behavior
Parse error: syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM), expecting ']' in manager/controllers/default/system/info.class.php on line 48 

### Environment
MODX version : v2.8.3-pl,
apache/nginx and version : Apache/2.2.34 (Unix),
 mysql version, browser, etc. Any relevant information. : Mysql 5.6.46,FireFox 88.0b9 (64-bit)
 
 ### Additional
 
 Changing line 48 of manager/controllers/default/system/info.class.php from this
 
```php

         if ($dbtype_sqlsrv && !empty($m['pdo_sqlsrv'])) $pi = array_merge($pi,array('pdo_sqlsrv' => $m['pdo_sqlsrv']));
        if (!empty($m['zip'])) $pi = array_merge($pi,array('zip' => $m['zip']));
        $mailerService = $this->modx->getService('mail', 'mail.modPHPMailer');
        $this->version = [
            'smarty'=> $this->modx->smarty->_version,
            'PHPMailer'=> $mailerService->mailer::VERSION
        ];

        $this->pi = array_merge($pi,$this->getPhpInfo(INFO_CONFIGURATION));
        return array(
            'pi' => $this->pi,
        );
    }

```
    
to this
    
```php
    
            if ($dbtype_sqlsrv && !empty($m['pdo_sqlsrv'])) $pi = array_merge($pi,array('pdo_sqlsrv' => $m['pdo_sqlsrv']));
        if (!empty($m['zip'])) $pi = array_merge($pi,array('zip' => $m['zip']));
        $mailerService = $this->modx->getService('mail', 'mail.modPHPMailer');
        $this->version = [
            'smarty'=> $this->modx->smarty->_version,
            'PHPMailer'=> $mailerService->mailer->VERSION
        ];

        $this->pi = array_merge($pi,$this->getPhpInfo(INFO_CONFIGURATION));
        return array(
            'pi' => $this->pi,
        );

    }
    
```
    
is working on php 5.6

```php
'PHPMailer'=> $mailerService->mailer->VERSION
```

**Comment by Mark-H** [comment]
I'd definitely encourage upgrading to a newer version of PHP. While 5.6 is formally supported in 2.8, using it in production really is a very bad idea. For MODX3, the minimum is already increased to at least 7.1. 

[This sure caught me by surprise though](https://3v4l.org/4Vj1N), the problem is trying to access a static constant on a class member which PHP5 doesn't understand. 

Rather than using a non-static accessor for a constant though, I'd propose the following fix:

```
        $mailerService = $this->modx->getService('mail', 'mail.modPHPMailer');
        $mailer = $mailerService->mailer;
        $this->version = [
            'smarty'=> $this->modx->smarty->_version,
            'PHPMailer'=> $mailer::VERSION
        ];
```

**Comment by GaneshKandu** [comment]
Thanks !
