### ISSUE TITLE
[Proposal] Remove "manager_direction" setting from manager panel

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15733]
### Summary
Many people don't guess, but in MODX you can change the direction of the text, through the `manager_direction` setting (`ltr` by default). However, changing the setting to `rtl` makes the manager area almost unusable.

**I think it's easier to remove it completely. It is unlikely that anyone often uses it, and it is unlikely that anyone will fix it.**

![manager_direction_rtl](https://user-images.githubusercontent.com/12523676/120633361-1e1a6580-c47b-11eb-93f3-4f1ca57289dc.gif)

### Step to reproduce
Change the `manager_direction` setting to "rtl".

### Environment
MODX 3.0.0-alpha3

**Comment by Mark-H** [comment]
I disagree with the proposal to remove it and would rather see the biggest issues with it fixed. Just briefly checked 2.x and that seems to work better than 3, although that also has some issues mostly with the tree and action buttons overlapping titles. 

Unfortunately usage of ltr/rtl is not a metric that's tracked in SiteDash so I don't have any data, but I think this is too important for some regions (even if it's not perfect) to remove entirely.

**Comment by Ruslan-Aleev** [comment]
I agree with you, but I don’t think this is **too important**. Otherwise, it would be relevant for other CMS, but we do not see it.

**Comment by alroniks** [comment]
I don't agree about removing RTL functionality, but I would remove it from the system settings and make it rely on language. List of RTL languages is known and limited, so it can be used for determining which text direction to use.

**Comment by Mark-H** [comment]
> I agree with you, but I don’t think this is too important. Otherwise, it would be relevant for other CMS, but we do not see it.

WordPress has it built in based on installed language (plus standardised support for front-end themes), and a very quick google shows Kirby,  Plone, Craft, Joomla, OctoberCMS and others also offer it either out of the box or with a plugin. Seems harder to find examples that don't offer any type of support for it ;) 

> I don't agree about removing RTL functionality, but I would remove it from the system settings and make it rely on language. List of RTL languages is known and limited, so it can be used for determining which text direction to use.

This proposal I would also support, especially now that language switching is done dynamically.

**Comment by Ruslan-Aleev** [comment]
> Seems harder to find examples that don't offer any type of support for it ;)

I was wrong. I was looking for exactly switching the direction of the text, but as it turned out, the direction of the text is connected with the selected language.

**Comment by JoshuaLuckers** [comment]
Since you're making the MODX manager work better in RTL mode I'm going to close this issue.
