### ISSUE TITLE
[Proposal] Change permission in system logs

### ISSUE THREAD

**Issue by catsmeatman** [modxcms/revolution#15739]
### Summary
System logs /manager/?a=system/logs is very useful thing. Now we have one permission 'logs' for two different action 'clear logs' and 'show logs'.

### Why is it needed?
To have more powerfull and flexible permission roles.

Example.
There are 5 editor in online store. 4 editor - is simple editor who can't show logs and 1 chief-editor who can show logs, but not truncate it.

### Suggested solutions
1. Add new permission 'clear_logs'
2. Permission 'logs' rename to 'show_logs'.
<img width="1341" alt="Screenshot 2021-06-17 at 12 59 03" src="https://user-images.githubusercontent.com/3153003/122378261-7b7bdf80-cf6e-11eb-890e-adbf0e6b5b27.png">

**Comment by Ibochkarev** [comment]
Update #15981
