### ISSUE TITLE
site_url placeholder coming back with wrong URL

### ISSUE THREAD

**Issue by 4rch1m3d35** [modxcms/revolution#15748]
The [[++site_url]] placeholder is returning with other URLs from our server.

After I cleared the cache the URL goes back to the current site.

But after an indeterminant amount of time, it will return to a different subdomain of the same URL from the other account on our server.

We have tried isolating the account like on a shared server but the issue keeps happening.

MODx version 2.8.3-pl

**Comment by garryn** [comment]
You can call the placeholder uncached to avoid that (notice the `!`):

```[[!++site_url]]```

**Comment by Mark-H** [comment]
What Garry said, but you'll probably also want to adjust your server configuration so it only accepts your defined host. Simplest way for that is a redirect in your .htaccess or nginx web rules that forces the expected domain.

**Comment by 4rch1m3d35** [comment]
@Mark-H could you refer me to the general syntax I would need to accomplish this in a .htaccess file?

**Comment by rthrash** [comment]
@4rch1m3d35 there should be an example `ht.access` file with your installation. Rename it to `.htaccess` and adjust its contents accordingly.
