### ISSUE TITLE
Inconsistency in title when copying an item in grids

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15745]
### Summary
When copying elements in a grid, the names of copies of elements in different grids are set differently:
- With or without the translated word "copy".
- With a different position of the word "copy" at the beginning / end of the title.

Media Sources
![sources](https://user-images.githubusercontent.com/12523676/123061691-ec167680-d41c-11eb-9a03-ad186e23b8f0.png)

Users
![users](https://user-images.githubusercontent.com/12523676/123061698-ed47a380-d41c-11eb-9d93-b9774378118e.png)

### Expected behavior
I think the word "copy" should be at the end so that the items are next to each other.
And the translation is not particularly needed, in my opinion.

### Environment
MODX 3.0.0-alpha3

**Comment by Ibochkarev** [comment]
Fixed in #15755
