### ISSUE TITLE
Extras won't update if case of package title has been changed

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15763]
### Summary
Trying to update and extra that has had the capitalization of the extra title changed doesn't work; the new version doesn't show up in the Extras Installer in the manager. 

### Step to reproduce
Try to update a package that has had its title changed. For example "GoodNews" was changed to "goodnews" in version 1.6.0-pl.

### Observed behavior
The new version shows up on the MODX Extras website page, but not when you go the to extras installer in your website. To update, I have to download the new version, upload to my server, and then look for packages locally in the Installer to find and install it.

### Expected behavior
The manager should recognize that a package is for the same Extra as before regardless of capitalization.

### Environment
All versions of MODX

**Comment by JoshuaLuckers** [comment]
When I look at the [listing page for GoodNews](https://modx.com/extras/package/?id=goodnews) The supported versions for the most recent release is set to `2.3 – 2.7`. I believe that's the reason why the update isn't showing up for you, unless you're running MODX 2.7.x.

**Comment by SnowCreative** [comment]
Oh, I hadn't thought of that! But, I have had this problem with other plugins, and the common factor seems to have been the change in capitalization, even for ones that did work with my current version of MODX. Sorry, but I can't remember what those plugins were.

**Comment by JoshuaLuckers** [comment]
I'm calling a helpline. Ping @Mark-H

**Comment by JoshuaLuckers** [comment]
The signature of the package is used, which is always in lowercase. I did some testing with calling the API manually and the change of name doesn't seem to cause any problems. In this case GoodNews doesn't support MODX 2.8 or later and therefore it doesn't show up as an update.
