### ISSUE TITLE
Using custom `locale` setting breaks file editor

### ISSUE THREAD

**Issue by BenceSzalai** [modxcms/revolution#15767]
### Summary
If the `locale` system setting is configured to a locale, that results in accented characters in the names of months, the file editor fails to load.

### Step to reproduce
1. Set the `locale` system setting to `hu_HU`.
2. Try to open a file in the editor under Files / Filesystem

### Observed behavior
The editor stays blank.

### Expected behavior
The editor should load.

### Environment
Happened on MODX Revolution 2.8.1-pl.

### Root cause analysis
Once the php locale setting is set, the `strftime` function may return accented characters. This function is used in `modFile::getLastAccessed()` and `modFile::getLastModified()`, which are both called from `modFileMediaSource::getObjectContents()`, which in turn fills the `SystemFileEditManagerController::$fileRecord` array. Once the array is filled with the accented characters, `SystemFileEditManagerController::loadCustomCssJs()` generates an invalid JSON, because the `record` part of the configuration for the `MODx.load` call remains empty. This breaks the JS in the manager and it stops with
```
Uncaught SyntaxError: expected expression, got ','
```
because of this JS containing a malformed JSON (note the `record` key is empty):
```html
<script type="text/javascript">
Ext.onReady(function() {
            MODx.load({
                xtype: "modx-page-file-edit"
                ,file: "examplefile.ext"
                ,record: 
                ,canSave: 1
            });
        });
</script>
```

### Naive fix
In my case the issue can be resolved by wrapping the `strftime()` calls in `mb_convert_encoding()` as the following:
```php
class modFile extends modFileSystemResource {
    //...
    public function getLastAccessed($timeFormat = '%b %d, %Y %I:%M:%S %p') {
        return mb_convert_encoding(strftime($timeFormat, fileatime($this->path)),'UTF-8', 'ISO-8859-1');
    }

    public function getLastModified($timeFormat = '%b %d, %Y %I:%M:%S %p') {
        return mb_convert_encoding(strftime($timeFormat, filemtime($this->path)),'UTF-8', 'ISO-8859-1');
    }
    //...
}
```
However I do not propose this as "THE" solution, because here I've hardcoded the 2nd parameter 'ISO-8859-1' according to my needs. But the point is that `getLastAccessed()` and `getLastModified()` should return a string in UTF-8 encoded format, otherwise the file editor won't load.

**Comment by Jako** [comment]
I am quite sure, that this can be solved by using a UTF8 capable locale, like `hu_HU.utf8`. The name of that locale depends a bit on your hosting system.

**Comment by BenceSzalai** [comment]
I've just tried as suggested, and it is working fine! Thank you! At least the issue would help others looking at the same problem! Consider the case closed.
