### ISSUE TITLE
S3 File and Folder Visibility

### ISSUE THREAD

**Issue by matdave** [modxcms/revolution#15762]
### Summary
The S3 file and folder visibility is showing as "private", which is preventing thumbnails in the media browser. When I try to change individual files to public I receive an unsuccessful response from the `Browser/Visibility` processor. 

### Step to reproduce
Add an S3 media source with the default visibility as public. Load that media source in the file browser. Inspect the response and see that all files are set to "private". Right click a file and try to change the visibility. 

### Observed behavior
Visibility is always returning "private"

### Expected behavior
The visibility should respect the default value from the source if it can't be determined correctly by the filesystem. 

### Related issue(s)/PR(s)
PR #15641

### Environment
MODX 3.0.0-alpha-3 on Cloud.

**Comment by Mark-H** [comment]
Related #15725 and #15757 (not sure if the latter fixes this already)

**Comment by matdave** [comment]
I tested this is the June 1 nightly build, and it is still present. Not sure if those were pushed into that or not.

**Comment by opengeek** [comment]
> I tested this is the June 1 nightly build, and it is still present. Not sure if those were pushed into that or not.

That would be impossible since the Flysystem v2 PR (#15757) was merged at the end of June.

**Comment by Mark-H** [comment]
There is a July 28th build available to try. ;)

**Comment by Ibochkarev** [comment]
@matdave Still relevant?

**Comment by matdave** [comment]
resolved
