### ISSUE TITLE
Fine-Tune PHPCS Config So PRs Without Errors Pass Code Quality Test

### ISSUE THREAD

**Issue by smg6511** [modxcms/revolution#15790]
### Summary
PHPCS is problematic in its current configuration, failing entire PRs with as little as one warning. A more defined configuration should be created.

### Why is it needed?
Maintainers are going to get a bad impression of or, at worst, ignore non-passing PRs when the "issues" the linter raises may be trivial.

### Suggested solution(s)
- At the very least, the config option _ignore_warnings_on_exit_ should be set to "1" so warnings are shown but do not fail the code quality test.
- Consider increasing the Generic.Files.LineLength limits. IMO the current 120 char limit is too short and can sometimes result in less readable code due to having to unnaturally break up a line.
- Need to address whether MODX will continue to camelCase class names, as it will require a custom rule and sniffer if so.

**Comment by smg6511** [comment]
Another consideration for the codeowners/maintainers: As I've tackled some issues and new features since the implementation of this linter I've noticed that, because there are a litany of changes necessary to pass (or at least attempt to pass) the code quality tests, spotting the actual _content_ changes to PR files can be quite the chore. Would it be better to drop enforcement of PSR-12 now and dedicate a time period (let's say a week or two) where normal PRs would be on hold and the entire php codebase could be brought up to speed PSR-12-wise. Perhaps you could recruit a group of contributors/maintainers/etc and assign specific areas each could update (I'd certainly be willing to be one).

**Comment by opengeek** [comment]
I agree. We need to disable it until it can be tackled at once as a final step before preparing for beta release. I want to see the changes being made and do not care about the formatting at this point.

**Comment by smg6511** [comment]
This most important problems have been solved here, so closing issue.
