### ISSUE TITLE
Classes not loading correctly using setPackage

### ISSUE THREAD

**Issue by sdrenth** [modxcms/revolution#15794]
### Summary
We've ran into a very specific issue when including MODX with custom objects in Laravel jobs, on other environments we can't reproduce this issue (not even in a Laravel command). In MODX itself it is working correctly. But after debugging for quite a while we're unable to figure out how this behaviour could occur and if there's a (neat) way around this.

What happens is that the custom table name can't be found when we use `addPackage`. When we use `setPackage` the custom tables can  be found, but for some reason core tables are no longer found.

For the custom models to work, the `_loadClass` method should be called where `$path` is the custom component path, but it is always called using the MODX core path unless we use setPackage. Somehow, it is not getting in this foreach loop in the `_loadClass` method:
```
foreach ($this->packages as $pkg => $pkgDef) {
    if ($pkg === $this->package) continue;
    $pqn= $pkg . '.' . $fqn;
    if ($pkgClass= $this->_loadClass($class, $pqn, $included, $pkgDef['path'], $transient)) {
        break;
    }
}
```

As a dirty fix, we've now gone for this solution:
```
$query = $this->modx->newQuery('modContextSetting');

$this->modx->setPackage('customPackage', 'path/to/package');
$query = $this->modx->newQuery('customPackageModel');

$this->modx->setPackage('core', 'path/to/core');
$query = $this->modx->newQuery('modContextSetting');
```

If someone has an idea what might be going on here and what we could try to fix this that would be great.

### Environment
Runs on Sterc Revolution, basically MODX 2.8 included in a Laravel Job

**Comment by Mark-H** [comment]
So you're loading MODX externally in a Laravel application, but addPackage doesn't register your model? Have you checked the return value to see if it finds it (bool), checked for messages in the MODX log? Doing anything Laravel specific with the model classes, or have it in an autoloader perhaps?

**Comment by sdrenth** [comment]
@Mark-H To be honest, I'm not a hundred procent sure where it is going wrong. But it looks like it has something todo with caching/memory. Because it's going wrong when the class exists:
```
$included= class_exists($class, false);
if ($included) {
    if ($transient || (!$transient && isset ($this->map[$class]))) {
        return $class;
    }
}
```

If `$included` is false, the objects are properly loaded but in the second job in Laravel the classes are already loaded, so $included returns true and the class is returned and because of this it never reaches this foreach part:
```
foreach ($this->packages as $pkg => $pkgDef) {
    if ($pkg === $this->package) continue;
    $pqn= $pkg . '.' . $fqn;
    if ($pkgClass= $this->_loadClass($class, $pqn, $included, $pkgDef['path'], $transient)) {
        break;
    }
}
```

The addPackage is working correctly, the `loadClass` method however does not.

I think we ran into a very specific issue with Laravel Jobs/Queues.

**Comment by sdrenth** [comment]
Seems we just found the solution, because the class was loaded multiple times. We'll provide with an update if we have more info on this.

**Comment by sdrenth** [comment]
Allright, the issue was the modx class was instantiated multiple times which was causing this specific issue. 

For anyone who might read this in the future, we now added this in the AppServiceProvider:
```
$this->app->singleton('modx', function ($app) {
    $modx = new ModxCMS();

    $modx->initialize();

    return $modx;
});
```

And in our job using this singleton:
```$modx = app('modx');```

**Comment by Mark-H** [comment]
Glad you figured it out :)
