### ISSUE TITLE
Add quality arg to imagewebp call in phpthumb.class.php

### ISSUE THREAD

**Issue by r3l0c** [modxcms/revolution#15811]
### Why is it needed?
imagewebp useless without quality arg

### Suggested solution(s)
imagewebp($this->gdimg_output,null, $this->thumbnailQuality);

**Comment by Ibochkarev** [comment]
@r3l0c This solution needs to be added to the repository https://github.com/JamesHeinrich/phpThumb as we use it as a library.

**Comment by r3l0c** [comment]
> @r3l0c This solution needs to be added to the repository https://github.com/JamesHeinrich/phpThumb as we use it as a library.

https://github.com/JamesHeinrich/phpThumb/issues/180#issuecomment-914488930

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to open a new issue. It would be really great if you could provide more details about your issue.

**Comment by JoshuaLuckers** [comment]
@r3l0c the author of phpThumb mentions it's already there, is there something missing in MODX that prevents you from using it?

**Comment by r3l0c** [comment]
@JoshuaLuckers check phpthumb.class.php

**Comment by Ibochkarev** [comment]
> @r3l0c the author of phpThumb mentions it's already there, is there something missing in MODX that prevents you from using it?

Since there hasn't been a phpthumb release for a long time.  that's why we don't have this solution.  You can also add updates before a new release is released.

**Comment by Jako** [comment]
There is a new version of phpThumb available: https://github.com/JamesHeinrich/phpThumb/commit/1ef2db62e8d4a4e391159653b200144a37462de3

In MODX 2.x we have to add that updated class manually.
