### ISSUE TITLE
Cache not clearing with use of getFeed

### ISSUE THREAD

**Issue by sewphl** [modxcms/revolution#15828]
Cache does not appear to be clearing with use of getFeed (Modx Revolution 2.8.3-pl). Though the RSS feed is updating at the URL used in the 'url' parameter, web content has not updated accordingly with use of Snippet call as shown below. Replacing URL with a different URL does not always update web content after saving. Is there a specific format that the URL must follow for the cache to clear? Are query strings allowed in the URL as in the example below? Is https (vs. http, as used in documentation) acceptable? Please let me know if additional info is needed. Created [issue](https://github.com/splittingred/getFeed/issues/20) in [getFeed](https://github.com/splittingred/getFeed) as well, and can close it in either repo as needed.

[[!getFeed? &url=`https://path.com/to/my/events/event/?feed=feed` &tpl=`RSSFeedParser`]]

**Comment by Mark-H** [comment]
Issues about extras belong in their own repo until proven otherwise. :)
