### ISSUE TITLE
Improve input formatting options for number TVs

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#15838]
### Summary
Some more options for how numbers can be entered and displayed would be very useful, for example when using number fields to enter prices.

### Why is it needed?
You can turn on “Allow Decimals” and set the Decimal Precision to “2”, but if you then type in a number like “12.00”, the zeros and period get stripped and it changes to just “12”. And “12.20” gets changed to “12.2”. That’s not so great when a field is meant to contain prices. 

### Suggested solution(s)
Adding a setting to force the number of decimal places to be displayed would make numbers like prices consistent.
Also, a setting to right-align numbers inside the field would be useful, for example when you use a MIGX grid to list a table of prices in columns.

**Comment by smg6511** [comment]
I've been doing a lot of work on the UI for TV creation and will take a look at this. Probably the best solution would be to create a new output option output type that would allow the specification of various currency formats.

**Comment by SnowCreative** [comment]
More output options would be great, but that won't affect the input fields, which is where this would be most beneficial. Output can already be managed through scripting.

**Comment by smg6511** [comment]
Yes, I see what you mean. I was more focused on the web page output end of it rather than the appearance within the manager. I agree it'd be distracting to see currency values without their full decimal places shown. I just submitted a PR that would satisfy your feature request.

**Comment by SnowCreative** [comment]
Thanks, the PR works great!

**Comment by smg6511** [comment]
Issue fixed in 2.x and 3.x
