### ISSUE TITLE
PR #15822 Breaks Template Variables

### ISSUE THREAD

**Issue by smg6511** [modxcms/revolution#15844]
### Summary
The new template preview feature introduced in PR #15822 mistakenly adds the _preview_file_ field to _modTemplateVar_ and removes it from _modTemplate_. 

### Step to reproduce
This PR is only a few hours old, so you'll need to test this against a build of the most recent commit for 3.0.0-alpha3.

### Observed behavior
Try to create a new TV and try to save a preview image in a template. You'll find that neither operation succeeds.

### Related issue(s)/PR(s)
PR #15822.

**Comment by opengeek** [comment]
I'm confused. #15822 simply removed a field. It does not add one.

**Comment by opengeek** [comment]
It looks to me like someone did not add those fields to the correct place in the schema file and did not make those changes to the platform class by running the parse-schema script. We should not be manually changing the platform files without running parse-schema afterward. This is why the whitespace changes from IDE settings were saved to the platform class in that PR, which had to correct by running parse-schema. By doing this, it exposed the problem with this field being improperly defined in the schema from somewhere else. This has nothing to do with #15822—it is just a coincidence that it was exposed by the merge process on that PR.
