### ISSUE TITLE
Unused processor: Security/User/Group/GetList

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#15858]
### Summary

core/src/Revolution/Processors/Security/User/Group/GetList.php does appear to be in use. I noticed because PHPStorm's code analysis flagged the duplicate array keys as a potential bug: https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/Processors/Security/User/Group/GetList.php#L48-L51

I then tried to find where it was used to confirm the issue, but couldn't find any reference to this processor.

The user edit screen fetches user groups in the security/user/get processor. 

### Step to reproduce

Try to find the processor being used. Either fail, or prove me wrong. 

### Observed behavior

Dead code found.

### Expected behavior

Dead code should be nuked from orbit.

### Related issue(s)/PR(s)
N/a

### Environment
MODX3 alpha3

**Comment by JoshuaLuckers** [comment]
I can't find any usage of this processor in the core either.

**Comment by Ibochkarev** [comment]
Fixed  #15910
