### ISSUE TITLE
The welcome_screen_url setting is not updated after upgrading from 2.8.x to modx 3 alpha 3

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15879]
### Summary
The welcome_screen_url setting is not updated after upgrading from 2.8.x to modx 3 alpha 3

### Step to reproduce
Upgrade from version 2.8.x to modx 3 alpha 3

### Observed behavior
![изображение](https://user-images.githubusercontent.com/2138260/139526589-413c0366-8334-49e5-b87d-2884ef372680.png)

### Expected behavior
The correct welcome window should be displayed

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/pull/15613/files#diff-83f8ed169ce446e127f046bdff9f46b5aa0d57f0979560afa2ce8c1a43df29f7R10

### Environment
MODX 3 aplha

**Comment by JoshuaLuckers** [comment]
We probably should modify the upgrade script to check for `//misc.modx.com/revolution/welcome.27.html` and `//misc.modx.com/revolution/welcome.28.html`.

**Comment by Ibochkarev** [comment]
> We probably should modify the upgrade script to check for `//misc.modx.com/revolution/welcome.27.html` and `//misc.modx.com/revolution/welcome.28.html`.

and 2.6

**Comment by opengeek** [comment]
The welcome screen should not show on upgrades. Why is this an issue?

**Comment by JoshuaLuckers** [comment]
I don't think it's an issue per se, it's just for consistency I guess.

**Comment by rthrash** [comment]
Since the welcome screen will not currently show after an upgrade, perhaps we should consider a new feature to show it on the first login after an upgrade. It might make sense to consider doing this only for certain roles, or only for minor and major versions instead of patch releases. 

As such, I'll move this to the 3.1 milestone as it be a new feature and b/c semver.

**Comment by JoshuaLuckers** [comment]
@rthrash maybe differentiate a new install from an upgrade. A fresh install should show the current "Welcome" content but when upgrading a "What's new" would make more sense.

p.s: the title of the page http://misc.modx.com/revolution/welcome.30.html says "Thanks for Installing MODX Revolution 2.8".

**Comment by rthrash** [comment]
@JoshuaLuckers that missing 3.0 typo was fixed a while ago … thanks for pointing that out!

I'm going to close this out as there would be a lot to figure out a what's new given that it could come from a much older version, etc. Definitely would be a good idea, but not in the context of this report.
