### ISSUE TITLE
There is no description / title for the static_resources section system setup 

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15878]
### Summary
There is no description for static_resources section 

### Step to reproduce
Open the Settings section, static_resources section

### Observed behavior
![изображение](https://user-images.githubusercontent.com/2138260/139526499-3469b78f-8281-4bec-9c45-0a612e291658.png)

### Expected behavior
There must be a description and title

### Related issue(s)/PR(s)
NA

### Environment
MODX 3 alpha

**Comment by JoshuaLuckers** [comment]
~I don't see those settings in my setup. Is this a clean install of 3.x?~

See: https://github.com/modxcms/revolution/issues/15877#issuecomment-955666916

**Comment by smg6511** [comment]
This was already fixed at some point ... the specified setting names and descriptions show fine in 3.0.3.
