### ISSUE TITLE
3.0.0-BETA1 displays as available

### ISSUE THREAD

**Issue by PeterBinc** [modxcms/revolution#15873]
### Summary
3.0.0-BETA1 displays as available in Updates on MODXcloud 3.0.0-alpha3 dashboard

### Step to reproduce
Updated the latest prerelease MODXcloud with alpha3

### Observed behavior
3.0.0-BETA1 displays as available in Updates on MODXcloud 3.0.0-alpha3 dashboard

### Expected behavior
It should display as UP TO DATE

### Related issue(s)/PR(s)
N/A

### Environment
MODXcloud
<img width="523" alt="3 0 0alpha3" src="https://user-images.githubusercontent.com/80120223/139288028-6a852a29-da02-42b6-9595-68eb7a1d3ca5.png">

**Comment by opengeek** [comment]
This has nothing to do with the CMS product. You have some extra installed that does updates and it is wrong.

**Comment by Ruslan-Aleev** [comment]
> This has nothing to do with the CMS product. You have some extra installed that does updates and it is wrong.

No, this is in the core of MODX 3, in widgets, not a extra.

**Comment by opengeek** [comment]
Wow. Ok. I had no idea that was there. But it is not showing the above for me in my local install.

**Comment by PeterBinc** [comment]
I created 2 new MODXclouds 3.0.0-alpha1, one in DE, the other in TX.
Both display the BETA1 as available.

Peter Bockenthien
720-999-4169

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/15483

**Comment by opengeek** [comment]
> Related with #15483

Alright. Closing this as a duplicate.
