### ISSUE TITLE
 Zend OPcache API is restricted during upgrade 2.8 - 3.0beta1

### ISSUE THREAD

**Issue by eydolan** [modxcms/revolution#15897]
### Summary
When trying to upgrade 2.8.3 to 3.0.0 beta1 itt gives me OPcache API error

### Step to reproduce
copy all new files over old ones, 
run setup
get 
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /usr/www/users/XXX/setup/includes/modinstallsettings.class.php on line 97 
Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /usr/www/users/XXX/setup/includes/modinstallsettings.class.php on line 97 
Warning: Cannot modify header information - headers already sent by (output started at /usr/www/users/XXX/setup/includes/modinstallsettings.class.php:97) in /usr/www/users/powerycwff/setup/includes/request/modinstallrequest.class.php on line 232 

cache was manually deleted before upgrade attempt

### Observed behavior
error and can not carry on install

### Expected behavior
should complete install

### Related issue(s)/PR(s)
n/a

### Environment
apache 
php 7.4 and 8.0
mariaDB

**Comment by garryn** [comment]
What's your setting for `opcache.restrict_api` in your `php.ini` (or, to check, use phpinfo)?

**Comment by eydolan** [comment]
its
opcache.restrict_api | /var/www/default | /var/www/default

**Comment by garryn** [comment]
Ok, after a bit of research .. sounds like we need an additional check in `modinstallsettings.class.php` at line 97 where the  `opcache_invalidate` function is checked to also check the validity of the `opcache.restrict_api` value.

**Comment by eydolan** [comment]
I dont recall this error happening on alpha release

I stand corrected same thing happens on alpha 3

**Comment by opengeek** [comment]
> Ok, after a bit of research .. sounds like we need an additional check in `modinstallsettings.class.php` at line 97 where the `opcache_invalidate` function is checked to also check the validity of the `opcache.restrict_api` value.

What do you mean by check the validity? If the PHP configuration is invalid, why is that something the software needs to detect here?

**Comment by Mark-H** [comment]
I think by checking validity Garry probably means checking if the filename is in the path [allowed to run the opcache commands](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.restrict-api). Kinda like open basedir checking?

**Comment by opengeek** [comment]
> I think by checking validity Garry probably means checking if the filename is in the path [allowed to run the opcache commands](https://www.php.net/manual/en/opcache.configuration.php#ini.opcache.restrict-api). Kinda like open basedir checking?

If that is the case, why should MODX be checking if you misconfigured your OPCache configuration? That's what I'm asking.

**Comment by Mark-H** [comment]
Is it _mis_configured, though? I'm not super familiar with opcache but I don't see why `/var/www/default` is an invalid path to put in that option. Even if that's not where the site is located causing the warning; that path might serve up a custom page to clear the opcache.

**Comment by opengeek** [comment]
> Is it _mis_configured, though? I'm not super familiar with opcache but I don't see why `/var/www/default` is an invalid path to put in that option. Even if that's not where the site is located causing the warning; that path might serve up a custom page to clear the opcache.

If it is a valid path, then why is it an issue? I am so confused.

**Comment by opengeek** [comment]
And by valid, I mean a path that includes where setup is running. We could try to detect if it is within the path, but that could potentially return false failures. It just seems like an odd corner case to be trying to handle automatically, but I'll let others decide.

**Comment by eydolan** [comment]
I am also not sure but I been using same php settings on modx 2 and no issues it installs fine, hence I posted this because I did not come across this before why 3 is giving an error.

**Comment by eydolan** [comment]
modx 3 alpha 1 works fine

**Comment by eydolan** [comment]
Some feedback from server admin: 
_opcache.restrict_api value is set to /var/www/default as a default server configuration.

This is done to increase security on the servers (this is the hosting company)

We would suggest using the workaround to suppress the exception by adding a “@” to your code where you work around the restricted_api. Usually, this error specifies the exact file on a specific line, where you would add the “@” in front of the code._

So all they are suggesting is just to suppress the error message not sure if that is ideal....

This is all they said. I am sure other hosting companies will have a similar setup.

**Comment by garryn** [comment]
Suppressing the error is not ideal. Checking the path in `opcache.restrict_api` prior to calling `opcache_invalidate()` is better.

**Comment by opengeek** [comment]
I'm confused. Is `/var/www/default` the path containing the MODX installation (including `setup/`)?

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx3-compatibility-of-popular-extras-bug-hunt-edition/3738/39

**Comment by JoshuaLuckers** [comment]
> Suppressing the error is not ideal. Checking the path in `opcache.restrict_api` prior to calling `opcache_invalidate()` is better.

I agree, we should check if the file calling `opcache_invalidate()` is allowed to do so by checking it against `opcache.restrict_api`. 
Currently we check if the `opcache_invalidate` function exists but this doesn't mean we are allowed to use it.

**Comment by JoshuaLuckers** [comment]
> I'm confused. Is `/var/www/default` the path containing the MODX installation (including `setup/`)?

I don't think that's the path containing the MODX installation. In the error log we see this path: `/usr/www/users/XXX/setup/`.

**Comment by JoshuaLuckers** [comment]
@phantomphondler do you see an opportunity to test PR #15911 ?

**Comment by eydolan** [comment]
Sure I will test tonight

**Comment by eydolan** [comment]
@JoshuaLuckers 

worked on web install :) have not tested in CLI setup but on web it works on php 7.4 and 8

if (stripos(__FILE__, ini_get('opcache.restrict_api')) !== false) {if (stripos(__FILE__, ini_get('opcache.restrict_api')) !== false) 
did the trick

tested using  MODX Revolution 3.0.0-rc1  cloned from github

worked using upgrade and fresh install

**Comment by eydolan** [comment]
I guess this can be closed?

**Comment by JoshuaLuckers** [comment]
@phantomphondler we will close the issue once the fix is merged. Thanks for testing.

**Comment by eydolan** [comment]
@JoshuaLuckers  hey joshua was it merged as I just tried to do another test using MODX Revolution 3.0.0-rc1 getting same error again? cloned from git

Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /usr/www/users/XXX/setup/includes/modinstallsettings.class.php on line 97 Warning: Zend OPcache API is restricted by "restrict_api" configuration directive in /usr/www/users/XXX/setup/includes/modinstallsettings.class.php on line 97

php 8.0.14

so 
this is the issue if I ignore the below line 96-98 it works

I can get it to work again if I do
      if (function_exists('opcache_invalidate')) {
          if (stripos(__FILE__, ini_get('opcache.restrict_api')) !== false) {
              opcache_invalidate($this->fileName);
          }
      }
line 97 the one you took out

unless I cloned the wrong version?

**Comment by JoshuaLuckers** [comment]
@phantomphondler the PR isn't merged yet. We will
Close this issue when we merge the PR.

**Comment by Ibochkarev** [comment]
Fixed #15911
