### ISSUE TITLE
Don't list page types the user does not have permission to create

### ISSUE THREAD

**Issue by Mark-H** [modxcms/revolution#15893]
### Summary

After #15888 is applied, the new create resource modal with template preview still lists page types the user does not have permission to create. 

### Step to reproduce

Apply #15888 or wait until that's been merged.

Restrict access to create a certain type of resource, eg static resource or weblink, with the permissions. 

Click the create resource button and try to create the restricted type.

### Observed behavior

Selecting the type is allowed (but it still fails server side).

### Expected behavior

Disallowed types should not be offered to the user.

### Related issue(s)/PR(s)

#15888 

### Environment
Any

**Comment by JoshuaLuckers** [comment]
FYI: PR #15888 has been merged.
