### ISSUE TITLE
[3.x] NaN dates in dashboard feeds

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#15908]
### Summary
Dates in dashboard feeds are showing as: 0NaN-NaN-NaN

![Screenshot 2021-11-19 at 17-55-52 Dashboard MODX Revolution](https://user-images.githubusercontent.com/5160368/142603525-f8fde718-bb18-4259-9a62-56a7f32d74a0.png)

### Step to reproduce
Look at the feeds on the dashboard

### Observed behavior
Dates are not showing correctly

### Expected behavior
Dates should be showing correctly.

### Related issue(s)/PR(s)
Unaware of any.

**Comment by JoshuaLuckers** [comment]
I'm unable to reproduce this.

**Comment by JoshuaLuckers** [comment]
@muzzwood does it help if you clear the cache folder?

**Comment by muzzwood** [comment]
@JoshuaLuckers Hmmm... that's odd! But thanks for testing it.
Clearing/deleting the cache makes no difference. Tested on both Chrome and Firefox.
I can see the dates come through correctly in the feed XHR request too.

I haven't looked into the code yet though.

Is anyone else able to replicate this?

**Comment by Ruslan-Aleev** [comment]
I don't have such a problem, the dates in the widgets are shown normally.

Here are the widget files:
https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/Processors/System/Dashboard/Widget/Feed.php#L83
https://github.com/modxcms/revolution/blob/3.x/manager/templates/default/dashboard/rssitem.tpl#L4

p.s. Maybe you haven't updated SimplePie in composer?

**Comment by JoshuaLuckers** [comment]
@muzzwood is this a clean install of 3.x? What version did you install?

**Comment by muzzwood** [comment]
@JoshuaLuckers It was a 3.x branch pull from git. I'll look into the cause asap.

**Comment by muzzwood** [comment]
It's this line causing the issue:
https://github.com/modxcms/revolution/blob/3.x/manager/assets/modext/widgets/modx.panel.welcome.js#L94

Before that the dates are correct. The `Ext.select` call outputs `0NaN-NaN-NaN` instead of the date.
An example date being: `<div class="date_stamp">Tuesday, September 11, 2018 AM06:45:54</div>`

Interestingly, if this line:
https://github.com/modxcms/revolution/blob/3.x/core/src/Revolution/Processors/System/Dashboard/Widget/Feed.php#L83
is changed to `get_date`, it works fine. So I'm guessing this has got to be a locale issue.

**Comment by Jako** [comment]
Then the date has to be retrieved with `get_date` and the locale transformation has to run in the browser afterwards.

**Comment by Ibochkarev** [comment]
Fixed #15980
