### ISSUE TITLE
PHP8 Fatal error when using Snippet Widget in Dashboard

### ISSUE THREAD

**Issue by Peeet93** [modxcms/revolution#15918]
### Summary
If you use "Inline-PHP-Widget" then create_function is called in core/model/modx/moddashboardwidget.class.php on line 321.

### Step to reproduce
Create Widget. Use "inline-php-widget". Use widget in dashboard. Go to dashboard. See the error.

### Environment
Modx 2.8.3

**Comment by JoshuaLuckers** [comment]
[create_function](https://www.php.net/manual/en/function.create-function.php) has been DEPRECATED as of PHP 7.2.0, and REMOVED as of PHP 8.0.0. Relying on this function is highly discouraged.

**Comment by JoshuaLuckers** [comment]
Suggestion from @Mark-H on how to fix this:

> Write to an include file like snippets, or deprecate and remove

**Comment by matdave** [comment]
Just a bump on this. Still an issue a year later.

**Comment by matdave** [comment]
Created a PR that runs script treating it as a psuedo snippet.

**Comment by smg6511** [comment]
This appears to have been addressed with the above referenced PR #16290.
