### ISSUE TITLE
How to work with extension packages?

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15914]
## A question for understanding
We have some kind of mess with extension packages. The documentation contains examples using system settings. But in the code we see the following 
![zoomx local – modx class](https://user-images.githubusercontent.com/4679725/142973980-2a7d91cf-c85a-4970-8187-f09022e43c77.jpg)

What is the correct way?
`$modx->addExtensionPackage(...)` or `$modx->newObject('modExtensionPackage')`?

**Comment by JoshuaLuckers** [comment]
I would recommend using `modExtensionPackage`. This would work with MODX 2.x and 3.x.

However [MODX 3 introduces a Dependency Injection Container](https://docs.modx.com/3.x/en/extending-modx/di-container). This removes the need to register an extension package and you can [inject a service](https://docs.modx.com/3.x/en/extending-modx/di-container#injecting-services) a lot easier.
Example: https://github.com/modxcms/revolution/pull/14920#issuecomment-567685397

**Comment by sergant210** [comment]
Then the system-setting based extension packages should be deleted in MODX3 as promised.

**Comment by smg6511** [comment]
Closing as system-setting based extension packages has been removed in 3.x and use of the DI Container will be the favored method moving forward.

**Comment by BobRay** [comment]
Is there documentation somewhere on how to use `modExtensionPackage`?  I successfully saved a `modExtensionPackage` object.  `$modx->initialize()` calls _loadExtensionPackages(), but that doesn't appear to load, or even retrieve packages in the `modx_extension_packages` table. It uses this code to get them, but the result is empty, though the table is not:
```
$cache = $this->call(modExtensionPackage::class, 'loadCache', [&$this]);
```

I'm instantiating and initializing MODX in cli mode, so I can step through the code in the XDebug if that matters.
