### ISSUE TITLE
Specific text in a modX_content breaks the web manager

### ISSUE THREAD

**Issue by vrdriver** [modxcms/revolution#15920]
### Summary
I have text in 'Content' of my user editable content (modx_site_content->content field) that are making pages fail to load in the manager.
This is not by deliberate malicious actions, but has been found by accident. 

### Step to reproduce
Over time, I think I've moved this modx website from a different server, and I can only guess, that migrating it, that there have been different db "Default collation"s as well. (I don't know what it has been in the past, but this is only a guess as to the cause.)

Either way, I have the following text in some of my pages/modx_site_content->content field:

`?Ç¬†<`

If you insert this above text in to a content field, it will break your page and you won't be able to load it, or quick update it in the modx manager.

Please note, that the pages do not just contain this above text, it's just what I've found is break the page. It's usually scattered amongst other HTML content.

As seen in this screen shot: 

![Screen Shot 2021-11-29 at 00 33 33](https://user-images.githubusercontent.com/5615487/143770079-f75c5dd3-813c-47fd-9305-b384472994c4.png)

You can see multiple times it's listed in this document.

![Screen Shot 2021-11-29 at 00 36 49](https://user-images.githubusercontent.com/5615487/143770403-041c9844-7776-4eec-b1fc-3dfbb0e9f258.png)

### Observed behavior
Once I removed the offend text, the page ounce again loaded, as shown in the screen shot.

![Screen Shot 2021-11-29 at 00 40 33](https://user-images.githubusercontent.com/5615487/143770378-8ef44fa0-bde0-42db-9985-86d33a996692.png)

Sometimes it commonly appears as the following:

`<p>?Ç¬†</p>`

In the Web Console, it also gives this result if that offending text is present.

![Screen Shot 2021-11-29 at 00 21 18](https://user-images.githubusercontent.com/5615487/143769654-c444a4c8-a740-4fdd-907b-e887bba9a49d.png)

Removing the content from the actual DB solves the problem.

### Expected behavior
It should just show that text, regardless.

### Environment
MODX Revolution 2.8.3-pl
SharedHost: A2 Hosting
PHP 7.4
Server: MariaDB Server
Version: 10.2.26-MariaDB-cll-lve
Tables/DB:
Default collation: latin1_swedish_ci
Default characterset: latin1

**Comment by Jako** [comment]
I am quite sure that this issue is caused by a non UTF8 database charset. The decoding process of UTF8 chars in the database is creating invalid chars in the JSON used by the MODX manager during loading the page code. If you change the database/tables/columns to an UTF8 charset, the issue should go away.

**Comment by JoshuaLuckers** [comment]
@vrdriver please let us know if changing collation and characterset solves your issue.

**Comment by vrdriver** [comment]
Thanks @Jako and @JoshuaLuckers. I'm suspecting this is the problem...
I will add the offending code back in, change the charset see if that solves it. 
If it does solve it, I wonder if it's worth making an alert/message under the 'Configuration Check' on the dashboard suggesting that "We have detected that your current database charset could cause compatibility problems. Please change it to X"?

**Comment by vrdriver** [comment]
Hi all, I have some good news.
I tried the suggestions, and it worked.

Instead now, I get the following:

`<p>???</p>`

Which is much better than an admin page failing to load.

To keep things simple, I used Bob's modified conversion script.
[](https://bobsguides.com/convert-db-utf8.html) https://github.com/BobRay/ConvertDatabaseCharset

After fixing an error where an sql comment wasn't escaped correctly it worked. (I'm sure you can see the problem).

```
ALTER TABLE polls_templates MODIFY `pt_colour_text_09` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT 'The default is 8 colours, however I've added 4 others for easy expansion in the future, and have left the original';
```

I also left the line in the config.inc.php alone too in the end:
`$database_connection_charset = 'latin1';`

I did try changing it to `'utf8_general_ci'`, however the site failed to load, so I kept it as `'latin1'`.
