### ISSUE TITLE
Logout all users action doesn't work with custom session handlers

### ISSUE THREAD

**Issue by sergant210** [modxcms/revolution#15928]
### Summary
If you have specified your own session handlers, you will not be able to flush all user sessions.

### Step to reproduce
1. Create a new session handler which extends the modSessionHandler class.
2. Specify it in the system setting "session_handler_class".
3. Try to logout all users in the admin panel (Manage/Logout all users).

### Observed behavior
![flush_sessions](https://user-images.githubusercontent.com/4679725/144698268-8f356a99-2bdd-4e29-802c-ce84971a45a4.png)

There are 2 problems
1. Corresponding lexicon topic is not loaded.
2. Sessions are not deleted.

The problem is in the very strange [check](https://github.com/modxcms/revolution/blob/1014ed8b4ed8a53f6fa46dda97bde31913e2fe9d/core/model/modx/processors/security/flush.class.php#L24). So we have got a system setting for extending the handler class, but we cannot change it.

### Environment
MODX 2.x, MODX 3 Beta 2.

**Comment by Ibochkarev** [comment]
Related https://github.com/modxcms/revolution/issues/15510
