### ISSUE TITLE
JS Error in MODx.combo.ComboBox if processor response takes too long

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#15924]
### Summary
This occurs when a MODExt combo box is set to `mode: remote`.
If a processor is slow to respond, the console shows this error:
```
Uncaught TypeError: this.pageTb is undefined
```
It references this line: 
https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/core/modx.combo.js#L114

### Step to reproduce
Add `sleep(3)` to your processor to replicate the issue.

### Observed behavior
The user will see the first row from the processor response in the combo but nothing else.

### Expected behavior
There should not be an error if the response is slow.

### Related issue(s)/PR(s)
n/a

### Environment
MODX 2.8.3 - I've yet to test it with 3.x but will do so tonight/tomorrow.

**Comment by muzzwood** [comment]
I've confirmed the same issue is present in 3.x

**Comment by Ibochkarev** [comment]
Fixed #15926
