### ISSUE TITLE
[3.0.0-beta2] Some %tags% not evaluated properly while installing

### ISSUE THREAD

**Issue by b-ced** [modxcms/revolution#15938]
### Summary
Some tags not evaluated properly while installing

![2021-12-12 11_32_02-MODX Revolution 3 0 0-beta2 » Installer](https://user-images.githubusercontent.com/74956171/145709198-a29f4e37-53fe-480b-bb51-5bb31fd7478d.png)

### Environment
MODX Revolution 3.0.0-beta2, Apache/PHP8 (French version)

**Comment by JoshuaLuckers** [comment]
@opengeek the `password_err_short` lexicon in some languages use `%length%` instead of `[[+length]]`. Can we change this directly in the source or do we need to change this through Crowdin?

**Comment by Mark-H** [comment]
Changes to English go via GitHub, the translations via CrowdIn.

**Comment by JoshuaLuckers** [comment]
@jaygilmore is this something you can fix in CrowdIn?

**Comment by opengeek** [comment]
@JoshuaLuckers — any translator can fix the translations.

**Comment by opengeek** [comment]
@JoshuaLuckers — I also upgraded you to manager so you can fix them 😂 don't hate!

**Comment by JoshuaLuckers** [comment]
The lexicons have been updated and they have been merged into 3.x. 

Thanks for taking time to report this issue!
