### ISSUE TITLE
[3.x] Resource tree does not show any resources

### ISSUE THREAD

**Issue by yannthomassen** [modxcms/revolution#15940]
### Summary
The resource tree won't show the contents of the (web) context properly. 

After updating to MODX 3.0.0-beta2 the resource items won't be listed properly under the "Resources" tab. The only visible item is the web context, which doesn't seem to budge after editing or refreshing it. Duplicating the context introduces the same context item which **does** show the resources properly.

This seems to happen sporadically across the websites that we are updating. We only observe this problem in some of them, it's not apparent what sets these sites apart.

The error log does not seem to report this problem.

### Step to reproduce
Update a website to MODX 3.0.0-beta2 via the UpgradeModX extra. 

### Observed behavior
No resources are listed under the "Resources" tab. Only the web context is visible. Refreshing or editing it does not seem to help introduce the missing resources, duplicating the context does (resources are listed in the newly created context).

### Expected behavior
After updating it should list the resources by default.

### Environment
MODX 3.0.0-beta2, PHP Version 7.3.16

**Comment by shamarin** [comment]
Do you have Ticket extra installed? I have the same issue, but the problem is in unsupported Ticket extra installed on my MODX 3 which is not currently supported by MODX 3

**Comment by jenswittmann** [comment]
Hello @YannThomassen ,
i've got the same issue the last days. Are you using the collections extra? If so, deinstall it and install the lastest alpha of collections (because a resolver script). Then ist should work.

**Comment by yannthomassen** [comment]
Hey Anton and Jens,

Thanks for the suggestions. We do not use Ticket, but we do use the Collections extra. After a little investigation by @beko1997 we deduced that the latter is causing issues here. A new issue has been made in the appropriate repository and I'll close this issue.

Thanks for your help!
