### ISSUE TITLE
MODX dies after installing HybridAuth package

### ISSUE THREAD

**Issue by guidenwagen** [modxcms/revolution#15943]
### Summary
MODX died after installing the HybridAuth package. At least none of the interface elements worked.

### Step to reproduce
When installing the HybridAuth package via modx or modxpro, the installation console hangs. Then, after reloading the page, the following "Undefined array key" modUser "in E: \ OpenServer \ domains \ guidenwagen \ core \ vendor \ xpdo \ xpdo \ src \ xPDO \ xPDOMap.php on line 44" will pop up.

### Observed behavior
All interface elements stop working. This error is present on all pages of the manager.

### Expected behavior
The package should just install

### Environment
Nginix_1.21
PHP_8.0
MySQL-5.7

### Correction
switch to PHP_7.4

**Comment by opengeek** [comment]
Thanks for taking the time to report the problems you are having. Unfortunately, this needs to be reported to the author of HybridAuth, not here. That said, I am unsure where one would do that.

**Comment by biz87** [comment]
> Thanks for taking the time to report the problems you are having. Unfortunately, this needs to be reported to the author of HybridAuth, not here. That said, I am unsure where one would do that.

The author has already seen 

Our repository is https://github.com/modx-pro/modx-hybridauth

**Comment by Ibochkarev** [comment]
@guidenwagen https://github.com/modx-pro/modx-hybridauth/issues/45

**Comment by guidenwagen** [comment]
> @guidenwagen [modx-pro/modx-hybridauth#45](https://github.com/modx-pro/modx-hybridauth/issues/45)

thnx
