### ISSUE TITLE
[MODX3] subsubnav position issue

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#15969]
### Summary
The subsubmenu is placed quite invisible in the menus on the top left:

![Bildschirmfoto 2022-01-14 um 13 11 14](https://user-images.githubusercontent.com/148371/149513871-1954a6ff-d2e6-4e75-b457-138c7fad7452.png)

Since it has `position: absolute; bottom: 0;` most of the entries are invisible.

The position has to be calculated or set different with , since the language submenu in the usermenu has to get `bottom: 0`. 

### Step to reproduce
Create some nested submenu entries i.e. in the extras menu.

### Observed behavior
The top ones are hidden.

### Expected behavior
The top ones should be visible.

### Related issue(s)/PR(s)
None known. The position is set that way since the first MODX3 release.

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.

**Comment by Ibochkarev** [comment]
Fixed #15970
