### ISSUE TITLE
MODX does not allow you to create/open an empty file

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15976]
### Summary
MODX does not allow you to create/open an empty file, even if the file is not created through the CMS.

### Step to reproduce
Try to create an empty txt file and save it.

![emptyFile](https://user-images.githubusercontent.com/12523676/150174182-d8bd2edf-31ff-4d0f-84bf-dd0f96ad17ec.png)

If you create an empty file on the server, then MODX will display the file in the tree, but will not allow you to open it.

### Environment
MODX 3.0.0-rc1

**Comment by Mark-H** [comment]
Fixed for rc1

**Comment by Mark-H** [comment]
While it's possible to create now, I somehow overlooked the tree not allowing it to be clicked: https://github.com/modxcms/revolution/pull/15977#issuecomment-1018613790 🤔
