### ISSUE TITLE
Error selecting parent resource in quick resource creation window

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#15983]
### Summary
Error selecting a parent resource in the quick resource creation window if you are editing the that resource you want to select as a parent quick resource creation window.

### Step to reproduce
1) Create a resource (for example, "Category 1") that will be the parent of the new resource.
2) Go inside edit resource "Category 1".
3) Create a new resource (for example, "Child 1") through the quick resource creation window and in the Settings tab, select "Category 1" as the parent.
4) The error "The resource cannot be its own parent."
The quick window sees the new resource "Child 1" as editable "Category 1", which is not correct.
Perhaps this problem is relevant for other fields of the resource.

### Observed behavior

![qew_parent](https://user-images.githubusercontent.com/12523676/150531087-d4bad316-2eed-4f0e-a67e-d00b46696eeb.gif)

### Expected behavior
There shouldn't be any error.

### Environment
MODX 3.0.0-rc1

**Comment by Ibochkarev** [comment]
fixed #16002
