### ISSUE TITLE
[3.0.0-rc1] container flag is set seemingly randomly after dragdrop in resource tree

### ISSUE THREAD

**Issue by halftrainedharry** [modxcms/revolution#15991]
### Summary
When moving around resources in the resource tree, the container flag (`isfolder` column) is set on seemingly random resources.

### Step to reproduce
![container_bug](https://user-images.githubusercontent.com/85392304/150691975-1ca03926-e911-4d19-920b-67b72cba9938.gif)

Take 3 resources. Drag resource 3 into resource 2. Refresh. Drag resource 3 out of resource 2 above resource 1. Refresh. 

### Observed behavior
Resource 1 is now a container.

### Expected behavior
The container flag of resource 1 remains the same.

### Environment
MODX 3.0.0-rc1

**Comment by halftrainedharry** [comment]
![isfolder](https://user-images.githubusercontent.com/85392304/150700045-128041f5-1313-469c-835b-7e19cd47318c.gif)

Most of the time when you drag downwards, the resource above the drop position is set to a container. When you drag upwards, the resource below the drop position. (It's not completely reliable though.)

**Comment by JoshuaLuckers** [comment]
@halftrainedharry thanks for taking time to report this issue. I have submitted a PR to address this issue.

**Comment by halftrainedharry** [comment]
@JoshuaLuckers Thank you for fixing the issue.

**Comment by Ibochkarev** [comment]
Fixed #16001
