### ISSUE TITLE
Improve form validation

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#16009]
### Summary
1) In the TV form, in case of a validation error, make the tab active, on which the error appeared. This is relevant for the tab "Input Options".
For resource and tab with TV it works now.

2) Move the window to the element with the error.

3) Make active sub-tabs of TV categories that have an element with invalid validation - https://github.com/modxcms/revolution/issues/11112

### Related issue(s)/PR(s)
NA

**Comment by smg6511** [comment]
@Ruslan-Aleev - These issues are already addressed in my PR #15887 (which is a port to 3.x of changes already merged into the 2.x branch) ... I just need people to review it and get it merged.

**Comment by Ruslan-Aleev** [comment]
@smg6511 It would be great if you divided the PR https://github.com/modxcms/revolution/pull/15887 into several smaller ones. Even scrolling through changes in files is hard, not to mention testing them :) You have in one PR and lexicons are corrected, and UX, and regular expressions, etc. - it's too much, I think.

**Comment by smg6511** [comment]
Closing, as I believe these issues had been resolved by the set of replacement PRs for #15887 which merged on 4/4/2022.
