### ISSUE TITLE
MODX 3.0.0-rc1 install, now getting filemtime() errors

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#16005]
### Summary
I upgraded my MODX 3 test site to the new release candidate. I have snippets set up as static files. Running these scripts now fails and pages don't finish loading.

### Step to reproduce
Install rc1. No idea what else might be involved here

### Observed behavior
The error log fills up with statements like this for each snippet:
Unable to retrieve the last_modified for file at location: [path to static files]/windowTitle.php. filemtime(): stat failed for  [path to static files]/windowTitle.php

Opening and resaving the snippets, either through the static file itself or through the Manager, has no effect.

### Environment
MODX 3.0.0-rc1, PHP 7.3, MySQL 5.7.36-cll-lve

**Comment by JoshuaLuckers** [comment]
Can you share the full error/warning that's being logged? Including the path (you can randomize the directory names). 

Does it also happen for new static elements you create?

**Comment by SnowCreative** [comment]
I see one thing that's happening. I have the static file paths set using the Filesystem media source. Somehow, the MODX base path is getting prepended twice, as in the following: 

[2022-01-30 09:59:50] (ERROR @ [PATH TO CORE]/src/Revolution/Sources/modMediaSource.php : 562) Unable to retrieve the last_modified for file at location: **/home/blahblah/rootdir**/code/windowTitle.php. filemtime(): stat failed for **/home/blahblah/rootdir/home/blahblah/rootdir**/code/windowTitle.php

The "file at location" path is correct, but the "stat failed for" path has the double prefix. I've tried changing the Filesystem path settings (basePath and baseUrl) to a forward slash instead of being blank, and that doesn't change anything. File and folder permissions are correct, and the MODX_BASE_PATH and MODX_BASE_URL are set correctly in the config file.

Additionally, when I try to set up a media source specifically for static files, I can't save any static resources using that media source. In fact, MODX won't let me save a snippet using a different media source at all; the file name field is outlined in red and it won't save, even though I've selected the file through the Media manager at its new source. The same error as above shows up, with the double prefix for the "stat failed" path.

Similarly, I can't create new static snippets at all; they won't save.

**Comment by SnowCreative** [comment]
UPDATE: The main problem seems to be that MODX won't let me edit PHP files. The static files have to have the php extension so that I can edit them locally in my IDE. If I add "php" to the "upload_files" system setting, then all the errors go away. But shouldn't there be a separate setting for uploading files versus editing static files?

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to share the additional info, it seems to be related to issue #15927.

**Comment by JoshuaLuckers** [comment]
I guess something goes wrong in `getSourceFile`: https://github.com/modxcms/revolution/blob/565537a1d7d13d49dc8ad18965479022f9d42760/core/src/Revolution/modElement.php#L567

**Comment by JoshuaLuckers** [comment]
A PR addressing this issue is merged and therefore I'm closing this issue.
