### ISSUE TITLE
Finish changing the background for the login

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#16014]
### Summary
1) Add pictures for the seasons for the login form

There is a code in the login that changes the background form depending on the season.
See https://github.com/modxcms/revolution/blob/3.x/manager/controllers/default/security/login.class.php#L85

Don't know why this was done, but if this code is already there, then we just need to add pictures and it will work.
It also makes sense to change backgrounds for major versions of MODX, so that you can tell which version of MODX now from the background (as in Mac OS, for example).

2) Add a setting to set your own backgrounds (both by default and seasonal).

As an option, set the path to the folder with backgrounds.

### Why is it needed?
To add beauty :)

**Comment by Mark-H** [comment]
Back when this was first built, I also made an extra that gives a different image every day via unsplash. I'm hoping to release that in the next week or two so that's available with the pl.

**Comment by JoshuaLuckers** [comment]
It's funny how the seasons are determined because what season it is also depends on where in the world you are located.

**Comment by Mark-H** [comment]
Great point! :) I wonder if that code should just be taken out. 

Also the extra I talked about the other day with the random daily images is now available. [Announcement](https://modmore.com/blog/2022/new-dailyphoto-for-modx-3/), [and in extras](https://modx.com/extras/package/dailyphoto). 

[The code to override the background is really simple, by the way](https://github.com/modmore/DailyPhoto/blob/master/core/components/daily_photo/elements/plugins/daily_photo.plugin.php#L66) in case people want to create their own plugins. Or just change the `login_background_image` system setting a few times a year. ;)

**Comment by Ibochkarev** [comment]
Fixed #16020
