### ISSUE TITLE
There is no port in the URL during installation

### ISSUE THREAD

**Issue by jbl3010** [modxcms/revolution#16015]
I use port HTTPS 88 as the port. After the installation process and installation, the URL does not carry the port number. As a result, I need to manually add':88'to the address bar to install and use it.

Resolvent

----

After installation, at core/config/config. Inc.php, change line 75 to:

$site_ Url=$url_ Scheme. $ Http_ Host.':'. $_ SERVER['SERVER_PORT']. MODX_ BASE_ URL;

Now I can use it normally.

----
From Machine Translation

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/pull/15622

**Comment by opengeek** [comment]
> Related with #15622

This has nothing to do with the database connection string.

**Comment by Ruslan-Aleev** [comment]
Yes, my bad, I confused the port for the database (https://github.com/modxcms/revolution/pull/15622#discussion_r733910682) with the port of the server.
Although we can fix it in one PR (if necessary), because refers to one file `core/config.inc.php`. Or delete the comments if I'm wrong.

**Comment by JoshuaLuckers** [comment]
@jbl3010 if you run setup, does it keep the port or do you have to manually add it there as well?

**Comment by jbl3010** [comment]
> @jbl3010 if you run setup, does it keep the port or do you have to manually add it there as well?

My address is https://xxxxxx:88

In the next step of setting, the ": 88" of the URL will disappear. Every time next, I have to add ": 88" manually

If you use non-standard ports (other than 80 and 443)

This phenomenon can be reproduced

**Comment by smg6511** [comment]
Yes, this is very annoying behavior, especially for those operating dev environments on non-standard ports. The issue on the front end is how the config makes its assumptions, and then strips out the port in most cases on L66-L68:
```
if ($_SERVER['SERVER_PORT'] != 80) {
    $http_host= str_replace(':' . $_SERVER['SERVER_PORT'], '', $http_host); // remove port from HTTP_HOST
}
$http_host .= ($_SERVER['SERVER_PORT'] == 80 || $isSecureRequest) ? '' : ':' . $_SERVER['SERVER_PORT'];
```

A similar issue is present in the setup's bootstrap file (setup/provisioner/bootstrap.php), L22-L25:
```
if (isset($_SERVER['SERVER_PORT']) && (string)$_SERVER['SERVER_PORT'] !== '' && $_SERVER['SERVER_PORT'] !== 80) {
    $installBaseUrl = str_replace(':' . $_SERVER['SERVER_PORT'], '', $installBaseUrl);
}
$installBaseUrl .= ($_SERVER['SERVER_PORT'] === 80 || ($https !== false || strtolower($https) === 'on')) ? '' : ':' . $_SERVER['SERVER_PORT'];
```

I've wondered for quite a while why it's done this way. Why not just check for the presence of the two standard ports and strip them out of the URL if present? Further, why even do that?

**Comment by opengeek** [comment]
It only strips out non-standard ports. I'm not understanding the problem.

**Comment by opengeek** [comment]
I thought this was designed to only strip out the port if it was a standard port, i.e. 80 or 443. It seems like the logic is reversed.

**Comment by opengeek** [comment]
Ok, no, it is not reversed. This first strips any port from HTTP_HOST and then adds the SERVER_PORT back to it if it is a non-standard port. This is exactly as intended, so I am failing to see the problem here. Is the problem perhaps that your server configuration is not setting the SERVER_PORT variable appropriately?

**Comment by smg6511** [comment]
No, it's not reversed. The problem is that it strips out the port if it's a secure one no matter what. What I'm wondering though is what is the functional purpose of stripping the port anyway?

**Comment by opengeek** [comment]
> No, it's not reversed. The problem is that it strips out the port if it's a secure one no matter what. What I'm wondering though is what is the functional purpose of strippig the port anyway?

Because you don't want the port if it is the standard port, which is how all production sites would want their URLs. You wouldn't want `http://foo.bar:80/home` or `https://foo.bar:443/home`…

**Comment by opengeek** [comment]
> The problem is that it strips out the port if it's a secure one no matter what.

It seems to me then that the only problem is it is not checking specifically for 443 on secure requests?

**Comment by opengeek** [comment]
It seems like there was a reason this was done for secure requests and that the `https_port` variable was provided in the config, but I am honestly not that knowledgeable about web server configuration with regards to SSL and I never use them when developing locally.

**Comment by smg6511** [comment]
> Because you don't want the port if it is the standard port, which is how all production sites would want their URLs. You wouldn't want `http://foo.bar:80/home` or `https://foo.bar:443/home`

The thing is the port will only be in the URL if it is typed in by the end user (if we leave it alone in our code).

**Comment by opengeek** [comment]
> > Because you don't want the port if it is the standard port, which is how all production sites would want their URLs. You wouldn't want `http://foo.bar:80/home` or `https://foo.bar:443/home`
> 
> The thing is the port will only be in the URL if it is typed in by the end user (if we leave it alone in our code).

No, it won't. This is how the site_url is constructed on every request and it would be appended for standard ports if this code was not there.

**Comment by smg6511** [comment]
That's _because_ the code in the config messes with it, right? The way I read it, the only thing reliant on assessing the secure status of the server connection is the protocol used in the `site_url` (http vs https) when it is built.

**Comment by opengeek** [comment]
> That's _because_ the code in the config messes with it, right? The way I read it, the only thing reliant on assessing the secure status of the server connection is the protocol used in the `site_url` (http vs https) when it is built.

I really do not understand what the problem is other than this needing to append the port if it is not the standard https_port for your server. That will take a slight adjustment to make it work.

**Comment by opengeek** [comment]
Also, this issue about installation, not the config.
