### ISSUE TITLE
[3.0.0-rc1] Error changing a resource template

### ISSUE THREAD

**Issue by smanu85** [modxcms/revolution#16010]
### Summary
Changing a template when editing a resource results in an error when the resource automatically reload to apply selected template.
The only way to change the resource template is to quick edit and save from the resource tree.

### Step to reproduce
Load a resource in the manager and try to switch template, even the empty one.

### Observed behavior
![modx3-rc1_tpl_error](https://user-images.githubusercontent.com/1263032/151463053-abb0b567-db57-4829-9b65-ca5ec2381ee7.png)
"Error: Class 'DocumentUpdateManagerController' not found
Errors:
 ResourceManagerController::getInstance(object, string "DocumentUpdateManagerController", Array ( [namespace] => core [namespace_path] => /paas/c0065/www/manager/ [action] => resource/update [controller] => resource/update ) )
 MODX\Revolution\modManagerResponse->outputContent(Array ( ) )
 MODX\Revolution\modManagerRequest->prepareResponse()
 MODX\Revolution\modManagerRequest->handleRequest()"

### Expected behavior
The page should reaload with the selected template.

### Environment
Tested on 2 environments:
- MODX Cloud install (c0065.paas2.ams.modxcloud.com)
- Local install using Laragon on a Windows 10 pc

**Comment by ghost** [comment]
I'll second that. Not sure when I last set or changed a template without error, but it was definitely one of the betas.

MODX Cloud
Revo 3.0.0 rc-1 updated via Cloud dashboard, not a new install

**Comment by ghost** [comment]
Definitely no problem with beta-2.

**Comment by muzzwood** [comment]
This may have been fixed here: https://github.com/modxcms/revolution/pull/15997

**Comment by smanu85** [comment]
> This may have been fixed here: #15997

Yes, I can confirm that this commit fix the problem. Thanks!

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx-3-0-0-error-class-document-update-manager-controller-not-found/4914/2
