### ISSUE TITLE
Error updating table for class MODX, when upgrading to MODX 3.0.0-rc2

### ISSUE THREAD

**Issue by h-futuris** [modxcms/revolution#16035]
### Summary
When upgrading to MODX 3.0.0-rc2, the system issues errors (see below).
At the same time, everything is updated and the site is working. 

### Step to reproduce
Updating MODX from version 3.0.0-rc1 to 3.0.0-rc2.

### Observed behavior
`Error updating table for class MODX\Revolution\modResource
Array
(
[0] => 42000
[1] => 1091
[2] => Can't DROP COLUMN `contentType`; check that it exists
)

Error updating table for class MODX\Revolution\modContentType
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'icon'
)

Error updating table for class modTemplate
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'preview_file'
)

Error updating table for class MODX\Revolution\modDashboard
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'customizable'
)

Error updating table for class MODX\Revolution\modDashboardWidget
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'permission'
)

Error updating table for class MODX\Revolution\modDashboardWidget
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'properties'
)

Error updating table for class MODX\Revolution\modDashboardWidgetPlacement
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'user'
)

Error updating table for class MODX\Revolution\modDashboardWidgetPlacement
Array
(
[0] => 42S21
[1] => 1060
[2] => Duplicate column name 'size'
)`

### Environment
MODX 3.0.0-rc2, PHP 7.3.33.
![modx-3rc2-errors](https://user-images.githubusercontent.com/98578060/152522506-3c880035-a2e8-4471-95a8-3ecc81dfb43a.png)

**Comment by Mark-H** [comment]
Those are safe to ignore; it just means the fields were already dropped/added. 

As you upgraded from rc1 to rc2 and these sorts of migrations were already done with the installation of rc1, but as the setup runs them based on the number only (so 3.0.0) you get these warnings when updating between pre-releases.

Thanks for reporting though, if you encounter other issues be sure to let us know.

**Comment by h-futuris** [comment]
Thanks.  I've got it.
