### ISSUE TITLE
Can't Rename Attributes Containers

### ISSUE THREAD

**Issue by GarretOverstreet** [modxcms/revolution#16032]
### Summary
While you can rename the Attributes Container in both user extended fields (going back to MODX 2.8.3) or dashboard widgets in MODX 3, the change doesn't save.

### Step to reproduce
Create attribute container and save.  Then try to rename it and save again.

### Observed behavior
After saving and reloading, the name reverts to its original name.

### Expected behavior
It should have the new name.

### Environment
MODX 2.8+ - MODX 3.0.0-rc2

**Comment by halftrainedharry** [comment]
It seems that when you **set a new container name**, the code sets the new name as the _id_ and as the _text_

https://github.com/modxcms/revolution/blob/28f1b46d4d4984c84dff7f4a5770b81ebe2be00e/manager/assets/modext/widgets/core/modx.orm.js#L181-L182

but when it reads the data to save it, it uses the _name_ attribute (that wasn't changed).

https://github.com/modxcms/revolution/blob/28f1b46d4d4984c84dff7f4a5770b81ebe2be00e/manager/assets/modext/widgets/core/modx.orm.js#L235-L237

So in the _renameContainer_ function, the name attribute probably has to be set as well:
```
nd.attributes.name = r.name;
```
----

The same problem exists, when you try to **change the name of an attribute**.
In the _saveProperty_ function, it sets the _text_ attribute, but not the _name_.

https://github.com/modxcms/revolution/blob/28f1b46d4d4984c84dff7f4a5770b81ebe2be00e/manager/assets/modext/widgets/core/modx.orm.js#L319
