### ISSUE TITLE
Install failure on fresh VPS (rc2)

### ISSUE THREAD

**Issue by mkovnick** [modxcms/revolution#16040]
### Summary
Installing on v3 RC2 a fresh VPS, while going through the fresh install wizard, I am getting the following error :
Page: 
`/setup/?action=database`

Screenshot:
[https://www.culturediscovery.com/files/modx_rc2_error.jpg](https://www.culturediscovery.com/files/modx_rc2_error.jpg)

### Step to reproduce
Went through the installation wizard, using all defaults.  Double checked that DB was created, user is correct, has full permissions, and double-checked db password.

### Environment
Ubuntu 20.04 LTS
MODX version: 3.0 RC2
Apache: 2.4.41,
MySQL:  8.0.28-0ubuntu0.20.04.3
PHP: 8.1.2 (using PHP-FPM)
Browser: Tried Brave, Chrome, Firefox, Apache

**Comment by mkovnick** [comment]
Update to this issue:
I switched to PHP7.4, and was able to install.  After install I re-enabled PHP 8.1 and all seems well.

**Comment by Jako** [comment]
I don't think that MODX3 is completely tested for 8.1 at the moment.

Can you specify the PHP error that occurred?

**Comment by opengeek** [comment]
This is a deprecation warning from an xPDO issue and is already fixed but not yet released and so it did not make it into RC2. Turn off deprecated warnings in error_reporting and/or disable display_errors and it will still work fine in 8.1.

**Comment by opengeek** [comment]
See https://github.com/modxcms/xpdo/pull/221

**Comment by mkovnick** [comment]
Just to be clear, I was aware of the depreciation error, and saw it on other pages in the setup, but none of those were blocking errors.  This one was.

**Comment by JoshuaLuckers** [comment]
@mkovnick the database password is still visible in your screenshot. 

The deprecation warning is blocking the redirect to the summary, if you turn off deprecation warnings the error will disappear and not block the setup. The issue that's causing the deprecation warning is fixed and will be part of the next release.

Thanks for taking time to report this issue and help MODX better.

**Comment by mkovnick** [comment]
Thanks.  As for the DB password, no worries. It is a test server, and that changes constantly :-)

**Comment by JoshuaLuckers** [comment]
This issue should be solved in the latest nightly. If it's still an issue please feel free to re-open this issue.
