### ISSUE TITLE
Unable to save edited content changes

### ISSUE THREAD

**Issue by Tetiana1986** [modxcms/revolution#16055]
### Summary
Unable to save edited content changes

### Step to reproduce
Navigate to http://bestdiplom.com.ua/manager/
![screen](https://user-images.githubusercontent.com/99543679/153714744-b65fe39b-1fb9-4624-8f5c-3f615e98aaa0.jpg)
Edit any content
Press "Save"

### Observed behavior
A pop-up window stating "Error. Access denied" is displayed, and in Chrome DevTools I observe 301 status code for PUT http method (Moved permanently), see screen in attachment

### Expected behavior
Edited content changes saved successfully.

### Related issue(s)/PR(s)
Let us know if this is related to any issue/pull request.

### Environment
MODX Revolution 2.2.11-pl (traditional), Google Chrome browser

**Comment by rthrash** [comment]
That version is very, very out of date. It's likely your host upgraded PHP and it's no longer compatible. Upgrade to the latest 2.8.x and also all your Extras to the latest version and let us know how it goes.

**Comment by Tetiana1986** [comment]
Can you, please, tell me how to make upgrade? Thanks

**Comment by rthrash** [comment]
Upgrade instructions are found in the documentation.  Based on the age of your install, I'd suggest upgrading to 2.3.6 first, then going to the latest version. Make sure you have a backup. Instructions here: https://docs.modx.com/current/en/getting-started/maintenance/upgrading

**Comment by Tetiana1986** [comment]
Thanks for instruction. I still have questions because I am not quite aware of how to do all this right and avoid loss of data (not a developer). Please, help me - how can I do this (see screen)?
![Снимок экрана 2022-02-12 165658](https://user-images.githubusercontent.com/99543679/153716363-c4842054-ad70-45ff-87a3-d420eed25411.jpg)
Also I can not make backup in ModX - when I press "Install", I see an empty pop-up window and nothing happens when I press OK or just close it.

**Comment by Tetiana1986** [comment]
Also I can't clear site's cache, an error occurs (see screen)
![3](https://user-images.githubusercontent.com/99543679/153717014-2b9a989e-3d49-42a8-8908-cde5f9988a94.jpg)
![4](https://user-images.githubusercontent.com/99543679/153717019-e8403676-a24a-4422-9007-4b8235336b16.jpg)

**Comment by Ruslan-Aleev** [comment]
@Tetiana1986, write to the telegram chat https://t.me/ru_modx, or to the forum https://modx.pro/all, you will find help there.
github for a different type of questions.

**Comment by Mark-H** [comment]
You may want to rebuild the site from clean files instead of upgrading, as there is a very high chance it has been hacked by now. There have been several cricial vulnerabilities fixed over the years.
