### ISSUE TITLE
Strange error message when trying to save a file

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#16074]
### Summary
When editing a file (css, js, possibly other files) and trying to save it, a window pops up with the message:

![error_message](https://user-images.githubusercontent.com/12523676/155228288-5803fdfc-ae85-4ac6-83ff-1406d22e1bb6.png)

Perhaps the matter is in the rights to the folders (installed component folder), then it is worth changing the text of the message to a more understandable one.

There was a clean install of MODX 3 via the installer.
The message appears in the 3rd branch, while there are no messages for the 2nd branch.

At the same time, if you upload a file to the same folder, then the uploaded file is saved, and their icons differ in the tree.

![icon_info](https://user-images.githubusercontent.com/12523676/155229501-fbc7b03d-bf20-4e2b-b9e4-29b896bbf743.png)

### Environment
MODX 3.0.0-rc-2

**Comment by JoshuaLuckers** [comment]
Is still still an issue?

**Comment by smg6511** [comment]
This isn't a bug, rather it's a request for better feedback when a file cannot be written to. This ambiguous message _does_ show when a user lacks the permissions (on the file system) to write to a file.
