### ISSUE TITLE
MODX 3.0 — Configuration Check widget no longer goes away

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#16109]
### Summary
In 2.8 and before, the Configuration Check widget was automatically hidden if there were no configuration errors.

### Observed behavior
In the 3.0 dashboard, Configuration Check appears even if there are no errors.

### Expected behavior
Why did this change? It's much better for this widget to be hidden if there are no problems so that it doesn't clutter up the dashboard.

### Environment
MODX 3.0.0.

**Comment by JoshuaLuckers** [comment]
I can confirm this as well. Clicking the X to remove the widget works as expected.
