### ISSUE TITLE
Setup Error Message Typo

### ISSUE THREAD

**Issue by mrcycling** [modxcms/revolution#16111]
### Summary
Error message generated during setup has typo

### Observed behavior
The MODX generated setup error message has a mis-spelling:

`MODX Setup cannot continue.  
MODX requires the PHP fileinfo extension.  
You're PHP configuration at version 8.0.16 does not appear to have this extension enabled.`

### Expected behavior
Last sentence should start **Your** (as it is possessive) not _You're_ (contraction for you are).

I tried to find the string in the lexicon, but could not.

### Environment
MODX version 3.0.0-pl, English language install

**Comment by Ibochkarev** [comment]
Fixed #16112
