### ISSUE TITLE
MODX 3.0.0 Wrong charset in body of HTML email

### ISSUE THREAD

**Issue by halftrainedharry** [modxcms/revolution#16116]
### Summary
When sending an email from MODX3, umlauts in the body do not display properly.

### Step to reproduce
Sending an html-email with umlauts.

```
$modx->getService('mail', 'mail.modPHPMailer');
$modx->mail->set(modMail::MAIL_BODY, 'Some text with umlauts ä, ü, ö, etc.');
$modx->mail->set(modMail::MAIL_FROM, $modx->getOption('emailsender'));
$modx->mail->set(modMail::MAIL_FROM_NAME, $modx->getOption('site_name'));
$modx->mail->set(modMail::MAIL_SENDER, $modx->getOption('emailsender'));
$modx->mail->set(modMail::MAIL_SUBJECT, 'Test');
$modx->mail->address('to', 'whatever@somedomain.com');
$modx->mail->setHTML(true);
if (!$modx->mail->send()) {
    $modx->log(modX::LOG_LEVEL_ERROR, 'Could not send mail.');
}
$modx->mail->reset();
```

### Observed behavior
The umlauts in the mail are converted to `Ã¤, Ã¼, Ã¶`.
The problem seems to happen in the class _InlineStyle_. I think DOMDocument::loadHTML assumes ISO-8859-1 if the charset can't be inferred from the mail body.

### Environment
MODX 3.0.0

### Related thread in the forum
https://community.modx.com/t/characters-in-email-body-messed-up/5145

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/characters-in-email-body-messed-up/5145/10

**Comment by Ibochkarev** [comment]
@halftrainedharry Did you have this problem in 2.x?

**Comment by halftrainedharry** [comment]
@Ibochkarev No. The problem happens here in the class _InlineStyle_. As far as I can tell this class wasn't used in MODX 2.x.

https://github.com/modxcms/revolution/blob/e72d984811d00aed1cf707c74788c8b3a3236ad6/core/src/Revolution/Mail/modPHPMailer.php#L227-L230

**Comment by Jako** [comment]
According to https://github.com/christiaan/InlineStyle/issues/27, charset issues are caused by a wrong detected charset in DOMDocument. Maybe an iconv or mb_convert_encoding can solve this in line 227. But please check the content of $this->mailer->Body before, if there is some mixed charset content inside.

**Comment by halftrainedharry** [comment]
I tried the solution with `mb_convert_encoding($this->mailer->Body, "ISO-8859-1", "UTF-8")`, but that doesn't seem to work because of this line:

https://github.com/christiaan/InlineStyle/blob/9c408760465f4e3ef2b5fb08cb6995e3233afa98/InlineStyle/InlineStyle.php#L79-L81

-----

The output is correct though, if I add a meta tag with the charset to the mail body:
```php
$modx->mail->set(modMail::MAIL_BODY, '<!doctype html><html><head><meta charset="UTF-8"></head><body>Some text with umlauts ä, ü, ö, etc.</body></html>');
//output = <!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>Some text with umlauts &auml;, uuml;, &ouml;, etc.</body></html>
```
Maybe the solution is to add this meta tag automatically, if it doesn't exist (or not using _InlineStyle_ at all).

**Comment by Mark-H** [comment]
InlineStyle is needed to make the new nicely formatted emails (eg login links, password resets) render properly, but yeah this is definitely something we'll need to figure out a fix for. Just ran into it testing Commerce on 3.0 as well, euro signs turning into gibberish... unfortunately that already had the meta tag in its templates 🤔

**Comment by Mark-H** [comment]
Potential fix that seems to work, [replacing this code block](https://github.com/modxcms/revolution/blob/e72d984811d00aed1cf707c74788c8b3a3236ad6/core/src/Revolution/Mail/modPHPMailer.php#L227-L230) with the following:

``` php
            if (strpos($this->mailer->ContentType, 'html') !== false) {
                if (!empty($this->mailer->Body)) {
                    $body = $this->mailer->Body;
                    // Turn UTF-8 characters into entities
                    $body = mb_convert_encoding($body, 'HTML-ENTITIES', "UTF-8");
                    $html = new InlineStyle($body);
                    /** @noinspection PhpParamsInspection */
                    $html->applyStylesheet($html->extractStylesheets());
                    $this->mailer->Body = $html->getHTML();
                }
            }
```

Will send a PR, but this is something that would require some testing especially from non-latin languages.

**Comment by halftrainedharry** [comment]
> InlineStyle is needed to make the new nicely formatted emails (eg login links, password resets) render properly

Would it be possible to make the conversion optional?
Like you had to set something like `$modx->mail->convertStyles(true);` explicitly in the code, to run the conversion with _InlineStyle_.

You wouldn't have to worry about other extras like _FormIt_, if _InlineStyle_ didn't run for every html-email by default (with no possibility to turn it off).

**Comment by Mark-H** [comment]
That... would've been a great idea to hear before 3.0 hit stable ;) I'd probably prefer this to be enabled by default as it's generally a good thing to do when sending emails and not having to update FormIt to use it is a nice improvement, but it does make sense to allow it to be disabled. Maybe for 3.1?
