### ISSUE TITLE
Edit snippet is shown twice in context-menu

### ISSUE THREAD

**Issue by Esger** [modxcms/revolution#16129]
### Summary
In the context-menu for snippets the translation in Dutch for 'duplicate snippet' is the same as 'edit snippet'

### Step to reproduce
Right-click on a snippet to show the context-menu

### Observed behavior
Translation for 'duplicate snippet' is the same as 'edit snippet' in Dutch and some other translations are still in English.

### Expected behavior
It should say 'snippet dupliceren'

### Environment
MODX version 3.0 - modx-cloud
<img width="429" alt="Schermafbeelding 2022-04-07 om 12 07 27" src="https://user-images.githubusercontent.com/70047/162176852-4e72922b-5308-46fd-a373-8df06d713d00.png">

**Comment by halftrainedharry** [comment]
Maybe you can change it and add new translations yourself via [Crowdin](https://crowdin.com/project/modx-revolution).

https://docs.modx.com/3.x/en/contribute/translate

(The wrong translation should be in the file `default.inc.php`)

**Comment by smg6511** [comment]
@Mark-H @JoshuaLuckers - Guys, can this be done directly in the MODX repo by chance, since @Esger gave us what the correct translation should be?

**Comment by Mark-H** [comment]
No, because as far as I know, CrowdIn is currently configured as a one-way integration when it comes to translations.
