### ISSUE TITLE
Unable to specify new password for users

### ISSUE THREAD

**Issue by Qowyn** [modxcms/revolution#16124]
### Summary
Unable to specify new password for users, modx sends the password confirmation as specifiedpassword.
Generated html observed in Firefox and Edge:
![grafik](https://user-images.githubusercontent.com/1871591/162008830-b49d588d-c358-4e4b-9792-5269124719a1.png)
modx.panel.user.js sent by server:
![grafik](https://user-images.githubusercontent.com/1871591/162009264-ab596796-fbbc-469f-99e6-74c2d7bc5179.png)

Manually changing the name of the second input from specifiedpassword to confirmpassword makes it possible to create a user with specified password.

### Step to reproduce
Install new MODX 3.0.0-pl.
Try to create a user and specify a password.

### Observed behavior
Submitting the user creation fails without error message.

### Expected behavior
User should be created with the specified password.

### Environment
MODX 3.0.0-pl, PHP 8.0.17, Database 10.5.15-MariaDB, fresh installation

**Comment by smg6511** [comment]
I can confirm this happening in the pl release. It was not occurring in the rc2 release.

**Comment by smg6511** [comment]
Found it: This was caused by the autoCreate block added in PR #16105. I can fix this later today.
