### ISSUE TITLE
MODX 3.0.0 Incompatible with Articles Extra

### ISSUE THREAD

**Issue by visualgui** [modxcms/revolution#16136]
### Summary
Pages created with Articles Extra are completely broken when upgraded to MODX 3.0.0

### Step to reproduce
Tried to update Article Extra, but it failed.

### Observed behavior
Here’s the failure message: “Could not download and create transport package with signature: articles-2.0.0-alpha1”

### Expected behavior
Update Articles Extra successfully.

### Environment
MODX Cloud. PHP 7.3

**Comment by Ibochkarev** [comment]
@visualgui please create issue in https://github.com/modxcms/Articles

**Comment by visualgui** [comment]
@Ibochkarev, thanks. Created it in Articles.
