### ISSUE TITLE
MODX 3.0.0 - wrong markup: at a link in the Overhead at "modx_transport_packages"

### ISSUE THREAD

**Issue by eire69k** [modxcms/revolution#16131]
### Summary
> Systeminformationen /  Tabellenname / modx_transport_packages / Overhead / a

The link for the cache in the "overhead table" is not usable because of a wrong html markup for the opening and closing character. The  the opening and closing character in the source text is written as &amp;lt; and &amp;gt; instead of &lt;a .. and &lt;/a&gt;.

### Step to reproduce
see below "Environment"

### Observed behavior
<code>
&lt;div class="x-grid3-cell-inner x-grid3-col-3"&gt;
	&amp;lt;a href="javascript:;" onclick="optimize('modx_transport_packages')" title="Click here to optimise this table"&amp;gt;2 MB&amp;lt;/a&amp;gt;
&lt;/div&gt;
</code>

### Expected behavior
The opening character in the source text should be written in the correct markup, so that the link is usable
<code>
&lt;div class="x-grid3-cell-inner x-grid3-col-3"&gt;
	&lt;a href="javascript:;" onclick="optimize('modx_transport_packages')" title="Click here to optimise this table"&gt;2 MB&lt;/a&gt;
&lt;/div&gt;
</code>

### Environment
**MODX Revolution**: 3.0.0-pl (traditional)
**PHP Version:** 7.4.28
**Linux**: 4.14.132
**Apache**: 2.0 Handler (20120211)
**mysql**: 5.7.37-40-log
**mysqlnd**: 7.4.28...
**Unicode-Zeichensatz**: "utf8" and "utf8_unicode_ci"
(local: MAMP PRO 6 and external server installation)
**Installt Packages are**:
AdvSearch, Breadcrumbs, CodeMirror, Collections, FormIt, getPage, getResourceField, getResources, getUserProfiles, If, pdoTools (3.0.0-beta), siblingNav, tagLister, TinyMCE Rich Text Editor, translit, UltimateParent, Wayfinder

**Comment by smg6511** [comment]
To clarify, this is referring to the database optimization links that should show in the Overhead column of the Database Tables tab (at Reports/System Info). The bug occurs on any row where the table needs optimizing, not just the one referenced.
