### ISSUE TITLE
MODX 3.0.0 Can’t download files from Media Browser when basePath & baseURL are set

### ISSUE THREAD

**Issue by halftrainedharry** [modxcms/revolution#16134]
### Summary
In the 'Media Browser', right click -> "Download File" doesn't work, if the file is in a 'Media Source' with basePath/baseUrl set.

### Step to reproduce
Create a 'Media Source' with basePath/baseUrl set to a value other than empty (e.g. `assets/images/`).
In the 'Media Browser' try to download a file from this 'Media Source' with right click -> "Download File".

### Observed behavior
Blank page with error message "Cannot open file: /assets/images/myimage.jpg".

It seems that the basePath is added to the image path twice: `.../assets/images/assets/images/myimage.jpg`
When the processor “Browser/File/Download” is called, the basePath is already prepended to the image name in the “file” request-parameter and then gets added again in the processor (function `prefixPath()` in `core/vendor/league/flysystem/src/PathPrefixer.php`).

### Environment
MODX 3.0.0

**Comment by halftrainedharry** [comment]
I tried to fix the bug, but I got confused by the code.
Why is the 'Browser/File/Download' processor **called twice** here? I must be missing something.

https://github.com/modxcms/revolution/blob/fe438bf3dd4a9863bc479e21945d05215141d853/manager/assets/modext/widgets/media/modx.browser.js#L195-L210

If all the code above is replaced by this code, it should work.
```js
if (!Ext.isEmpty(data.pathRelative)) {
    location.href = MODx.config.connector_url+'?action=Browser/File/Download&download=1&file='+data.pathRelative+'&HTTP_MODAUTH='+MODx.siteId+'&source='+this.config.source+'&wctx='+MODx.ctx;
}
```

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx3-cant-download-files-from-media-browser-when-basepath-baseurl-are-set/5202/3
