### ISSUE TITLE
PhpThumbof not work filters in modx 3.0.0

### ISSUE THREAD

**Issue by themaltsev** [modxcms/revolution#16138]
### Summary
In last version phpThumbof 
Not cut #fff color 

:phpthumbof in same situation now work filter 
In this example pthumb on photo
![image](https://user-images.githubusercontent.com/47543995/162971427-d305cc61-fdf5-4aa4-ab10-25989bd870ec.png)

**Comment by Mark-H** [comment]
Please report extras incompatibilities to their own repositories: https://github.com/modxcms/pThumb/issues
