### ISSUE TITLE
getResources Not Loading in MODX 3.0.0

### ISSUE THREAD

**Issue by visualgui** [modxcms/revolution#16139]
### Summary
getResources fails to load in MODX 3.0.0

### Step to reproduce
Here’s the code:
`[[getResources? &showHidden=`1` &includeTVs=`1` &tvPrefix=`` &limit=`0` &sortbyTV=`lname` &sortdirTV=`ASC` &parents=`1234` &depth=`1` &tpl=`faculty_list` &sortBy=`lname` &sortDir=`ASC` &display=`all` &filter=`hide_all,1,2`]]
`

### Observed behavior
It seems to get a timeout and load up a blank page.

### Expected behavior
It should populate all the children from the parent directory

### Environment
MODX version 3.0.0. PHP 7.3. MySQL 5.7.35-38

**Comment by Mark-H** [comment]
Please report extras issues in their respective repositories: https://github.com/opengeek/getResources/issues
