### ISSUE TITLE
Здравствуйте нашёл баг в MODX 3.0.0 pl при смене пароля у юзера

### ISSUE THREAD

**Issue by themaltsev** [modxcms/revolution#16137]
Не даёт поставить свой пароль
Любые комбинации 
Верхний регистр + нижний регист
+ цифра + спецсимвол !

**Comment by Ibochkarev** [comment]
@themaltsev Напишите, пожалуйста, на английском и используя шаблон как по ссылке:

https://github.com/modxcms/revolution/issues/new?assignees=&labels=bug&template=bug_report.md
