### ISSUE TITLE
MODX 3.0.0 – getResources & getPage fails to load TPLs using @FILE Binding

### ISSUE THREAD

**Issue by eire69k** [modxcms/revolution#16148]
### Summary
```@FILE``` Binding in  "getResources" & "getPage" no longer works in MODX 3.0.0.

### Step to reproduce
In one of my longstanding projects I have always used the following way to call child resources:

```
[[!getResources?
	&parents=`2`
	&where=`{"template:=":8}`
	&tplPath=`[[++assets_path]]templates/page/chunks/getResources/`
	&tplWrapper=`@FILE product_outer.tpl`
	&wrapIfEmpty=`0`
	&tpl=`@FILE product_item.tpl`
	&hideContainer=`1`
	&includeTVs=`1`
	&processTVs=`1`
	&.....
]]
```

### Observed behavior
and now the same call doesn't work anymore in Modx 3.0.0. It is the same with "getPage".
The call only works if I load the chunks directly from the element tree in the manager system, but not from the filesysrem.

This Example does still works:
```
[[!getResources?
	&parents=`2`
	&where=`{"template:=":8}`
	&tplWrapper=`product_outer`
	&wrapIfEmpty=`0`
	&tpl=`product_item`
	&hideContainer=`1`
	&includeTVs=`1`
	&processTVs=`1`
	&.....
]]
```
Does this issue have anything to do with the latest changes with ```@EVAL```?
I know that ```@EVAL``` is no longer supported, but the ```@FILE``` Binding should still work, right?

### Expected behavior
It should be possible to output external chunks with the use of ```@FILE``` binding in "getResources" & "getPage".

### Environment
MODX Revolution: 3.0.0-pl (traditional)
PHP Version: 7.4.28
Linux: 4.14.132
Apache: 2.0 Handler (20120211)
mysql: 5.7.37-40-log
mysqlnd: 7.4.28...
Firefox, Firefox Developer Edition, Safari, Chrome

**Comment by halftrainedharry** [comment]
When I test it, the problem seems to be that `[[++assets_path]]` in the template path  ``&tplPath=`[[++assets_path]]templates/page/chunks/getResources/` `` is not replaced with the value of the system setting before _getResources_ is called.

Does the tag `[[++assets_path]]` by its own output the correct value?

**Comment by Ibochkarev** [comment]
@eire69k And from what moment did the getResource start working with file elements?
As far as I know, this is implemented in a more modern set of snippets from the pdoTools set.

**Comment by JoshuaLuckers** [comment]
ping @opengeek

**Comment by zaigham** [comment]
> @eire69k And from what moment did the getResource start working with file elements? As far as I know, this is implemented in a more modern set of snippets from the pdoTools set.

https://github.com/opengeek/getResources/blob/master/core/components/getresources/include.parsetpl.php#L9 it has been supported all along.

**Comment by JoshuaLuckers** [comment]
@eire69k does it help if you change `[[++assets_path]]` (cached) to `[[!++assets_path]]` (uncached)?

**Comment by eire69k** [comment]
First of all, I thank you for your effort and I apologize for being so vague in my description... and I'm sorry that my english is not the best as well...

Maybe I should have described before that I always store all templates and almost all chunks from the webpage on the server and not in the manager to separate the tempates from the database. This allows me to use 'svn commit' to keep the original data for the strukture of the webpage on my localhost.

I also use allways the following snippet to call the templates from the manager.

[[includeTemplate]]
```
<?php
# Snippet to include files from filesystem
# [[includeTemplate? &file=`assets/templates/mytemplate/file.tpl`]]

if ( !isset($file) || $file== "" ) return "No file specified."; //check if there's a file given.

//Start the buffer
ob_start();

//include
include $file;
//get contents from the buffer
$ob_contents = ob_get_contents();
//and kill/delete the buffer
ob_end_clean();
//return it to MODx
return $ob_contents;
```
for example in Template I use this instead of using the static ressource option.
```
[[includeTemplate? &file=`assets/templates/page/home.tpl`]] 
```
and in the extern templates I have this:
```
[[includeTemplate? &file=`assets/templates/page/head.tpl`]]
...
[[*content]]
...
[[includeTemplate? &file=`assets/templates/page/footer.tpl`]]
```

When I use the debug mode on my MAC with MAMP 6 in Modx 2.8.3, the ```&tplPath``` with this tag ```[[++assets_path]]``` putout this:
```
Array
(
	...
	[tplPath] => /Users/mynamne/Sites/projectfolder/assets/templates/page/chunks/getResources/
	[tpl] => @FILE item.tpl
	[tplWrapper] => @FILE outer.tpl
	[uri] => weine/rosewein/chateau-minuty-cuvee-m-rose.html
	...
)
```
without this tag ```[[++assets_path]]``` and of course my snipped the whole thing in Modx 2.8.3 or older versions won't work but in Modx 3.0.0 not even the debug mode is displayed.

If the whole issue is just related to my snippet, I apologize and we can close this bug report.

**Comment by eire69k** [comment]
> @eire69k does it help if you change `[[++assets_path]]` (cached) to `[[!++assets_path]]` (uncached)?

No I'm sorry, unfortunately it doesn't work.

**Comment by JoshuaLuckers** [comment]
> First of all, I thank you for your effort and I apologize for being so vague in my description... and I'm sorry that my english is not the best as well...

No worries, we're happy that you took the time and effort to report the issue.

**Comment by eire69k** [comment]
> > First of all, I thank you for your effort and I apologize for being so vague in my description... and I'm sorry that my english is not the best as well...
> 
> No worries, we're happy that you took the time and effort to report the issue.

That's very nice, thanks a lot!
I have thought for a long time about whether I'm at the right place here at all and  if it has even to do with the new Modx Version. I have been looking for other solutions for days before... but I just can't figure out any solution. So I thought it could be a bug in the system....

**Comment by opengeek** [comment]
> > > First of all, I thank you for your effort and I apologize for being so vague in my description... and I'm sorry that my english is not the best as well...
> > 
> > 
> > No worries, we're happy that you took the time and effort to report the issue.
> 
> That's very nice, thanks a lot! I have thought for a long time about whether I'm at the right place here at all and if it has even to do with the new Modx Version. I have been looking for other solutions for days before... but I just can't figure out any solution. So I thought it could be a bug in the system....

I'll take a deeper look at this today, but nothing obvious is coming to mind.

**Comment by eire69k** [comment]
... By the way, I have changed my snipped above today to make my calls in the tamples shorter.
Like this:
```
<?php
# Snippet to include template files from file system
# usage: [[includeTemplate? &tpl=`templatename.tpl`]]

if (!isset($tpl)||$tpl=="") return "Missing Template file!";

$tpl = $base_path .'assets/templates/page/'.$tpl;
ob_start();
include($tpl);
return ob_get_clean();
```
... but it didn't changes at all. The pages works well but the getResources is not showing up.

**Comment by eire69k** [comment]
> I'll take a deeper look at this today, but nothing obvious is coming to mind.

Thanks a lot anyway, Jason!

**Comment by JoshuaLuckers** [comment]
In 3.0.0 `[[++assets_path]]` will return an empty string. This particular config value is filtered before the config placeholders are set. See PR #15754 (a port of the changes that went into 2.8.2).

PR #15714 addressed some unintentional side effects and got merged in 2.x (and part of 2.8.3), however these changes didn't go into 3.x.

**Comment by eire69k** [comment]
> In 3.0.0 `[[++assets_path]]` will return an empty string. This particular config value is filtered before the config placeholders are set. See PR #15754 (a port of the changes that went into 2.8.2).
> 
> PR #15714 addressed some unintentional side effects and got merged in 2.x (and part of 2.8.3), however these changes didn't go into 3.x.

Thank you, Joshua! Well, that explains a lot than.

**Comment by opengeek** [comment]
> > In 3.0.0 `[[++assets_path]]` will return an empty string. This particular config value is filtered before the config placeholders are set. See PR #15754 (a port of the changes that went into 2.8.2).
> > PR #15714 addressed some unintentional side effects and got merged in 2.x (and part of 2.8.3), however these changes didn't go into 3.x.
> 
> Thank you, Joshua! Well, that explains a lot than.

#16149 should solve the problem.

**Comment by eire69k** [comment]
That's awesome guys! And so fast. I thank all of you for your great and quick work! :)

**Comment by JoshuaLuckers** [comment]
@eire69k we closed this issue because a fix is merged. This fix will be part of the next release.

**Comment by eire69k** [comment]
All right, Joshua. Thanx a lot!
