### ISSUE TITLE
 After Upgrade to MODX 3.0.0 Error: Undefined class constant 'MAJOR_VERSION'

### ISSUE THREAD

**Issue by bambibextor** [modxcms/revolution#16159]
After Upgrade to MODX 3.0.0 i've get this error. Could you help me, what I should do?
Thank you. 

An error occurred...

Error: Undefined class constant 'MAJOR_VERSION'

 

Errors:

    GuzzleHttp\Utils::defaultUserAgent()
    GuzzleHttp\default_user_agent()
    GuzzleHttp\Client->configureDefaults(Array ( [handler] => GuzzleHttp\HandlerStack Object ( [handler:GuzzleHttp\HandlerStack:private] => Closure Object ( [static] => Array ( [default] => Closure Object ( [static] => Array ( [default] => GuzzleHttp\Handler\CurlMultiHandler Object ( [factory:GuzzleHttp\Handler\CurlMultiHandler:private] => GuzzleHttp\Handler\CurlFactory Object ( [handles:GuzzleHttp\Handler\CurlFactory:private] => Array ( ) [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 50 ) [selectTimeout:GuzzleHttp\Handler\CurlMultiHandler:private] => 1 [active:GuzzleHttp\Handler\CurlMultiHandler:private] => [handles:GuzzleHttp\Handler\CurlMultiHandler:private] => Array ( ) [delays:GuzzleHttp\Handler\CurlMultiHandler:private] => Array ( ) ) [sync] => GuzzleHttp\Handler\CurlHandler Object ( [factory:GuzzleHttp\Handler\CurlHandler:private] => GuzzleHttp\Handler\CurlFactory Object ( [handles:GuzzleHttp\Handler\CurlFactory:private] => Array ( ) [maxHandles:GuzzleHttp\Handler\CurlFactory:private] => 3 ) ) ) [parameter] => Array ( [$request] => <required> [$options] => <required> ) ) [streaming] => GuzzleHttp\Handler\StreamHandler Object ( [lastHeaders:GuzzleHttp\Handler\StreamHandler:private] => Array ( ) ) ) [parameter] => Array ( [$request] => <required> [$options] => <required> ) ) [stack:GuzzleHttp\HandlerStack:private] => Array ( [0] => Array ( [0] => Closure Object ( [parameter] => Array ( [$handler] => <required> ) ) [1] => http_errors ) [1] => Array ( [0] => Closure Object ( [parameter] => Array ( [$handler] => <required> ) ) [1] => allow_redirects ) [2] => Array ( [0] => Closure Object ( [parameter] => Array ( [$handler] => <required> ) ) [1] => cookies ) [3] => Array ( [0] => Closure Object ( [parameter] => Array ( [$handler] => <required> ) ) [1] => prepare_body ) ) [cached:GuzzleHttp\HandlerStack:private] => ) ) )
    GuzzleHttp\Client->__construct()
    UpgradeMODX->init()
    include(string "/home/ch235262/web/classictelephon.com/public_html/modx/core/cache/includes/elements/modx/revolution/modsnippet/3.include.cache.php")
    MODX\Revolution\modScript->process(NULL)
    MODX\Revolution\modDashboardSnippetWidget->render()
    MODX\Revolution\modDashboardWidgetInterface->process()
    MODX\Revolution\modDashboardWidget->getContent(object)
    MODX\Revolution\modDashboard->render(object, object)
    WelcomeManagerController->process(Array ( ) )
    MODX\Revolution\modManagerController->render()
    MODX\Revolution\modManagerResponse->outputContent(Array ( ) )
    MODX\Revolution\modManagerRequest->prepareResponse()
    MODX\Revolution\modManagerRequest->handleRequest()

**Comment by Mark-H** [comment]
This is a Guzzle conflict due to a package shipping with an older version of Guzzle, while MODX 3 now also has a recent version included. Installing the [guzzle7](https://modx.com/extras/package/guzzle7) package can help sort it out.

**Comment by bambibextor** [comment]
Thank you very much for your help. I just installed the package guzzle7 and now it runs.

**Comment by ilyamio** [comment]
Thank you very much for solution. This really works!
