### ISSUE TITLE
Bad link Commercial Support

### ISSUE THREAD

**Issue by Electrica** [modxcms/revolution#16177]
### Summary
![image](https://user-images.githubusercontent.com/3878386/166944821-edb6687d-47c8-46b9-9ec6-3c4a709bb65a.png)
Bad link https://modx.com/solutions/services

### Step to reproduce
Open Help and Support and click Commercial Support

### Environment

MODX 3.0.0

**Comment by matdave** [comment]
Thanks, fixed.
