### ISSUE TITLE
MODX >2.8.4 and >3.0.1: Remove privateweb privatemgr columns in site_content

### ISSUE THREAD

**Issue by patrickatwsrn** [modxcms/revolution#16174]
### Summary

I just stumbled upon these fields. They seem to be completely forgotten in the MODX core.

Bob Ray said avout them in 2014

> Those are deprecated and not used by MODX. At some point, they will probably be removed.
Source: https://forums.modx.com/thread/91384/what-are-privateweb-and-privatemgr

### Step to reproduce
Have a look at the site_content table

* privateweb 
* privatemgr

MODX 2.8.3
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/68318893/166447173-5ba6300b-0b6e-4420-bd9d-d0779f0af99f.png">

MODX 3.0.1
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/68318893/166447107-9a57de0e-205f-4c4f-95e3-304a699cb4f6.png">

Both columns don't seem to be used anymore:

* https://github.com/modxcms/revolution/search?q=privateweb
* https://github.com/modxcms/revolution/search?q=privatemgr

### Environment
Any MODX version up and including 3.x

I guess there are more fields like this. Any idea how we can identify them?

**Comment by Ruslan-Aleev** [comment]
> I guess there are more fields like this. Any idea how we can identify them?

Probably by manually reviewing the fields in the classes https://github.com/modxcms/revolution/tree/3.x/core/src/Revolution/mysql

By the way, the resource also has a strange `donthit` field.
