### ISSUE TITLE
It is impossible to create a New Document form Resources Tree if "Automatically generate alias" is set to "No" in System Settings

### ISSUE THREAD

**Issue by Treniota** [modxcms/revolution#16178]
### Summary
If "Automatically generate alias" is set to "No" in System Settings it is impossible to create a New Document from Resources Tree since **there is no field for "Alias" in the Popup window**.

### Step to reproduce
Set "Automatically generate alias" to "No" in System Settings and try to create new Document from Resources Tree.

### Expected behavior
There shloud be field for "Alias" in the Popup window.

### Environment
MODX Revolution 3.0.1

**Comment by smg6511** [comment]
I can confirm this issue, although a couple more conditions are required to trigger this bug:
- FURLs are on (`friendly_urls` = Yes) and
- The template picker is active (`enable_template_picker_in_tree` = Yes)

Perhaps the best way to handle this would be to conditionally add an alias field to the template picker when the above settings are encountered.

**Comment by modxcommunity** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx-3-0-3-resource-creation-gone-crazy/6754/2
