### ISSUE TITLE
Copy File Path option on the file context menu in the Media Browser is missing in MODX3

### ISSUE THREAD

**Issue by deJaya** [modxcms/revolution#16179]
### Summary

The "Copy File Path" option on the file context menu in the Media Browser is missing in MODX3

### Step to reproduce

Right-click a file in the Media Browser. 

### Observed behaviour

Copy File Path option is missing.

### Expected behaviour

Copy File Path option should be present.

### Environment

MODX3

**Comment by Ibochkarev** [comment]
Fixed #16180
