### ISSUE TITLE
Многие tv поля при выводе изображения или файла выводят ошибку 502?

### ISSUE THREAD

**Issue by G-Start2021** [modxcms/revolution#16175]
Самая явная ошибка это создаешь tv полей изображение или файлов выводишь шаблон выходит ошибку 502 ?
502 Bad Gateway
nginx-reuseport/1.21.1
Желательно проверить все tv поля потому, что другие поля ещё не проверял не сталкивался ещё.
Через migx всё отлично выводится изображение, если нужно напрямую то увы 502 ошибка.

**Comment by G-Start2021** [comment]
> Самая явная ошибка это создаешь tv полей изображение или файлов выводишь шаблон выходит ошибку 502 ? 502 Bad Gateway nginx-reuseport/1.21.1 Желательно проверить все tv поля потому, что другие поля ещё не проверял не сталкивался ещё. Через migx всё отлично выводится изображение, если нужно напрямую то увы 502 ошибка.

**Comment by G-Start2021** [comment]
Версия 3.0.1 была у меня ))

**Comment by Ruslan-Aleev** [comment]
Please correct the issue, write in English.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report your issue and help make MODX better.
Would you be so kind to describe the issue you're experiencing in English using the Bug Report template?
