### ISSUE TITLE
Notempty Output Filter cuts off value if it includes snippet properties

### ISSUE THREAD

**Issue by newswanger** [modxcms/revolution#16186]
### Summary
Not empty output filter will truncate the value if it includes a snippet with properties.

### Step to reproduce
Add the following to a template:
[[*content:notempty=\`[[!Wayfinder? &startId=\`0\` &level=\`1\`]]\`]]

### Observed behavior
Rendering this in a browser will display:
[[!Wayfinder? &startId=

### Expected behavior
The complete snippet tag should be returned from the filter and processed. This filter does work  MODX 2.8.4

### Environment
MODX 3.0.1, apache2 , mariaDB

**Comment by Bruno17** [comment]
you know, conditionals like that, will allways parse the snippet inside, also when content is empty.
Better try using the mosquito method, like that:
```[[[[*content:notempty=`Wayfinder? &startId=`0` &level=`1``]]]]```

Maybe, this will also help with your issue.
see: https://modx.com/blog/2012/09/14/tags-as-the-result-or-how-conditionals-are-like-mosquitoes/

**Comment by JoshuaLuckers** [comment]
Related to issue #16044

I've added test data to the Input Filter Unit Test in my repo, this will fail the Unit Test: https://github.com/JoshuaLuckers/revolution/commit/004b877ad0e597e77b19d4a6a09477495bdde4ad

**Comment by newswanger** [comment]
I tracked the problem to the `preg_match_all` in modInputFilter.php.

[revolution/core/src/Revolution/Filters/modInputFilter.php](https://github.com/modxcms/revolution/blob/697a0286117a7e30b19c7f78ef30803806daf6c3/core/src/Revolution/Filters/modInputFilter.php#L56)

I think I have a fix that works:
            if (preg_match_all('~:([^:=]+)(?:=\`((?:(?:[^:=][\s\S]\*?|(?R))\*?))\`$)?~s', $modifiers, $matches)) {

The addition of the '$' makes sure it matches the last tick mark in the string.

**Comment by newswanger** [comment]
Thanks @Bruno17, the example is just for testing. In the real world scenario the output filter looks like:

[[*content:notempty=\`<div class="content'>[[*content]]<\/div>\`]]

Then the end user includes a snippet with properties in the content field.

**Comment by JoshuaLuckers** [comment]
> I think I have a fix that works: if (preg_match_all('~:([^:=]+)(?:=`((?:(?:[^:=][\s\S]*?|(?R))*?))`$)?~s', $modifiers, $matches)) {
> 
> The addition of the '$' makes sure it matches the last tick mark in the string.

Sadly this will break the input filter in other scenario's, like this one: https://github.com/JoshuaLuckers/revolution/blob/004b877ad0e597e77b19d4a6a09477495bdde4ad/_build/test/Tests/Model/Filters/modInputFilterTest.php#L58-L71

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/output-modifier-issue-in-modx-3-0-1-pl/5376/20

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/some-modx-tags-not-getting-parsed-after-upgrade-to-modx-3/5430/10

**Comment by halftrainedharry** [comment]
Can we please revert PR #14458 until someone is able to come up with a solution that works reliably.

The problems with this change keep piling up here on github and in the MODX forum.

Here's another one. Same cause:
https://community.modx.com/t/tagger-uncached-calling-problem/5364

**Comment by Jako** [comment]
There is one problem in the original issue: Normally the parsing of nested output filters are going from inside out. Since the Wayfinder call is uncached it won't be already evaluated, when the output filter chain is parsed. Does it work, when you call the content uncached?

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/issue-with-contains-modifier/5491/3

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx3-broken-output-filters/5906/1

**Comment by Mark-H** [comment]
Fixed in #16288
