### ISSUE TITLE
Unzip files not working in 2.8.4

### ISSUE THREAD

**Issue by jmacdonald-spectacle** [modxcms/revolution#16188]
### Summary
Unzipping files doesn't work in tree or media browser

### Step to reproduce
Right-click on a zipped file in the file tree or media browser.  Choose Unzip file.

### Observed behavior
In tree (File tab or Media Browser) an alert appears with the file path. However, any slashes in the path are replaced by '%2f.' 
`Unzip File vendor%2Fswiper-8.1.4.zip`

After clicking OK, an Invalid path error is shown and the file is not unzipped.
`Invalid path for the unzipped file.: /var/www/vhosts/example.com/monocle-2019-10/vendor%2Fswiper-8.1.4.zip
 `

 In the Media browser panel, nothing happens after right-clicking.

### Expected behavior
File should unzip.

Note: I remember this error was a problem in a previous version.

### Environment
MODX 2.8.4

**Comment by patrickatwsrn** [comment]
I have the same problem and I also noticed, that I can't move zip files into another directory.

**Comment by patrickatwsrn** [comment]
Update: I also can't drag and drop directories inside the file tree to another location. I suspect there is something bigger going on that explains all problems above.

**Comment by jmacdonald-spectacle** [comment]
This morning I tried an unzip on a different site and it worked as expected. I'll investigate further.

However, as @patrickatwsrn indicates, dragging files in the tree doesn't work. It looks like it's working and then the file snaps back.

**Comment by jmacdonald-spectacle** [comment]
I tried again on the initial site and unzipping worked fine. Maybe it was a PHP or hosting error. Or maybe Chrome.

Anyway, I also confirmed that drag and drop in the tree doesn't work on this site either. I tried another site with no extras and moving a file still doesn't work.

**Comment by smg6511** [comment]
The drag-drop problem is fixed in #16202 ... just waiting on the PR to be merged.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue and help make MODX better. Since unzipping seems to work fine again I'm going to close this issue.
