### ISSUE TITLE
Fatal error: Uncaught TypeError: array_walk_recursive(): Argument #2 ($callback) must be a valid callback, class "modRestServiceRequest"

### ISSUE THREAD

**Issue by timo-schlotmann** [modxcms/revolution#16189]
After updating to version 3.x and making the necessary adjustments, we get the following error.

Fatal error: Uncaught TypeError: array_walk_recursive(): Argument #2 ($callback) must be a valid callback, class "modRestServiceRequest" not found in /xxx/core/src/Revolution/Rest/modRestServiceRequest.php:118 Stack trace: #0 /xxx/core/src/Revolution/Rest/modRestServiceRequest.php(118): array_walk_recursive(Array, Array) #1 /xxx/core/src/Revolution/Rest/modRestService.php(114): MODX\Revolution\Rest\modRestServiceRequest->setHeaders() #2 /xxx/rest/v1/manager/index.php(55): MODX\Revolution\Rest\modRestService->prepare() #3 {main} thrown in /xxx/core/src/Revolution/Rest/modRestServiceRequest.php on line 118

https://github.com/modxcms/revolution/blob/cb6f56a19af818ad4d1d62dc0d31b9819aaa876f/core/src/Revolution/Rest/modRestServiceRequest.php#L118

Quick solution for us

`array_walk_recursive($headers, ['MODX\Revolution\Rest\modRestServiceRequest', '_trimString']);`

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue and help make MODX better.

~I'm unable to reproduce this error, how are you bootstrapping the rest service?
Can you provide a small test case to reproduce this error?~

In my setup the error is a warning and not a fatal error.

**Comment by timo-schlotmann** [comment]
Hey Joshua, **sorry for the delay** ... 

**This is our way ...** 

Which one would be yours?!

```php
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

use MODX\Revolution\modX;
use MODX\Revolution\Rest\modRestService;
use MODX\Revolution\Rest\modRestServiceRequest;
use MyClass\MyClass;

// Boot up MODX
require_once dirname(dirname(dirname(dirname(__FILE__)))) . '/config.core.php';

if (!@require_once(MODX_CORE_PATH . "vendor/autoload.php")) {
    exit();
}

$modx = new modX();
if (!is_object($modx) || !($modx instanceof modX)) {
    exit();
}

$modx->initialize('web');
$modx->getService('error','error.modError', '', '');

define('XXX_PACKAGENAME', 'xxx_package');


// Boot up any service classes or packages (models) you will need
require_once rtrim($modx->getOption(XXX_PACKAGENAME . '.core_path', null, $modx->getOption('core_path') .'components/' . XXX_PACKAGENAME), '/\\') . '/vendor/autoload.php';

$myClass = new MyClass($modx);

$rest = $modx->getService('rest', 'rest.modRestService', '', array(
    'basePath' => $myClass->config['restPath'] . 'Manager/Controllers/',
    // 'controllerClassSeparator' => '',
    'controllerClassPrefix' => $myClass->config['restClassPrefix'],
    // 'xmlRootNode' => 'response',
));

// Prepare the request
$rest->prepare();

// Make sure the user has the proper permissions, send the user a 401 error if not
if (!$rest->checkPermissions()) {
    $rest->sendUnauthorized(true);
}

header('Access-Control-Allow-Origin: *');

// Run the request
$rest->process();
```

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx-revolution-3-restful-api/5432/2
