### ISSUE TITLE
MagpieRSS::feed_start_element() error with PHP 8.0 and 8.1

### ISSUE THREAD

**Issue by andrewcsp** [modxcms/revolution#16208]
### Summary
I've noticed the following error appears hundreds of times related to MagpieRSS when running PHP 8.0 or 8.1

(ERROR @ /home/user/core/model/modx/xmlrss/magpierss.class.php : 133) PHP warning: MagpieRSS::feed_start_element(): Argument #3 ($attrs) must be passed by reference, value given

### Step to reproduce
To reliably reproduce the Magpie errors, delete the contents of your cache folder (within core), then load the MODX manager homepage/dashboard (i.e. domain.com/manager/)

### Observed behavior
Review the errors in Manage > Reports > Error Log. You should see hundreds of the above MagpieRSS error (186 of them for me).

### Expected behavior
I would expect to see no MagpieRSS errors.

### Environment
MODX Revolution 2.8.4-pl
Apache/2.4.53 (cPanel)
10.3.35-MariaDB
Confirmed with PHP Version 8.0.19 and 8.1.6. The problem does not occur with PHP 7.4.29.

**Comment by claytonk** [comment]
The feed_start_element() function does indeed show the third argument as being passed by reference. That function is on line 152:

`function feed_start_element($p, $element, &$attrs)`

It appears that removing the reference indicator ('&') will fix this issue, or at least it did in my case.

**Comment by matdave** [comment]
I've got a PR in for this. Thanks for reporting!
