### ISSUE TITLE
Trash shows not deleted resources if filtered

### ISSUE THREAD

**Issue by jdaehne** [modxcms/revolution#16224]
### Summary
Filtering the trash manager by a resource name, shows all resources and not only "deleted" resources. You can not finally remove "undeleted" resources - but they are listed inside the trash manager.

### Step to reproduce
Type in any resource name of a resource that is not markt as "deleted".

### Expected behavior
I would expect to only filter resources marked as "deleted" and not the complete resources of the site.

### Environment
MODX version: 2.8.4

![Bildschirmfoto 2022-07-14 um 11 40 23](https://user-images.githubusercontent.com/10563227/178953349-b88d5496-c37f-438e-aa5e-94c27a212d63.png)

**Comment by Ruslan-Aleev** [comment]
Yes, this bug was fixed for the 3.x branch - https://github.com/modxcms/revolution/pull/15946/commits/ca556302a4efddc4d4b87022eee25872119a5994
We can make a fix for the 2.x branch as well, although I'm not sure if those fixes will be merged in.

**Comment by opengeek** [comment]
> Yes, this bug was fixed for the 3.x branch - [ca55630](https://github.com/modxcms/revolution/commit/ca556302a4efddc4d4b87022eee25872119a5994)
> We can make a fix for the 2.x branch as well, although I'm not sure if those fixes will be merged in.

Why would bug fixes not be merged in? 🤔

**Comment by Ruslan-Aleev** [comment]
Isn't the 2.x branch frozen?
For the 3.x branch, https://github.com/modxcms/revolution/pull/15946 has been tested and is ready to be merged, but has been on the list for half a year now. How fast will a fix for the 2.x branch be added?
In general, the current logic of merging is not clear.

**Comment by opengeek** [comment]
> Isn't the 2.x branch frozen?
> For the 3.x branch, #15946 has been tested and is ready to be merged, but has been on the list for half a year now. How fast will a fix for the 2.x branch be added?
> In general, the current logic of merging is not clear.

It is not frozen, no. That PR in 3.x is targeting 3.1 because it is a new feature and we just released 3.0 and have bug fixes to get released before we start the 3.1 release cycle. The bug fixes in 2.x will be merged as needed for the next release when there is enough of them or the severity is great enough to warrant release.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/16228
