### ISSUE TITLE
cache_scripts doesn't seem to work

### ISSUE THREAD

**Issue by benniledl** [modxcms/revolution#16222]
### Summary
Hello,
I noticed that even with cache_scripts set to 0, modx still writes my snippets to /core/cache/includes/elements/modx/revolution/modsnippet/2.include.cache.php

### Steps to reproduce
I wanted a script that is supposed to check the availability of a domain name,
if I try this in a snippet:
$output = var_dump($_POST);
return $output;

### Expected behavior
I want it to take the post data that I send and return it, after refreshing or sending another post request i want to have the $_POST data refresh

### Observed behavior
After saving the file the cache is deleted so 1 post request is working, after that everything is cached, when i output the $_POST array even on other devices it is the same thing that I sent once on another device

Also the script from the snippet is cached in /core/cache/includes/elements/modx/revolution/modsnippet/2.include.cache.php

### Environment
MODX 3.0.1-pl, apache 2.4.53, mysql 8.1.8, firefox, safari(IOS), FPM PHP 8.0

**Comment by Mark-H** [comment]
Sounds like you're calling the snippet as [[snippetName]] - to make it run every request, add the exclamation mark: [[!snippetName]]

The scripts cache you're trying to disable with that setting is for caching the content of the snippet (not its parsing), so I'd stay away from changing that. The thing that's actually causing repeated requests to have the same output in this case is the resource cache. 

The exclamation mark in the snippet tag makes sure it'll process each time and not have its result cached with the resource.

https://www.markhamstra.com/modx/2011/10/caching-guidelines-for-modx-revolution/

**Comment by benniledl** [comment]
> Sounds like you're calling the snippet as [[snippetName]] - to make it run every request, add the exclamation mark: [[!snippetName]]
> 
> https://www.markhamstra.com/modx/2011/10/caching-guidelines-for-modx-revolution/

Thank you so much I couldn't find that info, it works now thank you

**Comment by Mark-H** [comment]
Great :)
