### ISSUE TITLE
MODx.combo.Permission combobox not working in MODX3

### ISSUE THREAD

**Issue by muzzwood** [modxcms/revolution#16226]
### Summary
The combobox `MODx.combo.Permission` is not working in MODX3.
I'll look into this shortly.

Edit: 
It's an `only_full_group_by` issue.

### Step to reproduce
It's used in two places, on the Edit Widget panel of the Dashboards page, and in the Create New Permission window when editing a policy template.

### Observed behavior
The connector response shows success and gives the total count, but no results are returned.
Thus, the dropdown doesn't get populated.

### Expected behavior
It should load a list of permissions that can be selected.

### Environment
MODX 3 (both 3.0.1 and latest git), PHP 7.4, MySQL 8.0.27

**Comment by smg6511** [comment]
Fixed with #16273.
