### ISSUE TITLE
Access Policy Context not selectable

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#16239]
### Summary
On an almost fresh MODX installation, the Context policy is not selectable on usergroup/update -> contexts. 

The connector of that combo uses the following properties:

start: 0
limit: 20
action: Security/Access/Policy/GetList
group: Administrator,Object
combo: true
query:

### Environment
MODX 3.0.1, PHP 7.4

**Comment by smg6511** [comment]
I'm seeing an issue in the toolbar filter as well, which only lists Administrator-based policies. 

@Mark-H @BobRay (or any modx ACL gurus out there) - The question is: What should the relevant policy templates be for Contexts? In 2.8 it looks like it's Administrator, Object, and Context. Additionally, what is the intended use of the Object template (I've never really been clear on that)? And, why would one create a Context policy based off the Object template _instead_ of the Context one?
