### ISSUE TITLE
Add webp to default media source image formats

### ISSUE THREAD

**Issue by rthrash** [modxcms/revolution#16234]
### Summary
WebP is missing from the default image formats.

### Why is it needed?
WebP files are commonly used today but they will not generate thumbnails in the media browsers. 

### Suggested solution(s)
Update the default system setting for [[+imageExtensions]] to include `webp` … should be done in 2.x and 3.x branches IMO, and the upgrade scripts.

### Related issue(s)/PR(s)
Mentioned here: https://community.modx.com/t/webp-thumbnail-cannot-not-be-shown/5469/4

**Comment by Ibochkarev** [comment]
Added https://github.com/modxcms/revolution/pull/16235
