### ISSUE TITLE
modX.runSnippet Cache

### ISSUE THREAD

**Issue by benniledl** [modxcms/revolution#16243]
Hello,
I was wondering if there is an option to cache modX.runSnippet so that it isn't always executed
This page says: 
`When you call a Snippet using runSnippet, the Snippet code is always executed: the results are never returned from cache.`
https://docs.modx.com/current/en/extending-modx/modx-class/reference/modx.runsnippet#handy-hint
Thank you for any hints :)

**Comment by Bruno17** [comment]
You didn't tell, where you are calling runSnippet.
If you call it within another snippet, that is called cached, then the whole output is cached.

**Comment by benniledl** [comment]
Hi @Bruno17 
I am running this snippet in a snippet.

In a page i run this:
`[[!domain_check]]`
in the snippet domain_check i run this:
`$tldarray = $modx->runSnippet('tld_array');`

I didn't quite understand what you mean, can you explain it to me please?

**Comment by Bruno17** [comment]
I don't know, if your snippet has to be called uncached for some reason, because I don't know what it does, but when you call your snippet cached

```
[[domain_check]]
```
it would run only once, after the cache was cleared and the output of your snippet (domain_check) would be cached.

**Comment by benniledl** [comment]
the domain_check snippet has to be called uncached, it checks the availability of a domain the snippet tld_array must not be called this often
in the domain_check snippet there is a check to validate the tld, this is done by comparing the input of the user with an array that is generated in tld_arrar

tld_array should be called once in a while to keep the array with the tlds up to date but mustnt be called to often because:

the array shouldn't be generated everytime because it gets the data from iana.org and that slows down the script + i dont want to flood them with requests

**Comment by Bruno17** [comment]
maybe, you could try it that way:

```
[[!domain_check? &tldarray=`[[tld_array]]`]]
```
this would pass the cached result of tld_array to the tldarray property
You could also wrapp the tld_array snippet with getCache, which would give you more control for caching.

https://modx.com/extras/package/getcache

**Comment by benniledl** [comment]
$tldarray is now a string
var_dump($tldarray);
`string(5) "Array" Array `

**Comment by Bruno17** [comment]
snippets can only output strings, when parsed.
You can return a json - string and convert it back to an array within domain_check

**Comment by benniledl** [comment]
thank you very much this works :)
in tld_array i now return:
`return json_encode($tldarray);`
and in domain_check i convert it to an array like this:
`$tldarray = json_decode($tldarray, 1);`

**Comment by benniledl** [comment]
Nevermind, for testing purposes I called it uncached like this:
[[!domain_check? &tldarray=`[[!tld_array]]`]]
calling it cached
[[!domain_check? &tldarray=`[[tld_array]]`]]
then it doesn't work anymore

**Comment by halftrainedharry** [comment]
I would use the MODX cache manager in the "domain_check" snippet.

Try to read the value from the cache with `$value = $modx->cacheManager->get('mydata');`
If there is no value in the cache, then run the snippet "tld_array" and cache the value with `$modx->cacheManager->set('mydata', $tld_array_result, $lifetime);` for a certain amount of time.

See the documentation:
https://docs.modx.com/current/en/extending-modx/caching

**Comment by benniledl** [comment]
Thank you, Cachemanager works :)

**Comment by Bruno17** [comment]
Maybe it would be better to fetch the array by a cronjob and store it in a chunk or a file.
Also, I think for questions like that, it is better to ask in the forums
https://community.modx.com

**Comment by benniledl** [comment]
The function that creates the array now stores it in json_encode in the modx cache manager for 1 week
The domain check gets the data from the cache manager and converts it back to an array, if the cache expired thus the array is then NULL it runs the tldarray snippet again and then gets the data from the cache manager
It works like a charm

**Comment by benniledl** [comment]
Thank you all for helping :)
