### ISSUE TITLE
How set cookie_samesite none, not work

### ISSUE THREAD

**Issue by krot3232** [modxcms/revolution#16252]
MODX Revolution 2.8.4-pl, apache, php 70234
I set system var modx session_cookie_samesite | None.
Result not set in cookies samesite if php < 70300.
https://github.com/modxcms/revolution/blob/2.x/core/model/modx/modx.class.php#L2598

**Comment by Mark-H** [comment]
Support for the samesite option on session cookies was added to PHP 7.3. Upgrade PHP to 7.3 or higher.
