### ISSUE TITLE
Revo 3 loading object without class names (use case: modMediasource)

### ISSUE THREAD

**Issue by rtripault** [modxcms/revolution#16265]
### Summary
With Revo 3 (3.0.1), getting a `modMediaSource` the "legacy way" is not possible (while for example retrieving a resource using `modx->getObject('modResource', 1)` works).

### Step to reproduce
```
$source = $modx->getObject('modMediaSource', 1);
```

will result in 
```
core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 786) modMediaSource::load() is not a valid static method.
```

### Expected behavior
The object should be retrieved as if we were using `$modx->getObject(\MODX\Revolution\Sources\modMediaSource::class, 1);` or `$modx->getObject('sources.modMediaSource', 1);`

### Environment
MODX 3.0.1, PHP 7.4, mysql 8

### Some lead

During the digging, we found the following code would "fix" the issue, but that's nothing more than a hack (hoping it might bring some ideas for a real solution)

```
        if (!class_exists('modMediaSource_mysql')) {
            class_alias(\MODX\Revolution\Sources\mysql\modMediaSource::class, 'modMediaSource_mysql');
        }
        if (!isset($modx->map['modMediaSource'])) {
            $modx->map['modMediaSource'] = $modx->map[\MODX\Revolution\Sources\modMediaSource::class];
        }
```

The class aliasing happening in `modX::loadClass` is apparently not handling correctly objects in a sub folder.

**Comment by JoshuaLuckers** [comment]
Class names have been changed in 3.0, using the old class names is deprecated: https://docs.modx.com/3.x/en/getting-started/upgrading-to-3.0/class-names#model-service-classes

> For example `$modx->getIterator('modResource')` will still work - for now, even though the `\modResource` class is now `\MODX\Revolution\modResource`.

You should use the fully classified class name instead.

**Comment by rtripault** [comment]
Thanks for pointing that out. I completed get this has been deprecated (and if get the code comments correctly, will be removed in Revo 3.3). But to be honest, as of today, it's a bit more than a deprecation: it's broken.

The bug report was rather intended to prevent third party extras/components breaking and help transitioning to Revo 3.x

Hoping that makes sense

**Comment by Mark-H** [comment]
Most of my extras were already using `$modx->getObject('sources.modMediaSource', 1)` before, which works in both 2.x and 3.x. Not sure how else to smoothen this upgrade path, the submodels have always been a little weird to me.

**Comment by rtripault** [comment]
> Not sure how else to smoothen this upgrade path, the submodels have always been a little weird to me.

Agreed on the weirdness... regarding the approach to smooth that upgrade, no clue here too (for now), hence that issue, in case someone more knowledgeable could share some expertise ;)

**Comment by JoshuaLuckers** [comment]
I think we can solve this by adding a new class alias in `core/include/deprecated.php`.

```
class_alias(\MODX\Revolution\Sources\modMediaSource::class, \MODX\Revolution\modMediaSource::class);
```

See: https://github.com/modxcms/revolution/blob/f7bc0133f5f09184418a7ddf6f9b98a3f0decd9e/core/src/Revolution/modX.php#L2537

**Comment by Mark-H** [comment]
That would introduce a new class name (/alias) that never existed. Not a fan. 

I'd suggest* to close as wontfix with the suggestion to use `$modx->getObject('sources.modMediaSource', 1)` instead.
