### ISSUE TITLE
MODX3 resource saving returns http status code 500

### ISSUE THREAD

**Issue by nsuomine** [modxcms/revolution#16284]
### Summary
When I try to save a resource container with children, the saving will be infinite. The Javascript console reveals the status code 500. Saving the same resource without children works well. All logging is on but no log lines are generated.

Javascript console: index.php:1          Failed to load resource: the server responded with a status of 500 ()

### Step to reproduce
Create a resource container, add a child and try to save.

### Observed behavior
The saving is infinite.

### Expected behavior
The resource should be saved normally.

### Environment
MODX3.0.1, PHP 8.1. With PHP7.3, there are no issues. VersionX extra, but I turned it off.

**Comment by Mark-H** [comment]
Please check your server/PHP error log for the error message related to the 500 status code. Infinite saving issues can be a ton of different things.

**Comment by nsuomine** [comment]
Unfortunately, I don't get much data from access logs:

_2022-10-15
14:36:09
500
91.153.x.x
POST /connectors/index.php HTTP/1.1
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Finland
0
50085_

It confirms the 500 error but has no reason for it.

I have PHP error logging on MODX and I get other PHP log entries to the log. But related to this issue, no log lines. I can ask my hosting provider if they can provide me with more information.

**Comment by nsuomine** [comment]
I got the PHP logs and found the cause.

[15-Oct-2022 12:38:45 UTC] PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #2 must be of type array, xPDO\xPDOIterator given in /home/xxxxxxxxxxx/domains/xxxxxxxxxxxx.fi/public_html/core/cache/includes/elements/modx/revolution/modplugin/17.include.cache.php:27

The issue was caused by the autoRedictor plugin. I uninstalled it and saving works now. Thanks for the help.
