### ISSUE TITLE
MODX 3: Object in snippet properties gets converted to array

### ISSUE THREAD

**Issue by halftrainedharry** [modxcms/revolution#16283]
### Summary
In some cases an object that is passed by reference as a property to a snippet, gets converted to an array.

### Step to reproduce
Here is some example snippet code to showcase the issue:

```
<?php
$output = '';

$snippet = $modx->getObject('MODX\\Revolution\\modSnippet', ['name' => 'someSnippet']);
$user = $modx->getObject('MODX\\Revolution\\modUser', 1);
$properties = ['fields' => ['user' => &$user] ];
//$properties = ['user' => &$user]; //this works correctly

$output = "Type before: " . get_class($user);

$success = $snippet->process($properties);

$output .= " | Type after: " . (is_array($user) ? "ARRAY!" : get_class($user));
return $output;
```

Code of the snippet "someSnippet" (just to show that the variable `$user` isn't even used):
```
<?php
return "";
```

### Observed behavior

The output of the snippet is `Type before: MODX\Revolution\mysql\modUser | Type after: ARRAY! `. 
The variable `$user` gets converted to an array.

In MODX 2.x this is not the case.

This behavior creates a problem with custom hooks in the _Login_ extra.
https://github.com/modxcms/Login/issues/180

### Environment
MODX 3.0.1

**Comment by JoshuaLuckers** [comment]
This might have something to do with changes introduced in PR #15809

**Comment by halftrainedharry** [comment]
Yes, this is the place where the parameters get converted.

Specifically these lines:

https://github.com/modxcms/revolution/blob/f7bc0133f5f09184418a7ddf6f9b98a3f0decd9e/core/src/Revolution/modElement.php#L280-L284

---

Do you know of an easy way to make these conversions without accidentally converting the values in `$this->_properties` as well?

The following seems to work as a replacement for `array_walk_recursive`:

```php
$func = function ($item) use (&$func) {
	if (is_array($item)){
		return array_map($func, $item);
	} else if ($item instanceof \xPDOObject) {
		return $item->toArray('', false, true);
	} else {
		return $item;
	}
};
$value = array_map($func, $value);
```
