### ISSUE TITLE
OnResourceDelete event fired wrongly when saving a resource

### ISSUE THREAD

**Issue by wuuti** [modxcms/revolution#16295]
### Summary
When saving a resource in the manager, the event `OnResourceDelete` is fired, even if the "Deleted" on the resource is not ticked.

### Step to reproduce
- Create a silly plugin which listens for the `OnResourceDelete` event
- Log something in that case
- Save a resource (which is not in deleted state)

### Observed behavior
The event will be fired on save, which produces the logline.

### Expected behavior
Saving a resource should _only_ fire that event, if the "deleted" was ticked aka the resource in the deleted state (or cleaner: changed into the deleted state). 
It should _not_ fire on every save - this can have serious side effects (at least performance) if plugins are listening for that event and doing stuff as a reaction on that. 

### Potential root cause
It seems the root cause for this was a strict comparison introduced in this [change](https://github.com/modxcms/revolution/commit/399a55b0f8cf1ad4ed8ae1203c61809a5f19d9d0#diff-c902495ed4fd5241066b83f7d40e3172000d6f15b61aa686ef9b4e74ed56d73bR519) in the "checkDeletedStatus()" method of the Update Processor:
- getProperty returns an int
- object->get returns a boolean 
=> the introduced strict comparison lets the code assume that the deleted state has changed on the resource triggers the event

I have the feeling, that strict comparison changes like these might have introduced a lot more issues like this one under the hoods (also seems to not be covered by any test?). 

### Environment
MODX version: 3.0.1-pl (advanced)
Database: mysql 8.0.21 utf8mb4
PHP 8.1.11 (FPM)

**Comment by wuuti** [comment]
Update: the modx installation was updated from the latest modx 2 version to 3.

**Comment by halftrainedharry** [comment]
@wuuti I can confirm this bug and the root cause you discovered.
