### ISSUE TITLE
Neq filter behaviour

### ISSUE THREAD

**Issue by nsuomine** [modxcms/revolution#16308]
### Summary
I am not sure if this is a bug at all but I think the behaviour of neq filter changed after I upgraded to MODX3.

I have a TV _noAd_ with a value _false_ or _true_. If the value is not true, _ad_ chunk should be shown.

`[[*noAd:neq=`true`:then=`[[$ad]]`]]`

However, the previous tag returns _false_  text when I expect it to return the content of _ad_ chunk. I was able to correct this by calling _ad_ uncached:

`[[*noAd:neq=`true`:then=`[[!$ad]]`]]`

I am not 100% sure if this worked before MODX3 but at least, I didn't notice the issue earlier.

### Environment
MODX 3.02

**Comment by halftrainedharry** [comment]
I can't reproduce this problem.

Does the chunk `$ad` contain square brackets `[]`?
There is a problem with MODX 3.0.2 and output modifiers with single square brackets -> #16302.

**Comment by nsuomine** [comment]
Yes, $ad contains square brackets. I tried to remove them and the problem disappeared. So it seems to be the same issue as #16302.

**Comment by halftrainedharry** [comment]
So if you apply the changes (file `core/src/Revolution/Filters/modInputFilter.php`) in the pull request #16302, does that fix the problem?

**Comment by nsuomine** [comment]
Yes, it fixed the problem. Thank you.

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/pull/16302
