### ISSUE TITLE
Unable to save TV when it is created if you accidentally selected a type with a required field

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#16314]
### Summary
For example, I need to create a TV with **textarea** input type.
textarea input type at the very bottom of the list with input types, and if I clicked/loaded another input type (accidentally or not) where there is a required field (for example, for "Listbox (Multi-Select)" is "Dropdown List Options"), then my TV with textarea input type cannot be saved - an error appears.

![tv-save-bug](https://user-images.githubusercontent.com/12523676/205103773-c8d856ee-e570-46c9-97ee-20d94e2dd4c1.gif)

Also, the tab with the error does not activate, although I think @smg6511 fixed it.

### Environment
MODX 3.0.3-dev

**Comment by smg6511** [comment]
@Ruslan-Aleev - Verified - I'll take a look at fixing that in the next couple days ...
