### ISSUE TITLE
php 8.2 deprecated dynamic property in xPDO

### ISSUE THREAD

**Issue by catsmeatman** [modxcms/revolution#16330]
## Bug report
Update php to 8.2.

Show many errors
Deprecated: Creation of dynamic property xPDOQuery_mysql::$xpdo is deprecated in /core/xpdo/xpdo.class.php on line 2804

### Step to reproduce
Update php to 8.2 and go to any modx page

### Environment
MODX 2.8.4, mysql 8.0.31, php 8.2 install from brew on MacOS.

**Comment by catsmeatman** [comment]
If add `public $xpdo;` in class /core/xpdo/xpdo.class.php:2783 all will be ok

**Comment by JoshuaLuckers** [comment]
Fixed in PR https://github.com/modxcms/xpdo/pull/241
