### ISSUE TITLE
Installer causes a fatal PHP error if package release is not found

### ISSUE THREAD

**Issue by nsuomine** [modxcms/revolution#16345]
### Summary
Installer causes a fatal PHP error if a package release is not found.

_Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in .../public_html/core/src/Revolution/Processors/Workspace/Packages/GetList.php:219__

This is because the returned value is "An error occurred while connecting to the Provider: No Package release found." which is not a countable array.

### Step to reproduce
If you have a package downloaded which does not exist anymore on the Provider and you open the Installer, the error is triggered.

### Observed behavior
Installer shows nothing.

### Expected behavior
Installer should ignore the missing package or show an error message.

### Environment
MODX3.0.2

**Comment by halftrainedharry** [comment]
Wasn't this fixed with the PR #16217?

Also, when I look at the code of the file `core/src/Revolution/Processors/Workspace/Packages/GetList.php` in MODX 3.0.2, there is not call to `count()` on line 219. Are you sure it's MODX 3.0.2?

**Comment by nsuomine** [comment]
Sorry, I was on 3.0.1 when I noticed the bug. Good to know it is fixed in 3.0.2. I removed the package so I didn't anymore notice that the problem disappeared in 3.0.2.

**Comment by modxcommunity** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/dashboard-error/7667/6
