### ISSUE TITLE
MODX 3.0.3 Changelog, Readme, License not visible when installing packages

### ISSUE THREAD

**Issue by halftrainedharry** [modxcms/revolution#16357]
### Summary
In MODX 3.0.3, when you install a package in the package manager, the information for _Changelog_, _Readme_ and _License_ is not visible.

Installing the same package in MODX 3.0.2 shows the information.

![Package Management MODX Revolution](https://user-images.githubusercontent.com/85392304/213663234-b759985f-c071-41a2-a228-1e94dc3f1179.png)

### Environment
MODX 3.0.3

**Comment by rthrash** [comment]
Can confirm the 3.0.3 behavior.

**Comment by JoshuaLuckers** [comment]
This is the error logged to the browser console:

```
[Error] TypeError: undefined is not an object (evaluating 'currentTab.id')
	beforetabchange (modx.tabs.js:39)
	fire (ext-all.js:21:3553)
	fireEvent (ext-all.js:21:674)
	setActiveTab (ext-all.js:21:397823)
	updatePanel (package.panels.js:154)
	processResult (package.grid.js:325)
	success (package.grid.js:309)
	handleResponse (ext-all.js:21:47772)
	f (ext-base.js:21:17846)
	m (ext-base.js:21:18304)
	(anonymous function) (ext-base.js:21:8610)
```

cc @smg6511
