### ISSUE TITLE
When editing a pugin, you can no longer go back to the first tab.

### ISSUE THREAD

**Issue by christoph-menzi** [modxcms/revolution#16362]
### Summary
![modx3bug](https://user-images.githubusercontent.com/109087392/213986360-3c8fc00c-d9a2-4c55-87db-36ef0fc5c07d.jpg)

### Step to reproduce
Edit any plugin under Elements. Go to the second tab and then back to the first.

### Observed behavior
The first tab can no longer be opened.

### Expected behavior
It should be possible to open the first tab again.

### Environment
MODX version 3.0.3. / Chrome (109.0.5414.75) / Windows 11

### Video
https://ttprivatenew.s3.amazonaws.com/pulse/visions/attachments/20863267/TinyTake23-01-2023-08-15-31.mp4

**Comment by Bruno17** [comment]
I can confirm that issue.  Seems that was indroduced with 3.0.3 
It worked for me on 3.0.2

**Comment by Bruno17** [comment]
I think, that issue was indroduced with #16089
