### ISSUE TITLE
MODX3: Graphical glitch with dropdowns over ExtJS grids in Safari

### ISSUE THREAD

**Issue by gadgetto** [modxcms/revolution#16373]
### Summary
MODX 3 has a graphical glitch with dropdowns over ExtJS grids in Safari. When the dropdown is closed, parts of the border remain visible.

Works fine in Opera and Chrome.

### Step to reproduce
- open a grid view (eg. Manage -> Users)
- click on the group filter dropdown
- close the dropdown

### Observed behavior
![2023-01-31 14-49-50 2023-01-31 14_51_16](https://user-images.githubusercontent.com/876737/215780893-4aa6ad33-8dbc-452a-b9cb-c75948667b58.gif)

### Environment
MODX 3.0.3-pl
Browser: Safari 16.2 (on MacOS Ventura 13.1)

**Comment by JoshuaLuckers** [comment]
I was able to reproduce this earlier as well, but I can't seem to reproduce it on Safari 16.3.

**Comment by gadgetto** [comment]
I'll upgrade to Ventura 13.2 and Safari 16.3 and post back...

**Comment by gadgetto** [comment]
Safari 16.3 fixes the glitch indeed - so it's a Safari problem and not MODX! I think ticket can be closed as it's an edge case.

**Comment by JoshuaLuckers** [comment]
Thanks for reporting and testing it in a newer version! I’m glad it was a Safari issue ;)
