### ISSUE TITLE
Edit modx plugin tab issue

### ISSUE THREAD

**Issue by eydolan** [modxcms/revolution#16382]
### Summary
js error in edit plugin

### Step to reproduce
click on any plugin, edit it, navigate the top tabs General Informaiton, System Events, Properties.
It freezes

Give error 
 Uncaught TypeError: this.getBottomToolbar() is undefined
    clearGridFilters XXX/assets/modext/modx.jsgrps-min.js?mv=303pl:39
    beforetabchange XXX/assets/modext/modx.jsgrps-min.js?mv=303pl:39

**Comment by Bruno17** [comment]
that should allready be solved with #16364

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to help make MODX better and report this issue. 
A pull request addressing this issue has been merged and will be part of the next release.
