### ISSUE TITLE
Form customization fails in MODX 3.0.3

### ISSUE THREAD

**Issue by tschifri** [modxcms/revolution#16389]
### Summary
If a region is deselected in a form customization profile, the profile fails in the resource.

### Step to reproduce
In a form customization profile, deselect e.g. description and introtext. Go to the regions and deselect e.g. modx-resource-access-permissions.

### Observed behavior
In the resource, the description and introtext are displayed incorrectly.

### Environment
MODX 3.0.3

![Bildschirmfoto 2023-02-14 um 10 10 32](https://user-images.githubusercontent.com/10501072/218690912-8d08dda7-bfcf-40c0-85b0-4a5c2a890fe6.png)
![Bildschirmfoto 2023-02-14 um 09 51 08](https://user-images.githubusercontent.com/10501072/218691008-eedf423f-737f-4eea-a039-8569d1380dec.png)

**Comment by smg6511** [comment]
This is fixed in #16360, which should be included in the next patch release.
