### ISSUE TITLE
Can't rename regions or fields in form customization

### ISSUE THREAD

**Issue by dev-willis** [modxcms/revolution#16390]
### Summary
Using form customization in MODX 3.0.3, setting new labels and titles isn't working; they continue to use the default value. 

### Step to reproduce
Edit a set for a profile under form customization and enter a value for a Label or Title field.

### Observed behavior
Fields and regions are not renamed. In the console is the following error:

```
modx.tabs.js?mv=303pl:39 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at MODx.Tabs.beforetabchange (modx.tabs.js?mv=303pl:39:32)
    at y.Event.fire (ext-all.js:21:3547)
    at MODx.Tabs.fireEvent (ext-all.js:21:668)
    at MODx.Tabs.setActiveTab (ext-all.js:21:397813)
    at MODx.hideRegion (modx.js?mv=ff230c00:539:26)
    at ?a=resource/update&id=6:116:6
    at ext-all.js:21:2529
    at a (ext-all.js:21:17726)
```

### Environment
MODX 3.0.3, PHP 8.1, hosted by MODX Cloud.

@smg6511 it was suggested I ping you

**Comment by Ibochkarev** [comment]
That should all ready be solved with https://github.com/modxcms/revolution/pull/16364

Thanks for taking time to help make MODX better and report this issue.
A pull request addressing this issue has been merged and will be part of the next release.

**Comment by smg6511** [comment]
#16360 more directly addresses this, but both are related. All will be cleared up with the next patch release.
