### ISSUE TITLE
Enable DKIM capabilities by default via settings

### ISSUE THREAD

**Issue by krisznet** [modxcms/revolution#16396]
### Summary
Native DKIM capabilities in modMailer would be very useful. The functionality is already there but can't be used by default or with an extension like FormIt.

### Why is it needed?
More and more companies moving to DKIM and also using 2-factor authentication for email accounts, so even secure SMTP is not an option for those. SPF record is often not enough to be able to deliver email reliably. 

### Suggested solution(s)
MODx uses PHPMailer which is capable of sending emails using DKIM, even modMail and modPHPMailer implementation are capable of using them. It can be used from a snippet but it can't be used with in-built functionality or with an extra like FormIt. So a simple solution would be adding those DKIM options to the settings and also modifying modMailer::getDefaultAttributes() function so it would utilise those settings.

**Comment by JoshuaLuckers** [comment]
@krisznet sounds like a good improvement! We encourage you to submit a pull request (PR) with your proposed changes. Your contribution would greatly help in resolving the issue efficiently.

If you need any assistance with the process, feel free to ask for help. We are happy to guide you through creating a PR.

**Comment by modxcommunity** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/formit-how-can-avoid-anti-spam-firewall/9040/2
