### ISSUE TITLE
After enabling the hidden time option a Date TV looses its value in MODX 3.x

### ISSUE THREAD

**Issue by Jako** [modxcms/revolution#16393]
### Summary
After enabling the hidden time option a Date TV looses its value in MODX 3.x.

&#x1F534; **IMPORTANT**: The issue occurs also after updating the site from MODX 2.x to MODX 3.x In MODX 2.x. the value was displayed and saved right. After updating to MODX 3.x the value is displayed AND saved wrong.

### Step to reproduce
Create a date TV and edit a resource with that TV. Set the time to some value different than 0:00. Enable the 'Hide Time Option' in the TV and edit the resource again.

### Observed behavior
The displayed date is set to 1.1.1970. The wrong value is saved, when the resource is saved.

### Expected behavior
Only the time part of the date should be removed and the date part should remain as it was previously entered.

### Environment
MODX 3.0.3

**Comment by halftrainedharry** [comment]
The error seems to happen here in the code:

https://github.com/modxcms/revolution/blob/c553c47bf25a6d21e1995648bf1b21664420ea76/manager/assets/modext/util/datetime.js#L528-L531

The `Date.parseDate` function returns `undefined` for the format = `Y-m-d 00:00:00` when there is a time in the value.

**Comment by Jako** [comment]
This can be fixed in the database with the following SQL query:

```
UPDATE `modx_site_tmplvar_contentvalues` SET value = CONCAT(SUBSTR(`value`, 1, 10), " 00:00:00")  WHERE `tmplvarid` IN (x,y,z);
```

x, y and z are the IDs of the TVs using the hidden time option.

**Comment by smg6511** [comment]
Not sure how this ever worked actually. The problem stems from the `hiddenFormatForTimeHidden` config property having an invalid value (currently, as @halftrainedharry pointed out, `Y-m-d 00:00:00`). The _format_ should actually be the same as the default one. The value, on the other hand, may or may not need to be taken into account when hiding the time. I can take a closer look and should be able to provide a fix over the next few days.

**Comment by Jako** [comment]
The values in a MODX installation upgraded from MODX 2.x have a not zero time for a lot of records. And it worked for a long time in MODX 2.x. Maybe the value is saved with a not zero time in MODX 2.x even when the time part is hidden leading to the initial issue.

**Comment by smg6511** [comment]
@JoshuaLuckers - Hey, before submitting a fix for this issue I wanted to get insight into the intent of your change from #15000. I think it was just to set the time to 00:00:00 for date TVs that hide their time component. Please confirm.

**Comment by JoshuaLuckers** [comment]
> I think it was just to set the time to 00:00:00 for date TVs that hide their time component. Please confirm.

@smg6511 affirmative!

**Comment by JoshuaLuckers** [comment]
@smg6511 Would the changes from PR #15773 also have an impact on this behavior?

**Comment by smg6511** [comment]
> @smg6511 Would the changes from PR #15773 also have an impact on this behavior?

I don't _think_ so. I looked through the blame for `datetime.js` first to see if I'd made a change that would have caused the bug. At any rate, I have a fix that applies the default time in a different way that is nice and simple. I'll submit that tonight.
