### ISSUE TITLE
Don't work tab in edit plugin

### ISSUE THREAD

**Issue by tolanych** [modxcms/revolution#16413]
### Summary
Don't work tab in edit plugin

### Step to reproduce
1. Go to "Edit plugin".
2. Switch to tab "System Edit"
3. Try switch to other tab
4. Error in console:
`Uncaught TypeError: Cannot read properties of undefined (reading 'changePage')  `

[Demo, console error and network answer in right panel](https://jam.dev/c/4f121c1f-7d3d-4e90-87dc-45eb262ec9ee)

### Observed behavior
In demo

### Expected behavior
Tabs switching should work

### Environment
MODX 3.0.3, PHP/7.2.34, apache

**Comment by Ibochkarev** [comment]
Fixed https://github.com/modxcms/revolution/issues/16362
