### ISSUE TITLE
TV Listbox when positioned in "modx-resource-main-left" does not contain selected attribut in option tag.

### ISSUE THREAD

**Issue by retoeller** [modxcms/revolution#16426]
### Summary
In MODX 2.8.4 the TV Listbox (Single-Select) when positioned in "modx-resource-main-left" through form customization does not contain <option **selected**> after re-opening the resource.
So the list always shows the first entry and not the one saved in the db.

<img width="436" alt="Bildschirmfoto 2023-05-03 um 09 33 40" src="https://user-images.githubusercontent.com/19552350/235856172-0dcad02f-39e1-4c83-a9c2-c6156a9c28ea.png">

The attribut "selected" is missing in the option-Tag.

### Observed behavior
After selecting an entry in the listbox, saving and then re-opening the resource, the selected entry is not active.

### Expected behavior
The Listbox should show the selected entry. HTML should contain <option **selected**>

### Environment
MODX 2.8.4

**Comment by halftrainedharry** [comment]
I can't reproduce this issue. All works correctly when I test it.

* Does the TV-value get saved to the database (check the table "modx_site_tmplvar_contentvalues")?
* Does the TV work correctly without the form customization?

**Comment by achterbahn** [comment]
I can't reproduce this neither. 
Tested on MODX 2.8.4 and MODX 2.8.6
