### ISSUE TITLE
Custom label for Content field doesn't work in MODX 3

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/revolution#16441]
### Summary
Adding a custom label for the Content field through form customization doesn't work.

### Step to reproduce
Create a form customization for a template and set the Label field for modx-resource-content to custom text.

### Observed behavior
When editing the resource, the content field is still labeled "Content" instead of the custom label.

### Expected behavior
The Content field should display the custom label set up through form customization.

### Environment
MODX 3.0.4-20230207.

**Comment by halftrainedharry** [comment]
It looks like the code in this function doesn't work correctly anymore in MODX 3 for the label of the content field.

https://github.com/modxcms/revolution/blob/aed303b64594fc5490067e3a4336e109671d48e0/manager/assets/modext/core/modx.js#L666-L688

Maybe adding

```js
if (containerId == 'modx-panel-resource' && fieldId == 'modx-resource-content') {
    container = Ext.getCmp(containerId);
    if (container) {
        container.setLabel('ta', newLabel);
    }
} else if (...) { ...
```

at the beginning of the `if` statement fixes the issue. But I'm not sure what exactly the rest of the function code does.
