### ISSUE TITLE
Can't see Manager Actions Log unless I'm a sudo user

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#16445]
### Summary
In MODX 3.0.3 if I attempt to access the Manager Actions Log, I get an "Access Denied: Not allowed to access this controller" error. I'm an admin super user with all permissions, including the `mgr_log_view` permission which is the only one required for the log.

If I make myself a sudo user, I can see the log as usual.

**Comment by halftrainedharry** [comment]
The code checks for the permission `logs`:

https://github.com/modxcms/revolution/blob/aed303b64594fc5490067e3a4336e109671d48e0/manager/controllers/default/system/logs/index.class.php#L24-L26

But this permission doesn't seem to exist.

**Comment by BobRay** [comment]
Ironically, I found this issue when updating LogLogins for MODX 3. It appears that MODX itself now logs logins. So, LogLogins is obsolete, but no one can read the log. ;)

**Comment by smg6511** [comment]
@BobRay - If you can review the posted PR addressing this issue it'll get fixed sooner than later ... nudge, nudge  ;-)
