### ISSUE TITLE
Naming a context root crashes the manager resource tree

### ISSUE THREAD

**Issue by travisbotello** [modxcms/revolution#16457]
### Summary
When adding a context with context key `root` it crashed the resource tree.

### Step to reproduce
Create a context with key `root`

### Observed behavior
It duplicates all existing contexts and formats them twice in the resource tree.

### Expected behavior
It should just add a context named root.

### Environment
MODX 2.8.5
![Screenshot_2023-07-19_at_15_00_59](https://github.com/modxcms/revolution/assets/1157380/ed91ab86-96ad-46fc-bb91-b5488ab88210)

**Comment by halftrainedharry** [comment]
As far as I can tell, the string "root" is the ID of the root node in the tree. This is hard-coded in the Ext.js component (`modx-tree`) and also in the PHP processor (`resource/getNodes`).

So when you try to load the content of your "root" context, it instead loads all the contexts again.

**Comment by smg6511** [comment]
Consensus on this matter is shaping up to be that the key "root" should be reserved. I'll work up a new PR that prevents users from attempting to use that key for a Context.
