### ISSUE TITLE
MODX Update dashboard widget shows unreleased software as an upgrade

### ISSUE THREAD

**Issue by rthrash** [modxcms/revolution#16466]
### Summary
The MODX update check Dashboard Widget shows 3.1.0-dev as an upgrade target

<img width="582" alt="Screenshot 2023-08-17 at 11 48 52 AM" src="https://github.com/modxcms/revolution/assets/234237/97f65cb2-8755-429d-b03a-14860e390760">

### Step to reproduce
Look at the Dashboard Widget

### Expected behavior
It should only show the next minor or patch release as an available upgrade.

### Environment
MODX Revo 3.0.x

**Comment by smg6511** [comment]
Yes, I've noticed this too. I started looking into it and the first question becomes whether this widget should _only_ show newer stable releases (pl)—i.e., is there a reason to allow betas and/or rcs to be included, perhaps switchable via system setting, as update options? Also, if there's a newer feature release that is more than one patch release ahead of the user's currently installed version, which release should the widget be recommending (e.g., the latest stable is 3.1.0 and the user has 3.0.4 installed; should it show 3.0.9 [assuming that's the final patch in the 3.0.x line] or 3.1.0)? 

The most straightforward and quick fix would be to only take the newest pl into account and show it if it's ahead of the user's current version. That would take care of showing a more proper status for the majority of installs. To really cover the bases though, the desired options and scenarios to cover would really need to be thought through.

I guess it's a question of purpose: Is it simply to show the very latest upgrade option or the most appropriate _next_ upgrade option? (I think it goes without saying that dev "releases" should not be shown.)

**Comment by halftrainedharry** [comment]
In my opinion, the first step would be to create a proper **API endpoint** to query released MODX versions.

Currently, this widget gets the data from the following XML file on Github (that always only contains the next version):

https://github.com/modxcms/revolution/blob/b47a3c619d9e2c39026eea1df3a035de1adf45f1/_build/build.xml#L23-L24

---

Such a new API could then also be used by the _UpgradeMODX_ extra.

Currently  _UpgradeMODX_ relies on the Github API to get the released versions, which quite regularly creates problems (API rate limit exceeded messages).

Here a quote from Bob from [this forum thread](https://community.modx.com/t/upgrademodx-fatal-error-and-no-backup-function/1695/3) (that's almost 4 years old):

> I was told quite a long time ago that [modx.com](http://modx.com/) would “soon” have an API for this, but AFAIK, it hasn’t happened, so UGM is still dependent on GitHub.

**Comment by smg6511** [comment]
> which quite regularly creates problems (API rate limit exceeded messages)

Are you seeing this on MODX backends or are you referring to an issue with the use of the Github API in general? 

I see that Bob gets around this issue by creating a cache file and only hitting the Github API at a certain interval to update that cache file. We can do that too if using their API to solve the widget issue at hand.

BTW, I use UpgradeMODX on most of my sites and have never had any issues with it in terms of the GH rate limit issue.

There's a desire to re-fashion the MODX backend with a REST API, but who knows when that'll happen given the low number of "hands on deck" capable of building such an API.

Anyway, @halftrainedharry - I'm curious what your opinion is on the questions I posed above re _what_ should show in the widget.

**Comment by halftrainedharry** [comment]
As someone not involved in the development of MODX, there are certain things that make me scratch my head.
There exists an API to check for every installed extra if there is an update available.
But then for MODX itself, we rely on a _build-script_ on github and the _tags_ that are available in the github repository! Why?

> BTW, I use UpgradeMODX on most of my sites and have never had any issues with it in terms of the GH rate limit issue.

I don't experience it myself. But as someone who closely monitors the MODX forum, it's a recurring issue. And an unnecessary one IMO.

> There's a desire to re-fashion the MODX backend with a REST API, but who knows when that'll happen given the low number of "hands on deck" capable of building such an API.

Nothing fancy is required here. It could even be a simple static JSON file that contains a list of released MODX versions, where someone adds a new line manually when a new version gets released.

> _what_ should show in the widget.

Keep it simple. Don't overthink it. Always show the the latest released version. No system settings necessary.

**Comment by opengeek** [comment]
> As someone not involved in the development of MODX, there are certain things that make me scratch my head. There exists an API to check for every installed extra if there is an update available. But then for MODX itself, we rely on a _build-script_ on github and the _tags_ that are available in the github repository! Why?

Because someone built the widget and it got integrated without proper discussion. We have an API that *could* be utilized to pull updates, but the other questions here need to be answered.

> > _what_ should show in the widget.
> 
> Keep it simple. Don't overthink it. Always show the the latest released version. No system settings necessary.

The latest released version could be 2.8.7. This needs to be clearly defined. System settings are not necessary, no. But, there a various other things to consider. Should it should the latest patch for the minor version someone currently has installed? Or should it look for the newest even if it is in a different minor, or even major version? We do not need to overthink it, but some specification needs to be decided on.

**Comment by smg6511** [comment]
Ok, good feedback @halftrainedharry - thank you! I'll reach out to Jason and Mark re alternatives they might see for implementing a releases list. FWIW, the reason I pose the question about _which_ release to show is that often times it's recommended to upgrade to the final patch version before moving to the next feature/minor version.

**Comment by halftrainedharry** [comment]
> often times it's recommended to upgrade to the final patch version before moving to the next feature/minor version.

@smg6511 I was told that this is unnecessary and the recommendation based on that one time years ago when an update wasn't implemented correctly.

See this post:
https://community.modx.com/t/update-from-2-8-4-to-3-0-2-property-sets-not-following-perfectly/6191/6

**Comment by rthrash** [comment]
I think 2.3.6 was the bad version that needed an Extra stop from earlier ones. 

Upon further reflection, I would lobby for showing the latest patch version and also any other minor and/or major versions, too, with the dates of the releases for reference. The "Status" header could become "Release" to be a bit more accurate. More bases would be covered.

```
MODX      [ 2.8.7 ] 15-Aug-2023      Update
MODX      [ 3.0.4 ] 25-Aug-2023      Update
```

**Comment by modxcommunity** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/upgrademodx-hide-dev-version/7051/4

**Comment by jaygilmore** [comment]
The aim/goal of this indicator being in Revo is to notify the Manager user(s) there is an available update for the software. IMO, it should indicate the latest available patch by major version. Perhaps @rthrash's [comment](https://github.com/modxcms/revolution/issues/16466#issuecomment-1688962634) is the most simple. 

The only thing I'd be concerned about is the next major version nagging you to upgrade if you know you don't want to and don't want to show what could be perceived as a broken state for other Manager users.

I could see logic in either a system setting to hide major versions or a toggle in the dashboard widget to display other major versions but I don't think it's necessary to solve this issue.

**Comment by jaygilmore** [comment]
This is only an issue in 3.x and therefore we only need an endpoint for 3.x (we could worry about how 4 works when we build it). 

As such, I think the endpoint should work similarly to what appears at https://modx.com/download which is the latest officially published version of the current mainline version of the software.  The evaluation is here: https://github.com/modxcms/revolution/blob/3.x/manager/controllers/default/dashboard/widget.updates.php

It appears that it's only checking two fields which is the modx.core.version (3.x.x) and the modx.core.release (pl/dev/rc). I'm not sure if we need anything more unless we want to add in the date of the release. It could be useful to add in other metadata in that endpoint for consumers, but that could be iterated on.

**Comment by rthrash** [comment]
@opengeek spitballing here, but here's a rough stab at starting to shape up a scope. While there is currently no upgrade widget for 2.x, it probably makes sense to future-proof this as a single endpoint.

The endpoint should return an array of the latest versions in each major release and the release date. Since no breaking changes happens in minor releases, and that will be the target for future bugfixes, I don't see a reason to keep up with those, too, if we're just talking about the version upgrades for the major branches. 

@Mark-H, @halftrainedharry and @smg6511 may have a differing opinions here.

It should be up to the Extra/Dashboard widget to determine which version is the right one to show as an upgrade. E.g., for 3.x, it would ignore any version starting with a "2". 

If someone were running 3.0.4 without updating for a while, and both a 3.1 (or another patch for that matter) and a 4.0 were released, it could show the current major version and the next one, similar to my ascii mockup above:

```
MODX      [ 3.1.0 ] 29-Nov-2023    Update
MODX      [ 4.0.0 ] 16-Jul-2024    Update
Extras    (11)                     Update
```

**Comment by wuuti** [comment]
The Updater Extra (not actively maintained any more) did it with the github tags, which worked very well - i don't really see a need for an extra backend endpoint for this, as this would actually involve manual work to get the release data in _or_ would just mirror the information already in the github repository. 

The extra added (quite too many) system settings allowing you to set up a notification strategy to your needs, e.g. only show major, minor, patch updates etc. (Upgrade modx has similar).
Typically, you would not want to somehow blindly install a major version, as this usually contains breaking changes according to semver, while a major version is acceptable - and patch versions are always fine. So a standard setting default would be "Show me minor+patch updates with fixes and new features"...

**Comment by smg6511** [comment]
Looping back around on this, I think what @rthrash suggests in his comment above makes sense. I'd maybe nuance it slightly by terming major releases an "Upgrade" while keeping minors and patches within the users current major version as "Update." Then, I'd consider interrupting the flow when a user selects an _Upgrade_ with a confirmation dialog noting that major upgrades may contain breaking changes and to proceed with caution. 

We can play around with fine-tuning the appearance in a PR, but first we're going to need the API to get going. @opengeek -I think you mentioned quite some time ago on Slack that something was in the works on this front. If so, what's its status?

**Comment by opengeek** [comment]
> Looping back around on this, I think what @rthrash suggests in his comment above makes sense. I'd maybe nuance it slightly by terming major releases an "Upgrade" while keeping minors and patches within the users current major version as "Update." Then, I'd consider interrupting the flow when a user selects an _Upgrade_ with a confirmation dialog noting that major upgrades may contain breaking changes and to proceed with caution.
> 
> We can play around with fine-tuning the appearance in a PR, but first we're going to need the API to get going. @opengeek -I think you mentioned quite some time ago on Slack that something was in the works on this front. If so, what's its status?

Nothing has been developed. It seemed that there was very little agreement on how this endpoint would work or if it was even needed. I'll be happy to put one into production if we can define the details of how it should work.

**Comment by smg6511** [comment]
@opengeek - Ok, yeah this one's gone quiet but definitely needs solving (we can't be having dev releases showing up in this widget). Also, this would provide @BobRay's UpgradeModx the ability to use the new API instead of the github tags/caching method the widget currently relies on. I'd say, unless you see a current or future reason for a consumer to fetch the entire releases list, the following would do the trick:

- Allow the passing of the user's current install (just the numbered version #.#.#, without pl, etc.)
- Based on the above, output a full list beginning with the next release based on the above. Note that the idea here is to allow the consumer (be it the core, an Extra, or other) to decide how extensive a list to output and how to format it.
- Only output -pl releases. The only users that generally have reason to play with a dev release are not end users; developers can figure out (if they don't know already) how to access dev, pre-releases, or others.
- The only data needed for output (thinking JSON) are:
-- Full release number #.#.#
-- Release date (I'd say unix timestamp here)
-- Release download URL

Does this sound sensible?

**Comment by opengeek** [comment]
I think it needs to send the full version string, including the release labels. This will still be running even when users have various pre-releases currently installed. The real issue is limiting it by specific major or minor releases, and when to do that.

**Comment by smg6511** [comment]
Good point on the pre-releases; I hadn't considered the scenario where you might have say a 3.0.5-beta where you'd want to see the 3.0.5-pl when released. 

I think thought, re limits, that there a two contexts here: What the API outputs (raw form) and what an display component outputs. I'm thinking the API should make no decisions other than the starting point based on the input.

**Comment by opengeek** [comment]
So just include all releases > the one sent and let the component work it out?

**Comment by smg6511** [comment]
Yeah, that's what I'm thinking. It would keep the API flexible and it can be debated on the component end how to handle the extent of data to display.

And, the more I think about it, perhaps the output should work similar to how the Extras do (if I remember correctly) where major, minor, patch, and release label are parsed out into separate data points.

**Comment by BobRay** [comment]
FWIW, the UpgradeMODX widget shows the latest version of the branch (2.x or 3.x) that matches the user's platform. It also has options for "pl-only" and "versions to show." These might be useful options for the API. That way people could opt to see dev versions, with the default being pl-only.

Also, I recently helped someone who skipped an x.0 version, had trouble, and solved it by going back and installing the .0 version. I think that issue still exists, though I can't remember if this was a MODX 2 or 3 issue.

**Comment by smg6511** [comment]
> These might be useful options for the API. That way people could opt to see dev versions, with the default being pl-only.

Hey Bob, agreed you want flexibility in what to show, but I'm thinking that's a task for the component consuming the API data and not the API itself.

**Comment by opengeek** [comment]
> Also, I recently helped someone who skipped an x.0 version, had trouble, and solved it by going back and installing the .0 version. I think that issue still exists, though I can't remember if this was a MODX 2 or 3 issue.

That is not an issue except in specific cases where it was identified as one. All upgrades SHOULD be safe to run directly.

**Comment by BobRay** [comment]
> That is not an issue except in specific cases where it was identified as one. All upgrades SHOULD be safe to run directly.

I know this is the theory, but I've seen enough cases where that didn't work to make me skeptical. I consider installing the .0 versions very cheap insurance.

**Comment by opengeek** [comment]
> > That is not an issue except in specific cases where it was identified as one. All upgrades SHOULD be safe to run directly.
> 
> I know this is the theory, but I've seen enough cases where that didn't work to make me skeptical. I consider installing the .0 versions very cheap insurance.

Can we please take this up elsewhere? That is not the point of this discussion.

**Comment by BobRay** [comment]
> Hey Bob, agreed you want flexibility in what to show, but I'm thinking that's a task for the component consuming the API data and not the API itself.

UGM already does this, so I don't feel strongly about it, but I think a boolean pl-only option should be pretty easy to implement in the API.

**Comment by opengeek** [comment]
FYI, I'm testing an endpoint that can be used for this purpose. It will return all releases with a version greater than the "current" version sent to the endpoint. It will accept a few optional parameters to filter the results:

- level: Can be major (default), minor, or patch. Major will include major, minor, and patch version upgrades. Minor will limit the results to minor and patch. Finally, patch will limit results to only patch version upgrades.
- prereleases: If set to a non-zero value, prereleases will be included in the results. Defaults to 0 (prereleases not included).
- variant: Can be 'Traditional' (default), 'Advanced,' or 'SDK.' Only one variant type can be included.

Here are some sample requests/responses…

```
GET /api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=2.7.0-pl HTTP/1.1

{
    "_links": {
        "self": {
            "href": "/api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=2.7.0-pl"
        }
    },
    "upgrades": {
        "3.0.3-pl": {
            "version": "MODX Revolution 3.0.3-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2023-01-17",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f720-43fb-a681-01cd0050bbe7/download/"
        },
        "3.0.2-pl": {
            "version": "MODX Revolution 3.0.2-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-11-16",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f511-411f-8167-bab91322ecdb/download/"
        },
        "3.0.1-pl": {
            "version": "MODX Revolution 3.0.1-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-04-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f305-4791-ba80-8f1c661aa2f5/download/"
        },
        "3.0.0-pl": {
            "version": "MODX Revolution 3.0.0-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-03-30",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-eebf-418b-a7c3-0b25cee90b8a/download/"
        },
        "2.8.5-pl": {
            "version": "MODX Revolution 2.8.5-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2023-03-07",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f924-4fe8-8f32-802dfd8ae38f/download/"
        },
        "2.8.4-pl": {
            "version": "MODX Revolution 2.8.4-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-04-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f0fd-4ab3-a524-33e05bbc4600/download/"
        },
        "2.8.3-pl": {
            "version": "MODX Revolution 2.8.3-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2021-05-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e8e8-4804-8091-667e73d79e69/download/"
        },
        "2.8.2-pl": {
            "version": "MODX Revolution 2.8.2-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2021-04-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e6c6-4a0f-b161-926762b164bd/download/"
        },
        "2.8.1-pl": {
            "version": "MODX Revolution 2.8.1-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-10-22",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e4b7-4b18-b45d-e0d858818cce/download/"
        },
        "2.8.0-pl": {
            "version": "MODX Revolution 2.8.0-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-10-06",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e2b5-46fb-9fc5-ffa063106bf3/download/"
        },
        "2.7.3-pl": {
            "version": "MODX Revolution 2.7.3-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-02-27",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e099-4d71-90ca-7a1137e38454/download/"
        },
        "2.7.2-pl": {
            "version": "MODX Revolution 2.7.2-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2019-09-26",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-dd16-4760-ae8e-947e58c5ab18/download/"
        },
        "2.7.1-pl": {
            "version": "MODX Revolution 2.7.1-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2019-02-14",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-dc37-41ce-9d9e-a979a48c9b7e/download/"
        }
    }
}
```

```
GET /api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=2.7.0-pl&level=minor HTTP/1.1

{
    "_links": {
        "self": {
            "href": "/api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=2.7.0-pl&level=minor"
        }
    },
    "upgrades": {
        "2.8.5-pl": {
            "version": "MODX Revolution 2.8.5-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2023-03-07",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f924-4fe8-8f32-802dfd8ae38f/download/"
        },
        "2.8.4-pl": {
            "version": "MODX Revolution 2.8.4-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-04-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f0fd-4ab3-a524-33e05bbc4600/download/"
        },
        "2.8.3-pl": {
            "version": "MODX Revolution 2.8.3-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2021-05-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e8e8-4804-8091-667e73d79e69/download/"
        },
        "2.8.2-pl": {
            "version": "MODX Revolution 2.8.2-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2021-04-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e6c6-4a0f-b161-926762b164bd/download/"
        },
        "2.8.1-pl": {
            "version": "MODX Revolution 2.8.1-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-10-22",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e4b7-4b18-b45d-e0d858818cce/download/"
        },
        "2.8.0-pl": {
            "version": "MODX Revolution 2.8.0-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-10-06",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e2b5-46fb-9fc5-ffa063106bf3/download/"
        },
        "2.7.3-pl": {
            "version": "MODX Revolution 2.7.3-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-02-27",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e099-4d71-90ca-7a1137e38454/download/"
        },
        "2.7.2-pl": {
            "version": "MODX Revolution 2.7.2-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2019-09-26",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-dd16-4760-ae8e-947e58c5ab18/download/"
        },
        "2.7.1-pl": {
            "version": "MODX Revolution 2.7.1-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2019-02-14",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-dc37-41ce-9d9e-a979a48c9b7e/download/"
        }
    }
}
```

```
GET /api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=2.7.0-pl&level=patch HTTP/1.1

{
    "_links": {
        "self": {
            "href": "/api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=2.7.0-pl&level=patch"
        }
    },
    "upgrades": {
        "2.7.3-pl": {
            "version": "MODX Revolution 2.7.3-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-02-27",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-e099-4d71-90ca-7a1137e38454/download/"
        },
        "2.7.2-pl": {
            "version": "MODX Revolution 2.7.2-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2019-09-26",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-dd16-4760-ae8e-947e58c5ab18/download/"
        },
        "2.7.1-pl": {
            "version": "MODX Revolution 2.7.1-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2019-02-14",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-dc37-41ce-9d9e-a979a48c9b7e/download/"
        }
    }
}
```

```
GET /api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=3.0.0-alpha1&prereleases=1 HTTP/1.1

{
    "_links": {
        "self": {
            "href": "/api/releases/products/997329d1-6f68-48d5-8e5e-5251adbb1f38/upgrades/?current=3.0.0-alpha1&prereleases=1"
        }
    },
    "upgrades": {
        "3.0.3-pl": {
            "version": "MODX Revolution 3.0.3-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2023-01-17",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f720-43fb-a681-01cd0050bbe7/download/"
        },
        "3.0.2-pl": {
            "version": "MODX Revolution 3.0.2-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-11-16",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f511-411f-8167-bab91322ecdb/download/"
        },
        "3.0.1-pl": {
            "version": "MODX Revolution 3.0.1-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-04-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-f305-4791-ba80-8f1c661aa2f5/download/"
        },
        "3.0.0-pl": {
            "version": "MODX Revolution 3.0.0-pl",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-03-30",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-eebf-418b-a7c3-0b25cee90b8a/download/"
        },
        "3.0.0-rc2": {
            "version": "MODX Revolution 3.0.0-rc2",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-02-03",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-ee10-4c99-b767-c8911e679acd/download/"
        },
        "3.0.0-rc1": {
            "version": "MODX Revolution 3.0.0-rc1",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2022-01-20",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-ed69-4cc2-a826-c039b6c4fef4/download/"
        },
        "3.0.0-beta2": {
            "version": "MODX Revolution 3.0.0-beta2",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2021-11-23",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-ecc3-4398-bf3b-ba413374dd1c/download/"
        },
        "3.0.0-beta1": {
            "version": "MODX Revolution 3.0.0-beta1",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2021-11-09",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-ec17-47ad-9a21-657bb83d9ff4/download/"
        },
        "3.0.0-alpha3": {
            "version": "MODX Revolution 3.0.0-alpha3",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2021-10-27",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-eb46-4944-b736-cb298e7b46f7/download/"
        },
        "3.0.0-alpha2": {
            "version": "MODX Revolution 3.0.0-alpha2",
            "distribution": "Standard",
            "variant": "Traditional",
            "released": "2020-01-28",
            "url": "https://domain.tld/api/releases/variants/99dd6d6e-dfee-4bf8-9b1b-c9ceb2e7f3fb/download/"
        }
    }
}
```

NOTE: Because the downloads need to be logged, the urls will log the download and return the actual download url to the client, and it will need to send the MODX uuid from the configuration.

**Comment by smg6511** [comment]
@opengeek  - this looks great, plenty of flexibility. Re the logging downloads: I'm hoping downloads can be made frictionless (_i.e._, a one-click process for the user), particularly if integrated by @BobRay's Upgrade MODX widget (which I'd actually love to see integrated as a core widget). How, generally speaking, would you see that being done? Or would the API already provide that desired behavior?

**Comment by BobRay** [comment]
FWIW, I would also like to see it integrated into the core. I don't think I have the knowledge (or the time) to do this, but if someone else is willing and will maintain it through future releases, I'm definitely in favor.

**Comment by opengeek** [comment]
> @opengeek - this looks great, plenty of flexibility. Re the logging downloads: I'm hoping downloads can be made frictionless (_i.e._, a one-click process for the user), particularly if integrated by @BobRay's Upgrade MODX widget (which I'd actually love to see integrated as a core widget). How, generally speaking, would you see that being done? Or would the API already provide that desired behavior?

There won't be any friction. The url provided in that API response would just return another response containing the S3 object URL. It's similar to how the extras downloads already work.

**Comment by smg6511** [comment]
Alright, let's run with it! Thanks for putting it together so quickly :-)

**Comment by smg6511** [comment]
@opengeek - Hey, just checking to see if the API is ready to work with or will be soon. I'll work on this issue once it is...

**Comment by smg6511** [comment]
K, folks, I'm at the point with the Dashboard Updates widget where: 
1. I've called the new API from the widget's controller (`widget.updates.php`) and retrieved a specific modx package's id (dlid [download id]) which, in turn, is made available to the Update link button itself in `updates.tpl`
2. On click of the Update button, `MODx.Ajax.request` calls a new `GetFile.php` processor to grab the actual `zip_url` where the package in question actually resides ... all good so far
3. `GetFile` then tries to hit that `zip_url` in a new request (with the intention of initiating a download from the browser). This is where I'm not sure how best to make this happen; it's not happening now, I'm guessing because other php output has already occurred. This is the bit of code making the request: 
```php
$client = $this->modx->services->get(\Psr\Http\Client\ClientInterface::class);
$factory = $this->modx->services->get(\Psr\Http\Message\RequestFactoryInterface::class);

$request = $factory->createRequest('GET', $fileData['zip_url'])
    ->withHeader('Accept', 'application/zip')
    ->withHeader('Content-Type', 'application/zip');
try {
    $response = $client->sendRequest($request);
} catch (\Psr\Http\Client\ClientExceptionInterface $e) {
    $this->modx->log(modX::LOG_LEVEL_ERROR, $e->getMessage());
    return $this->failure($e->getMessage());
}
``` 
Note that I can easily return the `zip_url` in the success response object, and use `window.location.assign()` in js to initiate the download, but that does make the download url technically exposed.

**Comment by opengeek** [comment]
> Note that I can easily return the zip_url in the success response object, and use window.location.assign() in js to initiate the download, but that does make the download url technically exposed.

Honestly, I have no issue with the url being exposed in that way. I just don't want it presented in the UI as a direct link.

**Comment by smg6511** [comment]
> I have no issue with the url being exposed in that way.

Ok, well that will simplify things! I'll be able to put up the Phase 1 PR in the next day or two...

**Comment by modxcommunity** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/modx-2-8-8-to-modx-3-0-5/8183/2
