### ISSUE TITLE
Tabs on the plugin edit page are not working correctly

### ISSUE THREAD

**Issue by OlegAnTo2000** [modxcms/revolution#16471]
### Summary
Tabs on the plugin edit page are not working correctly. I open the plugin edit page, go to the "System Events" tab, and then can't get back to the "General Information" and "Properties" tabs. I see an error in the browser console.

### Step to reproduce
Open the plugin edit page, go to the "System Events" tab and try opening the "General Information" or "Properties".

### Observed behavior
Tabs are not opening. An error appears in the browser console.
![Снимок экрана 2023-09-13 174409](https://github.com/modxcms/revolution/assets/143202406/dd942adf-5636-4ff3-bf8d-f8f002a5329b)

### Expected behavior
I think the right tabs should open.

### Environment
MODX Revolution 3.0.3-pl (advanced), clean without extras.
Coogle Chrome 116.0.5845.182 and Firefox 117.0
mysql 5.5.68-MariaDB, utf8mb4

**Comment by halftrainedharry** [comment]
I believe this issue was fix with the pull request #16364.
