### ISSUE TITLE
MODX3: Form Customization breaks when hiding region tabs

### ISSUE THREAD

**Issue by frischnetz** [modxcms/revolution#16480]
### Summary
After disabling (hiding) one of the regions that represent tabs in the resource view, form customization breaks and some parts of the resource editing page (e.g. relocated tvs) sare missing. The browser console shows this error:

![image](https://github.com/modxcms/revolution/assets/652014/8accde47-0163-4bf5-a7f7-9c1eaa103f23)

This is especially problematic when moving TVs AND hiding the `modx-panel-resource-tv`. They could be all hidden when the page breaks.

### Step to reproduce

In an active form customization profile for your testing resource, hide e.g. the introtext field. Additionally hide one of the following regions: `modx-resource-settings`, `modx-page-settings`, `modx-panel-resource-tv` or `modx-resource-access-permissions`

### Observed behavior
The introtext field is visible. The console shows errors.

### Expected behavior
The introtext-field should be hidden.

### Environment
MODX 3.0.3, 10.5.22-MariaDB-1:10.5.22+maria~ubu2004-log.

**Comment by halftrainedharry** [comment]
This could to be the same bug as in the issue #16399.
Can you apply the pull request #16401 and check if that fixes the issue?

**Comment by smg6511** [comment]
No, the error pointed out above is fixed by #16360.

**Comment by smg6511** [comment]
@frischnetz - I believe the newly-released 3.0.4 should take care of this. Can you verify once you've upgraded and close this if the problem is indeed fixed?

**Comment by frischnetz** [comment]
In my test cases, with 3.0.4 it works now as expected. So I close this. Thanks for all involved!
