### ISSUE TITLE
pthumb.class.php not compliant with php < 8.x (use 'mixed' type in member function)

### ISSUE THREAD

**Issue by intersel** [modxcms/revolution#16491]
### Summary
When looking at images in the media browser in the manager using php version < 8 (like 7.4.3), it generates the following error:

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to phpthumb::__set() must be an instance of mixed, bool given in xxxx/core/model/phpthumb/phpthumb.class.php

### Step to reproduce
open media browser and got to a directory where you have an image

### Observed behavior
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to phpthumb::__set() must be an instance of mixed, bool given

### Expected behavior
no php error... as server requirements on the modx website are about php:
Component 	Minimum Required 	Recommended for Production
PHP 	5.6.x 	7.4+

To solve the problem, it is needed to change line 317 in core/model/phpthumb/phpthumb.class.php

//public function __set(string $name, mixed $value): void {
	public function __set(string $name, $value): void {
	}

### Environment
MODX version, apache/nginx and version, mysql version, browser, etc. Any relevant information.
Modx V2.8.6, Apache/2.4.38 (Debian) PHP 7.4.33

**Comment by halftrainedharry** [comment]
Duplicate of #16468 and #16483.

See these issues or [this forum post](https://community.modx.com/t/modx-2-8-6-3-0-4-php-7-4-breaks-thumbnails-in-the-manager/7100) for a temporary fix.

**Comment by intersel** [comment]
Thanks and sorry for my duplicate issue. I did search but with the wrong keywords :s
