### ISSUE TITLE
Add an ability to change URL in manager of MODx Revolution 2.8

### ISSUE THREAD

**Issue by litosh-web** [modxcms/revolution#16501]
### Summary
When I want to run MODx Revolution 2.8 on subdomain (for example), but Preview button has old url, not a new one

### Why is it needed?
It`s for a React, SPA and so on.

### Suggested solution(s) 
I want to change preview URL and would change it in extras like Collections and so on. I`ve wrote some [ExtJS script for that,](https://litosh-web.ru/blog/modx/modx-next-js-react-problemyi-i-resheniya-chast-3) but would to know, is it can be solve by CMS?

### Related issue(s)/PR(s)
No

**Comment by halftrainedharry** [comment]
If I understand this issue correctly (and I'm not sure I do), then you access the manager via a subdomain -> `mgr.yourdomain.com`. But when you click the "View" button for a resource in the manager, you want to see the URL `yourdomain.com/yourpage.html` (without the `mgr.` subdomain).

I believe this should be possible (without a plugin), when you just define the setting `site_url` in the context (= `https://yourdomain.com/`.
By default, the setting `site_url` is extracted from the current request. But when you add a setting, then the value is fixed.

**Comment by litosh-web** [comment]
Yes, you're understood. I just tried and it works. Thank you [halftrainedharry](https://github.com/halftrainedharry). You`re completely right.
