### ISSUE TITLE
[Form Customization] Set information and fields not active if modx-page-settings region disabled

### ISSUE THREAD

**Issue by Spheerys** [modxcms/revolution#16528]
### Summary
There is a bug with Form Customization : the Set of information and fields are not active if modx-page-settings region is disabled.

### Step to reproduce
1. create new Set in Form Customization and activate it for resources
2. in "Set Information and Fields" tab, disable (for example) the description field 
3. inside Regions tab, disable the modx-page-settings region
4. edit a resource with the FC enable and see the result

### Observed behavior
The description field is still present when editing the resource.
If the modx-page-settings region is checked, the description field is correctly hidden as set in FC.

### Expected behavior
The description field should be hidden, even if the modx-page-settings region is disabled

### Environment
MODX version: 3.0.3-pl

**Comment by smg6511** [comment]
@Spheerys - I am not able to replicate this issue in the current release (3.0.5). If you are still seeing this behavior please report back and maybe post a screen recording showing the bug. Otherwise, I'll close this issue in the next week or so...

**Comment by Spheerys** [comment]
Effectively, the issue is not existing anymore with 3.0.5-pl \o/
