### ISSUE TITLE
Show username in menu

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#16525]
### Summary
Menu item labels, which are located in the "User Navigation" menu area, are hidden in the styles.
Don't know why this was done, but ok.

https://github.com/modxcms/revolution/blob/87a62645573bd3fcde291fc269db3efd987c4962/_build/templates/default/sass/_navbar.scss#L86

However, it is worth always displaying the username, because to find it out you have to click on the menu, which is not convenient, **it's just bad UX**. 

![user_1](https://github.com/modxcms/revolution/assets/12523676/90fbc2a8-53d4-4589-9854-4fbb9cf187fb)
![user_2](https://github.com/modxcms/revolution/assets/12523676/946cefcc-d5da-4c57-88e2-815bf352575f)

There was a discussion (https://github.com/modxcms/revolution/issues/15595) that long name in login may not fit, but we can add `word-wrap: break-word;` this will fix the problem. And it’s strange to add long names to login.

![user_3](https://github.com/modxcms/revolution/assets/12523676/d381fd38-777a-483e-b849-eb50bff2dd7a)

Another option is to add a title="" attribute with login to avatar, at least you don’t have to click user menu item. The UX will improve a little, but in my opinion it would be better to display the name in the menu.

![user_4](https://github.com/modxcms/revolution/assets/12523676/7a526bfe-cc65-4ebd-b2a6-15277da2fee0)

### Related issue(s)/PR(s)
https://github.com/modxcms/revolution/issues/15595

**Comment by rthrash** [comment]
I'd vote for both a tooltip and CSS break-word, personally. Good suggestions @Ruslan-Aleev. Thanks!

**Comment by smg6511** [comment]
Absolutely agree with @Ruslan-Aleev that it's better to have the username visible. However, I'm not crazy about how long names would appear if using break-word. For some, the convention is to create short names like `m3admin` (I've done this a lot too in the past), but for arguably many others it might be to use one's email address.

At the same time, ideally we require zero user interaction to see that username. What if we show it in the sidebar, but truncate it to fit? So short names like Ruslan's example would fully show, but long form usernames (such as an email) would display as, for example, `jim@mysi...` .
