### ISSUE TITLE
MODX 2.8.5 - Workspace not found - Packages are not installing locally

### ISSUE THREAD

**Issue by TheMightyTeo** [modxcms/revolution#16547]
### Summary
Nothing happens when I try to upload a package via Extras -> Installer. It copies the transport.zip file to the /core/packages directory, but package copied does not appear in the MODX interface. When I try to search locally for packages, an error occurs: 'Workspace not found'

### Step to reproduce
Do a fresh install of MODX 2.8.5-pl using MSSQL -> Try to upload a package -> See the error

### Observed behavior
No packages were added; they have been copied to the /core/packages; after 'Searching locally for packages' an error 'Workspace not found' occurs

### Expected behavior
I expect the package to be visible and installable after uploading it

### Environment
MODX version - 2.8.5-pl
Apache - 2.4-PHP_7.2-7.4+nginx_1.23
PHP version - 7.2 
MS SQL Server 2012

**Comment by TheMightyTeo** [comment]
What I have in the error log: 
![image](https://github.com/modxcms/revolution/assets/163724679/18527029-9731-44c3-abda-0c071639bf48)
1. Invalid syntax around 'group'
2. Out of range navchar -> datetime
3. Column was mentioned multiple times under 'order by'
Maybe those errors are relevant to my problem.

I also checked my MSSQL database: there are no rows in the 'modx_workspaces' table 
![image](https://github.com/modxcms/revolution/assets/163724679/b3d7d3d0-e0c9-482e-8169-a639960f9dcf)

**Comment by halftrainedharry** [comment]
> I also checked my MSSQL database: there are no rows in the 'modx_workspaces' table

Did you try adding the row manually?
(id = `1` | name = `Default MODX workspace` | path = `{core_path}` | active = `1`)

---

Also, I don't know how much MODX is used/tested with MSSQL.
I know that [support for sqlsrv was removed in MODX 3](https://docs.modx.com/3.x/en/getting-started/upgrading-to-3.0/sqlsrv).
So if possible, better use MySQL to be compatible with future versions of MODX.

**Comment by TheMightyTeo** [comment]
> > I also checked my MSSQL database: there are no rows in the 'modx_workspaces' table
> 
> Did you try adding the row manually? (id = `1` | name = `Default MODX workspace` | path = `{core_path}` | active = `1`)
> 
> Also, I don't know how much MODX is used/tested with MSSQL. I know that [support for sqlsrv was removed in MODX 3](https://docs.modx.com/3.x/en/getting-started/upgrading-to-3.0/sqlsrv). So if possible, better use MySQL to be compatible with future versions of MODX.

I've done that - no result. The error still exists. I've tried that couple of times, also tried to reinstall MODX. As a result, auto incremented column 'ID' has value of 6, which is...weird?
![image](https://github.com/modxcms/revolution/assets/163724679/d68821fb-bc45-416f-bb7f-ec464b6a327c)
I dont know how SQL attempts to create a row here, fails, but STILL makes 'ID' increase by one

**Comment by halftrainedharry** [comment]
I believe the ID should really be `1` to make it work.

https://github.com/modxcms/revolution/blob/1371d061520cb6f016d52220a6c2a6cd3787a46f/core/model/modx/processors/workspace/packages/scanlocal.class.php#L29-L34

On line 30, the workspace ID is set to the default of `1` (if there is not request parameter "workspace").
Then on line 32, the error message "Workspace not found." is returned, if no corresponding workspace is found in the database.

**Comment by TheMightyTeo** [comment]
> I believe the ID should really be `1` to make it work.
> 
> https://github.com/modxcms/revolution/blob/1371d061520cb6f016d52220a6c2a6cd3787a46f/core/model/modx/processors/workspace/packages/scanlocal.class.php#L29-L34
> 
> On line 30, the workspace ID is set to the default of `1` (if there is not request parameter "workspace"). Then on line 32, the error message "Workspace not found." is returned, if no corresponding workspace is found in the database.

Well, that problem is solved, thank you! `DBCC CHECKIDENT (mytable, RESEED, 0)` helped me to reset ID column to 1 and 'Workspace not found' error is gone now. 
But, sadly, MODX doesn't see my uploaded packages. For every package uploaded I get a MSSQL error, related to 'value is out of range when converting navchar to datetime'. Any ideas?
![image](https://github.com/modxcms/revolution/assets/163724679/3245986d-9365-486b-b202-b6d19d251ac1)

**Comment by halftrainedharry** [comment]
> For every package uploaded I get a MSSQL error, related to 'value is out of range when converting navchar to datetime'. Any ideas?

Unfortunately I have no MSSQL server to test this. It seems that the format of the "created" time column is wrong for MSSQL.
Maybe try to find out the correct format for MSSQL (so that the value can successfully be converted from `string` to `datetime`).

**Comment by TheMightyTeo** [comment]
> > For every package uploaded I get a MSSQL error, related to 'value is out of range when converting navchar to datetime'. Any ideas?
> 
> Unfortunately I have no MSSQL server to test this. It seems that the format of the "created" time column is wrong for MSSQL. Maybe try to find out the correct format for MSSQL (so that the value can successfully be converted from `string` to `datetime`).

I've found the solution. Default language of my DB was set to russian. As far as I understand, it has date format dd/mm/yyyy. Every time MODX inserts date/time in SQL, it has yyyy/mm/dd format. Changing DBs default language to english fixed this problem for me. 
@halftrainedharry thank you kindly for your help!
