### ISSUE TITLE
[2.x] Dynamic property modConnectorResponse::$response PHP8

### ISSUE THREAD

**Issue by webinmd** [modxcms/revolution#16566]
### Summary

Deprecated: Creation of dynamic property modConnectorResponse::$response is deprecated in /public_html/core/model/modx/modconnectorresponse.class.php on line 145 

### Step to reproduce
Any code in the component modalConsole

Can be fixed if declared  $response in core/model/modx/modconnectorresponse.class.php 

### Environment
MODX 2.8.7, PHP 8.2

**Comment by halftrainedharry** [comment]
There already exists a pull request to fix this: #16563
