### ISSUE TITLE
The asterisk is missing in the TV header for required fields

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#16593]
### Summary
As far as I remember, TV, which are required, had an asterisk (*) in name in resource form.
After some version MODX the asterisk disappeared, which is not convenient.

![tv_r_2](https://github.com/user-attachments/assets/3f57268f-7b80-4012-badc-2e5c221e6cc2)

### Expected behavior
The asterisk must be in the TV name

### Environment
MODX 2.8.7

**Comment by smg6511** [comment]
Yup, I see this too. Note that it's not missing in 3.x.

**Comment by halftrainedharry** [comment]
PR #14522 added the asterisk to required fields in MODX 3.x.
It's likely that this feature never existed in MODX 2.x.

**Comment by Ruslan-Aleev** [comment]
It's strange, it seemed to me that it always worked like that.
