### ISSUE TITLE
Why is sorting needed in resource tree?

### ISSUE THREAD

**Issue by Ruslan-Aleev** [modxcms/revolution#16603]
### Summary
If a resource has child resources, then the context menu will have a sorting option (see screenshot), BUT sorting only affects the display of resources in the admin panel, as I understand it.

![tree_sort](https://github.com/user-attachments/assets/a77ef828-9ed0-4349-96bb-8ecff419d4c6)

_Why is sorting needed in resource tree?_

It would be convenient if the **sorting could be saved for the site as well**.
Or it would make sense to somehow rename the item, like "display in tree".

p.s. Or I didn't understand what this menu item is for.

**Comment by smg6511** [comment]
I'd agree in most cases that the sorting has limited use, particularly on smaller sites. I don't use it much. But a use-case I can think of is a news site or any type of site that would have folders containing a long list of Resources: In that scenario, it might be useful to change the sorting to more easily find a particular Resource to work on. 

Of course, it depends on one's style of searching for things: If a user tends to look for items primarily via the tree, the sorting _can_ be helpful. Personally I use the search bar a lot for larger sites; it's quite effective at finding whatever you need. Or I use the Collections Extra to organize larger related sets of documents.

**Comment by smg6511** [comment]
@Ruslan-Aleev - Are you ok with closing this request, or is there more to discuss?
