### ISSUE TITLE
ACL User Group UI not grouping users per role

### ISSUE THREAD

**Issue by smaddock** [modxcms/revolution#16664]
### Summary
The user groups displayed at `manager/?a=security/permission` have individual accordions (`x-grid-group`) for each user, even if users share roles with one another. Within a given user group, there should only be one accordion for each unique role, with all applicable users appearing in that accordion.

### Step to reproduce
Create a user group
Add at least two users to the user group with the same role
Navigate to `manager/?a=security/permission` and select the user group from the list

### Observed behavior
![Screenshot 2024-12-12 at 9 08 20 PM](https://github.com/user-attachments/assets/4c6f44be-5c13-49ea-8a4c-2117293915cd)

### Expected behavior
Users visually grouped in a single accordion for each role, so for the example in the screenshot, having an accordion with the title "Role: Member - 9999 (**4 Users**)" with the for users within that accordion.

### Environment
MODX 3.0.6-pl (traditional)
PHP-FPM 8.3.14
Apache 2.4.62
MySQL server 8.0.30
MySQL PDO client mysqlnd 8.3.14
Firefox 133

**Comment by smg6511** [comment]
@smaddock Thanks for your post! This is fixed in our 3.1.0-dev branch, which I imagine will be coming up for a -pl release in the first half of 2025 (_see_ #16529). It's quite a complex update, so hot-fixing isn't really an option ;-)

**Comment by smaddock** [comment]
Gah… I tried searching for an open issue, but missed it. Feel free to close this as a duplicate then. Thanks!

**Comment by smg6511** [comment]
@smaddock It's all good! There never was an issue posted to my knowledge (which is why a search specifically for an issue on the matter may not have yielded a result). Being the author of the PR that fixes the grouping issue, I happened to stumble upon the problem while working on something else a while ago.
