### ISSUE TITLE
Ask before restoring deleted properties in "Revert All to Default."

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#1850]
bobray created Redmine issue ID 1850

Custom property sets will often be much smaller than the full list of default properties. Users would probably assume that "revert all" would just revert their existing properties in the custom set. That should probably be the default, but with a checkbox for "Restore missing default properties" that would do what it does now.

**Comment by OptimusCrime** [comment]
No interest seen in 8 years. Closing this. Feel free to comment or reopen.

@modxbot close
