### ISSUE TITLE
Remove County And State Information from users and replace with ID from standardized lookup tables

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#2105]
wshawn created Redmine issue ID 2105

After the forth website (in as many months) needing these look ups, I have found public domain / gnu released cvs files and converted them to mysql containing: countries (released by http://www.iso.org/iso )
&#8211; containing 2 letter designation, 3 letter designation, iso numbers, country names (all caps), country name Camel Cased
&#8211; released annually and can be updated by core developers by running a perl script I also have, which will create the database for you on the fly and pull new list from them all in 30 seconds or less
&#8211; usage &#8211; replace web sign up form asking for county with a call to a snippet in the appropriate section, which creates the option select combination pulled from the standardized ISO list and / or provide a look up table for developers to cater content based on county
&#8211; provides a snippet for developers to use in their own projects
&#8211; a simple Perl script I have will pull the ISO list from the iso site and create the table on the fly in a few seconds thereby removing the need for developers to update the list or manage the sign up or other respected code
&#8211; currently modx has 239 counties listed in it and there are 244 zipcodes
&#8211; containing two letter state abbreviation
&#8211; counties
&#8211; this would allow us to only have to obtain the users zip code while allowing us access to their city, state, county, without having to store it in the database
&#8211; a simple left join in a query can combine the data as needed based on modx.zipcode = lookupZipCodes.zip
&#8211; usage &#8211; lower storage overhead, standardize user input by either removing the need for typing or simply verify a 5 digit number against the database (easy enough with a simple Ajax or JavaScript call) states
&#8211; Simple cross reference two letter abbreviation to state names (removes end users typing : fl, FL, FLORIDA, Florida, or even Floorida or Floriduh)
&#8211; mostly display continuity by removing direct user input (drop down instead) If developers think this is worth pursuing I can create the mysql tables: modx_lookup_countries, modx_lookup_zipcodes, modx_lookup_states
and the snippets to pull the look ups for states and countries. A possible snippet for zip code to verify what is typed is actually in the postal system may also be produced. Overhead: All three tables bzip into 545k of sql export file containing data and structure. Estimate is based on importing the tables (5 secs)
Writing the snippets
Changing the sign up in websignup.inc.php (will have to find the equivalent in revolution dumping a local server to install it locally)

**Comment by goldsky** [comment]
vote to close this

**Comment by OptimusCrime** [comment]
+1

**Comment by wshawn** [comment]
This is issue is seven years old. I have in fact created a third party lookup system, which works fine for many of my clients. Due to the type of data being provided I would have to decided where to draw the line for a public release of any sort.

I would also suggest closing this.

I would also suggest going through issues attached to my name and look for more to close, as I have contributed over 300 bug reports and feature requests - many of which are now quite old and should have been closed or dealt with years ago if they are indeed still open.

**Comment by Mark-H** [comment]
Shawn could you help with  validating those issues you've opened in the past? Looks like there's 39 remaining open issues from your account: https://github.com/modxcms/revolution/issues/created_by/wshawn there may be more under the modxbot user from the migration.

If you could close them or add a comment saying they're still accurate in the current release, that would greatly help bring order in the chaos. Thanks!

**Comment by wshawn** [comment]
I knocked out 23 of them.  Only a handful remain unaddressed.
