### ISSUE TITLE
Reports System Info addition

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#2508]
wshawn created Redmine issue ID 2508

Can a section be dedicated to provide Environment Variables (including browser) for the purpose of greatly simplifying a "cut and paste" of our "Environments" in bug tickets / forums/ irc/ etc.?  

Essentially, create a menu option which contains the predominate information developers need to troubleshoot in a simple copy past scenario.

I also wouldn't mind the ability to add that environment to my profile on Redmine somewhere, so it auto fills the Environment box.

**Comment by rtripault** [comment]
I am closing this one as "duplicate" of #2516.

Also, a PR has been sent (#12261) to allow copy/paste of the system information.
