### ISSUE TITLE
Moving text TVs to another tab makes them appear shifted down

### ISSUE THREAD

**Issue by dae** [modxcms/revolution#2650]
dae created Redmine issue ID 2650

Steps to reproduce:
# Make a text TV.
# Go to "Form Customization", create a new rule:
*Action:* core - resource/update
*Name:* modx-resource-settings
*Rule:* Move TV to Tab
*Value:* tvID, where ID is the ID of a newly created TV.
# Open any resource (page) for editing.
# If your browser is maximized, narrow the window.

The TV field will appear a little below the caption (as depicted in the screenshot).

This is actually an annoying problem because as a Mac user I don't have a habit to maximize windows.

**Comment by amdbuilder** [comment]
I would also suggest closing this issue, unless someone else can confirm it.

**Comment by adamwintle** [comment]
This seems to be fixed

**Comment by OptimusCrime** [comment]
@modxbot close
