### ISSUE TITLE
Add Element list to Reports Menu

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#2713]
wshawn created Redmine issue ID 2713

Provide a printable list of elements in the reports menu, allow filtering by category, group (document / user), ACL, and type.
This could prove handy for accountability and reporting.

Default display should simply show all elements (viewable by current manager user) alphabetically separated by type.
Created by and Created On should be toggles.

h1. Element Type 
*Element Name*  (created by) (created on)
 _Description_

**Comment by OptimusCrime** [comment]
-1 for this idea. Having functionality to print all the elements on a site is not something I think should be added to the core. This can be done by an extra is you for some reason would like to see those features.

Anyone else?

**Comment by pixelchutes** [comment]
I have thought about this idea as well, something similar *(but improved)* to the MODX Evo Elements "Combined View." I think the list could also allow quick linking to editing the Elements in question, etc.

That said, I totally agree...this would be a perfect candidate for an Extra for anyone looking for this additional behavior.

**Comment by wshawn** [comment]
When I suggested this, there was no real point to the Categories link in the element menu. I thought it would be nice to be able to see all of the components in a category without having to open almost a half-a-dozen types and then the category folders.

Yes an extra / add-on would be better.
