### ISSUE TITLE
Require and force a back-end user to change password first

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#2748]
bertoost created Redmine issue ID 2748

This one should be very cool. We always create a customer-account and we have a simple password for that user. It will be very nice if we could say that the user needs to change the password at first when logging in. Untill they don't do it, the manager is blocked for that user.

If this one exists; I can't find it.

**Comment by amdbuilder** [comment]
I'm going to suggest closing this issue considering there is a package to add the functionality if required.

**Comment by christianseel** [comment]
@modxbot close
