### ISSUE TITLE
Replace MagpieRSS with SimplePIe

### ISSUE THREAD

**Issue by freelancewebdev** [modxcms/revolution#2797]
freelancewebdev created Redmine issue ID 2797

I would suggest that MagpieRSS is replaced with Simplepie for the following reasons as described on the Simplepie website:

SimplePie is being actively developed.
The most recent development release of MagpieRSS was 2.0-alpha-alpha-alpha back in October 2006. The last stable release was in November 2005.
SimplePie doesn't require you to understand the XML guts.
MagpieRSS offers you ONLY a data array based on the guts.
SimplePie fully supports AND normalizes all documented versions of RSS, and all popular versions of Atom.
MagpieRSS has very limited Atom support, and doesn't do much normalizing.
SimplePie can correctly parse Tim Bray's Atom 1.0 feed.
MagpieRSS doesn't come close.
SimplePie has a well-trafficked support forum, public SVN repository, and a TON of unit tests.
Does ANYONE know what's going on with MagpieRSS?
SimplePie sanitizes the content of the feed to ensure safety against malicious feeds.
MagpieRSS doesn't implement any kind of data sanitization.
SimplePie has a less restrictive license than MagpieRSS.
MagpieRSS is licensed under the GPL which is more restrictive than SimplePie's BSD licensing.
SimplePie is contained in a single file for easier portability.
MagpieRSS comes in 4 separate files making it harder to move around without issues.
SimplePie supports the detection and embedding of audio and video podcasts including the popular Media RSS and iTunes RSS elements.
MagpieRSS has no explicit enclosure support.

**Comment by amdbuilder** [comment]
This issue is still valid as 2.3.3 still references it.

**Comment by hugopeek** [comment]
Looking into this today for #modxbughunt.

Learned from @goldsky that the news feeds in MODX are indeed still using Magpie. My question is: although MagpieRSS is not being actively developed anymore, does it still work without issues? Also in PHP7?

This seems to be related to #13209 also. As @Mark-H mentioned there already: maybe it's time to switch to a completely different library with MODX3.

**Comment by gpsietzema** [comment]
This isn't relevant anymore t.b.h. It still works. I think we should close it until it poses problems. It still works in PHP7.

@modxbot close

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @gpsietzema

**Comment by freelancewebdev** [comment]
Just looking at this from the perspective of the library still functioning seems a bit odd to me - what about security?

**Comment by OptimusCrime** [comment]
@freelancewebdev Are there any security concerns with this package? I am pretty sure this package will be changed in 3.x with composer.

**Comment by freelancewebdev** [comment]
Not that I am aware but that is kind of my point - if the package is not
maintained, where would any vulnerabilities be reported? How would anyone
be aware?

If the issue is closed then it's closed - just clarifying the full reason I
initially raised this.



Kind regards,

Joe Molloy

F R E E L A N C E  W E B  D E V E L O P E R

-----------------------------------------------------------------------------------
C O N T A C T  D E T A I L S
-----------------------------------------------------------------------------------
Mobile:                  +353 86 6087493
Landline:                +353 1 8348780
Web:                      hyper-typer.com

C o n n e c t i o n s
-----------------------------------------------------------------------------------
Twitter:                   twitter.com/FreelanceWebDev
Facebook:               fb.me/FreelanceWebDeveloperIreland
Google Plus:           gplus.to/FreelanceWebDev
Skype:                    FreelanceWebDev
RSS:                      hyper-typer.com/latestnews.rss
-----------------------------------------------------------------------------------
