### ISSUE TITLE
Allow unescaped backticks

### ISSUE THREAD

**Issue by rickj** [modxcms/revolution#2805]
rickj created Redmine issue ID 2805

I have a very specific question to do with the modxParser class and backticks. 

Backticks within a tag's property values must be escaped with another backtick. This is true if the backtick is visibly within a property like this:

<pre>
// Example #1
[[$mychunk? &prop_name=`property `` value`]]
</pre>

Also true for backticks within any content called by a nested tag within a property value:

<pre>
// Example #2
[[$mychunk? &prop_name=`property [[$backtick_chunk]] value`]]
// Where backtick_chunk looks like this:
escaped backtick example: ``
</pre>

I noticed that the parser expands the properties (evaluates all nested tags within a tag) before parsing out all the properties:

<pre>
// In modParser::processTag()
$this->processElementTags($outerTag, $innerTag, true);
$outerTag= '[[' . $innerTag . ']]';
</pre>

However, later the parser extracts the property values, then checks for and evaluates any nested tags again. If I remove the 2 lines above, I can have unescaped backticks in included content (the backticks within backtick_chunk of example 2 above wouldn't need to be escaped).

So here is my question: couldn't the parser skip the evaluation of nested within properties on the first go? 

I'm almost positive there is a good reason why nested tags are expanded before properties are parsed, but I just can't figure it out. Thanks for reading.

**Comment by gpsietzema** [comment]
Seeing no-one has shown interest in finishing this, I'm proposing to close this one. If you feel this is wrong, feel free to re-open it.

@modxbot close
