### ISSUE TITLE
Provide the ability to import / export categories

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#2832]
wshawn created Redmine issue ID 2832

This may be a consideration for packman, but I feel we should have a new addition to the tools menu which allows us to import/export property sets and categories directly.

**Comment by OptimusCrime** [comment]
-1 for this. The idea does not add anything that would be used in a single Modx installation, which the Modx Core should focus on. Additional feature like this (for development/prod) should be added by extras.

**Comment by wshawn** [comment]
I Agree. It would probably be better for an extra.  Five years late, but you are probably correct.

**Comment by OptimusCrime** [comment]
Working on cleaning up the issues here, @wshawn ;)
