### ISSUE TITLE
Provide more debug information on upgrade and advanced upgrade

### ISSUE THREAD

**Issue by Paprikas** [modxcms/revolution#2913]
paprikas created Redmine issue ID 2913

When I tried to move my Revo site to new hosting, I noticed that you don't get any debug info during upgrade or advanced upgrade. (I always use setup when migrating)
Installer thinks that I don't need any info, because its not fresh install, and that means we don't need to show any info.

After few hours of searching, I found a problem. Of course after I tried fresh install, and he point me to wrong pdo mysql socket path. (mysql and mysqli was correct)

Upgrade and advanced upgrade didn't tell anything. Need to fix it.

**Comment by gpsietzema** [comment]
In that case, closing unless it appears again.

@modxbot close

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @gpsietzema
