### ISSUE TITLE
snippet calls allowed to be case-insensitive

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#2919]
netprophet created Redmine issue ID 2919

Given a Snippet named "Foo", we are able to run it via [[Foo?]] as well as [[foo?]]
This is caused by db collation when the Snippet is looked up by name.

**Comment by whitebyte** [comment]
If this is not a bug, it should be closed, or some definite decision should be made. I agree with @Alroniks that changing this behavior will break a lot of existing code, but maybe this question should be discussed for upcoming 3.x?

**Comment by rtripault** [comment]
This indeed depends on the table collation. So gonna close this one.

Feel free to comment/reopen if needed.
Thanks
