### ISSUE TITLE
Add Clear Cache button in Clear Cache Modal Window

### ISSUE THREAD

**Issue by devtrench** [modxcms/revolution#2937]
devtrench created Redmine issue ID 2937

It would be nice to have a clear cache button in the clear cache modal window.  See image.

**Comment by christianseel** [comment]
I'd agree to the others - the "clear cache modal" is actually just the MODX console and not a specific modal where a "clear cache" button would make sense.

So I'd close this. Please reopen or comment if you have a different opinion.

@modxbot close
