### ISSUE TITLE
Timezones for publish/unpublish

### ISSUE THREAD

**Issue by leoandrews** [modxcms/revolution#3089]
leoandrews created Redmine issue ID 3089

It would be useful, when setting the time of day for a publish/unpublish field, if we could either select the timezone or have it auto detect. Ideally there should be an *easy to find* system setting which lets you set the timezone for your entire site in one place. "server_offset_time" might have been an effort in the right direction but it doesn't really cut it because that value will change during daylight savings time. Additionally different parts of the world start and end DST at different times.

Personally I think it'd be good if, out of the box, everything was anchored to GMT.

**Comment by rtripault** [comment]
Since Revo 2.2, a `locale` setting is available, which should take care of the issue described, so closing.

Feel free to comment/reopen if needed.
Thanks
