### ISSUE TITLE
Normalize resource field lexicon strings

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#3140]
bobray created Redmine issue ID 3140

If all the resource field lexicon strings took the form resource__fieldname_ and resource__fieldname__help, they could be generated by rule in prompts and error messages.

Almost all of them are already in that form. I think these are the only anomalies:

pub_date
unpub_date
hidemenu
isfolder

**Comment by Mark-H** [comment]
Many of the missing lexicons are old and not exposed anywhere. Others are definitely in place today. Closing, feel free to reopen for remaining issues.
