### ISSUE TITLE
Using resource/create, user can assign a doc to a group he or she doesn't have access to.

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#3202]
bobray created Redmine issue ID 3202

I'm not sure if this qualifies as a bug or even a desired sanity check, but you can't do it in the Manager and maybe you shouldn't be able to do it in the front end.

To reproduce:
-  Create a Resource Group called Private.
-  Attach the resource group to a user group the admin is not a member of with two Resource Group Access ACL entries for both web and mgr.
-  Have the Admin user run code in the front-end that assigns a new doc to the Private group and calls resource/create.

The doc is invisible to the admin in the Manager, but is created and attached to the Private group.

If it's worth fixing, the processor could check, but it would also be nice if the protected resource group didn't show up in get*() methods for resource groups and templateVarTemplates.

**Comment by OptimusCrime** [comment]
If this is done programmatically using `$modx->runProcessor` it should ignore permissions like it does today. Did I understand the issue correctly?

**Comment by BobRay** [comment]
I'm not sure I understand your question, but AFAIK, processors do check permissions when using runProcessor() unless you're in cli mode.

**Comment by pixelchutes** [comment]
To confirm, the Admin user in question does not have `sudo`, correct?

**Comment by Mark-H** [comment]
I don't understand the issue. "You can't do it" sounds like this is not an issue unless you write code to avoid it, so closing.
