### ISSUE TITLE
Resource auto-save

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#3382]
jrotering created Redmine issue ID 3382

I've had a few frustrated users report losing content changes because they've forgot to save over an extended period of editing a resource.  One possible remedy to this would be to have an auto-save feature that could be controlled by a system setting.  Maybe an on/off setting and also a time increment setting.

**Comment by whitebyte** [comment]
Since in relation to this issue was an alternative solution, this one should be closed maybe?

**Comment by OptimusCrime** [comment]
The conclusion from the pull was that this is not something we need to implemented. I suggest closing this.

**Comment by rtripault** [comment]
OK, closing.

As always, feel free to comment/reopen if needed.

Thanks everyone
