### ISSUE TITLE
Anonymous context permissions and unauthorized page/error page behaviour

### ISSUE THREAD

**Issue by lossendae** [modxcms/revolution#3387]
lossendae created Redmine issue ID 3387

I've protected some documents and want the (anonymous) user who try to access it to view the 403 page instead of the 404.

I've assigned to the (anonymous) user group a Resource Group Access with:

<pre>
Resource group => My resource group name
Role => 9999
Acess Policy => load Only
Context => my_context
</pre>

and Context access:

<pre>
Context => my_context
Minimum => 9999
Access Policy => Load Only
</pre>

But (anonymous)  ofusers are still redirected to the 404 page instead the unauthorized one.

**Comment by rtripault** [comment]
This is the intended behavior (see [documentation](http://rtfm.modx.com/revolution/2.x/administering-your-site/security/security-tutorials/making-member-only-pages#MakingMember-OnlyPages-3.AddUserstotheUserGroup)).

So closing.

Feel free to comment/reopen if needed.
Thanks
