### ISSUE TITLE
Modx Browser: change sort by button to text

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3418]
onepack created Redmine issue ID 3418

The Sort by button in the Modx Browser doesn't do/ sort anything when clicked.
When the page loads with sorting option "name" as the default value and you decide to click this button to actually sort the list by name. (this doesn't work upon page load. bug: 3417) nothing happens.
You see the button move but the list stays the same.

**Comment by whitebyte** [comment]
This issue seems to bre resolved a long ago, sortby in media browser works as expected in 2.3.2 and older 2.2.14. Suggest closing.

**Comment by rtripault** [comment]
Indeed, so closing.

Feel free to comment/reopen if needed.
Thanks
