### ISSUE TITLE
Modx Browser Sorting by name: capitals before lowercase??

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3419]
onepack created Redmine issue ID 3419

I have some files in the Modx Browser and couldn't find a file I just uploaded. I decided to sort by name and still could not find the file untill I scrolled all the way down in the list. Apparently The sorting sorts all the names with Capitals first and after that the lowercase words come.

It would be more logic to just keep the letters together n and N together in the list not separated because one has a capital.

**Comment by whitebyte** [comment]
Seems to be resolved in 2.3.2+
![capitals](https://cloud.githubusercontent.com/assets/7704186/5593192/57e5db82-921e-11e4-942f-a5e2ce2b29b3.png)

**Comment by rtripault** [comment]
This indeed seems to be fixed, so closing.

Feel free to comment/reopen if needed.
Thanks
