### ISSUE TITLE
Input file type renders like a dropdown list

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3420]
onepack created Redmine issue ID 3420

When I create a TV with the input option File it will render like a dropdownlist in the backend.

Maybe this is how it should work but it's kinda confusing and different from all other CMS systems I ever worked with

**Comment by whitebyte** [comment]
Well, as of 2.3 manager revamp file TV looks more intuitive, so maybe this one may be considered resolved?
![filetv](https://cloud.githubusercontent.com/assets/7704186/5593201/d8586dc4-921f-11e4-979e-331b35137b9c.png)

**Comment by rtripault** [comment]
Indeed, while still not being rendered as a "regular" file input, distinction between combo (select) & file browser is more obvious, so closing.

Feel free to comment/reopen if needed.
Thanks
