### ISSUE TITLE
Able to drag a resource to the trash icon to delete it

### ISSUE THREAD

**Issue by adamwintle** [modxcms/revolution#3430]
adamwintle created Redmine issue ID 3430

Being able to drag layers in Photoshop to the bin icon made me think of this - a tiny improvement, but it would speedup the workflow.

**Comment by Alroniks** [comment]
Such as MODX use "soft deleting" mode, to remove resource without the ability to restore very dangerous, especially by mouse movement. Mark as deleted moving to trash bin icon does not make sense.

**Comment by sottwell** [comment]
Indeed, I would think this to be very confusing and possibly dangerous. Deleting things should require a bit more deliberate action than just dragging things around.

**Comment by sottwell** [comment]
I asked around among some acquaintances, and everybody from other developers to relatively clueful users didn't like the idea at all.

**Comment by OptimusCrime** [comment]
Closing because it looks like the majority of people here are not so supportive of the suggested idea.

Feel free to comment or reopen.

@modxbot close
