### ISSUE TITLE
Binding as a default value for checkbox tv not working correctly

### ISSUE THREAD

**Issue by andybaughman** [modxcms/revolution#3454]
andybaughman created Redmine issue ID 3454

I have tried using @SELECT, @EVAL and @CHUNK to provide a default value for a checkbox tv, but no values will return. Even something as simple as the following fails: 

@EVAL $test = '23'; return $test;

Using '23' (as a string) for the default value works correctly. I am using @CHUNK to provide the input option values, which works correctly. Can you replicate this?

**Comment by sonicpunk** [comment]
#modxbughunt  I will see if this is relevant.

**Comment by sonicpunk** [comment]
According to the MODX documentation:
When placing @ bindings inside the "Default Value" field the returned value is used to render to the final web page. This makes it simple to build complex forms for data input on the web very quickly.

Setting a default value for a checkbox in the TV, you just need to add the value of checkbox input option.

So if your checkbox TV input values look like this if you want 'yes' to be the standard value:

<img width="411" alt="screen shot 2017-03-03 at 10 20 34" src="https://cloud.githubusercontent.com/assets/447453/23545323/25ec7e68-fffb-11e6-8d98-b2c6825dde88.png">

**Comment by OptimusCrime** [comment]
I think he just wants the content of default value to be parsed just like the options are? There is no implemented functionality for using bindings in the default value?

**Comment by rtripault** [comment]
Thing is the default value is parsed in non manager contexts, and not in the manager (for unknown reasons to me)... the fix is fairly easy tho... https://github.com/modxcms/revolution/blob/2.x/manager/controllers/default/resource/resource.class.php#L311-320 (using the processed default value when needed)... not sure if that would be a breaking change

**Comment by OptimusCrime** [comment]
What do you mean non manager contexts?

**Comment by rtripault** [comment]
i meant all `modContext` where `key !== 'mgr'`

**Comment by OptimusCrime** [comment]
Oh yeah. That makes sense. I thought that was the case for the options too, but I guess they are only parsed in mgr. Does this lead to any problems? Other than a slight performance impact, I can't see how this may cause any problems?

**Comment by rtripault** [comment]
There should not even have performance impact since the bindings are already parsed to check against inherited values, the output is just never used... i'm not seeing any problem either, so i guess i'll just send a PR...
