### ISSUE TITLE
Image TV url/path bug

### ISSUE THREAD

**Issue by multimedia** [modxcms/revolution#3481]
multimedia created Redmine issue ID 3481

The bug that occured from release Revolution-2.0.6-pl regarding image TV url values, filemanager_path and filemanager_url seems to work better now in Revolution-2.0.7-pl. But it still has some problems. Maybe this has to do with using different contexts and filemanager_path and filemanager_url settings per context.

*Systemsettings:*
* filemanager_path = /var/www/vhosts/local.crowneast.nl/httpdocs/assets/images/default/
* filemanager_path_relative = No
* filemanager_url = assets/images/default/
* filemanager_url_relative = Yes

---

h3. Context

This are the systemsettings for the contexts regarding the filemanager:

*Context 'orcon':*
* filemanager_path = /var/www/vhosts/local.crowneast.nl/httpdocs/assets/images/orcon/
* filemanager_url = assets/images/orcon/

*Context 'haen':*
* filemanager_path = /var/www/vhosts/local.crowneast.nl/httpdocs/assets/images/haen/
* filemanager_url = assets/images/haen/

---

h3. Folder overview

Here is an overview of the image folder structure inside httpdocs:

/assets/images/default/
/assets/images/orcon/
/assets/images/orcon/level1/
/assets/images/orcon/level1/image.jpg
/assets/images/orcon/level2/
/assets/images/orcon/level2/image.jpg
/assets/images/orcon/level3/
/assets/images/orcon/level3/image.jpg
/assets/images/haen/
/assets/images/haen/level1/
/assets/images/haen/level1/image.jpg
/assets/images/haen/level2/
/assets/images/haen/level2/image.jpg
/assets/images/haen/level3/
/assets/images/haen/level3/image.jpg

---

h3. Description

This is what happens when im editing/creating a resource in context 'orcon' with a template that has an image TV attached to it:

* Click resource in leftbar to open for editing
* Click Template Variables tab
* Click button with arrow-down icon on image TV input field
* It opens the MODx Browser showing me the folders inside /assets/images/orcon/
* it lists level1, level2, level3 as folders
* Click level1 folder, and select image.jpg by clicking on the thumbnail, after that click OK
* Im back in the Template Variables tab and the value of the image TV is set to /level1/image.jpg
* The thumbnail generated by phpthumb is shown below
* Click Save
* Click same resource in leftbar to open for editing again
* Click Template Variables tab
* The value of the image TV is now assets/images/orcon//level1/image.jpg
* Notice the double / between the filemanager_url and the path from there to the image
* No thumbnail is shown below the image TV
* Looking at the site where im using the image the url is http://www.domain.com/assets/images/orcon//level1/image.jpg
* It shows the image on the website altough the url is wrong

Now a different situation, where im showing the image scaled by phpthumbof on the website.
Everything is the same as above, only i select an image from assets/images/orcon/level3/
I'm using the phpthumbof output filter like this:

<pre>
[[+tv.img_level3_product:phpthumbof=`&f=jpeg&q=95&w=190`]]
</pre>

* After selecting the image.jpg from level3 the image TV value is /level3/image.jpg
* The thumbnail is shown below the image TV
* Click Save
* Looking at the site where im using the image the url is:
* http://www.domain.com/assets/components/phpthumbof/cache/assets_images_orcon__level3_image.jpg.bdee9d0f453e042eea649e79acfb5df4.jpeg
* Notice the double _ between the orcon and level3

But after going back to the manager editing the same resource and saving it:

* Click same resource in leftbar to open for editing again
* Click Template Variables tab
* The value of the image TV is now assets/images/orcon//level3/image.jpg
* No thumbnail is shown below the image TV
* Removing the extra / in between orcon and level3
* Click Save
* Looking at the site where im using the image the url is:
* http://www.domain.com/assets/images/default/assets/images/orcon/level3/image.jpg
* No image or thumbnail is shown

---

Possible solution:

When browsing for an image to use as value for an image TV. Always use the full url from the MODx base_url when filemanager_url is set and filemanager_url_relative is Yes.

So that after selecting an image the image TV value is the complete url eg. assets/images/orcon/level3/image.jpg
If the code to do that combines the filemanager_url with the relative url from there to the image look if the filemanager_url ends with a slash and the relative url from the filemanager_url to the image starts with a /. If so remove one / and then combine.
From that url generate the thumbnail to use below the image TV input field.

That might solve the problem.

Could it be the extra / is the base_url that been put in the wrong place?

**Comment by rtripault** [comment]
Those settings has been deprecated since Media Sources, so closing.

Feel free to reopen/comment if needed.
Thanks
