### ISSUE TITLE
Respecting the new-file-permission setting

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#3488]
bertoost created Redmine issue ID 3488

When I upload new files the permissions of the new files are not as setupped in the system settings. In my situation apache is running with suphp wich need the correct permissions. And also, why would you configure it if it isn't used... So it would be great that the manager (and also the phpthumbof snippet) respect the system settings

**Comment by sonicpunk** [comment]
#modxbughunt checking to see if this can be closed

**Comment by sonicpunk** [comment]
I checked this locally using MODX 2.5.5.  I was able through the MODX Manager interface to create a folder and upload a file to that folder.  I checked the permission of the folder and file, and they matched the corresponding system setting.  I would say that this can then be closed.  It worked for me. #modxbughunt rules.

**Comment by rtripault** [comment]
So closing.

Please feel free to comment/reopen if needed.
Thanks
