### ISSUE TITLE
Tv's Input Option Values Leftovers

### ISSUE THREAD

**Issue by gOmp** [modxcms/revolution#3494]
gOmp created Redmine issue ID 3494

{Didn't know to which category assign this}

When setting up a TV we can fill in an input option values as inline content, options separated by `||` , by bindings, delimiters and so...
The problem is when for example we save the TV with some chosen option across the different resources when adding/editing them,
And afterwards when we want to edit the TV's input option values, and remove an option that we used already somewhere in our resources,
Then it would show this removed-option at those resources even that we removed it from being an option, it would still be there but as a *blank label.

So generally speaking it doesn't update the input option values. and we left with a *blank leftovers.
It's because when rendering the values for the TV's in the Back-end Resource Page it takes the values of the TV's from `[[+PREFIX]]site_tmplvar_contentvalues` Table, and this values isn't always fit to what we set(changed) to be the options of the particular TV.

I Think that it would be much better if while rendering the tv input in the manager, to cross-check if the stored values are those who appears as part of the `Input Option Values` so if we change our input option values/or deleting a resource/chunk/whatever-filled as an option, you don't need to go and update the tv all across your site to avoid those ugly blanks.

I suppose it's a known behavior (if so, then why?), or is it a bug?

A little note: \* Blanks appear when using check boxes, In other types (e.g. `DropDown List Menu`) it's just outputs on the front-end the option we saved and removed.

as described here:
http://modxcms.com/forums/index.php?topic=59700

**Comment by OptimusCrime** [comment]
I am pretty sure this is known behavior and there are no better ways to do it.

If they implemented a way to "listen" to changes, they would have to analyze the changes and figure out what value was altered. How should be done if multiple values were added instead? Should they be changed to that or left alone?

I am pretty sure there is no easy way to fix this issue. And it is well known.

**Comment by goldsky** [comment]
https://forums.modx.com/index.php/topic,59700.0.html

I'm going to try and fix this today.

**Comment by goldsky** [comment]
I think this has already fixed.
Proposed to closed #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @goldsky

**Comment by rtripault** [comment]
Let's close then!
