### ISSUE TITLE
Giving a user access to element category before the Admin

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3497]
onepack created Redmine issue ID 3497

When you first give an Editor User Group access to a category via the "element category Access tab", before giving it to the Admin User Group. It will remove the category option from the category dropdown once you want to add this category to the admin user group as well!!

I had to remove the group access from the Editor User Group before I was able to access the elements again in that category.

*I also tried it the other way around:* 

I first gave the admin user group via the Element Category Access tab access to the category "userelements"
Then I went to the Editor User Group and in the Element Category tab I could still assign the "userelements" category from the dropdown.

**Comment by rtripault** [comment]
Will consider this as the expected behavior. Furthermore, a "sudo" option has been introduced to prevent that kind of issue. So closing.

Feel free to comment/reopen if needed.
Thanks
