### ISSUE TITLE
manager documents resource tree: Show page info on hover

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3506]
onepack created Redmine issue ID 3506

It would be nice if a user could see some page info on a document menu-item hover.
In Evolution this was the case although it was a big chunk of text with a lot of info

Maybe give the manager the ability to choose if he wants to show this, to who, and what info to show in the system settings.

An example is that I returned to a project that I was working on and saw I had to add a new document. When I came to the menu index setting I didn't know what the index of the other pages was so I had to guess the menu index of this new page. 
Off course I guessed wrong and had to open the old page that has to show "before" my new page to find out what the menu index was.
Then I had to open my new page again to adjust the index.

**Comment by OptimusCrime** [comment]
This is implemeted.

@modxbot close
