### ISSUE TITLE
Permission denied saving template in resource category

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3548]
onepack created Redmine issue ID 3548

I have setup two category groups, 1 for the editors and one for the admin with Templates like Maintenance Template etc.
I tried to create a new template in the Category Admintemplates that is assigned in the Element Category Access to the Admin User group.

However this usergroup has all the possible rights assigned that you can have. save, view etc etc (126 pieces) a Admin super user is not able to create a template under the Admintemplates category.

I'm still able to save it to another category and after done that I can drag it to the admintemplates category. After that I can adjust the template and save it without a problem still being in the admintemplates category.

See screenshot

**Comment by whitebyte** [comment]
Target version was Revolution-2.0.7-pl, and image is missing ever in the old redmine BT, so +1 for closing as not reproduceable
