### ISSUE TITLE
Custom Permissions on actions get overwritten on upgrade

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3558]
onepack created Redmine issue ID 3558

I noticed that some menu items that I was hiding for an editor became visible after a system upgrade.
It seems that the custom permissions you can set on Action items get overwritten by the default "empty" value.

I thought I have seen a similar bug report before but was unable to find it.

**Comment by rtripault** [comment]
Related to #4978, so closing in favor of mentioned issue.
