### ISSUE TITLE
Unwanted template inheritance from parent resource

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#3562]
onepack created Redmine issue ID 3562

When I create a child Document Resource under a list-template that child will by default also get list-template as the default template.
It doesn't matter what template I set as default in the System settings. I don't know if this is meant to be but it if so, it would be nice if this could be adjusted or set in the system settings.

**Comment by rtripault** [comment]
This indeed seems to be by design (see [relevant code](https://github.com/modxcms/revolution/blob/master/manager/controllers/default/resource/create.class.php#L179)), so closing.

Feel free to comment/reopen if needed.
Thanks
