### ISSUE TITLE
FC: tv default_text does not seems to tie to user group

### ISSUE THREAD

**Issue by u007** [modxcms/revolution#3583]
u007 created Redmine issue ID 3583

Hi,

i realized that when i set a default value for a specific user group which is set in the form customization profile,
the entry does not create any modx_access_actiondom.

Is there a bug in the actiondom generation for FC?
please advice,

thank you.

**Comment by raffy99** [comment]
can't confirm the second comment. active/inactive status does reflect the rules

**Comment by Mark-H** [comment]
As far as I can find, modAccessActionDom is not used anywhere currently, so I'm going to go ahead and close this. Perhaps it's changed since 2011, or was never used.

If this continues to be an issue, please open a new issue with details on how to test/address the probem. Thanks.
