### ISSUE TITLE
output the direct URL of a weblink

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#3621]
jrotering created Redmine issue ID 3621

It would be very useful to be able to output the direct URL of a weblink resource, either by a checkbox on the weblink form or by a scheme in the link tag, e.g [[~123? &scheme=`direct`]].  

See full forum post at [[http://modxcms.com/forums/index.php/topic,60285.0.html]]

**Comment by adamwintle** [comment]
Isn't this possible using ```[[~123? &scheme=`full`]]`` cc. @mark-h

**Comment by Mark-H** [comment]
As Mike mentioned the `use_weblink_target` setting is key here. With that enabled, any link tag to a weblink will use the actual target url rather than the url to the weblink resource. I personally don't see much use for adding `direct` and `weblink` schemes to toggle that feature per link tag.

**Comment by pixelchutes** [comment]
There have been a few rare occasions where I could have used an override to the global default. Relatively minor in the grand scheme of things.

**Comment by adamwintle** [comment]
I'd not consider this a core MODX bug and just a minor request. Could this be handled by a plugin if someone needs it specifically?

**Comment by pixelchutes** [comment]
Ha! I think this support is already be baked in. 

I tested overriding the global system setting, like so: ```[[~123? &use_weblink_target=`0`]]```

It worked as expected!
