### ISSUE TITLE
Sometimes the page doesn't save and I get stuck - new content is lost

### ISSUE THREAD

**Issue by xpix** [modxcms/revolution#3638]
xpix created Redmine issue ID 3638

Hi,

From time to time the manager doesn't save the document I just edited. 
The "Please Wait/Saving" overlay appears and stay there forever. 

If you just added content you cannot go back by pressing ESCAPE or by closing that overlay which means that you need to refresh the page.
By refreshing the page _the new content is lost._ 

Please provide a way, a close button for now, that will close the overlay and allow users to re-save. 
When the overlay is closed by pressing the close button a message should appear and say "Your data has not been saved. Please try again. If this continues to happen save the data in a file on your computer, reload the page and re-paste the content".

A better solution would be to implement a timer(configurable from settings) for the "Please Wait/Saving" message. If the document is not saved in 20 seconds you should alert the user to save the new content in a different format, reload and paste the content again and save.

Currently I am not sure if this is a MODX only problem or maybe from time to time the host doesn't properly answer to the MODX request but it never happen on Evo, and I know it happened in Revo in previous versions.

I attached a screen-shot with my thoughts. I keep posting what I find but I suspect a js error.

Thank you

**Comment by andrewcsp** [comment]
I just had this issue in MODX 2.4.2 on Firefox 42 and noticed that it coincided with a JS error in Firebug:

    uncaught exception: [object Object]
    domain.com/assets/components/tinymce/jscripts/tiny_mce/tiny_mce.js?v=242pl
    Line 1, col 118324

Inspecting col 118324 in the minified JS file leads me to the statement **o.cloneNode(true)** in the following code fragment:
```javascript
if(d&&i.select("script,style,select,map").length>0){n=o.innerHTML;o=o.cloneNode(false);i.setHTML(o,n)}else{o=o.cloneNode(true)}
```

Looking at the unminified file, I believe this correlates to line 10336 of https://github.com/splittingred/TinyMCE/blob/develop/assets/components/tinymce/jscripts/tiny_mce/tiny_mce_src.js (**node = node.cloneNode(true);**
```javascript
...

// Return public methods
return {
	schema : schema,

	addNodeFilter : htmlParser.addNodeFilter,

	addAttributeFilter : htmlParser.addAttributeFilter,

	onPreProcess : onPreProcess,

	onPostProcess : onPostProcess,

	serialize : function(node, args) {
		var impl, doc, oldDoc, htmlSerializer, content;

		// Explorer won't clone contents of script and style and the
		// selected index of select elements are cleared on a clone operation.
		if (isIE && dom.select('script,style,select,map').length > 0) {
			content = node.innerHTML;
			node = node.cloneNode(false);
			dom.setHTML(node, content);
		} else
			node = node.cloneNode(true);

...
```

**Comment by pixelchutes** [comment]
Do you receive any kind of errors saving the same content when TinyMCE is _not_ installed?

**Comment by andrewcsp** [comment]
Unfortunately it appears to be an intermitent bug. I was updating a bunch of 10 documents and it happened about 4-5 times within 5 minutes. After that, no problems at all.

I presume not using TinyMCE will fix the problem. Will try that the next time this problem surfaces.

For what it's worth, I don't think the actual content within the TinyMCE editor is a factor (could be wrong of course). The documents contained one <p> tag containing 10-20 words. No links, tables, images, nothing fancy at all.

**Comment by OptimusCrime** [comment]
I am going to close this for following reasons:

- Original issue can deal with multiple underlying issues (see below list)
- Has to do with extras
- No error log or extended information.

The manager interface is heavily ajax-based, now, without inspecting the network data, a wide range of reason could prevent a resource from saving. These include (but not limited to): javascript errors (request is never sent), PHP error (fatal error resulting in invalid JSON response), web server error (apache/nginx fails to deliver response).

Feel free to comment or reopen if you disagree with my decision.

@modxbot close
