### ISSUE TITLE
fetch request path from $_SERVER['PATH_INFO']

### ISSUE THREAD

**Issue by gaussgss** [modxcms/revolution#3691]
gaussgss created Redmine issue ID 3691

So instead of if/rewrite with latest nginx versions we can just use:
<pre>
try_files $url $url/ /index.php$url?$query_params
</pre>

**Comment by rtripault** [comment]
That's the way i'm using rewrite in NGINX, without issue, so closing.

Feel free to comment/provide additional information if needed.
Thanks
