### ISSUE TITLE
Add some "don't show this again" checkboxes to  intermediate dialogs

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#3750]
bobray created Redmine issue ID 3750

This would  make the Manager a lot less annoying for those doing a lot of development work.

The message on "Search Locally for Packages" only needs to be seen a few times.

The warning about changing a resource's template might also be a good spot for this.

**Comment by adamwintle** [comment]
+1 for this, surprised this issue is so old and never been discussed

**Comment by BobRay** [comment]
All of the JS confirmation dialogs still drive me crazy -- more so than ever.

**Comment by Mark-H** [comment]
I'm considering this a dupe of #3357 - while slightly different in requested execution, the goal of them is the same: limit the confirmation dialogs.
