### ISSUE TITLE
Property Sets + Templates

### ISSUE THREAD

**Issue by debussy** [modxcms/revolution#3778]
debussy created Redmine issue ID 3778

_Assigning a Property Set to a Template_
This would require an extra interface dongle somewhere in the Template editing screens that allowed you to actually assign a property set for the template (more of a hard setting than an on-the-fly setting like in Snippets & Chunks). I could very easily be wrong, but it seems like it shouldn't be too hard to just add a pop-up menu on the template editor somewhere: "Use Property Set: [list of property sets]" that the backend uses to make the property set assignment.

_Use example:_
When developing on a dev server, each template (and there may be many) has properties which are used to generate paths on the dev server (to a template folder, for example). Then a property set with the correct values is assigned to each template. When migrating to the server, rather than changing the template property on every template, one only need change the value in the Property Set.

**Comment by ilyautkin** [comment]
In 2.7.0 property sets is assignable for templates (like for chunks and for snippets).

![1zpwgi](https://user-images.githubusercontent.com/3328625/51164709-a6563b00-18bf-11e9-9a89-3c48641359c5.png)

**Comment by JoshuaLuckers** [comment]
This feature is implemented, therefore I'm closing this issue.

Thanks everyone for helping us make MODX better by providing input 👍.
