### ISSUE TITLE
move db queries from getlist processors into model

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#3794]
netprophet created Redmine issue ID 3794

Moving queries from getlist processors into the model, in general, will provide the following benefits:
- create access to lists of things via the API
- simplify the exercise of tweaking queries for specific db drivers
- set the stage for classes to be overridden without requiring change to getlist processors

**Comment by rtripault** [comment]
Definitely an interesting approach we should keep in mind when refactoring ;)

Anyway, closing due the lack of activity here.

Feel free to comment/reopen if needed.
Thanks
