### ISSUE TITLE
Reset option for system settings

### ISSUE THREAD

**Issue by antonyf** [modxcms/revolution#3819]
AntonyF created Redmine issue ID 3819

I am new to Revo, and have been tinkering with various settings in attempts to fix certain issues.

It becomes very quickly easy to forget what was the original setting, or in fact to know if I have even moved back to the original setting due to the 'last modified' date.

I think it'd be useful to have a reset option, to restore that setting to 'factory default' and also remove the last modified date so that it's clear it's back to the standard setting.

**Comment by rtripault** [comment]
Considering the issue age, i'm closing this one.

Feel free to comment/reopen if needed.
Thanks
