### ISSUE TITLE
Lexicon can be added, but can't be searched, modified, and deleted

### ISSUE THREAD

**Issue by nomo** [modxcms/revolution#3884]
nomo created Redmine issue ID 3884

When I installed FormIT snipet, I wanted to use custom lexicon for Japanese.
I created my custom entry from lexicon management like this.

----------------------------
Name: formit.contains
Namespace: formit
Topic: default
Language: ja
Value: value123
----------------------------

However, I can't search or update this entry any more because "ja" wasn't displayed.

BobRay advised me that I should prepare lexicon files like this.

# cp -a core/components/formit/lexicon/en core/components/formit/lexicon/ja

After this, I could search and update my entry.
I believe those custom entries should be searched and updated via management interface without preparing files.

Topic URL: http://modxcms.com/forums/index.php/topic,61276.0.html

**Comment by OptimusCrime** [comment]
Closing this due to old age and no further reports of the same problem.

If you have experienced this since or can give more information, feel free to comment or reopen this issue.

@modxbot close
