### ISSUE TITLE
Provide an option to exclude a "container" resource-alias from the fURL path

### ISSUE THREAD

**Issue by bmilton** [modxcms/revolution#3942]
bmilton created Redmine issue ID 3942

There is a need for resource organization that is simply virtual and not rendered in the URL path.  
I.e. creating a resource container to categorize many similar documents.  The usage here is very similar to the "category" feature that is available in the elements section.

So in some cases a container alias would appear in the actual URL and in other cases it would be for internal organization only.

Since this feature does not exist, the work-around is to use containers as organizational folders, turn off "use friendly alias path" in system settings, and modify the alias for any resources that actually need to render a folder path in the url directly.  i.e "/articles/myarticle"as the resource alias.

**Comment by rtripault** [comment]
Closing this issue in favor of #11153 since the thread is more activity there.

Thanks

#modxbughunt
