### ISSUE TITLE
Use chunks for signup, forgot, reminder emails body

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#3969]
gadamiak created Redmine issue ID 3969

The content of signup, forgot and reminder emails is set in a textfield in system settings, which is not handy. The field is small and standard placeholder can't be used.

That would be much more usable to specify a chunk name with the mail body instead and allow to use all MODx magic available in chunks.

**Comment by OptimusCrime** [comment]
While the small textfield is not ideal for editing it is much easier to use the textfield in Modx 2.3 (not sure how 2.2 or earlier looked).

Also, I do not agree that adding actual chunks accessable in the Elements-tab is a good solution. I like to keep my installation clean, and having a bunch of system related chunks would break that.

I suggest closing, based on the "easier to use textfields in Modx 2.3" which kind of solves this.

**Comment by rtripault** [comment]
The benefit i would see being able to use chunks (or anything the parser ca understand), is that you could make use of lexicon for internationalization.

So i would still consider this issue/feature "valid".

**Comment by rtripault** [comment]
A solution could be :

1. remove the manual processing of placeholders in https://github.com/modxcms/revolution/blob/master/manager/controllers/default/security/login.class.php#L239-243
2. replace with `$this->modx->setPlaceholders($placeholders);`
3. parse the message `$this->modx->getParser()->processElementTags('', $message, false, false);`
4. unset placeholders ? `$this->modx->unsetPlaceholders($placeholders);`

Worked flawlessly with default `forgot_login_email` value, as well as with value `[[$forgot-login]]`, which is a chunk with the same content as the original setting value.

**Comment by Mark-H** [comment]
Fixed in #12266
