### ISSUE TITLE
Unable to copy/paste from Reports | System Information page

### ISSUE THREAD

**Issue by ukwiz** [modxcms/revolution#3981]
ukwiz created Redmine issue ID 3981

When trying to extract data from Reports | System Information page, only the field description part is copied, not the values.

**Comment by rtripault** [comment]
I am closing this one as "duplicate" of #2516 & #2508.

Also, a PR has been sent (#12261) to allow copy/paste of the system information.

**Comment by whitebyte** [comment]
Historical moment: with the closing of this issue, the number of open tickets no longer 4-digit number!
