### ISSUE TITLE
Use clearer headings on the Form Customization panels

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#3997]
bobray created Redmine issue ID 3997

There are really three levels to form customization: Profiles, Sets, and Rules. The current headings are very confusing because the Profiles panel has "Form Customization" at the top, the Sets panel has "Profiles" at the top, and the Rules panel has "Sets" at the top.

I suggest just using Profiles, Sets, and Rules as the headings. I'm not sure the current subheadings help and they may add to the confusion depending on how the user names things. I'd suggest this scheme:

Form Customization Profiles
Sets (Editor Profile)
Rules (resource/create Set)

**Comment by rtripault** [comment]
Indeed, so closing.

Feel free to comment/reopen if needed.
Thanks
