### ISSUE TITLE
Add modUser->logout() and modUser->login($password)

### ISSUE THREAD

**Issue by splittingred** [modxcms/revolution#4009]
splittingred created Redmine issue ID 4009

Would be useful. Could fire the appropriate processors.

**Comment by alroniks** [comment]
Why do not use processors that already have all logic? Maybe it's a bit simpler for usage but it requires duplicating some logic in this methods even if we will use processors. More code - mode errors in the future. I would close, what do you think @opengeek @Mark-H ?

**Comment by OptimusCrime** [comment]
This feature has only been asked for twice in seven years. I agree, it should be closed. No reason to reimplement this as we have processors that does this very well.

**Comment by Mark-H** [comment]
This is already there's but called addSessionContext and removeSessionContext instead of login/logout. And checkPassword if you want to verify that.

**Comment by OptimusCrime** [comment]
Agreed to close it then Mark?

Oh, you closed it.
