### ISSUE TITLE
Date selector always hightlights current day, even in past/future months

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#4018]
pixelchutes created Redmine issue ID 4018

When you open a date selector for Publish/Unpublish Date while editing a Resource, the default view shows the current month/day with the day highlighted. However, upon going forwards/backwards (by month), the current day always stays highlighted...this is a bit confusing, as you may only expect the day of month to stay highlighted for the correct (read: current) Month/Year.

**Comment by sonicpunk** [comment]
#modxbughunt See if this is still relevant

**Comment by sonicpunk** [comment]
I can confirm this behaviour on MODX version 2.5.5.

**Comment by gernotebenlechner** [comment]
I can confirm this behaviour on MODX version 2.5.8-dev at #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @gernotebenlechner You just confirmed my confirmation.  Good job! :)

**Comment by alroniks** [comment]
I've investigated bug and can say that it is definitely ExtJS bug and, that is even worse, can not be fixed from MODX side. The first part with current day works as expected, the current day appears once, but selected day jumps across months (I've attached animation)

![calendar](https://user-images.githubusercontent.com/303498/42738725-4b77aae8-8891-11e8-9a7d-9027e91c6a05.gif)


So, I am closing this as unfixable, but if you have suggestions how to solve it, please, reopen the bug and share details. Thank you.
