### ISSUE TITLE
Documentation links  in Package manger should utilize "target=_blank" functionality

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#4036]
wshawn created Redmine issue ID 4036

Users may find it confusing to be "pulled" from the Manager to the documentation site, while in the process of installing extras.

Having those links finally there is very nice, but to have a work flow interrupted after clicking them may not be the best implementation

**Comment by whitebyte** [comment]
still actual for 2.4.0-dev

**Comment by rtripault** [comment]
What about using the browser feature to open in new tab/window instead ? (usually using `ctrl`, `alt` or `shift` keyboard key + click; or right clicking the link + pick the desired behavior)

**Comment by wshawn** [comment]
rtipault. If memory serves they are javascript links. Right clicking only follows link the same as a left click.

**Comment by rtripault** [comment]
@wshawn as far as i've noticed, all packages data (description, instruction, changelog...) are developers inputs, making links regular links.

But i might misunderstand which links you are talking about...

**Comment by wshawn** [comment]
Yes its the links in the descriptions. Clicking one of those takes from the site pulling the user away from the package manager. Makes it a pain to browse the packages via the Installer as not all extras are on the adds site.

By the way, right clicking is turned off on the links while control clicking works.

Most people would not think they are going to be yanked out of the installer when clicking a link.

**Comment by rtripault** [comment]
Closing that one since the proposed PR has been merged
