### ISSUE TITLE
Access policy requires web context for file access to work for other contexts

### ISSUE THREAD

**Issue by odeclas** [modxcms/revolution#4045]
odeclas created Redmine issue ID 4045

Multi-context installation - trying to create a new user with editing access to specific resources and assets.
Duplicate Content Editor policy - Context-Content Editor
Content Editor policy has no file access (a fault on it's own, in my view) by default so add file_\* and directory_\* access
Add Context access (Member 9999 with Context-Content Editor)
Add Mgr access 
Add user to group with that policy

When viewing in the manager the user can now see the Files tab and a files folder with a sideways arrow. Clicking on the arrow will remove the arrow and not allow browsing of the tree. This is only solved by adding Web context access - which gives them access to the entire files tree across all contexts by default.

**Comment by dannevang** [comment]
@odeclas It this not something that you would solve using Media Sources (Since Revo 2.2) 

I would imagine this could be closed now.

#modxbughunt

**Comment by rtripault** [comment]
Yes, i believe this could now be solved with Media Sources, so let's close this "oldy".

Feel free to comment/reopen if needed.
Thanks
