### ISSUE TITLE
Add resource_tree_default_action system setting

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#4075]
gadamiak created Redmine issue ID 4075

It would be useful to be able to set the default action in resource tree. It's hardcoded to edit resource, but it might be more suitable to assign quick update or refresh.

I guess adding @resource_tree_default_action@ would do.

**Comment by rtripault** [comment]
Interesting idea. I believe the lack of comment on the issue makes it a "won't fix" candidate, so closing.

Feel free to comment/reopen if needed.
Thanks
