### ISSUE TITLE
Assigning Form Customization profiles to specific roles within a usergroup

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#4081]
jrotering created Redmine issue ID 4081

Is there any way to create an FC profile based on a usergroup/role combination, rather than an entire user group?  I'm finding that the kind of customizations I want to make are very role-based.  Right now my user groups are based on departments within my organization... I have roles such as "site administrator", "site manager", and "site editor" that determine what level of access a user has to the department's resources.  

I could create additional user groups based on roles, but what I'm really after is the usergroup/role combination.  If someone is a "site administrator" in the group "group1" but only a site editor in "group2", I want them to have a different FC view depending on which group's pages they are working with.

**Comment by adamwintle** [comment]
I'm going to close this one due to inactivity. There may be a way to bend the Form Customiser into doing this, I'd suggest posting on the Forums or in a Slack chat room at http://modx.org to discuss this 

@modxbot close
