### ISSUE TITLE
[MS SQL Serv] installer database screen unresponsive in 2 scenarios

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#4082]
netprophet created Redmine issue ID 4082

Seems, in setup/processors/connector.php
- the sqlsrv driver may be timing out if the specified host is not found.. we need to wrap the ajax call in a timer and give a 'cannot connect' error if exceeds a certain length.
- another timeout is happening when user clicks 'Create or test selection of your database' .. needs further testing to identify how to replicate

**Comment by dannevang** [comment]
@netProphET Is this something specific to MS Sql? Since MS Sql isn't supported by modx today this could probably be closed?

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @dannevang

**Comment by rtripault** [comment]
Well, i believe SQLServer is still "supported", but agreeing we could probably close this one.

As usual, feel free to comment/reopen if needed.

Thanks

**Comment by mrhaw** [comment]
https://develop.modx.com/develop/revolution/requirements/

Database

MySQL 4.1.20 or higher (excludes 5.0.51)
**Microsoft SQL Server 2008**
Default table encoding of UTF-8
SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP
MyISAM storage engine

**Comment by OptimusCrime** [comment]
It is supported, but the original issue is old, difficult to decipher and lacks details.
