### ISSUE TITLE
Assign icons to content types

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#4139]
ncrossland created Redmine issue ID 4139

It would make the resource tree more user friendly if icons could be assigned to content types, as they were (albeit not in a customisable way) in Evo.

e.g. if you could assign an RSS icon to .rss content type so it would be differentiated in the Manager tree

**Comment by adamwintle** [comment]
Closing because duplicate of https://github.com/modxcms/revolution/issues/4841 @modxbot close
