### ISSUE TITLE
reload whole element list after saving

### ISSUE THREAD

**Issue by feeela** [modxcms/revolution#4152]
feeela created Redmine issue ID 4152

When saving an element in the MODx revolution manager, the element-tree is partly reloaded. This may lead to confusing side-effects. For example on saving an element with a new category, only that specific category part will be reloaded in the overview. The element then occurs twice in the element tree until next page reload or manually reloading the tree.

It would be nice, to reload the whole tree or get the logic to delete|rename|move unnecessary items.

**Comment by adamwintle** [comment]
The Element Tree and the Element names are now kept in synch upon saves. I'm going to close this issue. @feeela @wshawn if this bug comes back let me know and we can reopen the issue. 

@modxbot close
