### ISSUE TITLE
Site schedule after row edit time set to 12:00am

### ISSUE THREAD

**Issue by TheBoxer** [modxcms/revolution#4174]
theboxer created Redmine issue ID 4174

In site schedule, when I set different date, the time is set to 12:00am, unpublished date to 1970-01-01 and unpublished time to 12:00am. Is it possible to leave time unchanged or add another input for changing time entry, like in resource's settings tab?

**Comment by rtripault** [comment]
It's been more than 6 months without an answer from the OP, so closing :smile:

**Comment by TheBoxer** [comment]
lol :D

**Comment by TheBoxer** [comment]
anyway, the problem is still there, changing publish/unpublish date from site schedule page still reset time to 12:00am :)

**Comment by rtripault** [comment]
OK, reopening then

**Comment by TheBoxer** [comment]
I'll fix it :)

**Comment by opengeek** [comment]
@modxbot close

**Comment by opengeek** [comment]
just kidding @modxbot open
