### ISSUE TITLE
Add the ability to strip whitespace from templates

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#4186]
wshawn created Redmine issue ID 4186

In the template creation form, please provide a Boolean check box designating that template to have all white space stripped when used.

**Comment by rthrash** [comment]
Hi Shawn. I can think of some good uses for this, but I think it's best served as a plug-in that fires on save, or a plug-in that works when generating the cache objects for pages using that template. 

Would you agree?

**Comment by wshawn** [comment]
Definitely. I have been simply doing it in the template 
```
[[$Header:strip]][[*content:strip]][[$Footer:strip]]
```
I totally forgot about these feature requests...  Must have been in the 2.0 series....
