### ISSUE TITLE
"Min/max dimensions" option for image TVs

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#4203]
ncrossland created Redmine issue ID 4203

It would be useful to be able to specify a minimum or maximum pixel dimension for image TVs. This would prevent users from choosing images which are way too small for a design, or way too big for easy downloading. 

The options could allow the administrator to specify the operator
* <
* <=
* ==
* =>
* >

and value for any / all of width, height and total pixel count.

e.g.

Width greater than 300px

<pre>
Width:  [   > 300 ]
</pre>

Total pixel count less than 2500px (50x50px allowed; 51x51px not allowed)

<pre>
Pixel count:  [   <= 2500 ]
</pre>

For sites with many large images, it may be advantageous to cache the pixel dimensions of images to prevent files having to be read every time a TV is edited.

**Comment by rthrash** [comment]
I believe that the image+ TV would handle this requirement, so closing it. Here's a link to it's docs:

http://jako.github.io/ImagePlus/
