### ISSUE TITLE
Ability to have duplicate category names for children in different trees.

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#4218]
michaelm created Redmine issue ID 4218

Taken from -> http://modxcms.com/forums/index.php/topic,62885.0.html

Would like categories to be able to be named the same as another category in a different tree.  eg :

<pre>
- Example_A
   |- Web_Forms
   |- Navigation

- Example_B
   |- Web_Forms
   |- Navigation
</pre>

**Comment by rtripault** [comment]
Well, should indeed be possible since 2.3.0 (see https://github.com/modxcms/revolution/blob/master/core/docs/changelog.txt#L262), so closing.

Feel free to comment/reopen if needed (or if i did not understand the issue).
Thanks
