### ISSUE TITLE
FC: sorting of (user generated) tabs. Drag&Drop for settings and TVs

### ISSUE THREAD

**Issue by MadeMyDay** [modxcms/revolution#4224]
mademyday created Redmine issue ID 4224

It would be nice to have the possibility of sorting the (user generated) tabs in FC by adding a rank field. Additionally it would be nice to sort all the values (TVs, settings, tabs) by drag&drop and not by rank.

**Comment by rtripault** [comment]
While this is an old issue, it's still relevant.

Seems like ranks are implemented for tabs, but we still lack the drag & drop sorting...

**Comment by theboxer** [comment]
I don't think D&D sort needs to be everywhere, especially in places dedicated for low-frequency admin useage.
