### ISSUE TITLE
Permissions GUI - wireframe suggestion

### ISSUE THREAD

**Issue by jgulledge19** [modxcms/revolution#4226]
jgulledge19 created Redmine issue ID 4226

As I have been trying to figure somethings out via ACLs/Permissions I think I have a better understanding on how they work and I wish to provide a GUI suggestion to simplify this process.

Attached you will see my wireframe mockups.  modx-revo-Basic-Permissions.png this wireframe would replace both the Users and Content Access tabs for Security->Access Controls->New User Group/Update User Group.  All text in red is just to explain what should happen on the page.  I may post a Resource Group Access wireframe later if I have time to develop it.

Note I used Pencil to create these mockups: http://pencil.evolus.vn/en-US/Home.aspx and if anyone wants it I will send you the working file.  I also posted this in the forums: http://modxcms.com/forums/index.php/topic,62926.0.html

Thanks for reading and hopefully this is helpful.

**Comment by adamwintle** [comment]
@jgulledge19 I think the originally proposed wireframe has been lost from the Redmine to Github migration - still got the original designs?

**Comment by jgulledge19** [comment]
@adamwintle yes, your in luck :)

I attached the PDF that I created for this proposal, but I have not reviewed it in years! I don't have the working copy any more.

[Permissions-Suggestions-for-MODX-3.pdf](https://github.com/modxcms/revolution/files/88060/Permissions-Suggestions-for-MODX-3.pdf)

**Comment by OptimusCrime** [comment]
@jgulledge19 After scrolling (pretty fast) through your PDF, it strikes me that most of the things you mention is how MODX is structured today. The only exception if that things are more separated than what you suggest. 

Would you say that this issue is still valid and important today, or has most of the aspects been taken care of in some way during the past 5 years?

**Comment by OptimusCrime** [comment]
Ping @jgulledge19

**Comment by jgulledge19** [comment]
@OptimusCrime yes, there have been a number of improvements in the ACL/User management. With that said I think there is still an opportunity for improvement and UI simplification. This ticket is very old and would need a lot of review/rewrite to make it viable. So I will close.
