### ISSUE TITLE
Template dropdown should show folders

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#4235]
ncrossland created Redmine issue ID 4235

When editing a resource, the Template dropdown should show the templates in folders (if templates have been arranged in folders within the Elements panel). This would make it much easier to locate the correct template on sites with large numbers of templates.

**Comment by OptimusCrime** [comment]
Like other trees in the manager, it should store the current state for that user. Not sure if you wish for automatic expanded tree for all templates, in that case I disagree.

**Comment by rtripault** [comment]
I guess the op rather meant listing/displaying the template "category" in the combo box (select), the same way the categories combo (available when you create/edit an element) behaves, ie. `Category - Template name`

**Comment by alroniks** [comment]
Related to https://github.com/modxcms/revolution/pull/13905

**Comment by theboxer** [comment]
3.x shows templates under categories
