### ISSUE TITLE
When all uncategorized TVs are moved to new tab via FC, "uncategorized" subtab is still visible, and empty TV tab still shown

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#4241]
ncrossland created Redmine issue ID 4241

To reproduce:
1. Create a TV, but do not assign it a category. Assign it to a template.
2. Create a FC rule which applies to this template.
3. Within the FC rule, create a new tab, and move the new TV to the tab.

Result:

When editing a resource which uses this template (and has the FC rules applied), the new tab is created and moved to it. But, the "Uncategorized" subtab still appears, empty, within the "Template Variables" tab.

In addition, since there is now no TVs within the "Template Variables" tab, the whole TV tab should be hidden - see fixed bug http://bugs.modx.com/issues/3542

**Comment by Pfeifakopf** [comment]
Nothing new to fix this bug?

**Comment by GulomovCreative** [comment]
This bug has already been fixed and can be closed!
