### ISSUE TITLE
Add default JPEG quality setting for phpThumb

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#4245]
ncrossland created Redmine issue ID 4245

At the moment the only way to modify the JPEG quality of phpthumb is manually specifying it every time, or modifying the class file (which may be overwritten on upgrade). 

It would be helpful to have the option of specifying a different value for some sites - e.g. photography heavy sites, or mobile specific sites

**Comment by adamwintle** [comment]
pThumb adds this functionality @modxbot close
