### ISSUE TITLE
deleting template some TVs loose access permissions

### ISSUE THREAD

**Issue by krisj** [modxcms/revolution#4264]
krisj created Redmine issue ID 4264

Like the subject says, I deleted a few unused templates from the tree and some TVs lost the permissions assigned to other remaining templates.

Will try to debug a little more...

**Comment by hugopeek** [comment]
Will briefly try to reproduce for #modxbughunt, but this is oooooold and missing info too.

**Comment by sottwell** [comment]
I had this happen once, about that same time, but was busy at the time and didn't follow up on it. And the site was pretty much of a mess in general anyway so it wasn't a big surprise. Over 60 templates.

**Comment by hugopeek** [comment]
Can't really think of many ways to reproduce this.. But here we go:

- Fill elements and content with test data from a random project
- Find an unused template and check which TVs are assigned
- Find another template with the same TVs assigned
- Set log level to 4, so debug info is displayed in error log
- Delete the unused template and try to make any of the assigned TVs disappear in other templates

### Attempt 1:

Unsuccessful. Only deleted assignments for the correct ID:
```
Removed modTemplateVarTemplate instance with primary key Array
(
    [0] => 39
    [1] => 15
)
```
and so on.. (15 being the deleted template)

### Attempt 2:

Only thing that might be weird is the fact that it deleted a reference to a TV with ID:0
```
Removed modTemplateVarTemplate instance with primary key Array
(
    [0] => 0
    [1] => 7
)
```

_Resetting DB_

### Attempt 3:

- Duplicated a template and changed its ID to 150 (original is 15)
- Changed template IDs in the corresponding tmplvar_templates columns too
- Deleted the template again

Nothing.

What to do with old edge cases like this? Unless we know in what version the issue first appeared, this will be impossible to hunt down..

**Comment by hugopeek** [comment]
Can we close this one #modxbughunt -ers? Or any other ideas to try and reproduce?

**Comment by rtripault** [comment]
It's an old one, and since you were not able to reproduce with the given information, let's close it.

Feel free to comment/reopen if needed.
Thanks

**Comment by krisj** [comment]
Hi guys, this is very old indeed, I have stopped using ModX a long time ago too, so won't be able to help with the original issue.

**Comment by rtripault** [comment]
No problem krisj. We are in the process of cleaning things up, hence that notification from another time ;) (sorry for the noise)

Cheers
