### ISSUE TITLE
Add a class to each ressource to represent the template it is using

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#4273]
pepebe created Redmine issue ID 4273

Add  class="template_#" to each document resource where # is the id of the documents template (template_1). 

All you now have to do is to tweak the manager css to give some visual feedback which template is used for any document.  For a more detailed discription have a look at this thread: http://modxcms.com/forums/index.php/topic,58768.msg335571.html#msg335571

**Comment by whitebyte** [comment]
Since icon templates are implemented, this issue should be closed maybe?

**Comment by rtripault** [comment]
Guess so, so closing.

Feel free to comment/reopen if needed.
Thanks
