### ISSUE TITLE
need a way to set a default value for "Empty Cache" Resource setting.

### ISSUE THREAD

**Issue by krisj** [modxcms/revolution#4278]
krisj created Redmine issue ID 4278

Currently it defaults to `0` unless you create a FC profile and assignit there. Would be nice if I did not have to turn it on all the time as admin user.

**Comment by rtripault** [comment]
A first step has been done with #12178 and an update is on its way with #12218.

So i'm closing.

Feel free to comment/reopen if needed.
Thanks
