### ISSUE TITLE
Allowing sorting of items within Listbox (multi) TVs

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#4295]
ncrossland created Redmine issue ID 4295

It would be useful if the user could sort chosen items within Listbox (multi) TVs via drag and drop. This would allow control over the order that data values are stored.

**Comment by whitebyte** [comment]
Possible duplicate of #3881

**Comment by OptimusCrime** [comment]
Duplicate indeed

**Comment by achterbahn** [comment]
couldn't that be closed as already referenced as a duplicate?
