### ISSUE TITLE
resource menu does not refresh if resource moved back into original parent

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#4368]
netprophet created Redmine issue ID 4368

How to replicate:
* Edit a Resource
* Change the parent - resource tree refreshes
* Change the parent back to where it was originally - resource tree does not refresh

This is caused because the hidden field which keeps track of "original parent", and is used in the decision whether to refresh the tree or not, is not retaining the new "original parent", attempted around line 546 of manager/assets/modext/widgets/resource/modx.panel.resource.js
<pre><code class="javascript">
if(pa !== pao) {
    t.refresh();
    Ext.getCmp('modx-resource-parent-old-hidden').setValue(pa);
} else {
</code></pre>

**Comment by rtripault** [comment]
I guess this has been fixed (see [code](https://github.com/modxcms/revolution/blob/master/manager/assets/modext/widgets/resource/modx.panel.resource.js#L167-170)). So closing.

Feel free to comment/reopen if needed.
Thanks
