### ISSUE TITLE
Resource tree collapses on save

### ISSUE THREAD

**Issue by juro** [modxcms/revolution#4371]
juro created Redmine issue ID 4371

After saving resource and manager reloads, resource tree expands the current branch only to level of the edited resource. All other previously opened branches under the same parent are collapsed now. Parent's sibling branches are not affected.
That means editing any resource in the tree root collapses all branches.

Not sure in which Revo version this appeared for the first time. 2.0.3 works fine, 2.0.7 and higher including 2.1.0.rc3 all having this problem.

**Comment by rtripault** [comment]
This appears to be fixed, so closing.

Feel free to comment/reopen if needed.
Thanks
