### ISSUE TITLE
Resource access policy converted to template on upgrade to 2.1.0-rc3

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#4432]
gadamiak created Redmine issue ID 4432

I had 2 access policies based on Resource Template in 2.0.8-pl. On upgrade to 2.1.0-rc3 (git 4945198) one of them got based on administrator template while the other got transformed to a policy template on its own!

The policy in question got only one permission set -- @add_children@. After upgrade the permission was removed emptying the police, making it innefective. On policy templates tab, it shows admin group but has 0 permissions in it.

**Comment by pbowyer** [comment]
@gadamiak Given the version number involved, I suggest @theboxer closes the ticket. If you're still encountering this error with MODX 2.4, please let us know. Thank you!
