### ISSUE TITLE
MODx.Ajax.request calls concurrently share listeners

### ISSUE THREAD

**Issue by splittingred** [modxcms/revolution#4478]
splittingred created Redmine issue ID 4478

This causes strange issues to occur where two calls to the request method, if run at the same time, will only use the second listener.

I think this has to do with the singleton nature of Ext.Ajax.Request and the abstraction of MODx.Ajax.request around it. This will probably need to be a bit better isolated in the future to prevent this bug; however, I worry about introducing a major architectural change to the commonly-used method so late in the 2.1 cycle. Therefore, fixes for this issue will be pushed to a post 2.1+ minor release branch.

To reproduce, simply make any two MODx.Ajax.request calls that use separate listeners on the 'success' event.

**Comment by rtripault** [comment]
This should have been closed since 2.3.2-pl (yeah, finally!). So closing
