### ISSUE TITLE
Populate or Filter Element Tree based on Category name

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#4503]
wshawn created Redmine issue ID 4503

Currently, nothing happens when a Category name is clicked on in the Manager.

I believe the cleanest methodology would be to filter the Element tree to only the Category which has been selected, while providing a reset or clear filter to the display.

**Comment by wshawn** [comment]
This should still be pursued.

To reiterate, create a display where all of the Categories elements are displayed grouped by Type.

**Comment by Alroniks** [comment]
Duplicate of https://github.com/modxcms/revolution/issues/3934
