### ISSUE TITLE
connection charset and collation not always made available on install/upgrade

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#4576]
netprophet created Redmine issue ID 4576

When installing and specifying the name of a database that does not exist (in MySQL), the connection test passes but no list of charsets/collations is made available. Proceeding uses, it is assumed, the defaults defined by the database server.
This has been seen on upgrade as well, details to come.

**Comment by rtripault** [comment]
Closing as old without activity from the op ;p

Feel free to comment/reopen if needed.
Thanks

#modxbughunt
