### ISSUE TITLE
Image TV preview thumbnail does not appear

### ISSUE THREAD

**Issue by paramaniac** [modxcms/revolution#4578]
paramaniac created Redmine issue ID 4578

It seems that when I upload and select an image using an image TV, before I click on Save, the thumbnail preview is shown. The url to the preview img is: */connectors/system/phpthumb.php?h=150&amp;w=150&amp;src=uploads/images/treework1.jpg*

But when I save the resource and then edit it again, the thumbnail preview is not there. Looking at the source code, the url for the preview img has changed to: */connectors/system/phpthumb.php?h=150&amp;w=150&amp;src=uploads/images/treework1.jpg*
Which does not work. I presume it's because the ampersands are encoded, IE: *&amp;* instead of *&*

I think this may be the cause of the issue in my case anyway.

Also I notice that it takes ages for a thumbnail to be created in the filemanager itself. I upload an image and it shows in the filebrowser but blank/white without a thumbnail. After maybe 10-15 seconds the thumbnail appears.

**Comment by adamwintle** [comment]
This seems like it could have originally been a phpThumbs issue or a server issue and not a MODX Core issue.

@modxbot close
