### ISSUE TITLE
Renamed Chunk Does Not Refresh Tree

### ISSUE THREAD

**Issue by johnywhy** [modxcms/revolution#4581]
johnywhy created Redmine issue ID 4581

When you open an existing chunk, change the name, and click save, the Resources Tree does not refresh.

**Comment by adamwintle** [comment]
@garryn @OptimusCrime I just checked and it seems that this bug is there resent, do you think it'll be an easy one to fix?

**Comment by OptimusCrime** [comment]
I changed my mind, this is indeed a bug and it should be fixed.

However, I have no idea how to do this. Perhaps there are some ExtJs wizards out there that could take a look at it?

**Comment by wuuti** [comment]
#modxbughunt still confirmed

**Comment by Finetuned** [comment]
"I'm going to try and fix this today."
