### ISSUE TITLE
Parsing problem with placeholders

### ISSUE THREAD

**Issue by theuros** [modxcms/revolution#4588]
theuros created Redmine issue ID 4588

i have some problems to get parsed id in my chunk... i don't know if this is revolution problem or getResources problem.. well let me give you an example

I use getResources to list some resources .. to display them i use this chunk:
<pre>
<a href="[[~[[+id]]]]"><b>[[+pagetitle]]</b></a>
<p>[[+introtext]]</p>
<form action="" method="post">
  <input type="hidden" name="addtocart[[[+id]]]" value="1" />
  <input type="submit" value="to cart" />
</form>
<hr />
</pre>

when i submit, instead of getting  [4] => 1  i get [addtocart]] => 1
then i added another input field   <input type="hidden" name="test[[[+id]]]" value="1" />

the result was:
[test]] => 1 
[addtocart]] => 1

then i corrected  "test[[[+id]]]" to "test[ [[+id]] ]" and print_r($_POST) gave me:
<pre>
Array
(
    [test] => Array
        (
            [ 4 ] => 1
        )

    [addtocart] => Array
        (
            [4] => 1
        )

)
</pre>
in this case i got the [[+id]] parsed right... but if i use three [[[ then i get an error ... well this error occures only if you want to post data as array.

**Comment by rtripault** [comment]
So closing. Feel free to comment/reopen if needed.
Thanks
