### ISSUE TITLE
TV - Resources

### ISSUE THREAD

**Issue by jgulledge19** [modxcms/revolution#4589]
jgulledge19 created Redmine issue ID 4589

I have 1200 pages and will have like 8K when I get done importing all of my pages into MODX.  I am using a Resources TV and from that it builds the appropriate side links.  It is getting to be impossible to select one from the drop down.

Some ideas for improvement:
*  Use the same click and point option that is used for  the Parent
* Order by the menuindex and for sub folder use a "-" so like this:
> * folder
> * - folder
> * - - folder
> * - - - file
* Allow the type ahead feature like in the listbox - that is a great feature

Thanks

**Comment by adamwintle** [comment]
I think there is an AJAX typeahead TV type now, so you don't need to load all of the TVs into the DOM.

**Comment by OptimusCrime** [comment]
Like @adamwintle said, this is fixed in more modern versions of modx.

Closing this because of age. Feel free to reopen or comment.

@modxbot close
