### ISSUE TITLE
Add active and added user dates

### ISSUE THREAD

**Issue by bravado** [modxcms/revolution#4591]
bravado created Redmine issue ID 4591

Add date fields to database when user was made active and date when user was added to system.  Sometimes the dates will differ on when a user was added versus when they were made active.  Having this information available will greatly help in managing users in the system.  :)

**Comment by whitebyte** [comment]
This issue itself is a duplicate of #4055

**Comment by whitebyte** [comment]
...and should be closed in favor of #11472.

**Comment by rtripault** [comment]
While not entirely "duplicate" of #11472, i'm closing this one in favor of mentioned issue.

Please feel free to add your voice/comment there.

Thanks
