### ISSUE TITLE
More Consistent Interface Features

### ISSUE THREAD

**Issue by johnywhy** [modxcms/revolution#4598]
johnywhy created Redmine issue ID 4598

Intuitively, users expect consistent behaviors across whole app.
Architecturally, code-reuse is efficient.
Therefor, give similar parts of interface the same features/behaviors:

* Drag/Drop on all trees
* Field-Collapse on all object editors (to bring code-editor to top. Currently just on documents)
* "Add File" and "Add File Here" in Modx File Manager
* Quick Update for all objects
* etc

Opportunities for code-reuse!

**Comment by adamwintle** [comment]
Is this still relevant? The MODX UI has been pretty good since 2.3.x

**Comment by adamwintle** [comment]
@modxbot close`
