### ISSUE TITLE
Suggestion for file manager: Button to check if file is already in use on site.

### ISSUE THREAD

**Issue by yoleg** [modxcms/revolution#4640]
yoleg created Redmine issue ID 4640

This feature request came directly from a client who has MANY files on the server and likes to keep them organized. He loves the file manager that MODx provides, but does not like the fact that moving, renaming, or deleting a file or folder causes it to break accross the entire website. 

He came up with a simple suggestion based on his past experience with Wordpress: add a button to the file manager that will tell you if (and where) the file is in use on the site.

The easiest way to do this might be to add a link next to each file that redirect to the manager's existing search page with a query for occurrences of the file name.

**Comment by adamwintle** [comment]
There is a new Uber Search box at the top which lets you search all Elements and Resources, additionally the new MODX Browser has a filter feature at the top so you can quickly find files you need. 

For files which are not inside MODX, I'd suggest using another tool, or if possible search via the command line. 

Overall there's lots of ways to find files and Elements within MODX now.

@modxbot close
