### ISSUE TITLE
Display All Objects That Reference Chunk

### ISSUE THREAD

**Issue by johnywhy** [modxcms/revolution#4668]
johnywhy created Redmine issue ID 4668

In Chunk editor, above the content editor, display list of all objects that currently use this Chunk. Could also be done with Templates, snippets, TV's, and other objects.

This would be a huge aid to developers!

**Comment by OptimusCrime** [comment]
The Uberbar somewhat does this.

**Comment by rtripault** [comment]
Uberbar (search bar) does not do this, but http://modx.com/extras/package/moddevtools might fit the requirement (as mentioned in #11683). So closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by johnywhy** [comment]
i have not used modDevTools, but it appears to to the inverse of this request. i think modDevTools lists objects used by the object. I'm requestring to see objects that use the object.

http://docs.modx.pro/en/components/moddevtools#Features
