### ISSUE TITLE
Autohide Tree Pane

### ISSUE THREAD

**Issue by johnywhy** [modxcms/revolution#4672]
johnywhy created Redmine issue ID 4672

less clicking for users.
optional, in system settings.

**Comment by whitebyte** [comment]
If a final "wontfix" decision has been taken, this issue should be closed

**Comment by johnywhy** [comment]
amdbuilder commented on Jul 27, 2014
"If anything give us the option to lock it open."

Agreed. But why can't we have both? Option to auto-hide AND option to lock. Why is one preference superior to the other. Why must the work style SOME prefer be forced on EVERYONE?

Some commenters here say their "clients" will be confused. Ok, but some of us are working with clients, or maybe our clients never touch the back end. 

I don't see this as either/or. No one has yet responded to my request for auto-hide to be made an OPTIONAL SETTING. No one here has explained how making auto-hide an OPTIONAL SETTING will affect your workflow. IT WON'T.

**Comment by whitebyte** [comment]
@johnywhy, i agree. There is also an option to make sidebar "pinnable", add some button to enable/disable autohide
![pin](https://cloud.githubusercontent.com/assets/7704186/5593406/3bbacf0c-922e-11e4-9b18-5e0c9f109c8a.jpg)

**Comment by whitebyte** [comment]
Something like this
![pinned](https://cloud.githubusercontent.com/assets/7704186/5593412/e7f199a4-922e-11e4-99ca-202a41a466c7.png)

**Comment by rtripault** [comment]
I'm somehow torn on that one : 

1. i agree with the majority on the fact **i** find that behavior counter intuitive
2. developers/editors should be able to do so (personal taste)

I guess that should not be part of the core, but rather some kind of extra.

Auto hiding/expanding the left area can be done fairly easily with a plugin, bound on `OnBeforeManagerPageInit` event, loading a JS file with the following (minimalist) content : 

```js
Ext.ComponentMgr.onAvailable('modx-leftbar-tabs', function(west) {
    // West region (left area) is available, let's add a few convenient methods
    Ext.apply(west, {
        _onCollapse: function() {
            var split = Ext.get('modx-leftbar-tabs-xcollapsed');
            if (!split) {
                // No "collapse button", let's try again in a few ms
                Ext.defer(this._onCollapse, 250);
                return false;
            }
            var me = this;
            // Add a single listener to expand the left area when hovering the "collapse button"
            split.addListener('mouseover', function() {
                me.expand(true);
            }, me, {
                single: true
            });
        }

        ,_listenForMouseLeave: function() {
            var me = this;
            this.body.addListener('mouseleave', function() {
                // Defer the collapsing, eventually develop a way to cancel the collapsing
                Ext.defer(function() {
                    me.collapse(true);
                }, 500, me);
            }, me);
        }
    });

    west.on('afterlayout', west._listenForMouseLeave, this, {single: true});
    west.on('collapse', west._onCollapse);
});
```

So i'm voting to close that one.

**Comment by OptimusCrime** [comment]
Well, in that case. +1

**Comment by johnywhy** [comment]
Thanks for the plugin script. Great!

**Comment by johnywhy** [comment]
@rtripault Are those listeners running constantly during user-session?

**Comment by rtripault** [comment]
@johnywhy the listener set on the left area body (`_listenForMouseLeave`) is constantly running, the listener to show the left area is running the left area is expanded (then applied back when the left area is collapsed)

**Comment by rtripault** [comment]
I'm not sure CSS would be faster/less resource intensive than JS, but feel free to give it a try (my attempt at building it in JS was just because i felt curious on how i could achieve that with ExtJS...).

So instead of loading the JS file in your plugin, just load your stylesheet

**Comment by johnywhy** [comment]
thx
