### ISSUE TITLE
Change inline styles to CSS class in the manager 

### ISSUE THREAD

**Issue by lossendae** [modxcms/revolution#4675]
lossendae created Redmine issue ID 4675

All the panels and titles (h2) set lots of styles manually in MODExt.
It cause inconsistencies in alignements and upgrade more than difficult.

The solution : use CSS classes that can be edited once and re-used anywhere whitout breaking the actual design.
That can also allows better mgr styles guidelines in the future.

**Comment by whitebyte** [comment]
AFAIK it is impossible to totally get rid of inline styles in (modx)EXT, so this issue can't be "resolved" at least until 3.0. Suggest closing for now.

**Comment by rtripault** [comment]
Knowing the original poster (and his ExtJS skills), i bet the original intent was to suggest to stop/prevent using "ExtJS styling properties/attributes" (like https://github.com/modxcms/revolution/blob/master/manager/assets/modext/core/modx.js#L292 -- `bodyStyle: 'padding: 15px'`).

While the Revo 2.3 default theme might be a lot better than it used to be, i still feel this issue as relevant, especially since manager themes became "first class citizen".

**Comment by exside** [comment]
also think it's still relevant, there are still a lot of "inline" styles around!

**Comment by OptimusCrime** [comment]
Pretty sure it will be next to impossible to get all these weird Extjs-styles in embedded files.

**Comment by rtripault** [comment]
Removing all inline styles set by default ExtJS core behavior (thinking layouts... ie., while resizing the browser viewport) would indeed be impossible (or a real pain).

Not using what i would call "styling attributes" in modExt is definitely doable.

**Comment by OptimusCrime** [comment]
True, I still fail to see the real benefit of doing this. Of course it is cleaner, but it would require a lot work.

**Comment by rtripault** [comment]
To me, the benefit is that it would ease the process of customizing a manager (especially since Revo 2.3 handles custom manager themes way better than it used to).

Overriding a stylesheet is way easier than inline style!

**Comment by exside** [comment]
definitely agree and sometimes its very annoying to track down some css issue, finding nothing in the SCSS files and the having to crawl trough all responsible ExtJS code to see if some styling attributes were set there...

**Comment by OptimusCrime** [comment]
Yeah, I agree with that. Just saying this is not something that should have a high priority.

**Comment by adamwintle** [comment]
@jpdevries @OptimusCrime What are your thoughts on this now?  Is this actually going to be worked on or shall we close this?

**Comment by OptimusCrime** [comment]
I am not sure about this. Like to mention @exside as well. He did some work on the updated MODX theme. Perhaps be knows.

**Comment by jpdevries** [comment]
@adamwintle my thoughts are this would be a nice improvement.

Furthermore, it is absolute nonsense we are still using ExtJS in MODX 3.0 and any incremental improvements we make to make the modEXT less painful good be better put towards a working on a HTML-first "4.0" or "MODX Next" manager that rely on ExtJS or any other scripts.

We've been spending time for years solving problems that shouldn't have happened in the first place. Given the freedom of breaking changes I think we should start solving the root issues.

**Comment by adamwintle** [comment]
@jpdevries Wait. What!? Since when was MODX 3.0 going to continue using ExtJS?! When was that decided and by who?

**Comment by jpdevries** [comment]
@adamwintle keep in mind that 3.x is basically 2.x with composer and what the community had been thinking of as "3.x" is really 4.x or "MODX Next" now. At MODXpo 2015 @rthrash presented the minor breaking changes to make MODX work with composer and was asked by @isaacniebeling if we could drop ExtJS in 3.x and we were told ExtJS will remain in 3.x.

**Comment by OptimusCrime** [comment]
Leaving in ExtJS makes sense for 3.x. Removing that would crash every single extra ever written for Revo.

We have dubbed the version you are thinking about for MODX Next (working name for now). Nothing has been decided when it comes to the MODX Next manager, so just forget about that for now ;)

**Comment by adamwintle** [comment]
Ah okay, I was just thinking the *next* version was going to be 3.x because it's after 2.x.  Jumping ahead to 4.x for MODX Next is really confusing IMO. Anyway this is getting off topic :)

**Comment by jpdevries** [comment]
@OptimusCrime if there is a 4.x or "MODX Next" roadmap soon to follow that gets the tech stack more up to date I completely agree. If "MODX Next" isn't something that will see the light of day until 2017 or 2018 I think this is a serious issue. ExtJS 3.x has been irrelevant even in the ExtJS community for over four years and it prevents us from having a fat-finger or touch friendly manager experience which is _kinda_ important these days.

Meanwhile the Wordpress admin works on a phone with JavaScript AND webfonts disabled.

This is why roadmaps and communication are important. If the community was more aware of the plans with 3.x and given enough time to make those front end changes then there would have been a chance MODX 3.x wouldn't be shipped in 2016 with a front end stack from 2010. So here's a question. What's the MODX 4.x roadmap and where can people go to start contributing?

And yes, this is getting off topic. We should probably move this discussion to another issue or Slack if needed.

**Comment by adamwintle** [comment]
@jpdevries I'd like to discuss this, +1 for a new Github issue so everything is permanently logged.

**Comment by OptimusCrime** [comment]
@jpdevries I've been talking with @opengeek about MODX Next. He wants 2.5 done first, followed by 3.0, then work on MODX Next will begin. I hope it will not take that long. Perhaps we will see something in Q2 this year.

**Comment by jpdevries** [comment]
@OptimusCrime I guess what I don't understand is why we can't have teams making progress on independent projects. Anyone familiar with how Apple was historically split into Apple II and a Macintosh teams? One to work on the legacy tech, one to pioneer something new.

Why can't we organize something like that? Community members have been eager to start breaking ground since the LLC first started teasing thoughts of a "new manager" back at MODXpo 2012. We've been told to "hurry up and wait" for too long now.

**Comment by OptimusCrime** [comment]
Yeah, I know. I agree. I'd love to see more about MODX Next as soon as possible. No matter how little.

**Comment by opengeek** [comment]
@jpdevries Get me an Apple salary and resources and I'll show you some teams!

**Comment by jpdevries** [comment]
@opengeek fair enough. You can get the community an official place to contribute to the construction of MODX Next, no salary, and we'll show you what we can do though! If there are particular areas the LLC needs assistance with let us know but I think our best form of contribution is time, not money.

**Comment by rtripault** [comment]
OK, let's just close this one... ( :wave: @lossendae)

Feel free to comment/reopen if needed.
Thanks
