### ISSUE TITLE
Clean up language files and remove duplicates

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#4686]
gadamiak created Redmine issue ID 4686
- The language files in @core/lexicon/en@ contain duplicate entries and entries no longer used.
- Some entries (judging by their index) are replaced by others eg. @recent_docs@ is used instead of @activity_title@, @info@ is used in place of @yourinfo_title@.
- Entries are assigned to files based on topic or template, but this is not consistent eg. @dashboard@, @default@ and @welcome@ all contain entries used in welcome template.

This leads to confusion and should be re-organized or combined into one file. The indexes should be reviewed and their (mis)use corrected. Duplicates should be removed.

Attached is a list of duplicates as of revision f5bafbe.

**Comment by Mark-H** [comment]
Based on the date this was a discussion in the early days of Revo. At this point changing the lexicon format is a non-trivial task, but it's definitely worth drafting guidelines for MODX 3 on structuring lexicons and using a consistent voice. That's something that would also be different per language, possibly. 

For now I'm closing this issue as there is no immediate solution.
