### ISSUE TITLE
Custom alias path from root

### ISSUE THREAD

**Issue by MadeMyDay** [modxcms/revolution#4710]
mademyday created Redmine issue ID 4710

2.1. introduced a great improvement with its possibility to define individual alias paths. But it would be perfect if one would be allowed to define them from  root like "/my/path/to/document".

Why I would need this:

I have alias paths on. They work fine for me for most of my structure. But some content is deeply nested in some parent folders which I don't want in my URL path. 

- folder1 (domain.com/folder1 <- fine)
-- subfolder1
-- subfolder2 (domain.com/subfolder2 <- fine)
-- subfolder3
--- subsubfolder1
---- subsubsubfolder1 (domain.com/subfolder3/subsubfolder1/subsubsubfolder1 <- I'd like to manually change to domain.com/subsubsubfolder1)
----- document (domain.com/subfolder3/subsubfolder1/subsubsubfolder1/document <- this should get automatically domain.com/subsubsubfolder1/document)
--- subsubfolder2

So what I mean is: If I could enter "/subsubsubfolder1" for the document and the children inherit this path, everything would be perfect. But at the moment it is only possible to add another folder since the trailing slash is deleted on save.

**Comment by adamwintle** [comment]
@MadeMyDay I think this can now be achieved using the Freeze URL feature so I'm going to close this. @modxbot close
