### ISSUE TITLE
Manager Page Refresh

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#4761]
michaelm created Redmine issue ID 4761

Basically... no more full page refreshes of the manager.

ie currently in 2.1.0 b4 : Selecting a document from the tree, either right / left clicking to edit, triggers a full page refresh to open the document for editing.  In my environment, that's 25 resources to load (watching through firebug) and then executed - including the ext etc.

I can't think of any reason why extjs would need to be reloaded and executed, and for that matter, any of the modx core (modx-min.js), although you would lose the url changing in the manager.  Yet I would still prefer a quicker backend to a back button.  This will eliminate the flashing on the page as everything gets re-rendered, and speed up the manager considerably.

If there are deeper issues here, please disregard.

**Comment by OptimusCrime** [comment]
Pretty sure a fully ajax driven manager will not happen with Revo. It is just too big of a task to begin implementing that now.

Because of the age and the many changes the backend has seen since 2012 I am closing this issue.

Feel free to reope or comment.

@modxbot close

**Comment by whitebyte** [comment]
FWIW, there is an extra called AjaxManager that partially implemets, well, ajaxification of manager.
