### ISSUE TITLE
Resource Group Tree View

### ISSUE THREAD

**Issue by neilness** [modxcms/revolution#4780]
neilness created Redmine issue ID 4780

The resource group panel needs some work to become more user-friendly.

At the very least, the ID of the resource should be displayed next to the title.

It would be helpful if it reflected the parent/child tree layout in the resources pane, but I can see how that layout might be problematic, for instance if an intermediary resource is not part of the group.

The referenced resource (or it's parent, if closed) could also be highlighted in the resource pane on hover.

**Comment by inreti** [comment]
IDs already shown there (as of 2.4.0). Parent/child shown in resources pane (right side), but not in resource groups panel (left side).

Close?

**Comment by rtripault** [comment]
There indeed has been some work since the report, so closing.

Feel free to comment/reopen if needed.
Thanks
