### ISSUE TITLE
Menu Fails At Reduced Zoom Size

### ISSUE THREAD

**Issue by johnywhy** [modxcms/revolution#4786]
johnywhy created Redmine issue ID 4786

When viewing manager at reduced font-zoom size (set via browser view or tools menu), there is padding or margin at the top of the first item in each drop down menu. When mouse hovers over that gap, the menu closes.

**Comment by whitebyte** [comment]
The target version of original redmine issue was 2.0.8. Issue is no more actual (tested for 2.2.14 and various 2.3.x), suggest closing.

**Comment by rtripault** [comment]
This indeed seems to be better handled, so closing.

Feel free to comment/reopen if needed.
Thanks

**Comment by johnywhy** [comment]
rtripault commented:
"This indeed seems to be better handled, so closing."

Better how?

**Comment by rtripault** [comment]
With/because of a massive rework of the default manager style-sheets since Revo 2.3 ?

**Comment by johnywhy** [comment]
great! thx
