### ISSUE TITLE
Restrict access to the "(empty)" template

### ISSUE THREAD

**Issue by Martijn1981** [modxcms/revolution#4791]
Martijn1981 created Redmine issue ID 4791

Hi,

I'd like to gain complete control over the template dropdown field and its content. I want to restrict access to certain templates for certain usergroups, _but_ that would also include the "(empty)" template! I can't currently access it.

I'd love to able to edit/remove this "template"!

**Comment by rtripault** [comment]
Closing as "duplicate" of #9558 (more activity in the mentioned issue)

Feel free to comment/reopen if needed.
Thanks

#modxbughunt
