### ISSUE TITLE
Error Logging in InvokeEvent

### ISSUE THREAD

**Issue by shamblett** [modxcms/revolution#4808]
shamblett created Redmine issue ID 4808

In the InvokeEvent method the following code block is used :-

$msg= $plugin->process($eventParams);
                    $results[]= $this->event->_output;
                    if ($msg && is_string($msg)) {
                        $this->log(modX::LOG_LEVEL_ERROR, '[' . $this->event->name . ']' . $msg);
                    } elseif ($msg === false) {
                        $this->log(modX::LOG_LEVEL_ERROR, '[' . $this->event->name . '] Plugin failed!');
                    }

Why is the contents of $msg an error if its not false? From a plugin say on webpageprerender this is just the rendered page, the same as $this->event->_output; MODX dumps these errors in the error log repeatedly, what the purpose of this line if its not a bug?

**Comment by OptimusCrime** [comment]
Not 100% sure about this, but $msg will store the output from the process-call to that plugin. If the plugin for some reason fails, Modx will return false. If it does not fail, the variable will not be false. Duing the check in the if, it will always pass if the value is not false.

I don't think this is an error.

Would anyone else like to explain?

**Comment by rtripault** [comment]
I guess this is related to PR #11594. So i'm closing this one and encourage the discussion in the mentioned PR.

If you feel that is a mistake, please, feel free to comment/reopen.
Thanks
