### ISSUE TITLE
Suggested patch to be able to use :empty and :notempty output modifiers as conditions with :then and :else

### ISSUE THREAD

**Issue by hwmaier** [modxcms/revolution#4812]
hwmaier created Redmine issue ID 4812

Currently (Revo 2.0.8pl) the _empty_ and _notempty_ output modifiers are for string use only and cannot be used in conjunction with _:then_ and _:else_.

However it would be convenient to do so, for example:

<pre>
[[myTestSnippet:empty:then=`snippet returns false`:else=`snippet returns true`]]

[[+placeHolder:notempty:then=`class="something"`:else=`class="nothing"`]]
</pre>

The following patch for modoutputfilter.class.php allows to use these also in conditions but retains the string use as well:

Line 360:

<pre>
                    case 'default':
                    case 'ifempty':
                    case 'isempty':
                    case 'empty':
                        /* Returns the input value if empty */
//start added
                        $condition[]= intval(empty($output));
//End added
                        if (empty($output))
                            $output= $m_val;
                        break;

                    case 'ifnotempty':
                    case 'isnotempty':
                    case 'notempty':
                    case '!empty':
//start added
                        $condition[]= intval(!empty($output));
//End added
                        /* returns input value if not empty */
                        if (!empty($output))
                            $output= $m_val;
                        break;

</pre>

**Comment by sebastian-marinescu** [comment]
I'm surprised this seems to be still an issue :( 

In a chunk I'm trying this: 

```php
[[*tvField:isnotempty:and:isnot=`defaultValue`:then=`
  <something />
`]]
```

And it's not working. I also tried ":or:" instead of ":and:",
but this doesn't seem to matter. 

Anyone else can confirm this is still a bug?

**Comment by hwmaier** [comment]
This never was a bug.but a suggested enhancement which since I originally posted the suggestion in 2011 was simply never adopted.

**Comment by ilyautkin** [comment]
You can use modifier `eq` or it alias:
```
[[+placeHolder:eq=``:then=`Empty`:else=`Not empty`]]
```

For default value you can use modifier `default`:
```
[[+placeHolder:default=`defaultValue`]]
```

Is new modifier `empty`/`notempty` still required? If no, we can close issue.

**Comment by Jako** [comment]
empty/notempty are already there. They are not created as conditional output filter and it would be strange to change them to work this way (too).

**Comment by ghost** [comment]
We need to be careful to not get too convoluted with these output modifiers. They are nice, and handy for quick conditionals. But anything beyond that and they start to seriously degrade performance. I've seen it happen, and a simple dedicated snippet made a dramatic difference.
