### ISSUE TITLE
Inconsistent 'Duplicate' command behavior

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#4834]
gadamiak created Redmine issue ID 4834

Duplicating a resource behaves inconsistently when used via context menu in resource tree and via a button on resource edit form. The former opens a dialog with option to include children resources and setting title for a duplicate and allows to cancel duplication. The latter issues warning about all child resources being duplicated and creates new resource. User is presented with a form for a new resource and if cancels edition an empty untitled resource is left.

Both should have the same behavior of the former (there was an issue for it), ie. context menu command.

**Comment by OptimusCrime** [comment]
Good point, +1.

**Comment by ByteJamRob** [comment]
This one might need to be recategorized as a bug. When I use the "Duplicate" button to copy a resource, it never copies the children of the original resource, even though it shows a warning that states it is going to copy all resources. 

This issue does not exist when right-clicking on the resource in the tree and duplicating it that way. It does copy the children in this scenario.

I have confirmed this in Revo 2.4.0, 2.4.2, and 2.5.0.

**Comment by sonicpunk** [comment]
Another issue - when you have children that are hidden from the resource tree, like when using the Collections extra for example.  Clicking duplicate on the parent resource will not duplicate the children if they are not shown in the resource tree. Also the checkbox option for duplicating children does not show up in the modal.

It seems that duplicating children only works with resources that are actually shown in the resource tree.

**Comment by RinzeVanDerBrug** [comment]
Confirmed for MODX 2.5.5. #modxbughunt

**Comment by JonikUl** [comment]
Confirmed for MODX 2.7.0
![duplicate](https://user-images.githubusercontent.com/18344088/52857607-1cf58b00-3141-11e9-910d-04069bc5770a.gif)
