### ISSUE TITLE
Tab rank with (categorized) TVs can't be modified

### ISSUE THREAD

**Issue by Martijn1981** [modxcms/revolution#4855]
Martijn1981 created Redmine issue ID 4855

I've just encountered this bug on a brand new 2.1 pl installation.

I've been using a few TVs with a certain template and I always put them in categories. Now, when I go into Form Customization and want to modify the tab rank of different TVs in 1 category.... nothing happens. The order stays the same.

**Comment by rtripault** [comment]
Probably related to #6604 and old one, so closing.

Feel free to comment/reopen if needed.
Thanks

#modxbughunt
