### ISSUE TITLE
install error modx advanced (mssql)

### ISSUE THREAD

**Issue by samz** [modxcms/revolution#4887]
samz created Redmine issue ID 4887

Then I install try to install modx in the same db twice with another prefix.

Installation Summary

Errors were encountered during core installation. Please review the installation results below, correct the problems and proceed as directed.

    Successfully created table for class modAccessAction

    Successfully created table for class modAccessActionDom

    Successfully created table for class modAccessCategory

    Successfully created table for class modAccessContext

    Successfully created table for class modAccessElement

    Successfully created table for class modAccessMenu

    Successfully created table for class modAccessPermission

    Error creating table for class modAccessPolicy

    Successfully created table for class modAccessPolicyTemplate

    Successfully created table for class modAccessPolicyTemplateGroup

    Successfully created table for class modAccessResource

    Successfully created table for class modAccessResourceGroup

    Successfully created table for class modAccessTemplateVar

    Successfully created table for class modAction

    Successfully created table for class modActionDom

    Successfully created table for class modActionField

    Successfully created table for class modActiveUser

    Error creating table for class modCategory

    Successfully created table for class modCategoryClosure

    Error creating table for class modChunk

    Error creating table for class modClassMap

    Error creating table for class modContentType

    Successfully created table for class modContext

    Successfully created table for class modContextResource

    Successfully created table for class modContextSetting

    Successfully created table for class modElementPropertySet

    Error creating table for class modEvent

    Successfully created table for class modFormCustomizationProfile

    Successfully created table for class modFormCustomizationProfileUserGroup

    Successfully created table for class modFormCustomizationSet

    Successfully created table for class modLexiconEntry

    Successfully created table for class modManagerLog

    Successfully created table for class modMenu

    Successfully created table for class modNamespace

    Error creating table for class modPlugin

    Successfully created table for class modPluginEvent

    Error creating table for class modPropertySet

    Successfully created table for class modResource

    Error creating table for class modResourceGroup

    Successfully created table for class modResourceGroupResource

    Successfully created table for class modSession

    Error creating table for class modSnippet

    Successfully created table for class modSystemSetting

    Error creating table for class modTemplate

    Error creating table for class modTemplateVar

    Successfully created table for class modTemplateVarResource

    Successfully created table for class modTemplateVarResourceGroup

    Successfully created table for class modTemplateVarTemplate

    Error creating table for class modUser

    Error creating table for class modUserProfile

    Error creating table for class modUserGroup

    Successfully created table for class modUserGroupMember

    Error creating table for class modUserGroupRole

    Successfully created table for class modUserMessage

    Successfully created table for class modUserSetting

    Error creating table for class modWorkspace

    Successfully created table for class registry.db.modDbRegisterMessage

    Successfully created table for class registry.db.modDbRegisterTopic

    Error creating table for class registry.db.modDbRegisterQueue

    Successfully created table for class transport.modTransportPackage

    Error creating table for class transport.modTransportProvider

    Could not find the active workspace.

    Error saving the default admin user.
    Array ( [0] => 00000 [1] => [2] => )

**Comment by OptimusCrime** [comment]
I suggest closing as this either is an isolated issue, or because of the age. This is most likely fixed in later versions

**Comment by OptimusCrime** [comment]
Closing due to no answer for neither the original poster, nor anyone else that might have experienced this issue.

If this is in fact still happening, feel free to reopen and/or comment here.

@modxbot close
