### ISSUE TITLE
getFeed, and caching issues

### ISSUE THREAD

**Issue by AgentShark** [modxcms/revolution#4902]
agentshark created Redmine issue ID 4902

As discussed here: http://modxcms.com/forums/index.php?topic=55422.0

getFeed uses the core RSS reader (magpieRSS) which has default cache settings that have nothing to do with the site cache; it caches the feed data locally for a default amount of time (3600 seconds or 1 hour). This needs to be improved and made configurable.

**Comment by rtripault** [comment]
Closing since this is related to a [third party component](https://github.com/modxcms/getFeed), and not the core.
