### ISSUE TITLE
package manager doesn't fit on small screen

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#4933]
goldsky created Redmine issue ID 4933

I'm having a problem on using the manager on my small screen laptop (1024x768 px).

The package manager doesn't have vertical scroll bars, so I miss some buttons.

**Comment by rtripault** [comment]
Yes, some efforts has been made since the new 2.3.0 manager theme, so closing.

Feel free to comment/reopen if needed.
Thanks
