### ISSUE TITLE
Published setting behavior for duplicated contexts is undesirable

### ISSUE THREAD

**Issue by bmilton** [modxcms/revolution#4948]
bmilton created Redmine issue ID 4948

Set "publish_default"  to "Yes" in system settings.
Duplicate an exisiting context which has a resource that is set as published.

Expected behavior is that the resources in the new context will be set as published, but they are actually set as not published.  This forces manual publishing of all resources again when want was really wanted was an exact duplicate of the context.

**Comment by rtripault** [comment]
I concur duplicating should "mirror" the source state. Maybe adding an option to offer to : 

* unpublish all resources
* publish all resources
* keep publish state

could be a possibility/feature request.
All in all, closing.

Feel free to comment/reopen if needed.
Thanks
