### ISSUE TITLE
getTree does not get all Container values

### ISSUE THREAD

**Issue by mts7** [modxcms/revolution#4973]
mts7 created Redmine issue ID 4973

When using getTree (as referenced in http://rtfm.modx.com/display/revolution20/modX.getTree ), even with specifying a valid depth, not all containers are displayed in the tree.  For instance, I have a page that has a parent line with 5 parents, though when I execute getTree with the first parent value, I only get children down to 3 more values.  When testing the resource IDs closer to the original page, getTree works sometimes, and not others.

**Comment by Flowan** [comment]
Confirmed this does not work correctly in 2.5.x #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by OptimusCrime** [comment]
@Flowan Could you please narrow down the actual problem a bit more? The description is a bit lose here, not really easy to understand what is wrong here.

**Comment by wuuti** [comment]
@flowan @mts7 @sean69 Can anyone please give a more detailed description how to reproduce the behaviour with a small and easy testcase?

**Comment by OptimusCrime** [comment]
@wuuti It could be related to this #8430?

**Comment by JoshuaLuckers** [comment]
I decided to solve this issue and #8430 but I didn't manage to reproduce it.
Even with the changes mentioned in the (probably) related issue the outcome of getTree stays the same in my case.

**Comment by alroniks** [comment]
Issue fixed, please, have a look at #14002
