### ISSUE TITLE
Package management

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#4974]
onepack created Redmine issue ID 4974

I was wondering why my site had taken so much space on the server and starting searching trough the directories to find out that 70 MB was taken by older packages that were even not used anymore. TinyMCE had 5 versions and took most of the space.

Can this be changed? What is the underlying reason to keep all the transport zip and unzipped packages of all the versions available in the file system. If I have a 1 year old site and update on a regular basis how big would this become?

**Comment by adamwintle** [comment]
@onepack @rthrash A better title for this issue could be "Option to remove old packages to save server storage space" or something along those lines.

**Comment by onepack** [comment]
I have closed all my modx cases between 2010 and 2012.
This one is from 2011! and @adamwintle I agree that the name could be different but it is now more than 4 years later and I have no expectations anymore from logging cases for modx and seeing them "resolved".
So I will close this one as well and if someone still thinks it is valid, please create a new case.
I still work with modx sometimes but have stopped logging cases for it.
