### ISSUE TITLE
Stuck console window after successful package update

### ISSUE THREAD

**Issue by gerritvanaaken** [modxcms/revolution#4975]
gerritvanaaken created Redmine issue ID 4975

Package updates work a bit better now in 2.1.1, but not completely flawless. 

I started the update process for getpage 1.1.0, and after successfull installation, the "console running …" window is still there, grey faded and blocks the rest of the manager.

I have to reload the browser window.

**Comment by whitebyte** [comment]
Was also actual for some 2.2s, but I never see this with 2.3.x. @gerritvanaaken , would you mind checking again with the latest version?

**Comment by TheBoxer** [comment]
Closing for long inactivity. Feel free to reopen with more details.
