### ISSUE TITLE
Make top menu changes persistent

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#4978]
gadamiak created Redmine issue ID 4978

Any changes to top menu are reset to default on upgrade. It would be useful if menu customization were persistent. This could be achieved by using form customization (renamed to "manager customization" I guess).

**Comment by rtripault** [comment]
I believe we are good to close this one since an option is possible (and the lack of feedback).

Feel free to comment/reopen if needed.
Thanks
