### ISSUE TITLE
Customize top menu per user group

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#4979]
gadamiak created Redmine issue ID 4979

Whether menu item is displayed or not is resulting from permissions. If user has no permissions for 'content types' the corresponding menu item is hidden. However, it's not possible (is it?) to hide menu item which corresponds to action the user _has permission_ to.

My editors must be able to change content type for resources thus they have content type permission. But this gives them access to content type definitions in menu, which I don't want them to. I want them to be able to assign content types but not to define them.

It should be possible to customize menu per user group. I think form customization should be extended to allow this, or use a way similar to resource groups. Customization should be persistent and not affected by upgrade (see #4978).

**Comment by rtripault** [comment]
Closing as it is now possible to build custom menus (see #11858)

Feel free to comment/reopen if needed.
Thanks

#modxbughunt (but not counting since 9PM)
