### ISSUE TITLE
Target Security notices to product versions: Revo or Evo

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#4980]
wshawn created Redmine issue ID 4980

I would also suggest a "default" page to be added to simply point to a list of security issues if there are none less than 30 days of age.

It gets kind of old looking at an Evolution issue from January, when I run exclusively Revo

**Comment by wshawn** [comment]
Evo is still appearing in the 	
http://feeds.feedburner.com/modx-announce feed.

**Comment by pixelchutes** [comment]
While Evo does appear in the [modx-announce](http://feeds.feedburner.com/modx-announce) feed *(the MODX News Feed)*, closing this issue targeting security notices, per [resolved in 2.3.1](https://github.com/modxcms/revolution/blob/330020a20f81d1614925c370fd407d85fef6abd1/setup/includes/upgrades/common/2.3.1-feed_modx_security.php).

This was the point when the Revo specific security feed was introduced: http://forums.modx.com/board.xml?board=294
