### ISSUE TITLE
Quick Create and Keyboard Shortcuts

### ISSUE THREAD

**Issue by Optiki** [modxcms/revolution#4994]
optiki created Redmine issue ID 4994

 When using Ctrl+Shift+N to Fast Create Resources it opens the pop-up fine, but when you hit "Save", the window stays open, and each time you click "Save", it creates another resource with the same name, so you end up with multiple resources in the background ?!

**Comment by rtripault** [comment]
Here (Chrome/Linux) the shortcut is Ctrl+Shift+Alt+N, and the quick create window is properly closed when hitting save button. So closing.

Feel free to comment/reopen if needed.
Thanks
