### ISSUE TITLE
No $scriptProperties['children'] on event OnResourceUndelete

### ISSUE THREAD

**Issue by pureppl** [modxcms/revolution#5004]
pureppl created Redmine issue ID 5004

OnResourceDelete has $scriptProperties['children'] but OnResourceUndelete not.

**Comment by pbowyer** [comment]
The PR has been merged, this ticket can be closed #modxbughunt

**Comment by rtripault** [comment]
Thanks, so closing...

Feel free to comment/reopen if needed.
Thanks

**Comment by rthrash** [comment]
This issue has been mentioned on **MODX Community**. There might be relevant details there:

https://community.modx.com/t/discrepancy-in-event-triggering-when-deleting-undeleting-resources/4952/2
