### ISSUE TITLE
Have all Package Management Links transformed into target="_blank"

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#5022]
wshawn created Redmine issue ID 5022

It can really break up the workflow to click these links and be thrown to the docs site, and have to start over when we return.

I utilize a jQuery method on my sites. I am unfamiliar with related functionality with ExtJs.

**Comment by whitebyte** [comment]
Related issue: #4036

**Comment by rtripault** [comment]
What about using the browser feature to open in new tab/window instead ? (usually using `ctrl`, `alt` or `shift` keyboard key + click; or right clicking the link + pick the desired behavior)
