### ISSUE TITLE
Add 'disabled' field state in FC set

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#5048]
gadamiak created Redmine issue ID 5048

It would be useful to be able to disable a field via FC while leaving it visible to user. It could be a checkbox like for field visibility.

This can have many applications, one being show default value but not allow to edit it, the other to inform a user he is not authorized to change the field. Also when setting default values for resource/update its confusing for users to see they can change field value but the changes be gone on reopening a resource.

**Comment by gpsietzema** [comment]
Duplicate of thise one #5511

@modxbot close
