### ISSUE TITLE
Upgrade doesn't remove not applicable system settings

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#5054]
gadamiak created Redmine issue ID 5054

System settings, which are no longer applicable because they were removed or replaced are not removed from DB on upgrade.

For example @compress_*@ and @concat_*@ settings got no longer apllicable as of "introduction of on-the-fly CSS/JS compression":https://github.com/modxcms/revolution/commit/08652b3a6a22c0a209bf8143ec633eed04f10b9e but they still sit in DB after upgrade. This leads to confusion.

**Comment by rtripault** [comment]
I guess this is mostly due to being backward compatible (some other components/extras might rely on "deprecated" system settings). So gonna close this one.

Feel free to comment/reopen if needed.
Thanks
