### ISSUE TITLE
No image preview available when Image TV's Base Path/URL is not the endstation

### ISSUE THREAD

**Issue by Martijn1981** [modxcms/revolution#5056]
Martijn1981 created Redmine issue ID 5056

Let me explain this more clearly. I've setup an Image TV with the following settings:

Base Path: assets/files/Producten/
Base Path Relative: Yes
Base URL: assets/files/Producten/
Base URL Relative: Yes

Now, the "Producten" directory contains multiple subdirectories. For example, a subdirectory called "Welding". When I choose an image through the Image TV: the proper URL is visible: Welding/000591_Trolley.jpg and the image is perfectly visible at the front-end, but there's no Image Preview just beneath the TV itself.

This does not happen with another Image TV of mine, which only uses the Base Path & URL asset/files/Nieuws/ and does not contain any further subdirectories.

**Comment by rtripault** [comment]
Closing since this is no more relevant since Media Sources where introduced.

Feel free to comment/reopen if needed.
Thanks
