### ISSUE TITLE
Create link to weblink when resource is a weblink

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#5081]
bertoost created Redmine issue ID 5081

It would be great when I enter

````
<a href="[[~[[+id]]]]">[[+pagetitle]]</a>
````

That the link also will be made to the weblink and not to the internal url.

I saw in documentation that it would be redirected and that works fine, but why?

Regards, Bert

**Comment by Mark-H** [comment]
There's a setting to link to the weblink target. I don't think MODX could prefill [[+pagetitle]] without making major assumptions about what you're doing, so I'm gonna close this issue.
