### ISSUE TITLE
Improvement: Extension package initialize reposition

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#5093]
ReSpawN created Redmine issue ID 5093

As suggested more detailed in the following topic (http://modxcms.com/forums/index.php/topic,65886.new.html), the main idea is to provide a wider range of MODX functionality in the extension packages (lexicon and sessions, scripts being registered after the MODx.load functions and so on).

This is a big improvement for future development of, amoung others, VisionCart.

**Comment by rtripault** [comment]
Closing since you now can rely on `OnMODXInit` event if you want all initialized.

Feel free to comment/reopen if needed.
Thanks

#modxbughunt
