### ISSUE TITLE
intermittent disappearance of Access Policies

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#5148]
netprophet created Redmine issue ID 5148

This has been reported in the forums, e.g.
http://modxcms.com/forums/index.php/topic,60314.msg373166.html#msg373166

Seems mostly reported in 2.0.x but could still be lurking.

Need to investigate whether install/upgrade could potentially remove access_policy_template_groups records.

**Comment by wuuti** [comment]
#modxbughunt cannot be reproduced due to way old version. Definitely happens not in recent versions, if the policy templates and policies are as they should.

Can be closed.

**Comment by rtripault** [comment]
Closing due to the lack of activity in the issue :D

Feel free to comment/reopen if needed.
Thanks
