### ISSUE TITLE
Using removeObjectContainer() on package uninstall

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#5184]
bertoost created Redmine issue ID 5184

I would like to remove the database tables when I remove my package.

I tried this into my table resolver inside the 'build' script.

<pre>
case xPDOTransport::ACTION_UNINSTALL:
    $modx =& $object->xpdo;
    $modelPath = $modx->getOption('mycmp.core_path', null, $modx->getOption('core_path').'components/mycmp/').'model/';
    $modx->addPackage('mycmp', $modelPath);
    
    $manager = $modx->getManager();
    
    $manager->removeObjectContainer('mycmpData');

break;
</pre>

But that gives me an error on removal

**Comment by rtripault** [comment]
It's been a while, so closing the issue!

Feel free to comment/reopen if needed.
Thanks
