### ISSUE TITLE
Allow in-line editing in FC sets grid

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#5225]
gadamiak created Redmine issue ID 5225

FC profiles grid allows in-line editing of name and description for a profile. FC sets grid doesn't. It would be useful to allow editing of at least description field for a set in FC sets grid. Ideally all fields would be editable in-line: action, description, template, constraint. That would speed up working with FC.

**Comment by ilyautkin** [comment]
Confirmed for MODX 2.7.0

**Comment by smg6511** [comment]
This has been implemented in 3.0, both for the Profiles and Sets grids.
