### ISSUE TITLE
resource/update doesn't mark resource as modified

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#5227]
gadamiak created Redmine issue ID 5227

When using FC resource/update with default values to override user input the resource is not marked as modified upon edit and the save button is inactive. The user has no clue that changes have been applied and resource requires to be saved.

**Comment by rtripault** [comment]
Closing since it is no more relevant (save button is no more disabled).

Feel free to comment/reopen if needed.
Thanks
