### ISSUE TITLE
Allow multi-value constraint in FC

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#5230]
gadamiak created Redmine issue ID 5230

It will be very useful if constraints in FC can contain multi-value. ATM only one constraint field-value pair can be assigned to a set. Managing FC sets will be easier and simpler if multi constraints are possible. I guess JSON can be used to store the constraint.

**Comment by Mark-H** [comment]
Added in 6c07d38f4ca3e5728e6fe94e1bf9ebed8b3bcd40 per #11239
