### ISSUE TITLE
modX::makeUrl() recursive depth array args

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#5235]
bertoost created Redmine issue ID 5235

I have found a bug in the $args parameter of makeUrl(). The third parameter accepts an array to add key value pairs to the URL to generate, wich works fine, but I use "getPage"  snippet and I have made a filter form with checkboxes. The visitor can check there filters to finetune the page results, also works fine.

My query string looks like "?filters[43][]=1&filters[43][]=2&filters[54][]=3"

The problem occurs when using this kind of request parameters. The navigation links are not binding this because it's a multiple recursive array instead of a simple key value pair. Maybe this could be fixed in the modX::makeUrl() ?

I don't know if this is working in 2.1.x

**Comment by pbowyer** [comment]
Close as failed to reproduce and no updates for 6.5 years #modxbughunt

**Comment by rtripault** [comment]
So closing...

Feel free to comment/reopen if needed.
Thanks
