### ISSUE TITLE
Event for duplicating context > saving resource

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#5245]
bertoost created Redmine issue ID 5245

It would be great if there will be an event fired on the time someone duplicates a whole context, for every duplicated resource...

The event (like: OnContextDuplicateResource) should have at least 4 parameters
- The old context object
- The old resource object
- The new context object
- The new resource object

This is usefull when using Babel plugin for example. Then it will be possible to automatically keep tracking on the translated resources...

**Comment by gpsietzema** [comment]
Feels like something we don't really use in MODX, unless you do some weird stuff we do too sometimes (duplicating resources). Discussed it in Slack and we think you should just script this (the way you do it now) and it shouldn't be in the core.

Just re-open if you feel different :)

@modxbot close
