### ISSUE TITLE
System Process overwrites/overrides User Setting

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#5254]
wshawn created Redmine issue ID 5254

If I set up a welcome_screen setting for users, forcing them to look at another welcome url upon login, it takes on the same functionality as the system variable - it only works once.

I would prefer to have it left per the setting of true, forcing them to view it every time once it is at the level of a user setting.

**Comment by rtripault** [comment]
Confirming that the user setting override does its job, so closing (tested with current develop branch -- upcoming Revo 2.4).

Feel free to comment/reopen if needed.

Thanks.

**Comment by rtripault** [comment]
Sorry, i have been to prompt to close this : the welcome message indeed displays... until you log out (user setting is set as `false`, but remain as `true` in session... until you log back)

**Comment by wshawn** [comment]
Agreed to close. Widgets are better suited for this.
