### ISSUE TITLE
If updating a TV Listbox another Listbox is set to default.

### ISSUE THREAD

**Issue by Expanism** [modxcms/revolution#5281]
expanism created Redmine issue ID 5281

I have set up 3 Listbox TV's (New products / Used products / Product of the month) and assigned the TV's to the home template.
From the back-end the client can choose from 3 Listboxes to populate content on the home page.

When update only one TV Listbox the other two are being set to their default when saving.

_TV Listbox - New products_
Input Option Values:
@EVAL return $modx->runSnippet('getResources', array( 'parents'=>'1001,1002,1003','hideContainers'=>'0','includeContent'=>'1','depth'=>'10','tpl'=>'newProductsList','context'=>'web','limit'=>'0', 'includeTVs'=>'1','processTVs'=>'1','sortby'=>'editedon','sortdir'=>'DESC'));

_TV Listbox - Used products_
Input Option Values:
@EVAL return $modx->runSnippet('getResources', array( 'parents'=>'1013,1014,1015','hideContainers'=>'0','includeContent'=>'1','depth'=>'10','tpl'=>'usedProductsList','context'=>'web','limit'=>'0', 'includeTVs'=>'1','processTVs'=>'1','sortby'=>'editedon','sortdir'=>'DESC'));

_TV Listbox - Product of the month_
Input Option Values:
@EVAL return $modx->runSnippet('getResources', array( 'parents'=>'1022,1023,1024','hideContainers'=>'0','includeContent'=>'1','depth'=>'10','tpl'=>'productMonthList','context'=>'web','limit'=>'0', 'includeTVs'=>'1','processTVs'=>'1','sortby'=>'editedon','sortdir'=>'DESC'));

**Comment by wuuti** [comment]
#modxbughunt 
Also cannot reproduce with 2.5.5-pl. close?

**Comment by OptimusCrime** [comment]
@modxbot close
