### ISSUE TITLE
Equals Sign in Parameters Breaks Entire Chunk (nested only)

### ISSUE THREAD

**Issue by yoleg** [modxcms/revolution#5296]
yoleg created Redmine issue ID 5296

This problem is very particular to a particular nesting structure:
1. I use a chunk called [[[[$box]]]] to form a stylistic HTML wrapper around content. For example, [[[[$box? &amp;class=`blue` &amp;content=`Hello there`]]]] results in a fancy box with a class and content as specified - this is very important to my design (so I don't have to use three different chunks for $box_start,$box_middle, and $box_end). The content of $box is:
   
   <pre>
   <div class="box[[+box:default=`1`]] [[+class]]"><div class="c"><div class="b">[[+content]]</div></div></div>
   </pre>
2. I put another chunk (a widget) inside of the box: <pre>[[$box? &content=`[[$widget]]`]]</pre> 
3. Finally, if (in the content of $widget), I place any snippet with a parameter containing an equals sign, it breaks the box. In other words, set the content of $widget to something like below to break the box: 
   
   <pre>
   <div>[[!Wayfinder? &startId=`0` &test=`=`]]</div>
   </pre>

On the other hand, changing it as follows results in a working box:

<pre>
<div>[[!Wayfinder? &startId=`0` &test=`something else`]]</div>
</pre>

Equals signs come up quite a bit in snippet parameters (especially in lists that require == for a separator), so this effectively prevents me from using my fancy HTML wrapper around certain output.

An interesting fact is that putting the content DIRECTLY into the box's content parameter does not cause the problem. In other words, the following code works just fine:

<pre>
[[$box? &content=` <div>[[!Wayfinder? &startId=`0` &test=`=`]]</div> `]]
</pre>

**Comment by EasterPeanut** [comment]
Tested this on MODX 2.5.5. If called uncached like this -> [[!$box? &content=`[[$widget]]`]] it does not break and work as expected; the Wayfinder is shown. #modxbughunt

**Comment by rtripault** [comment]
So let's close this one.
Feel free to comment/reopen if needed.

Thanks
