### ISSUE TITLE
File Tree collapses on presentation of file contents

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#5297]
wshawn created Redmine issue ID 5297

Please leave it in its expanded state.

**Comment by adamwintle** [comment]
The file tree stays open when editing files in 2.4.2, so it looks like this is fixed - can you guys confirm?

**Comment by jpdevries** [comment]
I've got a client on 2.3.5 that when they click to edit a resource the tree doesn't remember its state. All the folders are closed. Does this sound like the same issue described here?

**Comment by wshawn** [comment]
jpdevries, I believe that is the behavior I described in the original bug report.

**Comment by jpdevries** [comment]
@wshawn I see. It is so strange. I downloaded the production site and installed it locally and I can't reproduce the issue locally. It's a mystery this one.

**Comment by wshawn** [comment]
@jpdevries This is an old issue. I seem to recall the browser had something to do with it, but five years is five years.

**Comment by jpdevries** [comment]
I can reproduce it on this particular install in any browser, but I think this is a mysterious bug.

**Comment by gpsietzema** [comment]
This happens in 2.5.5-dev. Is related to this one: #13234

**Comment by gpsietzema** [comment]
Therefore, will close this one.

@modxbot close

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @gpsietzema
