### ISSUE TITLE
Empty TV tabs not removed when moving fields

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#5335]
bertoost created Redmine issue ID 5335

I think I've seen this isse quite some times but in MODx 2.1.3 it is still there;

When I have created a new tab in Form Customization and move all fields from a category to the new tab; the tab is still there below the "TV" tab. Should be great when a TV sub-tab is empty he's not shown at all!

**Comment by rtripault** [comment]
Duplicate of #4241, so closing.
