### ISSUE TITLE
Resourcelist with parents across multiple contexts

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#5365]
onepack created Redmine issue ID 5365

I have run into the issue that I can assign resources to a resourcelist from multiple contexts but selecting the resource from another context results in a wrong url.

I have the resource paris.html only in the main domain.com and not in the sub.domain.com
www.domain.com/paris.html

When I'm working on a resource in the sub.domain.com and choose to link to resource paris.html in the main head context the url will render like the following:

www.sub.domain.com/paris.html

Output filter as URL or Default don't make any difference in the resourcelist TV.

**Comment by rtripault** [comment]
If you need absolute URLs, you could use the `[[~id? &scheme=`full`]]` syntax. So closing.

Feel free to comment/reopen if needed.
Thanks
