### ISSUE TITLE
Permissions not fully working

### ISSUE THREAD

**Issue by SebastienDaniel** [modxcms/revolution#5374]
Askarii created Redmine issue ID 5374

I created a new user, with all resource management permissions, but no "element" permissions, though he can list and  view the elements.
Upon editing a "chunk" and saving I get: "Permission Denied" message.
However, the change is still saved and applied to the website.
I cleared cache and flushed all sessions, the change remains.

**Comment by adamwintle** [comment]
@SebastienDaniel I hope you got this fixed within the last five years!  If you have problems with this type of thing again can you post on the Forums or the Slack chat at http://modx.org and people form the community will help you setup the persmissions

@modxbot close
