### ISSUE TITLE
Using the margins property in layout override any CSS fix

### ISSUE THREAD

**Issue by lossendae** [modxcms/revolution#5384]
lossendae created Redmine issue ID 5384

The main modx layout is using the property "margins" and even if i use an !important clause in my CSS, it's impossible to override it.
The properties set here can be replaced by a simple padding on #modx-content anchor with the same values (0 0 20px 15px).

Ultimately, that only solve the width issue, since the padding is applied on the container, the overflow bar is decaled from 20px on the bottom.
Each main-panel should have a 20px padding on the bottom set on the panel itself, not the container.

**Comment by rtripault** [comment]
Since some efforts have been done on current manager (2.3+), i will assume this is no more relevant, so closing ;)
