### ISSUE TITLE
Freeze URI and some aliases: are case sensitive

### ISSUE THREAD

**Issue by jgulledge19** [modxcms/revolution#5408]
jgulledge19 created Redmine issue ID 5408

If you put in something like Freeze-Uri in the Freeze text box and someone types in mysite.com/freeze-uri they get a 404.  Some of the URLs created via the alias are case insensitive, they seem to be only single containers like: mysite.com/Folder works.  All others are case sensitive.  It would be great if they were all case insensitive.

Easiest way to implement:
# For the Freeze URI to be all lowercase like the alias or have a system setting option to force lowercase URIs
# Use strtolower function for the method that processes the URI before it does a search.

Thanks for reading.

**Comment by gpsietzema** [comment]
@jgulledge19 I think this is already the case :)

@modxbot close
