### ISSUE TITLE
Make a publish option for duplicate contexts/resources

### ISSUE THREAD

**Issue by aladage** [modxcms/revolution#5435]
aladage created Redmine issue ID 5435

When duplicating a context or resource, there is no option to have the new content automatically published. There is currently a system setting for newly created content (publish_default), but it has no effect on duplication.

**Comment by whitebyte** [comment]
Duplication options was added somewhere in 2.2.x, so consider closing.

**Comment by RinzeVanDerBrug** [comment]
Testing this today.

**Comment by RinzeVanDerBrug** [comment]
Tested this in MODX 2.5.5.

After setting publish_default to 'Yes', duplicated contexts DO get published automatically. For resources there is an option now to publish on duplicate anyway, so issue is probably outdated. Can be closed. #modxbughunt

**Comment by OptimusCrime** [comment]
This is a duplicate of the issue #13277

Closing this in favor of that because it has more comments (and a pretty picture).

@modxbot close
