### ISSUE TITLE
Force_empty_paragraph behavior when adding system tags into TinyMCE

### ISSUE THREAD

**Issue by bbeer** [modxcms/revolution#5436]
bbeer created Redmine issue ID 5436

I would love to get a custom solution in Revolution to be able to add snippets, chunks and TV's into TinyMCE  without them being wrapped by a paragraph. There is a Plugin Solution for evo but I was not able to convert it to Revolution. I am also prepared to cover the cost for such a solution.
I am really convinced that this should be part of the core.
Thanks.

**Comment by rtripault** [comment]
Closing since this is related to a [third party component](https://github.com/modxcms/TinyMCE) and not the core.
