### ISSUE TITLE
Auto create folders and controller's files for new CMP/ Namespace

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#5440]
goldsky created Redmine issue ID 5440

I think it will be great if there is a feature that will automatically create folders and controller's file after the developer creates a new CMP/ Namespace

**Comment by OptimusCrime** [comment]
There are multiple extras that does this.

**Comment by rtripault** [comment]
Not only there are extras to hep doing this, but that should not be part of the core, but rather a developer "toolkit". So closing.

Feel free to comment/reopen if needed.
Thanks
