### ISSUE TITLE
Better implementation of creating links in templates/chunks

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#5455]
bertoost created Redmine issue ID 5455

When I have added a weblink or symlink I enter a URL or ID of the page where to link to.
In my templates/chunks I would like to use [[~id]] for generating the links. Only for web and symlinks it would be great if they are linked correctly to the entered URL or ID instead of his own internal URL.

Now it's redirecting when reached a weblink page or on a symlink page the symlinked content is loaded. I can think on things why you would do like this, but maybe a reserved parameter for this is a good solution.

**Comment by Mark-H** [comment]
There's a setting for this, `use_weblink_target`
