### ISSUE TITLE
Resources: Tree view / List view

### ISSUE THREAD

**Issue by maxpiepenbrink** [modxcms/revolution#5494]
mido created Redmine issue ID 5494

For some sections with lot of documents like blogs, news sections, etc. It could be usefull to configure the way the childs will be shown ( in parent settings ). For example, if we click "news" in the tree, instead of show all its childs there, MODX should load a new page with all the documents and options to order, filter and search in a list/grid instead of the tree.
I know we can make folders in the tree to organize documents, and I really love the tree view, but the "list view" can be so helpfull sometimes.

**Comment by adamwintle** [comment]
I still think installing a third-party component such as Collections is the way forward here. @theboxer thoughts?

**Comment by Alroniks** [comment]
+1 for using Collections or other components which can hide children. minishop2 hides goods in categories. No need to make a mess in the tree with several implementations. I suggest to close it as won't fix.
