### ISSUE TITLE
TV input type "textarea" not high enough

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#5512]
mindeffects created Redmine issue ID 5512

TV input type "textarea" is not high enough. RTFM says "about 15 lines", I count only about 8 lines (Chromium 15.x and FF5).

I will also write a feature request for textareas with editable height. Don't want to mix bugs and features. ;-)

**Comment by devlanda** [comment]
I am working on a fix for this issue.

**Comment by pyrographics** [comment]
Not sure if it would be related to this issue or not but is in same ballpark.  If you uncheck "Rich Text" on a resources settings to change a rich text box to a plain text box, a rich text TV correctly turns into a standard textarea but the size is so tiny (one short row) you can't use it and it cannot be resized.

**Comment by OptimusCrime** [comment]
Perhaps worth opening a new issue for this? It does not concern the rich text editor.

**Comment by ilyautkin** [comment]
PR https://github.com/modxcms/revolution/pull/13524 is closed and feature is not implemented yet.
Confirmed for MODX 2.7.0

**Comment by JoshuaLuckers** [comment]
There is a `grow` property that can be set to `true`. If `true` the textarea will be the same height as its content.
