### ISSUE TITLE
TV input type "text" with variable height and optional RTE

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#5513]
mindeffects created Redmine issue ID 5513

I would like to have some kind of clean-up with the TV input type. To many things just to the same thing. That's confusing and irritating. Let's start with "text"-things:

What about an input type "text" where you can define the numbers of lines needed and if you would like a rich text editor or not. Would make things much easier: 6 lines, no RTE, bam. 12 line, RTE, bam. 1 line, no RTE, bam. Sounds very nice to my ears.

**Comment by OptimusCrime** [comment]
This issue is 7 years old soon and has not gained any interest since it was posted. I think the idea is good, but there are other ways to do this. So I am closing this as a wontfix. Feel free to comment or reopen it :)

**Comment by OptimusCrime** [comment]
@modxbot close
