### ISSUE TITLE
Tab rank in FC goes up in increments of 10 every time I save the Set

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#5537]
paramaniac created Redmine issue ID 5537

I am using Form Customization to move all my TVs from the TV tab to the Create/Edit tab.

_Rant_
Shouldn't have to do this because all custom TVs should appear on the bottom of the create/edit tab by default like MODx Evo, why do they appear on their own tab in Revo!!!
_Rant over_

When I use the Tab Rank to order them and then save the FC Set, and then return to the set: via Security > Form Customization > Edit Profile > Edit Set
all the values I put in for tab rank have gone up by 10! Save the Set again and return, and the values have gone up by 10 again!
I have even set all the tab ranks to 0 and it still happens.

**Comment by Flowan** [comment]
This issue remains in 2.5.7 - It's even worse, all rank-values fall back to 0

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by sonicpunk** [comment]
@gpsietzema saw you give the point here live!

**Comment by OptimusCrime** [comment]
This issue is really, really weird. Should definitely be fixed.

**Comment by alroniks** [comment]
Good news! Issue solved and PR is merged.
