### ISSUE TITLE
getOption() on integer property returns a string

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#5598]
bobray created Redmine issue ID 5598

When you call getOption('propertyName', $scriptProperties) and the property is an integer property, you get back a string (at least with plugin properties -- haven't tested with a snippet but I assume it's the same).

So, this code will fail, because getTVValue uses is_string() and assumes that the number is a TV name:

<pre>
$resource->getTVValue($modx->getOption('propertyName', $scriptProperties));
</pre>

This works:

<pre>
$resource->getTVValue( (integer) $modx->getOption('propertyName', $scriptProperties));
</pre>

I think integer-type properties should be ints in the $scriptProperties array.

**Comment by pbowyer** [comment]
@opengeek Is this a bug or a feature?

**Comment by BobRay** [comment]
For the record, I filed this in 2011 before I knew that *all* elements in the $scriptProperties array that come from MODX object properties or properties in the snippet tag are always strings. I think that consistency is probably a good idea.

That said, maybe getTVValue() should consider values that begin with a numeral to be integers, even if they arrive as strings.

**Comment by pbowyer** [comment]
Thanks @BobRay, are you happy for this to be closed (as we're in a drive to get the ticket numbers down)?

**Comment by BobRay** [comment]
Sure. It should really be filed as a new issue on getTVValue() if the problem still exists.
