### ISSUE TITLE
Filemanager icon assignment

### ISSUE THREAD

**Issue by averest** [modxcms/revolution#5624]
averest created Redmine issue ID 5624

would be nice to have the possibility to assign the icons to corresponding filetypes.
So for example the movie icon for .f4v, .mp4, .webm  etc.

**Comment by achterbahn** [comment]
Isn't this issue mostly solved with the font-awsome integration? modfilemediasource.class.php adds a icon-"file extension" (e.g. file-svg) class to every leaf in the tree view.

**Comment by OptimusCrime** [comment]
I agree. In favor of closing this? We have icons for some know file types now at least.

**Comment by rtripault** [comment]
Indeed, furthermore one could come up with her own CSS to handle desired extension(s), so closing.

Feel free to comment/reopen if needed.
