### ISSUE TITLE
Form Customization - TV not loaded if default template set

### ISSUE THREAD

**Issue by herooutoftime** [modxcms/revolution#5643]
herooutoftime created Redmine issue ID 5643

I'm still experiencing this issue with 2.1.2-pl (traditional).

> For example,
> 
> if I define the following Form Customization Set for the resource/create action :
> - constraint => parent
> - value => 3
> - default value of template => 5
> 
> and if I create a child resource under the "resource (3)" the template successfully change in 5 but the TV related are not loaded.

**Comment by GulomovCreative** [comment]
I tested this issue, problem solved. You can close issue.

MODX Revolution 2.6.5-pl
