### ISSUE TITLE
Tree Reloading on Resource Save

### ISSUE THREAD

**Issue by salscode** [modxcms/revolution#5662]
thekiller237 created Redmine issue ID 5662

Would be great if the tree did not have to reload each time a resource is saved. On some of my larger MODX sites, the tree has 3-4k of documents and waiting for it to reload and re-expand each time can waste a lot of time.

**Comment by gpsietzema** [comment]
I'm afraid that can't be done in the current codebase + extjs3. It would be neat to have in a rewritten version of MODX though. If we go on with the UI-rewrite in a later MODX version, this will be on the priority list for sure.

Closing for now. @modxbot close
