### ISSUE TITLE
Language selection on the user profile

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#5668]
goldsky created Redmine issue ID 5668

I think we need a language selection on the user profile and the create new user.

Some people do have multilanguage manager users.
And also we as modx community like to help other non-english developers from the back-end.

**Comment by Devlanda** [comment]
This is not an issue: can be closed. Language selection is on the Manager login page.

#modxbughunt

**Comment by Mark-H** [comment]
It's also possible to set the manager_language in a user(group) setting, so this is possible through those :)
