### ISSUE TITLE
Duplicate alias/URi + lost published info when duplicating contexts

### ISSUE THREAD

**Issue by moniarde** [modxcms/revolution#5684]
moniarde created Redmine issue ID 5684

When duplicating a context, all publishing information is lost when the default behaviour for duplicating resources unpublishes all resources and deletes publishedon, publishedby information. Also, all aliases are now by default duplicated with their partner resources in the alternative context.

Suggest that some effort go into identifying where alias/uri conflicts across contexts exist and providing an alternative that synchronises the alias/uri with its associated parent context. Also, refer to Feature Request #5563 for dealing with Publish information retrieval.

**Comment by rtripault** [comment]
I guess some efforts have been made, since we can know set if we want to keep duplicated aliases. So gonna close this one.

Feel free to comment/reopen if needed.
Thanks
