### ISSUE TITLE
FC constraint class_key for resource/create not working

### ISSUE THREAD

**Issue by juro** [modxcms/revolution#5687]
juro created Redmine issue ID 5687

Setting FC constraint field to "class_key" in resource/create action causes that this set will never apply, i.e. creating resource is not customized.
Resource/modify with the same constraint works fine. Seems that during resource create the class_key is not defined, although it should be.
Works fine for other constraints, e.g. parent.
I need different FC for creating and editing different document classes (document, symlink...).

**Comment by rtripault** [comment]
It's been a while since the issue has been reported (and hopefully fixed), so closing.

Feel free to comment/reopen if needed.
Thanks
