### ISSUE TITLE
RTE toggle on introtext / description

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#5691]
goldsky created Redmine issue ID 5691

Please enable RTE toggle on introtext/description, so we can use that with the right HTML tags.

**Comment by whitebyte** [comment]
Related forum topic: http://forums.modx.com/thread/?thread=30943&page=1
Seems that someone managed to enable TinyMCE for introtext with simple plugin.

**Comment by Mark-H** [comment]
Redactor 2 has this built in through the redactor.loadIntrotext system setting, and after #12632 that will also work on non-document resources. 

I'd like to propose closing this issue as it's something extras can easily provide (either built in like Redactor 2, or via a plugin like this https://gist.github.com/christianseel/780b16f202c873b3b278).

**Comment by OptimusCrime** [comment]
I really, really like this. Nice work @Mark-H

**Comment by OptimusCrime** [comment]
Closing due to possible solution and no feedback in over a year.

@modxbot close
