### ISSUE TITLE
FC Sets: TVs moved to modx-resource-settings panel don't appear on resource/create

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#5701]
jrotering created Redmine issue ID 5701

If you create an FC set for resource/create, and change the tab value for a TV to 'modx-resource-settings', the TV does not show up on the resource settings tab when creating a new resource (with the template and/or constraints specified by the FC set).

To recreate: 
*  Create FC sets for resource/create and resource/update using a template that has a custom TV associated with it.
*  In both FC sets, change the tab value of the TV from 'modx-panel-resource-tv' to 'modx-resource-settings'.  
*  Save the FC sets.
* Create a new resource using the template.  The TV will not appear in the "Create/Edit Document" (resouce settings) tab.
* Save the new resource. After save, when the "resource/update" FC set is applied, the TV should then appear in the resource settings tab.

**Comment by rtripault** [comment]
So let's go close this one.

Feel free to comment/reopen if needed.
Thanks
