### ISSUE TITLE
Synchronize FC sets

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#5712]
jrotering created Redmine issue ID 5712

I've been working with FC sets, and my particular needs usually involve identical pairs of sets - one for resource/create and one for resource/update.  

Keeping changes synchronized between the two sets is a pain in the butt. If I tweak some field names in one set, I have to save, cancel to go back to the FC Profile, edit the other set, and manually make the same changes. (Alternatively I can duplicate the changed set and then change the action & constraint fields on the duplicate, but this isn't any less tedious, especially when making ongoing revisions).

How about an option to synchronize one FC set with another? You'd manually fill out the top fields (Action/Template/Description/Constraint Field/Constraint/Active), and then choose another FC set (from a dropdown) to synchronize all the rest of the customizations with. 

I'm not at all sure of how FC sets work under the hood, but I'm guessing this would involve an onSave action for FC sets, which would look for other sets that had a 'syncWith' value that matched the one that was just saved, and sync them accordingly.

This would be extremely useful IMO.

**Comment by whitebyte** [comment]
Possibly related to #3772

**Comment by Mark-H** [comment]
Dupe of #3772
