### ISSUE TITLE
Customizable resource identifier 

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#5720]
jrotering created Redmine issue ID 5720

Add the ability in FC sets to customize the resource identifier.  Instead of the heading "New Resource" or "New Weblink", allow the user to specify an identifier that helped to theme the custom experience... i.e. "New Meeting", "New Agenda", etc.

**Comment by rthrash** [comment]
Thanks for this suggestion James. Fortunately, this can be achieved in a variety of ways now, including custom Dashboard buttons and via Collections, and FC (or its replacement) should be more flexible and capable post ExtJS.
