### ISSUE TITLE
installer: allow short upgrade risk notices to be shown

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#5725]
netprophet created Redmine issue ID 5725

In order to ensure that users have every opportunity to understand the risks associated with upgrading to a major or point release, it would be beneficial to allow a message to be shown in the installer. It would be best for it to be a short message, with a link to a more comprehensive summary of any breaking changes in the release.

The tricky part here is that this message will likely be translated into the various languages, which is a good thing, but we may not have the breaking change summary translated. This is something that should be discussed prior to initiating a call for translations for 2.2.0

**Comment by OptimusCrime** [comment]
While this is a good point, I think every developer that does these upgrades should double check what problems might arise with the upgrade.

**Comment by OptimusCrime** [comment]
Not a single comment or any interest shown in six years. Closing this. While the idea is good I think changelogs and the blog posts does more or less the same as this message would. 

Feel free to comment or reopen.

@modxbot close
