### ISSUE TITLE
Duplicating resources doesn't keep Published status and changes duplicates names.

### ISSUE THREAD

**Issue by juro** [modxcms/revolution#5802]
juro created Redmine issue ID 5802

When duplicating whole or part of resource tree all duplicated resources are not published. There is no simple way how to publish them at once. There is also no way how to know which were originaly published and which were not.
Maybe there should be option "Keep published status" in Duplicate dialog box.

Another point is that all duplicates have names "Duplicate of..." with the same for alias and URI. So one must go manually across all duplicated resources, edit the name, clear alias and save the resource, so alias and URI are changed respectively. It is enough do change name of the top-most resource only, not the children.
For example if there is resource Product1 with sub-pages Features, Options, Specification, the simplest way to create new product is to duplicate this one, but sub-pages should keep their original names.

**Comment by rtripault** [comment]
There are now some options allowing to define the behavior on published status, so closing.

Feel free to comment/reopen if needed.
Thanks
