### ISSUE TITLE
Automatic Template Assignment System Setting

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#5808]
pixelchutes created Redmine issue ID 5808

In Evolution 1.0.5, a really great feature was added called "Automatic Template Assignment". Would it be possible to bring this back to the Revo core?

As new documents are created, provide a system option to have the assigned template default to: System default template, Parent container template, or Sibling template.  

See forum post here: http://forums.modx.com/thread/31609/default-template-assignment

**Comment by boformer** [comment]
I would like to help with this.

Can anyone hint me to the code that sets the template right now?

**Comment by OptimusCrime** [comment]
Form customization does this

**Comment by Mark-H** [comment]
Looks like current assignments are handled here for new resources https://github.com/modxcms/revolution/blob/develop/manager/controllers/default/resource/create.class.php#L178

**Comment by boformer** [comment]
I checked the source code. 

The template can be altered by plugins. I don't think that there is a need to change something in the modx core code.

Simple plugin that uses a parent TV value:
https://gist.github.com/boundaryfunctions/1474540

A plugin like this (maybe with more options) is missing in the modx Extras Repository.

**Comment by adamwintle** [comment]
Agree with @OptimusCrime @Mark-H and @boformer this is already possible using Form Customers or a custom plugin. @modxbot close
