### ISSUE TITLE
Req: Package Management: notify on updates

### ISSUE THREAD

**Issue by warenhaus** [modxcms/revolution#5811]
warenhaus created Redmine issue ID 5811

copied from: http://forums.modx.com/thread/70571/req-package-management-notify-on-updates#dis-post-394800

The page "System -> Package Management" in the Backend Manager only shows 10 extras per page. This apparently is a forced setting: http://bugs.modx.com/issues/5779

While I lack the technical knowledge about how and when modx.com gets contacted when I open the package management screen, I would like to have an option allowing me to see updateable packages in a more convenient way.

I have 11 packages installed, wayfinder is the only one on page 2, and I didn't notice the most recent update for weeks because I didn't browse to page 2.

Proposal: 

A) have the packages sorted by the status "Updates available" per default

B) show available updates in the welcome screen, like wordpress does.

C) have some e-mail notification on updates

**Comment by inreti** [comment]
A suitable dashboard widget is available as an extra named "Updater". See http://modx.com/extras/package/updater

**Comment by OptimusCrime** [comment]
Guessing that solves it? Feel free to reopen, OP!

Thanks for researching @inreti 

@modxbot close

**Comment by inreti** [comment]
It would still be a good idea to sort the updatable packages to the top. Updater just informs you, but then you will have to use the package manager of course, and you still have the "pagination" problem.
