### ISSUE TITLE
CLI setup complains about no memory limit

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#5836]
gadamiak created Redmine issue ID 5836

The CLI setup checks for memory limit and complains when it's set to @-1@, which means 'no limit'. This is mostly the case for CLI PHP.

See "this post on MODX forums":http://forums.modx.com/thread/70591/how-to-set-paths-for-cli-upgrade#dis-post-394985.

**Comment by rtripault** [comment]
It's been a while since the issue has been reported (and hopefully fixed), so closing.

Feel free to comment/reopen if needed.
Thanks
