### ISSUE TITLE
Add ssl_site_url to System Settings

### ISSUE THREAD

**Issue by lokamaya** [modxcms/revolution#5907]
lokamaya created Redmine issue ID 5907

There are some questions in the forum asking how to set HTTPS/SSL inside MODx. I think this should be resolved in MODx core, not in addon, plugin or else.

I suggested to add some key to system settings (applicable to context setting), there are: _ssl_site_url_, _ssl_manager_, and _ssl_force_ids_. And as part of this, also make little modification to _modx->makeURL_ function.
- ssl_site_url: required if the domain of http and https are different (default: empty)
- ssl_manager: drop_down('all', 'login'). "all" mean force SSL for all manager pages, while "login" mean force ssl only when modx->user->isAuthenticated('mgr') == false.
- ssl_force_ids: if value='all', force all web pages; otherwise it should be comma separated ids (ex. 2,3,4,5).

The important part: modify modx->makeURL function. 
# If ssl_site_url is not empty and different with default site_url, then it should be automagically replaces site_url in the return URL.
# If the $id in ssl_force_ids, or ssl_force_ids=all the schema should be (auto) changed to https--even if set otherwise
# The same rule apply for ssl_manager.
# When ssl_site_url != site_url and the page changes from http to https (or otherwise) the session should be (auto) included in args.

See: 
http://forums.modx.com/thread/14025/how-to-make-a-single-page-in-modx-ssl-secure?page=3#dis-post-396552

Thank you,
@zaenal

**Comment by Devlanda** [comment]
I think this issue can be closed.
The distinction for non-TLS and TLS is less important: TLS is becoming more the standard.

#modbughunt

**Comment by OptimusCrime** [comment]
You're right. There is no need for these system setting either way, as MODX works fine with SSL already.

@modxbot close
