### ISSUE TITLE
When removing file in resource browser, file list does not get refreshed.

### ISSUE THREAD

**Issue by jusmeig** [modxcms/revolution#5932]
jusmeig created Redmine issue ID 5932

Fresh install of MODx 2.1.3pl
PHP 5.3.3
Linux on Apache

Steps to re-create:
When editing an image TV  and launching the resource browser.
Right click on and image and choose Remove File and say OK to prompt.
File is removed with call to: /connectors/browser/file.php
Subsequent call to /connectors/browser/directory.php fails however with the message below:

{"success":false,"message":"Access denied.","total":0,"data":[],"object":[]}

As a result the removed file stays in the view, and if you try to remove again it throws an error.
Problem here in more detail:
http://forums.modx.com/thread/69942/valid-directory-error-with-image-delete?page=2#dis-post-396743

Thanks.

**Comment by whitebyte** [comment]
Not actual for 2.3.2+, remove file option in the TV resource browser works as expected, so suggest closing.

**Comment by rtripault** [comment]
I also wasn't able to reproduce. Chances are that has been fixed since that issue is rather old, so closing.

Feel free to comment/reopen if needed.
Thanks
