### ISSUE TITLE
Don't Go Into Edit Mode on Next Setting On System Edit

### ISSUE THREAD

**Issue by johnywhy** [modxcms/revolution#5943]
johnywhy created Redmine issue ID 5943

When you edit a system setting, "Enter" takes you into edit mode on the next setting in the list.

This is very high-risk for me (i'm clumsy) and my non-expert users (they are non-expert). I have to gingerly escape out of edit mode on the next item, hoping i did not screw something up.

It's an invalid assumption to assume that the admin is going to edit each system setting one after the other, down the list like that. I have never done that. It's always a one-shot deal-- I have to edit just one setting. I edit it, and then i'm done. 

I think it's also invalid to assume users EXPECT the next item to go into edit mode, particularly when it takes two clicks to get into edit mode on the first item, and NO clicks to get into edit mode on the next item. That is not expected. This is not an Excel spreadsheet, and if it was, hitting Enter after editing a cell does NOT take you into edit mode on the next cell in the spreadsheet. 

thanks

**Comment by RinzeVanDerBrug** [comment]
Confirmed issue in MODX 2.5.5. #modxbughunt

**Comment by OptimusCrime** [comment]
Never thought about this. The original issue has a good point.

**Comment by JoshuaLuckers** [comment]
This issue bit me a few times in the past. I tried fixing it but I can't figure out where to look.
Is "press enter to advance to the next row in the grid" this ExtJS functionality?
