### ISSUE TITLE
file manager: new folders not creted in the tv base path

### ISSUE THREAD

**Issue by pandro** [modxcms/revolution#5945]
pandro created Redmine issue ID 5945

the problem is also described here:
http://forums.modx.com/thread/69970/tv-input-type-image-base-path-not-used-when-creating-folder-in-modxbrowser

If I set a base path for a file TV, let's say:my tv "image" has the following base path:
[[++base_path]]images/

When uploading a new file, in the file manager, if I choose "create a folder here" the parent folder is set to root "/".
The user should manually force the parent folder to: "/images/"

It's also an annoying problem becouse users have created hundreds of empty folders in the root path...

**Comment by Flowan** [comment]
Confirmed this does not work in 2.5.x #modxbughunt

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by webinmd** [comment]
In the current version (2.7.1) I can not reproduce this error

**Comment by Ibochkarev** [comment]
Fixed earlier. Feel free to reopen.
