### ISSUE TITLE
default_template setting not used for New (child) Resource

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#5980]
netprophet created Redmine issue ID 5980

When a New Resource is created under a parent Resource via the context menu's New Resource option, the new Resource will default to the same Template as the parent. This may be desirable in some situations, but it is in contrast to the Quick Create option which uses the default_template system setting to set the Template of the new Resource.

See related ticket #5808 describing a new system setting in Evo 1.0.5 which allows the user to control which behavior they would like.

**Comment by adamwintle** [comment]
@netProphET Is this possible with Form Customiser or a custom plugin?

**Comment by gpsietzema** [comment]
Seems to be fixed by Matthew.

@modxbot close

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @gpsietzema
