### ISSUE TITLE
Filter Output

### ISSUE THREAD

**Issue by Pfeifakopf** [modxcms/revolution#6002]
Pfeifakopf created Redmine issue ID 6002

This doesn't work:
[[+url:is=``:then=`[[+company]]`:else=`<a href="http://[[+url]]" target="_blank">[[+company]]</a>`]]

On this it works:
[[+url:is=``:then=`[[+company]]`:else=``]]
[[+url:isnot=``:then=`<a href="http://[[+url]]" target="_blank">[[+company]]</a>`:else=``]]

The placeholder [[+company]] is just placed in the URL-Filter-Output, not before in the chuck.

**Comment by adamwintle** [comment]
Was this for Revo or Evo? Take a look here an check the examples https://rtfm.modx.com/revolution/2.x/making-sites-with-modx/customizing-content/input-and-output-filters-(output-modifiers)

I don't think this is a core issue and this issue can be closed?

**Comment by OptimusCrime** [comment]
I agree.

Feel free to comment or reopen this issue.

@modxbot close
