### ISSUE TITLE
Description field on resource tabs

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#6005]
jrotering created Redmine issue ID 6005

Through Form Customization, it would be really neat if there was an option to display a brief descriptive blurb at the top of any tab.  I have some categories of TVs that this would be useful for - rather than scanning through the list of TVs and their descriptions, if a user first saw a blurb that said "These options are for X and do not need to be modified unless you are concerned with X".

**Comment by rtripault** [comment]
Considering the activity on the issue, i guess we are good to close as "won't fix".

Feel free to comment/reopen if needed.
Thanks
