### ISSUE TITLE
Package Manager needs dependency resolution

### ISSUE THREAD

**Issue by zachofalltrades** [modxcms/revolution#6006]
zachofalltrades created Redmine issue ID 6006

I have encountered packages that would not function correctly without having some other package also installed. For example: prettyGallery will not function without the 'if' package and the Gallery package. The developer points out the dependency on gallery in the readme, but a sanity check like that ought to be built into the package management system itself. A transport package could bundle all dependencies, but that unnecessarily increases the size of all package downloads, and creates some risk that a bundled package will conflict with an older or newer version that is already installed. According to the documentation  http://rtfm.modx.com/display/revolution20/Transport+Packages a developer can include a 'Validator' that would run before a package install. This bug could be worked around if all developers included robust validators in their packages, but the better solution would be to have dependencies listed as part of the package meta-data. That way the dependencies could be listed in the Package Manager GUI, and installation procedures could even the retrieval of the dependencies.

**Comment by OptimusCrime** [comment]
I am pretty sure this is in the works right now?

**Comment by pixelchutes** [comment]
I believe you are correct, a feature slated for v2.4. I have not tested it yet, but think it has already landed in the `develop` branch.

@TheBoxer can speak to the current state of it, and whether or not it would satisfy closing this particular issue?

**Comment by rtripault** [comment]
This indeed will be part of Revo 2.4 (current develop branch), but might need some documentation.

Closing since the feature is "shipped".

Feel free to comment/reopen if needed.
Thanks
