### ISSUE TITLE
Error Msg on drag-n-drop sort on non-Admin policy tpl user

### ISSUE THREAD

**Issue by moniarde** [modxcms/revolution#6016]
moniarde created Redmine issue ID 6016

Receiving error message "A error occured while trying to save the document" when a user not in the Administrators User Group tries to drag-n-drop a resource in the Resource Tree to another location, be it sort within the original container, or change parent to a new container or context. Resource remains in old location on error.

**Comment by Ruslan-Aleev** [comment]
I tried to test, created a user with the "Content Editor" policy and non-Administrators User Group, turned off resource editing, dragging and deleting it in the policy template.
But I can still move resources in the tree, changing the parent, bug for me works completely the opposite.

It requires a clear description of the configuration of access policy to test this issue.

**Comment by Ibochkarev** [comment]
@moniarde I ask you to check this issue for relevance. Thank!

**Comment by alroniks** [comment]
It is a pretty old issue and seems it can not be reproduced in the latest versions, which may mean that it is fixed already. Feel free to reopen if needed.
