### ISSUE TITLE
Share option and filemanager_path and filemanager_url in the processing TV

### ISSUE THREAD

**Issue by spleanter** [modxcms/revolution#6026]
spleanter created Redmine issue ID 6026

If specify both parameters filemanager_path and filemanager_url - to specify a folder, file manager and TinyMCE will fulfill normal. 
However, the derivation of the parameres TV they both will be added before the selected in the file manager by the resource.
In my case - the path to the image in the folder / assets / files / images /.
Example
filemanager_path = assets/files/
filemanager_url = assets/files/
 Output TV (image-default): assets/files/assets/files/images/[.way-to-img.]

REVO 2.1.5-pl

**Comment by rtripault** [comment]
Closing since those settings have been deprecated since Media Sources.

Feel free to comment/reopen if needed.
Thanks
