### ISSUE TITLE
Problem FORM CUSTOMIZATION modx 2.3.1-pl

### ISSUE THREAD

**Issue by jorgehr7** [modxcms/revolution#6038]
jorge@netfactory.es created Redmine issue ID 6038

hello!, i've a problem with form customization when I create a new set using constraint "parent".
For example, the label "Constraint Field" has the value "parent" and the label "Constraint" has the value "4". Then, I uncheked the label isFolder and I uncheked one template variable. In the childs of document 4 everything works nicely, but in the other resources (documents) something strange happens. The label isFolder appears ( as we haven't set any FC ) but the template variable dissapear. It seems that the constraint affect all documents for TVs, and not only the childs of document 4.

Is this a bug or I'm doing something wrong?

Regards,
Jorge

**Comment by rtripault** [comment]
I will assume this is now fixed. If not, feel free to comment/reopen.
Thanks
