### ISSUE TITLE
When renaming assets folder, MODx recreates assets/components/

### ISSUE THREAD

**Issue by chunkyRice** [modxcms/revolution#6079]
chunkyrice created Redmine issue ID 6079

When you alter the name of the assets directory and change the core/config/config.inc.php file accordingly, everything runs fine. But after you install a new package, you will find that MODx added an empty assets/components/ folder. It doesn't break anything and so far I haven't had anything erased from existing assets folders, but it does look a bit sloppy.

**Comment by rtripault** [comment]
I assume this is due to the package setup script. If targeting `assets_path`, folders should be created in appropriate place. So closing.

Feel free to comment/reopen if needed.
Thanks
