### ISSUE TITLE
Manager actions aren't sub-sortable

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#6114]
ReSpawN created Redmine issue ID 6114

When expanding the core Actions listing, you'll see the following

* context (73)
* - context/create (4)
* - context/update (5)
* - context/view (6)
* - - context/create (4)
* - - context/update (5)
* - - context/view (6)

When you right click the first context/update (5), is automaticly selects the one in the context/view (6) tree. Now, looking at a private component, we see the same behaviour but even more chaotic.

* providers (79)
* - provider/update (85)
* - reviews (83)

reviews (83) isn't even sorted under the providers (79), so it seems something goes wrong in the parenting and even then it would be more desirable to keep it clean by only showing children under it's parent or even acenstor and not all of them again in the root of the Actions tree (under the designated namespace). Taking into account that the modActions database scheme has a parent label, this would be accomplished fairly easy.

I'm not sure if this is a improvement or bug or if it's minor or trivial, but this can confuse beginner programmers. :)

**Comment by rtripault** [comment]
Since actions have been deprecated, i assume this is no more relevant. So closing.

Feel free to comment/reopen if needed.
Thanks
