### ISSUE TITLE
Force Package Removal after Uninstall fails (console buggy as well)

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#6128]
ReSpawN created Redmine issue ID 6128

I installed Quip only to uninstall it again (just to test, no offense :P) and the uninstall console didn't go away. The OK button was also disabled, so I had to close it with the X. Not a big problem, but strange.

After that I directly, without refresh, tried to force remove the package from the FTP but the Remove Package window was like a mario block, I kept hitting it without anything happening. A quick refresh did the trick because after a fresh pageload it worked like a charm.

**Comment by Mark-H** [comment]
There's a force remove option for when uninstall fails. If this issue is still relevant, please reopen.
