### ISSUE TITLE
Context ACLs are extremely buggy

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#6135]
ReSpawN created Redmine issue ID 6135

I created an 'api' context for a project and of course I forgot to grant anonymous and admin rights over it, so I kept getting a Page Not Found error.

When correcting the problem under anonymous, I found that the administrator recieved the api ACLs 2 times, twice as a Member - 9999 and never as a Super User - 0. Fine as that may be, it's still bugged if I'm correct. So, I only wanted the admin to have Super User rights, so I firstly removed both of the context because the add-popup said there was already a ACL with that context. I know, 2 of them! :)

After removing them, I'm not able to add the ACL for the context because the window says the context does not exist, though it appears in the drop down. >.<

**Comment by adamwintle** [comment]
This sounds like MODX wasn't originally being setup properly, this issue is also almost 5 years old and is most likely fixed in the latest versions. If you still have the issue can you post more details and we can re-open the issue.

@modxbot close
