### ISSUE TITLE
RichText TV "Set to Default" Not Working

### ISSUE THREAD

**Issue by pixelchutes** [modxcms/revolution#6222]
pixelchutes created Redmine issue ID 6222

RichText TVs with a default value are not able to be reset (e.g. Set to Default) when editing a Resource. Clicking "Set to Default" seems to do nothing, leaving the current TV value present. The only way I've been able to get this to work is by disabling the TinyMCE plugin first (which defeats the purpose of the RichText TV)

_NOTE:_ I debated whether or not this bug should be filed here, or under TinyMCE given that it's related to a 3PC. Ultimately, I decided this issue may be best addressed here under the context of "RichText TVs" -- not necessarily limited to TinyMCE down the road.

FYI, this is using most recent stable TinyMCE (4.3.1-pl)

**Comment by rthrash** [comment]
Hey Mike is this one still valid with the newer version of TinyMCE? Have you been able to reproduce the behavior with other RTEs?

**Comment by pixelchutes** [comment]
Yes, still an issue with new TinyMCE. Also an issue with Ace.

As I understand it, it might not be possible based on the way the RTEs get loaded (iframed, etc). I think Jason mentioned more specifics about the reasoning, but I could be wrong.

Perhaps there could be an alternative approach, where if an RTE is active for a given TV, perhaps the "default value" could be presented somehow, allowing for copy & paste? *(grasping at straws here...)*

**Comment by wuuti** [comment]
#modxbughunt is this a modx problem or a rte extra problem? 

@Mark-H is this an issue with redactor tvs?

**Comment by pixelchutes** [comment]
It's mostly an RTE problem (definitely TinyMCE, and also Ace), I'd presume also Redactor assuming it can be used for TVs (I've not used, but super easy to test/confirm.)

**Comment by Mark-H** [comment]
It does sound like it would be something in the RTEs. No doubt also affecting Redactor. If the underlying markup changes from an external source, RTEs don't tend to read that. Just the other way around..

**Comment by rtripault** [comment]
So closing as not related to the core.

Feel free to comment/reopen if needed.
Thanks
