### ISSUE TITLE
Allow the Resource/Element trees to be filtered by category

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#6410]
wshawn created Redmine issue ID 6410

This would make life easier on large projects.  In essence allow the display to only reflect a single category or user selectable categories.

**Comment by alroniks** [comment]
I guess this PR solves the described issue (not fully, but at least idea is the same)
https://github.com/modxcms/revolution/pull/13997

**Comment by Ruslan-Aleev** [comment]
@Alroniks Probably we can close this issue.
