### ISSUE TITLE
Small UI Errors (Form Customization)

### ISSUE THREAD

**Issue by Seel-Media** [modxcms/revolution#6432]
seel-media created Redmine issue ID 6432

I'm experiencing 3 small UI erros in the manager:

1) When you add a TV to the modx-page-settings tab there is an empty box with a gray border. (please see image)
2) on the left side of the (date) TV there is some withespace... (please see image)

3) When you set the new system setting "tvs_below_content" to 1, and then you want to hide the TV tab via form customization it's still visible!

**Comment by Mark-H** [comment]
We've been through a few different manager changes since this issue was opened, closing.
