### ISSUE TITLE
Add more robust filtering options for FC set constraints

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#6478]
jrotering created Redmine issue ID 6478

Instead of, or in addition to, the current means of filtering FC sets (constraint field, constraint), it would be very handy to be able to list multiple values.

 I'm currently working on a system where I want certain FC rules to apply where ever the *parent* of the resource has a certain *alias*.  Right now in order to do this I have to copy the FC set, use 'parent' as the constraint, and hard-code the ID of the parent for each new parent resource.

I'm not sure what the best approach would be, but some things I'd like to see:

- allow a comma-separated list of constraint values rather than a single value.
- allow the use of a snippet to return the list of constraint values
- or maybe let the user create a custom query

**Comment by Mark-H** [comment]
Added in 6c07d38f4ca3e5728e6fe94e1bf9ebed8b3bcd40 per #11239
