### ISSUE TITLE
super user can't edit "web users"

### ISSUE THREAD

**Issue by frisco** [modxcms/revolution#6491]
Frisco created Redmine issue ID 6491

In modx 2.1.3-pl and 2.1.5-pl super users can't edit "web users" - users, who have restricted rights for a secured area in the web context. 

I described that thouroughly here:
[[http://forums.modx.com/thread/72710/problem-with-user-management]]

Summary:
modx runs under debian 6 (64bit, kernel 2.6.37 in a xen virtual server under lighttpd 1.4.29 with php 5.2.12 and mysql 5.0.51a (client/server), FURLs enabled with alias paths.

Logging in the managers gives a 302 for redirection, resulting in a time lag of about 75secs - all other redirects, i.e. in the web context, are fast and responsive.

By the first attempt to edit a user after logging in modx jumps to the web context, as the manager URL is like:
/manager?a=49 (without index.php) instead of /manager/index.php?a=49 

and modx jumps to the content page with the id=49

Typing in "/manger" manually solves the problem and modx remains in the mgr context.

I can edit the "web user" then, but the buttons in the upper right corner for saving and so on are missing, and all entries on the first tab (information) and on the third tab (access rights - to which group does the user belong) are empty.

I'd be glad to provide you with more information to track this down and help solving the problem.

Any help is greatly appreciated!

Cheers
Frisco

**Comment by adamwintle** [comment]
This has been fixed, if you get problems with editing users please post on the Forums or the Slack chat at http://modx.org or if you find this bug happens again we can reopen this issue.

@modxbot close
