### ISSUE TITLE
Wrong media source name shown in media browser of File TV

### ISSUE THREAD

**Issue by ncrossland** [modxcms/revolution#6577]
ncrossland created Redmine issue ID 6577

1. Create a media source which points to a subfolder of assets within the Filesystem
2. Set up a TV of type File, which uses the media source you have just created
3. In a resource which uses the TV, click the TV to choose a value
4. The contents of the folder are displayed correctly, but the Media Sources dropdown at the top of left hand column of the file browser shows the default "Filesystem", and the top level of the file tree shows "Files" instead of the defined Media Source folder.

Choosing the correct Media Source from the dropdown results in the display being correct.

**Comment by rtripault** [comment]
I'd say this issue is no more relevant since the Media Source "dropdown" is no more displayed. So closing.

Feel free to comment/reopen if needed.
Thanks
