### ISSUE TITLE
Feature: Quick edit template button when editing resource

### ISSUE THREAD

**Issue by FickleLife** [modxcms/revolution#6585]
ficklelife created Redmine issue ID 6585

It would be great if, when editing a resource, you had a button next to the "uses template" field which took you straight to editing the template itself. 

Would save a lot of time as you now have to see what template is applied, find the template (unfortunate the search in the tree is only for resources and not for elements) which can be a bit tough if there are many and then edit it. All could be done in one click. 

Something trivial but would speed up editing a lot I think!

Cheers

**Comment by greyskymedia** [comment]
Petitioning to close this. #modxbughunt

2.5.5+ addresses the search issue brought up here, so, non-issue. 

The other feature request, link to template" wouldn't work well at smaller screen sizes based on the current default manager skin. Also, adding this sort of link would step outside the intended purpose and expectation of this part of the MODX manager.

In addition, it's really not that difficult to find things in the current versions of MODX.

**Comment by rtripault** [comment]
So, let's close.

Feel free to comment/reopen if needed.
Thanks
