### ISSUE TITLE
Package Management - Usability (1)

### ISSUE THREAD

**Issue by ottogal** [modxcms/revolution#6609]
ottogal created Redmine issue ID 6609

The _View Details_ Button is overlaying the _Installed on_ info in the list of downloaded packages on a 1024 x 768 screen (see attached screenshot).
Why not remove the part "Installed on", just give the date/time?

**Comment by OptimusCrime** [comment]
Suggest closing because of age.

**Comment by rthrash** [comment]
It's still a valid issue, IMO. There's lots of UX wins to be had in the Package Management, and this is certainly one of them.
