### ISSUE TITLE
Change Sort Order by dragging items in the elements tree

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#6654]
onepack created Redmine issue ID 6654

It would be nice feature to automatically change the TV or Chunk order by dragging an element in the elements tree to the desired position.
With the option to turn this functionality on and off in the site settings.

**Comment by adamwintle** [comment]
I think due to inactivity of over a year, and @rtripault's points that TVs are bound to Templates making this difficult within the Element Tree this should be closed. 

@modxbot close

**Comment by onepack** [comment]
I just checked and see that there I have more modx cases open from 2012.
I will go through them and close all of them. No need to keep them open for so long as most of them are not valid anymore after 4 years. I get crazy remarks as, duplicate by newer case, etc etc... D'oh!
