### ISSUE TITLE
Add ability to upload company logo for login screen

### ISSUE THREAD

**Issue by ChrstnMgcn** [modxcms/revolution#6706]
chrstnmgcn created Redmine issue ID 6706

Before our company started using MODX for our client sites, we build a custom CMS for each client. On the login screen we would add the company's logo to give it a more branded feel. We would like to do that using MODX as well. Currently we can simply upload a new file named "modx-logo-color.png" in the /manager/templates/default/images/style/ directory and that would suffice, but upon any updates it would be overwritten. Having a system setting for a logo path would really be a nice feature to have. All of our clients know it's MODX (and they love it), but having their logo there would make it feel like it's theirs.

**Comment by rtripault** [comment]
Let's close this one.

Feel free to comment/reopen if needed
Thanks

#modxbughunt
