### ISSUE TITLE
Unable to select Policy (no list) when adding User Group

### ISSUE THREAD

**Issue by vlijmscherp** [modxcms/revolution#6721]
vlijmscherp created Redmine issue ID 6721

When trying to set Access Permissions on the default 'Filesystem' Media Source (or any new created Media Source), I cannot select a policy. The list is empty

Steps:
1. Update Media Source (filesystem)
2. Add User Group
3. Select User Group & Minimum Role (Administrator / Member - 9999)
3. Try to select Policy -- no can do, the list is empty/there is no list

Screenshots & Screenrecording: [[http://forums.modx.com/thread/?thread=73295&page=1]]

**Comment by wuuti** [comment]
I cannot reproduce the bug. Since 2.2 the manager UI has changed a lot in this section, and according to the forum entries this was due to missing policies and policy templates.
#modxbughunt close.
