### ISSUE TITLE
Media sources hidden or access denied in Resource Manager

### ISSUE THREAD

**Issue by acropia** [modxcms/revolution#6746]
acropia created Redmine issue ID 6746

I updated my two of my Revo installations to 2.2.0-pl2. In one of this installations, the one with ACLs configured, I can not use the Media Sources inside de Resource Browser.

Everthing works OK, except the Resource Browser.

- On the Files tab, everything works OK. I can see and can use the Media Sources.
- In the MODX Browser, via a Static Resource, everything works OK. I can see and can use the Media Sources.
- In the MODX Resource Browser, via TinyMCE, Insert/Edit Image, Browse, it's not OK.

I checked and double checked file system permissions, and MODX acls, but the problem remains. Even the administrator account with all checkboxes in all policies applied, has this same problem.

**Comment by rtripault** [comment]
I guess this has been resolved with #12139, so closing.

Feel free to comment/reopen if needed.
Thanks
