### ISSUE TITLE
TV Saving "Appears"to fail

### ISSUE THREAD

**Issue by AESmith** [modxcms/revolution#6835]
aesmith created Redmine issue ID 6835

If you have a validation error on an existing resource while within a TAB (ie: Template Variables) and then try to save while in the TV Tab all appears to save .. yet not .. The issue is that you a validation error is raised on the Docs tab , yet nothing tells you, you have an error unless you go to the Docs tab to see it.

This is a real head buster if you don't realize what is going on.

Possible Solution: Have a general error be presented in the overlay that was previously "saving" and/or a "error" appended to the TAB label very visibly.

**Comment by rtripault** [comment]
Let's close.

Feel free to comment/reopen if needed.
Thanks
