### ISSUE TITLE
phpThumb / modPHPThumb fails on relative hosts domain

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#6891]
ReSpawN created Redmine issue ID 6891

We are creating a website for a new client which hasn't yet pointer their domain towards the new server. We currenty have that domain plus the IP (duh) in our local hosts file which works fine.

I wanted to create a new phpThumbOf image which failed epicly on all fronts. I lost about 1 hour of debugging when I eventually came to the conclusion that phpThumbOf (or perhaps even modPHPThumb) couldn't find the file due to the server not recognizing the file path. It was going to the wrong server since it didn't have the ip/domain reference in /etc/hosts. We nano'd it, added it and tadaa, dynamicly created path by phpThumbOf and it all works. 

Now, the strange thing, all other thumbnails like in the manager or when adding it to a TV (since it uses system/phpthumb.php) works fine. Perhaps it's going wrong somewhere between frontend dynamic files and backend hardcoded to a php file.

So the question remains, is this a bug or perfectly normal behaviour? A colleague of mine said that perhaps it would be more benneficial if phpThumbOf would resolve the path absolute (thus /home/usr/domains/domain.tld/public_html/ on a DirectAdmin installation).

Again, not sure it's a bug but it's a nice feature non the less.

**Comment by adamwintle** [comment]
This sounds like it was originally a phpThumbs issue and not a MODX Core issue, going to close this for now. 

@modxbot close
