### ISSUE TITLE
A way to make a bulk install in Package Management

### ISSUE THREAD

**Issue by ghost** [modxcms/revolution#6911]
ggedamed created Redmine issue ID 6911

When you first install MODx or when you test packages, it's annoying to have to click "Install" for every single package and then to wait for completion.
I could use checkboxes for every package, a "Install" / "Remove" / "Uninstall" / "Reinstall" all checked packages global buttons.

**Comment by Alroniks** [comment]
Duplicate of https://github.com/modxcms/revolution/issues/5897
