### ISSUE TITLE
modx.class.php may bypass onwebpageinit

### ISSUE THREAD

**Issue by jamestan** [modxcms/revolution#6913]
jamestan created Redmine issue ID 6913

I'm just wondering,
is it possible that modx.class.php bypass modrequest onwebpageinit in handlerequest?
i think i saw the problem in modx.class.php :: sendForward() calling modRequest::prepareResponse

im not sure how its suppose to work, 
how does sendForward works? why is it bypassing onwebpageinit? and why OnLoadWebDocument used all the time?

thank you...

**Comment by rtripault** [comment]
I guess this would be better suited for the [forums](http://forums.modx.com), and since it's pretty old, closing.

Feel free to comment/reopen if needed.
Thanks
