### ISSUE TITLE
Custom resource tree sort order changes menuindex to all resources on drag and drop

### ISSUE THREAD

**Issue by juro** [modxcms/revolution#6976]
juro created Redmine issue ID 6976

Upon selecting any sort order other than menu index in the resource tree, and then changing resource parent or order using drag and drop, menuindex field for all resources in the tree is updated in database reflecting current sort order in the tree. So one can break custom menu index for the whole site by one drag and drop operation. There is no way to undo this. If available backup database can be used to restore menuindex field by comparing resource id.

Background: upon drag and drop operation on the resource tree, ajax operation on the background send array of resource ids reflecting current order in the tree, From the server side this looks like order of every resource have changed, so this change is written to the database (in processor core/model/modx/processors/resource/sort.php).

**Comment by alroniks** [comment]
Seems it fixed by #12462
