### ISSUE TITLE
additional resource id (not only autoincrement)

### ISSUE THREAD

**Issue by blankcheck** [modxcms/revolution#7032]
blankcheck created Redmine issue ID 7032

I believe that additional id for resource other than autoincrement would be very useful.

Now, we have to create resource, check the id and use it in templates, chunks(...) which is problem when developing new functionalities on live sites. This way resource id would have unique name and could be accessed by it. It would benefit team collaboration as well (when database changes are done through api and every dev has his own database).

This field should not be mandatory so the cms users (clients) don't have to enter it for every resource, but devs should have this option.

**Comment by alroniks** [comment]
I am closing issue such as it can be implemented in current design and it produces more questions than answers. 
For having unique ID we should use something like GUID but this ID is very long for using in snippets/chunks calls. Also, it is not solving the issue with synchronization between instances. What if we have different code in two copies with the same unique (second) ID? First or second? Who should solve it?
Do not hesitate to reopen if you disagree.

**Comment by OptimusCrime** [comment]
I see no benefit of another ID, in addition to the auto incremented one. Why would we ever need something like that? 

>This way resource id would have unique name and could be accessed by it. 

The incremented ID is an unique name and the resource can be accessed by it.
