### ISSUE TITLE
isfolder will return nothing if resource is not a folder

### ISSUE THREAD

**Issue by devolute** [modxcms/revolution#7049]
devolute created Redmine issue ID 7049

I have found that 'isfolder' will return 1 if it is a folder, but will return nothing if it is not folder.

This seems contrary to http://rtfm.modx.com/display/revolution20/Commonly+Used+Template+Tags 

I'd expect it to return '0' if it's not a folder. On further investigation it appears that the other tags have the same behaviour. (published, hidemenu, etc.)

I realise that this expectation might be due to my inexperience as a developer, but I think in that case then the documentation could be clearer. I have asked other developers and they too expected 'false' to bring back a value of '0', not nothing.

**Comment by Flowan** [comment]
Confirm this for 2.5.x #modxbughunt 

But if we change this, a lot of checks probably won't work anymore.

**Comment by rtripault** [comment]
Agreed. Changing this might break this. It would probably be better to update the documentation and plan this change for a major release (ie. 3.0)

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by bezumkin** [comment]
xPDO returns boolean `false`, so problem is not here.
```php
var_dump($modx->resource->get('isfolder'));
-> bool(false)
```

I think, MODX tags just can't handle boolean values. If you will check it by Fenom template engine - everything works as expected.
```smarty
{if $_modx->resource.isfolder === false}
    This is not a folder!
{/if}
```

**Comment by OptimusCrime** [comment]
The MODX parser handles everything like strings (I think). That is why true is evaluted as 1.

**Comment by CrazyBoy49z** [comment]
var_dump(false); //return "bool(false)"
print_r(false); //return ""
print_r(true); //return "1"
print_r( false?'true':'false'); //return "false"

php7.2

**Comment by CrazyBoy49z** [comment]
var_dump(false); //return "bool(false)"
print_r(false); //return ""
print_r(true); //return "1"
print_r((int)false); //return "0"
print_r((int)true); //return "1"

print_r( false?'true':'false'); //return "false"

**Comment by alroniks** [comment]
It is not a bug in my opinion. It returns the proper value, but type converted during usage. Need to understand it. I am closing as wontfix. Please, reopen if needed.
