### ISSUE TITLE
User manager policy allows the deletion of users over the role of the policy holder

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#7074]
wshawn created Redmine issue ID 7074

Simply stated a user with a Role of 100 with a User Administrator Policy (not assigned to any Resource Group) can still delete users with roles 0 - 99.  

I believe this needs to be corrected ASAP to only allow the user to administrate roles less than their own. In this case 101 - 9999.

I reported this some time ago in a much earlier version, but can not find it via the search at this time

Please consider fixing this - though this many imply there can only be one user 0.

**Comment by wshawn** [comment]
The primary issue herein, is that any user with the ability to save and edit other users can do so across the board without consideration of ACLs and their role therein.

In short a User Manager with a role of 1000 should not be able to do anything with roles 0 - 999.

**Comment by pixelchutes** [comment]
:+1: 

Closing in favor of #11208, solely because more conversation has occurred there *(the more eyes on this one the better.)*

Thank you for identifying the original issue, and 2 years earlier to boot!

**Comment by wshawn** [comment]
I have to read almost all of the modx code for my book. This was one of those I found...  Thanks for closing this in favor of more eyes. In my opinion this is a major problem.
