### ISSUE TITLE
User cannot edit Resources without Load access to web context

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#7253]
netprophet created Redmine issue ID 7253

Steps to reproduce:
- create a User Group and User with the Administrator  in a non-web context .. and only access to that context
- log in as that user - you will see the context that you expect to, and can perform any action (seemingly) except for editing a resource in that context
- add the Load Only Access Policy on the web context for this User Group - the user will now be able to edit resources in their original context

**Comment by jgulledge19** [comment]
#modxbughunt Close

I just did the steps on 2.5.5pl add Admin perms to mgr and and the none web context. I could save resources on the none web context.
