### ISSUE TITLE
Media Sources (& Resource Groups) Permissions

### ISSUE THREAD

**Issue by sepiariver** [modxcms/revolution#7255]
sepiariver created Redmine issue ID 7255

This has been ongoing with Resource Groups (RG) but now happens with Media Sources (MS) as well. 

If a MS or RG is assigned to a User Group to which the Super Admin does *not* belong, the Super Admin can no longer manage the MS or RG, even to assign it to the Administrator User Group. It simply disappears off the grid.

I understand it's because permission is limited to the User Group to which it was assigned. That is expected. However, adding the Super Admin to the User Group to regain access causes any assigned Form Customization to kick in for the Super Admin.

Suggest adding a "Minimum Role" setting to Form Customization, or allowing a Super Admin to manage *anything* regardless of whether it's assigned to another User Group or not. The latter has been suggested by other forum users and bug trackers and I think it's a good idea...

**Comment by rtripault** [comment]
Let's consider the sudo option takes care of that and close this issue.

Feel free to comment/reopen if needed.
Thanks
