### ISSUE TITLE
resource/create action incorrectly uses new_weblink permission

### ISSUE THREAD

**Issue by neilness** [modxcms/revolution#7327]
neilness created Redmine issue ID 7327

I was having trouble with an access policy. Some users were getting an "access denied" error when trying to create a new document.

Through trial and error, I realized that without the *new_weblink* permission, users could not create a new document.

removing new_symlink & new_static_resource permissions did not create this error.

**Comment by handyface** [comment]
After playing around with the permissions on my modx installation I have also encountered this bug. Whatever I do, I can't get my user group to create a resource. I hope you guys are able to squat this bug fast because it looks like I will have to revert to a fresh install because of this bug.

**Comment by Mark-H** [comment]
With #12255 this was fixed for 2.4, considering cherry picking it back into 2.3 too, see #12361.
