### ISSUE TITLE
Some system events are not responding in plugin

### ISSUE THREAD

**Issue by multimedia** [modxcms/revolution#7330]
multimedia created Redmine issue ID 7330

It looks like that the following system events are not triggered in a plugin:
- OnDocFormDelete
- OnBeforeDocFormDelete
- OnResourceDelete
- OnResourceUndelete

no matter what code i put in the switch at those cases it doesnt get executed.
- create a plugin
- put following code inside:
  <pre>
  $eventName = $modx->event->name;
  switch($eventName) {
  case 'OnDocFormDelete': 
      $modx->log(MODX::LOG_LEVEL_ERROR, 'event: ' . $eventName);
      break;
  case 'OnBeforeDocFormDelete': 
      $modx->log(MODX::LOG_LEVEL_ERROR, 'event: ' . $eventName);
      break;
  case 'OnResourceDelete': 
      $modx->log(MODX::LOG_LEVEL_ERROR, 'event: ' . $eventName);
      break;
  case 'OnResourceUndelete': 
      $modx->log(MODX::LOG_LEVEL_ERROR, 'event: ' . $eventName);
      break;
  }
  </pre>
- check the checkboxes at the system events tab for OnDocFormDelete, OnBeforeDocFormDelete, OnResourceDelete, OnResourceUndelete
- delete any resource with right mouse click
- undelete any resouce with right mouse click
- delete any resource by editing it and clicking the delete button
- check error log for any line that says event: ....

I tried this with OnDocFormSave and that works fine, it shows the line in the error log.

**Comment by adamwintle** [comment]
@rtripault @opengeek @Mark-H Are these System Events still having these bugs?

**Comment by alroniks** [comment]
I tested it from both places: tree and form. All events work fine except the case when user set checkbox Deleted and save the resource. During the update, only `OnResourceDelete` fired.

**Comment by JoshuaLuckers** [comment]
This seems to work fine in 3.x.
