### ISSUE TITLE
Database row ID assumption

### ISSUE THREAD

**Issue by Chillibear** [modxcms/revolution#7345]
Chillibear created Redmine issue ID 7345

I think there may be an assumption made about the row IDs of certain elements in the ModX Revolution codebase.  Having installed ModX Rev 2.2.0-pl2 onto one of our hosting environments that makes use of MySQL in a master-master configuration we found elements in the admin interface that were incorrect. 

Specifically the value of 'Content Type' and 'Uses Template' for new (and the existing sample) pages, both these properties were set to a value of '1' rather than their correct values of 'Base template' and 'HTML' (or rather the indexes of these keys behind the scenes).  

Upon a little investigation the default values (from global settings) were indeed '1' for both of these properties, so the system was _working correctly_ in assigning a '1', but due to the master-master database setup neither 'Base_template' or 'HTML' were assigned a DB row ID of 1 when the tables were populated and hence the problem.  It would appear that the 'default value' for these should be the DB row ID of 'Base template' and 'HTML' respectively and somewhere when those default values are generated there is an assumption that these DB row IDs will be '1'.  For many installs that will be correct, but it is still an assumption that can be wrong.

I should note that at this point I am second guessing the problem - I'm not familiar with the ModX codebase and have yet to locate the code that actually populates the settings values. However the 2.2.0-pl2 install works flawlessly on an environment with just a conventional MySQL deployment.  In a Master-Master deployment there are two key settings that affect the automatic row ID:

auto-increment_increment
auto-increment-offset

Those are used typically to avoid ID clashes when rows are created on different nodes, so in our case rows are not neatly numbered 1,2,3,4 etc. but instead increment say as 2,4,6,8,10 etc.  So that leads to a situation where those 'default' values for 'Content Type' and 'Uses Template' are not located in DB row ID 1, but rather in 2 or 3 or some other value. The code that populates these default values should of course be looking these IDs up by searching for their keys, I am guessing it isn't.

It should be possible to mimic this fault with a single MySQL instance by just setting the above parameters to adjust the ID increment, that's not something I have yet tested, but it should make replicating the bug easy.

It is possible to change the 'default settings' post install to reflect the correct values (although this seems only to work when changed via the 'inline' interface rather than the 'update settings panel' for each property) and we then find things to work as expected.

Essentially because 'out of the box' pages lack a content type or correct template nothing renders when viewing the default pages on the site.

**Comment by adamwintle** [comment]
@Mark-H This issue is 4 years old so it's most likely fixed, but just wanted to check with you first?

**Comment by pbowyer** [comment]
5 years old and 14 months since last comment. Recommend closing, #wontfix for Revolution 2.X #modxbughunt
