### ISSUE TITLE
Path in MODx config files

### ISSUE THREAD

**Issue by eprochasson** [modxcms/revolution#7366]
eprochasson created Redmine issue ID 7366

The config files generated by MODx (/config.core.php, /manager/config.core.php, /connectors/config.core.php and /core/config/config.inc.php) includes absolute path. 

As it works perfectly with a new install, I assume I'm not the only one who have a local version for development and a live version on a different server, with different config files (because different paths).

Is there a reason to not use automatically generated path in those config files, assuming most of the developer use the standard MODx file structure anyway.

For example, /config.core.php can be:

<pre>
<?php
define('MODX_CORE_PATH', dirname(__FILE__) . '/core/');
define('MODX_CONFIG_KEY', 'config');
</pre>

That makes the deployment of any website way easier (you just have to change the database information). Power user with a specific file structure can still change those information manually if required.

**Comment by adamwintle** [comment]
This is no longer relevant @modxbot close
