### ISSUE TITLE
Mysteriously checked resource groups when creating a new document

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#7386]
bobray created Redmine issue ID 7386

The is one of the more mysterious things I've ever run across. Probably something simple.

When I create a new resource, three of the four resource group checkboxes on the Access Permissions tab are already checked -- always.
I have all plugins disabled (and none of them would do that) and have cleared cache manually and browser cache/cookies - appears in all browsers. There are no snippets in the template.

When the resource is saved, it does _not_ belong to the resource groups even if I leave them checked, which makes it even more mysterious.

This will probably be one of those "can not reproduce," but I thought I'd report it.

**Comment by Mark-H** [comment]
Is this still a thing today? Haven't seen this before myself.

**Comment by devlanda** [comment]
I have tried to reproduce the random checks of resource groups.
After adding a new resource, I didn't find the same outcome.
Therefore, I think this old issue can be marked as solved. #modxbughunt

**Comment by rtripault** [comment]
Thanks @devlanda let's go close this one then.

Feel free to comment/reopen if needed.

Thanks

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @devlanda
