### ISSUE TITLE
Inconsistent getTVValue/setTVValue

### ISSUE THREAD

**Issue by aladage** [modxcms/revolution#7453]
aladage created Redmine issue ID 7453

I think this is more of an inconsistency than a bug, but let me explain and you decide.

If you have a TV with an input type that allows multiple input items (check box, listbox, etc.) and are using an output filter that transforms it into a delimited list, the API methods getTVValue and setTVValue (in an onDocFormSave-related plugin, for example) will treat the values differently.

For example: [[https://gist.github.com/2164597]]

The getTVValue example in this code retrieves a comma-delimited list, meaning it's the getting the value after it's been passed through the output filter. However, storing a comma-delimited list with setTVValue will cause a problem in MODx, because multiple TV values must be stored in a pipe-delimited list.

Possible resolutions could be: amending setTVValue to honor the TV's output filters, or allow the setting/getting of preprocessed/postprocessed values via two separate API methods.

**Comment by pbowyer** [comment]
Due to the missing gist, I recommend we close this issue. MODX isn't going to honor output filters when setting values in the current version.

#modxbughunt
