### ISSUE TITLE
Add ability to add a parameter to the resourcelist URL

### ISSUE THREAD

**Issue by onepack** [modxcms/revolution#7468]
onepack created Redmine issue ID 7468

Imagine you have an anchor in the middle of a page called #info
It's now impossible to use the resourcelist when you want to point to an anchor on a specific page.

An extra feature would be that a developer can choose that a resourcelist TV can have an extra parameter field for that RL-tv in the template.
So a user sees a dropdown list with pages and next to that an input field where they can enter a parameter value like #info or something else.

Just an idea and maybe not worth the effort.

**Comment by inreti** [comment]
I think this can be closed. The desired behaviour can easily be achieved with a resourcelist tv + text tv. Or even better with a custom list tv, which may also scan the resources content for named anchors and make them available to choose. Anyway, no need to enhance the core resourcelist tv here.

**Comment by pixelchutes** [comment]
I would agree. There are a few different approaches this can be achieved today directly from core or with existing Extras.
