### ISSUE TITLE
Add robots.txt to the Revolution package

### ISSUE THREAD

**Issue by Martijn1981** [modxcms/revolution#7483]
Martijn1981 created Redmine issue ID 7483

Hey,

I see you guys have already added a favicon.ico to Revolution. Nice work. The only thing missing now is a properly setup robots.txt file. The following contents would be great!

@
# Default exclusions
User-agent: *
Disallow: /assets/
Disallow: /connectors/
Disallow: /core/
Disallow: /manager/
Disallow: /setup/

# For sitemaps.xml autodiscovery. Uncomment if you have one:
#Sitemap: http://www.yoursite.com/sitemap.xml
@

**Comment by inreti** [comment]
And: the robots.txt should not reveal unneccessary information. In this case the manager url, core url, setup (!?). If these are in the robots.txt, no one would have to guess the manager url, you can just look it up.  That would foil basic hardening rules...

**Comment by zaigham** [comment]
@inreti @theboxer :+1: 
I suggest to close this one down.

**Comment by pixelchutes** [comment]
At this point, adding this to core could also end up clobbering many site owner's existing robots.txt. It's easy enough to add, and is not uncommon to require specific customizations depending on the site anyway.
