### ISSUE TITLE
Fix discrepancy between 'Edit' and 'Update' actions

### ISSUE THREAD

**Issue by MokoJumbie** [modxcms/revolution#7484]
MokoJumbie created Redmine issue ID 7484

There are several places in grid views in the MODx manager where, when right clicking on an item, the user is presented with the option to 'Update' an item. There are also many other places where a user can 'Edit' an item.

Update can present one of at least two possible resulting actions:
-In System Settings, 'Update Setting' presents a pop-up UI panel to edit the _setting definition_. One must double click on the value to be edited to present the UI to edit the actual value.
-In Manage Users, 'Update User' takes the user to a new page to edit the _values_ for the user.

Edit actions seem consistent in that they allow to to modify the values for the selected item.

I submit that the meaning of 'Update' in unclear to describe its intended action. I think that the term 'Update' is commonly understood to mean 'Update the application's view to reflect the state of the model' that 'Allow me to Update the values for this item'. In this way, it's closer to 'Refresh' than it is to 'Edit'.

Wouldn't it make more sense to change all uses of 'Update' to 'Edit'? And if an 'Edit' action is going to edit something other than the item's values, perhaps that should be clarified as well, as in 'Edit Setting Definition'?

I'm posting this for discussion in http://forums.modx.com/thread/75425/ui-discrepancy-between-edit-and-update-actions

**Comment by Ruslan-Aleev** [comment]
Fixed in https://github.com/modxcms/revolution/pull/15155. We can close this issue.
