### ISSUE TITLE
IE Compatibility - Manager UI - CSS Discrepencies

### ISSUE THREAD

**Issue by davidsmith** [modxcms/revolution#7485]
davidsmith created Redmine issue ID 7485

The attached file shows examples of the [sometimes inconvenient] difference in visuals in the Manager UI, comparing Firefox to IE9. It seems there's a problem with the CSS being overridden by IE filters to some rendering effects, causing various tabs and other items to appear incorrectly.

The issue was originally raised, and discussed in detail here: http://forums.modx.com/thread/?thread=75023

**Comment by rtripault** [comment]
I guess this is no more relevant since 2.3.0, so closing.

Feel free to comment/reopen if needed.
Thanks
