### ISSUE TITLE
Consolidate Functionality of Contextual Menu and Bulk Actions Menu

### ISSUE THREAD

**Issue by MokoJumbie** [modxcms/revolution#7492]
MokoJumbie created Redmine issue ID 7492

Currently, the contextual menu reflects the Bulk Actions Menu if multiple items are selected in a grid view. But the reverse is not true.

I'd like to see the Bulk Actions Menu Renamed to 'Actions' and have it reflect the items available in the contextual menu when single items are selected.

If no items are selected, instead of having an empty menu, it can be populated with the actions from other buttons next to the Actions button, such as the 'Create New Item' Action.

**Comment by alroniks** [comment]
Due to the lack of screenshots and detailed explanations about specific places where bulk menu used and also because it's a very old issue and a lot of screens were changed and going to be changed, I am closing this issue.
Feel free to reopen. But I would prefer a new issue with more details.
