### ISSUE TITLE
Allow Media Source to be bound to template

### ISSUE THREAD

**Issue by MokoJumbie** [modxcms/revolution#7512]
MokoJumbie created Redmine issue ID 7512

I'd like to be able to limit the rich text editor for the content area in a template to have access to a given media source for inserting images. I can't think of another way to accomplish this other than to suggest being able to bind a Media Source to te template that content area is derived from.

I might have thought this would be a TinyMCE issue, but this could apply to other RTEs and any other components attached to the content field.

**Comment by rtripault** [comment]
I believe this is finally fixed by #13110, so closing.

Feel free to comment/reopen if needed.
Thanks
