### ISSUE TITLE
Menu index conflict in resources until deleted resources removed

### ISSUE THREAD

**Issue by MokoJumbie** [modxcms/revolution#7528]
MokoJumbie created Redmine issue ID 7528

Recently, a resource went missing from the resource tree. It was clearly not deleted. We verified that a record for that resource still existed in the DB. Searching for the item in the search field above the resource tree showed and enabled editing of the item in the UI. We manually incremented the menu index of 6 by 2, resulting in 8. This caused the item to show up in the tree again. Then, dragging the item back to its original position caused it to disappear again. Examining the DB showed that all items sharing the same parent as the item in question had unique menu IDs, so there appeared to be no conflict, as we suspected.

We re-set the menu index of the item to 8, which caused it to show again. Then, checking the DB again revealed that two items existed with the same parent and same menu ID of 8. I don't know how to reproduce the situation that resulted in this bug, but it seems to be consistent.

Eventually, I found that removing deleted resources from the tree sorted out the visibiliity issue. But I am sure that the issue shouldn't be happening in the first place.

**Comment by Mark-H** [comment]
The menuindex has no impact on the visibility in the tree, which I just double checked, so given the age of this issue I'm going to close it assuming it's already been solved since. If it's still an issue today, please feel free to reopen with more information.
