### ISSUE TITLE
FC-rules lost while switching templates of a new document

### ISSUE THREAD

**Issue by Martijn1981** [modxcms/revolution#7548]
Martijn1981 created Redmine issue ID 7548

Seems the template-switching bug is still present in 2.2.1pl, but it *has* been partially fixed though.

Here's the current situation:

- *Saved* documents can switch templates properly. No issues there. Works fine.
- *New* documents, which haven't been saved yet, cannot switch templates properly. All FC-rules are lost when another template has been selected. 

Attached you'll find the temporary fix I'm using to make sure new documents retain all their FC-rules while templates are switched.

**Comment by whitebyte** [comment]
Related issue: #7254

**Comment by rtripault** [comment]
So closing in favor of mentioned issue.
