### ISSUE TITLE
Change "close" to "cancel" in edit/update popups

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#7555]
bobray created Redmine issue ID 7555

When doing things like creating new default properties, seeing "Close" and "Done" buttons can be confusing. "Cancel" more clearly describes what will happen if you click the left button.

Any place there's a "Done" button, the alternative should be "Cancel" IMO,

**Comment by Mark-H** [comment]
Pull requests for specific instances where this is the case are welcome. For non-English languages, translations are managed via http://translate.modx.com/
