### ISSUE TITLE
Please change click behaviour for nested elements in the tree

### ISSUE THREAD

**Issue by pepebe** [modxcms/revolution#756]
After a couple of years watching clients fiddling around with the resource tree I have come to the conclusion that the arrows in front of resource containers are a serious UI problem. 

Its much to easy to open a resource instead of unfolding the parent container.

I would suggest to unfold the parent container on clicking anything except the resource title (and perhaps the icon directly in front of it. This would make it much easier to navigate through the tree.

Please have a heart for people with clumsy fingers or bad eye-sight.

Regards,

pepebe

**Comment by sottwell** [comment]
At least, as of 4.0 double-clicking almost opens the branch. The child resource briefly shows half-hidden by the parent, then it disappears as the page is reloaded with the editing form.

**Comment by adamwintle** [comment]
I think the latest design from 2.3 handles this quite well, its certainly harder to miss-click and accidently open that branch and I can't think of a way this could further be improved. Going to close this issue.

@modxbot close
