### ISSUE TITLE
Unable to duplicate media resource

### ISSUE THREAD

**Issue by jcurtis** [modxcms/revolution#7563]
jcurtis created Redmine issue ID 7563

Following an upgrade to 2.2.1-pl I'm unable to duplicate media resources. This applies to media sources created in 2.2.0-pl2 and in 2.2.1-pl.

The browser simply throws a Javascript error.

FireFox 11.0 error:
<pre>
Timestamp: 9/04/2012 4:57:42 PM
Error: Ext.get(f.id) is null
Source File: http://[siteurl]/manager/assets/modext/core/modx.js
Line: 445
</pre>

IE 9.0.8112 error:
<pre>
SCRIPT5007: Unable to get value of the property 'dom': object is null or undefined 
modx.js, line 445 character 13
</pre>

**Comment by rtripault** [comment]
It's been a long time since this issue (sorry), and as of today i was not able to reproduce, so closing.

Feel free to comment/reopen if needed.
Thanks
