### ISSUE TITLE
Form-customized checkboxes  are bugged

### ISSUE THREAD

**Issue by Martijn1981** [modxcms/revolution#7570]
Martijn1981 created Redmine issue ID 7570

Ì'm using FC-sets for a certain template. On admin-level, the template is *not* hidden from the menu. On webmaster-level (the level of users which I'm using FC for) the template suddenly *is* hidden from the menu. And I've left those values untouched in Form Customization.

Fields and tabs are hidden properly, but it seems the checkboxes aren't always checked or unchecked properly.

**Comment by rtripault** [comment]
Guessing (hoping) MySQL version was the source of the issue, so closing.

Feel free to comment/reopen if needed.
Thanks
