### ISSUE TITLE
Alias not active on initial save of resource

### ISSUE THREAD

**Issue by xxxmicrobexxx** [modxcms/revolution#7587]
xxxmicrobexxx created Redmine issue ID 7587

I add a new resource which includes a URL alias.  I save it and go to the page linking to that new resource.  The link is to the root of the site, the alias isn't included.

To fix it I simply go back to the resource and save it again and then it works as expected.

**Comment by OptimusCrime** [comment]
Unable to reproduce

**Comment by xxxmicrobexxx** [comment]
A reply over 3 years later :o)

**Comment by OptimusCrime** [comment]
Trying to clean up the issues, @xxxmicrobexxx :)

**Comment by pixelchutes** [comment]
Possibly related to #12250 ?

**Comment by pbowyer** [comment]
Recommend closing, given timeframe. #modxbughunt
