### ISSUE TITLE
modUserMessage improvements

### ISSUE THREAD

**Issue by the-dunnock** [modxcms/revolution#759]
modUserMessage is missing two crucial indexes for recipient and sender.

Also could have fulltext index for subject, message pair

An improvement also would be possibility for threaded messaging, to enable this new column for thread could be added.

**Comment by silentworks** [comment]
@theboxer close

**Comment by sottwell** [comment]
so was the decision to remove them, or to just leave it alone?

**Comment by silentworks** [comment]
@sottwell it would be to leave them as they are. As @amdbuilder stated, they could only be removed in a major release in order to follow semantic versioning.

**Comment by sottwell** [comment]
Good. Because I use them sometimes. They're actually very nice.
