### ISSUE TITLE
Package Download Loader Bar Stuck

### ISSUE THREAD

**Issue by eightygrit** [modxcms/revolution#7617]
eightygrit created Redmine issue ID 7617

When downloading a package, the modal progress bar appears and never goes away. There is no way to cancel the download or exit the modal, so refreshing the page is the only option. The package does successfully download, so the issue appears to only be UI related.

**Comment by rtripault** [comment]
Due to the issue date, i assume this is no more relevant and/or fixed, so closing.

Feel free to comment/reopen if needed.
Thanks
