### ISSUE TITLE
Permissions are not working right in manager

### ISSUE THREAD

**Issue by theuros** [modxcms/revolution#7621]
theuros created Redmine issue ID 7621

i try to solve my problem for two days now and i don't have a clue if i'm doing something wrong or is there any bug i don't know.

I want to limit users to use only speciffic context. I allready done this before (last time on revo 2.1.3) ... now i tryed on 2.2.1 but i failed so i thought it was 2.2.1 bug .. so i installed 2.2.0 but i have same problems...

what i did (exactyle the same thing i've done on 2.1.3 before):

1. created a new context
2. created a new moderator role (10)
3. duplicated administrator access policy
4. created a new XXX user group
5. set context access to:
context / min role / access policy
mgr / moderator(10) / duplicated admin policy
mycontext / Member (9999) / duplicated admin policy
6. created a user in XXX user group with role moderator(10)

when i was testing i flushed permissions, deleted all from core/cache, deleted browser cache ...

i can login with new user and i see only one context wich is all ok but when i try to edit a resource in that context i get access denied .. i can create new resources but i can't delet them .. 

if i use quick edit on that resource i can change it .. direct click on it is access denied

**Comment by rtripault** [comment]
Closing this one, since that's an old one, and the screenshot is no more available (and hopefully this has been solved, if bug there was).

Feel free to comment/reopen if needed.
Thanks
