### ISSUE TITLE
System Setting "phpthumb_imagemagick_path" does not work

### ISSUE THREAD

**Issue by titanium** [modxcms/revolution#7632]
titanium created Redmine issue ID 7632

Whatever string I put in the system setting "phpthumb_imagemagick_path", phpthumb throws the debug message "    [9] => ImageMagickThumbnailToGD() aborting because cannot find convert in $this->config_imagemagick_path (), and `which convert` returned (/usr/bin/convert) in file "phpthumb.class.php" on line 1131"

$this->config_imagemagick_path is always empty, but should be set by "phpthumb_imagemagick_path" system setting.

"On git, there is a notice according to this, relating to MODx Revolution 2.0.1-rc1":https://github.com/modxcms/revolution/commit/9a80ac5bbcb4db34d88038176c890ef0394d40b0#diff-2

MODx Revolution 2.0.1-rc1
+- Added phpthumb_imagemagick_path for users that need to change the imagemagick path for different environments

In MODx Revolution 2.2.1, there is no "core/model/modx/processors/system/phpthumb.php" anymore. Maybe that's the fault.

**Comment by OptimusCrime** [comment]
This might be worth looking into.

@OptimusCrime

**Comment by alroniks** [comment]
Fixed in 2.6.5
