### ISSUE TITLE
nested if-then-else output filters (and gallery): errors and strange behavior

### ISSUE THREAD

**Issue by frischnetz** [modxcms/revolution#7638]
frischnetz created Redmine issue ID 7638

Putting content-tag in an if-then-else-statement, using gallery inside the content with templates that itself use itself if-then-else-cases lead to wrong output:

Testcase:

My Template:
<pre>
<html>
<head>
<title>[[++site_name]] - [[*pagetitle]]</title>
<base href="[[++site_url]]" />
</head>
<body>
  
  <h1>content inside an if-the-else-output-filter:</h1>
  [[*introtext:isnot=``:then=`[[*introtext]]`:else=`[[*content]]`]]

  <h1>content without </h1>
  [[*content]]
    
</body>
</html>
</pre>

My resource:
<pre>
[[Gallery? &album=`1` &thumbTpl=`testthumb_tpl` ]]
</pre>

(Install gallery 1.5.0rc1 and put some images inside gallery 1)

My chunk testthumb_tpl:
<pre>
<div class="[[+cls]]">
  <a rel="galerie" class="fancybox-image" href="[[+image]]"
  title="[[+name]][[+description:isnot=``:then=` – [[+description]]`:else=``]]">
	      <img class="[[+imgCls]]" src="[[+thumbnail]]" alt="[[+name]]"/>
  </a>
</div>
</pre>

Output of both instances of <pre>[[*content]]</pre> should be identical, but is not. It is indeed broken: there's a spurious <pre>`]]"></pre> inside the output.

<pre>
<html>
<head>
<title>Testpage</title>
<base href="http://test1110.knuust.de/" />
<link rel="stylesheet" href="/assets/components/gallery/css/web.css" type="text/css" />
</head>
<body>
  
  <h1>inside if-the-else:</h1>
  `]]">
	      <img class="" src="/assets/components/gallery/connector.php?action=web/phpthumb&amp;w=100&amp;h=100&amp;zc=1&amp;far=C&amp;q=90&amp;src=%2Fassets%2Fgallery%2F1%2F15.jpg" alt="IMG_5638_1_1000.jpg"/>
  </a>
</div>

  <h1>outside:</h1>
  <div class="gal-item-active">
  <a rel="galerie" class="fancybox-image" href="/assets/components/gallery/connector.php?action=web/phpthumb&amp;w=500&amp;h=500&amp;zc=0&amp;far=&amp;q=90&amp;src=%2Fassets%2Fgallery%2F1%2F16.jpg"
  title="IMG_5578_1_1000.jpg">
	      <img class="" src="/assets/components/gallery/connector.php?action=web/phpthumb&amp;w=100&amp;h=100&amp;zc=1&amp;far=C&amp;q=90&amp;src=%2Fassets%2Fgallery%2F1%2F16.jpg" alt="IMG_5578_1_1000.jpg"/>
  </a>
</div><div class="gal-item-active">
  <a rel="galerie" class="fancybox-image" href="/assets/components/gallery/connector.php?action=web/phpthumb&amp;w=500&amp;h=500&amp;zc=0&amp;far=&amp;q=90&amp;src=%2Fassets%2Fgallery%2F1%2F15.jpg"
  title="IMG_5638_1_1000.jpg">
	      <img class="" src="/assets/components/gallery/connector.php?action=web/phpthumb&amp;w=100&amp;h=100&amp;zc=1&amp;far=C&amp;q=90&amp;src=%2Fassets%2Fgallery%2F1%2F15.jpg" alt="IMG_5638_1_1000.jpg"/>
  </a>
</div>
    
</body>
</html>
</pre>

I encountered problems with nested if-then-else-output filters before but usually they can be fixed by making sure not to leave out any else-statements. This one is different: all else-statements are supplied.

**Comment by OptimusCrime** [comment]
Closing due to age and lack of activity.

Feel free to comment/reopen if this is still an issue.

@modxbot close
