### ISSUE TITLE
actions.cache.php causes problems when transferring site to new location

### ISSUE THREAD

**Issue by daanavitch** [modxcms/revolution#7643]
daanavitch created Redmine issue ID 7643

When moving the site to a new path on the same server, /core/cache/action_map/mgr/actions.cache.php causes problems because it doesn't take the config file into account. 'namespace_path' uses absolute paths, so when transferring the site to a new location, the files get linked incorrectly. Clearing the cache doesn't resolve the problem.

**Comment by rtripault** [comment]
As stated in the [documentation](http://rtfm.modx.com/revolution/2.x/administering-your-site/moving-your-site-to-a-new-server), it's recommended to delete the `core/cache/` folder, so closing.

Feel free to comment/reopen if needed.
Thanks
