### ISSUE TITLE
FC Resource/Create Not Being Applied

### ISSUE THREAD

**Issue by boomerang** [modxcms/revolution#7644]
boomerang created Redmine issue ID 7644

I have 2 user profiles, 4 different templates and I've set FC rules for all. They have all applied except one set. I created a Resource/Update set for this particular template which displays correctly for the specified user group, however, having duplicated the set and then changing from Resource/Update to Resource/Create the rules are not applied.

I've cleared cache, re-created without duplicating, made other changes but nothing has come through.  Have check the database and the rules are in place, but somehow this one particular set isn't being applied.

I did recently upgrade from 2.2.0 to 2.2.1.

**Comment by Mark-H** [comment]
Possibly due to a condition on the set, or a bug fixed since 2.2. Closing due to age.
