### ISSUE TITLE
Hide Article Tabs via Form Customization 

### ISSUE THREAD

**Issue by infomax** [modxcms/revolution#7657]
infomax created Redmine issue ID 7657
1. I can hide the Article Tabs via Form Customization
2. I inserted the additional "article id's" under structure tabs
3. As long as I have the visibility checkboxes "checked" the "article id's" are shown, but also the "article tabs" in manager
4. If I uncheck the visibility checkboxes, the "article tabs" are gone (that's good)
5. But the next time I opening the "Form Customization policy" the "article id's" are not shown
   (Take a look at the images)

**Comment by wuuti** [comment]
Confirmed in 2.5.x. #modxbughunt

Thats because the saving of the values is wrongly designed here like this. If you untick a checkbox for a tab here, modx removes that from the database instead of setting it to false (thats for custom tabs only).

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @wuuti

**Comment by smg6511** [comment]
It sounds like this has to do with an Extra, which would not be something to address in the core. Can we close this?
