### ISSUE TITLE
lexicon not updating full page edit view [quick edit IS updating though]

### ISSUE THREAD

**Issue by greyskymedia** [modxcms/revolution#7662]
greyskymedia created Redmine issue ID 7662

When i change the lexicon for description and introtext(i'm using them for Meta Description and Meta Keywords) the quick edit IS using my new lexicon; BUT, when i edit the page in full edit mode the lexicon(labels) are NOT changed. Thoughts?

**Comment by adamwintle** [comment]
@greyskymedia This sounds like it could have been a cache issue? I just did a quick test and it looks like this has been resolved. If the bug is still present please open the issue again.

@modxbot close.
