### ISSUE TITLE
OnHandleRequest Event During Connector Request Not Working.

### ISSUE THREAD

**Issue by AESmith** [modxcms/revolution#7678]
aesmith created Redmine issue ID 7678

Can anyone confirm the OnHandleRequest should not fire during connector request? Its not firing for me.

I have confirmed its not firing or at least the plugin within the event is not firing. By calling modPlugin within my connector above my handeRequest() I have been able to force it but without my plugin is not firing.

**Comment by rtripault** [comment]
Correct, the event is never fired (see https://github.com/modxcms/revolution/blob/2.x/core/model/modx/modconnectorrequest.class.php#L56).

Closing that one but feel free to comment/reopen if needed.
Thanks
