### ISSUE TITLE
Creating new TV in new 2.2.1 install cause a notice error

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#7680]
bertoost created Redmine issue ID 7680

I have made a new install of 2.2.1 and when I create a new TV I get this error

<pre>
Notice: Undefined index: rank in ***/core/model/modx/processors/element/tv/create.class.php on line 127
</pre>

I know it's a notice, but my development server has a strict policy. The "saving" window is not going to disappear but the TV is created normally.

**Comment by rtripault** [comment]
It seems so, so closing.

Feel free to comment/reopen if needed.
Thanks
