### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by redtoad** [modxcms/revolution#7685]
redtoad created Redmine issue ID 7685

have been ordered to list suggestions for the Revo manager UI

honestly, I just want to give a manager theme to the community. but I don't have time yet. 

biggest issues: there is no right click prompt on the site menu tree, there are mystery buttons with no labels everywhere the dropdowns are humungous, the huge settings lists are scary (can I have my tabs back please?) and I personally ....this is a personal thing... hate the boxiness.

too many boxes. I think it is the thin outline around the tabs, it just bugs me. I am not one who likes to complain unless I can help fix so with this I do promise to mock up some ideas to help and I will work on a theme. 

peace

**Comment by adamwintle** [comment]
There is definitely right-click in the tree now.  The rest of this issue is too broad, if there are other specific UI bugs or enhancements can you log them as individual issues? 

@modxbot close

**Comment by jpdevries** [comment]
@Mark-H @adamwintle 

> biggest issues: there is no right click prompt on the site menu tree, there are mystery buttons with no labels everywhere the dropdowns are humungous

I believe @redtoad is saying there is no right click **prompt** not that there is no right click feature. The feature exists, there is still no prompt.

**Comment by Mark-H** [comment]
Yep I think you're right @jpdevries - I agree with @adamwintle for closing this issue though, it is pretty broad mentioning numerous issues that would be better off split into multiple issues for as much as they're still accurate today. Otherwise issues like this tend to stay open indefinitely because there's one or two not done.

**Comment by adamwintle** [comment]
@jpdevries this was logged way back in 2013 when the Manager UI had a different theme, so some of the points from @redtoad have been resolved. 

For the right-click prompt, do you mean there is no way to know if something can be right-clicked or not?

If so, I don't really see that as an issue. There is no way to tell where you can and can't right-click on Windows or OS X. It would clutter up the UI if we were to add a little icon or indication to everything which can be right-clicked. 

Usually right-click menus offer optional choices or advanced options, the critical functionality should be visible by normal buttons in the UI. If something is buried in a right-click menu and it should be obvious then its a UI design issue, which could be specifically identified and log as its own issue.

**Comment by redtoad** [comment]
Please note that @redtoad is not the user that created this request in redmine!
