### ISSUE TITLE
Show console log entries for package uninstallation

### ISSUE THREAD

**Issue by fireproofsocks** [modxcms/revolution#772]
When uninstalling a package, any log messages generated by the resolvers should be shown in the console to alert the user to any problems or follow-ups that may be required.

For example, this code should generate a message in the console:

```
switch ($options[xPDOTransport::PACKAGE_ACTION]) {    
    case xPDOTransport::ACTION_UNINSTALL:
       $manager = $modx->getManager();
       $manager->removeObjectContainer('Customtable');
        $modx->log(modX::LOG_LEVEL_INFO, 'Your custom database table was removed successfully.');
        break;
}
return true;
```

It would be quite helpful to know whether or not the custom database table had been properly removed.  The current behavior in 2.2.10 is that no messages are displayed in the console when uninstalling a package.

**Comment by sottwell** [comment]
Console displays messages during uninstall. And sometimes for reasons unknown the console will just be blank, or a very minimal message of "Console running...", but this happens on installation sometimes as well.

So is this still a valid issue?

**Comment by adamwintle** [comment]
@fireproofsocks Is this still an issue or can this now be closed?

**Comment by fireproofsocks** [comment]
I think it's still an issue -- the steps to repeat should be clear for anyone with an active dev environment.

**Comment by OptimusCrime** [comment]
Re-reading stuff here makes things a bit clearer.

If I understand correctly, OP wants to output things in the console during package install/uninstall?

**Comment by Jako** [comment]
@OptimusCrime Yes, the console uses the `$modx->log` functionality.

**Comment by OptimusCrime** [comment]
Really? Hmm, do we know why entries from uninstall is not working properly?

**Comment by ilyautkin** [comment]
I checked installing and uninstalling of package. Console log entries for package installation/uninstallation works correctly.

Resolver for package:
![resolver](https://user-images.githubusercontent.com/3328625/51162587-90914780-18b8-11e9-8d31-ef445abf13f9.png)

Installing:
![install](https://user-images.githubusercontent.com/3328625/51162595-9555fb80-18b8-11e9-8eea-6315dce867a3.png)

Uninstalling:
![uninstall](https://user-images.githubusercontent.com/3328625/51162597-97b85580-18b8-11e9-9187-79765d5991e2.png)

**Comment by alroniks** [comment]
So, I am closing the bug as we see demonstration of the proper work. Please, reopen if it still should be addressed.
