### ISSUE TITLE
Items in the manager with contextual menus, require visual identifier

### ISSUE THREAD

**Issue by Crunch** [modxcms/revolution#7729]
crunch created Redmine issue ID 7729

When items appear on manager pages such as the 'manage users' page, there should be a visual indicator to signify a contextual menu is available on each item. Without it, it is a case of 'knowing' that a contextual menu exists.

This is not a problem for me as such, but when I first started using Revo - I took a while before I realised there were options available via context menus for most things. It's a UI issue, which is subtle but would improve the experience for new users. Even if it is something tiny, like a small arrow, to indicate that there are more options for this item, would help make the manager interface more intuitive. 

Note: I am not referring to the context menus in the resource tree, but items in data tables such as found on the 'system settings' page etc

**Comment by Ruslan-Aleev** [comment]
Same issue https://github.com/modxcms/revolution/issues/14125

**Comment by Ruslan-Aleev** [comment]
I think we can close this issue, done with PR https://github.com/modxcms/revolution/pull/14806
