### ISSUE TITLE
New: Manager page for system events management

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#7805]
bertoost created Redmine issue ID 7805

To manage system events there should be a manager page.

In there you should be able to create own events at least. Because for larger websites I use the events system to create hookable features and simple managing this would be great.

This could be in the way of a component I know, but I think this belongs to the core

**Comment by bertoost** [comment]
Still not in the manager. Will try to make this and make a PR.
What would be a good place to add this? Would love to decrease the number of menu items, so maybe a make tabs in System Settings?

**Comment by rtripault** [comment]
Closing as you've implemented it :D (thanks & :wave: BTW)

#modxbughunt
