### ISSUE TITLE
Resources/Elements tree keeps expanding, lags manager

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#7806]
ReSpawN created Redmine issue ID 7806

I've been aware of this bug for some time, but I have a hard time really believing this is indeed a bug.

We've usually got about 100 resources on the first release, with about 20/30 snippets and about 40 chunks and some plugins. Naturally some templates, too. While developing, you'll have the entire tree open for easy access. What happens now is, even when I manually close the ENTIRE tree with ALL subfolders individually clicked, uppon refresh, it still reloads the old view and thus opens all folders which takes for ever. This, in this later stadium, isn't improving workability as it would in development. Even one of our customers have complained to us about this.

The question remains, is this a bug? If not, what can we do to prevent this? The only way seems manually removing the entire cache folder on the filesystem and recreating it with CHMOD 777.

**Comment by wuuti** [comment]
@ReSpawN Do you still see such problems with the current versions (2.6.x?) If not this issue should be closed. @Mark-H

**Comment by Ibochkarev** [comment]
I vote to close this  issue.

**Comment by alroniks** [comment]
Seems to really old issue that probably was fixed in current releases. Feel free to open a new one if question still actual.
