### ISSUE TITLE
minifier rewrite css urls with server path instead of url

### ISSUE THREAD

**Issue by lexusburn** [modxcms/revolution#7815]
lexusburn created Redmine issue ID 7815

i have installed both revolution-2.2.1-pl and revolution-2.2.2-pl on my webserver.
i am using symlinks because i have to directories (modx and modx_old) that referes to the revolution-2.2.2-pl dir and the revolution-2.2.1-pl dir.

My directory listing looks like this:
<pre>
{HOSTNAME}/htdocs/modx -> ../modx
{HOSTNAME}/htdocs/modx_old -> ../modx_old
{HOSTNAME}/modx -> modx-2.2.2-pl
{HOSTNAME}/modx-2.2.2-pl
{HOSTNAME}/modx_old -> modx_old_versions/modx-2.2.1-pl
{HOSTNAME}/modx_old_versions/modx-2.2.1-pl
</pre>

When i activate compress_css the manager fails to load some background-images that are referred in minified css files.
This happens because the path in css files looks like this: 
<pre>
https://{HOSTNAME}/var/www/{HOSTNAME}/modx-2.2.2-pl/manager/templates/default/images/modx-theme/grid/page-last-disabled.png
</pre>

My quick & dirty resolution for this is to disable CSS URL rewriting in minifier by changing 
<pre>
$min_serveOptions['rewriteCssUris'] = true;
</pre>
to
<pre>
$min_serveOptions['rewriteCssUris'] = false;
</pre>
in manager/min/index.php

now i get the image path like this: 
<pre>
../images/modx-theme/grid/page-last-disabled.png
</pre>

i added these mod_rewrite-hack in manager/.htaccess to rewrite this url:
<pre>
RewriteEngine On
RewriteBase /modx/manager
RewriteRule ^images/(.*)$ /modx/manager/templates/default/images/$1 [L]
</pre>

Can anyone help me to get another better resolution for this problem?

**Comment by Mark-H** [comment]
Closing as #12611 made compression static
