### ISSUE TITLE
Attempting to sort the Template Variable Access tab fails on Description and Access fields

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#7896]
wshawn created Redmine issue ID 7896

The description is simply ignored, as it appears to be disabled.

Attempting to sort on Access completely blanks the form.

**Comment by wshawn** [comment]
Still exists in 2.4.0 GO to the Template access tab and attempt to sort on the description or access fields.
The Access column will blank the display area, while the description column does nothing.

Reclicking the name column repopulates the page.

**Comment by alroniks** [comment]
PR is merged and not reproducible on 2.7.0-dev, so closing.
