### ISSUE TITLE
Admin custom crop images in content areas and image TV

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/revolution#7951]
sonicpunk created Redmine issue ID 7951

What I and my clients would love to have is a way to crop and resize images when inserting an image into TinyMCE.  So as an admin picks their image, during this process, the admin can (like in Facebook) resize and crop the image.   These changes will be saved using phpthumbof or something similar so that the image is optimized for the page.  This would also be useful for the image TV input type as well.

**Comment by Alroniks** [comment]
Looks like that is a pretty old issue and now exists tools for solving this problem (not sure that it applied to the core). I guess we can close it. If it still actual, please, reopen the issue.
