### ISSUE TITLE
Policy grid and update policy window show not enabled permissions

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#7974]
gadamiak created Redmine issue ID 7974

This happens on the policy grid when policy is expanded by clicking a 'plus' icon and in update policy window. All permissions from a policy template are listed despite being enabled or not. However when adding a policy only enabled permissions are displayed as expected. See screens.

This makes reviewing permissions for a user group impossible.

**Comment by alroniks** [comment]
In the popup window it works as expected, but in grid issue still exists.
Screen ![](https://i.imgur.com/r2XK8Gy.png)
