### ISSUE TITLE
Clarify Media Source policy meaning

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#7977]
gadamiak created Redmine issue ID 7977

I was really surprised to discover that a user needs Media Source Admin policy assigned to be able to actually upload files into a MS. This in fact is logical but both docs and description in manager UI refer to a MS itself not its content, ie. files and folders they contain.

The docs are misleading esp. an example of editor user group being granted read-only access to a MS, which means they can't upload nor create any files/folders in it. The description in UI and docs should get clarified about it.

What mislead me most are the 'User' and 'Admin' suffixes to those policies' names. I guess a kind of 'read-only' and 'modify' wording would be more informative.

**Comment by adamwintle** [comment]
@theboxer @OptimusCrime Do you guys think this is still an issue?

**Comment by OptimusCrime** [comment]
I guess this is solved?

**Comment by OptimusCrime** [comment]
Closing this due to lack of feedback and age. I also think this is solved in a sense.

Feel free to reopen if you feel otherwise or if you have any further information/feedback/comments.

@modxbot close
