### ISSUE TITLE
gettvvalue on radio-tv-not-in-this-template, gives default value instead of empty string.

### ISSUE THREAD

**Issue by BertCatsburg** [modxcms/revolution#8066]
bertcatsburg created Redmine issue ID 8066

A Radio Template Variable called 'testtv'.
Options: As==AAA||Bs==BBB||Cs==CCC
Default Value:  BBB

TV is only assigned to Template XXX (!!)

There is a document (Resource) called 'test' and assigned to Template YYY (!!)
So, this Resource does not have the TV. (Triple checked in the manager)
ID of 'test' is 16.

Following code: 

$page = $modx->getObject('modResource', 16);
$tvvalue = $page->getTVValue('testtv');

Expected is that $tvvalue has an empty value, since testtv does not exist for this resource. 

But what is returned is the value 'BBB', the default value. 
Tested with entering a Default Value of 'DDD', and then that value is returned.

**Comment by ilyautkin** [comment]
I think, that is correct behavior. This is not a bug, this is a feature.

**Comment by OptimusCrime** [comment]
That is somewhat debatable. I would see this as incorrect behavior. Does someone else have any opinions about this? We could close it off as intended behavior as @ilyautkin states too. Seeing as this issue is 5 years old and has not gain any traction so far.

**Comment by pixelchutes** [comment]
Seems related to #11969 where it was also described as a:
> Surprising but useful "feature"

I'm not sure the behavior feels very intuitive. If it has no associated to the Template, it is my belief it should behave as though it doesn't exist.
