### ISSUE TITLE
TV ContentValues aren't removed after Context removal

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#8069]
ReSpawN created Redmine issue ID 8069

When removing a context, you'd obviously expect the resources would be removed as well. Though that indeed works, the linked content values (modTemplateVarResource) aren't removed thus leaving loads of overhead when using multiple if not dozen(s) of TV's.

**Comment by Flowan** [comment]
Confirmed on 2.5.x #modxbughunt

**Comment by Flowan** [comment]
I'm going to try and fix this today.

**Comment by pixelive** [comment]
Tested and works.

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @pixelive

**Comment by OptimusCrime** [comment]
@pixelive Tested what? What works? The PR or the issue? As @Flowan just confirmed this bug.

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @Flowan

**Comment by Alroniks** [comment]
Merged 345de06287bfba91b165e377fc3a346cdf8e81e3
