### ISSUE TITLE
Menuindex is not preserved when duplicating contexts.

### ISSUE THREAD

**Issue by sepiariver** [modxcms/revolution#8074]
sepiariver created Redmine issue ID 8074

This only starts to matter when a lot of context duplication is taking place, and there are a lot of resources in each context, as is the case here. Reordering them in the tree manually can be painstaking. From the client:

"Is there a reason that when you duplicate an entire context, the order of all documents and child resources is all over the place?"

**Comment by rtripault** [comment]
I guess this has been fixed since Revo 2.3.0-pl, introducing the ability to keep menuindex values, so closing.

Feel free to comment/reopen if needed.
Thanks
