### ISSUE TITLE
TV type hidden is removed when resource is updated

### ISSUE THREAD

**Issue by Crunch** [modxcms/revolution#8081]
crunch created Redmine issue ID 8081

Steps to reproduce:
- create a new tv with type 'hidden', attach to a template
- for an example resource using the template, programmatically add a value for it via a snippet eg
  @$resource = $modx->getObject('modResource', $resourceID);
  $resource->setTVValue('hiddenTV', 'test value');@
- check the db table 'modx_site_tmplvar_content', the hidden tv is there for your resource
- update the resource in the manager making any arbitrary change
- check the db table again, the hidden tv entry is gone

**Comment by JoshuaLuckers** [comment]
I tried reproducing this issue but without luck. Can someone confirm this issue and set up a test case?

**Comment by alroniks** [comment]
Yes, not reproducible on 2.7.0-dev for me too. It seems it was fixed before (I don't remember PR number exactly, but remember that it was discussed). So, closing.
