### ISSUE TITLE
MODX SiteId is not set at package provider Download request

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#8098]
bertoost created Redmine issue ID 8098

In this case the package couldn't be downloaded because I validate the UUID (which isn't sent at download request)... Please be consistant!

**Comment by ilyautkin** [comment]
This feature was added in commit https://github.com/modxcms/revolution/commit/83e508f44af5796938731a6df43f3d6a90233e4d

**Comment by OptimusCrime** [comment]
Old issue with an old fix. Looks good. Nice hunting @ilyautkin :)

Feel free to comment or reopen.

@modxbot close
