### ISSUE TITLE
PHP functions as fallback for output filters?

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#8099]
bertoost created Redmine issue ID 8099

Let PHP functions be an output filter when the method not already exists and the snippet couldn't be found.

Some stupid example:

[[+placeholder:base64_encode]]

The placeholder contents (as in this example) will be passed as first parameter to that base64_encode() method. Maybe also supporting parameters by :function=`p1=x&p2=y` etc.

Smarty does something too I know

**Comment by OptimusCrime** [comment]
While this is a good idea initially I think adding output filters on demand was done to ensure security and to limit what people could call as output filters.

I for one -1 this idea. Anyone else?

**Comment by Alroniks** [comment]
I think it will be insecure, such it was with eval filter. In snippet everybody can run any function, but developer have control on parameters and output.

**Comment by opengeek** [comment]
This is indeed what snippets are for.
