### ISSUE TITLE
MODX Transport Packages need to store unique identifier

### ISSUE THREAD

**Issue by fireproofsocks** [modxcms/revolution#814]
When installing and upgrading packages, the values in the modx_transport_packages table do not store a unique identifier for the package.  Instead, there's a "signature" value that seems to make lowercase the package's common name.  I think it's necessary to uniquely identify a slug or a url or a repository sub-directory as a package's unique identifier.

See http://forums.modx.com/thread/88704/transport-s-builder-awkward-pkg-name-vs-pkg-name-lower#dis-post-488055

**Comment by Mark-H** [comment]
I'm with Romain that the signature is unique. I'd also say it is to a point configurable, as the developer sets the name and version. In terms of composer-like packages, the package dependencies coming in 2.4 also use the signatures to resolve the requisite packages afaik...

**Comment by Alroniks** [comment]
I agree with @Mark-H and @rtripault 
I propose close this
