### ISSUE TITLE
Blank console after "search locally for packages"

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#8174]
bobray created Redmine issue ID 8174

I'm getting this reliably in Chrome. If I search locally for packages, and then install a found package, the console is always empty.
If I search locally for packages and then try to clear the site cache, the console is always empty.

If I reload the Manager page after the searching locally for packages, but before installing or clearing the cache, the error doesn't occur. This is also reliable.

Clearing the site_cache after searching for packages doesn't help. I have to reload the page.

**Comment by rtripault** [comment]
I remind some tweaks have been done lately on the console component, so will closing this one, assuming it's been fixed.

Please, feel free t comment/reopen if needed.
Thanks
