### ISSUE TITLE
Resource's Search Box freezes Firefox

### ISSUE THREAD

**Issue by goldsky** [modxcms/revolution#8202]
goldsky created Redmine issue ID 8202

As stated on the title.

Firefox 13.0.1 with FireBug
Works on others, eg: Chrome, Opera

**Comment by rtripault** [comment]
So closing, as this in no more relevant in 2.3.x & up.

Feel free to comment/reopen if needed.
Thanks

**Comment by goldsky** [comment]
oh wow... time flies... :+1:
