### ISSUE TITLE
Highlight Active Plugin Events

### ISSUE THREAD

**Issue by neilness** [modxcms/revolution#8212]
neilness created Redmine issue ID 8212

The Plugin UI would be greatly improved by moving the currently active system events to the top of the list, or in a separate section (see quick mockup)

this would require much less scrolling, and a glance would make it obvious which events are firing.

**Comment by whitebyte** [comment]
Unfortunately, original screenshot seems to be lost. For now, active plugins can be easily listed using standard column sorting functionality, so is this still actual?
![plugin_sorting](https://cloud.githubusercontent.com/assets/7704186/5604163/59c6d820-93cc-11e4-9800-97d234cecc9e.png)

**Comment by rtripault** [comment]
Not only active events can be sorted, but since 146c5e145b45996deef62f7c5c38e3c00053a158 (upcoming Revo 2.3.3), events are sorted by their active state per default, so closing this.

Feel free to comment/reopen if needed.
Thanks
