### ISSUE TITLE
xpdo json_encode()

### ISSUE THREAD

**Issue by meshkov** [modxcms/revolution#8236]
meshkov created Redmine issue ID 8236

Warning: json_encode() [function.json-encode]: Invalid UTF-8 sequence in argument in /home/us1/domains/test.ru/core/xpdo/xpdo.class.php on line 2327

there this error be then i want to edit files in modx and cann`t edit. then edit chunks this error not display.
And also i can`t work with documents and files.

modx 2.2.4

i use php 5.3. then i switched to 5.2, this problems and error is disappear.

Sorry for my bad english

**Comment by pbowyer** [comment]
We may have charset issues still but this has been more heavily tested since, and PHP has moved on.

Recommend closing #modxbughunt
