### ISSUE TITLE
Unexpected '{' error while installing on Windows/IIS

### ISSUE THREAD

**Issue by cktdesign** [modxcms/revolution#826]
After installing Revolution 2.2.11-pl Standard Advanced in IIS there is an error in lines 13/14/89 in config.inc.php. To fix it i surrounded the tags with ' '. Specifically i changed $config_options = {config_options}; to $config_options = '{config_options}'; , $driver_options = {driver_options}; to $driver_options = '{driver_options}'; and $modx_cache_disabled= {cache_disabled}; to $modx_cache_disabled= '{cache_disabled}'; .

**Comment by rtripault** [comment]
Let's close this.

Feel free to comment/reopen if needed.
Thanks
