### ISSUE TITLE
Form field errors below the fold

### ISSUE THREAD

**Issue by sottwell** [modxcms/revolution#8270]
sottwell created Redmine issue ID 8270

There are several forms that have required fields that fall below the fold in some situations. For example, when editing a user, the password field is below the fold when the form is saved and the page refreshes. If there is an error with the password, there is no indication that there are any errors, other than the lack of a "success" message. 

There are a couple of possible solutions to this; one would be to have an error message displayed in a popup or near the top of the page. Another would be to have the field with the error be given the focus so that the screen automatically scrolls down.

**Comment by sottwell** [comment]
This can be closed.

**Comment by OptimusCrime** [comment]
@modxbot close
