### ISSUE TITLE
Dashboards should adhere to Minimum Roles

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#8308]
wshawn created Redmine issue ID 8308

It would be nice to be able to offer different Dashboards to the same User Group without having to create Sub groups.

Following the logic in the Resource.

If is is not a Container it would serve the whole group.

If the Dashboard contains other Dashboards then the group would be applied.
Within the definition of the each Dashboard, Minimum Roles could be assigned

Additionally, It might prove helpful to toggle the inclusion of lessor Roles separated by some sort of grouping.

**Comment by alroniks** [comment]
Even if it an idea, I didn't get it. What needs to do? I am closing it, but if somebody finds it useful, please, reopen and provide an explicit description.
