### ISSUE TITLE
Duplicating a container does not maintin document ID order

### ISSUE THREAD

**Issue by wshawn** [modxcms/revolution#8315]
wshawn created Redmine issue ID 8315

I have 5 Resources

61 A
62 B
63 C
64 D
65 E
66 F

When Duplicated they become:
77 C
78 E
79 A
80 B
81 D
82 F

If someone were using sortBy=`id` in Wayfinder it would mess up the order.

**Comment by OptimusCrime** [comment]
I am pretty sure this was fixed some time ago. I will test and report back.

**Comment by wshawn** [comment]
It was fixed.
