### ISSUE TITLE
Searching for a package fails for newest additions

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#8333]
gadamiak created Redmine issue ID 8333

Not all of the newest additions in the package browser can be searched for (or displayed for that matter). They do show up as latest additions but can't be accessed by either clicking on them or typing their name or part of it into the search field. At this moment this applies to first 8 of 10 newest additions (mxCalendar 1.1.4-pl being the first and XHTML Beautify 1.0.0-beta being the last).

**Comment by rtripault** [comment]
I am closing this one since that's not a bug, but rather an "input" issue from extra developers.

Feel free to comment/reopen if needed.
Thanks
