### ISSUE TITLE
Cache not clearing when document is saved.

### ISSUE THREAD

**Issue by sean69** [modxcms/revolution#8375]
sean69 created Redmine issue ID 8375

Just had a client complain that 'her changes weren't showing up' ... when I looked at it, it appeared that the cache was not being cleared when the document was saved. 

When I looked at it, it appeared that there was so much stuff in the cache directory [massive error log] that the manager just wouldn't clear it.

Suggestion:
- move the error log out of the cache directory, 'logs' are not cache anyway & in normal circumstances I would not expect the log to be wiped when I clear the cache.

**Comment by Mark-H** [comment]
The logs are not wiped on clearing the cache.
