### ISSUE TITLE
Form Customization - Some Rules

### ISSUE THREAD

**Issue by EvilSoul** [modxcms/revolution#8407]
evilsoul created Redmine issue ID 8407

When I create a rule for one container, all ok. But when I try to create a rule for another container is one of the rules no longer work for another container.
P.S. In the explanation attached to the screenshots

**Comment by alroniks** [comment]
The issue pretty old and it seems screenshots were lost after migrating from redmine and it difficult to understand what's wrong and how to reproduce.
I am closing this one but if an issue still exists, please, reopen and share details.
