### ISSUE TITLE
default template values improperly set

### ISSUE THREAD

**Issue by rygar** [modxcms/revolution#8426]
rygar created Redmine issue ID 8426

I wanted to use form creation rules to force child document template.

I have created 'resource/create' action in FC for parent template (selected template from dropdown), and set default template as child template. It worked.

When I added second level child template, it broke - when creating new document, default template values were wrong, there was no consistent behaviour  - after using 'new document' function on parent, child templates were actually pretty random, i could not determine any pattern

example structure

parentTemplate1
--childTemplateA
-----childTemplateB

this can be fixed currently by creating separate 'resource/create' rule for parent template, without assigning template from dropdown, just using constraint field ( modResource.template = xx) - it works flawlessly then.

Bug also happens when you have 2 different parent/child templates that are not nested - modx randomly applies wrong template id (from different parent). 

This might be only visible when dealing with 'template' var, as it does influence template itself.

**Comment by rtripault** [comment]
Closing as requested per the OP
