### ISSUE TITLE
option to avoid row auto-select on grid _showMenu

### ISSUE THREAD

**Issue by netProphET** [modxcms/revolution#8450]
netprophet created Redmine issue ID 8450

Would be nice to be able to specify on a per-grid basis whether _showMenu autoselects the row or not. (Currently a custom grid may do so by duplicating _showMenu method and removing auto-select code.)

**Comment by alroniks** [comment]
Hi @netProphET It looks that it can be fix easy but could you explain why it needed?

**Comment by OptimusCrime** [comment]
This is also a very old issue that has seen no interest in the past few years. I suggest closing this as a wontfix.

**Comment by alroniks** [comment]
Closing as wontfix for now, but if it still actual, please, reopen the ticket. Thank you.
