### ISSUE TITLE
Editing Property Set Doesn't Populate Grid with Custom Values

### ISSUE THREAD

**Issue by sepiariver** [modxcms/revolution#8451]
sepiariver created Redmine issue ID 8451

Once a custom property set has been saved, going back to that snippet's property set editing tab and selecting the custom property set in the dropdown does NOT populate the custom values into the grid. Instead only the default values are displayed. The property set works as intended, but it seems like you have to re-import or re-enter ALL the values and re-save the property set if you want to edit it at all. Only noticed this in 2.2.1+ I think...

**Comment by dannevang** [comment]
Can not reproduce in MODX 2.5.7

Suggest closing this

**Comment by rtripault** [comment]
So closing.

Feel free to comment/reopen if needed.

Thanks

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @dannevang
