### ISSUE TITLE
Manager not functioning ("undefined") when accessing without "www" in front of domain

### ISSUE THREAD

**Issue by peterM** [modxcms/revolution#8458]
peterm created Redmine issue ID 8458

Hello,

I have a standard 2.2.4-pl MODX Revo installation which manager is not usable with Firefox. Using the manager with my Internet Explorer works.

When I try to access my Manager via "domain.tld/manager" using Firefox 14.0.1 it says "Undefined" instead of my site name on the left hand side, the navigation does not work, I cannot logout and there is no resources tree.

Now, there are several threads on the forum suggesting to turn of js and css compression via the MySQL entry and empty the cache (via SSH eg). That did not do to trick. There were no JS error messages on my browser, no error messages in the MODX logfile, I also tried running the manager via Firefox Safe-Mode (that is all extensions disabled) - to no avail.

Now, after searching more one member had the simpliest solution for my problem EVER. To use "www" in front of the domain name!

So when I use "www.domain.tld/manager" to login, the Manager works with with above setting!

**Comment by OptimusCrime** [comment]
Unable to reproduce. We have installations with both `www` and without `www`. Both works fine.

Going to close, feel free to reopen and/or comment if this is still an issue.

@modxbot close
