### ISSUE TITLE
Template Usage Tab

### ISSUE THREAD

**Issue by amdbuilder** [modxcms/revolution#8459]
amdbuilder created Redmine issue ID 8459

Instead of showing template usage on delete, make that data available on a separate tab.  Helpful to identify lightly used or unused templates without trying to delete each one.

**Comment by OptimusCrime** [comment]
Searching for resources by templates is supported in the uberbar now.

Going to close, feel free to reopen and/or comment.

@modxbot close

**Comment by whitebyte** [comment]
FWIW there is an extra called modDevTools by @argnist that makes exactly what topicstarter wants

**Comment by OptimusCrime** [comment]
Thanks for adding that, @whitebyte :)
