### ISSUE TITLE
System Setting of Template Type doesn't work correctly if not another type first

### ISSUE THREAD

**Issue by FuzzicalLogic** [modxcms/revolution#8464]
fuzzicallogic created Redmine issue ID 8464

For some reason, the Template Type in System Settings works great if it was originally text or a number. However, creating the setting as a Template does not allow the value to be retrieved from Snippets via getOption();. To allow getOption() to work with Template Type setiings, it must be created as a text or number first, saved, set to a valid Template ID, then changed to a Template Type.

Additionally, if it is not created in this manner, it doesn't work for any value, even if you change the type to another type. This is true on the Cloud and local installs, as well.

**Comment by alroniks** [comment]
I can not reproduce it anymore. And I don't remember such issues a lot of time. Please, reopen if it's still actual.
