### ISSUE TITLE
error message "filemtime() [function.filemtime]: stat failed" with static resource snippet

### ISSUE THREAD

**Issue by FickleLife** [modxcms/revolution#8466]
ficklelife created Redmine issue ID 8466

I have set a snippet called "getProductStats.php" located at assets/web_assets/snippets/getProductStats.php as a static resource using a media source pointing to assets/web_assets/. When I edit the file externally using Coda2 I save it and it is uploaded to the FTP automatically, I then visit the page where the snippet is called and all loads fine, but only the first time someone visits the page. Subsequent loads display this error:

<pre>
Warning: filemtime() [function.filemtime]: stat failed for snippets/getProductStats.php in /home/ccplay/public_html/core/model/modx/modscript.class.php on line 131
</pre>

on line 131 of modscript.class.php is:
<pre>
$sourceMTime = filemtime($this->getSourceFile());
</pre>

Seems like a bug, so I thought I'd put it here!

Cheers

**Comment by rtripault** [comment]
So closing.

Feel free to comment/reopen if needed.
Thanks
