### ISSUE TITLE
Form Customization Checkbox Field Label

### ISSUE THREAD

**Issue by doubleswirve** [modxcms/revolution#8485]
doubleswirve created Redmine issue ID 8485

I have a resource/update set and I'm trying to change the label of the "isfolder" field.

I have changed the label but it still displays the default label of "Container".

The other label changes have worked (for the "alias" field for example).  I wonder if this is related to "isfolder" being a checkbox.

**Comment by adamwintle** [comment]
I just quickly checked this and it seems to be working fine. It could have originally been a cache issue. You can also change these using the Lexicons.

@modxbot close
