### ISSUE TITLE
Element Category access permissions deletes Element content

### ISSUE THREAD

**Issue by SebastienDaniel** [modxcms/revolution#8487]
Askarii created Redmine issue ID 8487

This happened with Template Variables.

I create a User Group (Restricted) in which I place a TV called (restrictedTV)

As a user from the RESTRICTED group, I open a resource and see the restrictedTV, I add some content, save the resource and publish it.
When a user from ANOTHER user group opens that ressource, modifies something and SAVES the ressource, the content of restrictedTV (to which he didn't even have access) is deleted.

**Comment by smg6511** [comment]
I tested for this issue on 2.8.5 and 3.1.0-dev and found no problems.
