### ISSUE TITLE
modResource fetched from cache as "new"

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#8513]
ReSpawN created Redmine issue ID 8513

While trying to get all TVs and their values via the basic getTemplateVars function, it ocurred to me that they were empty. Later I found out that upon cache refresh, the first time they were available (not new, fetched from the database), and after the second they were gone. Simply because the resource was cached and then regenerated inside the modResource class, thus marking it as "new".

As a result of it being new, it could fetch the relative template variables by template, but not by the resource ID, thus missing the values.

I fixed it by flagging the resource as "not new" manually; @$this->_resource->_new = false;@

**Comment by OptimusCrime** [comment]
Have anyone else experienced this? I can not say I can recreate this.

Awaiting feedback.

**Comment by pbowyer** [comment]
No feedback in 11 months, recommend closure #modxbughunt
