### ISSUE TITLE
Form Customization category tab.

### ISSUE THREAD

**Issue by toasteddigital** [modxcms/revolution#8533]
toasteddigital created Redmine issue ID 8533

This is just a minor one but can cause some confusion with clients:

1. Move a template variable using form customization to one of the modx-resource-main- regions.

2. By default, this template variable's category will still appear in the template variables tab under "categories", even when empty.

**Comment by adamwintle** [comment]
@modxbot close because this is a duplicate

**Comment by adamwintle** [comment]
@modxbot close
