### ISSUE TITLE
Blank package manager in subdomain installation

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#8536]
gadamiak created Redmine issue ID 8536

Package Manager fails to load in 2.2.5-dev when site is in a subdomain and @compress_js@ is on. No such problem in subdomain install in 2.3.0-dev.

Switching it off or lowering number in @compress_js_max_files@ to @9@ makes it work again.

@compress_css@ is on, @compress_js_groups@ is on.

**Comment by rtripault** [comment]
Since 2.3.x is out, i guess it's time to close this one.

Feel free to comment/reopen if needed.
Thanks
