### ISSUE TITLE
phpthumb far=1 does not work if imagemagick available

### ISSUE THREAD

**Issue by erhard** [modxcms/revolution#8621]
erhard created Redmine issue ID 8621

In some of my MODX-installations the far-option of phpthumb does not work. I found out a relationship between ImageMagick and this behavior: If there is no ImageMagick installed on the server (and only GD is used), the far-option works correct. After installing ImageMagick it doesn't work any more.
In this case, e.g. the thumbnail-images in the file-browser are displayed in wrong aspect ratio.

**Comment by OptimusCrime** [comment]
Pretty sure this has to do with phpThumb, not Modx. There is no way to fix this in Modx alone.

**Comment by adamwintle** [comment]
I agree with @OptimusCrime this is a phpThumb issue and not MODX core

@modxbot close
