### ISSUE TITLE
Manager right-click on tablets

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#8750]
mindeffects created Redmine issue ID 8750

How can I work with the manager on a touch device like the iPad? The right-click menus just don't work. I would LOVE to see an "Edit" icon, because it simply speeds things up (not only on tablets): it's on click less for a standard function like edit something.

cheers
Oliver

**Comment by Ruslan-Aleev** [comment]
Related with https://github.com/modxcms/revolution/issues/14125

**Comment by JoshuaLuckers** [comment]
Related PR: https://github.com/modxcms/revolution/pull/14806

**Comment by Ruslan-Aleev** [comment]
I think we can close this issue.

**Comment by mindeffects** [comment]
Yes, we can close this.
John‘s solution #14806 is awesome!
