### ISSUE TITLE
Basic functions without JavaScript

### ISSUE THREAD

**Issue by Gallenkamp** [modxcms/revolution#8837]
gallenkamp created Redmine issue ID 8837

Sometimes, on not so well working installations, i.e. logout is impossible as it relies on Javascript. Or even "clear cache".

Those javascripts are generated via php and sometimes cause a 500 error on certain setups. Its nearly impossible to get rid of them quickly if the whole main funcions in the manager rely on javascript.

So: please replace these links with standard html links.

**Comment by Mark-H** [comment]
There's a MAB working group discussing the future manager. In ExtJS it's unlikely that everything that uses javascript for links is going to change, however I would accept pull requests that fix key places. 

Logging out is functional without javascript again as of 2.5.3/4.
