### ISSUE TITLE
Set amount of list grid-items in system settings

### ISSUE THREAD

**Issue by DonQuicky** [modxcms/revolution#8906]
donquicky created Redmine issue ID 8906

The default amount of packages shown in package management [grid] is set to 10. It would be nice to set the amount as an option in the system settings. Like any amount or all. For example: to examine  updates of packages are availble you have to go through many pages if you have many packages installed.

**Comment by netProphET** [comment]
Superceded by #12518. This has finally been looked at - thanks for reporting! #modxbughunt
