### ISSUE TITLE
Revo Manager: Large Resources/Elements Tree scrolls toolbar out of scope

### ISSUE THREAD

**Issue by skndn60** [modxcms/revolution#8958]
skndn60 created Redmine issue ID 8958

When working with sites with lots of elements/resources, the toolbar of the elements/resources tree scrolls out of scope. This is caused by the definition of the scrolling area of the manager tree which encloses the full tree, including the toolbar. The scrolling area should only enclose the actual content area of the tree.

**Comment by OptimusCrime** [comment]
With the rollout of the new manager theme, it is likely that this is fixed.

If this is indeed still an issue, feel free to comment or reopen this issue.

@modxbot close
