### ISSUE TITLE
Developer policy gives access to users and security

### ISSUE THREAD

**Issue by gadamiak** [modxcms/revolution#8961]
gadamiak created Redmine issue ID 8961

The default "developer" access policy is meant to be:

> Context administration policy with most Permissions except Administrator and Security functions.

However, it only disables access to relevant menu items not the actions itself. A user with developer policy can gain access to user management by directly using @?a=56@ in manager URL. The same applies to other "restricted" actions.

This policy should disable menus _and_ the relevant permissions.

**Comment by dannevang** [comment]
I do not believe there is a "Developer" access policy in current Revo?

Recommend this one to be closed.

#modxbughunt

**Comment by OptimusCrime** [comment]
You're right. It is gone.

@modxbot close
