### ISSUE TITLE
Modx revolution control panel

### ISSUE THREAD

**Issue by chekulaev** [modxcms/revolution#8972]
chekulaev created Redmine issue ID 8972

Is it possible to add to the system setings width of the left panel (containing the tabs Resources, Elements and Files)?

**Comment by OptimusCrime** [comment]
I think this is a horrible idea considering it is fluid, the manager is somewhat responsive and people have different resolutions.

I suggest closing this unless people have a really good use case for this.

**Comment by adamwintle** [comment]
@OptimusCrime I agree, this can be closed. @modxbot close
