### ISSUE TITLE
Form customization: TV moved to new tab, but the category of the TV still shows up under the Tempalte Variables Tab

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/revolution#8988]
sonicpunk created Redmine issue ID 8988

So the title of this post says it all. I used form customization to to move a TV to the main document settings tab - easy. But when I click on the template variable tab, the category that this TV belongs to still shows up there. How can I hide the category from the template variables tab?

Here is a link to my post on the forum with screenshots:
http://forums.modx.com/thread/79951/form-customization-tv-moved-to-new-tab-but-the-category-of-the-tv-still-shows-up-under-the-tempalte-variables-tab#dis-post-441052

**Comment by adamwintle** [comment]
@modxbot ~area-form_customization

**Comment by Jako** [comment]
Fixed with #13649
