### ISSUE TITLE
Add CSV to list of default content types

### ISSUE THREAD

**Issue by garryn** [modxcms/revolution#9027]
garryn created Redmine issue ID 9027

It'd be handy to have CSV added to the list of default content types. Needing to output resources in that format is quite frequent based on my experience.

**Comment by OptimusCrime** [comment]
I agree with @rtripault . I see no point in shipping MODX with a CVS content type. Right now MODX shipps with the most common web content types. HTML, JS, CSS, PDF and a few more. CVS is not that common. 

This feature request is old and has not gained a lot support. I'm closing this. Feel free to reopen or comment.

@modxbot close
