### ISSUE TITLE
Processor path mangled in runProcessor()

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#9031]
bobray created Redmine issue ID 9031

This is a weird bug that only occurs in the context of unit testing.

If a processor is called repeatedly, the path gets changed for later calls.

I was able to solve by putting these lines at line 1572 of runProcessor() in the modx class:

<pre>
    $className = str_replace('Workspace', '', $className);
    $className = str_replace('modElementPropertysetCreateProcessor', 'modPropertysetCreateProcessor', $className);
    if (!strstr($className, 'Category')) {
        $className = str_replace('modElementSnippetCreateProcessor', 'modSnippetCreateProcessor' , $className);
        $className = str_replace('modElementPluginCreateProcessor', 'modPluginCreateProcessor', $className);
        $className = str_replace('modElementTemplateCreateProcessor', 'modTemplateCreateProcessor', $className);
        $className = str_replace('modElementChunkCreateProcessor', 'modChunkCreateProcessor', $className);
        $className = str_replace('modElementTvCreateProcessor', 'modTemplateVarCreateProcessor', $className);
    }
</pre>

**Comment by Mark-H** [comment]
There's been several changes to the way processors are loaded since 2012, so I'm going to close this issue. If it's still an issue, feel free to reopen with more details.

**Comment by BobRay** [comment]
This is still an issue in 2.5.7 and the fix above still works. I can't see where it's happening, but it still is.  Somewhere, 'element' is being injected into the class name on subsequent calls to the create processor. It only happens with elements and namespaces, and only when running PhpUnit tests.

I consider it important because it makes serious unit testing impossible without the inserted code. 

I don't have the option to reopen this.

**Comment by OptimusCrime** [comment]
You need to post some of the unit tests that causes the error, as well as the actual PHP error in question. Running the test suit for MODX calls multiple processors multiple times and I've never had the issue you report here.

**Comment by BobRay** [comment]
The unit tests are for MyComponent and are really extensive and complicated. I don't think they would help, because I only found the error by spending hours stepping through the code in a debugger and I never did find the source of the problem.

It's probably more productive for me to look at the MODX unit tests.  If I can redesign mine to match, the probably may go away. 

Since I'm the only one experiencing this and I have a workaround. I'm closing this.
