### ISSUE TITLE
Speed up creation of new System Settings

### ISSUE THREAD

**Issue by BobRay** [modxcms/revolution#9032]
bobray created Redmine issue ID 9032

In a unit test script using the create processors on my machine, it takes 2.5 seconds to create over 40 elements, but it takes 7.4 seconds to create two System Settings.

Creating them directly with newObject is almost as slow.

I imagine it's because of the lexicon entries, so it may not be fixable, but it seems like an awfully long time.

**Comment by Mark-H** [comment]
I believe this was due to refreshing of the cache in modSystemSetting->save, which has been fixed in 2.2.11 (december 2013).

**Comment by BobRay** [comment]
Tested - this is definitely fixed.
