### ISSUE TITLE
Resources Browser size problem

### ISSUE THREAD

**Issue by rainbowtiger** [modxcms/revolution#9047]
rainbowtiger created Redmine issue ID 9047

When opening the Resources Browser from within TinyMCE, it sizes itself based on the monitor size rather than the browser window so, so that on large monitors the right side and bottom are cut off unless you make your browser window really wide and tall. My clients typically can't see the buttons at the bottom of the Resources Browser without resizing.

Additionally, the Resource Browser does not remember its size and position, so even if you adjust its size, then next time you open it from TinyMCE the size is too big again. 

The Resources Browser, when opened from the File tab in the Manager, works just fine. It bases its size on the browser window, and remembers its size and position.

**Comment by adamwintle** [comment]
The MODX Browser has had a recent overhaul and works well at most monitor sizes.  The TinyMCE bugs (if still present) should be logged on their own bug tracker. @modxbot close
