### ISSUE TITLE
Media source title wrong in browser

### ISSUE THREAD

**Issue by rainbowtiger** [modxcms/revolution#9048]
rainbowtiger created Redmine issue ID 9048

When creating a new media source (e.g., "images" linked to the images folder), then making that source the default, then opening the Resources Browser, the correct files are shown (e.g., the images in the images folder), but the folder name on the left says "media" rather than the actual folder name. If you change to a different media source, then change back, the folder name is now correct (e.g., it will say Images instead of Media).

**Comment by rtripault** [comment]
This appears to be fixed (at least in the 2.5 branch, but could very be solved since quite some times), so i'm closing the issue.

Feel free to comment/reopen if needed.
Thanks
