### ISSUE TITLE
Access Policies doesn't contain new permissions from the Policy Template automatic

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#9054]
bertoost created Redmine issue ID 9054

First off; I hope I can describe well... so let me try to explain a bit

I have several access levels in my project. So I created multiple user groups etc.
From highest to lowest;
- Professionals
- Ambassadors
- Members

Each of them has his own permissions and some of them are shared over all and some of them are just for a specific group of users.

For example I use an Agenda component. The Members can create new items, edit and remove their items. Ambassadors can do the same but Professionals can edit and remove items from everyone.

So for all this custom permissions I created a policy template. This template is going to contain all custom permissions. Near to that I create 3 new access policies, based on that new template.

Now when I add a new permission to the policy template I expect this to be "false" at default in all the accociated access policies, unless I check them and save that policy. This is not happening. The access policies doesn't contain this permission yet. So when I do $modx->hasPermission('my_new_permission_key'); it always returns true because he cannot find it yet.

I did flush the permissions of course but that wasn't it.
Somehow I need to edit the access policy itself and without changing anything, saved it.
Then I did a flush permissions again and voila.. the permissions is loaded in the list.

So the strange thing is; why do I need to save my access policies (without changing anything) to get the new permissions assigned (as false)?

This looks like a bug to me, but maybe I'm wrong.

**Comment by adamwintle** [comment]
@bertoost Is this still an issue or can this now be closed?

**Comment by alroniks** [comment]
In 2.7.0-dev it works as expected, so closing it.
