### ISSUE TITLE
Drag and drop resource tree operation bugs

### ISSUE THREAD

**Issue by juro** [modxcms/revolution#9084]
juro created Redmine issue ID 9084

Drag and drop operations in resource tree have many bugs, inherited from 2.1 version, regarding user rights checking, unnecesary database operations and wrong cache management.
We have reported this a long time ago, unfortunately this wasn't ever solved, althought we have provided our own patch. Please refer to #4918 for more details.

Also #6976 can ruin your entire site structure on single drag operation and is same for 2.2. We advise to our clients not to use any custom tree sort order, there is no way (other that restore from backup) to revert this operation

**Comment by OptimusCrime** [comment]
Pull request from @theboxer has been merged. Not sure why this was not closed. Going to do so now. Thanks for reporting this!

@modxbot close
