### ISSUE TITLE
Bug when OnMediaSourceGetProperties Fired

### ISSUE THREAD

**Issue by lokamaya** [modxcms/revolution#9150]
lokamaya created Redmine issue ID 9150

Activated OnMediaSourceGetProperties system event make all media browser error and unavailable to load files, if the event did not call $modx->event->output() and return valid array or json.

This bug triggered by modmediasource.class.php after invoked "OnMediaSourceGetProperties" around line 414-417, call _array_merge_ without validating the input array.

_Bug Fix:_

Add _@if (is_array($result) && !empty($result))@_ before merging the array should solve the problem.

<pre>
            foreach ($results as $result) {
                $result = is_array($result) ? $result : $this->xpdo->fromJSON($result);
                if (is_array($result) && !empty($result)) $properties = array_merge($properties,$result);
            }
</pre>

See http://forums.modx.com/thread/80492/static-resources-and-media-sources#dis-post-443774

**Comment by alroniks** [comment]
Seems to be fixed, works in 3.x.
