### ISSUE TITLE
Standard permissions in new installation

### ISSUE THREAD

**Issue by mathis** [modxcms/revolution#9177]
mathis created Redmine issue ID 9177

Hi

In a new MODX installation the standard directory permission for /assets is 777. Some providers - such as mine - may disallow PHP scripts within directories with permission 777. Therefore 755 may be a better choice.

I hope this is helpful.

**Comment by dannevang** [comment]
This is resolved. 

The MODX installer asks what permissions to use and the default suggestion in 755/644.

Recommend closing.

#modxbughunt
