### ISSUE TITLE
Menuindex from parent gets changed automatically to 1 when children are moved around in the tree

### ISSUE THREAD

**Issue by sonicpunk** [modxcms/revolution#9179]
sonicpunk created Redmine issue ID 9179

I have 3 separate admin rights with different resource groups.  Super Admin, Web Admin, Editor.  The parent is shown in the  navigation and should have a menuindex of 5.  Inside of this parent is another layer of parents.  So we have layer 1:  main navigation, layer 2:children of the main  navigation points, and layer 3: children of the children.  When the Editor drags the children resources around, their parents parent on layer 1 gets assigned a menuindex of 1 although it should be 5 and the Editor did not even touch that layer.  He has access to it however.  When I log in as a Super Admin or Web Admin, this does not happen.

**Comment by GulomovCreative** [comment]
> Testing is sad

The problem cannot be reproduced because (and this assumption) it is no longer possible to gain access to the children of the parent access to which is prohibited for you.

@Jako Probably you can close the issue?
