### ISSUE TITLE
Ellipsis filter needs to be smarter about handling of HTML Tags

### ISSUE THREAD

**Issue by MokoJumbie** [modxcms/revolution#9192]
MokoJumbie created Redmine issue ID 9192

Given the html string:

> @<p>Aenean lacinia bibendum nulla sed consectetur. <img src="path/to/image.png" alt="An image that doesn't really exist" /> Cum sociis natoque penatibus et magnis.</p>@

If the ellipsis filter cuts the string in the middle of the alt text, the following is output:

> @<p>Aenean lacinia bibendum nulla sed consectetur. <img src="path/to/image.png" alt="An image that&#8230;</img></p>@

This fails in a couple ways. The quoted attribute should be enclosed in quotes. Also, the filter doesn't know about self-closing tags like:

> @<area />
> <base />
> <basefont />
> <br />
> 
> <hr />
> 
> <input />
> <img />
> <link />
> <meta />@

The expected output would probably be:

> @<p>Aenean lacinia bibendum nulla sed consectetur. <img src="path/to/image.png" alt="An image that&#8230;" /></p>@

...but this corrupts attribute values and could lead to things like:

> @<p>Aenean lacinia bibendum nulla sed consectetur. <img src="path/to/ima&#8230;" /></p>@

...which would break the image, so maybe the following is a better solution:

> @<p>Aenean lacinia bibendum nulla sed consectetur. <img src="path/to/image.png" alt="An image that doesn't really exist" />&#8230;</p>@

**Comment by OptimusCrime** [comment]
This is more or less to be expected. The `ellipsis` output filter is dump and easy. I am _not_ very keen on implementing the monstrosity copied from the StackOverflow question that does [HTML parsing with regex](https://stackoverflow.com/a/1732454/921563). 

The developer needs to be in control of the input, and in scenarios where HTML/rich text is allowed, find other solutions that the `ellipsis` filter. Perhaps using CSS or something else.

Going to close this as wontfix. Feel free to comment or reopen the issue if you disagree.

@modxbot close
