### ISSUE TITLE
TVs not load properly when creating new resource

### ISSUE THREAD

**Issue by lokamaya** [modxcms/revolution#9246]
lokamaya created Redmine issue ID 9246

Discussion:
http://forums.modx.com/thread/81009/possible-bug-on-creating-new-resource

When creating new Resource, TVs did not load correctly when we change default template on the fly, either using Plugin or Form Customization.

**Comment by Alroniks** [comment]
Took for checking #modxbughunt

**Comment by Alroniks** [comment]
Checked on fresh 2.5.x, all works fine. I've created two templates, two TVs, linked them, created FC rule as described on forum and then tried to create child resource. Proper TV was loaded.
So need to close as fixed before. #modxbughunt
