### ISSUE TITLE
to automatically get relative path in installed modx revo config files. 

### ISSUE THREAD

**Issue by jackymao** [modxcms/revolution#9252]
jackymao created Redmine issue ID 9252

I recently try to install modx on appfog.com, I meet a problem that every time my appfog app (modx) restart, the real path of the app is changed, then the modx visiting will break.  So I want to use the relative path in all modx config file. or this could be an option when installing Modx.

Although this can be done manually after installed Modx, but I think this may better to be done automatically during installing process. This will also good for making a app template so any newly setuped modx app will automatically get relative path in the config files.

I searched and found this feature was asked 9 months ago by Eprochasson, (http://tracker.modx.com/issues/7366), and he has a solution which currently not integrated in Modx for now.

Can this feature be added in Modx 2.3.0-rc or any recently release? This should be really helpful and could make Modx be usable on many similar situations.

Thanks.

Best regards,
Jacky

**Comment by adamwintle** [comment]
Duplicate of https://github.com/modxcms/revolution/issues/7366 

@modxbot close
