### ISSUE TITLE
apache return wrong file with default .htaccess

### ISSUE THREAD

**Issue by Qwarble** [modxcms/revolution#9253]
Qwarble created Redmine issue ID 9253

Found situation, when apache didn't rewrite path for wrong urls (neither file nor dir). It returns index.php and status 200  instead.

There is example.
When I moved one site from Joomla, I had to set redirects for old urls:
/index.php/component/calckr
/index.php/component/calckr?var=12323
...

but when I try to get this url, apache doesn't rewrite wrong path and returns index.php with status 200 and modx doesn't fire PageNotFound event.
I think in these cases apache should do these rules:
# The Friendly URLs part
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]

but it doesn't
I am not strong in mod_rewrite and change my htaccess like this:

# The Friendly URLs part
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]

#New rule for urls with index.php
RewriteCond %{REQUEST_URI} index\.php.+
RewriteRule ^(.*)$ index.php?q=$1 [L,QSA]

May be someone who know more suitable solution can change default modx .htaccess file.

**Comment by adamwintle** [comment]
I think this was most likely a unique problem with your setup, and not a bug with MODX itself. If you keep having this issue post on the MODX Forums for help or go to the Slack chat at http://modx.org

@modxbot close
