### ISSUE TITLE
ellipsis outputfilter bug

### ISSUE THREAD

**Issue by joergwork** [modxcms/revolution#9265]
joergwork created Redmine issue ID 9265

in line 335 please change:
@if ($strLower != 'br' || $strLower != 'hr') {@
to:
@if ($strLower != 'br' && $strLower != 'hr') {@

**Comment by OptimusCrime** [comment]
The output filter for ellipsis has been enhanced and rewritte since this issue was posted. I am pretty sure this issue does not apply anymore.

@modxbot close
