### ISSUE TITLE
Issue on rackspace clouds

### ISSUE THREAD

**Issue by dylanwoo** [modxcms/revolution#9272]
dylanwoo created Redmine issue ID 9272

See this

http://forums.modx.com/thread/80423/modx-having-a-hard-time-on-rackspace-cloud?page=2#dis-post-446916

even though the newer versions of Modx is giving the ability to disable flock, it appears that the application is still using flock. I still see errors "Exclusive locks are not supported for this stream" on a site that has had flock disabled using the new variables in the latest version (./core/xpdo/xpdo.class.php: const OPT_USE_FLOCK = 'false';
)

On a host such as GoDaddy, you probably won't see the file corruption because of their single node environment (we use a multi node environment).

Speaking of multi node, Modx looks to be using the process PID, which won't work reliably on our environment as the same PIDs can be re-used at the same time in our environment on the different nodes. A more reliable process might be to use the hostname/servername in conjuction with the PID.

**Comment by OptimusCrime** [comment]
From what I can tell, this was solved in the xpdo repo.

Closing the issue, feel free to reopen if this is still an issue.

@modxbot close
