### ISSUE TITLE
System setting "container_suffix" not respected on containers if empty

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#9273]
bertoost created Redmine issue ID 9273

When you leave this one empty, containers will get ".html" after their alias name.

This is not what I expect. I would like to have URLs as "www.example.com/test" (not with the trailing slash, and even not with .html for contiainers).

**Comment by Alroniks** [comment]
Look like it works fine now. I removed value from `container_suffix` system setting and marked resource as container. It opens as it should, without trailing slash.
So let's close it. #modxbughunt
