### ISSUE TITLE
Outputmodifier "add" and , as decimal separator

### ISSUE THREAD

**Issue by spoetnik** [modxcms/revolution#9274]
spoetnik created Redmine issue ID 9274

Here in Holland we use a comma as the decimal-separator.
Ussing the "add" outputmodifier on a TV with a comma as seperator removes the decimals.

This is my nasty work-around::
[[+tv.productPrice:replace=`,==.`:add=`[[+price:replace=`,==.`]]`:replace=`.==,`]]

In fact, I replace the comma for a dot, use the "add" outputmodifier, en the replace the dot for a comma.

**Comment by Devlanda** [comment]
This is not an issue. You should use replace once at the end.
I tested this with two Template Variables (numeric values, 1 decimal), with a dot as separator.

[[*testTV:add=`[[*testTV2]]`:replace=`.==,`]]

#modxbughunt

**Comment by OptimusCrime** [comment]
@modxbot close
