### ISSUE TITLE
config.inc.php variables will not populate

### ISSUE THREAD

**Issue by ibnpaul** [modxcms/revolution#9278]
ibnpaul created Redmine issue ID 9278

I am trying to install 2.2 and have followed the basic install guide exactly. However, the placeholder variables in config.inc.php, such as {database_type}, are not being filled in with their values, which is causing the installation to fail. I have tried filling in the database variables and a few others which allowed the install to finish, but the site still fails to load due to the other variables not being filled in. I have tried multiple times, using both the zip file from the main site as well as the 2.2 stable branch from Github, but the result is the same each time. I also double checked permissions and unzipped the archive on the server to avoid file transfer errors.

I have attached a copy of the generated config.inc.php from my last install attempt.

**Comment by adamwintle** [comment]
I think this was most likely a unique problem with your setup, and not a bug with MODX itself.  If you keep having this issue post on the MODX Forums for help or go to the Slack chat at modx.org 

@modxbot close
