### ISSUE TITLE
Setup overwrites config with default placeholders

### ISSUE THREAD

**Issue by Gallenkamp** [modxcms/revolution#9292]
gallenkamp created Redmine issue ID 9292

Here's the setup:

Fresh MODX 2.2.6, installes in apache, PHPInfo is attached.

On rerunning the setup, it dies on step 2 (install?).

If I reopen  /core/config/config.inc.php, Its full of placeholders instead of actual values.

Contact me at guido.gallenkamp@googlemail.com for access data to the server.

**Comment by pbowyer** [comment]
Appears fixed; worth closing the issue #modxbughunt

**Comment by rtripault** [comment]
So closing.

Feel free to comment/reopen if needed.
Thanks
