### ISSUE TITLE
Uploaded file permissions are incorrect

### ISSUE THREAD

**Issue by Version2beta** [modxcms/revolution#9343]
version2beta created Redmine issue ID 9343

When uploading a file through the files tab in the manager's left pane, the file on the file system does not comply with the system settings for new files.

On the file system, the new file has these permissions:

<pre>-rw-r--r--  1 www-data www-data 35401 2012-12-24 19:51 karma.jpg</pre>

In system settings, the key "new_file_permissions" is set to "0660".

Likewise, when creating a folder, the permissions are not correct. The key "new_folder_permissions" is set to "0770". However, on the disk the new folder looks like this:

<pre>drwxr-x---  2 www-data www-data  4096 2012-12-24 19:54 tests</pre>

**Comment by BobRay** [comment]
I haven't tested this, but I think if the cache folder itself is deleted, MODX may re-create it with 0700 permissions.
