### ISSUE TITLE
baseURL in media source needs ../ for picture preview

### ISSUE THREAD

**Issue by DoggyStyle** [modxcms/revolution#9360]
doggystyle created Redmine issue ID 9360

When following instructions from http://rtfm.modx.com/display/revolution20/Adding+a+Media+Source the mouseover preview of pictures in the new media source is not working in the file tree. You have to add ../ before your path. If you do the same for basePath the media source is not working at all. Documentation should tell this or better it should not be necessary to add ../

Best,

Mike

**Comment by mcnickel** [comment]
@rtripault Since everything works as expected, the issue can be closed.
#modxbughunt

**Comment by rtripault** [comment]
Thanks @mcnickel this should indeed be fixed with #13295 being merged

**Comment by gpsietzema** [comment]
#modxbughunt #1point to @mcnickel
