### ISSUE TITLE
Make minify symlinks configurable through the system settings

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#9383]
bertoost created Redmine issue ID 9383

For local (components) development I have centralized all my components, lets say in /var/www/modx/components/***

I have also installed several MODX installations where I develop my components, lets say in /var/www/modx/modx-for-mycmp/ (which contains a clean MODX installation)

For developing I use symlinks in my assets/components/ and core/components/ directory, so I can keep my components code in 1 and my MODX in 2.

So it's like;
/var/www/modx/modx-for-mycmp/assets/components/mycmp/ ==> /var/modx/components/mycmp/assets/components/mycmp/
And:
/var/www/modx/modx-for-mycmp/core/components/mycmp/ ==> /var/modx/components/mycmp/core/components/mycmp/

Works like a charm, only the problem with the Google Minify is that this one works with realpath() of PHP and this way not allow symlinked paths. What I had to do is putting this in the manager/min/index.php

<pre>
$min_symlinks['/assets/components/mycmp/'] = '/var/www/modx/components/mycmp/assets/components/mycmp/';
</pre>

Would be great if this can be configged (in some JSON style?) through the system settings.

**Comment by alroniks** [comment]
As mininfier was removed from 3.x this issue becomes as won't fix. So, I am closing it.

Related PRs and issues:  https://github.com/modxcms/revolution/pull/13194 and https://github.com/modxcms/revolution/pull/12778
