### ISSUE TITLE
TV cross-reference breaks MODX

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#9402]
mindeffects created Redmine issue ID 9402

I just tested, if a TV could have another TV as default value. Guess what? It works! Awesome feature! 

But when you assign the values crosswise (tv1=tv2 and tv2=tv1) the parser does not solve this conflict (infinite loop) and creates a blank page. The error log stays empty.

Some error message would be nice to have. Either as tv-values or in the error log.

**Comment by adamwintle** [comment]
@mindeffects do you know if this issue is still present?

**Comment by mindeffects** [comment]
Yes, @adamwintle, it is. Same behaviour when you cross-reference TVs:

Works fine:
`TV1: = What?`
`TV2: = TV1 is "[[*tv1]]" and "[[*tv2]]" is TV2.`

Fails:
`TV1: = TV1 is "[[*tv1]]" and "[[*tv2]]" is TV2.`
`TV2: = TV1 is "[[*tv1]]" and "[[*tv2]]" is TV2.`
With this error:
`Fatal error: Allowed memory size of 104857600 bytes exhausted (tried to allocate 65484 bytes) in /webroot/www/core/xpdo/om/xpdoobject.class.php on line 660`

**Comment by OptimusCrime** [comment]
Can you show actual code for this? I am not sure how this works.

**Comment by mindeffects** [comment]
It's just two text TVs, @OptimusCrime. I edited the former post a little to make things a little easier to understand. Hopefully. ;-)
Just define TV1 and TV2 like in "fails" and let both TVs generate their output in the content field. You will see the error then.

**Comment by Mark-H** [comment]
Er, that sounds like intentionally creating a recursive loop. What is your expected outcome?

**Comment by mindeffects** [comment]
Yes, this is "intentionally creating a recursive loop" but I came up with it while testing different kinds of "using TVs inside TVs" or more complex structures like "TVs containing chunks with TVs based on system settings which have ..." and accidentally(!) creating a recursive loop.
The server reported a "time out" and there was nothing in the error log. I don't know if there is a simple and fast way for the parser to pre-check stuff like that without loosing to much performance. If not, well, then this issue can be closed.
-- 
mindeffects
creations for media.print.online
adr mindeffects e.K. · aachener str. 628 · 50226 frechen · germany
fon +49-2234-379545-0 ·  fax +49-2234-379545-2
eml info@mindeffects.de ·  web http://www.mindeffects.de
hrg Gerichtsstand Köln HR A 14875 ·  ust-id DE186270670

MODX Ambassador Deutschland (Köln)

**Comment by OptimusCrime** [comment]
Not sure how to solve this problem really. I guess it is possible to implement algorithms that looks for cycles in a graph, but that has a high time complexity.

The problem here is that is is much more problem than just `tv1 => tv2, tv2 => tv1`. What if you did `tv1 => tv2, tv2 => tv3, tv3 => tv1`?

**Comment by OptimusCrime** [comment]
Should we close this as a wontfix as this is not trivial to fix? The loops in these graphs can be much more complex than the one described in these posts. Locating cycles in a graph feels a bit overkill for this.

While this is indeed a problem it is not simple to fix this.

**Comment by mindeffects** [comment]
Maybe a "counter per item" could do the job? After N iterrations without a final result the parser could stop and output an error.
To simple?

**Comment by mindeffects** [comment]
Or just can this issue. :-D
There is way more important stuff!

**Comment by OptimusCrime** [comment]
I am closing this @mindeffects for reasons stated above. While a counter could work it still would be a hack for a scenario that happens veeery rarely.

Feel free to comment or reopen if you feel otherwise.

@modxbot close
