### ISSUE TITLE
Query string truncated inappropriately

### ISSUE THREAD

**Issue by mburtscher** [modxcms/revolution#9405]
mburtscher created Redmine issue ID 9405

We have the site ribbl.com running with Revolution 2.2.5 with friendly urls enabled. We have two contexts:

web: German website -> https://www.ribbl.com/de/
en: English website -> https://www.ribbl.com/en/

When accessing the context's start page with a query string, the query string is completely removed with a 301 redirect:

https://www.ribbl.com/de/?test=1 -> https://www.ribbl.com/de/

Same request works for all pages except the context's start page:

https://www.ribbl.com/de/kaufen/?test=1 works

I tracked down the issue in modRequest::_cleanResourceIdentifier. There is a check comparing base_url (https://www.ribbl.com/de/) to $_SERVER["REQUEST_URI"] (https://www.ribbl.com/de/?test=1) and redirects to base_url if the check fails.

Very bad for visitor tracking because campaign tracking will not work for links like this: https://www.ribbl.com/de/?utm_campaign=test&[.......]

**Comment by rtripault** [comment]
This appears to be solved (tested on 2.4.0-dev). Furthermore, the issue may depend on the way you handle context "routing" (ie. either a plugin or dedicated gateways -- tested with dedicated gateways). So closing.

Please, feel free to comment/reopen if needed.
Thanks
