### ISSUE TITLE
TV fields for files and images are to narrow

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#9423]
mindeffects created Redmine issue ID 9423

The TV fields for files and images are to narrow to show long paths. There is plenty of space on the right side – why not use it? Please look at the attached screenshot and you know what I mean. This is nearly a showstopper for user interfaces.

thanks
Oliver
![jpps](https://cloud.githubusercontent.com/assets/458619/5578254/3ec02c30-9024-11e4-9e09-139273d60455.png)

**Comment by Jako** [comment]
Close in favour of #11856
