### ISSUE TITLE
Dragging resource into weblink does not generate friendly url code.

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#9466]
pyrographics created Redmine issue ID 9466

The behavior of resource drag/drop into a weblink when furl is turned on should be to put [[~  ]] around the resource id in the Weblink field.  I understand this is different than symlink behavior and it can be worked around by dragging into another field then copy/pasting but for UX sake the furl should be generated.

**Comment by Mark-H** [comment]
Weblinks with just the ID in the content will have its link generated through makeUrl at the time they are requested, with scheme full. core/model/modx/modweblink.class.php
