### ISSUE TITLE
DateTV with input options

### ISSUE THREAD

**Issue by mindeffects** [modxcms/revolution#9473]
mindeffects created Redmine issue ID 9473

Sometimes I only need a date to be stored in a TV without a time – sometimes it's the other way around. Example: When I want to store the release day of a movie I just nedd the date and not the time, but it gets displayed anyway.

I wouldn't ask for that feature if my clients did not complain about this or, to be more precise, where confused and asked my what to enter here or if it was possible to hide the time. I had to say "No." – at least not possible without some "dirty plugin tricks". ;-)

Having the possibility to customize the backend appearence of dateTVs would be awesome, much more elegent and availale for every user – setting the time to a default value, like 00:00:00, or just don't show the time at all. Maybe there could be a date formatter string that controls the _visual_ appearance of dateTV?

A system like MODX should give its users this little interface freedom. Don't you think so, too? PLZ?!

cheers
Oliver

**Comment by Mark-H** [comment]
Added per #12348
