### ISSUE TITLE
TV multiple selection bug

### ISSUE THREAD

**Issue by jonleverrier** [modxcms/revolution#9492]
jonleverrier created Redmine issue ID 9492

When using TVs with multiple selection (Check Box, Listbox with multi-select), although multiple options might be selected, Revo only saves 1 option.

More can be read here:
http://forums.modx.com/thread/82276/tv-checkbox-issue#dis-post-454180

How to re-produce the bug:
# Create a new TV Checkbox
# Put this in the input: Input value: Item==0||Item2==1||Item3==2||Item4==3
# Assign TV to template
# View template, tick all options in the TV and save.
# Return to document, view TV setting and notice only 1 option is set.

The bug is triggered if you use a value of "0". Was working fine on 2.2.4.

After upgrading to 2.2.6, I had to reset TV values for over 30 documents, which were originally set to 0 to 1.

**Comment by joeke** [comment]
I'll look into this #modxbughunt

**Comment by jonleverrier** [comment]
yay - just seen somebody looking into it on the live stream!

https://www.youtube.com/watch?v=bVq0DP1zCi4&t=182s

**Comment by joeke** [comment]
@jonleverrier This should be fixed with PR#13369
