### ISSUE TITLE
Tag type TV could use a rewrite

### ISSUE THREAD

**Issue by chunkyRice** [modxcms/revolution#9493]
chunkyrice created Redmine issue ID 9493

When adding a Tag type TV to a template and using getResources (or getRelated or tagLister's getResourcesTag) it's impossible to search for a distinct search term. That renders it as good as useless in most cases.

Let's say I have a page tagged 'bike,car' and one tagged 'aluminium,carbon' and I'd like to find all pages using the Car tag. If I were to use getResources to search for 'tv==%car%' I would also find 'carbon'. I could therefore limit the search to 'tv==car'. That would not yield any results however, since a Tag TV is apparently treated as a whole sentence, rather than a collection of separate tags. An alternative could be to search for 'tv==car,%||tv==%,car||tv==%,car,%' but that returns an empty result as well. MODX may treat each Tag TV as a whole sentence, but somehow it does filter out the comma's. That basically leaves you out of options (at least, with a Tag TV).

Perhaps this could be solved by adjusting the way getResources handles the search query, but identical problems bug other tag-related snippets like tagLister and getRelated. I therefore suspect it would be simpler and more logical to tackle the problem at the core, being the way MODX handles the Tag type TV.

**Comment by smg6511** [comment]
Closing, as the Tagger Extra does an excellent job in the arena of tag management and rewiring the core Tag TV could be a big task with diminishing returns.
