### ISSUE TITLE
modResource::refreshURIs sortby

### ISSUE THREAD

**Issue by Fi1osof** [modxcms/revolution#9562]
fi1osof created Redmine issue ID 9562

$criteria->sortby('menuindex', 'ASC')  not necessary, but create highload if many resource in table.

**Comment by pixelchutes** [comment]
@opengeek do you know if the `sort` here is required to function correctly?

**Comment by opengeek** [comment]
it is absolutely necessary — the resourceMap and aliasMaps are expected to have the resources sorted by menuindex

**Comment by opengeek** [comment]
In fact, I think this is a non-issue now; IIRC we added an index to speed up the query and reduce load since this was suggested.
