### ISSUE TITLE
Make MODx.config less verbose and/or customizable

### ISSUE THREAD

**Issue by opengeek** [modxcms/revolution#9607]
opengeek created Redmine issue ID 9607

The MODx.config object that is constructed by the system/config.js processor is currently too verbose, exposing database connections, API tokens, credentials and other potentially sensitive information stored in MODX config settings. This should be customizable via a System Event where users and/or Extras could install Plugins that unset certain settings that should not be exposed.

**Comment by pbowyer** [comment]
While MODx.config is still verbose, it doesn't expose database connections etc AFAICT. @opengeek is this valid, as addressed in https://github.com/modxcms/revolution/pull/13180? Otherwise be good to close.

#modxbughunt

**Comment by opengeek** [comment]
I really don't deal with the modExt side of the house much. Would be better for others to provide input on this.

**Comment by OptimusCrime** [comment]
The MODx.config has been trimmed a lot since this issue was first reported. As far as I can see in what is left, there is nothing that should not be exposed there now.

Closing. Feel free to comment or reopen if you disagree.

@modxbot close
