### ISSUE TITLE
Dragging resource into another will not make the parent a container, creating one does!

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#9635]
bertoost created Redmine issue ID 9635

Title says enough I guess?

**Comment by TheBoxer** [comment]
Added system setting for that. More in 5041463e920d815c1274122a6d8c3cc8ea280751

**Comment by sottwell** [comment]
Not sure if this was supposed to help with setting the is_folder setting on drag-and-drop in the Tree, but in 2.5.0-rc1 it still doesn't set the Container checkbox.
