### ISSUE TITLE
Ability to filter / sort TVs that have been assigned to a template

### ISSUE THREAD

**Issue by studiorepublic** [modxcms/revolution#9685]
chris@studiorepublic.com created Redmine issue ID 9685

When working on a site with lots of TVs it's hard to quickly tell which TVs have been assigned. It would be great to have a filter to just show assigned/unassigned TVs, or alternatively be able to sort on the access column

**Comment by whitebyte** [comment]
Right now this can be easily archived with modDevTools extra, so should this really be a part of the core?

**Comment by Jako** [comment]
Sorting by 'assigned' column possible with the PR of @davidpede.
