### ISSUE TITLE
Add "parent" to Duplicate Resource modal window

### ISSUE THREAD

**Issue by jrotering** [modxcms/revolution#9699]
jrotering created Redmine issue ID 9699

I frequently duplicate a resource and then drag it to a different location in the tree. It would be a tremendous enhancement IMO if when the Duplicate window popped up, there was a field where you could enter the ID of the parent resource you want the new duplicate to reside under. A drag feature would be even better, but just being able to enter an ID would be a tremendous feature.

**Comment by alroniks** [comment]
Duplicating resource, in this case, becomes overcomplicated. Duplicating should work fast and simple like ctlr+c->ctrl+v, and after you will be able to fast edit resource using popup editor that already implemented into the system. I am closing it, but please, feel free to reopen if you insist on it.
