### ISSUE TITLE
Hardcoded HTTP/1.1 protocol on nginx return serives pages with wrong header

### ISSUE THREAD

**Issue by ebuster** [modxcms/revolution#9751]
ebuster created Redmine issue ID 9751

When we get Error 404 (for example),  modx always return HTTP status header with HTTP/1.1 protocol (it hardcoded).
But when nginx works with backend in protocol HTTP/1.0, instead of error page from modx we get corrupted unreadable content (i think it not ungziped).
When modx return the same http version header as in request then all works fine. 

Attached patch fix this problem.

**Comment by adamwintle** [comment]
@ebuster do you still have the fix for this? @rtripault Do you know if this bug is still present?

**Comment by ebuster** [comment]
@adamwintle, sorry but not. Сoincidentally, I removed them a few weeks ago. 

As I remember, I'd just replaced all code like this
```
header('HTTP/1.1 503 Service Unavailable');
```
from https://github.com/modxcms/revolution/blob/2.x/index.php#L42
to something like this
```
header($_SERVER['SERVER_PROTOCOL'] . ' 503 Service Unavailable');
```
And that's it.

**Comment by OptimusCrime** [comment]
This should be doable
