### ISSUE TITLE
Wrong TV Form Elements Style when tvs_below_content is enabled

### ISSUE THREAD

**Issue by MokoJumbie** [modxcms/revolution#9833]
MokoJumbie created Redmine issue ID 9833

After upgrading to 2.2.7, many of the tv form elements display incorrectly when the tvs are displayed below the content. In the case of the Image tv, it becomes unusable, because it's impossible to activate the file browser.

A workaround is to disable tvs_below_content. This is less than ideal because clients will have to modify their behaviour temporarily, until this is fixed.

**Comment by EasterPeanut** [comment]
This seems not to be an issue any longer in MODX 2.5.5 #modxbughunt
