### ISSUE TITLE
phpthumb memory limit for cli

### ISSUE THREAD

**Issue by Qwarble** [modxcms/revolution#9867]
Qwarble created Redmine issue ID 9867

File /core/model/phpthumb/phpthumb.class.php
Class constructor sets wrong memory limit for scripts that run through CLI.

Default value for memory_limit in CLI version of php.ini is -1. Property config_max_source_pixels is set to negative and scripts that use property fail.

<pre>
function __construct() {
		$this->DebugTimingMessage('phpThumb() constructor', __FILE__, __LINE__);
		$this->DebugMessage('phpThumb() v'.$this->phpthumb_version, __FILE__, __LINE__);
		$this->config_max_source_pixels = round(max(intval(ini_get('memory_limit')), intval(get_cfg_var('memory_limit'))) * 1048576 * 0.20); // 20% of memory_limit
		$this->iswindows = (bool) (strtoupper(substr(PHP_OS, 0, 3)) == 'WIN');
		$this->config_document_root = (@$_SERVER['DOCUMENT_ROOT'] ? $_SERVER['DOCUMENT_ROOT'] : $this->config_document_root);
		$this->config_cache_prefix = 'phpThumb_cache_'.@$_SERVER['SERVER_NAME'];
		$php_sapi_name = strtolower(function_exists('php_sapi_name') ? php_sapi_name() : '');
		if ($php_sapi_name == 'cli') {
			$this->config_allow_src_above_docroot = true;
		}
}
</pre>

**Comment by adamwintle** [comment]
This looks like it was originally a server configuration issue. 

If you feel this bug is still present can you post some more info and we can reopen the issue.

@modxbot close
