### ISSUE TITLE
Can't Apply Media Source baseURL/basePATH to User Settings

### ISSUE THREAD

**Issue by iamaaron** [modxcms/revolution#9900]
iamaaron created Redmine issue ID 9900

Before you implemented Media Sources, we were allowed to apply a baseURL and basePATH setting to each user, for specific user access. Now, it seems, that if we want that sort of functionality, we need to create an entire Media Source for each user if we want to restrict folders/files for just them.

Thank you!

**Comment by alroniks** [comment]
Seems no more issue. Closing.
