### ISSUE TITLE
AutoTag TV Type Causes Image/File TV Types to become unselectabe

### ISSUE THREAD

**Issue by pyrographics** [modxcms/revolution#9917]
pyrographics created Redmine issue ID 9917

Adding a bunch of tags in AutoTag causes the image/file tv input types to grow wider and wider until the arrows to the right are not selectable anymore.  The growing width should be fixed or the entire image/file input type box made selectable.

**Comment by Ruslan-Aleev** [comment]
In my opinion the bug is not relevant anymore

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue and help make MODX better.

Please reopen if you still encounter this issue.
