### ISSUE TITLE
Searching context settings gives empty results (xPDO query bug?)

### ISSUE THREAD

**Issue by bertoost** [modxcms/revolution#9919]
bertoost created Redmine issue ID 9919

When you search on a context-setting, by key. The query ends up with empty values for the "context_key" and "key" fields. This causes an empty result.

I have done a little research and I think this causes the multi-dimensional array which is provided to the where() method of the query. The array entries are also not set into the query, and the named keys stays empty so somewhere here is a bug..

Btw... Why not using normal getCollection().. I wasn't aware of $modx->call() method which is used here?

**Comment by Flowan** [comment]
Searching works in 2.5.x No issues here. Mark as fixed? #modxbughunt

**Comment by sonicpunk** [comment]
#modxbughunt #1point to @Flowan
