### ISSUE TITLE
Selecting media sources when creating a TV

### ISSUE THREAD

**Issue by pauloneill79** [modxcms/revolution#9923]
pauloneill79 created Redmine issue ID 9923

I've setup my media sources and next step is to tell me TV's (that look for to input values) to direct the users to my chosen media sources. I navigate to media sources tab. Double-click on the source from the table below, it highlights... when I click again to select my media source the menu collapses straight away.

This happend every time on every TV i go to assign a media source to.

Image attached

**Comment by alroniks** [comment]
It seems it works as expected. I've attached animation.
![mediasources](https://user-images.githubusercontent.com/303498/43081433-9e3e29a0-8e9a-11e8-9858-01cdba30a36f.gif)

If I wrong, please, reopen the ticket.
