### ISSUE TITLE
Media Source Access Permissions fails when updating

### ISSUE THREAD

**Issue by ReSpawN** [modxcms/revolution#9954]
ReSpawN created Redmine issue ID 9954

After assigning a User Group/Minimum Role/Policy combination to a Media Source, right clicking and updating it, I'm getting the entire Policy list in the ComboBox, which additionally doesn't update. The Media Source Access Permissions need removal before assigning it again with the new role (for example, switching Media Source Admin to Media Source User).

**Comment by ilyautkin** [comment]
Commit https://github.com/modxcms/revolution/commit/41a3711f676a2d82b2b18891d3f8b00668987126 fixed this bug. In 2.5.x the bug is not reproduced.
