### ISSUE TITLE
File browser/manager - delete file issue

### ISSUE THREAD

**Issue by paramaniac** [modxcms/revolution#9962]
paramaniac created Redmine issue ID 9962

Using the file manager from a file/image TV or from TinyMCE, when you right-click on an uploaded file and delete it. The file seems to remain after confirming deletion. It's not until I manually hit the refresh icon and click on different folders in the file manager tree multiple times, that the file eventually disappears.

This issue doesn't happen using the file manager under the "files" tab above the main site tree because the file/folder tree refreshes after deleting a file.

Obviously for clients this can be really confusing when they are trying to delete files.

**Comment by adamwintle** [comment]
@whitebyte yes confirmed this has been fixed @modxbot close
