### ISSUE TITLE
cacheManager Refresh with no parameters returns false

### ISSUE THREAD

**Issue by jasonabird** [modxcms/revolution#9972]
jasonabird created Redmine issue ID 9972

When using API to clear cache with $modx->cacheManager->refresh() it seems to clear the cache but returns a false boolean value. When passing a specific area to clear it returns true - $modx->cacheManager->refresh(array('system_settings'));

**Comment by Mark-H** [comment]
It returns false if there's an issue in refreshing one of the partitions. Maybe you had a partition 3 years ago that would fail to refresh (perhaps, because it was empty).
