### ISSUE TITLE
Custom system settings not counting correctly

### ISSUE THREAD

**Issue by iamram** [modxcms/revolution#9997]
iamram created Redmine issue ID 9997

Manually-added system settings not counting/displaying correctly.

I notice that at a seemingly random number the listing of settings within a custom namespace stops displaying, for instance in one case:

• View at default – 30/page, display shows 1–25 of 28.
• Results are there, display number just has to be increased.
• Display 31 per page shows 1–26, display 32 shows 1–27 etc.

More info at:
http://forums.modx.com/thread/85174/custom-system-settings-namespace-list-not-showing-all-items

**Comment by Alroniks** [comment]
The issued very old (3+ years) and seems that now it works fine (checked on some my real websites). I've never got such error last years and also I work a lot with custom system settings during developing my CMPs. So, lets close.
#modxbughunt

**Comment by rtripault** [comment]
So closing...

Feel free to comment/reopen if needed.
Thanks
